### ISSUE TITLE
[Reddit Suggestion] Botania Flower Snow Support

### ISSUE THREAD

**Issue by ProRedHD** [Vazkii/Botania#1000]
Could you add a feature if flowers are next to snow layers, that a snow layer appears in the same blocka space as the flower. I think the picture explains it pretty well.
Picture: http://i.imgur.com/2pdnzKG.png
Reddit Post: http://www.reddit.com/r/feedthebeast/comments/36qtwe/my_little_wish_request_is_that_botania_flowers/

**Comment by MrKunji** [comment]
This isn't even a vanilla thing, and Optifine is kinda unsorported by modders.

**Comment by Entoarox** [comment]
@MrKunji That doesnt change the fact that this would be a pretty awesome thing to have.

This has my vote, It would make the world look just that bit more realistic without any negative side-effects!

**Comment by MrKunji** [comment]
So either ask the Optifine devs if they can make this effect on Botania flowers, or wait until Vazkii comes back.

**Comment by Entoarox** [comment]
@MrKunji Why would anyone need to wait untill vazkii returns to post a suggestion, I'm fairly certain that vazkii will be spending quite a bit of time reading up on them anyway once she has the time for it.

**Comment by MrKunji** [comment]
Vazkii is out because it's exam season, there will be a long time untik we get any update.
