### ISSUE TITLE
Dupe bug

### ISSUE THREAD

**Issue by Gamer00769** [Vazkii/Botania#1004]
Bug: Dupe Bug
Pack: Skyfactory 2 (V. 2.4)
Mod Version: Botania r1.6.176 & RFTools 2.80
Optifine: No
Forge: forge-1.7.10-10.13.3.1395-1710ls-universal
Explanation: When you place a filled Black Hole Talisman into the Crafter Tier 3 from RFtools. (I have not experimented with other tiers sorry about that). When the crafter takes out blocks from the Talisman, its successful but it doesn't lower the amount of blocks that was taken from it.

Not sure if this is botania or RETools causing the dupe but I will be reporting to the creator of RFtools as well. Im sorry if it's not on your end.

**Comment by MrKunji** [comment]
If you can't reproduce with Botania v190, it is not valid.

**Comment by Gamer00769** [comment]
alright will test now

**Comment by Gamer00769** [comment]
Ahh it seems to have been fixed. Although it doesnt craft at all anymore but im not sure if that is intended.
