### ISSUE TITLE
Crash with warp lens?

### ISSUE THREAD

**Issue by dman11235** [Vazkii/Botania#1006]
http://pastebin.com/9UHcPjq4

I must admit I'm not good at doing a computer, so I hope this can be dealt with?  Using Storybook modpack on the AT Launcher, so lots of mods in there, but I'm not the admin and the admin won't send this (also decided to just nuke my house to prevent further crashes and then let all the items despawn, so yeah...), so here I am.  Crash report doesn't mention any other mods though, and total interactions of the apparent crash is just Botania.

I was setting up a pure-Botania method of automating livingwood/rock.  Set up a series of 4 redstone spreaders with Potency lenses, and a lense modifier with Bore and Warp.  Force Relays set to redirect the blast twice total so that the full 3x3 around the pure daisy is affected by the blast.  I used a lever and redstone crystals from Automagy to activate all four readstone mana spreaders at once as a test (with no livingwood/rock in place), and the server crashed, seemed to be about a half second after the blasts were sent.  It looked like the crash happened as the blasts reached the relays.

**Comment by TheMadmanofChaos** [comment]
Witching gadgets is causing this issue due to a slightly outdated API. Update it, should fix this.
