### ISSUE TITLE
Crashing when right-clicking on Ender IO Basic Capacitor while wearing Botania baubles.

### ISSUE THREAD

**Issue by Haggle1996** [Vazkii/Botania#1007]
http://pastebin.com/0NaQxv7u

While wearing any Botania baubles, right clicking on an Ender IO Basic Capacitor causes the client to crash with the above error. Removing all baubles results in no crash when clicking.

This does not happen to all players on our server -- some work fine regardless of what they're wearing. Only difference we can spot is Java 7 vs Java 8.

Latest Baubles and Botania (1.6-190). Using FastCraft, No OptiFine.

**Comment by MrKunji** [comment]
Roll EnderIO to a stable version (381) and see if it still happens.

**Comment by Haggle1996** [comment]
We've had this problem with Ender IO 378, 381, and 382.

**Comment by Lazersmoke** [comment]
My random guess of the day is that FastCraft strips the worldObj from the player for fastness reasons, causing player.worldObj.isRemote to NP. Why "onEquipped" would be run when right-clicking a capacitor bank is beyond me.¯\_(ツ)_/¯

**Comment by TheWhiteWolves** [comment]
@Haggle1996 have you replicated this with only Botania and EnderIO?

**Comment by Vazkii** [comment]
What the actual fuck.
