### ISSUE TITLE
Ring of Far Reach doesn't work when starting a world if it was equipped already

### ISSUE THREAD

**Issue by Titanium237458** [Vazkii/Botania#1009]
Same issue happened with the Soujouner's Sash before. If you start a world and you already have the Ring of Far Reach equipped, it won't work. To get it working again, you have to re-equip it.

First noticed in 189, then updated to 190 and the issue still exists.

Also, even if it doesn't have anything to do with the mod itself, I thought it was worth noting that the link to the Botania FAQ on the guidelines for contributing page still links to your old website.

**Comment by Vazkii** [comment]
I'm not fixing this one, every time I "fix" the ring it breaks more. The thing's a massive hack to begin with.
