### ISSUE TITLE
Gaia guardian battle does not prevent simply jetpacks flight from working

### ISSUE THREAD

**Issue by Entoarox** [Vazkii/Botania#1010]
As the title says, I just got out of a gaia battle where I used that to fly, made the whole thing about twice as easy, dont think that is the intended goal here.

This also means kt might also fail to block other forms of flight that are not actually creative-style flight.

**Comment by MrKunji** [comment]
This happens because the way jetpacks works, see past issues.

**Comment by Entoarox** [comment]
@MrKunji Still, if its impossible to stop non-creative flight, its better the gaia guardian fight is modified so that flight doesnt matter either way, instead of blocking only creative-style flight and allowing a rather large advantage when using alternative modes of flight
(The Tier 2 battle for example is equally difficult for me both with & without jetpack flight, not so for the Tier 1 battle)

**Comment by Skyshayde** [comment]
After a bit of thought, I think the best way to solve this is to add something to the NBT.  A boolean called isPlayerFightingGuardian or something.  The name doesn't really matter.  Set this to true for all the players in range along with the flight check and set it to false on death.  Then any mod can easily check for this value without having to actually enable the entire api. It'd take like 5 lines of code to disable the flight if it's true.  It would still have to be implemented on each mod, but it would be practically effortless.  I'll see if I can get it to work and submit a pull request.
