### ISSUE TITLE
Orechid Ignem spawning BoP Malachite Ore instead of TiC Ardite Ore

### ISSUE THREAD

**Issue by khardix** [Vazkii/Botania#1011]
In my instance, the ores spawning in Nether should be Quartz (Vanilla), Cobalt and Ardite (Tinker's Construct). Aside from TiC, the mods in use that influence the generation of Nether are Natura and Biomes O'Plenty.

The Orechid Ignem generates mostly Quartz Ore, with the occasional Cobalt and the BoP Malachite ore (which has stone as base texture, so I guess it is not an ore that should spawn in the Nether). However, no Ardite was spawned (I dig pretty much all Netherrack around the Orechid and found none). So I guess that the Orechid generates Malachite instead of Ardite. ![2015-05-23_15 17 30](https://cloud.githubusercontent.com/assets/2243379/7784247/4e609024-015f-11e5-9a71-884d70853b48.png)

I have no clue in which mod this bug occur, but since the natural generation of Nether seems fine, I suspect Botania.

If you need anything else form me, I will be glad to provide it. I'm also willing to help with testing, if instructed how :)

**Comment by Entoarox** [comment]
Botania uses the ore dictionary keys to generate the ores, netherOres has a malachite entry, so the BoP one is being generated due to sharing the dictionary key.

Ardite has the same spawn rarity as Cobalt, so it should spawn properly as long as a dictionary entry for `oreArdite` exists

**Comment by khardix** [comment]
Well, for four mana tablets worth amount of mana, I've got about five ores of Cobalt, similar amount of malachite and lots of Nether Quartz, yet no Ardite. Of course, I just might be unlucky.

Is there a way to check the values of Ore dictionary entries (netherOres, etc.) during play?

**Comment by Entoarox** [comment]
NEI integration comes with a ore dictionary tooltip/nei lookup, but both are disabled by default
