### ISSUE TITLE
The Terra Shatterer should be able to place torches

### ISSUE THREAD

**Issue by UntouchedWagons** [Vazkii/Botania#1018]
The Manasteel Pickaxe is able to place vanilla torches but not the Terra Shatterer which I feel is a bit of a downgrade. The Shatterer should be able to place vanilla torches (support for TiCon's stone torches would be awesome too) via right-clicking with the ability activation be relegated to shift right clicking.

**Comment by MrKunji** [comment]
The Terra Shatterer does place torchs, via shift-RC, do you want the controls to be inverted?

**Comment by UntouchedWagons** [comment]
Shift right clicking activates the Shatterer's ability for me.

**Comment by MrKunji** [comment]
See at version 186
http://botaniamod.net/changelog.php

**Comment by UntouchedWagons** [comment]
TPPI2 has version 170. (╯°□°）╯︵ ┻━┻ Oh well.

**Comment by UntouchedWagons** [comment]
I just upgraded to version 190, shift right clicking the shatterer does not place torches. It only activates or deactivates it.

**Comment by MrKunji** [comment]
Ok, so I will try to reproduce.

**Comment by Lazersmoke** [comment]
I can't reproduce using my custom build straight from Github, so this issue has been fixed in at least the latest github source code. Maybe check your keybindings?

**Comment by UntouchedWagons** [comment]
I couldn't find any options for Botania keybinds.

**Comment by MrKunji** [comment]
Because Botania doesn't have keybinds

**Comment by UntouchedWagons** [comment]
No wonder I couldn't find them.

**Comment by TheWhiteWolves** [comment]
@UntouchedWagons is this happening for you with only Botania installed?

**Comment by Barhandar** [comment]
I'm on 189 and TS places torches just fine. Are you sure you HAVE torches in inventory?

**Comment by Vazkii** [comment]
Can't reproduce.
