### ISSUE TITLE
Sparks glitch through blocks

### ISSUE THREAD

**Issue by UntouchedWagons** [Vazkii/Botania#1019]
I checked the changelog to make sure this issue hadn't already been fixed since TPPI2 has an old version of Botania (version 170). http://imgur.com/a/sqF4R

The sparks were placed on top of the pools (obviously) but underneath the glass. About every 20 seconds the sparks will pop up through the glass in a clockwise fashion then return to their original position. WAILA reports that they're there and I can interact with them using the Wand of the Forest.

Maybe revision 186 fixes this issue.

**Comment by MrKunji** [comment]
You still need to try to reproduce on v190.

**Comment by Entoarox** [comment]
I have 190 and can report that this does happen still.

**Comment by UntouchedWagons** [comment]
I made a custom instance with 190 and it doesn't happen. But if it happens to Entoarox, then that's good enough for me.

**Comment by Entoarox** [comment]
@UntouchedWagons It only happens to me with sparks directly below a block and adjacent to multiple other sparks.

**Comment by UntouchedWagons** [comment]
I removed all the pools and their sparks except for the corner ones, the sparks still glitch up through the glass.

**Comment by Vazkii** [comment]
This is a vanilla bug.
