### ISSUE TITLE
Itemcounduit doesn't connect to a Red string container

### ISSUE THREAD

**Issue by Bellwar** [Vazkii/Botania#1022]
I have problem with interacting Ender IO itemconduits with Redstring container. It doesnt appear everytime it is mostly after loading the world and comming back. After while moving around the conduit it just connect and work fine but need to go next to the conduit and wait for each to do it.

Im running DW20 pack on 1.3.1 with botania updated to build 190 and Ender IO is on version 2.2.8.367. It can be bug on Ender IO side but not sure.

PS: I have this area chunkloaded.

**Comment by TheWhiteWolves** [comment]
Have you been able to reproduce this with just Botania and EnderIO installed?

**Comment by Vazkii** [comment]
Break the conduit and place it again. They might not detect the change in the inventory.
