### ISSUE TITLE
Daybloom bug

### ISSUE THREAD

**Issue by Cbert** [Vazkii/Botania#1024]
FTB Infinity 1.7 pack.
Can’t craft Daybloom. Look @ screenshot.
After throwing seeds nothing happens.
![2015-05-26_14 18 00](https://cloud.githubusercontent.com/assets/9320867/7811692/01a5b0a4-03b5-11e5-97ba-c3cd17c6c785.png)

**Comment by akvgergo** [comment]
Botania version? Does it happen with the latest build?

**Comment by Cbert** [comment]
Botania r1.6-190.jar

**Comment by MrKunji** [comment]
Are you sure that you are using the correct petals? Double check it, because that one looks a blue, not a light blue.

**Comment by Entoarox** [comment]
Does the recipe show up in NEI? Because if it does, you must have made a mistake, since the NEI recipes are retrieved directly from the recipe list, if NEI shows a recipe, it exists. (Unless you have a server/client desync, but then you'd have bigger issues then just issues crafting a flower!)

**Comment by Cbert** [comment]
I’ve made a mistake, used cyan petal, sorry.

**Comment by Lazersmoke** [comment]
@Cbert please close your issue if you can now craft the flower. Thank you!

**Comment by Edix97** [comment]
in my regrowt the passive flower, (daybloom and nightshade ) vanish who is the problem

**Comment by yrsegal** [comment]
Works as intended.

**Comment by Edix97** [comment]
what ? is correct that flower vanish ?

**Comment by AEnterprise** [comment]
read your lexicon: the flowers whither away after a while, they are not infinite

also you are necro posting on an old thread that has nothing to do with your issue

**Comment by Edix97** [comment]
thanks for the information
