### ISSUE TITLE
Crash on worldload

### ISSUE THREAD

**Issue by tkdberger** [Vazkii/Botania#1032]
Have a log, because I'm so nice: http://pastebin.com/HMy4bReJ  
All I did was log in. Looking at the log, it may have something to do with an Arcane Bore in my world, with a Red Stringed Container as its output, but I'm not sure. This has never happened before version r1.6-190.
Small note: this crash is making it impossible to load the world.

**Comment by Vazkii** [comment]
This looks like world corruption, since you have a Tile Entity in a place where you shouldn't. Your own option is to downgrade botania and remove everything around the bore for now.

**Comment by tkdberger** [comment]
Thank you very much. *bows and leaves*

On 5/30/15, Lizbeth Rika <notifications@github.com> wrote:
> This looks like world corruption, since you have a Tile Entity in a place
> where you shouldn't. Your own option is to downgrade botania and remove
> everything around the bore for now.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/Vazkii/Botania/issues/1032#issuecomment-107048562


-- 
 Sincerely,
Caleb
