### ISSUE TITLE
[Suggestion] Wand of the Forest on bind mode can redirect Skulls/Heads

### ISSUE THREAD

**Issue by SeirVed** [Vazkii/Botania#1034]
Pretty self explanatory, affects vanilla block, craft-able by Botania.
Gotta get all the dead Soaryn heads to look at same thing.

**Comment by MrKunji** [comment]
Do they simply spin, or their eyes points to an object?

**Comment by Entoarox** [comment]
I think he wants the ability to freely rotate heads the way you can mana spreaders, but that would require a whole new block for functionality barely anyone is going to use.....
