### ISSUE TITLE
Duplication Bug

### ISSUE THREAD

**Issue by kenthalas** [Vazkii/Botania#1038]
If you take a stack (or less) of flowers out of the botania flower pouch, and then place that stack directly into your hotbar in the same slot as occupied by the flower pouch, it will throw the pouch on the ground and close its interface; however, you will have the flowers in your hotbar as well as in your pouch still, it's like it doesn't update the missing items from the pouch or something when it gets force closed by being thrown down in this method. The two sets of flowers are both fully functional, persist through logout, can both be placed on the ground or turned into petals or whatever, and had no visible difference in item ID that I could see, including NBT data. However, they would NOT stack together, no matter how many where in either stack, unless first placed in the world and picked up again, then both were stackable. Of course, petals crafted from either set could be stacked as normally. EDIT: also this is for Botania 184th edition, as part of the unmodified Direwolf20 modpack with no other custom configs or anything else outside of what that pack normally uses, and on a SMP for which I am an Op.

**Comment by TheWhiteWolves** [comment]
Reproduce this with the latest version with only botania installed
