### ISSUE TITLE
Black Hole Talisman + Resolute Ivy = not that balanced mechanic

### ISSUE THREAD

**Issue by Nedok** [Vazkii/Botania#1049]
In short:
"Resolute Ivy" + "Black Hole Talisman with X amount" = "Black Hole Talisman with X amount and Resolute Ivy" + "Black Hole Talisman with X - 64 amount"

More in dept:
Trying to put "Resolute Ivy" on an active "Black Hole Talisman" fild with 320 Cobblestone using inventory's crafting grid.
Result was one active "Black hole talisman" contaning 320 cobblestone with "Resolute Ivy" (The output of the crafting) and one inactive "Black Hole Talisman" with 256 cobbelstone.

My notes:
It seams to be a problem related to the feture that makes it posible to extrakt materials from the talisman as 64 items is removd for eatch dubblication.

Hers the FML Log:
https://drive.google.com/file/d/0B8z7J9fi11uRMHZJS1ZLcjcxbFE/view?usp=sharing
(To big for pastbin)

General info:
Minecraft 1.7.10
Forge v10.13.3.1388
Java 1.8.0_45 (64)

Instald mods:
Baubles 1.0.1.10
Botania R1.6 191
Code Ciken Core 1.0.6.43
NEI 1.0.4.106

(And no Optifine.)

**Comment by OJwithC** [comment]
This dupe bug exists in v208. (You get an talisman with the original number of items with resolute ivy on it, and an inactive talisman with the items minus a stack without ivy on it is left in the crafting grid.)

**Comment by OJwithC** [comment]
Also, when the ivy is crafted with a bauble that has cosmetic override, you get another of the cosmetic bauble.
Same for the mana blaster with a lens. You get another copy of the lens on the blaster.
