### ISSUE TITLE
Inventory Dupe

### ISSUE THREAD

**Issue by alfw** [Vazkii/Botania#1050]
Dupe of inventory.

We come over this dupe on a server while fighting the Gaia 1 boss. The player that did the fight had problems and right before he died he logged out, right after that he died ingame whiout be on the server and the inventory dropped. Then he logged back in and died by the wither effect and died once more. Both death dropped he's inventory.

It look like it only happen when you get hit and killed right when you press disconnect. And when the player press connect agan, player saved as dead, and then if you got the wither effect on you. It kills you and drop the inventory secound time.

I tried to reproduse this but you need to be realy presice and time it right.

Here is the chat messages when this happened: 
https://files.alfw.tv/1433343843-Alf-850.png

We are playing the As2 modpack by jaded cat.
AS2 - 1.1.5
Botania - #191
Forge - 1401

**Comment by TheWhiteWolves** [comment]
Most likely not going to be able to do anything about that, would be a nightmare to reproduce and so unlikely to happen most of the time that it's not worth it.
