### ISSUE TITLE
Ring of Loki issue

### ISSUE THREAD

**Issue by TheMadmanofChaos** [Vazkii/Botania#1054]
Botania: 191
Forge: 1355

Issue: It seems in recent version of botania the Ring of Loki has lost it's ability to place blocks. The normal method of use was done to no effect what so ever. 

To make sure I did nothing wrong, I followed these steps: Equipped Ring of Loki, Shift clicked a block with nothing in hand, shift clicked three others, shift clicked the starting block, placed a block while ensuring I had more then a stack available in my inventory.

**Comment by MrKunji** [comment]
Omnipresence block placing was reduced to shift+right click because of problems involving containers, IIRC

**Comment by TheMadmanofChaos** [comment]
Ah, my apologies. I missed any mention of this change, and this does seem to be the case. Closing issue,
