### ISSUE TITLE
Rod of the plentiful mantle does not detect Underground Biomes Constructs ores

### ISSUE THREAD

**Issue by talonos2** [Vazkii/Botania#1059]
This means that in a world with Underground Biomes Constructs, the Rod of the Pleltiful Mantle is useless.

Tested in Botania 191.

**Comment by talonos2** [comment]
Edit: It seems as though some ores are detected. Any ore with a metadata of one (that is, any ores found in Gneiss, Red Granite, or Limestone will be picked up as normal.

**Comment by talonos2** [comment]
Is this closed as "Will not fix"?

**Comment by Vazkii** [comment]
Yes.

**Comment by talonos2** [comment]
If anybody else runs into this issue, the beta UBC version "test-41" fixes this issue from the UBC side.
