### ISSUE TITLE
Terra Blade behaving weirdly

### ISSUE THREAD

**Issue by CatDany** [Vazkii/Botania#1060]
A burst is fired whenever item is swinged, which means that it'll be fired on any swing. That's really annoying when opening inventories and stuff. Feels like I'm wasting tiny bit of Mana. Still, isn't there any other way besides checking for swings? I'm pretty sure, there's left click method for items.

https://github.com/Vazkii/Botania/blob/c961ca976a7583557b59ffc0705d9e54ca09c31f/src/main/java/vazkii/botania/common/item/equipment/tool/terrasteel/ItemTerraSword.java#L58

**Comment by Lazersmoke** [comment]
https://github.com/Vazkii/Botania/issues/837
"Not worth fixing" - Vazkii

**Comment by CatDany** [comment]
High quality graphics. All details are polished.
Stupid derp is not worth fixing.

**Comment by Lazersmoke** [comment]
¯\_(ツ)_/¯

**Comment by CatDany** [comment]
No, it's still annoying >_<
