### ISSUE TITLE
Flask Effects Lasting Forever

### ISSUE THREAD

**Issue by Jaffamatt** [Vazkii/Botania#1067]
While wearing full Blood Magic Bound Armor with sigils, all flask effects last indefinitely until you log or change dimensions.

I tried it with certain pieces and combinations but it only worked with full.

Poition counts down to 00:00 and stays like that just like the BM sigil efffects.

**Comment by MrKunji** [comment]
The actual effects from the potions still active, or the counter is just stuck at 00:00 with no effect?
Also, provide more information.

**Comment by Jaffamatt** [comment]
It was hitting 00:00 and the effect staying active. But today i tried it again and its work properly. Must have just been freak happening. Guess you can close this.
