### ISSUE TITLE
[Suggestion]Way to retrieve a relic if it gets destroyed

### ISSUE THREAD

**Issue by Jacencaedus** [Vazkii/Botania#1068]
It fells a bit silly to have items so hard to get, so easy to lose, I know the relics are soulbound, but that is not a perfect system.An example I just came across is that a player on my server went through a Twilight Forest portal and a glitch caused him to fall through the world and lose all items, including the soulbound stuff.
I'd suggest some item that would retrieve any such lost relics

**Comment by MyDeloreanWontStart** [comment]
Itd make sense for them to be "soulbound" to the player, so that they don't lose them on death.
