### ISSUE TITLE
Suggestion: New Explosives

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [Vazkii/Botania#1080]
Almost every techmod, magicmod, whathaveyoumod add new items, blocks, tools, etc. but strangely almost none of them add any new explosives to the game.

I kinda want to have more choices besides TNT. Bigger, smaller, better, different, anything, really :).

New kaboom is gud!

**Comment by OJwithC** [comment]
Never played with it, but I believe the entropic lens makes an explosion.

**Comment by TheWhiteWolves** [comment]
@OJwithC You are correct the Entropic lens does the following:

"The Entropic Lens imbues the Mana Burst with entropy, causing it to release its energy in the form of an explosion when it collides against something that can't receive Mana."
