### ISSUE TITLE
Gaia Mana Spreader stops sending mana

### ISSUE THREAD

**Issue by Xiaminou** [Vazkii/Botania#1081]
![2015-06-10_17 44 00](https://cloud.githubusercontent.com/assets/8670392/8087037/e6dbcb24-0f98-11e5-9b5a-38c5883eac8d.png)
This setup uses 5 Kekimurus and a Gaia Mana Spreader to generate mana. It works flawlessly 90% of the time, however, sometimes I find that the mana spreader stopped sending mana to the mana pool and will not until I re-bind it, even thought it shows it is already aiming at the mana pool.
The chunk is always loaded, from server start, to server stop, and it does not occur on server start.

Forge: 1403
Botania: 192

**Comment by TheWhiteWolves** [comment]
When the spreader stops sending mana, is it still showing as bound to the pool?, also can u reproduce it with just botania on its own

**Comment by Xiaminou** [comment]
Yes it is still showing as bound to the pool, as far as reproducing it with only botania that would mean I have to come up with a way to automate cake placement with only botania and then run a server long enough to hopefully (or the opposite) get it to happen or to babysit the whole thing placing cakes for god knows how long. Sorry but that's too much work for me.

**Comment by TheWhiteWolves** [comment]
prob not gona be looked into at the moment then, its most likely a similar issue to the flowers unbinding.

And for the automating it with botania, you can probably set something up using the Rannuncarpus to place the cakes and feed it with a dropper and hourglass or similar.
