### ISSUE TITLE
texture issue

### ISSUE THREAD

**Issue by LukasXD01** [Vazkii/Botania#1082]
if you have a mana pool on top of a force relay and have a spark on the pool you can see the texture of the force relay through the spark

**Comment by TheWhiteWolves** [comment]
Minor graphical issue, probably to do with render layer ordering.

**Comment by Lazersmoke** [comment]
@LukasXD01 Please search previous issues, as your issue has already been reported https://github.com/Vazkii/Botania/issues/822
