### ISSUE TITLE
Greater Band of Mana not reporting mana correctly after rapidly spending via Rod of the Terra Firma

### ISSUE THREAD

**Issue by Nickoladze** [Vazkii/Botania#1083]
1. Fill Greater Band of Mana with Mana
2. Use Rod of the Terra Firma until mana is gone
3. Greater Band of Mana is now empty, but the blue bar over the XP bar is not empty.

http://i.imgur.com/HlqxB4L.png

You can see my ring is empty, but the mana bar over my XP is not.

Removing the ring and re-placing it fixes it.

**Comment by dragoniil1** [comment]
When mana band or grater mana band is in the bauble slot it dosent show up corectly on the exp bar

**Comment by Nickoladze** [comment]
It seems to work fine when I spend mana slowly, such as when flying with the tiara.

**Comment by SneakyDevil** [comment]
as dragoniil1 said, if the ring is not in your actual inventory, then the mana bar does not update correctly.
