### ISSUE TITLE
Bauble Bug

### ISSUE THREAD

**Issue by dragoniil1** [Vazkii/Botania#1085]
If i join a server without botania installed (lobby) in my case then join the main server with botania installed something wierd happends with baubles. Any bauble that i equip on the moded server dosent render and is not functional then if i make a single player world and i equip for example sash and flugel tiara then i go back on the server or any server the effects from this items remain and i can use them without any mana or even without botania at all installed on the server. All of the rings doesnt work and the flugel tiara dosent make you invulnerable to fall damage so if u fly up then slowly come back down you will take fall damage...this is so weird i like finding bugs :) found couple more but not sure how to reproduce them, updates later

**Comment by MrKunji** [comment]
You didn't specified wich version of Botania the server is running, also it could be just a weird server lag.

**Comment by dragoniil1** [comment]
lag? ok let's exclude moded servers...but since when lag allows you to fly and have super speed in vanilla servers?

**Comment by MrKunji** [comment]
It doesn't hurt trying to reproduce in the latest version, things are only be fixed if they still are happening. But now, how even the baubles' effects get transfered to the servers?

**Comment by dragoniil1** [comment]
Why do you ask me? You know what im done talking to you...you seem to say only that im not saying the truth tou seem to know everything if i say im sure is worging in 192 it is becouse thats the way the baubles are coded like most of the cheats in vanilla so test for yourself in the latest version...im done here

**Comment by MrKunji** [comment]
Forget the question mark, it was not meant to be answered :p.
But you do need to test, otherwise the devs are going to close due 'inconsistency', it's stated in the https://github.com/Vazkii/Botania/blob/master/contributing.md , and I do not play on servers, so I can't confirm.

**Comment by dragoniil1** [comment]
I dont care any more im done reporting bugs...and you can auto kill gaia guardian with just botania and vanilla minecraft but im not sure how to reproduce so ye...im not going to annoy anyone about my set-up Like you said is too old the version that im playing on
