### ISSUE TITLE
Rannucarpus places blocks in midair if block beneath dirt it's planted on is open air.

### ISSUE THREAD

**Issue by Iapyx** [Vazkii/Botania#1087]
Title explains it. Not sure if bug or feature. The Lexica Botania would suggest that you need an actual block underneath the dirt underneath the Rannucarpus, but the activity is logical if you assume "open air" is a valid block. It does make for some very pretty results if you toss a stack or two of blocks down, though, so maybe just a line in the Lexica to clarify?

**Comment by Lazersmoke** [comment]
I like the behavior, even if it isn't intended

**Comment by TheWhiteWolves** [comment]
The Rannuncarpus doesn't specifically filter out air blocks so it is classed as a valid block to place things.
