### ISSUE TITLE
Right-click on BigReactors Reactor Controller with Mana Tablet causes client disconnect.

### ISSUE THREAD

**Issue by talonos2** [Vazkii/Botania#1088]
I am able to reliably have myself booted from a server when I right-click the controller block of a BigReactors multiblock structure with a mana tablet.

Tested with BigReactors BigReactors-0.4.1A2 and Botania 191.

There are no crashlogs, because neither the client nor the server crashes. However, I generate the following stacktrace in the server's log file every time I cause the bug to occur: http://pastebin.com/raw.php?i=4bW0YzDC

If you need any additional info, feel free to ask. I'll also cross-post this to the BigReactors issue tracker: I will reply momentarily to this post with a link to the issue on their side.

Thanks!

**Comment by talonos2** [comment]
Oh hey, it does it automatically. Didn't know that. Well, there's the issue on their side.

**Comment by Vazkii** [comment]
The tablet doesn't have any action on right click, nor does it send any packets, so I can only assume it's on their end.
