### ISSUE TITLE
Wand can't bind force relay

### ISSUE THREAD

**Issue by Watchful1** [Vazkii/Botania#1089]
I am unable to bind a force relay to a block.

Placed a force relay in fresh world, right clicked with wand in bind mode, right clicked block. The wand did not animate with the clicking action and the relay doesn't seem to be bound.

Tested with both 190 and 192.

**Comment by VolterPL** [comment]
Are you doing Shift + RMB or just RMB?

**Comment by Watchful1** [comment]
Shift right click breaks and drops the block. I'm just doing a normal right click as specified in the lexica.

**Comment by TheWhiteWolves** [comment]
just to let you know, it is binding, it just never gave an indication of it so I've made it play a sound so you know it bound.
