### ISSUE TITLE
Tessellating Issue

### ISSUE THREAD

**Issue by whitestarx0312** [Vazkii/Botania#1090]
Getting this crash randomly when doing things in my base. I can't really be any more specific than that. One time I was working with bees, one time I was searching in my AE system.

http://pastebin.com/QbPHHF0L
Botania: Botania r1.6-192 (Latest)
Forge: 1.7.10-Forge10.13.4.1448-1.7.10 (Rec/Latest)

I am using Fastcraft and Optifine and I realize that this might be them. If it is, just say the word and close the issue and I will attempt to report it to them.

**Comment by XFactHD** [comment]
Your problem is optifine. Every tile entity can crash with this. Reporting this to the optifine dev is senseless.
