### ISSUE TITLE
What happens when Relics go poof?

### ISSUE THREAD

**Issue by ConVict19** [Vazkii/Botania#1092]
I had a look around the Internet and couldn't find an answer, so I thought this would be a good place. 

Image the senecio. You're playing on a public server. You get relic A and put it in a chest for safekeeping. The server crashes very shortly afterwards. You log back in and the server rolled back to before you got relic A and your player file is the same as when it crashed. What happens next? Is it a case of one and ONLY one per player or is it only one per player at any instance in time? Also, if the relic is dropped in lava etc by mistake, does that mean it's gone forever as well or do you just need to roll more dice?

**Comment by TheWhiteWolves** [comment]
You only ever get the one, that's why it needs to be protected.

For the instance with the server you would have to either get one from creative or have the player data deleted or rolled back and roll for it again.

**Comment by ConVict19** [comment]
Thanks for replying, clears up a little confusion I had.
