### ISSUE TITLE
Ring of Aesir/Loki not placing blocks

### ISSUE THREAD

**Issue by Singleton06** [Vazkii/Botania#1094]
The ring of Loki appears to not be placing blocks correctly. I found this in the Direwolf20 1.4.1 mod pack.  If this is the incorrect location to post this, then please let me know.  If you happen to have the right place, I'd be more than happy to log this elsewhere.

The odd part about this bug is that it only seems to be an issue for block placement.  I can do multiple selection and then use the terrashatterer (not activated) and it will break all of the expected blocks (in the pattern in which I have selected through the ring of loki/aesir).

The ring quit working somewhere between versions 1.3.1 and 1.4.1, which for Botania would be between r1.6-184 and r1.6-190.

This image shows what I am talking about.  You can see my selection as the first "row" of 4 blocks (with the wireframe), the right right block is my origin.  Then the block west (further away from me) is when I use the terrashatterer.  Then I tried to place dirt 1 block west, and only the original block was placed (no additional ones).  The same thing happened for stone.
![2015-06-16_01 08 19](https://cloud.githubusercontent.com/assets/2235110/8176869/487e98aa-13c4-11e5-867e-1948aa8e614f.png)

Mod Version: r1.6-190
Java Version: 1.8.0_40
OS: Windows 8.1 Pro 64 bit

If you need any additional information, or would like me to do some other kind of testing, please let me know.  Thanks!

**Comment by TheMadmanofChaos** [comment]
See #1054

**Comment by Singleton06** [comment]
Testing now, I was thinking that I tried this in desperation of trying to get it to work, but without any luck.  I'll post back what I find.

**Comment by Singleton06** [comment]
I've tried it with FTB launcher and disabling all mods except for Botania r1.6-190.  Based on the issue that you linked, I should be able to just shift + right-click and it will place multiple blocks (provided my selection).  This doesn't appear to be working though.  Any other suggestions that I could try out?
