### ISSUE TITLE
Issue + Request

### ISSUE THREAD

**Issue by yepidoodles** [Vazkii/Botania#1102]
Using Botania r1.6 192
Forge 1388
Cauldron for server.jar
Using optifine + 90ish other mods

I have an Issue and a Request.

Issue: On server restarts, all flowers (Functional and Generating) become disconnected from their mana pools/ distributors etc. This has been doing it for the past few updates, but wasn't doing it before then.

Request:
Being a server, we all have items we need to ban, I would like to ban a functional flower, but cannot due to there not being a config option to disable them and the ID's are the same as the other flowers; this causes issues for me. So I would like a config option to disable certain flowers.

So far I have been very impressed with the mod and have been using it for nearly a year for my server/ modpack.

- Alice (yepidoodles)
DragonTechMC
http://dragontechmc.com

**Comment by TheWhiteWolves** [comment]
We are looking into the flower unlinking problem already see #995.

As for the request, 

Short answer: Not likely to happen.

Long answer: [Vaz's Opinion](http://www.reddit.com/r/feedthebeast/comments/39wocx/modpack_makers_what_is_your_vote_for_most_and/cs895pf)

**Comment by yepidoodles** [comment]
I understand Vaz's opinion from a mod-maker perspective, but from a server owner/ admin with a custom modpack, it's important that somethings are tweakable to keep economies/ atmospheres in tune. Vaz believes that if somethings are able to be disabled, it will ruin the path of the mod, but servers will always ban items and as all the other items have IDs and sub IDs, they can be disabled by a ban plugin; But functional and generating flora don't have different IDs and sub IDs to be able to ban a single one. For me, this is something which could potentially get the mod pulled from the pack, as the flower I wish to ban is the Orechid, as it is too easy to automate and could break my very important economy. 
I understand that you wouldn't want people to change/ use your mod, which was made to be a certain way, and I respect that, I just hope my request gets considered, at least.

- Alice (yepidoodles)

**Comment by TheWhiteWolves** [comment]
If you want to remove it then you can probably use something like modtweaker to remove the ability to craft it etc but as vaz said thats on you if it causes a problem.

I don't know how all the cauldron and plugins stuff works as I never use it but you may be able to ban it using tile.botania:flower.orechid or botania:flower.orechid, I don't know why the plugins use id's considering that iirc most mods don't use ids anymore, the items/blocks are accessed through their names, e.g. in vanilla minecraft:stone is smooth stone, minecraft:dirt is dirt, etc.

**Comment by yepidoodles** [comment]
If I use a modtweaker, which I've never used and not happy using. I want to keep using and contributing to the mod, but I'm going to find it difficult if I can't use it to fit my server. 

IDs are removed in 1.8, most 1.7.10 plugins use IDs still, alot still use them on 1.8 still. IDs are much easier for plugins to process. 

So I'm stuck with this config request as a last option before I may have to remove the mod.

**Comment by Sandriell** [comment]
To remove flower recipes with minetweaker you would use something similiar in the script:

"mods.botania.Apothecary.removeRecipe("daybloom");"

**Comment by yepidoodles** [comment]
But then any issues I report would be invalid, and it is also liable to cause issues, which I am not willing to risk.

**Comment by Sandriell** [comment]
Thats why you test before implementing. And if you encounter an issue, you can safely comment out the line (you are just removing the recipe, not the item, so there is no harm from adding/removing it to your world), test for the issue again and report it if it still exists.

**Comment by TheWhiteWolves** [comment]
@Sandriell 's suggestion would probably be the best course of action, if you remove the recipe the item will still exist so it shouldn't cause any problems you just won't be able to craft it and if you get any issues in the future just remove the script, which you would have to do anyway to reproduce the bug with only botania and forge installed to have a valid issue.

btw this is likely what you'll need in the script (I assume you'd want to ban the nether version of the orechid aswell):

mods.botania.Apothecary.removeRecipe("orechid");
mods.botania.Apothecary.removeRecipe("orechidIgnem");
