### ISSUE TITLE
Flowers unbond from mana spreaders on server reload

### ISSUE THREAD

**Issue by Radviger** [Vazkii/Botania#1104]
Hi, @Vazkii.
Players on my server finded a glitch with botania flowers (mana generating flowers) that they unbound from mana spreader sometimes when chunk unloads or server restarts.
And when they loads chunk I get this error: http://pastebin.com/ZxaNqCWJ
Thanks!

**Comment by MrKunji** [comment]
It's already a long-running problem, see past issues.
It could also be Cauldron's fault.

**Comment by TheWhiteWolves** [comment]
Like @MrKunji said this is being looked into in issue #995

**Comment by Radviger** [comment]
What I can do for now? My players don't like this =(

**Comment by TheWhiteWolves** [comment]
unfortunately atm nothing
