### ISSUE TITLE
[SUGGESTION] Milk in vials and flasks

### ISSUE THREAD

**Issue by Nova001Sol** [Vazkii/Botania#1109]
Okay, so this came to me when I was using your potions and found how much space they save. The problem is that my milk still takes a bunch of inventory slots, and they're kind of really important. Hence my request. I'd like to be able to stuff a load of milk (four buckets for a vial, six for a flask) into a Botania potion container. Of course, a brew that works like milk would be great as well. If it only cleared negative effects, even better! But that would kind of break the balance of the Overload Brew, so I don't expect that. Anyway, thank you for reading.

**Comment by MrKunji** [comment]
Do you mean something like the Great Panacea (a potion from Reliquary, that cures, give regeneration and removes debuffs)?

**Comment by Nova001Sol** [comment]
No, just a multi-use version of milk. As I typed in the initial post, removing only debuffs would break the balance of Overload. I can do regen with other brews. I simply need either actual milk in a flask or a brew that does the same as milk.
