### ISSUE TITLE
Orechid Ignem generating useless nether ores

### ISSUE THREAD

**Issue by akvgergo** [Vazkii/Botania#1116]
Nether ores adds the ore blocks and registers them to the ore dictionary regardless of having normal or ingot versions of the ores. This means that because you have specified the spawning rates for things like nether copper and nether tin, you will wind up getting those ore blocks even if you're playing a pack where there are no uses for those ores.
A simple fix would be something like [this](https://github.com/pixlepix/Aura-Cascade/blob/168deb697500e1b0b705b06fbde028f8f762ec2c/src/main/java/pixlepix/auracascade/data/OreDropManager.java#L18-L20)

**Comment by Vazkii** [comment]
Well, that's kinda dumb >_>
