### ISSUE TITLE
Crash or GUI error when Botania mana containers are in inventory

### ISSUE THREAD

**Issue by Haggle1996** [Vazkii/Botania#1117]
Users of my pack are experiencing a common problem when Botania baubles (confirmed with eye of flugel, band of mana, mana tablet -- anything that holds mana) are in inventory and they right-click on blocks from a number of other mods (e.g., Ender IO, BuildCraft Additions, RotaryCraft, etc). Depending on the mod receiving the error packet, this results in either a crash, or an error printed to the screen. 

See Haggle1996/RevolutionPack#23 for an example when right-clicking on a RotaryCraft block. When right-clicking on BuildCraft Additions coils, users crash to desktop (see http://pastebin.com/fNTHDh15). I believe this is the same issue reported by another user with Archimedes Ships in Vazkii/Botania#845. I've also reported this previously as Vazkii/Botania#1007, with a slightly different, but similar error with Ender IO machines.

We are able to replicate this problem across multiple versions of Botania, up to 193.

**Comment by Vazkii** [comment]
Yeah, this log makes no sense at all.

**Comment by Haggle1996** [comment]
For what its worth, I can replicate this problem with a minimal mod set (Forge, Botania, Baubles, EnderIO), but only in multi-player. Works fine in single player and I don't see any errors flow through the log.
