### ISSUE TITLE
Graphic Issue?

### ISSUE THREAD

**Issue by Lunettadawn** [Vazkii/Botania#1121]
![screen shot 2015-06-24 at 7 03 41 pm](https://cloud.githubusercontent.com/assets/13041173/8344207/d9b81176-1aa3-11e5-9143-ac89495e7c68.png)
![screen shot 2015-06-24 at 7 04 16 pm](https://cloud.githubusercontent.com/assets/13041173/8344208/dbb73d26-1aa3-11e5-8f78-5b40099a8a76.png)

I'm not sure how to resolve this. All i have installed is forge, baubles and botania.

**Comment by porteriscool** [comment]
what version of forge are you currently running

**Comment by MrKunji** [comment]
Forge version? Botania version? Does the instance folder have a non-english character?

**Comment by Lunettadawn** [comment]
um the version of forge is 10.13.4.1451 which is the one for 1.7.10. and im running the newest update for botania. and no Mrkunji

**Comment by porteriscool** [comment]
The most recent build of Botania is built for this version of forge as shown in this file where it states forge_version=10.13.2.1291
Botania/build.properties
Try this and you might be all set, inform us how you do if you decide to downgrade your forge version.

**Comment by Lunettadawn** [comment]
thanks. im trying that now

**Comment by porteriscool** [comment]
Okay, and no problem.

**Comment by Lunettadawn** [comment]
much better. Thank you! i cant believe i over looked that when i was installing everything.

**Comment by porteriscool** [comment]
Perfect, have fun.
