### ISSUE TITLE
Reaction of Narslimmus

### ISSUE THREAD

**Issue by couragendures** [Vazkii/Botania#1125]
Nice to meet Vazkii.
My name is couragendrues.

I'm japanese.
I'm sorry when it was mistranslation since the message is sent through the translation site.

- Specifications for Narslimmus -
This flower will generate mana to eat slime , what should one body of slime for one flower is consumed ?

If so , I hope you'll look at the following gif.
http://giant.gfycat.com/VariableAltruisticHuman.gif

Multiple flowers seem to react to one body.
Is this would be specifications ?
I 've checked in the following environments.
--
Windows 7
Java 7 (Build 1.7.0_60-b19)
Forge10.13.4.1481-1.7.10
Botania r1.6-194.jar

Baubles-1.7.10-1.0.1.10.jar
CodeChickenLib-1.7.10-1.1.3.136-universal.jar
CodeChickenCore-1.7.10-1.0.6.43-universal.jar
extrautilities-1.2.6.jar
NotEnoughItems-1.7.10-1.0.4.107-universal.jar
OpenBlocks-1.7.10-1.4.3.jar
OpenModsLib-1.7.10-0.7.3.jar
Waila-1.5.10_1.7.10.jar
WailaNBT-1.7.10-1.4.jar

**Comment by roboliutas** [comment]
Narslimmus accounted for there being smaller slimes (gif shows natural large slime)
