### ISSUE TITLE
Sashes do not work in latest version

### ISSUE THREAD

**Issue by GeekBeam** [Vazkii/Botania#1132]
soujournour's sash (and Globetrotters' sash upon further testing) do not give the speed boost and step assist effect desired. 

further testing with ThaumCraft boots of the traveller indicate issue is mod specific.

issue started upon updating to R1.6-195 and playing any world. I noticed it whenever the sash did not give me the step assist, after playing around with the cosmetics and combining them with baubles in my baubles slot (I do not think this is relevant, as I spawned in a different soujourner's sash and a globetrotter's sash to test that, and also tested in my creative test world for the same problem with a guarantee that it should work properly...but I feel I should be safe saying that.)

Cheers, 
Technus

**Comment by MrKunji** [comment]
I'd assume you are not using a mana container in your inventory, try grabbing a Mana Tablet with some mana.

**Comment by GeekBeam** [comment]
you got it, I'm merely a butt and forgot to look at change logs. my bad.
