### ISSUE TITLE
Botania crashes on start-up

### ISSUE THREAD

**Issue by Floo-chan** [Vazkii/Botania#1136]
Heya! I just installed Botania and it doesn't work - crashes on the start. I have the latest version of everything. The game simply doesn't start and I suspect that some mods are clashing, but I couldn't find any information on incompatibilities. I also tried to find a way to fix it, but alas, nothing. Could you check if something is messing with it? I'd appreciate it! ^^ 

FML log: https://docs.google.com/document/d/1-LKImVcCiyvYEREGxhtvqtYaUn2Y46UNBN4yNg2a3jQ/edit?usp=sharing
Crash Log: http://jpst.it/zTWM

**Comment by TheWhiteWolves** [comment]
- cpw.mods.fml.common.LoaderException: java.lang.NoSuchFieldError: wheat_seeds

thats from the FML log, one of the mods you have installed is altering the vanilla seeds, so that they don't exist when botania tries to access them

**Comment by Floo-chan** [comment]
hmm... the only one I cna think of would be MoarFood. I'll try running the game without it

**Comment by TheWhiteWolves** [comment]
You'll want to drop them a bug report then as that will most likely be affecting more mod setups, basically anything that references the vanilla seeds will crash with it

**Comment by Floo-chan** [comment]
So I'm back again, After trying to run the game today, I still get the 'java.lang.NoSuchFieldError: wheat_seeds' part. Tried running it with just baubles and Botania, still gives me that. So. Not a mod issue.

**Comment by TheWhiteWolves** [comment]
try redownloading minecraft and starting from a fresh install of it, sounds like something corrupted and you lost some files and see it that solves it.

**Comment by Floo-chan** [comment]
I did try that, figured something was missing, but nope, still did that after redownloading

**Comment by TheWhiteWolves** [comment]
what versions are you running, MC, Forge, botania etc

**Comment by Floo-chan** [comment]
Minecraft 1.7.10
Forge: 10.13.4.1448-1.7.10
Botania r1.6-197

**Comment by MrKunji** [comment]
First thing, [Botania{r1.6-197} [Botania] (Botania r1.6-197-deobf.jar) Unloaded->Constructed->Errored].
Where did you downloaded Botania from?

**Comment by Floo-chan** [comment]
official website? http://botaniamod.net/downloads.php

**Comment by MrKunji** [comment]
Git is being a little troll to me, it's not showing the correct file name in the comment above.
What I meant is that you downloaded a deobf version, aka developer version, you might have clicked the wrong button in the page.

**Comment by Floo-chan** [comment]
oh? Lemme see...
