### ISSUE TITLE
Ender io and Botania compatibility (Moved from EnderIO issue tracker)

### ISSUE THREAD

**Issue by Bellwar** [Vazkii/Botania#1139]
I want to move the report here because i was told it is on Botania side.

I have problem with ender Io item conduit connecting redstring container. Im playing botania 191 build and ender io 2.2.8.381.

Screenshots: http://imgur.com/8nVgPas,jUVpUJs#0

There was little discussion about it: https://github.com/SleepyTrousers/EnderIO/issues/2600

**Comment by Vazkii** [comment]
This issue has already been fixed. Please update your version of Botania or wait for a new one to come out if the fix isn't available yet.
*This message is a macro.*
