### ISSUE TITLE
ALFheim portal not opening

### ISSUE THREAD

**Issue by snacdaws** [Vazkii/Botania#1143]
built the alfheim portal properly but it fails to open upon right clicking portal core

**Comment by MrKunji** [comment]
Botania version? FML log?
We don't have a crystal ball :P

**Comment by snacdaws** [comment]
it happens even with the latest version 

oh i should probably mention i am playing with the Direwolf 20 1.7 modpack

i'm not sure how to get the fml log as it doesn't crash so it doesn't generate one

**Comment by Titanium237458** [comment]
Are you right clicking it with a wand of the forest? Are you sure ou built it correctly? Do you have enough mana?
Opening the portal works fine for me.

**Comment by snacdaws** [comment]
yes titanium i am sure i built it correctly

i built it exactly as the lexicon told me to

every other part of the mod works perfectly

i even tried it with the creative mana pool and it still didn't work

**Comment by TheWhiteWolves** [comment]
Can u take a screenshot of it for us so we can see
