### ISSUE TITLE
Cosmetic bauble duplication

### ISSUE THREAD

**Issue by PaladinOne** [Vazkii/Botania#1146]
Earlier today I went into a battle wearing normal armor and a pair of Orange Shades and died. When I resurrected, I still had the Orange Shades equipped, but the rest of my inventory was strewn around where I died (the pack I was in didn't have gravestones).

While this is a fairly inconsequential item to be duplicated, if the duplication occurs with Baubles that have actual effects it could be an issue.

This may be a Baubles issue more than a Botania issue, but as it was a Botania item that was duplicated I decided to come here first. Running Botania r198.

**Comment by RoloEdits** [comment]
Can Confirm It Just Happened To me But With useful Baubles. I died and when i broke my grave stone the baubles that were on me were in there doubling my amount

![2015-07-08_21 21 42](https://cloud.githubusercontent.com/assets/12489689/8587880/ab964208-25b7-11e5-814f-8fbbab028cf6.png)

**Comment by RoloEdits** [comment]
unfortunately i went on a dying spree but after breaking another gravestone it happened again 

![2015-07-08_21 28 35](https://cloud.githubusercontent.com/assets/12489689/8587937/50dad9e0-25b8-11e5-840e-80a025e1ab83.png)

**Comment by TheWhiteWolves** [comment]
I've tried multiple ways of dying and not been able to reproduce with base botania, so unless you can manage to reroduce with only botania and can give me a consistent way to do it, I'm closing the issue.
