### ISSUE TITLE
Lexicon getting stuck

### ISSUE THREAD

**Issue by nrzimmer** [Vazkii/Botania#1149]
Botania version: Version R1.6 198
Forge version: 10.13.4.1481
No MCPC+
No Optifine
Single Player

After the last update of Botania I opened the lexica botania and navigated to the Horn of the Wild page.

When I press the Back arrow the book "close" and the game stops (similar to a non responding window) until I press ESC.

If I shift click in the Pasture Seeds recipe, the back button works fine, but when I get back to the Horn entry it stops working again.

After a game restart the problem was solved, but it happened 2 more times with different entries (I'm not sure how to reproduce it, but when it occurs only a full client restart to solve, saving the game and reloading the world leave me stuck in the same entry)

**Comment by Vazkii** [comment]
Can you reproduce it with only botania?

**Comment by nrzimmer** [comment]
Apparently i can't.
If i find a way to reproduce i'll update this Issue with it.
