### ISSUE TITLE
Garden of Glass

### ISSUE THREAD

**Issue by RedsaphirCZ** [Vazkii/Botania#1155]
Hello Vazkii,
I really enjoy idea of Garden of Glass. There is only one think I am missing.
Is it possible to modify Marimorphosis to give different types of stones? Like worldgen without ores?
Railcraft stones, saltpeter ore, skystone, marble etc...
Or is there way to generate them? :)
Thank you, keep up the awesome work

**Comment by Vazkii** [comment]
Use MineTweaker for that.
