### ISSUE TITLE
[Suggestion] Config option for Clayconia: sand to single clay item OR clay block

### ISSUE THREAD

**Issue by Mierzen** [Vazkii/Botania#1156]

**Comment by Vazkii** [comment]
Why?

**Comment by Mierzen** [comment]
I was playing AS2 and being used to barrels with water + dust = clay, I kind of expected Clayconias to replace sand blocks with clay blocks.

I planned on saying that the Ex Nihilo method renders the Clayconia useless in that case, but I have just realised that it does not - you get spared one step of turning the sand into dust first. 

Do you think it would be good to then add the feature and config option for also turning Ex Nihilo dust blocks into clay blocks?
