### ISSUE TITLE
Ring of Loki doesn't work properly

### ISSUE THREAD

**Issue by Dawnflash** [Vazkii/Botania#1159]
Reproducible in latest Botania versions 193+
The functionality works in version 192

Ring of Loki allows for omni-breaking blocks with the Terra Tools (Truncator and Shatterer), including their special abilities (Shatterer can thus break infinite blocks in one hit), but does NOT work with hand / other tool mining, NEITHER placing a block down as presented in the YT Omnipresence showcase.
Naturally, this also holds true for Ring of Aesir.

Not sure if bug or feature, but it's certainly not documented, so I'm asking for review

**Comment by MrKunji** [comment]
Ominpresence uses shift right click to place blocks.
As for breaking blocks, I'm pretty sure it shouldn't break.

**Comment by Dawnflash** [comment]
Nope, I tried that. Shift+Right Click does nothing, Omnipresence is broken.
I tested with Botania 201 and Baubles 1.0.1.10, forge 1448.
Breaking blocks works in Omnimode with Truncator and Shatterer. Placing blocks and breaking otherwise is impossible, no matter what keys are pressed

**Comment by Dawnflash** [comment]
65eaa8de51035770693b18350670c9fb3c93875f
The change happened here, supposedly fixing the Ring's functionality, but it removed its block-placing capabilities instead.

**Comment by Arkentosh** [comment]
Can confirm I'm having the same issues with my game, I thought it was an SMP issue so I tried SSP and it didn't work, I tried to update Botania to the latest version and that didn't work either. I can break blogs in the grid, but not place, so I'm assuming somehow the functionality got reversed..

**Comment by TheWhiteWolves** [comment]
Tried to replicate and the results are, placing multiple blocks works fine so not gona look into it, as for the breaking with hand or non terra tool, this is intentional as far as i can see

**Comment by Dawnflash** [comment]
Are you sure?
I could only place multiple blocks in 192 and prior versions.
What kind of magic do you use to place multiple blocks in 193+?

**Comment by Arkentosh** [comment]
Yes I would like to know the answer to this too, because I've tried placing while sneaking and without, both with the grid snapped and without with 0 luck.

**Comment by TheWhiteWolves** [comment]
http://gfycat.com/FlakyBogusIndochinesetiger

That's proof its working fine for me, Shift-Right Click to start Omnipresence, Shift-Right Click to place the blocks and break em with a terra shatterer, all works fine.

**Comment by Dawnflash** [comment]
Oh yes, thanks for that clarification.
So omnipresence placing blocks only works when the omni-grid is not "finished" by shift-right clicking the origin block.
So you can't visually move your omni-grid and place down blocks, but you can for mining.
Is this intentional?

Per se:
I set up a 3x3 omnigrid and like you've demonstrated, I put down 9 blocks. Then I move somewhere else and place down 9 more, but I can't see the omni-grid on the ground anymore.
If I decide to use the old mechanics and shift-right click the origin block of the omni-grid to make the grid move around, I lose the ability to place down blocks on it.

**Comment by TheWhiteWolves** [comment]
if you move somewhere else and try it, it should still place down the blocks, does for me iirc.

I'll have to take a look at the disconnecting from orgin one as it is possible that i did break that one.
