### ISSUE TITLE
Visual bug - Petal Apothecary

### ISSUE THREAD

**Issue by JugglerMaster** [Vazkii/Botania#1161]
When two of them are side by side, you can drop one seed and it looks like you crafted both flowers. Then you can drop another one and it will give you the missing flower. I am on version 193 using the FTB Infinity mod pack. 

![2015-07-11_13 32 07](https://cloud.githubusercontent.com/assets/5704557/8634898/0cae046a-27d2-11e5-87f2-e3a834390afe.png)

![2015-07-11_13 32 11](https://cloud.githubusercontent.com/assets/5704557/8634899/0eaf77b2-27d2-11e5-99f8-2032fc3b98a6.png)

**Comment by TheWhiteWolves** [comment]
http://gfycat.com/UntimelyPlainApatosaur

For future reference, GIF showing the bug.
