### ISSUE TITLE
Soujourner's Sash and Globetrotter's Sash Broken

### ISSUE THREAD

**Issue by kwstoudt** [Vazkii/Botania#1167]
I have made (and spawned in) the 2 sashes and neither of them fully work. They are both giving me the jump boost, but neither are giving me the speed or step assist. Multiplayer (Direwolf20 1.5.0) and Singleplayer (just Botania and Baubles) both produce the same result.

**Comment by MrKunji** [comment]
Grab a mana container item.

**Comment by TheWhiteWolves** [comment]
Like @MrKunji said it will be cos you've not got a mana container on you, also the reason only the jump works without the mana container is because you are using an old version from before I fixed it

**Comment by kwstoudt** [comment]
well it would have been nice to know that you needed a Mana Tablet because before DW20 1.5.0 came out that wasn't needed.

**Comment by Vazkii** [comment]
It says on the book and the changelogs. How else are we supposed to tell you?
