### ISSUE TITLE
Mana pool merg

### ISSUE THREAD

**Issue by BurningEagle** [Vazkii/Botania#1169]
I'd like a small change made to mana pools. Make them so they can have different sizes when placed next to eachother. So for mana storage people usually make massive spots with tiny pools inside them, wouldn't it be cool if they merged together as 1 big multiblock-structure pool? It would still take up the same amount of space, same amount of resources and be able to store the same amount of mana, but instead it acts as one pool. Think about it as like they were capacitor banks from ender-io (except not stackable in hight).

**Comment by Lazersmoke** [comment]
@BurningEagle I might implement this in my Botania Addon "[Botanical Workshop](https://github.com/Lazersmoke/Botanical-Workshop)", but no garuntees

**Comment by OJwithC** [comment]
http://vazkii.us/uncategorized/stuff-you-wont-see-in-botania/
