### ISSUE TITLE
Botania Flower

### ISSUE THREAD

**Issue by RaptorSB** [Vazkii/Botania#1173]
12 Dayblooms disappeared (know what that was now), used command /give me 737 12 and received the red Botania Flower in their place. Tried using the name Daybloom instead of the ID, and received the message that there was no item with that ID

FML Log: http://pastebin.com/DyRqtV5T

**Comment by MrKunji** [comment]
Passive generation flowers (Dayblooms, Nightshades and Hydroangeas) now wither away after two game days (by default).
Also, flowers are defined by NBT, not metadata.
Just check the changelog BEFORE submiting a issue.
