### ISSUE TITLE
Wither Time not working

### ISSUE THREAD

**Issue by OneofTen** [Vazkii/Botania#1174]
i have the setting at -1 and flowers disappearing regardless.

**Comment by OneofTen** [comment]
anything that i need to priovide ?

**Comment by TheWhiteWolves** [comment]
Read the contributing guidelines and provide us with version numbers etc.

**Comment by Bellwar** [comment]
http://vazkii.us/br101/

**Comment by OneofTen** [comment]
okay updated to the latest version, will check if still a problem.

**Comment by Vazkii** [comment]
Any info?

**Comment by Vazkii** [comment]
Closing for lack of updates.
