### ISSUE TITLE
Mana Container/Band of Aura issue in conjunction with Rotarycraft. 

### ISSUE THREAD

**Issue by Melakion** [Vazkii/Botania#1176]
There seems to be an issue with mana containers updating their mana levels with Rotarycraft installed.

This results in errors such as:
[15:49:45] [Client thread/INFO] [FML/]: A mod tried to access an invalid slot 9 for TileEntity Tile Entity Industrial Coil @ DIM0: -188, 63, 129.
[15:49:45] [Client thread/INFO] [FML/]: It is likely assuming the TileEntity has an inventory when it does not.

With a mana container in the top left inventory slot. I have seen it with Mana Tablets, Band of Mana, and Greater Band of Mana. (and for some reason with the Eye of Flugel, even though it isn't a mana container)

I have only been able to get the error with the mana container in the inventory, not in the hotbar. With the mana container in hand, you instead crash with a Ticking memory connection. Here is that crash log: http://pastebin.com/Qx37mTUq

To make this easily reproducible, I made a minimal modpack with Baubles, Botania, DragonAPI, and Rotarycraft. (Along with CodeChickenCore, NEI, and WAILA)
I equipped a Greater Band of Aura and Sojourner Sash with a full mana container in inventory so that the mana container is constantly ticking between full and almost full. 
Place a Rotarycraft Industrial Coil on the ground, then right click to open its GUI.

The error doesn't occur every time you open the GUI, but it does consistently happen.

Here is the full log file from test, first with the Greater Band of Mana in slot 9 (Top left main inventory), then in hand: http://pastebin.com/RzTX8MbH

**Comment by ReikaKalseki** [comment]
This is caused by an item/block/TickHandler/etc trying to access the inventory of the Container object even though the Container has no inventory slots. Normally, this would crash, but DragonAPI intercepts this and prints that error instead. Known causes include InventoryTweaks and Forestry backpacks.

**Comment by Melakion** [comment]
Was there a commit or any new information on this issue?

**Comment by ReikaKalseki** [comment]
It is not serious, and does not break anything. If Vazkii did do anything to avoid triggering it, she would be the first dev ever to do so (most other devs have historically brushed it off or said it was somehow my fault because "What's the point of a container with no inventory").
