### ISSUE TITLE
Make tall flowers spawn noral flowers around them

### ISSUE THREAD

**Issue by Kubuxu** [Vazkii/Botania#1178]
It would be cool mechanics that would make tall flowers special.
Currently their only use is for ascetics (that I am aware of).
Making them slowly spawn flowers in narrow range (4 blocks radius) with limit of N flowers around,
would allow them to be slow alternative to Jaded Amaranthus.

**Comment by MrKunji** [comment]
They can be grown by using bone meal on regular Mystical Flowers and cut with shears, they wield four petals instead of two. That's their current function (it's on the book, in case you haven't read)
