### ISSUE TITLE
Incense Sticks don't get ignited by Kindle Lens

### ISSUE THREAD

**Issue by luxamy** [Vazkii/Botania#1180]
This happens in Build 202. I didn't test in prior versions.
Heres a picture of my setup.
![2015-07-18_01 49 52](https://cloud.githubusercontent.com/assets/6637109/8759210/a6c8b802-2cef-11e5-92c4-fca4f8af7608.png)
The Mana Burst travels through the Incense Plate and dosn't ignite the stick.
I tried different Incense Sticks but none work.
Besides Botania I have following Mods Installed:
Baubles
CodeChickenCore
Garden of Glass
Inventory Tweaks
JourneyMap
NEI
Waila

FML log: http://pastebin.com/tGu6DWib

**Comment by MrKunji** [comment]
Have you tried to point the Spreader at the exact position of the Incense Plate? Collision boxes does matters.

**Comment by luxamy** [comment]
ohh... yea that was it.
sorry for posting this then.
