### ISSUE TITLE
Gaia Guardian(s) bug

### ISSUE THREAD

**Issue by Cayo-mist** [Vazkii/Botania#1183]
It's possible to summon two Gaia Guardians at once in version 201. Once you beat them the battle track keeps playing.

**Comment by MrKunji** [comment]
Must be tested in 202.

**Comment by Bellwar** [comment]
@MrKunji Can i ask you, why do you need update to check bug that has nothing to do with changed code? or is there a change, but from changelog i dont think so. (Im just asking :) )

**Comment by MrKunji** [comment]
Because otherwise the devs will not attempt to solve, it would might break unnecessary things.
And it's a statement in the Contribuition Guidelines.

**Comment by Bellwar** [comment]
Yes but like the new problem in CS when you dont change something how it could but the case. I dont want to talk about it here (we are not on reddit or so) but cant understand it.

**Comment by Vazkii** [comment]
Can't reproduce.
