### ISSUE TITLE
Gaia Guardian Not Spawnable with /summon (SSP/SMP)

### ISSUE THREAD

**Issue by duhadventure** [Vazkii/Botania#1186]
Botania Version: 198
Forge Version(s): 1231 & 1338
No Optifine

When you try to summon a Gaia Guardian with /summon Botania.botania:doppleganger X Y Z it will not summon. This is possibly because the Gaia Guardian must have a preset spawn position set to exist. (tested as cloning one would revert it to where it was originally created. I was going to attempt to create a version of the Gaia Guardian with a warded shield and potion effects (once I got the NBT data from Azanor on how to do that with Command Blocks). Logs probably wont help as it is with /summon as it is just 1 command....

Technic Log: http://pastebin.com/LsdbnuHV
Serverside Log: http://pasted.co/0d8e1178
![2015-07-18_14 42 24](https://cloud.githubusercontent.com/assets/8278338/8763321/0e10c5ce-2d5c-11e5-9f03-ae9cee25a29b.png)
![2015-07-18_14 43 02](https://cloud.githubusercontent.com/assets/8278338/8763322/0e1972dc-2d5c-11e5-9e6a-bc3ab31bb33b.png)
![2015-07-18_14 43 11](https://cloud.githubusercontent.com/assets/8278338/8763324/0e1ad906-2d5c-11e5-9075-83b9c287bc26.png)
![2015-07-18_14 47 54](https://cloud.githubusercontent.com/assets/8278338/8763323/0e19d2cc-2d5c-11e5-8ad9-c0ead96819a8.png)
![2015-07-18_14 47 58](https://cloud.githubusercontent.com/assets/8278338/8763325/0e1c1bfe-2d5c-11e5-8f21-fd7a5c2ab916.png)

First 3 pics are from server last 2 are SSP.

**Comment by Vazkii** [comment]
You also need to specify these tags so it knows where to check for players: https://github.com/Vazkii/Botania/blob/master/src/main/java/vazkii/botania/common/entity/EntityDoppleganger.java#L86-L88

**Comment by duhadventure** [comment]
Example please?

**Comment by Go-Wish** [comment]
How would I use these tags in a /summon command?

**Comment by williewillus** [comment]
Check the vanilla wiki on how to summon entities with NBT, and specify the sourceX/Y/Z tags somewhere nearby

**Comment by Go-Wish** [comment]
My apologies @williewillus, but I’m not sure exactly what nbt tags I should be applying in this situation.
