### ISSUE TITLE
Hopper carts can't put items in open crates

### ISSUE THREAD

**Issue by cdfa** [Vazkii/Botania#1189]
It's not the worst thing in the world that they can't, but they kinda should right?

**Comment by Kubuxu** [comment]
Hopper carts don't push items. They only collect.

**Comment by cdfa** [comment]
Oh right. I'm stupid. Sorry!

**Comment by TheWhiteWolves** [comment]
What u can do is run the minecart over a hopper that's connected to the open crate, that will then do whatever it is you want

**Comment by cdfa** [comment]
Yes I know. Thanks :)
