### ISSUE TITLE
Cocoon of Caprice is invisible in the Creative Tab and NEI

### ISSUE THREAD

**Issue by gabor6505** [Vazkii/Botania#1191]
I tried it without OptiFine in the latest version of FTB Infinity modpack too (1.8.2), but either in that and in my modpack it is invisible in the Botania Creative Tab, and NEI (and probably in every storage) But it do render fine as a block.

Versions I tested with:
r1.7-201 (Infinity and my modpack has this too)

![2015-07-21_22 19 44](https://cloud.githubusercontent.com/assets/12859334/8811615/530ab58e-2ff7-11e5-8be8-a7679215d7f4.png)
![2015-07-21_22 27 04](https://cloud.githubusercontent.com/assets/12859334/8811663/ab4f9890-2ff7-11e5-87a9-8c00e0af75d6.png)

**Comment by SquidDev** [comment]
Can also confirm for the Mana Prism. No optifine, Garden of Glass and Botania 202.

**Comment by Vazkii** [comment]
I can see it just fine.

**Comment by Kubuxu** [comment]
It might be connected with fact that older GFX require square textures and or power of two dimensions.
