### ISSUE TITLE
Sparks makes transparency in the Mana Pools

### ISSUE THREAD

**Issue by gabor6505** [Vazkii/Botania#1192]
If I put Sparks on top of Mana Pools, I can see through them a little bit. It could an be intended feature, I don't know, but I decided to report / ask this.
This issue appears in the FTB Infinity Modpack as well (tested with v 1.8.2).

Botania Version used:
r1.7-201

![2015-07-21_22 32 40](https://cloud.githubusercontent.com/assets/12859334/8811861/0cb42726-2ff9-11e5-86fb-dd43d6d8f753.png)

**Comment by Vazkii** [comment]
This is a vanilla bug.
