### ISSUE TITLE
Lost most Mana Generating Plants

### ISSUE THREAD

**Issue by AbnormalSee** [Vazkii/Botania#1195]
I updated to 203 in my FTB Infinity game, restarted and lost all my hydrangeas, dayblooms and nightshades. Replaced them all. Them 204 came out, exact same thing happened. Went back to my 201 jar file....grrrr.

**Comment by MrKunji** [comment]
Read the changelog
https://github.com/Vazkii/Botania/blob/d641bfc7a70c1e01f97d57cd6898c66da003d258/web/changelog.txt#L101

**Comment by Lazersmoke** [comment]
A recent change made passive generation flowers wither away by default. Is this what happened to yours?
