### ISSUE TITLE
config options for disabling items with invisibility effect

### ISSUE THREAD

**Issue by hunter688** [Vazkii/Botania#1197]
Please add some config options for disabling items with invisibility effect. I think invisibility is inconvenient for multiplayer and want disable it ot my server.

**Comment by TheWhiteWolves** [comment]
Most likely the answer is no, if you are on about the ability to make your armour invisible then you can go use minetweaker to remove the ability to craft Phantom Ink (this is what makes the armour invisible) but you take this upon yourself todo and if you cause a crash we are not responsible.
