### ISSUE TITLE
Cocoon of Caprice doesn't render properly

### ISSUE THREAD

**Issue by Slar-ti-bart-fass** [Vazkii/Botania#1200]
It seems like the rendering of the Cocoon of Caprice doesn't appear where it is supposed to.
The issue remains with just Botania, Garden of Glass and Baubles installed.
I have the latest Forge version(10.13.4.1492) installed and use an AMD graphics card.

![2015-07-24_21 12 45](https://cloud.githubusercontent.com/assets/6683337/8882651/f66d50b2-3248-11e5-883c-60fb0d5ea55e.png)

![2015-07-24_21 13 29](https://cloud.githubusercontent.com/assets/6683337/8882658/ffb34f46-3248-11e5-8877-aa24749d9eea.png)

![2015-07-24_21 13 40](https://cloud.githubusercontent.com/assets/6683337/8882661/0320da18-3249-11e5-82c9-624788ffd797.png)

**Comment by Slar-ti-bart-fass** [comment]
Also happy 1200th issue \o/

**Comment by SquidDev** [comment]
Duplicate of #1191. Vazkii can't reproduce though.

**Comment by Slar-ti-bart-fass** [comment]
I should've checked all the non-open issues *facepalm*
