### ISSUE TITLE
Config for Generating Flora

### ISSUE THREAD

**Issue by Gammelkebab** [Vazkii/Botania#1209]
I'd really like to see config for the generating flora so one could buff/nerf them on a server. Endoflames are pretty OP compared to pretty much everything else - i'd like to see the thermalilly viable too, which it isn't because the super long CoolDown.

**Comment by MrKunji** [comment]
Not going to happen.

**Comment by Lazersmoke** [comment]
MineTweaker

**Comment by MrKunji** [comment]
He wants to change the produced mana value, not recipies.
