### ISSUE TITLE
Problems with Lexica Botania

### ISSUE THREAD

**Issue by Cerugon** [Vazkii/Botania#1210]
Whenever I open a entry in my Lexica Botania, the spaces between the words are non-existend or even "inverted" (words overlapping each other) (as can be seen in this screenshot: http://imgur.com/ubXkbNb )

I tried to delete the config (after this bug) to fix this bug, since it appeared first when I updated from an very old version of Botania (updated a few times since then).

Also this does not appear in the Listing of the different articles or the first page. Its only in the articles themselves.

FML Log: http://pastebin.com/ngZruQXf

**Comment by Vazkii** [comment]
Update reika's mods.
