### ISSUE TITLE
Botania Addon :D (yay!)

### ISSUE THREAD

**Issue by romaoplys** [Vazkii/Botania#1215]
Vaskii, you said that you wants to know what we are doing for addons, so: I will (try) to do a tree-version of the flowers, that generates 10x mana than a normal flower , they would be realy big ( 4x4 and 10 blocks tall) and if any part of it gets broken, it would corrupt the tree and makes it unfunctional!

Ps- Can you tell me what programs do you use for coding? :P

**Comment by MrKunji** [comment]
Everything is made on Eclipse, the API is free to use.
But things like this must be asked on the Minecraft Forum, not here.
Also, Vazkii is currently not watching the Botania repository.

**Comment by Lazersmoke** [comment]
I didn't know that Vazkii wanted to know; I am making a Botania Addon when I feel like it called [Botanical Workshop](https://github.com/Lazersmoke/Botanical-Workshop). It adds lots of random stuff that doesn't really belong in Botania, and random stuff that I feel like adding (quake-style bunny hopping boots, etc.)
