### ISSUE TITLE
Bore lens on mana spreader don't fire a break block event.

### ISSUE THREAD

**Issue by AfterWind** [Vazkii/Botania#1217]
This is for a protection forge mod called MyTown2. We are using the break event to protect against griefing and we've found out that the mana spreader with a bore lens on it does not fire the Forge break block event.
Can you please fix this to significantly lower our work time for protecting against this specific block?

**Comment by superscruffy** [comment]
The mana blaster with bore lens might have the same issue.

**Comment by ruifung** [comment]
Thats because both the mana blaster and mana spreader uses the same code. At least for the mana burst entity anyway.

**Comment by Eufranio** [comment]
Is there a fix?
