### ISSUE TITLE
Curseforge dependencies.

### ISSUE THREAD

**Issue by Claycorp** [Vazkii/Botania#1220]
On curseforge when you upload you can set if the mod depends on another library/api or whatever.
Sence Botania needs Baubles you should set that requirement so when people use the Curse Voice launcher it will automatically download Baubles.

Also you should update your links on curseforge to the new site.

**Comment by Vazkii** [comment]
Paging @nekosune

**Comment by Vazkii** [comment]
https://github.com/Vazkii/Botania/pull/1256
