### ISSUE TITLE
Terrasteel not crafting

### ISSUE THREAD

**Issue by jimmyh77** [Vazkii/Botania#1222]
I am unable to craft Terrasteel using Botania r1.7-208 and Forge 1.7.10-10.13.4.1448-1.7.10

I have plenty of mana with sparks on each mana pool and a spark on the Agglomeration plate.
The block below the plate is living rock.  I put the Mana Pearl and Mana Diamond and the Manasteel on the plate and nothing happens.

If I point the spreader I have at the plate then it starts to work.

Here is a screen shot showing my setup.
http://i.imgur.com/WqK25kX.png

**Comment by TheWhiteWolves** [comment]
I can't be 100% certain off the top off my head but it looks like you got your lapis and livingrock the wrong way round, the livingrock goes in the corners and lapis goes on the sides.

**Comment by MrKunji** [comment]
I can ensure the pattern is wrong, I remember the book says 'There's Livingrock under the plate'.

**Comment by jimmyh77** [comment]
gah, I feel like a complete dumbass :(
