### ISSUE TITLE
Rannucarpus cannot target farmland.

### ISSUE THREAD

**Issue by AshleyWright** [Vazkii/Botania#1227]
The intention of this was to complete the normal difficulty challenge of a full crop farm. However the automated planting of crops appears impossible unless you want an ugly mess of dispensers.

Floating flowers appear to cause the farmland it is placed upon to turn to dirt, which cannot be re-tilled whilst the flower remains atop it. A non-floating rannucarpus would require the farmland to be under the soil block which vanilla minecraft doesn't allow.

Potential solutions are:
- Special case for the rannucarpus, when placed on a tilled soil type it targets said tilled soil.
- The placing of a floating rannucarpus does not un-till the soil.
- If you want to be really evil: A redstring spoofer can be placed atop farmland without un-tilling it.

**Comment by Lazersmoke** [comment]
IIRC the farmland goes two blocks below the floating flower, not one. This may have been changed, though.

**Comment by Titanium237458** [comment]
@Lazersmoke that changed in build 170.

**Comment by AshleyWright** [comment]
Why close this issue? My original testing was in build 208. I believe @Titanium237458 comment was purely in reply to @Lazersmoke about the target block distance from floating flower. The original post as far as I'm aware still has no resolution.

**Comment by OJwithC** [comment]
I would guess the answer is "use dispensers" since, as you stated, they can plant. The second challenge is making it look pretty.
