### ISSUE TITLE
Crash on loading client

### ISSUE THREAD

**Issue by Simlirr** [Vazkii/Botania#1234]
This happens when I try to launch my game. 
inb4: It is not the Optifine causing problems, I tried it without Optifine and got the same error, and in my other modpack it works well with Optifine.
Crash log: http://pastebin.com/akmhcz7d

**Comment by TheWhiteWolves** [comment]
Have you replicated this with only botania installed, if not then take out all your mods and add them back in one at a time until you find which one causes the crash

**Comment by Simlirr** [comment]
Ok, the problem was in Blocks3D Mod. Any ways to solve it (except deleting)?

**Comment by TheWhiteWolves** [comment]
Assuming that their mod is done through core modding it is unlikely, you best bet is to delete it atm and submit a bug report to them so that they know about the incompatibility so that they know about it and in future may be able to find a solution.
