### ISSUE TITLE
Pure Daisy doesn't convert Cherry Wood when placed sideways

### ISSUE THREAD

**Issue by Zyin055** [Vazkii/Botania#1235]
I have not tested with other Biomes O' Plenty woods, but the Cherry Wood acts in this way. See screenshots:

Before: http://i.imgur.com/F9g59l4.jpg
After: http://i.imgur.com/L2xd6ZR.jpg

Using Botania r1.7-208.jar.

Also I love that uwotm8 tag :D

**Comment by Vazkii** [comment]
Not my problem, it's not on the oredict for some reason.
