### ISSUE TITLE
Factorization Dark Iron

### ISSUE THREAD

**Issue by anexusarchon** [Vazkii/Botania#1239]
It seems that at least as of Factorization 0.8.95 (Current as of nowish), Dark Iron ore is no longer in the Oredict: oreDarkIron, but is instead in oreFzDarkIron, spent hours in GoGlass trying to get Dark Iron, using Botania 208.

As a workaround I've just used minetweaker to add Dark Iron to oreDarkIron.

**Comment by TheWhiteWolves** [comment]
Look like its been changed, this is from the Factorization 0.8.95 - Registry.class L315

OreDictionary.registerOre("oreFzDarkIron", this.dark_iron_ore);
