### ISSUE TITLE
FTB Botania quest book problem

### ISSUE THREAD

**Issue by RowenaLee** [Vazkii/Botania#1242]
I downloaded Botania from the FTB launcher as the Game of The Month. In the quest book under Beyond The Basics I have made the mana lenses Bore and Phantom but the questing book will not accept them when I press Manual Detect.

FML Log: http://pastebin.com/rYGJDC6T

This is the client-1 log.

Here is the latest log: http://pastebin.com/7Djx5MJ0

**Comment by TheWhiteWolves** [comment]
nothing to do with us
