### ISSUE TITLE
Runic altar index page

### ISSUE THREAD

**Issue by Hyxaru** [Vazkii/Botania#1244]
The first and the seventh page share the same lines of text.

**Comment by MrKunji** [comment]
https://github.com/Vazkii/Botania/blob/master/src/main/resources/assets/botania/lang/en_US.lang#L1607
^This particular line should be changed to 'botania.page.runeAltar22'
https://github.com/Vazkii/Botania/blob/master/src/main/java/vazkii/botania/common/lexicon/LexiconData.java#L317
^So does the related entry
[it was a silly error, @Vazkii ¬¬]
