### ISSUE TITLE
Loki Ring not firing a place block event

### ISSUE THREAD

**Issue by AfterWind** [Vazkii/Botania#1245]
This is for protection, please take this issue into consideration. With a simple event implementation we can prevent all the griefing that can be done with this item.

**Comment by Vazkii** [comment]
Delegating this to @TheWhiteWolves because I'm lazy.

**Comment by Vazkii** [comment]
Oh, and #858

**Comment by Vazkii** [comment]
And #1217. All the same thing.

**Comment by spannerman79** [comment]
Expressing an interest in this, block breaks need to fire the correct Forge BreakEvent standards  - hence a fakeplayer is needed.

If it helps Mekanism already introduced this change in https://github.com/aidancbrady/Mekanism/commit/77db81bcf0c0eaaa7f3757e7b1a610b804491253 for the readout/log file for people wishing to place the fake player with the correct permissions.

**Comment by Eufranio** [comment]
Is there a fix?
