### ISSUE TITLE
Basalt Brick Double Slab block drops single slab when broken.

### ISSUE THREAD

**Issue by SephirothWS** [Vazkii/Botania#1249]
As said on the tin. If you create a full block with two basalt brick slabs, when you break it you only get a single slab back. Vanilla slabs work in a way where these "double-slab" blocks drop both slabs.

**Comment by Vazkii** [comment]
Can't reproduce.

**Comment by SephirothWS** [comment]
Steps to Reproduce:

1. Place a basalt brick slab down.
2. Place a second basalt brick down down on top.
3. Watch as it becomes a full block.
4. Mine up the double basalt brick block with your pickaxe in survival mode.
5. Receive only 1 basalt brick slab.

**Comment by OJwithC** [comment]
I get both slabs back.
