### ISSUE TITLE
Odd visual when rotating double chest with Wand of the Forest

### ISSUE THREAD

**Issue by OJwithC** [Vazkii/Botania#1259]
Botania v208 
Using the wand to rotate a double chest on the north or west side makes it only visually change. The chest that is visually moved is in its original position (and can be targeted), and you can walk through where it visually appears. Persists after relog.
![2015-08-15_16 19 26](https://cloud.githubusercontent.com/assets/10445127/9290744/12420e70-436c-11e5-9024-58a52c2c3cf4.png)

**Comment by Vazkii** [comment]
This is a forge bug.
