### ISSUE TITLE
Ring of Loki/Aesir + Terra Shatterer breaks liquids

### ISSUE THREAD

**Issue by OJwithC** [Vazkii/Botania#1260]
Botania v208

Using the ability of the Ring of Loki, the Terra Shatterer can break water and lava in the highlighted boxes. Might be useful in the Nether, but I don't think it's intentional.

**Comment by Zsashas** [comment]
Do they drop as if mined, or are they simply destroyed?

**Comment by OJwithC** [comment]
Just destroyed.
