### ISSUE TITLE
Potion effect persisted[Botania?]

### ISSUE THREAD

**Issue by Elvarion** [Vazkii/Botania#1261]
Botania r1.7-208

So I decided to Fight Gaia. Brew up some potions (Reg, Hp, Protection and Strength)
Fought Gaia but noticed that the icons for regeneration, protection and strength never left my inventory screen. They were there just flashing at 00:00. Didnt think of it much since a relog fixed this.

BUT, then I got into Blood Magic and created the Bound Blade and started killing every mob in 1 hit, dealing around 45 points of damage. Way way to much damage, since you actually need to kill mobs in 2 hits to get shards to progress. Went to singleplayer > Normal damage / Moved all the config + mobs to a new server > normal damage.

Removed my playerdata > normal damage.

So I opened up my playerdata with an NBT editor and found that under Attributes I still had a potion effect for damage boost. Ive only used the vials from Botania for potion effects, So im guessing I must have gotten the effect from there. But its only the strength that has persisted. And it ONLY effected the Bound Blade, every other weapon did normal damage. Found it pretty strange.

Id guess this is pretty hard to reproduce, but ill post it here just to say what happened.

Amount: 2,6
Name: potion.damageBoost 1
Operation: 2
UUIDLeast: -8449101711440750679
UUIDMost: 7245570952092733273
https://gyazo.com/eb2b98215cbcea29999a4c313ee4c34d

**Comment by Vazkii** [comment]
Doesn't really seem like something caused by botania. Try to see if you can reproduce it without other mods.

**Comment by Elvarion** [comment]
Did some tests and was unable to reproduce with only Botania installed.
This might be caused by [1.7.10]StatusEffectHUD-client-1.27, because on our previous server we didnt have that mod and Im pretty sure we had no issues with potion effects then.

If I find out anything else ill drop a note here.
Thanks for checking it out.
Keep modding, We love Botania!
