### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by blockbreaker1361** [Vazkii/Botania#1262]
I think that a really cool idea would be to have something like mana tanks. They would have the same GUI-less interface like the pools, but would hold something like 2x, 4x, 8x and 16x the mana of a standard pool. As always, I totally understand if you don't want to do this, but it would be soooo awesome if you did. :)

**Comment by MrKunji** [comment]
Not going to happen.

**Comment by phantamanta44** [comment]
There's always the Technomancy mana condenser.
