### ISSUE TITLE
Have withering flowers wither more explicitly

### ISSUE THREAD

**Issue by GTMelo** [Vazkii/Botania#1264]
Since the version that makes dayblooms and nightshades wither after a while, I've seem some people (myself included) mistaking this for a bug. (example: #1263). I think that the problem is that the plants simply disappear, leaving those who didn't read the entry in the latest versions confused.

Maybe it would help to make this withering more explict. Maybe having those plants turn into "dead flower" or something like this, that drops nothing (and with the added bonus of having the lexica point to what we were supposed to read anyway).

**Comment by MrKunji** [comment]
https://github.com/Vazkii/Botania/commit/b640d681ac2e907ae150f4fab18efa4c145ef468
Implemented half an hour before the issue :)

**Comment by GTMelo** [comment]
And I was all like "I'm helping!". Curse you Vaskii!!!
