### ISSUE TITLE
Spectral Platform crafting crash

### ISSUE THREAD

**Issue by itanshi** [Vazkii/Botania#1267]
First, the recipe doesn't show for me when I manually place the items. The crash occurs when you attempt to shift click the "?" recipe with NEI

Garden of Glass 1.0
Botania 208
Multiplayer and Single Player

http://pastebin.com/1LQNRjhB

**Comment by Vazkii** [comment]
Oh this again? :V

**Comment by itanshi** [comment]
Ok, the recipe did show when I had the right parts. So it can be crafted manually. I redid the test with the same result.
