### ISSUE TITLE
Unable to request Botania potions by name via Corporea Index

### ISSUE THREAD

**Issue by PsiGuy60** [Vazkii/Botania#1276]
Minecraft version: 1.7.10 (as if that needed explanation)
Mod version: Latest (R1.7-210)
Forge version: Latest 1.7.10 (10.13.4.1492)
OS: Arch Linux
Tested in single/multiplayer: Singleplayer.

Steps to reproduce:
1. Create a Corporea Index
2. Attach it to a network and add a chest.
3. Put any Botania potion in the chest.
4. Request said potion, via tab completion (in my case, Flask of Revitalization (6)), from the Index.
5. Crash, with message "Connection Lost, Illegal Characters in Chat"
6. Log back in and repeat request, this time typing the full name manually.
The item will not be given, and the Corporea Index will not see any of them in its network.

Suspected reason:
Special characters are being used to make the number 6 bold when tab-completion is used to get the item name. These characters are not allowed in chat and cause a crash. Furthermore, use of these characters makes it so the item name is not recognized when manually typed without including them.

Suggested fix:
Remove special characters from the names of potions.

**Comment by TheWhiteWolves** [comment]
[ItemBrewBase.getItemStackDisplayName](https://github.com/Vazkii/Botania/blob/master/src/main/java/vazkii/botania/common/item/brew/ItemBrewBase.java#L153)

The brews use EnumChatFormatting.BOLD, which is from base MC, don't know what that adds in there though.

**Comment by PsiGuy60** [comment]
I dunno either, I just know that:
1. Since I don't have any way of inserting a section symbol into chat (Linux, no compose key), I can't insert the section symbol needed for chat formatting manually.
2. The tab-completed version crashes my game for apparent illegal characters.
3. Typing the name of the item without the chat formatting stuff causes it to not be recognized.

**Comment by PsiGuy60** [comment]
I can't even type a section sign into chat, so...

**Comment by Vazkii** [comment]
This is all @soundlogic2236's fault :V

**Comment by PsiGuy60** [comment]
Confirmed fixed in version 211.
... Just in case I need to confirm.
Thanks!

**Comment by phantamanta44** [comment]
Pretty sure Vazkii tests her commits :v

**Comment by PsiGuy60** [comment]
Probably yes, but it doesn't hurt to have the person who submitted the issue also notify that it's fixed for them.
