### ISSUE TITLE
Bubbell creates a dome of air instead of a helix

### ISSUE THREAD

**Issue by flarn2006** [Vazkii/Botania#1281]
Helix is good. Dome is bad. It's not that hard to remember. Please fix this!

![Kappa](https://static-cdn.jtvnw.net/emoticons/v1/25/1.0)

**Comment by HyperionNexus** [comment]
Can you explain more of what this block/item is and how it was recreated?

**Comment by flarn2006** [comment]
Helix is love. Helix is life.

**Comment by Vazkii** [comment]
༼  つ ◕_◕ ༽つPRAISE HELIX༼ つ ◕_◕ ༽つ

**Comment by flarn2006** [comment]
![EleGiggle](https://static-cdn.jtvnw.net/emoticons/v1/4339/1.0)
