### ISSUE TITLE
Tiara's dash function rubberbands on multiplayer

### ISSUE THREAD

**Issue by OJwithC** [Vazkii/Botania#1282]
Botania v210

When I sprint while flying with the tiara on a server, it makes the "fwoosh" sounds and shows going forward for a moment, but takes you back to about 5 blocks ahead of where you were before dashing.

On a side note, gliding works wonderfully.

**Comment by HyperionNexus** [comment]
This also happens to me, it's very distracting sometimes.

**Comment by Vazkii** [comment]
Gah, this is a pain. Movement in multiplayer is horrible because most of the stuff is handled clientside. I'll see if I can find a way to fix it.

**Comment by OJwithC** [comment]
It works!
