### ISSUE TITLE
Force Relay Breaking

### ISSUE THREAD

**Issue by HyperionNexus** [Vazkii/Botania#1286]
Botania r1.7-210

First off, the video below shows two times where it gets broken, however the last one (end of the video) is the one that I'm reporting.

https://www.youtube.com/watch?v=MpdUvJ2xl8s

Now this might be because the block behind the one in front above have nowhere to go so it breaks either the one in front of it or the one that is getting pushed to accommodate for this. It would need a bit of re-writing of the block to make this not to happen and push the farthest first and then so on and so forth.

**Comment by Vazkii** [comment]
I can't fix this bug due to the way the force relays work.
