### ISSUE TITLE
custom inventory handling interface for corporea

### ISSUE THREAD

**Issue by ruifung** [Vazkii/Botania#1288]
This would allow other mods to write handlers for their own custom inventories, which can be difficult to translate to a IInventory

For example AE2, which doesn't even have a concept of a IInventory in its network at all, therefore slots don't make much sense there. 

It would be nice if the current IInventory handling code can be abstracted into a InventoryHandler interface.

**Comment by Vazkii** [comment]
Feel free to make a PR for this.
