### ISSUE TITLE
Allow rotation of Framed Livingwood/Dreamwood

### ISSUE THREAD

**Issue by ray10k** [Vazkii/Botania#1300]
The runes on framed Living/Dreamwood would make for great decorations along paths and floors, but right now the band on the top and bottom faces can only go east-to-west.
As a feature request, I would like to be able to rotate Framed wood, so the band can point north-to-south as well.

**Comment by Barhandar** [comment]
Vertical in addition to horizontal too, please. And if you do bother, even corners - through CTM.

**Comment by phantamanta44** [comment]
How about we CTM-ify everything instead of implementing rotation?
