### ISSUE TITLE
ATG and Botania : Already Decorating!! Crash

### ISSUE THREAD

**Issue by Milkyway3640** [Vazkii/Botania#1305]
Crash experienced on a vanilla forge server and kcauldron server running forge 1448.
Both crashlogs are from a vanilla forge server however.

[Crashlog with Fastcraft's "monitorBiomeDecorators" enabled](http://pastebin.com/pMp9V6m3)
[Crashlog with only Botania and ATG](http://pastebin.com/8mAufBxy)

**Comment by Saereth** [comment]
Just wanted to add to this, I help out on the server @Milkyway3640 runs and I seem to have gotten it to stop throwing this error.
in Botania.cfg

    # The size of each Botania flower patch. The larger this is the farther the each patch can spread
    I:worldgen.flower.patchSize=6

We had this turned up to 12 and it seems to be the culprit. Once we turned it back down to 6 the already decoration issues seem to have stopped (we're still pregenning but it's done over 1000 radius already without issue.

**Comment by Vazkii** [comment]
This possibly happens because large flower patches might end up going off the chunk, causing other chunks to generate while one is still busy. At least that's the only theory that comes to mind, I'll see if there's any way to fix it.
