### ISSUE TITLE
Can't craft Mekanism item because of Botania?

### ISSUE THREAD

**Issue by dominsbeard** [Vazkii/Botania#1308]
When trying to put a Mekanism Induction Casing into a crafting grid the game crashes. Only happens with Botania installed. I've also made an issue in the Mekanism repo because I'm not sure who this really belongs to. https://github.com/aidancbrady/Mekanism/issues/2930

http://pastebin.com/Xkdt39Rk

**Comment by kotoroshinoto** [comment]
I am also having this issue.

**Comment by kotoroshinoto** [comment]
There appears to be an open issue on their side about this: https://github.com/aidancbrady/Mekanism/issues/2938
