### ISSUE TITLE
Botania Greater Band of Mana dupe glitch

### ISSUE THREAD

**Issue by KingMidgey** [Vazkii/Botania#1309]
I think i found a dupe bug. i'm running the recommended version of forge, baubles and GoG. I am however running Botania R1.7 212. Even though I'm not running the latest version i decided that reporting this would be a good idea because i couldn't find the fix in the change logs. i'm not sure if it's problem with baubles or Botania but i was able to dupe a Greater band of mana by clicking on it and closing my inv. I haven't been able to replicate the bug. I was standing on a mana pool connected to a Terrestrial aglom plate with a spark. As well something i found strange is that the duped GBoM had 1000/1000 Durability rather than the 999/1000 durability one that I was carrying.
FML Log: http://pastebin.com/BBiuQ5EB
Edit: i forgot to say that when I took the GBoM out of the 1st ring slot (the 2nd out of the 4 slots(top/down)) a second appeared almost instantly.
Edit:Edit: the version of Baubles i'm using is Baubles-1.7.10-1.0.1.10 and i'm using Forge forge-1.7.10-10.13.4.1448-1.7.10-installer

**Comment by MrKunji** [comment]
Can confirm with a normal Band of Mana, but in my case I equipped it in the exact moment my Soujourner Sash was draining mana.
Results: two Bands of Mana, none of them was a ghost item.

**Comment by KingMidgey** [comment]
did that happen in the latest version?

**Comment by MrKunji** [comment]
I'm trying to reproduce that once again in the latest release, but it's hard.

**Comment by pjfranke** [comment]
Well now that I see this, it's making me thing I *didn't* accidentally key+click to creative dupe it in NEI Cheat mode.  After updating from 208 to 212, I'm pretty sure I had this happen too with a band of mana.  Possibly twice now, unless I didn't *actually* get rid of it the first time.

**Comment by akvgergo** [comment]
Found a (relatively) solid way to reproduce:
-Have something in your inventory that constantly uses mana (Globetrotter's sash seems to be the way to go, but managed to do it once with the Flügel tiara too)
-Have a ring in your upper ring slot (I used magnetization)
-Start spam clicking with the band of mana

This will quickly start swapping your two rings, and eventually you'll end up with 2 mana bands, and the other ring deleted.

**Comment by iTpyn** [comment]
"If you die with an equipped Band of Mana (Botania) and an equipped Sash of Sojourning or Sash of Globetrotting, you will respawn with an identically filled Band of Mana still equipped."
Posted by araneavalon at FTB Forums.
More detailed description of the bug:
http://forum.feed-the-beast.com/threads/1-8-2-1-11-2-item-duplication-in-botania.123185/

**Comment by simsonmeno** [comment]
I had similar problem:
When I quickly (probably within a tick) double shift clicked a ring of magnetization to swap it with a band of mana equipped in bauble ring slot the ring of magnetization disappeared and I head a second band of mana with the same durability.
It happened in singe player.
I could reproduce it more times.
Botania version 1.7-226
Baubles version 1.7.10-1.0.1.10
ps.:computer has problems keeping up with ticks

**Comment by wamphyrri** [comment]
I had the same issue with a normal band of mana. To reproduce, i opened the baubles screen, clicked the band of mana into the top ring slot, then shift clicked it out of the ring slot. I found the band had to be full, and I was wearing a soujourners sash and snow pendant thing also at the time. Every time I shift clicked it down to my inventory, it gave me a full band of mana (100/100 durability)

**Comment by TheWhiteWolves** [comment]
looks like if you change the ring at the exact same moment as something draws mana from it you can dupe the item, or in some cases replace the one its being swapped with, with a copy of the band.

**Comment by kutschkem** [comment]
After looking at the code, I suspect this bug happens when sending bauble sync packets in vazkii.botania.api.mana.ManaItemHandler. Maybe duplicate packets from different sources, or the packet is handled too late? I get this duplication bug regularly while using the openblocks gravestones. In that case, not only does the ring get duplicated, it stays with me after death without soulbound or anything. So I suspect the sync packet is handled after my death, or in the cases above, after the clicking down into the inventory.

**Comment by Darkosto** [comment]
Not sure if this is part of the same glitch, but I can reproduce duplicating the Band of Mana and the Greater Band of mana 100% of the time.

1. Have a band of mana in your first ring slot and a botania sash in the 3rd slot (You don't need anything else but could have inventory/armor and it will still work)
2. Die from wither damage and don't move around or have inventory open
3. You will respawn with the band of mana in your bauble slot while the rest of your items are in a grave or on the ground including the band of mana that dropped when you died

I managed to fill 5 mana pools in the span of 5 minutes with this duplication glitch.

I'm using 1.7.10 mc, forge 1614 and Botania r1.8-249

**Comment by williewillus** [comment]
1. That's due to Baubles being coded (and still being coded as of 1.9/10) in a completely broken way. It's bad.
2. 1.7.10 Botania isn't being maintained
