### ISSUE TITLE
Idea: fuzzy filtering functionality for the Hopperhock

### ISSUE THREAD

**Issue by desht** [Vazkii/Botania#1310]
Right now, the only filtering which can be done for the hopperhock is to either white- or blacklist precise items (ID + metadata) in item frames.

While I know this has been changed for non-stackable items, it would be really nice if there were some kind of upgrade (sidegrade?) to the hopperhock to allow more general fuzzy functionality: matching only on the item ID, not the metadata - e.g. pick up all wool regardless of colour.  Such fuzzy functionality could come with a more expensive recipe and/or an increased mana cost?

**Comment by Vazkii** [comment]
It ignores the damage in anything that actually takes damage and doesn't use it for sub-items. There will be no option to change the search mode because botania does not rely on metaconcepts of ID, metadata or NBT to be played properly.

**Comment by desht** [comment]
Fair enough!
