### ISSUE TITLE
Flugel Tiara HUD not visible with Blood Arsenal & TiC installed

### ISSUE THREAD

**Issue by thephoenixlodge** [Vazkii/Botania#1314]
I noticed while working on development of Regrowth that the HUD flight bar for the Flugel Tiara wasn't rendering. As such I went about disabling mods until I determined which mod was causing it.
Initial testing indicated it to be related to Blood Arsenal, but having only Botania, Blood Magic (required for BA) and Blood Arsenal installed the flight bar rendered fine.
I have since managed to narrow it down to the flight bar only not rendering when both Tinker's Construct and Blood Arsenal are installed. With only one or the other the bar renders fine, but when both installed it does not.
I also tested having them both installed with Blood Arsenal's TiC integration disabled in the BA config and the bar still failed to render.
May be related to https://github.com/Vazkii/Botania/issues/1273 ?

Forge 10.13.4.1448-1.7.10
Botania r1.7-215
Blood Magic 1.3.3-13
Blood Arsenal 1.1-14
Mantle 0.3.2.jenkins184
Tinker's Construct 1.8.7

FML Log: http://paste.ee/p/ziZqz

**Comment by Vazkii** [comment]
@Arcaratus, do you do anything with rendering? I couldn't find any rendering hooks in your repo.

**Comment by Arcaratus** [comment]
My mod does not do anything with HUD's; it could be Blood Magic or TiC

**Comment by Vazkii** [comment]
Does the bar work with Blood Magic and not Blood Arsenal?

**Comment by thephoenixlodge** [comment]
Yes, as soon as either TiC or Blood Arsenal are removed the bar shows back up

**Comment by Vazkii** [comment]
I'm gonna page @bonii-xx and @TheWhiteWolves to see if they know anything about this.

**Comment by TheWhiteWolves** [comment]
Doesn't look to be a problem with TCon and Botania as its working fine with TCon 1.8.7 and Mantle 1.3.2a, ill take a look at BM next

**Comment by TheWhiteWolves** [comment]
Right what I've found is that its something going on with Blood Arsenal and Tinkers, HUD renders fine with different combinations of Botania, Blood Magic and Tinkers but once Blood Arsensal is added along with Tinkers it breaks the rendering.

Blood Arsenal works fine with Botania on it's own, so I'd say its not something on our end that's causing it.

A note for @bonii-xx and @Arcaratus when looking into it, rendering works fine in the dev environment but breaks in the live versions.

**Comment by bonii-xx** [comment]
Apparently TiC cancels the RenderGameOverlayEvent.Pre event with type HEALTH. I don't know why.

**Comment by TheWhiteWolves** [comment]
That'll prob be why when I moved the Botania side of stuff the RenderGameOverlayEvent.Pre from the .Post event it fixed it on our side.

Would stopping the cancelling of the event on your side break things for you?

**Comment by bonii-xx** [comment]
I have no idea, but there most likely wont be any further updates for the current TCon version so it's best to work around it

**Comment by TheWhiteWolves** [comment]
Mind giving it a try? and if it works just dropping a final stealth hotfix, if not I guess it'll just have to go on the list on known things.

**Comment by bonii-xx** [comment]
I don't really have the time to support such changes. But you can simply increase the priority of your event handler, that way it'll always be handled before Tcon, no matter the load order.
