### ISSUE TITLE
Flare Chakram turns back into Thorn Chakram upon catching

### ISSUE THREAD

**Issue by PsiGuy60** [Vazkii/Botania#1315]
Botania version: Latest (215).
Forge Version: Latest 1.7.10 (10.13.4.1492).
Minecraft Version: Do I really need to say it?

Steps to reproduce:
1. Create Thorn Chakram.
2. Turn them into Flare Chakram via crafting.
3. Throw all of them randomly to see what it looks like when thrown (the fire particles are a nice touch by the way).
4. Catch them.

The Chakram will revert to regular Thorn Chakram when returned to the inventory.

**Comment by Vazkii** [comment]
Derp :p
