### ISSUE TITLE
Ring of Magnetism Persisting

### ISSUE THREAD

**Issue by Givemeyourgits** [Vazkii/Botania#1319]
I used to use Ring of Magnetism, but I stopped wearing it as it caused too much problems in my base with pulling things it shouldn't.  

I have had it off for a long time, and now all of a sudden I have the effect again and it is breaking some machines that require dropped items.  

I am not 100% sure it is Botania, but it is the only thing that has that effect I know of.  I tried taking off all my armor and items but I can get rid of the effect.

What's weird is I haven't worn it in a while but now I'm stuck with the effect.

**Comment by Givemeyourgits** [comment]
I removed all my items and put them in a chest, then I deleted my character files on the server thinking this would clear the effect.  When I logged back in and created a new character file I still had the effect.  I tried looking in MCEdit on my character to see if there is any flag that might be set on my player but I couldn't find anything.

I have multiple things that depend on dropping items and it just keeps pulling things away (like making terrasteel, feeding endoflames and so on).

**Comment by TheWhiteWolves** [comment]
Try putting down a solegnolia, if its the ring causing it this should stop the effect near it, if its not the ring making this happen then it should make no difference when near the solegnolia.

Tell us what happens after u do this please.

**Comment by Givemeyourgits** [comment]
Just tried it, I was standing about 4-5 blocks away from the flower (and confirmed it had particles) and it still did it.

Just to be clear, I have no ring on, I stopped wearing it.  I think residual effect from the ring as I can't think of anything else causing it.  What's weird I stopped using it a week or so ago and all of a sudden the effect came back out of no where.

**Comment by Vazkii** [comment]
Please read the [contributing guidelines](https://github.com/Vazkii/Botania/blob/master/contributing.md) before posting an issue. Your issue is either missing critical information or going against one of the guidelines there stipulated.
I'm closing this issue until it's rectified to follow the guidelines. You can comment on closed issues.
*This message is a macro.*
