### ISSUE TITLE
(Bug) Snowflake Pendant entry not working

### ISSUE THREAD

**Issue by Schluck123** [Vazkii/Botania#1321]
![2015-08-29_13 17 37](https://cloud.githubusercontent.com/assets/14033785/9564135/e869bfb8-4e50-11e5-9d48-87f12c96c149.png)

Snowflake Pendant entry is missing a icon, and when clicked on it goes back to the Lexica Main Menu
Version 217

**Comment by Schluck123** [comment]
Snowflake Pendant entry is missing a icon, and when clicked on it goes back to the Lexica Main Menu

**Comment by MrKunji** [comment]
Can confirm
