### ISSUE TITLE
Cocoon of Caprice has no texture in inventory (again)

### ISSUE THREAD

**Issue by liftoff** [Vazkii/Botania#1325]
Running build 217 and the Coccon of Caprice is missing its texture:

![Cocoon of Caprice Missing Texture](http://i.imgur.com/aPM5qGj.png)

I know this came up once before in the past (issue #1211) but it's been long enough that I suspect it warrants a new report.

Hardware info: Running Intel HD4000 Graphics in Kubuntu Linux 15.04

**Comment by phantamanta44** [comment]
The mana prism doesn't have an icon either, but that might be a different issue.

**Comment by Vazkii** [comment]
Oh god, this again ._.

**Comment by Barhandar** [comment]
It's technically not even missing, NEI shows the cocoon being about one and a half squares to the left of where it _should_ be. Oh, and even that disappears on mouseover.

**Comment by natedogith1** [comment]
I'm having this issue in 233, with nothing but Botania and Baubles. What can I give to help with this?

**Comment by Vazkii** [comment]
Send the context menu (CTRL+SHIFT in the F3 menu)

**Comment by natedogith1** [comment]
![2015-11-16_13 33 53](https://cloud.githubusercontent.com/assets/1638163/11191069/4c59ab6a-8c67-11e5-9f70-66e0e52a819d.png)

**Comment by Vazkii** [comment]
How does it look on an item frame?

**Comment by Xilef11** [comment]
it dosen't appear in the Item frame either. (this is the Botania pack)
![2015-11-16_14 28 48](https://cloud.githubusercontent.com/assets/8212678/11192327/8b21e93c-8c6e-11e5-8602-deb0f60c1982.png)

**Comment by Vazkii** [comment]
Try putting it with glass behind it. It's possible it's getting poorly translated for some reason.

**Comment by Xilef11** [comment]
Nothing either (fast graphics)
