### ISSUE TITLE
Ring of Magnetism Persisting

### ISSUE THREAD

**Issue by Givemeyourgits** [Vazkii/Botania#1327]
I don't know what I did when i posted it before, I read the guidelines.  I added [Bug] Tag and added more information about what I'm using and tested latest version of Botania.

I manually updated Botania to r1.7-218 and the problem persists.

I seem to have a ring of magnetism effect on my character that is persisting past taking the ring off and putting it in a ME system.  I deleted my character profile files in on my server and started a new character and it is still stuck to my character (other player on server does not have problem, but never used ring of magnetism).  

I tried dropping a Solegnolia but it did not stop the effect.  Which would lend itself to think it wasn't the ring or left over effects of it, but nothing else causes this effect that I have seen and it only happens to the one person who used the ring in the past (me).

I am using Inifinity 1.10.1, I am not running Optifine.
Fml log file: https://dl.dropboxusercontent.com/u/5143353/log.txt

**Comment by Vazkii** [comment]
How do you know it's the botania ring and not some other?

**Comment by Givemeyourgits** [comment]
I don't, but it is the same effect I had when I wore the ring, and nothing else has created that effect for me in the past.  I was the only one wearing the ring for a while (I stopped about a week ago because the effect was causing too many problems around town and I kept forgetting to take off) and I am only one having the problem.

**Comment by Vazkii** [comment]
Are you sure you didn't just leave NEI's magnet mode enabled by accident or something?

**Comment by Givemeyourgits** [comment]
Thanks!! That was it.  I've never used that feature and not sure how it got toggled on.
