### ISSUE TITLE
Corporea funnel not updating comparators on hoppers

### ISSUE THREAD

**Issue by Abacor** [Vazkii/Botania#1328]
Place a working corporea funnel one or two blocks above an empty hopper. Place a comparator coming out of the hopper. Trigger the funnel.

Expected result:
- An item ends up in the hopper
- The comparator turns on

Actual result 
- An item ends up in the hopper
- The comparator stays off
- The comparator is now a BUD. Any block updates around it cause it to turn on

Oddly this only happens with hoppers. The comparator works as expected if you replace the hopper with a chest, dropper or dispenser.

R1.7 217

**Comment by Vazkii** [comment]
I might actually leave that in the game as it seems like a pretty interesting concept.

**Comment by Abacor** [comment]
I like the idea of having a Botania based BUD, but I think a dedicated and documented block which doesn't depend on implementation gitches would be a better way to do it.

On the other hand this was easy to workaround once I debugged the behaviour. Just put another hopper between the funnel and comparator'ed hopper. So if you do decide to leave this behaviour in there's no real harm done to any redstone contraptions, they just get a little bigger.
