### ISSUE TITLE
Dire Slimes from EnderZoo spawning when using the Terra Shatterer

### ISSUE THREAD

**Issue by cauliflower69** [Vazkii/Botania#1336]
I'm not sure if this is intended or not but the Terra Shatterer spawns a crazy amount of dire slimes as it isn't registering as a shovel 

Apparently you can fix this by adding 

@Override
public Set<String> getToolClasses(ItemStack stack) {
  Set<String> set = Sets.newHashSet("pickaxe");
  if(whatever) {
    set.add("shovel");
  }
  if(whatever) {
    set.add("axe");
  }
  return set;
}

**Comment by TheWhiteWolves** [comment]
Well the Terra Shatterer is a pick and is not an axe or shovel, so probably not going to change.

Your solution would be to actually use a shovel instead of a pick for whatever you are doing

**Comment by cauliflower69** [comment]
The main problem with this is there would be little to no point in trying to upgrade the shatterer. Can you disable the insta break of dirt then ?

**Comment by phantamanta44** [comment]
Use a stone of temperance if you're really concerned.

**Comment by cauliflower69** [comment]
As the TS is a pick how come it instantly mines dirt then ?

**Comment by TheWhiteWolves** [comment]
on which blocks is it insta mining dirt, the one u mine or on one of the ones in its expanded breaking range

**Comment by cauliflower69** [comment]
The blocks in its expanded range. If this could be disabled then it would be perfect as you previously stated its a pick axe so shouldn't be behaving like that

**Comment by TheWhiteWolves** [comment]
The way things work at the moment, the expanded range blocks do not break blocks as if broken by a tool, it just breaks the blocks.

This would require abit of rewriting so for the moment prob not going to change as its a low priority and its only a minor capability thing.
