### ISSUE TITLE
Idea : Terra Shatterer placement box 

### ISSUE THREAD

**Issue by cauliflower69** [Vazkii/Botania#1337]
I am an admin on a busy whitelisted server and on occasion we have to use commands like xu_killitems to clear someones messy setup. 

This causes the Terra Shatterer to also be removed. You can imagine the annoyance of losing your S nearly SS TS. 

Maybe if you could place it in a container whilst charging it would alleviate the issue

**Comment by yrsegal** [comment]
The issue is with the fact that you have to kill items. perhaps limit total items on the server?

**Comment by bookerthegeek** [comment]
That is not really an option for bigger (or even small top medium) sized servers, unless of course @yrsegal you have an easy forge based way of doing what your suggesting?

**Comment by Zsashas** [comment]
Or, you know, broadcast an announcement that you're going to use the command. If it's YOUR Terra Shatterer, then just pick it up first. 
Alternately, if you have ClearLag, is has a /lagg area command for destroying all entities in a specified radius instead of simply everything.
