### ISSUE TITLE
Idea: Placing Mana Spreaders on the side of the Spreader Turntable and supporting multiple Mana Spreaders

### ISSUE THREAD

**Issue by liftoff** [Vazkii/Botania#1342]
This may sound strange but I'd like for the ability to put a Mana Spreader on the side of the Spreader Turntable so I can have 360 degrees of rotation on the Y axis.  I'd also like the ability to stack multiple Mana Spreaders on top of the Spreader Turntable so I can have, say, 7-8 blocks worth of Mana Spreaders firing in a line around whatever axis they're on.

For reference, I'm envisioning a more efficient (in terms of resources) tree farm with Mana Spreaders in the center and trees planted all around in a circle.  I think it might push people over the edge to start actually using the Spreader Turntable!

**Comment by Dakedres** [comment]
Why was this marked as completed? As far as I can tell, spreader turntables still can't rotate spreaders up or down?
