### ISSUE TITLE
Spellbinding Cloth get damaged when put into crafting table

### ISSUE THREAD

**Issue by Speiger** [Vazkii/Botania#1343]
https://youtu.be/Af8lVK-KGBs?t=23m27s

That shows as soon Vaygrim puts that item it gains damage. Is that normal or is that a bug?
Would be interesting to know. (ForgeCraft Version of Botania)

**Comment by OJwithC** [comment]
For reference, it occurs around 23:25.

**Comment by Speiger** [comment]
@Vazkii did you solve it?

**Comment by Vazkii** [comment]
This seems like a desync, not a bug.

**Comment by Speiger** [comment]
with a vanilla handled recipe? Is forgecraft that unstable?
