### ISSUE TITLE
Suggestion: Auto-convert tall mystical flowers to mystical when put into flower pouch

### ISSUE THREAD

**Issue by p455w0rd** [Vazkii/Botania#1346]
That or maybe a bigger pouch inventory that includes spaces for the tall flowers?

**Comment by TheWhiteWolves** [comment]
That would defeat the purpose of tall flowers, which is to give you 4 petals per flower instead of 2

**Comment by p455w0rd** [comment]
And that defeats the purpose in what way??? Having a pouch for regular flowers but not for tall defeats the purpose of the pouch which would is flowers taking less inventory space. Do you even think before you type?

**Comment by Vazkii** [comment]
You're getting banned for disrespectful behaviour. Sorry but I do not tolerate this type of nonsense.
