### ISSUE TITLE
Some rebalance

### ISSUE THREAD

**Issue by AscalTheBest** [Vazkii/Botania#1351]
Gaia is too easy while fighting with friends. I'll introduce some ideas to make it harder and more interesting. First, about Gaia's HP. You can remove Gaia II, III, DCMXIV... And calculate it's HP by simple formula. "%player HP% * %player attack% * (1 + %player protection% / 100)" Two examples of how formula working: we've got player with 60 HP (TiC HP canisters), 20 HP attack sword and 35 protection points (not PP :P), so Gaia will spawn with 60*20*1,35=1620 HP; we've got player with 20 HP, 5 HP attack and 0 protection points, so Gaia will spawn with 20*5*1=100 HP. If player has more, than one weapon and one armor set, formula chooses most powerful weapon or/and armor set. If player has more, than one TYPE of weapon, formula chooses most powerful weapons from each type, sums its' attack and divides by weapon type count, received value will be used as player attack. Second, fighting with friends. If there are more than one player summons the Gaia, formula will be like that: "(%sum of players' HP% / %players count%) * (%sum of players' attack% / %players count%) * (1 + (%sum of players' protection points% / %players count%) / 100)". Amount of loot will be varied from players count and Gaia HP. And you can write some formulas for Gaia abilities, attack, protection and phases. I hope to see this in the mod =)

P.S. Sorry for my english, if it's bad =)

**Comment by phantamanta44** [comment]
I'm pretty sure the gaia guardian already has scaling difficulty based on player count...?
