### ISSUE TITLE
Mana in a Bottle

### ISSUE THREAD

**Issue by dt8884** [Vazkii/Botania#1362]
Today was the first day I decided to test Mana in a Bottle.  One of the first things that happened was I got a water block at my feet.  I was curious if the code to spawn that in would apply to water in the nether.  It took a few tries and using Mana in a Bottle in the nether has a couple really interesting things that can happen.

It shot me super high into the air... and I landed on top of the bedrock ceiling of the nether; all of my items were ejected from my inventory; and a water block did indeed spawn at my feet, and stayed.

The one that ejected my inventory was even more interesting.  My chest, legs, and feet (all enchanted terrasteel) along with my enchanted Thundercaller immediately dissapeared.  I was able to pick everything else back up.  There was no fire or lava nearby.  A second thing to note was that none of my equipped Baubles were ejected, they all stayed on my person.

Edit: Note that I tested placing water in the nether with a bucket and with the Rod of the Seas so it isn't something another mod is allowing.

**Comment by dt8884** [comment]
I solved the mystery of the disappearing items.  A Zombie Pigman had picked them up.  I noticed when one was sporting a Thundercaller instead of a diamond sword.

The nether shooting me onto the roof and water in the nether are still probably unexpected side effects.

**Comment by Nagapito** [comment]
I might be misreading the code but didnt you forgot to check for the hell dimension in case 9?

**Comment by dt8884** [comment]
I just realized that the issue with ejecting items not ejecting equipped baubles was skipped, but not obviously stated on my part.  Definitely a minor but, if at all.
