### ISSUE TITLE
Resolute Ivy not attaching to items

### ISSUE THREAD

**Issue by dt8884** [Vazkii/Botania#1363]
Resolute Ivy won't attach to a few items.

Rod of the Bifrost - It just doesn't attach.

Black Hole Talisman - It won't attach if there are any items in it.  It attaches if it is empty regardless if the Talisman is Active/Inactive or if it is bound to an item or not.

Mana Blaster that has a lens attached.  If there is a Lens Clip connected, it only won't attach if there is a lens in the currently selected slot.

The Black Hole Talisman and Mana Blaster seem related as putting either into a grid already has a recipe (ie giving back the lens or giving a stack of what the talisman is holding).  It's easy enough to work around the Mana Blaster since detaching and attaching lenses is so simple.  The Black Hole Talisman with 80k Cobblestone in it isn't nearly as simple to empty, attach the ivy, and refill it.

**Comment by MrKunji** [comment]
It doesn't attach to items that are return from a crafting recipe to prevent dupes.

**Comment by dt8884** [comment]
Which makes sense, but there should be a way to script around letting that dupe.  Because of the theme between the Mana Blaster and the Black Hole Talisman, I wouldn't have created this ticket just for them.  It seemed like it might have been done on purpose.  The Rod of the Bifrost, however, doesn't make sense why it won't attach with Resolute Ivy.

**Comment by OJwithC** [comment]
You can make the bifrost blocks with it now.

**Comment by dt8884** [comment]
So is it intended to never be able to attach Resolute Ivy to a Rod of the Bifrost?  Unlike the other 2 items, there are no workarounds like removing the lense or emptying the talisman.

**Comment by Vazkii** [comment]
The Resolute Ivy does not attach to anything that returns an item upon being crafted, no exceptions.
