### ISSUE TITLE
Suggestion: Tall Flower pouch support

### ISSUE THREAD

**Issue by Zsashas** [Vazkii/Botania#1371]
I can think of three ways to make this work:
1: Add an additional set of slots in the pouch for Tall Flowers
2: A second pouch for them
3: A way to convert one Tall Flower into two normal ones

**Comment by OJwithC** [comment]
Definitely not the third (since bonemealing small flowers make big ones).

**Comment by Zsashas** [comment]
Oh it does? Cool. Never tried that. I have it set in my pack to like 90% tall flowers.

**Comment by Zsashas** [comment]
Perhaps an alternate version of the pouch for holding the petals, or maybe the floral dyes, then? Chromatic Satchel? Petal Pouch?
