### ISSUE TITLE
Soujourner and Globetrotter's sash don't give step assist

### ISSUE THREAD

**Issue by Azruine** [Vazkii/Botania#1372]
Occurs with fantastic fish mod
URL : http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/1443050-wip-1-7-10forge-fantastic-fish-alpha-v1-4

Using
Minecraft 1.7.10
Forge 1481
botania r1.7-221
fantastic fish 1.4

**Comment by PsiGuy60** [comment]
Does it occur with just Botania, or is it only with Fantastic Fish installed?

**Comment by Azruine** [comment]
Only with fantastic fish mod. I've reported this problem to that mod's author too.
