### ISSUE TITLE
Suggestion: Thaumcraft Integration: Warp

### ISSUE THREAD

**Issue by Zsashas** [Vazkii/Botania#1374]
I know that the Wrap thing isn't serious, but maybe there could be a config option (set to false by default) that makes certain items give Warp when crafted? Always a very low amount, of course.
Some possible Warp-inducing items:

Soulscribe
Heisei Dream
Bellthorne
Dreadthorne
Vinculotus
Cocoon of Caprice
Hand of Ender
Black Hole Talisman
Cloak of Sin

Also sorry if this isn't the best place for suggestions, if there is a better place please let me know.

**Comment by MrKunji** [comment]
They don't even use Thaumcraft's resources to be crafted, would not make sense to inflict Warp.

**Comment by Zsashas** [comment]
Alright fair enough. Honestly didn't even think about that aspect of it. :P

**Comment by phantamanta44** [comment]
Warp is loss of sanity, and Botania is supposed to be a peaceful/natural mod. If anything in this mod might cause sanity loss, the somebody did something wrong.

**Comment by Zsashas** [comment]
Well I was thinking of items that have a more harmful or "eldritch" effect. Also this is why you don't make suggestions at 3am lol.
