### ISSUE TITLE
Suggestion: Decayed Dayblooms/Hydrangeas

### ISSUE THREAD

**Issue by eslachance** [Vazkii/Botania#1376]
So, I myself (and others here, apparently) have wondered why their dayblooms were simply disappearing from the world for no apparent reason. Some, like me, just didn't realize that decay had been added. Others just don't read the Lexica Botania (who RTFM anyways, right?) or don't notice the paragraph on decay.

Anyways, here's my suggestion: visually show that the flower has decayed, instead of simply making it disappear. A shriveled up, dead-looking flower is probably more of an indicator of decay than an empty space. Perhaps I could go as far as to suggest the ability to restore the flowers by throwing them in a mana pool (spending more mana than originally from the petals, but saving the crafting operation)? Or do some darker magic with them later on, I don't know :)

**Comment by OJwithC** [comment]
Passive flowers have decayed into dead bushes since v209.

**Comment by riskable** [comment]
I wish to second this suggestion.  A lot of folks following the old tutorials on Botania will think something is broken in their world, will read about chunkloading issues in the Changelog, and think they just got unlucky.  I've seen that exact scenario play out exactly as described.

A withered flower where the old one stood is the perfect solution to the problem.  I would also suggest making a shift-right-click with the Lexica Botania bring up a page specifically about withered flowers.

**Comment by MrKunji** [comment]
@riskable, there is already info about flower decay in the Daybloom/Nightshade/Hydroangeas entry, and the changelog does provide details (such as flowers being replaced with bushes after withering), the players should just read ;)

**Comment by riskable** [comment]
@MrKunji I agree that folks should "just read" but the notes about decaying flowers in the changelog come *after* loads of notes about fixing chunkloading issues.  Also, for a lot of folks it's not a matter of "reading" the Lexica Botania it's a matter of *re-reading*.  As in, they read it once a while back and are now picking up Botania again for, say, Garden of Glass.  So for them to understand what's going on with the passive flowers they would have to read the book all over again.
