### ISSUE TITLE
Crash whule crafting with CS3 items and Botania

### ISSUE THREAD

**Issue by teamMK** [Vazkii/Botania#1377]
Hi,

with Botania above 208 version, minecraft is crashing when i try to craft something with my custom stuff 3 items

http://pastebin.com/cEV2P8Wd

Maybe its CS3 related, but i cant find CubeX2's issue tracker, but maybe u guys can fix something. Thanks :-)

**Comment by Vazkii** [comment]
Send me your item files please.

**Comment by teamMK** [comment]
Cs3 has no real item files, it has its own ingame manager, but i uploaded the data dumpfile

http://pastebin.com/tg0p8kjH

The recipies are managed with newest minetweaker 3 and modtweaker versions.

**Comment by Vazkii** [comment]
Yeah, this doesn't look like a botania issue.
