### ISSUE TITLE
Runic Altar issue preventing automation (not ejecting runes off the altar)

### ISSUE THREAD

**Issue by riskable** [Vazkii/Botania#1379]
I've created this awesome build for fully automating the Runic Altar but I've run into a problem:  Sometimes the runes don't get fully ejected from the altar.  This results in the just-crafted runes (or just one or two) being added to the altar as potential crafting ingredients before Hopperhocks can pick them all up.  I've tried a few workarounds to this issue:

1) Making sure there's only ever one piece of Livingrock on top of the altar (in case I was hitting some sort of max pickup limit for Hopperhocks).  I also tried using multiple Hopperhocks; that didn't work either.
2) I tried using a Daffomill to blow the runes off the top of the altar before they get re-added as crafting ingredients but this screws up the next recipe being dropped onto the altar by blowing away the first ingredient (assuming the Daffomill is being enabled/disabled via a Comparator signal of 2 coming off the Runic Altar).  I'm still trying to figure out a way to make this work without adding zillions of Redstone Repeaters to delay starting the next crafting/drop cycle but I haven't had much success.

I've created a video that very clearly illustrates the problem here:

https://youtu.be/R8h7vIWtpFc

If you just want to see the issue as it occurs (don't need to listen to me describe the setup) you can skip to 1:19:

https://youtu.be/R8h7vIWtpFc?t=1m19s

**Comment by riskable** [comment]
Just an update on some of the other things I've tried:

* Offsetting the open crate above the altar in order to allow the Daffomill to be constantly blowing failed.  Sometimes the ingredients won't land on the altar or the altar takes too long to pick them up resulting in them blowing off.  Another problem with this method is that sometimes the altar throws the freshly-created runes in the direction of the Daffomill which ends up blowing them back on to the altar.
* I tried using the Influence Lens to fire a mana burst over the altar after the comparator signal reaches 2 but this often results with the next ingredient being blown off the altar before it picks it up.

...still trying out all sorts of designs with self-resetting Redstone latches and timers but so far nothing has turned out to be reliable.

**Comment by riskable** [comment]
Update:  I got it working despite this issue!  I will be posting a video soon with the details.  Having said that I do believe that there should be a mechanism in place to ensure that generated runes don't end up back in the altar on their own.  That would reduce the complexity of my build considerably.

**Comment by Zsashas** [comment]
This is very odd...I've often had the runes sitting on the altar after crafting, and it's never picked them back up again.

**Comment by Vazkii** [comment]
This is intended behaviour, if you notice, after you craft a rune the altar gets a bit of smoke on it. During that time it won't pick up items.
