### ISSUE TITLE
Missing features? Build 221 - Enchanting with mana

### ISSUE THREAD

**Issue by tjsd** [Vazkii/Botania#1383]
Hello there!
I can not get the crystal bow to get the looting III enchant using the mana enchanter.

It will not accept Hoes for unbreaking III enchant. I cant put diamond hoes or thermal foundation hoes on the enchanter.

**Comment by OJwithC** [comment]
That's to be expected. Bows cannot have the looting enchantment, only swords. Hoes cannot be enchanted in a table; unbreaking can only be applied via anvil.

**Comment by Zsashas** [comment]
What do you mean hoes can't be enchanted in a table? I've enchanted hoes several times before in an Enchanting Table.

**Comment by Vazkii** [comment]
The mana enchanter only does primary enchants.

**Comment by OJwithC** [comment]
Zsashas: I'm going off of what the wiki says and my own foggy memory of trying to enchant a hoe and it not entering the table. I'm saying the only enchant a hoe can normally receive is unbreaking, but has to be via anvil.
"A hoe can receive the following enchantment, but only through an anvil:

Unbreaking"
