### ISSUE TITLE
Warp Lens not working correctly in multiplayer

### ISSUE THREAD

**Issue by Seiklus** [Vazkii/Botania#1385]
In multiplayer, a burst modified with a warp lens does not teleport when hitting a force relay, even when the force relay has been bound to a block.

example:
https://gfycat.com/FormalLavishHoopoe

I bound the force relay multiple times, but it had no effect. the relay properly pushes the block when moved by a piston, but no mana is teleported through it.

modlist:
http://pastebin.com/S1dXLDXL

no errors were posted to the log of the server, nor to the client.

**Comment by OJwithC** [comment]
From what I see in the gif, it should be working. Since you only bound it to blocks in the floor, the beam would come out the block opposite the side of the relay it went into. It would dissipate because it hits a non-mana-container. Try clearing out the blocks in a 3x3 after binding to a block?

**Comment by Seiklus** [comment]
Sorry about the confusion for clarification, i bound the dirt block next to the  relay... theres no visual indication of that.
