### ISSUE TITLE
Magic Missile Crash

### ISSUE THREAD

**Issue by CandiceJoy** [Vazkii/Botania#1386]
I'm not sure if this is actually Botania's fault or not, but it's the only mod in the stacktrace.  Someone was fighting a Gaia 2 with an Enderium Rapier (in the mob spawning phase) when the server crashed and was thrown into limbo (I had to manually stop then start the server; normally it restarts automagically).  Upon restart it works fine.  Here is the generated crash report: http://pastebin.com/DXV9VUB3

**Comment by Vazkii** [comment]
This seems like a bug in one of the CoFH mods.
