### ISSUE TITLE
Suggestion: Cosmetic Passive Generating Flowers

### ISSUE THREAD

**Issue by Zsashas** [Vazkii/Botania#1388]
With the whole decay functionality, Dayblooms, Hydroangeas, and Nightshades don't last very long. However, they do look nice in the proper set up. Perhaps have a separate purely cosmetic version of each flower that does absolutely nothing but look pretty, and won't die after a certain amount of time. And hey, why stop with just the passive flowers?

**Comment by Sentenryu** [comment]
That could be made like the Glimmering Flowers, combine the flower with an item on a crafting table and get a version that does nothing.

**Comment by Zsashas** [comment]
That's more or less what I was thinking of.
