### ISSUE TITLE
Arrow missing when inspecting a mana pool

### ISSUE THREAD

**Issue by Rasmun** [Vazkii/Botania#1392]
When I inspect a mana pool with the Wand of the Forest, I see the mana tablet and mana pool overlay, but there is no directional arrow indicating if mana will be inserted or extracted into/from the tablet.  Is there anything I can do to resolve this, or is this a defect?

![botania - missing arrow](https://cloud.githubusercontent.com/assets/14100145/9947841/54b99070-5d52-11e5-9d20-e1fadb2228ed.JPG)

Versions:
Direwolf20 1.6.1
Minecraft 1.7.10
Botania r1.7-221.jar  (updated to this version after seeing the problem in an older version)

Thanks!

**Comment by MrKunji** [comment]
It's not Botania's fault, ask the creators of the resource pack to include the arrow texture.

**Comment by Rasmun** [comment]
I will.  Thanks MrKunja
