### ISSUE TITLE
Redstone Mana Spreaders stop firing after a while of using the Bounce Lens

### ISSUE THREAD

**Issue by riskable** [Vazkii/Botania#1393]
So I'm building this *epic* pre-Alfheim tree farm that uses the Weight Lens to drop tree wood onto torches.  It works by detecting if a tree has grown using the Bounce Lens.  The problem I'm having is that if a mana burst from a Redstone Mana Spreader bounces back into it's adjacent Mana Pool a few times that Redstone Mana Spreader will stop working entirely until you re-bind it.

It's hard to illustrate with screenshots so I've made a ~1 minute video demonstrating the problem:

https://youtu.be/X7Gw-PjBo7A

It's not supposed to do that, right?  :smile:

**Comment by Vazkii** [comment]
This actually isn't a bug. A spreader won't take mana from the pool it's bound to, because that's logical. Putting a block that would redirect the mana to the same pool the spreader is pulling from will cause it to turn into the target, so it won't pull mana from it.

**Comment by Vazkii** [comment]
This should work out for you: https://github.com/Vazkii/Botania/commit/60098d3ede23b86d8b6c57841144185fce1af0c3
