### ISSUE TITLE
[Bug] Warp lens without bore not teleporting mana burst

### ISSUE THREAD

**Issue by Gragnar** [Vazkii/Botania#1395]
As the title says. The same setup with a bore+warp lens will teleport mana but with only a warp lens, the mana spreader doesn't shoot a burst at all.

Warp lens:
![2015-09-19_13 14 27](https://cloud.githubusercontent.com/assets/7951011/9977330/dce727c6-5ed0-11e5-910a-d51f8f6dee0b.png)
Bore+warp lens:
![2015-09-19_13 14 43](https://cloud.githubusercontent.com/assets/7951011/9977331/df79b044-5ed0-11e5-8f4a-111b13d89e93.png)

List of mods:

AppleCore-mc1.7.10-1.1.0
Aroma1997Core-1.7.10-1.0.2.15
AromaBackup-1.7.10-0.0.0.5
Atum-1.7.10-0.6.60
backpack-2.0.0-1.7.x
Baubles-1.7.10-1.0.1.10
BiblioCraft[v1.10.5][MC1.7.10
BiblioWoods[BiomesOPlenty][v1.9
BiblioWoods[Natura][v1.5
BiomesOPlenty-1.7.10-2.1.0.1067-universal
Botania r1.7-221
Carpenter's Blocks v3.3.6 - MC 1.7.10
Chisel2-2.4.1.40
ChiselTones-1.7.10-1.0-3
chocolateQuest-1.7.10-1.0
CodeChickenCore-1.7.10-1.0.6.43-universal
CoFHCore-[1.7.10]3.0.3-303
Decocraft-2.0.2_1.7.10
denseores-1.6.2
dimensional-anchor-59.0.3
DoomlikeDungeons-1.8.7-MC1.7.10
EnchantingPlus-1.7.10-3.0.2-d
EnderStorage-1.7.10-1.4.7.33-universal
fastcraft-1.21
immibis-core-59.1.2
InfiniBows-1.7.10-universal-coremod-1.3.0.20
INpureCore-[1.7.10]1.0.0B9-62
InventoryTweaks-1.59-dev-152
ironchest-1.7.10-6.0.62.742-universal
IvToolkit-1.2
Jabba-1.2.1a_1.7.10
journeymap-1.7.10-5.1.0-unlimited
Mantle-1.7.10-0.3.2
mystcraft-1.7.10-0.12.3.00
natura-1.7.10-2.2.0.1
neiaddons-1.12.11.36-mc1.7.10
NEIIntegration-MC1.7.10-1.0.12
NetherOres-[1.7.10]2.3.0-12
NotEnoughItems-1.7.10-1.0.4.107-universal
NotEnoughKeys-1.7.10-1.0.0b29
NotEnoughResources-1.7.10-0.1.0.106
OpenBlocks-1.7.10-1.4.4
OpenModsLib-1.7.10-0.8
PassiveTorch-1.7.10-0.1.0
RecurrentComplex-0.9.6.3
ResourceLoader-1.2
runicdungeons-1.1.5c
StevesWorkshop-0.5.1
StorageDrawers-1.7.10-1.5.15
Translocator-1.7.10-1.1.1.14-universal
ttCore-MC1.7.10-0.1.1-78
twilightforest-1.7.10-2.3.7
Waila-1.5.10_1.7.10
WailaHarvestability-mc1.7.x-1.1.2
Wawla-1.3.1-1.7.10
Ztones-1.7.10-2.2.1

**Comment by OJwithC** [comment]
https://github.com/Vazkii/Botania/issues/1385 ?

**Comment by Gragnar** [comment]
No, the mana was accumulating in the origin mana pool, so I doubt it's just a rendering issue. Also, I'm in single player.

**Comment by curiosity-a** [comment]
As a workaround you can use phantom lens, it's cheaper.

The problem is that warp lens alone doesn't make force relays transparent to beam pathfinding. So you have to combine it with a lens that does or use redstone spreader. This should be explicitly said in the lens's article to avoid confusion.

**Comment by Gragnar** [comment]
Ah, that's good to know, thanks!
