### ISSUE TITLE
Manaseer Monocle Render Issue

### ISSUE THREAD

**Issue by natedogith1** [Vazkii/Botania#1397]
Playing Agrarian Skies 2, the manaseer monocle shows a gray box for a flower's area instead of the intended colorful semi-transparent one that's supposed to be there.

**Comment by Vazkii** [comment]
Press F7 to turn off the NEI display.

**Comment by natedogith1** [comment]
Is this something that can be fixed? (I'm not familiar with rendering, so I don't really know)

**Comment by Vazkii** [comment]
This is a problem with NEI not properly resetting GL flags they use.
