### ISSUE TITLE
Use "minecraft" assets folder for 1.8 textures

### ISSUE THREAD

**Issue by Yulife** [Vazkii/Botania#1398]
When you use a 1.8 resourcepack in your instance with Botania, the blocks such as Prismarine and Stone variants are not re-textured by the resourcepack. This is due to the Botania's 1.8 textures being in the "botania" assets folder, thus the resourcepack maker has to make duplicate retextures in a seperate "botania" assets folder. If you put the 1.8 textures in a "minecraft" folder with the appropriate .png names they would automatically be retextured if you use a resourcepack. An example is Et Futurum by @ganymedes01 that automatically does this.

[Reference](https://github.com/ganymedes01/Et-Futurum/tree/master/src/main/resources/assets/minecraft/textures/blocks)
![Proof](https://cloud.githubusercontent.com/assets/8559428/9980455/41dc021c-5f9b-11e5-861b-0890d29203e8.png)

**Comment by Yulife** [comment]
:neutral_face:

**Comment by BBoldt** [comment]
:cry:
