### ISSUE TITLE
Wearing soujourner's sash, can't pass over slabs.

### ISSUE THREAD

**Issue by ahze** [Vazkii/Botania#1402]
While wearing the soujourener's sash, you can not pass over a slab if another slab is 2 blocks above it.  This is possible in vanilla.

![image](https://cloud.githubusercontent.com/assets/10377481/10036138/50894194-6171-11e5-95d3-2b69cdceffdd.png)

**Comment by OJwithC** [comment]
To confirm, it isn't the trodden dirt's fault.

You can hold shift, should be able to do it.

**Comment by MrKunji** [comment]
It's a vanilla thing, more info in https://github.com/Vazkii/Botania/issues/1014

**Comment by PsiGuy60** [comment]
It doesn't work if you don't wear the Soujourner's Sash, either. This isn't a bug in Botania, it's in Vanilla.

**Comment by OJwithC** [comment]
No, I can walk into it without a sash in vanilla. With the sash, I just had to hold shift.

**Comment by Vazkii** [comment]
That's the same bug that prevents you from walking up from soul sand into a 2 high area. Since you can step up higher it's just somewhat magnified.
