### ISSUE TITLE
Mod Sorting Crash After Updating To Botania 222

### ISSUE THREAD

**Issue by RoloEdits** [Vazkii/Botania#1403]
After updating to Botania 222 i'm getting this crash directly after startup 

http://pastebin.com/aTu8prNN

**Comment by Vazkii** [comment]
@ReikaKalseki, does DragonAPI load after botania?

**Comment by RoloEdits** [comment]
I'm not sure, could you point to where I might find that info?

**Comment by ReikaKalseki** [comment]
No, I do not specify as such.

**Comment by Zebia** [comment]
I have the same issue (or at least a similar one) the cycle for me is: Botania{r1.7-222} wants to go after DragonAPI(v8g) which wants to go after MagicBees{1.7.10-2.3.5} which wants to go after Botania.

I got this from the error message that comes up on trying to run these three together; as I can't find where it puts the 'ForgeModLoader-client-0.log' that apparently contains more information, sorry.

**Comment by ReikaKalseki** [comment]
> DragonAPI(v8g) which wants to go after MagicBees{1.7.10-2.3.5}

My "after Forestry" has been there for months...

**Comment by Zebia** [comment]
?¿?

anyways, I found the screencap app on my computer so here is a picture of the error message (I still can't find the FML log)
![mod cycle](https://cloud.githubusercontent.com/assets/9011480/10066759/5c55ba42-6253-11e5-8aac-694724490480.jpg)

**Comment by Vazkii** [comment]
https://github.com/Vazkii/Botania/commit/f59615e2b1f607d9e7c3918d7c4631bdc990ef1b
