### ISSUE TITLE
Lexicon issues

### ISSUE THREAD

**Issue by Nova001Sol** [Vazkii/Botania#1405]
1) The lexicon says that passive flowers decay after two days. The changelog says three. Which should I believe?
2) The entry for the manaweave robes says that wearing them makes rods cost less Mana (first page) but also says "increasing the power or range of them, or just their cost, for some of the more simpleton ones" (second page) which contradicts what was written earlier.

**Comment by OJwithC** [comment]
I'm not sure I see the contradiction in the second one. It seems to be saying that while wearing the robes will (presumably) reduce the mana cost of using all rods, it can have an additional effect on power or range for the rods where such a thing would be helpful.

**Comment by Nova001Sol** [comment]
I was talking about the "increasing...their cost" part. Nowhere in that sentence does that increase become a decrease.

**Comment by OJwithC** [comment]
Ah, my mind must have inserted "decrease" into that statement. I see the ambiguity now.
