### ISSUE TITLE
Botania/Forestry crash at launch

### ISSUE THREAD

**Issue by cih187** [Vazkii/Botania#1408]
Hello,

I think I have a conflict between Botania and Forestry. I tested different configuration and it's only when I have these two modes together that my game crash at launch. at the 7th step ("finishing up").

FML Log : http://pastebin.com/Vjq7Ja6D

I can't reproduce the bug with only baubles / botania / forestry.

Code where bug happens : 
@Override
public String getItemStackDisplayName(ItemStack itemstack) {
	return definition.getName(itemstack); // <-- right here
}
Well i tried looking through the code and it seems he doesn't implements this method ("getName"). But i didn't program much in java... What is weird is why your mod is making this error happen ?

**Comment by Vazkii** [comment]
This seems like someone is messing with the API and using it wrong, you'd have to do a binary search to find which mod it is.

**Comment by Judge-NZ** [comment]
For me it was Mariculture_(1.7.10)_v1.2.3d.jar... sigh, I know why i am not a programmer.  Great mod btw Vazkii :)
