### ISSUE TITLE
Soujourner's sash not working with Iguana Tweaks

### ISSUE THREAD

**Issue by EfficiencyVI** [Vazkii/Botania#1409]
Hi,

I'm not a 100% sure if this is a Botania or an Iguana Tweaks problem but when I have Iguana Tweaks installed the Soujourner's sash does nothing. It does not make me faster and also the step up assistant does not work.

Mods:
Botania r1.7-222.jar
IguanaTweaks-1.7.10-2B.jar (http://minecraft.curseforge.com/mc-mods/228798-iguana-tweaks)

**Comment by kotasc3** [comment]
Do you have some form of mana storage on you? Because it now requires a small bit of mana to function

**Comment by EfficiencyVI** [comment]
Okay, I missed that change. Problem solved!
