### ISSUE TITLE
Plants withering even though wither setting is -1.

### ISSUE THREAD

**Issue by Imrtltrtl** [Vazkii/Botania#1410]
My DayBlooms are disappearing. I found a dried herb in place of where one was after planting some new ones, but I have the wither setting set to -1 by default and once I updated from version 214 to 223, they started withering is what I'm guessing. I hadn't touched the setting before and I checked and it's still set to -1 like it says to do in the config. I usually update more frequently but 218 or something kept giving me mod sorting cycle errors and I couldn't get the game running at all.. 

FML Log: https://gist.github.com/anonymous/f540f3d3688dae61eca4

**Comment by OJwithC** [comment]
Seems you missed the storm.
Botania v222
"Removed passive wither config and locked it to 72000 ticks (3 ingame days, 1 IRL hour). Also added an entry to the Generating Flora section to explain it better."

**Comment by Imrtltrtl** [comment]
Sadface.. My bad..
