### ISSUE TITLE
Config option to disable stairs & slabs

### ISSUE THREAD

**Issue by kotasc3** [Vazkii/Botania#1411]
Currently Botania uses over 100 ids alone on stairs and slabs, which cannot be disabled, its a pretty easy fix, and would be useful for people who have mods such as Carpenter's Blocks which allows any block as a stair or slab

**Comment by catzs** [comment]
Or can the stairs and slabs be the same ID, but with metadata?

**Comment by kotasc3** [comment]
Stairs cannot due to how stairs use metadata to store rotation. Slabs could be compressed a little I suppose

**Comment by Vazkii** [comment]
Slabs are used for recipes, so this would be one hell of a mess to make. Putting it on the backburner.
