### ISSUE TITLE
Dissapearing flowers...

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [Vazkii/Botania#1412]
With the latest version all my 200+ floating hydrogeas disappeared....what gives?

I replaced them via cheat, but after closing the game and restarting later, they disappeared again.

**Comment by MrKunji** [comment]
Read the version 222 changelog
http://botaniamod.net/changelog.php

**Comment by Unrepentant-Atheist** [comment]
I did, but can't find anything why they keep on disappearing.

**Comment by kotasc3** [comment]
"Removed passive wither config and locked it to 72000 ticks (3 ingame days, 1 IRL hour). Also added an entry to the Generating Flora section to explain it better...."

**Comment by Unrepentant-Atheist** [comment]
Oh well, I was away a while. When reading wither I thought about the wither potion effect.
