### ISSUE TITLE
[Bug] Can't pick up Items on abstruse platform

### ISSUE THREAD

**Issue by Minetrix** [Vazkii/Botania#1413]
I just noticed a bug, that if you throw Items on an abstruse platform, other players can't pick those items up. I, myself, can. I don't know if it is a bug within Botania or the Modpack (FTB Mage Quest), but I post it here, because of the abstruse platform. I use edition 201.

I hope it helped, I'm sorry for my english.

**Comment by Zsashas** [comment]
I have noticed this as well, intermittently. I thought maybe the item didn't know if it was supposed to be on top of the block or not.

**Comment by Lazersmoke** [comment]
Are items supposed to go through spectral (dreamwood) platform? they aren't for me and I think this is related
