### ISSUE TITLE
Official Botania Garden of Glass Modpack Crash

### ISSUE THREAD

**Issue by Timetech01** [Vazkii/Botania#1416]
Error found on the latest version of Garden of Glass Modpack on the Beta Curse Launcher
[Botania Skyblock: The Modpack: The Mod: The Modpack]

Partway through loading, after clicking play, I encounter a game crash.  I am returned to the Minecraft Launcher loaded by Curse.

FML Log: http://pastebin.com/sD3AmW26

**Comment by Vazkii** [comment]
Give the game more ram.
