### ISSUE TITLE
Solegnolia not working for items on pressure plates

### ISSUE THREAD

**Issue by M-a-r-t-i-a-n** [Vazkii/Botania#1420]
Items dropped onto pressure plates aren't kept from magnetization by the Solegnolia

**Comment by M-a-r-t-i-a-n** [comment]
Changed issue to pressure plates - open crates weren't the problem.

**Comment by MrKunji** [comment]
Are you sure that the said pressure plate isn't disabling the Solegnolia?

**Comment by M-a-r-t-i-a-n** [comment]
Oh my god it is powering it since I have it right next to the plate. I didn't even make that connection. I feel dumb now. Thanks (Also how do I delete this issue?)
