### ISSUE TITLE
Keybind for gliding

### ISSUE THREAD

**Issue by OJwithC** [Vazkii/Botania#1421]
I would like to request a keybind for the tiara's glide function that is separate from sneaking. As I typically have the globetrotter's sash on with it, I tend to hold shift on stairs to not hit my head, and when going down slabs so I don't overshoot, but the gliding makes that not as simple. There is also the occasional odd behavior of the game believing you can go up a half slab with one block of air between them when you have the sash on. 
Also, there is no way to stay still on ladders/vines with a tiara on (holding shift by one makes you go up it).

**Comment by Vazkii** [comment]
![](https://media.giphy.com/media/dePaPOPNSLDsk/giphy.gif)~

# No keybinds!

**Comment by OJwithC** [comment]
Understandable. 
I take it I should just live without being able to shift on ladders then (since it really isn't a big deal if it isn't "fixed")?
