### ISSUE TITLE
Multiple problems with Mana Fluxfield

### ISSUE THREAD

**Issue by pennywis3** [Vazkii/Botania#1423]
1. Fluxfields do not work with BC Kinesis Pipes. The Wooden/Emerald pipes will visually connect, but no power will be transmitted. I believe this is because the Fluxfield can only transmit RF while pipes can only extract, not receive. TD Fluxducts or TE Energy Cells do work however.
2. Fluxfields lose power/mana if you provide them more mana than it can output RF. For instance hooking up one Fluxfield with an Energy Cell set to accept 100RF/t and feeding it with a Gaia Spreader will yield just ~600k RF for one full Mana Pool. Setting the cell to accept 32kRF/t will get you just short of 10M RF for the same amount of mana.
3. Fluxfields only ever output to one receiver at a time. This is not really a serious issue though since you can always branch off further down the line or build more Fluxfields depending on the problem at hand. I just wanted to point it out.

Using Botania r1.7-223 and Buildcraft 7.0.25

**Comment by pennywis3** [comment]
Granted, No.3 was a false alarm, I simply hadn't expected this kind of distribution.
The code looks like No.2 is anything but intended, yet here I am reporting suspicious behaviour.
And finally No.1 is a consequence of your decision not to implement IEnergyProvider. Could you please give this a second thought?

**Comment by bookerthegeek** [comment]
Question, does it work with a non wooden power pipe from buildcraft?

**Comment by pennywis3** [comment]
No, it doesn't.
