### ISSUE TITLE
Extensive use of Entropinnyums causes chunk corruption

### ISSUE THREAD

**Issue by Baughn** [Vazkii/Botania#1425]
http://pastebin.com/prtmsDfy

This one's a bit hard to diagnose. The way it works is: Our botania player does [something] with entropinnyums, likely involving generating enormous amounts of mana; the in-memory state gets corrupted; when he logs off, the server crashes. On startup it does what's in that pastebin.

**Comment by Castone22** [comment]
Build in question makes use of 50 entropinnyums that are semi-automated at the moment, using redlogic redwire to trigger the tnt on a 10 second timer.  2 rannuncarpus are used to place the TNT on thaumcraft warded blocks to prevent any serious damage should a mana buffer somehow overflow.

Best picture i have of this build: http://imgur.com/FE9Zx7H

**Comment by TheComputerGeek2** [comment]
Forgive me if I missed something, but I don't see any indicator of Botania contributing to that error, I couldn't find any of Vaskii's package declarations within that stack trace. I think that the log from when the server crashed is needed, not only the one from startup.

**Comment by Castone22** [comment]
At this point i've just ended up removing the build and decided to automate something else, there's not enough information to really say one way or the other.  I wasn't able to replicate the error in a single player world at all, so it's likely something server side.

**Comment by TheMadmanofChaos** [comment]
The issue is not with Botania, but actually the Warded Blocks. U;ve seen a crash log like this one show up as a result of a Wither farm.

**Comment by Baughn** [comment]
Castone did indeed have warded blocks. Interesting.
