### ISSUE TITLE
Dandelifeon Deletes Blocks When Generating Mana

### ISSUE THREAD

**Issue by natedogith1** [Vazkii/Botania#1427]
In the 3x3 area around the flower, if I have a block where a cell would generate, the block gets destroyed.

**Comment by Vazkii** [comment]
That's exactly what it's supposed to do :V

**Comment by natedogith1** [comment]
It's supposed to delete redstone? And probably bedrock?

**Comment by Zsashas** [comment]
So the cells overwrite other blocks? That doesn't sound good.

**Comment by Vazkii** [comment]
I can't reproduce this.

**Comment by natedogith1** [comment]
I can still reproduce it in the latest version (225). If you turn on the lever in the setup the bedrock will disappear.

![2015-10-13_19 12 57](https://cloud.githubusercontent.com/assets/1638163/10470896/b70929c0-71de-11e5-80a3-96b0f2090ffe.png)
