### ISSUE TITLE
Daybloom issue on disappearing

### ISSUE THREAD

**Issue by CitiesXL2815** [Vazkii/Botania#1428]
Dayblooms are disappearing, I had 4 of them and now theres two left, i'm using them to creat mana in the day and now the other two just disapeared just now at 6:23PM. i'll send the link: http://imgur.com/a/72699

**Comment by AlterAkima** [comment]
Read the 'Caveats of passive generation' entry under the Generating Flora section, non issue.

**Comment by CitiesXL2815** [comment]
if it works i'll keep it close but if reopen then it's an issue, but thx
