### ISSUE TITLE
Placing non-iron beacon-safe blocks doesn't complete the Ritual of Gaia structure

### ISSUE THREAD

**Issue by yrsegal** [Vazkii/Botania#1431]
this is for visualization purposes.

**Comment by OJwithC** [comment]
What version are you using? Thought it was fixed in 209.

**Comment by NezcalSpindrake** [comment]
What blocks are you using?

**Comment by yrsegal** [comment]
Manasteel and Elementium. They look pretty :P

**Comment by TheWhiteWolves** [comment]
Update to the latest Botania version and try again, for now I'm closing this issue l, you can still comment on a closed issue if you want to add anything

**Comment by yrsegal** [comment]
I am on the latest botania.

**Comment by phantamanta44** [comment]
Can you please display a screenshot of your setup?

**Comment by yrsegal** [comment]
![2015-10-04_19 56 38](https://cloud.githubusercontent.com/assets/6596492/10271055/19051044-6ad2-11e5-8704-e03dbef92702.png)
![2015-10-04_19 56 35](https://cloud.githubusercontent.com/assets/6596492/10271053/19007278-6ad2-11e5-94de-2c64786022f6.png)
![2015-10-04_19 56 31](https://cloud.githubusercontent.com/assets/6596492/10271054/1901cf92-6ad2-11e5-832a-37c7f7134c70.png)

**Comment by Zsashas** [comment]
Why are the blocks transparent?

**Comment by yrsegal** [comment]
it's a structure visualization.
