### ISSUE TITLE
Crash after using Eye of Flugel

### ISSUE THREAD

**Issue by jaxx050** [Vazkii/Botania#1433]
I was playing on the private MP server [ Direwolf20 mc1.7.1, pack version 1.6.1, botania version 1.6-98 (yes i know it's old) ] that I usually do, and I had just gotten the Eye of Flugel from the dice. I used it once or twice, went ok, but I went a distance from my base and then tried using it again, and it CTD'd me, and I've now started to CTD on every attempt to load. I know I'll be told to update, but if I do that, chances are things are going to break and I'd appreciate being able to work something out in my current game. Logs:
crash report: http://pastebin.com/4S6ibspT
log: http://pastebin.com/7NCVV11T

**Comment by phantamanta44** [comment]
Looks like a rendering issue with Thaumcraft to me.

**Comment by TheWhiteWolves** [comment]
That's a Thaumcraft warded block problem
