### ISSUE TITLE
Can't disguise abstruse platform as some modded blocks.

### ISSUE THREAD

**Issue by ewanm89** [Vazkii/Botania#1434]
When right clicking the abstruse platform with a modded block from chisel2 or enderio it  just tries to place the chisel 2 block against that side of the platform rather than disguising the platform.

**Comment by Zsashas** [comment]
What blocks specifically are you trying?

**Comment by ewanm89** [comment]
It was various forms of chiselled glass, I also tried enderio quite clear glass, I wanted a transparent block I could both walk on or fall through.

**Comment by Zsashas** [comment]
I didn't think transparent blocks worked. Have you tried modded solid blocks?
