### ISSUE TITLE
Suggestion: Lower Threshold For Gaia Guardians' Environment Check 

### ISSUE THREAD

**Issue by RoloEdits** [Vazkii/Botania#1436]
I had to clear out a lot of trees and dirt to be able to fight the Gaia Guardian, way more than the boundary created when fighting and it looks very unnatural and ugly. I don't know if this intended to be this strict when doing the environment check, but if it is could you consider lowering the check a little?

Thanks a lot.

**Comment by yrsegal** [comment]
as an aside to this; the Gaia Arena must be square, as that's where the guardian can teleport. Perhaps make the arena and the teleport bounds circular?
