### ISSUE TITLE
Exoflame - Alchemical Furnace incompatibility

### ISSUE THREAD

**Issue by Hyxaru** [Vazkii/Botania#1441]
As the tile says, the Exoflame doesn't seem to recognize the Alchemical furnace from thaumcraft as something it can fuel. The alchemical furnace burns on everything normal vanilla furnaces do, so I think it should be able to be fueled with mana.

**Comment by OJwithC** [comment]
"The Exoflame will now ignore other mods' Furnace blocks unless they specifically opt in with the API interface." Azanor's side.

**Comment by Hyxaru** [comment]
Oh, I wasn't aware this was changed. When did this happen actualy? I do remember it working before. Thank you anyway.

**Comment by OJwithC** [comment]
Looks like v 171.

**Comment by Zsashas** [comment]
If you still need it, have this: http://www.curse.com/mc-mods/minecraft/238061-tcbotaniaexoflame
