### ISSUE TITLE
Hydroangeas can actually consume Buildcraft oil due to Material.water

### ISSUE THREAD

**Issue by 3TUSK** [Vazkii/Botania#1443]
Update 224, Forge 10.13.4.1470
![consumingoil-1](https://cloud.githubusercontent.com/assets/9113033/10414200/7c21b61a-6f95-11e5-9963-5674e5482bc3.gif)
But who will pour petroleum nearby a hydroangeas...

**Comment by Vazkii** [comment]
Ayyy, not even mad.

**Comment by 3TUSK** [comment]
won't fix?

**Comment by Vazkii** [comment]
No.

**Comment by 3TUSK** [comment]
<s>then I need to keep flowers away from any fluid that is not water... </s>

**Comment by TheWhiteWolves** [comment]
If it makes you feel better just imagine it as the hydroangea consuming the hydrogen that is contained in the oil.

**Comment by Zsashas** [comment]
Sounds like something to bug Buildcraft about.

**Comment by 3TUSK** [comment]
Technically it's an issue about interaction. [Here](https://github.com/BuildCraft/BuildCraft/blob/7.1.x/common/buildcraft/BuildCraftEnergy.java#L210) shows that buildcraft oil block has property of `Material.water`, and hydroangea consumes any block whose `Material` is `Material.water`.

**Comment by Zsashas** [comment]
Why does Oil have the property of Water, though? It's Oil.

**Comment by Kubuxu** [comment]
Because it is standard material used for fluids: https://github.com/CoFH/ThermalFoundation/blob/4f3d314796b578f0f9e4a4a21e4f21c8eb281a82/src/main/java/cofh/thermalfoundation/fluid/BlockFluidCoal.java#L23
