### ISSUE TITLE
Suggestion: Turbo charged unstable cubes

### ISSUE THREAD

**Issue by Cruddly** [Vazkii/Botania#1446]
Love the unstable cubes, but the effect is too small and can't be seen from very far. I am hoping you could introduce tiered versions. Wrap each tier in mana diamonds or whatever to boost the sparking radius and bolt thickness (thus viewable range?).

An additional recipe they could be a component for would be for a spark jump between two placed blocks, for an electric fence forcefield appearance.

Love this mod to death, great work.

**Comment by Vazkii** [comment]
These things lag far too much to have them produce large range effects, sorry.
