### ISSUE TITLE
Petal Apothecary not showing visual petal inventory, cannot add seeds / craft flowers

### ISSUE THREAD

**Issue by Randulv** [Vazkii/Botania#1452]
I'm playing Modsauce 2 on ATLauncher, it's Minecraft v1.7.10. I have OptiFine 1.7.10 installed because "Animated Terrain" drops my frames by 30-40, rendering the mod pack unplayable otherwise. This setting is currently disabled, but even enabled does not seem to impact the Petal Apothecary. (I don't really care about visual glitches anyway)

The issue:

I can add mystical petals to the Petal Apothecary, but they do not float around inside. I can see the white sparkly particles around the base of the apothecary, and harvest the "buried" petals, but the water inside appears empty. Not a big deal, but on top of that, I cannot put seeds into the apothecary either. Right-clicking and Shift-Right-Clicking the apothecary with an empty hand does nothing. 

This right here makes Botania unplayable without cheats, something I won't do.

I cannot craft anything using the Petal Apothecary, despite loading it with petals in the correct recipe format. I'm using Botania R1.7.225, the latest version. I had R1.7.221 but updated to see if that would fix it. It did not. 

I would really appreciate your help as I've been really excited to give Botania a try, but I can't even craft a couple Pure Daisies! :(

It won't let me upload the ATLauncher log, which I copied and pasted into a text file. I've had to upload it separately. 

Log here: http://www.filedropper.com/atlauncherlog
Modsauce 2 mod list: http://hermitcraft.com/modsauce

Any recommendations?

**Comment by OJwithC** [comment]
You mentioning buried petals confuses me. You are *dropping* the petals into the apothecary, right?

**Comment by Randulv** [comment]
Sure wasn't! 

I swear I tried that and it wasn't working, then I checked a video and it looked like he was right-clicking items in. 
 
Thanks OJ! It's user error 99% of the time isn't it? :P
