### ISSUE TITLE
Issue with Botania 220+ and AE2 Stable 10

### ISSUE THREAD

**Issue by mostwanted12354** [Vazkii/Botania#1454]
Hey Vazkii,

The issue I am having is that when I have Botania versions 220+ installed. I currently am running the newest version 225. I am having issues with the certus quartz knife and nether quartz knives breaking in all crafting grids by simply taking the knives in and out of the grid. If I remove Botania and Baubles then the knives don't lose durability unless you craft something as expected. 

I have also posted this over at AE2 and yueh has stated he cannot recreate the issue with just MC and AE2 and suggested removing mods until we find the culprit. I tried removing DragonAPI first but it wasn't the culprit. I put Reika's mods back in, and removed Botania and Baubles and the issue stopped occurring.

Thank you,

Here is a Mod list of what i have. I am running an updated and custom version of Bevo's Tech Pack http://pastebin.com/sA7wne3a

**Comment by AlterAkima** [comment]
Can confirm, recording ATM.

**Comment by AlterAkima** [comment]
Notice it happens to any item that loses durability, so https://github.com/Vazkii/Botania/issues/1343 was a real issue then.

**Comment by AlterAkima** [comment]
Not AE2's fault, for example, the Spellbinding Cloth is losing durability just by being put in a crafting table, tested with only Botania.

**Comment by AlterAkima** [comment]
https://youtu.be/sG9QKaSJzFI

**Comment by ranger135xp** [comment]
This happens with AE2 quartz knives as well but only when Botania is installed. I have all the same versions as @mostwanted12354 as we play on the same server.

**Comment by Vazkii** [comment]
I see, yeah, the cloth does take damage. Why other things would is beyond me though.
