### ISSUE TITLE
AE2 with latest Botania causes Quartz Knives to take damage without crafting

### ISSUE THREAD

**Issue by ranger135xp** [Vazkii/Botania#1458]
https://github.com/Vazkii/Botania/issues/1454
This issue still exists. AE2 says it isn't them. I'm not really sure what to do or where to post it. Thank you for your time, Vazkii. I did check the cloth though from issue https://github.com/Vazkii/Botania/issues/1343 and that no longer occurs! Again, thank you.

UPDATE: I just checked by removing Botania and leaving Baubles and the issue doesn't persist. The issue comes and goes with the addition and subtraction of Botania 226 from this modlist: http://pastebin.com/sA7wne3a

**Comment by natedogith1** [comment]
I think this might be caused by using "getItemContainer() == null" rather than "hasItemContainer()" in KeepIvyRecipe
https://github.com/Vazkii/Botania/blob/9cf015ee972bb8568f65128fa7b84c12c4a7cfff/src/main/java/vazkii/botania/common/crafting/recipe/KeepIvyRecipe.java#L33

**Comment by Vazkii** [comment]
Shit! You're right. Thanks.
