### ISSUE TITLE
[Feature Update Request] Minecart with Mana Pool update

### ISSUE THREAD

**Issue by McSharidan** [Vazkii/Botania#1465]
Greetings Vazkii!

The addition of the Minecart with Mana Pool to Botania, is certainly a very nice feature, however it's causing a tiny bit of grief in my rail system setup, using Railcraft. I know from a different issue posted here, that you don't really want to support a lot of rail stuff and I respect that, but I figured I would give it a go and ask anyways. CovertJaguar posted back on my issue on his github about this particular issue which you can find here: [CovertJaguar/Railcraft#713](https://github.com/CovertJaguar/Railcraft/issues/713)

CovertJaguar mentioned something about your Minecart with Mana Pool not extending the vanilla ItemMinecart reference for the item itself. The problem I'm having is not being able to use Railcraft's Cart Dispensers for your minecart. While the Cart Dispensers can despawn your Manapool minecart, they don't accept the Manapool cart item so I can't use the Cart Dispensers to spawn your Manapool minecart. I don't know the extend of your code, so I have no idea how big of a change it would be for you. Would it be a huge amout of work for you to perhaps fix this problem with the Manapool cart item?

Worth noting, is that there are no other major issues once the Manapool minecart is on the tracks, except it doesnt move as far down the tracks as other minecarts do. Seems like the Manapool minecart is heavier or has a higher drag value of some kind. I'm not sure if that is something you are controlling in your code or not. It's not a big issue, certainly not something a few more booster tracks can't solve. Linking the Manapool cart with oher minecarts using Railcraft works just fine.

Thank you Vazkii for giving us Botania! It's an awesome mod for sure.

Sharidan

**Comment by McSharidan** [comment]
I'm sorry for bothering you Vazkii, but may I ask what you mean by the "compatibility" tag? Would love to know what the outcome was of your debate with CovertJaguar :)

**Comment by Vazkii** [comment]
https://github.com/Vazkii/Botania/commit/69ed66aca0182462dad1cbc756c0a391754aa2af

**Comment by McSharidan** [comment]
@Vazkii You rock! :)
