### ISSUE TITLE
Manufactory halo sometimes places returned items in equipment slots when inventory almost full

### ISSUE THREAD

**Issue by jesskay** [Vazkii/Botania#1467]
With a recipe saved for automatic crafting of Magical Crops weak essence (under Regrowth 0.8.2 specifically, but I'll attempt to reproduce it with just Botania and MC) which returns the infusion stone, if only one slot is free in the inventory, the manufactory halo places the infusion stone in my foot slot. If the foot slot has an item equipped, it places it in legs, and I assume this would continue upwards until it found an open slot.

I have no baubles equipped, and no armour equipped besides the Elementium Boots I used to test whether it would use other equipment slots.

If there's any details I left out that would potentially be important, let me know and I'll try my best to get them!

**Comment by Vazkii** [comment]
Can't reproduce.
