### ISSUE TITLE
[Bug] Items in range of multiple Hopperhocks/Hoppers/Open Crates can duplicate

### ISSUE THREAD

**Issue by PaladinOne** [Vazkii/Botania#1470]
I have a setup in which I have two Hopperhocks above Open Crates, one of which is above a hopper and one of which is above a Runic Altar. Inconsistently, when either I drop a Rune or the Altar produces a set of Runes, both Hopperhocks can pick up one or more runes, resulting in the output chest having a rune sitting in it and the Altar having an erroneous rune sitting in it.

Unfortunately, I'm having a lot of trouble reliably reproducing it reliably, so I don't know exactly if it's the Hopperhocks, the Crates, or a vanilla bug with the Hoppers.

On Botania 225, pack Beyond Reality: Divergence.

Attached: screenshot of the current setu
![2015-10-23_07 22 11](https://cloud.githubusercontent.com/assets/7624297/10695121/e54257e2-7956-11e5-8360-5fb134f529a6.png)

**Comment by L0neKitsune** [comment]
That sounds like the expected behavior.  There isn't an item frame on either of the hopperhocks so both of them will try picking up everything.  The altar throws the item when its done so if the hopperhock above the altar grabs it then you get the item back in the altar.
