### ISSUE TITLE
Option to disable passive flower decay gone?

### ISSUE THREAD

**Issue by yepidoodles** [Vazkii/Botania#1472]
After my last update to the latest version, the option to disable flower decay has gone. My players are freaking out that all their flowers are now dead bushes, obviously causing me a big headache. I didn't see anything about this in the changelog

What happened to it?

- Alice

**Comment by AlterAkima** [comment]
Check the changelog for version 222.

**Comment by yepidoodles** [comment]
That only states for the passive wither, not for the flower decay

**Comment by phantamanta44** [comment]
Same thing.
When flowers decay, they wither.

**Comment by yepidoodles** [comment]
Oh I thought that was in regards to the pink wither

**Comment by Tyfyter** [comment]
[The page explaining the reason for the change](https://vazkii.net/uncategorized/sins-of-a-solar-empire-or-the-passive-generation-conundrum/) is now gone.

**Comment by Alwinfy** [comment]
see https://vazkii.net/#blog/sins-of-a-solar-empire

**Comment by eehunter** [comment]
I can't find the changelog, but I found that in 1.16.5, you can drop a flower on the ground and use this command to effectively negate decay: 
/data merge entity @e[sort=nearest,limit=1,type=item] {Item:{tag:{BlockEntityTag:{passiveDecayTicks:-10000000}}}}

It basically gives an extra 10000000 ticks (500000 seconds) before the flower decays. Of course, one must be opped/have cheats enabled to do this.

**Comment by LeoBeliik** [comment]
You can simplify the command by using `/give @p botania:creative_pool` instead.
