### ISSUE TITLE
Botania Custom Infusion

### ISSUE THREAD

**Issue by LewisTehMinerz** [Vazkii/Botania#1474]
Hey Vazkii, I would like a way to add custom infusions (in-game or external program) for modpack developers. Is there a way to do this or a mod? Thanks!

**Comment by ray10k** [comment]
If you mean infusions in the runic altar, that is already possible. The Regrowth modpack adds a massive number of recipes.
One thing to keep in mind however is that the livingrock at the end is still necessary.
(( http://forum.feed-the-beast.com/threads/1-7-10-regrowth-a-wip-hqm-pack-now-listed.57184/ ))

**Comment by LewisTehMinerz** [comment]
The thing is, how do they do it?

**Comment by ray10k** [comment]
From what I can see at the Regrowth repository, they first use Minetweaker (https://github.com/thephoenixlodge/Regrowth-Stuff/blob/master/mods/ModTweaker-2-0.9.0.jar), then use a number of scripts to change the recipes around. [Here](https://github.com/thephoenixlodge/Regrowth-Stuff/blob/master/scripts/magiccrops.zs#L187) is one of the lines that seem to add stuff to the runic altar crafting recipes.
Hope this helps, and best of strength with your endeavours!
