### ISSUE TITLE
Guardian of Gaia can be caught by minecart

### ISSUE THREAD

**Issue by bakaxyf** [Vazkii/Botania#1476]
![image](https://cloud.githubusercontent.com/assets/10368307/10715092/d3e46064-7b43-11e5-8c93-f318928a9376.png)

**Comment by PsiGuy60** [comment]
This image is hilarious. Vazkii, I know this is not the way to do it but I humbly request a decorative minecart with a Gaia Guardian lookalike riding around in it.

**Comment by SihenZhang** [comment]
Now Gaia can be caught again...
Minecraft Version: 1.12.2
Forge Version: 14.23.5.2815
Mod Version: r1.10-360
![](https://i.imgur.com/CQSAqhz.jpg)
![](https://i.imgur.com/Fal5kJi.png)

**Comment by williewillus** [comment]
been broken since the 1.9 update. oops.
