### ISSUE TITLE
odd crash with black hole talisman

### ISSUE THREAD

**Issue by NoobFortress2** [Vazkii/Botania#1477]
I tried shift-rightclicking the air with the black hole talisman on a server. I crashed
every time I log in to the server now I get the same crash report. I don't know exactly what is happening but it seems to me that it has something to do with the tooltip render.

crash report: http://pastebin.com/E76vdwi9
FML log: https://www.dropbox.com/s/by3my1naprdj3w8/fml-client-1.log?dl=0 (sorry too big for pastebin)

**Comment by Vazkii** [comment]
Update botania.
