### ISSUE TITLE
The Gaia Guardian's Head Block is visible in NEI

### ISSUE THREAD

**Issue by gabor6505** [Vazkii/Botania#1478]
## Description
The Gaia Guardian's Head, the block itself is listed in NEI. It also has a Missing Texture, and it's placement (the block itself) is a little bit odd. The item's placement is fine.

**Sorry if this is an intended feature or an already known issue.**

### Screenshots:
*The Gaia Head Block on NEI, and Placing it*
![2015-10-25_18 11 42](https://cloud.githubusercontent.com/assets/12859334/10716794/37244ed2-7b44-11e5-8d3c-d30fecff7cad.png)
![2015-10-25_18 12 56](https://cloud.githubusercontent.com/assets/12859334/10716795/37350b32-7b44-11e5-8f6d-a2e84846830e.png)

*The Gaia Head Item in NEI, and Placing it*
![2015-10-25_18 11 48](https://cloud.githubusercontent.com/assets/12859334/10716797/45e3198a-7b44-11e5-941b-b19813d958e9.png)
![2015-10-25_18 12 41](https://cloud.githubusercontent.com/assets/12859334/10716798/45fa957e-7b44-11e5-9b04-bc0371cbffa9.png)

### Versions:
**Botania**: r1.7-228

**If you need forge logs, modlist, or anything like that, tell me.**
**Thanks for the help!**

**Comment by Vazkii** [comment]
This is a non-issue, there's also other internal blocks that can be seen through NEI.

**Comment by PsiGuy60** [comment]
NEI does weird things like that - you can also get a lit furnace, half of a door or the top of a piston that way, along with a ton of other blocks like that from other mods (like the Cutting Board and Pot blocks from Pam's Harvestcraft). This is not something that Vazkii can fix, nor is it really something that needs fixing.

**Comment by AEnterprise** [comment]
it can kinda be fixed by using the nei api and tell it to hide those blocks
