### ISSUE TITLE
[idea] Lexica Botania should indicate spreaders range

### ISSUE THREAD

**Issue by Ncrpts** [Vazkii/Botania#1479]
I find the lexica botania to be a great documentation for the mod but when designing stuff i never remember the spreaders range before occuring mana losses (in block distance) and always end up searching on wikis this information, maybe adding them to the lexica once it is thrown in the portal for example would help. But this information may be intentionally left vague by design to force the user to experimentate with the spreaders in that case forget this issue.

**Comment by L0neKitsune** [comment]
Holding the wand of the forest will show the mana burst path.  At the point where mana loss starts to occur there is a pinpoint of light that doesn't move like the rest of the animation.

**Comment by L0neKitsune** [comment]
![2015-10-25_23 10 40](https://cloud.githubusercontent.com/assets/3188396/10721705/b4cd75e2-7b6d-11e5-8a92-94207c12f23f.png)

**Comment by Ncrpts** [comment]
Yeah but you have to place the spreader and take notes of those informations, i always end up forgetting the numbers and to lazy to reproduce so i end up typing on google "botania spreaders range" and get the info i'm looking for on the wiki (12 blocks for normal spreader) but like i said this may be omited in the book by choice, still it would be helpful for people who likes to "design" on paper before crafting

**Comment by ray10k** [comment]
I think you could try this yourself. As in, make a branch for yourself, add a mention of the range in the Lexica, and submit a pull request.

**Comment by Ncrpts** [comment]
Okay i did that, but i'm not sure Vazkii will agree tho

**Comment by Vazkii** [comment]
That's what the notes feature is there for.
