### ISSUE TITLE
Dandelifeon can destroy non-cell blocks

### ISSUE THREAD

**Issue by Abacor** [Vazkii/Botania#1484]
*I'm not sure if you see comments on closed issues so I'm opening this as a new issue.*

Issue #1427 still exists in build 228. I've reproduced it using @natedogith1's setup. If you turn on the lever in this setup then the bedrock will disappear.

![b70929c0-71de-11e5-80a3-96b0f2090ffe](https://cloud.githubusercontent.com/assets/11965311/10727479/25845f80-7bd2-11e5-8dad-39e6002e5464.png)

Blocks get destroyed if they are in the mana generating zone and the game-of-life rules want to place a cell with generation >= 2 in that location.

**Comment by TheWhiteWolves** [comment]
Yes we can see comments on closed issues.
