### ISSUE TITLE
Hopperhock dropping a bug flower when between two chests, seemingly randomly?

### ISSUE THREAD

**Issue by birb-ebooks** [Vazkii/Botania#1488]
...I really don't know how much more I can tell you, the console showed nothing weird or relating to Botania at all when the bug happened. I'm using r1.7-226, and my modlist is here: 
![modd](https://cloud.githubusercontent.com/assets/15340096/10754653/1067c110-7c67-11e5-9cbf-8cac6cf8df4d.png). 

Essentially, I placed a hopperhock between two vanilla chests which were next to two Gendustry industrial Apiaries, since the apiaries decided to start spewing items everywhere. When I went to move it though, it broke into the bugged flower. I tested this several more times, both in the same spot, nearby, and far away, and seemed to randomly get the bugged flower, literally no reason or event beforehand that would effect it I would think, and the console log shows nothing weird happening at that time.

Sorry I don't have much info, if you need any more let me know and I'll try to get it for you.

**Comment by yrsegal** [comment]
Cannot reproduce using 226 or 228.

**Comment by birb-ebooks** [comment]
I really don't know what could've happened, it would randomly decide to drop the bug flower instead. I felt like I should at least mention it, even if there's not much to go on.
