### ISSUE TITLE
Rannuncarpus can't grab items on active pressure plates

### ISSUE THREAD

**Issue by Roxforbraynz** [Vazkii/Botania#1492]
I was working on an automated Kekimurus using a simple system that I also used for my Endoflames when I noticed that the Rannuncarpus won't grab an item that's on a wooden pressure plate. Further investigation shows that the same holds true for any pressure plate that is pressed down, even a stone one if the player can't pick up the item on it. The stone pressure plate leads me to believe that this is a bug.

I'm not sure if this is intended or not. If it was intended then I feel that such an important thing should be mentioned in the Rannuncarpus's Lexica Botania entry and if it's not intended then it needs fixing.

**Comment by AlterAkima** [comment]
Is the said pressure plate placed on the side of the plant?

**Comment by Roxforbraynz** [comment]
Yes, you're right. It looks like it only does this while the pressure plate is next to it.

**Comment by phantamanta44** [comment]
Fyi, plants are disabled by redstone signals.

**Comment by Roxforbraynz** [comment]
I see now. This isn't an issue then, I'll close this.

**Comment by Vazkii** [comment]
:100:

**Comment by OJwithC** [comment]
Specifically, plants that use a redstone root in their crafting (and the orechid in Garden of Glass) turn off with a redstone signal.
