### ISSUE TITLE
Appllied energistics 2 interaction clientside crash.

### ISSUE THREAD

**Issue by wutwutington** [Vazkii/Botania#1495]
when attempting to automate botania functions and monitor using AE2 systems a clientside crash is observed. stacktrace and crashdump can be found at http://pastebin.com/e0Nk4E8G

**Comment by mindforger** [comment]
try updateing botania first(228), but botania seems in general to currently have some issues with their render-hooks

**Comment by Vazkii** [comment]
AE crash, their AABB code is crashing.
