### ISSUE TITLE
EnderIO Coord selector crashes with Botania.

### ISSUE THREAD

**Issue by XFRGod** [Vazkii/Botania#1496]
http://pastebin.com/BeDbj00V

**Comment by mindforger** [comment]
did you also report this over @ botania? looks more like a renderhook of botania going nuts?!
>at vazkii.botania.client.core.handler.TooltipAdditionDisplayHandler.render(TooltipAdditionDisplayHandler.java:62)

**Comment by XFRGod** [comment]
I only opened this issue here.

**Comment by Vazkii** [comment]
This is an EnderIO crash, for some reason the tooltip for that item isn't being created properly.
