### ISSUE TITLE
Botania conflict with Mekanism (Crafting item)

### ISSUE THREAD

**Issue by TsumiHokiro** [Vazkii/Botania#1499]
While trying to craft a Mekanism item, Induction Port, the game crashes, I've tried with 3 different tables (Tinker's, Vanilla and Thermal Foundation) and it happens on all the tables. For some reason or another the Botania mod is being called on the crash report and as such I'm also posting this here.

http://pastebin.com/QGnck2EC

**Comment by phantamanta44** [comment]
This is an issue on Mekanism's end.
