### ISSUE TITLE
Mana Enchanter entry in the Lexica Botania has information cut off

### ISSUE THREAD

**Issue by Roxforbraynz** [Vazkii/Botania#1502]
For example, if a single book with Efficiency V and Unbreaking III is used then the Mana Enchanter will only apply the Efficiency V enchant. I've tried it multiple times with various books and items and this seems to always happen.

**Comment by OJwithC** [comment]
"If any book has more than one enchantment, only the first will be accounted for."

**Comment by Roxforbraynz** [comment]
Where is that said? It's nowhere in the Lexica Botania entry for the Mana Enchanter.

**Comment by bookerthegeek** [comment]
Yes it is.

**Comment by AlterAkima** [comment]
In https://github.com/Vazkii/Botania/blob/master/src/main/resources/assets/botania/lang/en_US.lang#L2574

**Comment by Roxforbraynz** [comment]
That's odd. The entry in Lexica Botania 228 only shows 6 pages, that's on page 8. This is an issue with the Lexica then.
