### ISSUE TITLE
Fighting Gaia Gaurdian crashes Cleint to Minecraft window while on Server.

### ISSUE THREAD

**Issue by Mariolink93** [Vazkii/Botania#1504]
Hey Vaskii, first of all thanks for Botania! I love it!

Soo my server crashes ME only when I try to defeat the Gaia Gaurdian. Whether I'm in god mode or survival doesn't matter. 

So I'm fighting the Gaia Gaurdian and I get him to the 2nd stage where he summons mobs and BAM! I crash on my server and cant get back on. The first time i fought him i was by an EnderIO Killer Joe and when I crashed, I couldn' log on anymore. it didn't give me a crash report so i just looked at the console and it said reason unknown. so i got my friend to go and destroy the Killer Joe item and he crashed also and couldn't get back on the server as well. Well i got a third friend to try and help us out and he didn't crash and destroyed the blocks and we where able to log back in. I did some editing of my modpack and removed AE2 because i seen some bug report online about AE2 and the chicken chunkloader not working right so i deleted the mod. once again i tried to kill the Gaia Gaurdian and i crashed again, but this time i was able to get back on the server. I'm not sure if it has something to do with Enderio because i checked the crash reports or logs and it says something like
caused.by. cant spawn EnderIO entity id #7. not sure if thats completely correct but just saying..

anyways here is the Log you asked for:

https://gist.github.com/anonymous/e1d1bb62508d94402070

Also here is a snippet of the FML Client latest log:

https://gist.github.com/Mariolink93/334134ad5a891498861f

Edit: I traced the coordinates where the game couldn't spawn the EnderIO ID 7 and it turns out it was in the exact same spot where the GG was releasing the mobs.

**Comment by Vazkii** [comment]
Disable EnderIO's wither skeletons in their config.
