### ISSUE TITLE
Dandelifeons generate mana from cells belonging to another Dandelifeon

### ISSUE THREAD

**Issue by Abacor** [Vazkii/Botania#1511]
A Dandelifeon will generate mana from cells which were aged by a different Dandelifeon. This is very easy to abuse and makes it possible to generate a flower-full of mana using a [still life](http://conwaylife.com/wiki/Ship) and very little effort.

**Comment by phantamanta44** [comment]
Dandelifeons should not be able to operate with intersecting fields.

They should also clear their respective fields if mana is generated on any particular step.
