### ISSUE TITLE
Thaumcraft arcane lamp light projections count as obstructions for gaia guardian arena.

### ISSUE THREAD

**Issue by Daenyth** [Vazkii/Botania#1513]
To reproduce, place an arcane lamp ten blocks high outside the arena area. The light projection will be inside the arena and prevent spawning the guardian

**Comment by L0neKitsune** [comment]
I believe the arcane lamps spawn a block called Thaumcraft:blockAiry when placed.  If that's any help.

**Comment by Daenyth** [comment]
@Vazkii Is this fixed with 9c684b3cd86155f273e00553f99571abbba24cdc or is this closed as a "wont fix" ?

**Comment by Vazkii** [comment]
That should fix it

**Comment by Daenyth** [comment]
Thanks!
