### ISSUE TITLE
Crafted Tablet Not Equal to Empty Tablet

### ISSUE THREAD

**Issue by natedogith1** [Vazkii/Botania#1515]
This makes it annoying to filter empty tablets, as you have to filter on both empty and freshly crafted tablets. I believe this probably has something to do with nbt tags not being set on crafting. (Botania 228)

**Comment by Vazkii** [comment]
I don't get what the issue is.

**Comment by mindforger** [comment]
i think what he wanted to state was, an freshly crafted (thereby empty) mana tablet is not the same item like an "used" empty mana tablet which makes it hard to setup filter for
