### ISSUE TITLE
Ring of Loki / Ring of Aesir (Loki's ability) not working.

### ISSUE THREAD

**Issue by Roxforbraynz** [Vazkii/Botania#1519]
The Ring of Loki and it's counterpart ability in the Ring of Aesir simply don't work. They create the wireframes properly showing what blocks are bound, but when placing/breaking blocks, nothing happens, even with a full Greater Band of Mana or even a Creative Mana Tablet.

**Comment by Vazkii** [comment]
Describe exactly what you are doing.

**Comment by Roxforbraynz** [comment]
I right-click on a block making the thicker wireframe, then right-click on a different block nearby making the thinner wireframe, then I right-click the original block as the book said. After that, the thick wireframe disappears and the thin wirefrime of the bound block will move around when I mouse over a different block. When I dig a block such as dirt or grass when the wireframe is over another of the same block, it does nothing. Same goes for placing a block, wether the wireframe is over another block or air.

**Comment by Vazkii** [comment]
Ok, you're not sneaking.

**Comment by Roxforbraynz** [comment]
Having to sneak was not mentioned in the Lexica, but yes, that seems to be what was wrong.
