### ISSUE TITLE
picking up Primus Loci

### ISSUE THREAD

**Issue by Yusunoha** [Vazkii/Botania#1520]
I came across some rare Primus Loci in my survival world (using Infinity Evolved) and I tried picking them up, but whenever I broke them, the plants didn't drop anything. I tried breaking them with my hands, a pickaxe, an axe and also shears, but none of them dropped the flowers.

in the changelog it's mentioned that primus loci are "Rare worldgen flower patches with Primus variants of Dayblooms and Nightshades that don't decay. " so I thought you would be able to pick them up, or is it intended that you cannot pick them up?

**Comment by AlterAkima** [comment]
Read further, the book says they die when you try to pick them up, also, look at their tooltip in NEI.

**Comment by Yusunoha** [comment]
yup, I noticed that aswell when I searched a bit more, derp on my part, sorry.
