### ISSUE TITLE
Worldshaper's Sextant Crash

### ISSUE THREAD

**Issue by ColeBeall** [Vazkii/Botania#1524]
My game crashes when I try to use the Worldshaper's Sextant. I point at a block, right click, and the game crashes after freezing up for a second or two. This happens consistently whenever I attempt to use the item. So far, nothing else causes a crash like this.

FML Log: http://pastebin.com/MGryARw4

**Comment by Titanium237458** [comment]
You don't have CodeChickenCore installed.
Seems like Vazkii imported the wrong Vector class :3

**Comment by ColeBeall** [comment]
Thank you. Didn't realize I needed CodeChicken.

**Comment by TheWhiteWolves** [comment]
You've not supposed to need it, it's happened before it's just a mis-import when using the Vector class.

**Comment by yrsegal** [comment]
shouldn't be that hard a PR
