### ISSUE TITLE
Botania Mana Prism crashing client

### ISSUE THREAD

**Issue by c0rn3j** [Vazkii/Botania#1527]
Prism placed on top of MFR's Harvester harvesting sugar canes results in this crash
http://pastebin.com/HR7MDa0W
Somehow it affected only my friend and not me(I placed it).
http://i.imgur.com/1JXUFYD.png
I got the Mana Prism through Illuminati pet(spawns random items) {Inventory Pets}
http://i.imgur.com/ksrJyKi.png

**Comment by Titanium237458** [comment]
I think the Harvester puts the sugar cane into the prism and the prism tries to render the "lens" it just got. Because sugar canes aren't lenses, it crashes.

**Comment by OJwithC** [comment]
It seems any item can be inserted into the prism via a hopper. (Granted, I'm a few versions behind, so I don't know if it's been fixed.)
