### ISSUE TITLE
Rannuncarpus can't place Harvestcraft's cakes

### ISSUE THREAD

**Issue by AlterAkima** [Vazkii/Botania#1529]
Tested with Botania v230 and Pam's Harvestcraft 1.7.10j
The Rannuncarpus can't place any of the cakes: 

![](http://i.imgur.com/tUZJN7D.png)

**Comment by OJwithC** [comment]
Warning though: last time I used those cakes, they overwrote things like torches, flowers, and other cakes if placed on the same block. ( That's Harvestcraft's problem though.)

**Comment by PsiGuy60** [comment]
Can you place it using, for example, a Block Placer (from OpenBlocks)?
If not, this is Harvestcraft's problem rather than Botania's.

Either way, this probably has something to do with needing to sneak in order to place a Harvestcraft cake. If you use a normal right click, you just eat the cake.

**Comment by Vazkii** [comment]
Not on my end, since they seem to have some weird behaviour.

**Comment by natedogith1** [comment]
MatrexsVigil/harvestcraft#30
