### ISSUE TITLE
Witcerhy "Mog's Quiver" and any Botania Bow w/ mana derpage

### ISSUE THREAD

**Issue by PokeMaserJ** [Vazkii/Botania#1530]
When wearing a "Mog's Quiver" from Witchery, and shooting with a Botania Bow w/ mana in your inventory shows the bow (s) as taking damage, as in no mana. But here's the weird thing, they DON'T take damage, just looks like they do. If you drop the bow change to another inventory tab, like the Baubles, either of the TiCon ones (Knapsack, or the one where you place the Heart Canisters), or open a chest, it "corrects" it self. Here's the weird part. I tested with the Redstone Arsenal bow and a Capacitor from Thermal Expansion, and it works, well, besides one thing, which I am going to see if it's been reported on Redstone Arsenals side, since Witchery doesn't have a GitHub for some reason... and if it's not reported, I'll make one.

**Comment by Vazkii** [comment]
What's that item supposed to do? If it causes damage to the bow it's possible there's a desync going on. Either way it doesn't sound like a problem.

**Comment by OJwithC** [comment]
The quiver provides unlimited arrows for bows (also makes the arrows travel faster and apply Weakness).
