### ISSUE TITLE
Luminizers drop the player at wrong location

### ISSUE THREAD

**Issue by I-Need-A-Username** [Vazkii/Botania#1531]
When using a pair of luminizers that are placed vertically from another, attempting to get off will place the player at the top luminizer, regardless of where they player is on the path between the two luminizers.
FML Log: http://pastebin.com/PqZ7W5en

**Comment by I-Need-A-Username** [comment]
This only happens when the player boards at the top luminizer.

**Comment by Vazkii** [comment]
Screenshot please.

**Comment by I-Need-A-Username** [comment]
http://i.imgur.com/7X7C99J.png
The stone is next to the luminizer blocks. The block between the two is an abstruse platform, but its presence does not effect the issue.
Also, in this recreation, it does not matter whether you board at the top or bottom luminizer; it will always drop you at the luminizer you boarded at.
As a side note, they are properly bound to each other.

**Comment by Vazkii** [comment]
I can't reproduce, it always drops me properly.
