### ISSUE TITLE
Crash with New Lexica Botania

### ISSUE THREAD

**Issue by I-Need-A-Username** [Vazkii/Botania#1532]
Whenever I open the Lexica Botania that has been updated for new visuals and such, the game immediately crashes. This happens with all version starting from when it wa originally changed.
FML Log: http://pastebin.com/PqZ7W5en
Crash Report:http://pastebin.com/Gj8RNz5B

**Comment by AlterAkima** [comment]
Botania wasn't mentioned in the FML loading log.

**Comment by mindforger** [comment]
your forge is heavily outdated! try update forge first
