### ISSUE TITLE
v231 Lexica Botania makes screen go completely black, can't escape

### ISSUE THREAD

**Issue by seajay1221** [Vazkii/Botania#1533]
Entering into the Lexica Botania in the newest update, 231, causes the screen to go black. Pressing esc and clicking mouse buttons doesn't help. Game doesn't seem to crash (nothing weird in crash log) but must be quit to restart.

**Comment by Vazkii** [comment]
Give me a log. I also need to know which graphics card you're using. If this didn't happen in 230, try changing "shaders.secondaryUnit" to 6, if that doesn't work, try 15.

**Comment by I-Need-A-Username** [comment]
I've had the same issue. I changed the specified value in the config to 6, and then to 15, but that didn't help. When I changed it to 6, nothing changed, and when I changed it to 15, I crashed upon opening the Lexica Botania.
However, I can say that although the screen goes black, it doesn't completely fade out. I could still just barely make out the game (shown in this screenshot http://i.imgur.com/Ujf08Mc.png ), and it was still running, since I could hear the sound of re-opening my Lexica Botania. I was able to log out of my world, open it back up, and exit again without a problem, since I knew where to click.

Crash Report from value set to 15: https://gist.github.com/I-Need-A-Username/d288e5755ad0c021573f#file-gistfile1-txt
FML Log with value set to 15: https://gist.github.com/I-Need-A-Username/e0a753e24258a1a7a095#file-gistfile1-txt
FML Log with value set to 6: https://gist.github.com/I-Need-A-Username/0b57541f56e44d7e393a#file-gistfile1-txt
FML Log with value set to default of 7: https://gist.github.com/I-Need-A-Username/273f264279009962e6c2#file-gistfile1-txt

**Comment by seajay1221** [comment]
This definitely didn't happen in 230. Playing with it a bit more, it's only the Lexica Botania's splash page that makes the world go dark. Using the Lexica on items in the inventory or the world is just fine and takes you to the right page, which renders fine. It's only when opening the Lexica for the first time after logging in or when backing out to the main page that things get weird. As I-Need-A-Username noticed, the screen doesn't go completely black. It just gets super dark. Here's are two screenshots. The first is of me trying to use the Lexica after the world went dark. There's a flower (Flowey?!) showing up when you mouse over that area, and that's it. The second is a shot of what the world looks like.
Here's a log. It doesn't really paint much of a picture. 
http://pastebin.com/xe9xfAdT
My computer is a Macbook with integrated graphics. Intel HD Graphics 4000 1536 MB

**Comment by AlterAkima** [comment]
Shader types 6 and 7 cause the screen to go dark here, but type 15 works fine, the problem is not consistent across all Intel HD Graphic 4000 cards.

**Comment by I-Need-A-Username** [comment]
I forgot to mention earlier that I have an ATI Radeon HD 2600 XT 512 MB

**Comment by seajay1221** [comment]
Shader to 6 doesn't change anything. Shader to 15 fixes the rendering on that page but slows FPS ingame to about 1fps. Not playable.

**Comment by Vazkii** [comment]
@seajay1221, does your log get filled with GL errors with shader 15? Can you try other values from 0 to 7 (resetting the game every time)?

**Comment by seajay1221** [comment]
I will be happy to do so, but I’m at work now and won’t be able to test that out for several hours.


On November 11, 2015 at 1:57:11 PM, Vasco Lavos (notifications@github.com) wrote:

@seajay1221, does your log get filled with GL errors with shader 15? Can you try other values from 0 to 7 (resetting the game every time)?

**Comment by Vazkii** [comment]
Anyone else who's having the same problem could also try this out. If nothing works, disable shaders altogether.

**Comment by I-Need-A-Username** [comment]
When I brought the shaders value down to 1, my problem was fixed. The screen visibly darkens when I initially open the Lexica Botania, but it's easily readable, and it brightens back up once I go into a page or exit the book.

**Comment by Vazkii** [comment]
I wouldn't use 1, minecraft uses 1 for the lightmap.

**Comment by I-Need-A-Username** [comment]
When I bring it down to 0, there are no problems with lighting, but this happens.
![2015-11-11_13 36 05](https://cloud.githubusercontent.com/assets/15763131/11102345/305e68e8-8879-11e5-8cb9-367adf8cec57.png)

**Comment by Vazkii** [comment]
That's normal.

**Comment by Vazkii** [comment]
Try deleting your config file and trying this again with 232.

**Comment by devemouse** [comment]
Nvidia GeForce GT 750M
Same here. Changing to 6 didn't work but 15 did.

**Comment by grompe** [comment]
Here "shaders.secondaryUnit" set to 7 or 6 leads to blackening, 15 works as normal.

![Botania debug screen](http://i.imgur.com/wEwEGkP.png)

**Comment by Vazkii** [comment]
Hm, ok. Anyone who is having any problem whatsoever, please describe it **exactly** (and not just "same as that guy"), with a screenshot of their context (CTRL+SHIFT on the F3 menu).

@grompe Do you get any lag with 15 or GL errors in your console while you open the book

**Comment by grompe** [comment]
@Vazkii, I can see no lag, no GL errors, 15 works just fine for me.

**Comment by Kurbz** [comment]
When I open the Lexica Botania, the entire game begins to lag heavily. By that I mean that everything gets sluggish. Mouse movement, keyboard input, etc. The book opens and you can somewhat navigate around it. However after a short period it begins to be nearly non-responsive. It does so in any menu. That is, the book menu, inventory screen, or even the pause/alt tab screen.

I have moved around and reloaded the world fine. And everything works brilliantly before opening the book. No lag, no issues.

SSP, Slightly altered Infinity (added Iguana Tinker Tweaks and Minechem).

I have the log for the relevant time period, but I'm unsure of how much use it is.

http://pastebin.com/HvCFs1WV

All it really shows is the loading of the world, a bit of moving and looking around, opening the book, and then alttabbing. I can give full load-up sequence log if that would help more.

Thats from my other issue. This is the complete startup log: http://pastebin.com/fADvgr9A

As for the black screen issue, and this is on build 232 not the same as the others. I get mostly the same experience, sudden black screen and game non-responsive. One time I did notice that I could move around a bit and see some things in dark grey (Birch trees and sand I think it was). Couldn't reproduce.

Screenshot you asked for: http://imgur.com/IkGkqVz

**Comment by MTH-Gamer** [comment]
Every time I open the Lexica, my screen goes black after I updated to v231. It has stopped happening, when I updated to v232 and set the shaders.secondary Unit to 15. Hope this can help.

**Comment by howtonotwin** [comment]
Adding my info to the mix: running on Intel HD Graphics 4000 with driver 10.18.10.4276. Set option to 15, no lag, no errors.
F3 Shift+Ctrl:
![2015-11-12_18 08 12](https://cloud.githubusercontent.com/assets/15616055/11134256/524f604c-8969-11e5-819e-fc0d68118d4a.png)
(My computer is poopy; don't worry about FPS.)
But in the Lexica it looks like this, and I'm not sure if that's intended or a lingering issue:
![2015-11-12_18 08 37](https://cloud.githubusercontent.com/assets/15616055/11134290/85e29c62-8969-11e5-8335-c3537d59f554.png)
(The icons fill in while moused over.)

**Comment by Vazkii** [comment]
Should be fixed with 233.

**Comment by seajay1221** [comment]
It's fixed in 233. Thanks so much Vazkii!
