### ISSUE TITLE
Placing Managlass or Alfglass into an abstruse platform shows no texture

### ISSUE THREAD

**Issue by I-Need-A-Username** [Vazkii/Botania#1535]
When disguising an abstruse platform with one of the two managlass types, it becomes completely invisible and shows no texture at all except for the wireframe. This does not happen with vanilla glass.
![2015-11-11_12 43 22](https://cloud.githubusercontent.com/assets/15763131/11101073/284d8000-8872-11e5-99af-c6e6cd188891.png)
![2015-11-11_12 43 25](https://cloud.githubusercontent.com/assets/15763131/11101081/30066d0c-8872-11e5-85dd-e743da4ef8dd.png)

**Comment by Vazkii** [comment]
To be honest, I can't do much about this because of they using a different render pass. Consider this a feature!

**Comment by AEnterprise** [comment]
sounds like a usefull feature, allowing you to make the abstruse platform invisible
