### ISSUE TITLE
Corporea Interceptor doesn't intercept request for multiple items from Corporea Funnel

### ISSUE THREAD

**Issue by Shoob189** [Vazkii/Botania#1536]
Botania r1.7-230 (in Regrowth 0.8.4 mod pack)

When requesting 16, 32, or 64 of an item with the Corporea Funnel, Interceptor does not emit a redstone signal even when Corporea Network contains 0 of the requested items. Tested using coal and baked potato. Requests for those amounts using a Corporea Index trigger the interceptor as expected.

**Comment by Vazkii** [comment]
https://github.com/Vazkii/Botania/commit/767cd39036f399e8da5277fb781ee5fbaae3a4d9
