### ISSUE TITLE
Shooting Drum of the Wild with phantom mana lens does not stop mana burst

### ISSUE THREAD

**Issue by I-Need-A-Username** [Vazkii/Botania#1537]
I'm not sure if this is even a problem or not, but I noticed that shooting a Drum of the Wild with a mana spreader equipped with the phantom mana lens activates the drum, but the burst continues going on.
This first screenshot shows the path of the burst going through the Drum.
![2015-11-11_15 28 22](https://cloud.githubusercontent.com/assets/15763131/11105047/af057c58-8889-11e5-9e76-9fe2c639d250.png)
This second screenshot shows the point at which the burst starts to lose its mana, which is below the drum.
![2015-11-11_15 28 40](https://cloud.githubusercontent.com/assets/15763131/11105050/b4cf6a36-8889-11e5-8234-98e19a914275.png)
The only reason I can think of this being a problem is that you can essentially activate the drum of the wild at no mana cost if you harvest the burst.

**Comment by Vazkii** [comment]
Meh, no problem.
