### ISSUE TITLE
v232 and v299 issue opening Lexica Botania

### ISSUE THREAD

**Issue by Kurbz** [Vazkii/Botania#1538]
When I open the Lexica Botania, the entire game begins to lag heavily. By that I mean that everything gets sluggish. Mouse movement, keyboard input, etc. The book opens and you can somewhat navigate around it. However after a short period it begins to be nearly non-responsive. It does so in any menu. That is, the book menu, inventory screen, or even the pause/alt tab screen. 

I have moved around and reloaded the world fine. And everything works brilliantly before opening the book. No lag, no issues. 

SSP, Slightly altered Infinity (added Iguana Tinker Tweaks and Minechem). 

I have the log for the relevant time period, but I'm unsure of how much use it is.

http://pastebin.com/HvCFs1WV

All it really shows is the loading of the world, a bit of moving and looking around, opening the book, and then alttabbing. I can give full load-up sequence log if that would help more.

**Comment by Vazkii** [comment]
Pitch in on #1533
