### ISSUE TITLE
Random server crashes

### ISSUE THREAD

**Issue by oleg599** [Vazkii/Botania#1541]
Crash report: http://laravel.io/bin/52jwG (because pastebin is went down at current time)
Botania b231

**Comment by Vazkii** [comment]
What the actual hell did you do to acomplish this?

**Comment by oleg599** [comment]
This crash report does not show block, but simmilar crash with SOE give coords, when entering to problematic chunk - client FPS is less than 5-10 and server will be crashed.
Screenshot: http://take.ms/pkNbx

**Comment by Vazkii** [comment]
Same gist as  #1542
