### ISSUE TITLE
Console flood when loading chunk

### ISSUE THREAD

**Issue by oleg599** [Vazkii/Botania#1542]
Log: http://pastebin.com/5trnxXAH
Problematic chunk screenshot: http://take.ms/DLqvr

Because of what it can be?

**Comment by yrsegal** [comment]
well you are just a bundle of edge cases, aren't you? o.o

**Comment by Vazkii** [comment]
I'm going to have you run through the guidelines for this one. Too many variables at play. https://github.com/Vazkii/Botania/blob/master/contributing.md
