### ISSUE TITLE
Server crash - java.lang.IllegalArgumentException: Don't know how to add class vazkii.botania.common.entity.EntitySpark! Report this error to mod author.

### ISSUE THREAD

**Issue by ProsperCraft** [Vazkii/Botania#1546]
http://pastebin.com/dZ0r6qLf

**Comment by Vazkii** [comment]
Can you reproduce with only botania?

**Comment by ProsperCraft** [comment]
It was a one time crash which has not repeated on a server with many many people, I would not know how to repeat I am sorry.

**Comment by GirafiStudios** [comment]
Most likely related to the server running on cauldron.
