### ISSUE TITLE
Visual bug when mana bursts pass through leaves. Version 233

### ISSUE THREAD

**Issue by acpcalin** [Vazkii/Botania#1548]
Mana bursts don't seem continous when passing through leaves.
![2015-11-14_18 33 57](https://cloud.githubusercontent.com/assets/9417983/11164622/79900102-8afe-11e5-93b0-b502b5bf5b27.png)
![2015-11-14_18 33 59](https://cloud.githubusercontent.com/assets/9417983/11164621/798ddfe4-8afe-11e5-9f01-54d610e19d7c.png)

**Comment by AlterAkima** [comment]
It happens whenever a burst travels inside a block, best visualized with the Phantom Lenses.

**Comment by yrsegal** [comment]
Bore lens is a good visualisation too, when it breaks a block it appears to rise.
