### ISSUE TITLE
Recessive Spark not emptying mana pool.

### ISSUE THREAD

**Issue by Rasmun** [Vazkii/Botania#1549]
I have several mana spreaders that point to a single mana pool with a recessive spark on it.  That recessive spark fills several other pools.  I setup a BC Basic gate next to the mana pool (with the Recessive spark) to monitor when the mana pool is empty.  However, this mana pool never empties, even when several of the other mana pools it feeds run out of mana.  The recessive spark leaves behind a bit of mana, so the gate never triggers.  If I drop a mana tablet in there to suck out the last bit of mana, it empties the pool, which triggers the gate, but I am trying to automate my mana production based on this single pool being empty.

Any chance this can be considered a bug and fixed?  Thanks.

Note:  I am using Botania r1.7-221.jar, at least until I can get this automation running and then I will abandon my passive mana generation for this automation I am trying to create.

**Comment by thejims** [comment]
Probably working as intended, you can use comparators on manapools to determine when they are close to empty.  
But, for example why it may not be easy to 'completely' empty the manapool..
You generate 10 mana 
You have 3 other mana pools to distribute to
3 mana goes to each pool
1 mana is left behind
