### ISSUE TITLE
Idea: Corporea Crystal Cube ideas

### ISSUE THREAD

**Issue by thejims** [Vazkii/Botania#1550]
Two ideas, the first is more of a cosmetic request:
1. Make Corporea Crystal Cubes rotatable  similar to logs in that it's base would be on the side of the block clicked to place it, this way you can have them hanging from the ceiling or sticking out from the wall.
2: Make Corporea Crystal Cubes work like item frames when attached to a side of a corporea funnel or interceptor, or just develop a replacement for item frames, please?

**Comment by Vazkii** [comment]
What's wrong with item frames?

**Comment by thejims** [comment]
They tend to randomly dissapear in smp
