### ISSUE TITLE
Mana spreader stops firing after a few shots, fills up

### ISSUE THREAD

**Issue by grauerkoala** [Vazkii/Botania#1551]
Greetings!

I'm using this setup to generate a whole bunch of mana from Endoflames: https://imgur.com/QVr6If6

However, the Elven Mana Spreader only fires a few shots into the Mana pool opposite it across the pressure plate, then stops. The entire time, even when it's still working, it's completely filled up (like in the screenshot above).

There are 12 Endoflames in that setup, all bound to that one Elven Mana Spreader; also there is a Solegnolia for no-coal-sucky-uppy reasons and an Exoflame on that dirt block next to the three furnaces that cook up the charcoal. Finally, there is a ComputerCraft computer doing nothing else than compare the outputs of the coparators, thus deciding by means of a redstone output from its top if coal can make its way into the Open Crate.

The same issue occurs when I swap the Elven Mana Spreader for a regular old Mana Spreader.

Curiously enough, however, the spreaders either side of the Mana Pool next to the pressure plate work great when I bind a few of the Endoflames to them. When I do that, coal continues to be consumed (which it isn't before on account of both the Mana Spreader and the Endoflames being full of mana), which appears to trigger the Elven Mana Spreader into working again temporarily.
Because of that, I'm assuming that the redstone emitted by the pressure plate stops the Elven Mana Spreader from working, which shouldn't be the case since both an Elven Mana Spreader and a regular Mana Spreader (unless the latter is upgraded, that is) are not supposed to be controllable using redstone. Maybe the spreader starts working again because of a block update? ... I'll just stop now.

Here's the utterly crowded log: http://pastebin.com/7bJHspKc

I'm using the latest version of Botania (R1.7 233), the recommended version of Forge (10.13.4.1558) and FastCraft (1.21), if that's at all of interest to you. All of them are accompanied by a bunch of mods I gathered, not all of them up-to-date (if only it was an FTB-pack that took care of that for me...): http://pastebin.com/M781mPGc

This issue *may* be related to these: #836, #265

I hope this includes at least the basics of what you need to know. If it doesn't, feel free to poke me into investigating further or gathering other information regarding this.

Oh, also: love this mod.

Cheers, koala

**Comment by grauerkoala** [comment]
Detail that I forgot to include: Closing the game and loading it again makes the Mana Spreader work again for a few shots.

**Comment by OJwithC** [comment]
Why do you think they shouldn't be controllable by redstone?
"Applying a Redstone Signal to the spreader will have it cease to function."

**Comment by Vazkii** [comment]
Your pressure plate is stopping the spreader.

**Comment by grauerkoala** [comment]
Oh man, had this filed as "should not react to redstone unless upgraded".
Sorry for the trouble, I feel like a fool.
