### ISSUE TITLE
Multibreaking does not work outside of the normal zone using the ring of far reach

### ISSUE THREAD

**Issue by hacatu** [Vazkii/Botania#1552]
When using the ring of far reach and a tool that can break multiple blocks like a tinker's construct hammer or a terra shatterer of rank other than D, only the block clicked is broken if it is outside of the normal range one would be able to reach without the ring.  This is in Botania 232 and forge 10.14.4.1448-1.7.10 for minecraft 1.7.10, although I recall experiencing the issue beginning in Botania 220 (I never used an earlier version but presumably it was a problem then too).  Here is the fml log (although I have a lot of other mods installed): https://gist.githubusercontent.com/hacatu/ffc27973089653a8e6ce/raw/0164eb79ef317f20f7760ece25dd1eb2b7330f15/fml-client-1.log.

**Comment by Vazkii** [comment]
I can fix this for the Terra Shatterer, but not for the TCon tools.

Both require a raytrace, which needs a distance defined. Obviously you'd define the player reach. The extension requires a change that is not visible to other mods, unless they choose to use the botania api's [IExtendedPlayerController](https://github.com/Vazkii/Botania/blob/master/src/main/java/vazkii/botania/api/item/IExtendedPlayerController.java), there's no way to make this work on their side.

paging @bonusboni

**Comment by Vazkii** [comment]
Update: I can't reproduce this. The Terra Shatterer breaks blocks just fine for me with the ring equipped.
