### ISSUE TITLE
Botania Shears don't disarm tripwires as normal shears. (Just close this issue >->)

### ISSUE THREAD

**Issue by Tristaric** [Vazkii/Botania#1555]
If you break tripwire with your hand, it'll set off a redstone signal for a moment, even though there's no entities on the tripwire.
If you break tripwire with vanilla (iron) shears, it won't set off the redstone signal.
However, Botanai shears (both manasteel and elementium) don't disarm the tripwire like normal shears. If you break tripwire with Botania shears, it'll trigger the redstone signal.

I'd like to see this fixed, thanks :3

**Comment by Tristaric** [comment]
Nevermind, tis unfixible.

**Comment by Tristaric** [comment]
And I never read the lexica's disclaimer >->

Waaaay to go Tristaric

**Comment by TheWhiteWolves** [comment]
just to let you know, you can close issues that you opened yourself

**Comment by Zsashas** [comment]
Why is this unfixable, though? Just vanilla being stubborn?

**Comment by L0neKitsune** [comment]
Breaking tripwires is hardcoded to check only for vanilla shears.
