### ISSUE TITLE
Mutated Grass Missing Texture

### ISSUE THREAD

**Issue by Tristaric** [Vazkii/Botania#1556]
(Just a headsup, I have intigrated graphics.)

The sides of the Mutated Grass block added in V234 has the missing texture pattern on it. This is only on the sides, not on the top.

I've tried this with both optifine installed and uninstalled, missing texture with both instances.

**Comment by Entoarox** [comment]
Verified, the texture file has a lower case g in grass when a upper case G is expected.

**Comment by Vazkii** [comment]
Ah, the old "case matters in compiled but not in dev", will fix.
