### ISSUE TITLE
Suggestion: Dyable Manaweave Armour (Using Floral Powder)

### ISSUE THREAD

**Issue by Tristaric** [Vazkii/Botania#1565]
I was looking at the manaweave armour, and thought "This'd look good in black." So, I tried to craft it with black floral powder, sadly, it did not work.

So, I came on github, and posted it as a suggestion for the all mighty Vazkii to read >->

(no srsly, this'd be awesome to have.)

**Comment by yrsegal** [comment]
I could probably PR it if I wasn't lazy
