### ISSUE TITLE
Wand Rotation Changes Mode

### ISSUE THREAD

**Issue by natedogith1** [Vazkii/Botania#1570]
Rotating things via the wand of the forest shift-click functionality causes the wand to change between bind mode and function mode.

**Comment by Vazkii** [comment]
I tried, I can't fix this in a way that isn't crazy hacky. Sorry.

**Comment by natedogith1** [comment]
Wouldn't returning true if block.rotateBlock (at https://github.com/Vazkii/Botania/blob/master/src/main/java/vazkii/botania/common/item/ItemTwigWand.java#L86) returns true work? Or am I missing something?

**Comment by Vazkii** [comment]
Yes. That's what I thought. However, block.rotateBlock returns false on clients every time, which means the right click event gets passed to the server, which changes the wand's mode.
