### ISSUE TITLE
Alfheim Lenses entry kicks to main menu

### ISSUE THREAD

**Issue by Zsashas** [Vazkii/Botania#1571]
It happens when the arrow to go back to the previous entry is clicked (from any page in the entry). What's odd is there is absolutely no transition, and nothing in the console whatsoever. Re-entering the game shows that everything saved properly, but it's still odd.

**Comment by Vazkii** [comment]
Can't reproduce.

**Comment by Zsashas** [comment]
Now it does it for the Rod of the Bifrost entry, and the Elven Mana Lenses entry is fine...

Also doesn't happen every time...I've been trying to capture a video of it, but it never happens when I do this.

**Comment by Zsashas** [comment]
It hasn't happened again, but it may be that the problem moved to another entry again. If the problem re-appears, I'll add a comment. But for now it appears to be gone.
