### ISSUE TITLE
Witchery wiki integration doesn't respect case-sensitiveness of google sites

### ISSUE THREAD

**Issue by the-vindex** [Vazkii/Botania#1573]
When I right-click Spanish Moss, web browser goes to
https://sites.google.com/site/witcherymod/Spanish-Moss

Which does not exist, because it's case sensitive. By lower-casing URL it's fixed
https://sites.google.com/site/witcherymod/spanish-moss

**Comment by catzs** [comment]
Wrong page?...
Try http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/1445248-witchery-0-24-1

**Comment by Nincodedo** [comment]
He's talking about the Lexica's wiki integration.

**Comment by TheWhiteWolves** [comment]
This is due to the capitalisation that happens on (Line 64)[https://github.com/Vazkii/Botania/blob/master/src/main/java/vazkii/botania/api/wiki/SimpleWikiProvider.java#L64] in the SimpleWikiProvider.

Witchery doesn't capitalise their names thus to incorrect link is created.
