### ISSUE TITLE
Featherfeet effect stopping tiara gliding function

### ISSUE THREAD

**Issue by TheWhiteWolves** [Vazkii/Botania#1577]
The featherfeet potion effect granted by a livingwood avatar holding a rod of the skies when you jump stops the tiara glide effect from triggering. (due to the minimum 2 block fall distance bot triggering)

As discussed possible solution to test: Set featherfeet fall distance to 2.5 to allow 2 block fall distance but prevent fall damage at 3 block fall distance

**Comment by Zsashas** [comment]
You don't usually take fall damage from falling two blocks anyway, do you? So 3 blocks would make more sense.

Unless you mean 2 blocks past the safe distance...

**Comment by TheWhiteWolves** [comment]
@Zsashas :

The way the fall distance negation works is that we constantly reset the distance the player has fallen to 0, this makes the game think that the player has not fallen any distance and thus no damage.

As far as we can remember the damage from falling starts at 3 blocks so if we have featherfeet set it to 2.5 instead of 0 then it should still negate the fall damage but also allow the gliding to still trigger.
