### ISSUE TITLE
superflat garden of glass

### ISSUE THREAD

**Issue by wesleybruce** [Vazkii/Botania#1578]
It's probably not recommended to try gog on a superflat world but I have. I have a fear of heights which is why I tried it. The recipes work but nothing else gog added does. shift right clicking dirt and getting melon and pumpkin seeds don't seem to work. That's not the bug, I expected that. The bug is that if you open a Lexica Botania in the super flat all the lighting goes even in the exit screens and splash screens. The world loses all it's light shaders. The book is black, everything else is greys or blacks and it effect's menus, inventory, start exit screen and gui's. I have to find the save and exit game buttons by guess work. I will check if it's happening in the overworld and if its height based so this is a preliminary report. I can make a video of it if needed. It does look rather amazing.
I want to do a botania based, mod racing hqm challenge map and want botania gog in it but I may need to go with a classic botania + an orechid.

**Comment by OJwithC** [comment]
What version of Botania are you using?

**Comment by TheWhiteWolves** [comment]
make sure you are on the latest version (R1.7 235) and you have deleted your configs.

**Comment by wesleybruce** [comment]
It's fixed now and spectacularly fast fix too done by the time I longed out and got back into the game.
