### ISSUE TITLE
Mana lenses don't render properly in the Assembly/Manufactory Halo

### ISSUE THREAD

**Issue by Roxforbraynz** [Vazkii/Botania#1579]
![Screenshot](http://i.imgur.com/0D8mNXK.png)

**Comment by yrsegal** [comment]
more information: This applies to any multipass item. Pass 1 is 90º away from pass 0, no matter which face of the Halo it is on.
![2015-11-23_19 54 00](https://cloud.githubusercontent.com/assets/6596492/11354719/164c8bcc-921c-11e5-9d6d-6b44aeabee5c.png)
