### ISSUE TITLE
Endoflames consume items instantly from catalysts

### ISSUE THREAD

**Issue by VortexJD** [Vazkii/Botania#1583]
When dropping items into a mana pool with either an alchemy or conjuration catalyst beneath, nearby endoflames consume the result (assuming it's combustible) immediately.  Examples are; saplings in the alchemy catalyst; and coal in the conjuration catalyst.  I can't find any mention of this interaction in the Lexica Botania.  It's possible this is by design, but since it's not defined in the book, and it's not consistent with how the endoflame normally works, I'm assuming this is a bug.

I tested this using latest Forge and only installing latest Botania.

**Comment by Zsashas** [comment]
Even stranger considering the Endoflames don't even consume normally dropped fuel instantly, there is always a slight delay.

...it must be considering it still the same item, so the delay already happened.

**Comment by yrsegal** [comment]
I believe it's because the pickupDelay is set to minimum when an item is transmuted. The endoflame then thinks the item has been there for a while.

**Comment by VortexJD** [comment]
I don't see any commits related to this and while there is some feedback here, I see no consensus if this is intended or not.  Does this result mean working as intended?

**Comment by yrsegal** [comment]
WAI, she closed it on stream.

**Comment by Vazkii** [comment]
Yes, it's working as intended.
