### ISSUE TITLE
Gaia Guardian syncing issues

### ISSUE THREAD

**Issue by zlainsama** [Vazkii/Botania#1586]
When you summon a guardian (enhanced or not), there's two guardian summoned. One on the server side, and another on the client side.
Causing music issues and after you defeating the actual guardian, you can't leave the area.

Video showing the issue: https://youtu.be/-rJjE_4PhMU

Client Info: 1.7.10, Forge 1448, Optifine U C1, fastcraft 1.21.
Server Info: 1.7.10, Forge 1448, No Optifine, fastcraft 1.21, Not Cauldron.

Edit: I can provide a mod list if needed. And botania version is 235.

**Comment by yrsegal** [comment]
https://github.com/Vazkii/Botania/blob/4365522ee701322f78c466ef61f327153673d6f0/src/main/java/vazkii/botania/common/entity/EntityDoppleganger.java#L205 seems like the relevant line. Should just require an isRemote check.
