### ISSUE TITLE
New Pasture Seeds do not spread vertically

### ISSUE THREAD

**Issue by Zsashas** [Vazkii/Botania#1587]
https://i.gyazo.com/6299463492e778376adfa13cdb7d767e.mp4

Ideally, the special grass types would spread up and down one-block slopes, but they don't.

**Comment by Vazkii** [comment]
Non issue.

**Comment by Zsashas** [comment]
Aren't they aupposed to spread similar to normal grass?

**Comment by Vazkii** [comment]
They'll spread normally over time.

**Comment by Zsashas** [comment]
Oh ok. So it's only the initial burst that's horizontal-only.
