### ISSUE TITLE
[Bug] Graphical Glitches

### ISSUE THREAD

**Issue by tjsd** [Vazkii/Botania#1594]
Water is not visible when looking through alfheim portal - http://imgur.com/a/hsy1f

The particles on runic altar when passing over a manapool makes the manapool see through. But I could not recreate this for screenshots at the moment.

Edit: Pack - FTB Inifnity Evolved v2.1.3 (Expert Mode)
Botania Version: 1.7 (233)

**Comment by AlterAkima** [comment]
https://github.com/Vazkii/Botania/issues/822

**Comment by TheWhiteWolves** [comment]
This is a bug in vanilla, nothing we can do about it.
