### ISSUE TITLE
Livingwood Burn Time not removable

### ISSUE THREAD

**Issue by Zsashas** [Vazkii/Botania#1595]
I tried using MineTweaker to remove the burn time of Livingwood and Mana Spreaders so my Endoflames wouldn't eat them, but when tested, they still take them. The script did change the burn time to 0 for both, and MineTweaker wiki says that should remove it as valid furnace fuel.

**Comment by Vazkii** [comment]
That's a vanilla thing. Wooden blocks  always have 30 ticks of burn time, I didn't set them myself.
