### ISSUE TITLE
Giving Botania:specialFlower gives undefined flower

### ISSUE THREAD

**Issue by JRoffel** [Vazkii/Botania#1598]
Cheating in a flower through "/give [playername] Botania:specialFlower" gives you an undefined flower. 

(I know you shouldn't cheat, but this time it's okay, as it uncovered a (possible) minor bug. Also, I didn't feel like crafting another Thermalily.)

**Comment by AlterAkima** [comment]
The flowers are defined by NBT.

**Comment by JRoffel** [comment]
I know they are, but giving a Botania:Flower also just gives the white one by default, so he could maybe add a default for Botania:specialFlower too. Also only reporting this because my flower told me to, I don't normally report bugs :/

**Comment by AlterAkima** [comment]
It would be a bug if you got the undefined flower when crafting or breaking it, creative menu works fine

**Comment by bookerthegeek** [comment]
@JRoffel if you define the nbt data you won't (shouldn't) get that error.

**Comment by Zsashas** [comment]
I would have guessed this to default to giving a Pure Daisy or something.

**Comment by t0rched** [comment]
I get this error whenever spawning most botania items from NEI in creative. I can seem to figure out what /i command to pass to NEI to include the type: field. Please help.

**Comment by williewillus** [comment]
`/give @p botania:specialFlower 1 0 {type: endoflame}`

**Comment by t0rched** [comment]
How would I structure this for NEI client side config? IE, the Daybloom. 

And ty...

**Comment by t0rched** [comment]
It seems I just get this error on client side:

![image](https://user-images.githubusercontent.com/20378331/27774544-dccda3ba-5f59-11e7-9748-6580d7d0493f.png)

![image](https://user-images.githubusercontent.com/20378331/27774545-eb814d3a-5f59-11e7-90e6-e30240e63593.png)


![image](https://user-images.githubusercontent.com/20378331/27774542-ce3735a0-5f59-11e7-85a2-9cefdb9b80ed.png)
