### ISSUE TITLE
Crash when deleting a bookmark

### ISSUE THREAD

**Issue by Mustang351c** [Vazkii/Botania#1600]
When attempting to delete a bookmark, the game crashes. Here is the report:
[crash-2015-11-30_20.14.55-client.txt](https://github.com/Vazkii/Botania/files/48033/crash-2015-11-30_20.14.55-client.txt)

**Comment by TheWhiteWolves** [comment]
Fixed by 994c8821f324ac6ae5af610ac7c06d6742aef5cc
