### ISSUE TITLE
Compatability Bugs

### ISSUE THREAD

**Issue by Stormalisk** [Vazkii/Botania#1602]
So been playing around with the mod, found two minor bugs. Normal flowers can be put into carpenter's pots but motif versions of the functional flowers cannot.

Also, been using ZZZZZZCustomConfigs mod to make tall flowers drop themselves when broken, though any with an metadata of 2 or 3 (and their top counterparts) will not work unless broken from only the bottom. The rest work fine.

**Comment by yrsegal** [comment]
the 2/3 error might be due to extending BlockDoublePlant. I was running into issues with that with my grasses in BotAdd.
