### ISSUE TITLE
[Request] Option to reverse sneaking behaviour for Ring of Magnetization

### ISSUE THREAD

**Issue by PrincessRTFM** [Vazkii/Botania#1608]
I love using the Ring of Magnetization, but it can a bit annoying to have to take it off when I get home so I don't pick up things from my farms. As it works now, it stops pulling when the player is sneaking. Could you add a configuration option to invert that behaviour, so it only pulls when the player is sneaking?

**Comment by JRoffel** [comment]
That would indeed be a really cool feature, and very useful near my opencrate+endoflame setup, that way I won't get home with an inventory full of coal coke after walking past that.

**Comment by AlterAkima** [comment]
Or you could try the recommended path: the Solegnolia.

**Comment by JRoffel** [comment]
The problem with the Solegnolia is that it fully blocks the ring, so that when I were to put one near my house, I can't use the ring at all, while when inverting behavior, I still keep the ring feature. (Maybe instead of a config option, you could add an alter recipe that fuses the Solegnolia and the ring together, inverting it's behaviour

**Comment by PrincessRTFM** [comment]
An "upgraded" ring would work great, and I like the idea of fusing it with the Solegnolia! Maybe a runic altar recipe? Either way, I would rather not just use the flower, because that wouldn't let me use the ring at all within range, and would also require placing a bunch of Solegnolias around my home.

**Comment by Zsashas** [comment]
I believe this USED to be a thing, where shift-right clicking with the ring inverted the behaviour. No idea why this was removed.

**Comment by TheWhiteWolves** [comment]
Closed by d4d7bef73e24542103bd176a5bb8cefc8a588167
