### ISSUE TITLE
Various armor visual problems

### ISSUE THREAD

**Issue by Roxforbraynz** [Vazkii/Botania#1609]
All helms but the Manaweave one suffer from Z-fighting and their model is a bit small so the hat layer on a player's skin covers part of them.

http://imgur.com/a/ghVV1

**Comment by TheWhiteWolves** [comment]
@wiiv this something you can sort?, maybe make em a touch bigger to clear the hair layer on the player

**Comment by Roxforbraynz** [comment]
I'd like to add on after inspecting the helms further for anything I may have missed, one side of the noseguard of the terrasteel helm has an offset UV map.

http://i.imgur.com/whVLlZQ.png

**Comment by Roxforbraynz** [comment]
Once again, adding onto this. Terrasteel and Elementium boots have Z-Fighting on the back, and Terrasteel's legging's straps Z-fight with the boots.

http://imgur.com/a/2AAS0
