### ISSUE TITLE
Corporea funnel does not work with another corporea funnel between it and inventory.

### ISSUE THREAD

**Issue by I-Need-A-Username** [Vazkii/Botania#1622]
Normally, the Corporea Funnel will place blocks in an inventory that is one or two blocks below it, or drop the item into the world if there is none. This works as it should. However, if the block between the corporea funnel and the inventory is another corporea funnel, it instead drops the item into the world as if there was no inventory below it.
Here's the system I set up.
![2015-12-06_14 31 47](https://cloud.githubusercontent.com/assets/15763131/11615773/014c661a-9c27-11e5-8c21-1c09a57c7af2.png)
Here's what happens when the system is triggered. (Also, there weren't actually any grass blocks in the system. Another bug?)
![2015-12-06_14 32 03](https://cloud.githubusercontent.com/assets/15763131/11615785/18dcaee8-9c27-11e5-9c91-2aa6e3623b6e.png)
This also happens when the bottom corporea funnel isn't even set to request anything.
![2015-12-06_14 33 03](https://cloud.githubusercontent.com/assets/15763131/11615789/4b6d254a-9c27-11e5-86f5-2b0600a76d40.png)
And even the bottom isn't even a part of the corporea network.
![2015-12-06_14 33 28](https://cloud.githubusercontent.com/assets/15763131/11615795/71f57e88-9c27-11e5-9841-373aec8bc34c.png)

**Comment by yrsegal** [comment]
This is because all corporea funnels are considered inventories. I'll see what I can do.

**Comment by hohserg1** [comment]
I have similar bug. When I place funnels by ring up to 2(see screenshot) and activate continualy first cycle of bottom layer of funnels doing normaly, but top layer dont work. In second cycle work only last funnel  in top layer
![image](https://user-images.githubusercontent.com/35610168/60373277-4a641680-9a08-11e9-93f2-a078b76c8911.png)
