### ISSUE TITLE
The amount of mana obtained from a Black Lotus seems way too low for it's rarity

### ISSUE THREAD

**Issue by Roxforbraynz** [Vazkii/Botania#1623]
Going forward with this, please keep in mind that this is not complaining, I'm just expressing concerns over what seems to be a pointless item that has potential. Feel free to ignore me and I can carry on pretty much ignoring this item, but at least hear me out.

For being a rare flower found from loot chests, the Black Lotus gives a surprisingly low amount of mana when used; giving just over three quarters of a Diluted Mana Pool worth of mana. They become pretty much pointless beyond a little nudge when starting out unless you can find a way to hoard several stacks of them.

I decided to give it a fair shot by comparing it to other mana generation methods. One Black Lotus generates slightly less mana than 7 charcoal in a single Endoflame. A single Thermalily with one block of lava fills the Diluted Mana Pool almost twofold. That seems way too low for a rare flower that emits "strong" magical vibes.

The Blacker Lotuses obtained from the Gaia Guardian II seem better, filling about 1/10th of a normal Mana Pool, but they still feel underwhelming with how hard that fight is and at that point you're close to or at end game.

To me, it would seem better to increase the normal Black Lotus close to what the Blacker Lotus is now, and make the Blacker Lotus fill a substantial amount of the regular Mana Pool or remove it entirely and make the Gaia Guardian II drop a small amount of normal Black Lotuses.

**Comment by Stormalisk** [comment]
Same issue with the item here, in fact, I'm planning to make it craftable using certain mob drops with a recipe mod. Since I am not willing to see the item, with such potential, fall from grace.

**Comment by yrsegal** [comment]
This seems like a suggestion. Save those for reddit, not for the issue tracker.
