### ISSUE TITLE
Runic Altar Rune Error

### ISSUE THREAD

**Issue by BaalofFire** [Vazkii/Botania#1624]
Version 240, when crafting higher tier runes, the lower tier runes aren't consumed, they pop off when the new rune is crafted.

**Comment by AlterAkima** [comment]
Intended behavior, read the book again.

**Comment by TheWhiteWolves** [comment]
That is intended behaviour, please read the [change log](http://botaniamod.net/changelog.php#r1-8-238) and [contributing guidelines](https://github.com/Vazkii/Botania/blob/master/contributing.md) before reporting a bug.

This change was made in R1.8 238 as part of the major restructing.
