### ISSUE TITLE
R1.8 240 crash

### ISSUE THREAD

**Issue by BrokenHearted2** [Vazkii/Botania#1625]
I broke a dungeon chest and got a CTD. No clue what is in the chest that made it happen. The magnet API does not like what is in it.

http://pastebin.com/YXxK4GAi

**Comment by JRoffel** [comment]
I feel like this isn't the full crash log... I'm missing part of the summary info... Is that correct?

**Comment by yrsegal** [comment]
Also, this doesn't look... possible. The recursion is happening, but Vazkii is setting the damage correctly o.O

can you give us a list of mods, perhaps? maybe one of them is messing with this.

**Comment by JRoffel** [comment]
Hmmmm, according to the crash log, there is an unknown entity near all the dropped items from the chest... Possibly the culprit?

**Comment by Vazkii** [comment]
Ah. This is a problem, since some items intercept getItemDamage I can't use it properly for recursion. Hm.

**Comment by Vazkii** [comment]
https://github.com/Vazkii/Botania/commit/3b6ebcae1e023bc5974cff329b47bd047b3583e6 will have to do

**Comment by JRoffel** [comment]
Well, that was quick...

**Comment by Zsashas** [comment]
You should be able to use MCEdit to find what the ID of the entity is, then look that up in-game to find out what item was causing the problem? I didn't know there WAS a blacklist for the magnet.

**Comment by yrsegal** [comment]
The issue was resolved, @Zsashas. The problem would not have been solved by your method.

**Comment by Zsashas** [comment]
I was thinking more along the lines of simply finding out what the item was that caused the issue in the first place, might be useful to know.
