### ISSUE TITLE
Terra Shatterer broken when full set of terrasteel armour is equipped.

### ISSUE THREAD

**Issue by RiskyKen** [Vazkii/Botania#1626]
After updating from r1.7-237 to r1.8-241 the Terra Shatterer looks like it keeps getting updates or something causing it to reset it's mining progress.

If the player had more than one Terra Shatterer on their hotbar the 2nd one seems to work fine.

Not been able to reproduce this in single-player. 

https://www.youtube.com/watch?v=atcqLWKWPhk

Forge: 10.13.4.1558-1.7.10
Botania: r1.8-241

EDIT
Additional Info
Other Botania picks work fine.
Botania was the only mod updated.

**Comment by yrsegal** [comment]
modlist?

**Comment by JRoffel** [comment]
Fml log?

**Comment by RiskyKen** [comment]
Here http://pastebin.com/iu5x3QE4

**Comment by yrsegal** [comment]
does anything happen in the log when you use a Shatterer and it fails?

**Comment by JRoffel** [comment]
Have you also tried using the pick without any mana on you?

(Phones are annoying bastards when you need to read a pastebin, I hate my phone)

**Comment by RiskyKen** [comment]
Tried without the mana band still the same.

Don't see anything in the server or client logs when it happens.

**Comment by yrsegal** [comment]
This seems like the relevant function, not quite sure what's going on. https://github.com/Vazkii/Botania/blob/9cf015ee972bb8568f65128fa7b84c12c4a7cfff/src/main/java/vazkii/botania/common/item/equipment/tool/terrasteel/ItemTerraPick.java#L131-L141

**Comment by JRoffel** [comment]
Is build 241 designed for the recommended version of forge, or the latest version of forge?

(I really need to get some sleep in order to understand code again)

**Comment by MikuPL** [comment]
I'm experiencing the same issue but it only occurs while wearing full set of terrasteel armour, no matter if single or multiplayer.
Just taking one piece of terrasteel armour off allows for usage of shatterer once again.

**Comment by RiskyKen** [comment]
@MikuPL Confirmed seems to be the same for me.

**Comment by yrsegal** [comment]
Could you try no terrasteel, but a Greater Band of Mana?

**Comment by yrsegal** [comment]
I mean a band of Aura

**Comment by yrsegal** [comment]
I believe this is due to the filling effect of the Band of Aura/Terrasteel
armor, as they will fill Terra Shatterers. There needs to be a way to
blacklist mana items from such dispatches.

**Comment by RiskyKen** [comment]
Seems to work fine with the Band of Aura or Greater Band of Aura equipped.

**Comment by yrsegal** [comment]
The Bands fill slower than the armor. Try mining for a while, look for
small discrepancies.

**Comment by RiskyKen** [comment]
Was just looking at this line should the armour not also be listed? https://github.com/Vazkii/Botania/blob/9cf015ee972bb8568f65128fa7b84c12c4a7cfff/src/main/java/vazkii/botania/common/item/equipment/tool/terrasteel/ItemTerraPick.java#L271

**Comment by yrsegal** [comment]
Aha! That's how to fix the bug.
