### ISSUE TITLE
Suggestion: Possible sword idea?

### ISSUE THREAD

**Issue by jmc666** [Vazkii/Botania#1628]
I have no idea if you are familiar with the anime/manga bleach - but there is a sword called Senbonzakura supposedly 'Thousand Cherry Blossoms' that controls waves of pink flower petals to cut targets. The mechanic of the Terra shatterer where the ability of a tool is improved by the mana, I wondered if having a sword that became more powerful with the more petals/mana that were added?

**Comment by yrsegal** [comment]
No suggestions here.
