### ISSUE TITLE
Creeper powered Entropinnyum

### ISSUE THREAD

**Issue by Cerugon** [Vazkii/Botania#1631]
Pretty self exlaining. 
Would help a LOT with Magical Crops (One of the crops can spawn a Creeper, and I don't want my farm to be blown up)...

**Comment by Nincodedo** [comment]
[As per the contributing.md on this repo](https://github.com/Vazkii/Botania/blob/master/contributing.md) "Suggestions are not accepted here. Post them on the forums or reddit instead. If there's any still open they're old ones before this rule was added."

**Comment by Cerugon** [comment]
More to add: Entropinnyum powered by Hunters Handgun using Buster Magazine... (from Reliquary...)
