### ISSUE TITLE
Dandelifeon's mana production algorithm may have logical error 

### ISSUE THREAD

**Issue by GWYOG** [Vazkii/Botania#1634]
Using Botania r1.8-242.
This is not a suggestion to be posted on reddit, I think.

Your design of Dandelifeon is really amazing, but I doubt that your Dandelifeon System is not working properly as it was designed to be. That is to say, there exists some very simple way to generate lots of mana in 30 secs.

1.You added the feature that Cellular Blocks only become alive on a block which is not air. However, we can design a simple way to make a stable system according to this feature: place Cellular Blocks on (0,3),(1,2),(2,1),(3,0),(2,-1),(1,-2),(0,-3),(-1,-2),(-2,-1),(-3,0),(-2,1),(-1,2) and place four stones on (0,2),(2,0),(0,-2),(-2,0).This system is stable and won't change. When you remove the two stones (0,2) and (0,-2) at age 59, there will be 6 age 60 Cellular Blocks into the 3*3 absorbing area! This way to generate mana is really IMBA.
http://imgur.com/eNUbNwV

2.Another sub-optimal way is that if you place 3 Cellular Blocks on (-1,3),(0,3),(1,3)and put another Cellular Blocks on (0,2) when the first 3 blocks are at age 58, there will be a block of age 60 in the absorbing area in the end. Most of the 25*25 area are not used.
http://imgur.com/M6SduoY

3.Also, situation 1 will happen when using ME Annihilation Plane from AE2(or anything else which has similar function) to destroy the newly revived Cellular Block.

Maybe setting the Cellular Block undestroiable or removing the feature that Cellular Blocks only become alive on air block is better(So that situation 1 doesn't occur). If the algorithm takes "When a new Cellular Block is placed by a player, all Cellular Block's age is set to zero.", situation 2 's problem may be solved.
I hope you could improve the design of Dandelifeon to make it more complex for players to find out the optimal Cellular Blocks placing strategy. I think Dandelifeon has more potency than it could have.

**Comment by Lazersmoke** [comment]
Maybe make it so the 25x25 area has to be all air?

**Comment by justicesays** [comment]
Perhaps make the consumption area a random 3x3 or 4x4 space within the "arena" , so the mana generation is based on average density *age of blocks rather than on getting blocks in a specific location at a specific time in the cycle.
Also, it's a bit of a stretch to imagine most players working out an optimal strategy themselves. Once one player finds something that works well it will be posted on youtube or forums and everyone will follow it until someone works out a more optimal strategy....

**Comment by GWYOG** [comment]
I agree with your first point. Anyway, it is impossible for all the players to find out an optimal strategies themselves.....

From my perspective, if the optimal strategy really exists but is nearly impossible to find out, things will be better. There may be some fine strategies, but I think most of the people will still tend to find out a better one rather than just follow it.

Just like IC2's nuclear reactor's design, nobody could prove that the design which has an output of 420EU/t is the best one. It's true that lots of people just follow the 420EU/t's design, but there are still many of them trying to find out a better one by themselves, I am one of them too. XD 

Moreover, sometimes the design with the highest output is not the best one and nobody could give a specific definition to the word 'best' or 'optimal'. For instance, we may want to find out a fast way to get the mox fuel rather than focus on its output efficiency when it comes to IC2's nuclear reactor's design. There are always some good designs for us to find out. 

The uncertainty is really awesome, so posting strategy which works well probably may not harm a lot, it will only let the uncertainty attract more people joining in and trying their best to find out a better design by themselves =D
