### ISSUE TITLE
Full Terrasteel armour treats Terra Shatterer as a mana tablet.

### ISSUE THREAD

**Issue by I-Need-A-Username** [Vazkii/Botania#1635]
Thanks to the new passive mana generation on a full set of terrasteel armour, mana tablets can now be filled up constantly. However, if the Terra Shatterer is in a slot that is checked before a mana tablet, the generation goes to the shatterer instead. This wouldn't be too much of a problem; free passive mana generation on the leveling for the Terra Shatterer, but it renders the pickaxe unusable. So long as there's mana generation on the pickaxe, it cannot break blocks. It gets some progress done, but resets before the block is broken.
The only way I found around this is to have a mana tablet in the hotbar before the Terra Shatterer.
I have also noted that this does not occur with a band of aura.

**Comment by AlterAkima** [comment]
Already solved https://github.com/Vazkii/Botania/issues/1626
