### ISSUE TITLE
[journeymap/]: Error getting BlockDoublePlant icon from mod.

### ISSUE THREAD

**Issue by srs-bsns** [Vazkii/Botania#1637]
Botania r1.8-242
journeymap-1.7.10-5.1.3-unlimited

```
[Client thread/WARN] [journeymap/]: Error getting BlockDoublePlant icon from mod. Plese report this exception to the mod author of Botania:doubleFlower1: java.lang.NullPointerException
	at net.minecraft.block.BlockDoublePlant.func_149888_a(BlockDoublePlant.java:128)
	at journeymap.client.forge.helper.impl.ColorHelper_1_7_10.getDirectIcon(ColorHelper_1_7_10.java:197)
```

I get that about a dozen times total for Botania:doubleFlower1 and Botania:doubleFlower2.
I'm not sure of the implications with journey map since I haven't looked into it yet, but it may just mean that the map won't render the tall flowers, but It's only a warning so this can obviously be low priority.

**Comment by yrsegal** [comment]
Speaking from experience (colored double grass had this problem with me): BlockDoublePlant has a lot of strangeness. I'd suggest just overriding func_149888_a like so (change variable names as is required)
```java
@SideOnly(Side.CLIENT)
@Override
public IIcon func_149888_a(boolean top, int index) {
    return top ? this.topIcon : this.bottomIcon;
}
```
