### ISSUE TITLE
Entire client crashes if you trigger a red-stringed interceptor repeatedly too quickly

### ISSUE THREAD

**Issue by Azutte** [Vazkii/Botania#1640]
Was testing with a red-stringed interceptor directly below a thaumcraft item grate, and just spamming right click.

Circa release 237, but I'm not noticing any changes to the interceptor in the changelog since then.

http://pastebin.com/c2KKL6Sn

**Comment by yrsegal** [comment]
mod list?

**Comment by Azutte** [comment]
http://imgur.com/NxIpq0v

**Comment by yrsegal** [comment]
Perhaps WAILA is doing it? I could imagine that being a slight issue...
(although what is my texture doing inside your mods folder? o.O)

**Comment by Azutte** [comment]
(shhh)

**Comment by Vazkii** [comment]
I have to ask how the actual fuck you managed to accomplish this. Either way it's an easy fix.

**Comment by Azutte** [comment]
I managed to accomplish it because the item grate in thaumcraft doesn't open a GUI when you right click it, but does work with the interceptor. I wouldn't be able to do it with a chest.
