### ISSUE TITLE
Crash When Browsing Lexica Botania

### ISSUE THREAD

**Issue by Slither88** [Vazkii/Botania#1643]
When I browse through certain entries in the Lexica the game crashes. I just can't remember which entry. I will test and update this... 

Here is the crash report:
[crash-2015-12-11_08.46.39-client.txt](https://github.com/Vazkii/Botania/files/59088/crash-2015-12-11_08.46.39-client.txt)

**Comment by TheWhiteWolves** [comment]
Looks like something is messing with the Leaf block, can you try and reproduce this with only the latest botania.

**Comment by Slither88** [comment]
I will do that
