### ISSUE TITLE
Floral Powder colours pool instead of converting to Mana Powder

### ISSUE THREAD

**Issue by TheWhiteWolves** [Vazkii/Botania#1644]
See [Reddit Post](https://www.reddit.com/r/botania/comments/3wcv6v/bugkinda_mana_powder_creation_changes_the_pools/)

> yovliporat:
> "Since mana powder can be made with the different coloured floral powders, and throwing a floral powder into a pool changes its colour, trying to make mana powder with a floral powder will result in the colour of the pool changing. Not really a bug, but... I wanted endoflames, not a magneta pool :("

**Comment by JRoffel** [comment]
I have the same thing (Most recent version of botania: R1.8 242), it does however make the powder...
