### ISSUE TITLE
pure daisy appears to have issues with metadata

### ISSUE THREAD

**Issue by dualinfinities** [Vazkii/Botania#1645]
specifically, it appears not to distinguish between the different meta values, converting all blocks of that id. this is an issue when using mods that use metadata for very different blocks.

**Comment by yrsegal** [comment]
Using Oredict keys can get around this.

**Comment by JRoffel** [comment]
Do you have a few examples of mods that have this problem, cuz I can't really think of a mod that adds blocks that can be converted by the pure daisy?

**Comment by yrsegal** [comment]
We do, and I know for sure that oredict solves this problem (played around with this kind of thing when adding the recipes)

**Comment by bookerthegeek** [comment]
So my understanding is that the op has a block (say id  597 and meta data 123) that should be transformed by the pure daisy. He also has another block (say id 597 and meta data 529) that should not be transformed. But it is being transformed. Is this right?

Ore dictionary would work except that maybe he does not want the first block treated like something else.

**Comment by dualinfinities** [comment]
that is precisely the problem. fortunately in my case oredicting the block was a suitable solution, but other people may find it is not.

**Comment by Vazkii** [comment]
The Pure Daisy uses the Ore Dictionary to map which blocks are which. Please contact the mod authors of the problematic mods to add the relevant keys to all relevant metadata values of their blocks.
