### ISSUE TITLE
[Bug] Mana Blaster uncraftable

### ISSUE THREAD

**Issue by Kurukuu** [Vazkii/Botania#1646]
I tried to craft the Mana Blaster from Botania r1.8-242, gathered the materials as seen in NEI and the Lexica Botania (TNT, Mana Rune, Mana Diamond,3x Livingwood), tried to craft it at the Vanilla Minecraft crafting table, but did not get it, got no items as result of the crafting recipe. tried it in a survival world, and ina  creative, and in neither of them I can craft the Mana Blaster

(image trying to craft it: http://imgur.com/be8UIgK)
FML Log: http://pastebin.com/zmdyS91k

--Using the last version of the mod (Botania r1.8-242)
Using the last Forge version
Using Vanilla Forge
Not using Optifine
Mod List: http://imgur.com/qjMJ8na

**Comment by yrsegal** [comment]
I don't see a Redstone Mana Spreader in the crafting ingredients...
This isn't a bug, you didn't gather the right ingredients :V

**Comment by Kurukuu** [comment]
Yeah, I confused the Redstone Mana Spreader, with LivingWood, Sorry

**Comment by yrsegal** [comment]
please close the issue, as it is invalid.

**Comment by PsiGuy60** [comment]
If it makes you feel any better, the amount of times I tried to craft a Blaster with a regular Mana Spreader...
