### ISSUE TITLE
Rod of the Unstable Reservior's missiles targets the player casting them.

### ISSUE THREAD

**Issue by Tristaric** [Vazkii/Botania#1647]
Botania R1.8-242
When using the Rod of the Unstable Reservior, the missiles target you, instead of hostile mobs around you.

**Comment by Vazkii** [comment]
Can't reproduce.

![2015-12-13_01 31 57](https://cloud.githubusercontent.com/assets/1794735/11764866/59e52bd8-a139-11e5-9527-f6c919e74759.png)

**Comment by Tristaric** [comment]
huh, odd ._.
