### ISSUE TITLE
Livingrock and Livingwood have Pure Daisy's descriptions when shift-looked at with Lexica

### ISSUE THREAD

**Issue by Schluck123** [Vazkii/Botania#1648]
![2015-12-11_23 12 46](https://cloud.githubusercontent.com/assets/14033785/11760774/0f9d8ad4-a05d-11e5-97e1-183057555743.png)
![2015-12-11_23 12 48](https://cloud.githubusercontent.com/assets/14033785/11760775/12bce0e8-a05d-11e5-9e8a-eb89338f1bf4.png)
Botania R1.8-242

**Comment by AlterAkima** [comment]
They belong to the Pure Daisy entry, that's why.

**Comment by yrsegal** [comment]
This should be closed as it works as intended
