### ISSUE TITLE
Cant apply Resolute Ivy to anything

### ISSUE THREAD

**Issue by aikpoppel** [Vazkii/Botania#1657]
Hey Vazkii,
i have tried many many Tools, Rods and Baubles but cant apply Resolute Ivy and Timeless Ivy to anyting. Maybe im doing something wrong...
LG Aik

**Comment by JRoffel** [comment]
Please check out vazkii's "bug reporting 101" (http://vazkii.us/br101/) and edit your issue appropriately

**Comment by aikpoppel** [comment]
Sry!
---
Hey Vazkii,
i have tried many many Tools, Rods and Baubles but cant apply Resolute Ivy and Timeless Ivy to anyting. I have was trying vanilla crafting bench, player crafting grid and tinkers crafting table.+ Maybe im doing something wrong...
LG Aik

Botania r1.8-243
Forge 10.13.4.1558 no MCPC+
Optifine HD C1

FML Log: http://pastebin.com/p94eWZMZ

**Comment by yrsegal** [comment]
can you give us the recipe(s) you're trying to use?

**Comment by aikpoppel** [comment]
http://imgur.com/a/pSljr
Some Screens for you. tested with all items in inventory.

**Comment by yrsegal** [comment]
it looks like you're not applying the Timeless Ivy correctly (1 timeless ivy + 2 of that object's repair material), but I don't know why the resolute stuff won't work.
