### ISSUE TITLE
Crash when requesting recipe in NEI (using R key)

### ISSUE THREAD

**Issue by the-vindex** [Vazkii/Botania#1659]
Botania 243.
NotEnoughItems-1.7.10-1.0.5.118-universal
NotEnoughResources-1.7.10-0.1.0-121
neiaddons-1.12.14.40-mc1.7.10

http://pastebin.com/wHSjGdAN

**Comment by the-vindex** [comment]
Downgrading to 242 with the rest untouched solves the problem.

**Comment by BrokenHearted2** [comment]
Same here, went back to 242 until it is fixed or a solution is found.

**Comment by JRoffel** [comment]
I would like to refer you to vazkii's bug reporting 101 (http://vazkii.us/br101/) and please pay extra attention to Step 2... Your current issue is hurting my eyes :(

**Comment by yrsegal** [comment]
It appears an `ItemStack` is being made with a null `Item`.
