### ISSUE TITLE
support Et Futurum stones in all Botania crafting recipes

### ISSUE THREAD

**Issue by wjrogers** [Vazkii/Botania#1660]
Currently, only the smooth stone and brick recipes accept both Botania and Et Futurum stones as inputs. This means you cannot craft, for example, Granite Stairs, Granite Slabs, or Granite Walls using Granite generated in the world by Et Futurum.

**Comment by Zsashas** [comment]
Chisel also adds it's own versions. Not sure if those are compatible yet.

Those stone types are really popular...

**Comment by yrsegal** [comment]
they are, after all, from 1.8.
