### ISSUE TITLE
Overgrowth land unable to be silk-touched

### ISSUE THREAD

**Issue by Stormalisk** [Vazkii/Botania#1661]
The enchanted soil is unable to be silk-touched, not sure if this is intentional or not. If it is, could there be a possible config option for it in the future?

**Comment by JRoffel** [comment]
Silk Touch (and the Weight lens) were specifically made to ignore Enchanted Soil. It's not meant to be movable [Citation needed]

**Comment by PsiGuy60** [comment]
It's 100% intentional, Vaz has stated that she has no plans to allow moving Enchanted soil.

**Comment by TheWhiteWolves** [comment]
that is the intended design
