### ISSUE TITLE
Adventure gamemode and manasteel tools

### ISSUE THREAD

**Issue by hanakocz** [Vazkii/Botania#1663]
Hello,
we are playing small modpack with Botania on Adventure gamemode, so we found quite strange behaviour of manasteel tools.

As known, manasteel is made from iron + mana , so possibly it should be tier 2 (iron tools) or maybe tier 3 (diamond tools). However due to easiness to make it (haha, with GregTech 6 it is so hard to get even iron , but that is another story), I would say it should be tier 2 tool. 

However our gameplay showed us quite strange behaviour.
Manasteel Pickaxe behaves like tier 3 (or above) tool, with quite fast digging of obsidian and so...
BUT Manasteel shovel seems to be only tier 0 tool , not capable of shoveling ores and so (YES, there are mods that add ores as sand/gravel ones....so they need in adventure gm proper tool tier as well)

Can you have a look into it, probably adding the shovel proper material tier, too? We like to use Botania tools. :)
 And if you have time, can you describe here what tier those tools are at all? We now play just casually, but when I would want to make balanced modpack, this information is crucial for balance. 
Thanks, Hanako.

**Comment by AlterAkima** [comment]
The Manasteel Pickaxe is intentionally obsidian level, just like how Thaumium is, but about the shovel, the devs may take a look at it.

**Comment by Zsashas** [comment]
Have you also tested the axe?

**Comment by hanakocz** [comment]
OK, I took some ironwood GT pipes (only block I found that needs Tier 2 Axe) and it worked, but it worked with wood axe, too(really not tier 2, so probably GT fault), so nothing can be said, probably...wood material is probably always low tier...
So all wood with axes do work....

Just a note, vanilla tiered shovels don't work neither on higher tier sandy materials, probably because there was no block with such a need in vanilla....

**Comment by Zsashas** [comment]
True, there isn't much use for higher-tier shovels or axes. There are only three times I've needed a higher tier for more than speed: Hydraulicraft ores and TiCon gravel ores (shovel) and Natura Bloodwood (needs iron level axe).

**Comment by hanakocz** [comment]
Further research : Floating flowers from Botania cannot be broken by manasteel shovel, also Quicksand from BOP. So not only ores. 
Both blocks have shovels as the right tool (and GT shovels Tier 1 (flint ones) are good to do so, but even diamond vanilla one is not working as well, as mentioned before)

**Comment by howtonotwin** [comment]
Wait, what? I was just looking through the source and all of the Manasteel tools use the same Material. It's initialized with a tier of 3 and the shovel should therefore also be tier 3. Beyond that, Floating Flowers lack a setHarvestLevel call, and therefore can be mined by anything, regardless of tier and tool type. Maybe this is a Forge issue? <sup><sub>Magical tier nullification? Spooky! OOooOOoooOOOOoooOooOoOoOOOoooOoOO...</sub></sup>

**Comment by yrsegal** [comment]
I believe ItemShovel overrides the tier system.

**Comment by howtonotwin** [comment]
Strange, ItemSpade seems to be a mostly empty class. I don't think it does it itself. Is the change done somewhere else, like `item instanceof ItemSpade`? Either way, this should be a Forge bug.

**Comment by hanakocz** [comment]
I know you can hate me for this, but really don't know better reference. In adventure gamemode GregTech shovels do work properly (where vanilla ones or others do not), so I would point out for GT code for shovel, however I am really begginer in coding, but maybe you can see something in it and et what is up there and probably fix it for Botania, too :) Because it is mutual wanting that all the things do work properly, I think.

https://github.com/Blood-Asp/GT5-Unofficial/blob/experimental/src/main/java/gregtech/common/tools/GT_Tool_Shovel.java
Here is a link to GT5 unnoficial source (which had working shovels as well)....
My amateur skills in Java and modding telling me (and might be totally wrong), that the whole magic could be in this function:  
public boolean isMinableBlock(Block aBlock, byte aMetaData)

However GT5 code lacks GT6 sandy ores with tiers, but there was still same problem with vanilla tools back then (only GT shovels worked for some blocks in Adv), so it still might help here, too.

**Comment by JRoffel** [comment]
Knowing GregTech, they have probably not assigned tiers to vanilla tools on purpose (So you HAVE to follow the GregTech progression route). Even though you want Botania to tier their shovels to GregTech's tier system, does not mean that the developer(s) of GregTech intended this to happen, and it can therefore "harm" player experience for (somewhat) the same reason as RF -> Mana things do not exists within Botania. Therefore I am of opinion that this is not a feature Botania should implement, as to not harm the GregTech experience. You could always try asking the mod author(s) of GregTech to implement compatibility with Botania (And any other mod that adds shovels). This way you leave some choice up to the creator(s) of GregTech in how their mod comes out.

Related: [story about mod engagement by Vazkii] (http://vazkii.us/uncategorized/sins-of-a-solar-empire-or-the-passive-generation-conundrum/)

**Comment by hanakocz** [comment]
Ah, I think you misunderstand the thing. GT does not do anything with vanilla or other tools, it is gamemode settings, that does. You can have */gamemode 2* even without GT and it should be the same problem.

Okay, the test: Only Botania installed, setted up */gamemode 2*:
Floating herbs cannot be broken by any means. (because really working shovel from GT is not here)
Did not tested other blocks, but it will be same.

I mentioned GT ONLY because their shovels DO work, so we can probably find where is the difference.

**Comment by JRoffel** [comment]
If you are in gamemode 2, it makes sense things can't be broken... Gamemode 2 is designed for maps, meaning blocks can't be broken at all (Some special MC 1.8 NBT tags disables this effect in specific situation, but that is not related to this issue)...

**Comment by hanakocz** [comment]
MC 1.7 adventure gamemode is different to MC1.8 adventure. MC1.7 adv means that the right tools need to be used to break the blocks, not that you cannot break any blocks at all. 
So for breaking the dirt you need shovel, for wood you need axe etc. And for floating flowers you need shovels, but Botania ones not vanilla ones do not work, because shovels are bugged with this.

**Comment by JRoffel** [comment]
I see, sorry my bad... So, if I got this right, you are saying that some blocks can't be destroyed because they don't have a "right tool" (or tool of correct tier) in adventure mode. Now I imagine this could (I'm not a developer in this mod, so can't be 100% sure) be intentional... Minecraft 1.7 adventure mode (pure vanilla) also has some blocks that can't be broken whatever happens (Like beds and haybales), but I'll be leaving that up to Vazkii (Or someone else, I've only been around here for ~10 days and not sure who are the key developers within Botania)

**Comment by hanakocz** [comment]
Well, the blocks are good, because they have setted up "shovel" as the right tool, as they should. Then GT shovel do work. If they have no right tool, GT shovel won't work on them, only crowbar (as universal tool for blocks with no "right tool") would do. 
The whole thing is about shovels, because they are bugged (and Greg stated it sometimes in past) in vanilla, so if you make your shovel similar way, it probably inherits this thing. They still do work for normal blocks as dirt, sand and so, but not for special blocks that have setted up better material tier (but still "shovel material")

**Comment by JRoffel** [comment]
So simply put, all Botania shovels are tier 1 shovels, and can't break tier 2 and/or tier 3 stuff?

**Comment by hanakocz** [comment]
They behave like that, yes, even though their material is setted up as tier 3, what is not enough for shovels, it seems.

**Comment by yrsegal** [comment]
Maybe it's that itemspade lacks a tier descriptor?

**Comment by JRoffel** [comment]
GregTech doesn't use the ItemSpade class, so I assume they use their own class (which does have a tier descriptor). Only problem is that we can't really base our shovels off of that, as not everyone has gregtech installed, and creating an entire shovel class might fall under [But it takes effort] (http://vazkii.us/uncategorized/but-it-takes-effort/) so I will be leaving this up to someone who has a better judgement of effort vs reward in this case

**Comment by yrsegal** [comment]
ItemManasteelShovel can have a tier added with very little effort.
