### ISSUE TITLE
Runic Altar Dupe Bug

### ISSUE THREAD

**Issue by aikpoppel** [Vazkii/Botania#1668]
Hey Vazkii,
i´ve found a dupe bug with runic altar. i´ve make a rune of summer and after the first recipe, i use "right click with empty hand" function and no runes in inventory where consumed but other items are consumed.
LG Aik

Botania r1.8-244
Forge 10.13.4.1558 no MCPC+
Optifine HD C1

FML Log: https://dl.dropboxusercontent.com/u/75415718/fml-client-1.log

**Comment by SquidDev** [comment]
See #1624. This is intended: this change was made in R1.8 238 as part of the major restructing.

**Comment by JRoffel** [comment]
Please close as this is not an issue
