### ISSUE TITLE
cosmetic bauble(s?) not aligning properly in f5

### ISSUE THREAD

**Issue by Azutte** [Vazkii/Botania#1669]
Kinda visible here http://i.imgur.com/qqbTCFY.png 

I'm not sure how to describe, but it... is just not in the right spot?? Circa 237.

**Comment by OJwithC** [comment]
The wills on a terrasteel helmet (don't know if the new models have them) also rotate oddly when on a horse. (And are you using luminizers, or is your horse flying?)

**Comment by yrsegal** [comment]
For a possibly related point, the Rod of the Shaded Mesa can pick up a
horse you're riding.

**Comment by Lazersmoke** [comment]
@yrsegal bug? thats most certainly a feature! https://gfycat.com/BleakEuphoricBullmastiff

**Comment by yrsegal** [comment]
I never said it's not an awesome bug.

It's sadly a bug, though.
