### ISSUE TITLE
Corporea Index Tab Complete Crash

### ISSUE THREAD

**Issue by Lonemind** [Vazkii/Botania#1671]
When standing within the area of effect of the Index using tab to complete a player's name crashes the client. It would be nice if this did not happen. XD
[crash-2015-12-19_12.38.25-client.txt](https://github.com/Vazkii/Botania/files/67585/crash-2015-12-19_12.38.25-client.txt)

**Comment by JRoffel** [comment]
Please update Botania to the latest version and try again, if the crash still happens in the most recent version, try to reproduce the crash with just botania installed, you can also try to reproduce the crash in the most recent version of forge (Not the recommended one).

**Comment by Vazkii** [comment]
Can't reproduce.

**Comment by yrsegal** [comment]
Vazkii, try to use tab complete when the chat contains only a space near an
index. That reliably reproduces it.
