### ISSUE TITLE
Crash upon load up after update

### ISSUE THREAD

**Issue by malhavok13** [Vazkii/Botania#1677]
I was using version r1.7-237 with forge 1614. When i upgrade to r1.8-238 or higher, the game crashes upon load up. No other mods are loaded.
[Botania crash.txt](https://github.com/Vazkii/Botania/files/68454/Botania.crash.txt)

**Comment by Zsashas** [comment]
I noticed that you're using Java 8. Have you tried with 7?

**Comment by malhavok13** [comment]
ok   rolled java back to 7.79 and still same issue

**Comment by malhavok13** [comment]
Well I got it figured out. I deleted everything Botania i could find, the .jar file, the config and the BotaniaVars.dat file. Then tried again, and it worked.
