### ISSUE TITLE
New starfield sometimes has the components converge.

### ISSUE THREAD

**Issue by howtonotwin** [Vazkii/Botania#1678]
I'm not quite sure how to word this, however as the new starfield is made up of 3 vanilla starfields rotated and tinted, they sometimes end up converging. The stars eventually line up in rows of three. These rows compress down to a single point, then expand back out into a row of stars. This takes place over a few seconds and eventually the rows break up. This can be reproduced simply by opening a world with the new skybox and waiting.

Latest Forge and Botania. No optifine or stuff like that.
Pics (was in a bit of a rush, sorry for ugliness): 
![2015-12-21_11 30 34](https://cloud.githubusercontent.com/assets/15616055/11935735/7b0fac26-a7d7-11e5-863a-dea52897cf3e.png)
![2015-12-21_11 30 37](https://cloud.githubusercontent.com/assets/15616055/11935736/7b16756a-a7d7-11e5-88a8-f85466620c2b.png)
![2015-12-21_11 30 39](https://cloud.githubusercontent.com/assets/15616055/11935737/7b17ac14-a7d7-11e5-88eb-6a34e2d5de8e.png)
![2015-12-21_11 30 42](https://cloud.githubusercontent.com/assets/15616055/11935738/7b1afb3a-a7d7-11e5-89fa-d472bc45f51d.png)

[Log (nothing too interesting and I was playing for a while so this is GIANT)](https://github.com/Vazkii/Botania/files/68718/fml-client-latest.txt)

**Comment by ray10k** [comment]
Personally, I think it looks pretty cool, and it might not be easily prevented in the first place, anyway.

**Comment by howtonotwin** [comment]
This should be pretty easy to fix, I expect it's just randomizing the orientation of the starfields, but I never __*EVER*__ want to touch Minecraft's rendering code.
