### ISSUE TITLE
Redstring Recipe

### ISSUE THREAD

**Issue by Zsashas** [Vazkii/Botania#1679]
It seems to have two recipes. One requires a pumpkin, the other does not. The recipes are otherwise identical. Is there a reason for this?

**Comment by ray10k** [comment]
I can confirm that indeed, there is a second recipe. To the best of my knowledge, the resulting red string is identical to the one created via the recipe without the pumpkin, so I am also curious as to why this second recipe exists.

**Comment by yrsegal** [comment]
It says "in a pinch?" In the code comments. Wat

**Comment by Zsashas** [comment]
It seems that "Are you in a pinch?" is simply the line of text from the Lexicon entry. Still no idea about the pumpkin, the recipe in the book doesn't require one.

**Comment by bit2shift** [comment]
According to the [red string article on the official FTB gamepedia](https://ftb.gamepedia.com/Red_String), it's a reference to [Pumpkin from _Akame ga Kill!_](http://akamegakill.wikia.com/wiki/Pumpkin).
It's one of many Botania's Easter eggs.
