### ISSUE TITLE
Halo Interface Item Deletion with Mod That Changes Vanilla Crafting Table Behaviour

### ISSUE THREAD

**Issue by charlie-e09ae35d** [Vazkii/Botania#1681]
minecraft 1.7.10, forge 10.13.4.1558, baulbes 1.7.10-1.0.1.10, botania r1.8-245, realbench 1.2.0

Exiting Assembly Halo or Manufactory Halo crafting interface with items still in it will not drop anything on ground but delete them instead. Happens with RealBench ([curseforge] (http://minecraft.curseforge.com/projects/realbench)) mod that modifies vanilla crafting table to keep its content after player exits crafting interface.

**Comment by yrsegal** [comment]
If someone wants to play around in vanilla classes, of course botania will have problems trying to use them. This is an issue in that mod, not botania.
