### ISSUE TITLE
Thermalily r1.8-245

### ISSUE THREAD

**Issue by mezoty** [Vazkii/Botania#1684]
Thermalily consume constantly lava, including cool down phase.

**Comment by yrsegal** [comment]
This is intended behavior.

**Comment by mezoty** [comment]
According to you has consumed 500 buckets of lava in 2 minutes? Ridiculous ...

**Comment by yrsegal** [comment]
yeah, so build better automation

**Comment by mezoty** [comment]
You'd better go to bed buddy.

**Comment by yrsegal** [comment]
read the changelogs. This is entirely intended behavior.
https://github.com/Vazkii/Botania/blob/master/web/changelog.txt#L95

**Comment by mezoty** [comment]
OK, I'm going to bed.

**Comment by mezoty** [comment]
Better would be slow evolution than revolution. This solving lost logic, when flower have cool down, then digest, sleep or relax. Why have eat next huge amount of lava? Well, nothing. I kept quiet.

**Comment by yrsegal** [comment]
that... makes no sense.

It was changed so the automation for the Thermalilly has to have some thought to it, as opposed to just set it and forget it.

**Comment by mezoty** [comment]
I just wanted to express their opinion. I had Botania mod ranked among the magic mods, but rearrange it between technical, such as GregTech.
