### ISSUE TITLE
Compatibility issues with the new skybox and Shaders mod

### ISSUE THREAD

**Issue by mistfox** [Vazkii/Botania#1686]
I'm not sure if you can fix this, or if the fix is on your end. But When using the shaders mod and the new skybox, everything breaks visually.
http://imgur.com/MI7uwfb
This is something like how everything should look, shaders set to none and the rainbow shows the skybox is working.
http://imgur.com/gdFrZ8Q
This is what it looks like with the Cel shaders shader pack enabled. Note that all the visuals are displaying at the same time.
http://imgur.com/RWqEk22
This is what it looks like with a couple of more "conventional" shader packs - Continuum and MrMeepz's shaders.
http://imgur.com/XJZm5Ai
Finally, although it's still not perfect (botania blocks are still looking kinda odd, see the petal apothecary there), this is what it looks like with the skybox off and MrMeepz's shaders enabled.

**Comment by Flaeme** [comment]
Okay, wait, no, it got even weirder. I re-enabled the skybox (I did this through the ingame config GUI btw) and went back in with the shader pack enabled and everything is mostly okay, except your skybox is very dim. Crazy interactions between the two, I guess. http://imgur.com/uOyegai

**Comment by blacksmithgu** [comment]
Shaders are a notoriously finicky business to debug, because the order in which shaders are applied amongst other things can really do strange things to custom rendering. I'll look into it.
