### ISSUE TITLE
Lexica Botania does not show changed recipes

### ISSUE THREAD

**Issue by Zsashas** [Vazkii/Botania#1688]
I used ModTweaker to fix the recipes for the Magic Bees flowers (since mana petals are gone) but the book still shows the original recipes. Also, it seems that the book cannot render fire. The original recipe for the Beegonia used three mana petals.

The book also will not show any additional Mana Infusion recipes, whether normal, Alchemy, or Conjuration. Only NEI shows these.

Lexicon: https://gyazo.com/a88aa1a4499e6899a5dc5a5d468d770e

New Recipe in NEI: https://gyazo.com/b12c2f286a651accc7589f1b4f4e45ed

**Comment by yrsegal** [comment]
this isn't a bug in botania, it's how minetweaker does things. You'd have to recreate the lexicon entry to make this work.
