### ISSUE TITLE
Unused crystal bow textures

### ISSUE THREAD

**Issue by williewillus** [Vazkii/Botania#1692]
I came across this when porting, in ItemLivingwoodBow there's an array for 3 icons and the pulling icon is selected from those three. ItemCrystalBow directly inherits this but has 2-3 extra unused textures that seem to continue the same animation. Are they intended to be unused? Now that I've seen the extra textures the current pull animation does seem a bit incomplete

**Comment by Lazersmoke** [comment]
In theory, the crystal bow shoots stronger, so maybe it should be pulled back further?
