### ISSUE TITLE
Manaweave Cowl of Revealing

### ISSUE THREAD

**Issue by Zsashas** [Vazkii/Botania#1694]
https://github.com/Vazkii/Botania/blob/master/src/main/java/vazkii/botania/common/crafting/recipe/HelmRevealingRecipe.java#L100

Looks like Manaweave got overlooked.

**Comment by Lazersmoke** [comment]
We shall consult the @Vazkii 

Should manaweave be allowed to have goggles or revealing? [Mockup](http://imgur.com/jZLPzfJ)
