### ISSUE TITLE
Hovering Hourglass top face doesn't allow block placement

### ISSUE THREAD

**Issue by howtonotwin** [Vazkii/Botania#1696]
The top face of the Hovering Hourglass (only the top, not the bottom) does not allow a block to be placed on it. Instead, when placing a block, it places it on the side opposite the player. For a clearer description, the vector representing the crosshair passes right through the top face as if it doesn't exist. Whichever face of the hourglass it hits next is the one the block is placed on.
Pics (don't judge my paint.exe ;-;):
![2015-12-27_22 25 20](https://cloud.githubusercontent.com/assets/15616055/12013665/d6804f72-ace9-11e5-94f3-bd0e077e1b30.png)
Those 5 blocks were placed without any adjacent block (except the HG itself) to place them on, from the top face of the hourglass.
![2015-12-27_22 37 11](https://cloud.githubusercontent.com/assets/15616055/12013763/d44edbd6-aceb-11e5-8d98-f2a8e0a8b005.png)
Sorry for eyerape.

Scanned through the log, nothing of notice there, just a void between load and save.

<sub><sup>I feel kinda useless, dumping all of these strange arcane bugs on you ;~;</sup></sub>

**Comment by yrsegal** [comment]
Same with the Pylons.

**Comment by Vazkii** [comment]
Vanilla bug that happens if the block's hitbox goes above the 1 diameter block. Not fixing.
