### ISSUE TITLE
Add config option to enable/disable Thaumcraft stabilization by Botania flowers

### ISSUE THREAD

**Issue by the-vindex** [Vazkii/Botania#1698]
Please see subject. I want to make a Thaumcraft pack with more precise control over stabilizers, so I would like Botania flowers not to stabilize.

Thank you.

**Comment by JRoffel** [comment]
Just a quick question, if you want your mod pack to be centered around thaumcraft, then why install another large magic mod? Wouldn't that just make it the 100.000.000th kitchen sink pack out there?

**Comment by the-vindex** [comment]
@JRoffel Because I'll use what suits me from Botania and minetweaker out what I don't need. Right now I have a Witchery pack with Botania and like 50 % of Botania (weapons, tools...) are turned off, but automation part of Botania is on.

**Comment by the-vindex** [comment]
Oh, and thank you, @Vazkii, very very much.
