### ISSUE TITLE
Phantom + Weight Lens

### ISSUE THREAD

**Issue by howtonotwin** [Vazkii/Botania#1704]
The Phantom and Weight Lenses cannot be combined due to sharing the PROP_TOUCH attribute. I was not able to find anything about this anywhere, except the entry in the Lexica ("some combinations will not work"), but I feel [this](https://www.reddit.com/r/feedthebeast/comments/2kltof/how_do_i_magically_break_blocks/clmk8a7) reddit comment (from a year ago :V) should override that.

**Comment by yrsegal** [comment]
The point of the Weight lens being terminated is to use more mana (as silk SHOULD be more expensive). This is a non-issue.

**Comment by howtonotwin** [comment]
Was just wondering, but Vazkii *had* said she'd let them combine, so I'll wait for what she says.

**Comment by howtonotwin** [comment]
Looking back at this, maybe this would be better off as a Reddit suggestion. Closing.
