### ISSUE TITLE
GoG rainbow bobs with player

### ISSUE THREAD

**Issue by Lazersmoke** [Vazkii/Botania#1705]
If you have view bobbing on, the rainbow in the GoG skybox bobs around and makes me motion sick (and I don't get motion sick). Without view bobbing it doesnt do this.

**Comment by Flaeme** [comment]
Happens to me too, find it very disorientating.

**Comment by Lazersmoke** [comment]
I would fix this but rendering code scares me and would take [an alot of time](http://i0.kym-cdn.com/photos/images/newsfeed/000/180/207/tumblr_ls4sxp0Rpc1r3yow8o1_500.jpg) to figure out

**Comment by williewillus** [comment]
Not sure if this would be easy to fix, the sun and moon in vanilla bob as well.

**Comment by Lazersmoke** [comment]
@williewillus CANT UNSEE AHHHHHHHHHH MY EYES

**Comment by yrsegal** [comment]
this is why i turn off view bobbing
