### ISSUE TITLE
Odd issue with world shutting down single player world.

### ISSUE THREAD

**Issue by Mortismorte** [Vazkii/Botania#1707]
Haven't tried on a multiplayer server yet.

The issue, when I first start a world, or when I first try to enter a world after starting the game, it gives me an error about internal issues and gives me a button to go back to the title screen. Actually takes you to server screen lol.

Anyway, after that if I try to play the world it loads in just fine.

I made it so the launcher stays open and found the error that occurs:

http://pastebin.com/f4px0qWT

From the looks it might be NEI actually doing the error but I thought I'd put it here so you could check it out, as it does include Botania in the error.

Facepalms, forgot to add a couple things here lucky for edit buttons :)

Using Botaniar1.8-247 (curse client)
and I do have fastcraft in there.

**Comment by Lazersmoke** [comment]
This is a problem with Botanical-Addons, report it here please. https://github.com/L0neKitsune/Botanical-Addons/issues/new

**Comment by Mortismorte** [comment]
Thanx :)

**Comment by yrsegal** [comment]
It's already reported, and fixed on our side. Next release this will be
fixed.

**Comment by Mortismorte** [comment]
Yeah went there saw that, sorry for putting it in the wrong place, just hard to read those and get the right info every time, thanx for all your guy's help.
