### ISSUE TITLE
Special Grass

### ISSUE THREAD

**Issue by MrPotatoGaming** [Vazkii/Botania#1711]
Edit coming

Botania: 245
Forge: 1558

Sorry for the Edit, miss-pressed the enter button.

Overall the grass works well, but I noticed some odd behaviors while using it. 
This is all I was able to figure out didn't work as expected:

Can't use normal bonemeal - floral fertilizer works fine.
Can't grow sugarcane on it.
Shovel isn't marked as correct tool.
And can't hoe it, though there was a closed issue related to hoeing so I assume you already know.

If I recall right, another mod had this issue - you have to override sugarcane because sugarcane checks the block below it against a whitelist.

**Comment by yrsegal** [comment]
you couldn't just open the issue with the relevant information? you had to edit it in?

**Comment by Lazersmoke** [comment]
heh its funny because im watching this close enough to catch this when its still "edit coming" and you still beat me to it

**Comment by yrsegal** [comment]
I watch botania more than Direwolf. ¯\\\_(ツ)\_/¯

**Comment by MrPotatoGaming** [comment]
A+ on the speed. As the edit said, pressed the enter button instead of the shift button, sorry.

**Comment by yrsegal** [comment]
Sugarcane works fine on my Iridescent Dirt, and we didn't override it.  
Hoeing is a trivial issue, but that's all V's decision.  
Bonemeal would be specifically whitelisted in. Sure, V COULD make it have a bonemeal behavior (from experience, it's not hard) but... meh, the minecraft tall grass block doesn't look good with Alt grass, and V isn't about to go down the Botanical Addons path and make special grasses for those dirts.

**Comment by MrPotatoGaming** [comment]
I agree, Vaskii probably already knows about the other two I reproted. The bonemealing isn't really for the grass for me, I need flowers from the bonemeal. Though it's quite easy to just pasture myself some grass. Not really too worried about it. Everything here is pretty low priority imho.

I know that's how (I think) Gregtech did it way back when. But my minds a little foggy, that was back in 1.5~

Though I was quite inspired to make a cosmetic grass mod that takes the average color of the block below it - and use that to render the color. But that's a bit out of my coding capabilities. I have a few "Misc Block" ideas that I've considered modding.

**Comment by yrsegal** [comment]
Oof, texture averaging. Possible. I could... actually probably add it to Botanical Addons. Buuuuut...

it would be extremely resource inefficient, unless... I ran through every. single. block. and used that as cached. :V

there's a lot of problems with the idea, which is why it won't happen. sorry.

**Comment by MrPotatoGaming** [comment]
Wouldn't need to cache it every time, just every /new/ block beneath it. The resource intensive part would stem from the (going to chop this code, don't java) "if block = x then" and have it cache the new block instead of generate it every time. Then, so the client always knows, save it NBT. But this is seriously off topic.

**Comment by yrsegal** [comment]
caching as in during postinit.

yeah, this is off-topic.

**Comment by Lazersmoke** [comment]
Actually, having an average texture for every block would be pretty nice a lot of times, maybe there should be some library or code chicken core or something that does it once at postinit then makes it available for other mods!

**Comment by yrsegal** [comment]
The problem: what do you do with nonstandard renders?

**Comment by MrPotatoGaming** [comment]
Plus, there are a lot of blocks (grass) which have multi-texture faces that aren't "average color" usually grass has a face (the top) that is a uniform color. So i planned on only sampling the top face.

Doubtful, but mod-devs /could/ define the average themselves and make it part of the Forge-API but that's quite unlikely.

**Comment by yrsegal** [comment]
Making it a part of the IStandardRenderer or whatever, in a form like
`IIcon getTopTexture()` might work, but I doubt people would go for it.

**Comment by Lazersmoke** [comment]
I guess you could make it so it actually renders each side of each block, then stores it in a file so you can use it across restarts, adding only to the first-run performance hit. That way you can even do stuff like ruidmentary reflections using the prebaked colors.

**Comment by MrPotatoGaming** [comment]
And for my personal application, I'd only have to hit whatever extends classes "grass" and "altgrass." Some mods already do this: Dense Ores and Compact Drawers uses the material type to color itself. Or at least, I assume it does.
