### ISSUE TITLE
Ring of Odin Fire Resistance Config

### ISSUE THREAD

**Issue by Kentngo** [Vazkii/Botania#1714]
Hi, I don't know how to find the logs for this, but when this option is set to false, Ring of Aesir will still apply Fire Resistance.

I mean, I don't mind being a fireproof vampire, but I figured I would report this and see if it's actually an issue.

Thanks!

**Comment by Lazersmoke** [comment]
On it, sending PR soon

**Comment by Lazersmoke** [comment]
Can't reproduce. Just to make sure we are on the same page, both Odin and Aesir should extinguish you if you are on fire, but not standing in fire. If the config says so, you will also be completely protected from lava and fire damage all together.
