### ISSUE TITLE
Garden of Glass Mana Flash does not link to the Lexica Botania GoG entry

### ISSUE THREAD

**Issue by Mace134** [Vazkii/Botania#1719]
Apologies, but a shift click with the Lexica Botania while pointed at the Mana Flash that exists statically over the GoG skyblock does not take you to the GoG entry within the Lexica but to http://ftb.gamepedia.com/Mana_Flash

**Comment by TheWhiteWolves** [comment]
We're missing the ILexiconable extension and getEntry calls in [BlackManaFlame](https://github.com/Vazkii/Botania/blob/master/src/main/java/vazkii/botania/common/block/decor/BlockManaFlame.java)

**Comment by Lazersmoke** [comment]
Will fix tonight
