### ISSUE TITLE
TileSpecialFlower logic is broken for enchanted soil

### ISSUE THREAD

**Issue by SquidDev** [Vazkii/Botania#1720]
The [checks for enchanted soil](https://github.com/Vazkii/Botania/blob/master/src/main/java/vazkii/botania/common/block/tile/TileSpecialFlower.java#L93-L103) are broken, meaning `overgrowthBoost` will always be false and `onUpdate` is executed twice. It should probably be:

```java
boolean special = isOnSpecialSoil();
boolean special = isOnSpecialSoil();
if(special) {
	subTile.overgrowth = true;
	subTile.onUpdate();
	if(subTile.isOvergrowthAffected())
		subTile.overgrowthBoost = true;

} else {
	subTile.onUpdate();
	subTile.overgrowth = false;
	subTile.overgrowthBoost = false;
}
```

**Comment by yrsegal** [comment]
No, that looks right to me...

**Comment by TheWhiteWolves** [comment]
Same here, looks right to me. It checks if its on Enchanted Soil, if it is then it checks if its allowed to be boosted and runs an update if it is, then carries on to run the standard update that should be run anyway.
