### ISSUE TITLE
Petal Apothecary does not like outside items

### ISSUE THREAD

**Issue by Zsashas** [Vazkii/Botania#1723]
I was trying to make new recipes for the Magic Bees flowers, and it seems that anything other than petals, powder, and runes will not be accepted by the apothecary (I was trying to include a bee in the recipe). Also, the original (bugged) recipes have Fire as a placeholder, so I thought I'd try that before attempting a fix, and Fire is also not accepted in item form (my pack has an obscure way to get fire items).

**Comment by yrsegal** [comment]
A fire-like item is the default in recipes if an item isn't registered. What you're seeing is what used to be the Mana Petal.

**Comment by Zsashas** [comment]
II know, but I figured, since my pack actually has a way to obtain fire (very specific way) I'd try the recipes anyway before fixing them, but the Apothecary doesn't accept fire.

**Comment by yrsegal** [comment]
it's not a real item, of course. fire's just used so it doesn't crash.

**Comment by Zsashas** [comment]
I then tried to make the new recipe include a bee, since it's a Magic Bees flower, but it wouldn't accept that either. It seems to only accept a limited list of items, and rejects everything else. Is there a way to add more items to this list?

**Comment by yrsegal** [comment]
No, as it's not a list: the item must implement [`IFlowerComponent`](https://github.com/Vazkii/Botania/blob/master/src/main/java/vazkii/botania/api/recipe/IFlowerComponent.java)

**Comment by Zsashas** [comment]
Alright, makes sense.
