### ISSUE TITLE
Accessories rendering too high on other players

### ISSUE THREAD

**Issue by MikuPL** [Vazkii/Botania#1726]
![1](https://cloud.githubusercontent.com/assets/3191269/12216979/40e32d90-b6f3-11e5-9cbe-9fb9b5f30f4c.jpg)
![2](https://cloud.githubusercontent.com/assets/3191269/12216982/4b99e7d8-b6f3-11e5-96a0-ba501495fe69.jpg)

**Comment by blacksmithgu** [comment]
Issue reproduced. Screenshot:
![2016-01-13_21 53 02](https://cloud.githubusercontent.com/assets/616490/12315405/1df2bf26-ba40-11e5-8de2-6074ef1b7284.png)

This is just a mild offset issue, this should be easily patched. Let me look at how exactly the rendering position is being derived.

**Comment by blacksmithgu** [comment]
I'm not sure what caused the issue in the first place, but modifying the offset from `1.62F` to `1.68F` fixed the problem for most of the cosmetic baubles. There are a few cosmetics which look like they've been broken for a while, so I'll sort through those later. In the mean while, the monocle and glasses now look right on other players:

![2016-01-13_22 34 27](https://cloud.githubusercontent.com/assets/616490/12315903/f91c9cac-ba45-11e5-8c56-53c255f3d733.png)

![2016-01-13_22 34 34](https://cloud.githubusercontent.com/assets/616490/12315904/fb13bacc-ba45-11e5-9d6b-75faf366fdf1.png)

![2016-01-13_22 34 43](https://cloud.githubusercontent.com/assets/616490/12315905/fcd00000-ba45-11e5-9ec4-b7b7e3f498f8.png)

The change is a single line in `api/item/IBaubleRender.java`, namely
```java
			GL11.glTranslated(0, (player != Minecraft.getMinecraft().thePlayer ? 1.62F : 0F) - player.getDefaultEyeHeight() + (player.isSneaking() ? 0.0625 : 0), 0);
```

to

```java
			GL11.glTranslated(0, (player != Minecraft.getMinecraft().thePlayer ? 1.68F : 0F) - player.getDefaultEyeHeight() + (player.isSneaking() ? 0.0625 : 0), 0);
```

Pull request forthcoming.
