### ISSUE TITLE
Gaia Summoning

### ISSUE THREAD

**Issue by ZaganStoanes** [Vazkii/Botania#1729]
I am playing on minecraft 1.7.10 with botania version  r1.7-230.jar and I am unable to summon the gaia guardian. I have tried the old way with the elementium blocks and the mana steel blocks, I have even tried 9 iron blocks under the beacon. Both methods fail to summon the guardian and paste's this into My local chat, "As hard as you try, the Beacon will not accept your sacrifice. You believe the ritual grounds might be imporoper. It might be a good idea to check for obstructions on the nearby area or large gaps on the floor." I have the alter on vanilla minecraft grass and made sure the area around it was completely flat.

**Comment by NezcalSpindrake** [comment]
You need to make the arena more clear and/or bigger.

**Comment by ZaganStoanes** [comment]
how big of an area do I need? it doesn't say in the book

**Comment by NezcalSpindrake** [comment]
I believe it shows you how big when you attempt to start it. Unless I'm wrong, somewhere between 12x12 and 15x15. I dunno the height requirement

**Comment by ZaganStoanes** [comment]
I moved it out to the desert, cleared a ton of area and still got same issue, here is some picture link's. http://tinypic.com/view.php?pic=2zdr3ir&s=9#.VpHzPYHMeUk  http://tinypic.com/view.php?pic=1zfj3no&s=9#.VpHzxYHMeUk  http://tinypic.com/view.php?pic=j0i5p0&s=9#.VpH0HoH1WUk

**Comment by NezcalSpindrake** [comment]
That... Looks like it should work. Are there cloud blocks from another mod above the arena? That could be a problem with old releases. Your best bet would probably be to update and try again.

**Comment by ZaganStoanes** [comment]
I have no mod's that add clouds to the over world. Most of My pack is the direwolf20 mod pack version 1.9.0 I have added in a few more mod's on top of what he normally has but nothing to special.

**Comment by ZaganStoanes** [comment]
no visible clouds that I can see http://tinypic.com/view.php?pic=2132mix&s=9#.VpJJnYFdqUk

**Comment by NezcalSpindrake** [comment]
You might need to update Botania individually.

**Comment by ZaganStoanes** [comment]
I updated botania and at first it didn't want to spawn but after trying a few times it finally kicked in and spawned the guardian. Thank you so much for your help.
