### ISSUE TITLE
Traveller's Gear Support

### ISSUE THREAD

**Issue by Sunconure11** [Vazkii/Botania#1730]
This was suggested on the subreddit, but, I felt like it should go here instead.

https://www.reddit.com/r/botania/comments/3z8q31/suggestion_detect_travellers_gear_to_put_cloaks/

**Comment by Nincodedo** [comment]
The [contributing guidelines](https://github.com/Vazkii/Botania/blob/master/contributing.md) on this repo say suggestions are not accepted here and should be posted to the subreddit.
