### ISSUE TITLE
Ring of Correction does not work with Pumpkins or Melons

### ISSUE THREAD

**Issue by xlstadal** [Vazkii/Botania#1732]
The best tool to break pumpkins or melons is an axe, but the ring of correction does not switch to the axe when breaking them. The ring of correction does not switch to anything specific either, just remains on whatever tool you have in hand.

**Comment by blacksmithgu** [comment]
The axe is the quickest for both pumpkins and melons, as seen in the minecraft wiki:
- http://minecraft.gamepedia.com/Melon_%28block%29
- http://minecraft.gamepedia.com/Pumpkin

This is another very easy fix. `Material.gourd` just needs to be added to the `materialsAxe` array in `common/item/equipment/ToolCommons.java`.

I'm not sure if a single line fix is worth a pull request, but someone with write permission can fix this quite easily.
