### ISSUE TITLE
Sugar cane plantable on special grass without water.

### ISSUE THREAD

**Issue by Luxor5393** [Vazkii/Botania#1736]
![2016-01-10_22 38 51](https://cloud.githubusercontent.com/assets/7762387/12224210/ef608866-b7ea-11e5-820a-9e2da5f7c138.png)

Botania v: 248
Forge v: 10.13.4.1448

**Comment by Lazersmoke** [comment]
If you update it, does it pop out?

**Comment by yrsegal** [comment]
no. This is because of this image (attached) not being implemented.
<img width="902" alt="screen shot 2016-01-10 at 6 07 58 pm" src="https://cloud.githubusercontent.com/assets/6596492/12224676/2835d720-b7c5-11e5-9454-a1cc4f05ebd1.png">

**Comment by Vazkii** [comment]
Nah it's fine.

**Comment by JRoffel** [comment]
Welp, that gives an additional bonus to the special grasses :D

**Comment by TheWhiteWolves** [comment]
haha, taking the Microsoft approach then :P, its not a bug it's a feature.
