### ISSUE TITLE
Rannuncarpus wastes cake because it placed cake on cake on cake on a floating flower if set to place blocks on a floating flower

### ISSUE THREAD

**Issue by TopPercentageRattata** [Vazkii/Botania#1740]
Rannuncarpus with a floating flower under soil places cake on cake on cake on floating flowers, not just on floating flowers.

**Comment by JRoffel** [comment]
Ok, this issue is wrong on so many levels....

Please read the [contributing guidelines](http://vazkii.us/br101) and edit your post accordingly
