### ISSUE TITLE
Colored Corporea sparks don't work on corporea funnels until logging out and back in.

### ISSUE THREAD

**Issue by Janseycraft** [Vazkii/Botania#1751]
When I create a new, colored, channel and connect a colored corporea spark to a funnel, adding a redstone signal has no response. Once I log out and back in it begins to work again. have an example in this video; https://youtu.be/aYBuncaZdo0?t=2m15s .

**Comment by Janseycraft** [comment]
The same issue goes for the interceptors as well.

**Comment by blacksmithgu** [comment]
Thanks for the bug report - I'll look into it first thing tommorow.
