### ISSUE TITLE
Rune Dupe Bug v247

### ISSUE THREAD

**Issue by yepidoodles** [Vazkii/Botania#1753]
Well, it's more of a Not-using-runes-when-it's-supposed to

When you make a rune which requires other runes, I keep getting the runes needed to craft said rune back
Here's a GIF:
https://i.gyazo.com/ace271900b588cd9cfcc4c2ff97e276d.mp4
The MP4 version didn't seem to want to load, so he's the original
https://gyazo.com/ace271900b588cd9cfcc4c2ff97e276d

**Comment by JRoffel** [comment]
This is intended behavior, the runes used in runic altar recipes are only used as catalyst.

Not an issue, please close
