### ISSUE TITLE
Spreader crashes client when unloaded

### ISSUE THREAD

**Issue by mille449** [Vazkii/Botania#1756]
Using r1.8-248 on a minecraft 1.8.9 server.  Placed the spreader (missing item texture btw) near some daybloom/nightshade primus flowers then teleported away.  No chunkloading.  Got this crash:

http://pastebin.com/ZGdSkeuz

Very repeatable.

**Comment by AlterAkima** [comment]
Issues related to the 1.8 port don't belong in this repo.
