### ISSUE TITLE
Apothecary & Everfull Urn with TC5

### ISSUE THREAD

**Issue by Zsashas** [Vazkii/Botania#1761]
https://github.com/Azanor/thaumcraft-5/issues/266

**Comment by TheWhiteWolves** [comment]
TC5 is 1.8 so that'll be with the 1.8 port of Botania, go report it to @williewillus on his repo [here](https://github.com/williewillus/Botania/issues)

**Comment by Vazkii** [comment]
The everful urn in TC4 was from Thaumic Exploration and had specific integration for the petal apothecary.

**Comment by Zsashas** [comment]
The Everfull Urn was also added to TC5 itself.

**Comment by Vazkii** [comment]
Yes, but naturally not using the TE code, and thus not retaining the petal apothecary integration.
