### ISSUE TITLE
Bauble case: shift-click behaviour

### ISSUE THREAD

**Issue by desht** [Vazkii/Botania#1763]
The Bauble case is a very useful item, but having used it, I believe it could do with one little quality-of-life enhancement...

Right now, when the case is open, shift-clicking items in the case or shift-clicking equipped baubles transfers them to the main character inventory.  I think it would be more intuitive if a shift-click (when the case is open) transferred items between the case and the equipment slots.

i.e. the following behaviour would be the most intuitive IMHO:

* Shift-click equipped item when case open: transfer to the case if space, main inventory otherwise
* Shift-click item in case: transfer to equipped bauble slot if space, main inventory otherwise
* Shift-click item in main inventory when case open: transfer to case if space, equipped bauble slot otherwise

**Comment by yrsegal** [comment]
This seems like a suggestion. Suggestions go on Reddit, not the issue
tracker.

**Comment by desht** [comment]
It's an enhancement request.

**Comment by yrsegal** [comment]
Yeah. Those go on Reddit.

**Comment by JRoffel** [comment]
Note the word: request

This belongs on reddit. 

Please close this issue, as it does not belong here

**Comment by JRoffel** [comment]
@yrsegal it seems like you were faster than me Senpai, well done :P

**Comment by TheWhiteWolves** [comment]
As @yrsegal and @JRoffel have correctly said please put any requests, suggestions, etc. on [reddit](https://www.reddit.com/r/botania/).

The github issue tracker is only for bugs, issues, problems, etc.
