### ISSUE TITLE
Crash when Shift+rightclicking Lexica Botania on multipart torch

### ISSUE THREAD

**Issue by mateon1** [Vazkii/Botania#1768]
When you place two torches on the same space/block, and create a Multipart torch, then shift+right click the torch with Lexica Botania, the game client crashes (server unaffected).

FML Log: https://gist.github.com/mateon1/beaaea0cc3212dfb8271

Related crash on OpenEye: http://openeye.openmods.info/crashes/7aa4baef5dabc5882ce1646e3fe2fc39

**Comment by TheWhiteWolves** [comment]
That looks to be a ClassCastException on FMP's side, I'd go report this to Chickenbones
