### ISSUE TITLE
2 high flowers do not give you a drop

### ISSUE THREAD

**Issue by Razorskills** [Vazkii/Botania#1769]
I created a new 1.7.10 instance on the curse launcher, it automatically uses forge 1614. I then added Botania(r1.8-248), and it auto installed Baubles(1.0.1.10)

The first image shows a 2 high vanilla flower. It drops correctly.
The next 3 are of a 2 high botania flower which do not give drops.
I also tested this in the WIP 1.8.9 version of botania which also has the same results.

![2016-01-22_19 00 29](https://cloud.githubusercontent.com/assets/6126264/12527021/4d0e9d88-c13a-11e5-985a-e0e000bed66c.png)
![2016-01-22_19 00 31](https://cloud.githubusercontent.com/assets/6126264/12527019/4d0e853c-c13a-11e5-8a53-a94b279692fe.png)
![2016-01-22_19 01 03](https://cloud.githubusercontent.com/assets/6126264/12527020/4d0e805a-c13a-11e5-9d2a-697f49c572ce.png)
![2016-01-22_19 01 05](https://cloud.githubusercontent.com/assets/6126264/12527022/4d0f7b54-c13a-11e5-8178-1bbc3fe008d5.png)
![2016-01-22_19 01 06](https://cloud.githubusercontent.com/assets/6126264/12527023/4d105b32-c13a-11e5-93f4-44f6c33290e9.png)

I had a look at the currently open issues and didn't see any similar ones on a quick glance. If you need anything else from me, please let me know.

**Comment by AlterAkima** [comment]
Botania's tall flowers only drop if broken by shears, it's listed in the book.

**Comment by Razorskills** [comment]
oh, darn. Il close this then. It didn't seem like an intended feature.
