### ISSUE TITLE
Guardian of Gaia I and 2 not fighting

### ISSUE THREAD

**Issue by Dewfire** [Vazkii/Botania#1770]
If you summon the Guardian and step back to the edge of the field and just use the Terrasteel sword's projectiles the Guardian will never move from the top of the Beacon to fight you.  

This is on a server running FTB Infinity, Botania 2.0-pre14

Let me know if you need/want more info or try anything.

**Comment by JRoffel** [comment]
Could you try to reproduce this in the latest version of botania? And the latest version of forge? If you still get this problem in the most recent version of botania & forge, please upload an fml log.

**Comment by TheWhiteWolves** [comment]
What the hell version of Botania is that, I don't remember us ever giving it the version number 2.0-pre14 the current latest is r1.8-248

**Comment by JRoffel** [comment]
Now you say it, I don't remember a version like that either... Maybe someone copied botania, gave it a "more recent" version and distributed that?

**Comment by Vazkii** [comment]
That looks like Binnie's version schema. It's possible they got the version for Botany instead.

**Comment by Dewfire** [comment]
r1.7-237  I guess I did copy the wrong version number from the Mod List, apologies!

I am unable to update to a newer version as it's from the Modpack Stated above, Infinity Evolved on a server I am playing on.  I could try loading it alone and testing.

**Comment by yrsegal** [comment]
Please do, this bug might have been fixed since the version you're on.
