### ISSUE TITLE
if I plant petals in dirt he not drop's

### ISSUE THREAD

**Issue by DyeffersonAz** [Vazkii/Botania#1773]
//

**Comment by yrsegal** [comment]
[/r/titlegore](reddit.com/r/titlegore)

Can you explain the issue further?

**Comment by DyeffersonAz** [comment]
I break a high flower and not drop...

**Comment by yrsegal** [comment]
have you tried shears?

**Comment by DyeffersonAz** [comment]
no, thanks!

**Comment by yrsegal** [comment]
please close the issue, as this is intended behavior. And read the Lexica Botania next time.
