### ISSUE TITLE
17.10 Crash - Clientside 

### ISSUE THREAD

**Issue by DPxKnightxZero** [Vazkii/Botania#1776]
Its a combination I know of your mod and NEI https://gist.github.com/DPxKnightxZero/db13920d673879678a27

This may also help -> https://gist.github.com/DPxKnightxZero/0ab50418531575a62ea5

**Comment by mindforger** [comment]
@DPxKnightxZero a full crashlog including used mod versions and and forge version would be a LOT more helpfull

**Comment by TheWhiteWolves** [comment]
Provide a full log please

**Comment by DPxKnightxZero** [comment]
Okay

**Comment by DPxKnightxZero** [comment]
Sorry I always clear my logs after I report something ... I will give you the full log next time an issue arises.

**Comment by TheWhiteWolves** [comment]
For now ill close this, if it pops up again, provide a full log and ill reopen it.
