### ISSUE TITLE
Corporea + Thermal Expansion caches

### ISSUE THREAD

**Issue by goroyoshi** [Vazkii/Botania#1786]
When hooked up to the network, the network will only detect a max size stack of whatever item is inside the cache.
http://puu.sh/mVhvB.png
http://puu.sh/mVhwc.png
Would there be a way to detect all the items in the cache?

**Comment by Vazkii** [comment]
Would #1775 do this?

**Comment by TheWhiteWolves** [comment]
it might do, depends if TE uses the same storage api, even then it may need a wrapper to count them, we can only see after you release 249 or when someone can be bothered to test it in a dev environment
