### ISSUE TITLE
Agricarnations unbinding whenever there is no nearby player

### ISSUE THREAD

**Issue by goroyoshi** [Vazkii/Botania#1787]
http://puu.sh/mVhCL.png Setup
Whenever there is no nearby player (probably when there's no player in the world since we go inside MystCraft worlds frequently) the Agricarnations unbind from the pool, there's a ChickenChunks Chunk Loader that is loading that area.
This seems to happen with Functional Flora that are linked through walls.

**Comment by mindforger** [comment]
"ChickenChunks Chunk Loader" try with another Chunkloader, those are known to cause strange loading issues, especially on dimension/worldload
