### ISSUE TITLE
Broken/missing texture. (Purple and Black blocks)

### ISSUE THREAD

**Issue by edddyeee** [Vazkii/Botania#1793]
I have Botania installed in my modpack folder for 1.7.10 and when I go ingame, there are these purple and black blocks. So does anyone know how to fix it. Also there are some items with the name "tile.botania.flower" instead of "flower". So can anyone help me fix my 2 issues?

**Comment by AlterAkima** [comment]
This is missing critical information (mod version, other mods instaled).

**Comment by edddyeee** [comment]
So how do I fix it?

Sent from my iPhone

On Feb 6, 2016, at 4:41 PM, Patric Alexandre <notifications@github.com<mailto:notifications@github.com>> wrote:


This is missing critical information (mod version, other mods instaled).

-

**Comment by AlterAkima** [comment]
Just saying that it's broken does not help.

**Comment by edddyeee** [comment]
Okay, I have it for 1.7.10 I have it in my Modpack folder, I have optifine, it is the latest version for 1.7.10. The blocks are purple and black.

Sent from my iPhone

On Feb 6, 2016, at 4:47 PM, Patric Alexandre <notifications@github.com<mailto:notifications@github.com>> wrote:


Just saying that it's broken does not help.

-

**Comment by yrsegal** [comment]
that's not the information that's needed.

**Comment by AlterAkima** [comment]
File names and full mod list (screenshot will do).

**Comment by yrsegal** [comment]
and what block is purple/black.

**Comment by edddyeee** [comment]
Okay give me a few moments

Sent from my iPhone

On Feb 6, 2016, at 4:52 PM, Wire Segal <notifications@github.com<mailto:notifications@github.com>> wrote:


and what block is purple/black.

-

**Comment by JRoffel** [comment]
If I remember correctly, vazkii's bug reporting 101 clearly states that issues using optifine are not accepted (unless of course the issue can be reproduced without optifine)

On 6 feb. 2016, at 23:54, edddyeee <notifications@github.com<mailto:notifications@github.com>> wrote:

Okay give me a few moments

Sent from my iPhone

On Feb 6, 2016, at 4:52 PM, Wire Segal <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com>> wrote:


and what block is purple/black.

-
Reply to this email directly or view it on GitHub<https://github.com/Vazkii/Botania/issues/1793#issuecomment-180879152>.

-
