### ISSUE TITLE
Sporadic crash on world load, magnet/Solegnolia related

### ISSUE THREAD

**Issue by ItsTheKais** [Vazkii/Botania#1794]
[Crash report here.](http://pastebin.com/usPHLXKE)

This happens intermittently, and never twice in a row (the world loads fine after launching MC again). As far as I can tell, it isn't related to whether or not I'm actually standing within range of a Solegnoila, nor if an item within range of a Solegnolia would be affected by my magnet.

Sorry if this is a little vague. I've been trying to figure out more about this, but I still can't reproduce it on demand. The last time I saw it before today was one week (fifteen or so Minecraft launches) ago.

Botania r1.8-248
Forge 10.13.4.1558

**Comment by JRoffel** [comment]
Can you reproduce (or try to) this with just botania installed? Also, are there any chunkloaders nearby?

On a side note, I like how you were ~150 blocks above sea level when the crash happened

**Comment by ItsTheKais** [comment]
There are no chunkloaders anywhere in the world where this happened. I have tried to produce it with just Botania, but as I mentioned, this happens very rarely.

(ATG volcano is the reason I'm that high up)

**Comment by yrsegal** [comment]
a CME? o.o
that shouldn't happen... someone's calling things from threads.

It can be solved by making a new ArrayList out of existingFlowers, but it shouldn't exist in the first place...

**Comment by williewillus** [comment]
yes, cme is possible in this case. This is because the client and server threads were accessing a static field at the same time, which fits with the description of this being an SP world.

The Weakhashmap needs to be thread local or split into two, one for each side.
