### ISSUE TITLE
EndoFlames+Indirect Chunkloading

### ISSUE THREAD

**Issue by Atraxi** [Vazkii/Botania#1795]
http://imgur.com/ov49Opt
This happens while a mana system is loaded indirectly by a nearby chunk loader, in this case 2 chunks outside the directly loaded area.
When loaded by a player or chunk loader directly there is no issue, but when partially loaded by redstone, hoppers, or some pipe/power systems crossing chunk boundaries the endoflames do not eat the charcoal. Combined with a couple of vanilla "features" (arguably bugs) where item despawn timers do not decrease under the same circumstances, while droppers+redstone continue functioning, this has the potential to cripple a server with excess item entities (which has happened to my server a few times before), as well as causing unaware players to lose stacks of fuel on a smaller scale.

Botania r1.8-247
Modpack FTB Infinity 2.3.5

I think there is also a related issue with mana bursts (9k+ existed at the same time as the charcoal), with associated performance impact, although I have been unable to confirm if it is the same issue. It would make sense though if mana spreaders operate in partially loaded chunks, since entities aren't processed it would cause them to stack up.

**Comment by yrsegal** [comment]
I think this is due to the item despawn timer, as that's what botania uses to detect whether an item is ready to burn.
