### ISSUE TITLE
Flügel Tiara's Wings don't render properly with Smart Moving

### ISSUE THREAD

**Issue by Renniuq** [Vazkii/Botania#1796]
Just thought I'd point this out, since with the animation change added by smart moving the sylph wings would look epic, but they instead just float above the player in a single orientation. Specifically, the wings always render as if the player was facing south, regardless of their actual orientation. this seems to apply to all armors and other cosmetics from the mod too, now that I test it.

**Comment by TheWhiteWolves** [comment]
That's because smart moving messes around with the renderers, at the moment I don't think we'll do anything about it.

**Comment by Renniuq** [comment]
I knew that smart moving does really rude things to renders (and that player API does really rude things to hit boxes and aiming, such as the ring of loki. That thing is off with player API, but I've used morph and Ars Magica enough to cope), just thought I'd give you a heads up in case it was something you felt like fixing and/or didn't know about, not really a problem though. Although that flying animation would be pretty perfect, right?
