### ISSUE TITLE
Corporea Crystal Cube Comparator Issue

### ISSUE THREAD

**Issue by Loraanicus** [Vazkii/Botania#1797]
When re-loading a chunk with a comparator on a corporea crystal cube, sometimes the comparator will not output a signal even if there are items in the network.

**Comment by mindforger** [comment]
just out of curiosity, are there any "chickenchunks chunkloader" present? They act funny sometimes!

**Comment by Loraanicus** [comment]
nope, no chunkloaders of any kind

**Comment by TomiBelan** [comment]
Just FYI, this sounds like an earlier duplicate of #3763. It's fixed for 1.16+ by f60aa3d348778755e62700ab4fcbacc59883f3ac.
