### ISSUE TITLE
Composite mana lens kindle warp ignites block after force relay

### ISSUE THREAD

**Issue by Janseycraft** [Vazkii/Botania#1803]
When sending a burst through the force relay (already linked), the kindle lens will ignite the block on the other side of the relay (with respect to the direction that the burst has come from) eg. burst from bottom will ignite the top of the force relay, burst from the east will ignite the block on the other side of the force relay. The burst then continues to function as expected after it hits the force relay.

**Comment by TheWhiteWolves** [comment]
any chance you can make a gif or vid of it for us

**Comment by yrsegal** [comment]
onImpact is being called when encountering a Force Relay...

Have you tried both warp/kindle and kindle/warp?
