### ISSUE TITLE
[Suggestion] Adding a Petite version of the Clayconia?

### ISSUE THREAD

**Issue by starg09** [Vazkii/Botania#1805]
As there are petite versions of other "block modifying" functional flowers, like the Marimorphosis for example, I thought this would be useful for the Clayconia, as its default range of 11x11x11 can cause problems (I have some crops on sand nearby, luckily not close enough to where I placed it... Although I did noticed some holes under my dirt shore)

Anyway, basically the petite would have a smaller range, similar to the reduction on the other petites... probably a 3x3x3?

**Comment by yrsegal** [comment]
Suggestions go on Reddit, not here.

**Comment by starg09** [comment]
My bad, sorry for that... Will make a thread over there, thanks!
