### ISSUE TITLE
[REQUEST] API or config to add custom blocks to the Rod of Plentiful Mantle

### ISSUE THREAD

**Issue by Haggle1996** [Vazkii/Botania#1806]
Please add either an API or a configuration option (whitelist/blacklist) to manually add blocks that the Rod of Plentiful Mantle can detect.

Some blocks should or should not be detectable by the rod, and using the ore dictionary is a great start; however, it would be very useful for me, as a pack developer, to have finer-grained control over what the rod can and can't see. Specifically, this addresses a conflict I've run into where I must remove blocks from the ore dictionary in order to prevent their processing on certain mods' machines, but I still want them detectable via the Rod.

**Comment by Nincodedo** [comment]
[According to the contributing.md on this repo](https://github.com/Vazkii/Botania/blob/master/contributing.md), "Suggestions are not accepted here. Post them on the forums or reddit instead. If there's any still open they're old ones before this rule was added."

**Comment by Haggle1996** [comment]
My apologies.
