### ISSUE TITLE
super strange therma lilly behaviour

### ISSUE THREAD

**Issue by mindforger** [Vazkii/Botania#1812]
i just had the strangest issue ever

I had 4 thermalilly around a blood magic nether/lava ritual

they were accidentially linked to an spreader right infront of an runic altar

the moment the altar was activated, the thermalillys hyperspammed the lavablock and used up a million mb worth of life essensce in a matter of seconds

no crash or anything just a complete loss of life essence, heavy lag and immense sound overload XD

EDIT: oooookaaaay this happens even with a normal mana spreader shooting at an mana pool ... is this some new sort of "i don't want you to spawn lava from cheap source" mechanic? i mean, we already made life essence production alsmost a nightmare so it's not cheap in our case but the thermalillys consume the lava at an rate i can only tell is bugged imho

**Comment by yrsegal** [comment]
That's intended behavior. Read the lexicon entry, it says that lava will be
consumed without power gen within five minutes of lava being fed to the
thermalilly. Use the Redstone interaction with the Master Ritual Stone to
control the lava flow.

**Comment by mindforger** [comment]
to be honest, when playing already a very long time with botania 
and having this cool down feature there for a long time
suddenly popping up with a new way of dealing with this timeout is a little bit confusing

this new way breaks the usage of the thermalilly completely ... needing to setup 1 lava source + timer + manadetector + spreader per lilly this is utterly wasting space

i know the thermalilly was WAY to OP back in the past ... with the cooldown it was a nice (yet low) base income of mana ... and now it becomes an automation nightmare

or is there any sane way to determine the state of the thermalilly?

**Comment by yrsegal** [comment]
Nope. Automate, that's what botania tries to make you do.
