### ISSUE TITLE
NEI Integration crash after mods update

### ISSUE THREAD

**Issue by belathus** [Vazkii/Botania#1813]
http://pastebin.com/dQm5A0Jz

I got the above crash after updating a few mods, including Botania (from 247 to 248), COFH Core, Thermal Expansion, NEI Integration, NEI Addons, and NEI itself (From 1.0.5.111 to 1.0.5.120). I've reverted a number of the updates, Including Botania itself, but I can't seem to isolate the cause of this crash. Any help would be appreciated.

**Comment by belathus** [comment]
After reverting Minetweaker and Modtweaker, I think this issue was caused by the newest version of Minetweaker. It is hard to say, though, but I do know that reverting it solved my crash. Also, I should note that the crash only occurred on a server, not in SSP.

**Comment by TheWhiteWolves** [comment]
Probably minetweaker doing something weird again, ill close this for now unless it can be pinned down to being specifically botania causing a crash and not minetweaker messing with things

**Comment by belathus** [comment]
I am fine with this. I'll try updating again and let you know what I see, but it doesn't seem to be a Botania issue at this point.
