### ISSUE TITLE
Multiblock Render Water Crash

### ISSUE THREAD

**Issue by L0neKitsune** [Vazkii/Botania#1816]
MultiblockRenderHandler throws a NPE when trying to get color multiplier for water.  The crash happens at line 165 when trying to get the multiplier.  It looks like minecraft throws the NPE when it tries to get the multiplier for the chunk.

**Comment by TheWhiteWolves** [comment]
do you have a copy of the stacktrace by any chance Lone

**Comment by L0neKitsune** [comment]
http://pastebin.com/NTkYffe0

I should really be better at remembering this.  Since half my job is fixing bugs.
