### ISSUE TITLE
Double Config Option?

### ISSUE THREAD

**Issue by Zsashas** [Vazkii/Botania#1818]
The Passive Wither option appears to have two lines with an option, defaulting to conflicting values.

    I:passiveDecay.time=72000
    I:passiveWither.time=-1

What do I set both to, to set decay to the proper values?

Vazkii, don't let them get to you.

**Comment by williewillus** [comment]
first one is correct
ignore the second

**Comment by Zsashas** [comment]
So the second option does nothing? Ok then.

**Comment by yrsegal** [comment]
it's a leftover from old configs.
