### ISSUE TITLE
Mana Tablet does not fulfil and recharging animation

### ISSUE THREAD

**Issue by SoskaCream** [Vazkii/Botania#1819]
I tried to fulfil a mana tablet. I had a full mana pool, when I pulled the mana tablet out of the pool, the green line didn't disapear (but the mana pool has still mana, and I checked the mana tablet stopped pumping mana). Not like a Band of Mana: when full, there is no green line for this item.
The number after the mana tablet (and Band of Mana) id does not appear too, so I can't easily check if full or not (or classify it with ID filters).

Plus, when the mana tablet is not full and handed after scrolling from a full mana tablet, it plays the recharge animation (very quick draws, like a mana tool recharging), but it does not recharge.

This is new from the last update, optifine disabled.

FML Log: http://paste.ee/p/YEqR7

**Comment by williewillus** [comment]
the number does not appear becayse mana tablets no longer use metadata (which is what that number is)

**Comment by blacksmithgu** [comment]
Indeed, mana tablets use NBT and other information in the most recent patch - a full bar implies a full tablet. That reminds me - the Band of Mana should be retrofitted as well to use the durability bar as well.

**Comment by williewillus** [comment]
yea - I'm going to start gathering up things from here that I want to implement in 1.8
