### ISSUE TITLE
Crafty crate + logistics pipe

### ISSUE THREAD

**Issue by nailfor** [Vazkii/Botania#1822]
Connecting logistics pipes(mekanism) with crafty crate have the problem of loss.
I have created a packer of coal blocks coming out of the box to which are connected logistics pipes. If the box gets more than 1 coal it all the coal from this slot is placed in one slot crafty crate. Next, if fill the crafty crate then leaves only 1 coal block, the rest of the coal simply disappears
The problem is solved installing slow pipes (bildkraft) or chute in front of the crafty crate

**Comment by williewillus** [comment]
sounds like a mechanism bug (not checking stack limit)

**Comment by nailfor** [comment]
if i'm break crafty crate before fill them, i get all coal back
