### ISSUE TITLE
Buried White Petal (Botania) then Bonemeal causes the following crash.

### ISSUE THREAD

**Issue by KaneHart** [Vazkii/Botania#1827]
Not sure if there is anything else I can provide. It's 100% repeatable. It was just in dirt, placed the white petal then bonemealed it.

http://pastebin.com/3aHGxaLs

**Comment by yrsegal** [comment]
Applecore.

**Comment by KaneHart** [comment]
It is a Applecore issue? I was wondering that /u/squeek502 Going post it at your github then.
