### ISSUE TITLE
Thaumcraft is spelled "thaumraft" in the config

### ISSUE THREAD

**Issue by TeamDman** [Vazkii/Botania#1829]
https://github.com/Vazkii/Botania/blob/0ee62f53e3d9759fd4d03bd5fac720141498fd23/src/main/java/vazkii/botania/common/core/handler/ConfigHandler.java#L253

**Comment by yrsegal** [comment]
This is obviously referring to a raft of thaumium. I don't know why anyone would report such a bug.

**Comment by williewillus** [comment]
Not much you can do now without breaking everyone's config

**Comment by yrsegal** [comment]
https://www.reddit.com/r/feedthebeast/comments/3mtv2e/introducing_thaumic_equivalence_projectethaumraft/?

https://www.reddit.com/r/feedthebeast/comments/3nrmfw/thaumic_equivalence_bridging_thaumcraft_and/?

Thaaaat's where I remembered thaumraft from
