### ISSUE TITLE
Dup Bug with Runic Altar

### ISSUE THREAD

**Issue by krakel** [Vazkii/Botania#1830]
With the automatic refill technic the used runes was not consumed. Also all Runes of Lust ... also you get back the recipe runes. Found on Botania r1.8-249 at Pack Ozone.

**Comment by JRoffel** [comment]
This is intended behavior, read your lexicon

On 28 mrt. 2016, at 11:02, Uwe D?rl <notifications@github.com<mailto:notifications@github.com>> wrote:


With the automatic refill technic the used runes was not consumed. Also all Runes of Lust ... also you get back the recipe runes. Found on Botania r1.8-249 at Pack Ozone.

-

**Comment by krakel** [comment]
Ok, Runes as catalyst. Good to know.
