### ISSUE TITLE
Weird Bug

### ISSUE THREAD

**Issue by killmetohell** [Vazkii/Botania#1831]
Some unknown reason after i updated botania i think any new made generating flowers or at least placed those new flow are not doing anything i hade kekmerius and not eating the cake i had place long while ago and i make thermaliys after i place and place lava for them they eat lava and nothing else i think and some reason their not identifying taking lava and generating from it. i want if there any way to fix this.

**Comment by williewillus** [comment]
There was a change made quite a while to thermalilies regarding how they take lava. Read your lexicon

**Comment by killmetohell** [comment]
i know but my a bit weird they don't cooldown when place more lava when notice they are not generating mana no particles do show that they stored the lava also said the kekmerius was not eating the cake as well.

**Comment by killmetohell** [comment]
also forgot to add all my old thermalilies are generating mana.

**Comment by JRoffel** [comment]
If you look at the flowers with your wand, do they show that they are connected to a mana spreader?

**Comment by killmetohell** [comment]
yes they i check twice and replace them and rebind them to right spreader

**Comment by JRoffel** [comment]
Oh, in that case, we don't handle 1.8, https://github.com/williewillus is in charge of that... (At least I think that's his git account, please correct me if I'm wrong)

**Comment by yrsegal** [comment]
you can tag people on github like so, @JRoffel 

@williewillus would be the way to call him out.

**Comment by JRoffel** [comment]
Well, totally forgot about being able to do that... My apologies

**Comment by killmetohell** [comment]
what u guys handle I'm not sure because i'm not because how mod author handle versions in that 1.8 think for mc 1.8.

**Comment by williewillus** [comment]
@yrsegal @JRoffel there was a build of Botania for MC 1.7 called "1.8-b249"

**Comment by killmetohell** [comment]
minecraft 1.7 the modpack use it is for 1.7 amd not don't the fact mana not generating not a modpack author choice at least i think its call TokienCraft 2

**Comment by yrsegal** [comment]
Could we have a screenshot of the setup, please?

**Comment by killmetohell** [comment]
of the mod pack of the mod or in-game showing the problem?

**Comment by yrsegal** [comment]
in-game.

**Comment by killmetohell** [comment]
k  let me get a screenshot.

**Comment by killmetohell** [comment]
![2016-04-03_11 02 51](https://cloud.githubusercontent.com/assets/11909414/14233996/b1402756-f98c-11e5-90f1-81ca6101ca93.png)
![2016-04-03_11 09 46](https://cloud.githubusercontent.com/assets/11909414/14233997/b42cd658-f98c-11e5-82fb-40ddc19d6a21.png)
![2016-04-03_11 02 51](https://cloud.githubusercontent.com/assets/11909414/14233998/b7eaf022-f98c-11e5-8753-c4f4f783ff8d.png)
![2016-04-03_11 11 20](https://cloud.githubusercontent.com/assets/11909414/14234008/e0a25794-f98c-11e5-98bb-fa79de7caecb.png)
![2016-04-03_11 11 23](https://cloud.githubusercontent.com/assets/11909414/14234009/e0a50a16-f98c-11e5-95e2-df07f00414dd.png)
i hope this is ok

**Comment by killmetohell** [comment]
odd thing is some odd reason my other thermalilies stop working no expect the one in cooldown

**Comment by yrsegal** [comment]
you can't have them share lava sources. It's undefined behavior.

**Comment by killmetohell** [comment]
really that new to me because how setups use to work well

**Comment by killmetohell** [comment]
old

**Comment by yrsegal** [comment]
yeah, balance changes.

**Comment by killmetohell** [comment]
what about kekmerius not working if well that right also my game crash for odd reason take while to resart back up also it seem u were right only thermalily for 1 lava seem to did the trick how odd that it changed in 249 i know many balance changes that said but was nothing saying old setup for thermaliliys and have 1 lava placement would not work anymore at i think in the change logs

**Comment by killmetohell** [comment]
oh just re thought you said some reason didn't think that one thought i know that don't share lava source that only 1 them would take it so why didn't only them didn't take source :P. i mean seen thermalilies been this the long them for take one lily take 1 source it should be fine only problem what thermalily would take and that's it.

**Comment by killmetohell** [comment]
found something after loading up my back up file because reason i'll show screenshot.
![2016-04-03_11 56 40](https://cloud.githubusercontent.com/assets/11909414/14234260/6f62ebf0-f993-11e5-8755-1c1db4d5cf65.png)
![2016-04-03_11 56 44](https://cloud.githubusercontent.com/assets/11909414/14234261/6f633132-f993-11e5-84f8-47eb35aed9e7.png)

**Comment by killmetohell** [comment]
ok found what causeing the bug for thermalilys and this one even weirder apprently for some unknown reason the the the thermalily that was on cooldown was the cause.

**Comment by killmetohell** [comment]
not still need figure that kekiurmus promblem

**Comment by killmetohell** [comment]
oh i just read book didn't notice was something new oh well didn't knew part but wasn't sure what ment it a bit so if a thermaliliy can absorb lava in cooldown then what the point cooldown in first place when was ment so thermaliliy were ment abuse that way was done beforce but oh well. oh by does any know where where they change that part is botania changelog

**Comment by williewillus** [comment]
so this can be closed?

And in the future, a little more punctuation in your messages might be easier on other readers :p

**Comment by killmetohell** [comment]
sorry about that and no it cannot not it was solve there one other problem you forgot i said before now i know was was reason thermalily problem it doesn't help me with the kekmerius problem i have haven't solve that yet don't if modpack or something in configs or something other wise.

**Comment by killmetohell** [comment]
should i Rename this or close this and make new issue for Kekimurus problem i have?

**Comment by killmetohell** [comment]
Closing this because it what ever cause is it seem it just only for whatever in my modpack and the fack there is a work a around for now.

**Comment by die4uece** [comment]
@williewillus i've got same thermalily problem on modpack project ozone 2.. got a small setup 4 thermalilies with a mfr fountain. 
first they all consumes lava and generates mana, 
than they going to cooldown, after the cooldown 3 of them are ready to generate mana while 1 is being still on cooldown process and eats all lava that fountain provides and not generating mana at all

**Comment by ArukaAlter** [comment]
Providing a constant supply of lava for flowers that are somewhat adjacent isn't optimal. They will always consume, whether in cooldown or not.

**Comment by killmetohell** [comment]
yaa i don't if there disable for it but in lexibotina it says it would consume even while on cooldown but it would also extend the cooldown time if remember reading correctly
