### ISSUE TITLE
[Request] Terrasteel armor recipes keep the enchantments from the chestplate used in crafting

### ISSUE THREAD

**Issue by oitsjustjose** [Vazkii/Botania#1832]
So hopefully the title is pretty explanatory of what my suggestion is: When crafting the Terrasteel chestplate (which consumes a manasteel chestplate) - could you add a crafting handler to clone the enchantments off of the original chestplate used? As someone progressively moving up the botania line, I got settled in with all my manasteel gear with enchantments, but now I'm finding that was all a waste!

Thanks :D

**Comment by yrsegal** [comment]
This repository isn't maintained anymore. You should probably request this
from github.com/williewillus/botania instead.

**Comment by oitsjustjose** [comment]
Oh is it not? My bad!
