### ISSUE TITLE
craft band of mana uncomfortable

### ISSUE THREAD

**Issue by TaKaQod** [Vazkii/Botania#1833]
I'm running botania on r1.8-238 and i'm knowing this is not the latest version but i'm on a modpack and i don't want to update.
It seems that this was not be change since this issue #691.
So i was trying to craft the band of mana with a mana tablet slightly fill-up and i had to empty it to get working the crafting recipe.
it would be handy if stored items could be craftable without this trick and with the maintain of mana of course ;).
Thanks for this great mod!

**Comment by yrsegal** [comment]
This repository is no longer maintained! This issue is doing absolutely nothing, sorry :P 
However, @williewillus is maintaining the Botania port. Go report this over (here!)[github.com/williewillus/botania/issues]

**Comment by yrsegal** [comment]
(also, once you do, i'm probably going to fix it. I've been doing that a lot lately.)
