### ISSUE TITLE
Mana Pool and Terrasteel Plate despawn items within 5 seconds

### ISSUE THREAD

**Issue by remyxomatosis** [Vazkii/Botania#1834]
I am playing Infinity Evolved (latest version), without any modifications. Also using faithfull 32 texture pack.

Trying to advance through botania I set up a Terrasteel plate in the required pattern. I have a spark on a mana pool and the plate, and if I toss the required three items on the plate, they will despawn after about 5 seconds. The weird part is that the blueish halo starts to form, like it is working, and then the items are gone. 
A similar behavior can be found with mana pools and tablets. Upon tossing a tablet into a full pool to transfer mana, the charging animation (blue lightning) starts, and again, five seconds later the tablet despawns.

I used to be able to charge tablets in the same world before I tried to make Terrasteel...

**Comment by JRoffel** [comment]
This repository is not being maintained anymore, you should move this issue to @williewillus botania port

**Comment by yrsegal** [comment]
This pertains to 1.7, not 1.8 or 1.9. This should not be reported to @williewillus's repo, @JRoffel.

**Comment by JRoffel** [comment]
Ahhhh, my apologies, for some reason my brain told me infinity evolved was 1.8

**Comment by OJwithC** [comment]
Sounds like you have a hopperhock nearby, not a despawning problem.

**Comment by yrsegal** [comment]
He claims he doesn't have one on the other issue.

**Comment by mindforger** [comment]
> am playing Infinity Evolved (latest version), without any modifications
single player? multiplayer? if MP what kind of server(cauldron or plain forge, any plugins installed)?
