### ISSUE TITLE
Botania r1.6-191 vs r1.8-249

### ISSUE THREAD

**Issue by Benedictum** [Vazkii/Botania#1837]
I am building a new modpack for use by my friends and family and one of the mods I'm including is from another modpack and was written for that pack. It looks like he edited an existing botania recipe and inserted 2 more, however, when i try and use his mod with the most recent build of botania i get lots of errors - http://imgur.com/EZmx7tL

I assume something changed between the botania versions thats breaking this, but the author of that other mod hasnt been responsive to my inquiries. Are you able to help me with this issue or should i just revert to botania 1.6-191 as its known to work?

**Comment by AlterAkima** [comment]
Seems like a problem with badly written scripts in MineTweaker, not on Botania.

**Comment by Benedictum** [comment]
ah so it IS done through minetweaker, i wasnt sure if it was minetweaker or an api call from these other "not" botania mods. Thanks that gives me a direction to run off in.

**Comment by williewillus** [comment]
Minetweaker 1.7 isn't being maintained anymore

**Comment by Benedictum** [comment]
Im running MineTweaker3-1.7.10-3.0.10 with ModTweaker2-0.9.5 . 

Heres the snips that are failing:

mods.botania.Lexicon.addEntry("botania.entry.etherealBloom","botania.category.functionalFlowers");
game.setLocalization("en_US", "botania.entry.etherealBloom", "Ethereal Blooms");

mods.botania.Lexicon.addEntry("botania.entry.shimmerleaf","botania.category.functionalFlowers");
game.setLocalization("en_US", "botania.entry.shimmerleaf", "Shimmerleaf");

mods.botania.Lexicon.addTextPage("botania.page.etherealBloom0","botania.entry.etherealBloom",0);
game.setLocalization("en_US", "botania.page.etherealBloom0", "The thaumaturges might believe that they own the concept of ethereal blooms, but they're wrong. The bloom is a flower, and all things flowery belong to the botanist. Obviously, there is a way to make them in a petal apothecary."); 

mods.botania.Lexicon.addTextPage("botania.page.shimmerleaf0","botania.entry.shimmerleaf",0);
game.setLocalization("en_US", "botania.page.shimmerleaf0", "The thaumaturges might believe that they own the concept of ethereal blooms, but they're wrong. The bloom is a flower, and all things flowery belong to the botanist. Obviously, there is a way to make them in a petal apothecary."); 

mods.botania.Lexicon.addPetalPage("botania.page.etherealBloom1","botania.entry.etherealBloom",1,[<Thaumcraft:blockCustomPlant:4>.withTag({display: {Name: "Botanist Ethereal Bloom"}})],[[<ore:manaPetalWhite>, <ore:manaPetalWhite>, <ore:manaPetalLightBlue>, <ore:manaPetalLightBlue>, <ore:manaPetalGreen>, <ore:petalLime>, <ore:petalCyan>, <ore:petalCyan>, <ore:petalBlue>, <ore:petalBlue>, <ore:runeEarthB>, <ore:runeSpringB>]]);
game.setLocalization("en_US", "botania.page.etherealBloom1", "&oRequires a surprising amount of iron.&r"); 

mods.botania.Lexicon.addPetalPage("botania.page.shimmerleaf1","botania.entry.shimmerleaf",1,[<Thaumcraft:blockCustomPlant:2>.withTag({display: {Name: "Botanist Shimmerleaf"}})],[[<ore:petalWhite>, <ore:manaPetalWhite>, <ore:petalLightBlue>, <ore:manaPetalLightBlue>, <ore:petalGreen>]]);
game.setLocalization("en_US", "botania.page.shimmerleaf1", "&oWay easier than with blood magic. What'd you expect?&r"); 

I tried to move that to the following:


//Add Botanist Ethereal Bloom
mods.botania.Lexicon.addEntry("botania.entry.etherealBloom","botania.category.functionalFlowers");
game.setLocalization("en_US", "botania.entry.etherealBloom", "Ethereal Bloom");
mods.botania.Lexicon.addPetalPage("botania.page.etherealBloom1","botania.entry.etherealBloom",1,[<Thaumcraft:blockCustomPlant:4>.withTag({display: {Name: "Botanist Ethereal Bloom"}})],[[<ore:manaPetalWhite>, <ore:manaPetalWhite>, <ore:manaPetalLightBlue>, <ore:manaPetalLightBlue>, <ore:manaPetalGreen>, <ore:petalLime>, <ore:petalCyan>, <ore:petalCyan>, <ore:petalBlue>, <ore:petalBlue>, <ore:runeEarthB>, <ore:runeSpringB>]]);
game.setLocalization("en_US", "botania.page.etherealBloom1", "&oRequires a surprising amount of iron.&r");
mods.botania.Apothecary.addRecipe(<Thaumcraft:blockCustomPlant:4>.withTag({display: {Name: "Botanist Ethereal Bloom"}}), [<ore:manaPetalWhite>, <ore:manaPetalWhite>, <ore:manaPetalLightBlue>, <ore:manaPetalLightBlue>, <ore:manaPetalGreen>, <ore:petalLime>, <ore:petalCyan>, <ore:petalCyan>, <ore:petalBlue>, <ore:petalBlue>, <ore:runeEarthB>, <ore:runeSpringB>]);

//Add Botanist Shimmerleaf
mods.botania.Lexicon.addEntry("botania.entry.shimmerleaf","botania.category.functionalFlowers");
game.setLocalization("en_US", "botania.entry.shimmerleaf", "Shimmerleaf");
mods.botania.Lexicon.addPetalPage("botania.page.shimmerleaf1","botania.entry.shimmerleaf",1,[<Thaumcraft:blockCustomPlant:2>.withTag({display: {Name: "Botanist Shimmerleaf"}})],[[<ore:petalWhite>, <ore:manaPetalWhite>, <ore:petalLightBlue>, <ore:manaPetalLightBlue>, <ore:petalGreen>]]);
game.setLocalization("en_US", "botania.page.shimmerleaf1", "&oWay easier than with blood magic. What'd you expect?&r"); 
mods.botania.Apothecary.addRecipe(<Thaumcraft:blockCustomPlant:2>.withTag({display: {Name: "Botanist Shimmerleaf"}}), [<ore:petalWhite>, <ore:manaPetalWhite>, <ore:petalLightBlue>, <ore:manaPetalLightBlue>, <ore:petalGreen>]);

and now i get a different set of errors, if anyone can help me with that

**Comment by Voidi** [comment]
The Minetweaker-Support **for** is done **in** Modtweaker. If there is really something wrong make an issue in  [there](https://github.com/jaredlll08/ModTweaker2)
But first, I need all your Scripts (if you don't definitvly know which one) and the full minetweaker.log.
All of these preferential via gist/pastebin.

**Comment by yrsegal** [comment]
Also the fact that you're allowing someone to literally change the SOUL MAKEUP of a flower made of MERCURY by just throwing petals and runes in an apothecary feels... wrong. Spring and Earth are not, and never will be, elemental Change, Corruption, and Healing.

\</rant\>

**Comment by Benedictum** [comment]
Voidi, thanks at first i thought it was a botania issue, so ill close this out and move it over to there.
