### ISSUE TITLE
Endoflames burn sapplings immediately after they have been changed into another type

### ISSUE THREAD

**Issue by Yadokingu** [Vazkii/Botania#1839]
When you change a sappling into another type by throwing it into a manapool with an alchemy catalyst it gets picked up immediately by nearby endoflames, instead of staying on the ground for a bit like any other fuel does. That is problematic as this makes it effectively so that you can't change sapplings if you have endoflames nearby.

r249

**Comment by yrsegal** [comment]
This repository is no longer maintained! This issue won't be fixed, sorry.

*This reply is a macro.*

**Comment by mindforger** [comment]
but still to answer that, this is a compromise solution!

You wouldn't be able to collect the items the moment they are transformed if this delay would be added again!

Items have a timer how long they have been floating on the ground, and after a certain time they become collectible ... so it's a race condition between you and the endoflames .. they would also probably win if the delay were present .. you just have a bad layout there :( add some more mana spreaders and relay the mana further away

**Comment by williewillus** [comment]
The endoflame should work with the new slowdown mechanic

**Comment by yrsegal** [comment]
The problem here is that mana pools spawn items with age high enough they can be picked up.
