### ISSUE TITLE
[1.8.9] Crash when rendering botania:pylon with shaders enabled

### ISSUE THREAD

**Issue by Drakonas** [Vazkii/Botania#1840]
I simply enabled the latest KUDA Shader beta with the built-in shadermod in Optifine HD U5, and Minecraft crashed when it attempted to render a pylon nearby.

[Minecraft Crash Report](http://pastebin.com/wLwhFZww)

[FML latest.log](http://pastebin.com/pb4NJJXf)
[FML Full Log (Trimmed)](https://gist.github.com/Drakonas/d4c859e8b5df5d8331a76932b6ca1dcb)

**Comment by Drakonas** [comment]
Should I report this to the Optifine dev instead?

**Comment by Nincodedo** [comment]
Optifine, probably. If not, still not this repo though. The 1.8.9 version of Botania is at https://github.com/williewillus/Botania, not this repo.

**Comment by Drakonas** [comment]
Oh. my bad. lol Thanks
