### ISSUE TITLE
Lexica Botania entries sorted when localized

### ISSUE THREAD

**Issue by elbo2525** [Vazkii/Botania#1841]
When I change languages, the order of lexica botania entries seems changed.

For example, in Japanese, in the Gen Flower Section, the entries come in order of DayBloom, Primus Loci, Caveats, Intro, while in English Intro, Caveats, Daybloom, Primus Loci.

Some entries seems to be prioritized, but Intro comes after DayBloom seems strange and perhaps confusing for starters.

Can the order of entries be fixed?

**Comment by yrsegal** [comment]
It's sorted by Unicode char precedence. Intended.

**Comment by elbo2525** [comment]
OK, I got it. Thank you anyway.
