### ISSUE TITLE
Getting this error when opening inventory.

### ISSUE THREAD

**Issue by KristjanKr** [Vazkii/Botania#1842]
Upon opening inventory i get error saying something about Botania Contributor Fanciness.
http://paste.ee/p/noGFb

Botania:r1.8-249.
Minecraft:1.7.10
Forge:build 1614 for minecraft 1.7.10

**Comment by TheWhiteWolves** [comment]
thats just saying that it couldn't load the contributor list, its nothing to worry about and its not an issue.
