### ISSUE TITLE
Poppy of doom:  breaking a flower still bound to a pool that is gone.

### ISSUE THREAD

**Issue by CanisArtorus** [Vazkii/Botania#1843]
I couldn't find an existing (or closed) issue on this point, for something so simple.

Breaking a Hopperhock with bare hand dropped instead a 64 stack of your 'report this' flower.
I had just silk touched (rotary bedrock pick) the only mana pool in range.  The adjacent Hibeescus ([MB] functional flower) continues to list the old location of the pool as it's bound -pool-> air block.

Probable- server communication issue, I have often seen things go temporarly to data-less state during breaking.  (turns into fail poppy, then actually breaks and drops the right flower; similarly endertanks forget their colour code for a second, then actually break into the correct item.)

**Comment by OJwithC** [comment]
Honestly I would blame the super-silk-touch bedrock pick, but I can't speak of what happened either way.

**Comment by yrsegal** [comment]
Uh... things are still bound to broken pools. NO idea what happened with the 64x borked though.
