### ISSUE TITLE
Force Relay - Not working w/Warp Lens

### ISSUE THREAD

**Issue by Sorbe** [Vazkii/Botania#1844]
Vanilla FTB IE 2.5.0.0 with included Botania r1.8-249.jar.   No other mods loaded.

Setup a simple Creative Mana Pool | Mana Spreader | .........  | Mana Pool -- verify mana is transmitted and that the pool starts to fill up. 

CMP | MS | ............ | Mana Pool

Attach a Warp Mana Lens to the Mana Spreader.  Verify that the Mana Pool continues to fill.

Put a Force Relay block between the spreader and the now filling mana pool - verify mana spread is blocked and no mana flows.

CMP | MS | ..... FR ...... | Mana Pool

Put another block (say Stone) between the Force Relay and the Mana Pool.

CMP | MS | ..... FR ..  S .. | Mana Pool

Using a Wand of the Forest, trying either function or bind mode, click on FR and then S blocks.
You will hear the appropriate audio sounds indicating the blocks were selected correctly.

No mana ever flows to the previously filling Mana Pool, no matter what you try.

The Force Relay appears to simply not work.

**Comment by mindforger** [comment]
as far as i remember (and i also found the reddit article to this one), it was never intended to warp mana, the warp lense and force relay were intended to relay any effect you burdened upon the mana burst via other lenses!

technical it is still possible to warp lense a redstone spreader and target it at a relay that links directly to a pool, but you will have to use the triggered spreader as a normal will not see a valid dumping target then!

**Comment by Sorbe** [comment]
https://youtu.be/ysMknXgYFh0?t=4m

and

From http://botaniamod.net/lexicon.php
"Elven Mana Lenses
The knowledge of mana handling methods of alfheim comes, of course, with an array of new Mana Lenses that can be experimented with.
Unlike common overworld-y lenses, these are a bit more ubiquitous in their uses...
First off, the Paintslinger Lens. This lens needs to be dyed one of the 16 colors of the spectrum to function. When a burst with its effect hits a colorable block (Wool, Stained Clay or Glass...) it'll turn any blocks connected, of the same type and color, into the color of the Mana Burst itself. It seems to work with Sheep too.
**The Warp Lens is an interesting one. A burst with its effect, when colliding with a Force Relay will teleport to the end position of said Force Relay, maintaining its momentum. **Furthermore, when it's used as a composite material to a Bore Lens (the Bore Lens must be visible) it'll make the lens not break Force Relays or Pistons, as well as teleport any blocks to the spot where the burst was fired."

**Comment by Sorbe** [comment]
Actually, If I combine a slimeball, phantom lens and warp lens, this works with non-pulsed spreaders.

It just isn't well documented that you need both of these lenses to make this work.

Recommend this as a wiki and ingame documentation update

**Comment by Sorbe** [comment]
[URL=http://lookpic.com/O/i2/745/SFUVdiwK.png][IMG]http://lookpic.com/O/t2/745/SFUVdiwK.png[/IMG][/URL]

**Comment by yrsegal** [comment]
you... tried. [you derp](!http://lookpic.com/O/i2/745/SFUVdiwK.png)

**Comment by Sorbe** [comment]
(I was still editing...)

**Comment by Sorbe** [comment]
In summary, this can be made to work, with any mana spreader, but only if you combine two lenses.
Can someone label this as a doc wiki update and then I'll close it.

**Comment by yrsegal** [comment]
This isn't a documentation update, it's the way the Spreader behaves. Without a pool to go to, it won't fire. You have to convince it you have a pool to go to (that's what your phantom lens is doing, or a bore lens) to make it fire.

**Comment by Sorbe** [comment]
It's very poorly documented.  A lot of people on reddit, myself and even Mindforger (above) didn't even know how to get this working.  

The official documentation says: "*The Warp Lens is an interesting one. A burst with its effect, when colliding with a Force Relay will teleport to the end position of said Force Relay, maintaining its momentum. *"

That alone will not get you a working solution for remote mana transmission.  It needs an update.

**Comment by yrsegal** [comment]
From the lexicon page on Mana Spreaders: "If the target of the spreader is a block that can contain Mana, and isn't full, the spreader will fire a Mana Burst, which will travel to the target, and pass the Mana along to it."
