### ISSUE TITLE
Lan Server does not seem to work with Botania(no mana usage for other players)

### ISSUE THREAD

**Issue by Lodugh** [Vazkii/Botania#1845]
I use open to lan to play with my friends and they cant use mana items. However I can use them still... I am using the latest version for Minecraft 1.7.10.

**Comment by yrsegal** [comment]
This repository is no longer maintained! This issue is doing absolutely nothing, sorry :P 
However, @williewillus is maintaining the Botania port. Go report this over [here!](http://github.com/williewillus/botania/issues)

*This reply is a macro.*
