### ISSUE TITLE
Massive log spam, GL ERROR

### ISSUE THREAD

**Issue by lightning02** [Vazkii/Botania#1846]
I'm using Botania r1.8-249.jar with Psychedelicraft 1.5.2 and i get this error.
 
![26dbbb273358a4283835b15031101a19edf40dd111817347f1 pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/11884147/15223421/a2914ae4-1874-11e6-8901-816276119983.png)

Since I don't like make duplicates i will refer to this other post that is the same problem, still not solved.

https://github.com/Ivorforce/Psychedelicraft/issues/25

**Comment by yrsegal** [comment]
This repository is no longer maintained! This issue won't be fixed, sorry.

*This reply is a macro.*

**Comment by AlterAkima** [comment]
Development in Botania 1.7.10 ceased ages ago.

**Comment by lightning02** [comment]
Well I understand.. many modders are moving to 1.9, but well.. at least the bug fixes for 1.7.10(that is still a very popular version for mods) would be nice

**Comment by yrsegal** [comment]
Vazkii quit Botania development a long time ago, and the agreement with
Willie doesn't allow him to work on 1.7 Botania, so no, it won't be fixed.
1.7 is ages old, anyway. Don't know why people keep making packs for it.

**Comment by williewillus** [comment]
Turn off shaders in the config

**Comment by lightning02** [comment]
> Vazkii quit Botania development a long time ago, and the agreement with
Willie doesn't allow him to work on 1.7 Botania, so no, it won't be fixed.
1.7 is ages old, anyway. Don't know why people keep making packs for it.


This is no sense... why Vazkii would let botania die in that way??.. it's sad

**Comment by yrsegal** [comment]
Because she had wanted to quit its development for a long time, and finally just gave up when she broke and added the passive config back. Willie is, at this point, the de-facto maintainer of Botania. It's not dead, it's just moved on.

**Comment by lightning02** [comment]
> Turn off shaders in the config, your GPU is somehow ancient and can't use them, if I'm right with what I'm seeing

I have a gtx 960 and i'm not the only one getting this error, this error happens no matter what grafic card do you use, it's somehow a fault regarding psychedelicraft, seems that psyche would conflict with every other mod that use any kind of shaders. 
Btw you're right turing off shaders in botania config solve the problem from botania side

**Comment by williewillus** [comment]
if psychedelicraft is breaking other mods, report it to them
