### ISSUE TITLE
[1.8.9] Garden of Glass does not register new world generator

### ISSUE THREAD

**Issue by hron84** [Vazkii/Botania#1847]
I tried to install Garden of Glass for 1.8.9 from [here](http://mods.curse.com/mc-mods/minecraft/232502-botania-garden-of-glass) but in the new world creation screen there is no GoG worldgen. The default worldgen creates a default world.

**Comment by williewillus** [comment]
1. Wrong repo
2. Make sure you are using the 1.8 GoG jar and the latest 1.8.9 botania
2. You need to choose the GoG world type

**Comment by hron84** [comment]
@williewillus 

1. Please link me the correct repo
2. I made sure, I using Curse launcher and I selected both mod to my custom profile from there. I also checked curse.com about versions
3. I cannot choose the GoG world type, that is the problem I trying to report.

**Comment by Nincodedo** [comment]
https://github.com/williewillus/Botania

**Comment by hron84** [comment]
For the archives: It seems like a Curse client error. Curse downloads 1.7.10 Botania for 1.8.9 GoG. You have to ensure delete the 1.7.10 Botania and install "Botania Unofficial" mod before you start the profile. Otherwise, Curse will burn some kittens and you do not want that.
