### ISSUE TITLE
Botania Skyblock Modpack running from Curse crashes on loading

### ISSUE THREAD

**Issue by MrPage** [Vazkii/Botania#1850]
Running the modpack using Curse Client. Half-way through the Mojang Loading screen, the game crashes and re-opens the minecraft launcher with the crash log.

Here's the log: http://pastebin.com/fjCdTmmx

**Comment by yrsegal** [comment]
This isn't a botania issue, it's a Dynamic Surroundings one. Remove the mod and it should work.

**Comment by MrPage** [comment]
Issue fixed. Thank you so much!
