### ISSUE TITLE
[Feature Request] Petal Block Back to Petals Recipe

### ISSUE THREAD

**Issue by Mochnant** [Vazkii/Botania#1854]
It would be a convenient enhancement if Petal Blocks could be converted back to Petals.  Currently Petals to Petal Blocks is a one way process, making them not suitable for storage purposes.

Thank you!

**Comment by yrsegal** [comment]
Done for 1.9, 1.7.10 is no longer maintained.

**Comment by Mochnant** [comment]
Thank you!  It can be done with Minetweaker in the meantime.
