### ISSUE TITLE
[Bug] Botania flower

### ISSUE THREAD

**Issue by JavaPresidente** [Vazkii/Botania#1856]
I'm getting the "Botania flower" and the achievement "Take it easy" (Awesome DW20 reference btw vazkii) When placing endoflames with the Unbreakable wand from Better Builder's Wands. Haven't tested it with other flowers but might be with other flowers aswell
![2016-06-20_19 59 44](https://cloud.githubusercontent.com/assets/19917485/16204955/989a6892-3721-11e6-993d-d77c1d0cd747.png)

**Comment by yrsegal** [comment]
This repository is no longer maintained! This issue won't be fixed, sorry.

*This reply is a macro.*
