### ISSUE TITLE
[1.10] Crash when flying around

### ISSUE THREAD

**Issue by Sejoslaw** [Vazkii/Botania#1857]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  EnderCorePlugin (EnderCore-1.10-0.4.0.29-alpha.jar)
  IC2core (industrialcraft-2-2.6.1-ex110.jar)
Contact their authors BEFORE contacting forge

// Sorry :(

Time: 28.06.16 16:33
Description: Ticking block entity

java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.util.ArrayList$Itr.next(Unknown Source)
	at net.minecraft.world.World.func_175690_a(World.java:2437)
	at net.minecraft.world.chunk.Chunk.func_177424_a(Chunk.java:785)
	at net.minecraft.world.World.func_175625_s(World.java:2393)
	at vazkii.botania.common.block.tile.TileEnchanter.func_73660_a(TileEnchanter.java:149)
	at net.minecraft.world.World.func_72939_s(World.java:1802)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1789)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.util.ArrayList$Itr.next(Unknown Source)
	at net.minecraft.world.World.func_175690_a(World.java:2437)
	at net.minecraft.world.chunk.Chunk.func_177424_a(Chunk.java:785)
	at net.minecraft.world.World.func_175625_s(World.java:2393)
	at vazkii.botania.common.block.tile.TileEnchanter.func_73660_a(TileEnchanter.java:149)

-- Block entity being ticked --
Details:
	Name: botania:enchanter // vazkii.botania.common.block.tile.TileEnchanter
	Block type: ID #895 (tile.enchanter // vazkii.botania.common.block.mana.BlockEnchanter)
	Block data value: 1 / 0x1 / 0b0001
	Block location: World: (139,143,84), Chunk: (at 11,8,4 in 8,5; contains blocks 128,0,80 to 143,255,95), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Actual block type: ID #895 (tile.enchanter // vazkii.botania.common.block.mana.BlockEnchanter)
	Actual block data value: 1 / 0x1 / 0b0001
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1802)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['SeiA666'/322, l='MpServer', x=276,01, y=76,49, z=99,08]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (208,64,248), Chunk: (at 0,4,8 in 13,15; contains blocks 208,0,240 to 223,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1064072 game time, 6430 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 61 total; [EntityCow['Cow'/257, l='MpServer', x=306,81, y=67,00, z=89,77], EntityItem['item.item.egg'/166531, l='MpServer', x=217,13, y=141,13, z=52,27], EntityCow['Cow'/258, l='MpServer', x=310,49, y=67,00, z=99,22], EntityCow['Cow'/259, l='MpServer', x=306,83, y=74,00, z=129,21], EntityBat['Bat'/213899, l='MpServer', x=349,50, y=20,87, z=115,25], EntityCow['Cow'/266, l='MpServer', x=330,82, y=73,00, z=126,90], EntitySquid['Squid'/207251, l='MpServer', x=239,59, y=52,00, z=113,60], EntityBat['Bat'/212632, l='MpServer', x=332,21, y=20,70, z=124,74], EntityBat['Bat'/213922, l='MpServer', x=205,55, y=27,01, z=75,52], EntityCow['Cow'/63780, l='MpServer', x=330,49, y=66,00, z=37,23], EntityCow['Cow'/164, l='MpServer', x=197,19, y=69,00, z=169,45], EntityCow['Cow'/165, l='MpServer', x=202,21, y=69,00, z=169,50], EntityChicken['Chicken'/169, l='MpServer', x=217,80, y=141,13, z=52,80], EntityChicken['Chicken'/170, l='MpServer', x=217,20, y=141,13, z=52,80], EntityChicken['Chicken'/171, l='MpServer', x=217,20, y=141,13, z=52,20], EntityCow['Cow'/64172, l='MpServer', x=340,77, y=68,00, z=87,48], EntityChicken['Chicken'/172, l='MpServer', x=217,80, y=141,13, z=52,80], EntityCow['Cow'/64173, l='MpServer', x=343,64, y=63,00, z=48,84], EntityChicken['Chicken'/173, l='MpServer', x=217,80, y=141,13, z=52,20], EntityBat['Bat'/206637, l='MpServer', x=281,75, y=19,10, z=60,25], EntityChicken['Chicken'/174, l='MpServer', x=217,20, y=141,13, z=52,80], EntityChicken['Chicken'/175, l='MpServer', x=217,80, y=141,13, z=52,20], EntityChicken['Chicken'/176, l='MpServer', x=217,80, y=141,13, z=52,80], EntityChicken['Chicken'/177, l='MpServer', x=217,80, y=141,13, z=52,20], EntityChicken['Chicken'/178, l='MpServer', x=217,20, y=141,13, z=52,80], EntityChicken['Chicken'/179, l='MpServer', x=219,80, y=140,00, z=52,80], EntityChicken['Chicken'/180, l='MpServer', x=219,20, y=140,00, z=52,20], EntityChicken['Chicken'/181, l='MpServer', x=219,20, y=140,00, z=52,20], EntityChicken['Chicken'/182, l='MpServer', x=219,80, y=140,00, z=52,80], EntityChicken['Chicken'/183, l='MpServer', x=219,20, y=140,00, z=52,80], EntityChicken['Chicken'/184, l='MpServer', x=219,20, y=140,00, z=52,80], EntityChicken['Chicken'/185, l='MpServer', x=219,61, y=140,00, z=52,39], EntityChicken['Chicken'/186, l='MpServer', x=219,20, y=140,00, z=52,80], EntityCow['Cow'/63803, l='MpServer', x=328,22, y=70,00, z=69,85], EntityItem['item.item.egg'/190, l='MpServer', x=217,21, y=141,13, z=52,13], EntityItem['item.item.egg'/193, l='MpServer', x=219,13, y=140,00, z=52,25], EntityPlayerSP['SeiA666'/322, l='MpServer', x=276,01, y=76,49, z=99,08], EntityCow['Cow'/196, l='MpServer', x=244,18, y=83,00, z=92,50], EntityBat['Bat'/213446, l='MpServer', x=198,36, y=48,37, z=114,03], EntityCow['Cow'/205, l='MpServer', x=241,02, y=79,00, z=90,47], EntityCow['Cow'/206, l='MpServer', x=245,83, y=82,00, z=92,23], EntityCow['Cow'/207, l='MpServer', x=248,48, y=76,00, z=102,06], EntityCow['Cow'/208, l='MpServer', x=251,55, y=74,00, z=127,59], EntityCow['Cow'/209, l='MpServer', x=240,32, y=74,00, z=139,55], EntityCow['Cow'/217, l='MpServer', x=271,41, y=74,00, z=143,30], EntityCow['Cow'/218, l='MpServer', x=267,80, y=74,00, z=154,50], EntityCow['Cow'/219, l='MpServer', x=271,55, y=75,00, z=144,32], EntityBat['Bat'/208988, l='MpServer', x=338,19, y=33,04, z=76,27], EntityBat['Bat'/207708, l='MpServer', x=330,74, y=54,03, z=159,50], EntityArmorStand['Armor Stand'/226, l='MpServer', x=274,50, y=142,00, z=49,50], EntityCow['Cow'/228, l='MpServer', x=279,22, y=69,00, z=128,47], EntityCow['Cow'/229, l='MpServer', x=276,50, y=74,00, z=143,18], EntityCow['Cow'/230, l='MpServer', x=275,40, y=76,00, z=147,15], EntityItem['item.item.feather'/100583, l='MpServer', x=219,13, y=140,00, z=52,13], EntityBat['Bat'/214379, l='MpServer', x=217,44, y=14,04, z=26,56], EntityItem['item.item.feather'/159337, l='MpServer', x=219,13, y=140,00, z=52,88], EntityCow['Cow'/240, l='MpServer', x=297,44, y=68,00, z=89,45], EntityCow['Cow'/241, l='MpServer', x=299,53, y=67,00, z=85,15], EntityCow['Cow'/242, l='MpServer', x=297,81, y=68,00, z=88,52], EntityCow['Cow'/243, l='MpServer', x=302,21, y=74,00, z=135,45], EntityCow['Cow'/244, l='MpServer', x=290,15, y=71,00, z=136,53]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:414)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:392)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_92, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 660081512 bytes (629 MB) / 2093809664 bytes (1996 MB) up to 2093809664 bytes (1996 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn512M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.32 Powered by Forge 12.18.0.2000 17 mods loaded, 17 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10-12.18.0.2000-1.10.0.jar) 
	UCHIJAAAA	Forge{12.18.0.2000} [Minecraft Forge] (forge-1.10-12.18.0.2000-1.10.0.jar) 
	UCHIJAAAA	Baubles{1.2.1.0} [Baubles] (Baubles-1.9.4-1.2.1.0.jar) 
	UCHIJAAAA	JEI{3.7.1.219} [Just Enough Items] (jei_1.10-3.7.1.219.jar) 
	UCHIJAAAA	BloodMagic{1.9.4-2.0.2-46} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.9.4-2.0.2-46.jar) 
	UCHIJAAAA	Botania{r1.8-311} [Botania] (Botania-unofficial.r1.8-311.jar) 
	UCHIJAAAA	DurabilityShow{3.1.1} [Durability Show] (Durability Show-1.9.4-3.1.1.jar) 
	UCHIJAAAA	endercore{1.10-0.4.0.29-alpha} [EnderCore] (EnderCore-1.10-0.4.0.29-alpha.jar) 
	UCHIJAAAA	EnderIO{1.10-3.0.0.50_alpha} [Ender IO] (EnderIO-1.10-3.0.0.50_alpha.jar) 
	UCHIJAAAA	forestry{5.1.5.184} [Forestry] (forestry_1.10-5.1.5.184.jar) 
	UCHIJAAAA	graves{1.10-b2-universal} [Graves Mod] (graves-1.10-b2-universal.jar) 
	UCHIJAAAA	IC2{2.6.1-ex110} [IndustrialCraft 2] (industrialcraft-2-2.6.1-ex110.jar) 
	UCHIJAAAA	IronChest{7.0.2.790} [Iron Chest] (ironchest-1.10-7.0.2.790.jar) 
	UCHIJAAAA	Morphtool{GRADLE:VERSION-GRADLE:BUILD} [Morph-o-Tool] (Morph-o-Tool-1.0-4.jar) 
	UCHIJAAAA	Psi{r1.0-36} [Psi] (Psi-r1.0-36.jar) 
	UCHIJAAAA	soulshardstow{1.10-2.5.0-34} [Soul Shards - The Old Ways] (SoulShards-TOW-1.10-2.5.0-34.jar) 
	Loaded coremods (and transformers): 
EnderCorePlugin (EnderCore-1.10-0.4.0.29-alpha.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
IC2core (industrialcraft-2-2.6.1-ex110.jar)
  
	GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.4276' Renderer: 'Intel(R) HD Graphics 4000'
	EnderIO: No known problems detected.
	Launched Version: 1.10-forge1.10-12.18.0.2000-1.10.0
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 4000 GL version 4.0.0 - Build 10.18.10.4276, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: PureBDcraft 128x MC19.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz

**Comment by williewillus** [comment]
Please report it to the 1.10 repo (williewillus/Botania) and put your log on pastebin
