### ISSUE TITLE
Feature Request: Crafting With Mana Mirror

### ISSUE THREAD

**Issue by Dupdge** [Vazkii/Botania#1859]
I'd like to be able to craft using mana mirror, as an example, let's say I place the mana mirror in my crafting grid and put in a redstone, I would then get mana powder and it would use some mana. Also, I would like to see some modifications for the mana mirror or maybe have the mana mirror read if its linked mana pool has a catalyst for use with this feature.

As an alternate, maybe we could throw redstone on the ground with the mana mirror and an arrow with a check or x pops up like at the mana pool, and when you right click the pile of items with your Wand of The Forest it makes the mana powder depending on whether you have enough mana.

**Comment by AlterAkima** [comment]
This repository is no longer being maintained.

**Comment by Zsashas** [comment]
Using the crafting grid wouldn't really fit the style of most of the mod, but the second idea led to an idea of my own...what about a new Mana Lens: Catalyst? When fired at items on the ground, it infuses them with mana. Capable of applying to several items per burst, each item would just take what it needs, like blocks with the Bore lens.

**Comment by williewillus** [comment]
I don't like a lens because then it starts stealing from the mama pool's role in automation.

If I were to do this (probably not) I would make the mana mirror a "right click hold" item that changes anything om the ground in front of it for a higher cost.

**Comment by yrsegal** [comment]
That sounds like a good solution, it can't supplant the mana pool and it isn't even worth it to use in an autoactivator if they want to
