### ISSUE TITLE
The whole game turns green if I open the lexica botania

### ISSUE THREAD

**Issue by Esmey** [Vazkii/Botania#1860]
Good morning,
first thanks for your great mod :) And i hope you can help me.

If i open the lexica my games changes the color to a green tone. Everything looks like you are underwater. Even if i close my world the colour are changed in the titel screen.
If i closed the game completly and open it again everything turns to normal until i open the book again.

Here is a picture
http://www.pic-upload.de/view-31112756/Bevore_and_after.png.html

Thanks a lot in advance.

Gameversion: 1.7.10
Forge: 10.13.4.1614-1.7.10
Botania Version: Botania r1.8-249.jar

Other installed mods:

AncientTrees-1.7.10-1.3.0.jar
antiqueatlas-4.2.2-1.7.10.jar
AppleCore-mc1.7.10-1.1.0.jar
backpack-2.0.1-1.7.x.jar
BetterFoliage-1.0.3.jar
BiblioCraft[v1.11.4][MC1.7.10].jar
BiblioWoods[BiomesOPlenty][v1.9].jar
BiblioWoods[ExtraBiomesXL][v1.4].jar
BiomesOPlenty-1.7.10-2.1.0.1826-universal.jar
Botania r1.8-249.jar
buildcraft-7.1.16-core.jar
buildcraft-7.1.16-transport.jar
buildcraft-compat-7.1.5.jar
Carpenter's Blocks v3.3.6 - MC 1.7.10.jar
Chisel2-2.3.10.37.jar
CodeChickenCore-1.7.10-1.0.7.47-universal.jar
CoFHCore-[1.7.10]3.1.2-325.jar
CustomMobSpawner 3.4.0.jar
Decocraft-2.2.1_1.7.10.jar
DrZharks MoCreatures Mod v6.3.1
DynamicLights-1.7.10.jar
EasyCrafting-1.7.10-2.0.1.16.jar
EnchantingPlus-1.7.10-3.0.2-d.jar
extrabiomesxl_1.7.10-3.16.4.jar
ExtraButtons-1.7.10.1.jar
Farseek-1.0.1.jar
GardenStuff-1.7.10-1.6.3.jar
gilded-games-util.jar
GraveStones-1.7.2_1.4.jar
hopperductmod-1.7.10-1.3.2.jar
HungerOverhaul-1.7.10-1.0.0.jar
InventoryTweaks-1.59-dev-152.jar
KoreSample-1.7.10-1.3.0.jar
liteloader-1.7.10.jar
LitWR-1.7.10-1.0.7.jar
Mantle-1.7.10-0.3.2b.jar
millenaire-6.0.0.jar
MineFactoryReloaded-[1.7.10]2.8.1-174.jar
neiaddons-1.12.14.40-mc1.7.10.jar
NetherOres-[1.7.10]2.3.1-22.jar
NotEnoughItems-1.7.10-1.0.5.120-universal.jar
OptiFine_1.7.10_HD_U_D1.jar
Pam's HarvestCraft 1.7.10j.jar
plantmegapack-4.23-1.7.10-1448.jar
RecipeAPIv1.0.1.jar
RedstonePasteMod-1.7.10-1.6.2.jar
Ruins-1.7.10.jar
ShadersModCore-v2.3.31-mc1.7.10-f.jar
SimpleRefinement-mc1.7.10-1.0.jar
SoundFilters-0.8_for_1.7.X.jar
StorageDrawers-1.7.10-1.5.6.jar
StorageDrawers-BiomesOPlenty-1.7.10-1.0.1.jar
Streams-0.1.2.jar
TConstruct-1.7.10-1.8.8.jar
TelePads-Mod-1.7.10.jar
Thaumcraft-1.7.10-4.2.3.5.jar
ThermalExpansion-[1.7.10]4.1.2-240.jar
ThermalFoundation-[1.7.10]1.2.4-114.jar
UndergroundBiomesConstructs-1.7.2-0.7.jar
VeganOption-mc1.7.10-0.1.1.jar
Waila-1.5.10_1.7.10.jar

**Comment by Esmey** [comment]
mh the link doesnt work maybe:
[URL=http://www.pic-upload.de/view-31112756/Bevore_and_after.png.html][IMG]http://www2.pic-upload.de/thumb/31112756/Bevore_and_after.png[/IMG][/URL]

**Comment by Esmey** [comment]
Sry I dont know why, but to see the picture you must copy the link in the browser search bar. :)

**Comment by AlterAkima** [comment]
Shader conflict.
This version is also not supported anymore.

**Comment by Esmey** [comment]
Really? oh I dind't know that this version is not supported anymore. thats so sad :,(
Is it possible that i can fix it myself in some way? Did i need that botania book for crafting or is it just a help?

**Comment by AlterAkima** [comment]
Botania's shaders can be turned off in the config. You can use NEI for checking recipes, but the book is the official documentation on how everything works. You can close the issue.

**Comment by Esmey** [comment]
It worked! Thanks a lot <3
