### ISSUE TITLE
The sparks rendering is too slow

### ISSUE THREAD

**Issue by Cyl18** [Vazkii/Botania#1863]
I placed 620 sparks on our server.
When I looking to them, there is only 3 fps
(http://imgur.com/8FC9ays)

But if I looking to other places, there is 63 fps

Could you add a config for disable sparks' animation?

**Comment by ArukaAlter** [comment]
This repository is no longer maintened.
Sparks are entities, placing many of them in one area and then complaining about performance drop is user fault.
Disable Terrain animations via Optfine if it's that important.

**Comment by williewillus** [comment]
It can be improved, but only with a Forge change (that would only be in 1.10.2)
For now disable terrain animations

**Comment by williewillus** [comment]
The sparks use a normal atlas sprite, the animation cannot be disabled unless you use a resource pack to change the spark texture to not be animated
