### ISSUE TITLE
Thermalily bug

### ISSUE THREAD

**Issue by Yerthh** [Vazkii/Botania#1864]
I'm playing a custom modpack in the 1.7.10 version. I tried to make a thermalily setup with a flood gate. When I place them they take lava and generate mana, but when they overheat they get bugged and some of them don't cool down and the flood gate stops working, so then I've got some thermalilies permanently overheated and a flood gate that doesn't work. I tried putting Sluices from Mariculture but nothing changed.

Note: sometimes the floodgate works, but it places lava and then the lava dissapears and then appears again all the time.

**Comment by ArukaAlter** [comment]
Intended, read the manual.
This repository is no longer maintened.

**Comment by die4uece** [comment]
i having same problem. i got a fountain setup with 4 thermalilies, after they going to cooldown fountain keeps working, means 1 or some of them consuming the lava, and when 3 of them getting ready for mana generation 1 is in cooldown and eats all lava with no generation of mana.
