### ISSUE TITLE
Bedrock Shears give undefined flower

### ISSUE THREAD

**Issue by Savageshaman** [Vazkii/Botania#1865]
I'm using the mod Rotarycraft in conjuction with Bontania and the Bedrock shears allow you to harvest any flower no matter how delicate it says, so when I tired to harvest a daybloom it turned into an undefined flower. 

FML Log:
https://gist.github.com/anonymous/9486ead7bc774d96d88d9afe6f188835

**Comment by howtonotwin** [comment]
This repository is no longer maintained; development has moved to williewillus/Botania.
