### ISSUE TITLE
Lexica Botania's wiki functionality infinitely opening pages

### ISSUE THREAD

**Issue by EZtouch** [Vazkii/Botania#1868]
I was trying to open the wiki page for cobblestone using lexica botania, it did an infinite loop sequence in the web browser, kept opening more and more tabs of the same page. I'm using FTB infinity evolved, with the 249th release of Botania.
This only happens when I'm on fullscreen mode, and when i switch to minecraft I see that it's constantly right clicking on the block, therefore opening more pages.
I have the latest JDK, but I believe minecraft is using its own version of java. I'm on Windows 10 Pro, anniversary update.

How to reproduce:
be in fullscreen mode
Shift-right click a block
Wiki page appears
another wiki page appears
infinitely more wiki pages appear
try to switch to minecraft, see it constantly right clicking the block, and the focus going to the new opened page.

This doesn't happen in non-fullscreen mode.

latest fml log: http://m.uploadedit.com/ba3s/1471281255953.txt

**Comment by williewillus** [comment]
it's a mc bug, any keybinding that is held when you tab out in fullscreen or toggle fullscreen keeps repeating until you press it again.

**Comment by EZtouch** [comment]
Well, this minecraft bug makes Botania's wiki unusable (in full-screen mode).

A possible fix would be to show the open link gui instead of automatically opening the browser and switching the focus.

**Comment by williewillus** [comment]
Either way, 1.7.10 Botania is not being worked on
