### ISSUE TITLE
Server crash when dropping petals into apothecary

### ISSUE THREAD

**Issue by Miles341** [Vazkii/Botania#1869]
Hey guys, was just trying to create my first Pure Daisy, but when I dropped the first petal into the apothecary, it just crashed? It works perfectly fine on my singleplayer world, the crash only happens on the server. Crash report below. Would be very grateful for any help you could give me.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CXLibraryCore (cxlibrary-1.10.2-1.2.2.jar)
Contact their authors BEFORE contacting forge

// Hey, that tickles! Hehehe!

Time: 28/08/16 5:26 PM
Description: Ticking block entity

java.lang.NoSuchMethodError: vazkii.botania.common.item.material.ItemPetal.getColorFromItemStack(Lnet/minecraft/item/ItemStack;I)I
	at vazkii.botania.common.item.material.ItemPetal.getParticleColor(ItemPetal.java:97)
	at vazkii.botania.common.block.tile.TileAltar.func_73660_a(TileAltar.java:263)
	at net.minecraft.world.World.func_72939_s(World.java:1804)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:619)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at vazkii.botania.common.item.material.ItemPetal.getParticleColor(ItemPetal.java:97)
	at vazkii.botania.common.block.tile.TileAltar.func_73660_a(TileAltar.java:263)

-- Block entity being ticked --
Details:
	Name: botania:altar // vazkii.botania.common.block.tile.TileAltar
	Block type: ID #390 (tile.altar // vazkii.botania.common.block.BlockAltar)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (211,68,245), Chunk: (at 3,4,5 in 13,15; contains blocks 208,0,240 to 223,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Actual block type: ID #390 (tile.altar // vazkii.botania.common.block.BlockAltar)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1804)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:619)

-- Affected level --
Details:
	Level name: world
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 625 Drop: 0
	Level seed: 6502407705538853314
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (208,64,252), Chunk: (at 0,4,12 in 13,15; contains blocks 208,0,240 to 223,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1062618 game time, 437854 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 102610 (now: false), thunder time: 28971 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_45, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 676412248 bytes (645 MB) / 1000865792 bytes (954 MB) up to 1000865792 bytes (954 MB)
	JVM Flags: 2 total; -Xmx1024M -Xms1024M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.32 Powered by Forge 12.18.1.2075 25 mods loaded, 25 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.1.2075-universal.jar) 
	UCHIJAAAA	Forge{12.18.1.2075} [Minecraft Forge] (forge-1.10.2-12.18.1.2075-universal.jar) 
	UCHIJAAAA	cxlibrary{1.2.2} [CXLibrary] (cxlibrary-1.10.2-1.2.2.jar) 
	UCHIJAAAA	advInv{1.2.0} [Advanced Inventory] (advInv-1.10-1.2.0.jar) 
	UCHIJAAAA	Baubles{1.2.1.0} [Baubles] (Baubles-1.9.4-1.2.1.0.jar) 
	UCHIJAAAA	guideapi{@VERSION@} [Guide-API] (Guide-API-1.10.2-2.0.2-45.jar) 
	UCHIJAAAA	BloodMagic{1.9.4-2.0.4-56} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.9.4-2.0.4-56.jar) 
	UCHIJAAAA	Botania{r1.8-319} [Botania] (Botania-unofficial.r1.8-319.jar) 
	UCHIJAAAA	Chameleon{1.10-2.1.7} [Chameleon] (Chameleon-1.10-2.1.7.jar) 
	UCHIJAAAA	chiselsandbits{11.7} [Chisels & Bits] (chiselsandbits-11.7.jar) 
	UCHIJAAAA	crossbowmod{1.3} [Crossbow Mod] (crossbowmod-1.3.jar) 
	UCHIJAAAA	valkyrielib{1.10.2-0.10.3} [Valkyrie Lib] (valkyrielib-1.10.2-0.10.3.jar) 
	UCHIJAAAA	environmentaltech{1.10.2-0.10.3a} [Environmental Tech] (environmentaltech-1.10.2-0.10.3a.jar) 
	UCHIJAAAA	mysticalcrops{2.0} [Mystical Crops] (Mystical Crops-1.8.8.jar) 
	UCHIJAAAA	reap{1.3.0} [Reap Mod] (ReapMod 1.3.0.jar) 
	UCHIJAAAA	roots{0.112} [Roots] (roots-1.10.2-0.112.0.jar) 
	UCHIJAAAA	simplegenerators{1.10.2-0.10.3a} [Simple Generators] (simplegenerators-1.10.2-0.10.3a.jar) 
	UCHIJAAAA	SimpleUpgrades{2.1.2-Beta} [SimpleUpgrades] (simpleupgrades-1.10.2-2.1.2-Beta-release.jar) 
	UCHIJAAAA	StorageDrawers{1.10.2-3.2.5} [Storage Drawers] (StorageDrawers-1.10.2-3.2.5.jar) 
	UCHIJAAAA	storagenetwork{1.12.8} [Storage Network] (StorageNetwork-1.9.4-1.12.8.jar) 
	UCHIJAAAA	ICSE{1.1.0.0} [I Can See Everything] (Wawla-1.10-2.3.0.193.jar) 
	UCHIJAAAA	wawla{2.3.0.193} [What Are We Looking At] (Wawla-1.10-2.3.0.193.jar) 
	UCHIJAAAA	waystones{2.0.4} [Waystones] (Waystones_1.10.2-2.0.4.jar) 
	UCHIJAAAA	YALSM{2.1.6} [Yet Another Leather Smelting Mod] (yalsm-2.1.6-mc1.9.4.jar) 
	Loaded coremods (and transformers): 
CXLibraryCore (cxlibrary-1.10.2-1.2.2.jar)
  cubex2.cxlibrary.CoreModTransformer
	Profiler Position: N/A (disabled)
	Player Count: 0 / 2; []
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by yrsegal** [comment]
@williewillus is maintaining the Botania port for 1.10. Go report this over [here!](http://github.com/williewillus/botania/issues)

*This reply is a macro.*
