### ISSUE TITLE
Corporea Autocomplete does not work

### ISSUE THREAD

**Issue by Vazkii** [Vazkii/Botania#1873]
1.9 changed autocompletion entirely, and I have a branch where it kinda (doesn't) work in the new system here: https://github.com/williewillus/Botania/tree/corpauto. Feel free to take it or I can finish it off.

original issue: https://github.com/williewillus/Botania/issues/328
Originally posted by williewillus on the now defunct BotaniaV2 repo.

**Comment by Hubry** [comment]
I don't think this is ever gonna happen again, I don't think anyone wants to take a shot at it, the relevant lexicon page was yeeted, and the request keybind is back and stronger than ever, so I'll just close this right now.
