### ISSUE TITLE
JEI integration for lesser-known recipes

### ISSUE THREAD

**Issue by Vazkii** [Vazkii/Botania#1874]
When I ported the NEI integration to JEI, I didn't notice that some of the lesser recipes don't have any indication they exist. So these have been absent for a long long time

This includes:
- Floating flower creation
- Ivy application
- Probably more I forgot (Do a find usages on IRecipe class and see what classes we have that implement it, that's everything that is missing)

Original issue: williewillus/Botania#432
Originally posted by williewillus on the now defunct BotaniaV2 repo.

**Comment by williewillus** [comment]
to my knowledge there's nothing left here to do
