### ISSUE TITLE
Aux renders are wrongly positioned when using elytra

### ISSUE THREAD

**Issue by Vazkii** [Vazkii/Botania#1876]
Baubles, mana tablet render, etc. etc.

original: https://github.com/williewillus/Botania/issues/318
Originally posted by williewillus on the now defunct BotaniaV2 repo.

**Comment by Vazkii** [comment]
Can't reproduce

**Comment by williewillus** [comment]
Should be, it'll look right when you're flying normal but if you fly, go to f3 and look downward it'll offset. Easily reproducible with monocle, etc.

If it actually doesn't happen then that's good I guess ?shrug
