### ISSUE TITLE
Remove useless fluff and irrelevant items

### ISSUE THREAD

**Issue by Vazkii** [Vazkii/Botania#1883]
- [x] Timeless Ivy (mending supersedes it)
- [x] Dispenser Tweaks (quark has it)
- [x] Natural Shedding (quark has it, and it encourages passive stalling)
- [x] Roof Tile (quark, irrelevant)
- [x] Hellish, Soul and Frosty Bricks (quark, irrelevant)
- [x] Trodden Dirt (superseded by dirt paths)
- [x] Unstable Blocks

**Comment by psychofad** [comment]
Dang, I really liked the unstable beacons, oh well, enjoyed them while they lasted :(
