### ISSUE TITLE
Incompatability with IngameInfo XML

### ISSUE THREAD

**Issue by ulkunderscore** [Vazkii/Botania#1887]
When replacing the F3 Screen with the IngameInfo XML mod's screen, the Botania debug info stays and overlaps. [Picture](http://imgur.com/a/hB9tp)

Lunatrius (current owner) said it is either a botania bug or forge.
> Forge has events for debug information that should be hidden when the event is cancelled (unless there is a bug in Forge).

Is it Botania?

**Comment by williewillus** [comment]
He needs to raise the priority of his event. Botania (B) gets the event before ingameinfo (I) can cancel it.

**Comment by williewillus** [comment]
Events are broadcast in mod load order (alphabetical + dependencies)

**Comment by Lunatrius** [comment]
Haven't seen the screenshot up until now so I wasn't sure what exactly it was. This is definitely not Botania's fault and is partially a priority issue and partially an implementation/design flaw.

I'm pretty sure that the event getting cancelled is not supposed to render anything that was collected. Why else would be there a hardcoded empty line at the top?

I have [fixed](https://github.com/Lunatrius/InGame-Info-XML/commit/7c5acdc4dbe11b1a5d0a3ed2da6b00cb0b777110) this on my side. If it's still a problem let me know.

You can safely close this issue as it's clearly not a Botania bug. *If the text didn't move to the top of the screen then that would be a Botania bug/derp (some people still don't know/use the debug event correctly).*
