### ISSUE TITLE
Server Crash - at vazkii.botania.common.item.equipment.tool.ItemGlassPick.onBlockDrops(ItemGlassPick.java:39)

### ISSUE THREAD

**Issue by ProsperCraft** [Vazkii/Botania#1889]
http://pastebin.com/Zhsek2Db

RFtools builder used as a quarry hitting something from Botania?

Minecraft version: 1.10.2
Modpack - Allthemods

**Comment by ProsperCraft** [comment]
The server is now in a crashloop-
http://pastebin.com/NCTt0uiK
http://pastebin.com/zCjksVpB

**Comment by ProsperCraft** [comment]
It thought the rftools builder acting as a quarry was a Vitreous pickaxe?

**Comment by Vazkii** [comment]
No, the pickaxe has an event handler which was being called.

**Comment by williewillus** [comment]
Screw blocks that return null getDrops >~<

**Comment by yrsegal** [comment]
Yeah, that's not supposed to happen, it's marked as @Nonnull >.>
