### ISSUE TITLE
Ring of Odin and moving dimensions

### ISSUE THREAD

**Issue by h3rrmiller** [Vazkii/Botania#1895]
Wearing the Ring of Odin and Tinker's heart canisters and traveling to dimensions like the Nether and Deep Dark cause a loss of the 10 hearts (20 hp) and when well fed will never heal back up until I take Ring of Odin off and put it back on again.  

Could be a duplicate of [Issue #803](https://github.com/Vazkii/Botania/issues/803) except I am losing the health until re-equipping the Ring not gaining extra

Mod-pack: Infinity Evolved 2.5.0

**Comment by Vazkii** [comment]
1.7 is no longer supported.

I should update the contributing.md with that...
