### ISSUE TITLE
"Removed" Dayblooms and Nightshades leave behind broken textured flowers that cause CTD

### ISSUE THREAD

**Issue by psychofad** [Vazkii/Botania#1896]
After updating to the Official Botania, any Dayblooms or Nightshades that were already in the world left behind what appeared to be poppy flowers, but TheOneProbe saw them as Botania Special Flowers.   When you remove the flower and hover over it in your inventory with your mouse it causes a Crash To Desktop making them darn near impossible to get back out of your inventory.   If they happen to land on your hotbar you are golden, simply tossing them in fire or lava removes them, but if they land in your main inventory, well, how do you remove something that you cannot pick up?  I am a server operator, so I was able to NBT edit the player.dat to remove them from the affected inventory, but others may not be so lucky.

Is there anything you can do to actually delete these flowers out of the world in an upcoming update as I am still finding the Primus versions of these flowers littered around my world.  They are much easier to spot now with that bright Pink/Black checkerboard texture that signifies a broken textured block.

**Comment by williewillus** [comment]
What's the crash? Undefined flowers should have a tooltip indicating so, not crash

**Comment by psychofad** [comment]
Oops, forgot to add the crash log, sorry.

http://pastebin.com/Ue7KnQzw

**Comment by LordHellscream** [comment]
same here, after the update from unofficial, crashing every once in a while, starting to happen after destroy and daybloom primus (which is shown as unknown object without texture after updating)
Now it crash every once in a while. I had to restore to my previous save to roll back to the unofficial version for now.

http://pastebin.com/y77WQjPi
