### ISSUE TITLE
[1.7.10] What's the getter for get the Mana Burst shooter?

### ISSUE THREAD

**Issue by Eufranio** [Vazkii/Botania#1899]
I have a server and I have installed MyTown2 for deal with griefing. I am working in protect claims from mana bursts from non-members players modify, like breaking with bore lenses, etc. Here is a guide for making protections: https://github.com/MyEssentials/MyTown2/wiki/Making-Protections

I am following the guide, and i wanted to know if there is a (accessible) method to get the owner of a Mana Burst, to allow only the owner of a claim to modify the land. Can you please help me with this?

**Comment by williewillus** [comment]
a spreader does not know who placed it

**Comment by Eufranio** [comment]
Yeah i know, but i can at least protect from Mana Bursts coming from Mana Blaster (the majority of the players of my server uses it to grief), and protecting against the Mana Burst and not the Mana Blaster is better because i would need to set the range of the protection to a high value, that would end the chances of players live near :/

**Comment by williewillus** [comment]
bursts extend vanilla's `EntityThrowable` so you can use the `getThrower()` method.

Note that this doesn't return a player *and* it could be null. Up to your protection plugin to handle it properly.

**Comment by Eufranio** [comment]
Understandable, thank you!
