### ISSUE TITLE
Crashing when an item on Mike Dongles is on a Crafting Table

### ISSUE THREAD

**Issue by MrAmericanMike** [Vazkii/Botania#1904]
Hello guys, I'm the developer of Mike Dongles, I have been reported about a crash caused by one of my tools when placed on a Crafting Table. I'm really not sure what is causing it. Maybe you can give me a hint.

This is one of the reports

https://minecraft.curseforge.com/projects/mike-dongles/issues/9

Also here.

http://pastebin.com/ebACWA2A

I couldn't reproduce the crash, so not sure what the problem is. Now I have more information, apparently it happens with already used Crop Dongles, so I'm gonna experiment with that too. But hopefully you know whats going on and help me fix it.

**Comment by ArukaAlter** [comment]
The item may have a null or invalid repair item.

**Comment by yrsegal** [comment]
This is a problem on your side, @MrAmericanMike. It's a relatively simple fix, set your tool's repair material to something nonnull.

**Comment by MrAmericanMike** [comment]
Thanks a lot. Yes I was almost 99% sure it was something I did wrong :D
The repair material, makes sense, I was confuse when creating the materials and I may have derped there and leave the wooden level one without a repair material ;)
Thanks a lot for the feedback.
