### ISSUE TITLE
Causing issues with Chisel

### ISSUE THREAD

**Issue by OldManCraft** [Vazkii/Botania#1905]
After updating to r1.9.326 in single player and server, the chisel Block futura cyan screen has changed to the video on twitter.  So I have been testing to see why.  If I remove the last chisel update and new botania 326 it don't do it. If I have the new chisel with Botania 325 it don't do it. New chisel  update and new Botania 326 it shows up. I'm pretty sure it's a Chisel thing, but why Botania is triggering it?  I will report to Chisel as well. 

chisel 1.9.4-0.0.6.48 (new) 
chisel 1.9.4-0.0.6.46 (old) 
Forge 12.18.1.2094 and 2095

**Comment by yrsegal** [comment]
If you could post the video here, it'd help those trying to figure out the problem.

**Comment by OldManCraft** [comment]
I will as soon as I get back home. Was looking at chisel issues and looks like they have a issue reported as well with other mods blocks being invisible. 

Tom

**Comment by OldManCraft** [comment]
With Botania 326 https://www.youtube.com/watch?v=afm5fbAE3To&feature=youtu.be
with Botania 325
![img_3113](https://cloud.githubusercontent.com/assets/10180530/19045628/ac8c9c88-894e-11e6-82ca-b15eeb7385a5.JPG)

**Comment by Drullkus** [comment]
ಠ_ಠ That's one weird Z Fighting. @tterrag1098, what could be causing this? 

Are you using optifine?

**Comment by OldManCraft** [comment]
No optifine

**Comment by OldManCraft** [comment]
so interesting. When I try to down grade Chisel to 46 on existing world it crashes. this is with Botania 325 and 326.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (Quark-r1.0-56.jar)
  ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.1.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.56-beta.jar)
  CoreMod (Aroma1997Core-1.9.4-1.1.1.0.jar)
  LoadingHook (Mekanism-1.10.2-9.2.0.292.jar)
  CodeChickenCorePlugin (CodeChickenCore-1.10.2-2.1.8.79-universal.jar)
  SFRCore (SolarFluxReborn_1.10.2-1.4r.jar)
  IC2core (industrialcraft-2-2.6.69-ex110.jar)
  LoadingPlugin (RandomThings-MC1.10.2-3.7.6.jar)
  TransformerLoader (OpenComputers-MC1.10.2-1.6.0.37-dev.jar)
  CCCDeobfPlugin (unknown)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.2.3.73-universal.jar)
  DepLoader (BrandonsCore-1.10.2-2.1.0.46-universal.jar)
Contact their authors BEFORE contacting forge

// You're mean.
Time: 10/3/16 10:11 AM
Description: Ticking block entity
java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=variant, clazz=class vazkii.botania.api.state.enums.PoolVariant, values=[DEFAULT, CREATIVE, DILUTED, FABULOUS]} as it does not exist in BlockStateContainer{block=bloodmagic:BlockAltar, properties=[]}
at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:196)
	at vazkii.botania.common.block.tile.mana.TilePool.getCurrentMana(TilePool.java:407)
	at vazkii.botania.common.block.tile.mana.TilePool.isFull(TilePool.java:119)
	at vazkii.botania.common.block.tile.mana.TileDistributor.func_73660_a(TileDistributor.java:36)
	at net.minecraft.world.World.func_72939_s(World.java:1804)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:619)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)

**Comment by Drullkus** [comment]
Call it a hunch but it might be related to Blood Magic

**Comment by OldManCraft** [comment]
I just tried backing down blood magic to it's prior release 1.0-63 with Botania 326 and Chisel 48 and the problem is still there. We have noticed on the server that ender io conduit facade when painted with chisel blocks are invisible in the world. They are fine painted with any other block.  Just throwing that out there....

**Comment by minecreatr** [comment]
The problem with painting with Chisel blocks is a known problem.

**Comment by OldManCraft** [comment]
I was only putting that out there as this was discovered during this process as well.  Just want to make sure all findings are shared.
