### ISSUE TITLE
Baubles beta is not recognised / Crashes when opening a world

### ISSUE THREAD

**Issue by Susjin** [Vazkii/Botania#1906]
Looks like botania is not recognizing the newer version of Baubles (1.3.BETA4), so the game dosen't start

**Comment by Vazkii** [comment]
https://github.com/Azanor/Baubles/issues/142
Don't use the beta for now.

**Comment by Vazkii** [comment]
Opening this back so I can label it as wontfix.

**Comment by Zettt** [comment]
I have a similar, or perhaps related, issue. Minecraft crashes on world load with the following error:

```
java.lang.NoClassDefFoundError: baubles/common/lib/PlayerHandler
	at vazkii.botania.common.core.handler.InternalMethodHandler.getBaublesInventory(InternalMethodHandler.java:187)
	at vazkii.botania.common.core.handler.InternalMethodHandler.getBaublesInventoryWrapped(InternalMethodHandler.java:192)
```

I have disabled the Baubles mod from FTB Unstable 1.10. No matter which combination of mod disabling and enabling I'm doing, Botania seems to be the mod that causes the crash, and it always mentions `baubles`. I presumed disabling the Baubles mod would cause Botania not to use `getBaublesInventory`, but that doesn't seem to be the case. Is this a wrong presumption or what causes this crash?

http://pastebin.com/Z7hEPKA7

**Comment by ArukaAlter** [comment]
Don't use the Baubles beta, as answered just a few lines above.

**Comment by Zettt** [comment]
Thank you for your message. I thought writing: "I have disabled the Baubles mod" would help clarify the situation.

**Comment by yrsegal** [comment]
Use a non-beta version of Baubles. Baubles is still required for botania to run.

**Comment by Zettt** [comment]
Thanks. I thought I was being more careful. Didn't know Azanor was actively working on his mods again.

For anyone else: you can return to non-beta of Baubles straight from the Curse app. Click on Baubles in the mod list, select Versions, and the choose the non-beta version to install it.

**Comment by williewillus** [comment]
*mumbles about getting rid of the dependency and just adding our own in-house auxiliary slots*

**Comment by JAWSAWN** [comment]
Is this https://gist.github.com/JAWSAWN/7575d09a1b7ff5e5d8c53264ce59512a 
crash related to that? Updated botania and baubles (i think) and upon making a new world it crashed.

**Comment by CJOak** [comment]
Yes. It says you're using Baubles{1.3.BETA5}

**Comment by JAWSAWN** [comment]
Going back to release version fixed it. Nice that I didn't make a new issue

**Comment by lilmoefow** [comment]
The BETA version will actually load up with the latest versions, but i still don't think it is recommended.

**Comment by Vazkii** [comment]
@williewillus I've considered, actually. There's a decent chance I'll actually do it tbh.

**Comment by Tamaized** [comment]
@Vazkii I'm curious, would you be adding more slots or keeping it at 4?

**Comment by Hypsellis** [comment]
It seems that I get the same bug http://pastebin.com/ZvNasG5A

**Comment by Azanor** [comment]
Any reason baubles/common/lib/PlayerHandler (and a few other classes) is being accessed directly and not via the API?

**Comment by Vazkii** [comment]
Botania has a hard dep on Baubles, and the API was reflective when I wrote
that.

**Comment by Azanor** [comment]
Understood, but to avoid stuff like this in the future it might be best to stick with the API methods. :)

**Comment by Vazkii** [comment]
Could you potentially add fallbacks for them for now? I don't want to have to split support between beta and non beta branches.

**Comment by Azanor** [comment]
The API's between beta and release versions are identical - not sure what fallbacks you are referring to.

**Comment by Vazkii** [comment]
I meant the methods outside the API, but I'll look into mitigating when I
can, though I believe I had something that required an inner class
somewhere, but I'll get to you on that.

**Comment by Azanor** [comment]
Ah ok. Let me know if you need any help, but in theory it should be a simple change.

**Comment by Vazkii** [comment]
I know this is not a good vector for it, but I do need to talk with you
about some stuff. You rarely show up on IRC so do you have any other
preferred contact method?

**Comment by Azanor** [comment]
I'm on IRC atm, or email otherwise

**Comment by Vazkii** [comment]
Fixed with https://github.com/Vazkii/Botania/commit/4d9f300087f4bf3dd62a4ea110b8d432ac5513da
