### ISSUE TITLE
Baubles 1.10

### ISSUE THREAD

**Issue by Gamewalker** [Vazkii/Botania#1915]
If I use Baubles 1.10 BETA5 and Botania 327 I get the following crash:
https://gist.github.com/Gamewalker/7bc8f780911738a8547e6076d28c8b7d

Quote Azanor:
This is a problem with Botania - it seems to be trying to access baubles directly without using the API. Since those classes don't exist anymore it now crashes. Tsk tsk

**Comment by Gamewalker** [comment]
Tried to rewrite the code to use BaublesAPI but there are few classes left that use internal packet handler from baubles to sync stuff. If someone is able to complete the code (dont know if its possible with API only) he can use my changes: https://github.com/Gamewalker/Botania/tree/BaublesAPI

**Comment by Vazkii** [comment]
#1906
