### ISSUE TITLE
Main menu stuck with new versions of Botania

### ISSUE THREAD

**Issue by Susjin** [Vazkii/Botania#1917]
I tried to update Botania to r1.9-328, but when the game is loading, the menu loads but i can't click on anything, it do not crash, just stuck
It is working just fine with version r1.9-326

Log:
http://pastebin.com/UY7dwkrC

**Comment by Vazkii** [comment]
I can't reproduce this. You'll need to do some testing to see if you can determine whether another mod causes it.
