### ISSUE TITLE
Sponge 5.0.0-BETA-1785 - Botania Botania r1.9-327 Nullpointer

### ISSUE THREAD

**Issue by alicheek** [Vazkii/Botania#1921]
Crash on startup with the latest sponge mod and botania it seems .

---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (Quark-r1.0-56.jar)
  ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.1.jar)
  IC2core (industrialcraft-2-2.6.69-ex110.jar)
  LoadingPlugin (RandomThings-MC1.10.2-3.7.6.jar)
  SpongeCoremod (hermit.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.56-beta.jar)
  NWRTweak (redstonepaste-mc1.9.4-1.7.4.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
  LoadingHook (Mekanism-1.10.2-9.2.0.292.jar)
  TransformerLoader (OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar)
Contact their authors BEFORE contacting forge

// Everything's going to plan. No, really, that was supposed to happen.

Time: 10/7/16 9:01 PM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at vazkii.botania.common.item.ItemBaubleBox$InvProvider.serializeNBT(ItemBaubleBox.java:82)
	at net.minecraftforge.common.capabilities.CapabilityDispatcher.serializeNBT(CapabilityDispatcher.java:121)
	at net.minecraft.item.ItemStack.func_77946_l(ItemStack.java:356)
	at net.minecraftforge.oredict.ShapedOreRecipe.<init>(ShapedOreRecipe.java:52)
	at vazkii.botania.common.crafting.ModCraftingRecipes.addOreDictRecipe(ModCraftingRecipes.java:2194)
	at vazkii.botania.common.crafting.ModCraftingRecipes.init(ModCraftingRecipes.java:1994)
	at vazkii.botania.common.Botania.init(Botania.java:154)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:597)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:239)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:217)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.redirect$onPost$0(LoadController.java:53)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:142)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:790)
	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:107)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:333)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:214)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Linux (amd64) version 3.14.32-xxxx-grs-ipv6-64
	Java Version: 1.8.0_102, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1704261528 bytes (1625 MB) / 3140747264 bytes (2995 MB) up to 5234491392 bytes (4992 MB)
	JVM Flags: 28 total; -Xms3G -Xmx5G -XX:NewRatio=3 -XX:+UseThreadPriorities -XX:ReservedCodeCacheSize=2048m -XX:+UseCMSCompactAtFullCollection -XX:CMSFullGCsBeforeCompaction=1 -XX:SoftRefLRUPolicyMSPerMB=2048 -XX:CMSInitiatingOccupancyFraction=90 -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+CMSParallelRemarkEnabled -XX:MaxGCPauseMillis=50 -XX:ParallelGCThreads=4 -XX:+UseAdaptiveGCBoundary -XX:-UseGCOverheadLimit -XX:+UseBiasedLocking -XX:SurvivorRatio=8 -XX:TargetSurvivorRatio=90 -XX:MaxTenuringThreshold=15 -Xoss4M -Xss4M -XX:UseSSE=4 -XX:+UseLargePages -XX:+OptimizeStringConcat -XX:+UseFastAccessorMethods -XX:+AggressiveOpts
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.1.2095 91 mods loaded, 91 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHI	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHI	FML{8.0.99.99} [Forge Mod Loader] (hermit.jar) 
	UCHI	Forge{12.18.1.2095} [Minecraft Forge] (hermit.jar) 
	UCHI	OpenComputers|Core{1.6.0.3-rc.1} [OpenComputers (Core)] (minecraft.jar) 
	UCHI	spongeapi{5.0.0-SNAPSHOT-61eeec0} [SpongeAPI] (minecraft.jar) 
	UCHI	sponge{1.10.2-2092-5.0.0-BETA-1785} [SpongeForge] (hermit.jar) 
	UCHI	actuallyadditions{1.10.2-r65} [Actually Additions] (ActuallyAdditions-1.10.2-r65.jar) 
	UCHI	autopackager{1.6.3} [AutoPackager] (autopackager-1.6.3.jar) 
	UCHI	Psi{r1.0-39} [Psi] (Psi-r1.0-39.jar) 
	UCHI	Quark{r1.0-56} [Quark] (Quark-r1.0-56.jar) 
	UCHI	AutoRegLib{1.0-2} [AutoRegLib] (AutoRegLib-1.0-2.jar) 
	UCHI	Baubles{1.2.1.0} [Baubles] (Baubles-1.9.4-1.2.1.0.jar) 
	UCHI	bdlib{1.12.2.8} [BD Lib] (bdlib-1.12.2.8-mc1.10.2.jar) 
	UCHI	betterbuilderswands{0.6.5} [Better Builder's Wands] (BetterBuildersWands-0.6.5-1.10r138+8595fc7.jar) 
	UCHI	guideapi{@VERSION@} [Guide-API] (Guide-API-1.10.2-2.0.2-45.jar) 
	UCHI	JEI{3.12.5.303} [Just Enough Items] (jei_1.10.2-3.12.5.303.jar) 
	UCHI	BloodMagic{1.9.4-2.1.0-65} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.9.4-2.1.0-65.jar) 
	UCHE	Botania{r1.9-327} [Botania] (Botania r1.9-327.jar) 
	UCHI	Chameleon{1.10-2.1.7} [Chameleon] (Chameleon-1.10-2.1.7.jar) 
	UCHI	ChestTransporter{2.5.3} [Chest Transporter] (ChestTransporter-1.10.2-2.5.3.jar) 
	UCHI	chisel{MC1.9.4-0.0.6.46} [Chisel] (Chisel-MC1.9.4-0.0.6.46.jar) 
	UCHI	mcmultipart{1.2.1} [MCMultiPart] (MCMultiPart-1.2.1-universal.jar) 
	UCHI	chiselsandbits{12.4} [Chisels & Bits] (chiselsandbits-12.4.jar) 
	UCHI	cookingforblockheads{4.2.15} [Cooking for Blockheads] (CookingForBlockheads_1.10.2-4.2.15.jar) 
	UCHI	MineTweaker3{3.0.11} [MineTweaker 3] (CraftTweaker-1.10.2-3.0.11.jar) 
	UCHI	cyclicmagic{1.7.10} [Cyclic] (Cyclic-1.10.2-1.7.10.jar) 
	UCHI	IC2{2.6.69-ex110} [IndustrialCraft 2] (industrialcraft-2-2.6.69-ex110.jar) 
	UCHI	forestry{5.2.14.263} [Forestry] (forestry_1.10.2-5.2.14.263.jar) 
	UCHI	ElecCore{1.5.311} [ElecCore] (ElecCore-1.9.4-1.5.311.jar) 
	UCHI	OpenComputers{1.6.0.3-rc.1} [OpenComputers] (OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar) 
	UCHI	deepresonance{1.2.8} [DeepResonance] (deepresonance-1.10-1.2.8.jar) 
	UCHI	StorageDrawers{1.10.2-3.2.7} [Storage Drawers] (StorageDrawers-1.10.2-3.2.7.jar) 
	UCHI	bitdrawers{0.31} [Drawers & Bits] (DrawersBits-1.10.2-0.31.jar) 
	UCHI	endercore{1.10.2-0.4.1.56-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.56-beta.jar) 
	UCHI	EnderIO{1.10.2-3.0.1.117_beta} [Ender IO] (EnderIO-1.10.2-3.0.1.117_beta.jar) 
	UCHI	shetiphiancore{3.3.1} [ShetiPhian-Core] (shetiphiancore-1.10.0-3.3.1.jar) 
	UCHI	endertanks{1.4.2} [EnderTanks] (endertanks-1.10.0-1.4.2.jar) 
	UCHI	EnderZoo{1.10-1.2.3.43} [Ender Zoo] (EnderZoo-1.10-1.2.3.43.jar) 
	UCHI	valkyrielib{1.10.2-0.10.4} [Valkyrie Lib] (valkyrielib-1.10.2-0.10.4b.jar) 
	UCHI	environmentaltech{1.10.2-0.10.4b} [Environmental Tech] (environmentaltech-1.10.2-0.10.4b.jar) 
	UCHI	ExtraUtils2{1.0} [ExtraUtils2] (extrautils2-1.10.2-alpha-1.1.0a.jar) 
	UCHI	zerocore{1.10.2-0.0.8.0} [Zero CORE] (zerocore-1.10.2-0.0.8.0.jar) 
	UCHI	bigreactors{0.4.5.16} [Extreme Reactors] (ExtremeReactors-1.10.2-0.4.5.16.jar) 
	UCHI	fastleafdecay{v11} [Fast Leaf Decay] (FastLeafDecay-v11.jar) 
	UCHI	flatcoloredblocks{mc1.10-v4.2} [Flat Colored Blocks] (flatcoloredblocks-mc1.10-v4.2.jar) 
	UCHI	flighttweaks{0.0.6-alpha} [Flight Tweaks] (flighttweaks-1.10.2-0.0.6-alpha.jar) 
	UCHI	ftbl{3.0.0} [FTBLib] (FTBLib-1.10.2-3.0.0.3.jar) 
	UCHI	ftbu{3.0.0} [FTBUtilities] (FTBUtilities-1.10.2-3.0.0.2.jar) 
	UCHI	gendustry{1.6.4.17} [GenDustry] (gendustry-1.6.4.17-mc1.10.2.jar) 
	UCHI	gravestone{1.5.6} [Gravestone] (GraveStone Mod 1.5.6.jar) 
	UCHI	hermitquest{0.1.18-beta} [HermitQuest] (hermitquest-1.10.2-0.1.18-beta.jar) 
	UCHI	hopperducts{1.4.8} [Hopper Ducts] (hopperducts-mc1.9.4-1.4.8.jar) 
	UCHI	inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks] (InventoryTweaks-1.61-58.jar) 
	UCHI	ironchest{1.10.2-7.0.11.797} [Iron Chest] (ironchest-1.10.2-7.0.11.797.jar) 
	UCHI	jeibees{0.9.0.1} [JEI Bees] (jeibees-0.9.0.1-mc1.10.2.jar) 
	UCHI	journeymap{1.10.2-5.2.4} [JourneyMap] (journeymap-1.10.2-5.2.4-unlimited.jar) 
	UCHI	mantle{1.10.2-1.0.0.jenkins170} [Mantle] (Mantle-1.10.2-1.0.0.jar) 
	UCHI	Mekanism{9.2.0} [Mekanism] (Mekanism-1.10.2-9.2.0.292.jar) 
	UCHI	MekanismGenerators{9.2.0} [MekanismGenerators] (MekanismGenerators-1.10.2-9.2.0.292.jar) 
	UCHI	MekanismTools{9.2.0} [MekanismTools] (MekanismTools-1.10.2-9.2.0.292.jar) 
	UCHI	mercurius{1.0.1} [Mercurius] (Mercurius-1.10.2-1.0.1.jar) 
	UCHI	modtweaker{2.0.4} [Mod Tweaker] (ModTweaker2-1.10.2-2.0.4.jar) 
	UCHI	Morpheus{1.10.2-3.1.7} [Morpheus] (Morpheus-1.10.2-3.1.7.jar) 
	UCHI	multistorage{1.2.3} [Multi-Storage] (multistorage-1.10.0-1.2.3b.jar) 
	UCHI	notenoughwands{1.3.7} [Not Enough Wands] (notenoughwands-1.10-1.3.7.jar) 
	UCHI	harvestcraft{1.9.4-1.10.2f} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9.4-1.10.2f.jar) 
	UCHI	platforms{1.2.0} [Platforms] (platforms-1.10.0-1.2.0.jar) 
	UCHI	reborncore{2.7.3.46} [RebornCore] (RebornCore-1.10.2-2.7.3.46-universal.jar) 
	UCHI	quantumstorage{3.2.6} [QuantumStorage] (QuantumStorage-1.10.2-3.2.6.jar) 
	UCHI	randomthings{3.7.6} [Random Things] (RandomThings-MC1.10.2-3.7.6.jar) 
	UCHI	rangedpumps{0.3} [Ranged Pumps] (rangedpumps-0.3.jar) 
	UCHI	reborncore-mcmultipart{2.7.3.46} [reborncore-MCMultiPart] (RebornCore-1.10.2-2.7.3.46-universal.jar) 
	UCHI	redstonepaste{1.7.4} [Redstone Paste] (redstonepaste-mc1.9.4-1.7.4.jar) 
	UCHI	refinedstorage{1.1.2} [Refined Storage] (refinedstorage-1.1.2.jar) 
	UCHI	xreliquary{1.10.2-1.3.3.571} [Reliquary] (Reliquary-1.10.2-1.3.3.571.jar) 
	UCHI	rftools{5.26} [RFTools] (rftools-1.10-5.26.jar) 
	UCHI	rftoolsdim{4.40} [RFTools Dimensions] (rftoolsdim-1.10-4.40.jar) 
	UCHI	roots{0.203} [Roots] (roots-1.10.2-0.203.0.jar) 
	UCHI	shadowmc{3.4.8} [ShadowMC] (ShadowMC-1.10.2-3.4.8.jar) 
	UCHI	Signals{1.0} [Signals] (Signals-1.10.2-0.4.3-universal.jar) 
	UCHI	simplegenerators{1.10.2-0.10.4e} [Simple Generators] (simplegenerators-1.10.2-0.10.4e.jar) 
	UCHI	simplyconveyors{1.7.10-1.0.0} [Simply Conveyors] (SimplyConveyors-1.0.3.jar) 
	UCHI	SleepingBag{1.3.0} [Sleeping Bag] (SleepingBag-1.10.2-1.3.0.jar) 
	UCHI	tconstruct{1.10.2-2.5.3.jenkins387} [Tinkers' Construct] (TConstruct-1.10.2-2.5.3.jar) 
	UCHI	techreborn{1.4.6.67} [TechReborn] (TechReborn-1.10.2-1.4.6.67-universal.jar) 
	UCHI	theoneprobe{1.1.3} [The One Probe] (theoneprobe-1.10-1.1.3.jar) 
	UCHI	TinkersAddons{1.0.3} [Tinkers' Addons] (Tinkers' Addons-1.10.x-1.0.3.jar) 
	UCHI	tinkertoolleveling{1.10.2-0.2.0.DEV.45854fb} [Tinkers Tool Leveling] (TinkerToolLeveling-1.10.2-0.2.0.jar) 
	UCHI	Torcherino{4.2s} [Torcherino] (Torcherino-4.2s.jar) 
	UCHI	usefulnullifiers{1.2.1} [Useful Nullifiers] (usefulnullifiers-1.2.1.jar) 
	UCHI	weaponcaseloot{4.0.1} [WeaponCaseLoot] (weaponcaseloot-1.10.2-4.0.1.jar) 
	Loaded coremods (and transformers): 
LoadingPlugin (Quark-r1.0-56.jar)
  vazkii.quark.base.asm.ClassTransformer
ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.1.jar)
  shetiphian.core.asm.ClassTransformer
IC2core (industrialcraft-2-2.6.69-ex110.jar)
  
LoadingPlugin (RandomThings-MC1.10.2-3.7.6.jar)
  lumien.randomthings.asm.ClassTransformer
SpongeCoremod (hermit.jar)
  org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
EnderCorePlugin (EnderCore-1.10.2-0.4.1.56-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
NWRTweak (redstonepaste-mc1.9.4-1.7.4.jar)
  net.fybertech.nwr.NWRTransformer
FMLPlugin (InventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
LoadingHook (Mekanism-1.10.2-9.2.0.292.jar)
  
TransformerLoader (OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar)
  li.cil.oc.common.asm.ClassTransformer
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)

	List of loaded APIs: 
		* actuallyadditionsapi (23) from ActuallyAdditions-1.10.2-r65.jar
		* Baubles|API (1.1.1.0) from Baubles-1.9.4-1.2.1.0.jar
		* BloodMagic|API (@VERSION@) from BloodMagic-1.9.4-2.1.0-65.jar
		* BotaniaAPI (82) from Botania r1.9-327.jar
		* ChiselAPI (0.0.1) from Chisel-MC1.9.4-0.0.6.46.jar
		* ChiselAPI|Carving (0.0.1) from Chisel-MC1.9.4-0.0.6.46.jar
		* ChiselsAndBitsAPI (11.7.0) from chiselsandbits-12.4.jar
		* CoFHAPI (1.8.9R1.2.0B1) from extrautils2-1.10.2-alpha-1.1.0a.jar
		* CoFHAPI|block (1.8.9R1.2.0B1) from zerocore-1.10.2-0.0.8.0.jar
		* CoFHAPI|core (1.8.9R1.2.0B1) from zerocore-1.10.2-0.0.8.0.jar
		* CoFHAPI|energy (1.8.9R1.2.0B1) from refinedstorage-1.1.2.jar
		* CoFHAPI|inventory (1.8.9R1.2.0B1) from zerocore-1.10.2-0.0.8.0.jar
		* CoFHAPI|item (1.8.9R1.2.0B1) from zerocore-1.10.2-0.0.8.0.jar
		* CoFHAPI|tileentity (1.8.9R1.2.0B1) from zerocore-1.10.2-0.0.8.0.jar
		* CoFHAPI|transport (1.8.9R1.2.0B1) from zerocore-1.10.2-0.0.8.0.jar
		* ComputerCraft|API (1.80pr0) from zerocore-1.10.2-0.0.8.0.jar
		* ComputerCraft|API|FileSystem (1.80pr0) from zerocore-1.10.2-0.0.8.0.jar
		* ComputerCraft|API|Lua (1.80pr0) from zerocore-1.10.2-0.0.8.0.jar
		* ComputerCraft|API|Media (1.80pr0) from zerocore-1.10.2-0.0.8.0.jar
		* ComputerCraft|API|Peripheral (1.80pr0) from zerocore-1.10.2-0.0.8.0.jar
		* ComputerCraft|API|Permissions (1.80pr0) from zerocore-1.10.2-0.0.8.0.jar
		* ComputerCraft|API|Redstone (1.80pr0) from zerocore-1.10.2-0.0.8.0.jar
		* ComputerCraft|API|Turtle (1.80pr0) from zerocore-1.10.2-0.0.8.0.jar
		* DR-API (1.0.4-Beta) from deepresonance-1.10-1.2.8.jar
		* ElecCore|Abilities (#API_VER#) from ElecCore-1.9.4-1.5.311.jar
		* EnderIOAPI (0.0.2) from EnderIO-1.10.2-3.0.1.117_beta.jar
		* EnderIOAPI|Redstone (0.0.2) from EnderIO-1.10.2-3.0.1.117_beta.jar
		* EnderIOAPI|Teleport (0.0.2) from EnderIO-1.10.2-3.0.1.117_beta.jar
		* EnderIOAPI|Tools (0.0.2) from EnderIO-1.10.2-3.0.1.117_beta.jar
		* environmentaltech-api (1.10.2-0.10.4b) from environmentaltech-1.10.2-0.10.4b.jar
		* ForestryAPI|apiculture (5.0.0) from forestry_1.10.2-5.2.14.263.jar
		* ForestryAPI|arboriculture (4.2.1) from forestry_1.10.2-5.2.14.263.jar
		* ForestryAPI|circuits (3.1.0) from forestry_1.10.2-5.2.14.263.jar
		* ForestryAPI|climate (2.1.0) from forestry_1.10.2-5.2.14.263.jar
		* ForestryAPI|core (5.0.0) from forestry_1.10.2-5.2.14.263.jar
		* ForestryAPI|farming (2.1.0) from forestry_1.10.2-5.2.14.263.jar
		* ForestryAPI|food (1.1.0) from forestry_1.10.2-5.2.14.263.jar
		* ForestryAPI|fuels (3.0.0) from forestry_1.10.2-5.2.14.263.jar
		* ForestryAPI|genetics (4.7.1) from forestry_1.10.2-5.2.14.263.jar
		* ForestryAPI|greenhouse (5.2.0) from forestry_1.10.2-5.2.14.263.jar
		* ForestryAPI|hives (4.1.0) from forestry_1.10.2-5.2.14.263.jar
		* ForestryAPI|lepidopterology (1.3.0) from forestry_1.10.2-5.2.14.263.jar
		* ForestryAPI|mail (3.0.0) from forestry_1.10.2-5.2.14.263.jar
		* ForestryAPI|multiblock (3.0.0) from forestry_1.10.2-5.2.14.263.jar
		* ForestryAPI|recipes (5.4.0) from forestry_1.10.2-5.2.14.263.jar
		* ForestryAPI|storage (5.0.0) from forestry_1.10.2-5.2.14.263.jar
		* ForestryAPI|world (2.1.0) from forestry_1.10.2-5.2.14.263.jar
		* gendustryAPI (2.3.0) from gendustry-1.6.4.17-mc1.10.2.jar
		* Guide-API|API (1.10.2-2.0.2-45) from Guide-API-1.10.2-2.0.2-45.jar
		* jeresources|API (0.5.1.56) from JustEnoughResources-1.10.2-0.5.1.56.jar
		* journeymap|client-api (1.2) from journeymap-1.10.2-5.2.4-unlimited.jar
		* journeymap|client-api-display (1.2) from journeymap-1.10.2-5.2.4-unlimited.jar
		* journeymap|client-api-event (1.2) from journeymap-1.10.2-5.2.4-unlimited.jar
		* journeymap|client-api-model (1.2) from journeymap-1.10.2-5.2.4-unlimited.jar
		* journeymap|client-api-util (1.2) from journeymap-1.10.2-5.2.4-unlimited.jar
		* JustEnoughItemsAPI (4.9.0) from jei_1.10.2-3.12.5.303.jar
		* McJtyLib (1.10-2.1.3) from mcjtylib-1.10-2.1.3.jar
		* MekanismAPI|core (9.0.0) from Mekanism-1.10.2-9.2.0.292.jar
		* MekanismAPI|energy (9.0.0) from Mekanism-1.10.2-9.2.0.292.jar
		* MekanismAPI|gas (9.0.0) from Mekanism-1.10.2-9.2.0.292.jar
		* MekanismAPI|infuse (9.0.0) from Mekanism-1.10.2-9.2.0.292.jar
		* MekanismAPI|laser (9.0.0) from Mekanism-1.10.2-9.2.0.292.jar
		* MekanismAPI|reactor (9.0.0) from Mekanism-1.10.2-9.2.0.292.jar
		* MekanismAPI|recipe (9.0.0) from Mekanism-1.10.2-9.2.0.292.jar
		* MekanismAPI|transmitter (9.0.0) from Mekanism-1.10.2-9.2.0.292.jar
		* MekanismAPI|util (9.0.0) from Mekanism-1.10.2-9.2.0.292.jar
		* OpenComputersAPI|Component (6.0.0-alpha) from zerocore-1.10.2-0.0.8.0.jar
		* OpenComputersAPI|Core (6.0.0-alpha) from zerocore-1.10.2-0.0.8.0.jar
		* OpenComputersAPI|Driver (6.0.0-alpha) from zerocore-1.10.2-0.0.8.0.jar
		* OpenComputersAPI|Driver|Item (6.0.0-alpha) from OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar
		* OpenComputersAPI|Event (6.0.0-alpha) from zerocore-1.10.2-0.0.8.0.jar
		* OpenComputersAPI|FileSystem (6.0.0-alpha) from zerocore-1.10.2-0.0.8.0.jar
		* OpenComputersAPI|Internal (6.0.0-alpha) from zerocore-1.10.2-0.0.8.0.jar
		* OpenComputersAPI|Machine (6.0.0-alpha) from zerocore-1.10.2-0.0.8.0.jar
		* OpenComputersAPI|Manual (6.0.0-alpha) from OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar
		* OpenComputersAPI|Network (6.0.0-alpha) from OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar
		* OpenComputersAPI|Prefab (6.0.0-alpha) from zerocore-1.10.2-0.0.8.0.jar
		* PsiAPI (2) from Psi-r1.0-39.jar
		* reborncoreAPI (2.7.3.46) from RebornCore-1.10.2-2.7.3.46-universal.jar
		* StorageDrawersAPI (1.7.10-1.2.0) from StorageDrawers-1.10.2-3.2.7.jar
		* StorageDrawersAPI|config (1.7.10-1.2.0) from StorageDrawers-1.10.2-3.2.7.jar
		* StorageDrawersAPI|event (1.7.10-1.2.0) from StorageDrawers-1.10.2-3.2.7.jar
		* StorageDrawersAPI|inventory (1.7.10-1.2.0) from StorageDrawers-1.10.2-3.2.7.jar
		* StorageDrawersAPI|pack (1.7.10-1.2.0) from StorageDrawers-1.10.2-3.2.7.jar
		* StorageDrawersAPI|registry (1.7.10-1.2.0) from refinedstorage-1.1.2.jar
		* StorageDrawersAPI|render (1.7.10-1.2.0) from refinedstorage-1.1.2.jar
		* StorageDrawersAPI|storage (1.7.10-1.2.0) from refinedstorage-1.1.2.jar
		* StorageDrawersAPI|storage-attribute (1.7.10-1.2.0) from refinedstorage-1.1.2.jar
		* techrebornAPI (1.4.6.67) from TechReborn-1.10.2-1.4.6.67-universal.jar
		* valkyrielib.api (1.10.2-0.10.4) from valkyrielib-1.10.2-0.10.4b.jar
		* zerocore|API|multiblock (1.9.4-0.0.1) from zerocore-1.10.2-0.0.8.0.jar
		* zerocore|API|multiblock|rectangular (1.9.4-0.0.1) from zerocore-1.10.2-0.0.8.0.jar
		* zerocore|API|multiblock|validation (1.9.4-0.0.1) from zerocore-1.10.2-0.0.8.0.jar
	EnderIO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker.):
                 An unsupported base software is installed: 'sponge'. This is NOT supported.
                 This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
	Detailed RF API diagnostics:
                  * RF API class 'EnergyStorage' is loaded from: jar:file:/home/minecraft/hermit/mods/Mekanism-1.10.2-9.2.0.292.jar!/cofh/api/energy/EnergyStorage.class
                  * RF API class 'IEnergyConnection' is loaded from: jar:file:/home/minecraft/hermit/mods/Mekanism-1.10.2-9.2.0.292.jar!/cofh/api/energy/IEnergyConnection.class
                  * RF API class 'IEnergyContainerItem' is loaded from: jar:file:/home/minecraft/hermit/mods/Mekanism-1.10.2-9.2.0.292.jar!/cofh/api/energy/IEnergyContainerItem.class
                  * RF API class 'IEnergyHandler' is loaded from: jar:file:/home/minecraft/hermit/mods/Mekanism-1.10.2-9.2.0.292.jar!/cofh/api/energy/IEnergyHandler.class
                  * RF API class 'IEnergyProvider' is loaded from: jar:file:/home/minecraft/hermit/mods/Mekanism-1.10.2-9.2.0.292.jar!/cofh/api/energy/IEnergyProvider.class
                  * RF API class 'IEnergyReceiver' is loaded from: jar:file:/home/minecraft/hermit/mods/Mekanism-1.10.2-9.2.0.292.jar!/cofh/api/energy/IEnergyReceiver.class
                  * RF API class 'IEnergyStorage' is loaded from: jar:file:/home/minecraft/hermit/mods/Mekanism-1.10.2-9.2.0.292.jar!/cofh/api/energy/IEnergyStorage.class
                  * RF API class 'ItemEnergyContainer' is loaded from: jar:file:/home/minecraft/hermit/mods/Mekanism-1.10.2-9.2.0.292.jar!/cofh/api/energy/ItemEnergyContainer.class
                  * RF API class 'TileEnergyHandler' is loaded from: jar:file:/home/minecraft/hermit/mods/Mekanism-1.10.2-9.2.0.292.jar!/cofh/api/energy/TileEnergyHandler.class
                  * RF API class 'TileEnergyHandler' is loaded from: jar:file:/home/minecraft/hermit/mods/Mekanism-1.10.2-9.2.0.292.jar!/cofh/api/energy/TileEnergyHandler.class

	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge,sponge'
	Type: Dedicated Server (map_server.txt)

**Comment by Vazkii** [comment]
Report this to Sponge.
