### ISSUE TITLE
What version of Baubles?

### ISSUE THREAD

**Issue by MrAmericanMike** [Vazkii/Botania#1922]
When I try to launch and create a world this error happens.

http://pastebin.com/TzYDDPNd

I guess it's because of the Baubles version I'm using, but already tried Baubles-1.10.2-1.3.BETA7.jar and Baubles-1.10.2-1.3.BETA6.jar and both generate same error.

What could be the problem here?

Using Botania r1.9-328.jar
and Forge 12.18.1.2092

**Comment by Alaberti** [comment]
https://github.com/Vazkii/Botania/issues/1906
