### ISSUE TITLE
Terrasteel Helmet Renders Back to Front?

### ISSUE THREAD

**Issue by thiakil** [Vazkii/Botania#1923]
I'm guessing a helmet should have the gap at the front?

Botania r1.9-327

My Back:
![2016-10-09_20 30 22](https://cloud.githubusercontent.com/assets/1788847/19220466/25b08726-8e60-11e6-88d6-af06893f105c.png)

My front
![2016-10-09_20 30 30](https://cloud.githubusercontent.com/assets/1788847/19220468/2792ce96-8e60-11e6-9f4d-5d258a9c8bf0.png)

**Comment by CJOak** [comment]
Pretty sure that's how it's supposed to look.

**Comment by ArukaAlter** [comment]
The texture is slightly inclined, the back of the helmet was supposed to be lower, and the front higher.

**Comment by thiakil** [comment]
oh, ok xD 
Hard to find images on google to confirm... Don't helmets usually cover the back of the head?

**Comment by ArukaAlter** [comment]
You can check with an 1.7.10 build or in the last unofficial one.

**Comment by Vazkii** [comment]
The current armor models are temporary to fit with the 1.8+ player models
until wiiv sorts some new ones out.
