### ISSUE TITLE
[1.10.2] Damaging Lens doesn't damage and tripwire lens can't be mixed with a prism

### ISSUE THREAD

**Issue by JAWSAWN** [Vazkii/Botania#1925]
Damaging lens doesn't damage players. 

And putting a mana prism in front of the tripwired mana spreader, it simply blocks the path between pool and the spreader.

**Comment by howtonotwin** [comment]
I doubt this is the issue, but I would like to point out that `LensTripwire.TAG_TRIPPED` has a typo `botania:`*`triwire`*`LensTripped`.

**Comment by Vazkii** [comment]
The prism detaches the lens from the burst, so this is normal. The damage
lens not working on players is intentional.
