### ISSUE TITLE
Kindle Lens does not Extinguish Nether Portals

### ISSUE THREAD

**Issue by Dilnu** [Vazkii/Botania#1928]
I fired a mana burst directly at the portal as shown in the screenshot and the portal did not extinguish.

Screenshot:
http://imgur.com/a/dzNF4
Log:
http://paste.ee/p/OYpgm

**Comment by williewillus** [comment]
the teleportation code runs before the impact code so I don't think this is possible.

Maybe try aiming it at the edge of the frame next to the portal block

**Comment by Dilnu** [comment]
I've tried a bunch of variant aimings. Including some that point at the inside edge of the portal frame. None of them have any effect. If you have a more specific suggestion or a screenshot of something that works for you I'd be happy to try it myself. 

Screenshot:
http://imgur.com/a/0zfJ8

**Comment by williewillus** [comment]
If it doesn't work on the inside edge then it's probably just a missing feature/oversight in the implementation
