### ISSUE TITLE
world creation crash

### ISSUE THREAD

**Issue by DRJONES15** [Vazkii/Botania#1929]
When ever I create a world it loads for a little bit then freezes, so i have to force stop the game. Then when I reload a try to launch the previously created world it gives me the following crash report.  This report my be related to an earlier post but i tryed mixing the last three versions of botaina woth the last three versions of baubbles and get the same error every time.
Forge log https://gist.github.com/DRJONES15/93aed7865c3639bfa7cedddc9710429c
Forge Crash report https://gist.github.com/DRJONES15/eb4c0e286fb52813a65f7c648d220fd8

**Comment by jod4** [comment]
@DRJONES15 I had the same issue. Make sure you have the correct Baubles version installed, Baubles-1.9.4-1.2.1.0.jar (in Curse launcher). Baubles is undergoing some major restructuring implementations and Vazkii will wait for a proper release before switching to supporting newer versions of the Baubles-API, I guess.

**Comment by DRJONES15** [comment]
thanks for the help i hope this problem gets fix soon because i hate not being on the latest version. having the little download symbol in my mod list on curse drives me nut knowing i cant push it.
