### ISSUE TITLE
Key of King's Law glitches on half the circle

### ISSUE THREAD

**Issue by DaedalusGame** [Vazkii/Botania#1930]
In half the circle, the key produces the hips of babylon as it should, on the other half, the one pointing towards NE, it merely produces a shaft of babylon and two balls of babylon.

[Illustration not available for red-green colorblind men](http://i.imgur.com/a8KaAGy.png)

**Comment by Vazkii** [comment]
💯 description.

**Comment by Vazkii** [comment]
quality math @williewillus https://github.com/Vazkii/Botania/blob/master/src/main/java/vazkii/botania/common/item/relic/ItemKingKey.java#L81
