### ISSUE TITLE
Rosa Arcana not taking proper amount of EXP per level

### ISSUE THREAD

**Issue by SimPiko** [Vazkii/Botania#1931]
While playing Skyexchange modpack (Botania r1.9-327), I've noticed that when Rosa Arcana has taken whole EXP level, it restores only ~50% of EXP bar (at ~30lvl and up) and it restores more than a bar at ~5lvl or lower (the highlighted part of Exp bar goes waay to the right).

I've quickly looked in code here on GitHub, and looks like '[ExperienceHelper.java](https://github.com/Vazkii/Botania/blob/e38556d265fcf43273c99ea1299a35400bf0c405/src/main/java/vazkii/botania/common/core/helper/ExperienceHelper.java#L38)' uses old equations for figuring out exp amount. It should be something like (at least according to Minecraft Wiki):
```
if (level > 0 && level < 17)
	return (int) (level * level + 6 * level);
else if (level > 16 && level < 32)
	return (int) (2.5 * level * level - 40.5 * level + 360);
else
	return (int) (4.5 * level * level - 162.5 * level + 2220);
```

**Comment by Vazkii** [comment]
Cheers.
