### ISSUE TITLE
Elven Mana Spreader stops working...

### ISSUE THREAD

**Issue by AnthonyKane5528X** [Vazkii/Botania#1932]
I'm having an issues with an Elven Mana Spreader that randomly stops working.

Running Botania in the Direwolf20 1.7.10 Mod Pack
Botania r1.8-224

My setup is a simple entropinnyum automation.
3 entropinnyums (setup in a v shape) feeding into 1 Eleven Mana Spreader with a Potency lens firing through a Mana Detector.  Underneath the mana detector I'm using Ender IO insulated redstone conduit to run back to a  Projectred Intergration State Cell set to only trigger a redstone signal 10 seconds AFTER the last pulse.
2 Autonomus activators set to only output with a strong redstone signal.  Using 1st slot only.  They are dispensing Mini TNT from AE2.  They eject the Mini TNT simultaneously directly onto 2 restone blocks to activate the TNT.

At first I thought this might be a chunk issue as when I checked my build the timer sat right on the chunk boundary.  I moved the entire setup within the same chunk but the issue keeps happening.  I switched to Mini TNT from regular TNT after the second time the system stopped working.

As far as I can tell the Mana spreader either fills completely and then stops outputting randomly or simply stops outputting mana.  I either have to break and replace the spreader or rebind to the mana pool to get it to finish emptying out.

I did a brief google search and see that this issue has occurred before.

I know that this is an old issue and do not know if it can be fixed for the 1.7.10 mod pack.

Any advice or solutions would be appreciated

Please let me know if you need more info.  I will do what I can to provide you with data for this problem.

btw:  Regardless of the issues Botania is still an awesome mod and I have a lot of fun playing with it.

Thanks.  Anthony Kane.

**Comment by ArukaAlter** [comment]
1.7 is no longer supported.
