### ISSUE TITLE
Game Crash When Unequipping Active Baubles

### ISSUE THREAD

**Issue by InsomniaKitten** [Vazkii/Botania#1938]
The game crashes to desktop when unequipping the Ring of Aesir from the Baubles inventory. Also, I'd like to note that unequipping/re-equipping the Ring of Aesir via the Bauble Box does not cause health etc to be updated. In turn, unequipping the ring via the Bauble Box inventory then re-equipping it via the Baubles inventory also causes a crash. The ring was spawned in from JEI, in case that information is relevant to this issue.

Crash report: **[pastebin.com/yj2mG933](http://pastebin.com/yj2mG933)**

Minecraft version: **[1.10.2](https://mojang.com/2016/06/minecraft-1101/)**
Forge version: **[12.18.2.2099](http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.10.2-12.18.2.2099/forge-1.10.2-12.18.2.2099-changelog.txt)**
Mod version: **[R1.9-330](http://botaniamod.net/changelog.php)**
Baubles version: **[1.3.BETA9](https://minecraft.curseforge.com/projects/baubles/files/2335832)**

**[12 Oct 2016 22:21 GMT] EDIT:** Crash seems to occur with any 'active' bauble. Tested the mod again (same mod versions) in my dev environment, and it also caused the crash with the Tectonic Girdle. There are no crashes with bauble items such as the cosmetic baubles, which have no active effects at the time of unequipping.

New crash report: **[pastebin.com/bFkWFWX6](http://pastebin.com/bFkWFWX6)**

**Comment by Devintrainer** [comment]
I DESPERATELY need Vazkii to fix it PLEASE! Worst currently-unfixed bug EVER!

**Comment by InsomniaKitten** [comment]
Well with that attitude you're gonna get nothing in life lmao

**Comment by Devintrainer** [comment]
This is THE worst bug of all time.

**Comment by yrsegal** [comment]
That is THE biggest overstatement of all time.

**Comment by Eladkay** [comment]
oh shit

**Comment by Vazkii** [comment]
You guys need to take a fucking chill pill. Spamming caps won't magically enable my schedule to have extra time to work on mods.

**Comment by Vazkii** [comment]
This seems to happen with the Ring of Odin/Aesir and the Tectonic Girdle due to them changing attributes. Not sure why it's breaking stuff.

**Comment by Vazkii** [comment]
This is a baubles issue. I'll open a ticket there in a bit. For now, you can bypass it by placing another bauble that can go in that slot on top of it rather than just removing it.

**Comment by InsomniaKitten** [comment]
Due to the nature of your workaround, it allows the player to stack their health infinitely by crafting the Ring of Aesir, equipping it, dropping it, equipping the Ring of Odin, equipping it and restarting the whole process. Is there anything you could do to prevent this? Maybe only allow the health increase and other modifiers to be triggered once in a world by the bound player, now that they aren't "untriggering", as it were?

**Comment by Vazkii** [comment]
I'll just have to wait for azanor to fix this issue, because there's no proper way to prevent that other than just disabling the feature entirely.

**Comment by InsomniaKitten** [comment]
Azanor seems to have fixed it now from what I saw on his issues page. Maybe double check and then push a new build with your workaround reverted? I've been testing with the latest Baubles and Botania build 330 and it's been working fine so far.

**Comment by Zsashas** [comment]
> Due to the nature of your workaround, it allows the player to stack their health infinitely by crafting the Ring of Aesir, equipping it, dropping it, equipping the Ring of Odin, and then restarting the whole process. 

I thought each player could only get each relic once? You shouldn't be able to get two rings of Odin if that's the case.

**Comment by PsiGuy60** [comment]
> I thought each player could only get each relic once? You shouldn't be able to get two rings of Odin if that's the case.

It doesn't need 2 Rings of Odin to do. You re-craft the Rings into the Ring of the Aesir, equip that, get more health. Drop the Aesir ring, re-equip the Ring of Odin, get even more health.

**Comment by Zsashas** [comment]
Ah. Didn't realize you could separate them again.

**Comment by Crazy-KSK** [comment]
https://gist.github.com/37f2077f8dc07a06bc9701815c8730e4
this looks like a similar crash that occurs when unequipping the ring of loki
