### ISSUE TITLE
Botania/Bauble Issue

### ISSUE THREAD

**Issue by Gengi0927** [Vazkii/Botania#1940]
I've been having  a problem with Botania, When i attempt to load Minecraft, it tells me that Botania needs the "Baubles" mod to work, i have the latest version of the Baubles, and Botania, if anyone can help me, i'd appreciate it.

**Comment by Tsukiumy** [comment]
latest release seems a bit vague, you should post the version you are using, as the last botania update needs the beta version of baubles, somenthing like beta 9, and you probably using the latest **release** version of it.

**Comment by Gengi0927** [comment]
I have the latest Botnia release (r1.9 330), i do not know how to get the Baubles Beta mod, if you could tell me, i beleive this would fix the issue.

**Comment by Vazkii** [comment]
https://minecraft.curseforge.com/projects/baubles On the right, below Minecraft 1.10.
