### ISSUE TITLE
Infrangible Platform is not Blastproof

### ISSUE THREAD

**Issue by 666lumberjack** [Vazkii/Botania#1942]
Not sure if this is a bug or not but it seems unintended since the Infrangible Platform is supposed to be an unbreakable block for mapmakers. Tested with Creeper and TNT explosions and the blast from a Blood Magic meteor landing, all three destroyed it and dropped it as a block. 

This is in Forge 1299, Botania V330.

**Comment by Vazkii** [comment]
https://github.com/Vazkii/Botania/commit/8969fcf3a6d4cd7a6ed1baa102a19ff3c3e71ed1
