### ISSUE TITLE
Orechid isnt generating osmium from Mekanism

### ISSUE THREAD

**Issue by EvilZombieLlamma** [Vazkii/Botania#1943]
The orechid doesn't generate osmium from mekanism, iv'e tested it with an auto system and 2000 stone and didn't get any. ive noticed it works with the other 2 mekanism ores so this may be because osmium registers as mekanism:OreBlock 0 and the rest have positive meta data values

**Comment by Vazkii** [comment]
The orechid uses ore dict names for the whitelist. I'd be glad to add it if someone can get me the amount of osmium generated on average relative to the current values: https://github.com/Vazkii/Botania/blob/master/src/main/java/vazkii/botania/api/BotaniaAPI.java#L148-L190

**Comment by EvilZombieLlamma** [comment]
i think it should be somewhere around 6917 based on the amount of osmium, coal, iron, redstone and lapis generated in one chunk

**Comment by EvilZombieLlamma** [comment]
While your at it i think oreQuartzBlack should be around 5533

**Comment by Vazkii** [comment]
Is oreQuartzBlack for the nether?

**Comment by MrNinja93** [comment]
> Is oreQuartzBlack for the nether?

Actuality additions Quartz is overworld spawn.

**Comment by Vazkii** [comment]
https://github.com/Vazkii/Botania/commit/8306a38d831f1acf1d743c473defb6de978120a6
