### ISSUE TITLE
Monocle not working with new Bauble slot

### ISSUE THREAD

**Issue by iPencil** [Vazkii/Botania#1945]
The monocle stopped working with the Bauble slot rework.

I believe your hasMonocle method is only checking the old 3 slots

https://github.com/Vazkii/Botania/blob/master/src/main/java/vazkii/botania/common/item/equipment/bauble/ItemMonocle.java

`public static boolean hasMonocle(EntityPlayer player) {
		for(int i = 0; i < 4; i++) {
			ItemStack stack = BaublesApi.getBaubles(player).getStackInSlot(i);`
			

i < 4 should be 7 now with the new slots.

**Comment by Vazkii** [comment]
God dammit you post this right after I make a build. Thanks, I'll make another to fix it :v

**Comment by iPencil** [comment]
Haha sorry :P Had to check the code to make sure that it wasn't everyone using Optifine on my server that caused the overlay to be gone :D
