### ISSUE TITLE
Crash on world load with Botania r1.9-332 and compatibile versions of Baubles.

### ISSUE THREAD

**Issue by Zarepheth** [Vazkii/Botania#1946]
The latest **RELEASE** version of Botania is dependent upon **BETA** versions of Baubles.

Forge will not let me run the latest Botania without installing Baubles 1.10.2-1.3.BETA8 or above. However, both BETA8 and BETA9 of Baubles causes a crash-to-desktop when loading my world.

I've already left a bug report for Baubles. Forge does not show anything other than Baubles, Forge, Minecraft, and Java code in the stack trace, but I've attached a crash report just in case you can ferret out something useful - like which mods are conflicting...

[crash-2016-10-14_20.38.28-client.txt](https://github.com/Vazkii/Botania/files/530704/crash-2016-10-14_20.38.28-client.txt)

In the interim, I'll be reverting to the previous versions of both Botania and Baubles.

**Comment by esotericist** [comment]
Based on that crash report, the problem is not with baubles or botania, but the Baubles Stuff mod (https://minecraft.curseforge.com/projects/baubles-stuff) which is still looking for the old baubles internals.
