### ISSUE TITLE
Runic altar doesn't work

### ISSUE THREAD

**Issue by Susjin** [Vazkii/Botania#1949]
An very weird thing is happening, when i place items in it, eg. Rune of earth, the sound effect start, but when i target an mana spreader, it does not send the mana to the altar
I've tried to breake everything and replacing but still doesn't work

When i re-enter my world, if the itens are in the altar it works

**Comment by ArukaAlter** [comment]
This is missing critical information, go read https://github.com/Vazkii/Botania/blob/master/contributing.md and provide proper info.
