### ISSUE TITLE
Mana Pool and Red Stringed Comparator crash

### ISSUE THREAD

**Issue by Aseroter** [Vazkii/Botania#1950]
Pastebin: http://pastebin.com/5puSNRLS

Game crashed when removing a Mana Pool bound to a Red Stringed Comparator. Comparator was removed first and still seems to reference the spot the pool was at when I removed the pool, pointing the Comparator to an invalid block ID.

**Comment by KingDGrizzle** [comment]
It actually points to an air block.

I'm guessing there should be a check if the block is broken? This might happen with other Red String things

**Comment by Aseroter** [comment]
My thoughts as well. Would do more testing but my rig is so damn slow, takes 15 min to open vanilla + Botania on lowest settings possible.
