### ISSUE TITLE
Mana mirror

### ISSUE THREAD

**Issue by M0ult** [Vazkii/Botania#1951]
Mana mirror isnt working with armor, tables, rings, some tools and would be cool it out putting mana into a mana pools if not to game breaking

**Comment by Vazkii** [comment]
https://github.com/Vazkii/Botania/blob/master/contributing.md

**Comment by M0ult** [comment]
Cant get the report to work.

**Comment by Vazkii** [comment]
Sorry?

**Comment by M0ult** [comment]
Im not sure what your linking me to/for.
Is it working as intended?

**Comment by JRoffel** [comment]
You're loketten being linked to the contributing page because your issue is missing critical information (version numbers for botania and forge, forge (crash)logs or other information). Please make sure this information is included in your issue so we can work with it
