### ISSUE TITLE
Botana missing mods when i got Baubles-1.9.4-1.2.1.0

### ISSUE THREAD

**Issue by DaFuJosh** [Vazkii/Botania#1952]
please find the issue fast Baubles-1.9.4-1.2.1.0

has caused the game to not start

![2016-10-18_11 42 52](https://cloud.githubusercontent.com/assets/22819922/19474632/53c8f6ec-9528-11e6-89f4-f16eafb52f87.png)

**Comment by ArukaAlter** [comment]
You haven't update Baubles in quite a while, eh?
https://minecraft.curseforge.com/projects/baubles/files

**Comment by KamranMackey** [comment]
@DaFuJosh Try updating Baubles to the latest version, as you are ridiculously behind. @ArukaAlter linked above the link for you ^
