### ISSUE TITLE
Botania Mod Tweaker Issue OR Botania API issue

### ISSUE THREAD

**Issue by ElvenChaos** [Vazkii/Botania#1958]
_I was sent over here from the Mod Tweaker GitHub via https://github.com/jaredlll08/ModTweaker/issues/377_ 

When adding an Elven Trade Page to the lexica botania that has multiple inputs for one output, or several paired recipes that should cycle through in order, this occurs: https://postimg.org/image/8xqgho9pn/
The input will cycle, but the output will display all possible states given to the page.
If you want to see the scripts used, they are on the linked issue.

Also, an oredict entry can not be used as an input.

Botania ~~322~~ 332 _EDIT: whoops_
ModTweaker 2.0.4
CraftTweaker 3.0.12
Forge 2105
MC 1.10.2

**Comment by Drakma** [comment]
Adding to this, I am experiencing issues with recipes being added by ModTweaker/Craftweaker.  They are added correctly and show correctly, but don't actually work.

For all of the Apothecary recipes I add the recipe shows up in JEI, but the Apothecary will not accept those items.

In addition to this, Mana Infusion recipes show in JEI and work, but do not always consume mana.

Botania 337
ModTweaker 2.0.6
CraftTweaker 3.0.14
Force 2122
MC 1.10.2

**Comment by ElvenChaos** [comment]
Issue still prevalent in modern versions, or I don't know how to do this properly.

Botania 352
ModTweaker 4.0.6
CraftTweaker2 1.12-4.0.12
Forge 2590
MC 1.12.2
