### ISSUE TITLE
Soujourner's Sash does not prevent fall damage

### ISSUE THREAD

**Issue by TvL2386** [Vazkii/Botania#1967]
I'm having Soujourner's Sash in my bauble belt slot. Movement speed, jump height and walking over 1 block height works perfectly, but fall damage is not negated/prevented. I have a ring of mana with sufficient mana. If I jump from my roof, I loose 1 heart.

See this screenshot:
![image](https://cloud.githubusercontent.com/assets/459167/19619193/4764db1e-9861-11e6-9092-e40a1ee9ab91.png)

I'm running the pack hermitcraft 1.1.0 on minecraft 1.10.2. 
The server creator added mods:
- ImmersiveEngineering-0.10-44
- Railcraft_1.10.2-10.0.0-beta2
- Waila-1.7.0-B3_1.9.4

Kind regards,
TvL2386

**Comment by yrsegal** [comment]
Fall damage is only reduced by the sash.
