### ISSUE TITLE
Terra Shatterer doesn't absorb mana from a mana pool

### ISSUE THREAD

**Issue by TheCharles13** [Vazkii/Botania#1970]
The Terra Shatterer doesn't absorb mana from a mana pool in 1.9-333.

**Comment by Vazkii** [comment]
Can't reproduce.

**Comment by quat1024** [comment]
Try shiftrightclicking the mana pool with a Wand of the Forest. If it's in "take mana from a mana tablet" mode, it won't fill a Terra Shatterer
