### ISSUE TITLE
In-game updater doesn't work with cheats off

### ISSUE THREAD

**Issue by quat1024** [Vazkii/Botania#1971]
(I actually tested in Botania 332, because if I use the latest version I obviously won't get the choice to update :wink: )

* Open an old version of botania
* Create a world with cheats off
* Click download

![](http://i.imgur.com/eHAFg39.png)

It's because [/botania-download-latest](https://github.com/Vazkii/Botania/blob/e38556d265fcf43273c99ea1299a35400bf0c405/src/main/java/vazkii/botania/common/core/command/CommandDownloadLatest.java) is using the default permission setting which defaults to "ops only," override `getRequiredPermissionLevel()` to return 0

**Comment by Vazkii** [comment]
I don't believe there's a way to fix this, since non OPs shouldn't be able to use the command.

**Comment by williewillus** [comment]
You can make commands runnable for non-ops (see the /seed command)
