### ISSUE TITLE
"Minecart with Mana Pool" Not Compatible With RailCraft

### ISSUE THREAD

**Issue by Cobra1117** [Vazkii/Botania#1973]
The Minecart with Mana Pool is not compatible with RailCraft (for things like linking carts together into trains). @CovertJaguar mentioned (here https://github.com/CovertJaguar/Railcraft/issues/962) that the cart needs to extend EntityMinecart for it to be compatible.

Tested with:
Botania r1.9-334
Railcraft_1.10.2-10.0.0-beta-4
forge 1.10.2-12.18.2.2105

**Comment by Nincodedo** [comment]
Looks like it does? https://github.com/Vazkii/Botania/blob/master/src/main/java/vazkii/botania/common/entity/EntityPoolMinecart.java#L42

**Comment by Cobra1117** [comment]
Yeah.... I'm not really sure (I was looking at the item, not the entity... derp.) Perhaps @Vazkii  and @CovertJaguar can figure it out. I'm not well-informed on the Minecraft API, unfortunately.

**Comment by liach** [comment]
Well that is not related to vazkii at all. As I see vazkii probably should readd the compat for railcraft from railcraft api, for cart dispensers to place carts properly.

**Comment by CovertJaguar** [comment]
None of that is needed, it all optional. Not even all my carts have that stuff. It should just work. I'm highly skeptical of any reports that it does not.

**Comment by Cobra1117** [comment]
Example:
https://www.youtube.com/watch?v=jsnBFOvPbN4&feature=youtu.be
(Sorry for how dark the recording is)

**Comment by CJOak** [comment]
https://github.com/CovertJaguar/Railcraft/issues/713
https://github.com/Vazkii/Botania/issues/1465
Either of these still relevant?

**Comment by CovertJaguar** [comment]
Hmm...it actually appears that something is preventing the Crowbar from interacting with the Cart.

I image that if you used a Coupler Track it would work just fine.

**Comment by Cobra1117** [comment]
Confirmed. Coupler track works properly. Maybe there is some kind of "on click" handler that's preventing the crowbar from activating?

**Comment by liach** [comment]
event bug?

**Comment by Cobra1117** [comment]
@Vazkii this is probably still a bug, even if the cause isn't what I originally believed--something is blocking the RailCraft crowbar from interacting with the mana pool cart.

**Comment by williewillus** [comment]
The mana pool cart does not add any right click interactions, so I don't think this is caused by botania

**Comment by liach** [comment]
Does it post minecartinteractevent?

**Comment by CovertJaguar** [comment]
Yeah, the event is a new thing, its not posted in EntityMinecart but the child classes. If you minecart doesn't post it, the Crowbar won't work.

**Comment by williewillus** [comment]
Oh what, I didn't know carts had their own event instead of using the entity one
