### ISSUE TITLE
Randomly crashed to desktop; seems to be related to alf portal

### ISSUE THREAD

**Issue by kaitoyuuki** [Vazkii/Botania#1974]
https://gist.github.com/kaitoyuuki/3a1278f5d15ca8dc46b6785637a7c56c

as far as I can tell from the crash log, it seems to be related to the alf portal. However, there aren't any alf portals built nearby. closest one is several thousand blocks away.

**Comment by Vazkii** [comment]
Looks like your world was corrupted by removing some mod. Not much I can do here.

**Comment by kaitoyuuki** [comment]
I believe this is in need of some additional information. Apologies for not having all of this at the outset, but I wasn't able to obtain all of this initially. 
This is a client side crash on a multiplayer server, and has only affected one user. The events leading up to the crash, according to the user, are as follows:

"Well, I was out adventuring, I warped home and died in the soil. I dug up my grave, wandered around inside a bit. I opened my food chest and my wood chest then I started to head outside, I looked at the clock in there then I turned and clicked a doggo to follow me and then crashed"

We have not removed any mods, nor added any new ones at the time. The server has had no issues. The player has been unable to log in since then, although she only gets netty io exceptions, so we're not sure if it's related.

**Comment by gdude2002** [comment]
Just a note here, this ticket was created by users of my server (which is the server being referred to here) - There are two Alf portals on the server (that I know of); given the info above I can surmise that one actually was within chunkloading range. I'm going to check the area for myself, will report back.

**Comment by gdude2002** [comment]
Yep, that portal is still there and active. I don't get the crash myself.

**Comment by KingDGrizzle** [comment]
My opinion is to shut down the portal thats causing the crash, make the person join again, then re-activate the portal.

**Comment by gdude2002** [comment]
We haven't encountered this since the issue was created, so I haven't been able to follow up.
