### ISSUE TITLE
Can't reset Lexica Botania GUI size after changing it

### ISSUE THREAD

**Issue by Garonne** [Vazkii/Botania#1978]
I tested the newly added Lexica Botania GUI scale button, but even with the first click the GUI expanded beyond my screen size. Now that button is off screen and unable to be reached to reduce GUI size again. Sadly the GUI size doesn't seem to be stored anywhere accessible to reset it to normal size so now I'm stuck and unable to use the Lexica Botania anymore.
![2016-10-24_19 29 15](https://cloud.githubusercontent.com/assets/164475/19656419/34348c04-9a20-11e6-84ec-e2331bed2449.png)

**Comment by ArukaAlter** [comment]
It's not actually offscreen, it is on the same spot as it would be on normal scale, try clicking where it was before.

**Comment by Garonne** [comment]
Can someone make a screenshot of the GUI so I at least have a CLUE as to where to click?

**Comment by Vazkii** [comment]
What's your screen resolution?

**Comment by Garonne** [comment]
1366 x 768 px (widescreen laptop)
