### ISSUE TITLE
spreaders reseting

### ISSUE THREAD

**Issue by Efimero** [Vazkii/Botania#1982]
it seems whenever I go away from my base and come back, all the spreaders that are not facing a cardinal direction are reset to looking east and get the lenses removed, like the data was not properly saved
this only happens since I upgraded to the latest Botania, with spreaders that have been sitting there for a long time
it happens whenever the chunk gets unloaded by distance, dimension or logout, apparently

**Comment by williewillus** [comment]
are you using some alternate server software? like cauldron (if it's on 1.10) or sponge

**Comment by Efimero** [comment]
no, it's a local singleplayer world with forge and a few other mods, but nothing that changes how things are saved:
-abyssalcraft
-appleskin
-baubles
-blood magic
-botania
-chamaleon (library)
-chisel
-clipboard
-crafttweaker
-ffs
-fixchiselstonegen
-forgelin (library)
-guide-api (library)
-immersive engineering
-jei
-mcmulipart (library)
-mousetweaks
-optifine
-Pam's harvestcraft
-realtime clock
-refined storage
-roots
-shadowmc (library)
-storage drawers
-substratum

**Comment by Efimero** [comment]
I noticed mana pools also getting emptied of mana and losing the sparks, as well as the botania enchanting block losing the spark
for some reason also item frames and armor stands disappear completely sometimes

**Comment by williewillus** [comment]
if it happens to non-botania things as well then I doubt it's a botania bug, try removing any coremods and failing that normal mods until you can't reproduce it anymore

**Comment by hellpa** [comment]
might be related or not but it's seems there is probably an issue with forge chunk cache ATM https://github.com/MinecraftForge/MinecraftForge/issues/3325  you may want to take a look into it and check wether or not you have dormantchunkcache enabled and if turning it off solve your issue.

**Comment by Efimero** [comment]
makes sense, thank you! :* :* :* <3 <3 <3
