### ISSUE TITLE
not sure if right place to post this but

### ISSUE THREAD

**Issue by snacdaws** [Vazkii/Botania#1983]
Norton Just flagged the botania r1.9-335.jar as threat WS.Reputation.1, i will probably report this mistake to Norton as well but just thought i should say this here so people (mainly Devs) know about it 

this is the first time My Norton has flagged a mod jar or any jar for that matter

edited to change r1.9-355 to the proper 1.9-335

**Comment by ArukaAlter** [comment]
Any .jar files are passive of being tagged as malware to antivirus software.
Manually scanned the file, couldn't trigger the warning.

**Comment by snacdaws** [comment]
what is weird is that it only flagged botania and was fine with the file last night 

in the midst of reporting the mistake to Norton right now
anyway i mainly made this post so that both the devs and anyone with the same issue knows what is going on

**Comment by CJOak** [comment]
I really hope you mean 1.9-335, or you might actually have a problem.

**Comment by AEnterprise** [comment]
where did you download the file? if it's not the botania site or it's curse(forge) page there is  a very real possibility that it's a virus

**Comment by snacdaws** [comment]
yes, CJOak I do mean 1.9-335

the funny thing is that I didn't catch it even reading it back 4 times 

Also AEnterprise i only ever download from curse or the official page of anything i download whether it be mods or programs

**Comment by williewillus** [comment]
Compare the hash with the one on curseforge

**Comment by snacdaws** [comment]
Will do

But considering I downloaded it from the update text from within minecraft from the one I installed from curse I'd assume they will be the same

But will check Anyway when I get a chance

**Comment by snacdaws** [comment]
the md5's do indeed match so not sure why it cropped up in the first place

 someone could label this a PSA and close it if u want

i know people would freak out if they saw their antivirus flag any mod as a virus, especially if they did indeed download it from a recognised source

**Comment by AEnterprise** [comment]
@snacdaws as you created the issue you can close it yourself, button is next to 'comment'
