### ISSUE TITLE
[1.10.2- r1.9-335] Cloak of invisibility does not remove invisibility upon unequipping 

### ISSUE THREAD

**Issue by Crazy-KSK** [Vazkii/Botania#1985]
http://i.imgur.com/jyFxQzL.png 
Once unequiped the buff does start ticking down but it still gives 81 years of invisibility.

Botania r1.9-335 
Forge 1.10.2-12.18.2.2114

**Comment by Vazkii** [comment]
Can't reproduce.

**Comment by ArukaAlter** [comment]
It was an actual issue, https://github.com/Vazkii/Botania/commit/936f02ffc97293f817172c740a40202198cd390e fixed it too.
