### ISSUE TITLE
HELP!!! crashes when trying to use any sword to attack mobs, need help figuring out the cause

### ISSUE THREAD

**Issue by snacdaws** [Vazkii/Botania#1986]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ChiselCorePlugin (Chisel-MC1.10.2-0.0.7.3.jar)
  CXLibraryCore (cxlibrary-1.10.2-1.2.2.jar)
  AppleCore (AppleCore-mc1.10.2-2.0.1.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.56-beta.jar)
  BCModPlugin (zz-backpacks 1.10.2 - 3.1.3.jar)
  DLFMLCorePlugin (DynamicLights-1.10.2.jar)
  CoreMod (Aroma1997Core-1.9.4-1.1.1.0.jar)
  AppEngCore (appliedenergistics2-rv4-alpha-1.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
Contact their authors BEFORE contacting forge

// Would you like a cupcake?

Time: 28/10/16 5:14 PM
Description: Unexpected error

java.lang.IllegalAccessError: tried to access field net.minecraft.item.ItemSword.field_150934_a from class p455w0rd.ccmm.CCMM$EventsHandler
	at p455w0rd.ccmm.CCMM$EventsHandler.resetCooldown(CCMM.java:45)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_82_EventsHandler_resetCooldown_AttackEntityEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.common.ForgeHooks.onPlayerAttackTarget(ForgeHooks.java:936)
	at net.minecraft.entity.player.EntityPlayer.func_71059_n(EntityPlayer.java:1217)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78764_a(PlayerControllerMP.java:526)
	at net.minecraft.client.Minecraft.func_147116_af(Minecraft.java:1452)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2179)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1961)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1749)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at p455w0rd.ccmm.CCMM$EventsHandler.resetCooldown(CCMM.java:45)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_82_EventsHandler_resetCooldown_AttackEntityEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.common.ForgeHooks.onPlayerAttackTarget(ForgeHooks.java:936)
	at net.minecraft.entity.player.EntityPlayer.func_71059_n(EntityPlayer.java:1217)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78764_a(PlayerControllerMP.java:526)
	at net.minecraft.client.Minecraft.func_147116_af(Minecraft.java:1452)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2179)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1961)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['faze_pigman'/10347, l='MpServer', x=159.16, y=53.00, z=362.99]]
	Chunk stats: MultiplayerChunkCache: 49, 49
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-44,64,256), Chunk: (at 4,4,0 in -3,16; contains blocks -48,0,256 to -33,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 1464752 game time, 151701 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 9 total; [EntityPlayerSP['faze_pigman'/10347, l='MpServer', x=159.16, y=53.00, z=362.99], EntityBlaze['Blaze'/31330, l='MpServer', x=157.50, y=53.00, z=363.50], EntitySkeleton['Skeleton'/31331, l='MpServer', x=156.55, y=53.00, z=363.55], EntityBlaze['Blaze'/31332, l='MpServer', x=155.79, y=53.88, z=356.50], EntityPigZombie['Zombie'/31416, l='MpServer', x=169.35, y=16.00, z=364.35], EntityPigZombie['Zombie'/31417, l='MpServer', x=170.50, y=16.00, z=363.50], EntityPigZombie['Zombie'/31418, l='MpServer', x=168.50, y=16.00, z=361.50], EntityPigZombie['Zombie'/31419, l='MpServer', x=170.50, y=16.00, z=362.50], EntityPigZombie['Zombie'/31438, l='MpServer', x=174.50, y=64.00, z=359.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:400)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 349115880 bytes (332 MB) / 3105882112 bytes (2962 MB) up to 5758779392 bytes (5492 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6178m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.32 Powered by Forge 12.18.2.2114 64 mods loaded, 64 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAAAAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAAAAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.2.2114.jar) 
	UCHIJAAAAAAAAA	Forge{12.18.2.2114} [Minecraft Forge] (forge-1.10.2-12.18.2.2114.jar) 
	UCHIJAAAAAAAAA	appliedenergistics2-core{rv4-alpha-1} [Applied Energistics 2 Core] (minecraft.jar) 
	UCHIJAAAAAAAAA	Aroma1997Core{${version}} [Aroma1997Core] (Aroma1997Core-1.9.4-1.1.1.0.jar) 
	UCHIJAAAAAAAAA	backpacks16840{3.1.3} [Backpacks!] (zz-backpacks 1.10.2 - 3.1.3.jar) 
	UCHIJAAAAAAAAA	movillages{1.5.2} [Mo' Villages] ([1.9.4]Mo' Villages-1.5.2.jar) 
	UCHIJAAAAAAAAA	mantle{1.10.2-1.0.0.jenkins170} [Mantle] (Mantle-1.10.2-1.0.0.jar) 
	UCHIJAAAAAAAAA	tconstruct{1.10.2-2.5.3.jenkins387} [Tinkers' Construct] (TConstruct-1.10.2-2.5.3.jar) 
	UCHIJAAAAAAAAA	immersiveengineering{0.10-48} [Immersive Engineering] (ImmersiveEngineering-0.10-48.jar) 
	UCHIJAAAAAAAAA	JEI{3.13.0.334} [Just Enough Items] (jei_1.10.2-3.13.0.334.jar) 
	UCHIJAAAAAAAAA	AppleCore{2.0.1} [AppleCore] (AppleCore-mc1.10.2-2.0.1.jar) 
	UCHIJAAAAAAAAA	appliedenergistics2{rv4-alpha-1} [Applied Energistics 2] (appliedenergistics2-rv4-alpha-1.jar) 
	UCHIJAAAAAAAAA	Aroma1997CoreHelper{1.1.1.0} [Aroma1997Core|Helper] (Aroma1997Core-1.9.4-1.1.1.0.jar) 
	UCHIJAAAAAAAAA	Aroma1997sDimension{1.0} [Aroma1997's Dimensional World] (Aroma1997s-Dimensional-World-1.9.4-1.2.0.2.jar) 
	UCHIJAAAAAAAAA	AromaBackup{1.0.1.1} [AromaBackup] (AromaBackup-1.9.4-1.0.1.1.jar) 
	UCHIJAAAAAAAAA	AromaBackupRecovery{1.0} [AromaBackup Recovery] (AromaBackup-1.9.4-1.0.1.1.jar) 
	UCHIJAAAAAAAAA	Baubles{1.3.0} [Baubles] (Baubles-1.10.2-1.3.0.jar) 
	UCHIJAAAAAAAAA	Botania{r1.9-335} [Botania] (botania r1.9-335.jar) 
	UCHIJAAAAAAAAA	ccmm{1.1} [CombatCooldown--] (ccmm-1.10.2-1.1.jar) 
	UCHIJAAAAAAAAA	ChestTransporter{2.5.3} [Chest Transporter] (ChestTransporter-1.10.2-2.5.3.jar) 
	UCHIJAAAAAAAAA	chisel{MC1.10.2-0.0.7.3} [Chisel] (Chisel-MC1.10.2-0.0.7.3.jar) 
	UCHIJAAAAAAAAA	cxlibrary{1.2.2} [CXLibrary] (cxlibrary-1.10.2-1.2.2.jar) 
	UCHIJAAAAAAAAA	cyclicmagic{1.7.21} [Cyclic] (Cyclic-1.10.2-1.7.21.jar) 
	UCHIJAAAAAAAAA	DynamicLights{1.4.3} [Dynamic Lights] (DynamicLights-1.10.2.jar) 
	UCHIJAAAAAAAAA	DynamicLights_onFire{1.0.7} [Dynamic Lights Burning Entity Module] (DynamicLights-1.10.2.jar) 
	UCHIJAAAAAAAAA	DynamicLights_creepers{1.0.6} [Dynamic Lights Creeper Module] (DynamicLights-1.10.2.jar) 
	UCHIJAAAAAAAAA	DynamicLights_dropItems{1.1.0} [Dynamic Lights EntityItem Module] (DynamicLights-1.10.2.jar) 
	UCHIJAAAAAAAAA	DynamicLights_entityClasses{1.0.1} [Dynamic Lights Entity Light Module] (DynamicLights-1.10.2.jar) 
	UCHIJAAAAAAAAA	DynamicLights_mobEquipment{1.1.0} [Dynamic Lights Mob Equipment Light Module] (DynamicLights-1.10.2.jar) 
	UCHIJAAAAAAAAA	DynamicLights_flameArrows{1.0.1} [Dynamic Lights Fiery Arrows Light Module] (DynamicLights-1.10.2.jar) 
	UCHIJAAAAAAAAA	DynamicLights_floodLights{1.0.3} [Dynamic Lights Flood Light] (DynamicLights-1.10.2.jar) 
	UCHIJAAAAAAAAA	DynamicLights_otherPlayers{1.0.9} [Dynamic Lights OtherPlayers Light Module] (DynamicLights-1.10.2.jar) 
	UCHIJAAAAAAAAA	DynamicLights_thePlayer{1.1.3} [Dynamic Lights Player Light Module] (DynamicLights-1.10.2.jar) 
	UCHIJAAAAAAAAA	endercore{1.10.2-0.4.1.56-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.56-beta.jar) 
	UCHIJAAAAAAAAA	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
	UCHIJAAAAAAAAA	EnderIO{1.10.2-3.0.1.110_beta} [Ender IO] (EnderIO-1.10.2-3.0.1.110_beta.jar) 
	UCHIJAAAAAAAAA	excore{1.6.2} [EXCore] (Excore-1.6.2-1.10.2.jar) 
	UCHIJAAAAAAAAA	ExtraUtils2{1.0} [ExtraUtils2] (extrautils2-1.10.2-alpha-1.2.1.jar) 
	UCHIJAAAAAAAAA	zerocore{1.10.2-0.0.8.0} [Zero CORE] (zerocore-1.10.2-0.0.8.0.jar) 
	UCHIJAAAAAAAAA	bigreactors{0.4.5.18} [Extreme Reactors] (ExtremeReactors-1.10.2-0.4.5.18.jar) 
	UCHIJAAAAAAAAA	fastleafdecay{v11} [Fast Leaf Decay] (FastLeafDecay-v11.jar) 
	UCHIJAAAAAAAAA	fw{1.3.0} [Fullscreen Windowed] (FullscreenWindowed-1.10.2-1.3.0b.jar) 
	UCHIJAAAAAAAAA	grapple_hooks{1.0.8} [Grapple Hooks] (Grapple-Hooks-1.10.2-1.0.8.jar) 
	UCHIJAAAAAAAAA	HungerInPeace{1.0.0} [Hunger In Peace] (HungerInPeace-mc1.9.4-1.0.0.jar) 
	UCHIJAAAAAAAAA	inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks] (InventoryTweaks-1.61-58.jar) 
	UCHIJAAAAAAAAA	ironchest{1.10.2-7.0.11.797} [Iron Chest] (ironchest-1.10.2-7.0.11.797.jar) 
	UCHIJAAAAAAAAA	journeymap{1.10.2-5.3.0b2} [JourneyMap] (journeymap-1.10.2-5.3.0b2-unlimited.jar) 
	UCHIJAAAAAAAAA	testdummy{1.11} [MmmMmmMmmMmm] (MmmMmmMmmMmm-1.11.jar) 
	UCHIJAAAAAAAAA	craftelytra{1.1} [Craftable Elytra] (modid-1.1-1.10.2.jar) 
	UCHIJAAAAAAAAA	harvestcraft{1.9.4-1.10.2g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9.4-1.10.2g.jar) 
	UCHIJAAAAAAAAA	pixelmon{5.0.0-beta10} [Pixelmon] (Pixelmon-1.10.2-5.0.0-beta10-universal.jar) 
	UCHIJAAAAAAAAA	pixelextras{2.2.1} [Pixel Extras] (PixelExtras-1.10.2-2.2.1-universal.jar) 
	UCHIJAAAAAAAAA	simpleharvest{1.05} [Simple Harvest] (simpleharvest-1.10.2-2002-1.05.jar) 
	UCHIJAAAAAAAAA	simpleretrogen{4.0.1+8} [Simple Retrogen] (simpleretrogen-1.10-4.0.1+8.jar) 
	UCHIJAAAAAAAAA	slabcraftmod{6.03} [Slabcraft] (Slabcraftmod v6.03 - MC1.10.2 Forge.jar) 
	UCHIJAAAAAAAAA	staircraftmod{6.02} [Staircraft] (Staircraftmod v6.02 - MC1.10.2 Forge.jar) 
	UCHIJAAAAAAAAA	supercraftingframe{1.2.1.88} [Super Crafting Frame] (supercraftingframe-1.10.2-1.2.1.88.jar) 
	UCHIJAAAAAAAAA	VeinMiner{0.34.1_1.9-73be663} [Vein Miner] (VeinMiner-0.34.1-1.9r571+73be663.jar) 
	UCHIJAAAAAAAAA	VeinMinerModSupport{0.34.1_1.9-73be663} [Mod Support] (VeinMiner-0.34.1-1.9r571+73be663.jar) 
	UCHIJAAAAAAAAA	WailaHarvestability{1.1.9} [Waila Harvestability] (WailaHarvestability-mc1.10.2-1.1.9.jar) 
	UCHIJAAAAAAAAA	waterstrainer{1.3.1} [Water Strainer] (WaterStrainer-1.9.4-1.3.1.jar) 
	UCHIJAAAAAAAAA	icse{1.1.0.0} [I Can See Everything] (Wawla-1.10.2-2.3.0.206.jar) 
	UCHIJAAAAAAAAA	wawla{2.3.0.202} [What Are We Looking At] (Wawla-1.10.2-2.3.0.206.jar) 
	Loaded coremods (and transformers): 
ChiselCorePlugin (Chisel-MC1.10.2-0.0.7.3.jar)
  team.chisel.common.asm.ChiselTransformer
CXLibraryCore (cxlibrary-1.10.2-1.2.2.jar)
  cubex2.cxlibrary.CoreModTransformer
AppleCore (AppleCore-mc1.10.2-2.0.1.jar)
  squeek.applecore.asm.TransformerModuleHandler
EnderCorePlugin (EnderCore-1.10.2-0.4.1.56-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
BCModPlugin (zz-backpacks 1.10.2 - 3.1.3.jar)
  brad16840.common.asm.ClassTransformer
DLFMLCorePlugin (DynamicLights-1.10.2.jar)
  atomicstryker.dynamiclights.common.DLTransformer
CoreMod (Aroma1997Core-1.9.4-1.1.1.0.jar)
  
AppEngCore (appliedenergistics2-rv4-alpha-1.jar)
  appeng.transformer.asm.ASMIntegration
FMLPlugin (InventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 372.70' Renderer: 'GeForce GTX 750/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- WailaIntegration (Enabled/Not Forced)

	AE2 Version: alpha rv4-alpha-1 for Forge 12.18.2.2104
	EnderIO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker.):
                  * An unknown AE2 API is installed (rv4 from appliedenergistics2-rv4-alpha-1.jar).
                    Ender IO was build against API version rv2 and may or may not work with a newer version.
                 This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
	Detailed RF API diagnostics:
                  * RF API class 'EnergyStorage' is loaded from: jar:file:/D:/Curse/Instances/1.10.2%20Pixelmon/mods/ImmersiveEngineering-0.10-48.jar!/cofh/api/energy/EnergyStorage.class
                  * RF API class 'IEnergyConnection' is loaded from: jar:file:/D:/Curse/Instances/1.10.2%20Pixelmon/mods/ImmersiveEngineering-0.10-48.jar!/cofh/api/energy/IEnergyConnection.class
                  * RF API class 'IEnergyContainerItem' is loaded from: jar:file:/D:/Curse/Instances/1.10.2%20Pixelmon/mods/ImmersiveEngineering-0.10-48.jar!/cofh/api/energy/IEnergyContainerItem.class
                  * RF API class 'IEnergyHandler' is loaded from: jar:file:/D:/Curse/Instances/1.10.2%20Pixelmon/mods/ImmersiveEngineering-0.10-48.jar!/cofh/api/energy/IEnergyHandler.class
                  * RF API class 'IEnergyProvider' is loaded from: jar:file:/D:/Curse/Instances/1.10.2%20Pixelmon/mods/ImmersiveEngineering-0.10-48.jar!/cofh/api/energy/IEnergyProvider.class
                  * RF API class 'IEnergyReceiver' is loaded from: jar:file:/D:/Curse/Instances/1.10.2%20Pixelmon/mods/ImmersiveEngineering-0.10-48.jar!/cofh/api/energy/IEnergyReceiver.class
                  * RF API class 'IEnergyStorage' is loaded from: jar:file:/D:/Curse/Instances/1.10.2%20Pixelmon/mods/ImmersiveEngineering-0.10-48.jar!/cofh/api/energy/IEnergyStorage.class
                  * RF API class 'ItemEnergyContainer' is loaded from: jar:file:/D:/Curse/Instances/1.10.2%20Pixelmon/mods/ImmersiveEngineering-0.10-48.jar!/cofh/api/energy/ItemEnergyContainer.class
                  * RF API class 'TileEnergyHandler' is loaded from: jar:file:/D:/Curse/Instances/1.10.2%20Pixelmon/mods/ImmersiveEngineering-0.10-48.jar!/cofh/api/energy/TileEnergyHandler.class
                  * RF API class 'TileEnergyHandler' is loaded from: jar:file:/D:/Curse/Instances/1.10.2%20Pixelmon/mods/ImmersiveEngineering-0.10-48.jar!/cofh/api/energy/TileEnergyHandler.class

	AE2 Integration: IC2:OFF, RotaryCraft:OFF, RC:OFF, BuildCraftCore:OFF, BuildCraftTransport:OFF, BuildCraftBuilder:OFF, RF:OFF, RFItem:OFF, MFR:OFF, DSU:OFF, FZ:OFF, FMP:OFF, RB:OFF, CLApi:OFF, Waila:ON, InvTweaks:OFF, JEI:ON, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF, OpenComputers:OFF, PneumaticCraft:OFF
	Launched Version: forge-12.18.2.2114
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 750/PCIe/SSE2 GL version 4.5.0 NVIDIA 372.70, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz

**Comment by snacdaws** [comment]
nvm it happens with any sword 

need help figuring out what is causing it

**Comment by Nincodedo** [comment]
Does this happen with only Botania?

**Comment by snacdaws** [comment]
give me a min to test, will let u know

**Comment by yrsegal** [comment]
`at p455w0rd.ccmm.CCMM$EventsHandler.resetCooldown(CCMM.java:45)`

this isn't botania's fault.

**Comment by snacdaws** [comment]
yrseagal 


ahh ok will see if it still happens when i disable that mod

**Comment by snacdaws** [comment]
yes it's gone now 

it was Combat cooldown that was causing it 

it has been removed 

thanks guys

**Comment by Eladkay** [comment]
you're welcome bro

**Comment by Eladkay** [comment]
from the author: https://gyazo.com/da0c5febb4cbc81d03642b8dfc1737b6
I'm going to pull that mod..there's the Classic Combat which claims to do the same, but I have not tested as I, personally love the new combat mechanics..link to Classic Combat: https://minecraft.curseforge.com/projects/classic-combat sorry about this
