### ISSUE TITLE
Dandelifion Internal Buffer Too Small

### ISSUE THREAD

**Issue by Cobra1117** [Vazkii/Botania#1987]
This may be a case of "working as intended", but the internal buffer for the dandelifion appears to only store 50,000 mana. However, I have come up with a design that should (in theory) generate 54,000 mana per run. 

If it's true that there's a 50k cap on mana, it'd be nice if the cap were higher so that you could reach the theoretical maximum of 72,000 (8 blocks around the flower * max age of 60 * 150 mana per age).

Tested with:
Botania r1.9-334.jar
forge 1.10.2-12.18.2.2105

**Comment by VT-14** [comment]
6 blocks around the flower is the cap.  If those numbers are right, you are only loosing 4,000 mana.

To get 8, you would need all 4 sides (non-corners) to have all 3 neighbors just outside the flower's range to be living.  That condition on sides that share a corner forces the corner to have at least 4 neighbors, which won't produce a live cell.

**Comment by Cobra1117** [comment]
Hrm. Hadn't considered that you couldn't actually get up to 8 cells. Being a completionist, I'd love to be able to get that last 4k mana, but obviously that's a minor request :-)
