### ISSUE TITLE
Third Eye Issue

### ISSUE THREAD

**Issue by CJCWIS** [Vazkii/Botania#1990]
I am using Java 8, Update 111 (64-bit)
Vanilla Forge.
Botania version R1.9-335.
Forge version 12.18.2.2099 (the recommended build).
I am using OptiFine, I hope that isn't the source of this issue (I am very sorry if it is).

My friend made the Third Eye, which as you know allows you to see mobs through walls. He put it on and I could see through mobs through the wall, even though I didn't have the item. We tried it vice-versa, and it did the same thing.

Here is a screenshot of the issue:
![2016-10-28_20 56 56](https://cloud.githubusercontent.com/assets/23131218/19826560/73c6eae8-9d53-11e6-98c0-a664d9e0f901.png)

**Comment by AEnterprise** [comment]
as you have optifine and suspect it's the cause: could you temp remove optifne and see if the issue persists? then you know for sure

**Comment by Vazkii** [comment]
This is normal.
