### ISSUE TITLE
Server lag + Rod of the skies

### ISSUE THREAD

**Issue by Mii1128** [Vazkii/Botania#1994]
I was playing Singleplayer and was eploring new terrain with the planeswalkers sash, and they Rod of the Skies started to lift me not the usual like 30ish block in the air but more like 100ish. I was at like 8 ticks/sec (Worldgen) and when i returned it behaved normal again.

TL;DL: The Rod of Skies acts REALLY weird with low ticks/sec.

Being lifted in the air 100 blocks without the uncertanty of the cooldown is not nice.

**Comment by Vazkii** [comment]
Can't really do much on this one.
