### ISSUE TITLE
Manaburst Float to BlockPos conversion error

### ISSUE THREAD

**Issue by AaronOziel** [Vazkii/Botania#1995]
Error Log: http://pastebin.com/9fxtvbTx
Modpack: AllTheMods v1.39
Botania Version: 1.9 335

I placed a spreader down, then placed a mana pool on top, then placed 24 endoflames around it. I threw down 64 lava crystals (from Armor+) and when the spreader sent a mana burst I crashed. Logged back in and crashed again as soon as it sent another burst.

**Comment by KingDGrizzle** [comment]
That might be a bug with the mana pool being directly above the spreader. Can you try one block gap between spreader and pool?

**Comment by williewillus** [comment]
i think this is another mod messing with the entitythrowable datawatcher

**Comment by Vazkii** [comment]
What williewillus said.

**Comment by Saereth** [comment]
This is also happening in FTB Infinity Lite 1.10.2

Summary of the problem Client crashes from Botania Mana Bursts 

Pack Version 1.0.1

What is the bug? When a mana burst happens, everyone in the area crashes. This has happened to half a dozen people on our fresh server (less than 24 hours old.) so far all setups involve endoflames with a spreader set a few blocks from mana pools. 

Mod & Version Botania r1.9-337 

Link to log file https://gist.github.com/Saereth/c32000d72e3a817f8f98fb69d8411801 

Is it repeatable? Yes 

Known Fix? none.
 

I've reported this with the pack devs so they can examine possibly conflicting mods but also reporting here.
