### ISSUE TITLE
Spawning of squids in Garden of Glass.

### ISSUE THREAD

**Issue by curiosity-a** [Vazkii/Botania#2001]
I feel bad for bothering you with what essentially is a vanilla MC issue, but squids don't respawn in superflat worlds. And since botania-skyblock worldgen derives from flat worldgen, they don't respawn in GoG.
I apologise if you are not the person to address with this issue, though I think it is related to GoG. It would be nice if you could bypass superflat generator altogether, since the problem is in it (squids seem to respawn normally in other custom generations, like Quark's realistic worldgen).

**Comment by ArukaAlter** [comment]
Squid spawns occurs between Y 46 and 64, superflat worlds are mostly on Y=3 and doens't limits the spawn.

**Comment by curiosity-a** [comment]
@ArukaAlter 
I am well aware of that. Don't worry all was tested properly. The only thing that made them spawn was changing worldgen to a different type.
