### ISSUE TITLE
Server crash on creeper explosion, references the Goddess Charm

### ISSUE THREAD

**Issue by Febilian** [Vazkii/Botania#2002]
https://gist.github.com/Febilian/e9de3db4dd98089e8003e981e06ac108

Let me know if you need more information than the log, but it's happened several times now whenever a creeper attempts to explode on a player(neither had any baubles equipped, let alone the goddess charm). Downgrading for now, but thought you should know.

**Comment by HellishINC** [comment]
Can also confirm that explosions (ghast fireball) are causing this crash. I also have no baubles/botania items on me what so ever.

https://gist.github.com/HellishINC/202cc4775aaa3f200acb26f7afeba5c9

**Comment by gdude2002** [comment]
Can confirm, this is happening to me too. Latest Botania and Forge from this morning.

**Comment by williewillus** [comment]
oshit i didn't even notice lol
