### ISSUE TITLE
Constant Output on Console

### ISSUE THREAD

**Issue by Symsyr** [Vazkii/Botania#2008]
I don't think it is much of an issue but I keep getting:

[Server thread/INFO] [STDOUT/]: [vazkii.botania.common.block.subtile.functional.SubTileLoonuim$DropHandler:onDrops:191]: call
 outputted to the console and I am not sure why.  If someone could either let me know if it is okay or not, that would be great.

**Comment by Tamaized** [comment]
#1988

**Comment by Symsyr** [comment]
Thank you very much Tamaized, I will wait for the HermitPack to be updated.  Also, nice Yachiru avatar.  =D
