### ISSUE TITLE
Ring of Far Reach is causing target block to desync.

### ISSUE THREAD

**Issue by curiosity-a** [Vazkii/Botania#2009]
Mod list:
Baubles-1.10.2-1.3.0
Botania r1.9-337

Was tested in singleplayer. Break a block out of normal reach. It will break client-side, but when you walk into the place it occupied, place another block there or reopen the world turns out the old block is still there.

**Comment by Febilian** [comment]
I was having the same issue on a server, and I was actually wearing the ring of far reach when it kept happening. Quite possible there's a correlation.

**Comment by Ruby-Hallows** [comment]
I do not know if this has happened to others, but i have also found that the effects of the ring continued after i removed the Ring of Far Reach to the Bauble Case. the bauble case was not in my inventory when i noticed the error. I have also noticed the desync issue noted by curiosity-a. Thank you.
