### ISSUE TITLE
Client crash when looking at a item

### ISSUE THREAD

**Issue by S-Fort** [Vazkii/Botania#2010]
Botania version:  r1.9-337
Forge version: 12.18.2.2107

When searching for "log" in JEI / Creative tab
Client crashes when i enter the letter o
This does not happen when botania is not in the pack

Crash in [JEI](http://pastebin.com/aN63Lvq2) / [Creative Search](http://pastebin.com/qp5aAx3v)
This does not occur in the botania tab

**Comment by curiosity-a** [comment]
Doesn't happen to me in Forge 2099. Forge bug maybe?

**Comment by S-Fort** [comment]
Just got a new crash but with another mod. This making me suspect it might be another mod trying to access the textures of this one.. in something like a cover. So now I'm not so sure who to report to yet.
