### ISSUE TITLE
Idea: Shields

### ISSUE THREAD

**Issue by EvilCooky** [Vazkii/Botania#2015]
I'm surprised this hasn't been added already.
Maybe you're working on it, or your too busy with bugfixes to add anythign new...

It would be nice to have Manasteel and Terrasteel Shields for MC1.10
Manasteel Shields just use Mana instead of durability.
The Terrasteel Shield could have some fancy magical effects, like... AoE knockback in front of you when it's hit.

**Comment by ArukaAlter** [comment]
IIRC, this same sugestion received a "no" before.
