### ISSUE TITLE
[r1.9-337] Third Eye never stops rendering on players in multiplayer

### ISSUE THREAD

**Issue by SPMoo66** [Vazkii/Botania#2020]
If you put on a Third Eye and then take it off in multiplayer, the Third Eye rendered on the chest of the player never disappears for other clients. The person who removed it will no longer see it, but everyone else does.

**Comment by Vazkii** [comment]
I'd report this to bauble, as botania only renders what it knows is on the player, which is handled by baubles.

**Comment by SPMoo66** [comment]
Ok thanks, I'll share it with Azanor then.
