### ISSUE TITLE
Client ocassionally crashes when I go near my own mana pools

### ISSUE THREAD

**Issue by kayila** [Vazkii/Botania#2021]
It seems like occasionally when I'm working by my mana pools, it crashes my client

Crash report:
https://gist.github.com/b8f7716a813d6c1a62fcd19a2dcf4212

**Comment by Scrogs63** [comment]
Also having this same type of issue.

Multiplayer server - Infintiy Lite 1.0.1

**Comment by KingDGrizzle** [comment]
Are you using the diluted mana pool?

**Comment by KingDGrizzle** [comment]
Can't reproduce, sorry!

**Comment by kayila** [comment]
Nope, only using regular standard mana pools  It doesn't happen every time,
I havn't managed to pin down the conditions where it does happen yet.

**Comment by Aoxmodeus** [comment]
Are you using a texture pack?  I've been having a ticking entity crash of the client for days now, and I pulled my Soartex texture pack, and knock on wood, I haven't crashed in about four hours so far.

**Comment by kayila** [comment]
Nope, vanilla textures.

**Comment by Aoxmodeus** [comment]
Yeah I just CTD'd again, that wasn't it.

**Comment by Vazkii** [comment]
This happens if a tile entity is not properly removed from the world, and happens with basically anything that make use of block states AND tile entities for their data. You can use forge's "remove erroring tile entities" config option to band aid it, but I can't fix the source.

**Comment by kayila** [comment]
That might fix it on the server, but it's not crashing the server, it's
only crashing the client.  Looking at the config option:

```
    # Set this to true to remove any TileEntity that throws an error in its
update\
 method instead of closing the server and reporting a crash log. BE WARNED
THIS CO\
ULD SCREW UP EVERYTHING USE SPARINGLY WE ARE NOT RESPONSIBLE FOR DAMAGES.
    B:removeErroringTileEntities=false
```

Unless I'm mistaken, that will only happen if it has been crashing the
server.

**Comment by kayila** [comment]
That might fix it on the server, but it's not crashing the server, it's
only crashing the client.  Looking at the config option:

```
    # Set this to true to remove any TileEntity that throws an error in its
update method instead of closing the server and reporting a crash log. BE WARNED
THIS COULD SCREW UP EVERYTHING USE SPARINGLY WE ARE NOT RESPONSIBLE FOR DAMAGES.
    B:removeErroringTileEntities=false
```

Unless I'm mistaken, that will only happen if it has been crashing the
server.
