### ISSUE TITLE
Consistent repeated client crash caused by Botania flower/spreader ticking entity, affecting multiple users

### ISSUE THREAD

**Issue by Aoxmodeus** [Vazkii/Botania#2023]
Getting client crashes every 10-60 minutes on a lategame 1.10.2 Hermitpack 1.2.0 installation.  This is using version Botania r1.9-334.jar

This is on a server, but the crash only affects the client.

This started happening once I started planting large modified Forestry trees in farms in the area, but I don't think that's causal.  I will do experimenting to see if not having the trees around allows the issue to continue.

Ticking entities so far have been flowers and mana spreaders.

-- Head --
Thread: Client thread
Stacktrace:
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at net.minecraft.world.World.func_189508_F(World.java:2419)
	at net.minecraft.world.World.func_175625_s(World.java:2397)
	at vazkii.botania.common.block.BlockFloatingSpecialFlower.func_180656_a(BlockFloatingSpecialFlower.java:106)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185911_a(BlockStateContainer.java:379)
	at net.minecraft.world.World.func_175651_c(World.java:3244)
	at vazkii.botania.api.subtile.SubTileFunctional.onUpdate(SubTileFunctional.java:80)
	at vazkii.botania.common.block.subtile.functional.SubTileBellethorn.onUpdate(SubTileBellethorn.java:44)
	at vazkii.botania.common.block.tile.TileSpecialFlower.func_73660_a(TileSpecialFlower.java:100)

-- Block entity being ticked --
Details:
	Name: botania:floatingSpecialFlower // vazkii.botania.common.block.tile.TileFloatingSpecialFlower
	Block type: ID #608 (tile.floatingSpecialFlower // vazkii.botania.common.block.BlockFloatingSpecialFlower)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (86,70,-70), Chunk: (at 6,4,10 in 5,-5; contains blocks 80,0,-80 to 95,255,-65), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Actual block type: ID #608 (tile.floatingSpecialFlower // vazkii.botania.common.block.BlockFloatingSpecialFlower)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1804)

[crash-2016-11-05_21.10.59-client.txt](https://github.com/Vazkii/Botania/files/574148/crash-2016-11-05_21.10.59-client.txt)
[crash-2016-11-05_21.16.11-client.txt](https://github.com/Vazkii/Botania/files/574149/crash-2016-11-05_21.16.11-client.txt)
[crash-2016-11-05_21.38.42-client.txt](https://github.com/Vazkii/Botania/files/574150/crash-2016-11-05_21.38.42-client.txt)
[crash-2016-11-05_22.10.13-client.txt](https://github.com/Vazkii/Botania/files/574151/crash-2016-11-05_22.10.13-client.txt)
[crash-2016-11-05_22.22.21-client.txt](https://github.com/Vazkii/Botania/files/574152/crash-2016-11-05_22.22.21-client.txt)
[crash-2016-11-06_13.18.02-client.txt](https://github.com/Vazkii/Botania/files/574153/crash-2016-11-06_13.18.02-client.txt)
[crash-2016-11-06_13.39.45-client.txt](https://github.com/Vazkii/Botania/files/574154/crash-2016-11-06_13.39.45-client.txt)

**Comment by Aoxmodeus** [comment]
I was running Soartex pack "Fanver_Modded_Universal.zip", and have changed to a different texture pack.

My client has been running four a few hours now with no crashes.  This may have been the problem.  I will continue to test.

**Comment by Aoxmodeus** [comment]
Well that wasn't it...

[crash-2016-11-09_16.36.56-client.txt](https://github.com/Vazkii/Botania/files/582289/crash-2016-11-09_16.36.56-client.txt)

**Comment by KingDGrizzle** [comment]
It has 0 sense for a resource pack to crash the game due to a mod block. Are you using a Floating Flower?

**Comment by Vazkii** [comment]
The crash happens on a simple call to get the tile entity at that position. Something else is breaking your world.
