### ISSUE TITLE
Botania crashes when fighting the Gaia Guardian 2

### ISSUE THREAD

**Issue by kayila** [Vazkii/Botania#2024]
This is new, it didn't used to do this, however I also havn't updated the version of Botania.

I've already killed the second version of the guardian twice without an issue and died to her another few times besides that.

https://gist.github.com/kayila/5f17fd2eda7d09998f620345c11f749d

**Comment by yrsegal** [comment]
Something is messing with the datawatcher. This is not a botania bug, that mod shouldn't be doing that.

**Comment by kayila** [comment]
Alright, I'll take a look. Would you have any idea at what might be doing it, otherwise I'll start removing stuff  till I can figure it out.

**Comment by yrsegal** [comment]
Nope, there's no way I know of to know just from the log, doing a removal test may well be the only way.
