### ISSUE TITLE
Manasteel shovel turns dirt into path blocks

### ISSUE THREAD

**Issue by curiosity-a** [Vazkii/Botania#2025]
Normally shovels don't do that. Is this a bug or a feature?

**Comment by ArukaAlter** [comment]
The shovel used to turn dirt and grass into farmland, now it turns the grass patch into farmland instead, but the first part of the code wasn't touched.
Technically an oversight.

**Comment by Vazkii** [comment]
Shovels do that since 1.9.

**Comment by ArukaAlter** [comment]
They should do this only on grass, not on dirt like the Manasteel Shovel is doing.

**Comment by Vazkii** [comment]
I hate that they don't do it on dirt, so yes, feature.
