### ISSUE TITLE
[r1.9-337] Sparks seem to not react between pools

### ISSUE THREAD

**Issue by KingDGrizzle** [Vazkii/Botania#2026]
Testing out sparks in 1.10.2 in FTB Infinity Lite, this [setup](http://media-kingdgrizzle.tk/2016/11/Date-09---Time-09_28_36---UTC.png) doesn't seem to do anything. I've tried adding a dispersive augment, but nothing happened. Guessing Sparks aren't fully working?

**Comment by ArukaAlter** [comment]
Dispersive Augment acts between Sparks and players, you want either Dominant or Recessive for pool to pool interaction.

**Comment by KingDGrizzle** [comment]
I though that a spark without augment will split the mana between all pools

**Comment by KingDGrizzle** [comment]
Nop, I'm dumb. Haven't used sparks in ages, so I derped

Sorry!
