### ISSUE TITLE
Problem when summoning Gaia Guardian

### ISSUE THREAD

**Issue by tbell1623** [Vazkii/Botania#2030]
I cant summon gaia guardian on my ftb infinty evolved normal mode server.
Screenshots attached: 
http://prnt.sc/d66pdx 
http://prnt.sc/d66pqc

Please help!

**Comment by williewillus** [comment]
the message tells you.. your pylons are off

**Comment by tbell1623** [comment]
Thanks for the help
My lexicon doesnt seem to have a setup guide for Ritual of Gaia that I can see?
![screen shot 2016-11-13 at 11 29 47 am 2](https://cloud.githubusercontent.com/assets/23410723/20243004/9bb0a1be-a994-11e6-8286-76ba0da46ae2.png)
![screen shot 2016-11-13 at 11 29 57 am 2](https://cloud.githubusercontent.com/assets/23410723/20243005/9ea1de60-a994-11e6-82dd-752082a441ea.png)

**Comment by ArukaAlter** [comment]
Unload your resource pack, maybe it is causing the previews to not show up.

**Comment by williewillus** [comment]
is your lexicon upgraded? (alf portal)

**Comment by tbell1623** [comment]
Ahh thanks, just unloaded my resource pack and same but I never thought of upgrading my lexicon I will try that right now

**Comment by tbell1623** [comment]
Hmm just threw my lexicon in my alfien portal and I crashed, my server didnt crash though. I will see what happens when i rejoin

**Comment by tbell1623** [comment]
OK now I have a section of both rituals of gaia and I will reply (and hopefully close) later on when i get my friend on to try the ritual 
Thanks

**Comment by tbell1623** [comment]
Ok I just got the structure complete message so I will close this, thanks for all the help
