### ISSUE TITLE
Continuous crash from entity.mana burst

### ISSUE THREAD

**Issue by garlicinyoureye** [Vazkii/Botania#2031]
Playing the Infinity Lite pack, as soon as I loaded chunks around my Botania setup I experienced the following crash.  Numerous log on attempts yielded the same crash.  Using 7 gourmaryllis flowers with 7 spreaders pointed to a mana distributor.  

Crash Log: http://pastebin.com/FReqsvXQ

**Comment by yrsegal** [comment]
This is another mod, messing with the entitythrowable datawatcher. Not botania's fault.

**Comment by garlicinyoureye** [comment]
Hmm.. I'm using vanilla dispensers, maybe the RFTools timer that's emitting pulses to dispensers.  Possibly the culprit then?

**Comment by yrsegal** [comment]
There's pretty much no way to know from just the crash log, so you'd have to remove mods one by one until the error was resolved to figure it out.

**Comment by garlicinyoureye** [comment]
gotcha, problem is I can't even get close to that chunk before client crashes.

**Comment by garlicinyoureye** [comment]
Thanks for the input yrsegal

**Comment by garlicinyoureye** [comment]
The only other entity throwable datawatcher in the area would be the vanilla MC dispensers

**Comment by tjsd** [comment]
I get the exact same crash on Infinity Lite v1.02. I have no other mod even close to my botania setup. All I have is 6 endoflames with a pressure plate holding a hopper locked untill the coal goes away. All is done with vanilla redstone. As soon as I drop 1 coal on the flowers I crash with the same error.

http://pastebin.ubuntu.com/23467712/

**Comment by yrsegal** [comment]
@garlicinyoureye the DataWatcher is a special property of the entity, nothing to do with blocks.

**Comment by garlicinyoureye** [comment]
@yrsegal ah, thank you for the information.

**Comment by frank89722** [comment]
It's too easy to crash with other mods.
I found lot of mods can crash entity.manaburst.

Is that possiable from forge out of date?

**Comment by Vazkii** [comment]
This crash happens because minecraft's entity data manager can not find the right type of data there. Which means another mod is messing with it somehow. Sadly there is nothing I can do about this.
