### ISSUE TITLE
[1.10.2] Terrasteel dosent form but consumes recipe items

### ISSUE THREAD

**Issue by Morpheus1101** [Vazkii/Botania#2032]
I have the Agglomeration Plate, set to recieve more than enough mana over time, it consumes the 3 items to make the Terrasteel ingot but dosent produce the ingot itself. My setup is shown below

https://puu.sh/sgcqr/4616852f31.png

**Comment by CJOak** [comment]
That single mana spreader is not going to be able to give the plate enough mana before the items on it despawn.

**Comment by ArukaAlter** [comment]
Flip through the manual, it says to use Sparks.

**Comment by Morpheus1101** [comment]
Ok, guess i'll have to work out how to use spark then

**Comment by CJOak** [comment]
For the Terrestrial Agglomeration Plate (and the Mana Enchanter), it's as simple as putting a spark on the plate and another spark on a nearby mana pool(s).
