### ISSUE TITLE
[1.10.2] Dropping the Ring of Aesir doesn't get rid of your extra lives

### ISSUE THREAD

**Issue by milano1110** [Vazkii/Botania#2033]
When you drop the Ring of Aesir from within your baubles inventory doesn't get rid of your extra lives. Normally the Ring of Aesir give you 20 extra hitpoints or 10 extra hearts, but if you drop the Ring of Aesir your lives stay and when you put the ring back on, it gives you another 20 extra hitpoints. And you can keep repeating it, I got to a point where I had 500 hitpoints (I play with my sister on a Lan world, so that is how I knew how many hitpoints I had). I do have other mods installed and if you need a modlist you can leave a comment.

**Comment by Vazkii** [comment]
Report this to baubles please.
