### ISSUE TITLE
Terra Shatterer with Elementium Pick Upgrade glitches on Redstone Ore

### ISSUE THREAD

**Issue by bec7** [Vazkii/Botania#2034]
When you use a Terra Shatterer that was combined with an Elementium Pick to break redstone ore in area mode it doesn't work like it should. The center block is not mined at the correct mining speed and only random blocks in the area around it are broken. (tried with botania 334 and forge 2099 in HermitPack and botania 337 and forge 2125 in a clean install)

In HermitPack this bug also crashes the game both in single- and multiplayer mode. (It does not crash with only Botania installed, so the crash is probably caused by some kind of cross mod interaction)

Crashlog for singleplayer HermitPack: http://pastebin.com/zF8XCAwr

**Comment by williewillus** [comment]
3d3aee2
