### ISSUE TITLE
Iron/Diamond/Enderpearl "trades" in Elven Portal consume mana

### ISSUE THREAD

**Issue by yrsegal** [Vazkii/Botania#2035]
![image](https://cdn.discordapp.com/attachments/205306823765393408/247869110988308480/unknown.png)

These sort of trades still cost mana.

**Comment by ArukaAlter** [comment]
Well, it makes sense to cost, since it physically sends the items to another dimension, to be rejected and sent back.

**Comment by bookerthegeek** [comment]
Stupidity tax?
