### ISSUE TITLE
"Not Enough Wands" Swapping Wand Replaces Flowers/Floating Flowers With "Botania Flower"

### ISSUE THREAD

**Issue by Guswut** [Vazkii/Botania#2039]
I just accidentally replaced a few of my floating endoflame flowers with stone when I was trying to tidy up my base, and the result was that I got a few "Floating Botania Flower" instead.

I tested it on a standard endoflame and got a "Botania Flower"; a pure daisy and got a "Botania Flower"; a floating jaded amaranthus  and got a "Floating Botania Flower"; and a few mystical flowers of varying colors which worked properly, giving me the correct flower so it appears that mystical flowers are alright but the generating and functional flowers, both floating and otherwise, are not.

Below are screenshots for the two flowers I got in the case of when things didn't work out properly:

![2016-11-17 18_38_42-minecraft 1 10 2](https://cloud.githubusercontent.com/assets/3208397/20416866/4f98021c-acf6-11e6-85af-8e3dfdf6355d.png)

![2016-11-17 18_40_00-minecraft 1 10 2](https://cloud.githubusercontent.com/assets/3208397/20416869/541ca0e0-acf6-11e6-8684-26b1adbccfca.png)

I'm playing on the FTB Hermitpack with the addition of a few other mods (I can post a full mod list/full log if requested). It uses Botania r1.9-334, and I don't see anything in any of the changelogs between that version and the latest talking about the swapping wand ("swap" and "wand" ctrl-f, no results in that range).

Thanks!

**Comment by williewillus** [comment]
This is a bug with NEW, where it's not respecting nbt on getDrops()

**Comment by Guswut** [comment]
Ah, makes sense.

Do you know if it has already been reported to the NEW mod author?

I don't see it on their Github (https://github.com/romelo333/notenoughwands1.8.8/issues?q=is%3Aopen+is%3Aissue).

If you aren't sure, I'll post an issue over there and toss a link back to it here so we have a reference in case anyone else has the same issue and comes to make a report.

Thank you!

**Comment by KingDGrizzle** [comment]
I didn't see it on NEW issue tracker, so I would say report it there as well

**Comment by Guswut** [comment]
I have submitted a ticket to the NEW issue tracker (https://github.com/romelo333/notenoughwands1.8.8/issues/15) and will now close this ticket.

Thanks!
