### ISSUE TITLE
DireWolf20 1.10 Pack

### ISSUE THREAD

**Issue by Solj1n** [Vazkii/Botania#2042]
Crash in the Direwolf 20 1.10 Pack version 1.0.0 botania causes a crash.   

Description:
                                  Endo-flame...............................Endo Flame
Diluted Mana Pool -                    Mana Spreader
                                  Endo-flame............................. Endo-flame

I drop 4 coal or 4 coal coke, it crashes after a second (Most likely during mana burst)>
Crash log states ticking tile entity.

[crash-2016-11-19_01.06.44-client.txt](https://github.com/Vazkii/Botania/files/601283/crash-2016-11-19_01.06.44-client.txt)

**Comment by Vazkii** [comment]
I can't fix this. Another mod is breaking the data watcher.
