### ISSUE TITLE
Botania.cfg Request configuration settings

### ISSUE THREAD

**Issue by Xiaoyan366** [Vazkii/Botania#2043]
Request configuration settings

Close GardenOfGlass produce pebble function

The player through continuous mouse click software Quickly get a lot of pebble

Because I used exnihiloomnia
They can use it to get stone

So I want to have the configuration option to turn it off

**Comment by Nincodedo** [comment]
[As per the contributing.md on this repo.](https://github.com/Vazkii/Botania/blob/master/contributing.md)

> Suggestions are not accepted here. Post them on the forums or reddit instead. If there's any still open they're old ones before this rule was added.

**Comment by Xiaoyan366** [comment]
Can you help me publish this advice do ?? @Nincodedo

**Comment by Nincodedo** [comment]
https://www.reddit.com/r/botania/

**Comment by Xiaoyan366** [comment]
Thank you, I have released in reddit @Nincodedo
