### ISSUE TITLE
Vivid Grass / Bonemeal

### ISSUE THREAD

**Issue by Kurfursten** [Vazkii/Botania#2045]
Cannot use Bonemeal on Vivid Grass to produce tall grass

Version: r1.3-153/Regrowth Pack

**Comment by Vazkii** [comment]
What the fuck is that version?

**Comment by JRoffel** [comment]
I know modpacks don't like updating their mods, but this is bit extreme, don't you think? Also, contributing.md should be read before posting issues

**Comment by Kurfursten** [comment]
Well spotted. I thought it was suspect so I investigated the folder myself. Botania actually runs version r1.8-249.

The pack author simply forgot to update the version number.

**Comment by Vazkii** [comment]
Alas, 1.7 is not supported, though this may still be happening in 1.10.
