### ISSUE TITLE
Mana Pool Loading Crash [Again]

### ISSUE THREAD

**Issue by SuperSaiyanSolar** [Vazkii/Botania#2046]
I truly am sorry to come to you with this issue again since its first fix, as I'm sure it's a pain for everyone involved, but I felt it'd be better to tell you than to ignore it.

It's pretty much the same crash as it was the last time around, all caused by a ticking block entity when loading a chunk containing a mana pool. Whenever I leave a chunk for a while and eventually go back in, my game crashes entirely. All logs will be in the bottom of this post, and I truly hope there can be another fix.

The crash was gone in R1.9 337, but the day we updated to R1.9 339 it returned, and has only been happening ever since. This could just be coincidence, but I'm sure you'll be able to figure out more. Again, it's just a ticking entity and crash upon reloading any chunks containing a mana pool of some sort, the logs will reveal more.

Crash Log: http://pastebin.com/TUVgxQV0
FML Log:  https://www.dropbox.com/home?preview=Mana+Pool+Crash+FML+Log.gz

(The FML log is a zip file because it was too large for Pastebin, my apologies.)

**Comment by Bluexin** [comment]
Reoccurrence of #2021 (and probably many other ones)
On R1.9 340, getting this issue (which seems related) http://pastebin.com/X13TJ9xS
It's only a client crash, the server doesn't say anything, and happens without end (only fix we found this far was to tp people right after they connected).
Server is running SpongeForge 1.10.2-2221-5.1.0-BETA-2151 (so Forge 2221)
#2086 seems to be related

In #2021 @Vazkii said to enable the option to remove erroring TE's, which it is on the server. We'll try on the client as well and get back with more info.

**Comment by Bluexin** [comment]
Update:
Alright so enabling that option on the client fixed it, for whatever weird reason the description seems misleading.

**Comment by williewillus** [comment]
does the crash still happen if you disable sponge on the server temporarily?

**Comment by williewillus** [comment]
#2205
