### ISSUE TITLE
Ticking tile / block entity crashing Sponge server

### ISSUE THREAD

**Issue by iamomicron** [Vazkii/Botania#2049]
* **Sponge Version:** `spongeforge-1.10.2-2123-6.0.0-BETA-1890.jar`
* **[Crash Log](http://pastebin.com/EHhKikDH)**
* **[Crash Log 2](http://pastebin.com/eKD28gz6)**
* **[In-Game Preview](https://cdn.discordapp.com/attachments/247415707715895297/251098415167963148/2016-11-23_21.35.15.png)**

No idea why it's crashing and I'm unsure if it's a Botania issue, or Sponge. In the above instances 2 different Endoflames appears to be crashing the server. There are 3 near to each other with no difference in method of placement or block type underneath, but 2 of them have caused this crash so far.

**Comment by iamomicron** [comment]
Another very similar crash, this time from the Altar.

[Crash Log](https://cdn.discordapp.com/attachments/247415707715895297/253231618133590026/crash-2016-11-29_12.42.02-server.txt)

**Comment by williewillus** [comment]
#2205
