### ISSUE TITLE
Mana Lens not working correctly

### ISSUE THREAD

**Issue by xenongfx** [Vazkii/Botania#2050]
I am trying to use the mana lens to harvest crops. I have tried putting a bore lens on the spreader shooting it down a row of crops to break them for my hopperhawk to gather them, at the end of the row I have a mana prism with a warp lens on it, which then feeds to a force relay. Instead of going to where the force relay is bound the mana burst breaks my force relay. I have tried also changing the lens on the spreader to a warp lens with a mana prism right next to it with a bore lens on the prism. Same results.

**Comment by williewillus** [comment]
why not just bore warp on the same lens on the spreader? (or maybe it was warp bore, try both)

**Comment by xenongfx** [comment]
what do you mean "bore warp"?

**Comment by williewillus** [comment]
you can have two types of lenses together in one, just craft a bore lesns + slimeball + warp lens together

**Comment by xenongfx** [comment]
Ya tried, that, thank you btw didnt know i could craft that, but differnt result now. The mana spreader  doesnt fire at all.

**Comment by darkshadow543** [comment]
I had a similar issue, except it would warp, then break the force relay, and, once it warped, it would not enter any mana pools.

**Comment by williewillus** [comment]
I don't think this is valid for several reasons:

1. Prism replaces the lens effect, doesn't augment it
2. Can't reproduce your problem with a Bore Warp lens in 1.10
3. Warp lenses no longer transfer mana if they've warped.
