### ISSUE TITLE
Dead Bush glitch

### ISSUE THREAD

**Issue by ProxyPlayerHD** [Vazkii/Botania#2051]
Whenever a passive Flower Decays it spawns a Dead Bush, but the Bush keeps Breaking itself over and Over.
it Destroys EVERY Block that you place in and even if you mine the Block under it, if you place the Block again it will Start again.
(for some reason i can't post Imagines in the Mod's Github... so here is a Link of what it Looks like.)
https://i.gyazo.com/0f6f65d8a824a93773b6555681c52944.png

**Comment by williewillus** [comment]
are you running some custom server?

**Comment by ProxyPlayerHD** [comment]
no, it is a Server network. it is Called "FrozenSoul" and it is on the HermitPack (1.4.0).

**Comment by williewillus** [comment]
closing from staleness

**Comment by ProxyPlayerHD** [comment]
That was 2 godamn years ago.

**Comment by osirisgothra** [comment]
happening on project ozone 3 mythic which i believe is pretty new (the pack) where it generates endless sticks forever as if being broken over and over

**Comment by williewillus** [comment]
PO3 is 1.12 which has not been supported by us for years. I imagine this "glitch" is due to other mods or player claim/protection plugins misfiring. The logic in Botania itself is just a plain old "become dead bush" call.
