### ISSUE TITLE
Force Relays don't work when pushed with pistons twice in one direction

### ISSUE THREAD

**Issue by Artillect** [Vazkii/Botania#2052]
Here is my initial setup, two pistons pushing one force relay bound to the chisel factory block

![2016-11-25_09 57 26](https://cloud.githubusercontent.com/assets/8906201/20632904/c074b2c8-b2f5-11e6-905b-cf9268c492fd.png)

This is the result that I got after activating both of the pistons with the levers.

![2016-11-25_09 57 37](https://cloud.githubusercontent.com/assets/8906201/20632902/c01101ce-b2f5-11e6-8b15-51285c6d2d56.png)

This is the result I intended.
![2016-11-25_09 57 45](https://cloud.githubusercontent.com/assets/8906201/20632903/c039faac-b2f5-11e6-878d-4d8f4d48e7b2.png)

Varying the timing of the levers does not change anything.

**Comment by Artillect** [comment]
It appears that when a force relay is pushed by a block that is being pushed by a piston, the push does not register. If it is directly pushed twice by a piston, both pushes register

**Comment by Vazkii** [comment]
Welcome to the incredible world of force relays, where their very existence is a variable and the fact that they even work is a miracle.

On other words, can't fix, won't fix.
