### ISSUE TITLE
Force Relays are destroyed when pushed by a piston on a very short pulse

### ISSUE THREAD

**Issue by Artillect** [Vazkii/Botania#2053]
Here is my setup (under the grass block there is a sticky piston facing upwards to generate a very short pulse)
![2016-11-25_10 23 04](https://cloud.githubusercontent.com/assets/8906201/20633246/40d9ab00-b2f9-11e6-89ee-c67fb4aa40fe.png)

After activating the lever, the force relay is destroyed.
![2016-11-25_10 23 13](https://cloud.githubusercontent.com/assets/8906201/20633248/438b9444-b2f9-11e6-830a-8d005c52b5ba.png)

All other blocks I tested with the above setup were not destroyed.

When using a pulse former with a longer pulse, the force relay is not destroyed.

**Comment by Artillect** [comment]
When using a force relay with a pulse former from charset, the force relay does not move the block that it is connected to.

**Comment by Vazkii** [comment]
See #2052
