### ISSUE TITLE
Rafflowsia says it can eat all flowers but it only eats generating ones

### ISSUE THREAD

**Issue by quat1024** [Vazkii/Botania#2054]
![](http://i.imgur.com/Y5x08LN.png)

^ "any sort of man-made flowers"

https://github.com/Vazkii/Botania/blob/master/src/main/java/vazkii/botania/common/block/subtile/generating/SubTileRafflowsia.java#L58 

^ "instanceof SubTileGenerating"

Looks like it's time for some `M I N O R T E X T F I X E S`

**Comment by Vazkii** [comment]
r

**Comment by codewarrior0** [comment]
Maybe the mana yield should be bumped up a bit, too? Back when it could eat Dayblooms, it would produce about two-thirds as much mana as the Daybloom would produce over its lifetime. But for the Hydroangea, it gives about a tenth of its lifetime yield, and for the Endoflame just a few hundredths.

Or maybe it could be cut out entirely. Who knows?

**Comment by quat1024** [comment]
I agree, the mana amount is a bit disappointing at the moment for how challenging it is to automate. You can barely run the jaded amaranthus setup off of it last I checked.

**Comment by williewillus** [comment]
a2a0ba4
