### ISSUE TITLE
Unidentified Botania Flower on Sponge 1.10 Server

### ISSUE THREAD

**Issue by tolly7654** [Vazkii/Botania#2056]
We were playing on our sponge based HermitCraft server (v1.4.0) on 1.10 and I was setting up some botania mana gen. A creeper came along and blew up next to our pure daisies. Instead of breaking the blocks and daisies (as we have mob griefing turned off), the pure daisies turned into missing textures. I broke the flowers and got the achievement that told me to report the flower and the method that i attained it. This occurence happened in an area that was not claimed, and it was on a sponge based forge server.

Attached are the flowers and achievement:
![achievement and flowers](https://cloud.githubusercontent.com/assets/9297773/20680981/64d7c350-b599-11e6-9774-a8623e1652d7.jpg)

**Comment by williewillus** [comment]
does it happen every time and does it happen without sponge?

**Comment by cleverca22** [comment]
unable to reproduce on this end with sponge-free single player and ``/gamerule mobGriefing false``, it might be a weird glitch in a mob griefing mod?

**Comment by tolly7654** [comment]
Tested this in a private server with no sponge, no issue found. Tested it in SSP, no issue found. Tried it in sponge, issue found. I also tested it with the psi gun in SSP and non-sponge server with the Explode trick and an issue was found on all 3.

**Comment by tolly7654** [comment]
Also sorry it took me this long to reply, I had to deal with something earlier last night (uk time)

**Comment by williewillus** [comment]
Is it a specific sponge plugin or just sponge in general?

**Comment by tolly7654** [comment]
We have griefprevention on our sponge server

**Comment by williewillus** [comment]
if you remove it does this still happen?

**Comment by tolly7654** [comment]
With our setup, we have not had a proper chance to do so at this time. It is something we will try in the near future, but as of this moment, our server guy is having a hard time keeping up with some other problems.

**Comment by tolly7654** [comment]
I have managed to test this in a private server, but without any other plugins, just sponge and forge. I hope this helps
