### ISSUE TITLE
Game crashes on startup.

### ISSUE THREAD

**Issue by DrMeepster** [Vazkii/Botania#2057]
It just crashes, even with just Baubles and Botania installed. Also It stopped working after I quit the game and turned it back on. I am using Curse so maybe it auto updated
Forge 12.18.2.2166
Botania 1.9-339
[crash-2016-11-28_20.47.32-client.txt](https://github.com/Vazkii/Botania/files/618128/crash-2016-11-28_20.47.32-client.txt)

**Comment by williewillus** [comment]
closing from staleness and irreproducability
