### ISSUE TITLE
Crash with storage drawers and hopper hock

### ISSUE THREAD

**Issue by ProsperCraft** [Vazkii/Botania#2058]
Server crash- https://gist.github.com/ProsperCraft/a9be64733f9b2b1fbcc02d4915c6ea15

Reproduced in single player - http://pastebin.com/D2PdxeYQ

Players description of what he did "place a hopperhock and drop items next to it then place a Storage Drawers controller slave on top of it.

**Comment by jaquadro** [comment]
The stack trace is potentially misleading, since line 80 itself shouldn't produce an NPE due to the check above it.  It might be coming from execution of enumerator though.  Looks like this could happen if I get passed a null stack.  If that's the case, it probably warrants a fix on both sides.
