### ISSUE TITLE
latest 1.10.2 Botania (Direwolf20 1.10.2 modpack)

### ISSUE THREAD

**Issue by snacdaws** [Vazkii/Botania#2061]
Terrasteel fails to craft

**Comment by ArukaAlter** [comment]
Pictures of the setup and actual versions numbers.

**Comment by snacdaws** [comment]
![2016-12-03_12 14 22](https://cloud.githubusercontent.com/assets/3342589/20860951/1d3990ac-b952-11e6-9e74-170395653c0d.png)
Botania r1.9-339 

it uses the mana but terrasteel doesn't appear like it should

**Comment by Tamaized** [comment]
Use sparks

**Comment by snacdaws** [comment]
ok will try that

if that is why then i will close

**Comment by snacdaws** [comment]
wow that worked, i thought that u could use the mana spreaders on the Agglomeration Plate in 1.7.10 then use sparks later, 

TIL

**Comment by quat1024** [comment]
You can use mana spreaders, it's just really slow. If you use only one spreader it takes so long that the items despawn before it even finishes
