### ISSUE TITLE
Can't spawn Gaia bosses.

### ISSUE THREAD

**Issue by Creeper246** [Vazkii/Botania#2065]
Hello!
I am playing on Direwolf20 1.10.2 (version 1.1.3) server. Version of Botania is 1.9-339. When I try to shift-right click on beacon with terrasteel or gaia spirit ingot, the hand moves, but the boss won't spawn. If I ask my friend to spawn it, it works.
![2016-12-09_09 47 07](https://cloud.githubusercontent.com/assets/24472636/21042975/f0ab8a2a-bdf4-11e6-82f3-fec4700b6fb1.png)

**Comment by Thinjon100** [comment]
I just had this same issue.... do you by chance have an Iron backpack equipped (mine is bound to the 'V' key) ... when I un-equipped mine, the ritual started working again

**Comment by Creeper246** [comment]
Hmm,.. that might be it :) Can't check right now, cuz im not home atm.
