### ISSUE TITLE
Dandilifeon question

### ISSUE THREAD

**Issue by deathsiroj** [Vazkii/Botania#2066]
Hi,

I was wondering when an Cellular Block gets absorbed by the dandilifeon and mana gets created, all the other blocks do they also generate mana or is it just the blocks that hit the 3x3 in the middle.

**Comment by ArukaAlter** [comment]
Read the book.

**Comment by deathsiroj** [comment]
it only says they die but when they die does it generate blocks

**Comment by VT-14** [comment]
When I last read it, the book made it clear that only the center 3x3 generated mana.

**Comment by Elvarion** [comment]
Page 7/11 about the Dandelifeon
"The 3x3 Zone centered around the Dandelifeon itself is not habitable by cells. Any live cells that would exist in that area are turned into Mana instead.
