### ISSUE TITLE
Refined Storage Interaction

### ISSUE THREAD

**Issue by Nomn-Nomn** [Vazkii/Botania#2067]
While playing on the Direwolf20 modpack, I found a bug that occurs when trying to place hydroangeas using refined storage's constructor. The constructor was placed above the desired location for the flower. When the constructor tried to place a hydroangea, an invalid flower was placed instead.

**Comment by Tamaized** [comment]
#2063

**Comment by Nomn-Nomn** [comment]
Thanks Tamaized
