### ISSUE TITLE
Mana Production Crashing Client But Not Server

### ISSUE THREAD

**Issue by AlexCassin** [Vazkii/Botania#2068]
Im using Direwolf20 1.10.2 version 1.1.3 modpack FYI.

I've tried using Endoflame's and Hydroangeas and both have crashed my client immediately just before it's due to send a mana burst. When I return to the server after the mana production has finished I can log back in fine. It's fine on a single player world. I've also tried production on different dimensions both in the overworld and on a dimension made using RFTools. 

I've also tried with and without optifine as well. 

Crash report: http://pastebin.com/Es1tDiYx

**Comment by Vazkii** [comment]
This is a data watcher bug. I can't fix it.
