### ISSUE TITLE
Curse Effect from Gaia arena?

### ISSUE THREAD

**Issue by DigitalSketch** [Vazkii/Botania#2069]
I can't find anything that would indicate that the Gaia "Arena" would give us a curse effect, but it is.  Is this normal functionality?

**Comment by ArukaAlter** [comment]
This is missing critical information, version numbers, other mods present in the environment, conditions to reproduce.

**Comment by DigitalSketch** [comment]
The version of Botania is r1.9-339, and it's within the HermitPack mod pack 1.5.1, so there are many mods installed.  I've been searching all over the internet to see what causes the cursed effect but haven't found anything.  I setup a new area (the old one we had was giving you curse instantly) and for the first few gaia fights, it wasn't there, then it started again. It happens before summoning the Gaia.  Hope that helps.

**Comment by DigitalSketch** [comment]
One of the patreons on the server says that blood magic has a curse effect with it.  This is installed with the hermit pack, if that helps.
