### ISSUE TITLE
1.10 Gaia 2 Client Crash

### ISSUE THREAD

**Issue by mkaiser84** [Vazkii/Botania#2070]
I spawned the Gaia 2, went to drink a resistance potion from the flask and the client crashed. When logging back in I crash before everything finishes loading, but the server doesn't.

Things to know that may help:

Mod Pack: Direwolf20 1.10 version 1.1.3

I have 3 separate full beacons in the area (resist 2, strength 2, regen)

FML Log: http://mikekaiser.net/MC/fml-client-3.log

Crash Log: http://mikekaiser.net/MC/crash-2016-12-13_11.02.49-client.txt

**Comment by mkaiser84** [comment]
It's fixed in the 1.2 version of the pack.

**Comment by dagit** [comment]
I think it's back. I'm using the 1.2.1 version of the pack and the Gaia 2 fight causes a client crash about 5 seconds into the fight.
