### ISSUE TITLE
Bore Warp Lens Bugs

### ISSUE THREAD

**Issue by darkshadow543** [Vazkii/Botania#2072]
I was attempting to make an auto tree farm that would eventually turn everything into mana, however, when I used the force relay with a bore-warp lens, it broke the force relay.  That I am pretty sure is a bug.  Perhaps it is caused by me running it through a mana detector first, that was to shut down the hopper hocks that picked up the items.  Also, when the leftover mana in the mana burst hit the mana pool, it dissipated as opposed to being absorbed.  Later testing revealed that this only occurs after it warps, once the force relay is broken, it will enter any mana pool along its path.

**Comment by CJOak** [comment]
Botania v334 changelog: "Mana Bursts that have been teleported by a Warp Lens can no longer deliver mana to receiving blocks."

For your first issue, if we assume the change didn't break anything, make sure that the Bore lens (green) is the lens that is showing, not the Warp lens.

**Comment by darkshadow543** [comment]
Oh, I did not know there was a specific order to the lenses
