### ISSUE TITLE
Bug with Gaia Guard and strength potion.

### ISSUE THREAD

**Issue by CBKirito** [Vazkii/Botania#2073]
1.- Drink a Flask of Overload. 
![2016-12-15_14 23 08](https://cloud.githubusercontent.com/assets/24586655/21222442/ec819e20-c2d2-11e6-9db8-9b8df391a3c5.png)

2.- Called Gaia Guard.
3.- Kill Gaia Guard.
4.- You have Eternal effect of strenght 4!
![2016-12-15_14 27 38](https://cloud.githubusercontent.com/assets/24586655/21222463/ff66f7ba-c2d2-11e6-8c5f-27ef6acf1fae.png)
![2016-12-15_14 29 04](https://cloud.githubusercontent.com/assets/24586655/21222467/07be7d7a-c2d3-11e6-905f-e26b1cc0f3c6.png)

Please, fix this bug.

**Comment by TheWhiteWolves** [comment]
Versions?
Other mods?

[contributing.md](https://github.com/Vazkii/Botania/blob/master/contributing.md)

**Comment by CBKirito** [comment]
1.7.10.
![mods](https://cloud.githubusercontent.com/assets/24586655/21232672/805916da-c2fd-11e6-8883-52671b4dc5f5.jpg)
This is minecraft project. (Magic Server)

**Comment by Tamaized** [comment]
1.7.10 isn't supported

**Comment by CBKirito** [comment]
At 1.10 he is also present.

**Comment by Tamaized** [comment]
This bug exists in 1.10 with no other mods?

**Comment by CBKirito** [comment]
Oh course.

**Comment by williewillus** [comment]
cannot reproduce
