### ISSUE TITLE
Baubles version?

### ISSUE THREAD

**Issue by robertmaxton42** [Vazkii/Botania#2075]
Yes, I know, it's been mentioned a thousand times. I did check the FAQ, the Curse dependencies, and all previous issues, but I can't seem to find a mention for which version of Baubles is matched with the current version of Botania - everything I found is a month or three out of date. Is there any way you could mention that somewhere?

**Comment by MightyCupcakes** [comment]
Just get the latest Baubles version for your minecraft version. It should work unless there are API changes on baubles side.

**Comment by robertmaxton42** [comment]
Tried that, got the usual error. Both 1.3.8 and 1.3.BETA11, on the off chance the older beta worked.

**Comment by Nincodedo** [comment]
The code says required-after:Baubles@[1.3.BETA8,]. Does 1.3.BETA8 work?

**Comment by Tamaized** [comment]
just use Baubles-1.10.2-1.3.6

**Comment by williewillus** [comment]
The dpeendency string probably should be updated
