### ISSUE TITLE
Crash with other book mods

### ISSUE THREAD

**Issue by DrMeepster** [Vazkii/Botania#2077]
Botania crashes when installed with Tinker's Construct.
[Crash Log](https://gist.github.com/DrMeepster/8b0c1f471b50895c03441afeee1870d3)

**Comment by DrMeepster** [comment]
Weird. It crashes with Immersive Engineering too. All three of these mods have books.
[Crash Log](https://gist.github.com/DrMeepster/3d08521f192247d47c49483df7abaf64)

**Comment by DrMeepster** [comment]
It's clear to me that Botania hates other mods that have books in them. 
[HQM Crash Log](https://gist.github.com/DrMeepster/6f02e3803eee0925decbf99f0385aee0)

**Comment by ArukaAlter** [comment]
Can't reproduce any of the three cases, re-download Botania and update Forge.

**Comment by DrMeepster** [comment]
Anything remotely book-like crashes Botania. Wow
[Psi Crash Log ](https://gist.github.com/DrMeepster/f140ca520ff76d0a651a14ccad038840)

**Comment by DrMeepster** [comment]
You are right. I have no idea why my first times didn't work.
