### ISSUE TITLE
[Bug] floating special flower entity tick with rannuncarpus

### ISSUE THREAD

**Issue by MvanRietschoten** [Vazkii/Botania#2079]
Hello,

This is the crash report i'm getting on my direwolf20 1.1.4 server: http://pastebin.com/5RBPnESj

I could not find any related issues in open or closed.

Someone on my server build an awesome build.
It started for the first time when a HourGlass began ticking.
The rannuncarpus tries to plant a normal oak sappling.
It could not plant it, because of the block it that he is placing on is removed by a sticky piston... good story right?

**Comment by williewillus** [comment]
#2182
