### ISSUE TITLE
Recipes that accept any color flowers/petals use up 8 pages in JEI

### ISSUE THREAD

**Issue by randomdude999** [Vazkii/Botania#2082]
This includes crafting recipes for:
* Shard of Laputa
* Mana Spreader
* Elven Mana Spreader
* Petal Apothecary
* Sparks
* Wand of the Forest (except it has 128 pages)

This could probably be fixed by having all the flowers/petals have a shared ore dictionary name, like botaniaMysticalFlower and botaniaMysticalPetal.

Looking up how to use the ore dictionary, I could probably do this myself, but tell me if you like it.

**Comment by Vazkii** [comment]
This has to do with the old lexicon code iterating through lists rather than properly assuming variants.
