### ISSUE TITLE
dreadthorne killing animals outside of it's "area of effect"

### ISSUE THREAD

**Issue by jdratlif** [Vazkii/Botania#2083]
I placed some adult cows on a slab atop a dreadthorne. There is water in the block space so they continually try to jump out of the water. (I'm stealing, er using, this build https://www.youtube.com/watch?v=Zv7dPbSOHh0)

If you look at the dreadthorne with the manaseer monocle, it shows that the area of effect is only on the same y-level as the flower, but it kills animals a full two blocks above this area.

MC 1.10.2
Forge 2185
Botania 1.9-339

**Comment by williewillus** [comment]
the monocle only shows a 2D preview of the AOE

**Comment by jdratlif** [comment]
Oh, I didn't realize that about the monocle.

Did the AOE change? I didn't see anything in the changelog related to dreadthornes, and it appeared to work in that video, but in my world, the second an adult cow gets placed on that block, it dies.

**Comment by MightyCupcakes** [comment]
From the code it looks like its +/- 6 blocks in the x, y and z direction
