### ISSUE TITLE
Hopperhock Is Faster Than Rannuncarpus Even When Slowed

### ISSUE THREAD

**Issue by natedogith1** [Vazkii/Botania#2084]
When a Hopperhock on Podzol and a Rannuncarpus on dirt compete to pick up the same item, the Hopperhock tends to win, even though it's slowed down.  If the Hopperhock is on Mycellium, the Rannuncarpus will win like it's supposed to.  I expect the issue is caused by the Rannuncarpus only running every 10th tick (https://github.com/Vazkii/Botania/blob/master/src/main/java/vazkii/botania/common/block/subtile/functional/SubTileRannuncarpus.java#L69)

**Comment by ElectronicRU** [comment]
Ran into this as well. With Mycelium, Rannuncarpus tends to win, but still not 100% of the time.
