### ISSUE TITLE
Tangleberrie does not affect Enderman

### ISSUE THREAD

**Issue by 7OOTnegaTerces** [Vazkii/Botania#2085]
I tried setting up an enderman farm with an EnderIO powered spawner, a Tangleberrie, a Bellethorne, and a Vinculotus. However, while the Bellethorne and Vinculotus work as advertised, the Tangleberry doesn't do jack for keeping the endermen inside the trap.  Having used the manaseer monocle it is clear that the Tangleberrie plant does not work on enderman which, baring clarification to it's entry in the Lexica, it should.

**Comment by TheWhiteWolves** [comment]
are the endermen teleporting out or are they walking away?

**Comment by 7OOTnegaTerces** [comment]
Walking away (the Vinculotusr is working just fine for yanking them back whenever they try to teleport away).

**Comment by TheWhiteWolves** [comment]
any chance u could get a small video or gif of it, particularly looking at the endermen, need to see if the sparkle effect is happening

**Comment by 7OOTnegaTerces** [comment]
Sorry it took me so long to reply, I've been sick!  I just tried to recreate the setup I'd been using in a blank test world and the Enderman are now reacting to the Tangleberrie as if it's a Bellethorne.  At first I wondered if it had always been like this and I just hadn't been able to tell since I'd always had the Bellethorne active.  But then I remembered noticing that the Bellethorne could only affect one mob at a time whereas now all the Enderman within the Tangleberrie's area of affect were being harmed.  Thus something had definitely changed.  So then I went back to my original world and recreated the old setup (when I'd planned on fencing the Enderman in with the Tangleberrie.  This did work as expected (no Enderman were harmed by the Tangleberrie), or at least, exactly as I expect it to not work.  The Enderman seem to almost notice the Tangleberries boundary, but they are able to cross it with only a slight pause, as my accompanying GIF shows.  And no, I never noticed any sparkle effect.

On a side note, it would be REALLY helpful for special plants like the Tangleberrie and Jiyuulia if there was some sort of particle effect always active that showed the player exactly where the boundary of their effect is.  The monocle is great and all, but it only shows that boundary if you're staring at the plant, and from relatively closely. Not only does this mean that you can only view the boundary opposite to your position, and from some distance away, but it means that you actually have to come within the plant's area of effect, which puts you INSIDE the lion's cage in the case of the Tangleberrie, in order to inspect it's bars.  That's really NOT useful, AT ALL.  Even in creative mode, it was still difficult to keep the Enderman and the Tangleberrie in my sight for the GIF I made so it was clear exactly when they walked over it's boundary.  On the other hand, with some sort of boundary particle effect, a player could confidently walk just inside (or outside) that boundary without ever worrying about crossing it and getting eaten.


![enderman and tangleberrie a](https://cloud.githubusercontent.com/assets/9096722/21572096/6c079bf0-ce8a-11e6-8e03-93f2dd4bf19c.gif)
![enderman and tangleberrie b](https://cloud.githubusercontent.com/assets/9096722/21572095/6c001d12-ce8a-11e6-93be-82e86c48098d.gif)

**Comment by TheWhiteWolves** [comment]
if there's no sparkle effects then the tangleberrie is probably not affecting them, I'd load up MC and check myself but my system is unable to load it without crashing straight away anymore. 😛

**Comment by CJOak** [comment]
In case you didn't know, if you bind your Wand of the Forest to a flower while wearing the monocle, you can see the range without looking directly at the flower.

**Comment by williewillus** [comment]
cannot reproduce, it keeps endermen in fine in my test world

**Comment by williewillus** [comment]
it seems like whatever the flower applies isn't "strong enough" to keep it in
