### ISSUE TITLE
mana burst from Mana spreader crash client

### ISSUE THREAD

**Issue by Guhigh** [Vazkii/Botania#2087]
playing on direwolf 20 mod pack pack for 1.10  with botania r1.9-339

a mana pulse from a mana spreader crash the client on a multiplayer server (but not the server)
testing with a pulse mana spreader resulted in the same issue
    pointing to a diluted mana pool = client crash with mana pulse
            some mana in the pool after log back in the pool
    pointing to a mana pool =  client crash time with mana pulse
            some mana in the pool after log back in the pool
    pointing to nowhere = client crash on mana pulse

reduced particle visual from all to minimal
  same issue on all case

Server owner gave an elven mana spreader for additionnal test
  mana pulse work normaly with elven mana spreader in all situation

**Comment by Tamaized** [comment]
logs..?

**Comment by atakle** [comment]
Got the same issue. This one was caused by swinging the Terra Blade.

https://gist.github.com/atakle/d44de30f3e5653ff3f05e7b188061be1

**Comment by FiveEYZ** [comment]
here is a crash-report from one of my players

http://pastebin.com/4nfrM5KM

**Comment by BinaryCrafter** [comment]
Also seeing this problem, exception details identical to the two examples posted above. It's a client only crash on mana burst from endflame via mana spreader to mana pool. Server unaffected. FTB Forum post [here](https://forum.feed-the-beast.com/threads/client-crashes-from-botania-mana-bursts.193455/).

**Comment by TheWhiteWolves** [comment]
that looks to be a vanilla function throwing the mis-cast, from what I can see its being thrown when the datamanager tries to get the block position of the shooter during the a ping but for some reason its giving back a float instead of the BlockPos it was asked for.
