### ISSUE TITLE
Crash when opening the botania tab of the creative inventory

### ISSUE THREAD

**Issue by jaz3001** [Vazkii/Botania#2088]
---- Minecraft Crash Report ----
// I just don't know what went wrong :(

Time: 27-12-16 16:20
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
	at net.minecraft.item.ItemStack.func_82833_r(ItemStack.java:507)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:569)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.updateFilteredItems(GuiContainerCreative.java:367)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_147053_i(GuiContainerCreative.java:334)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_147050_b(GuiContainerCreative.java:523)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146286_b(GuiContainerCreative.java:427)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:558)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146274_d(GuiContainerCreative.java:539)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:517)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1700)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.item.ItemStack.func_82833_r(ItemStack.java:507)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:569)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.updateFilteredItems(GuiContainerCreative.java:367)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_147053_i(GuiContainerCreative.java:334)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_147050_b(GuiContainerCreative.java:523)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146286_b(GuiContainerCreative.java:427)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:558)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146274_d(GuiContainerCreative.java:539)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:517)

-- Affected screen --
Details:
	Screen name: net.minecraft.client.gui.inventory.GuiContainerCreative

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['reinavonhartz'/1875, l='MpServer', x=268,50, y=64,00, z=203,50]]
	Chunk stats: MultiplayerChunkCache: 440, 440
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (275,64,210), Chunk: (at 3,4,2 in 17,13; contains blocks 272,0,208 to 287,255,223), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 24750 game time, 24750 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 72 total; [EntityPlayerSP['reinavonhartz'/1875, l='MpServer', x=268,50, y=64,00, z=203,50], EntityCreeper['Creeper'/514, l='MpServer', x=345,40, y=42,00, z=277,83], EntityCreeper['Creeper'/515, l='MpServer', x=344,50, y=42,00, z=277,50], EntityCreeper['Creeper'/516, l='MpServer', x=341,61, y=42,00, z=272,93], EntityZombie['Zombie'/517, l='MpServer', x=344,50, y=42,00, z=276,50], EntityCreeper['Creeper'/648, l='MpServer', x=301,50, y=20,00, z=264,50], EntityZombie['Zombie'/649, l='MpServer', x=308,50, y=20,00, z=260,50], EntityCreeper['Creeper'/650, l='MpServer', x=301,50, y=20,00, z=264,50], EntityZombie['Zombie'/1420, l='MpServer', x=323,22, y=13,00, z=269,70], EntitySquid['Squid'/141, l='MpServer', x=218,88, y=56,62, z=190,50], EntitySquid['Squid'/142, l='MpServer', x=215,35, y=56,33, z=190,41], EntitySkeleton['Skeleton'/1166, l='MpServer', x=296,50, y=22,00, z=250,50], EntitySquid['Squid'/143, l='MpServer', x=216,74, y=58,88, z=186,78], EntitySquid['Squid'/144, l='MpServer', x=214,63, y=61,18, z=186,96], EntityZombie['Zombie'/1168, l='MpServer', x=325,50, y=13,00, z=276,50], EntityBat['Bat'/530, l='MpServer', x=301,25, y=20,10, z=255,60], EntitySkeleton['Skeleton'/1426, l='MpServer', x=337,50, y=18,00, z=221,50], EntityBat['Bat'/533, l='MpServer', x=306,85, y=20,64, z=262,44], EntityBat['Bat'/1941, l='MpServer', x=321,81, y=33,89, z=266,61], EntityBat['Bat'/534, l='MpServer', x=299,44, y=20,26, z=259,41], EntityCreeper['Creeper'/1047, l='MpServer', x=337,50, y=14,00, z=275,50], EntityVillager['Villager'/24, l='MpServer', x=246,50, y=76,00, z=283,34], EntityZombie['Zombie'/1048, l='MpServer', x=331,50, y=14,00, z=279,50], EntityBat['Bat'/1944, l='MpServer', x=325,76, y=32,02, z=268,12], EntityBat['Bat'/1945, l='MpServer', x=329,46, y=32,94, z=267,75], EntityBat['Bat'/1946, l='MpServer', x=317,32, y=33,90, z=266,23], EntityBat['Bat'/410, l='MpServer', x=343,56, y=16,51, z=210,46], EntityVillager['Villager'/27, l='MpServer', x=251,50, y=74,00, z=282,50], EntityZombie['Zombie'/1179, l='MpServer', x=319,50, y=15,00, z=266,50], EntityChicken['Chicken'/28, l='MpServer', x=254,33, y=72,00, z=278,52], EntitySheep['Sheep'/30, l='MpServer', x=285,18, y=67,00, z=204,84], EntitySheep['Sheep'/31, l='MpServer', x=274,50, y=68,93, z=223,60], EntitySheep['Sheep'/32, l='MpServer', x=253,08, y=63,00, z=203,49], EntitySheep['Sheep'/33, l='MpServer', x=268,18, y=65,00, z=222,50], EntityChicken['Chicken'/34, l='MpServer', x=259,50, y=70,00, z=278,50], EntityChicken['Chicken'/35, l='MpServer', x=262,11, y=70,00, z=280,55], EntityCreeper['Creeper'/932, l='MpServer', x=256,50, y=47,00, z=186,50], EntityChicken['Chicken'/36, l='MpServer', x=266,31, y=69,00, z=277,52], EntityCreeper['Creeper'/425, l='MpServer', x=347,50, y=16,00, z=205,50], EntitySquid['Squid'/172, l='MpServer', x=220,70, y=55,43, z=191,46], EntitySquid['Squid'/173, l='MpServer', x=212,63, y=56,13, z=193,09], EntityZombie['Zombie'/1453, l='MpServer', x=314,50, y=16,00, z=245,50], EntitySquid['Squid'/174, l='MpServer', x=213,04, y=56,55, z=192,27], EntitySquid['Squid'/175, l='MpServer', x=212,31, y=55,75, z=186,52], EntityZombie['Zombie'/306, l='MpServer', x=324,05, y=13,00, z=268,87], EntitySheep['Sheep'/52, l='MpServer', x=289,50, y=71,00, z=231,50], EntitySheep['Sheep'/53, l='MpServer', x=293,50, y=71,00, z=230,50], EntitySheep['Sheep'/54, l='MpServer', x=291,50, y=71,00, z=230,50], EntitySkeleton['Skeleton'/1206, l='MpServer', x=299,50, y=23,00, z=251,50], EntitySheep['Sheep'/55, l='MpServer', x=302,23, y=73,00, z=238,49], EntitySkeleton['Skeleton'/697, l='MpServer', x=299,50, y=21,00, z=256,50], EntityZombie['Zombie'/699, l='MpServer', x=297,50, y=21,00, z=252,50], EntitySkeleton['Skeleton'/700, l='MpServer', x=297,50, y=21,00, z=252,50], EntitySheep['Sheep'/65, l='MpServer', x=339,50, y=63,00, z=248,22], EntitySheep['Sheep'/66, l='MpServer', x=339,41, y=63,00, z=247,14], EntitySheep['Sheep'/67, l='MpServer', x=340,04, y=63,00, z=245,36], EntitySheep['Sheep'/68, l='MpServer', x=340,61, y=63,00, z=262,21], EntityBat['Bat'/1994, l='MpServer', x=339,78, y=18,92, z=220,44], EntityBat['Bat'/331, l='MpServer', x=340,67, y=11,47, z=266,51], EntitySkeleton['Skeleton'/716, l='MpServer', x=323,50, y=25,00, z=224,50], EntitySkeleton['Skeleton'/1872, l='MpServer', x=301,50, y=19,00, z=256,50], EntitySkeleton['Skeleton'/720, l='MpServer', x=327,50, y=26,00, z=225,50], EntityZombie['Zombie'/1873, l='MpServer', x=301,50, y=19,00, z=261,50], EntityZombie['Zombie'/1874, l='MpServer', x=301,50, y=19,00, z=262,50], EntityCreeper['Creeper'/1106, l='MpServer', x=334,50, y=33,00, z=216,50], EntityZombie['Zombie'/595, l='MpServer', x=334,51, y=47,00, z=274,20], EntityZombie['Zombie'/2006, l='MpServer', x=319,50, y=54,00, z=150,50], EntityCreeper['Creeper'/352, l='MpServer', x=325,50, y=26,00, z=225,50], EntityBat['Bat'/1638, l='MpServer', x=317,25, y=14,10, z=129,75], EntitySpider['Spider'/1133, l='MpServer', x=309,50, y=20,00, z=263,50], EntityCreeper['Creeper'/1775, l='MpServer', x=337,50, y=43,00, z=270,50], EntityBat['Bat'/373, l='MpServer', x=322,57, y=32,32, z=267,46]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:392)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 400825272 bytes (382 MB) / 849989632 bytes (810 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.32 Powered by Forge 12.18.3.2185 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2185.jar) 
	UCHIJA	Forge{12.18.3.2185} [Minecraft Forge] (forge-1.10.2-12.18.3.2185.jar) 
	UCHIJA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.10.2.jar) 
	UCHIJA	Baubles{1.3.8} [Baubles] (Baubles-1.10.2-1.3.8.jar) 
	UCHIJA	Botania{r1.9-339} [Botania] (Botania r1.9-339.jar) 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 376.33' Renderer: 'GeForce GTX 1060 6GB/PCIe/SSE2'
	Launched Version: 1.10.2-forge1.10.2-12.18.3.2185
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1060 6GB/PCIe/SSE2 GL version 4.5.0 NVIDIA 376.33, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz

**Comment by TheWhiteWolves** [comment]
what other mods are you running at the same time and can you reproduce this with only botania?

**Comment by Vazkii** [comment]
Closing from lack of updates
