### ISSUE TITLE
Botania crash when opening lexica botania

### ISSUE THREAD

**Issue by matty72** [Vazkii/Botania#2089]
i attempted to open the Lexica Botania in order to begin the mod, and my entire computer (linux) went to a black screen, saying something about hex codes. there was no crash log, as Minecraft itself didn't crash, the computer just went to a black screen. i have managed to open the lexica botania before to a specific page, but if i try to open it to the main page, my computer goes to a black screen

This is using forge 1.7.10, botania r1.8-249 for 1.7.10 and Java 8 on an Ubuntu 10.04 box

**Comment by ArukaAlter** [comment]
1.7 is no longer supported, try to reproduce this in 1.10, and if works, grab just the latest client log.

**Comment by matty72** [comment]
Ok

**Comment by matty72** [comment]
It still crashes my computer in 1.10, but there is no crash log as Minecraft itself didn't stop, the computer crashed, so Minecraft didn't really have time to create a log

**Comment by Vazkii** [comment]
Replace your graphics card.
