### ISSUE TITLE
Ring of Loki wireframes/selection not working

### ISSUE THREAD

**Issue by Infinidoge** [Vazkii/Botania#2091]
the wire frames of the ring of loki do not appear when i shift right click with the ring on
instead to make the frames appear and for the ring to work i have to take it off, shift click with
the ring which puts it on and makes the frames disappear then i have to repeat for all the blocks
i want to highlight for the effect of the loki ring then shift right click the source block.
then the effect work as normal. i am playing in 1.10.2 with these mods
wireframes appear after selection via my workaround (sometimes does not show and or
changes the selection by removing selections i have made without deselecting them)

http://pastebin.com/L48n0tch

botania for 1.9/1.10(.2) version 339

i have tried with the ring of aesier and loki but it makes no diffrence
will record video of it not working upon request

**Comment by EnderiumSmith** [comment]
use a yeta wrench. i dont know why it works.

**Comment by Infinidoge** [comment]
ok, will try.

**Comment by Infinidoge** [comment]
it works! thank goodness that i have ender io

**Comment by harry2258** [comment]
It also works is Manasteel/Gaia Spirit Ingot.
