### ISSUE TITLE
Livingwood Bow Crashes Game

### ISSUE THREAD

**Issue by Jacobeta** [Vazkii/Botania#2094]
I am using the latest version of Botania. This has not happened when I used the unofficial version. Hitting an entity, including yourself, with the livingwood bow results in a crash of the game and server. 

Below is a pastebin of the crash:
http://pastebin.com/M1wb05iq

**Comment by williewillus** [comment]
`at arc.bloodarsenal.compat.baubles.ItemSelfSacrificeAmulet.selfSacrificeHandler(ItemSelfSacrificeAmulet.java:61)`

it's another mod

**Comment by Jacobeta** [comment]
alright, I'm very sorry! Thank you for helping me out!
