### ISSUE TITLE
Horns are dropping items even if the block break event is cancelled

### ISSUE THREAD

**Issue by Eufranio** [Vazkii/Botania#2096]
Demonstrations, using GriefPrevention and Sponge:

https://gyazo.com/701ef04c5ac6f0313a77aac33c47eb33
https://gyazo.com/772a23e676c82fe0a80ff8d1c09208fa
https://gyazo.com/b5fa9515e798efc839fa53fcea43926c

**Comment by Aaron1011** [comment]
Duplicate of https://github.com/Vazkii/Botania/issues/2173.

**Comment by Eufranio** [comment]
Oh, right!
