### ISSUE TITLE
crashed while summoning gaia 2

### ISSUE THREAD

**Issue by notagain** [Vazkii/Botania#2102]
error just after summoning the gaia v2  saw the  summoning lines and just as he spawned  crashed 2 of us got kicked.
http://pastebin.com/zf01WgRt

**Comment by bookerthegeek** [comment]
Please remove all of that and put the crash report into pastebin and link it back here in your post.

**Comment by notagain** [comment]
done sorry
http://pastebin.com/zf01WgRt

**Comment by TheWhiteWolves** [comment]
Looks to be another issue with MC's data manager not giving back the correct values.

[EntityMagicMissile Line 79](https://github.com/Vazkii/Botania/blob/master/src/main/java/vazkii/botania/common/entity/EntityMagicMissile.java#L79)

**Comment by Xandaros** [comment]
Just had the same issue when someone else on the server used the Key of the King's Law.
I uploaded the [full log](https://sf.inp.io/xan/fml-client-latest.txt). We are playing Sky Factory 3 using the FTB launcher, so the log is a tad... long...

See also #1898
