### ISSUE TITLE
Biomes O' Plenty Flower basket

### ISSUE THREAD

**Issue by ChakatSilverpaw** [Vazkii/Botania#2103]
This is a pretty big issues. The Flower basket from Biomes O' Plenty duplicates flowers if there is one in there and you pick up any other flower from Botania. Having a EndoFlame in the basket and picking up up say a Pure daisy, Will create more EndoFlames.

**Comment by williewillus** [comment]
this is on BOP's side. they use vanilla's `InventoryBasic.addItem`, except that method doesn't check for differences in NBT (which are how botania flowers are distinguished)

**Comment by ChakatSilverpaw** [comment]
Alright, I should have posted on their side.

**Comment by oporcony** [comment]
![Screenshot_2023-06-08-23-06-41-719_com google android youtube](https://github.com/VazkiiMods/Botania/assets/135988636/ebb47d6c-3d09-49e8-bdaf-6e4a57a39437)
How can I find this one can you tell me please 😭😭🥺
