### ISSUE TITLE
Runes of Water/Fire not consumed when crafting Rune of Spring

### ISSUE THREAD

**Issue by eslachance** [Vazkii/Botania#2104]
Minecraft: 1.10.2
Mod Version: Botania r1.9-339

I'm running on a very slightly modified version of AllTheMods Lite (Mekanism removed, Agricraft removed, Iron Backpacks and Elevator Mod added).

When crafting a  Run of Spring on the Runic Altar, the Saplings and Wheat are consumed, but the Rune of Fire and Rune of Water are returned to my inventory when applying the Livingrock and hitting the altar with the Wand of the Forest.

No messages are output to the log (running this in MultiMC, so I got the live console log).

**Comment by ArukaAlter** [comment]
That was a change mades ages and ages ago, read the book, it says that runes used to make other runes are returned upon completion.

**Comment by eslachance** [comment]
Whoops. I guess I should learn to RTEFM (E stands for Entire) before posting things like this. I remembered they were consumed back in 1.7.10, last time I made higher tier runes. smh at myself.
