### ISSUE TITLE
Pollidisiac doesn't work with Rabbits

### ISSUE THREAD

**Issue by Hund** [Vazkii/Botania#2105]
I'm running Minecraft 1.10.2 with Botania r.1.9-339. And the pollidisiac isn't working with rabbits for some reason. I tried both carrots, golden carrots and dandelion - and nothing.

It works just fine with cows, pigs, chickens and cheeps though.

**Comment by TheWhiteWolves** [comment]
Without being able to actually load the game and look my thought atm is that maybe the rabbit is not classed as an animal, even though i'd expect it to inherit from EntityAnimal.

**Comment by williewillus** [comment]
is there an error thrown on the log?

**Comment by jlbrewer** [comment]
@TheWhiteWolves - From a "I haven't seen the code" POV, rabbit behavior shares more with Ocelots than the other farm animals - they run from players unless lured and they will hunt food (read: your carrot patch) in the wild. The main difference is rabbits can't be "tamed". Do Ocelots (and untamed wolves for that matter) inherit from the same Animal class as cows, etc?

(Am interested in this having discovered that Rabbit Stew is now the best Vanilla food in the game, for potential gourmarllys setups later.)

**Comment by Tamaized** [comment]
@jlbrewer That would be AI which doesn't really matter for what the class is. Well, besides being `EntityLiving` which contains the `tasks` field.

`EntityRabbit` does infact extend `EntityAnimal` though.
I can't say why this isn't working as I haven't even bothered to look at Botania's code for this. (Yet anyway)

**Comment by Tamaized** [comment]
Also side note: Just tested this myself with no other mods in `r1.9-339`, it's working with rabbits just fine.

**Comment by williewillus** [comment]
same here

**Comment by Hund** [comment]
So.. yeah. I'm perhaps the biggest dumbass ever. I forgot to add a mana pool... :(
