### ISSUE TITLE
Rod of Terra Firma works at one level *above* sea level

### ISSUE THREAD

**Issue by eslachance** [Vazkii/Botania#2107]
Minecraft: 1.10.2
Mod Version: Botania r1.9-339

I'm running on a very slightly modified version of AllTheMods Lite (Mekanism removed, Agricraft removed, Iron Backpacks and Elevator Mod added).

According to the Lexica Botania, the Rod of Terra Firma does not work *below* Sea Level. However, it doesn't seem to be working *at* sea level either. I can only get it to work when my minimap shows Y Level 64, but sea level is Y Level 63, one *below*. Since I built my base on level 63, it means if I want to flatten terrain I have to do it one level higher, and then remove a complete layer of dirt (obviously, really annoying).

Here I am standing *at* sea level, holding right-click on the rod, and nothing is happening. The rest of the dirt seen is me standing at level 64, one above.

![2017-01-04_13 34 35](https://cloud.githubusercontent.com/assets/643344/21654263/caa15e48-d282-11e6-8b03-21a31502060b.png)

Is this an off-by-one error, or is sea level different in AllTheMods or something?

**Comment by TheWhiteWolves** [comment]
afaik sea level in minecraft has always been at Y 64

**Comment by TheWhiteWolves** [comment]
[Line 114](https://github.com/Vazkii/Botania/blob/master/src/main/java/vazkii/botania/common/item/rod/ItemTerraformRod.java#L114)

This is where it checks for it, all it does is check if you are below the sea level as provided by MC.

however its probably [Line 112](https://github.com/Vazkii/Botania/blob/master/src/main/java/vazkii/botania/common/item/rod/ItemTerraformRod.java#L112) that's causing it as its offsetting the position it checks against down by 1 block.

**Comment by williewillus** [comment]
world.getSeaLevel is 63 by default, by the way

**Comment by TheWhiteWolves** [comment]
its probably the downwards offset that's causing it then.
