### ISSUE TITLE
r1.8-249 - Terra Shatter not repairing with mana

### ISSUE THREAD

**Issue by Lordicon** [Vazkii/Botania#2108]
Been trying to get the terra shatter to repair itself for a bit of time now. Not sure exactly why it is not repairing. Took mana down some and the durability started to drop. Noticed that the durability on the Terra Shatter is displaying one extra durability than the on screen durability while held in hand. Not sure if this has something to do with it or not. Including screenshots of both. 

Also noticed the same issue that was resolved in the past here https://github.com/Vazkii/Botania/issues/376

Screenshots
http://i.imgur.com/MCjfxse.png
http://i.imgur.com/lWhC2sl.png

**Comment by williewillus** [comment]
the off-by-one is unrelated, vanilla's Durability tooltip goes down to 0, then breaks, which means you actually have one more use at 0/2300, hence the hud mod showing 444

**Comment by Lordicon** [comment]
Was misinformed on how the item uses mana and durability. Did not know that you have to have a mana tablet in your inventory for it to restore its durability and that you can not restore the durability using mana from a mana pool directly. Or is this incorrect?

**Comment by ArukaAlter** [comment]
All items repair using mana from any mana storing item.
The Terra Shatterer only use mana from the pool to maintain it's AoE mining ability.
