### ISSUE TITLE
Crash when placing Corporea Spark

### ISSUE THREAD

**Issue by AlexKurokishi** [Vazkii/Botania#2109]
I tried to place a Corporea Spark on top of a Birch Chest and when I placed it, my client crashed. A Friend who was on the same server came to check out the area and he too crashed when he got too close to the spot where I placed the Corporea Spark. Removal of the Spark with TNT allowed us to go to that spot again. 

My Minecraft version is 1.10.2 and my Botania version is r1.9-339. I am playing on a custom modpack.

Crash Report: http://pastebin.com/Lx9smKXF

**Comment by TheWhiteWolves** [comment]
ok somethings definitely wrong with the data manager, this is the third time I've seen it throw back something with the wrong value.
