### ISSUE TITLE
[Bug] [SinglePlayer] [1.10.2] Spectator does not highlight all relevant inventories, only searches once hovered over

### ISSUE THREAD

**Issue by imakunee** [Vazkii/Botania#2111]
With The Spectator equipped in the head Bauble slot it does not function entirely properly. 

- The Spectator will only search for items when you open your bauble inventory and hover the cursor over the equipped Spectator item in the bauble slot. 

- The spectator will have all matching items on the ground correctly highlighted however only 1 inventory containing the item will be highlighted. The same inventory is always highlighted. 

- The highlighting will remain even when changing what item is in the main hand until you hover the cursor over The Spectator in the baubles inventory again

- If a furnace contains the searched for item The Spectator will (sometimes) cease to highlight any inventory at all. I haven't found a pattern to when it does or does not function.

FML Log: [fml.txt](https://github.com/Vazkii/Botania/files/687809/fml.txt)

Installed Mods: Botania r1.9-339
                        Baubles-1.10.2-1.3.8

Forge Version: forge 1.10.2-12.18.3.2185

**Comment by williewillus** [comment]
It seems like right clicking it puts the spec into the wrong baubles slot or something, or the wrong slot is being resynced after it's put there

**Comment by Vazkii** [comment]
https://github.com/Vazkii/Botania/blob/master/src/main/java/vazkii/botania/common/core/helper/MathHelper.java#L28-L43

This code seems somewhat borked.

> 7:15:17] [Server thread/INFO] [STDOUT]: [vazkii.botania.common.item.equipment.bauble.ItemItemFinder:getBlockPositions:213]: READ: [-4863, -4671, 2305843885387022336, 0]
[17:15:17] [Server thread/INFO] [STDOUT]: [vazkii.botania.common.item.equipment.bauble.ItemItemFinder:setBlockPositions:221]: WRITE: [-20611078291258, -20885889089336, -19511566663479, -20061255368500]
[17:15:17] [Client thread/INFO] [STDOUT]: [vazkii.botania.common.item.equipment.bauble.ItemItemFinder:getBlockPositions:213]: READ: [-4863, -4671, 2305843885387022336, 0]

**Comment by williewillus** [comment]
It might be but I don't think so. If it was then the bauble wouldn't work at all, instead of working partially.
