### ISSUE TITLE
Rod of Shifting Crust won't replace blocks with "leaves block"

### ISSUE THREAD

**Issue by Jomik** [Vazkii/Botania#2112]
I am trying to replace dirt blocks with leaves. Nothing happens however. It does correctly show the dirt blocks as the target blocks.
I was expecting it to replace the blocks, I believe leaves should count as a "full" block, they don't do cheaty things, like torches jumping off walls to instantly remove large quanties of blocks.

FML Log: https://gist.github.com/Jomik/77d1a80c3e8720d5bb2b4630bc0dba92

**Comment by TheWhiteWolves** [comment]
can you make a vid or gif of what you are doing?

**Comment by Jomik** [comment]
With Rod of the Shifting Crust; Shift+Right click an oak leaves block, right click dirt block.
Not entirely sure why you'd want a graphical preview. Best I can do was this: https://gyazo.com/edc3bc11bb0ad9c915f05e2d071a28f6

**Comment by TheWhiteWolves** [comment]
mmm, strange you're doing everything right by the looks of it and iirc leaves should work, can't see anything in the code to say they shouldn't.

Could be a cross-mod thing causing it, have you tried with only botania installed.

**Comment by Jomik** [comment]
I will try when I get the chance. I currently have exams, so I don't have time to test, sadly. I use minecraft to relax at the moment :)
Have you tried to replace with leaves in other packs?

**Comment by Jomik** [comment]
@TheWhiteWolves 
Are you sure this line isn't preventing the exchange? https://github.com/Vazkii/Botania/blob/8c2b282f8999942ea2e1b730754358ea1b6b8306/src/main/java/vazkii/botania/common/item/rod/ItemExchangeRod.java#L224
Specifically thinking of `stateAt.getPlayerRelativeBlockHardness(player, world, pos) > 0`

**Comment by quat1024** [comment]
I think this has something to do with tree leaves, player placed leaves, and the item form of leaves all having different data values.

Leaves naturally generated off of trees can be either `minecraft:leaves` or `minecraft:leaves2`. All leaves use the two least significant bits of their data values to determine the type of leaves, and the other two bits are **irrelevant** as far as the Rod of the Shifting Crust is concerned, they're used internally to determine if a leaf should decay when you cut down the tree.

This means that leaves in the inventory always have data values of 0 through 3, but in-world leaves can have data values of anywhere from 0 to 15.

http://minecraft.gamepedia.com/Leaves#Block_data

The Rod doesn't seem to know about this - it seems to think that leaves with the check decay or decayable blockstates are different than leaves that don't have those states.

**Comment by Jomik** [comment]
The issue isn't replacing leaves in world. The issue is replacing blocks in world (dirt) with leaves from inventory.
