### ISSUE TITLE
Terra Blade doesnt show third enchantment

### ISSUE THREAD

**Issue by Novian3002** [Vazkii/Botania#2113]
When trying to add a third enchantment to the terra blade with a vanilla anvil, the terra blade doesn't show the new enchantment that was added.

It seems to be irrelevant which enchantments are used.
[Images](http://imgur.com/a/TPSQ6)
[FML Log](http://paste.ee/r/B8RPO)

**Comment by CJOak** [comment]
All swords can only have one of the following enchantments: Sharpness, Smite, Bane of Arthropods.
It's not showing up because it isn't being added.

**Comment by Novian3002** [comment]
It does drain xp and consume the book though

**Comment by TheWhiteWolves** [comment]
iirc you can't combine smite and sharpness on the same weapon.

**Comment by williewillus** [comment]
Vanilla thing. If you have conflicting enchants one just overwrites the other
