### ISSUE TITLE
[1.10.2]Bug with Crafty crate

### ISSUE THREAD

**Issue by Myknakryu** [Vazkii/Botania#2119]
Minecraft version: 1.10.2
Forge version: 2202
Botania version: r1.9-339
Baubles version: 1.3.8
JEI version: 3.14.2.401

When block is below crafty crate created items gets destroyed(maybe not captured on video but i've put stack of planks to hopper so it should make 8 chests). Does not behavior like open crate when items are buffered.

Video:
https://youtu.be/C2BdSvrweR8

**Comment by Vazkii** [comment]
https://github.com/Vazkii/Botania/commit/3013253c9036106a77b16aaa18a093c517914726
