### ISSUE TITLE
[1.10.2]Strange behavior with tiny planet (Bauble)

### ISSUE THREAD

**Issue by Myknakryu** [Vazkii/Botania#2120]
Minecraft version: 1.10.2
Forge version: 2202
Botania version: r1.9-339
Baubles version: 1.3.8
JEI version: 3.14.2.401

Very strange behavior when Tiny Planet (bauble) is used. When Tiny Planet block is placed mana spreader works normally Mana Spreader.

Video:
https://youtu.be/Vx3VhCbicQM

**Comment by Vazkii** [comment]
Intended.
