### ISSUE TITLE
[1.10.2] Bug/Feature Force relay getting destroyed when squished by pistons

### ISSUE THREAD

**Issue by Myknakryu** [Vazkii/Botania#2123]
Minecraft version: 1.10.2
Forge version: 2202
Botania version: r1.9-339
Baubles version: 1.3.8
JEI version: 3.14.2.401

When Force Relay is getting squished by two pistons block connected gets pushed and relay is destroyed. I think it should stop pistons. But it's unstable block as it was written in Lexica Botania so i don't know. And for some reason when pistons break Force Relay the connection is still saved and can be used without connecting again.

Video:
https://youtu.be/Pnq4Ie2Y5ao

**Comment by Vazkii** [comment]
Due to how force relays work, I can't fix this one.

**Comment by Myknakryu** [comment]
One question about ender air does it have Area effect with no limit or it has limit how many blocks can it transform.

**Comment by williewillus** [comment]
keep your messages relevant to the ticket please, get on irc if you want general discussion
