### ISSUE TITLE
[MC 1.10.2]Red Stringed Container Either Not Exposing Inv or Not Issuing Neighbour Update On Chunk Reload

### ISSUE THREAD

**Issue by Armitige** [Vazkii/Botania#2125]
Red stringed containers don't appear to be exposing their inventory or are not issuing a neighbour update on chunk reload.

I have several red stringed containers with multiple ender io item conduits attached to them. The item conduits disconnect on chunk reload, and will only reconnect with a block update (ie. placing a piece of dirt next to the conduit). 

Forge: 12.18.3.2185
Botania: r1.9-339
FML Log: http://pastebin.com/S9zyhQjg

**Comment by williewillus** [comment]
is the thing it's connected to in another chunk from the red string itself? it may be that the red string loads first, sees that nothing is where its binding is, and disconnects.

That being said, it rechecks for a binding every tick so the glitch is just visual I think

**Comment by Armitige** [comment]
@williewillus no, the red stringed containers are pointing straight up, and the target inventories are about 3 blocks away. That's 1 of the first things I would have checked if it was possibly applicable, and in this case, it's not. Also, it's not just visual, because items in the inventories the containers are bound to are no longer being extracted or inputted.
