### ISSUE TITLE
The Drum of the Gathering causes server to crash (Direwolf20 1.10.2)

### ISSUE THREAD

**Issue by NevetsDotLua** [Vazkii/Botania#2126]
I'm currently using the Direwolf20 1.10.2 modpack version 1.2.2, and the Drum of the Gathering crashes the server.

Are you in the latest version of the mod?
Yes

Are you in the latest version of Forge?
Yes

Are you using vanilla Forge (not MCPC+)?
Sponge, so no

Are you using Optifine?
Server, N/A

The crash log seems to indicate that on upon collision with the Drum of the Gathering, a mana burst had a java.lang.NullPointerException.

This was likely an automated system, and it doesn't happen every time. I am unsure of what exactly causes the crash, since it was an automated system. This is obviously probably not very easy to reproduce.

Crash Report: http://pastebin.com/10d37y5j

**Comment by ArukaAlter** [comment]
Try to reproduce on a standard Forge server.

**Comment by williewillus** [comment]
^
