### ISSUE TITLE
Livingwood bow enchanted with infinity consumes arrows

### ISSUE THREAD

**Issue by jdratlif** [Vazkii/Botania#2127]
I enchanted my livingwood bow with Infinity, but arrows are still consumed when firing the bow. And you cannot pick up the arrows fired into the ground, which is consistent with the infinity enchant.

MC 1.10.2
Forge 2185
Botania 1.9-339

I enchanted the bow in a vanilla anvil with a enchanted book of inifinity. I got the book from ender IO enchanter, but I don't see why that should cause problems. I also have Punch II on the bow (usingthe same process), and that seems to work correctly.

**Comment by Myknakryu** [comment]
Yup... It consumes arrows when bow is enchanted with infinity
Minecraft version: 1.10.2
Forge version: 2202
Botania version: 1.9-339

**Comment by jdratlif** [comment]
My friend pointed out something I had not tested, you can still fire the bow if you have infinity enchant and no arrows, so the fact that it uses up arrows might be irrelevant. Perhaps that is 'working as intended'?

**Comment by williewillus** [comment]
nah, it's a bug. infinity on vanilla bows doesn't use arrows so this shouldn't either

**Comment by Vazkii** [comment]
https://github.com/Vazkii/Botania/commit/86bdfaa186c6bfe2dcfd3d235c6ded86b8f2bba1
