### ISSUE TITLE
Crashing Issues with Mana Bursts

### ISSUE THREAD

**Issue by Briancd2** [Vazkii/Botania#2130]
I'm playing on **Direwolf20 1.10.2 version 1.1.4** and I've been crashing in my server every time I log in. I didn't start crashing until I placed down a few Botania functional flowers and a mana spreader. I equipped the Wand of the Forest and my game crashed. I've tried logging into the server multiple times, but I crash after a few seconds.

This is a picture of the Botania setup I had when the crashing started: http://i.imgur.com/xayHTO1.png

This is the crash report link: http://pastebin.com/NfPiAJ06

This is the FML log link: http://www.mediafire.com/file/v1dy5q830l9i4h9/fml-client-1.log

**Comment by chris54721** [comment]
Same here. Sky Factory 3.0.4
https://hastebin.com/xayuhokamu
