### ISSUE TITLE
Crashed from changing worlds

### ISSUE THREAD

**Issue by BrofistKittycat** [Vazkii/Botania#2135]
I was meddling around in creative when I decided to switch over to my survival world and got this crash:
[http://pastebin.com/vbwmQHn7](url)
I **think** it was from Botania, but I'm not very sure. If it helps I was spamming the mana blaster quickly right before I switched. I also deleted the creative world immediately after exiting.

**Comment by BrofistKittycat** [comment]
Now that I think about it, I added some mods after creating the world, so my guess is that the id used for the mana blaster in the creative world is the Manasteel Axe ID in my survival world.

**Comment by Tamaized** [comment]
1.7.10 is no longer supported.

**Comment by BrofistKittycat** [comment]
Ah, sorry.
