### ISSUE TITLE
Ring of Loki/Aesir inverted empty hand check behavior.

### ISSUE THREAD

**Issue by Tomaszal** [Vazkii/Botania#2136]
As said in Lexica Botania, ring of Loki requires an empty hand to use.. except it's reversed. When you shift + right click on a block with an empty hand, nothing at all happens. But when you shift + right click on a block with almost anything in your hand, it selects it and starts showing the wire frame. What is weird as well (and probably even more annoying) is the fact, that when you look in some inventory that requires shift + right click to open (f.e. storage drawers) it also selects the block and makes you have to reopen the inventory later to get rid of the wire frame.

Botania: r1.9-339
MC: 10.2
Forge: 12.18.3.2185
FML: 8.0.99.99

**Comment by Cal26lum** [comment]
Additionally, it is possible to select blocks using even the ring itself, as it equips and selects at the same time.

**Comment by CJOak** [comment]
This has been my experience with how the ring has been working:
If you have an item in the offhand slot (have not tried with blocks) and shift-right click with an empty hand, the Ring creates a wireframe. If you shift-right click while you also hold something in your main hand, no wireframe is created.

If you do NOT have an item in the offhand, shift-right clicking with an empty hand does not create a wireframe. But if you are holding an item in your main hand (like a pickaxe) and shift-right click, a wireframe is created.

**Comment by williewillus** [comment]
Unfortunately, I can't fix this until some of my bugfixes get into forge (which they still haven't...)
