### ISSUE TITLE
Mana enchanter doesn't recognize floating flowers

### ISSUE THREAD

**Issue by jeridan** [Vazkii/Botania#2137]
Modpack: Direwolf20 1.10-1.10.2-1.4.1
Botania: Botania r1.9-339

When building the mana enchanter it will not complete using floating flowers.

**Comment by ArukaAlter** [comment]
It only uses the regular variant, not even glowing flowers are allowed, intended.

**Comment by Vazkii** [comment]
This is not intended.

**Comment by ArukaAlter** [comment]
I may had misinterpreted, sorry.
