### ISSUE TITLE
Broken Texture Lapis Ore

### ISSUE THREAD

**Issue by Coolcabbage** [Vazkii/Botania#2138]
When hitting a lapis ore block with a weight lens and dropping it onto a slab the item you get out is untextured.
It still places down properly and has the correct name.
This happened with orechid spawned lapis and jei cheat lapis
I was using a weight messenger lens

Mod list:
Minecraft 1.10.2
Forge-12.18.3.2215
AppleCore-mc1.10.2-2.1.0
AutoRegLib-1.0-2
Baubles-1.10.2-1.3.8
Botania r1.9-339
Ding-1.10.2-1.0.1
FTBLib-1.10.2-3.2.3
FTBUtilities-1.10.2-3.2.4
GardenOfGlass
InventoryTweaks-1.61-58
itemscroller-1.10.2-0.10.2
jei_1.10.2-3.14.3.403
JustEnoughResources-1.10.2-0.5.8.98
LLOverlayReloaded-1.1.1-mc[1.9-1.11]
Neat 1.3-12
NoMobSpawningOnTrees-1.2.0-mc1.10.2
Quark-r1.1-70

**Comment by williewillus** [comment]
this is a vanilla bug - EntityFallingBlock drops an ItemStack made with `(block, 1, block.damageDropped(state))`, but lapis block's `damageDropped` assumes the thing dropping is the dye item, and returns that meta value instead. any fix would require changing vanilla or using our own falling entity

**Comment by williewillus** [comment]
closing due to the above, I reported it to vanilla: https://bugs.mojang.com/browse/MC-112891
