### ISSUE TITLE
Elven Gateway Reveals The Truth

### ISSUE THREAD

**Issue by jcool2314** [Vazkii/Botania#2139]
I have discovered a visual bug that I call 'Elven Gateways and Sparks Reveal The Truth'. Basically, when looking at Mana Pools, Botanical Breweries, and sometimes Pylons, through a Spark or Elven Gateway, they disappear from view, but when not, they reappear. Is this the 'wrap' you referred to in the Lexica Botania? I am using the latest version of Sky Factory 2.5, and here is the current log. http://paste.feed-the-beast.com/view/e881bec9

**Comment by ArukaAlter** [comment]
It's just how Minecraft render things through translucent things like portals, it has been noted before, you are just overreacting :}
