### ISSUE TITLE
[1.10] mousing over the rod of the shifting crust in any gui crashes the game

### ISSUE THREAD

**Issue by GoldenZdude** [Vazkii/Botania#2143]
Mousing over the rod of the shifting crust in any gui crashes my game, I tested in my inventory, an actually additions crate, and an iron backpack. I do not need to click the item for it to crash.
http://pastebin.com/YVDJzpkK

**Comment by GoldenZdude** [comment]
I'm currently using a modified Direwolf20 1.10.2 modpack version 1.1.4.
Are you in the latest version of the mod?
Yes

Are you in the latest version of Forge?
Yes

Are you using vanilla Forge (not MCPC+)?
yes

Are you using Optifine?
no

**Comment by williewillus** [comment]
your pastebin seems to be cut off, can you post the whole thing? thanks!

**Comment by williewillus** [comment]
I also can't reproduce this with botania alone

**Comment by williewillus** [comment]
not enough info
