### ISSUE TITLE
Botania Ring of Far Reach not working right. [1.7.10]

### ISSUE THREAD

**Issue by TangyOnion** [Vazkii/Botania#2145]
I made the ring on a server me and and my friend play on. He hosts it and only the two of us play on it. When i equip it, waila works for block farther away but i can't interact with them. It doesnt work in single player either. It is probably Aether II causing the problem because removing it makes it work in single player.  Is there a version of botania that fixes this? Or a setting that helps because i really like Aethher II and don't want to remove it.

**Comment by ArukaAlter** [comment]
1.7 is not supported anymore.

**Comment by TangyOnion** [comment]
But is there a version of the mod for 1.7.10 that fixed this?

**Comment by TheWhiteWolves** [comment]
If its not working in the last 1.7.10 version then no
