### ISSUE TITLE
Minecraft crashes when using NEI, may have to do with Botania

### ISSUE THREAD

**Issue by Ventus51701** [Vazkii/Botania#2146]
When I try to use any of the features of NEI, the game crashes. Looking up recipes, spawning items, both crash the game. It doesn't matter what item I try, it will crash. Other than that, if I don't use NEI, it doesn't crash.

FML Log: https://gist.github.com/anonymous/73c1bb8636bae4bbeee647cb8dab4f53

**Comment by williewillus** [comment]
1.7 is no longer supported, but an addon might be adding invalid recipes so maybe look at that

**Comment by Ventus51701** [comment]
by 1.7, are you referring to the minecraft version?

**Comment by Tamaized** [comment]
> by 1.7, are you referring to the minecraft version?

Yes
