### ISSUE TITLE
Infinite mystical white flowers via plant harvest upgrade from Baubles Stuff

### ISSUE THREAD

**Issue by wolpoff** [Vazkii/Botania#2147]
With a ring with the Baubles Stuff upgrade Plant Harvest Upgrade, it will infinitely harvest Mystical White Flowers from Botania. It surprised me at first, and then didn't repeat, but I figured out that if there is a vine hanging down on top of the mystical flower, it causes it to infinitely harvest. Yay swamps I guess.
The most interesting part is if you have a different color mystical flower, you place it underneath the hanging vine, and then it kicks the non-white one out, replaces it with a white one, and then infinitely harvests white flowers.

Please see crappy video: https://drive.google.com/file/d/0B0CmhRPuv37CN3ExRUk1MkR6TmM/view?usp=sharing
:)

**Comment by williewillus** [comment]
Thanks for the detailed video!
I'm pretty sure this is a bug with the bauble mod but it needs some investigation

**Comment by williewillus** [comment]
Bauble's Stuff has a bug.

Right [here](https://github.com/ZAZPRO/BaublesStuff/blob/ab3f8d4d61b8b428d219e8acbb4fbfa0309fafcf/src/main/java/md/zazpro/mod/common/baubles/Ring_Core.java#L234-L235) the logic is saying "drop the block's drops, then put that block's default state back" which as you've seen causes an infinite loop :P 

I think the modder wanted a clever way to revert an IGrowable to its ungrown state but that approach doesn't work for everything.

**Comment by williewillus** [comment]
(if you a file a bug report for them feel free to link to this for analysis)

**Comment by wolpoff** [comment]
Cool! Filed issue 51 with Baubles Stuff:
https://minecraft.curseforge.com/projects/baubles-stuff/issues/51

Thanks!
