### ISSUE TITLE
Mana Detector causing huge lag spikes

### ISSUE THREAD

**Issue by swemoney** [Vazkii/Botania#2149]
I was working on a simple way to drop blocks of coal onto my endoflames whenever there wasn't mana being passed to the mana pool. So I had a mana detector pulse an RFTools sequencer whenever mana passed through it which would reset the timer that was connected to the conduits that would extract the blocks of coal and pass them to the open crate. I started noticing HUGE lag spikes. My overall FPS was down towards 7. I started disconnecting things with SHIFT+ALT+F3 up and kept seeing the lag spikes until I broke the mana detector. Clear as day at a constant 60 fps after that. I tried both Ender IO redstone conduits and Super Circuit Maker red alloy wire to connect everything and it didn't  make a difference. Even with nothing connected to the mana detector, I was still getting the lag spikes. I even took apart the entire contraption and was left with only the spreader, pool detector and 14 endoflames and the spikes came back with the detector present.

Edit: This is version 1.9-339 in the Sky Factory 3 pack (3.0.5)

**Comment by williewillus** [comment]
can't reproduce with botania alone

**Comment by williewillus** [comment]
can you build the stripped down botania only part that still has lag spikes and put a link here?

**Comment by williewillus** [comment]
the mana detector just uses normal block updates to rerender, it shouldn't be any more laggy than something like a repeater or redstone torch toggling

**Comment by swemoney** [comment]
I tested in a creative completely clean sky factory 3 world and didn't see the same issue so it was definitely a combination of other things interacting. We can close this. Doesn't seem to be a Botania issue.
