### ISSUE TITLE
All Botania Mana disappears when playing offline

### ISSUE THREAD

**Issue by Zeno410** [Vazkii/Botania#2151]
All my pools and the mana tablet on my person became empty when I started a game offline. Two mana tablets in a chest which I didn't open while offline were unaffected. I have been having problems with pools emptying which may happen during Waystones teleports but I didn't teleport this time, and that had not been affecting Mana tablets on my person.

MC 1.10.2
Forge 2185
Botania 340

Complete Modlist:
AppleCore-mc1.10.2-2.1.0.jar
backpack-3.0.1-1.10.2.jar
Baubles-1.10.2-1.3.6.jar
BiomesOPlenty-1.10.2-5.0.0.2086-universal.jar
Botania r1.9-340.jar
davincisvessels-1.10.2-0005-full.jar
ForgeAmidst-1.9.4-1.4.1.jar
GeographiCraft-0.8.3.jar
GuideBook-1.6.3.jar
movingworld-1.10.2-0003-full.jar
NaturesCompass-1.10.2-1.2.0.jar
Pam's HarvestCraft 1.9.4-1.10.2h.jar
RTG-1.10-test.jar
SpiceOfLife-mc1.9.4-1.3.6.jar
UndergroundBiomesConstructs-1.10-test.jar
Waystones_1.10.2-2.0.10.jar
ВращениеЗемли-1.9.4.jar

**Comment by JRoffel** [comment]
Just out of curiosity, what is that last mod?

**Comment by Zeno410** [comment]
Those were all the 1.10.2 versions when I started, because 1.9.4 and 1.10.2 are generally interoperable.  Most have never even bothered to update. The last mod is often called B3M (Roman version of the Cyrillic initials) and allows adjusting the length of the day, plus some celestial year features with length of day and celestial inclinations.

**Comment by williewillus** [comment]
for the pools: is it visual? does the mana appear if you relog?

**Comment by Zeno410** [comment]
No, it's not just visual. My gear and flowers stop working. Relogging doesn't help other than I stop getting the pools zeroed out. I didn't test adding mana to pools while logged out.
