### ISSUE TITLE
Corporea Related Crash

### ISSUE THREAD

**Issue by Ravin890** [Vazkii/Botania#2153]
So while on my server, a friend threw 16 elementium onto the runic altar in the following setup:
![2017-02-02_18 48 49](https://cloud.githubusercontent.com/assets/13302573/22576426/5616fd9e-e989-11e6-9bef-50d01d7eb28f.png)

And results in the following crash: 
[crash-2017-02-02_20.34.38-server.txt](https://github.com/Vazkii/Botania/files/749416/crash-2017-02-02_20.34.38-server.txt)

*it occurs in both single player and multiplayer

**Comment by williewillus** [comment]
not sure why it happened in the past but this *shouldn't* happen in 1.11 anymore
