### ISSUE TITLE
The Rod of the Shifting Crust doesn't work on Seared Bricks from Tinker's Construct.

### ISSUE THREAD

**Issue by Ansalem** [Vazkii/Botania#2155]
The Rod of the Shifting Crust doesn't work on Seared Bricks (or any other Seared block for that matter) from Tinker's Construct. I can't choose them and I can't replace them with something else. Shift-right-clicking does nothing, right-clicking does nothing, left-clicking does nothing. Tested with a fresh rod in a fresh world just in case mine was broken somehow.

FML Log: https://gist.github.com/Ansalem/063e1fecc66c685ed55c1241258f81aa

(Are these things supposed to be this huge? Sorry if I did this wrong.)

**Comment by Penrif** [comment]
Rod of the Shifting Crust does not work on TileEntity objects, which Seared Bricks are.  You can confirm this by testing if vanilla pistons move them, as they have the same restriction.
