### ISSUE TITLE
Another Thermalily Glitch

### ISSUE THREAD

**Issue by LemonLord1** [Vazkii/Botania#2156]
Hey! Got the cool achievement, [Take it easy]! But the problem is, I was playing SkyFactory3 (Modpack) and I was using a system with a dispenser that placed lava every 1500 ticks to automate mana production via Thermalily. Picture here, Thermalilies (Thermalilys?) are around the middle, slightly to the left.
![image](https://cloud.githubusercontent.com/assets/25561230/22624396/b4950a70-ebc6-11e6-8012-d7047fc84e77.png)
The only thing I could figure out what was wrong was that I went into an RF Dimension and came back and found out that I had a purple and black block, which was harvested immediately and put in my storage system. I had used Draconic portals as well but I don't know if I can figure out anything else. Note: The lava placed by the dispenser stays there for around 20-60 seconds before being absorbed by the Thermalily due to timing issues when I set up the system.

Thanks!
-Lemon Lord

P.S. Love the mod, made a few things similar in Vanilla with Command Blocks.

**Comment by ArukaAlter** [comment]
Are you using any sort of terrain protection mod or plugin against players/Creepers?

**Comment by LemonLord1** [comment]
No. Only thing I can think of is that I'm using the Charm of the Benevolent Goddess in order to stop creepers destroying my world.

**Comment by ArukaAlter** [comment]
I overlooked everything because of that primed TNT in the corner. Do you have an Entropynium set outside the screenshot area?
But I can tell your Thermalilly side has flaws, they can absorb lava when they are with smoke particles, raising the cooldown again and generating nothing by doing so.

**Comment by LemonLord1** [comment]
Actually the TNT is on top of a single Entropynnium, given I have a Gaia Mana Spreader it is on a 20s timer, possible complication? Also the Thermalilies don't seem to consume anything when they can't generate mana, must be a config in the modpack. Also the lava is on a 1500 tick timer which means that it can only go when at least one of the lilies is able to get some lava on it. However, this did not really help.

**Comment by williewillus** [comment]
closing from staleness (it's likely was just a temporary glitch)
