### ISSUE TITLE
[1.10.2] Orechid and Project:Red

### ISSUE THREAD

**Issue by Xiaminou** [Vazkii/Botania#2158]
Orechid doesn't generate any ores from Project:Red.

**Comment by codycoolwaffle** [comment]
As far as I can see in the code, it should be working, but I have not tested yet. I will test when I get a chance. As for now, please provide a mod list and the Botania config. Upload those two here and link to it in a comment: http://pastebin.com/

**Comment by codycoolwaffle** [comment]
Also, report the version of Botania you are using. As you are using a 1.10 version this may have already been fixed.

**Comment by codycoolwaffle** [comment]
Finally, if it is a current issue, and it does get fixed, it will not be officially back-ported to 1.10 period.
