### ISSUE TITLE
Mana Pool Not Accepting Mana

### ISSUE THREAD

**Issue by BigFriendlyJakey** [Vazkii/Botania#2160]
Just started Botania in a new world, but I'm stuck in the early game; I have an Endoflame supporting 2 Mana Spreaders that's target is my mana pool. I've spent about 3 stacks of coal so far, and the Endoflame and both Mana Spreaders are full, but the Mana Pool isn't getting any bursts from the Mana Spreaders. Anything I'm doing wrong?

**Comment by williewillus** [comment]
did you bind the spreader to the pool?

**Comment by CJOak** [comment]
And make sure nothing is in the way of the spreader, like a torch (at least, I seem to recall it blocking mana bursts).

**Comment by BigFriendlyJakey** [comment]
yeah I did that, the spreader says "mana pool" below it, but no mana's going in

**Comment by BigFriendlyJakey** [comment]
nothing's blocking it either :/

**Comment by CJOak** [comment]
If breaking and replacing the mana spreader doesn't work, could you take a screenshot?

Actually, before that, make sure the spreader is not receiving a redstone signal either.

**Comment by BigFriendlyJakey** [comment]
Breaking & replacing fixed it! Thanks a bunch

**Comment by BigFriendlyJakey** [comment]
Okay I'm sure it's probably me, but now the Runic Altar is doing the same thing. I've tried breaking & replacing both the altar and the spreader, I'm sure they're binded, and on top of this it doesn't respond to the right click from the wand to begin the process, nor a right click from an empty hand to take away the items.
