### ISSUE TITLE
Runic Altar Glitched?

### ISSUE THREAD

**Issue by BigFriendlyJakey** [Vazkii/Botania#2161]
I did just have a similar problem, but I can't find a workaround for this. My previous problem involved mana spreaders not sending mana to a mana pool, but it was fixed with a simple break & replace. The runic altar is now having the same issue. I've tried breaking & replacing, unbinding & rebinding, using sparks instead of mana spreaders to send mana to the altar, and adding & removing a redstone source. Nothing seems to be sending mana, but when I put the items in to make something it makes the sound affect like it's making the item :/

**Comment by williewillus** [comment]
can we have a modlist?

**Comment by williewillus** [comment]
it could be that it's just not rendering for some reason

**Comment by BigFriendlyJakey** [comment]
Agricraft
AlchemicAsh
AppleSkin
AstroLib
AutoRegLib
Baubles
BloodMagic
Bookshelf
Botania
Calculator
Chameleon
Chisel
Chisel & Bits
Embers
EnderCore
EnderIO
ExtraUtils2
FlatColoredBlocks
GeneticsReborn
Guide-API
ImmersiveEngineering
InfinityLib
InventoryTweaks
IronChest
JEI
JourneyMap
JustEnoughResources
LibrarianLib
LongFallBoots
LucraftCore
LunatriusCore
Mantle
MoreOverlays
Neat
Optifine
PSIonicUpgrades
PSI
Quark
Refraction
Reliquary
Sanguimancy
SimpleCore
SimpleOreGen
SonarCore
SpeedsterHeroes
StorageDrawers
TinkersConstruct
TinkerToolLeveling
UniDict
VeinMiner
Wawla

**Comment by BigFriendlyJakey** [comment]
^^ All up to date for 1.10.2

**Comment by BigFriendlyJakey** [comment]
Update: Mana Pool is no longer taking mana from the mana spreader again. I'm sure I can break and replace the mana spreader and it'll work, but I'm sure it's not meant to be this fidgity.

**Comment by williewillus** [comment]
redirecting to #2165
