### ISSUE TITLE
r1.9-340 Hydroangeas

### ISSUE THREAD

**Issue by GalvenTreenock** [Vazkii/Botania#2163]
The Hydroangeas seem to be broken. They don't always seem to auto connect to spreaders as well as not transferring mana to pools. I will test further to see if it is from my end, but it doesn't seem to be.

**Comment by yrsegal** [comment]
Have you tried placing the hydroangea *after* the spreader?

**Comment by GalvenTreenock** [comment]
Yes.

**Comment by Penrif** [comment]
![image](https://cloud.githubusercontent.com/assets/17394578/22905848/c13842de-f1f6-11e6-9deb-13a4e7609804.png)

Works fine for me, placed spreader first then hydros.

**Comment by GalvenTreenock** [comment]
Hmm sorry to waste your time. Your mods awesome btw 😏
