### ISSUE TITLE
Achievements window causing crashes

### ISSUE THREAD

**Issue by ShaunDreclin** [Vazkii/Botania#2164]
When I move to the top left corner of the achievements window, the game crashes. Only happens when botania achievements are selected.

[crash-2017-02-14_03.18.59-client.txt](https://github.com/Vazkii/Botania/files/773490/crash-2017-02-14_03.18.59-client.txt)

Playing in All The Mods: Expert modpack

**Comment by williewillus** [comment]
Dupe of #2060, forge bug https://github.com/MinecraftForge/MinecraftForge/issues/3293
