### ISSUE TITLE
Mana spreader wont export mana

### ISSUE THREAD

**Issue by NicosaurusRex99** [Vazkii/Botania#2165]
I discovered that v 1.9 340 mana spreaders will not push mana to mana pools unless the pool is directly below the mana spreader. 

Video is unlisted and is probably a little off topic as i was recording an episode but it shows the bug (only a short video like 5 minutes) https://youtu.be/A-zLkUmlAKE?t=28s

**Comment by williewillus** [comment]
works fine for me

**Comment by NicosaurusRex99** [comment]
O.o should i reinstall the JAR file?

**Comment by dsbookbug** [comment]
I'm also having this issue with version 340

**Comment by williewillus** [comment]
need more info. what mods? (optifine and sponge?) redstone source near the spreader? etc.

**Comment by KingDGrizzle** [comment]
Also, try breaking and replacing the spreader, that might fix it

**Comment by SerialCrasher23** [comment]
Hi, problably the same problem here. Normal Mana spreaders works, if placed at one block distance facing the pool, any try to bind it to the pool goes flat. The runic altar works if the spreader is placed directly above, again, facing the altar, no wand involved. Transmisson between spreaders seems to work fine. Elven mana spreader dont work with a pool, at all. Using Forge .2221 and this modlist: http://pastebin.com/RwkqnucN

**Comment by williewillus** [comment]
anyone able to make it happen with just botania?

**Comment by SerialCrasher23** [comment]
The issue present itself interacting with this mod: 
https://minecraft.curseforge.com/projects/lucraft-core?gameCategorySlug=mc-mods&projectID=230651
Posting a message on the mod page

**Comment by williewillus** [comment]
Does it happen even if that mod is just installed? Or does a certain block or item from that mod need to be present in the setup to cause it

**Comment by SerialCrasher23** [comment]
Just installed

**Comment by NicosaurusRex99** [comment]
The modpack i used was https://minecraft.curseforge.com/projects/the-great-pack

**Comment by williewillus** [comment]
did this mod ever fix the interaction?

**Comment by NicosaurusRex99** [comment]
I think so
