### ISSUE TITLE
[1.10.2] Body and Legs armor stats appear to be swapped

### ISSUE THREAD

**Issue by Mike-T4** [Vazkii/Botania#2166]
This is the case for all armor sets added by Botania.
Bodies appear to have the stats that legs are supposed to have, and the other way around.
Eg: Manasteel Body provides +5 armor, while Manasteel legs provide +6 armor.
Same thing with Terrasteel and Elementum.

The Lexicana Botanica states that Manasteal is meant to be identical to Iron stat-wise, which pretty much confirms that this is an error. 

And of course, it makes no sense that an item that is easier to make (7 bars as opposed to 8) has notably worse stats. 

Version: r1.9-340

**Comment by williewillus** [comment]
lol, these keep propping up because mojang flipped the slot numbers between 1.7 and now
