### ISSUE TITLE
The Spectator not detecting objects in chests/on ground

### ISSUE THREAD

**Issue by Olontora** [Vazkii/Botania#2167]
I am using the latest version of the mod on the Direwolf20 1.10.2 Pack (Version 1.5.1). Forge should be updated to the latest version and I am not using optifine.

Bug:

The Spectator doesn't update when I am trying to use it. It doesn't show items in chests. If I throw something onto the ground then it does nothing until I unequip it and re equip it. Even then it is just the single object on the ground. Shifting with The Spectator also does not show everything around you. I had optifine installed but uninstalled it and reinstalled the pack without adding it just using the same save file and it still didn't work. I have mipmap levels at 0 if that even matters. Maybe it isn't updating as it should be so it can detect the objects around it. I really love The Spectator its quite helpful so I hope there is a fix and I am not just screwed lol.

I am also using the Curse Client instead of the legacy client. Doubt that that is relevant but still.

Latest Log: https://gist.githubusercontent.com/anonymous/ea284340b5e60d93ce3133b9b3bb1ff7/raw/70c653c7cd5413eabd9fd98e4a5e477b034980d1/FTB%2520Client%2520Log

Also quick question on the Direwolf20 1.10.2 pack. Holding shift to see more info about the item doesn't seem to work as it doesn't display any other information for me.

**Comment by williewillus** [comment]
Fixed in next version
