### ISSUE TITLE
[feature request]  Config to turn off each item

### ISSUE THREAD

**Issue by Zygus42** [Vazkii/Botania#2170]
Would be great to be able to turn off individual items that break certain world builds / economies.  Good examples of this are: Ring of Odin (because it's way OP for one item), Loonium (very OP depending on what mods add dungeon loot), Orechid (can break an economy easily or provide mod loot that is meant to be very rare).  But really, would be nice to have an on/off for each item.

**Comment by ArukaAlter** [comment]
You can easily remove or change recipes with Minetweaker, and there are plugins that can confiscate items.

**Comment by JRoffel** [comment]
From the contributing.md file: `Suggestions are not accepted here. Post them on the forums or reddit instead. If there's any still open they're old ones before this rule was added.`

Please read the rules before opening issues

**Comment by williewillus** [comment]
see previous 2 comments ^
