### ISSUE TITLE
Hitboxes not lining up with flowers

### ISSUE THREAD

**Issue by ShaunDreclin** [Vazkii/Botania#2172]
Botania version
r1.9-340

Modpack
All The Mods: Expert v1.0.24

See screenshot:
![screenshot 583](https://cloud.githubusercontent.com/assets/5851433/23102708/41e30a48-f67c-11e6-876e-1273c7a03e4c.png)

**Comment by quat1024** [comment]
I think this only happens with Optifine.

**Comment by ShaunDreclin** [comment]
Ahh weird. I do have optifine installed.

**Comment by quat1024** [comment]
I think, maybe both. Don't have time to do any testing right now, but maybe Optifine and Botania are using different random seeds (?)

I think this is mostly a bug on Optifine's side. Botania flowers extend `BlockFlower` just as they should and don't *appear* to be doing any other shifting.

**Comment by ArukaAlter** [comment]
Vanilla is the one that does the small random shift in any flower position.
I can't tell if this bigger shift is related with Optifine or not, can't reproduce.

**Comment by williewillus** [comment]
the hitbox not matching the visual shift is a vanilla bug fixed in 1.11
