### ISSUE TITLE
Narslimmus problem 

### ISSUE THREAD

**Issue by Hibik** [Vazkii/Botania#2176]
Nice to meet Vazkii.
My name is Hibiki.

The Narslimmus are not doing their job, the Slimes go over their range of action but do not absorb them.

![2017-02-20_15 59 58](https://cloud.githubusercontent.com/assets/25919315/23152128/10c967bc-f7bd-11e6-8005-e84934a6cdd8.png)

**Comment by williewillus** [comment]
working for me

your slimes need to be natural-spawned slimes, in a slime chunk. They can't be slimes spawned by a bigger slime after it dies.

**Comment by Hibik** [comment]
It's a natural-spawned slime in a slime chunk ;-;

**Comment by williewillus** [comment]
do you have a mod list? is this the latest version of botania?

**Comment by Hibik** [comment]
![afa](https://cloud.githubusercontent.com/assets/25919315/23189193/0a1668ba-f84f-11e6-8c4e-41e58280ac4a.png)

**Comment by Hibik** [comment]
Narslimmus work in Garden Of Glass, but not on a normal or super-flat map

**Comment by williewillus** [comment]
can you make it happen with botania alone?

**Comment by williewillus** [comment]
lack of update
