### ISSUE TITLE
[1.10.2] Server crash with Sponge

### ISSUE THREAD

**Issue by Wadimich** [Vazkii/Botania#2177]
Hello! Here is crashlog: http://pastebin.com/VzyHGjJM
I'm using forge 2221 and sponge 2177 with botania build 340

Happens frequently, around 2-4 times a day and i don't know, where is a problem

**Comment by yepidoodles** [comment]
I believe it's a Hopperhock causing the crash, so removing them may stop the crashes but I could be wrong.

**Comment by williewillus** [comment]
#2205
