### ISSUE TITLE
Incompatibility with RS Constructors

### ISSUE THREAD

**Issue by soerenkk** [Vazkii/Botania#2178]
I'm playing Sky Factory 3 (3.0.7) in a single player world.

I was trying to place a Hydroangeas with a Constructor from Refined Storage. The result of that is that there are placed an entity with the pink and black checkered pattern indicating broken texture. When I break it, i get an item with the name "Botania Flower", with the texture of red flower from vanilla Minecraft, the tooltip says "If you have this, it means something went wrong, you should report it".

Screenshot of the texture of the flower: http://imgur.com/a/ypUBq
I've tried multiple settings on the Refined Storage Constructor, no luck.

I cannot give you a log, since it haven't been generated, or it have been overwritten. The reproduction of this bug is described above.

**Comment by williewillus** [comment]
Fixed in next refined storage
