### ISSUE TITLE
Rod of the Unstable Reservoir targeting passive mob as hostile, from excessive distance

### ISSUE THREAD

**Issue by pjfranke** [Vazkii/Botania#2180]
When trying to fight Gaia, and use the Rod of the Unstable Reservoir to defeat the mob spawns, the missiles completely ignored the nearby mobs, and shot off towards spawn.  After the fight was over, this behavior continued.  I flew to spawn, confirming behavior hadn't changed occasionally.

Upon reaching spawn, the missles were targeting a single passive mob...a vanilla rabbit, even from >20 blocks away.  Once I got close enough, the missiles were able to reach the mob and kill it.  At this point, I was unable to use the rod anymore, as there were no more hostile mobs nearby.  Heading back towards my base and allowing hostile mobs to spawn, the rod functioned correctly again now that the rabbit had been defeated.

This was playing on Minecraft 1.10.2, FTB Skyfactory 3, version 3.0.6, with Botania r1.9-340, Forge 12.18.3.2215.  Confirmed that this was not just my player (though same client install), by using a 2nd account.  Reproduceable using a backup from prior to killing the evil rabbit.

**Comment by williewillus** [comment]
can't reproduce, is this rabbit from vanilla?

**Comment by pjfranke** [comment]
It turned out to be, yes.  I truly don't understand what data attribute it possessed that made it be targeted.  I can post the world save somewhere if you'd like so you can try to run it and see it for yourself.  It was a "vanilla" Sky Factory 3 instance.

![2017-02-27_19 10 38](https://cloud.githubusercontent.com/assets/8549006/23446223/15ef571a-fe07-11e6-97ea-7f9a8a409247.png)

**Comment by Tamaized** [comment]
Oh so it was singleplayer?

**Comment by pjfranke** [comment]
Sorry, no, I didn't mean to imply that.  It was on an SMP instance.  Being a skyblock instance, even with world exploration, the WORLD folder zips up to 15MB.  Since this was happening at spawn, it's easy for a new player to find the place this was happening, since that's where a new player will join in.

This was happening on the internet hosted server.  To confirm/troubleshoot, I downloaded a prior backup of the world folder, added it to a new local SMP instance running on my system, then joined my client to 127.0.0.1.  Confirmed it was still happening, and confirmed it happened still when logging in with a 2nd user account I have.

**Comment by Tamaized** [comment]
so a normal forge server, not a sponge based one, the ones that can use bukkit plugins?

**Comment by pjfranke** [comment]
Correct, as far as I see.  I confirmed the internet server is not using Sponge, nor is my test instance.

Server mods list:

ActuallyAdditions-1.10.2-r98.jar
actuallycomputers-1.0.0.jar
angelRingToBauble-1.10.2-0.2.1.12+45380c9.jar
AppleCore-mc1.10.2-2.1.0.jar
AppleShields-0.1.7.jar
AppleSkin-mc1.10.2-1.0.5.jar
autopackager-1.6.3 (1).jar
AutoRegLib-1.0-2.jar
baconators-1.10.2-3.0.5.jar
base-1.10.2-1.2.3.jar
Baubles-1.10.2-1.3.8.jar
bdlib-1.12.2.20-mc1.10.2.jar
BedBugs-1.10.2-1.1.4.jar
BetterBuildersWands-1.10.2-0.11.0.215+2d66774.jar
BetterFps-1.3.2.jar
BetterThanBunnies-1.10.2-1.1.0.jar
BiomeTweaker-1.10.2-2.1.230.jar
BlockDispenser-1.0-1.jar
BloodMagic-1.9.4-2.1.0-69.jar
Bookshelf-1.10.2-1.4.3.338.jar
Botania r1.9-340.jar
BrandonsCore-1.10.2-2.1.3.82-universal.jar
Ceramics-1.10.2-1.1.4b.jar
Chameleon-1.10-2.2.2.jar
ChanceCubes-1.10.2-2.3.4.171.jar
Charset-mc1.10.2-0.3.2-b6c6110f0942700e.jar
ChestTransporter-1.10.2-2.5.6.jar
ChickenChunks-1.10.2-2.2.0.52-universal.jar
chickens-4.3.2.jar
Chisel-MC1.10.2-0.0.7.7.jar
chiselsandbits-12.11.jar
ClientTweaks_1.10.2-1.1.16.jar
Clipboard-1.10.2-1.1.1.jar
Clumps-1.0.4.jar
CodeChickenCore-1.10.2-2.4.0.101-universal.jar
CodeChickenLib-1.10.2-2.5.2.198-universal.jar
ColossalChests-1.10.2-1.5.0.jar
CommonCapabilities-1.9.4-1.3.0.jar
compatlayer-1.10-0.1.7.jar
Controlling-1.0.3.jar
CookingForBlockheads_1.10.2-4.2.29.jar
CraftTweaker-1.10.2-3.0.17.jar
CustomMainMenu-MC1.10.2-2.0.2.jar
CyclopsCore-1.9.4-0.9.1.jar
DarkUtilities-1.10.2-1.1.6.105.jar
Decocraft-2.3.6.1_1.10.2.jar
DefaultOptions_1.10.2-6.1.5.jar
dimensionalcake-1.9.4-0.0.1.jar
Draconic-Evolution-1.10.2-2.0.7.168-universal.jar
DragonMounts-r46-1.10.2.jar
DrawersBits-1.10.2-0.35.jar
ElevatorMod[V.1.3.0][MC.1.10.2].jar
EnderCore-1.10.2-0.4.1.65-beta.jar
EnderIO-1.10.2-3.1.164.jar
EnderStorage-1.10.2-2.2.0.96-universal.jar
EngineersWorkshop-1.1.4-1.10.2.jar
environmentaltech-1.10.2-0.10.5i.jar
etlunar-1.10.2-0.10.5b.jar
ExCompressum_1.10.2-2.0.68.jar
exnihiloadscensio-1.10.2-0.1.12.jar
ExtraBitManipulation-1.10.2-2.3.1.jar
extrautils2-1.10.2-1.1.3d.jar
ExtremeReactors-1.10.2-0.4.5.24.jar
fairylights-2.0.6-1.10.2.jar
flatcoloredblocks-mc1.10-v4.4.jar
FluxNetworks-1.10.2-1.1.1.jar
foamfix-0.5.3-anarchy.jar
Forgelin-1.2.0.jar
FTBLib-1.10.2-3.2.3.jar
FTBUtilities-1.10.2-3.2.4.jar
FullscreenWindowed-1.10.2-1.4.0.jar
Funnels-1.10.2-1.1.2.jar
GardenOfGlass.jar
generators-0.9.20.19-mc1.10.2.jar
GooglyEyes-1.10.2-6.0.0.jar
GraveStone Mod 1.5.12.jar
Grue-1.9.4-1.3.4.jar
Guide-API-1.10.2-2.0.2-45.jar
Gyth-1.10.2-2.0.0.18.jar
HammerCore_1.10.2-1.2.3.jar
hatchery-1.10.2-0.2.7.jar
Headcrumbs-2.0.1.jar
hopperducts-mc1.9.4-1.4.8.jar
Hwyla-1.8.8-B22_1.10.2.jar
hydrogel-0.9.jar
ImmersiveEngineering-0.10-55.jar
InGameInfoXML-1.10.2-2.8.1.89-universal.jar
InitialInventory-1.0.1.jar
IntegratedDynamics-1.10.2-0.6.7.jar
IntegratedTunnels-1.10.2-1.1.0.jar
inventorysorter-1.10.2-0.10.5+46.jar
IronBackpacks-1.10.2-2.2.22.jar
ironchest-1.10.2-7.0.11.797.jar
ItsBecauseUHasNoGoodSpawn-1.0.5.jar
itsrainingfood-1.10.2-0.1.0.jar
jei_1.10.2-3.14.3.403.jar
journeymap-1.10.2-5.4.4.jar
KleeSlabs_1.10.2-3.3.5.jar
literalascension-1.10.2-1.0.0.4.jar
llibrary-1.7.4-1.10.2.jar
LongFallBoots - Hard Mode.jar
LootBags-1.10.2-2.3.2.jar
LunatriusCore-1.10.2-1.1.2.38-universal.jar
Mantle-1.10.2-1.1.4.jar
mcjtylib-1.1x-2.3.4.jar
MCMultiPart-1.3.0-universal.jar
Mercurius-1.10.2-1.0.2.jar
MineMenu-1.10.2-1.4.5-universal.jar
minicoal-1.1.0.jar
missing_pieces-1.10.2-4.1.3.jar
MoarSigns-1.10.2-4.2.2.8.jar
MobGrindingUtils-01814.jar
ModTweaker2-2.0.9.jar
MoreChickens-1.10.2-1.0.11.jar
MoreShearables1.2.1-1.10.2.jar
moreshears-1.10.2-1.0.2-release.jar
Morpheus-1.10.2-3.1.13.jar
MouseTweaks-2.6.4-mc1.10.2.jar
mpbasic-1.10.2-1.1.5.jar
mputils-1.10.2-1.2.5.jar
MTLib-1.0.1.jar
mysticalagriculture[1.10.2]-1.3.9.jar
natura-1.10.2-4.1.0.17.jar
Neat 1.3-12.jar
nice-0.1.0.jar
NotEnoughItems-1.10.2-2.1.3.199-universal.jar
notenoughwands-1.1x-1.5.3.jar
OpenComputers-MC1.10.2-1.6.1.6.jar
OreExcavation-1.2.84.jar
PackingTape-1.10.2-0.6.0.jar
Pam's HarvestCraft 1.9.4-1.10.2h.jar
platforms-1.10.0-1.2.8.jar
Psi-r1.0-42.jar
QuantumStorage-1.10.2-3.2.19.jar
RandomThings-MC1.10.2-3.7.7.jar
rangedpumps-0.3.jar
RebornCore-1.10.2-2.13.1.104-universal.jar
RebornStorage-1.10.2-1.0.0.25.jar
redstonepaste-mc1.9.4-1.7.4.jar
refinedstorage-1.2.18.jar
Reliquia-[1.10.2]-0.0.7.jar
ResourceLoader-MC1.9.4-1.5.1.jar
rftools-1.1x-5.82.jar
rftoolsctrl-1.1x-1.6.4.jar
rftoolsdim-1.1x-4.53.jar
roots-0.208.jar
SBM-WoodenShears-1.10.2-0.0.1b2-universal.jar
scanner-1.4.jar
ShadowMC-1.10.2-3.6.1.jar
shearmadness-1.10.2-1.4.1.jar
shetiphiancore-1.10.0-3.3.6.jar
SimpleAchievements-MC1.9.4-1.2.2-27.jar
simplebarrels-1.26e.jar
SimpleCorn1.10-1.2.1.jar
simplegenerators-1.10.2-0.10.5d.jar
simplelabels-1-10.2-0.0.2.jar
SimplyJetpacks2-1.10.2-2.0.3.26.jar
Snad-1.10.2-1.6.09.20a.jar
SolarFluxReborn_1.10.2-2.4r.jar
SonarCore-1.10.2-3.2.1.jar
StevesCarts-1.10.2-2.1.0.62.jar
StorageDrawers-1.10.2-3.5.17.jar
SuperCircuitMaker-1.0.4.jar
Surge-1.10.2-1.1.0.66.jar
TConstruct-1.10.2-2.6.2.jar
The Beneath-1.10.2-1.2.0.jar
TinkerToolLeveling-1.10.2-1.0.1.jar
tinyprogressions-1.10.2-1.0.19.jar
torchmaster_1.10.2-1.1.0.11.jar
Translocators-1.10.2-2.1.3.51-universal.jar
TS2K16-1.0.3.jar
Twitchcrumbs_1.10.2-2.0.4.jar
UniDict-1.10.2-2.5c.jar
valkyrielib-1.10.2-0.10.5f.jar
voidcup-1.10.2-0.0.1.jar
Waddles-1.10.2-0.5.0.jar
WanionLib-1.10.2-1.3.jar
Wawla-1.10.2-2.3.1.214.jar
witherCrumbs-1.10.2-0.9.jar
xprings-1.10-1.3.0.jar
YUNoMakeGoodMap-1.10.2-6.1.0.26.jar
zerocore-1.10.2-0.1.0.1.jar
[1.10.x]FenceOverhaul-1.2.1.jar

**Comment by Tamaized** [comment]
The only possible thing I can think of after looking through the code is that some mod SOMEHOW is messing with the data manager for the EntityMagicMissile TARGET but I highly doubt it. But yea, it's possible.

**Comment by pjfranke** [comment]
If I did this right, this should allow the zipped world folder to be downloaded:
https://mega.nz/#!Dx11XCRL!u_uKoVvBV9CC4639h96JDfwnR-I9LIWOl6riJvfj2-M

Unzip the server download from here:
https://www.feed-the-beast.com/projects/ftb-presents-skyfactory-3/files/2373070

Unzip the world.zip into the FTBPresentsSkyfactory3Server_3.0.6 folder, then run the ServerStart.bat script, and it should launch a local instance.

There is a chest right next to the spawn location with a creative mana tablet, Rod of the Unstable Reservoir, and a Flugel Tiara, so anyone who wants to duplicate this doesn't even need to be OP.

I just tested with a clean install of Skyfactory 3.0.6 to a new instance via Curse, to make sure there wasn't something goofy in the install instance I've been playing on.  Still happens.

**Comment by pjfranke** [comment]
I captured and uploaded an example of the issue.  Here I actually created a new /mods folder for the server and clients, and copied only the Botania, Baubles, and BetterThanBunnies jars into the folder.  AFAIK, BetterThanBunnies is a client-side only mod, that visually puts hats on the rabbits. It should not actually affect their data.

When confirming the issue, this time it actually targeted a chicken, not a rabbit.  When I re-copied the World folder, removed BetterThanBunnies from client and server, and tested again...it still had the issue, but with a _different_ chicken.

https://youtu.be/ALQpzdP0T8c

Mod list during that last test:

![modlist-botania debugging](https://cloud.githubusercontent.com/assets/8549006/23467351/685e9d4c-fe63-11e6-8481-ffc44ab39bc1.png)

**Comment by cleverca22** [comment]
potentially related? http://minecraft.gamepedia.com/Rabbit#The_Killer_Bunny

**Comment by Doragoon01** [comment]
I had this happen too.  The rod was trying to target a villager in my potato farm even from hundreds of blocks away.  Not wanting to kill the villager, i picked up the villager in a capture wand from Not Enough Wands.  The rod went back to working normally.  I placed the villager back in his potato patch and so far the wand is still working.

I'm playing on a server running MC1.11.2, Forge 2296, Botania r1.9-343
