### ISSUE TITLE
Crash to desktop when clicking Respawn after dying from Magic when fighting Gaia Guardian

### ISSUE THREAD

**Issue by pjfranke** [Vazkii/Botania#2181]
When fighting the Gaia Guardian, if I am unsuccessful and die from Magic (the wither effect), I am experiencing a crash to desktop.  I can die from other methods, and not experience this crash.  I have switched to Terrasteel armor, which helps me be more successful with the fight compared to other armor, but dying still results in this crash.

This was playing on Minecraft 1.10.2, FTB Skyfactory 3, version 3.0.7, with Botania r1.9-340, Forge 12.18.3.2234.

http://pastebin.com/BaSsuset

**Comment by williewillus** [comment]
Is this on a sponge server?

**Comment by Tamaized** [comment]
haha, I asked the same thing on discord. Unsure still though.

**Comment by NicosaurusRex99** [comment]
@williewillus does botania not like sponge or something?

**Comment by williewillus** [comment]
Not specifically, but I've been noticing a pattern

**Comment by pjfranke** [comment]
Negative, not Spong.

**Comment by williewillus** [comment]
also is this crash on dying or on respawning?

**Comment by pjfranke** [comment]
That's a great question, I was incorrect in my initial post.  I can see the death message, and it's only upon hitting the "respawn" button that it crashes.

**Comment by williewillus** [comment]
#2205
