### ISSUE TITLE
Rannucarpus induced crash on placing sticky piston

### ISSUE THREAD

**Issue by DanNetwalker** [Vazkii/Botania#2182]
Sticky pistons (minecraft:sticky_piston) placed by Rannucarpus doesn't have a value for it's property PropertyDirection. A valid value should be applied to prevent a crash.

How to reproduce: prepare a working Rannucarpus and toss a sticky piston to the plant.

Example log: http://pastebin.com/MhRiqv8D

**Comment by williewillus** [comment]
I blame vanilla for giving me back an invalid meta >_<
