### ISSUE TITLE
Redstone Power does not disable Floating Marimorphosis

### ISSUE THREAD

**Issue by ntseng** [Vazkii/Botania#2184]
![2017-03-04_09 37 40](https://cloud.githubusercontent.com/assets/6503151/23580853/5170fbae-00be-11e7-9dab-15d8340a231f.png)

**Comment by CJOak** [comment]
Try feeding redstone dust directly into it. I can't test right now, but it may have to do with Redstone blocks only giving off weak signal.

**Comment by ntseng** [comment]
Tested with levers and redstone dust and marimorphosis kept going. It isn't just redstone blocks being weird.

**Comment by williewillus** [comment]
b044c98
