### ISSUE TITLE
[1.11.2] Mana Enchanter only puts 1 enchantment on items

### ISSUE THREAD

**Issue by Yoghurt4C** [Vazkii/Botania#2188]
Mana Enchanter doesn't seem to check for more than one book.

built from https://github.com/Vazkii/Botania/commit/f369c9ee55e2e3d2738df533a86f120bf3ceda29
Forge: 2252

**Comment by ArukaAlter** [comment]
It will be done in due time, asking will probably just get Vazkii angry.

**Comment by williewillus** [comment]
#2189
