### ISSUE TITLE
Lexica Botania missing flowers

### ISSUE THREAD

**Issue by dabigmoose** [Vazkii/Botania#2190]
Wento to the Lexica in SF3.0.8 and noticed seems to be missing stuff like kekimunos and several others.  I notice they are in JEI just not the lexica which has several just not all, missing solomundos? Sorry on spelling I am at office.

Minecraft 1.10.2
Forge 2254
Botania r1.9-340

Just wanted to make you aware.

**Comment by ArukaAlter** [comment]
They are under Elven Knoledge, not availabe in the manual until you open the portal.
