### ISSUE TITLE
Botania 1.9.342, Minecraft 1.11, Storage Drawers 4.2 [Compability]

### ISSUE THREAD

**Issue by knord1** [Vazkii/Botania#2192]
Comapability issues.

Storage Drawers are not behaving correctly with Botania installed.

Drawers are rotated incorrectly.
Locked/void drawer info is not shown.
Right Click to insert places a block in the world before inserting in drawer.
shift-right click to show content of drawer only shows max a stack amount of 64.

Forge *.2233
Minecraft 1.11.2
Storage Drawers 1.11.2-4.2.0
Chameleon 1.11.2-3.0.2

**Comment by ArukaAlter** [comment]
There was a "Botania for 1.11 will not have any support yet" warning next to the download.

**Comment by knord1** [comment]
Ouch. That information is not available in the course app.
Thank you for the quick response.

**Comment by williewillus** [comment]
The one released on twitter is not supported by iirc the one on curse is. 
I'm not sure what these issues are coming from though, botania doesn't make sweeping interaction changes.

**Comment by knord1** [comment]
I posted same bug report to storage drawers.
Could be a forge feature that behaves inconsistent.

**Comment by codewarrior0** [comment]
ref: https://github.com/jaquadro/StorageDrawers/issues/443

**Comment by knord1** [comment]
Seems to work with Forge 13.20.0.2255
