### ISSUE TITLE
Placing of the Marimorphosis flower crashed a server

### ISSUE THREAD

**Issue by jc2xs** [Vazkii/Botania#2197]
Vazkii,

Keep up the good work.  I'm hopping you can use this info.  One of my players placed the Marimorphosis flower in the Beyond server I'm running.  This is a pure forge server running the 1.1.0 version of the pack from the FTB team.  No modifications were made to the pack except to re-enable the default PSI recipes.

Crash report from server:  http://paste.feed-the-beast.com/view/683d979c

**Comment by williewillus** [comment]
...shit >_>
missed a % on this line and the numbers were small enough in dev 
https://github.com/Vazkii/Botania/blob/master/src/main/java/vazkii/botania/common/block/subtile/functional/SubTileMarimorphosis.java#L91

**Comment by williewillus** [comment]
fixed and also cherrypicked the fix to 1.10
idk how long until the next build comes out but mari's are pretty much broken until then, I'm so sorry T_T

**Comment by williewillus** [comment]
@jc2xs for now, in `forge.cfg` enable the "remove erroring tile entities" option, start the server to delete the mari, then set the option back to false

**Comment by jc2xs** [comment]
Thanks williewillus, I had already implemented that fix and my player trashed the flower.  So my server was already running when I made the report.  I just wanted to make sure you and Vazkii were made aware of the issue.  And I'm truly impressed with the response.  So I'm glad my bug report helped!

**Comment by phit** [comment]
is this ever gonna be released for 1.10.2?

**Comment by Nicholaiii** [comment]
This is still a problem

**Comment by richard-hajek** [comment]
Hello, to anyone encountering this issue, this is the fixed version. Note that you have to **unzip it first**. Only once (ie do not unzip the jar).

[Botania r1.9-342.zip](https://github.com/user-attachments/files/18219756/Botania.r1.9-342.zip)

Replace your 'Botania r1.9-341.jar' with this 'Botania r1.9-342.jar'. Both on server and on clients and enjoy!

---

If you would rather compile it by yourself follow these commands, a Linux, wget, git, Java 8, is necessary.
```
git clone https://github.com/VazkiiMods/Botania
cd Botania

# Change version to 1.10
git checkout 1.10-final

# Download some other mod this one needs
# I don't know
wget https://mediafilez.forgecdn.net/files/2375/820/Baubles-1.10.2-1.3.9.jar -O Baubles-deobf.jar

# I don't know
cp private.properties.example private.properties

# Compile the mod
./gradlew build

# The final mod will be stored here
ls "build/libs/Botania r1.9-342.jar"
```
