### ISSUE TITLE
Crash when harvesting grass with water in Botania/GoG 1.11.2

### ISSUE THREAD

**Issue by JumpyDragon** [Vazkii/Botania#2198]
Using a bucket of water on grass to clear it/harvest seeds causes a crash to desktop in Botania Garden of Glass 1.11.2

[crash-2017-03-12_19.20.50-server.txt](https://github.com/Vazkii/Botania/files/837026/crash-2017-03-12_19.20.50-server.txt)

Using Baubles-1.11-1.4.3, Botania r1.9-342, and GardenOfGlass

**Comment by williewillus** [comment]
forge bug, see https://github.com/MinecraftForge/MinecraftForge/pull/3778
