### ISSUE TITLE
Space in filename

### ISSUE THREAD

**Issue by C0rn3j** [Vazkii/Botania#2200]
Hi, this mod is one of the few that have a space in the filename, would you consider replacing it with an underscore? Thanks!

http://i.imgur.com/A4KSJQI.png

It breaks my program, which I'm planning to fix, but I think it'd be better if mods had consistent naming too ^^

**Comment by Tamaized** [comment]
Tbh, it's on the program author to handle these kinds of cases, shouldn't really need to restrict others to use a specific format.

**Comment by C0rn3j** [comment]
I agree! I just put it up here for consideration, as it'd avoid having people to work around it.

Out of the 161 mods I have for 1.10.2 only 8 of them have a space in the file name, of which 1 seems to have tried and missed one space.

**Comment by C0rn3j** [comment]
Looks like this naming suggestion is not very popular with mod authors, so I'll just close this here.
