### ISSUE TITLE
GoG - Breaking tall grass doesn't drop melon or pumpkin seeds.

### ISSUE THREAD

**Issue by sdaddy** [Vazkii/Botania#2201]
1.11.2 Botania r1.9-342 & GoG
Forge: 13.20.0.2259

Used over 2 stacks of bonemeal and have yet to get a single pumpkin or melon seed. I'm hoping this is a bug and I don't have the worst luck in the world.

**Comment by williewillus** [comment]
Forge bug (https://github.com/MinecraftForge/MinecraftForge/pull/3778)
