### ISSUE TITLE
[1.10.2] Loonium not dropping EnderIO loots

### ISSUE THREAD

**Issue by Xiaminou** [Vazkii/Botania#2202]
I tried to get some of the EnderIO capacitors using the Loonium but none of EnderIO's loots are dropping from it.
Here is what's dropping from it:
![2017-03-16_17 18 00](https://cloud.githubusercontent.com/assets/8670392/24006577/87e47f46-0a6c-11e7-83e5-842b1d84c3d9.png)

Minecraft: 1.10.2
Mods: [list.txt](https://github.com/Vazkii/Botania/files/848329/list.txt)

**Comment by williewillus** [comment]
it just uses the dungeon loot table, so check if they're showing up in dungeon loot. I have no idea otherwise

**Comment by williewillus** [comment]
^ and closing from staleness
