### ISSUE TITLE
Help? (SOLVED)

### ISSUE THREAD

**Issue by Gold3nOcean** [Vazkii/Botania#2203]
Whenever i try to play minecraft with the Botania Mod My screen Shows This: 
![20170316222528_1](https://cloud.githubusercontent.com/assets/26490293/24056324/42e2fd3c-0b11-11e7-81d4-ef865d8a3b1f.jpg) Also. when i try to play. i can only see 1 quarter of my screen... can you help?

**Comment by Tamaized** [comment]
Possible mod conflict, could be optifine, could be the texture pack. start removing things one by one to find the issue. (leaving botania in ofcourse)

**Comment by Gold3nOcean** [comment]
Thanks It Did Work! I Am Going To Miss Having Smooth FPS...
