### ISSUE TITLE
[1.11.2] Weird Metamorphic Mesa Cobblestone Recipe

### ISSUE THREAD

**Issue by ThomasAunvik** [Vazkii/Botania#2204]
![Weird Mesa Cobblestone Recipe](http://i.imgur.com/lpJGoz7.png)

Botania Version: r1.9-324
Forge Version: forge-13.20.0.2259
JEI version: 4.2.10.248

**Comment by williewillus** [comment]
is this with botania alone? there may be other mods that auto-scan recipes and add their own

**Comment by ThomasAunvik** [comment]
This is not botania alone, and Quark is installed.

**Comment by ThomasAunvik** [comment]
Found this at Quark: Slabs to Blocks.

**Comment by Vazkii** [comment]
Yes, this is a minor quark bug. The recipe itself only needs 1 though.

**Comment by williewillus** [comment]
not a botania issue then
