### ISSUE TITLE
Garden of Glass - No Way to get Mushrooms

### ISSUE THREAD

**Issue by ShadowDrakken** [Vazkii/Botania#2206]
Unless I'm completely missing something, the only way to get mushrooms in Garden of Glass is via the Nether. Unfortunately, this requires obsidian. Which requires blaze rods via the Cocoon of Caprice. The Cocoon requires a Fel Pumpkin, which needs a vanilla Pumpkin, which can only be gotten through the Alchemy Catalyst as it doesn't appear to drop from grass in the 1.11 version. This wraps back around to needing Blaze rods again to craft the Brewing Stands...

So either I'm missing a lava source, or I'm missing a pumpkin seed source, or there's a hole in Garden of Glass that needs repaired :\

**Comment by williewillus** [comment]
forge bug with the pumpkin drops https://github.com/MinecraftForge/MinecraftForge/pull/3778
