### ISSUE TITLE
Baubles equipped by right-click get destroyed if slots they can go in are occupied

### ISSUE THREAD

**Issue by Hubry** [Vazkii/Botania#2208]
Botania-added baubles are destroyed whenever you try to equip one, but all slots they can go into are already full. This does not happen with the Miner's Ring from Baubles.

How to reproduce:

- Equip any two rings. Make sure you're in survival.
- Right-click with the Miner's Ring from Baubles. Notice it stays in your hand.
- Right-click with any ring from Botania. It disappears, relogging doesn't seem to make it reappear.

Using Minecraft 1.11.2 Forge 13.20.0.2259, Baubles 1.4.3, Botania R1.9-342.

**Comment by williewillus** [comment]
I fixed the main issue you described, but I sometimes can get all baubles to disappear when clicking really rapidly. Not sure if it's a botania issue but I think it's a baubles one. And it's unrelated to this ticket anyway.
