### ISSUE TITLE
Game Crash when loading all my mods (NoSuchMethodError: ......RenderBlocks;)

### ISSUE THREAD

**Issue by felix0111** [Vazkii/Botania#2211]
I want to make a big modpack out of more than 200 mods. I decided to to try something new with the mod Botania but I couldn't get the game to work. Everytime the game loads (right after it's done with "Loading - Initializing mods Phase 2") the game closes and give me the crash report. 

First I had Optifine installed but when I removed it, it changed nothing. I also changed nothing in the config or so.

Here is the pastebin: http://pastebin.com/ejLqGnQs

Minecraft Version: 1.7.10
Mods Loaded: around 200
Botania: r1.8-249
Forge: 10.13.4.1558
FML: 7.10.99.99
Java: 1.8.0_25
Operating System: Windows 7
System Memory: 8Gb
RAM given to Minecraft: 7Gb (I know it's a bit too much to give 7 out of 8 Gb)

**Comment by williewillus** [comment]
1. check if it's actually botania that's causing this
2. try updating for to the latest 1.7 (1614)
3. 1.7 isn't supported anymore
