### ISSUE TITLE
[1.10.2] Gaia Guardian II Boss Fight not ending properly [v340]

### ISSUE THREAD

**Issue by AceologyGaming** [Vazkii/Botania#2213]
Upon killing Gaia II, the arena (pink border) doesn't go away, music continues to play, and flight is still disabled. This isn't a one off, happened 4x in a row.
![2017-03-23_20 18 39](https://cloud.githubusercontent.com/assets/25800778/24268514/ebabac68-1005-11e7-9aca-88efccf60c65.png)

**Comment by AceologyGaming** [comment]
Also like to add that when you jump up too high while it's like this, you bounce up and down in midair, from which you must tp out.

**Comment by williewillus** [comment]
can't reproduce

can you make it happen with botania alone?

**Comment by AceologyGaming** [comment]
Ah. It's a bug when morphed as the Gaia Guardian using Metamorph.
