### ISSUE TITLE
Wand of the Forest changes mode when rotating blocks

### ISSUE THREAD

**Issue by ShelLuser** [Vazkii/Botania#2215]
One of the features of the wand of the forest is to rotate blocks around (like chests). However, when I sneak-right-click on the chest it both rotates but _also_ changes the mode of the wand. I was under the impression that this should only happen when sneak rightclicking in the air.

I'm using the latest version (Botania r1.9-342) on Minecraft 1.11.2.

**Comment by ktole1999** [comment]
and you confirmed the key bind was not set for mode change?

**Comment by ArukaAlter** [comment]
Botania has no keybinds. The check needs to be revised.
