### ISSUE TITLE
Suggestion: shift vs. sneak

### ISSUE THREAD

**Issue by ShelLuser** [Vazkii/Botania#2216]
When you hold the Lexica in an active hand while looking at some items then it will show an icon saying "shift" below it, this is to indicate that you'll get more information when sneaking.

The problem is: not everyone will have the shift key associated with the sneak function, for example I use ALT myself, and then pressing shift will do absolutely nothing.

As such my suggestion: don't mention keys but functions unless you've really bound them (like with the control key when hovering the mouse over a Botania item). So instead of mentioning "shift" use "sneak" instead.

**Comment by TheWhiteWolves** [comment]
Better option is actually to get the current keybind and display that
