### ISSUE TITLE
Endoflames trying to burn unburnable items crashes game

### ISSUE THREAD

**Issue by Rocco155** [Vazkii/Botania#2219]
Whenever I drop accidentally something not burnable near my Endoflame Manafarm, the game crashes. It happened quite a few times and in this case it was probably a snowball. Also after I installed Botania the same happens with a normal furnace, if I put something unburnable in the "to  burn" slot, the game crashes. From the crashreport it seems like Endoflames count as furnaces and it fails to get the burn time for unburnable stuff.
Here is the crashreport: https://hastebin.com/ujomegocur.coffeescript

**Comment by Rocco155** [comment]
Btw. I tried updating from version 339 to 341 but still the same thing occurs.

**Comment by williewillus** [comment]
The crash is in ic2 code, botania is just calling the standard forge method to get burn time

**Comment by Rocco155** [comment]
Oh thank you, good to know. Sorry for blaming botania then... time to deinstall ic2, huh? .... but then I can't join my second favorite Server... mmhhmm, well, at least I know now what to watch out for.

**Comment by williewillus** [comment]
just report it to ic2
