### ISSUE TITLE
Gaia Guardian "easy kill"

### ISSUE THREAD

**Issue by Winter** [Vazkii/Botania#2222]
When using the Draconic Bow, if you spawn Gaia (1 or 2) and not move, you can kill it within seconds bypassing the invincible event where mobs spawn.

Minecraft Version 1.10.2
Version: r.19-341
Forge: 12.18.3.2254
FML: 8.0.99.99
Optifine: True
Draconic Evolution Version: 2.0.8.177

**Comment by williewillus** [comment]
I think anything with that mod is out of the "balance" question lol.

Doesn't it deal damage by manually setting health instead of actually dealing damage?
