### ISSUE TITLE
Cannot bonemeal buried petals to grow tall flowers [1.11.2]

### ISSUE THREAD

**Issue by Cal26lum** [Vazkii/Botania#2224]
Petals buried in dirt/grass cannot be grown into the two tall flowers with bonemeal as they should be. They are still able to be planted.

MC - 1.11.2
Botania - r1.9-342

**Comment by williewillus** [comment]
seems to work for me

**Comment by williewillus** [comment]
does it happen w botania alone?

**Comment by llorelei** [comment]
I am having this same issue - Minecraft 1.11.2 Botania r1.9-342 - I'm playing it as part of the All the Mods 2 pack. I can plant the petal and it emits particles in the ground and then the green particles when I hit it with bonemeal, but the flower itself doesn't actually grow.

**Comment by williewillus** [comment]
let us know if you find out which mod it is and if it's possibly botania's fault
