### ISSUE TITLE
Crash after opening a crashed save

### ISSUE THREAD

**Issue by AsmodeiXIII** [Vazkii/Botania#2225]
https://paste.ee/p/Gpg70

My game crashed, probably for some issue unrelated to your mod, however, opening that save again seems to make it crash again, and this time, the crash seems to be related to your mod.

https://paste.ee/p/GEk1W
First crash, in case you want to take a peek. Like i said, this one doesn't seem to be related, but every crash after does.

**Comment by williewillus** [comment]
links broken
