### ISSUE TITLE
Crash while breaking a Redstring container

### ISSUE THREAD

**Issue by Kinomora** [Vazkii/Botania#2226]
Attempting to connect a redstring container to a Quantum Storage Unit 2 blocks below it in Sky Factory 3 (worked) but could not attach Item Translocators to it, so I went to break it using a Tinkers' Construct pickaxe and got this crash.
Error given was: "Error: java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[down, up, north, south, west, east]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}"

Full crash report:
[https://pastebin.com/hQMmri8Y](https://pastebin.com/hQMmri8Y)

**Comment by Tamaized** [comment]
#2205

**Comment by williewillus** [comment]
^
