### ISSUE TITLE
Try to place floating endoflame with unbreakable wand, but just botania flower placed

### ISSUE THREAD

**Issue by ZZaphodd** [Vazkii/Botania#2227]
probably it's not a botania problem
![image](https://cloud.githubusercontent.com/assets/8099421/24576029/38f3d7b2-16ef-11e7-9134-ac9f57b94116.png)
![image](https://cloud.githubusercontent.com/assets/8099421/24576033/46c5d5c0-16ef-11e7-9567-ee48ee82abea.png)

modpack : FTB skyfactory 3
Botania r1.9-339
Better builder's wands 0.9.3

**Comment by yrsegal** [comment]
This would probably be a problem with better builder's wands, not botania.

**Comment by williewillus** [comment]
^ it needs to call `ItemBlock.placeBlockAt` properly
