### ISSUE TITLE
[1.10.2] (Blood Magic) Dagger of Sacrifice, (Botania) Golden Laurel Crown and (GraveStone) GravestoneInteractions

### ISSUE THREAD

**Issue by SyncStelar** [Vazkii/Botania#2230]
When wearing the Golden Laurel Crown and shaving yourself in front of the altar using the Dagger of Sacrifice, the player can "die" from stabbing himself too much without triggering a death event. This causes the player to lose everything the player owns and two of the Golden Laurel Crown message that tells the player have died and is saved.

**Comment by Tamaized** [comment]
#2099

**Comment by williewillus** [comment]
^ and also the laurel is removed in 1.11 anyways in favour of the totem
