### ISSUE TITLE
The snowflake pendant turns oil, crystallized oil, and empowered oil from Actually Additions to ice

### ISSUE THREAD

**Issue by PapiDimmi** [Vazkii/Botania#2236]
The snowflake pendant is supposed to turn water into ice, but it also turns all types of oil from Actually Additions to ice, which disrupts my automatic canola oil system.

If this can’t be fixed, a flower could be added that disrupts the snowflake pendant, similar to the solegnolia. A flower like this would also be very useful in farms, where water turns to ice when the water is needed to hydrate the farmland.

I also posted this on Actually Additions’ GitHub page: Ellpeck/ActuallyAdditions/issues/739

**Comment by williewillus** [comment]
actually a vanilla/forge thing, the snowflake pendant just calls the frost walker code :P

**Comment by PapiDimmi** [comment]
I assumed so. It’s really annoying, though.

Like I said, it’d be very nice if there were a flower similar to the solegnolia which disrupts the snowflake pendant in an area around the flower, so that I can protect my canola oil system as well as my farms.

**Comment by williewillus** [comment]
fixed in forge
