### ISSUE TITLE
[Suggestion] Mana number

### ISSUE THREAD

**Issue by PapiDimmi** [Vazkii/Botania#2237]
Rather than just a bar, add a number displayed when looking at mana pools and in the tooltips of mana tablets—so you know exactly how much mana you have.

**Comment by ArukaAlter** [comment]
This is a thing that wasn't added on purpose and will not be added.

**Comment by SquidDev** [comment]
[Stuff you won't see in Botania](http://vazkii.us/p/stuff-you-wont-see-in-botania/) provides some rational behind this. It's rather old, but I'm pretty sure it still holds true today:

> Numbers must exist. Their existence is unavoidable, in fact, you can dig into the code or a wiki and find them all spread right there like one of your French girls. However, in Botania I decided to go on an approach where you don’t see the raw numbers? Why? To encourage experimentation. Spreaders also change their output depending on distance for that same objective. It also has an objective which I find incredibly important, which is a stopgap on the urge to minmax the game. For those unfamiliar, “minmaxing” refers to the act of making sure every little number is the exact optimal value for the situation, which in leads to people actively trying to make sure they’re getting the most out of their generation, conduction, etc. I don’t want to do that with botania, I’d rather people just play with the mod rather than try to math it through.

**Comment by PapiDimmi** [comment]
Oh, well, that sucks.
