### ISSUE TITLE
The Wand of the Forest can rotate Command Blocks in Survival

### ISSUE THREAD

**Issue by Hubry** [Vazkii/Botania#2239]
Simple - shift right-clicking a Command Block with the wand rotates it in any gamemode other than Spectator, with or without access to commands. Probably not ideal, because they're meant to be completely inaccesible to people other than ops in creative.

To reproduce: place any command block, shift right-click with the wand on face with the arrow visible.

Using Minecraft 1.11.2, Forge 13.20.0.2279, Baubles 1.4.3, Botania R1.9-342.

**Comment by yrsegal** [comment]
A possible solution: Blacklist the rotate behavior if hardness < 0?

**Comment by williewillus** [comment]
iirc there's a canPlayerEdit in World
