### ISSUE TITLE
MD5 incorrect

### ISSUE THREAD

**Issue by arcadymtr** [Vazkii/Botania#2240]
Botania [Botania r1.8-249.jar] MD5 signature is not correct. currently reported:
```757cfb6db285068b617c382fc7a1e9ed```

here the proper checksum:
```
MD5 Checksum: 2339512F8028A1D6908EBE1FBBA01BDA
SHA-1 Checksum: 4284E4EF9171D1EDCEF227E7A866865195A79BCD
SHA-256 Checksum: 3E615960748600EE43E6CE71932B8CAC9B7E0BBD020192E4EFFFFB279A1C2745
SHA-512 Checksum: D3628116E0C2AAAE9BA1035E5CFBFB66BC3C62A00BE37ACD8063E0E34B52861DA5B8728518D91E3120350BFC57A261440E78761824F797EDF0BDB9AAC1B0812D
```

take your time, but please fix the issue.
on the contrary, i'm not gonna download your software.

thanks for your attention.

_reference: https://minecraft.curseforge.com/projects/botania/files/2283837_

**Comment by williewillus** [comment]
1. this isn't an issue with botania, curse manages all that
2. wherever you got your jar from is wrong because the jar I get from curse matches the hash:
```
>certutil -hashfile "Downloads\Botania r1.8-249.jar" MD5
MD5 hash of file Downloads\Botania r1.8-249.jar:
757cfb6db285068b617c382fc7a1e9ed
CertUtil: -hashfile command completed successfully.
```

**Comment by arcadymtr** [comment]
thanks for your anwser. i will download the file again.
