### ISSUE TITLE
If dropping a lot of items from the open crate, some of the items are not dropped directly below the open crate

### ISSUE THREAD

**Issue by PapiDimmi** [Vazkii/Botania#2241]
![2017-04-10_16 40 04](https://cloud.githubusercontent.com/assets/25916106/24867140/8fd9c1d0-1e0c-11e7-90ab-baf436d1bdc4.png)

The items are supposed to land on the pressure plate, but some of them landed beside it.
****
**Minecraft version**: 1.10.2
**Botania version**: [r1.9-341](https://minecraft.curseforge.com/projects/botania/files/2391169)

**Comment by williewillus** [comment]
what do you mean by a lot? how are you feeding it?

**Comment by williewillus** [comment]
tested with five hoppers going into a single crate, everything seems to work still

**Comment by PapiDimmi** [comment]
I’m feeding it with a crafter from Refined Storage.

**Comment by legodude17** [comment]
What did you request to be crafted?

**Comment by PapiDimmi** [comment]
I figured it out. My Ring of Magnetization was interfering with my setup. It has nothing to do with the crafter or open crate.

I _did_ have a Solegnolia flower underneath my setup, but it appeared as though it range wasn’t large enough, so I had to make another one.
