### ISSUE TITLE
[1.10] Cannot place spark on Mana Enchanter

### ISSUE THREAD

**Issue by Hydrokinetic** [Vazkii/Botania#2244]
Right-clicking a spark on a mana enchanter block does not place the spark on the block. Other blocks, such as the terrestrial plate and regular mana pools, have no issues with spark placement. The enchanter will still receive mana from spreaders, but not from the sparks on adjacent pools, since the enchanter doesn't have its own spark.

**Comment by williewillus** [comment]
fixed in 1.11. for now, use a shift right click to get it on there
