### ISSUE TITLE
Botania 1.9-341 - Weird hovering hourglass behavior

### ISSUE THREAD

**Issue by cake-master** [Vazkii/Botania#2248]
![2017-04-21_19 17 33](https://cloud.githubusercontent.com/assets/27862451/25286680/47a685ec-26c7-11e7-81b0-4f1919486c6f.png)
In this configuration the mana from the pulse mana spreader passes through the hourglass, not triggering it (hourglass contains 1 mana powder, and no redstone pulse is created by the hourglass), although usually passing through leaves doesn't affect the mana pulse.
![2017-04-21_19 17 49](https://cloud.githubusercontent.com/assets/27862451/25286679/47a057e4-26c7-11e7-8906-3651c69bb43a.png)
In this configuration (nothing changed except for the leaves being removed), the hourglass detects the mana pulse as expected.
This wasn't mentioned in the changelog for the next release, I am running the FTB Beyond 1.5.3 pack for 1.10.2, which uses Forge 12.18.3.2254.

Log: https://gist.github.com/cake-master/eaa680bdd2f020448e8556d26785da53

Edit: I wasn't able to replicate this in any other configuration of the hourglass, leaves and mana spreader, only in the one pictured.

**Comment by williewillus** [comment]
this seems like a byproduct of the vanilla impact code. It only triggers an "I hit a block" event if it passes from airspace into a solid block. Even though the burst itself ignores the leaf block, if the angle is setup such that there is no air gap between the leaf and hourglass' bounding box it won't hit. Not sure how to get around it without copypasting vanilla code and editing it
