### ISSUE TITLE
Using the Mana Enchanter locks up my game every time I try to interact with it

### ISSUE THREAD

**Issue by CryinMo** [Vazkii/Botania#2253]
I am using Botania r1.9-343 and this is the first time I've built a mana enchanter. I built it, hooked up a mana pool to it and dropped a diamond axe (partially used) on the enchanter. All the pylons light up, etc. but when I right click on the enchanter or break any block incorporated in the enchanter build (flowers, pylons, dirt, obsidian), the game stutters to 5 fps and then locks up. I had to force quit it about 20 times trying to figure out what exactly was causing it, but it just seems to be the enchanter itself. If I don't touch it, it just keeps up with it's particle effects and does nothing else, but if I interact with the enchanter at all, it crashes the game.

I did create a new world from scratch, built a mana enchanter, put in a diamond axe (I have not tried a different item) and then broke a block, and the same thing happened. So, it might just be that when the enchanter is not done (like the green progress wheel is not finished) that this is when the game crashes if the enchanter is broken. Just trying to supply as much info as possible.

Also, I am playing Minecraft 1.11.2 with Forge 1.11.2-13.20.0.2228 on a Mac.
FML Log: https://pastebin.com/W27staA3

EDIT: I have now determined that this issue only happens when interacting with the mana enchanter while it is building up mana/processing an item. Once the item is done, there is no issue with breaking any of the blocks in the mana enchanter, etc.

**Comment by williewillus** [comment]
yeah, not sure what that code was doing :P
