### ISSUE TITLE
[1.11.2] Up to quadrupling mana pool recipe gains

### ISSUE THREAD

**Issue by Aphyxia** [Vazkii/Botania#2254]
Steps to reproduce:
1) Line up 4 mana pools with mana in a square formation next to each other.
2) Drop 1 iron ingot right in the middle of the 4 mana pools.
3) Result: 4 manasteel ingots.

Haven't tried with alchemy catalyst, etc. but I reckon it works the same.

Forge: 2282 and also tested on 2285, both server and singleplayer
Botania: R1.9 343
Also used JEI and latest baubles and autoreglib as of this post. No other mods.

**Comment by JRoffel** [comment]
#2228

**Comment by Aphyxia** [comment]
I dropped iron ingot with Q (default keymap for drop item). Might not work when dropped from inventory.

**Comment by williewillus** [comment]
found it, stack.isItemEqual doesn't check empty state -.- so the recipe matches even when the stack has been invalidated.
