### ISSUE TITLE
Please delete the fu*** Mana in a Bottle crap :(

### ISSUE THREAD

**Issue by aaronegger** [Vazkii/Botania#2255]
Me as an stupid idiot was trying the mana in a bottle without knowing what would happen..
Suddenly all the inventory was gone.
I didn't drop or something like that, it is just gone.

Who the hell implents such a fu*** piece of sh***???

Now I have to spend hours on rebuilding my inventory out of my brain and some backups.

Thanks a lot for this sh***

**Comment by ArukaAlter** [comment]
That is NOT how you report an unintended behavior, this is missing critical information such as mod version and/or other mods present in the environment.

**Comment by williewillus** [comment]
If it is a bug, report it properly with steps to reproduce. The inventory is obviously dropped in the world as the code shows [here](https://github.com/Vazkii/Botania/blob/master/src/main/java/vazkii/botania/common/item/ItemBottledMana.java#L106)

Verbal abuse will not be tolerated :/

**Comment by Vazkii** [comment]
This is the first thing I read in the morning and you can be assured it's the high point of my day. Thanks for the laugh. 

In any case, the items should fall on the ground. See if you have any super fast collectors nearby that picked them up for you.

**Comment by ktole1999** [comment]
unless perhaps something else is blocking the drops.

**Comment by aaronegger** [comment]
Sorry I am very late. I forget it completely..

I am really sorry for being such an asshole!

I was angry at that moment, but it was my fault, that i tried something, without knowing what will happen, without making a backup before.

It tried it several times, but the stuff was gone.

But it have to admit, that it was in one of the abysalcraft dimensions.
Dropping items normaly works, but it's maybe possible that there are some incompatibilities.

I don't think that this is really an issue.

Thank you for this great mod! 
It is one of the best and most stable mods we have here on our server!
