### ISSUE TITLE
Mana Fluxfield and Woot

### ISSUE THREAD

**Issue by Alchemii** [Vazkii/Botania#2257]
So, I'm playing modded minecraft on 1.10.2 forge, and I was trying to power the Woot mob factory using botania. However I can't seem to get any power transfer from the Mana Fluxfield to the factory, I'm not sure what the issue is, weather it be on Botania's side or Woot's side.

**Comment by williewillus** [comment]
does Woot support forge energy?

**Comment by Alchemii** [comment]
No, it supports RF, and for 1.10 the book said it was still running the RF version of the Mana Fluxfield, not the Forge version that it runs in 1.11

**Comment by williewillus** [comment]
the RF support might have been broken before it got replaced with FE

**Comment by Ipsis** [comment]
Woot moved over to using  Forge energy a good few releases ago, (1.10.2-1.2.5) I  just never got around to updating the manual. There is always the chance that I've missed out something Botania needs, so I'll throw it in my dev environment and see what I can find out.

**Comment by Alchemii** [comment]
Ok, so I downgraded Woot to 1.10.2 - 1.2.4, and that seems to have solved the problem. Since we now know that Woot is running forge in every version after 1.2.5, then that's probably the case, Botania is still running RF for 1.10 and Woot is not. Though I would like a confirmation that this is in fact the issue.

**Comment by williewillus** [comment]
yeah, I just checked. the last 1.10 version still uses RF, but I'm not sure if it ever worked after 1.7, hence the switch to FE.

**Comment by Alchemii** [comment]
ok I can confirm, it does work after I downgraded to the older version, it just takes like 2-4 Mana Fluxfields (I'm currently running 4, but when I was first testing I was running 5) to power it, which of course is a massive drain on mana, but that was to be expected.

**Comment by williewillus** [comment]
okay, i'll mark this as resolved then since 1.10 botania isnt receiving further updates. it should just work ^tm with FE in 1.11+
