### ISSUE TITLE
1.11.2 r1.9-343 Alchemy Catalyst Sapling Bug

### ISSUE THREAD

**Issue by TwitchtvCarbs** [Vazkii/Botania#2258]
Getting a small bug with the Alchemy Catalyst in this version.

https://github.com/TwitchtvCarbs/The-Collection-Issues/issues/28

**Comment by ArukaAlter** [comment]
Make sure there's absolutely nothing picking the items up, there was a similar issue before where there was a Endoflame eating the saplings before they could been picked up.
