### ISSUE TITLE
Unindentified Flower after creeper blowed up

### ISSUE THREAD

**Issue by EscolarProgramming** [Vazkii/Botania#2260]
Hello everybody, 
We are playing on our sponge based Beyond server (v1.5.3) on 1.10.2 and I was setting up some botania mana gen. A creeper came along and blew up next to our Endoflames. Instead of breaking the flowers, the Endoflames turned into missing textures. I broke the flowers and got the achievement that told me to report the flower. It happended in a claimed area, chunk-claimed with FTB Utilities.

I hope, you can fix it :)

**Comment by ArukaAlter** [comment]
Terrain protection mods usually fail to fully negate explosions on modded blocks, causing them to lose stored data, in the case of Botania's flowers, they are defined by a NBT tag, which is lost on the attempt of stopping the explosion.

**Comment by williewillus** [comment]
restoring protected areas should restore the tile entity data, try reporting to FTBU or sponge? either way, not botania
