### ISSUE TITLE
Not using .isEmpty for lens tooltip

### ISSUE THREAD

**Issue by yrsegal** [Vazkii/Botania#2262]
https://github.com/Vazkii/Botania/blob/master/src/main/java/vazkii/botania/common/item/ItemManaGun.java#L203
<img width="296" alt="screen shot 2017-05-13 at 9 37 16 pm" src="https://cloud.githubusercontent.com/assets/6596492/26030548/89efbfb8-3824-11e7-83cf-73070352daec.png">

**Comment by williewillus** [comment]
thx
