### ISSUE TITLE
Make punching 2-high mystical flowers give a normal flower?

### ISSUE THREAD

**Issue by abculatter2** [Vazkii/Botania#2265]
Mainly just to help with the 'wtf!?' moment in the start of the game for new players.

**Comment by Nincodedo** [comment]
Duplicate of #1769

**Comment by williewillus** [comment]
^
but I'm wondering if there's a reason for it to be like that anymore. iirc it was disabled due to technical issues back then

**Comment by Hubry** [comment]
Wasn't that because of inventory clutter? Which would make more sense, seeing how much clutter the normal flowers can be already (flower pouches are nice).

**Comment by williewillus** [comment]
Okay then we'll stick with it then (this is a dupe anyway)
