### ISSUE TITLE
Terrasteel Crafting not working

### ISSUE THREAD

**Issue by alzeiher** [Vazkii/Botania#2266]
I have sufficient amount of mana, im pretty sure that my setup is right, and after i put the mana pearl, the mana diamond and the manasteel, the plate do the ''particle show'' and after this nothing happen, just the itens vanish.
PLS I NEED SOLUTION
I'm not very good at Botania, so please, be patient, and i'm playing FTB Beyond
![sufficient amount of mana](https://cloud.githubusercontent.com/assets/24842971/26476327/4f4cefe2-4194-11e7-8f19-3f8ad0a7f0ea.png)

**Comment by ArukaAlter** [comment]
You're feeding too little mana, read the manual, use Sparks.
