### ISSUE TITLE
Unknown Floating Botania Flower using Builders Wand

### ISSUE THREAD

**Issue by Julian0704** [Vazkii/Botania#2268]
By using a Builders Wand on any Floating Flower (tested with Floating Pure Daisy and Floating Endoflame) let the new Floating Flower be unknown. The Floating Flower you were right-clicking on is still the right, only the new Floating Flower you wanted to set is affected.

I hope, I made everything right (if not, just say it) 👍 

Maybe you can fix this :)

Best regards,
Julian_0704

**Comment by Tamaized** [comment]
dupe of #2227

**Comment by Julian0704** [comment]
Ok, thanks:)
