### ISSUE TITLE
[1.10.2] Right click AOE effect of BM bound shovel kills floating flowers (AKA Take it easy Achieve)

### ISSUE THREAD

**Issue by MrNinja93** [Vazkii/Botania#2269]
Only taken me like three years to finally get this achievement 10/10 worth the wait.

Title says it all using the Blood Magic's bound shovel's area of effect use kills floating flowers resulting in limited edition floating poppy's.

Botania: R1.9 341
Forge: 12.18.3.2281

**Comment by williewillus** [comment]
this is on BM's side, made a ticket: https://github.com/WayofTime/BloodMagic/issues/1155
