### ISSUE TITLE
Managlass and alfglass cause ambient occlusion

### ISSUE THREAD

**Issue by quat1024** [Vazkii/Botania#2272]
Version 343, Minecraft 1.11. Picture speaks for itself:

![image](https://cloud.githubusercontent.com/assets/2068021/26758170/789b4ea4-48a4-11e7-9533-8b8b4dc859c6.png)

Placing managlass or alfglass next to something makes it have a crappy dark shadow, unlike vanilla glasses.

**Comment by williewillus** [comment]
no idea what makes this happen

**Comment by TheWhiteWolves** [comment]
my guess would be it thinks the glass isn't transparent, thus doesn't let the light through it correctly :man_shrugging:
