### ISSUE TITLE
1.11.2 Baubles Case not saving items

### ISSUE THREAD

**Issue by SimulatorSia** [Vazkii/Botania#2275]
My baubles case in survival seems to clear out all the items in it if I completely close the game with any in it. If I close that world and open another then go back to that world, they're still there. Only deletes them when I close minecraft entirely. Only other mods being ran are Extra Utilities 2 and Optifine.

**Comment by williewillus** [comment]
forge issue, the fix is about to get in (hopefully)

**Comment by SimulatorSia** [comment]
alright <3
