### ISSUE TITLE
1.10.2 Redstone Comparator bug

### ISSUE THREAD

**Issue by samox73** [Vazkii/Botania#2276]
When trying the read the mana pool's amount of mana with a comparator (both vanilla and ProjectRed:Integration), the redstone signal doesn't get updated as the mana pool fills (or empties). Only when breaking one of the redstone paths or redstone conduits/cables, the signal gets its respective strength.
![2017-06-08_23 45 22](https://user-images.githubusercontent.com/29289920/26952194-a6f3ab08-4ca4-11e7-83d3-abc5d0882018.png)
After filling up the mana pool, and **before** replacing one of the redstone paths.
![2017-06-08_23 45 40](https://user-images.githubusercontent.com/29289920/26952197-a81aa82e-4ca4-11e7-8cc6-f91b49b7913a.png)
**After** replacing one of the redstone paths.

**Comment by williewillus** [comment]
Does it happen in 1.11?

**Comment by samfisher39** [comment]
I don't know. Happens in FTB Beyond 1.8.1, MC 1.10.2

**Comment by williewillus** [comment]
can't reproduce on 1.11, and I'm pretty sure the code hasn't changed since 1.10 0.o
