### ISSUE TITLE
Terrasteel helmet backwards

### ISSUE THREAD

**Issue by nodar86** [Vazkii/Botania#2277]
Minecraft version: 1.10.2
Botania version: r1.9-341

I think the terrasteel helmet is displayed backwards.

Front:
![2017-06-10_14 07 30](https://user-images.githubusercontent.com/15035875/27002601-2f453c5a-4de6-11e7-8e47-e5490d0447e9.png)

Back:
![2017-06-10_14 07 36](https://user-images.githubusercontent.com/15035875/27002602-31e0c998-4de6-11e7-8779-8148b0b2d688.png)

In inventory:
![2017-06-10_14 09 37](https://user-images.githubusercontent.com/15035875/27002614-76150282-4de6-11e7-9e87-4615745319c4.png)

**Comment by Vazkii** [comment]
It's not, it's just scaled up because of the change in player models. It'll
be replaced with a more fitting one soon.

**Comment by nodar86** [comment]
Sorry then :)

It just looked odd. Looking forward to the updated one.
