### ISSUE TITLE
Enchanter crash on Cannot get property PropertyEnum

### ISSUE THREAD

**Issue by leagris** [Vazkii/Botania#2281]
#### Versions:

- Botania: r1.9-343	
- Minecraft Forge: 1.11.2 13.20.0.2311
- [Complete mods list for Beyond Reality: Farscapes 1.0.3-r1](http://rawgit.com/Beyond-Reality/Beyond-Realty-Farscapes/master/modlist.html?p=Beyond%20Reality:%20Farscapes&v=1.0.3-r1)

#### Description

Server crashing when using the enchanter:
[`crash-2017-06-12_07.23.56-server.txt`](https://gist.github.com/leagris/617b9f62b939155c61a2e6662097d600)
```
java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=facing, clazz=class net.minecraft.util.EnumFacing$Axis, values=[x, z]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:201)
	at vazkii.botania.common.block.tile.TileEnchanter.func_73660_a(TileEnchanter.java:144)
```

#### See also

- [All blockstate crashes go here (cannot get property...) #2205](https://github.com/Vazkii/Botania/issues/2205)
- https://github.com/Beyond-Reality/Beyond-Realty-Farscapes/issues/9

**Comment by Crumbology** [comment]
Was my enchanter, was enchanting terrasteel boots with just vanilla enchants, protection, feather falling, depth strider and unbreaking, was accepting mana and working fine and halted with the pie chart icon almost full, sat there idle for a good few mins.

Then I broke the enchanter multiblock, server crashed, boots and the lapis block disappeared, books were still around.

**Comment by williewillus** [comment]
comment your case on #2205 instead of making a new ticket, thanks for the report!
