### ISSUE TITLE
Server crash on Startup "Colliding entity with block" Crash log enclosed

### ISSUE THREAD

**Issue by Gamerbolts** [Vazkii/Botania#2282]
Hi, I was wondering if you could help me I am getting a server crash on my modpack. Not too sure what is going on. Here is my crash log https://pastebin.com/Kf0mumY0. Thank you.

**Comment by Tamaized** [comment]
1.7.10 isn't supported

**Comment by Hubry** [comment]
It might not be supported, but seriously - it's the type of crash that's nice to fix, just go to the listed coords in MCEdit and remove stuff...

**Comment by Gamerbolts** [comment]
ok i'll do that, ty

**Comment by williewillus** [comment]
also there is a mod in that stacktrace modifying physics 
`    at com.creativemd.itemphysic.physics.ServerPhysic.update(ServerPhysic.java:237)`
so that might be causing screwy stuff (and thermos), but anyways yeah we're on 1.11
