### ISSUE TITLE
Pure Daisy issue when a block is used as both an output and input in CraftTweaker

### ISSUE THREAD

**Issue by TheDeviantCrafter** [Vazkii/Botania#2283]
I'm attempting to use the Pure Daisy as a way to obtain all of the logs from Rockhounding: Surface. To do this, I'm using the pure daisy since it's fun to automate. The script I'm using is as follows:

```
val creosoteWood = <railcraft:generic:5>;
val rockhoundingWood1 = <rockhounding_surface:bogLogs:0>;
val rockhoundingWood2 = <rockhounding_surface:bogLogs:1>;
val rockhoundingWood3 = <rockhounding_surface:bogLogs:2>;
val rockhoundingWood4 = <rockhounding_surface:bogLogs:3>;

	#Convert railcraft wood block into Rockhounding logs
mods.botania.PureDaisy.addRecipe(creosoteWood, rockhoundingWood1);
mods.botania.PureDaisy.addRecipe(rockhoundingWood1, rockhoundingWood2);
mods.botania.PureDaisy.addRecipe(rockhoundingWood2, rockhoundingWood3);
mods.botania.PureDaisy.addRecipe(rockhoundingWood3, rockhoundingWood4);
```

What I expected to happen:

After 60 seconds or so, the creosote wood block would convert into the first type of bog log. After another 60 seconds, it would change again. After four minutes, it would have transformed four times and it would stop doing anything.

What actually happened:

The creosote block transformed instantly, becoming the first bog log type. After that, it kept trying to transform a few times a second but didn't change. This caused a lot of particle spam.

[Gif of the bug in action](https://i.gyazo.com/6fe54bde74e3429704f6b0b7b123f81d.mp4)

[Latest.log file](https://pastebin.com/VUeHw3R9)

**Comment by TheWhiteWolves** [comment]
[17:54:35] [Client thread/INFO]: [CHAT] ERROR: Botania.zs:72 > No such static member in minetweaker.item.IItemStack: rockhoundingWood5
[17:54:35] [Client thread/INFO]: [CHAT] ERROR: Botania.zs:73 > No such static member in minetweaker.item.IIngredient: rockhoundingWood5
[17:54:35] [Client thread/INFO]: [CHAT] ERROR: Required parameters missing for Botania PureDaisy Recipe.
[17:54:35] [Client thread/INFO]: [CHAT] ERROR: Required parameters missing for Botania PureDaisy Recipe.

These lines might explain it, never used minetweaker so I have no clue what stuff it does but looks like you might be missing something.

**Comment by TheDeviantCrafter** [comment]
That error was caused when I was troubleshooting the script. RockhoundingWood1 isn't a modname. I got lazy with Ctrl + H.

The script I included in the OP is error-free.

**Comment by williewillus** [comment]
since it didn't actually change, I think this is just a desync, since the pure daisy runs its logic on both sides.

Should be fixed by just running it serverside
