### ISSUE TITLE
1.11.2 Sashes have no jump boost

### ISSUE THREAD

**Issue by Crumbology** [Vazkii/Botania#2284]
Sojourners and Globetrotters sashes are giving no jump boost, have plenty of mana in inventory.  Lexica entry is unchanged and I saw nothing in changelogs to explain it.

Running Beyond Reality: Farscapes pack from the AT launcher.

**Comment by TheWhiteWolves** [comment]
have you tried it with just botania installed?

**Comment by Crumbology** [comment]
Just tried, sash works as normal, jump boost works, will do some digging around to see what mod is interfering with it.
