### ISSUE TITLE
Coporea interceptor pulses {suggestion}

### ISSUE THREAD

**Issue by tobiasvdp** [Vazkii/Botania#2288]
As far as I can see there is no way to know how any items were not present on request.
For example requesting 10 oak wood planks and having 4 in storage gives 1 pulse. 
It would be handy if the interceptor would give 6 pulses. (or x pulses divided by the block rotation in the itemframe). This would allow to craft the requested amount, and not just single craft.

**Comment by williewillus** [comment]
combining in to #2860
