### ISSUE TITLE
Add CraftTweaker support on your end (read below)

### ISSUE THREAD

**Issue by Sunconure11** [Vazkii/Botania#2290]
As Jared is focusing on 1.12, and this mod would likely take a bit to get to 1.12, would it be possible to add crafttweaker support in a 1.11.2 build?

https://cdn.discordapp.com/attachments/318434717525475338/327167349226602506/unknown.png

**Comment by williewillus** [comment]
I don't know what the linked picture is supposed to mean. I'm pretty sure botania already exposes api calls for MT/CT to work properly? It's on them to just call the methods.

**Comment by Sunconure11** [comment]
Jared wants to focus more on 1.12, so he doubts 1.11.2 will get much support.

**Comment by williewillus** [comment]
I still don't know what it's asking for. Botania has exposed the necessary calls for MT/CT for a long time, it's up to MT/CT from there to provide a way to call them (which I'm sure they do already)

**Comment by bookerthegeek** [comment]
If i am reasing this correctly, he is askimg you to implement Minetweaker support directly into your mod for 1.11 as MT is focusing on 1.12 and will not be adding any mod mod support.

So you would add the code that add the scripting mechanics

**Comment by williewillus** [comment]
> So you would add the code that add the scripting mechanics
No, that's exactly what MT is for, and MT has already had support for botania, so unless they removed it things should already work
