### ISSUE TITLE
Some Garden of Glass Features not working (1.11.2)

### ISSUE THREAD

**Issue by Fade-Alchemist** [Vazkii/Botania#2291]
I am having a strange issue in my Garden of Glass world. This world started as 1.10.2 and I updated it to 1.11.2 and I am currently using Botania version 344. The ability to get pebbles from dirt no longer works and the Garden of Glass Sky-box is absent. (The sky-box being absent doesn't bother me too much, but I list it here as it is a sign of the problem) Particularly odd is that other features do represent, like the Garden of glass recipe for mana spreaders for example.  I am not sure what information I need to provide to help diagnose this problem, but I would be grateful for any help you can provide! Thank you in advance. :-) #

**Comment by williewillus** [comment]
the GoG mod jar needs to be updated when going from 1.10 -> 1.11, download a fresh one from curse

**Comment by Fade-Alchemist** [comment]
Thank you for your reply. I have tried this. Just to be sure I did it
again. I deleted the old GoG Jar file, went to curse and loaded a fresh one
(1.11.2 version). However, I am having the same result. The recipes seem to
update, but aside from that, the world is acting like it is a
non-gog world.
