### ISSUE TITLE
Bore Warp lens destroying blocks not breaking

### ISSUE THREAD

**Issue by JewNoodles** [Vazkii/Botania#2292]
Bore Warp lens destroying blocks not breaking.  the blocks break and nothing is dropped.

setup:  http://oi66.tinypic.com/hugfux.jpg
wood breaking and no blocks dropping: http://oi66.tinypic.com/qs5q8y.jpg

**Comment by williewillus** [comment]
Make sure nothing is picking them up or some plugin isn't suppressing drops or whatever

**Comment by JewNoodles** [comment]
if i put a warp bore lens items are dropped.
