### ISSUE TITLE
Garden Of Glass and Botania 1.9.344

### ISSUE THREAD

**Issue by jmrio** [Vazkii/Botania#2295]
When pressing shift+right mouse button to get pebbles the game crashes.

The error
`The game crashed whilst unexpected error
Error: java.lang.NoSuchMethodError: net.minecraftforge.event.entity.player.PlayerInteractEvent$RightClickBlock.setCancellationResult(Lnet/minecraft/util/EnumActionResult;)V`

**Comment by williewillus** [comment]
update forge

**Comment by jmrio** [comment]
Solved
