### ISSUE TITLE
Agricarnations finnicky

### ISSUE THREAD

**Issue by Redempt** [Vazkii/Botania#2297]
I was designing an automated wheat farm and figured that I'd spam 12 agricarnations to make the wheat grow fast enough. When I did this, I found the wheat to not grow at all. Reducing it to 4 agricarnations, I got 7 of the 16 wheat. I tried adding back 2 to see what it yielded, but it stopped growing entirely again, and didn't resume when I removed the 2 agricarnations I had added.

**Comment by williewillus** [comment]
All the agricarnation does is schedule extra ticks on the crops, it never does any growing itself. Because crops have a random check on their ticks, what you're seeing is just bad luck, unless there's a bug in the logic (unlikely).

**Comment by Redempt** [comment]
I checked the code for the agricarnation myself, and it seems sound, but I don't write mods (only plugins) and don't know exactly what it's doing. Is it scheduling the plant to have extra growth, or is it scheduling extra chances for random ticks to occur and make it grow?

**Comment by Redempt** [comment]
Also, I'm finding it hard to pin this on bad luck. I've given these 8 agricarnations 5 minutes to grow 16 wheat, and none of them are beyond 0% growth.
