### ISSUE TITLE
[BUG]Botania 1.9-345:Doubled Armor Points

### ISSUE THREAD

**Issue by Lodugh** [Vazkii/Botania#2299]
I dont know why nobody mentioned it before, but the Armor Points of all the Botania Armor is doubled and even different than it says in the tooltip. Would be great if that gets fixed soon! Tested it with nothing but Botania in the latest Forge version for Minecraft 1.11.2(2391).

**Comment by Lodugh** [comment]
Seems to be a problem with every forge version from 2307, because they changed the armor calcluation in that one.

**Comment by williewillus** [comment]
what do you mean? the "+5 armor" on the tooltip means 2.5 shield icons on the HUD because one point is a half shield

**Comment by Lodugh** [comment]
Yes, but in the latest forge version you get 5 shield icons for armor pieces with +5 armor.

**Comment by Lodugh** [comment]
Well, for now I just turn off the recipes in my modpack, however I would be very thankful for a soon fix.

**Comment by Lodugh** [comment]
Another thing I noticed with this bug is that if you put it on just for a short moment it shows the right amount of armor points but then it adds the same amount on top of that.

**Comment by Lodugh** [comment]
Dont want to push you but I'd really like to use Botania armor again. Just wanted to make sure you dont forget this bug because there wasnt any more responses.

**Comment by williewillus** [comment]
I can't reproduce this with botania alone

**Comment by Lodugh** [comment]
Weird. Did you try it in the latest forge version for 1.11.2? Because for me it happened since Forge 2307, when they changed something with the armor points. I tried it just with Botania once again and its still the same for me. Manasteel Armor goes way over the 20 Armor Points.

**Comment by Gelles** [comment]
Just tested, and I'm also getting this with Botania alone. Forge 2454 and Botania r1.9-345 for 1.11.2
