### ISSUE TITLE
This devil has a problem

### ISSUE THREAD

**Issue by a5992369** [Vazkii/Botania#2301]
This devil has a problem!!

is eazy to kill with use tinker bow  

this boss  will not move and die

**Comment by KingDGrizzle** [comment]
uhh, What?

**Comment by Vazkii** [comment]
What the shit

**Comment by a5992369** [comment]
devil ----> Botania BOSS

**Comment by a5992369** [comment]
is really eazy to kill with use this mod item----->(tinker bow)
Can  let him react?
