### ISSUE TITLE
Spark Dupe Bug

### ISSUE THREAD

**Issue by Norakthes** [Vazkii/Botania#2302]
I was casually playing Skyfactory 3 and playing with Botania, when I discovered when i was removing my spark from my mana pool the spark was duped. I played a little more with it to replicate it, and discovered when i was quickly pressing right click 2 times really fast it dupes the spark. Hope this was helpfull

Sincerely Norakthes  

Photographic evidence: https://www.youtube.com/watch?v=WL579B4jjSk

PS: If you're lagging it's easier to do

**Comment by xenxero1** [comment]
Sparks function as entities correct? I have a feeling this could be somewhat related;
https://github.com/SleepyTrousers/EnderIO/issues/4282

**Comment by HenryLoenwind** [comment]
If it is an entity: Minecraft doesn't do server-side checking if the entity is dead when processing the mouse clicks the client sends.
