### ISSUE TITLE
Botania {  Gaia boss  with  Tinkers' BOW }

### ISSUE THREAD

**Issue by a5992369** [Vazkii/Botania#2304]
Can you let gaia fight back immediately when it take any damage ? specialy tinker's bow and cross bow , because everyone in my server use ccross bow killed gaia , it just like an idiot stand there and they beaten it like a moron...

**Comment by ArukaAlter** [comment]
You are providing very little information.

**Comment by xenxero1** [comment]
Hes saying the tinkers weapons are doing way too much damage to the Gaia Guardian and it's making the boss fight too easy, maybe even causing glitches in fight phases?

**Comment by Tamaized** [comment]
I mean, if you're complaining about balance when using another mod, that's your own problem. That's like saying you need to make your mod harder just because you use DE and it's too easy now.

**Comment by williewillus** [comment]
also there should be the damage cap of 25 unless tinkers is being dumb and directly setting health

**Comment by xenxero1** [comment]
I think that might be what the issue is. Either tinkers is bypassing the damage cap, or the damage cap isn't working properly in the new version.

**Comment by bookerthegeek** [comment]
The other issue is if you stand rigbt at the edge of the arena, the Gaia Guardian does not start to move around. It stays still not moving, resulting in an easy kill no matter how much damage you do as it never fights back or moves.

**Comment by a5992369** [comment]
..... i mean Gaia take tinker bow any damage , he didn't move

**Comment by a5992369** [comment]
...Gaia was hurt didn't moving

**Comment by VolterPL** [comment]
That's an issue I know for a long long time, it doesn't even involve any other mods than Botania to make it happen:
a) get a Terrasteel/Gaia ingot,
b) go to the Gaia arena,
c) activate the ritual,
d) run as fast as you can to the border of the arena,
e) grab your Terra Blade and spam clicks until Gaia is dead,

Gaia won't even move, nor activate mob waves...
