### ISSUE TITLE
[1.10.2] Crash on world create with OTG

### ISSUE THREAD

**Issue by Claycorp** [Vazkii/Botania#2305]
https://pastebin.com/xxDiMfzT

This issue has been plaguing me for weeks now, I am having a tough time trying to pinpoint what is exactly causing it and any help would be appreciated. I started with opening an issue on OTG PG85/OpenTerrainGenerator#43
PeeGee thought I was trying to use an old world I had made without the mod but even after deleting every file I could possibly find that has anything to do with Biome Bundle and OTG. This did not fix the problem.

I then went through the mod list disabled a bunch of mods and started testing till it crashed again. Once I enabled Prefab it would no longer generate thus Brian-Wuest/MC-Prefab#48 came about.
This didn't seem right, and I did test with just Botania, BiomeBundle and Prefab but this combo on its own will not crash.
I'm kinda lost at what to do now as I've exhausted everything I could think of, Including copying the mods into a new instance and letting them generate new configs to rule that problem out.

Any input or help would be greatly appreciated.

**Comment by williewillus** [comment]
TerrainControl is attempting to set invalid metadata for a mana spreader. There's only 4 but it's trying to get the 5th

**Comment by Claycorp** [comment]
I understand the log but I can't figure out what to do or who the issue is at this point.
I'm not sure why it would do that after disabling the mods making a few test worlds then turning them back on and attempting to make a new world, when it was working fine before hand.

**Comment by williewillus** [comment]
closing from staleness (the terrain generator mod is setting bad blocks)
