### ISSUE TITLE
Ring of Loki

### ISSUE THREAD

**Issue by waig548** [Vazkii/Botania#2307]
The lexicon said that this ability can extend to destruction using Terra Shatterer or Terra Truncator.
I followed the procedure and it can place blocks correctly, but I can't mine block as the pattern I set even if I'm using Terra Shatterer or Terra Truncator (tested with holding shift and without it).

**Comment by quat1024** [comment]
I accidentally duplicated this bug a while back in https://github.com/Vazkii/Botania/issues/2366 . It was fixed a while ago.

I guess this issue can be closed now (I can't close it myself)
