### ISSUE TITLE
Beegonia causes a crash

### ISSUE THREAD

**Issue by Calcutroll** [Vazkii/Botania#2308]
The beegonia flower (from magic bees mod) had no textures, and randomly crashed the server a few seconds after being placed.

[crash-2017-07-15_23.57.52-server.txt](https://github.com/Vazkii/Botania/files/1150832/crash-2017-07-15_23.57.52-server.txt)

**Comment by ArukaAlter** [comment]
Report it to Magic Bees.

**Comment by Calcutroll** [comment]
Reporting to magic bees
