### ISSUE TITLE
Beegonia etc not available with Magic Bees. MC 1.10.2

### ISSUE THREAD

**Issue by Jobs2k** [Vazkii/Botania#2310]
With FTB Beyond (1.10.0) fully working I added Magic Bees (MagicBees-Alpha-3.0.2.jar for MC 1.10).

The Beegonia, Hiveacynth and Hibeescus are not available.
The rest of the Magic Bees mod items appear to be working fine.

What could be causing this issue? What have I missed?
Or have I missed nothing and this is indeed a bug? If so, with which mod?

**Comment by TheWhiteWolves** [comment]
afaik those are not added by Botania, I'd go submit this the the Magic Bees dev

**Comment by williewillus** [comment]
^
