### ISSUE TITLE
Redirective Lens bursts go through walls 

### ISSUE THREAD

**Issue by Hubry** [Vazkii/Botania#2311]
Reproducing: Put two mana spreaders side by side, put blocks in front of them, give one the Redirective lens, the other - the Phantom lens. Look at the trails with the Wand of the Forest.

I think [this part](https://github.com/Vazkii/Botania/blob/924ee0267b40ccff6fdb10fdc2df95edcff6c1f6/src/main/java/vazkii/botania/common/item/lens/LensRedirect.java#L67-L70) of collideBurst causes that - it's a copy of [collideBurst](https://github.com/Vazkii/Botania/blob/924ee0267b40ccff6fdb10fdc2df95edcff6c1f6/src/main/java/vazkii/botania/common/item/lens/LensPhantom.java#L22-L25) from the Phantom lens code.

Using MC 1.11.2, Forge 13.20.1.2414, Botania R1.9-345, Baubles 1.4.5.

**Comment by williewillus** [comment]
@Vazkii is this intended?
