### ISSUE TITLE
Miscellaneous Botania Flower bug.

### ISSUE THREAD

**Issue by biker-trash** [Vazkii/Botania#2314]
Hiya Hiya,

I had two bugged flowers in my mana generating setup.  Both were Endoflames. I have 4 identical setups feeding 5 mana pools. Two of the four had bugged Endoflames. In both cases an Item Transfer Node (pulling coal coke from the chest) and one piece of transfer pipe disappeared from the setup. In only one of the cases the sand (10 blocks=10s) had disappeared from the Floating Hourglass.  

![2017-07-22_17 37 53](https://user-images.githubusercontent.com/30378115/28494795-e157293a-6f06-11e7-886f-aeb23ef0244e.png)

![2017-07-22_17 38 47](https://user-images.githubusercontent.com/30378115/28494797-edb7764e-6f06-11e7-9f0a-369c056ee4d5.png)

**Comment by williewillus** [comment]
what version?

**Comment by kjarvi** [comment]
This happens to me on Botania 344. The flowers and such work fine, but I'll come back after not playing for a few hours and suddenly they will have that texture bug. WIALA just says that it is a "Botania Flower" and has the poppy icon. Breaking it drops the original flower. It happens to the Endoflame and Gourmaryllis at least, probably others.
