### ISSUE TITLE
Munchdew stops eating

### ISSUE THREAD

**Issue by JanWalsh91** [Vazkii/Botania#2315]
Hi, 

Please let me know if you think this is a bug or if I'm doing something wrong.

- I set up my munchdew next to saplings in my auto farm. 
- I set them to a mana spreader (not shared with anything else) which is set to a mana pool (not full).
- First birch tree (vanilla) grows and leaves are eaten by munchdew.
- I destroy tree.
- Any subsequent birch tree leaves spawned by new birch trees (also tried with oak) are not eaten by munchdew even though its internal mana is depleted, its spreader's mana is depleted and the mana pool is not full. 

Good luck!

**Comment by Tamaized** [comment]
From the Lexica Botania:
`However, after if finishes eating all the available leaves, when left without any, it'll take a break from doing so and will only be able to eat again after a bit over a minute.`

Could it just be the cooldown?

**Comment by JanWalsh91** [comment]
I'll check it out. Thanks!

**Comment by williewillus** [comment]
Maybe it needs to have a visual cooldown indicator
