### ISSUE TITLE
Mana Spreader Bug

### ISSUE THREAD

**Issue by HaX4R** [Vazkii/Botania#2317]
Pack: DW20 1.10.2
Botania: r1.9-341
Private MC Server

The issue is the mana spreaders stop sending mana to anything. When i try to bind them and then right click them to check the bar of mana to see is its working, the spreader will reset to a default position,
I have fixed the issue but deleting my player data from the server but the issue will comeback after a short time

**Comment by Hubry** [comment]
Possibly related to #2263? This matches the description of the Forge issue linked there, with the spreader losing target...
Check the server's `I:dormantChunkCacheSize` option in `forgeChunkLoading.cfg`

**Comment by HaX4R** [comment]
Nope not the same issue i checked everything then and didnt work
