### ISSUE TITLE
Dreadthorne kills Animania baby animals (the horror)

### ISSUE THREAD

**Issue by capnkirok** [Vazkii/Botania#2319]
Looks like you are using GrowingAge and not IsChild to determine if the EntityAnimal is a baby: 
 
`@Override
	public Predicate<Entity> getSelector() {
		return var1 -> var1 instanceof EntityAnimal && ((EntityAnimal) var1).getGrowingAge() == 0;
	}`

Any particular reason for this? I mean I can set my entities to have a negative GrowingAge, but seems a bit odd since the IsChild flag is right there....

**Comment by williewillus** [comment]
fixed in 1.12

**Comment by capnkirok** [comment]
Cheers @williewillus
