### ISSUE TITLE
Ok  I think there might be problem with the cocoon of caprice.

### ISSUE THREAD

**Issue by kbcoder** [Vazkii/Botania#2321]
I created one of those cocoon and it started spawning non-stop mobs.. had to shut down the server and restore from a backup.  I Couldn't get it to stop spawning at all.

MC. 1.11.2
Botania: 1.9-345

**Comment by williewillus** [comment]
The block is not being destroyed properly. Is some plugin or something preventing it from deleting itself? A full modlist or log would be nice

**Comment by Saklad5** [comment]
Possibly related: using an Acceleration Wand from Not Enough Wands on a Cocoon of Caprice seems to spawn a bazillion mobs.

Minecraft 1.12.2, Botania v352
