### ISSUE TITLE
Mana pool particles have a heavy diagonal bias

### ISSUE THREAD

**Issue by quat1024** [Vazkii/Botania#2322]
![image](https://user-images.githubusercontent.com/2068021/28884495-17c29582-7780-11e7-9d8a-bfcc8923d5c1.png)

Botania 345 for Minecraft 1.11.

I just noticed that the mana pool crafting effect is really weird looking. Most particles go in the +X,+Z / -X,-Z diagonal direction. Some particles go the other way, but they spawn at the corner of the pool, not the center. No particles are close to being axis-aligned; every single one goes diagonally.

Obviously this is ~~fkin unplayable~~really minor

**Comment by codewarrior0** [comment]
Fixed by #2329
