### ISSUE TITLE
(1.10.2) Game crashes with any version of Botania

### ISSUE THREAD

**Issue by MrIzumaki** [Vazkii/Botania#2323]
If I add Botania to my mods folder then my game will crash on startup. 

Crash report:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CorePlugin (MrTJPCore-1.10.2-2.0.1.20-universal.jar)
  OpenModsCorePlugin (OpenModsLib-1.10.2-0.11.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.9.283-universal.jar)
  CoFH Loading Plugin (CoFHCore-1.10.2-4.1.11.16-universal.jar)
  NEICorePlugin (NotEnoughItems-1.10.2-2.1.3.220-universal.jar)
  Brandon's Core (BrandonsCore-1.10.2-2.1.10.122-universal.jar)
  AppEngLoadingPlugin (appliedenergistics2-rv4-stable-1.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
Contact their authors BEFORE contacting forge

// I blame Dinnerbone.

Time: 8/2/17 9:11 PM
Description: Initializing game

java.lang.OutOfMemoryError: Java heap space
	at net.minecraftforge.client.model.pipeline.UnpackedBakedQuad$Builder.<init>(UnpackedBakedQuad.java:112)
	at net.minecraftforge.client.model.ItemLayerModel.buildQuad(ItemLayerModel.java:369)
	at net.minecraftforge.client.model.ItemLayerModel.buildSideQuad(ItemLayerModel.java:353)
	at net.minecraftforge.client.model.ItemLayerModel.addSideQuad(ItemLayerModel.java:278)
	at net.minecraftforge.client.model.ItemLayerModel.getQuadsForSprite(ItemLayerModel.java:225)
	at net.minecraftforge.client.model.ItemLayerModel.bake(ItemLayerModel.java:126)
	at slimeknights.tconstruct.library.client.model.MaterialModel.bakeIt(MaterialModel.java:80)
	at slimeknights.tconstruct.library.client.model.ToolModel.bake(ToolModel.java:97)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:182)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:132)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:113)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:755)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:340)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.client.model.pipeline.UnpackedBakedQuad$Builder.<init>(UnpackedBakedQuad.java:112)
	at net.minecraftforge.client.model.ItemLayerModel.buildQuad(ItemLayerModel.java:369)
	at net.minecraftforge.client.model.ItemLayerModel.buildSideQuad(ItemLayerModel.java:353)
	at net.minecraftforge.client.model.ItemLayerModel.addSideQuad(ItemLayerModel.java:278)
	at net.minecraftforge.client.model.ItemLayerModel.getQuadsForSprite(ItemLayerModel.java:225)
	at net.minecraftforge.client.model.ItemLayerModel.bake(ItemLayerModel.java:126)
	at slimeknights.tconstruct.library.client.model.MaterialModel.bakeIt(MaterialModel.java:80)
	at slimeknights.tconstruct.library.client.model.ToolModel.bake(ToolModel.java:97)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:182)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:132)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:113)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:755)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:340)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (x86) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 283932000 bytes (270 MB) / 1060372480 bytes (1011 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2185 Optifine OptiFine_1.10.2_HD_U_E3 53 mods loaded, 53 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2185.jar) 
	UCHIJA	Forge{12.18.3.2185} [Minecraft Forge] (forge-1.10.2-12.18.3.2185.jar) 
	UCHIJA	appliedenergistics2-core{rv4-stable-1} [Applied Energistics 2 Core] (minecraft.jar) 
	UCHIJA	NotEnoughItems{2.1.3.220} [Not Enough Items] (NotEnoughItems-1.10.2-2.1.3.220-universal.jar) 
	UCHIJA	openmodscore{0.11} [OpenModsLib Core] (minecraft.jar) 
	UCHIJA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJA	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.10.2-2.5.9.283-universal.jar) 
	UCHIJA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.10.2.jar) 
	UCHIJA	appliedenergistics2{rv4-stable-1} [Applied Energistics 2] (appliedenergistics2-rv4-stable-1.jar) 
	UCHIJA	bdlib{1.12.4.24} [BD Lib] (bdlib-1.12.4.24-mc1.10.2.jar) 
	UCHIJA	ae2stuff{0.6.0.9} [AE2 Stuff] (ae2stuff-0.6.0.9-mc1.10.2.jar) 
	UCHIJA	Baubles{1.3.11} [Baubles] (Baubles-1.10.2-1.3.11.jar) 
	UCHIJA	Botania{r1.9-340} [Botania] (Botania r1.9-340.jar) 
	UCHIJA	JEI{3.14.7.419} [Just Enough Items] (jei_1.10.2-3.14.7.419.jar) 
	UCHIJA	chiselsandbits{12.12} [Chisels & Bits] (chiselsandbits-12.12.jar) 
	UCHIJA	CodeChickenLib{2.5.9.283} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.5.9.283-universal.jar) 
	UCHIJA	cofhcore{4.1.11} [CoFH Core] (CoFHCore-1.10.2-4.1.11.16-universal.jar) 
	UCHIJA	brandonscore{2.1.10} [Brandon's Core] (BrandonsCore-1.10.2-2.1.10.122-universal.jar) 
	UCHIJA	draconicevolution{2.1.3} [Draconic Evolution] (Draconic-Evolution-1.10.2-2.1.3.256-universal.jar) 
	UCHIJA	CodeChickenCore{2.4.1.102} [CodeChicken Core] (CodeChickenCore-1.10.2-2.4.1.102-universal.jar) 
	UCHIJA	EnderStorage{2.2.1.106} [EnderStorage] (EnderStorage-1.10.2-2.2.1.106-universal.jar) 
	UCHIJA	exnihiloadscensio{0.1.5} [Ex Nihilo Adscensio] (exnihiloadscensio-1.10.2-0.1.20.jar) 
	UCHIJA	extrautils2{1.0} [Extra Utilities 2] (extrautils2-1.10.2-1.5.1.jar) 
	UCHIJA	flatcoloredblocks{mc1.10-v4.4} [Flat Colored Blocks] (flatcoloredblocks-mc1.10-v4.4.jar) 
	UCHIJA	gobackpacks{1.0.0} [Good Old Backpacks] (GoodOldBackpacks-1.10.2-1.0.0.jar) 
	UCHIJA	inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks] (InventoryTweaks-1.61-58.jar) 
	UCHIJA	ironchest{1.10.2-7.0.15.804} [Iron Chest] (ironchest-1.10.2-7.0.15.804.jar) 
	UCHIJA	yunomakegoodmap{1.10.2-6.1.0.26} [YUNoMakeGoodMap] (YUNoMakeGoodMap-1.10.2-6.1.0.26.jar) 
	UCHIJA	itsbecauseuhasnogoodspawn{1.0.5} [ItsBecauseUHasNoGoodSpawn] (ItsBecauseUHasNoGoodSpawn-1.0.5.jar) 
	UCHIJA	lootbags{2.3.9} [Loot Bags] (LootBags-1.10.2-2.3.9.jar) 
	UCHIJA	forgemultipartcbe{2.0.0.38} [Forge Multipart CBE] (ForgeMultipart-1.10.2-2.0.0.38-universal.jar) 
	UCHIJA	MrTJPCoreMod{2.0.1.20} [MrTJPCore] (MrTJPCore-1.10.2-2.0.1.20-universal.jar) 
	UCHIJA	projectred-core{4.8.4.49} [ProjectRed Core] (ProjectRed-1.10.2-4.8.4.49-Base.jar) 
	UCHIJA	projectred-integration{4.8.4.49} [ProjectRed integration] (ProjectRed-1.10.2-4.8.4.49-integration.jar) 
	UCHIJA	projectred-transmission{4.8.4.49} [ProjectRed Transmission] (ProjectRed-1.10.2-4.8.4.49-integration.jar) 
	UCHIJA	projectred-fabrication{4.8.4.49} [ProjectRed Fabrication] (ProjectRed-1.10.2-4.8.4.49-fabrication.jar) 
	UCHIJA	projectred-illumination{4.8.4.49} [ProjectRed Illumination] (ProjectRed-1.10.2-4.8.4.49-lighting.jar) 
	UCHIJA	projectred-expansion{4.8.4.49} [ProjectRed Expansion] (ProjectRed-1.10.2-4.8.4.49-mechanical.jar) 
	UCHIJA	projectred-transportation{4.8.4.49} [ProjectRed Transportation] (ProjectRed-1.10.2-4.8.4.49-mechanical.jar) 
	UCHIJA	projectred-exploration{4.8.4.49} [ProjectRed Exploration] (ProjectRed-1.10.2-4.8.4.49-world.jar) 
	UCHIJA	mantle{1.10.2-1.1.5.205} [Mantle] (Mantle-1.10.2-1.1.5.jar) 
	UCHIJA	tconstruct{1.10.2-2.6.5.10} [Tinkers' Construct] (TConstruct-1.10.2-2.6.5.jar) 
	UCHIJA	thermalfoundation{2.1.5} [Thermal Foundation] (ThermalFoundation-1.10.2-2.1.5.12-universal.jar) 
	UCHIJA	thermalexpansion{5.1.9} [Thermal Expansion] (ThermalExpansion-1.10.2-5.1.9.23-universal.jar) 
	UCHIJA	thermaldynamics{2.0.10} [Thermal Dynamics] (ThermalDynamics-1.10.2-2.0.10.16-universal.jar) 
	UCHIJA	bspkrsCore{at_0.9} [bspkrsCore] (Treecapitator-1.10.2-at_0.9.jar) 
	UCHIJA	Treecapitator{at_0.9} [Treecapitator] (Treecapitator-1.10.2-at_0.9.jar) 
	UCHIJA	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
	UCHIJA	WailaHarvestability{1.1.10} [Waila Harvestability] (WailaHarvestability-mc1.10.2-1.1.10.jar) 
	UCHIJA	microblockcbe{2.0.0.38} [Forge Microblocks] (ForgeMultipart-1.10.2-2.0.0.38-universal.jar) 
	UCHIJA	minecraftmultipartcbe{2.0.0.38} [Minecraft Multipart Plugin] (ForgeMultipart-1.10.2-2.0.0.38-universal.jar) 
	UCHIJA	openmods{0.11} [OpenModsLib] (OpenModsLib-1.10.2-0.11.jar) 
	Loaded coremods (and transformers): 
CorePlugin (MrTJPCore-1.10.2-2.0.1.20-universal.jar)
  
OpenModsCorePlugin (OpenModsLib-1.10.2-0.11.jar)
  openmods.core.OpenModsClassTransformer
CCLCorePlugin (CodeChickenLib-1.10.2-2.5.9.283-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.CCL_ASMTransformer
CoFH Loading Plugin (CoFHCore-1.10.2-4.1.11.16-universal.jar)
  cofh.asm.CoFHClassTransformer
  cofh.asm.repack.codechicken.lib.asm.ClassHierarchyManager
NEICorePlugin (NotEnoughItems-1.10.2-2.1.3.220-universal.jar)
  codechicken.nei.asm.NEITransformer
Brandon's Core (BrandonsCore-1.10.2-2.1.10.122-universal.jar)
  com.brandon3055.brandonscore.asm.ClassTransformer
AppEngLoadingPlugin (appliedenergistics2-rv4-stable-1.jar)
  appeng.coremod.transformer.IntegrationTransformer
FMLPlugin (InventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
	OpenModsLib class transformers: [pre_world_render_hook:FINISHED],[movement_callback:FINISHED],[player_damage_hook:FINISHED],[map_gen_fix:ENABLED],[player_render_hook:FINISHED]
	AE2 Version: stable rv4-stable-1 for Forge 12.18.3.2185
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- WailaIntegration (Enabled/Not Forced)

	NotEnoughItems Invalid Fingerprint Reports: 
	List of loaded APIs: 
		* appliedenergistics2|API (rv4) from appliedenergistics2-rv4-stable-1.jar
		* Baubles|API (1.3.1.3) from Baubles-1.10.2-1.3.11.jar
		* BotaniaAPI (85) from Botania r1.9-340.jar
		* ChiselsAndBitsAPI (12.10.0) from chiselsandbits-12.12.jar
		* cofhapi (1.5.0) from BrandonsCore-1.10.2-2.1.10.122-universal.jar
		* cofhapi|block (1.7.0) from CoFHCore-1.10.2-4.1.11.16-universal.jar
		* cofhapi|core (1.7.0) from CoFHCore-1.10.2-4.1.11.16-universal.jar
		* cofhapi|energy (1.5.0) from BrandonsCore-1.10.2-2.1.10.122-universal.jar
		* cofhapi|item (1.7.0) from CoFHCore-1.10.2-4.1.11.16-universal.jar
		* cofhapi|tileentity (1.7.0) from CoFHCore-1.10.2-4.1.11.16-universal.jar
		* cofhapi|util (1.7.0) from CoFHCore-1.10.2-4.1.11.16-universal.jar
		* cofhlib (1.7.5) from CoFHCore-1.10.2-4.1.11.16-universal.jar
		* cofhlib|audio (1.7.5) from CoFHCore-1.10.2-4.1.11.16-universal.jar
		* cofhlib|gui (1.7.5) from CoFHCore-1.10.2-4.1.11.16-universal.jar
		* cofhlib|gui|container (1.7.5) from CoFHCore-1.10.2-4.1.11.16-universal.jar
		* cofhlib|gui|element (1.7.5) from CoFHCore-1.10.2-4.1.11.16-universal.jar
		* cofhlib|gui|element|listbox (1.7.5) from CoFHCore-1.10.2-4.1.11.16-universal.jar
		* cofhlib|gui|slot (1.7.5) from CoFHCore-1.10.2-4.1.11.16-universal.jar
		* cofhlib|inventory (1.7.5) from CoFHCore-1.10.2-4.1.11.16-universal.jar
		* cofhlib|util (1.7.5) from CoFHCore-1.10.2-4.1.11.16-universal.jar
		* cofhlib|util|helpers (1.7.5) from CoFHCore-1.10.2-4.1.11.16-universal.jar
		* cofhlib|world (1.7.5) from CoFHCore-1.10.2-4.1.11.16-universal.jar
		* cofhlib|world|feature (1.7.5) from CoFHCore-1.10.2-4.1.11.16-universal.jar
		* DraconicEvolution|API (1.3) from Draconic-Evolution-1.10.2-2.1.3.256-universal.jar
		* JustEnoughItemsAPI (4.10.1) from jei_1.10.2-3.14.7.419.jar
		* WailaAPI (1.3) from Waila-1.7.0-B3_1.9.4.jar
	CodeChickenLib Invalid Fingerprint Reports: 
	CodeChickenCore Invalid Fingerprint Reports: 
	EnderStorage Invalid Fingerprint Reports: 
	AE2 Integration: IC2:OFF, RF:OFF, RFItem:OFF, Waila:ON, JEI:ON, THE_ONE_PROBE:OFF
	Launched Version: 1.10.2-forge1.10.2-12.18.3.2185
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics GL version 4.0.0 - Build 10.18.10.4276, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Atom(TM) CPU Z3735F @ 1.33GHz
	OptiFine Version: OptiFine_1.10.2_HD_U_E3
	Render Distance Chunks: 6
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.0.0 - Build 10.18.10.4276
	OpenGlRenderer: Intel(R) HD Graphics
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by Tamaized** [comment]
`java.lang.OutOfMemoryError: Java heap space`

You need to allocate more ram to the game

**Comment by JRoffel** [comment]
Just a side question, didn't minecraft crash logs used to show allocated memory? I can't seem to find it in any crash log anymore

**Comment by williewillus** [comment]
it's right here
`Memory: 283932000 bytes (270 MB) / 1060372480 bytes (1011 MB) up to 1060372480 bytes (1011 MB)`
for a pack of your size you probably need 1.5-3G of ram allocated, increase it in the launcher.

**Comment by MrIzumaki** [comment]
Thanks all of you, sorry to bother about a simple ram issue
