### ISSUE TITLE
Azanor change API in Baubles

### ISSUE THREAD

**Issue by Rumaruka** [Vazkii/Botania#2324]
Crash log : https://pastebin.com/FLr25HjU
Minecraft 1.11.2

**Comment by Vazkii** [comment]
@azanor mate come on don't go breaking backwards compatibility like that :|

**Comment by Rumaruka** [comment]
@Vazkii :(

**Comment by Azanor** [comment]
Not sure what you mean - those are new additions and should break backwards capability at all.

**Comment by Vazkii** [comment]
I've had a look at your code, and yeah, it's impossible for this error to
actually happen. I'm officially confused.

**Comment by Azanor** [comment]
Maybe there is another mod that has the api source in its code and it is being used over the newer code in the baubles .jar?

**Comment by Vazkii** [comment]
Yeah, this would probably have to be tested in isolation.

**Comment by 016Nojr** [comment]
Could it be Actually Baubles? Try removing that @Rumaruka

**Comment by Rumaruka** [comment]
@016Nojr Nope, Im downgrate Baubles and WORKING
I

**Comment by Jacky1356400** [comment]
My mod (Actually Baubles) shouldn't be causing this crash as it depends on Baubles as well.
Plus, the 1.11.2 Actually Baubles build was compiled based on Baubles 1.4.6 (which is the version in the crash report) and I've tested that build before releasing it.

**Comment by williewillus** [comment]
@Rumaruka can you reproduce this with just new baubles and botania?

**Comment by TehBlizzy** [comment]
I would like to add that I am receiving this crash as well after I updated a modpack to the latest versions. Creating a new profile and only adding the latest Baubles and Botania works perfectly fine. I'm going to add/remove mods down my list to see what could be interfering with it and edit this with any update(s).

**Comment by IchigoGames** [comment]
Happens with Baubles-1.11-1.4.6 does not happen with Baubles-1.11-1.4.5 so something changed and its crashing now im just not going to update Baubles for now when i update my pack.

**Comment by IchigoGames** [comment]
anyone know if baubles will come out with a fix ?

**Comment by Xalcon** [comment]
@Rumaruka is your modpack publicly available? I would like to do some tests. For me it looks like there is a mod in your pack that ships with an outdated Baubles-API package. The API Package doesnt contain a ModID - therefore forge cant check the version.

**Comment by Xalcon** [comment]
Okay, good news everyone. I found the offending Mod, its NineTailsLib (a ProjectX 2 dependency)
https://minecraft.curseforge.com/projects/ninetaillib?gameCategorySlug=mc-mods&projectID=264381
https://github.com/TeamMD5/NineTailLib/tree/1.11.2/src/main/java/baubles/api

You can easily reproduce the issue with the following mods installed:
* Botania
* Baubles
* ProjectX 2
* NineTailsLib
* CodeChickenLib

**Comment by williewillus** [comment]
^
