### ISSUE TITLE
[1.10.2] greater fairy ring causes crashes on damge

### ISSUE THREAD

**Issue by exultanthabit** [Vazkii/Botania#2325]
Forge: 12.18.3.2422
Botania Version: r1.9-341
Description: A zombie hit a player with a ring on, causing crash on two occasions.

[Crash Log](https://gist.github.com/exultanthabit/bf58e046e3c35fce7224c1708352a05e)

**Comment by williewillus** [comment]
I'm pretty sure this is a blood arsenal blood. the pixie from the ring is just attacking the zombie like normal
