### ISSUE TITLE
[1.11.2] Chisel and Bit compability 

### ISSUE THREAD

**Issue by Medusalem** [Vazkii/Botania#2332]
Minecraft: 1.11.2
forge: 13,20,1,2393
Botania r1.9-345 
Server and Client

Issue presented in this Githhub: https://github.com/AlgorithmX2/Chisels-and-Bits/issues/298
like written there maybe linked to this Issue: https://github.com/AlgorithmX2/Chisels-and-Bits/issues/135

I will try to back track which version changed the possibility to chisel Mana Glass and Alfglass.
Since this is no "Crash" Report i am not sure what i can present, Alorithm said to take a look at the logs, but i was not able to find something in this direktion, but I just have a basic understanding of reading Crashlogs. So if i can offer anything to help just post and i will try to deliver!

Please excuse my bad English,

Greetings

**Comment by AlgorithmX2** [comment]
@Hubry on the C&B issue found https://github.com/Vazkii/Botania/commit/2494a5d2b0288cc58d1f3f1fdd6dcc42375ef976

I haven't been able to confirm that this is indeed responsible, but there is a good chance.

Might I suggest using:
FMLInterModComms.sendMessage( "chiselsandbits", "ignoreblocklogic", "[myBlockName]" );

to force glass compatibility?
