### ISSUE TITLE
RFTools Builder places undefined flower

### ISSUE THREAD

**Issue by IeuanK** [Vazkii/Botania#2334]
![image](https://user-images.githubusercontent.com/1075598/29245579-7b1cabf2-7fde-11e7-911f-2e415ca1098d.png)

Was going to see if I could place Pure Daisies on just the dirt (which would make automating Hydroangeas super easy) but instead it just dropped two pure daisies and two undefined flowers in the far corner. Seems like an issue with RFTools not placing items correctly, but your mod told me to report it so that's what I'm doing. Let me know if I need to submit a bug report for RFTools on this instead

**Comment by williewillus** [comment]
hmm so it worked for some of them but not for some others? weird
I looked and RFTools does the proper things for custom itemblocks, so this should work. Not sure what's up

**Comment by IeuanK** [comment]
Yep, does not seem to have any issues whatsoever with most custom blocks/TEs, just Botania flowers..
