### ISSUE TITLE
Vanir representation

### ISSUE THREAD

**Issue by Umber0010** [Vazkii/Botania#2336]
so something that's been bothering me for a while is that Botania, a nature- based mod with HEAVY references to the Norse Mythos, has almost no representation of the Vanir. now for those who don't keep up with Norse Mythology, there are 2 clans of Norse gods, and Aesir, which include Odin, Thor, Tyr, Loki, ect, and are often associated with War and such, while the Vanmir, containing gods and goddeses such as Frey, Freya (yes they are twins)  and there father Njörðr. they are often associated with Nature, wisdom, and fertility. things that perfectally fit the theme of Botania.

as for what I would do for said representation, I don't know enough about Norse Mythology to give many suggestions, but I have a few ideas

-sumarbrandar, the former sacred blade of Frey, he had given it to his messenger and it is profocised that he will die for that. perhaps give it a decent attack damage, and make it do magic damage like splash potions. also, it should talk if you rename it Jack in an anvil (let's see how many of you get the reference)
-Freya's Carriage, a flying carriage pulled by cats, (no really, that's a thing) would be good for long-distance travel, but can't use items while flying 
-honestly, probably some rings or something, I probably should have thought these through more, but I just wanted to put some examples out there.

**Comment by yrsegal** [comment]
Addons already do this~

Namely, Natural Pledge adds an entire section of the mod dedicated to Njord.

**Comment by williewillus** [comment]
not happening in the near future, try out some addons instead ^
