### ISSUE TITLE
Alchemy Catalyst voids anything thrown into it

### ISSUE THREAD

**Issue by gerhard2202** [Vazkii/Botania#2337]
Currently compiled and testing out the 1.12 version. Am on this version:
https://github.com/Vazkii/Botania/commit/7ff0fd2d18eff4f055f33f3109b19323c0b5c158

Made an alchemy catalyst pool, threw my tablet on to it to fuel it, and it just ate my tablet.
Tried to create melon seeds from beetroot seeds, also got nothing back.

Seems to just void items thrown into it regardless of whether a valid transmutation is available. Possibly the reason behind #2258.

**Comment by gerhard2202** [comment]
Did some investigation into this and figured out the issue. The Mini Flower recipes are being registered as having both an input and output of Air blocks, and this is interfering with all other alchemy recipes.

The `ofType` method in `ItemBlockSpecialFlower` calls `new ItemStack(ModBlocks.specialFlower)`. This eventually calls `getItemFromBlock(botania:specialflower)`.

The problem, however, is that when registering the mini flowers (and probably when using any Botania block as an ingredient in mana pool crafting if I understand the issue correctly), the recipe is being registered before the `Item.BLOCK_TO_ITEM` map is populated with Botania's entries, resulting in `ofType` returning Air blocks instead of the correct ingredients.

I was able to fix this by moving the call of `initTileEntities()` from the end of `ModBlocks.registerBlocks` to the end of `ModBlocks.registerItemBlocks`. I'm not sure if there is a better place to put this method or if this change could have other, breaking impacts, so I won't make a PR for it, but it seems that the issue is entirely fixed by not calling `initTileEntities` until `registerItemBlocks` has been called.

**Comment by williewillus** [comment]
that seems like a reasonable fix, you can make a PR for it
