### ISSUE TITLE
 Crash in 1.11.2 Botania r1.9 - 345

### ISSUE THREAD

**Issue by karikusa** [Vazkii/Botania#2343]
Hello, everyone in the Botanist! Probably, because it caused a buggy crash on a floating flower, I will report it for the time being!
After crashing I got crashed as soon as I entered the world and I could not recover ... XD
Perhaps I pulled out Optifine and it was able to enter the world at first, so it seems that it improved if I removed the floating flowers.
It may be a difficult problem because we could not reproduce the same crash even if we installed floating flowers in Creative World ...
[crash-2017-08-30_09.55.31-client.txt](https://github.com/Vazkii/Botania/files/1262165/crash-2017-08-30_09.55.31-client.txt)

**Comment by karikusa** [comment]
I tried it in the creative world to reproduce bugs from that.
I understand it so I will report it!
The condition seems to be when you installed vanilla logs within the effect range of suspended pure daisy.
It seemed to be OK if it was Pure Daisy set up in the dart.

**Comment by williewillus** [comment]
another mod is interfering with the floating flower's rendering. in this case, it appears to be some sort of connected textures mod (CTM or optifine?). I don't think it's a botania issue
