### ISSUE TITLE
[1.12.1] Crash when rejoining world

### ISSUE THREAD

**Issue by EmosewaGamer** [Vazkii/Botania#2348]
So I added Botania to my pack, so I wanted to test it and see what is new in the 1.12 version. When I tried opening my old test world (that was made before I added Botania):

- I got a warning about the world being corrupted

- I got this crash: https://pastebin.com/EXYugxwd

It does not happen on worlds created after Botania was added.

**Comment by Vazkii** [comment]
Looks like some sort of ID desync. Did you remove any mods prior to adding
botania?

**Comment by EmosewaGamer** [comment]
Nope. That'swhy I assumed that it had to do with Botania.

**Comment by Vazkii** [comment]
Can you reproduce this in that world every time?

**Comment by williewillus** [comment]
also, are you trying to upgrade a pre-1.12 world to 1.12? Forge had some pretty deep registry changes

**Comment by EmosewaGamer** [comment]
Welp, I rejoined the world and it was actually corrupted. Many modded blocks were replaced by Botania blocks. However, after a minute I got the same crash.

**Comment by EmosewaGamer** [comment]
@williewillus I did not. It was just a 1.12.1 modded world to which I simply added Botania.

**Comment by EmosewaGamer** [comment]
Welp, I tested another world where I had blocks from all the mods laid out. I still don't get how my world randomly got corrupted.
