### ISSUE TITLE
[Suggestion} Configurable Orechid

### ISSUE THREAD

**Issue by EmosewaGamer** [Vazkii/Botania#2349]
Many times when making a pack the Orechids have been an issue for me as they allow the player to get ores he's not supposed to easily (in terms of the progression of the pack) get. So that's why I'm suggesting a config option to either disable it or to either blacklist some of the ores it can generate, as just having it generate early-game ores isn't an issue.

**Comment by Exxudus** [comment]
That would be great, white and black listing would be awesome

**Comment by Vazkii** [comment]
ModTweaker can do this.
