### ISSUE TITLE
Botania 346 crash with Albedo 0.1

### ISSUE THREAD

**Issue by quat1024** [Vazkii/Botania#2350]
Game crashes on startup before reaching the main menu with Botania 346, Baubles 1.5.1, and Albedo 0.1. Crashlog: https://paste.ee/p/lFWRz#s=0&l=166

Minecraft 1.12.1, Forge 14.22.0.2467, AMD Radeon 6800 graphics card.

Disclaimer - I had to modify Albedo to get it to run on my PC https://github.com/elucent/Albedo/issues/1 . This is probably my fault, caused by me not repacking the Albedo jar properly or something. I don't really know what I'm doing.

**Comment by Vazkii** [comment]
Yeah, I can't really support you if you're using a custom jar.

If anyone else with a stock one can reproduce this I'll have a look.
