### ISSUE TITLE
[ 1.11.2 and 1.12.1 ]plants supporting magic bees bugged

### ISSUE THREAD

**Issue by mickwok** [Vazkii/Botania#2352]
I was trying to test the 3  plants added by Botania , but I found out that 3 plants are either missing texture or in poppy texture ( https://imgur.com/w9JVsZS ) . 

Furthermore , when I using the Hiveacynth , I've also found that it never spawn marshy bees and valiant bees. 

This bug happened both 1.12 and 1.11 
version

FML Log: https://pastebin.com/JEUBV4iP

**Comment by EmosewaGamer** [comment]
They aren't from Bortania, they're from Magic Bees.
