### ISSUE TITLE
[1.12] Iridium ore with Orechid

### ISSUE THREAD

**Issue by Skillotic0703** [Vazkii/Botania#2353]
Could you add oreIridium to the Orechid please?

**Comment by KingDGrizzle** [comment]
Isn't iridium ore an item and not a block?

Afaik, iridium can only be found through dungeon loot, and made with uu. Am i wrong?

**Comment by Skillotic0703** [comment]
ThermalFoundation now has an Iridium Ore block and it's compatible with mods that use Iridium!

**Comment by Skillotic0703** [comment]
Did you add it?

**Comment by Skillotic0703** [comment]
Iridium ore block is also added by TechReborn!

**Comment by Vazkii** [comment]
You can add in your own ores using ModTweaker.

**Comment by Skillotic0703** [comment]
I didn't know that modtweaker had support for Botania in 1.12
