### ISSUE TITLE
In-game vanilla crafting guide displays wrong crafting shapes

### ISSUE THREAD

**Issue by ShySkream** [Vazkii/Botania#2354]
Botania version:  R1.10-346
Forge version:  forge-1.12.1-14.22.0.2469
Fresh install of only Botania, Baubles and Forge.

I noticed the in-game vanilla crafting guide (green book icon) has the wrong recipes for various things, showing the right ingredients in the wrong locations.  The items I noticed are the pestle & mortar and terra blade.  I then noticed the pestle & mortar recipe changed, to another wrong recipe. however I have no idea what caused them to change as rebooting the game and even using a different Minecraft profile appears to show the same results now.  

I made a fresh install of forge with the bare minimum for Botania to make sure it wasn't another mod in my pack causing it.  I have not found it happening to any vanilla items, 
Recipes shown:  https://puu.sh/xr4xv/c885e6a2eb.png

FML log:  https://puu.sh/xr3Z7/f13667b8d3.log

**Comment by Vazkii** [comment]
Now this is pretty weird. Any fancy stuff you did that could cause this @williewillus?

**Comment by williewillus** [comment]
@ShySkream but does the actual recipe itself have the right shape?

**Comment by williewillus** [comment]
just checked myself, the actual recipe is correct, and it also shows correctly in JEI. I suspect forge patches have introduced a bug, but not sure yet.

**Comment by williewillus** [comment]
does this happen if you update to a forge higher than 2462?

**Comment by williewillus** [comment]
this is https://github.com/MinecraftForge/MinecraftForge/issues/4088

**Comment by williewillus** [comment]
also seems like it's fixed in newer forge
