### ISSUE TITLE
Botania/Albedo crash

### ISSUE THREAD

**Issue by gilfort** [Vazkii/Botania#2356]
My instance just crashed, caused by shooting a manaburst from the terrablade. 
https://paste.ee/p/af6u2

Botania version: r1.10-346
Albedo version: 0.1
Forge: 1.12.1 - 14.22.0.2467

**Comment by quat1024** [comment]
cannot reproduce with Albedo 0.1.1

**Comment by Vazkii** [comment]
Yeah, use 0.1.1.

**Comment by gudenau** [comment]
Was just about to make an issue, too bad it does not show up on Curse for some reason...
