### ISSUE TITLE
[1.12] Curse Launcher Missing 1.12 version...intentional?

### ISSUE THREAD

**Issue by MokahTGS** [Vazkii/Botania#2358]
Does the 1.12.1 version work with 1.12 and if so can you update the Curse entry to make the launcher see it for 1.12 mod packs?  If not can you please upload a dedicated 1.12 version so we can add Botania to our 1.12 mod packs.

**Comment by Vazkii** [comment]
It was built for 1.12.1, but it should run in 1.12. I'll add the version to the file info, but I can't ensure it'll work 100%

**Comment by MokahTGS** [comment]
Yeah it doesn't work in 1.12.  It says that 1.12.1 is required.  Any chance this could be changed or an actual 1.12 version be made.  1.12.1 is missing so many mods.

**Comment by williewillus** [comment]
1.12 mods should work on 1.12.1 unchanged though, and it's more likely modders mark 1.12 -> 1.12.1 than the other way around

**Comment by MokahTGS** [comment]
Well should and do are two different things.   I'm telling you that this does not.  The game does not launch and complains that the mod requires 1. 12. 1 to function.   It would be very nice of it did however.
