### ISSUE TITLE
In-game update downloader just downloads a 303 See Other error

### ISSUE THREAD

**Issue by quat1024** [Vazkii/Botania#2359]
I hit Update in-game to download the latest botania version today and got a 338 byte jar. Hmm.

When I opened the jar in Notepad, turns out it really just contains:
```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>303 See Other</title>
</head><body>
<h1>See Other</h1>
<p>The answer to your request is located <a href="https://botaniamod.net/files/Botania%20r1.10-347.jar">here</a>.</p>
<hr>
<address>Apache/2.4.7 (Ubuntu) Server at botaniamod.net Port 80</address>
</body></html>
```

**Comment by Vazkii** [comment]
Ah yes, the downloader currently does not handle redirection, and since I added redirection to force https, well, that happens. Thanks for pointing it out.
