### ISSUE TITLE
[1.12.1] You can place ladders on ALL THE THINGS.

### ISSUE THREAD

**Issue by quat1024** [Vazkii/Botania#2365]
You've probably heard that 1.12 tweaked the way ladders are placed and fences connect to blocks. They did this with block face shapes - anything that returns `BlockFaceShape.SOLID` from the `Block.getBlockFaceShape` method from the appropriate side will have ladders placed, snow layers atop, and fenceposts connect against that side.

Well guess what the default return value in `getBlockFaceShape` is.

![image](https://user-images.githubusercontent.com/2068021/30223447-e107d6e8-9498-11e7-9f0f-74f4beb164ba.png)

I fixed this in my mod by just returning `BlockFaceShape.UNDEFINED` from that method.

**Comment by williewillus** [comment]
/me mutters about how dumb `BlockFaceShape` is
