### ISSUE TITLE
Switching a corporea spark to another network causes it to not connect until chunk reload

### ISSUE THREAD

**Issue by quat1024** [Vazkii/Botania#2368]
Botania 347 for Minecraft 1.12.

This is a bit hard to explain so bear with me. Video inside.

Switching a corporea spark that is part of a valid network from one color to another, causes it to not connect to the new network.

1. Create two corporea master sparks. (I used white and magenta.) Add some chests or whatever to the white network.

2. Apply magenta floral powder to some of the sparks. They do NOT become part of the magenta network.

3. Relog. Now the sparks are part of the magenta network.

That probably made 0 sense! So have a video instead! https://youtu.be/FjAhTvJYz9E

Some things to note: 
* Note that when you place a spark that is NOT part of a network and dye it, it connects fine and does not need a chunk reload. The bug only happens when you switch a spark *out* of an existing network.
* It's not just a visual glitch, the spark is really not connected. You can see that with a crystal cube or something - it won't be able to read from the glitched spark.
* This applies to all things that can accept a corporea spark (not just chests or containers)
* This bug is particularly annoying when creating multi-network systems where one of the colors is white.

**Comment by codycoolwaffle** [comment]
It gets disconnected from the previous network, but doesn't sync with the new network, likely having to do with something in the way they initially connect. Through some more testing I found that if you add a new spark to the network with the glitched spark(s), it connects them to the network.
