### ISSUE TITLE
Big Boom > Thorn Chakram

### ISSUE THREAD

**Issue by SteptimusHeap** [Vazkii/Botania#2369]
so apparently a creeper can destroy a Thorn Chakram thrown at him if he explodes. it just get destroyed like any item would. which i don't think is fair.

**Comment by williewillus** [comment]
I think this is reasonable

**Comment by Vazkii** [comment]
I disagree.

**Comment by SteptimusHeap** [comment]
I mean it's not much work to get a new one, but I still don't believe that's right. If a creeper starts to explode nest to you, what do you do? You attack him, but then he blows up your weapon, imagine that if you hit him with a sword while he was exploding he destroyed your sword.

**Comment by SteptimusHeap** [comment]
I know that this probably wasn't an intentionaI feature, but it needs to b a dressed either way.

**Comment by williewillus** [comment]
I was thinking of how a ring of vines could ever stop a creeper explosion but whatever :P

**Comment by williewillus** [comment]
I was thinking of how a ring of vines could ever stop a creeper explosion but whatever :P
