### ISSUE TITLE
Floating Endoflames not picking up fuel

### ISSUE THREAD

**Issue by lrwerewolf** [Vazkii/Botania#2373]
I have tried a number of contraptions trying to feed a huge hedge of floating endoflames, but none seem to be working.  In one instance, one out of 14 endoflames in the test build worked but the remaining 13 did not.  This was true even when I dropped the block of coal directly on top of the central most one, well within range of all of them.  This is impacting r1.10-347, MC 1.12.1, running forge 14.22.0.2469

**Comment by williewillus** [comment]
Update forge to >= 2475 or downgrade to <= 2449 (https://github.com/MinecraftForge/MinecraftForge/issues/4386)

**Comment by lrwerewolf** [comment]
Negative on close.  The referenced ticket is unrelated.

**Comment by williewillus** [comment]
Is this with botania alone?
Can anyone else reproduce this?

**Comment by lrwerewolf** [comment]
Further testing revealed the cause -- earlier versions did not require me to have the endoflame connected to a mana spreader or equiv before they would consume fuel.  It seems this is now required.  Not sure if this change is intentional or not, but it does resole the issue I was seeing.  Please mark this accordingly and leave it closed.
