### ISSUE TITLE
Redstone dust points towards flowers visually, but not logically

### ISSUE THREAD

**Issue by quat1024** [Vazkii/Botania#2375]
Botania 347.

Redstone dust orients itself visually to point towards Botania flowers, however, it doesn't actually power them.

For example, this hopperhock can still pick up items, even though it looks like it's disabled with the redstone dust: 
![image](https://user-images.githubusercontent.com/2068021/30252925-e6b7790c-9648-11e7-9121-3b9719add2b0.png)

**Comment by williewillus** [comment]
Most likely the same thing as #2365

**Comment by codycoolwaffle** [comment]
The problem is it requires a direct signal, like forcing redstone one-way, or using a repeater. The connecting likely has to do with #2365 but the interaction still works, like a piston. Not sure if the piston, redstone is intended.

**Comment by codewarrior0** [comment]
I remember fixing something similar in GregTech 5 for 1.10, let me go find it...

[Here it is.](https://github.com/Blood-Asp/GT5-Unofficial/pull/870). Two things were causing Redstone to connect: `canProvidePower()` always returning True, and `canConnectRedstone()` always returning True. I followed the Vanilla rule of "Redstone emitters connect, redstone consumers don't" and changed them to only connect according to which covers are installed on the machine.
