### ISSUE TITLE
[Request] Additional config option steel ingots/blocks to manasteel

### ISSUE THREAD

**Issue by b0bst3r** [Vazkii/Botania#2377]
Hi

Is it easy to add an additional config option for us pack makers to change iron>manasteel to steel>manasteel?

I know a few pack makers who minetweak this in everytime and it would make things so much easier to have a config option within the mod instead. 

- change manasteel to steel ingots/blocks instead of iron (false by default)
manasteel=true

Please

Regards
b0b

**Comment by williewillus** [comment]
minetweaker is the better option here. 
it's unsustainable for us to have to add a mod config option for every single alternate material out there that people want to use, when minetweaker can make the edit in a clean and simple way without cluttering the config file.

**Comment by EmosewaGamer** [comment]
There's no Botania support for 1.12, nor 1.11. That is the issue!

**Comment by Vazkii** [comment]
Well, you have to wait on ModTweaker.

**Comment by EmosewaGamer** [comment]
Well in theory we the need to wait for someone to make a pull request as lately every mod integration has been added via pull request. The problem is that none of the people that need it know how to.
