### ISSUE TITLE
NPE during game initialization and world creation.

### ISSUE THREAD

**Issue by PsiGuy60** [Vazkii/Botania#2379]
During the initialization phase, the game will often throw a NPE saying something about Manasteel.HasArmorSetItem before crashing. The stacktrace almost exclusively mentions Botania as well.

It also happens during world creation, with the same stacktrace, but instead of crashing outright the game will lock up.

[Link to last crash log.](https://pastebin.com/tGHLd6YK)

This happens regardless of other mods installed. Latest versions of Forge, AutoRegLib, Botania and Baubles.

**Comment by PsiGuy60** [comment]
ADDENDUM: I initially thought it only occurred with other mods installed. It doesn't - I just got the same exact crash with just Botania and its dependencies.

**Comment by PsiGuy60** [comment]
That wasn't a fix, unfortunately. I just had another crash.

[Log here.](https://pastebin.com/hRUduNzw)

**Comment by Vazkii** [comment]
🤔

**Comment by williewillus** [comment]
can anyone else reproduce this?

**Comment by PsiGuy60** [comment]
I dunno, but according to the log it's now complaining about the same method in Terrasteel.

I think the null checks do fix it, they just need to be repeated for the other armor pieces.
