### ISSUE TITLE
[1.12.1] Pack Loading 

### ISSUE THREAD

**Issue by DaggerTM** [Vazkii/Botania#2383]
I get a crash when I load a custom modpack. 

Minecraft: 1.12.1
Forge: 14.22.0.2481
Botania: r1.10-347 

Crash:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ForgelinPlugin (Forgelin-1.5.1.jar)
  FarseekCoreMod (Farseek-1.12-2.2.jar)
  EcomodLoadingPlugin (EcologyMod-1.12.1-1.1.1.0.jar)
  IELoadingPlugin (ImmersiveEngineering-0.12-72-core.jar)
  LoadingPlugin (Quark-r1.3-109.jar)
  LoadingPlugin (Bloodmoon-MC1.12-1.5.1.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63+beta.108.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.7.4-1.12-anarchy.jar)
  AppleCore (AppleCore-mc1.12.1-2.2.2.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.2.jar)
  CTMCorePlugin (CTM-MC1.12-0.2.2.7.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  Plugin (NotEnoughIDs-1.5.4.1.jar)
Contact their authors BEFORE contacting forge

// Why is it breaking :(

Time: 9/16/17 2:56 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Botania (botania)
Caused by: java.lang.NoClassDefFoundError: vazkii/botania/api/item/TinyPotatoRenderEvent
	at vazkii.botania.client.core.proxy.ClientProxy.initRenderers(ClientProxy.java:210)
	at vazkii.botania.client.core.proxy.ClientProxy.preInit(ClientProxy.java:164)
	at vazkii.botania.common.Botania.preInit(Botania.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:609)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:253)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:231)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:604)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:266)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: vazkii.botania.api.item.TinyPotatoRenderEvent
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 43 more
Caused by: java.lang.SecurityException: class "vazkii.botania.api.item.TinyPotatoRenderEvent"'s signer information does not match signer information of other classes in the same package
	at java.lang.ClassLoader.checkCerts(ClassLoader.java:895)
	at java.lang.ClassLoader.preDefineClass(ClassLoader.java:665)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:758)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 45 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 905363352 bytes (863 MB) / 2604662784 bytes (2484 MB) up to 5488246784 bytes (5234 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5888m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.41 Powered by Forge 14.22.1.2481 Optifine OptiFine_1.12.1_HD_U_C5 109 mods loaded, 109 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                       | Version                 | Source                                          | Signature                                |
	|:----- |:------------------------ |:----------------------- |:----------------------------------------------- |:---------------------------------------- |
	| UCH   | minecraft                | 1.12.1                  | minecraft.jar                                   | None                                     |
	| UCH   | mcp                      | 9.19                    | minecraft.jar                                   | None                                     |
	| UCH   | FML                      | 8.0.99.99               | forge-1.12.1-14.22.1.2481.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge                    | 14.22.1.2481            | forge-1.12.1-14.22.1.2481.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | ivtoolkit                | 1.3.3-1.12              | minecraft.jar                                   | None                                     |
	| UCH   | foamfixcore              | 7.7.4                   | minecraft.jar                                   | None                                     |
	| UCH   | simplebedrolls           | 1.2.1                   | [1.12]SimpleBedrolls-1.2.1.jar                  | None                                     |
	| UCH   | abilstones               | 12.2.0.0                | Ability.Stones.12.2.0.0.jar                     | None                                     |
	| UCH   | crafttweaker             | 4.0.6                   | CraftTweaker2-1.12-4.0.6.jar                    | None                                     |
	| UCH   | mtlib                    | @VERSION@               | MTLib-3.0.0.jar                                 | None                                     |
	| UCH   | modtweaker               | 4.0.2                   | modtweaker-4.0.2.jar                            | None                                     |
	| UCH   | jei                      | 4.7.8.95                | jei_1.12.1-4.7.8.95.jar                         | None                                     |
	| UCH   | abyssalcraft             | 1.9.4-pre-4             | AbyssalCraft-1.12-1.9.4-pre-4.jar               | None                                     |
	| UCH   | applecore                | 2.2.2                   | AppleCore-mc1.12.1-2.2.2.jar                    | None                                     |
	| UCH   | chisel                   | MC1.12-0.0.14.18        | Chisel-MC1.12-0.0.14.18.jar                     | None                                     |
	| UCH   | mantle                   | 1.12-1.3.1.21           | Mantle-1.12-1.3.1.21.jar                        | None                                     |
	| UCH   | tconstruct               | 1.12-2.7.3.30           | TConstruct-1.12-2.7.3.30.jar                    | None                                     |
	| UCH   | theoneprobe              | 1.4.18                  | theoneprobe-1.12-1.4.18.jar                     | None                                     |
	| UCH   | immersiveengineering     | 0.12-72                 | ImmersiveEngineering-0.12-72.jar                | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| UCH   | betterwithmods           | 1.2.9-1.11.2            | BetterWithMods-1.12-2.0.10.jar                  | None                                     |
	| UCH   | appleskin                | 1.0.8                   | AppleSkin-mc1.12-1.0.8.jar                      | None                                     |
	| UCH   | architecturecraft        | @VERSION@               | architecturecraft-1.12-1.20.jar                 | None                                     |
	| UCH   | quark                    | r1.3-109                | Quark-r1.3-109.jar                              | None                                     |
	| UCH   | autoreglib               | 1.3-13                  | AutoRegLib-1.3-13.jar                           | None                                     |
	| UCH   | baubles                  | 1.5.1                   | Baubles-1.12-1.5.1.jar                          | None                                     |
	| UCH   | betterbuilderswands      | 0.11.1                  | BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar | None                                     |
	| UCH   | bibliocraft              | 2.4.3                   | BiblioCraft[v2.4.3][MC1.12.0].jar               | None                                     |
	| UCH   | biomesoplenty            | 7.0.0.2291              | BiomesOPlenty-1.12-7.0.0.2291-universal.jar     | None                                     |
	| UCH   | blockarmor               | 2.4.8                   | BlockArmor-1.12-2.4.8.jar                       | None                                     |
	| UCH   | bloodmoon                | 1.5.1                   | Bloodmoon-MC1.12-1.5.1.jar                      | None                                     |
	| UCH   | bonfires                 | 1.1.2                   | Bonfires-1.12-1.1.2.jar                         | None                                     |
	| UCE   | botania                  | r1.10-347               | Botania r1.10-347.jar                           | None                                     |
	| UCH   | codechickenlib           | 3.1.2.297               | CodeChickenLib-1.12-3.1.2.297-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | redstoneflux             | 2.0.1                   | RedstoneFlux-1.12-2.0.1.2-universal.jar         | d4f1503fbacd9b9fb767720420c5395104239ec9 |
	| UCH   | brandonscore             | 2.3.2                   | BrandonsCore-1.12-2.3.2.129-universal.jar       | None                                     |
	| UCH   | bullseye                 | 3.0.3                   | Bullseye-1.12-3.0.3.jar                         | None                                     |
	| UCH   | canijoinnow              | @VERSION@               | CanIJoinNow-1.12.1-1.1-3.jar                    | None                                     |
	| UCH   | chesttransporter         | 2.8.7                   | ChestTransporter-1.12-2.8.7.jar                 | None                                     |
	| UCH   | chiselsandbits           | 14.7                    | chiselsandbits-14.7.jar                         | None                                     |
	| UCH   | cyclopscore              | 0.10.17                 | CyclopsCore-1.12-0.10.17.jar                    | None                                     |
	| UCH   | commoncapabilities       | 1.4.0                   | CommonCapabilities-1.12-1.4.0.jar               | None                                     |
	| UCH   | cookingforblockheads     | 6.3.6                   | CookingForBlockheads_1.12.1-6.3.6.jar           | None                                     |
	| UCH   | corpsecomplex            | 1.0.0                   | corpsecomplex-1.12.1-1.0.0.jar                  | None                                     |
	| UCH   | ctgui                    | 1.0.0                   | CraftTweaker2-1.12-4.0.6.jar                    | None                                     |
	| UCH   | crafttweakerjei          | 2.0.0                   | CraftTweaker2-1.12-4.0.6.jar                    | None                                     |
	| UCH   | croparia                 | 1.14.1                  | Croparia 1.12-1.14.3.jar                        | None                                     |
	| UCH   | ctm                      | MC1.12-0.2.2.7          | CTM-MC1.12-0.2.2.7.jar                          | None                                     |
	| UCH   | cucumber                 | 1.0.2                   | cucumber[1.12]-1.0.2.jar                        | None                                     |
	| UCH   | custommainmenu           | 2.0.7                   | CustomMainMenu-MC1.12.1-2.0.7.jar               | None                                     |
	| UCH   | cyclicmagic              | 1.8.3                   | Cyclic-1.12-1.8.3.jar                           | None                                     |
	| UCH   | defiledlands             | 0.3.0                   | defiledlands-1.12.1-0.3.0.jar                   | None                                     |
	| UCH   | draconicevolution        | 2.3.3                   | Draconic-Evolution-1.12-2.3.3.261-universal.jar | None                                     |
	| UCH   | ecomod                   | 1.12.1-1.1.1.0          | EcologyMod-1.12.1-1.1.1.0.jar                   | None                                     |
	| UCH   | extendedcrafting         | 1.0.1                   | extendedcrafting[1.12]-1.0.1.jar                | None                                     |
	| UCH   | extrabitmanipulation     | 1.12-3.2.1              | ExtraBitManipulation-1.12-3.2.1.jar             | None                                     |
	| UCH   | farseek                  | 2.2                     | Farseek-1.12-2.2.jar                            | None                                     |
	| UCH   | firstaid                 | 1.1.1                   | firstaid-1.1.1.jar                              | None                                     |
	| UCH   | foamfix                  | @VERSION@               | foamfix-0.7.4-1.12-anarchy.jar                  | None                                     |
	| UCH   | forgelin                 | 1.5.1                   | Forgelin-1.5.1.jar                              | None                                     |
	| UCH   | mcmultipart              | 2.2.2                   | MCMultiPart-2.2.2.jar                           | None                                     |
	| UCH   | ftbl                     | 0.0.0                   | FTBLib-4.1.3.jar                                | None                                     |
	| UCH   | ftbu                     | 0.0.0                   | FTBUtilities-4.1.3.jar                          | None                                     |
	| UCH   | ftbg                     | 1.12.1-1.0.01           | ftbg-1.121.-1.0.0.jar                           | None                                     |
	| UCH   | fp                       | 26.2.6                  | Futurepack-1.12.1-26.2.6.jar                    | None                                     |
	| UCH   | fp.api                   | 1.1.0                   | Futurepack-1.12.1-26.2.6.jar                    | None                                     |
	| UCH   | guideapi                 | 1.12-2.1.4-57           | Guide-API-1.12-2.1.4-57.jar                     | None                                     |
	| UCH   | immersivetech            | 1.3.2                   | immersivetech-1.12-1.3.2.jar                    | None                                     |
	| UCH   | teslacorelib             | 1.0.8                   | tesla-core-lib-1.12-1.0.8.jar                   | None                                     |
	| UCH   | industrialforegoing      | 1.12-1.12               | industrialforegoing-1.12-1.2.1-48.jar           | None                                     |
	| UCH   | integrateddynamics       | 0.9.0                   | IntegratedDynamics-1.12-0.9.0.jar               | None                                     |
	| UCH   | integrateddynamicscompat | 1.0.0                   | IntegratedDynamics-1.12-0.9.0.jar               | None                                     |
	| UCH   | integratedtunnels        | 1.3.2                   | IntegratedTunnels-1.12-1.3.2.jar                | None                                     |
	| UCH   | integrationforegoing     | 1.12-1.0                | IntegrationForegoing-1.12-1.0.jar               | None                                     |
	| UCH   | inventorypets            | 1.4.9.8                 | inventorypets-1.12-1.4.9.8.jar                  | None                                     |
	| UCH   | inventorytweaks          | 1.63+beta.108.6ff67c4   | InventoryTweaks-1.63+beta.108.jar               | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCH   | journeymap               | 1.12.1-5.5.0b4          | journeymap-1.12.1-5.5.0b4.jar                   | None                                     |
	| UCH   | justanothersnad          | 1.12-1.0.0.0            | JustAnotherSnad-1.12-1.0.0.0.jar                | None                                     |
	| UCH   | lostcities               | 1.0.0                   | lostcities-1.12-1.0.0.jar                       | None                                     |
	| UCH   | lostsouls                | 1.0.0                   | lostsouls-1.12-1.0.0.jar                        | None                                     |
	| UCH   | magicalwings             | 1.0                     | magicalwings-1.2.jar                            | None                                     |
	| UCH   | modelloader              | 1.0.5                   | modelloader-1.0.5.jar                           | None                                     |
	| UCH   | magneticraft             | 2.0.0                   | Magneticraft_1.12-2.0.0.jar                     | None                                     |
	| UCH   | modnametooltip           | 1.9.0                   | modnametooltip_1.12.1-1.9.0.jar                 | None                                     |
	| UCH   | morpheus                 | 1.12-3.3.2              | Morpheus-1.12-3.3.2.jar                         | None                                     |
	| UCH   | mousetweaks              | 2.8                     | MouseTweaks-2.8-mc1.12.1.jar                    | None                                     |
	| UCH   | neid                     | 1.5.4.1                 | NotEnoughIDs-1.5.4.1.jar                        | None                                     |
	| UCH   | oreberries               | 0.2.0                   | oreberries-1.12.x-0.2.0.jar                     | None                                     |
	| UCH   | plustic                  | 6.3.1.2                 | plustic-6.3.1.2.jar                             | None                                     |
	| UCH   | quacklib                 | 1.1.1                   | quacklib-1.1.1.jar                              | None                                     |
	| UCH   | quickleafdecay           | 1.2.4                   | QuickLeafDecay-MC1.12.1-1.2.4.jar               | None                                     |
	| UCH   | reccomplex               | 1.4.5                   | RecurrentComplex-1.4.5.jar                      | None                                     |
	| UCH   | refinedstorage           | 1.5.18                  | refinedstorage-1.5.18.jar                       | None                                     |
	| UCH   | resourceloader           | 1.5.3                   | ResourceLoader-MC1.12.1-1.5.3.jar               | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| UCH   | retrocomputers           | 1.1.3                   | RetroComputers-1.1.3.jar                        | None                                     |
	| UCH   | roots                    | 0.025                   | roots-2-0.025.jar                               | None                                     |
	| UCH   | roughmobs                | 1.0                     | roughMobs1.0.13-1.12.1.jar                      | None                                     |
	| UCH   | rustic                   | 0.4.2.1                 | rustic-0.4.3.jar                                | None                                     |
	| UCH   | shetiphiancore           | 3.5.2                   | shetiphiancore-1.12.0-3.5.2.jar                 | None                                     |
	| UCH   | streams                  | 0.4                     | Streams-1.12-0.4.jar                            | None                                     |
	| UCH   | teckle                   | 1.12.1                  | teckle-1.12-5.394.jar                           | None                                     |
	| UCH   | terraqueous              | 1.4.3                   | terraqueous-1.12.0-1.4.3.jar                    | None                                     |
	| UCH   | tinkertoolleveling       | 1.12-1.0.2b.DEV.1a79301 | TinkerToolLeveling-1.12-1.0.2b.jar              | None                                     |
	| UCH   | tombmanygraves           | @VERSION@               | TombManyGraves-1.12-4.0.1.jar                   | None                                     |
	| UCH   | topaddons                | 1.12-0.15.1             | topaddons-1.12-0.15.1.jar                       | None                                     |
	| UCH   | universalremote          | 1.12-0.9.3              | UniversalRemote-1.12-0.9.3.jar                  | None                                     |
	| UCH   | va                       | 1.12.1-1.3              | va-1.12.1-1.3.jar                               | None                                     |
	| UCH   | wificharge               | 1.0.1                   | WirelessCharger-1.0.1.jar                       | None                                     |
	| UCH   | yabba                    | 1.12-1.0.2              | YABBA-1.12-1.0.2.jar                            | None                                     |
	| UCH   | teslacorelib_registries  | 1.0.8                   | tesla-core-lib-1.12-1.0.8.jar                   | None                                     |

	Loaded coremods (and transformers): 
ForgelinPlugin (Forgelin-1.5.1.jar)
  
FarseekCoreMod (Farseek-1.12-2.2.jar)
  farseek.core.FarseekClassTransformer
EcomodLoadingPlugin (EcologyMod-1.12.1-1.1.1.0.jar)
  ecomod.asm.EcomodClassTransformer
IELoadingPlugin (ImmersiveEngineering-0.12-72-core.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
LoadingPlugin (Quark-r1.3-109.jar)
  vazkii.quark.base.asm.ClassTransformer
LoadingPlugin (Bloodmoon-MC1.12-1.5.1.jar)
  lumien.bloodmoon.asm.ClassTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.63+beta.108.jar)
  invtweaks.forge.asm.ContainerTransformer
Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.7.4-1.12-anarchy.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
AppleCore (AppleCore-mc1.12.1-2.2.2.jar)
  squeek.applecore.asm.TransformerModuleHandler
LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  lumien.resourceloader.asm.ClassTransformer
ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.2.jar)
  shetiphian.asm.ClassTransformer
CTMCorePlugin (CTM-MC1.12-0.2.2.7.jar)
  team.chisel.ctm.client.asm.CTMTransformer
IvToolkit (IvToolkit-1.3.3-1.12.jar)
  
Plugin (NotEnoughIDs-1.5.4.1.jar)
  ru.fewizz.neid.asm.Transformer
	GL info: ' Vendor: 'Intel' Version: '3.1.0 - Build 9.17.10.4459' Renderer: 'Intel(R) HD Graphics'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- theoneprobeIntegration (Enabled/Not Forced)

	OptiFine Version: OptiFine_1.12.1_HD_U_C5
	Render Distance Chunks: 5
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.1.0 - Build 9.17.10.4459
	OpenGlRenderer: Intel(R) HD Graphics
	OpenGlVendor: Intel
	CpuCount: 2

**Comment by williewillus** [comment]
#2380
