### ISSUE TITLE
[1.12.1] [r1.10-347] Render Crash

### ISSUE THREAD

**Issue by GWSheridan** [Vazkii/Botania#2385]
Get this crash while loading up pack during loading phase 
forge version 14.22.1.2481 
minecraft version 1.12.1
Botania r1.10-347

https://pastebin.com/sPYA5dV8

**Comment by BluMasc** [comment]
also got this crash. Tracked it down to the latest version of Immersive Engineering. If you downgrade to version 0.12-71 of IE, it should work.

**Comment by williewillus** [comment]
see #2380
