### ISSUE TITLE
Dreathorne kills baby animals

### ISSUE THREAD

**Issue by Hyro-Shima** [Vazkii/Botania#2393]
Botania version r1.10-347
Forge version 14.22.1.2478

In the latest version (only) baby animals are killed by Dreadthrones.
No other mods are installed.
Can reproduce with all baby animals.

Contact me if more information is required.

**Comment by Hyro-Shima** [comment]
Was this introduced with https://github.com/Vazkii/Botania/commit/eab67fea137bb770d690d73c6cd6ec553084bcbd ?

**Comment by williewillus** [comment]
No, it was actually fixed by eab67fe (this is a duplicate), there just hasn't been a release since then

**Comment by Hyro-Shima** [comment]
Excuse me for this mistake.

**Comment by williewillus** [comment]
No worries
