### ISSUE TITLE
Globetrotters Sash (and possibly lower tiers) prevent critical hits.

### ISSUE THREAD

**Issue by Sanctonis** [Vazkii/Botania#2395]
Tested this out for a while with a friend. No matter the jump height, how low the ground I was or high above it, you cannot perform a critical hit with the extra jump height. The particles show up somewhat but it does not work. 

Reason I know this, is because I have the Wills applied to my Terrasteel helmet, and none of them were applying. The second I took off the sash, I was able to hit him and apply all the effects.

**Comment by codycoolwaffle** [comment]
Odd, it's working fine for me. Do you have any other mods installed, and what version of Botania are you using?

**Comment by Sanctonis** [comment]
@codycoolwaffle I'm currently using Botania in FTB Beyond. May be conflicting with something inside. Not sure what version it is, sorry :s

**Comment by codycoolwaffle** [comment]
Well, it's either compat or it's been fixed, I would recommend reaching out to the FTB team for assistance.

**Comment by codycoolwaffle** [comment]
Just for future reference, do not report bugs from FTB packs here, they are hardly updated, and many bugs that exist there are likely already fixed. Seeing as FTB Beyond is on 1.10, it's outdated. There is currently NO FTB mudpack that uses the most recent version of Botania, and likely never will be.
