### ISSUE TITLE
[CRASH] On startup (issue with Connected Textures Mod)

### ISSUE THREAD

**Issue by armuell** [Vazkii/Botania#2397]
Botania throws an error on startup if Chisel/Connected Textures Mod are in the same pack. Disabling Chisel&CTM makes it so no error is thrown.

Crashlog:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ForgelinPlugin (Forgelin-1.5.1.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  FarseekCoreMod (Farseek-1.12-2.2.jar)
  ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.2.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  CTMCorePlugin (CTM-MC1.12-0.2.3.9.jar)
  BetterFoliageLoader (BetterFoliage-MC1.12-2.1.10.jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.7.2.jar)
  DummyPlugin (ForgeEndertech-1.12-3.0.1.0-build.0012.jar)
  TANLoadingPlugin (ToughAsNails-1.12-3.0.0.64-universal.jar)
  LoadingPlugin (ChunkAnimator-MC1.12-1.2.jar)
Contact their authors BEFORE contacting forge

// Daisy, daisy...

Time: 10/1/17 10:54 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Botania (botania)
Caused by: java.lang.NoClassDefFoundError: vazkii/botania/api/item/TinyPotatoRenderEvent
	at vazkii.botania.client.core.proxy.ClientProxy.initRenderers(ClientProxy.java:210)
	at vazkii.botania.client.core.proxy.ClientProxy.preInit(ClientProxy.java:164)
	at vazkii.botania.common.Botania.preInit(Botania.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:611)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:253)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:231)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:604)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:266)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: vazkii.botania.api.item.TinyPotatoRenderEvent
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 43 more
Caused by: java.lang.SecurityException: class "vazkii.botania.api.item.TinyPotatoRenderEvent"'s signer information does not match signer information of other classes in the same package
	at java.lang.ClassLoader.checkCerts(ClassLoader.java:895)
	at java.lang.ClassLoader.preDefineClass(ClassLoader.java:665)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:758)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 45 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1490215512 bytes (1421 MB) / 2175270912 bytes (2074 MB) up to 4772593664 bytes (4551 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5120m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.0.2493 93 mods loaded, 93 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                   | Version                  | Source                                          | Signature                                |
	|:----- |:-------------------- |:------------------------ |:----------------------------------------------- |:---------------------------------------- |
	| UCH   | minecraft            | 1.12.2                   | minecraft.jar                                   | None                                     |
	| UCH   | mcp                  | 9.42                     | minecraft.jar                                   | None                                     |
	| UCH   | FML                  | 8.0.99.99                | forge-1.12.2-14.23.0.2493.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge                | 14.23.0.2493             | forge-1.12.2-14.23.0.2493.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | ivtoolkit            | 1.3.3-1.12               | minecraft.jar                                   | None                                     |
	| UCH   | adventurebags        | 0.6                      | ab-1.12-0.6r.jar                                | None                                     |
	| UCH   | antiqueatlas         | 4.4.4                    | antiqueatlas-1.12-4.4.4.jar                     | None                                     |
	| UCH   | antiqueatlasoverlay  | 1.2                      | antiqueatlas-1.12-4.4.4.jar                     | None                                     |
	| UCH   | jei                  | 4.7.10.97                | jei_1.12.2-4.7.10.97.jar                        | None                                     |
	| UCH   | ctm                  | MC1.12-0.2.3.9           | CTM-MC1.12-0.2.3.9.jar                          | None                                     |
	| UCH   | chisel               | MC1.12-0.0.14.18         | Chisel-MC1.12-0.0.14.18.jar                     | None                                     |
	| UCH   | mantle               | 1.12-1.3.1.21            | Mantle-1.12-1.3.1.21.jar                        | None                                     |
	| UCH   | tconstruct           | 1.12-2.7.3.30            | TConstruct-1.12-2.7.3.30.jar                    | None                                     |
	| UCH   | theoneprobe          | 1.4.18                   | theoneprobe-1.12-1.4.18.jar                     | None                                     |
	| UCH   | immersiveengineering | 0.12-72                  | ImmersiveEngineering-0.12-72.jar                | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| UCH   | natura               | 1.12-4.3.0.17            | Natura-1.12-4.3.0.17.jar                        | None                                     |
	| UCH   | betterwithmods       | 1.2.9-1.11.2             | BetterWithMods-1.12-2.0.11.jar                  | None                                     |
	| UCH   | appleskin            | 1.0.8                    | AppleSkin-mc1.12-1.0.8.jar                      | None                                     |
	| UCH   | astralsorcery        | 1.6.1                    | astralsorcery-1.12-1.6.1.jar                    | None                                     |
	| UCH   | crafttweaker         | 4.0.7                    | CraftTweaker2-1.12-4.0.7.jar                    | None                                     |
	| UCH   | base                 | 3.3.1                    | base-1.12-3.3.1.jar                             | None                                     |
	| UCH   | baubles              | 1.5.1                    | Baubles-1.12-1.5.1.jar                          | None                                     |
	| UCH   | bedbugs              | @VERSION@                | BedBugs-1.12-1.0.1.jar                          | None                                     |
	| UCH   | betterbuilderswands  | 0.11.1                   | BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar | None                                     |
	| UCH   | betterfoliage        | 2.1.10                   | BetterFoliage-MC1.12-2.1.10.jar                 | None                                     |
	| UCH   | betterplacement      | 1.0.0-1                  | BetterPlacement-1.0.0-1.jar                     | None                                     |
	| UCH   | betterquesting       | 2.5.236                  | BetterQuesting-2.5.236.jar                      | None                                     |
	| UCH   | bibliocraft          | 2.4.3                    | BiblioCraft[v2.4.3][MC1.12.0].jar               | None                                     |
	| UCH   | biometweaker         | 3.1.306                  | BiomeTweaker-1.12.1-3.1.306.jar                 | bdea6e9d19f35da4858ffcc93210c6207dd590bd |
	| UCH   | biomesoplenty        | 7.0.1.2297               | BiomesOPlenty-1.12.2-7.0.1.2297-universal.jar   | None                                     |
	| UCH   | birdsnests           | 2.0.0                    | BirdsNests1.12-2.0.0.jar                        | None                                     |
	| UCH   | bonsaitrees          | 1.0.0                    | bonsaitrees-1.0.0-b28.jar                       | None                                     |
	| UCH   | bookshelf            | 2.1.449                  | Bookshelf-1.12.2-2.1.449.jar                    | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCE   | botania              | r1.10-348                | Botania r1.10-348.jar                           | None                                     |
	| UCH   | ceramics             | 1.12-1.3.2               | Ceramics-1.12-1.3.2.jar                         | None                                     |
	| UCH   | chameleon            | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                        | None                                     |
	| UCH   | chesttransporter     | 2.8.7                    | ChestTransporter-1.12-2.8.7.jar                 | None                                     |
	| UCH   | chiselsandbits       | 14.8                     | chiselsandbits-14.8.jar                         | None                                     |
	| UCH   | chunkanimator        | 1.2                      | ChunkAnimator-MC1.12-1.2.jar                    | None                                     |
	| UCH   | shadowmc             | 3.8.0                    | ShadowMC-1.12-3.8.0.jar                         | None                                     |
	| UCH   | clipboard            | @VERSION@                | Clipboard-1.12-1.3.0.jar                        | None                                     |
	| UCH   | clumps               | 2.0.0                    | Clumps-3.0.0.jar                                | None                                     |
	| UCH   | controlling          | 3.0.3                    | Controlling-3.0.3.jar                           | None                                     |
	| UCH   | cookingforblockheads | 6.3.6                    | CookingForBlockheads_1.12.1-6.3.6.jar           | None                                     |
	| UCH   | ctgui                | 1.0.0                    | CraftTweaker2-1.12-4.0.7.jar                    | None                                     |
	| UCH   | crafttweakerjei      | 2.0.0                    | CraftTweaker2-1.12-4.0.7.jar                    | None                                     |
	| UCH   | custommainmenu       | 2.0.8                    | CustomMainMenu-MC1.12.2-2.0.8.jar               | None                                     |
	| UCH   | dailies              | 1.12-6                   | dailies-1.12-6.jar                              | None                                     |
	| UCH   | darkutils            | 1.7.173                  | DarkUtils-1.12.2-1.7.173.jar                    | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCH   | dsurround            | 3.4.7.2                  | DynamicSurroundings-1.12.2-3.4.7.2.jar          | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| UCH   | presets              | 3.4.7.2                  | DynamicSurroundings-1.12.2-3.4.7.2.jar          | None                                     |
	| UCH   | elevatorid           | 1.3.4                    | ElevatorMod-1.12-1.3.4.jar                      | None                                     |
	| UCH   | shetiphiancore       | 3.5.2                    | shetiphiancore-1.12.0-3.5.2.jar                 | None                                     |
	| UCH   | endertanks           | 1.6.0.2                  | endertanks-1.12.0-1.6.0.2.jar                   | None                                     |
	| UCH   | extrabitmanipulation | 1.12-3.2.1               | ExtraBitManipulation-1.12-3.2.1.jar             | None                                     |
	| UCH   | extrautils2          | 1.0                      | extrautils2-1.12-1.6.3.jar                      | None                                     |
	| UCH   | fairylights          | 2.1.1                    | fairylights-2.1.1-1.12.jar                      | None                                     |
	| UCH   | farseek              | 2.2                      | Farseek-1.12-2.2.jar                            | None                                     |
	| UCH   | fastleafdecay        | v13                      | FastLeafDecay-v13.jar                           | None                                     |
	| UCH   | flatcoloredblocks    | mc1.12-6.6               | flatcoloredblocks-mc1.12-6.6.jar                | None                                     |
	| UCH   | foamfix              | 0.8.0-1.12               | foamfix-0.8.0-1.12-law.jar                      | None                                     |
	| UCH   | forgeendertech       | 1.12-3.0.1.0             | ForgeEndertech-1.12-3.0.1.0-build.0012.jar      | None                                     |
	| UCH   | forgelin             | 1.5.1                    | Forgelin-1.5.1.jar                              | None                                     |
	| UCH   | fw                   | 1.6.0                    | FullscreenWindowed-1.12-1.6.0.jar               | None                                     |
	| UCH   | gravestone           | 1.10.0                   | gravestone-1.10.0.jar                           | None                                     |
	| UCH   | hopperducts          | 1.5                      | hopperducts-mc1.12-1.5.jar                      | None                                     |
	| UCH   | inventorypets        | 1.4.9.9                  | inventorypets-1.12-1.4.9.9.jar                  | None                                     |
	| UCH   | inventorytweaks      | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                        | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCH   | ironchest            | 1.12.2-7.0.32.819        | ironchest-1.12.2-7.0.32.819.jar                 | None                                     |
	| UCH   | jaff                 | 1.7_for_1.12             | JustAFewFish-1.7_for_1.12.jar                   | None                                     |
	| UCH   | jeresources          | 0.8.3.23                 | JustEnoughResources-1.12-0.8.3.23.jar           | None                                     |
	| UCH   | longfallboots        | 1.2.1a                   | longfallboots-1.2.1a.jar                        | None                                     |
	| UCH   | naturescompass       | 1.5.0                    | NaturesCompass-1.12-1.5.0.jar                   | None                                     |
	| UCH   | netherportalfix      | 5.3.9                    | NetherPortalFix_1.12.1-5.3.9.jar                | None                                     |
	| UCH   | openglider           | @VERSION@                | OpenGlider-1.12-1.0.1.jar                       | None                                     |
	| UCH   | harvestcraft         | 1.12.1c                  | Pam's HarvestCraft 1.12.1c.jar                  | None                                     |
	| UCH   | platforms            | 1.4.0.1                  | platforms-1.12.0-1.4.0.1.jar                    | None                                     |
	| UCH   | reccomplex           | 1.4.5                    | RecurrentComplex-1.4.5.1.jar                    | None                                     |
	| UCH   | roots                | 0.103                    | roots-2-0.103.jar                               | None                                     |
	| UCH   | rustic               | 0.4.2.1                  | rustic-0.4.3.jar                                | None                                     |
	| UCH   | simplecorn           | 2.3.2                    | SimpleCorn1.12-2.3.2.jar                        | None                                     |
	| UCH   | simplytea            | 1.4                      | simplytea-1.4.jar                               | None                                     |
	| UCH   | bq_standard          | 2.4.134                  | StandardExpansion-2.4.134.jar                   | None                                     |
	| UCH   | storagedrawers       | 1.12-5.2.5               | StorageDrawers-1.12.1-5.3.3.jar                 | None                                     |
	| UCH   | streams              | 0.4                      | Streams-1.12-0.4.jar                            | None                                     |
	| UCH   | tp                   | 1.12                     | tinyprogressions-1.12-3.2.6.jar                 | None                                     |
	| UCH   | topaddons            | 1.12-0.15.1              | topaddons-1.12-0.15.1.jar                       | None                                     |
	| UCH   | toughasnails         | 3.0.0.64                 | ToughAsNails-1.12-3.0.0.64-universal.jar        | None                                     |
	| UCH   | tumbleweed           | @VERSION@                | Tumbleweed-Dark-1.12.2-1.0.0.jar                | None                                     |
	| UCH   | veinminer            | 0.38.1                   | VeinMiner-1.12-0.38.1.639+134fb1e.jar           | None                                     |
	| UCH   | veinminermodsupport  | 0.38.1                   | VeinMiner-1.12-0.38.1.639+134fb1e.jar           | None                                     |
	| UCH   | waddles              | 0.5.6                    | Waddles-1.12.2-0.5.6.jar                        | None                                     |
	| UCH   | waystones            | 4.0.15                   | Waystones_1.12.1-4.0.15.jar                     | None                                     |

	Loaded coremods (and transformers): 
ForgelinPlugin (Forgelin-1.5.1.jar)
  
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
FarseekCoreMod (Farseek-1.12-2.2.jar)
  farseek.core.FarseekClassTransformer
ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.2.jar)
  shetiphian.asm.ClassTransformer
IvToolkit (IvToolkit-1.3.3-1.12.jar)
  
CTMCorePlugin (CTM-MC1.12-0.2.3.9.jar)
  team.chisel.ctm.client.asm.CTMTransformer
BetterFoliageLoader (BetterFoliage-MC1.12-2.1.10.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.7.2.jar)
  org.blockartistry.DynSurround.asm.Transformer
DummyPlugin (ForgeEndertech-1.12-3.0.1.0-build.0012.jar)
  
TANLoadingPlugin (ToughAsNails-1.12-3.0.0.64-universal.jar)
  toughasnails.asm.transformer.CropDecayTransformer
  toughasnails.asm.transformer.EntityRendererTransformer
  toughasnails.asm.transformer.WorldTransformer
LoadingPlugin (ChunkAnimator-MC1.12-1.2.jar)
  lumien.chunkanimator.asm.ClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 382.05' Renderer: 'GeForce GTX 750 Ti/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- theoneprobeIntegration (Enabled/Not Forced)

	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)

**Comment by Vazkii** [comment]
#2380
