### ISSUE TITLE
When I try to summon Gaia, it roars at me, and eats my Terrasteel.

### ISSUE THREAD

**Issue by SteptimusHeap** [Vazkii/Botania#2399]
I've done the ritual many times before for testing purposes (I've been doing it in creative to practice for survival) and all of a sudden it just starts roaring at me whenever i try to do it. It uses up the terrasteel, and nothing happens after that.

**Comment by williewillus** [comment]
are there errors in the log? does this happen with botania alone?

**Comment by SteptimusHeap** [comment]
It doesn't crash, it just does a roar sound and my terra steel is gone. I fixed it, I don'-t know how though. I just broke a bunch of things and replaced them.
