### ISSUE TITLE
Portal to Alfheim immediately disappears

### ISSUE THREAD

**Issue by SteptimusHeap** [Vazkii/Botania#2401]
Whenever i try to make a portal to alfheim it does the startup animation, then immediately disappears, there is still mana left in the mana pools, and quite a bit too. [Here's a video of it happening](https://youtu.be/YavoFjTU4GA)        

Sorry, I know I've been posting issues a lot, and they are probably all my fault, but I suck at this.

**Comment by williewillus** [comment]
what version is this? can you clear out the vicinity of the portal and try again?

**Comment by SteptimusHeap** [comment]
There was a little bit of dirt touching it, I guess I can clear that and retry.

**Comment by quat1024** [comment]
I don't think there's enough mana in the pool to the right. See how much mana the pool on the left consumed? - try filling the rightmost pool with at least that much mana.

But it's not all your fault, there's a real bug here. I doubt the alfheim portal is supposed to consume *any* mana from the pool if it can't open.

**Comment by SteptimusHeap** [comment]
Kay, I'll try that, but I would like it for people to keep suggesting things.

**Comment by codycoolwaffle** [comment]
Tried on the latest version (249) and it doesn't consume the mana, but does open then close. It does this even if there is no mana in the pools.

**Comment by williewillus** [comment]
That's because the gateway core starts the animation, then draws mana, which is intended to give some visual feedback about what's going wrong. Maybe more particles near the pools to warn about it are necessary :P
