### ISSUE TITLE
The Alfheim Portal saves every invalid item into its inventory for all eternity

### ISSUE THREAD

**Issue by DaedalusGame** [Vazkii/Botania#2403]
...causing nbt tag overflows. Caused mostly by this conversation:
"Hey Bord, you think the portal consumes mana for throwing things in that don't trade into anything?"
"I don't think so"
"Bigass Trashcan."
Followed by an infinite bread machine feeding the people of Alfheim for all eternity.
Turns out they didn't like our bread.

**Comment by KomradeSpectre** [comment]
The error in question thrown off afterwards was the following.
![687474703a2f2f692e6e656e746966792e6d652f6d7a4c6b566b466e2e706e67](https://user-images.githubusercontent.com/12734451/31205989-22badf86-a943-11e7-9187-1569aa1d8770.png)

**Comment by Vazkii** [comment]
ಠ_ಠ
