### ISSUE TITLE
Left hand and lexica botania

### ISSUE THREAD

**Issue by ghost** [Vazkii/Botania#2404]
Pages clip trought the back of the book, you can see this when book is on the left hand. You could fix this by flipping the book or making the pages shorter.
![1007161348-java](https://user-images.githubusercontent.com/22749547/31308191-d8010f26-ab7a-11e7-867b-707912045cee.png)

**Comment by codycoolwaffle** [comment]
This is obviously an update before the graphic overhaul, and it doesn't look like this anymore. Can We get this closed?
