### ISSUE TITLE
Challenges marked "completed" don't persist across world loads

### ISSUE THREAD

**Issue by dalapo** [Vazkii/Botania#2405]
Basically what the title says. When I exit the world and reload, any challenges previously marked "completed" are no longer marked "completed". It's trivial to mark them again, but it is certainly frustrating to not have an effective log of which ones I've done.

**Comment by Vazkii** [comment]
It's intentional, since it works as a checklist for what you've done in
that world.

**Comment by TehStoneMan** [comment]
I read that as him meaning reloading the SAME world, not a new one.

**Comment by dalapo** [comment]
Yes, that's what I meant. Exiting a world and then reloading the same world clears all challenges.

**Comment by codycoolwaffle** [comment]
Could not replicate, what version were you using?

**Comment by dalapo** [comment]
The latest one, 348 (iirc).

**Comment by codycoolwaffle** [comment]
349 is latest. Can you update and see if it's working as intended?
