### ISSUE TITLE
floating endoflame and betterbuilders wand

### ISSUE THREAD

**Issue by lukehinz** [Vazkii/Botania#2406]
floating endoflame turns into floating botania flower when using an unbreakable builders wand to place them

**Comment by lukehinz** [comment]
not sure about the other wands as i dont use them

**Comment by codycoolwaffle** [comment]
Works with Extra Utilities builder's wand, but not better builder's wands wands. Therefore, I doubt this is Botania's fault.

**Comment by Tamaized** [comment]
#2227

**Comment by codycoolwaffle** [comment]
Ah, I thought I've seen this topic before. This is dup of a closed issue, can we get this closed?
