### ISSUE TITLE
[1.12.1] Equipping the Spectator in bauble slot causes player crash 

### ISSUE THREAD

**Issue by b0bst3r** [Vazkii/Botania#2407]
Not sure if this is a baubles issue or botania issue (or both)

Baubles-1.12-1.5.1
Botania r1.10-349
Forge-1.12.1-14.22.1.2485

Link to crash when player joins world - http://pastebin.ubuntu.com/25713587/

**Comment by codycoolwaffle** [comment]
I am unable to replicate. We need more info, this is very vague.

**Comment by williewillus** [comment]
Not a botania bug. Some mod's machine is saying it has an inventory (hasCapability) but then returns null when we actually go get it (getCapability). Look at what machines were around you at the time of the crash, narrow it down, then report it to them (link this post if necessary)
