### ISSUE TITLE
[1.12.2] Bauble Case and Flower Pouch lose items

### ISSUE THREAD

**Issue by angelnc1989** [Vazkii/Botania#2408]
Minecraft 1.12.2
Forge 14.23.0.2503
Botania r1.10-349

I had it happen twice now, that all my baubles stored in a Bauble Case and all Mystical Flowers I collected in my Flower Pouch were just gone. I can't nail it down to a specific event, but they just disappeared from the inventories.

**Comment by williewillus** [comment]
Just botania? On a server?

**Comment by angelnc1989** [comment]
No, a [modpack](https://minecraft.curseforge.com/projects/deus-ex-machina). And yes, on a server.

**Comment by williewillus** [comment]
without more information and reliable reproduction with botania alone (no sponge or other mods), not much can be done

**Comment by angelnc1989** [comment]
Thought that might be the case. Sadly I don't have more information.
I was able to reproduce it once in singleplayer, but now I can't.
In singeplayer the items were basically straight deleted. I put them in, closed the Bauble Case, opened again and they were gone.

**Comment by codycoolwaffle** [comment]
As this needs more info, can this get tagged with that?

**Comment by PieExplosion** [comment]
One of the conditions is entering Creative mode, but it doesn't seem to repeat.  It also wipes the contents of Flower Pouches.  I haven't quite figured out the other conditions yet.

**Comment by Ayelwen** [comment]
Happening to me as well. Posted on reddit about it and was directed here. I'll see what I can do to replicate the issue.

**Comment by Hund** [comment]
I have the same issue. I can realably reproduce the bug by entering creative mode using `/gamemode 1` and then taking any item out of the creatve inventory.

I'm runnning Minecraft 1.12.2 with 14.23.1.25555 and these mods: https://dpaste.de/2Sh0

**Comment by williewillus** [comment]
this is probably https://github.com/MinecraftForge/MinecraftForge/issues/4580

**Comment by raoulvdberge** [comment]
It is. RS is suffering from the same problem :(

**Comment by SquidDev** [comment]
Just wondering if this related to #1894, and so caused by MinecraftForge/MinecraftForge#2523? The two issues seem rather similar and I don't think the code has changed since that issue was reported,

**Comment by williewillus** [comment]
Yeah it's all forge (and vanilla for having a broken creative menu), botania is using the interfaces as-advertised
