### ISSUE TITLE
Right click interactions double-count

### ISSUE THREAD

**Issue by SteptimusHeap** [Vazkii/Botania#2409]
So I moved my Munchdew, which is my main source of mana, to a group of trees to eat it. All of a sudden, i can't bind the Munchdew to anything, i can't connect the spreader to anything, i can't change the mana pool from accepting to giving. If  i try to select something with the wand of the forest, it highlights for a split second, and then goes back to normal. Same with the mana spreader. When i try to change the mana pool from accepting mana to giving mana, it changes, then changes back. It actually does put some mana in the mana tablet. But then it changes and puts it back. I tried breaking and replacing the blocks, i tried re-logging onto the server. I waited for a server reset. Everything i could think of, I tried. BUT IT STILL HAPPENS. I can't get any farther with this happening, and I'm too annoyed to try anything more right now

**Comment by williewillus** [comment]
1. It would help a lot if your title was informative
2. Does this happen in SP? I suspect all your double clicks are double-counting serverside due to lag to your server.

**Comment by SteptimusHeap** [comment]
doesn't happen in singleplayer, I'll ask the server owners. For the 10th time

**Comment by Vazkii** [comment]
Yeah no. We're not here for you to treat like a joking matter. You're not getting any help.
