### ISSUE TITLE
Manasteel armor is twice as strong as iron

### ISSUE THREAD

**Issue by krokots** [Vazkii/Botania#2410]
Botania book and ftb wiki says it should give the same amount of armour as iron, but it gives double. At least this is what hud shows. Check this out.
https://gifyu.com/image/Mj6S

The mods that I'm using:
AutoRegLib-1.3-13.jar
Baubles-1.12-1.5.1.jar
binnie-mods-1.12.2-2.4.0.78.jar
BiomesOPlenty-1.12.2-7.0.1.2297-universal.jar
**Botania r1.10-349.jar**
ChestTransporter-1.12-2.8.7.jar
CodeChickenLib-1.12-3.1.3.313-universal.jar
CoFHCore-1.12-4.3.5.13-universal.jar
CoFHWorld-1.12-1.0.1.8-universal.jar
forestry_1.12.2-5.6.0.199.jar
Forgelin-1.5.1.jar
industrialforegoing-1.12.1-1.4.2-69.jar
ironchest-1.12.2-7.0.34.820.jar
jei_1.12.2-4.8.0.105.jar
OptiFine_1.12.2_HD_U_C6.jar
Quark-r1.3-111.jar
RedstoneFlux-1.12-2.0.1.2-universal.jar
RoguelikeDungeons-1.12.2-1.7.2.jar
SpartanShields-1.12-1.3a.jar
tesla-core-lib-1.12-1.0.9.jar
ThermalDynamics-1.12-2.3.5.12-universal.jar
ThermalExpansion-1.12-5.3.5.19-universal.jar
ThermalFoundation-1.12-2.3.5.14-universal.jar

**Comment by codycoolwaffle** [comment]
I experimented with ONLY the latest build of Botania (349), and it's not a visual bug, like I had initially thought. On normal mode, zombies deal 1 1/2 hearts of damage without armor, with iron armor it's 1/2 ~ 1 hearts, but with manasteel it occasionally dealt 1/2 heart, the other times doing nothing at all. Elementium is the same. Terrasteel, being stronger, gives you 8 armor points in the chestplate alone.

**Comment by codycoolwaffle** [comment]
This is a dup of #2299 

Can we get this tagged and closed
