### ISSUE TITLE
Chiseled slabs are uncraftable

### ISSUE THREAD

**Issue by Hubry** [Vazkii/Botania#2415]
Saw this on discord (reported by user Geranot), willie said "file a bug or I'll forget in 30 seconds", decided to file a bug.

![Image 1](https://cdn.discordapp.com/attachments/154261184701267969/369173315098771456/unknown.png)
![Image 2](https://cdn.discordapp.com/attachments/154261184701267969/369174470272745472/unknown.png)

**Comment by williewillus** [comment]
I'm pretty sure this issue existed in 1.7 since these jsons were just generated by an autogenerator reading the old recipes ¯\\_(ツ)_/¯
Anyways, fixed by removing the first recombination recipe.
