### ISSUE TITLE
Taken it easy

### ISSUE THREAD

**Issue by DarkScorn** [Vazkii/Botania#2417]
![2017-10-18_21 24 07](https://user-images.githubusercontent.com/24631889/31735669-44eba992-b44b-11e7-8d37-3e3b45215b87.png) as you can see in the picture above i got that bug flower. I was trying to move primus loci with endersoul hand to my home. I thought I would succeed but no man it seem like impossible to move those primus flowers. I felt like i have to report it.

**Comment by Vazkii** [comment]
a) It is impossible.
b) Primus Flowers were removed over 18 months ago.
