### ISSUE TITLE
Manaseer Monocle cannot receive a Cosmetic Override

### ISSUE THREAD

**Issue by Allydra** [Vazkii/Botania#2418]
Placing a Manaseer Monocle in a crafting grid with any Cosmetic Bauble doesn't yield anything.

**Comment by Hubry** [comment]
It can be applied as a cosmetic override itself (the item actually implements ICosmeticBauble), so this might be actually intended.

**Comment by Allydra** [comment]
Interesting. I would think it being a functional bauble would warrant it being override-able.
