### ISSUE TITLE
[1.12.2 Rannuncarpus Can Place Shulker Boxes

### ISSUE THREAD

**Issue by commonsensei** [Vazkii/Botania#2419]
A rannuncarpus nabbed my filled shulker box and placed it. When I picked up the shulker box, it was empty..
Forge 14.23.0.2512
Botania r1.10-349

This is on a server.

**Comment by williewillus** [comment]
should no longer clear the boxes

**Comment by quat1024** [comment]
Also worth noting that when I tried it, the rannuncarpus placed the shuller box upside down so I couldn't open it

**Comment by williewillus** [comment]
that's because the rannuncarpus just places the default state of everything (it doesn't target any given side of an adjacent block), and I didn't want to change the mechanics too heavily without consideration.
