### ISSUE TITLE
[1.12.2] 'Botania Flower' cross-mod interaction with Quark bug.

### ISSUE THREAD

**Issue by charagarlnad** [Vazkii/Botania#2420]
By putting some (only seems to be functional flowers) flowers from Botania in a dispenser with quark installed so it can place it, it creates a Botania Flower

Video in action: https://youtu.be/NW5-W2QZYDU

**Comment by williewillus** [comment]
Quark bug, but I think this is actually fixable on the botania side (by moving the post-place logic from the ItemBlock to the Block class) so keeping open

**Comment by williewillus** [comment]
well, actually no because Quark calls neither ItemBlock.placeBlockAt nor Block.onBlockPlacedBy, so report it there
