### ISSUE TITLE
[1.12.2 Botania r1.10-347] Mana Potion effect causing server crash

### ISSUE THREAD

**Issue by VallenFrostweaver** [Vazkii/Botania#2421]
I realize I am 2 Botania versions behind and we are running Radon v1.3.0 on a server (which is also 1 version behind - I'm having issues updating the server and am working on getting on current versions) and one of my players drank a mana potion and crashed the server. Restarted the server and others can play but if that person tries logging back in the server crashes. Going near the area they were crashes. Pastebin results below: https://pastebin.com/4Su0EXwZ

EDIT UPDATE: Deleting the flare entity using an NBT editor worked. I also deleted a butterfly nearby just in case.

**Comment by Vazkii** [comment]
This was fixed in 348.

**Comment by VallenFrostweaver** [comment]
ok then. Thanks. I thought that may do it.
