### ISSUE TITLE
Dispensers not planting crafted botania flowers properly

### ISSUE THREAD

**Issue by Seramme** [Vazkii/Botania#2423]
1. Create a flower (e.g. endoflame) in a petal apothecary
2. Place a dispenser facing a grass tile
3. Place the flower in dispenser
4. Activate dispenser

Expected: the correct flower is placed
Result: A generic "botania flower" is placed instead (the one granting the achievement)

This is with r1.10-349 on Minecraft 1.12

As a side note, when rafflowsia attempts to eat said generic flower, the game crashes. :-)

**Comment by williewillus** [comment]
Duplicate of #2420
