### ISSUE TITLE
Unable to use Garden of Glass Skybox on the overworld

### ISSUE THREAD

**Issue by ubergeek77** [Vazkii/Botania#2425]
I want to use the Garden of Glass skybox on the overworld with my server. On both the client and the server, the `B:fancySkybox.enable` and `B:fancySkybox.normalWorlds` options are both set to `true`. However, when it is night time, I can't see the Garden of Glass Skybox - there are no planets, aurora rings, or anything special. I just see the normal vanilla night skybox. Unfortunately, the same is true for single-player worlds as well. Even if I create a new single-player world, I still can't see the skybox at night.

How can I use the skybox? It looks really nice, and I'd love to use it.

I should note that I am using OptiFine, if it matters. Additionally, I'll link my modlist below, with more info about my setup. The information is the same for both my client and my server, besides the modlist, which has additional client-only mods.

**Minecraft Version:** 1.12.2
**Forge Version:** 1.12.2-14.23.0.2515
**Botania Version:** r1.10-349
**Modlist**: [Pastebin](https://pastebin.com/raw/MmXv21xi)

Additionally, (and perhaps this should go in its own issue), Botania settings cannot be set in-game. I believe this was possible previously, but please correct me if I am wrong.

When trying to set settings in-game, I receive the following message:

> **No mod information found**
> **Please ask your mod author to provide a mod **mcmod.info file****

Because of this, I had to manually specify "true" for the two options mentioned previously.

Please let me know if I can gather more info about this!

**Comment by Vazkii** [comment]
Try removing optifine.

**Comment by ubergeek77** [comment]
I removed OptiFine, and loaded up my single-player world, but I still can't see the skybox. I just see the normal vanilla moon.

**Comment by ubergeek77** [comment]
Ok, I must apologize. This turned out to be me not knowing how Astral Sorcery works, as I didn't know it attempts to override the skybox in favor of constellations.

Removing the overworld ID (0) from `S:skySupportedDimensions` in `astralsorcery.cfg` made the Garden of Glass skybox show up in the overworld, and the skyblock world. It even works with OptiFine!

On a side note, thanks for making it. It looks amazing - I had no idea everything would be visible even during the day!
