### ISSUE TITLE
Tinted Mana lens not working

### ISSUE THREAD

**Issue by meminpanda** [Vazkii/Botania#2426]
Tainted paintslinger and flash lens dont shoot and when i forced a beam pointing a mana spreader with the lens server crashed.
After this i cant enter the server without it crashing since it is still trying to fire it
[crash-2017-10-27_22.41.20-server.txt](https://github.com/Vazkii/Botania/files/1423961/crash-2017-10-27_22.41.20-server.txt)

**Comment by Hubry** [comment]
Seems to be a duplicate of #2389. Update the mod, you're 2 builds behind.

**Comment by williewillus** [comment]
^
