### ISSUE TITLE
breaking a tiny planet with a burst orbiting around it does not register as the burst despawning

### ISSUE THREAD

**Issue by lag42** [Vazkii/Botania#2430]

**Comment by TheWhiteWolves** [comment]
Mod List?
Version?
Logs?

Anything?

**Comment by lag42** [comment]
albedo
autoreglib
baubles
botania(is r349)
codechickenlib
cofh core
cofh world
just enough items
journeymap
magicalpsi
mob mash
psi
redstone flux
thermal dynamics
thermal expansion
thermal foundation
and any logs you think would be useful just tell me where to find them and i will give them

**Comment by lag42** [comment]
i was building a star forge(large structure that uses mana prims to enlarge a mana burst in appearance so that with albedo it lights up the area massively) and i had it orbiting around a tiny planet then i broke that planet and somehow it doesnt register that as despawn so the issue is completely different

**Comment by lag42** [comment]
nevermind, i was having it orbit around a tiny planet way up in the sky so it just keep going off in a random direction for a while instead
