### ISSUE TITLE
crystal bow does not generate arrows from mana and takes real ones

### ISSUE THREAD

**Issue by lag42** [Vazkii/Botania#2431]

**Comment by TheWhiteWolves** [comment]
Mod List?
Version?
Logs?

Anything?

**Comment by lag42** [comment]
albedo
autoreglib
baubles
botania(is r349)
codechickenlib
cofh core
cofh world
just enough items
journeymap
magicalpsi
mob mash
psi
redstone flux
thermal dynamics
thermal expansion
thermal foundation
and any logs you think would be useful just tell me where to find them and i will give them

**Comment by codycoolwaffle** [comment]
Last I checked, it requires them in your inventory, but doesn't consume them. Like the infinity enchantment. Is the bow actually taking them out of your inventory?

**Comment by lag42** [comment]
Yes it consumes them and if it requires an arrow there's a typo in the lexica botania

**Comment by codycoolwaffle** [comment]
That is definitely unintended behavior, and as for the arrow requirement, either I'm mistaken or it was changed.

**Comment by williewillus** [comment]
#2362

**Comment by codycoolwaffle** [comment]
Oh. Team COFH really outa' fix that.
