### ISSUE TITLE
1.12.1 Lexicon Beegonia Crash

### ISSUE THREAD

**Issue by BigFriendlyJakey** [Vazkii/Botania#2432]
Forge version: 1.12.1-forge1.12.1-14.22.1.2485
Botania version: Botania r1.10-347
Link to crash log: https://pastebin.com/MycGb0RF

Steps to reproduce:
1. Craft new Lexicon
2. Go into the 'Generating Flora' section
2. Hold shift or attempt to open the 'Beegonia' page
3. ...
4. Profit

What I expected to happen:
(Holding Shift): Info about flower
(Clicking the word Beegonia): Lexicon opens page to show detailed info about flower

What happened instead:
freeze, then c r a s h

If you need a modlist, let me know :)

**Comment by williewillus** [comment]
Heyo
This is because the mod that adds the Beegonia does not have a proper localization string so MC panics trying to translate.

Try reporting this to the mod that adds the Beegonia flower (Magic Bees maybe?), but this flower isn't from botania. Thanks for the report!
