### ISSUE TITLE
Worldshaper's Astrolabe can place blocks outside world border

### ISSUE THREAD

**Issue by KiRtAp2** [Vazkii/Botania#2433]
Forge version: 14.23.0.2529
Botania version: 1.10-349
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)
The game doesn't crash.

Steps to reproduce:
1. Go to world border, use the astrolabe to place any block

What I expected to happen:
Astrolabe places blocks inside the border and ignores blocks outside the border.

What happened instead:
Astrolabe places blocks inside and outside the world border.

**Comment by codycoolwaffle** [comment]
Just tested on 349, can confirm this happens.
