### ISSUE TITLE
severe lag when breaking a mana spreader that still has a burst going

### ISSUE THREAD

**Issue by lag42** [Vazkii/Botania#2434]
Forge version:14.23.0.2528
Botania version: 1.10-r394

Steps to reproduce:
1. get a pulse mana spreader and fire it at a tiny planet block
2. break the pulse mana spreader while the burst still orbits the tiny planet

What I expected to happen:for the mana burst to keep going even though the mana spreader that made it is broken

What happened instead:severe lag as well as what i expected to happen

albedo is installed alongside botania if this makes a difference

**Comment by williewillus** [comment]
Can you try without albedo? I can't reproduce this

**Comment by williewillus** [comment]
Maybe show a screenshot of the setup

**Comment by lag42** [comment]
i think this is something else now that coincided with me breaking mana spreaders i can't reproduce it again either even though it happened twice
