### ISSUE TITLE
The Agglomeration Plate should work with a Shimmerock base

### ISSUE THREAD

**Issue by ConnorPr** [Vazkii/Botania#2435]
Forge version: 1.12.2-forge1.12.2-14.23.0.2512 (outdated because Extra Utilities 2 breaks otherwise)
Botania version: r1.10-349

With the checkerboard pattern when making the "ritual" for Terrasteel, you should also be able to use Shimmerock since it matches the Gaia Spreader/Fabulous Mana Pool Theme. I know this isn't an issue and it's more of a suggestion, I just have no idea where to post suggestions since im relatively new to the issue tracker :)

**Comment by codycoolwaffle** [comment]
Can someone label this as "idea"
