### ISSUE TITLE
IC2 Ores produced by Orechid are not functioning properly

### ISSUE THREAD

**Issue by Deny8** [Vazkii/Botania#2438]
Forge-14.22.0.2474
Botania r1.10-349
https://pastebin.com/m0i8uVdT (Game didn't crash, so my latest fml log)

**What I expected to happen:**
I use the orechid and weight lense to silk touch all my vanilla ores, and everything went right. I started my pack with just botania and later added a bunch of other mods (AE2, IC2 and a lot more). Now some new ores started to generate and I'd think they should work fine just like the vanilla ores.

**What happened instead:**
The ores from TE and AE2 all seemed to work fine, but the IC2 ores react very weird when produced by the orechid. If I break them with a manasteel (or vanilla diamond) pick, they break and give  me nothing in return. And when I tried to use the weight lense on them, they'd only drop basalt cobllestone instead of the ores.

**Comment by williewillus** [comment]
all the weight lens does is spawn a vanilla falling sand entity set to that block, anything that happens from then on is up to the vanilla logic

**Comment by Deny8** [comment]
I got that part, but I think the problem is in the orechid along with IC2 which resulted in a piece of stone turning into a invalid IC2 ore. All other ores are fine but IC2 is not working properly

**Comment by williewillus** [comment]
it's probably because all IC2 ores share the same block ID, and due to a vanilla bug (don't remember the number), falling sand only takes a specific metadata of the block ID.

the vanilla bug is fixed in 1.13, but there's not much botania can do - try asking them to remove the ores from botania's orechid list
