### ISSUE TITLE
CraftTweaker Support for 1.12.2

### ISSUE THREAD

**Issue by DrDarkfire** [Vazkii/Botania#2442]
Is it possible for you to build in CraftTweaker support for botania? It's been a sitting issue/suggestion in modtweaker for over a month...

What I expected to happen:
Craft/ModTweaker to add support
What happened instead:
They haven't, and it's causing pack devs to not be able to use your mod for integration.

**Comment by Vyraal1** [comment]
Going to second this, Botania has a lot of mechanics and features that I'd love to incorporate into my pack.

**Comment by The-Arcanian** [comment]
Immersive Engineering and Astral Sorcery added CraftTweaker compatibility on their sides. So either party can do it.

**Comment by bookerthegeek** [comment]
It is preferred if mods add there own integration for crafttweaker as this causes less issues for everybody.

**Comment by DrDarkfire** [comment]
so codycoolwaffle do you actually work on this mod or are you just here to comment on legit questions? Because I'm seeing reason for botania to have everything native to the mod.

**Comment by Vazkii** [comment]
Zenscript support has always been on the ModTweaker and it'll continue to be.

**Comment by codycoolwaffle** [comment]
I have contributed to the mod a few times, and Vazkii has stated above that support will ONLY be provided by ModTweaker, and he has stated this multiple times in the past. I'm simply relaying this.
