### ISSUE TITLE
Thermal Foundation Platinum does not drop with Weight Lens

### ISSUE THREAD

**Issue by scotty9090** [Vazkii/Botania#2443]
Forge version: 12.18.3.2488
Botania version: r1.9-3-341
Minecraft: 1.10.2
Thermal Foundation: 1.10.2-2.1.5.12

Not sure if this is a Botania issue or a Thermal Foundation issue - if the latter I will report this on their repo.

Working fine with all other ores as far as I can tell but Platinum won't respond to the weight lens.

Steps to reproduce:
1.  Setup Orechid wait for Platinum from Thermal Foundation to be produced.  Shoot mana burst at it with a Weight Lens attached to the spreader.

What I expected to happen:

Expected Platinum ore to drop like the other ores.

What happened instead:

Nothing, I have to break it manually then things resume as normal.

**Comment by williewillus** [comment]
One of [these](https://github.com/Vazkii/Botania/blob/master/src/main/java/vazkii/botania/common/item/lens/LensWeight.java#L46) conditions is not being met:

* there is space below the block
* the block has no TE
* the block is breakable
* the block's harvest level is less than or equal to the harvest level in the botania config (it's probably this one, by default the mining level of the weight lens is only equal to an iron pick I think)
* the block is silk touchable

**Comment by scotty9090** [comment]
Thank you!  It's the mining level (which shows as Obsidian for Platinum).  I didn't realize there was a max mining level for the weight lens.  I bumped up the mining level in the config file to Diamond and it's working fine now.  I will go ahead and close this.  Thanks again for your help.
