### ISSUE TITLE
Lexicon Crash: "Planestrider's Sash" Page 2 unreadable

### ISSUE THREAD

**Issue by xerberus333** [Vazkii/Botania#2444]
Forge version: 1.12.2-14.23.0.2546
Botania version: r1.10-350
Link to crash log: https://gist.github.com/xerberus333/ae7515a42c288e63cf7c14c3900eb606

Steps to reproduce:
1. In-game, hold Lexica and read the entry on the PLANESTRIDER'S SASH
2. Click NEXT PAGE arrow, or RIGHT ARROW on your keyboard

What I expected to happen: Go to the next page

What happened instead: Crash

Note: I've been going through the items list chronologically. I stopped reading other entries right after the Planestrider's Sash entry started giving me crashes. Meaning I don't know if other Lexica pages after Planestrider are doing this.

Edit: Checked all baubles/accessories. Seems only this guy causes a crash on page 2.

**Comment by williewillus** [comment]
hmm I couldn't get it to happen but the fix is a good check to have anyways, so whatever

**Comment by DrakusorU** [comment]
the bug is caused by forge... i've solved this bug by going back to version 14.23.0.2531.. wasted 2 hours removing mods 1 by 1 to see which one is the culprit and at the end was forge :(
