### ISSUE TITLE
Botania Gaden of Glass Issue

### ISSUE THREAD

**Issue by saphsara** [Vazkii/Botania#2447]
Forge version: 14.23.0.2537
Botania version: r1.10-350.jar
Link to crash log:) No crash log does not apply
It works in single player not server

Steps to reproduce:
1.  when using apothecary to create orechid flower it does not create one, using water in apothecary recipe petals  colors and a seed

What I expected to happen:  i excepted to receive a orechid flower

What happened instead: nothing

**Comment by Colton-Slayden** [comment]
Are you using a modpack you made or one someone else made?

**Comment by saphsara** [comment]
I put together a bunch on 1.12.2 mods together. and that was only thing not working, i have 2 servers running and the other server is fine. i might just delete the non working one. it isnt that active.  just wanted to let you know in case it is an issue or becomes one.

**Comment by codycoolwaffle** [comment]
Please include mod list
