### ISSUE TITLE
Feature Request - Drums and Pam Harvestcraft tree fruit

### ISSUE THREAD

**Issue by vakermit** [Vazkii/Botania#2448]
I apologize in advance if this the wrong place to post, but wish to share an idea

It would be interesting if the drum (one of existing or new) was capable of shaking loose mature fruit from Pam Harvestcraft trees, then we can use hopperhock to collect

I am using a mechanical user for this currently, but it is a very ugly solution.
as I can only target a single fruit and need to pipe command and control and bone meal to them

no other mod I have seen tackles this automation, and a drum would be so pretty for this

thoughts?

**Comment by Hubry** [comment]
As far as I know the Horn/Drum of the Wild has no special compat with modded blocks. It is possible to make blocks that are harvested by them by using the API interface [IHornHarvestable](/Vazkii/Botania/blob/e38556d265fcf43273c99ea1299a35400bf0c405/src/main/java/vazkii/botania/api/item/IHornHarvestable.java), which should be done on Pam's side.

**Comment by williewillus** [comment]
there's no common "harvest crop in place" interface in vanilla/forge, so pam's will have to support the horn itself
