### ISSUE TITLE
Lexicon crashes when reading Planestrider's Sash Page 2 due to forge?

### ISSUE THREAD

**Issue by DrakusorU** [Vazkii/Botania#2450]
Forge version: any above build 1.12.2-14.23.0.2541
Botania version: r1.10-350
Link to crash log: https://gist.github.com/DrakusorU/5e3d52d2b8f8dd110e94440406c50c1e

Steps to reproduce: updating to any version of forge newer than 14.23.0.2541 ( I did not tested with 14.23.0.2542 but with 14.23.0.2543 it crashes as well )

Some people needs to update forge because they cannot use some mods ( like buildcraft which needs at least 14.23.0.2544 )

**Comment by williewillus** [comment]
downgrade forge if you want an immediate fix, otherwise this is fixed in the next version.
