### ISSUE TITLE
Armor attributes are not displayed on the tooltip

### ISSUE THREAD

**Issue by Hubry** [Vazkii/Botania#2451]
Forge version: 14.23.1.2556
Botania version: r1.10-350
Link to crash log: n/a

Steps to reproduce:
1. Get some Botania armor pieces.
2. Look at their tooltips.

What I expected to happen: I see the armor attribute values.

What happened instead: I don't see any armor attribute values except the knockback resistance on terrasteel equipment. When equipped the armor still protects properly and the armor bar is filled.

Related: f55fa57d14ba7b0fb53d172922224f00829d85b7, which fixed #2299.

**Comment by williewillus** [comment]
yeah it's unfortunate that the tooltip is gone, but otherwise the armor double-stacks.
and just hardcoding the tooltip back in isn't really a nice solution.
so this'll probably stay the way it is

**Comment by codycoolwaffle** [comment]
From some screenshots I saw on Discord, I think Quark, while glitchingly, forces the armor tooltips. Goes right over the shift-info though

**Comment by Hubry** [comment]
Not an issue in 1.14 anymore
