### ISSUE TITLE
Gardens of Glass Help

### ISSUE THREAD

**Issue by Colton-Slayden** [Vazkii/Botania#2453]
Forge version: 12.18.3.2511
Botania version: R1.9-341
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)

https://pastebin.com/bXNXvJpD
Steps to reproduce:
1. Change
B:fancySkybox.enable=false to true
B:fancySkybox.normalWorlds=false to true

EDIT: you can use MCedit to change worldtype and that works but i want to be able to generate a survival map so all players dont have to download it and change it to play correctly

What I expected to happen: Be able to shift click to obtain cobble stone.

What happened instead: Nothing happens like it should when creating Gardens of Glass world type and still spawns in an island.

**Comment by williewillus** [comment]
you aren't playing GoG unless you're in a GoG world, changing the skybox option has nothing to do with the gameplay

**Comment by Colton-Slayden** [comment]
Well i just used Mcedit to change world type to botiana-skyblock so it allows me to use it which should be added to the mod so anyone and make survival maps.

**Comment by Colton-Slayden** [comment]
Mainly what i am needing then is an addon to allow the gardens of glass ability to get pebbles to be enabled in every world type
