### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Colton-Slayden** [Vazkii/Botania#2454]
Forge version: 12.18.3.2511
Botania version: R1.9-341

Add the ability in Botania config to allow the ability to shift+click grass to obtain pebbles in all world types.
Or make it a gamerule.

**Comment by codycoolwaffle** [comment]
It's meant to be a skyblock only feature, so no.

**Comment by williewillus** [comment]
please direct enhancement requests to /r/botania (but I don't think this is likely to happen)
