### ISSUE TITLE
[Enhancement] Config option for mana use of all items

### ISSUE THREAD

**Issue by ejektaflex** [Vazkii/Botania#2455]
It would be nice to have a config option to change the base multiplier for how much mana different items use, as well as mana cost for different operations.

E.g. With a multiplier of 1.25, it would make it so that you need 25% more mana to open the portal to Alfheim, runes require 25% more mana to craft, and all baubles use up mana 25% faster (or 25% more per use).

As a modpack maker, this would be really handy. I'd like to make the game a little bit more difficult and last a little bit longer.

**Comment by williewillus** [comment]
please direct enhancement requests to /r/botania
