### ISSUE TITLE
Crash while using the manual

### ISSUE THREAD

**Issue by neoc666** [Vazkii/Botania#2456]
Versions are Direwolf20 1.12 pack FTBPresentsDirewolf20112-1.3.0-1.12.2
forge-14.23.1.2555

Link to crash log: https://gist.github.com/neoc666/e00d58163ec1653d0cbd862d9a1cdd8f

Steps to reproduce:
1. Navigate to Baubles section and open entry "Planetstrider's Sash"
2. Click page forward button -> immediate crash

**Comment by TheWhiteWolves** [comment]
Does this happen with only Botania installed?

**Comment by codycoolwaffle** [comment]
When we ask for version, we are referring to Botania version. Not your modpack.

**Comment by codycoolwaffle** [comment]
Unable to replicate with only Botania 350

**Comment by neoc666** [comment]
It doesn't seem that you're involved with developing this mod.

**Comment by williewillus** [comment]
I fixed this already
