### ISSUE TITLE
Band of Aura not working?

### ISSUE THREAD

**Issue by c5shen** [Vazkii/Botania#2460]
Forge version: 1.12.2-14.23.0.2531
Botania version: 349th
mod list:
Botania-r1.12-349
baubles-1.12-1.5.1
industrialcraft-2-2.8.16-ex112
jei-1.12.2-4.8.0.114
journeymap-1.12.2-5.5.2
mantle-1.12-1.3.1.21
optifine-1.12.2
TConstruct-1.12-2.7.4.34
qualityarmory-v1.1.23

Steps to reproduce:
1. produce a band of aura/greater version, hold a mana tablet in inventory.
2. wait for x mins/hours.

What I expected to happen:
mana stores in tablet (tablet mana to increase)
What happened instead:
no mana stored

**Comment by c5shen** [comment]
update: nvm, it is just the speed of regeneration and the relatively undetectable increase on the tablet that tricked me.

**Comment by williewillus** [comment]
yea, the tablet holds a lot of mana relative to the production rate, so it's not easily noticeable
