### ISSUE TITLE
Botania Book crash on shift/sneak

### ISSUE THREAD

**Issue by mlinn1989** [Vazkii/Botania#2462]
Forge version: 14.23.1.2555
Botania version: r1.10-350
Link to crash log: https://gist.github.com/mlinn1989/beb913c64b959a738759c83a4ae2956d (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)

Steps to reproduce:
1. starting up botania with a looted lexica botania while looking through the generating flora pressing shift to see the tooltip and then it crashed,tried it agian and sa

What I expected to happen: seeing the tooltip?

What happened instead: while looking through the generating flora pressing shift to see the tooltip and then it crashed,tried it agian and same result

**Comment by mlinn1989** [comment]
mod gotten from the twitch client through dw20 pack no mods added

**Comment by williewillus** [comment]
the crash log you linked doesn't have anything to do with botania though (it's a refined storage gui crashing)

**Comment by mlinn1989** [comment]
updated the ling with full log
