### ISSUE TITLE
Botania breaks dispenser functionality on Animania

### ISSUE THREAD

**Issue by SSyl** [Vazkii/Botania#2463]
Forge version: 14.23.1.2562
Botania version: r1.10-352
Animania version: 1.4.3

Steps to reproduce:
See bug report on Animania's side: https://github.com/capnkirok/animania/issues/429

What I expected to happen:
On Animania, using a dispenser will dispense seeds on the ground as food for chickens.
What happened instead:
Botania overrode the functionality, planting the seeds if there's farmland or simply shooting them out instead.

A config option to disable Botania's dispenser functionality would fix this. That way we can choose between Animania's functionality or Botania's.

**Comment by codycoolwaffle** [comment]
I agree that this should definitely have a config. I can see this interfering with other mods adding related features in the future as well.
