### ISSUE TITLE
[Suggestion] Fully copy Quark dispenser planting.

### ISSUE THREAD

**Issue by The-Arcanian** [Vazkii/Botania#2464]
Quark allows you to add custom seeds for dispenser planting as a way of mod support. But Quark disables its version of dispenser planting in favor of Botania's which is the same sans the custom seeds. It seems odd to have a feature defer to a less complete version. Or, for people that don't want Quark, to just have a less complete version when you already have the code.

**Comment by Vazkii** [comment]
This feature should be disableable anyway, since other animania also adds
it and it can break stuff if botania overrides it.

**Comment by The-Arcanian** [comment]
Fair point, but not completely in line with my suggestion. Being able to use Quark's planting and disable Botania's would fix problems for me. But on the larger scale that does not fix the problem of people who want to be able to farm mod crops with Botania but for some reason do not want Quark.
I think you have said before that it is best to ask a mods devs to add support using your API and I agree that native support is best, but you already have code for those that are so inclined to add it themselves. So why not enable that possibility?

**Comment by The-Arcanian** [comment]
This may be off topic but looking at the code dispenser planting looks like it is really easy to account for. Just register the dispenser behavior using your BehaviourSeeds class when Botania or Quark are present.
I am not very familiar with Minecraft code so I wanted to make sure I understand for my own sake and for when I ask some mod authors to add compatibility.
