### ISSUE TITLE
Error opening plainstrider sash page 2 in book

### ISSUE THREAD

**Issue by coolman1324** [Vazkii/Botania#2465]
Forge version: 1.12.2-forge1.12.2-14.23.0.2545
Botania version: r1.10-350
Link to crash log: https://gist.github.com/coolman1324/83b4f59729c7a1fc4d1be549dac81a19

Steps to reproduce:
1.  Go to the plainstriders sash entry in the book, and flip to the second page of the entry. The game will then crash. Is reproduced every time.

What I expected to happen: Open the next page of the entry

What happened instead: Game crashed

**Comment by williewillus** [comment]
Update to 352
