### ISSUE TITLE
Flugal tiara flight indicator overlaps with underwater breath indicator when used with a potion of water breathing

### ISSUE THREAD

**Issue by JSideris** [Vazkii/Botania#2466]
Forge version: 1.12.2-14.23.1.2554
Botania version:  r1.10-352
Link to crash log: N/A
Steps to reproduce:
1.  Wear Flugal Tiara.
2. Drink Potion of Water Breathing on land.
3. Jump under water.

What I expected to happen:
![2017-12-14_05 19 37](https://user-images.githubusercontent.com/8083793/33987458-ecdbad18-e08e-11e7-8f31-03ca50977487.png)
Works fine before the potion is drunk.

What happened instead:
![2017-12-14_05 19 49](https://user-images.githubusercontent.com/8083793/33987454-e9906ed2-e08e-11e7-8ba7-259a77335f07.png)
Note that this only happens after jumping into the water with the water breathing potion effect active. Drinking the potion while under water doesn't immediately cause the issue.

**Comment by codycoolwaffle** [comment]
Are you using any other mods?

**Comment by JSideris** [comment]
Yes. I just re-tested with only the following mods installed:

Botania r1.10-352
Baubles 1.12-1.5.1
JEI (to easily get the flugal tiara through the UI)

Still able to reproduce issue.
