### ISSUE TITLE
[Crash Event][MC1.10.2-botania-r1.9-341]client crashed in Sponge Forge Server

### ISSUE THREAD

**Issue by Tollainmear** [Vazkii/Botania#2468]
Forge version: 1.10.2-forge1.10.2-12.18.3.2511
Botania version: r1.9-341

(And it also happened on Forge:2185 & Botania r1.8-314)

Link to crash log: 
                  [gist](https://gist.github.com/Tollainmear/77e4d33c4116b7073afcc0471129e2b3)

Steps to reproduce:
1. A player told me that his client was crashed
2.Then he restart & join the server(a server plugin will teleport players to the lobby while player join sever,so it wasn't crash that time)
3.But when he use a command to back to his home,the client crash again
4.He redo the step 2
5.He approach home by run normaly，so the chunk loaded one by one until his home was loaded and client crash again
6.Some player Others told me that they client was crash too while approaching his friend's home(loading the bad chunk)
7.So I update the botania to the latest version but crash still happened.

What I expected to happen:

What happened instead: client crashed

> But It is worth mentioning that the sponge-forge server still running without any exception

**Comment by williewillus** [comment]
#2205
