### ISSUE TITLE
Rod of the shifting crust shift right click crash

### ISSUE THREAD

**Issue by Poke1650** [Vazkii/Botania#2469]
Forge version: Forge 12.18.3.2511
Botania version: r1.9-341
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline): https://gist.github.com/Poke1650/09b44bcfc07d2df68ac4172198e280f5

Steps to reproduce:
1. Have a rod of the shifting crust (regname exchangeRod)
2. Shift right click the lower half of two cobble slabs on top of each other
3. NPE and crash

What I expected to happen:
Not crash

What happened instead:
Crashed :c

**Comment by williewillus** [comment]
sorry, we aren't releasing builds for 1.9/10 anymore. this problem should be fixed in 1.11/1.12, though.
