### ISSUE TITLE
Cannot place spark on an old mana pool

### ISSUE THREAD

**Issue by belathus** [Vazkii/Botania#2470]
Forge version: 1.12.2-14.23.1.2565
Botania version: 1.10-352
Link to crash log: Not a crash

Steps to reproduce:
1. Place spark on mana pool
2. Let mana pool fill with mana overnight
3. Remove spark with wand
4. Replace spark on mana pool

What I expected to happen:
Spark places on mana pool

What happened instead:
Nothing. Spark stayed in my hand.

I had a row of 4 fabulous mana pools (the problem still occurs with normal mana pools). They filled with mana, then stopped. Someone else decided to try troubleshooting them when I was offline and broke the pool trying to fix it, and couldn't place the spark back on it in the same spot. Seems no matter what I try, a spark will not go on a pool in that spot, even after a server restart. But, putting the pool in an adjacent block works just fine... until we've let that one sit for a while and then break that one, too.

Here I am trying to place the spark on the pool: https://i.imgur.com/zy4fvDQ.jpg

I'll admit, I have no idea what is going on here.

This probably isn't related, but there is a bit more: we also have a cart with mana pool underground and every once in a while one of the powered rails decides that it doesn't want to let the cart to pass. Breaking and replacing that rail doesn't help, and we can't put anything else there (though we can replace the powered rail, which still won't let a minecart pass). Though, pushing another block into that spot using a piston does fix the problem; doing similar to the mana pools from the aforementioned issue does not fix that problem.

**Comment by williewillus** [comment]
Is this on a server and Does it happen in the same world in SP?

**Comment by belathus** [comment]
I'll have to check. It is a big world, so it will take me a moment to
download it from the server.
