### ISSUE TITLE
Ticking entity - Runic Altar crashing players who get near

### ISSUE THREAD

**Issue by falcnor** [Vazkii/Botania#2471]
Forge version: forge-1.12.2-14.23.1.2565-universal
Botania version: Botania r1.10-352
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)
https://gist.github.com/falcnor/7553584d1a18124f0c775d2118774773
Steps to reproduce: Runic altar placed in the world, gaia mana spreader pointed at it from a pool.  Player walks by or logs in, crash to launcher.
1. 

What I expected to happen: To be able to walk by

What happened instead: Crashed client to launcher

**Comment by cybercatgurrl** [comment]
same problem 
[crash-2018-04-17_23.53.07-client.txt](https://github.com/Vazkii/Botania/files/1920071/crash-2018-04-17_23.53.07-client.txt)
