### ISSUE TITLE
Mana spreaders issue

### ISSUE THREAD

**Issue by TrickShotMagic** [Vazkii/Botania#2472]
Forge version: 1.12.2
Botania version: the last one for 1.12.2(?
More than a issue this would be something not yet implemented that I think will be great and help a lot, since Mana spreaders can take Mana from Mana pool, it would be great if you could link one to them, since it actually just picks up Mana from a Mana pool with Mana inside.

**Comment by TrickShotMagic** [comment]
At least I tried for exampling putting a Mana pool under a Mana spreader and afterwards one above it but it still picks up mana from both

**Comment by TheWhiteWolves** [comment]
iirc mana spreaders pull from any valid source touching them.

**Comment by TrickShotMagic** [comment]
Yeah that's the problem

**Comment by yrsegal** [comment]
This issue is relatively unreadable. What specifically are you asking for?

**Comment by Darinth** [comment]
@TrickShotMagic are you just wanting the ability to bind them to a specific adjacent spreader or are you wanting the ability to bind them to spreaders at range so a spreader could pull from a pool several blocks away?

**Comment by txr13** [comment]
I believe @TrickShotMagic wants the ability to bind a mana spreader to one (and only one) mana pool, so that the spreader only pulls from the bound pool, rather than pulling from all available pools.

**Comment by TrickShotMagic** [comment]
yeah thats correct, responding do txr14, sorry for not answering before i was busy, but yea thats what i mean, also had another suggest lately also related to binding (a thing that in my opinion could be much better) is that flowers automatically bind to mana pools, and you cant unbind it, got this problem with a ranuncarpus and had to break all mana pools near before planting the ranuncarpus so that it never gets mana since it radius it increased that way
