### ISSUE TITLE
Manasteel armor provides no armor?

### ISSUE THREAD

**Issue by Zsashas** [Vazkii/Botania#2477]
Forge version: 2565
Botania version: 352

Steps to reproduce:
1. Put some Manasteel armor on

What I expected to happen: To be protected

What happened instead: Tooltips show no armor rating, and the armor bar does not appear, even with a full set.

![2017-12-22_00 47 57](https://user-images.githubusercontent.com/6917535/34291599-ce6b1de0-e6b1-11e7-98cd-798a5dd59d9a.png)
![2017-12-22_00 48 01](https://user-images.githubusercontent.com/6917535/34291600-ce81dd14-e6b1-11e7-95cb-246068229e8a.png)
![2017-12-22_00 48 01_2](https://user-images.githubusercontent.com/6917535/34291601-ce974b36-e6b1-11e7-8e3a-c6d2d4e4ba50.png)

**Comment by williewillus** [comment]
cannot reproduce, I get the armor display icons.

the tooltip is intended, since the armor doesn't add protection the normal vanilla attribute way.

**Comment by InsomniaKitten** [comment]
If you have Rustic installed it is likely you are running an outdated version, which breaks the armor HUD for Botania's armor.  Try updating it.
