### ISSUE TITLE
Flight Meter has a background in third-person

### ISSUE THREAD

**Issue by Zsashas** [Vazkii/Botania#2480]
Forge version: 2565
Botania version: 352

Steps to reproduce:
1. Put on a Flugel Tiara
2. Hit F5

![2017-12-22_03 06 02](https://user-images.githubusercontent.com/6917535/34296021-56849b08-e6c5-11e7-8cb3-c34167d11edb.png)
![2017-12-22_03 06 04](https://user-images.githubusercontent.com/6917535/34296022-569af074-e6c5-11e7-85d6-75f12988d12d.png)
![2017-12-22_03 06 05](https://user-images.githubusercontent.com/6917535/34296023-56af8c64-e6c5-11e7-90df-2aed26dec47e.png)

**Comment by williewillus** [comment]
does this happen with botania alone?

**Comment by Zsashas** [comment]
Not sure, it also only happens to the first frame of a full icon on the bar. The instant an icon starts fading, the background vanishes.
