### ISSUE TITLE
Off-hand Rods cannot be seen when in use

### ISSUE THREAD

**Issue by Zsashas** [Vazkii/Botania#2481]
Forge version: 2565
Botania version: 352

Steps to reproduce:
1. Put a rod in the off-hand slot
2. Use it

They look fine in third-person.

Not in use:
![2017-12-22_03 09 07](https://user-images.githubusercontent.com/6917535/34296085-a1cb97e2-e6c5-11e7-8b83-80498400533e.png)

In use:
![2017-12-22_03 09 08](https://user-images.githubusercontent.com/6917535/34296088-a4ae6fa2-e6c5-11e7-9ecd-7ba20480ba25.png)

**Comment by williewillus** [comment]
cannot reproduce
