### ISSUE TITLE
Flugel Tiara prevents TiCon slime boots from working

### ISSUE THREAD

**Issue by Zsashas** [Vazkii/Botania#2482]
Forge version: 2565
Botania version: 352

Instead of bouncing, you stop dead stop on the ground as if you weren't wearing them.

**Comment by TheWhiteWolves** [comment]
Most likely due to the fall damage cancellation, iirc the slime boots only work once you've fallen 2 blocks (the fall damage threshold) and to cancel that damage the tiara will be keeping the player at or below 2.

**Comment by Zsashas** [comment]
Makes sense.
