### ISSUE TITLE
Terrasteel Ingot creation failure

### ISSUE THREAD

**Issue by Danickar** [Vazkii/Botania#2484]
Forge version:  2566 (Minecraft 1.12)
Botania version: 352
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)

No crashing

Steps to reproduce:
1.  Simply put the ingredients on the plate and wait.

What I expected to happen: Ritual is performed and terrasteel ingot is returned.

What happened instead: Ritual gets through various phases of completion (based upon the orb movement/colors) but the ingredients vanish and nothing is returned, every time. At least 20 different attempts have been made.

**Comment by williewillus** [comment]
cannot reproduce

make sure nothing is picking it up, and that you can give it enough mana to make the ingot before the ingredients despawn

**Comment by Danickar** [comment]
There is nothing that is picking up the ingredients, they simply vanish. The server item despawn timer is set to 10 minutes, so that isn't the problem either.

**Comment by williewillus** [comment]
can you reproduce it in single palyer with botania itself?

**Comment by Lethann** [comment]
I'm having this happen as well. There is no error given, nothing showing up on the server logs. It just starts to go and it's taking forever, then the items vanish with no terrasteel given. I wish there was a way to precharge the plate to avoid timeouts, etc
