### ISSUE TITLE
Toggle and Fork Luminizer recipe pages are switched

### ISSUE THREAD

**Issue by Zsashas** [Vazkii/Botania#2486]
![2017-12-23_10 23 56](https://user-images.githubusercontent.com/6917535/34321780-be50dede-e7cb-11e7-8bf9-55fcff465f1e.png)
![2017-12-23_10 23 59](https://user-images.githubusercontent.com/6917535/34321781-be67c72a-e7cb-11e7-914c-18f9388079c5.png)
![2017-12-23_10 25 23](https://user-images.githubusercontent.com/6917535/34321782-be7c738c-e7cb-11e7-8c0c-56a0a2c3d333.png)
![2017-12-23_10 25 31](https://user-images.githubusercontent.com/6917535/34321783-be90c51c-e7cb-11e7-815f-5f1c46d09300.png)

**Comment by HipHopHuman** [comment]
@williewillus This issue needs to be re-opened, as it has appeared again in 1.16.4:

![image](https://user-images.githubusercontent.com/70091260/106536947-0a2d1a00-6502-11eb-936c-736118d4677b.png)
![image](https://user-images.githubusercontent.com/70091260/106536863-e8cc2e00-6501-11eb-88ed-954690ba5a20.png)
![image](https://user-images.githubusercontent.com/70091260/106536885-eff33c00-6501-11eb-9650-4c67faba4c7c.png)
