### ISSUE TITLE
Weight Lens and Lapis Lazuli Ore Block Creating Untextured Items

### ISSUE THREAD

**Issue by LeoIP** [Vazkii/Botania#2488]
Forge version: 1.12.1 - 14.22.1.2485/1.12.2 - 14.23.1.2581
Botania version: R1.10 352
FML Log: https://pastebin.com/NMWzNNEX

Steps to reproduce:
1. I found a bug using the weight lens and lapis lazuli ore block, creating an untextured version of the ore block. 

When the weight lens apply to the lapis lazuli ore block, and the ore block drops onto a slab, or anything that makes it drop itself, it will drop an untextured version of the lapis lazuli ore block. Picking up the item will result in having an untextured item. And when you pick up more lapis lazuli ore blocks (which are not broken), they will stack, creating more untextured lapis lazuli ore blocks. But the blocks still acts the same. This only works with lapis lazuli ore blocks, with the blocks that I have tested.

**Comment by williewillus** [comment]
this is a vanilla bug with the falling sand entities (that's fixed in the 1.13 snapshots), so nothing botania has control over. As a workaround, just place and break them again.
