### ISSUE TITLE
Mobs killed by Unstable Reservoir bolts do not drop player kill drops

### ISSUE THREAD

**Issue by Zsashas** [Vazkii/Botania#2492]
Forge version: 2565
Botania version: 352

Things like all the mob drops from Reliquary, or Ability Totems from Everlasting Abilites never drop when using the rod.

**Comment by williewillus** [comment]
cannot reproduce. We pass the player to the damage function and it appears to apply: Blazes drop blaze rods, which are a player-kill-only drop. Can you do this with botania or just the mods in question alone?

**Comment by williewillus** [comment]
bump?

**Comment by williewillus** [comment]
stale
