### ISSUE TITLE
Loonium loot table server crash

### ISSUE THREAD

**Issue by falcnor** [Vazkii/Botania#2493]
Forge version: forge-1.12.2-14.23.1.2565-universal
Botania version: Botania r1.10-352
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)
https://gist.github.com/falcnor/264fb143e8bdc09a6573ee7552dc6d60

Steps to reproduce:
1.  Place mana pool and loonium.  Let the loonium grab loot from a loot table.  Server crashes.

What I expected to happen: Loonium to produce loot and mobs.

What happened instead: Loonium attempts to pull loot from loot table and crashes server.

**Comment by williewillus** [comment]
does this happen with just forge + botania? and are there mods that are modifying loot tables?

**Comment by falcnor** [comment]
I am not the server admin, so unable to try only forge/botania.
And yes, I believe there are a few mods that do modify loot tables.
Is there any way to get a more verbose log of what the loonium is specifically trying to pull from a table?

**Comment by williewillus** [comment]
it's just calling the vanilla function to generate loot (as if you set the same loot table on a chest and opened it). 

The table it's trying to draw from is in the NBT tag of the flower, which you can see by doing `/blockdata <coords of flower> {}`

**Comment by falcnor** [comment]
I will work with the admin and see if we can't get more infos.
Thanks willie!

**Comment by belathus** [comment]
Server admin here. Yeah, I'm heavily modifying the loot table via [LootTweaker](https://github.com/Leviathan143/LootTweaker). The script I wrote to modify the table is [here](https://github.com/belathus/Wanderlust-Renewed/blob/master/scripts/loot.zs). Looks like the loonium is pulling from "minecraft:chests/simple_dungeon". I've been running a loonium in my single player world with the same mods and changes, and several mobs have spawned with no issues.

I've just used Random Thing's Loot generator to spawn a bunch of simple dungeon chests, and it doesn't seem to totally respect the script I wrote (it is giving way too much condensed blood when it should only give 1-5 per chest, it still gets stuff from Random Things, etc. despite that I removed everything from the loot table via the .clear() function). No crashes from it, though, after generating a dozen chests this way.

**Comment by belathus** [comment]
So I broke the loot script by updating some mods today (they removed items that I had added via the script) and, when I loaded my SinglePlayer test world that had a running loonium, it almost immediately crashed.

I think that the script may have been broken when Falcnor was messing with the Loonium, which might answer the question as to what caused the crash.

**Comment by williewillus** [comment]
does a crash (or at least some log spam) occur if you set the loot table onto a chest using `/blockdata` and open the chest? (there's probably instructions to do this on the wiki or somewhere). the loonium generates loot exactly the same way a dungeon chest does, so I want to make sure it's a botania issue and not a loot tweaker one

**Comment by belathus** [comment]
I'll intentionally re-break the script and see what happens.
