### ISSUE TITLE
Generation LivingWood stairs in the world

### ISSUE THREAD

**Issue by pingvikin** [Vazkii/Botania#2495]
Forge version: 1.12.2-14.23.1.2582-universal
Botania version: 1.10-352

Hello, I installed your mod, and encountered a very interesting situation: in the new generated world, can often be found standing alone stairs of the living-wood.

Screenshot:
![2018-01-01_18 46 56](https://user-images.githubusercontent.com/26678843/34469010-64968242-ef26-11e7-9846-75331a3f082d.png)

**Comment by SimulatorSia** [comment]
you should provide a list of other mods you have to help them, it's probably an ID issue.
https://minecraft.curseforge.com/projects/notenoughids
this mod might help
