### ISSUE TITLE
Hopperhocks not sorting correctly with quark's varient chests

### ISSUE THREAD

**Issue by Evo112358** [Vazkii/Botania#2497]
Forge version: 14.23.1.2562
Botania version: r1.10-350
Quark version: r1.4-120

It was suggested on reddit i post here after noticing hopperhocks werent filtering correctly in the 1.12.2 version of Garden of glass by melanX. 
I have modified the pack, however the below can be reproduced on a fresh install, on the latest forge and botania.

Steps to reproduce:
1. Load into a new gog world.
2. Place 3 quark chests, 2 of one wood type 1 of another side by side. (think normal, trapped, normal chest pattern)
3. Add item frames to the face and add items. (i used each chest and the item frame as all 3 are already in inventory)
4. Add either floating hopperhocks behind the chests. 
5. Toss the items associated to the item frames onto the middle chest or hopperhocks. (the range indicated by the monocle covers both areas)

What I expected to happen:
Items sorted into correct chest, indicated by the item frames.

What happened instead:
If hopperhock is used, all items are placed into the chests at random. 2 items in 1 chest, 1 in another. 
If hopperhock petite is used, all items are placed into middle chest.

**Comment by Evo112358** [comment]
![image](https://user-images.githubusercontent.com/32474418/34517158-f853e06c-f0cd-11e7-990e-c2785cfd9e11.png)
this is the setup that i mentioned.
![image](https://user-images.githubusercontent.com/32474418/34517183-1a039e3c-f0ce-11e7-8a62-6126cb6d5dd1.png)
this is the result from the petite hopperhocks.

**Comment by quat1024** [comment]
A guess: the hopperhock is probably assuming that the chests form a double chest, even though they do not
