### ISSUE TITLE
Planestrider's Sash not craftable

### ISSUE THREAD

**Issue by NoodlesKing** [Vazkii/Botania#2498]
Forge version:1.12.2-14.23.1.2582
Botania version:r1.10-352(Baubles 1.12-1.5.1)

**Comment by williewillus** [comment]
you need to have any filled map in the top middle slot, I'm not sure why JEI doesn't show it properly but if you do then the recipe works.

**Comment by NoodlesKing** [comment]
Ok the Botania book also does not include the map
