### ISSUE TITLE
Flügel Tiara Overrides Extra Utilities' wing rings

### ISSUE THREAD

**Issue by SimulatorSia** [Vazkii/Botania#2499]
Forge version: 12.2-14.23.1.2582
Botania version: all latest all the way down past 1.7.10 but I'm currently on 1.12.2

What I expected to happen: have infinite flight while wearing the Extra Utilities flight rings and a Flügel Tiara

What happened instead: the Flügel Tiara runs out of flight overriding Extra Utilities, also the Flügel Tiara named "Flügel" makes a the left wing from Extra Utilities not render.
https://i.imgur.com/ZEZcbH7.png

(Side issue) Soujourner's sash doesn't let you bounce on slime blocks, CFM's trampoline or diving board.

These issues have been in Botania as long as I can remember, I never got around to saying something about them till now.

**Comment by SimulatorSia** [comment]
no one gonna reply? ;m;

I cry

**Comment by SimulatorSia** [comment]
I see other issues being closed and helped... Why not mine >:(

**Comment by quat1024** [comment]
This is because the angel ring and the tiara end up fighting over `player.capabilities.allowFlight`. The angel ring wants it on, the tiara wants it off.

This proposed Forge feature would allow for a solution, but I don't know if there's any progress on it: https://github.com/MinecraftForge/MinecraftForge/pull/3931

**Comment by SimulatorSia** [comment]
oh, I'm sorry for sounding insensitive >.<
I didn't know it was an issue of competing usage of .class'

**Comment by SimulatorSia** [comment]
What about the other issues? One wing not rendering, soujourner's sash not letting you bounce on slime blocks, CFM's trampoline or diving board.

You know you could solve the first issue by adding code to disable Flügel Tiara entirely when the Wing Ring is present in the inventory...

**Comment by quat1024** [comment]
Did you seriously put 4 bugs in the same issue report, are you crazy

**Comment by williewillus** [comment]
"conflicting creative flight" is an issue faced by every mod that adds creative flight -
the linked forge PR is a likely solution but it seems pretty dead. if someone doesn't pick it up I might get around to it sometime ^tm but until then just don't have conflicting items together

**Comment by SimulatorSia** [comment]
I'm sorry, I didn't know I wasn't supposed to add multiple in one report. What should I do?

**Comment by quat1024** [comment]
Well that sounds like a recipe for bugs

Also hardcoding behavior for other mods' items is stupid

**Comment by SimulatorSia** [comment]
Should I close the issue?
