### ISSUE TITLE
Pure Daisy Metadata

### ISSUE THREAD

**Issue by Zer0Lyfe** [Vazkii/Botania#2501]
Forge version: 14.23.1.2584
Botania version: r1.10-352 (1.12)
Link to crash log: No Crashes

Steps to reproduce:
1. use this Script https://gist.github.com/Zer0Lyfe/1f49ba2dcad1086cd8fcc153fa151f63
(test script is block of Constantan to block of uranium for testing purposes)
2. try converting block of Constantan to block of uranium

This issue has been brought up to Jared here
https://github.com/jaredlll08/ModTweaker/issues/579
and has said this is an issue with botania

What I expected to happen:
to convert to uranium

What happened instead:
converts to copper instead.

**Comment by Zer0Lyfe** [comment]
![2018-01-06_12 03 43](https://user-images.githubusercontent.com/28994351/34636324-b53945e8-f2d9-11e7-8e15-9ee522da9ded.png)
this is what happens when shown in Jei

**Comment by williewillus** [comment]
fixed, but modtweaker will need to update to pass an IBlockState, after the next Botania version has been released.

**Comment by Zer0Lyfe** [comment]
ok thank you.
