### ISSUE TITLE
IllegalAccessError when attempting to add Botania to the dev environment

### ISSUE THREAD

**Issue by TurboPig** [Vazkii/Botania#2502]
**Forge version:** MDK 1.12.2 - 14.23.1.2578
**Botania version:** r1.10-352-deobf
**Link to crash log:** https://gist.github.com/TurboPig/103e65edb1997bed3b3aceaa95eb71c4#file-crash-2018-01-06_14-54-20-client-txt

**Steps to reproduce:**
1. Add deObf Botania JAR to /libs folder.

    - I have also put `compile files("libs/Botania r1.10-352-deobf.jar")` in `build.gradle` dependencies; same error regardless.

2. Attempt to run client

**What I expected to happen:**
Botania should be added to the dev environment.

**What happened instead:**
Crash!

As per issue #2378 I have also attempted to delete the /build folder, run `setupDecompWorkspace` again, and refresh the Gradle project, but this has not resolved the issue.
Additionally, trying to download Botania through the Gradle dependencies (how do I word this? Adding the Botania repository and specifying the dependency as the appropriate path) results in a handshake error.  Disabling SNI only resulted in further errors.  Thus, I have instead added Botania to the /libs folder.

**Comment by williewillus** [comment]
add this line to your gradle in the right place https://github.com/Vazkii/Botania/blob/master/build.gradle#L57

**Comment by TurboPig** [comment]
Unfortunately, `useDepAts = true` made no difference.  I am still getting the same crash.

**Comment by yrsegal** [comment]
Yeah, this is not solved. You can do a "patch" by copying botania_at.cfg to your build/depAts folder, but this is NOT A SOLUTION, merely a way to get around the error for now.
