### ISSUE TITLE
Feather Feet Tainted Blood Pendant is Flawed

### ISSUE THREAD

**Issue by MaxAstro** [Vazkii/Botania#2503]
Forge version: 12.18.2.2477 (SkyFactory 3 version 3.0.15)
Botania version: 1.9-341

Steps to reproduce:
1. Create, equip, and power a Feather Feet Tainted Blood Pendant
2. Jump off a ledge, timing it so that you land exactly as the effect refreshes

What I expected to happen:
Pendant should stop all falling damage

What happened instead:
If you hit the ground very close to the tick that the pendant refreshes (might be the exact tick?), you take full falling damage

**Comment by williewillus** [comment]
This is just because fall damage is partially controlled by the player, so this is probably lag.

I'll make the pendants refresh a *bit* sooner (when the effect reaches 50ms left, which is about the average round trip ping time on a decent internet connection)
