### ISSUE TITLE
corporea index broadcasting in smp chat

### ISSUE THREAD

**Issue by forestasog** [Vazkii/Botania#2507]
Modpack version: Direwolf20 1.12 1.4
Forge version: 14.23.1.2566
Botania version: 1.10-352

Steps to reproduce:
1.  request items from corporea index while in smp

What I expected to happen: people to not think i'm crazy

What happened instead: people think i'm crazy

**Comment by williewillus** [comment]
are you using another mod like a server management mod that listens/modifies chat? Botania properly cancels messages sent near an index, unless another mod is interfering or forge is broken

**Comment by forestasog** [comment]
alright i asked the server owner and they're looking into it

**Comment by forestasog** [comment]
i think he said essentials plugin did what you said, but i stopped playing on that server.  i might have another issue though, i thought ring of odin was supposed to give regeneration?

**Comment by TheWhiteWolves** [comment]
no the Ring of Odin doesn't give regen, it gives you 10 extra hearts and immunity to suffocation, drowning, fire, lava, starvation and fall damage.

**Comment by forestasog** [comment]
haha ok, thx for the help :)
