### ISSUE TITLE
[1.12.2] Flügel Tiara Crash (NoSuchMethodError)

### ISSUE THREAD

**Issue by SjetCraft** [Vazkii/Botania#2512]
Forge version: 14.23.1.2587
Botania version: r1.10-352
Link to crash log: [gist](https://gist.github.com/SjetCraft/11a99d41d01ffcb48f7bbd80a4815868)

Steps to reproduce:
1. Equip Flügel Tiara,
2. Have a Greater Band of Mana in inventory
3. Attempt to fly.

What I expected to happen:
Fly and not crash.

What happened instead:
Crash to desktop.

**Comment by SjetCraft** [comment]
Also tested with Forge version: 14.23.1.2560.

**Comment by williewillus** [comment]
same root cause as #2509
