### ISSUE TITLE
[1.12.2] Server Crash - maybe Baubles Packet Sync Issue?

### ISSUE THREAD

**Issue by Vyraal1** [Vazkii/Botania#2513]
Forge version: Forge 14.23.1.2584
Botania version: Botania r1.10-352.jar     
Baubles version: 1.12-1.5.2 (not sure if relevant)
Link to crash log: https://pastebin.com/6jQBPHmR

Steps to reproduce:
1. According to my tester he was just walking over wood slabs and dirt with a Pure Daisy on it. Crashed with a ring of magnetization on him.

What I expected to happen:
Not crashing.

What happened instead:
Rip.

**Comment by williewillus** [comment]
Same as #2509
