### ISSUE TITLE
Joke-Things

### ISSUE THREAD

**Issue by CTH999** [Vazkii/Botania#2515]
So, if people keep pestering you to add in a feature, add it in, but as a joke

For instance, instead of not adding in an alfhime dimension if someone asks for it, add it in. But, the portal is very complex, and it sends you to an overworld with no ores or structures, and no way out, not even death. You can't get out. The "explanation" could be something like "It appears a very powerful being might have pulled a joke on me. Sending me to this place. Taking all items but the lexica botania. I don't know who it was, but I suspect, I don't know why, but the name Vazkii comes to my head."

That should show people who are pestering you!

P.S. It's just a joke idea (Not an idea I put here as a joke, but an idea that is a joke in the mod)
I'm just giving suggestions)

P.P.S I got this idea from [Stuff you won't see in Botania](https://vazkii.us/p/stuff-you-wont-see-in-botania/)

P.P.P.S. Have fun modding!

**Comment by williewillus** [comment]
Wut

**Comment by CTH999** [comment]
What do you mean wut?

**Comment by yrsegal** [comment]
He means wut, because this is a nonsensical suggestion that, according to the *very thing you linked* is invalid.

**Comment by CTH999** [comment]
@yrsgal, what I meant was add it in, but don't (It was an idea for a joke, and I see what you mean. Thanks for explaing)

And it does make sense, at least to me, but I see exactly what you mean,
