### ISSUE TITLE
Feather Feet Breaking Crops?

### ISSUE THREAD

**Issue by MaxAstro** [Vazkii/Botania#2516]
Forge version: 12.18.2.2477 (SkyFactory 3 version 3.0.15)
Botania version: 1.9-341

Steps to reproduce:
1. Create, equip, and power a Feather Feet Tainted Blood Pendant
2. Walk on farmland

What I expected to happen:
Nothing

What happened instead:
Farmland instantly reverted to dirt, breaking the crops on it; taking the pendant off causes this to stop happening, while putting it back on while standing on a farmland tile turns that tile into dirt.

**Comment by codycoolwaffle** [comment]
Feather feet too op?

I can replicate this on latest Botania(352)
