### ISSUE TITLE
Baubles / Botania kicks off server and won't let back on.

### ISSUE THREAD

**Issue by Toapoint** [Vazkii/Botania#2517]
Forge version: forge- 14.23.1.2589
Botania version: 352
Link to crash log: 
https://pastebin.com/868uzNeT

Modpack in use:
https://minecraft.curseforge.com/projects/shavercraft

Steps to reproduce:
1. Just take a Botania flying device [The tiara's], open baubles, and place on the helmet. 

What I expected to happen:
Just to be able to fly
What happened instead:
Server won't let me back on unless I delete my player file

**Comment by yrsegal** [comment]
Reproduced in Natural Pledge dev environment.

**Comment by JolyGoodDay** [comment]
Server updated, kicks me if I try and fly.

**Comment by DoragonKeiyou** [comment]
Similar issue, single player with same version, Terrasteel Equipment + Greater Mana Ring.  Put ring on, instant game crash, and continues to crash every load-in.

**Comment by williewillus** [comment]
Same as #2509, downgrade baubles as a temporary workaround
