### ISSUE TITLE
Putting rings on crashes client [Unable to login to servers]

### ISSUE THREAD

**Issue by Toapoint** [Vazkii/Botania#2519]
Forge version: 14.23.1.2590
Botania version: 352
Link to crash log: 
Crash: https://pastebin.com/LEABxQ7d
Video leading to Crash: https://youtu.be/zbXr2GEXdGA
Modpack: https://minecraft.curseforge.com/projects/shavercraft

Steps to reproduce:
1. Open Inventory
2. Place botania ring in Baubles slot

What I expected to happen:
For the item to work
What happened instead:
Client crashes and unable to log back in single player. On Multiplayer, the game refuses to let be back on the server. The server does not crash.

**Comment by williewillus** [comment]
fixed in next botania. as a stopgap in the meantime, downgrade baubles to the previous 1.12.x version
