### ISSUE TITLE
ticking entity crash mana storage

### ISSUE THREAD

**Issue by NalyKalZul** [Vazkii/Botania#2520]
Modpack: mech & magic 2.0.3 for 1.12.2
Forge version: 14.23.1.2584
Botania version: r1.10-352
Link to crash log: https://gist.github.com/NalyKalZul/1512c8e4f7df68931e2f7941cfeec539

Steps to reproduce:
1. equiped either the mana band or a have a tablet inside the inventory with any amount of mana value above 0, i used the band of aura to trigger the instant crash after equipping it.

What I expected to happen: to have access to the basic resource of botania on the player for using items

What happened instead: turned into a ticking player entity, single player crashes back to the atlauncher launcher, on the official M&M server it gives a iou exception error and kicks me back to the main minecraft menu.

**Comment by williewillus** [comment]
fixed in next botania, downgrade baubles as a workaround

**Comment by NalyKalZul** [comment]
thank you, ill pass on the fix to the mod pack owner
