### ISSUE TITLE
Fel Pumpkin Configs

### ISSUE THREAD

**Issue by Vyraal1** [Vazkii/Botania#2521]
Forge version: 2590
Botania version: 352

Would it be possible to add configs for Fel Pumpkin blazes to allow them to drop Blaze Rods? How actually do the drops for these mobs work? Are they marked to specifically not drop any blaze rods and cancel that event? The reason I ask is that it's a small automation challenge that I want the player to have in order to get their first blaze rods (Nether access occurs later in my pack than normal).

**Comment by williewillus** [comment]
fel blazes now use a loot table, use loottweaker or a custom loot table to modify their drops
