### ISSUE TITLE
Adding Garden of Glass causes Botania not to be seen by Forge

### ISSUE THREAD

**Issue by JGgithub2018** [Vazkii/Botania#2522]
Forge version: 1.10.2 - 12.18.3.2185
Botania version: r1.9-341
Link to crash log: https://gist.github.com/JGgithub2018/a5aaca6faa805fd7cd3b5336adbd0a30

Steps to reproduce:
1. Download Botania _AND_ Garden of Glass.
2. Place them BOTH in the mods folder before running the game.
3. Run Minecraft Forge (the version written above).

What I expected to happen:
The mods would run smoothly.
What happened instead:
Forge states that I don't have Botania, says I need to either get Botania or delete Garden of Glass.

**Comment by codycoolwaffle** [comment]
1) I don't see any signs of a crash in that file
2) I don't see Botania sending anything

Did you send the right file?
