### ISSUE TITLE
Mana Band Crashing Game

### ISSUE THREAD

**Issue by Astral2003** [Vazkii/Botania#2523]
Forge version: Forge 14.23.1.2589 (For Minecraft 1.12.2)
Botania version: Botania r1.10-352
Link to crash log: https://gist.github.com/Astral2003/0a184e6180eb2896322671d183ca9df7
Other Mods: https://gist.github.com/Astral2003/071ea1a54ac7ecbbed868d3b5e58445f
Steps to reproduce:
1. Start Singleplayer
2. Create materials to craft Mana Band
3. Craft Mana Band
4. Equip Mana Band in Bauble Ring Slot

What I expected to happen:
Mana Band would equip as normal and work as expected

What happened instead:
The game froze briefly upon equipping the Mana Band and proceeded to crash. The world can no longer be accessed without uninstalling Botania or finding a way to edit player data to remove the Bauble.

**Comment by williewillus** [comment]
fixed in the next version of botania, downgrade baubles for a workaround in the meantime
