### ISSUE TITLE
Dw20 1.12 pack, game crashes when i equip the Band of Mana and Sojourner's Sash

### ISSUE THREAD

**Issue by Shackram** [Vazkii/Botania#2524]
Forge version: 14.23.1.2587
Botania version: r1.10-352
Link to crash log: https://gist.github.com/Shackram/35c4a3ccde505820ba71a89e08059d17

Steps to reproduce:

1. Get a Sash (or any other accessory that consumes mana) and a band of mana (with some mana on it)
2. Equip one of them to the bauble slot
3. Equip the other one, the actual order doesn't matter
4: When the second is equiped, the game crashes. If you then try to load the save it crashes during loading.

What I expected to happen: Accessories work as they should
What happened instead: Game crashes

I've tested on creative and it also crashes if i use a tool that consumes mana while the band of mana is in the bauble slot, no issue if the band is in the inventory.

Using NTB explorer to move the Band of Mana from the bauble slot to the inventory i was able to load the save. Both the sash and band of mana work normaly, doesn't crash as long as i don't equip the band into the bauble slot.

**Comment by williewillus** [comment]
fixed in next botania, downgrade baubles in the meantime for a temporary fix

**Comment by Shackram** [comment]
That worked, thanks!
