### ISSUE TITLE
multiplayer issue with Soujourner's Sash 

### ISSUE THREAD

**Issue by ShinyChunks** [Vazkii/Botania#2525]
Forge version: 14.23.1.2555
Botania version: r1.10-352
Link to crash log: [log](https://gist.github.com/ShinyChunks/79a08fedb76ce0a07f6426deff95cc60)

Steps to reproduce:
1. Equipped Soujourner's Sash on Server in Baubles slot -> kicked from server

What I expected to happen: 

What happened instead: rejoining the server is impossible

This happened to a friend. Oddly enough I can't recreate this issue with my account on the server while giwing me the sash in creative mode...

edit: I can recreate the issue. It only seems to happen if you also wear a charged mana ring. If you then put the sash in the baubles slot you get kicked from the server.

edit 2: This only happens if both items are in the baubles slots. If you put the sash in the belt slot but keep the ring in the inventory it works fine...

**Comment by williewillus** [comment]
Fixed in next botania. In the meantime downgrade baubles as a workaround

**Comment by zuoanqh** [comment]
glad to know i was on the right track to downgrade baubles lol. Thanks for the fix!

**Comment by ShinyChunks** [comment]
I used the sash with a mana tablet in the inventory as a workaround. But nice to know it'll be fixed soon.
Thanks!
