### ISSUE TITLE
Crash fighting Gaia Guardian II

### ISSUE THREAD

**Issue by PaulMurrayCbr** [Vazkii/Botania#2526]
Forge version: Project Ozone Lite, 1.3.3 (twitch version)
Botania version: Project Ozone Lite, 1.3.3 (twitch version)
Link to crash log: https://gist.github.com/PaulMurrayCbr/0702047432098f2603077512015c90c1

Steps to reproduce:
1. Offer Gaia Spirit Ingot to gaia altar
2. stand underneath the guardian
3. spam-click guardian with an infinity sword

What I expected to happen: guardian II dies, get loot.

What happened instead: game crashed.

**Comment by TDplai** [comment]
Just thought I'd retrieve some info from the crash report, might help resolve the issue.
Forge version 12.18.3.2511
Botania version r1.9-341 (latest 1.10.2 botania)
MCver 1.10.2

**Comment by codycoolwaffle** [comment]
Looks more like you killed it before it could finish spawning and rendering what it needs. As it's supposed to be invulnerable during that time, and the infinity sword negates that, I doubt this will be fixed. No chance for it to be fixed on 1.10.2 either, as Botania is on 1.12.2, and we don't backport.

**Comment by williewillus** [comment]
does the infinity sword really ignore invulnerability flags on mobs? jesus christ

**Comment by codycoolwaffle** [comment]
I believe so, since instead of dealing damage, it kills the entity

**Comment by codycoolwaffle** [comment]
The way it works is they set the entity's health to 0 in the hitEntity function

**Comment by williewillus** [comment]
not going to support mods that do breaking things like this
