### ISSUE TITLE
Ring of Magnetization deletes items when the item is thrown

### ISSUE THREAD

**Issue by sunsparkda** [Vazkii/Botania#2527]
Forge version: 14.23.2587
Botania version: r1.10-352
Link to crash log: n/a

Steps to reproduce:
1. Equip a ring of magnetization
2. Throw an item from your hotbar with hotkey (q by default)

What I expected to happen: The thrown item appears in the world.

What happened instead: The thrown item is deleted.

Note that this does NOT occur if you throw an item from the inventory screen. It only occurs when using the hotkey to throw an item from your hotbar.

**Comment by williewillus** [comment]
known issue, fixed in next botania
downgrade baubles for a fix in the meantime
