### ISSUE TITLE
[1.12] Server Crash when using Botania Baubles

### ISSUE THREAD

**Issue by MasterEnderman** [Vazkii/Botania#2528]
Forge version: 14.23.1.2602
Botania version: r1.10-352
Link to crash log: https://pastebin.com/WvQvy3SP

Steps to reproduce:
1. Be on a Server
2. Wear a Magnet Ring
3. Open Baubles menu

What I expected to happen:

Baubles Menu opens and let's you change out your botania baubles

What happened instead:

The server crashes and all clients get kicked from the server.

**Comment by williewillus** [comment]
Fixed in next botania or downgrade baubles

@vazkii maybe we should release soon we've gotten like 7 dupes of this

**Comment by mrdeadlocked** [comment]
A release would be great. :-)
