### ISSUE TITLE
Band of Aura / Mana crash

### ISSUE THREAD

**Issue by TDplai** [Vazkii/Botania#2529]
Forge version: 14.23.1.2590
Botania version: r1.10-352 (1.12, latest as of writing)
Link to crash log: https://pastebin.com/gJa2UM9t

Steps to reproduce:
1. Get Band of Aura (encountered with greater)
2. Equip
3. Get Band of Mana (encountered with full greater from creative menu)
4. Equip
(encountered in Creative Singleplayer with 256x Sphax and BDcraft sounds/music, but also crashes without. Also, I'm using Garden of Glass and Optifine. May be an optifine issue.)

What I expected to happen: Mana for use

What happened instead: Game crash and every time I attempt to log back in it crashes again. (isn't that a corrupt world or something? .'|)

**Comment by TDplai** [comment]
Currently testing without Optifine.

**Comment by TDplai** [comment]
Still crashes with no optifine and no rpacks.
In case it's helpful, optifine-free crash: https://pastebin.com/3Z49uywd

**Comment by williewillus** [comment]
duplicate issue
fixed in next botania
downgrade baubles for a workaround in the meantime

**Comment by TDplai** [comment]
Good to know it'll be fixed. :)
