### ISSUE TITLE
Crash using Flugel Tiara

### ISSUE THREAD

**Issue by ChiefLogan3010** [Vazkii/Botania#2530]
Forge version: 14.23.1.2601
Botania version: R1.10-352
Link to crash log: https://gist.github.com/ChiefLogan3010/a6e9fcf5b40b0b0909ac07ee906c8f2b (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)

Steps to reproduce:
1. The first time it happened while using the 'boost' feature of the Flugel Tiara into some leaves, then while trying to reproduce it, I crashed as soon as I attempted to fly. It was the Phoenic wings version and taken from JEI's cheat mode if that makes any difference.

What I expected to happen:
I fly.

What happened instead:
I crash.

**Comment by williewillus** [comment]
fixed in next botania
downgrade baubles in the meantime for a workaround
