### ISSUE TITLE
Ring of magnetization removing dropped items.

### ISSUE THREAD

**Issue by DigitalSketch** [Vazkii/Botania#2532]
Forge version: 14.23.1.2599
Botania version: 1.10-352
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)

Steps to reproduce:
1. Equip ring of magnetization
2. Drop an item from your inventory
3. Item vanishes forever, ring's "gem" seems to change to a dark color

What I expected to happen:  When I drop items, they shouldn't vanish.

What happened instead: I was disappointed that my items vanished.

**Comment by williewillus** [comment]
update botania
