### ISSUE TITLE
Crash with band of mana/baubles

### ISSUE THREAD

**Issue by kevador** [Vazkii/Botania#2534]
Forge version: ?? FTB revelation 1.4.0
Botania version: R1.10 352
Link to crash log: 
1: https://gist.github.com/kevador/bee67d22f2506192975fd358d931a605
2: https://gist.github.com/kevador/cde02a26638eb8eeb7d18909d0bd4077
3: https://gist.github.com/kevador/f70551eeb3135edbad92b371a99aebb1
4: https://gist.github.com/kevador/35220d45ab9f7a7ce45e172b98cb91a3
5: https://gist.github.com/kevador/b1c5aff6565432aec5bafb18d495fb90

(i don't know which one is which but i only loaded up single player to test what caused the crash so i assume these all have something to do with it)

Steps to reproduce:
1. something with putting the (greater) band of mana inside the baubles, or taking it out of the baubles slot.  (it seemed to only happen with an empty one) I've tried multiple things now and it crashes at random moments when i am hloding the band of mana with my mouse in my inventory

What I expected to happen:
amm, the game to work and not crash?

What happened instead:
it crashed.....

**Comment by williewillus** [comment]
update botania to 353+ or downgrade baubles to the previous version
