### ISSUE TITLE
Rock Crystal Disappearing with Greater Ring of Magnetization

### ISSUE THREAD

**Issue by bthrom** [Vazkii/Botania#2535]
Forge version: 1.12.2(modded) forge 14.23.1.2601
Botania version: r1.10.353
Link to crash log: N/A

Steps to reproduce:
I go to throw a rock crystal in a pool of starlight when wearing the greater ring of Magnetization the rock crystal just vanishes nothing hits the ground nothing goes in the pool nothing back into my inventory tried to disable ring with Solegnolia and same things happen. I take the ring off and it works like it should into the pool no issue. There is no crash log but running most updated version 1.12.1-1.8.5 of astral Sorcery and r1.10.353 of Botaina 

What I expected to happen:
The rock crystal goes into the pool of starlight or ground
What happened instead:
The rock Crystal Vanishes 

Cross-posted on Astrals Github
https://github.com/HellFirePvP/AstralSorcery/issues/543

**Comment by kevador** [comment]
wasn't there the issue where anything you drop out of your inventory while wearing the ring of magnetization will delete it?

**Comment by bthrom** [comment]
The Rock Crystals so far has been the only thing I have noticed it on

**Comment by PG-Fuury** [comment]
I have been noticing this interaction too, as it is in the current FTB:Revelations

**Comment by PG-Fuury** [comment]
I have noticed that when I drop things, the game doesn't allow me to open any inventory GUIs, except vanilla chests, where the dropped item is immediately in my hand

**Comment by codycoolwaffle** [comment]
This sounds an awful lot like issue #2509... Is Baubles updated?

**Comment by PG-Fuury** [comment]
got it fixed by updating baubles, no idea about bthrom

**Comment by bthrom** [comment]
Will have to try that when I get home
