### ISSUE TITLE
Manifest doesn't provide AT to dependant mods

### ISSUE THREAD

**Issue by yrsegal** [Vazkii/Botania#2536]
https://github.com/yrsegal/NaturalPledge/tree/1.12

When I setup using Botania (as of [latest maven build](https://github.com/yrsegal/NaturalPledge/blob/1.12/build.gradle#L87)), despite [using dep ATs](https://github.com/yrsegal/NaturalPledge/blob/1.12/build.gradle#L39), the `botania_at.cfg` isn't copied into my `build/depAts` folder, causing all builds and runs to fail with a security exception.

This can be solved by copying `botania_at.cfg` into the `build/depAts` manually, so it's not a problem with the AT, but in how it's set up in the manifest.

**Comment by williewillus** [comment]
so what am I supposed to do to fix this :thonk: idk how the manifests work

**Comment by yrsegal** [comment]
i don't either maybe don't have it in a META-INF folder in src/main/resources? i'm spitballing though

**Comment by quat1024** [comment]
:thinking:
![image](https://user-images.githubusercontent.com/2068021/42042467-3efae38e-7ac2-11e8-88cd-d3c0dc11bf0d.png)

**Comment by williewillus** [comment]
idk gradle someone just fix it pls :cry:

**Comment by Hubry** [comment]
Seems like there are two Botania jars deployed on Maven - one of them is the `universal` jar, which is the proper one that has the AT defined in the manifest, and the other one has no classifier and no FMLAT in manifest (and also has all the files it is supposed to exclude?). Sadly idk gradle either that well and I have no idea which step does this, I couldn't get it to create the `universal` jar
