### ISSUE TITLE
Tiny Potato and Banners

### ISSUE THREAD

**Issue by TehTemmie** [Vazkii/Botania#2537]
Forge version: 14.23.1.2608
Botania version: r1.10-353
Link to crash log: None, unrelated to bug

Steps to reproduce:
1. Obtain a banner of any color, a dye of any color, and a tiny potato
2. Craft them together in a crafting grid

What I expected to happen:
Get a banner with the tiny potato icon
What happened instead:
The tiny potato is not recognized as an item usable to craft a banner icon and therefore it is not possible to craft the banner

**Comment by yrsegal** [comment]
That's not a bug, that's a feature request.

**Comment by yrsegal** [comment]
(nevermind, misread the issue.)
