### ISSUE TITLE
[question] Default Orechid ignem weights ?

### ISSUE THREAD

**Issue by Thyriel** [Vazkii/Botania#2538]
Is there anywhere a file or so in the source where i can lookup the default weights (chances) for the orechid ignem ?
Modtweaker badly isn't having a command to output the current registered ores for the ignem so when i want to add some it's hard to find the right ratio without knowing the current weights

**Comment by yrsegal** [comment]
https://github.com/Vazkii/Botania/blob/master/src/main/java/vazkii/botania/api/BotaniaAPI.java#L192-L215

**Comment by Thyriel** [comment]
Thanks :)
