### ISSUE TITLE
Greater Mana ring with sash 

### ISSUE THREAD

**Issue by fyrenmotr** [Vazkii/Botania#2540]
Forge version: FTB 1.4.16; Forgelin- 1.6.0; Direwolf20 1.12(v1.7.1)
Botania version: rl.10.-352
Link to crash log: (https://gist.github.com/fyrenmotr/27428057c15edc9418c9be375bec48ef
Steps to reproduce:
1. These last two attempts were attempting to test new mods with existing pack. Those mods have been removed in my first 2 attempts of testing.

2. Created a brand new Creative world. Added the Globetrotter's sash, the Greater Mana Ring, and the Greater Mana Aura ring. 

3. Switched to Survival to get access to the Baubles menu. 

4. Attempted to equip the items to the Baubles menu. When putting on the sash or the Greater Mana ring on last, the client freezes and then crashes.

What I expected to happen:
The items should be able to co-exist in the baubles menu.

What happened instead:
The game became unresponsive and crashed.

**Comment by williewillus** [comment]
update to latest botania and it should be fixed

**Comment by fyrenmotr** [comment]
*Facepalm* I downloaded it and forgot to install it. My bad.
