### ISSUE TITLE
Bergamute errata

### ISSUE THREAD

**Issue by Chinthor** [Vazkii/Botania#2543]
Forge version:  12.18.3.2477
Botania version:  r1.9-341

No crash. Just a detail in the Lexica Botania.

As read, the book states that the Bergamute generates an almost-0 amount of mana.
In practice, it is set up to use an almost-0 amount of mana.

That's all. Book describes it as a generator instead of a user. Total mana involved either way is tiny, but I wanted to generate a few extra drops from tnt. Harvest the explosion and also the noise. Or just correct the book. Whetevs.

Laters

**Comment by williewillus** [comment]
That's just flavour text to describe the little particles it gives off when it muffles a sound.

in actuality the flower doesn't make or use any mana (even though it has an internal buffer, it doesn't do anything with it)

**Comment by williewillus** [comment]
^
