### ISSUE TITLE
Vinculotus not attracting teleporting endermen

### ISSUE THREAD

**Issue by mathwiz617** [Vazkii/Botania#2544]
Forge version: 14.23.1.2758
Botania version: r1.10-352
Link to crash log: No crash, but rather an in-game bug (I think).

Steps to reproduce:
1. Place and power a vinculotus with mana.
2. Spawn an enderman in water, within range of the flower

What I expected to happen: Enderman would teleport to the vinculotus.

What happened instead: The enderman stayed in the water, making teleporting noises every damage tick, and eventually died.

**Comment by mathwiz617** [comment]
![2018-02-04_18 58 30](https://user-images.githubusercontent.com/9375804/35784028-67a14b5a-09e0-11e8-9e4d-6140e2a3eeb2.png)

There's a vinculotus linked to a full mana pool 12 blocks away from the water pool.

More curious, endermen teleporting from outside of the water do end up at the vinculotus, but any in the pool just die.

**Comment by williewillus** [comment]
cannot reproduce, dropping endermen into a water pool with a vinculotus nearby pulls the endermen to the flower reliably

**Comment by williewillus** [comment]
there's some visual glitches where it seems like they can teleport away, but that's visual only and they should appear at the flower after a second
