### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by Explosivee** [Vazkii/Botania#2545]
FTB Revelation v1.4

I dont know if it happens in single player but in multiplayer if you wear a manasteel armor and if you let a Ancient Golem hits you (Embers) it crashes the server.

**Comment by codycoolwaffle** [comment]
Can you send a crash report or a log?

**Comment by Sixmorphugus** [comment]
Manasteel is just crashing generally for me.
[crash-2018-02-19_07.46.12-server.txt](https://github.com/Vazkii/Botania/files/1736968/crash-2018-02-19_07.46.12-server.txt)

**Comment by SquidDev** [comment]
@Sixmorphugus You'll need to update Botania: see #2560.

**Comment by Sixmorphugus** [comment]
ah. Thanks!

**Comment by codycoolwaffle** [comment]
Close please.
