### ISSUE TITLE
[Enhancement] Extend config

### ISSUE THREAD

**Issue by Warrock3280** [Vazkii/Botania#2546]
I think balance settings should be included in config. Now there is only graphic and generation settings, but gameplay configuration isn't less important.

**Comment by Vazkii** [comment]
Nope, sorry.

**Comment by Warrock3280** [comment]
@Vazkii Could you explain why? It's fully rational and anyone would just don't touch these options.

**Comment by williewillus** [comment]
Botania has always been opinionated in its design, and does not like config creep for its mechanics. It's simply a different style of design than other mods.
