### ISSUE TITLE
Botania Corrupt PlayerData on my Server

### ISSUE THREAD

**Issue by Meathelix** [Vazkii/Botania#2547]
Forge version: 1.12.2
Botania version: r1.10-352
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)

I am using FTB Revalations 1.12.2 FTB version 1.4.0

Here is the log in my server.

https://pastebin.com/6WTq6WLA

Steps to reproduce:
1. Used Wand of Crushed to replace ground and playercrash on server

What I expected to happen: Ground to change to dirt

What happened instead: Player Crashed and cant log back in due to error.

**Comment by williewillus** [comment]
Update botania
