### ISSUE TITLE
I have a question to ask.

### ISSUE THREAD

**Issue by joshuasuperboy** [Vazkii/Botania#2548]
Forge version:forge-1.12.2-14.23.1.2610
Botania version:  Botania r1.10-353.jar

I wanted to ask whats the name of this whole song that i have found in your mod
![2018-02-08_07 39 58](https://user-images.githubusercontent.com/32559193/35975972-7048301a-0c93-11e8-9a25-537cfa76333b.png)
I found that sound file in your mod i was wondering whats the whole name to it. The reason why im asking is because its sooo goood of a song. If you know the whole name please tell me because the sound file is very catchy and thanks.

**Comment by Vazkii** [comment]
NOMA - Brain Power

**Comment by joshuasuperboy** [comment]
k thanks i really like this song i guess its a easter egg is that what it is

**Comment by williewillus** [comment]
unused currently, it's whatever you want it to be :P
