### ISSUE TITLE
The game does not respond when I made Terrasteel ingot

### ISSUE THREAD

**Issue by freedmps** [Vazkii/Botania#2551]
Forge version: forge-1.12.2-14.23.1.2587
Botania version: Botania r1.10-353 (I install v347 for first time and continue update until this version)

The game does not respond (Time out on server) when I made Terrasteel ingot (after 
 I throw material on Terrestrial Agglomeration Plate).
I play on Own Server with Hamachi, The server don't have any issue and just report me lost connect because time out.
I must stop client and join again every time I made it. (the game just does not respond, don't crash, don't have crash log)

Ps. but I can made it normally in Botania r1.10-347 to 352 (but sure, them for forge 1.12.1 and It has many problem for 1.12.2)
![issue](https://user-images.githubusercontent.com/36303664/36034560-0f8642c6-0de7-11e8-8d13-75ceb12b7856.png)

**Comment by williewillus** [comment]
can you get some logs on either the client or server?

**Comment by TheSnowyChickens** [comment]
Ehmm, is your  bug something like that? xD (hard fps perma drops + that in the right corner)
Botania+r1.10-354 + Forge 1.12.2 - 14.23.4.2705
![2018-06-03_03 41 14](https://user-images.githubusercontent.com/29357962/40882370-03c4b6f0-66e0-11e8-9ff5-7b5cadc4dbed.png)

**Comment by belathus** [comment]
https://gist.github.com/belathus/2f5dcb9ef070381a0feb351ae1c48025

I don't know if it is related, but when I make terrasteel, I get the above crash report. VanillaFix catches the crash, but it continues to crash. I basically get trapped in a crash cycle as VanillaFix keeps catching the crash.

**Comment by williewillus** [comment]
this is will be fixed in the next release, sorry about that.

VanillaFix should have an option to disable crashing and to just log a warning.

**Comment by belathus** [comment]
I used it. Thanks, sir.
