### ISSUE TITLE
Cant transfer mana to a terrasteel plate via spark.

### ISSUE THREAD

**Issue by Amplefii** [Vazkii/Botania#2552]
unless im miss understanding the way sparks are supposed to work i cant understand why this wont transfer mana

Forge version: forge-14.23.2.2611
Botania version: Botania r1.10-353

This is the setup

![javaw_2018-02-10_14-19-24](https://user-images.githubusercontent.com/30732400/36067332-9f09cd0e-0e6f-11e8-8c3e-9df0acbcf7b7.png)

Steps to reproduce:
1. place a spark on a mana pool then place a spark on the terrasteel plate and drop 1 of each mana diamond, mana pearl, mana steel.

What I expected to happen:mana to transfer to the plate and craft terrasteel

What happened instead:nothing...

**Comment by CJOak** [comment]
Your lapis-livingrock pattern is incorrect.

**Comment by williewillus** [comment]
^
