### ISSUE TITLE
[1.12.2 - 252]Client crashes when loading chunk with TileAltar

### ISSUE THREAD

**Issue by i9hdkill** [Vazkii/Botania#2555]
Forge version: 2589 client
Botania version: 252 
Link to crash log: [gist](https://gist.github.com/anonymous/bae1666aef1737699c51a7e55edaedbf/)
Steps to reproduce:
1. Clients loads the chunk and crashes. Guess it while TileAltar.update()

I am aware that I am one version behind, but don't think that this crash is covered by 253. Can't really test tbh.

What I expected to happen:
Client does not crash
What happened instead:
Client crashes

If you need more info or the crash is fixed by 253 feel free to close the ticket or let me know

**Comment by codycoolwaffle** [comment]
We need to actually know what you were doing to cause this. Were you loading a sp world? Joining a server? Exploring terrain?

**Comment by i9hdkill** [comment]
Oh it's on a server. Every player-client that tried to load this chunk, got a crash. No error server-side.
Removed the altar on that said positon via a command and didn't happen again since that.
