### ISSUE TITLE
serverside disconnect by sneaking with The Spectator 

### ISSUE THREAD

**Issue by Eld0r** [Vazkii/Botania#2560]
# Version Information
Forge version:  ?
Botania version:  r1.10-352
Baubles version:  1.12-1.5.2
FTB Revelation version: 1.4.0

# Further Information
Link to serverside console log: [TheSpectator.log](https://github.com/Vazkii/Botania/files/1733691/TheSpectator.log)
Every time a client equip The Spectator and sneak the serverside client thread crashes.
(even far away from any civilization in the world)
But he can just join again and unequip the spectator.
pm me, if anyone want to test anything on my server.

Steps to reproduce:
1. use FTB Revelation 1.4.0
2. Equip The Spectator
3. Sneak

What I expected to happen:
no disconnect

What happened instead:
client disconnect by serverside client thread crash
 in method sendBaubleUpdatePacket

**Comment by williewillus** [comment]
Update botania
