### ISSUE TITLE
[REMOVE CRAFTTWEAKER] Entropinnyum Flower

### ISSUE THREAD

**Issue by Okii35** [Vazkii/Botania#2563]
Hello.
How i can remove the Entropinnyum Flower with CraftTweaker?

Because the 1.12.2 have a duplication tnt glitch.

And on my server a player use it so i disable TNT but disable Entropinnyum is better.

Or make an update that makes the plant has a cooldown between 2 explosion of TNT. Like that the plant can be destroy.

**Comment by codycoolwaffle** [comment]
I do not believe it can currently be disabled with CraftTweaker, as they removed integration with Botania.

This type of question doesn't belong here, but rather on our discord:
https://discordapp.com/invite/SFrYxxD


Please close <3

**Comment by codycoolwaffle** [comment]
Looking back, you shouldn't have asked how to block the flower, but report the duplication glitch. Can you provide an explanation?

**Comment by Okii35** [comment]
https://www.youtube.com/watch?v=EgMMUDbLxeQ

We can use that glitch to feed the flower. With a clock instead of lever. And it's free mana.

**Comment by williewillus** [comment]
Unfortunately the base game being broken shouldn't affect our balance decisions.  That bug is also fixed in 1.13
