### ISSUE TITLE
Spark Texture Issue

### ISSUE THREAD

**Issue by PessimisticBastard** [Vazkii/Botania#2564]
# Version Information
Forge version:  14.23.2.2618
Botania version: r1.10-353

This isn't a crash, but I remember sparks being much more detailed once placed than this:

https://imgur.com/F6cdkdn

I looked through the changelog and issues, and hadn't found anything about either a texture bug or a texture change, so I'm assuming it's a visual bug.

**Comment by Sandriell** [comment]
Was intentionally changed, "to be less detailed to better match default textures".

**Comment by williewillus** [comment]
^
