### ISSUE TITLE
Mana bursts that bounce back to their originating pool render as if they hit but actually become invisible and pass through

### ISSUE THREAD

**Issue by vebyast** [Vazkii/Botania#2565]
# Version Information
Forge version:  14.23.2.2611
Botania version:  r1.10-353

Other mods: [Modern Skyblock 3.1.1.1](https://minecraft.curseforge.com/projects/modern-skyblock-3-departed/files/2528725)

# Further Information

logs/fml-server-latest.log, though this isn't a crash: https://gist.githubusercontent.com/vebyast/913d8e766b46d77fa4f7a6c716a4bd3d/raw/5ccb085770596cf0ccd3bf77729728a522a50161/fml-server-latest.log

## Steps to reproduce:
1. Construct:
```M  P> H```
   Where P is a mana pool, > is a pulse mana spreader facing right, M is a mana detector, and H is a hovering hourglass.
2. Put some sand in the hourglass to make it a timer.
3. Place a lens on the mana spreader that includes the bounce property.
4. Activate the spreader to hit the hourglass with a mana pulse which will bounce off it to return to the pool.

## What I expected to happen:

~~The hourglass toggles `paused` state.~~

The mana pulse hits the pool and stops.

*or*

The mana pulse passes through the pool the same way it passed through the spreader, bouncing back and forth between the mana detector and the hourglass.

## What happened instead:

~~Strange behavior on `paused` state, precise nature depending on the lens used:~~
- ~~Bounce lens: toggles `paused` state as expected, but the change reverts after several seconds, leaving the hourglass in its original state.~~
- ~~Bounce-Messenger: Sometimes the hourglass does not react at all. The rest of the time the hourglass toggles between a normal paused or unpaused state and a buggy "toggling" state in which the hourglass pauses/unpauses at a constant frequency, somewhere between 1 and 2 hz, without further interaction. Hard to describe, so [recording of this behavior here](https://imgur.com/7Il2CLR).~~

The mana burst bounces off the hourglass and returns back, passing through the spreader. It appears to hit the pool, but actually only _renders_ that way; in reality the burst has become invisible and continues bouncing back and forth between the wall and the hourglass. This can be observed using the `paused` property of the hourglass and by the activation of the mana detector and by noting that no mana is deposited into the pool.

Using a bounce-messenger lens, with its faster travel and longer lifetime, should result in a pulse train from the mana detector and the hourglass repeatedly and rapidly toggling its `paused` state, but this this appears to be inconsistent. It may work differently if the mana detector is replaced with another solid block?

**Comment by vebyast** [comment]
It looks like mana is not being deposited in the pool when the burst hits it. So this is actually a rendering bug: bursts that bounce and return to the mana pool feeding the spreader that fired them render as if they hit the mana pool but actually continue onward.

**Comment by codycoolwaffle** [comment]
Can you provide screenshots instead of analogies?

**Comment by williewillus** [comment]
this is just a result of bursts running their logic on both client and server sides. Until we get around to refactoring things so that mana system only runs server side, visual bugs like this will result, unfortunately.

**Comment by williewillus** [comment]
I can't seem to reproduce the effect in the video

**Comment by codycoolwaffle** [comment]
I was referring to the "M P> H" analogy

I also can not reproduce
