### ISSUE TITLE
Don't place botania flowers with a builders wand

### ISSUE THREAD

**Issue by Ender0ragon** [Vazkii/Botania#2566]
# Version Information
Forge version:  7.10.99.99
Botania version:  r1.8-249

# Further Information
Steps to reproduce:
1. Place a botania flower
2. Try to place a second one with a builders wand

What I expected to happen: A second flower would be placed

What happened instead: An undefined botania flower was placed

**Comment by brainiac744** [comment]
#2227 - its a bug with builders wands

**Comment by williewillus** [comment]
^
