### ISSUE TITLE
Runic Altar will accept damaged items but then will not craft

### ISSUE THREAD

**Issue by mattstreet** [Vazkii/Botania#2568]
# Version Information
Forge version:  14.23.2.2616
Botania version:  Botania+r1.10-353

# Further Information

Steps to reproduce:
1. Add ingredients to Runic Altar to create a Rune of Water
2. Be sure fishing pole used is damaged (less than 100% durability)
3. Note that altar accepts the pole but will not craft

What I expected to happen:
Runic Altar would either refuse a damaged item or use it in recipe.

What happened instead:
Runic Altar accepted damaged item (fishing pole in this case) but would not craft
Rune of Water
Because damaged item was not the last to be inserted into the altar, item could
not be removed, altar had to be removed and replaced.

**Comment by williewillus** [comment]
I'm not sure what the issue is:

* the rune altar can accept anything you give it, even though it doesn't form a valid recipe
* the rune of water recipe requires an undamaged rod
* you can shift right click with an empty hand to remove the last inserted item

**Comment by mattstreet** [comment]
I could only get the very last item back, after getting back the living wood stone nothing else would return.

**Comment by codycoolwaffle** [comment]
Living wood stone?

**Comment by williewillus** [comment]
when you get the last item back, it might go into your hand, so your hand is no longer empty and subsequent clicks don't do anything. that might be why?

**Comment by confusingSmile** [comment]
The altar does not refuse items. This seems to be working as intended. I could not reproduce the issue of not being able to get the fishing rod back without destroying the altar. I did have to remove multiple items as the fishing pole was not the last item I put in.
