### ISSUE TITLE
Floral Bee causing "glitch flowers" from Botania to grow

### ISSUE THREAD

**Issue by 123zane321** [Vazkii/Botania#2570]
# Version Information
Forge version:  14.23.1.2604
Botania version:  r1.10-352

# Further Information
Link to crash log: N/A, no crash
Steps to reproduce:
1: Get a purebred Floral Queen from Forestry  
2: Place bee in Industrial Apiary in a large grassy area

What I expected to happen:
Mystical flowers should have grown in the nearby area

What happened instead:
Only the glitch flowers from Botania grew instead

**Comment by williewillus** [comment]
report this to forestry (or whichever mod adds floral bees)
