### ISSUE TITLE
Pure Daisy on DW20 1.12.2 MC 1.8.0 turns into Textureless block

### ISSUE THREAD

**Issue by CloudFFXI** [Vazkii/Botania#2571]
Placed a Pure Daisy on DireWolf 20 v1.12.2 on MineCraft v1.8.0 and it turns into a "botania flower" that reads "if you have this, it means something went wrong, you should report it."  
There are no crashes, not sure what forge version this is. The Botania version is: r1.10-352  
  
This is happening on a server host, not a personal minecraft server.   
  
# Further Information  
Steps to reproduce:  
1. Obtain Mystical White Flowers  
2. Craft Pure Daisy  
3. Place on the ground  
4. Watch it turn into a texture-less block  
  
What I expected to happen:  
For it to stay a pure daisy that makes living wood and living rock.  
What happened instead:  
Turns into a black/purple block that doesn't work like a pure daisy.

**Comment by codycoolwaffle** [comment]
A few things:
 -How long does it take?
 -Are you idling for it? (not moving, not interacting with game)
 -Does it happen on SP?
 -Can you try it on the latest Botania

**Comment by codycoolwaffle** [comment]
Also, you have the versions swapped for the modpack and MC. Drove me a little insane, lol

**Comment by CloudFFXI** [comment]
Almost instant.  
It'll happen if I move or not.  
Haven't tried in SP yet, will need to try. A previous staff mentioned to post it here instead of on their site as an issue.  
Not sure what the latest Botania is, it's a public server that this issue is on. Ex-Staff said to post it here. Will try to see if it duplicates on SP here in the next 30 minutes.  
  
  
Also saw "forge version" on the FTB launcher.  
Forge Version: 14.23.1.2601  
  
Will try SP and update here in just a few.

**Comment by CloudFFXI** [comment]
Alright, just tried SP and the Botania r1.10-352 (same as mentioned above) places a Pure Daisy down with no issues. This is a fresh SP world. Item given in creative, placed in survival. Also crafted the Pure Daisy with Mystical Petals in the Apothecary and planted that with no issues.  
  
  
Offnote: Draconic Evolution place items in world doesn't work either (after most recent minecraft update).  
DW20 [1.12.2] 1.7.1 is how it looks on website, hasn't been updated for 1.8.0 update (as of today, 2/28/2018)

**Comment by codycoolwaffle** [comment]
Do you know if the server is running a normal forge server or not?

**Comment by CloudFFXI** [comment]
How can you tell that information? It does launch from FTB on those settings?

**Comment by codycoolwaffle** [comment]
Basically what I'm asking is does it run using just Forge or something like Sponge. You might need to ask the server owners for that.

**Comment by CloudFFXI** [comment]
http://www.brierieserver.co.uk/  
FTB is dw20new.brierie.net

**Comment by CloudFFXI** [comment]
They have told me that sponge has had problems on their server and has caused issues. That they were waiting for sponge to fix some of the problems they have caused.

**Comment by CloudFFXI** [comment]
Also, Cody, I do appreciate your timely responses in trying to fix the issue. It's appreciated!

**Comment by codycoolwaffle** [comment]
I do not know if Sponge will ever be able to fix the great amount of bugs it presents, but we have run into problems that exist only with it. Don't even know where to begin with fixing problems with Sponge, we normally just put it onto them to fix it. Sorry man. Nothing else we can do, was afraid of this
¯\_(ツ)_/¯

**Comment by CloudFFXI** [comment]
Like I mentioned Cody, I do appreciate your help and insight. Hopefully sponge gets their s* together and fixes things.

**Comment by codycoolwaffle** [comment]
Yea, rather unfortunate. If you want to see more examples as to how sponge create problems with Botania specifically, you can look here: https://github.com/Vazkii/Botania/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+sponge
This specific issue, I just realized, already has a thread here: #2056 

Seeing as we have another thread on this, can this be closed, please <3
