### ISSUE TITLE
Entropinnyum turning into "glitch flower"

### ISSUE THREAD

**Issue by 123zane321** [Vazkii/Botania#2573]
# Version Information
Forge version: 14.23.1.2604
Botania version: r1.10-352
Modpack version: Revelation 1.4.0

# Further Information
Link to crash log: N/A
Steps to reproduce:
1. Place entropinnyum on grass
2. Detonate TNT beside entropinnyum
3. Detonate another TNT beside entropinnyum while it still has mana in it
4. Break entropinnyum

What I expected to happen:
Entropinnyum should drop

What happened instead:
"Glitch flower" drops instead

**Comment by williewillus** [comment]
are you on a sponge server with terrain protection plugins?

**Comment by 123zane321** [comment]
Uh, yes and yes I think - pretty sure the server I'm on uses GriefPrevention for terrain protection, and 99% sure they use Sponge

**Comment by williewillus** [comment]
I imagine this issue is likely caused by the grief prevention plugin, then

**Comment by williewillus** [comment]
Specifically, when it restores or cancels TNT damage it doesn't replace the block entity / tile entity data of the blocks it restores.

**Comment by williewillus** [comment]
^ this is an issue with your protection plugins
