### ISSUE TITLE
Poor performance with floatingSpecialFlowers

### ISSUE THREAD

**Issue by i9hdkill** [Vazkii/Botania#2574]
# Version Information
Forge version:  1.12.2 2611
Botania version:  r1.10-352

We are running Direwolf20 1.8.0 with sponge

So far so good. Unless you start using (floating)specialFlowers.

You will get massive lags with just one user online.

Thats the interesting part:
http://prntscr.com/im42y2

But please have a closer look:

https://timings.aikar.co/dev/?id=c2d16e45204e4573823048e0e65f275f

Java flags: `java -Xms6g -Xmx9g -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:MaxGCPauseMillis=50 -XX:+DisableExplicitGC -XX:G1HeapRegionSize=4M -XX:TargetSurvivorRatio=90 -XX:G1NewSizePercent=50 -XX:G1MaxNewSizePercent=80 -XX:InitiatingHeapOccupancyPercent=10 -XX:G1MixedGCLiveThresholdPercent=50 -XX:+AggressiveOpts`
Server is running on a ssd.
If you need more info, please let me know and what.

Edit: We tried without sponge and getting almost the same results

**Comment by williewillus** [comment]
Does it happen with the regular (nonfloating) version of the flower?
