### ISSUE TITLE
Weird rendering issues on the latest forge build

### ISSUE THREAD

**Issue by Sunconure11** [Vazkii/Botania#2575]
# Version Information
Forge version:  14.23.2.2624
Botania version:  1.10.353

# Further Information
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)\
Steps to reproduce:
1. Install latest build of forge
2. Install botania
3. etc...

Note: TexFix is installed.

What I expected to happen:

No textural issues

What happened instead:

![screenshot 2018-03-04 19 00 34](https://user-images.githubusercontent.com/5614902/36952460-59c127a8-1fde-11e8-9002-dc3381a6f72a.png)

**Comment by williewillus** [comment]
does it happen without texfix?
are there errors in the log on startup?

**Comment by Sunconure11** [comment]
I shall check.

**Comment by Sunconure11** [comment]
Clean instance, both with and without texfix, seems to be unable to replicate this. I think I saw a weird issue on another mod's repo that might be related, though.

**Comment by Sunconure11** [comment]
Could be Erebus.

https://github.com/ganymedes01/TheErebus/issues/576

**Comment by Sunconure11** [comment]
Weird, the issue is only happening in multiplayer.
