### ISSUE TITLE
Flügel Tiara with wings won't show the wings

### ISSUE THREAD

**Issue by ShionWayne** [Vazkii/Botania#2576]
![2018-03-05_17 13 38](https://user-images.githubusercontent.com/37065575/36967010-87a41098-2099-11e8-9bf8-c3ace154eca2.png)
I play with Botania r1.10-353 (for Minrcraft 1.12) and put on the Flügel Tiara with wings, but there are no wings shown.
Other mods in my modpack:
Appleskin, AE2, BiblioCraft, ClockHUD, Draconic Evolution, ExU2, Forestry, Hwyla and addon of Waila, Immersive Engineering, IC2, JEI and its addons, Metamorph, Thermal Expansion, Twilight Forest, Wearable Backpacks.
And the tiny wings above hunger bar looks strange except the no-wing Tiara.
Other functions of the Tiaras work out fine.

**Comment by ShionWayne** [comment]
forge version: 1.12.2-14.23.1.2607

**Comment by CTH999** [comment]
Ok... Interesting. You do realize you can edit comments, the top comments, right?

What armor is that?

Also, any potion effects?

Did you test it in creative? Just Wondering.

That way, the devs get the answer's they need, without asking!

**Comment by ShionWayne** [comment]
Thanks for reminding.
That armor is Terrasteel gear in Botania.
And yes, I tested in Creative Mode with and without gears/baubles. Also there were no potion effects on me.

**Comment by ShionWayne** [comment]
I have just discovered that if there are only Botania and Baubles in the modpack there will be no such problems. But I still wonder which of those mods has a conflict with Tiara.

**Comment by ShionWayne** [comment]
It's metamorph.
