### ISSUE TITLE
[World Breaking Bug] changing one config line reloads entire 

### ISSUE THREAD

**Issue by Akitori** [Vazkii/Botania#2578]
# Version Information
Forge version:  1.12.2 2555
Botania version:  r.1.10353

# Further Information
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)\
Steps to reproduce:
1.Change one config line (in this case, turning particles off)
2. load world
3. everything is broken

What I expected to happen:
nothing, just fixing config so clients don't die horribly
What happened instead:
This entire monstrosity. 

https://cdn.discordapp.com/attachments/383141601200832515/421448550166298625/unknown.png

https://cdn.discordapp.com/attachments/383141601200832515/421451071261638666/unknown.png

**Comment by williewillus** [comment]
can you reproduce this reliably multiple times? Just saying this happens once doesn't really help narrow anything down.

Can you make it happen multiple times with Botania, Baubles, and Forge alone, stating the specific config you changed?

Things like this are usually the result of other mods screwing around (as Botania itself does no registry hackery), so it's easy to blame a specific event when something else was the true cause.

**Comment by Akitori** [comment]
As for repeating, no. I think its more coincidence more than correlation in this case....Weird.

Weird mindset really, but when you change a simple config option and then the world decides to turn all your blocks to the wrong type, you kinda wonder if it was the config fille's fault...

Anyhow, closing for now.
