### ISSUE TITLE
Incompatible with Dynamic Trees Tree Felling

### ISSUE THREAD

**Issue by whitestarx0312** [Vazkii/Botania#2579]
# Version Information
Forge version:  forge-14.23.2.2624
Botania version:  r1.10-353

# Further Information
Link to crash log: N/A
Steps to reproduce:
1. Plant a dynamic trees tree
2. Have a bore mana blast hit the bottom log and break it
3. the bottom log breaks, but not the entire tree

What I expected to happen:
Dynamic Trees has a felling ability so that when the bottom log of a tree is broken, the entire tree comes down and drops wood, saplings, sticks. etc. I was thinking that given this feature, Botania could still be used for tree farms even though dynamic trees complicates the structure of trees.
What happened instead:
The bore lens only breaks the bottom piece of wood, and does not fell the tree.

**Comment by williewillus** [comment]
this is because dynamic trees only fells the tree if a player breaks the block, and the bore lens does not count as a player. you can see this in effect by trying to explode a tree with tnt, for example.

This will probably need to be changed by dynamic trees
