### ISSUE TITLE
Leggings are rendered twice while sneaking

### ISSUE THREAD

**Issue by OfficialCFM** [Vazkii/Botania#2581]
# Version Information
Minecraft version: 1.12.2
Forge version: 14.23.2.2611 
Botania version: r1.10-353

# Further Information
Steps to reproduce:
1. Equip any of the following leggings: Terrasteel Leggings, Manasteel Leggings, or Elementium Leggings.
2. Press the Sneak key and look behind the player in third person.

What I expected to happen:
The leggings would correctly render on the player while they sneak.
What happened instead:
A clone of the leggings appear behind the player whenever they sneak.

# Screenshots
![Screenshot 1](https://i.imgur.com/MymZLFY.png)
![Screenshot 2](https://i.imgur.com/b8I56BY.png)
![Screenshot 3](https://i.imgur.com/tSgQAtN.png)

**Comment by T4ge** [comment]
Still an issue as of Botania r1.10-354.
Using forge-14.23.4.2712.
Installed mods: Baubles & Botania.
Happens with all 3 Leggings as above, can confirm Manaweave Robe Bottom does not have this issue.
Steps to reproduce is the same as post above.

![image](https://user-images.githubusercontent.com/8440488/42114267-ae14e63e-7bee-11e8-9a68-8762563554aa.png)

**Comment by yrsegal** [comment]
https://github.com/Vazkii/Psi/commit/14a513b2313531a4a759c83bf80454246512fdda

I had the same issue. Willie, this is how to fix it: have a separate belt and pants anchor.

Also, remove the boxes from the anchors, if you can.

**Comment by bunnyman14** [comment]
I can confirm that this is STILL happening in version 1.15.2
Botania version 1.15-383
Modpack is Valhelsia 2, if that matters.
![2020-05-14_00 39 27](https://user-images.githubusercontent.com/7276888/81893670-07f1ec80-957c-11ea-9181-e06496d6557b.png)

**Comment by williewillus** [comment]
bump
