### ISSUE TITLE
Mana Spreader problem

### ISSUE THREAD

**Issue by SolitudeWR** [Vazkii/Botania#2583]
![2018-03-19_13 51 39](https://user-images.githubusercontent.com/37557238/37621858-3376477a-2b8e-11e8-97e6-9a05bea25d3d.png)
![2018-03-19_14 38 02](https://user-images.githubusercontent.com/37557238/37621863-36100980-2b8e-11e8-88e6-f9a18e5beee2.png)
![2018-03-19_15 00 12](https://user-images.githubusercontent.com/37557238/37621870-38af2414-2b8e-11e8-8bdf-1e78614ec3a6.png)

# Version Information
Forge version:  10.13.4.1614
Botania version:  r1.8-249

# Further Information

Steps to reproduce:
1. First step - first and second pic is my botania set up (minus the distributor and the mana pool closest to the altar), made a bunch a runes and botania stuff, haven't used it in a couple weeks. Left speader linked to mana pool. Tried to craft a fire rune, linked spreader to altar, no progress. Spreader fills up with mana though.
2. Second step - Spreader is no longer filling up mana pools. broke, moved, crafted all new mana pools and spreaders, took lens off.
3. Added and removed a distributor, removed the redstone automation from the endoflames. did a basic set up with a diluted mana pool to see if i just couldn't tell. 

What I expected to happen: to link my spreader to the altar and craft a rune. like a had been doing previously.

What happened instead: mana spreader fills up with mana, but doesn't seem to transfer it to mana pools or altars.

**Comment by williewillus** [comment]
are you absolutely sure your altar has a correct recipe in it?

**Comment by SolitudeWR** [comment]
I can provide a photo of it, I just won't be home for 4 hours. but I have put all fresh items down. the flowers fill, I link them to the spreader, the spreader fills, I link to pool, the spreader goes to about 10% full and nothing is in the diluted mana pool that I'm using to test. I dropped a fresh tablet in it thinking ok it just stopped rendering and got nothing. my mana star next to the pool doesn't indicate it receiving mana. I hooked a second spreader up to point directly at the altar from the mana pool and my fire rune just sits with no progress.

**Comment by SolitudeWR** [comment]
I apologize for all the photos, but I  wanted you to see step by step what I'm doing and what is happening.
 Is the recipe right?
![2018-03-20_19 12 51](https://user-images.githubusercontent.com/37557238/37689713-bc208aea-2c74-11e8-82cf-f066ad7839b4.png)
New mana tablet never used.
![2018-03-20_19 19 30](https://user-images.githubusercontent.com/37557238/37689718-bfb86182-2c74-11e8-986f-b43655f26c95.png)
all test done with charcoal block
![2018-03-20_19 19 36](https://user-images.githubusercontent.com/37557238/37689719-c3115118-2c74-11e8-9362-0da2b8d13f6c.png)
![2018-03-20_19 23 04](https://user-images.githubusercontent.com/37557238/37689730-cc991ec8-2c74-11e8-9a76-ed99809e77b9.png)
![2018-03-20_19 23 30](https://user-images.githubusercontent.com/37557238/37689732-d0894cf6-2c74-11e8-8768-108366f23177.png)
![2018-03-20_19 24 05](https://user-images.githubusercontent.com/37557238/37689740-d42c2892-2c74-11e8-9e28-96a017f7dbeb.png)
![2018-03-20_19 24 43](https://user-images.githubusercontent.com/37557238/37689745-da17e84a-2c74-11e8-8f9c-0bd0135a7bae.png)
![2018-03-20_19 24 47](https://user-images.githubusercontent.com/37557238/37689747-e16848c4-2c74-11e8-8b4d-ebc73af045ba.png)
![2018-03-20_19 25 34](https://user-images.githubusercontent.com/37557238/37689749-e846c242-2c74-11e8-9efc-d6340811cb07.png)
![2018-03-20_19 25 46](https://user-images.githubusercontent.com/37557238/37689753-ef64eacc-2c74-11e8-875b-12126ad6b731.png)

**Comment by SolitudeWR** [comment]
ok so you can close this, i figured it out, on a whim i decided to remove the tiny planet that i had placed nearby, and that fixed everything. And i do officially feel stupid, it was like the last thing i had crafted during my last session with botania, so I'm guessing all the coal i had been feeding my endoflames was for naught these last two weeks. I'm not sure the range on it, but I'll just remove it from this area completely.

**Comment by williewillus** [comment]
glad to see you figured it out :P
