### ISSUE TITLE
game crashes when it loads a chunk containing a Mana pool

### ISSUE THREAD

**Issue by mateoIPI** [Vazkii/Botania#2584]
# Version Information
Forge version: 14.23.2.2627
Botania version: r1.10-353

# Further Information
Link to crash log: https://gist.github.com/mateoIPI/6bd172da7ad9c06d273cc316c20106cf#file-crash-2018-03-21_13-32-08-client-txt
Steps to reproduce:
1. place mana pool
2. unload it's chunk
3. load it again

What I expected to happen: normal chunk loading and no crash

What happened instead: game crashes

**Comment by williewillus** [comment]
see #2205
