### ISSUE TITLE
Beam particles rendered on top of everything (no depth buffer?)

### ISSUE THREAD

**Issue by panoskj** [Vazkii/Botania#2588]
# Version Information
Forge version:  1.12.2-14.23.2.2613
Botania version:  r1.10-353

# Further Information
Beam particles are rendered on top of everything else. Here is a screenshot: https://i.imgur.com/ogA60k4.jpg

I'm playing on a custom FTB modpack (~50 mods) with Optifine, but the issue persists even when Optifine is disabled.

**Comment by panoskj** [comment]
yeah, is that a normal feature?

**Comment by williewillus** [comment]
Yes, one of the monocles features is that you can see all bursts in the world no matter if they're blocked or not

**Comment by williewillus** [comment]
^
