### ISSUE TITLE
Band crash

### ISSUE THREAD

**Issue by MardiGraskid** [Vazkii/Botania#2591]
<script src="https://gist.github.com/MardiGraskid/ec2f4e53ed928267ced91032a688d62f.js"></script>
Steps to reproduce:
1. Make and equip Band of Aura
2. Make Band of Mana
3. Equip Band of Mana

What I expected to happen:
Nothing. Both would work together.

What happened instead:
I crashed client side, and had to wait for a server admin to pull up a back up, and reset my character inventory, since I couldn't log back in. I have since made a new Band of Mana, and it works just fine being equipped.

**Comment by williewillus** [comment]
uh I can't read your log, it's just a giant minified javascript file?

**Comment by MardiGraskid** [comment]
Sorry. I don't know how to do the logs.

**Comment by Dalethium** [comment]
https://gist.githubusercontent.com/MardiGraskid/ec2f4e53ed928267ced91032a688d62f/raw/83c91fe094444ede5854640633ee36b504a53b34/2018-04-04-1.log 
here's the log

**Comment by williewillus** [comment]
there's not really much that client log says. maybe it's a serverside issue?

**Comment by MardiGraskid** [comment]
Unfortunately, I'm at work at the moment, but the issue was, I made the
Band of Aura, and had it in my baubles slot, then made and put in the Mana
one, and it crashed me, forcing the admin to reset my inventory to the
latest backup, which thankfully, wasn't too long before.
