### ISSUE TITLE
1.10.2 Floating Pure Daisy Vanilla Log Crash

### ISSUE THREAD

**Issue by quantumSuperposition** [Vazkii/Botania#2592]
# **Version information**
Forge version: Forge-12.18.3.2511
Botania version: Botania r1.9-341

# **Further Information**
Link to crash log: https://gist.github.com/quantumSuperposition/5aacd7222336da7842b95e2bb51331d5
Steps to reproduce:
1. Place floating Pure Daisy.
2. Place vanilla logs (not sure if this matters) around pure daisy.
3. Crash and unable to recover world except by using MCEdit to delete the Floating Pure Daisy.

What I expected to happen: To create livingwood and livingrock.

What happened instead: The Minecraft window turned to a sky blue and then stopped responding and crashed. I was unable to go back into the world; every time the world would crash. All other floating flowers work. The floating Pure Daisy will crash when a log is placed next to it and is reproducible. Very similar if not same crash as issue #2343.

**Comment by williewillus** [comment]
another mod is interfering with the floating flower's rendering. in this case, it appears to be codechickencore. I don't think it's a botania issue

**Comment by quantumSuperposition** [comment]
Is there a way to fix this issue without removing the codechickencore itself?
