### ISSUE TITLE
items voiding when dropped with magnet on

### ISSUE THREAD

**Issue by SilverAlphaWolf** [Vazkii/Botania#2593]
# Version Information
Forge version:  14.23.2.2652
Botania version:  10-352

Steps to reproduce:
1. First step: have the ring of magnitization equipped in a bauble slot
2. Second step: drop any item from your inventory, either by pressing Q or clicking and dropping from inventory.

What I expected to happen: the item to drop as an entity as normal

What happened instead: vanishing as if voided.

im using a minor modpack on the twitch app that has a main focus of tinkers construct, i added botania baubles and a mod to allow the crafting of charcoal blocks, by the time i started botania i had the mods installed for a little bit so i honestly couldn't tell you what is conflicting at the current moment but when i crafted and put on the ring of magnitization every time i try to drop an item it just vanishes, like it was voided somehow. even logging in and out didn't recover the item so i dont think its a sync issue. any help would be thanked whole heartedly.

**Comment by williewillus** [comment]
update botania
