### ISSUE TITLE
Crashes game client side, not Server Side

### ISSUE THREAD

**Issue by Brekendor** [Vazkii/Botania#2595]
# Version Information
Forge version:  1.12 - 14.21.1.2387
Botania version:  Botania+r1.10-353

# Further Information
Link to crash log: https://gist.github.com/Brekendor/4810f1f5c858d0b9884be5671e049578
Steps to reproduce: 
1. Created a mana pool
2. Filled it up with mana
3. try to do anything near it
What I expected to happen: The mana pool to work

What happened instead: Crashes anybody nearby

**Comment by williewillus** [comment]
rolling into #2205
