### ISSUE TITLE
1.12.2 Health Glitch

### ISSUE THREAD

**Issue by ShadowTheEnder** [Vazkii/Botania#2596]
You know when you fight the gaia guardian your health has a glitch effect... well after i uninstalled the mod i still got that glitch effect when i was fighting bosses( mod bosses, ender dragon, wither) and its very annoying
if you need some pictures i have 5

**Comment by williewillus** [comment]
> your health has a glitch effect

it shouldn't, all it does to your health is give you the vanilla Wither potion effect
could you post the pics?

**Comment by ShadowTheEnder** [comment]
sure
![2018-04-08_19 54 12](https://user-images.githubusercontent.com/38188056/38538152-2066d398-3c9b-11e8-9675-702f41b6d13d.png)
![2018-04-08_19 54 13](https://user-images.githubusercontent.com/38188056/38538153-20876266-3c9b-11e8-9b50-d50db3b9d734.png)
![2018-04-08_19 54 14](https://user-images.githubusercontent.com/38188056/38538155-20a32f8c-3c9b-11e8-874d-333fe6272fda.png)
![2018-04-08_19 54 15](https://user-images.githubusercontent.com/38188056/38538156-20bfab30-3c9b-11e8-8690-cbc24c84f132.png)
![2018-04-08_19 54 16](https://user-images.githubusercontent.com/38188056/38538157-20de71e6-3c9b-11e8-99d3-8ca779f374ab.png)
![2018-04-08_19 54 16_2](https://user-images.githubusercontent.com/38188056/38538159-20fb3b28-3c9b-11e8-8754-1c8973193390.png)
![2018-04-08_19 54 16_3](https://user-images.githubusercontent.com/38188056/38538160-2117946c-3c9b-11e8-8bb5-5a4c21d31291.png)
 these shoud be the ones

**Comment by codycoolwaffle** [comment]
List of mods you're using, please.

**Comment by ShadowTheEnder** [comment]
Slashblade twighlight forest baubles baubley heart canister tinkers construct xaeros minimap and world map Rpg HUD optifine  step up 
 those are all the mods that i was using while i took the pictures

**Comment by codycoolwaffle** [comment]
Unable to recreate :/

**Comment by ShadowTheEnder** [comment]
:(

**Comment by codycoolwaffle** [comment]
Can you provide a screenshot of your baubles menu?

**Comment by ShadowTheEnder** [comment]
Yeah
![2018-04-16_12 38 45](https://user-images.githubusercontent.com/38188056/38801706-415a6b96-4173-11e8-82f5-015d5d257ede.png)

**Comment by EvilDylan** [comment]
Use f3+R to reload resource packs. Does this change anything?

Do you, by chance, have Fast Render enabled in optifine?

**Comment by ShadowTheEnder** [comment]
Yeah i have Fast Reder on

**Comment by ShadowTheEnder** [comment]
Yeah I have it on

**Comment by EvilDylan** [comment]
It's a conflict with Optifine's Fast Render. A similar issue occurs with Astral Sorcery's journal with Fast Render enabled.

I recommend turning it off if possible.

**Comment by ShadowTheEnder** [comment]
I tried and i didn't work

**Comment by ShadowTheEnder** [comment]
I tried and i didn't work
