### ISSUE TITLE
API needs some reworking...

### ISSUE THREAD

**Issue by KingLemming** [Vazkii/Botania#2597]
So I'm trying to add Solegnolia support for my magnets, and I started by importing the API.

Unfortunately, files within API require some stuff in botania.common, and that doesn't really jive.

I'm also unable to just use a partial API (while including package-info.java, of course) because BotaniaAPI.java effectively requires that EVERYTHING be there. :(

**Comment by williewillus** [comment]
fixed and it'll be in the next version, sorry about that!

**Comment by KingLemming** [comment]
thanks <3
