### ISSUE TITLE
[1.7.10] Crash with Pages in "Thaumcraft Integration" - Lexica Botania

### ISSUE THREAD

**Issue by chaos234** [Vazkii/Botania#2598]
# Version Information
Forge version:  1614 (latest) for MC 1.7.10
Botania version:  1.8-249 (latest) for MC 1.7.10

# Further Information
Crash report: https://paste.ee/p/CErKZ

What I expected to happen:

To see the brew recipe on Page 7/7

What happened instead:

Stated in the linked crash report; a Rendering Screen error occured. Sadly I have reported this into the false repro here on git and a few secounds later the issue section was directly closed so I can not reference to it anymore (404 page).

However and even if there will be no new feature for Botania 1.7.10 but it would be good to get rid of this bug and to see the recipe and which item it is.

Additionally this happends with and without optifine, means OF is not the culprit.

**Comment by williewillus** [comment]
1.7 is no longer supported (and the paste is gone)
