### ISSUE TITLE
Nullpointer exception

### ISSUE THREAD

**Issue by Sunconure11** [Vazkii/Botania#2601]
# Version Information
Forge version:  14.23.3.2657
Botania version:  r1.10-353

# Further Information
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)\

https://pastebin.com/bPiQUaCV

Steps to reproduce:
1. Load up a game
2. ???
3. https://pastebin.com/bPiQUaCV

What I expected to happen:

No crash

What happened instead:

https://pastebin.com/bPiQUaCV

**Comment by williewillus** [comment]
downgrade to forge 2655 or below, or upgrade to forge 2658 or above. 56 and 57 are bugged.
