### ISSUE TITLE
1.12 Duplicate Relics

### ISSUE THREAD

**Issue by barbieqfreak** [Vazkii/Botania#2602]
Forge version:  1.12.2-14.23.2.2654
Botania version: r1.10-353 

Hello~

I've killed the Gaia Guardian 6 times now. I have 2 Rings of Thor, 2 Rings of Loki, 1 Fruit of Grisaia, and 1 Key of the King's Law.

I rolled the Die of Fate as soon as it dropped every time. 
The Gaia Guardian always dropped a Die. 

Please let me know if there's any other information I can provide.

**Comment by williewillus** [comment]
the dice tracks your advancements to determine if you've received a relic, is there something messing with advancements?

**Comment by williewillus** [comment]
yeah I can't replicate this

**Comment by Soundmastermatt** [comment]
I can confirm MC 1.12 Direwolf20 1.7.1 - 1.11

3 Eyes of Frugel
2 Rings of Loki
1 Fruit of Grisaia
2 Rings of Odin (Which does stack [20+ extra hearts])

Have not gotten a failed Die. Other people on the server experience the same. I can send world if needed.

**Comment by Soundmastermatt** [comment]
I found the some of the problem.

I did not have the achievement "World Calling".
After getting said achievement, it then allowed the die to fail.

That said I went into single player and could not replicate. 
With only "Open Book", "Drop Pop Candy", and "Dead and Seek".

**Comment by yepidoodles** [comment]
Does anyone know the Advancement IDs in order to add them manually to fix this?

**Comment by williewillus** [comment]
under the `challenge` folder here https://github.com/Vazkii/Botania/tree/master/src/main/resources/assets/botania/advancements
