### ISSUE TITLE
[Bug] Botania game crash with CraftTweaker 

### ISSUE THREAD

**Issue by trilexcom** [Vazkii/Botania#2605]
# Version Information
Forge version:  2657
Botania version: Botania r1.10-353 

# Further Information
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)

https://gist.github.com/trilexcom/1c557d9ecdb5af37034fd85b4ac67f6d

Steps to reproduce:
1. After Updating CraftTweaker to latest version game Crashes it says in the bug report its botania 
may be you can tell me its botania or crafttweaker i will let them know if its them.

What I expected to happen:

i was excepting the game to run ok but the game crashes and i dont know why ? may be its something CraftTweaker changed in their API ?

What happened instead:

game crash

**Comment by trilexcom** [comment]
i think i figured out, it was my script but i am waiting for the game to load once it loads i am going to close this ticket issue sorry.

**Comment by TheEventHorizon** [comment]
> i think i figured out, it was my script but i am waiting for the game to load once it loads i am going to close this ticket issue sorry.

Did you figure out what script was causing the crash? I'm having the exact same issue.
