### ISSUE TITLE
Forge Build 1.12.2-14.23.2.2642 or higher

### ISSUE THREAD

**Issue by Xiaminou** [Vazkii/Botania#2607]
Version Information

Forge version: 1.12.2-14.23.2.2642 or higher
Botania version: Botania r1.10-353
Further Information

Link to crash log: [crash-2018-04-03_20.05.49-client.txt](https://github.com/Vazkii/Botania/files/1915052/crash-2018-04-03_20.05.49-client.txt)

Steps to reproduce:

    Start Game
    crash...

What I expected to happen:
Launch Minecraft
What happened instead:
Crash

**Comment by Xiaminou** [comment]
nope: [crash-2018-04-17_13.33.46-client.txt](https://github.com/Vazkii/Botania/files/1919478/crash-2018-04-17_13.33.46-client.txt)

**Comment by williewillus** [comment]
does it happen with botania alone? I can't really see why this should be happening (Botania does not use touch the SoundManager at all), so it may be a cross-mod thing

**Comment by codycoolwaffle** [comment]
I believe it is blood magic crashing

**Comment by Xiaminou** [comment]
I tried with Blood Magic + Botania, works fine.

**Comment by Xiaminou** [comment]
any more ideas?

**Comment by Xiaminou** [comment]
Found it, it's Up and Down And All Around

[crash-2018-04-21_13.57.42-client.txt](https://github.com/Vazkii/Botania/files/1934459/crash-2018-04-21_13.57.42-client.txt)

**Comment by Xiaminou** [comment]
https://github.com/Mysteryem/Up_And_Down_And_All_Around/issues/91
