### ISSUE TITLE
Crash when TC6 is loaded

### ISSUE THREAD

**Issue by tyra314** [Vazkii/Botania#2608]
A Minecraft instance with only Botania and Thaumcraft beta9 is crashing with a class not found error. Without TC6, botania loads just fine.

# Version Information
Forge version: 14.23.3.2655
Botania version: r1.10-353
Thaumcraft: 6.1.BETA9

# Further Information
Link to crash log: https://gist.github.com/tyra314/6033a50d3be1fe17e5d3e198f695ed0e
Steps to reproduce:
- Happens during startup.

See also: Azanor/thaumcraft-beta/issues/468

**Comment by CurePindal** [comment]
Also happens with TC6 Beta10. According to Azanor its probably an outdated TC integration. 
Can we haz a hotfix? Was so looking forward for Botania and TC on 1.12.2 =(

**Comment by CurePindal** [comment]
Oh, just noticed this commit as hotfix?
https://github.com/Vazkii/Botania/commit/ed72ff3d5fcf92b1760a164c30797d6ba68da374
When does this get live?

**Comment by Dalethium** [comment]
I just built and tested that commit, this error comes up: 
https://pastebin.com/aaCPMbvc

**Comment by Dalethium** [comment]
Thanks for the speedy fix! I'll test it later today!
