### ISSUE TITLE
Daffomill ignores powered open crate restrictions, but only on the client-side

### ISSUE THREAD

**Issue by quat1024** [Vazkii/Botania#2620]
# Version Information
Forge version:  14.23.3.2655
Botania version:  r1.10-354

Steps to reproduce:
1. Build something like this:
![image](https://user-images.githubusercontent.com/2068021/39496171-514f11c4-4d6b-11e8-93d8-31e742969e12.png)
The important part is the daffomill has to push an item coming out of a powered open crate.
2. Place an item in the hopper
3. The daffomill tries to push the item client-side, even though the item does not move serverside (evidenced by the pressure plate staying pressed)

![2018-05-01_18-15-05](https://user-images.githubusercontent.com/2068021/39496259-a71eef48-4d6b-11e8-9f26-31b62f12ccf4.gif)

What I expected to happen: The item remains on the pressure plate, both client and server side.

**Comment by williewillus** [comment]
this is because the entityitem's age is not synced to client on spawn.

not sure if I want to solve this by sending the age (which is fragile since you have to remember to do it everywhere the age is touched), or just moving it server-side only (which makes it look choppier)
