### ISSUE TITLE
Corporea retainer

### ISSUE THREAD

**Issue by larskr96** [Vazkii/Botania#2624]
it does not work With the inteceptor when the retainer is at the top
Is this a bug or is it inteded?

This system is just a test i put up to test it in a world
i request 1 grass Block With a dirt Block in the chest then i Place a grass Block in the chest
and i dont get the gass block
![2018-05-04_17 03 01](https://user-images.githubusercontent.com/10383027/39635190-08913b02-4fbd-11e8-82ce-a683e95dfea1.png)

Botanaia versjon r1.10-354
forge versjon 14.23.3.2678

**Comment by williewillus** [comment]
This is intended, the interceptor will only look for a retainer horizontally adjacent to itself
