### ISSUE TITLE
Thaumcraft 6 + Botania crash, but only when with other mods

### ISSUE THREAD

**Issue by Vampyricon** [Vazkii/Botania#2625]
# Version Information
Forge version:  1.12.2-forge1.12.2-14.23.3.2655
Botania version:  Botania r1.10-354

# Further Information
Link to crash log: https://gist.github.com/Vampyricon/ddf0ce4cd4f5182529a176af4148d330
Steps to reproduce:
1. Install Forge and open a new profile with it
2. Add the following mods: 
2a. zerocore-1.12-0.1.2.1
2b. ThermalFoundation-1.12.2-2.4.1.15-universal
2c. Thaumcraft-1.12.2-6.1.BETA13
2d. tesla-core-lib-1.12.2-1.0.14
2e. Tesla-1.12.2-1.0.63
2f. TConstruct-1.12.2-2.9.1.65
2g. RedstoneFlux-1.12-2.0.1.2-universal
2h. Psi-r1.1-59
2i. MmmMmmMmmMmm-1.12-1.14
2j. Mantle-1.12-1.3.2.24
2k. jei_1.12.2-4.9.1.175
2l. ironchest-1.12.2-7.0.40.824
2m. industrialforegoing-1.12.2-1.9.0-163
2n. Hwyla-1.8.24-B39_1.12
2o. Guide-API-1.12-2.1.5-60
2p. Forgelin-1.6.0
2q. ExtremeReactors-1.12.2-0.4.5.48
2r. extrautils2-1.12-1.7.6
2s. EnderStorage-1.12.2-2.4.2.126-universal
2t. EnderIO-1.12.2-5.0.24
2u. EnderCore-1.12.2-0.5.22
2v. CoFHWorld-1.12.2-1.1.1.12-universal
2w. CoFHCore-1.12.2-4.4.1.12-universal
2x. CodeChickenLib-1.12.2-3.1.8.341-universal
2y. Baubles-1.12-1.5.2
2z. AutoRegLib-1.3-17
3. Add Botania
4. Open Minecraft on the Forge profile

What I expected to happen:
Minecraft opens normally, with mods

What happened instead:
Crashed at step 1/7 or 2/7 (forgot which) in the Minecraft loading screen

NOTE:
Situations where Minecraft opens normally:
+1. Thaumcraft 6 + Botania (+ Baubles)
+2. All the mods listed in step 2 above + Applied Energistics 2 + Blood Magic
+3. All the mods listed in step 2 WITHOUT Thaumcraft, but with Applied Energistics 2 + Blood Magic + Botania
Situations where Minecraft crashes:
-1: All the mods listed in step 2 + Botania
-2: All the mods listed in step 2 + Applied Energistics 2 + Blood Magic + Botania
Only the 5 situations listed above have been tested. All other situations have not been tested.

**Comment by Vampyricon** [comment]
Tried it again with the addition of ExtraCells and JouneyMap and it worked. I doubt it is because of those two mods though.

**Comment by SquidDev** [comment]
Have you tried updating to the latest botania? I believe Thaumcraft integration has been fixed in later versions.
