### ISSUE TITLE
Botanurgist's Inkwell doesn't work with celestial note scanning

### ISSUE THREAD

**Issue by FenrisWolf123** [Vazkii/Botania#2626]
# Version Information
Forge version: 14.23.3.2655  
Botania version: r1.10-354  

# Further Information
Steps to reproduce:
1. Make the Botanurgist's inkwell.  
2. Have some paper in inventory.  
3. Scan sky with thaumometer.  

What I expected to happen:
Get celestial notes.  

What happened instead:
Nothing.

**Comment by FenrisWolf123** [comment]
Scratch it. I forgot to research the celestial notes thingy.

**Comment by the-pieman** [comment]
I know this has already been closed, but I'm having the same issue, but I do have the Celestial Notes research. I can scan the Sun and it says I can't take notes. The inkwell is full. I create some regular scribing tools and then it lets me. So I'm also having the same problem, but Wags' "fix" doesn't work for me.
