### ISSUE TITLE
Suggestion: Thaumcraft Aspects

### ISSUE THREAD

**Issue by Wotzinator** [Vazkii/Botania#2629]
i just wanted to say that it would be cool if you could give the items and blocks and so on thaumcraft aspects .

**Comment by codycoolwaffle** [comment]
This probably won't happen until Thaumcraft is stable, even then it's unlikely

**Comment by williewillus** [comment]
I'm interested in making this happen as traditionally botania has supported thaumcraft.

I haven't played the new version though so I don't know what opportunities there are for integration. Definitely want some though.

**Comment by yrsegal** [comment]
I had aspects in Botanical Addons if you want to use that as a base. Back in 1.7.10 x.x

**Comment by yrsegal** [comment]
https://github.com/L0neKitsune/Botanical-Addons/blob/develop/src/main/java/ninja/shadowfox/shadowfox_botany/common/compat/thaumcraft/BotaniaTCAspects.kt

**Comment by yrsegal** [comment]
It's very old stuff and in kotlin, but it's probably easier to change this than start from scratch

**Comment by Leppan** [comment]
Botania still has the Botajurnist's Inkwell IIRC, so the only reason why this hasn't happened is because of how tedious it is.

**Comment by yrsegal** [comment]
Hence why I provided this
