### ISSUE TITLE
[1.12.2] Crash when creating Terrasteel

### ISSUE THREAD

**Issue by wiloxe** [Vazkii/Botania#2630]
# Version Information
Forge version:  forge-14.23.3.2678
Botania version:  r1.10-354

# Further Information
Link to crash log: https://pastebin.com/PYRHe7fQ
Steps to reproduce:
1. Build the structure needed to make Terrasteel
2. Drop all required items to make Terrasteel
3. Then crash!

What I expected to happen:
Without any crash, Terrasteel should be created and I can continue my day.

What happened instead:
A second or two after providing with mana the game froze and crashed.

Comments:
I don't know if this is mod conflict-related, however, since the crash report only reports Botania I cannot say it is.

**Comment by williewillus** [comment]
Does it happen without any other mods? (just baubles, botania, and forge)

**Comment by wiloxe** [comment]
Okay, so it turns out to be a mod conflict-related issue with VanillaFix.
https://github.com/DimensionalDevelopment/VanillaFix/issues/18

**Comment by Runemoro** [comment]
Not a conflict, VanillaFix helps mod authors to find bugs which are otherwise difficult to fix by crashing (in 1.0.1) or showing a warning screen (in 1.0.2) in an exception during a scheduled executable.

**Comment by williewillus** [comment]
I still want to see if this is reproducible without any other mods. 
The particle ID in the packet is somehow changing (it's trying to show another particle effect unrelated to terrasteel crafting) which should never happen unless there's network/memory corruption or a mod's messing with the network system.

**Comment by wiloxe** [comment]
I was unable to reproduce when testing with no other mods than Botania, Baubles, and Forge.

**Comment by Hillage** [comment]
Howdy,

As stated above, I do not get this bug with only Botania and Baubles. As soon as I add VanillaFix it crashes.

Note - VanillaFix 1.0.4-35 has changed what happens when it encounters the "error" - it now shows a warning screen instead of kicking back to the title, however this doesn't help as the warning re-appears immediately after dismissing it.

With Botania, Baubles, VanillaFix the following crashlog occurs:

https://paste.dimdev.org/bazujeseze.txt

I will be commenting on the issue over at VanillaFix's github as well

**Comment by williewillus** [comment]
I want to be 100% sure; there is no way I am sending the wrong effect ID there, so I suspect another mod causing network or memory corruption.

The packet is sent from [here](https://github.com/Vazkii/Botania/blob/124fc8518a28bfeb79875e15ada9e1db39740549/src/main/java/vazkii/botania/common/block/tile/TileTerraPlate.java#L98)

But the exception is occurring [here](https://github.com/Vazkii/Botania/blob/d244e12437de3d5aa8669a18b8f714efbadbdcda/src/main/java/vazkii/botania/common/network/PacketBotaniaEffect.java#L236) in a completely different effect ID. 

This is nonsensical and also doesn't happen in the dev workspace so it has to be a conflict or something hacking around.

**Comment by Hillage** [comment]
Baubles and Botania ONLY, the following is thrown in the log (repeatedly as the process goes on):

https://pastebin.com/kQRC2hN5

Tested with creative pool, agg plate setup, and both mana spreader and spark in different tests.

**Comment by williewillus** [comment]
Ah, I derped. Blame C-style switch for being dumb :P 
Fixed in next release.
