### ISSUE TITLE
Sash speed too high when walking in water

### ISSUE THREAD

**Issue by pythondude325** [Vazkii/Botania#2636]
# Version Information
Minecraft version: 1.12.2
Forge version: 14.23.4.2703  
Botania version: r1.10-354  

# Further Information
Steps to reproduce:
1. Make a superflat world with preset `3;minecraft:bedrock,2*minecraft:dirt,minecraft:water`
2. Equip the Planestrider's Sash or Globetrotter's Sash  
3. Provide the sash with mana
3. Sprint in the water  

What I expected to happen:  
Sprinting in the water should be slower than on land  
What happened instead:  
With the Globtrotter's Sash, the speed of walking in water is 10.460m/s and 8.062m/s on land  
With the Planestrider's Sash, the max speed of walking in water is 26.960m/s and 15.330m/s on land  

Extra note:
This does not work in deeper water and it does not work with the Soujourner's Sash

**Comment by PG-Fuury** [comment]
http://www.monkeyuser.com/assets/images/2018/80-the-struggle.png

**Comment by pythondude325** [comment]
Was it intended behavior?
