### ISSUE TITLE
Lexica Botania crashes Minecraft when clicking on Next Page or using the Scroll Wheel to move to Next Page

### ISSUE THREAD

**Issue by thethirdrey** [Vazkii/Botania#2639]
# Version Information
Forge version: 14.23.4.2703
Botania version: r1.10-354 

# Further Information
Link to crash log: [gist](https://gist.github.com/thethirdrey/7478adb5377150f5da0d572a15794ef3)
Steps to reproduce:
1. On any world, open Lexica Botania
2. Go to any item that has more than one page
3. Click on Next Page or use the Scroll Wheel to go to the Next Page
4. Boom, crash :(

What I expected to happen: To go to the Next Page

What happened instead: Crashes Minecraft :(

**Comment by thethirdrey** [comment]
I've singled out the mod that was apparently causing the crashing using the process of elimination! :D It seems that the No Recipe Book mod by Seneschal_Luwin wasn't playing well with Botania

**Comment by Foxgreat** [comment]
This conflict is actual) so i hope it will be fixed

**Comment by williewillus** [comment]
I checked the No Recipe Book code and it blindly removes buttons from all guis without checking whether the gui is a vanilla one, or the button actually *is* the recipe book button, which is completely broken behaviour. This is not a botania issue.

**Comment by quat1024** [comment]
As a workaround, the mod FastWorkbench also removes the recipe book button, but in a sensible way (ime. a way that won't crash every mod that adds a GUI ever). You can get it [here](https://minecraft.curseforge.com/projects/fastworkbench).

**Comment by InsomniaKitten** [comment]
Charset also has a disabled-by-default feature for removing the recipe button.

**Comment by SeneschalLuwin** [comment]
Fixed in No Recipe Book v1.2.2 as of Jun/3/2018.
