### ISSUE TITLE
Render Issues with Optifine

### ISSUE THREAD

**Issue by PhiPhiper** [Vazkii/Botania#2642]
Hi, 
I m currently playing ftb revelation with optifine and after a while playing the botania particles(mana bursts) stop rendering. Anyone an idea why?

Best Phi

Botania Version: r1.10-353
FML: 8.0.99.99
Forge: 14.23.2.2627
Optifine: 1.12.2_HD_U_D1.jar

**Comment by PhiPhiper** [comment]
It happende without Optifine as well

**Comment by scotty9090** [comment]
Getting the same issue (no Optifine), but doesn't seem localized to Botania either.
