### ISSUE TITLE
Narslimmus doesnt work anymore

### ISSUE THREAD

**Issue by xILikepuddingx** [Vazkii/Botania#2643]
# Version Information
Forge version:  2690
Botania version:  Botania+r1.10-354

# Further Information
Steps to reproduce:
Show Video:
https://files.ilikepudding.de/iqo2zzfgqn.mp4

**Comment by williewillus** [comment]
Are those naturally spawned slimes? You tried a spawn egg but the flower only accepts slime  spawned in a slime chunk

**Comment by xILikepuddingx** [comment]
there is a slime chunk. i tested it with the egg and with slime cube from random things. naturally i dont test it

**Comment by quat1024** [comment]
That's just how it works right now - the hidden tag that Botania adds to slimes that spawn in a slime chunk, doesn't transfer to the smaller slimes that appear when it dies. You have to move the slime over to a Narslimmus without killing it.
