### ISSUE TITLE
Bubbel Crash when running out of mana

### ISSUE THREAD

**Issue by whitestarx0312** [Vazkii/Botania#2647]
Forge version:  forge-14.23.3.2697
Botania version:  Botania r1.10-354

# Further Information
Link to crash log: https://pastebin.com/HBD5tBUp
Steps to reproduce: Place a pool of mana and link it to a bubbel somewhere in water. Then, remove the mana source.

What I expected to happen: Bubbel will run out of mana, and the water will refill the space

What happened instead: Game crashes.

**Comment by williewillus** [comment]
can you reproduce this only with botania?

**Comment by whitestarx0312** [comment]
Hmm it seems I cannot. Any idea what the interaction could be?

**Comment by williewillus** [comment]
unfortunately, it looks like a general CME, so the only way to find it is to do the old binary search (add half the mods back, see if it happens; if not, the bad mod is in the other half; repeat the process until you're down to the last one)

**Comment by whitestarx0312** [comment]
Ok I'll try that. Thanks for your help!
