### ISSUE TITLE
`ItemMagnetRing` doesn't check `EntityItem#cannotPickup()`

### ISSUE THREAD

**Issue by skyboy** [Vazkii/Botania#2648]
As a result, fake items (see: `EntityItem#makeFakeItem()`) will be dragged to the player, as well as any other items with long, or infinite pickup delays.

**Comment by kiwifrogg** [comment]
I have this same issue when updating our pack to the newest recommended forge, the magnet becomes slow, almost useless, being a skyblock ppl really want the magnets to work. Any updates due to come out that might fix this wee bug?

**Comment by williewillus** [comment]
What? The issue you're describing is completely unrelated to this one.

**Comment by kiwifrogg** [comment]
Oh lol sorry I saw magnet and assumed it was the same issue,
