### ISSUE TITLE
[1.12.2] Lexica Botanica crashes when flipping page

### ISSUE THREAD

**Issue by KingCactaur** [Vazkii/Botania#2650]
# Version Information
Forge version:  1.12.2 - 14.23.4.2707
Botania version:  Botania r1.10-354.jar

# Further Information
Link to crash log: https://pastebin.com/WR1yB59u
Steps to reproduce:
1. Open up Lexica Botanica
2. Press "next" button
3. Crash

What I expected to happen:
Flip the page

What happened instead:
Crash

**Comment by williewillus** [comment]
Remove NoRecipeBook and use a different mod to remove the recipe book, its implementation is poorly-done and causes crashes. See #2639 for more information

**Comment by SeneschalLuwin** [comment]
Fixed in No Recipe Book v1.2.2 as of Jun/3/2018. v1.0.0 should also work fine.
