### ISSUE TITLE
[1.12.2] Weird separator in Lexica Botanica after white dog animation

### ISSUE THREAD

**Issue by KingCactaur** [Vazkii/Botania#2652]
# Version Information
Forge version:  1.12.2 - 14.23.4.2707
Botania version:  Botania r1.10-354.jar

# Further Information
Link to image: https://imgur.com/a/lWWNukY
Steps to reproduce:
1. Open up Lexica Botanica
2. Click the numerical botany thing to get the dog animation
3. Space is left, on other pages too

What I expected to happen:
White meme dog steals numbers from Botania and then we're all ok

What happened instead:
That void will never be filled

**Comment by williewillus** [comment]
can you try with just botania?

**Comment by KingCactaur** [comment]
Just to be clear, under what conditions does the dog animation play? With a new world, not the option for numerical botany (if you can't tell I don't remember the exact name) nor preventing decay (which I know used to call the dog) appear, even when I added mods back.

**Comment by Hubry** [comment]
The fact you touched the entry is saved in `BotaniaVars.dat` in your instance folder, together with your 
Lexica notes and bookmarks along with a few other things. Delete the file, or open it with NBTExplorer and set the `dog` variable to 0.

**Comment by KingCactaur** [comment]
Alright. By the way, while I was testing on a new world the break disappeared, with my old BotaniaVars.dat

**Comment by KingCactaur** [comment]
I can't replicate the bug, however in my original world, the break is gone as well. I removed "NoRecipeBook" by Seneschal_Luwin and that seemed to fix it.
