### ISSUE TITLE
Server timeout when nearing chunks with EntityManaBurst

### ISSUE THREAD

**Issue by KajesLorian** [Vazkii/Botania#2653]
# Version Information
Forge version: forge-1.12.2-14.23.2.2611-universal 
Botania version:  Botania+r1.10-353 AND Botania+r1.10-354

# Further Information
Link to crash log: https://pastebin.com/9kSi20uH
Steps to reproduce:
1. Load into world
2. Move to area with large Botania setup
3. Chunks will not load, then times out of server, and server shuts down due to timeout.

What I expected to happen: Botania flowers and rainbow generators

What happened instead: Withers and saddness

Jokes aside, any help you can give on pointing me in the right direction to fix this would be a huge help.

**Comment by williewillus** [comment]
does this area load fine with just botania?

**Comment by KajesLorian** [comment]
It's an established server. I'll have to make a copy and try it tomorrow. It used to work without issue.
