### ISSUE TITLE
Floral Fertilizer recipe doesn't show result until closing and re-opening the Crafting Table

### ISSUE THREAD

**Issue by Zsashas** [Vazkii/Botania#2657]
# Version Information
Forge version:  2705
Botania version:  354

# Further Information
Steps to reproduce:
1. Place the recipe for Floral Fertilizer in a Crafting Table or TiCon Crafting Station
2. See that there is seemingly no output
3. Close the GUI, then re-open it. Poof, it works.

What I expected to happen: Show the result right away

What happened instead: Requires a GUI refresh or something, I don't know.

**Comment by williewillus** [comment]
does it happen with just botania?

**Comment by quat1024** [comment]
Cannot reproduce in a vanilla crafting table with Botania 354 and Forge 14.23.4.2705

Closing and opening it dumps the items into your inventory anyways in vanilla, are you sure some mod isn't registry-replacing the vanilla crafting table or something? (I think redstone++ does)
