### ISSUE TITLE
Natura Pylons are invisible when held

### ISSUE THREAD

**Issue by Sunconure11** [Vazkii/Botania#2658]
Since a log and crash report are not applicable here, I'll just state the version of Botania, and a mod I believe may be a culprit.

Botania version is Botania r1.10-354

Minecraft version is 1.12.2

Forge version is 14.23.4.2712

Culprit mod is likely Endless Traverse, as it caused some fucky rendering issues with Erebus. (https://minecraft.curseforge.com/projects/endlesstraverse?gameCategorySlug=mc-mods&projectID=274515)

**Comment by williewillus** [comment]
can you verify it's that mod doing it? if so, it's likely that mod not overriding a TEISR properly (and it's not open source so I can't check that easily)

**Comment by Sunconure11** [comment]
Can confirm its endless traverse.

**Comment by Sunconure11** [comment]
https://github.com/ganymedes01/TheErebus/issues/619
