### ISSUE TITLE
Manasteel Tools not breaking blocks (still)

### ISSUE THREAD

**Issue by ElazulAoneko** [Vazkii/Botania#2659]
# Version Information
Forge version:  14.23.4.2705
Botania version:  r1 10-354

# Further Information
Steps to reproduce:
1. Have Manasteel tools
2. Have mana-storing items
3. Try (And subsequently fail) to break blocks with said tools, even appropriate ones.

What I expected to happen:
I expected it to work like it always does: Break blocks, eat a little mana to repair, nice and simple.

What happened instead:
I tested this on both a friend's custom pack. Whenever I have mana in my inventory, be it a ring (worn in baubles slot or not), or a mana tablet, the tools suddenly cannot break blocks. Shovel takes nearly as long to break dirt as it does to mine obsidian by hand, pick can't break netherrack, and so on. Even the sword can't break cobwebs or leaves. I take all mana-storing items out of my inventory, and I can use them like normal. And having the bauble case in my inventory seems to count for the "having mana" thing too.

I know this has been brought up before, but that was before the most recent update back in April, and if the advice is to downgrade Baubles, the game won't let me work with anything other than latest if I'm using 354.

Update: Seems to be server-only, though my own Single Player has mixed results.

**Comment by quat1024** [comment]
Very strange.

Modlist? Is this a plain Forge server or are you using some Spongeforge-like thing?

> though my own Single Player has mixed results

What do you mean by this?

**Comment by ElazulAoneko** [comment]
What I mean is that when playing single player, it seems sometimes the world generated doesn't have issues with the tools, and in others, it does. Friend who runs the modpack tested it single-player, had zero issue.
Also turns out that I can't break blocks with -anything- from botania as long as I have mana storage on me, as I found when trying to dig at some dirt while holding Living Rock and the thing you use to make Terrasteel.

As for the mod list... 
![image](https://user-images.githubusercontent.com/40618371/42074514-87de1d14-7b21-11e8-9f2f-6b7587b8104a.png)
![image](https://user-images.githubusercontent.com/40618371/42074542-a07e40d8-7b21-11e8-8a7c-d87412146145.png)

**Comment by williewillus** [comment]
Update baubles

**Comment by ElazulAoneko** [comment]
Baubles is up to date, 1.5.2 is the most recent version

**Comment by williewillus** [comment]
Post logs when this happens

**Comment by ElazulAoneko** [comment]
Getting logs for this problem is not possible as it is not causing a crash, no error messages are popping up, it just simply... Isn't working. Manasteel tools, manasteel sword, living rock, living wood, and a few other various Botania items simply are not doing anything when trying to break blocks with them, regardless the block, as long as there is mana in the inventory or a bauble case is being held. When trying to left-click to break things, like with a shovel on dirt, nothing happens. It makes the motions, but no progress at all is made towards breaking the block. At least punching obsidian makes progress.

There are no logs to post because of -how- it's not working.
