### ISSUE TITLE
Pride ring isn't providing attack range

### ISSUE THREAD

**Issue by Darkmega18** [Vazkii/Botania#2660]
# Version Information
Forge version: 1.12.2, 2705
Botania version:  Botania+r1.10-354

# Further Information
Link to crash log: There is no crash. it's just not doing the thing like the potato wants it to.
Lots of mods. two or three which add their own block reach abilities but seem to compound with the block breaking range to create mile long break range. but attack range still remains close.

cyclic reach enchant on armor
armorers construct TK glove
general effect of weilding valkyrie tools in aether

Valkyrie tools and weapons from aether legacy seems to be the only one who's attack range is improved with while ALSO simultaneously providing their block break range. they could be the culprits stopping everyone else due to funky core mods? (I don't code, so just guessing. since aether would probably load first due to alphabet)
edit: hold on. it might be cyclic. I put on a piece of armor from it and now even the block range won't work... so turns out that stuff is pretty good from cyclic if the range was just from that and my ring was doing nothing for me... o.o

Steps to reproduce:
try to punch mob. to check range. step back till you can't punch stuff.
put on pride ring to try to increase general block breaking, scanning and attacking range.
Try to punch mob again at further than current range. still won't punch.

What I expected to happen:
Should be able to punch mobs at the +3 range that it says in the book.

What happened instead:
no attack range added. However block breaking range still works and block breaking actually can get increased further by using mods with their own block breaking range upgrades.

**Comment by Darkmega18** [comment]
oh, ok then. I just did botania + JEI + hwyla + wayla in pack by themselves. no attack range on ring... so does that make it just a book write up error due to changes...? (which no matter what you say in your "botania has changed" pop-up, this seems like a step back) or is there really something wrong? D:

**Comment by Hubry** [comment]
Since build 353 the ring uses Forge's reach attribute, which currently has a limitation that it does not work with entities (deliberately omitted for simplicity). The only followup PR to Forge that was submitted to make it work with them didn't get merged. So yeah, this is a regression...

**Comment by Darkmega18** [comment]
Does that mean aether legacy does something hacky with just it's items when held in hand to allow them to at the very least strike mobs when at range?
