### ISSUE TITLE
Very frequent,strange and annoying crash in botania.

### ISSUE THREAD

**Issue by nghngn** [Vazkii/Botania#2663]
I‘m sorry to trouble you,but I really cannot visit the gist.
############################################

# Version Information
Forge version:  1.12.2-forge1.12.2-14.23.4.2705
Botania version:  Botania+r1.10-354

# Further Information
[crash-2018-07-01_17.43.28-client.txt](https://github.com/Vazkii/Botania/files/2152709/crash-2018-07-01_17.43.28-client.txt)
[2018-07-01-7.log.gz](https://github.com/Vazkii/Botania/files/2152711/2018-07-01-7.log.gz)

Steps to reproduce:
1. First step When I used my save,it showed that "Close the built-in server"and it crashed.
2. Second 
3. etc...

What I expected to happen:

What happened instead:

**Comment by SquidDev** [comment]
May better to post on #2205 instead?

**Comment by williewillus** [comment]
^ another case of #2205
