### ISSUE TITLE
There's an incompatibility with Voidaic Arcania that was discovered

### ISSUE THREAD

**Issue by CammiePone** [Vazkii/Botania#2665]
# Version Information  
Forge version:  Forge-14.23.3.2668  
Botania version:  r1.10-354  

# Further Information  
Link to crash log: There isn't a crash, but rather an incompatibility with Voidaic Arcania  
Steps to reproduce:  
1. Put on Ring of Odin  
2. Put on any bauble from Voidaic Arcania  
3. Infinite hearts if you spam removal of the baubles, and putting them back on  
  
What I expected to happen:  
Not to keep getting more health for every new bauble put on  
  
What happened instead:  
Infinite health. Also, I went ahead and tested it with other methods of increasing max HP, but it only seems to occur with the Ring of Odin. Removing it does not remove the health.

**Comment by CammiePone** [comment]
I would recommend changing it so the Ring of Odin changes the player's health like so:

`	@Override
	public void onEquipped(ItemStack itemstack, EntityLivingBase player)
	{
		player.getEntityAttribute(SharedMonsterAttributes.MAX_HEALTH).setBaseValue(player.getMaxHealth() - 20);
	}
	
	@Override
	public void onUnequipped(ItemStack itemstack, EntityLivingBase player)
	{
		player.getEntityAttribute(SharedMonsterAttributes.MAX_HEALTH).setBaseValue(player.getMaxHealth() + 20);
	}`

Also, apparently the game maxes health at 1024, which I found out, so it's not infinite, exactly, but it's still... pretty broken.

**Comment by Hubry** [comment]
Aren't you supposed to add a new attribute to the player on equipping the bauble and remove it when you unequip it? You seem to be modifying the base value of the player's health to be (base value + buffs he has + 2) instead of (base value + 2).

**Comment by CammiePone** [comment]
The issue is it's not just when you unequip, it's also when you equip. Not to mention, it adds 20 HP, not 2 HP. It is 100% due to the Ring of Odin. However, a fan of VA has requested that, rather than mess with health for the debuff, I make the baubles run off the original idea, where they draw power from crystals, so it's possible this will no longer be an issue.

**Comment by williewillus** [comment]
You're not supposed to modify base value like that for equipment. Use an attribute modifier

**Comment by CammiePone** [comment]
I could try that, I guess. Don't think it'll fix the issue, though. Either way, I'm going with the other method, of using the crystals that will power spells to power some of the baubles.

**Comment by williewillus** [comment]
There's the close issue button right around here vvv
