### ISSUE TITLE
Elven Gateway Core is causing lag

### ISSUE THREAD

**Issue by Philosyang** [Vazkii/Botania#2669]
# Version Information
Forge version:  14.23.3.2655
Botania version:  r1.10-354 (1.12.2)

# Further Information
Steps to reproduce:
1. Build an Elven Gateway multiblock
2. Turn it on and **keep it on for some hours**
3. TPS dropping gradually from stable 20 to ~10 (on a dedicated server)
4. Turn it off
5. TPS back to 20

What I expected to happen:
Keeping it on without lag.

What happened instead:
Noticeable TPS drop as time passes.

**Gateway uptime - 5min: (expected)**
![5min](https://philosyang.github.io/assets/img/imgdump/botania_uptime5min.png)
**Gateway uptime - 5hrs:**
![5hrs](https://philosyang.github.io/assets/img/imgdump/botania_uptime5hrs.png)

**Comment by williewillus** [comment]
can you capture a profile report at the "5 hours in" stage using something like visualvm, warmroast (if that's still a thing), sampler, or even the vanilla profiler (/debug start, wait a minute or two, /debug stop) and share the results here?

**Comment by williewillus** [comment]
and is this gateway core idle or are items being put in it?

**Comment by Philosyang** [comment]
I believe players are putting things into it at times, but I can't confirm whether not putting items will stop the lag or not.
Vanilla debugging is so laggy that I will choose another time when there is no one except me in the server.

**Comment by quat1024** [comment]
Do items happen to be going in to it? I know there's a bug (https://github.com/Vazkii/Botania/issues/2403) where any item that enters the portal that *isn't* part of a valid elven recipe just stays there, forever, in the NBT tag.

Can you `/blockdata <gateway core position> {}` ?

**Comment by Philosyang** [comment]
There were no excess items thrown into the portal.

**Comment by Hubry** [comment]
The block data shows 44 stacks of random things like quartz blocks, so it is related to #2403. I think another thing is that the recipe copies items to check for matching. I'm gonna try to mitigate this a bit if not fix outright.
