### ISSUE TITLE
Lexica Botania NBT Error

### ISSUE THREAD

**Issue by Hekera** [Vazkii/Botania#2670]
# Version Information
Forge version:  14.23.4.2727
Botania version:  r1.10-354
JEI version: 4.11.0.204
Refined Storage version: 1.5.34

# Further Information
Steps to reproduce:
1. Go onto a multiplayer server.
2. Go into Refined Storage crafting terminal. RS system should have materials necessary to create 1 Lexica Botania.
3. Find Lexica Botania in JEI, and click/press hotkey to go to recipe page.
4. Press + in the bottom right of the recipe.

What I expected to happen:
The recipe would be added to the RS terminal's crafting grid without issue.

What happened instead:
I was kicked from the server with an NBT error; screenshot attached. The game did not crash. The recipe worked fine on a normal crafting bench, but kicked when done in RS crafting terminal and equivalents (wireless crafting terminal). 

![unknown](https://user-images.githubusercontent.com/40907168/42406898-44506a5c-817f-11e8-9e10-08647c1d786d.png)

**Comment by raoulvdberge** [comment]
Not a botania issue
