### ISSUE TITLE
the spark Entity cause client crash

### ISSUE THREAD

**Issue by MoeShimaKaze** [Vazkii/Botania#2673]
Botania Version:r1.10-354
Forge Version:1.12.2-14.23.4.2705
Mod list:https://pastebin.com/Zsf5A1wL
error logs:https://paste.dimdev.org/igiceqabuh.mccrash
when i join to the server and i watching the spark enity,the Cilent crash

**Comment by quat1024** [comment]
This looks like it could be another data manager bug?

You can see here that Botania reads a value from an EntityDataManager and uses it as an index of an array: https://github.com/Vazkii/Botania/blob/73a1055b65c3aa43917653bc22eed19102d5c1ad/src/main/java/vazkii/botania/common/entity/EntitySpark.java#L340

This value is only ever supposed to be 0-4, but some other mod is messing up the data manager. When Botania tries to read the spark augment type, it is apparently getting 38. More information here https://github.com/Vazkii/Botania/issues/2114 .

Unfortunately, it is very difficult to debug these sorts of things. It's hard to figure out which mod is causing the data managers to get all out of sync.

\* Also: Ask your server operator if they see any EntitySpark-related errors in the *server* console. If it's not a data manager bug, it's possible that the spark itself somehow has a ridiculous value set for the spark augment. That would cause an error in `readEntityFromNBT`, which would at the very least, print an error in the server console.
