### ISSUE TITLE
No wings animation with VanillaFix

### ISSUE THREAD

**Issue by YueLengM** [Vazkii/Botania#2675]
# Version Information
Forge version:  1.12.2-14.23.4.2705
Botania version:  r1.10-354

# Further Information
Steps to reproduce:
1. Install VanillaFix(I am using the latest one)
2. Equip the Matrix Wings

What I expected to happen:
The Wings should have animation.
![2](https://user-images.githubusercontent.com/11801894/42860333-7cbf51de-8a88-11e8-988f-f85c7e9e9382.gif)

What happened instead:
The Wings just simply flap.
![3](https://user-images.githubusercontent.com/11801894/42860388-c7dbf3f2-8a88-11e8-834b-73a021776ef7.gif)

**Comment by YueLengM** [comment]
Also if `B:textureFixes=true` was set to `false` in `vanillafix.cfg`, this will be fixed.

**Comment by williewillus** [comment]
report to their issue tracker and crosslink here. I suspect the issue to be on their side, probably has to do with their `Tick only visible animated textures (huge FPS increase, up to 3x on very large modpacks)` feature.
