### ISSUE TITLE
Spectranthemum will not teleport certus quartz seeds

### ISSUE THREAD

**Issue by nathan416** [Vazkii/Botania#2676]
# Version Information
Forge version:  14.23.4.2705
Botania version:  r1.10-354
Applied Energistics version: rv5-stable-11
Modpack: Revelation 2.0.0

# Further Information
Steps to reproduce:
1. place down spectranthemum
2. place down full mana pool
3. bind mana pool to spectranthemum
4. bind spectranthemum to teleport target
5. throw down certus quartz seeds onto the spectranthemum

What I expected to happen: The seeds will be teleported to the target block

What happened instead: nothing

![2018-07-18_19 54 25](https://user-images.githubusercontent.com/30889482/42918958-79dfe32a-8ac4-11e8-895a-3432b905c721.png)

**Comment by codewarrior0** [comment]
Certus Quartz Seeds begin with age -6000, and many Botania flowers require dropped items to be a certain age before they will act on the item. The Spectranthemum will probably act on the item after five minutes.

Report this issue to Applied Energistics.
