### ISSUE TITLE
WIP Flower ID

### ISSUE THREAD

**Issue by N0tMyFaultOG** [Vazkii/Botania#2680]
# Version Information
Forge version:  1.7.10
Botania version: r1.8-249
Server version: Thermos 1.7.10 - 1614.58

# Further Information
No log necessary ![](https://i.imgur.com/BZhVYGL.png)

We try to give our players the Loonium thru essentials kits but it returns the flower from the image above. How can you give players the loonium thru a kit? I tried it with different item id's but they all return the special flower

**Comment by williewillus** [comment]
you need to set the `type` NBT tag of the flower to the flower type you want. e.g. `{"type": "loonium"}`

**Comment by N0tMyFaultOG** [comment]
`519 "type": "loonium" 1` doesn't work
