### ISSUE TITLE
The "Force Relay" can't relay mana with the wrap lens

### ISSUE THREAD

**Issue by EMROF-H** [Vazkii/Botania#2681]
# Version Information
Forge version:  1.12.2-14.23.3.2676
Botania version:  r1.10-354

# Further Information
![2333](https://user-images.githubusercontent.com/30215440/43071826-856ba7ca-8ea6-11e8-9c8c-701372d4a7d6.png)
As you see , the pool is empty.

**Comment by Hubry** [comment]
Intended, as seen in this snippet of Warp Lens's code: 
https://github.com/Vazkii/Botania/blob/15f71c8a537ef7ca93dabdbcaf8b1f130782aa57/src/main/java/vazkii/botania/common/item/lens/LensWarp.java#L48-L51

**Comment by williewillus** [comment]
works as intended
