### ISSUE TITLE
When you kill regular Blaze with terra blade beam, the game crashes (Garden of Glass)

### ISSUE THREAD

**Issue by AlexProGear** [Vazkii/Botania#2682]
# Version Information
Forge version:  14.23.4.2705
Botania version:  r1.10-354

# Further Information
Link to crash log: https://pastebin.com/uVTt53f8
Steps to reproduce:
1. Kill blaze with terra blade beam

What I expected to happen:
The Blaze die and drop some rods
What happened instead:
The game crashed, after re-logging there is no drop from Blaze

**Comment by williewillus** [comment]
report to crafttweaker

**Comment by ZeroLevels** [comment]
Looks like someone added a custom drop with a minimum stacksize of 0.  Unfortunately, it's not coded for a 0 case, so it literally tries to drop an item with 0 quantity.
