### ISSUE TITLE
Mana burst causes client crash when joining the server

### ISSUE THREAD

**Issue by belathus** [Vazkii/Botania#2683]
# Version Information
Forge version:  14.23.4.2739
Botania version:  r1.10-354

# Further Information
Link to crash log: https://gist.github.com/belathus/512da4dbba84c16c5e297e217db3e08d
Steps to reproduce:
1. Not entirely sure.
2. I set up a source of mana in the form of a gourmaryllis (just one), a gaia mana spreader, and a number of mana pools with sparks several days ago; the flower is being fed with cooked steak and mutton from a cow and sheep spawner.
3. After letting it work for a while, I logged off.
4. Now, when I log in, I get the above crash.

What I expected to happen:
Things continue to run without crashing.

What happened instead:
Client crashes when joining the server.  The server does not crash.

I'm pretty sure that the gaia mana spreader moving mana from the gourmaryllis to a mana pool is the only source of mana bursts in my base right now.

**Comment by stepsword** [comment]
Do you by any chance have "enable particle spawns on ships" enabled in valk warfare config, @belathus ? I noticed we have the same issue and also valk warfare on our modlist and turning that off seems to have fixed the problem for me (for now at least, unless it fixed itself some other way)

**Comment by stepsword** [comment]
update: it came back shortly after, and I disabled primitive mobs which seems to have fixed it.
