### ISSUE TITLE
Crash with Project E and Botania making Terra Steel

### ISSUE THREAD

**Issue by NanoHeart** [Vazkii/Botania#2687]
# Version Information
Forge version:  14.23.4.2744
Botania version:  r1.10-354
Project E version: 1.12-PE 1.3.0
# Further Information
Link to crash log: https://pastebin.com/G7A2TbSk
Steps to reproduce:
1. Make Terrasteel

What I expected to happen: 
To craft as normal

What happened instead:
ProjectE crashing to desktop

**Comment by frank89722** [comment]
Have same issue without projectE 
Forge version: 2745
Botania version: r1.10-354
crash log https://paste.dimdev.org/opoxacuyed.mccrash

**Comment by williewillus** [comment]
fixed in next version. in the meantime, disable vanillafix's hard crash mode
