### ISSUE TITLE
issue transmuting beetroot seeds

### ISSUE THREAD

**Issue by red-mist** [Vazkii/Botania#2688]
When throwing beetroot seeds in a mana pool with alchemy catalyst, the transmutation sound plays and the beetroot seeds disappear but no melon seeds appear.
Expectation: to receive melon seeds (as also shown in the overlay/tooltip).

Other transmutations (eg. potato->carrot->beetroot) function as expected.

Modpack: all the mods 3
Botania version r1.10-354

**Comment by williewillus** [comment]
can't reproduce. make sure you have right catalyst, and nothing nearby is picking up the melon seeds.

**Comment by red-mist** [comment]
Dear Williewillus,

Just to prove I'm not crazy:
https://drive.google.com/file/d/1WMl-k7LQhR7uwyK-64s39Dww4q39Fdnp/view?usp=sharing

Could it be a mod compatibility thing? All the mods does have a lot of them.

Thanks for all your efforts; botania's an awesome mod ^^

**Comment by williewillus** [comment]
do you hear the whoosh after you toss each item? you have an endoflame nearby that's catching and eating the melon seeds as fuel. move the pool and the flower further apart

**Comment by red-mist** [comment]
Yup. Did not even realize they had a burn time :-/ Thanks!
