### ISSUE TITLE
Worldshaper's Sextant can cause freezes with very large radii

### ISSUE THREAD

**Issue by YoshiRulz** [Vazkii/Botania#2694]
# Version Information
Forge version:  14.23.4.2745
Botania version:  r1.10-354

# Further Information
Link to crash log: N/A (freezes; log after killing MultiMC instance: [paste.ee](https://paste.ee/p/eryVx)/[gist.github.com](https://gist.github.com/YoshiRulz/5464cd51d845f0d6df339b1750cef2c9))
Steps to reproduce:
1. `/give @p botania:sextant`
2. Press and hold M2 while looking at ground
3. Look into horizon until a very large number is displayed beside the crosshair, and release M2

What I expected to happen:
Circle radius limited to render distance

What happened instead:
Minecraft freezes (presumably because the calculation isn't done asynchronously).

**Comment by CyberFLG** [comment]
What was the solution?
When I draw a circle at more or less 60+ blocks they disapear, but when I go back in the 60 block range I see them again. My render distance is 32 chunks.

**Comment by YoshiRulz** [comment]
That's not the problem I had, and the relevant code change was 6 years ago. ~~Open a new issue~~ Check #4732 since that seems much closer to your problem.
