### ISSUE TITLE
Crash with Chromaticraft upon launch

### ISSUE THREAD

**Issue by NightH4nter** [Vazkii/Botania#2696]
# Version Information
Forge version:  10.13.4.1614
Botania version:  r1.8-249

# Further Information
https://pastebin.com/YzhrPX68
https://pastebin.com/sEvmPeGJ
Steps to reproduce:
1. Just launch the game

What I expected to happen: game launched

What happened instead: crash
This is the copy of https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/1902 made just to be sure this is not caused by botania.

**Comment by ReikaKalseki** [comment]
It is an API version issue.

**Comment by williewillus** [comment]
botania 1.7 is not receiving further updates. it also looks like the issue is neither CC or botania's fault
