### ISSUE TITLE
Mana Burst crash

### ISSUE THREAD

**Issue by stepsword** [Vazkii/Botania#2698]
# Version Information  
Forge version:  forge-14.23.4.2732  
Botania version:  1.10-354  

# Further Information  
Link to crash log: https://gist.github.com/stepsword/8ea24461030397d7bd10d0c3eec0aec4  

I realize this probably is not a Botania problem as there was a previous [thread ](https://github.com/Vazkii/Botania/issues/2114) with something similar (but it was Float to BlockPos in that post, but here it's BlockPos to Float) stating it was a Draconic Evolution problem. I don't have that mod so I was hoping someone could maybe point me towards which mod could be doing this?

The mod list is in the crash log. I didn't modify any of them, I just downloaded as is.

Steps to reproduce:  
1. Set up a small endoflame setup to convert wood to mana, used two spreaders, 5 endo flames, 1 exoflame and 1 mana pool.
2. Player login near a mana burst (host PC unaffected, only player joining via multiplayer)  

 
What I expected to happen:  
Mana burst goes from mana spreader to pool without issue  

What happened instead:   
Player is booted from the server with a crash log

**Comment by williewillus** [comment]
these problems are hard to diagnose. you will have to do the whole "remove half the mods and check" dance to find the bad mod.

**Comment by stepsword** [comment]
Hi, I think I actually discovered the problem - it appears to be something with valkyrien warfare. Once I disabled "particle spawns on Ships" in the valk warfare config file, it stopped happening to the client connecting to the server. Hopefully this helps someone

**Comment by stepsword** [comment]
update: it came back shortly after, and I disabled primitive mobs which seems to have fixed it.
