### ISSUE TITLE
Crash with Botania's Exoflame and foundrys alloy furnace

### ISSUE THREAD

**Issue by scalda** [Vazkii/Botania#2699]
# Version Information
Foundry: Foundry-1.12.2-3.2.0
Botania: Botania r1.10-354
Forge: 14.23.4.2739

# Further Information
Link to crash log: [Crash Log](https://pastebin.com/ptvbWHDF) 
Steps to reproduce:
Place exoflame next to an alloy furnace from the foundry mod

What happened instead: crash to desktop on placement and then on world load

https://github.com/scalda/Foolcraft_3/issues/179

**Comment by Hubry** [comment]
Can be closed now as it was a Foundry issue fixed on their side.
