### ISSUE TITLE
[Idea] Hyacidus

### ISSUE THREAD

**Issue by DylanGK** [Vazkii/Botania#27]
The Hyacidus should be Botania's take at ore processing, in a more interesting way. It uses quite a bit of mana, and the more mana it receives, the more it produces. The mana one Thermalily produces should be the max speed it can be.

When you drop an ore nearby, it'll pick it up and the thing will float above the centre flower. Then, there will be acidic particles sprayed onto it, until it eventually breaks down (to be picked up by Hopperhocks perhaps).

Recipe:
- Purple Mana Petal x2
- Brown Mana Petal
- Green Petal x2
- Rune of Greed
- Rune of Water
- Rune of Earth

Loot table for a variety of ores (to be discussed):

Iron Ore
- 1 Iron Chunk
- 3-8 Iron Nuggets
- 0-3 Manasteel Nuggets
- Modcomp: 0-3 Tin Nuggets
- Modcomp: 0-1 Nickel/Ferrous Nuggets

Coal Ore:
- 2 Coal
- Random Floral Dusts
- 0-1 Diamond Fragment (rare)

Diamond Ore:
- 1 Diamond
- 2-6 Diamond Fragments
- 0-2 Managem Fragments

Gold Ore:
- 1 Gold Chunk
- 3-8 Gold Nuggets
- Modcomp: 1-5 Copper Nuggets
- Modcomp: 0-2 Electrum Nuggets (or 0-1 Electrum Dust, but far more rare)

Dylan: Lapis Ore:
- 7-10 Lapis 
- Blue Floral Dye

Redstone Ore:
- 7-10 Redstone Dust
- Red/Orange Floral 
- 0-2 Glowstone Dust
- Modcomp: 0-1 Copper Dust

Nether Quartz Ore:
- 1-2 Nether Quartz
- 0-1 Manaquartz (I'll expand on this later)

**Comment by eslachance** [comment]
Funny, you once said you'd never do RF generation with Botania either... Another bullet to bite? ;)
