### ISSUE TITLE
Pasture seeds do not work with bop dirt

### ISSUE THREAD

**Issue by Trinsdar** [Vazkii/Botania#2700]
I cannot currently turn bop dirt types into their respective bop grass types with pasture seeds.

# Version Information
Forge version:  14.23.4.2705
Botania version:  r1.10-354
I am using the modpack exoria version 1.3.0c.
Bop 7.0.1.2346

# Further Information
Steps to reproduce:
1. place down loamy dirt pr sandy dirt or silty dirt.
2. try to use a regular pasture seed on it.

What I expected to happen:
it to turn into either loamy grass, sandy grass, or silty grass based on what dirt it was used on.

What happened instead:
nothing at all happened.

Edit: turns out the version of bop that exoria uses is a bit old. I'll need to test it with the latest version.

**Comment by hm-ysjiang** [comment]
I think the pasture seeds would only work on the vanilla dirt blocks.

**Comment by williewillus** [comment]
^, there's no plans currently to have it work on other dirt blocks (perhaps in 1.13 if we get a dirt tag)
