### ISSUE TITLE
[Crash] Corporea Index render entity

### ISSUE THREAD

**Issue by Carbon-Key** [Vazkii/Botania#2711]
# Version Information
Forge version:  14.23.4.2756
Botania version:  r1.10-354

# Further Information
Link to crash log: https://pastebin.com/CY1pnL7d
Steps to reproduce:
1. Type "basic drawer" next to the index
2. Crash

What I expected to happen:
Receive a drawer.

What happened instead:
Received drawer and crashed. 

But more seriously, it seems to only crash me when it selected a Silverbell Drawer from all the drawers in the corporea network. A normal one didn't crash me when I tried it. Silverbell is a natura wood type. Not really sure what side this crash is on, my bad if it is a storage drawer (etc.) problem. Also, it only crashed the client, not the server (because it was a rendering issue I believe).

**Comment by williewillus** [comment]
I'm not sure what the problem is here, could you report it to storage drawers extras?
