### ISSUE TITLE
Synthesis terrasteel error

### ISSUE THREAD

**Issue by Xiazihong** [Vazkii/Botania#2712]
# Version Information
Forge version:  forge-1.12.2-14.23.4.2750-universal
Botania version:  Botania+r1.10-354

# Further Information
Link to crash log: https://paste.ubuntu.com/p/CFqN3wVTK5/
Steps to reproduce:
1. Synthesis terrasteel
2. When laying down the last required material

What I expected to happen:  Correct synthesis, no error

What happened instead:  Correctly synthesized, but an error has occurred.

**Comment by SquidDev** [comment]
I believe this is a duplicate of #2687.

**Comment by Xiazihong** [comment]
Maybe

**Comment by williewillus** [comment]
Yup, this will be fixed in the next version
