### ISSUE TITLE
Terrasteel aggl. plate crashes :(

### ISSUE THREAD

**Issue by CommanderTvis** [Vazkii/Botania#2717]
# Version Information
Forge version:  14.23.4.2757
Botania version:  1.10-354

# Further Information
Link to crash log: [https://paste.dimdev.org/apedigudeb.mccrash]

What I expected to happen: to get a terrasteel ingot. 

What happened instead: crash that was hooked by [https://minecraft.curseforge.com/projects/vanillafix](VanillaFix).

**Comment by SquidDev** [comment]
See #2687

**Comment by CommanderTvis** [comment]
@SquidDev thank you!
