### ISSUE TITLE
Colossal chests aren't visible through corpora sparks

### ISSUE THREAD

**Issue by Gaelan** [Vazkii/Botania#2719]
# Version Information
Forge version: 14.23.4.2175  
Botania version: r1.10-354  

# Further Information
Steps to reproduce:
1. Build a Colossal Chest (Colossal Chests mod; mine was 5x5x5 wooden)
2. In front of the colossal chest, place down a normal chest and place a corporea spark on it
3. Look through the corporea spark towards the colossal chest

What I expected to happen: I see the colossal chest. 

What happened instead: I see through the colossal chest  

Not sure where to report this, so I've reported it here for now

**Comment by quat1024** [comment]
I believe this happens with pretty much any TESR? It can be dependent on rendering order though

**Comment by enderger** [comment]
This happens when looking down on a mana pool with a spark on it: the mana becomes invisible

**Comment by quat1024** [comment]
This is a dupe of https://github.com/Vazkii/Botania/issues/2736 anyways

**Comment by Gaelan** [comment]
looks likee this is indeed a dupe
