### ISSUE TITLE
Portal to Alfhiem wont return updated Lexica Botania

### ISSUE THREAD

**Issue by FSFan** [Vazkii/Botania#2725]
v3.55   Two full pools of mana and everything set up properly.  Right clicking on core starts the process.  About an eight of the mana is used.  I chuck in the Lexica and it vanishes.  I try tossing in a mana pearl and it returns pixie dust like it is supposed to do.  No errors given

**Comment by Hubry** [comment]
...welp, that's the one special case I should've tested but didn't. 😓
