### ISSUE TITLE
Elven Lexica not returned when tossed into Portal

### ISSUE THREAD

**Issue by FSFan** [Vazkii/Botania#2729]
Portal set up correctly and functioning.  I toss the Lexica through the port but it does not return.  It just disappears.  Tossing mana pearls in return pixie dust so I know the portal is working.  I've posted this once but it disappeared from the github for some reason. 

-Rick

**Comment by SquidDev** [comment]
See #2725

**Comment by FSFan** [comment]
What the heck?  I SWEAR I couldn't find that.  I was looking for it!  Sorry for the dupe.
