### ISSUE TITLE
Quark flower pots take it extremely easy

### ISSUE THREAD

**Issue by ItsTheKais** [Vazkii/Botania#2735]
Forge 14.23.4.2758
Botania r1.10-356
Quark r1.5-129

1. Put any generating/functional flower in a flower pot.
2. Achievement unlocked!

![2018-09-10_09 27 19](https://user-images.githubusercontent.com/9879642/45337111-b4780180-b543-11e8-9bb7-e6351b4050dc.png)

(I'm not actually sure whether this is a Botania bug or a Quark bug!)

**Comment by williewillus** [comment]
quark bug/oddity, not really easy way to fix it except *maybe* in 1.13
