### ISSUE TITLE
crash with tiny planet

### ISSUE THREAD

**Issue by TheNimbleNinja** [Vazkii/Botania#2740]
# Version Information
Forge version:  14.23.4. 2760
Botania version:  r1.10-356

# Further Information
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)\
https://gist.github.com/TheNimbleNinja/d3b6095d68256170f09ed05e0a309115

**Comment by quat1024** [comment]
```
java.lang.NoSuchFieldError: CHARM
	at vazkii.botania.common.item.equipment.bauble.ItemTinyPlanet.getBaubleType(ItemTinyPlanet.java:47)
```
Someone is shipping a really old baubles API.
