### ISSUE TITLE
Small typo in Elementium Tools section of Lexica Botania

### ISSUE THREAD

**Issue by TheDeviantCrafter** [Vazkii/Botania#2743]
# Version Information
Forge version:  14.23.4.2759
Botania version:  r1.10-356

In the Elementium Tools section of the Lexica Botania, the first sentence of page 5 says:

"The Elementium Shovel will, **case** the block dug is affected by gravity (Gravel, Sand, etc), dig all the blocks..."

I believe the word "case" should be an "if".

**Comment by williewillus** [comment]
this is valid, it's short for "in the case"
