### ISSUE TITLE
Cobalt and Ardite ore from Tinkers' Construct vanish when mined with an elementium pick

### ISSUE THREAD

**Issue by TheDeviantCrafter** [Vazkii/Botania#2744]
# Version Information
Forge version: 14.23.4.2759
Botania version: r1.10-356
Tinkers Construct version: 2.10.1.87

# Further Information

Steps to reproduce:
1. Spawn an elementium pick with no enchantments in survival mode
2. Mine Cobalt and Ardite from the Tinkers' Construct mod

What I expected to happen:

I expected netherrack to vanish, but both of the Tinkers' ores to drop as an item when mined.

What happened instead:

Both netherrack and the Tinkers' ores vanish without dropping an item when mined.

**Comment by TheWhiteWolves** [comment]
Elementium is indeed only a harvest level of 3 so would be unable to mine cobalt and ardite, you'll need to use a terra shatterer (harvest level 4) to mine them.
