### ISSUE TITLE
Creeper turned two botania flowers into unknown flowers

### ISSUE THREAD

**Issue by 11001O10** [Vazkii/Botania#2746]
# Version Information
Forge version:  14.23.4.2705
Botania version:  r1.10-354
Modpack:  Primal Skies(server)

# Further Information
The creeper got lit on fire by a torch(feature of primalcore) and it blew up.

What I expected to happen:
The creeper will blew up the surrounding area and destroy the orechid and clayconia.

What happened instead:
The area didn't get destroyed at all,but the orechid and clayconia turned into a unknown botania flower.

**Comment by 11001O10** [comment]
Also,it happened on the server,not singleplayer

**Comment by williewillus** [comment]
do you have any terrain protection plugins active? if so, they might not handle nbt drops properly
