### ISSUE TITLE
Rannuncarpus only picks up player dropped items

### ISSUE THREAD

**Issue by jgeekw** [Vazkii/Botania#2748]
# Version Information
Forge version:  14.23.4.2759
Botania version:  r1.10-356

# Further Information
Steps to reproduce:

1. Place rannuncarpus (floating or non)
2. Set "looking for" block one or two blocks below flower (two for non-floating)
3. Bind rannuncarpus to mana pool
4. Place Open Crate a few blocks above ground within range of rannuncarpus
5. Connect hopper to Open Crate
6. Insert item into hopper
7. Watch item drop onto ground

What I expected to happen:
I expected the Rannancarpus to pick up the item and place onto target block

What happened instead:
Item sat there unaffected. Player must pick up item, then drop onto ground. Defeats the purpose of some automatic farms.

**Comment by williewillus** [comment]
Make sure your open crate is not powered

**Comment by jgeekw** [comment]
I tried again in a creative test world and placed an open crate above the ground. I then attached a hopper directly to the crate and inserted any functional flower.  With the rannuncarpus in range, and bound to a mana pool, it still never placed the flower on the target block.  Once I picked up the flower and threw it myself, the rannuncarpus functioned as expected.

**Comment by jgeekw** [comment]
ok, so this may not be a bug because it works as expected without other mods present. I just need to figure out which mod is causing the problem.
