### ISSUE TITLE
Ring of the Mantle deflects projectiles

### ISSUE THREAD

**Issue by ZXQWAS** [Vazkii/Botania#2750]
# Version Information
Forge version:  14.23.4.2730
Botania version:  Botania+r1.10-356.jar

# Further Information
Steps to reproduce:
1. Wear Ring of the Mantle in bauble ring slot

What I expected to happen:
Only have Haste 2?

What happened instead:
In addition to adding infinite Haste 2 like it should, I'm now deflecting all projectiles fired at me. How come? I've removed everything wearable and left only that ring, and was still deflecting all arrows, Lycanites charges, etc (not Techguns bullets it seems though). Moved the ring from the bauble slot to inventory, and immediately started receiving hits. Put it back - no hits.

**Comment by Hubry** [comment]
All the ring does is put Haste II on the player, so this seems like some mod adds an arrow deflecting effect to players with Haste. Try to apply the potion effect itself (either with commands, the haste brew, or a beacon) without the ring.

**Comment by ZXQWAS** [comment]
Yes indeed. I drank Botania's vial of haste and effect was the same, right until Haste ended. Very weird.
