### ISSUE TITLE
Reply/Clarification

### ISSUE THREAD

**Issue by FloratheFernFern** [Vazkii/Botania#2754]
_Originally posted by @williewillus in https://github.com/Vazkii/Botania/issues/2752#issuecomment-426154288_

I'm sorry I wasn't clear in my original issue post/question, but I mean to say that I have already tried using the recipes and features in the normal world, but so far are only able to use the recipes. I also want to be able to use the pebble, waterbowl, and buffed orechid of GoG, but seeing that I can't make pebbles or waterbowls in normal,customized or superflat worlds, I don't think rebuffed orechids would work and that GoG features aren't, for me, working in the default type worlds. Specifically, I want skyblock where you can bridge far enough to reach land and explore and generate structures or mod specific ore. I've tried splicing in customized generation into a GoG generated skyblock world by using NBTexplorer into the "generatorName" in the level.dat file, but then for some reason I can't make any more pebbles or water bowls. These are the features I really want since they are important for a sort of survival in the "dire conditions" type of world I have created in customized worlds.

**Comment by Hubry** [comment]
You also asked on /r/botania right? Well, I am just gonna copypaste my response I just posted there.

Things that depend only on Garden of Glass being loaded:

* Alternate recipes: Cocoons of Caprice, Blaze Lamps, End Portal Frames, Slime Balls from Magma Cream, Cobble from Pebbles, Living Roots to Floral Fertilizer and Saplings, Mana Spreaders, tripled output of normal Floral Fertilizer recipe
* Mana infusions: Sugarcane from hay blocks, prismarine from quartz with the alchemy catalyst
* Cheaper orechid recipe
* Orechid takes a fraction of time and mana to run
* Petal Apothecaries can't be emptied by buckets
* Burntime of blaze lamps halved
* Whether or not the Orechid and Cocoon of Caprice are listed as elven in the Lexica
* If GoG exclusive items are listed in creative tabs and have aspects assigned

Things that depend on both GoG being loaded *and* the worldtype being set to skyblock:

* Getting pebbles from dirt, grass and similiar blocks
* Empty bowls being possible to fill with water
* A quarter of wheat seeds dropped by grass being replaced by pumpkin or melon seeds 
* If lights from the Flash lens will give you a lexicon when right clicked with a sapling when you dont have a lexicon.

**Comment by quat1024** [comment]
NB: Botania Tweaks can enable the water bowl and OP orechid settings in non-GOG worlds, and you could probably pull off the pebble thing with a little Scavenge trickery.

**Comment by williewillus** [comment]
I'm probably going to fix this so that nothing depends on the worldtype itself, just gog jar.
