### ISSUE TITLE
Server doesnt load, crash.

### ISSUE THREAD

**Issue by adamboyce556** [Vazkii/Botania#2756]
# Version Information
Forge version:  whatever is included in FTB infinity evolved 2.6.0
Botania version:  r1.8-249 for 1.7.10

# Further Information
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)\
Steps to reproduce:
1. First step
2. Second step
3. etc...

What I expected to happen:

I work for a server hosting company, and we have a preset template for FTB Infinity Evolved 1.7.10 - 2.6.0. One of our customers used it and brought an issue up as the server wouldnt start
What happened instead:
The server crashes while loading, printing a NoClassDefFound error (see attached) https://pastebin.com/HRhHbPJU

only this mod errors, we run java 1.8.0_181 and update regularly, on a linux OS dedicated machine.

**Comment by williewillus** [comment]
try botania alone, perhaps another mod is messing with it. a fresh copy in case the jar got corrupted.
the 1.7.10 release isnt supported anymore, but it should be mostly stable and usable.
