### ISSUE TITLE
(request) Corporeal request change

### ISSUE THREAD

**Issue by larskr96** [Vazkii/Botania#2757]
is it possible to make the corporeal request work in the recipes window for jei

What does this change do=
It makes you can craft what you want easly
and not have to search throught jei to find the items you need for one craft

**Comment by williewillus** [comment]
is this what you wanted? https://github.com/Vazkii/Botania/pull/2755

**Comment by codewarrior0** [comment]
Doesn't that let you request individual items by hovering on them and clicking the hotkey?

What would be even better is if the JEI autofill `+` key could be used to request all of the ingredients at once, instead of having to request them individually. Kind of like the old LP Request Table.

**Comment by Hubry** [comment]
Yes, my PR lets you request items in the same way as from the item list, but inside the recipe gui, which is not currently possible.

I don't know if the JEI autofill option is actually possible, as much as that would be great - it would probably require overriding the default transfer handler for the workbench container, hijacking the crafting table interface, or possibly adding some kind of corporea workbench, which feels opposite to the aim of this mod.

I do think the poster of this issue wants what I made the PR for though.
