### ISSUE TITLE
Draconic Evolution flight and Gaia fight

### ISSUE THREAD

**Issue by DemonfangArun** [Vazkii/Botania#2759]
# Version Information
Forge version:  14.23.4.2749
Botania version:  r1.10-354

#Issue: Draconic armor flight does not work during gaia boss fight. The expected result is that it does. I could not find a config option in either Botania or Draconic Evolution that controls this. Thusly I must assume it's a bug or something hardcoded.

If I had to pick a direction, I would look at how flight is disabled. DE uses double tap space to initiate flight (the same as creative). It's possible it's being misinterpreted.

-If it's a bug, well, it needs fixed

-If it's hardcoded, please do not hard code options like this, put them in a config file. Disabling stuff from another mod, without a way to undo it, is frowned upon.

**Comment by Hubry** [comment]
The Guardian of Gaia disabling creative flight during the battle is entirely intended and I do not forsee a config option being added for this, as the original intention of this boss fight was to not be cheesable. 

"without a way to undo it" - end the fight (by killing the Guardian, leaving the arena, or dying) and it is undone! I don't see an issue here.

**Comment by DemonfangArun** [comment]
My problem with it is not whether or not it makes the fight "cheesable", it's more on principle. I dislike it when one mod messes with another such as to nerf it, without giving an option to disable the behavior (most mods allow this).

By "without a way to undo it" I was referring to having a config option. The major point I'm trying to get to is that it should be up to the end player to decide on whether one mod can affect another. I respect those that like flying disabled in xyz scenario, I'm not one of them. I put a lot of work into armor that allows flight, and I want it available at all times.

**Comment by williewillus** [comment]
what Hubry said

**Comment by quat1024** [comment]
Bye Felicia

**Comment by FenrisWolf123** [comment]
kekkers be kekking
