### ISSUE TITLE
Nothing happens after getting on a linked Luminizer

### ISSUE THREAD

**Issue by Alan19** [Vazkii/Botania#2760]
# Version Information
Forge version:  14.23.4.2765
Botania version:  r1.10-354

# Further Information
Link to crash log: https://paste.ee/p/OcAxK
Steps to reproduce:
1. Place two luminizers next or close to each other
2. Link them using the bind function of the wand of the forest and see the particles that link them appear
3. Right click the first luminizer to get on

What I expected to happen:

I should be moved to the next luminizer

What happened instead:

Particles appear under me but I do not move

![2018-10-09_10 50 19](https://user-images.githubusercontent.com/11682762/46678314-5f66f400-cbb2-11e8-845b-f31b72d12d58.png)

**Comment by MrTitainin** [comment]
Same here, also with Valkyrien Warfare. Can it be expected to be fixed or worked around on Botania's side? Valkyrien Warfare contributors doesn't seem to be very active.
