### ISSUE TITLE
Is garden of glass server-side only?

### ISSUE THREAD

**Issue by BrandHyde** [Vazkii/Botania#2763]
# Version Information
Forge version:  
Botania version:  

# Further Information
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)\
Steps to reproduce:
1. First step
2. Second step
3. etc...

What I expected to happen:

What happened instead:

**Comment by williewillus** [comment]
if there's anything that affects gameplay, the server side is what controls it.
