### ISSUE TITLE
Pistons pushing mana bursts

### ISSUE THREAD

**Issue by aMerryElk** [Vazkii/Botania#2765]
Under certain conditions, pistons can push mana bursts, as demonstrated [here](https://youtu.be/qjfTbmV4RN0)  
  
The timing has to be precise, so it's not a big problem once you realise what's happening, but it left me very confused for 20 minutes until I figured out.

# Version Information
Forge version:  14.23.5.2768
Botania version:  r.1.10-356

**Comment by williewillus** [comment]
tempted to say that this is intended since bursts are entities and nearly all entities in mc are pushable by pistons

**Comment by williewillus** [comment]
let's say this is intended
