### ISSUE TITLE
"Portal to Alfheim" but it'll be an error of "Tried to read NBT tag that was too big".

### ISSUE THREAD

**Issue by moondoldo** [Vazkii/Botania#2769]
# Version Information
Forge version:  release 1.12.2-forge1.12.2-14.23.4.2749
Botania version:  Botania+r1.10-354.jar

# Further Information
"Portal to Alfheim" but it'll be an error of "Tried to read NBT tag that was too big".
It ends by an error at the time of a server connection from a client.
The mechanism to carry an item in automatically is made "Portal to Alfheim".
When a "Portal to Alfheim" block group was eliminated in mcedit2, it was settled.
log file
[2018-10-27-6.log](https://github.com/Vazkii/Botania/files/2522619/2018-10-27-6.log)

What I expected to happen: login

What happened instead: error message
![2018-10-28_13h25_58](https://user-images.githubusercontent.com/26758846/47614142-47620080-dade-11e8-89d9-056fd1d9b5d4.png)

**Comment by Hubry** [comment]
Duplicate of #2403, update Botania. If you can't, the workaround is: stop throwing thousands of useless items that are not traded into the portal.

**Comment by moondoldo** [comment]
It was confirmed to be corrected by the following version.
Thank you very much.

Botania - Changelog
https://botaniamod.net/changelog.php
>R1.10 355
>・Fixed the Alfheim Portal storing useless items internally. (Hubry)
