### ISSUE TITLE
Lens: Kindle not working properly?

### ISSUE THREAD

**Issue by Marcelo-Petrucelli** [Vazkii/Botania#2770]
# Version Information
Forge ML version:  8.0.99.99
Botania version:  r1.10-354

# Further Information
Link to crash log: I have no crash
Steps to reproduce:
1. Attach a Kindle Lens on a Mana Spreader
2. Link the spreader to any block
3. No fire seems to be set

What I expected to happen: I expected the burst of mana light blocks on fire, the ones in the way or, at least, the one that was selected as a target of the burst.

What happened instead: Nothing.

Am I doing something wrong?
https://imgur.com/a/IiBaDXh

**Comment by Hubry** [comment]
Most mana spreaders only fire mana bursts if they know that a fired burst will hit a block that accepts mana. You want a pulse spreader, or a contraption that would trick the spreader into firing and then redirecting the burst away with something like an influence lens. This is working as intended.

**Comment by williewillus** [comment]
^
