### ISSUE TITLE
Petal Apothecary Collecting An Extra Item From A Stack

### ISSUE THREAD

**Issue by ConnorMiner** [Vazkii/Botania#2773]
# Version Information
Forge version:  14.23.5.2768
Botania version:  r1.10-357
Realistic Item Drops version: 1.2.14

# Further Information
Video: https://drive.google.com/file/d/1x4FJrSK1agKsj5CttspuR_eosKRHHPE5/view?usp=sharing
Modpack Used: Stoneblock
Steps to reproduce:
1. Fill Petal Apothecary with Water
2. Toss in more than 1 of an item
3. An extra {itemname} appeared!

What I expected to happen:
The items to go in without duplicating.

What happened instead:
The items had an extra copy of them made from nowhere.

**Comment by Hyperleogamer** [comment]
ok i did this it is something that is a bug/glitch in the mod 1.Are you using a mod pack 2.check the other mods 3.check the mods info if  you said yes to 1 then there IS  a chance a mod that is IN that modpack is doing something to botania's coding

**Comment by williewillus** [comment]
I couldn't get this to happen with just botania
