### ISSUE TITLE
Horse virus can create baby animals

### ISSUE THREAD

**Issue by duely** [Vazkii/Botania#2777]
This feels like undesirable behaviour as you then have to wait a few minutes for it to grow to adulthood. Saddles aren't lost (thankfully).

Forge version:  2768
Botania version:  83bbf64acb & r357

Link to crash log: Not relevant.

Steps to reproduce:
Difficult to reproduce. AbstractHorse:onInitialSpawn has a 1-in-5 chance of creating a baby animal instead of an adult.

1. Tame a horse, equip it with a saddle and capture it in an EnderIO soul vial.
2. In creative mode, use the vial to spawn infinite tamed horses.
3. Apply nulloderm virus (or necroderm) until you get a baby animal.

What I expected to happen:
I mean, getting a baby horse isn't a huge deal, it's just a mild inconvenience.

Theoretically it should be possible to simply call newHorse.setGrowingAge(0) at ItemVirus:103 to re-adultify the animals before spawning them while still gaining the benefits of whatever onInitialSpawn does additionally. 

I'd file a pull request but it seems an awful lot of work for a 1 line change.

**Comment by Hubry** [comment]
I was looking at this, thinking it would be an easy oneliner patch, but it seems like there's an another issue to handle - the viruses stopped applying the bonus to the horse stats at some point, making the created horses always have double the default speed and health of a zombie/skeleton horse, with the only attribute varying being the jump height (which is the only random stat of zombie and skeleton horses).
