### ISSUE TITLE
Endoflame Not Working

### ISSUE THREAD

**Issue by NathanH759** [Vazkii/Botania#2779]
# Version Information
Forge version:  14.23.4.2760
Botania version:  1.10-356
Modpack: Direwolf20

# Further Information
What I expected to happen: When throwing any fuel the endoflame doesnt pick up/use the fuel?

What happened instead: fuel just stays on floor next to endoflame
![2018-11-18_21 47 42](https://user-images.githubusercontent.com/45152674/48678484-f349b980-eb7b-11e8-9214-aee02b08663e.png)
![2018-11-18_21 47 59](https://user-images.githubusercontent.com/45152674/48678485-f349b980-eb7b-11e8-81d4-92f467a686b5.png)

**Comment by KrazyBrute** [comment]
Yes, I just checked using wand of forrest

**Comment by KrazyBrute** [comment]
> are the flowers bound to the spreader?

Yes, I've just checked using wand of the forrest. I threw one piece of coal down and it used it for the first time but it wont do it again

**Comment by quat1024** [comment]
Blocks of coal, like you're using in your screenshot, burn for quite a while. Try again later.

It's also possible that the flower isn't able to empty its mana anywhere. Is the mana spreader emptying into the mana pool?

**Comment by VadersFist0501** [comment]
Blocks of Coal burn for around 7 minutes.
1 block of coal burns in a furnace for 80 items, which is 800 seconds. (at ten seconds per item)
800 divided by 2 (for endoflame's faster speed) and then by 60 gives you 6.66 minutes
A block of coal has to sit in the endoflame for nearly seven minutes to be fulling burned, though an overgrowth seed will halve this further.

**Comment by curiosity-a** [comment]
Perhaps this is related, something I have noticed while playing. If endoflame doesn't find any suitable fuel, it goes into some sort of idle mode for quite a while. Botania version is the same as OP's.
