### ISSUE TITLE
"Glowing" effect has strange render in the center of manaseer monocle, is this intentional?

### ISSUE THREAD

**Issue by Azutte** [Vazkii/Botania#2785]
# Version Information
Forge version:  14.23.5.2772
Botania version:  Botania r1.10-357

# Further Information
Steps to reproduce: 
1. get Glowing
2. wear the monocle
3. 
![2018-11-26_14 31 02](https://user-images.githubusercontent.com/6581284/49046275-6066db80-f188-11e8-8231-5a168fa752e2.png)
![2018-11-26_14 31 11](https://user-images.githubusercontent.com/6581284/49046276-6066db80-f188-11e8-9e4b-f4573a28cacc.png)

**Comment by williewillus** [comment]
yes, the glow effect just works like that - it's because the middle pixels of the monocle (where the square is) are partially transparent, so the glow effect treats it as an edge it should highlight
