### ISSUE TITLE
Tile entities are not rendered through sparks

### ISSUE THREAD

**Issue by TheNoseOfSauron** [Vazkii/Botania#2789]
# Version Information
Forge version:  1.12.2 - 14.23..5.2768
Botania version:  r1.10-357

Tile entities such as chests and mana in mana pools are not rendered through sparks, as shown in the screenshot in the attached link.
https://imgur.com/a/y19n5Ls

**Comment by Hubry** [comment]
Duplicate of #2736, see also #2719.

**Comment by williewillus** [comment]
dupe
