### ISSUE TITLE
GoG worlds missing Bedrock

### ISSUE THREAD

**Issue by Seyeght** [Vazkii/Botania#2801]
# Version Information
Forge version:  1.12.2-14.23.5.2784
Botania version:  r1.10-357

# Further Information
Garden of Glass worlds no longer spawn with a piece of bedrock in the island.

What I expected to happen:
Starting block to be a 3x3x4 island with a piece of bedrock in the center

What happened instead:
The bedrock location is now a stone block.

**Comment by williewillus** [comment]
this is probably another mod messing with things, the code still generates bedrock: https://github.com/Vazkii/Botania/blob/master/src/main/java/vazkii/botania/common/world/SkyblockWorldEvents.java#L192

**Comment by Cazadorsniper** [comment]
It is very likely Noodle https://minecraft.curseforge.com/projects/noodle?gameCategorySlug=mc-mods&projectID=278785 that is causing this issue
