### ISSUE TITLE
Crash on world load/generation

### ISSUE THREAD

**Issue by MrTitainin** [Vazkii/Botania#2802]
# Version Information
Forge version: 1.12.2-forge1.12.2-14.23.2.2611
Botania version:  r1.10-358

# Further Information
Game crashes while loading particular singleplayer world (I may attach this save somewhere if it's needed). There are other mods used there, but crash log indicates it's Botania's fault. Problem first occured after updating botania from r1.10-353 (Quark and AutoRegLib were also updated around this time and Quark Oddities were added) and flying around for a while (probably fired chunk generation).
Other worlds I tested works fine.

Link to crash log: [here](https://gist.github.com/MrTitainin/247d4571c0dd6e5b2b889d7a79b194a9)

Steps to reproduce:
1. Run the world
2. Wait, typically until world starts to render
3. See crash information on launcher

What I expected to happen:
World loads/generates.
What happened instead:
Crash with return to launcher.

**Comment by williewillus** [comment]
update forge
