### ISSUE TITLE
Mana Pool Ticking Block Entity Error? in Stoneblock

### ISSUE THREAD

**Issue by Algester** [Vazkii/Botania#2805]
# Version Information
Forge version:  14.23.5.2768
Botania version:  Botania r1.10-357

# Further Information
Link to crash log: https://pastebin.com/puyJQ2gN

Steps to reproduce:
1. I "upgraded" the mana pools into the fabulous ones...
2. Stay around the area
3. and Crash

What I expected to happen:

not crashing so much

What happened instead:

Ticking Block Entity Error instead

**Comment by quat1024** [comment]
see #2205
