### ISSUE TITLE
Alchemy Array Shard of Laputa bypass

### ISSUE THREAD

**Issue by Shybella** [Vazkii/Botania#2806]
# Version Information
Forge version:  2768
Botania version:  Botania r1.10-356
Blood Magic version: BloodMagic-1.12.2-2.3.3-101

# Further Information

Steps to reproduce:
1. Place a alchemy array on the ground
2. Add Redstone then Lapis block
3. Creates the shard of laputa and bypasses claims
4. The alchemy array must be on the border of the claim

What I expected to happen: Works as intended but doesn't respect ftb claims or sponge plugin claims.

Again, not sure if this is the right place to open this but it seems to be related more to botania than blood magic.

Thank you

**Comment by quat1024** [comment]
Does this have anything to do with the alchemy array, or can you just put a Shard on the edge of a claim nornally?
