### ISSUE TITLE
Copy Item Bug Using Bauble Case or similar item

### ISSUE THREAD

**Issue by ExtraMeteorP** [Vazkii/Botania#2809]
# Version Information
Forge version:  14.23.4.2765
Botania version:  1.10-357

# Further Information
Forgive my poor english
1. Hold a Bauble Case with something inside
2. Press Q and right-click at the same time
3. Item was thrown but the gui is still
4. Shift-click to get the item
5. Press E to open the inventory to prevent the copied item from disappeared
6. Pick up the bauble case, then we will have double

in ContainerFlowerBag.java
`if(slot != null && slot.getHasStack() && canInteractWith(player))`
I think this may help

**Comment by williewillus** [comment]
I can't replicate with your instructions, which I'm a bit confused with. Can you record a video?

**Comment by ExtraMeteorP** [comment]
The bug has existed for a long time, so many chinese servers have banned them. 
![_rqgku](https://user-images.githubusercontent.com/10953378/50274250-bb35df00-0477-11e9-8131-eb6276d9cb22.gif)

**Comment by ExtraMeteorP** [comment]
![ezgif-2-76fb9b6299a9](https://user-images.githubusercontent.com/10953378/50274487-575fe600-0478-11e9-9f8d-2f770eddf714.gif)
sorry, this is the full version

**Comment by ExtraMeteorP** [comment]
i wonder when it will be fixed

**Comment by williewillus** [comment]
I still can't get it to happen

**Comment by Hubry** [comment]
From our testing when discussing on Discord, this does only happen in Creative mode (probably thanks to the client's authority thing on the inventory), where it doesn't matter. In survival mode, it appears to have duplicated the bauble until you try to move it or open the case normally, which refreshes the inventory to show no actually duplicated baubles.
