### ISSUE TITLE
Crash on Startup with Railcraft 1.12.2-beta-2

### ISSUE THREAD

**Issue by hayesj1** [Vazkii/Botania#2815]
# Version Information
Forge version: 1.12.2-14.23.5.2784  
Botania version: r1.10-354  

# Further Information
Link to crash log: [https://pastebin.com/WPxRuGwi](https://pastebin.com/WPxRuGwi)
Steps to reproduce:
1. Add Botania and Railcraft(1.12.2-beta2) to mods folder
2. Startup MC
3. Wait
4. Crash during loading

What I expected to happen:
MC should have loaded

What happened instead:
MC Crashed

I was going to post in Railcraft's issues, but I found a similar issue already there from a while back, where they determined Botania needed to update their use of RC's API:
 [https://github.com/Railcraft/Railcraft/issues/1398](https://github.com/Railcraft/Railcraft/issues/1398).

**Comment by williewillus** [comment]
railcraft support was removed in 355 since we heard the API wasn't stable yet, so you can fix this by updating botania

support will be readded once it's stable.
