### ISSUE TITLE
Mana tablet uncraftable?

### ISSUE THREAD

**Issue by jgirl13245** [Vazkii/Botania#2817]
# Version Information
Forge version:  8.0.99.99
Botania version:  r1.10-356

# Further Information
Using Botania through FTB Pyramid Reborn 3.1 modpack, worked previously with 3.0?
Issue does not cause a crash. Simply doesn’t work. 

What I expected to happen:
crafting a mana tablet
What happened instead:
Cannot craft at all. Item, with recipe, is not shown in JEI, though item itself can be found when used as ingredient (such as mana ring). Item recipe in the lexicon is empty icons.
Putting the required items in a crafting table as though to make it does nothing. 

Not sure I’m submitting this right as the link on the botania website to the page about how to report issues is 404 Errored.
Also submitted this to FTB bug forum, though it’s pending public display.

**Comment by Hallowizer** [comment]
I have seen the Mana Tablet crafted many times. I believe this is an issue within your modpack.

**Comment by williewillus** [comment]
does it happen with just botania? if not, it's an issue with the pack
