### ISSUE TITLE
Vine ball can place vines in a position where they immediately break

### ISSUE THREAD

**Issue by quat1024** [Vazkii/Botania#2819]
1. place a glass block 2 blocks above the ground (or something like a slab)
2. throw a vine ball at the side (or use the slingshot)
3. https://i.imgur.com/wdJHxnt.gifv

If you don't place it above the ground, you get a vine that disappears when you update it

bonitia 1.10-357 w/ forge 14.23.4.2705

**Comment by Brominarium** [comment]
Does the vine ball get consumed when you throw it at the slab?

**Comment by williewillus** [comment]
it's consumed when you throw it..
