### ISSUE TITLE
Botania r1.2-110 cannot craft/upgrade Band of Mana

### ISSUE THREAD

**Issue by sandalle** [Vazkii/Botania#282]
After updating to Botania r1.2-110 with Baubles 1.7.10-1.0.1.5 (modpack: http://www.technicpack.net/modpack/details/modderation-permabanned-edition.449941), I can no longer craft the Band of Mana nor upgrade to a Greater Band of Mana.

I've tried upgrading with an empty Band of Mana and one with full Mana. I tried making a completely new one to see if charging changes NBT, but I can't craft a new one. Other Baubles I seem to be able to craft (did not try Band of Aura). When trying to make a fresh Band of Mana, that is a fresh Tablet that has never been charged. Also tried charging it to full capacity, but no dice.

![2014-08-31_21 14 52](https://cloud.githubusercontent.com/assets/2447608/4111613/36b6b4c0-320d-11e4-9f46-27a3b7c7ab79.png)
![2014-08-31_21 16 28](https://cloud.githubusercontent.com/assets/2447608/4111614/36ba5b98-320d-11e4-8b92-c2d660bacf17.png)
![2014-08-31_21 13 51](https://cloud.githubusercontent.com/assets/2447608/4111612/36b597ac-320d-11e4-960b-8f809ce37979.png)
![2014-08-31_21 14 00](https://cloud.githubusercontent.com/assets/2447608/4111615/36bedfa6-320d-11e4-93f7-45e2dbc11429.png)

**Comment by gbradburn** [comment]
I hate to resurrect and old thread but with Botania 1.5.169 I cannot upgrade either the Band of Mana. I was able to upgrade the Band of Aura.

I believe I have completely drained the aura from this band (I threw it into a mana pool that was set to accept mana from items). The damage bar looks empty to me. I also tried to upgrade it when it was full. Based on this thread that shouldn't matter any more regardless.

Am I doing something wrong?

![2015-03-17_17 53 05](https://cloud.githubusercontent.com/assets/5175789/6698387/9d99e142-ccce-11e4-9cef-24919200f123.png)

Thanks,

Greg.

**Comment by MrKunji** [comment]
I've experienced this problem before. I had to empty the Band of Mana and put the Terrasteel Ingot to the left.

**Comment by Vazkii** [comment]
Not a bug, it's intended.

**Comment by gbradburn** [comment]
Okay. It wasn't totally empty. I completely emptied it and was able to
craft the upgrade.
Sorry for the false alarm.

On Tue, Mar 17, 2015 at 6:07 PM, Lizbeth Rika <notifications@github.com>
wrote:

> Not a bug, it's intended.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Vazkii/Botania/issues/282#issuecomment-82617300>.
>



-- 
beknown.com/greg-bradburn
