### ISSUE TITLE
Game load/generation crash

### ISSUE THREAD

**Issue by Venus96** [Vazkii/Botania#2828]
# Version Information
Forge version: 1.12.2-forge1.12.2-14.23.5.2807
Botania version: +r1.10-358

# Further Information
I've downloaded all the required mods for botania to their latest release, not the latest beta; 
I've downloaded the latest versions of forge and java;
I've deleted then re-downloaded every mod that the curseforge botania download page says is required;
I've removed all other unrelated mods and I've searched through a lot of this forum to try and find a solution to my problem without actually posting an issue but i'm at a loss.

Link to crash log : https://gist.github.com/Venus96/5d39d27172d58551fe08b0f56f656dff 

Steps to reproduce:
1. Load into minecraft
2. Create a new world/load into 1.12.2 world
3. Crashes after about 10 seconds of loading into new world

What I expected to happen:
Load into modded world
What happened instead:
Game crashed

**Comment by williewillus** [comment]
update forge
