### ISSUE TITLE
Some Coding Issue According to Caliper

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Vazkii/Botania#2831]
# Version Information
Forge version:  1.12.2 - 14.23.5.2808
Botania version:  Botania r1.10-358.jar

# Further Information
Recipes with Air

If a recipe has air in it as an ingredient or output it can cause many issues
such as crashes and uncraftable recipes.

Recipe: botany:ceramic_tile Class: public class binnie.botany.recipes.CeramicTileRecipe
Recipe: botany:pigment Class: public class binnie.botany.recipes.PigmentRecipe# Bad Version

Steps to reproduce:
1. Use Caliper
2. Load Caliper
3. Shows you a small coding oversight

What I expected to happen:
-

What happened instead:
-

**Comment by brainiac744** [comment]
Looks like those classes are part of Botany, not Botania. The bug tracker for Botany is here: https://bitbucket.org/binnie567/binnie-mods/issues

**Comment by P3rf3ctXZer0** [comment]
I don't have Botany installed I only have Botania...

**Comment by P3rf3ctXZer0** [comment]
ty
