### ISSUE TITLE
Enchanted Spellbinding Cloth deletes items

### ISSUE THREAD

**Issue by thenewdreamer** [Vazkii/Botania#2836]
Forge version:  14-23-5-2796
Botania version:  358

Attempting to disenchant an item using an enchanted spellbinding cloth will consume the item you're trying to disenchant and produce a second, unenchanted spellbinding cloth. This only happens if the cloth is placed before the other item in the crafting grid, and does not happen if placed afterwards or if the cloth is unenchanted

![image](https://user-images.githubusercontent.com/45403659/51816839-6b2c1280-2296-11e9-97e0-51534669b98e.png)

**Comment by TheWhiteWolves** [comment]
Not at home so can't check but its probably happening on [SpellClothRecipe L57](https://github.com/Vazkii/Botania/blob/master/src/main/java/vazkii/botania/common/crafting/recipe/SpellClothRecipe.java#L57), we look for the first enchanted item int he provided recipe but dont check that said item isnt the cloth itself.

Probably just need "&& stack.getItem() != ModItems.spellCloth" adding to the conditions.
