### ISSUE TITLE
Stateleak with pylon items

### ISSUE THREAD

**Issue by quat1024** [Vazkii/Botania#2850]
1. Put *one* of any pylon in your inventory.
2. Don't have any items positioned after it in your inventory.
3. Your offhand slot does this:
![image](https://user-images.githubusercontent.com/2068021/52621504-71fd7c80-2e75-11e9-8d82-1e05071b6b71.png)
If you pick up the item with your mouse while under a potion effect, the potion UI does this: 
![image](https://user-images.githubusercontent.com/2068021/52621611-c143ad00-2e75-11e9-926b-c204bdcc70d8.png)

Version / modlist is the same as in the current development instance, so this does include Thaumcraft.

**Comment by Hubry** [comment]
Checked and this happens with no Thaumcraft too.

**Comment by Hubry** [comment]
Still a thing in 1.14
