### ISSUE TITLE
Performance Issues with Exoflame, Hopperhock, Mana Spreaders, Elven Portal

### ISSUE THREAD

**Issue by Luke616** [Vazkii/Botania#2856]
Hello,

I've been running a server for a modpack with Botania in it and have been periodically performing CPU time profiles using the mod [LagGoggles](https://minecraft.curseforge.com/projects/laggoggles). I've noticed certain aspects of Botania setups being consistently expensive, and was wondering if there was any optimization you could do. Blocks which are frequently taking up a disproportionately high amount of CPU time include the Exoflame, Hopperhock, Mana Spreaders, and the Elven Portal block.

Here are some images to demonstrate what I mean:
![2019-02-13_05 36 34](https://user-images.githubusercontent.com/3951604/52741009-68bdfe00-2fa2-11e9-98ca-de61251f4bbc.png)
![2019-02-13_05 39 36](https://user-images.githubusercontent.com/3951604/52741156-b175b700-2fa2-11e9-836d-90935607db4f.png)
This is the absolute worst I've ever seen - usually exoflames cost around ~500us/tick after they are set up for a while which is still insanely high but this one block was singlehandedly responsible for around ~70% of the server lag that day.

![2019-02-06_14 35 49](https://user-images.githubusercontent.com/3951604/52741165-b89cc500-2fa2-11e9-965b-38e2b1c1a148.png)
Here is an expensive Elven Portal, pretty much all of the elven portals I've seen set up have a disproportionately high CPU cost.

![2019-02-06_02 48 08](https://user-images.githubusercontent.com/3951604/52741223-dcf8a180-2fa2-11e9-89dd-3e8282fd326d.png)
![2019-02-06_02 47 54](https://user-images.githubusercontent.com/3951604/52741228-df5afb80-2fa2-11e9-809a-cee14e332d06.png)
Hoping you could shed some light on this, I've noticed that some mana spreaders cost a high amount of CPU time but others work just fine. Not sure what is happening that causes some spreaders to cost ~5 us/t and others to cost ~500us/t, this is by far the most inconsistent but it seems every botania setup I've come across has one or two extra laggy spreaders.

I understand that its likely that there is little you could do about this in the short-term, but I was hoping that bringing these performance issues to your attention might give you some indication as to where the mod could be better optimized in the future.

Thanks!
-Luke616

# Version Information
Forge version: 14.23.5.2808
Botania version:  r1.10-359

# Further Information
Link to crash log: n/a
Steps to reproduce: 
1. Download Botania and a profiler of your choice
2. Make various botania setups
3. Profile CPU load to see what processes are using a lot of memory

**Comment by Hubry** [comment]
While LagGoggles is a fantastic tool for identifying issues, it's not really a substitute to a providing a profiler report. Could you provide one?

Either a VisualVM profiler snapshot (can be created with Player's [Sampler](https://minecraft.curseforge.com/projects/sampler) mod or with VisualVM itself), or a report link from the [spark](https://github.com/lucko/spark/blob/master/README.md) profiler would be fine.

For Spark, `/spark start --timeout 60 --include-line-numbers`, optionally with a lower interval, would be a nice starting point. For Sampler, `/sampler start`, then after a while `/sampler stop` and `/sampler export`, then providing the report here.

**Comment by Luke616** [comment]
Oh, thanks for showing me these tools - been mourning the fact that I couldn't profile with VisualVM itself since my server is offsite and did not realize there were tools to generate snapshots. I'll get you a proper profile report when I get a chance

**Comment by Luke616** [comment]
Alright, here's a snapshot. Hoping you can get some good info out of it, I did a profile using laggoggles right before and botania stuff really wasn't lagging as hard as it has in the past but there are certainly some hits.

[sampler-snapshot.zip](https://github.com/Vazkii/Botania/files/2864059/sampler-snapshot.zip)
![2019-02-14_02 47 16](https://user-images.githubusercontent.com/3951604/52775300-54631b00-300d-11e9-8034-a85926754adc.png)
This screenshot is from the laggoggles profile I took immediately before using sampler. I sampled for roughly 30 seconds. The 3 TileSpecialFlowers you see at the top all pointed to Pure Dasies in different people's homes, each were already surrounded by 8 livingwood/livingstone which had yet to be removed. The TileFloatingSpecialFlowers were all exoflames, I've seen them reach much higher CPU time than in the profile above but hopefully this helps somewhat. Next time I see an exoflame flip out like in the screenshot from the main post I'll be ready with sampler installed to catch it for you though!

Thanks again for looking in to this!

**Comment by bigenergy** [comment]
UP
