### ISSUE TITLE
Botania 1.10.2 issue - Searching for something induces a crash where its log includes something about Gaia Head?

### ISSUE THREAD

**Issue by a1m3ndr4** [Vazkii/Botania#2866]
Here, I showcase info about a crash that may be threatening 
# Version Information
Forge version: Forge 12.18.3.2185 (1.10.2... like you would expect)
Botania version: In Curseforge, I downloaded (and used) Botania r1.9-341. It ran on 1.10.2, like the title said.

# Further Information
Link to crash log: https://gist.github.com/a1m3ndr4/ab4679757d7a4b81b7f8fc2702876e30
Steps to reproduce:
1. Search "Gaia Head", or a part of it (gaia, head)
2. This also works with only "G" or "H". I also tried "D" and it worked. (What you notice about this message is that inputting almost any letter in the name "Gaia Head" works.)
3. Great job, you now have your Gaia Head-related crash.

What I expected to happen: Nothing. I was expecting to go through the Creative menu without crashing.

What happened instead: Minecraft froze with a blank screen, then crashed. I searched the crash log for information, and it seemed to say something about the item "Gaia Head".

**Comment by williewillus** [comment]
does it happen with botania alone? there's something screwing with the render view entity. also this is 1.10, which is no longer receiving updates, so I'll close this. But it's probably a cross mod thing.
