### ISSUE TITLE
When you put a Botania flower in a vanilla pot, you get the miscellaneous Botania flower

### ISSUE THREAD

**Issue by Tamarutoe** [Vazkii/Botania#2869]
# Version Information
Forge version:  
Botania version:  

# Further Information
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)\
Steps to reproduce:
1. First step
2. Second step
3. etc...

What I expected to happen:

What happened instead:

**Comment by quat1024** [comment]
Putting non vanilla flowers in a flowerpot is neither a vanilla nor a Botania feature.

And the issue template isn't just for decoration...
