### ISSUE TITLE
Why the Alfheim Portal can explode when a player throw a bread?

### ISSUE THREAD

**Issue by mcBegins2Snow** [Vazkii/Botania#2871]
# Version Information
Forge version:  14.23.5.2815
Botania version:  r1.10-359

# Further Information
[The Alfheim Portal's Botania FTB wiki](https://ftb.gamepedia.com/Portal_to_Alfheim) said:
`Inserting Bread will cause a small explosion, destroying most of the portal frame.`
I wonder if this feature is an easter egg, a bug, or a meme.

**Comment by SquidDev** [comment]
https://github.com/Vazkii/Botania/blob/ff834dc823e740eca600b745f764e8f30019f6b7/src/main/java/vazkii/botania/common/block/tile/TileAlfPortal.java#L194

[Teleporting bread is a bad idea](https://www.youtube.com/watch?v=NE1-dKc6R_I).

**Comment by williewillus** [comment]
It's a meme, from the TF2 video linked above

**Comment by ProxyPlayerHD** [comment]
It's not a TF2 reference, it's a reference to issue #2403 (even says it in the code)

**Comment by williewillus** [comment]
It can be both, I'm a dev, I can say it's whatever I want :P . Is there something to add by necroing this two-year-old ticket?

**Comment by ProxyPlayerHD** [comment]
oh i'm sorry i didn't look at the dates, i was just googling for the meme and came across this issue.
