### ISSUE TITLE
Paintslinger Lens doesn't color Concrete or Concrete Powder

### ISSUE THREAD

**Issue by gamma-delta** [Vazkii/Botania#2872]
# Version Information
Forge version:  14.23.5.2814
Botania version:  r1.10-360

# Further Information
Steps to reproduce:
1. Place some concrete, concrete powder, and wool (as a control) on the ground.
2. Fire at each with a Paintslinger Lens.
3. The wool changes color to match the lens, but the concrete and powder don't.

What I expected to happen: Concrete and Concrete powder should change to match the lens color along with wool

What happened instead: Only wool changed color; concrete and powder remain the same.

**Comment by ToMe25** [comment]
This got closed for being stale, but i fixed it already.
Should be in the next update.
