### ISSUE TITLE
Shard of Laputa and gravity affected blocks

### ISSUE THREAD

**Issue by chaosblad3** [Vazkii/Botania#2874]
When using the Shard of Laputa in a desert or sandy beach etc, the fact that the Shard works one block at a time from top to bottom with each slice of land it moves, means that if a block it moves in each column is a block affected by gravity (Sand/Gravel) it moves it up but it immediately falls before it has a solid block below it for it to sit on, ideally the Shard should intelligently scan each block before it moves it and in case of a gravity affected block, place a temporary solid block below where it is about to be moved, then replace the temporary block when it tries to move the next block in the column into that spot so that way each gravity affected block always has a solid block below it at every stage in the process. 

Also it might be a good idea to reverse the order from top->bottom to bottom->top (so instead leave  a temporary block behind when moving a solid block if the next block up is a gravity affected block then remove any temporary blocks when it gets to the end of that column) that way it would be able to move up other things that rely on having a block below them (plants/crops/etc) after moving the grass layer at the top. 

See screenshot for example: https://imgur.com/a/GHozsmE
Note that the front should have 3-4 layers of sand there but instead they dropped into the hole the Shard left.

This is just a suggestion btw but perhaps you could also add a new feature where you can craft a Shard of Laputa with a Rod of Terra Firma + Rod of the Lands + Rod of the Depths + a full Mana Tablet to create an empowered Shard that instead of just moving every block up into the sky, it leaves behind an mundane block (dirt/cobble) in place of the original, that way people can make floating islands without leaving behind a big hole in the ground!

# Version Information
Forge version:  14.23.5.2815
Botania version:  r1.10-360

# Further Information
Steps to reproduce:
Use a shard anywhere with sand/gravel

What I expected to happen:
Sand/Gravel moved up with the rest of island.

What happened instead:
Sand/Gravel dropped back down before a solid block was moved up below them for it to sit on.

**Comment by f-raZ0R** [comment]
This is still an issue, but I don't see how it would get fixed without a complete rewrite of the shard.
