### ISSUE TITLE
Bore Warp lens can still wirelessly send mana

### ISSUE THREAD

**Issue by quat1024** [Vazkii/Botania#2877]
Botania version r1.10-359

When a Warp lensed mana burst travels through a force relay, it is not supposed to be able to fill a mana pool, the burst just disappears. (this was added to nerf easy wireless mana transport)

However, Bore Warp lenses are excluded from this rule.

![image](https://user-images.githubusercontent.com/2068021/55031569-3eba1b80-4fe5-11e9-92af-a5c25178e04d.png)

**Comment by TheWhiteWolves** [comment]
I suspect something has probably changed with the entities since this was originally introduced in 1.10 making [L50 in LensWarp.java](https://github.com/Vazkii/Botania/blob/master/src/main/java/vazkii/botania/common/item/lens/LensWarp.java#L50) evaluate as false everytime.

**Comment by ElectronicRU** [comment]
Checked this on r1.10-361: any Composite X Warp can do that. That's because [the code for getManaToTransfer](https://github.com/Vazkii/Botania/blob/fb8ebd8ca7e4dd24a1c93bf2a92ea4f93fee98fe/src/main/java/vazkii/botania/common/item/lens/ItemLens.java#L311) doesn't actually check for composite lens.
