### ISSUE TITLE
Armors are ignored in some other mods' calculations (includes fix)

### ISSUE THREAD

**Issue by MoriyaShiine** [Vazkii/Botania#2882]
# Version Information
Forge version:  Any
Botania version:  Any

# Further Information
Steps to reproduce:
1. Put on any of the mod's armors
2. See your armor increase
3. Find out that mods such as Astral Sorcery and Monk ignore the armor value because of ISpecialArmor and are incredibly overpowered

How to fix:  
  In ItemManaSteelArmor, return 0 in ISpecialArmor#getArmorDisplay()
  In ItemManaSteelArmor, delete the override of ItemArmor#getAttributeModifiers()
  On line 63 of ItemTerrasteelArmor, instead of using getArmorDisplay(), use damageReduceAmount

**Comment by williewillus** [comment]
> because of ISpecialArmor and are incredibly overpowered

not sure what this means.

**Comment by MoriyaShiine** [comment]
In Astral sorcery, there's a player infusion that removes all armor points and converts it into health. With armor like Botania's current one, it gives you the extra health but doesn't remove the armor, I'm assuming because it removes the attribute which doesn't exist anyway and it gets player total armor.

The Monk mod has things that only activate if you have no armor, same effect, Botania armor doesn't trigger that.
