### ISSUE TITLE
Crash related to the ring of magnetization and Extra Utilities 2’s angel ring

### ISSUE THREAD

**Issue by Dimentive** [Vazkii/Botania#2883]
#### Versions
* **Modpack:** [Enigmatica 2](https://minecraft.curseforge.com/projects/enigmatica2) (version [1.63a](https://minecraft.curseforge.com/projects/enigmatica2/files/2691579), latest)
* **Minecraft:** 1.12.2
* **Forge:** 14.23.5.2781
* **Botania:** [r1.10-360](https://minecraft.curseforge.com/projects/botania/files/2677096) (latest)
* **Baubles:** [1.5.2](https://minecraft.curseforge.com/projects/baubles/files/2518667) (latest)
* **Extra Utilities 2:** [1.9.9](https://minecraft.curseforge.com/projects/extra-utilities/files/2678374) (latest)

#### Further Information
I’m using Botana’s ring of magnetization and the angel ring from [Extra Utilities 2](https://minecraft.curseforge.com/projects/extra-utilities), and my game crashed when I broke a cable from Applied Energistics 2. This crash has only occurred once.

Crash report: https://pastebin.com/raw/v26TMpFA

_java.util.concurrent.ExecutionException: java.lang.ClassCastException: com.rwtema.extrautils2.items.ItemAngelRing cannot be cast to baubles.api.IBauble_

**Comment by Dimentive** [comment]
Comment.

**Comment by Hubry** [comment]
Looks like this was fixed by #3044. I am not sure how it exactly happened in your case (did you try to swap baubles by accident there?), and in 1.14 we no longer handle right clicking baubles ourselves.
