### ISSUE TITLE
[Game Crash] Loading a chunk with a mana pool is crashing my game

### ISSUE THREAD

**Issue by Furtie-Hubo** [Vazkii/Botania#2884]
# Version Information
Forge version:  14.23.5.2768
Botania version:  r1.10-360

# Further Information
Link to crash log: https://gist.github.com/Furtie-Hubo/c06a50e51daf4c27e02690afdfb5e67e
Steps to reproduce:
1. Go away to unload the chunk with the mana pool
2. Go back
3. As soon as the chuck is loaded, my game is crashing

Could an exception fix this problem?

**Comment by williewillus** [comment]
redirect to #2205, if you're using voxelmap it's causing unsafe access to the world
