### ISSUE TITLE
Rod of the Shifting Crust crush using chisel blocks

### ISSUE THREAD

**Issue by Cri16228** [Vazkii/Botania#2886]
# Version Information
Forge version:  14.23.5.2808
Botania version:  Botania r1.10-360

# Further Information
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)\
The error log part: https://gist.github.com/Cri16228/ebd462dd7c87c97a3f7b33b49d6dcffd
The whole log (16000+ lines): https://gist.github.com/Cri16228/d4e2f46c0e1919c010cd1ed86e154bbe

A little info: I'm playing [Modern Skyblock 3 Departed](https://minecraft.curseforge.com/projects/modern-skyblock-3-departed) and I have my world broken, I'll reroll it. Since its a curse modpack the version is not the last also because the last one is posted less than 24 hours ago (taking the post date and time).

Steps to reproduce:
1. Craft/Take the Rod of the Shifting Crust in creative
2. Use a random chisel block (I used a cobblestone version) 
2.1 Tried with vanilla cobblestone and it crash
3. Shift-right-click the block
4. Crash

What I expected to happen:
Select the block to use it to replace other blocks
What happened instead:
Crashed and broken my save

**Comment by Hubry** [comment]
Some mod you have installed repacks Botania's API classes from an ancient version, and the game loaded them instead of the proper up to date ones. Same thing applies to your other report. If you can, try to find out which mod contains the `vazkii.botania.api.mana.IManaDiscountArmor` class and report it to them, deleting the API from that mod's jar would fix this crash.

**Comment by Cri16228** [comment]
> Some mod you have installed repacks Botania's API classes from an ancient version, and the game loaded them instead of the proper up to date ones. Same thing applies to your other report. If you can, try to find out which mod contains the `vazkii.botania.api.mana.IManaDiscountArmor` class and report it to them, deleting the API from that mod's jar would fix this crash.
> 
> Honestly it seems like it's time to check the mod jar that loaded those classes and hard-crash if found, like Redstone Flux does in 1.12, of course with a bypass method. It's been like two years since this class was changed.

I saw now the modpack page again and.. this modpack contains "Avaritia 1.12 version" and "Avaritia-1.13" but 1.7.10 version
Is that even possible? As far as I know its impossible for forge load an old version of the mod or it crashes.
Thanks for your help
