### ISSUE TITLE
Mana Enchanter Doesn't Use Apotheosis Tomes As Valid Enchanting Book

### ISSUE THREAD

**Issue by Numorphan** [Vazkii/Botania#2896]
# Version Information
Forge version:  2836
Botania version:  r1.10-361
Apotheosis version: 1.9.3

# Further Information
Steps to reproduce:

1. Place any number of apotheosis tomes (of the right type) in the mana enchanter.
2. Activate the mana enchanter.
3. Nothing happens.
4. Add a regular book.
5. Activate it.
6. The regular book's first enchant will be applied, with all the tome's enchants ignored.

What I expected to happen:

The mana enchanter should treat the tome as a regular enchanted book.

What happened instead:

When using an Apotheosis tome (of Helmets, Weapons, etc) in the Botania mana enchanter, the mana enchanter will ignore the tome and not apply the enchant to the central item.

(https://github.com/Shadows-of-Fire/Apotheosis/issues/40)

**Comment by williewillus** [comment]
there's no way to really tell if something is an "enchanted" book without hardcode checking for the vanilla one.

**Comment by quat1024** [comment]
The Apotheosis book happens to extend `ItemBook` so you could *mayyyybe* check for `|| item.getItem() instanceof ItemBook`
