### ISSUE TITLE
Gaia Guardian ritual not workng

### ISSUE THREAD

**Issue by mrdeadlocked** [Vazkii/Botania#2897]
# Version Information
Forge version:  14.23.5.2836
Botania version:  r1.10-361
Modpack: Dragons Dungeons and Space Shuttles (https://minecraft.curseforge.com/projects/dungeons-dragons-and-space-shuttles 4.11a)

![2019-04-27_12 59 49_2](https://user-images.githubusercontent.com/461352/56852809-b2558e00-68ed-11e9-8831-811ac24aa88b.png)

# Further Information
Steps to reproduce:
1. Setup Gaia Ritual
2. Try to summon

What I expected to happen:
Gaia Guardian spawns

What happened instead:

Ritual says cannot make

**Comment by mrdeadlocked** [comment]
It appears that my previous arena layout does not meet the new stricter criteria. I had to lower the beacon/pylons down one. Sorry for this bad report. :-)

**Comment by williewillus** [comment]
@quat1024 should this have happened?

**Comment by quat1024** [comment]
I've seen a bunch of people on reddit with the same problem. I'll change it. I didn't account for the floor being 1 lower than how I and everyone else I play with builds an arena tbh :sweat_smile:
