### ISSUE TITLE
Terra shatteterer breaking when out of mana

### ISSUE THREAD

**Issue by mrdeadlocked** [Vazkii/Botania#2900]
Forge version: 14.23.5.2836
Botania version: r1.10-361
Modpack: Dragons Dungeons and Space Shuttles (https://minecraft.curseforge.com/projects/dungeons-dragons-and-space-shuttles 4.11a)

Is it intended for terra shatterer to break when out of mana and durability goes to zero? I did this on SSP and SMP testing.

http://falseprovince.com/broken.gif

**Comment by williewillus** [comment]
yes, the pickaxes are all normal tools that have durability, and will break.
durability is first consumed from mana, then from the tool's real durability.
available mana also goes to repair the tool.

so make sure you have mana at all times.
