### ISSUE TITLE
Texture(Model) error

### ISSUE THREAD

**Issue by SettingDust** [Vazkii/Botania#2901]
# Version Information
Forge version:  1.12.2 14.23.5.2815
Botania version:  r1.10-361

# Further Information
![xxx](https://i.imgur.com/5al3bGW.jpg)

**Comment by williewillus** [comment]
mod list? does it happen with just botania?

**Comment by SettingDust** [comment]
> mod list? does it happen with just botania?

I removed one by one. It appeared with the [Mo'Bends](https://minecraft.curseforge.com/projects/mo-bends)
