### ISSUE TITLE
Forestry Saplings & Rannuncarpus

### ISSUE THREAD

**Issue by moller21** [Vazkii/Botania#2905]
# Version Information
Forge version: 14.23.5.2835
Botania version: r1.10-361
Forestry: 1.12.2-5.8.2.387

# Further Information
Rannuncarpus is not able to put down saplings from Forestry. It's probably a Forestry creating a special block for the saplings since you can put torches on them aswell, but wanted to report it here in case you wanted to add support for them. 

Mana bursts with the bore lense does also break these sapling (doesn't break normal ones.)

**Comment by quat1024** [comment]
> since you can put torches on them aswell

`getBlockFaceShape` claims another victim
