### ISSUE TITLE
(Easter egg??) Anime Reference idea that would be fitting for this mod! (Not a bug not a crash)

### ISSUE THREAD

**Issue by SirAron111** [Vazkii/Botania#2910]
OK here is the thing Since this text was too long for a PM and Curse flagged it as Spam I do it like this but I think having these Easter eggs a bit secret is better XD.
 
I love the Botania Mod since it first came out. Especially the ever so growing anime and game references.

The desugun brought me to a funny idea for a new one that defo needs to be in this mod as it already has all needed things to make it possible.

Kono Subarashii Sekai ni Shukufuku o!  The Character Megumin who only uses one super overpowered spell that depletes her mana for the day, EXPLOSION!!! etc. I bet you know it anyway.

You need to make it so that if you rename a Manastorm Charge to “EXPLOSION!” and then put it in a full mana pool it will drain the pool of all its mana and become a powered up version of a mana charge XD basically making a huge super huge explosion like the chaos guardian island one or the one from the Oblivion Deathbomb from abyssalcraft.

 I mean it shouldn’t be too hard to program or anything as most of the parts needed are already there and I think this would be a super fun little Easter egg for endgame botania fitting in since the components to drain all mana from the character (drain a full mana pool), EXPLOSION! …explosions being key to minecraft base game and so on.

Let me know what you think of this idea at least even if you don’t put it in.

GZ
SirAron

**Comment by williewillus** [comment]
leave suggestions on the subreddit
