### ISSUE TITLE
Duplication Glitch involving Petal Apothecary

### ISSUE THREAD

**Issue by saokyy** [Vazkii/Botania#2911]
# Version Information
Forge version:  14.23.5.2836
Botania version:  r1.10-361

# Further Information
I'm playing in the modpack Dimension Zero from the Twitch Launcher

Steps to reproduce:
1. Place a Petal Apothecary down and fill with a water source.
2. Throw an item from within the inventory screen so it lands both inside the apothecary and on the floor.
3. Break the apothecary before the item on the floor disappears.
4.  You will get the original stack+1

I expected to happen:
To get all the original items back

What happened instead:
Got the original amount +1.

# Note:
I managed to double a stack of petals last night accidentally which led to me discovering this bug, but since then, I've only been able to get the original stack +1.

Also, I don't use github so if you would like to contact me for further information my discord is: saokyy#5444

**Comment by williewillus** [comment]
> Throw an item from within the inventory screen so it lands both inside the apothecary and on the floor

how exactly does one get this to happen?
