### ISSUE TITLE
Bore lenses randomly misfire when player collides with the bursts

### ISSUE THREAD

**Issue by tlagore** [Vazkii/Botania#2914]
# Version Information
Forge version:  Forge-14.23.5.2821
Botania version:  Botania r1.10-360
Modpack: Direwolf 20 1.12

# Further Information
Steps to reproduce:
1. Build tree farm as seen in this screenshot: ![Tree farm](https://user-images.githubusercontent.com/16272842/58680829-7499ba00-831e-11e9-97b9-4502f620d8ab.png)
2. Run in between where the trees are being planted, collide with mana bursts from spreaders with bore lens
3. bore lenses will destroy nearby blocks, usually down 1 level , but also on the same level not in their line of site.
4. See this screenshot for where they destroyed blocks not in their line:
![BotaniaSplosions](https://user-images.githubusercontent.com/16272842/58681007-449ee680-831f-11e9-992d-4f68bd760cf1.png)

What I expected to happen:
Bore lenses shoot in a straight line away from where the spread is set

What happened instead:
If the farm is left alone entirely, the bore lenses respond as expected. When the player walks into/around the mana bursts, they will often redirect and shoot blocks that are not in their line of sight.

**Comment by williewillus** [comment]
anyone wearing a tiny planet or other thing that messes with bursts?

**Comment by tlagore** [comment]
No, the majority my Botania is coming from this setup.

Of the Botania items

**Player is wearing:**
- Cirrus Amulet
- Ring of the Mantle 
- Greater Band of Mana
- Soujourner's Sash
- Full Terra steel

**In Inventory:**
- Terra shatterer 
- Terra blade
- Wand of the forest
- Lexica Botania

**External Botania stuffs**
- All mana gen is done through endoflames through a setup of hopper, open crate, pressure plate and redstone.
- All charcoal is built by cooking wood from the farm using exoflames connected to the same network.
- There is an Alfheim portal which was closed when the issues happened
- Most mana distribution is with elven mana spreaders and mana splitters with sparks

**Comment by williewillus** [comment]
can you upload a minimal creative flat world with the contraption that reproduces the issue? that'd be great

**Comment by tlagore** [comment]
Will try to get to this soon, thanks

**Comment by tlagore** [comment]
This is the approximate setup:
[New World.zip](https://github.com/Vazkii/Botania/files/3242608/New.World.zip)

I was successful in reproing the issue. With no items on, the issue would not occur. I then equipped:
- Terra steel helm/pants/chest (not boots)
- Cirrus amulet
- Greater band of mana
- Ring of the mantle
- Soujourner's sash

I proceeded to double jump around the setup, walking over all parts of it. Eventually the blocks started getting uprooted (not destroyed, as I was able to pick up the blocks).

Note that I believe that this happened prior to getting ring of the mantle and greater band of mana (was a regular band of mana at the time). 

It seems this has something to do with the double jump mechanism of the cirrus amulet, I will try to repro with minimal equipped gear.

**Comment by tlagore** [comment]
Repro'd wearing only band of the mantle with regular band of mana in inventory, I believe this bug is to due with ring of the mantle. With enough jumping around the setup, it basically destroys everything within a +-1 (y) block of the spreaders that are shooting the bursts. 

![2019-05-31_12 31 28](https://user-images.githubusercontent.com/16272842/58730142-275e2c80-83a0-11e9-89ca-8a1625d5f07e.png)

**Comment by Hubry** [comment]
So, some mod (I don't know which one) adds a projectile reflection effect to the Haste potion effect, and mana bursts count as projectiles, so this is basically a "works as intended".
