### ISSUE TITLE
Crash upon summoning Gaia Guardian 

### ISSUE THREAD

**Issue by Maitredetoi** [Vazkii/Botania#2920]
# Version Information
Forge version:  1.12.2-14.23.5.2838
Botania version:  Botania+r1.10-361

# Further Information
Link to crash log: (https://gist.github.com/Maitredetoi/bbc71abe7c3c3b9dcb0175fbf877ab0a), 
I've removed all mods besides botania and it's dependancies. 

Steps to reproduce:
1.Summon Gaia Guardian
2.Watch him Spawn 

What I expected to happen:
Begin Battle
What happened instead:
Entire Screen Turns sky blue then crashes.

**Comment by Hubry** [comment]
Can you post the entire game debug log as well?

**Comment by Maitredetoi** [comment]
Removing Albedo from my modpack resolved this issue. It's listed as a
dependency in curseforge.

**Comment by TheElementalOfCreation** [comment]
It seems to have something to do actually with the static effect of it. I am having the same issue, so here are my logs:
[2019-08-24-1.log.gz](https://github.com/Vazkii/Botania/files/3537717/2019-08-24-1.log.gz)
[2019-08-24-2.log.gz](https://github.com/Vazkii/Botania/files/3537718/2019-08-24-2.log.gz)
[debug-1.log.gz](https://github.com/Vazkii/Botania/files/3537719/debug-1.log.gz)
[debug-2.log.gz](https://github.com/Vazkii/Botania/files/3537720/debug-2.log.gz)

**Comment by Bulldogg6404** [comment]
I can also confirm this issue and I agree with the aforementioned details: the error occurs immediately after the Guardian of Gaia finishes loading, causing the game to crash. I can reload Minecraft and open the world again, and the Guardian of Gaia is there, but attacking it or despawning and resummoning it causes the game to crash again. I, too, suspect the problem to be related to the Guardian of Gaia's TV static animation/shader. Following Maitredetoi's suggestion,, removing the Albedo dependency from the modpack allows the Guardian of Gaia to be summoned, fought, and killed without issues.

Versions:
Minecraft 1.12.2
Forge 14.23.5.2838
Botania r1.10-361
Albedo 1.1.0
