### ISSUE TITLE
MP - Charm of the Diva makes Gaia Guardian healing

### ISSUE THREAD

**Issue by Sewef** [Vazkii/Botania#2921]
# Version Information
Forge version:  14.23.5.2837
Botania version:  1.10.361

# Further Information
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)\
Steps to reproduce:
1. Get a Charm of the Diva
2. Summon Gaia (normal or hard)

What I expected to happen:
Nothing special

What happened instead:
Gaia set itself full life randomly after teleporting. Makes it almost impossible to kill (needs luck and OP weapons).
Tested with 1 and 2 players on dedicated server.

**Comment by MrTitainin** [comment]
I second this. Also Flügel Tiara seems to heal the Enderdragon. It might be a feature, but I can't find information about it anywhere.
