### ISSUE TITLE
Unlocalized block names when using vanilla's "Can be placed on" thing for Adventure Mode

### ISSUE THREAD

**Issue by aaronhowser1** [Vazkii/Botania#2928]
# Version Information
Forge version:  14.23.5.2836
Botania version:  Botania r1.10-361

What I expected to happen:
It should say that it can be placed on Infused Grass and Livingwood

What happened instead:

![2019-06-16_11 09 29](https://user-images.githubusercontent.com/15698722/59566547-583c9380-9027-11e9-9684-13495640c51f.png)

**Comment by williewillus** [comment]
botania handled localization pretty weirdly in 1.12. Not a problem anymore in 1.14 thanks to the flattening, but wontfix in 1.12.
