### ISSUE TITLE
Crash at world load due to PropertyBool with MobGrindingUtils' Fan

### ISSUE THREAD

**Issue by Chupp4-Jo3** [Vazkii/Botania#2934]
No idea what's going on here:

`java.lang.IllegalArgumentException: Cannot get property PropertyBool{name=powered, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in BlockStateContainer{block=botania:redstringcontainer, properties=[facing]}`

For clarity the crash happens when I open the world not at MC launch

https://pastebin.com/SUiHbhMR

MC: 1.12.2
forge: 14.23.5.2838
MobGrindingUtils-0.3.13
Botania: r1.10-361

Same issue I posted [here](https://github.com/vadis365/Mob-Grinding-Utils/issues/126) haven't heard anything back but I'm not sure if it's Botania or MGU

**Comment by codycoolwaffle** [comment]
What was being done in-game to produce this?

**Comment by Chupp4-Jo3** [comment]
Not sure, I'm looking now with MCEdit (I've changed the title to better describe the issue) but I'll attach a compressed copy of the world file as well in case that helps but I can't find anything helpful myself. The thing is, I don't think a redstring block of any kind has been placed in the world so I'm not sure why it's started giving blocks redstring properties.

**Comment by Chupp4-Jo3** [comment]
Okay deleted the fan in the crash and I get the same issue with the other fan and I'm sure that one definitley wouldn't have any redstring blocks so.... yeah. xD

**Comment by williewillus** [comment]
see https://github.com/vadis365/Mob-Grinding-Utils/issues/126

**Comment by Chupp4-Jo3** [comment]
Thanks for figuring this out! :D
