### ISSUE TITLE
(Progression limiting) The Gaia Guardian cannot be summoned

### ISSUE THREAD

**Issue by Hyxaru** [Vazkii/Botania#2935]
# Version Information
Forge version:  14.23.5.2836
Botania version:  r1.10-361
Other mods: Baubles & AutoRegLib

# Steps to reproduce:
1. Create a default superflat world
2. Assemble a Gaia ritual site, as per the book's instructions. Placed directly on or slightly in the ground.
3. Attempt to insert the catalyst.

What I expected to happen:
The Gaia Guardian spawns.

What happened instead:
"As hard as you try, the Beacon will not accept your sacrafice. You believe the ritual grounds might be improper. It might be a good idea to check for obstructions in the nearby area or large gaps in the floor.
![2019-06-19_19 21 41](https://user-images.githubusercontent.com/11833817/59786421-8213e580-92c7-11e9-8ff7-62ef161b7675.png)

**Comment by ito725** [comment]
the red dots tell you the missing blocks you need to fill in.

move beacon 1 layer lower is easiest fix though, (possibly pylons too.)

**Comment by Hyxaru** [comment]
That will not do it. I tried that before.
