### ISSUE TITLE
Rain Flowers, Snow Flowers CRASH

### ISSUE THREAD

**Issue by DrTHC** [Vazkii/Botania#2937]
So we can place the flowers down behind the block as soon as it rains or snows the server crashes.. i will put a crash report below. 
# Version Information
Forge version:  1.12.2-14.23.5.2836
Botania version:  r1.10-361

# Further Information
https://gist.github.com/DrTHC/823629025dd7b998b4750ef76b14074e
Steps to reproduce:
1. First step
Put flowers down
2. Second step
Set it to rain or snow
3. as soon as rain or snow particle hits flower it forces a crash!

What I expected to happen:

What happened instead:

**Comment by MelanX** [comment]
The crash is caused by Bontanic Additions
