### ISSUE TITLE
Bad mod with null item results in Resolute Ivy crash upon death

### ISSUE THREAD

**Issue by noobanidus** [Vazkii/Botania#2939]
# Version Information
Forge version:  2838
Botania version:  

# Further Information
Link to crash log: https://pastebin.com/nYtAbkVR
Steps to reproduce:
1. ???
2. Profit?

Potentially related to [this](https://github.com/Vazkii/Quark/issues/1345) Quark issue with a previous version of the server that somehow introduced a null item into the chain (which should only ever be ItemStack.EMPTY, as far as I'm aware, so it's definitely another mod breaking the contract). However, I'm unable to track down exactly which item is responsible. 

What I expected to happen:

What happened instead:

**Comment by gchpaco** [comment]
I've done some more work with this and can reproduce this with just Quark Oddities and the 1.9.6 version of ToolBelt.  I'm going to attack the ToolBelt side, but this might be worthwhile to make Botania robust against people doing really dumb stuff?

**Comment by duely** [comment]
It's unfortunately not limited to just Botania, I was going to most likely close the issue as nothing should really be adding a null drop... I'll leave it up to the maintainers as to whether or not it's something they want to implement meanwhile I'll be do a mass-decompile to search for bad drops.
