### ISSUE TITLE
Corporea Index in-inventory request adds history entries to chat

### ISSUE THREAD

**Issue by samuelxyz** [Vazkii/Botania#2942]
I am strongly of the opinion that this should not be intended behavior. This occurs even when the Corporea Index does not have a Corporea Spark on it, which is definitely a bug.

(By "history entries" I mean the list of previously typed chat messages and commands, accessed by pressing the up arrow key in the chat interface. )

# Version Information
Forge version:  1.12.2-14.23.5.2838
Botania version: R1.10 361

# Further Information
Steps to reproduce:
1. Have your inventory open within the area of effect of a Corporea Index.
2. Hover over an item in your inventory.
3. Press the "Corporea Request" key (default `C`).
4. Exit your inventory and open chat.
5. **Press the up arrow to view your chat input history.**

What I expected to happen:
The previous text that the player entered into chat should appear.

What happened instead:
Text such as `1 Cobblestone` appears.

**Comment by Hyper-Miiko** [comment]
I think the shortkey to request an item within corporea area do just one thing : 
Write the proper command in the chat to request the item.

Idk if we can call it a bug, some people would appreciate this "feature?".

**Comment by samuelxyz** [comment]
Yes, I can see how it might be useful in some limited circumstances. However, one of the main reasons I use the shortkey in the first place is to avoid cluttering the chat input history, because I need to be typing other repetitive messages in the meantime (like using commands while testing or map-building). I am still strongly of the opinion that it would benefit from being a config option at least.
