### ISSUE TITLE
passive decay

### ISSUE THREAD

**Issue by PiikaPops** [Vazkii/Botania#2944]
Hi , I don't know how to disable passive decay on hydroangeas in minecraft 1.12.2 (FTB Present Direwolf20 v2.5.0)

**Comment by TheMadmanofChaos** [comment]
The answer is simple: You don't. Passive decay is there in order to push you to use other generation flowers and automate them for mana production.

**Comment by PiikaPops** [comment]
okay , it's sad that this config is deleted , it's our own choice but okay

**Comment by macks2008** [comment]
To be fair, it's also your choice whether you want to play the mod or not as is. If you want a change badly enough, fork it, find the line of code that makes it happen, tweak, and build

**Comment by williewillus** [comment]
@macks2008 please stop bumping months-old issues with pointless comments

**Comment by macks2008** [comment]
my apologies...
