### ISSUE TITLE
Display bugs in Wand of the Forest and in the Lexicon pages

### ISSUE THREAD

**Issue by TheDirectorX** [Vazkii/Botania#2948]
# Version Information
Forge version:  14.23.5.2838
Botania version:  r1.10-361

# Further Information

- [ ] **Small rendering bug at Wand of the Forest.**
![image](https://user-images.githubusercontent.com/43481085/62427428-3947ad00-b70c-11e9-8e1c-9b2cfa41bab2.png)

- [ ] **Error displaying working Botanical Brewery with Wand of the Forest on Mana Spreader.** https://github.com/Vazkii/Botania/issues/2141
![2019-07-31_23 22 58](https://user-images.githubusercontent.com/43481085/62428083-d90a3880-b716-11e9-90b4-68d40c55da5c.png)

- [ ] **"Format error" on the Challenges page.**
![2019-08-04_23 39 08](https://user-images.githubusercontent.com/43481085/62427761-664a8e80-b711-11e9-86dc-1e4ee9deea29.png)
**Fix:** 100% > 100%%
https://github.com/Vazkii/Botania/blob/5d2f404a77c6a0cc2e5b8c2911f0775cbc80d2ec/src/main/resources/assets/botania/lang/en_us.lang#L634
https://github.com/Vazkii/Botania/blob/5d2f404a77c6a0cc2e5b8c2911f0775cbc80d2ec/src/main/resources/assets/botania/lang/en_us.lang#L638

**Comment by ElectronicRU** [comment]
Re: the last part, I have a strong suspicion that this is due to % symbol being used.
