### ISSUE TITLE
When all the flowers are destroyed, they turn into red roses.

### ISSUE THREAD

**Issue by Chinesesw** [Vazkii/Botania#2949]
When my flowers are destroyed or wait for a while, they all turn into red roses and cannot be used properly. How to solve this problem?

**Comment by williewillus** [comment]
does this happen with only botania installed? what version?

**Comment by Chinesesw** [comment]
Game version is 1.12.2
Mod version is Botania+r1.10-361
This happened on my server.

**Comment by Chinesesw** [comment]
> does this happen with only botania installed? what version?

This BUG bothers me a lot.

**Comment by williewillus** [comment]
does it happen with only botania and baubles? what about singleplayer?
