### ISSUE TITLE
Manasteel armor provides no protection in MP

### ISSUE THREAD

**Issue by nirvanaxiao6** [Vazkii/Botania#2950]
# Version Information
Forge version:  14.23.5.2768
Botania version:  r1.10-361

# Further Information

Steps to reproduce:
1. First step: Put manasteel aumor on in server, and the tooltip shows that I have 15 points of aumor.
2. Second step: Hit by a skeleton

What I expected to happen: As Wiki says, attacks from skeletons will cause 3 - 4 damage; Also, when a player has 15 points of aumor, a skeleton should cause 1.92 damages at most.

What happened instead: I lost 4 points(2 hearts), which means the aumor didn't protect me at all.

But in Singleplayer, it works well.

**Comment by bobodoustaud** [comment]
Happens to me too but with every armor (1.12.2) but the armors works very well in singleplayer. It seems to be a little bit random. Could you test with vanilla armors ? (iron and diamond without enchants)
