### ISSUE TITLE
achievement get [take it easy]

### ISSUE THREAD

**Issue by TrueDiamant777** [Vazkii/Botania#2954]
i was about to /give me the pure daisy then on the jei interface it says that the correct id was "specialflower" so I wrote /give me specialflower but i get the achievement take it easy and a red flower

**Comment by williewillus** [comment]
the flowers use nbt data to store which type they are so just using raw `give` won't work, you need to provide the appropriate nbt tags (examine the nbt of a well formed stack to see the tags to add)
