### ISSUE TITLE
Wearing manasteel chestplate made player unable to connect

### ISSUE THREAD

**Issue by Zaflis** [Vazkii/Botania#2957]
# Version Information
Forge version:  1.12.2-14.24.5.2808
Botania version:  r1.10-360

# Further Information
Link to (partial) server log: https://pastebin.com/vUQFSjBk
Steps to reproduce:
1. Wear manasteel helm (unsure if this step is needed)
2. Wear manasteel chestplate

What I expected to happen:
Wear the armor normally...

What happened instead:
Booted from server, and you cannot log back even after server is restarted.

Workaround: Delete player file from world folder and cheat other items back.

Other info; we are playing latest Modern Skyblock modpack.

**Comment by Hubry** [comment]
Thanks for the info on what pack it is. Can you try opening the `Avaritia-1.13.jar` file and deleting the entire `vazkii` directory from it, then relaunching the game? (Or maybe even deleting that fire entirely?) 

(Also, why in the name of tiny potato does this pack have both 1.12 and 1.7.10 Avaritia???)

**Comment by Zaflis** [comment]
Before that i wanted to see how this happens to me so i cloned the server and client, because it was other player who found the issue with vague details. To know what to expect when i edit jars soon...

So test 1 i spawned on snow island i gave myself full manasteel armor and still all fine. Then gave manasteel shears and it booted when i dig pumpkin with it. Couldn't relog.
Test 2 i started with shears straight away and dig the pumpkin, still fine. Then i equipped just manasteel helmet and booted.

**Comment by Zaflis** [comment]
Deleting the vazkii directory seems to fix the bug entirely, although i can't be sure it has side-effects to recipes or other things in the pack. It even fixed the bugged character when i tried once without reseting world.

So i assume this should be handed to modpack authors if mod itself has nothing wrong.
