### ISSUE TITLE
Dice of Fate giving repeated items

### ISSUE THREAD

**Issue by SigmaSnake** [Vazkii/Botania#2963]
# Version Information
Forge version:  14.23.5.2844
Botania version:  r1.10-361

# Further Information
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline) N/A
Steps to reproduce:
1. First step: Defeat Gaia Guardian II 6 times to receive all 6 items from the dice of fate
2. Second step: Repeatedly get more items out of the Dice of Fate when it should disappear

What I expected to happen:
For the Dice of Fate to Dissappear
What happened instead:
![2019-08-31_01 18 04](https://user-images.githubusercontent.com/54494265/64060112-f99aa680-cb8d-11e9-8c51-b3272f8abe39.png)
![2019-08-31_01 18 51](https://user-images.githubusercontent.com/54494265/64060114-fa333d00-cb8d-11e9-9754-0c7aee8e2b51.png)

**Comment by williewillus** [comment]
the mod checks the relevant advancement for each relic to determine if it should give it or not.

do you have something overriding or otherwise suppressing botania advancements?

**Comment by SigmaSnake** [comment]
Not that I am aware of, but I have been having a lot of issues with the advancement system as of late.

**Comment by SigmaSnake** [comment]
Ok, after clearing away the TPS lag, the advancements seem to work fine now. It was only a few seconds of lag, so I did not think it was that much of a issue, my apologies.
