### ISSUE TITLE
Not able to collect Dragon's Breath

### ISSUE THREAD

**Issue by nanderLP** [Vazkii/Botania#2964]
#2101 Version Information
Forge version:  
Botania version: r1.10-361 

Steps to reproduce:
1. Wait for the Ender Dragon to spit a Ball and let it explode.
2. Use a Bottle to collect Dragon Breath

What I expected to happen: I receive Dragon's Breath

What happened instead: I receive Ender Air

**Comment by Hubry** [comment]
Don't right click blocks with bottles, that will always bottle the air. Right click in the air instead.

**Comment by DizzyDJW** [comment]
This is still an issue in the lastest version for some unknown reason somebody thought it would be smart to make it so that you can collect Ender Air by right clicking the air or a block.

It's such a ridiculously simple fix JUST make it so the player needs to CROUCH when right clicking to collect Ender Air. There. Fixed it for ya

**Comment by williewillus** [comment]
Attacking the maintainers achieves nothing. If it bothers you so much, send a patch yourself.

**Comment by osirisgothra** [comment]
I've wished for almost a decade to see no more ender air bottles by default, or to have at least it be in offhand or require a secondary action/item of some sort just so they don't interfere with the breath gathering, they are so annoying and when you are fighting especially in hard mode packs in multiplayer, you are: trying-to-chase-it + trying-to-kill-it + get-dragons-breath + not-get-killed + not-get-ender-air + deal-with-server-side-lag... all at the same time on a dragon that has been resummoned by every player on the server so it is nearly immortal... and anyone who has ever sent in patches knows that the chances of them actually being merged/pulled in is like waiting for paint to dry underwater. 

Not that the difficulty is a problem, no, it's the fact that adding an annoying 'feature' into the mix, makes it very unpleasant and honestly, I'd disable that feature on my own mod packs even if it meant just not including it in the pack at all. There is no way they will ever get rid of it though; you are wishing for rain in a desert.

**Comment by NolanHewitt** [comment]
Is there any actual way to get dragons breath with this mod installed? It seems like its impossible to do so currently.
