### ISSUE TITLE
Lapis Lazuli Ore drops a missing texture after falling onto a torch via the Weight Lens

### ISSUE THREAD

**Issue by TepperPepper** [Vazkii/Botania#2965]
# Version Information
Forge version: forge-14.23.5.2846
Botania version: Botania r1.10-361.jar

# Further Information
Steps to reproduce:
1. Place a Lapis Lazuli Ore block >= 2 blocks above a torch (or other block that causes falling block entities to turn into their dropped form).
2. Fire a mana blaster with the Weight Lens at the Ore.

I was harvesting ores from the Orechid and when I tried using the weight lens trick to make ores drop as themselves on a block of Lapis Lazuli Ore it dropped a glitched version of itself. I can place the glitched ore back down and it'll have the correct texture and behave as normal but it cannot be smelted or processed in machines like TE's Pulverizer.

![lapisorebug](https://user-images.githubusercontent.com/46273243/64306587-4bae4400-cf61-11e9-8dbc-786e08fc1c10.gif)

**Comment by williewillus** [comment]
see #2488
unfortunate side effect of how falling sand entities work in 1.12, this is fixed in 1.14 but probably infeasible to fix reliably in 1.12
