### ISSUE TITLE
Certain Item Models from other mods not Rendering when Botania is Installed

### ISSUE THREAD

**Issue by xlea99** [Vazkii/Botania#2967]
# Version Information
Forge version:  forge-14.23.5.2846
Botania version:  Any version for 1.12.2 (tested on all of them)

# Further Information

Steps to reproduce:
1. Install OpenComputers and OpenSecurity on a fresh vanilla pack. The 'energy turret' item renders perfectly fine in inventory.
2. Install any version of Botania. The 'energy turret' item now doesn't render at all, instead it appears empty (the item still exists, just the texture is gone in inventory)

Simply put, for some reason, installing Botania will make certain, rare item models in inventories disappear. It seems to do the same with certain RFTools portal blocks, but the OpenSecurity example was the best/easiest one to reproduce. I've tested this extensively with hundreds of other mods, and the render issue only ever occurs when Botania is installed.

I've also tried changing practically every value in the config to see if that helped, but nothing did.

Thanks for taking the time to read this!

**Comment by ben-mkiv** [comment]
https://github.com/Vazkii/Botania/blob/483a816616d86f5ff36e1fc150afa1527042efce/src/main/java/vazkii/botania/client/render/tile/RenderTilePylon.java#L64

This is probably the issue, you override the `render()` method but return if it shouldn't render, while it would require to delegate the rendering to the "old" `TileEntityItemStackRenderer.instance` which you do fine for the `renderByItem()` method. So i would suggest to move the method to the ForwardingTEISR class. 

https://github.com/Vazkii/Botania/blob/483a816616d86f5ff36e1fc150afa1527042efce/src/main/java/vazkii/botania/client/render/tile/RenderTilePylon.java#L151-L159
