### ISSUE TITLE
[1.14] Gaia Guardian music keeps restarting

### ISSUE THREAD

**Issue by williewillus** [Vazkii/Botania#2984]
idk why

**Comment by iTitus** [comment]
Related issues:
probably this: https://github.com/LWJGL/lwjgl3/issues/185
And https://github.com/CreativeMD had a similar issue with repeating sounds.

Quick and dirty fix would probably be to disable repeating and then to manually replay the sound.

**Comment by williewillus** [comment]
how do you know when it's done?

**Comment by iTitus** [comment]
We know how long the music piece is and can use the that to replay it.
That's hacky, I know.
But due to the technical limitations of the new Vanilla Sound Engine or some Bug we have to - for now.

**Comment by williewillus** [comment]
"fixed" in a641aed
