### ISSUE TITLE
CoFH Multishot enchants do not function with Livingwood/Crystal Bow

### ISSUE THREAD

**Issue by OverlordKyo** [Vazkii/Botania#2989]
# Version Information
Forge version:  14.23.5.2836
Mod versions: Botania r1.10-362, CoFH Core 1.12.2-4.6.3.27-universal

# Further Information
Botania bows only fire 1 arrow when enchanted with Multishot I/II/III/IV.
Steps to reproduce:
1. Enchant Crystal/Livingwood bow with Multishot I/II/III/IV
2. Shoot bow
3. Observe as only a single arrow flies out.

What I expected to happen:
Multiple arrows to shoot when bow is enchanted with multishot.

What happened instead:
Only a single arrow is shot.

**Comment by bobodoustaud** [comment]
happens to me too, but it could also be a bug from cofh
