### ISSUE TITLE
[1.14.x] ConcurrentModificationException while teleporting into non-generated chunks

### ISSUE THREAD

**Issue by iTitus** [Vazkii/Botania#2993]
# Version Information
Forge version:  1.14.4-28.1.44
Botania version:  current 1.14.x branch from GitHub

# Further Information
Link to crash log: [here](https://gist.github.com/iTitus/f65312008b3438d66ee272afce97119a)
Steps to reproduce:
1. be in a fresh world and stand in a swamp in the overworld
2. /locate minecraft:desert_pyramid
3. click on the resulting coordinates to paste tp command into your chat input
4. submit the command
5. see yourself get teleported, but then it crashes instantly before control is regained

What I expected to happen:
Safe teleport into the desert.

What happened instead:
Crash

This crash happened in a dev environment. There were no minecarts nearby. After restarting the client it worked fine.

**Comment by williewillus** [comment]
wtf....

**Comment by williewillus** [comment]
a2b2b3e
