### ISSUE TITLE
Runic Altar Not Working?

### ISSUE THREAD

**Issue by theoneandonlytoasty** [Vazkii/Botania#2995]
Hello all, I've been recently dabbling in Botania and trying to use the Runic Altar, as it's a necessary item for progression in the game. However, when I have attempted to use it, it's seemingly not accepting mana. Setup is attached here:
<img width="1440" alt="Screen Shot 2019-10-18 at 6 50 14 PM" src="https://user-images.githubusercontent.com/33645324/67136589-1d1cbd80-f1dd-11e9-973c-3f886a3b5f19.png">
I don't know why, but it just doesn't work. I've tried uninstalling conflicting mods, but it doesn't seem to work either. All help appreciated. I am running RLCraft with additional mods, and Botania Version r1.10-362 on 1.12. Thanks!

**Comment by Raz56buddy** [comment]
Bro same I, I am playing Levitated and am having this same problem
None of the runes will work
