### ISSUE TITLE
Shears act like normal items onBlockDestroy

### ISSUE THREAD

**Issue by MelanX** [Vazkii/Botania#2996]
# Version Information
Forge version:  28.1.44
Botania version:  r1.10-363-d69389a

# Further Information
Steps to reproduce:
1. Try to farm grass with shears
2. Look sad in the camera

What I expected to happen:
I wanna have my grass.

What happened instead:
I don't get my grass.

**Comment by williewillus** [comment]
Awaiting https://github.com/MinecraftForge/MinecraftForge/pull/6270

**Comment by williewillus** [comment]
should be closed by the forge:shears PR? but could be improved further since there's no standard tag yet
