### ISSUE TITLE
[1.14] Ring of Chordata is broken in several ways

### ISSUE THREAD

**Issue by Hubry** [Vazkii/Botania#3011]
### Version Information
Forge version: 28.1.87
Botania version: Botania 1.10-364

### Further Information
* You don't need to be fully submerged to benefit from the ring
* The ring stacks with the vanilla swimming changes really weirdly, allowing extremely fast swimming, but hard to control.
* Trying to swim into the one direction while having momentum in opposite direction just makes you keep swimming fast with your momentum.
* Swimming along an axis eventually ends up going in a diagonal direction.
* The effect stacks with Dolphin's Grace, making you outpace world generation.
* The effect gets reduced by Depth Strider. Ring + DS3 is still better than Depth Strider 3 alone, and is about what I would expect from the ring. 
* The effect might be a little bit too cheap, given vanilla's changes to underwater terrain. A comparable block is the [Conduit](https://minecraft.gamepedia.com/Conduit) which provides Conduit Power (Water Breathing/Haste/Night Vision in one) in a limited area around itself, while also damaging nearby hostiles touching water. It costs one Heart of the Sea (one in each buried treasure chest) and 8 Nautilus Shells (Drowned and fishing drop). The ring basically has two effects of the Conduit, and a significant swim speed boost. I would consider putting a Heart of the Sea into the recipe.

**Comment by WittySwat** [comment]
Adding to the "Swimming along an axis eventually ends up going in a diagonal direction". It only occurs as soon as you are not looking directly north, south, east, west. (0, 90, -90, 180 degrees on the F3 screen. It appears to exponentially adding the perpendicular direction until it matches the original direction until you are going directly diagonal.
