### ISSUE TITLE
[1.14] Multiple render issues related to sparks

### ISSUE THREAD

**Issue by WittySwat** [Vazkii/Botania#3015]
# Version Information
Forge version:  28.1.87
Botania version:  364

# Further Information
https://imgur.com/zVj4PED

What I expected to happen:
Sparks render in front of other objects and don't make them invisible. 
What happened instead:
Sparks override models and particles and make them invisible
Some that I've noticed:

- Mana Spreaders
- Players with Mana Armor
- Alfheim Portal
- Nether Portal
- Runic Alter Item Renders
- Runic Alter center pariticles
- Mana Bursts
- Floating Flowers
- Mana Pylons
- Campfire/Torch Particles
- Quark:foxhound

**Comment by williewillus** [comment]
Not easy to fix since it's basically vanilla's TE render order issue
Maybe in 1.15.
