### ISSUE TITLE
[1.14] Alfheim Portal completely broken

### ISSUE THREAD

**Issue by g4bri3lDev** [Vazkii/Botania#3017]
# Version Information
Forge version: 28.1.87
Botania version: Botania_r1.10-364

What I expected to happen:
1. Portal should require 'a substantial amount of mana' to open.
2. Portal should give correct items back when mana is present for the exchange
What happened instead:
Portal requires no mana at all to open.
Items thrown into the portal are just voided even though enough mana being present for the transaction.

**Comment by williewillus** [comment]
couldn't get the second to happen when under good conditions (enough mana + pylons in right place). Fixed the first though.
