### ISSUE TITLE
Crash when using Rod of the Unstable Reservoir (?)

### ISSUE THREAD

**Issue by Chupp4-Jo3** [Vazkii/Botania#3025]
(the wand that makes it rain wet death)

Crashes when right clicking with rod in hand.

https://pastebin.com/E8H4R4yT

Botania: r1.10-362
MC 1.12.2
Forge: 14.23.5.2847

Let me know if you need more info!

**Comment by Hubry** [comment]
It's a bit late to respond, but check if you have more than one Avaritia version installed. If yes, tell us the jar names and remove the old 1.7 one.
