### ISSUE TITLE
[1.14.4] Ring of odin extra hearts reset

### ISSUE THREAD

**Issue by WittySwat** [Vazkii/Botania#3027]
# Version Information
Forge version:  90
Botania version:  368

What I expected to happen:  
My hearts are persistent until I remove the ring.  
What happened instead:  
My hearts don't disappear and regen every time i leave the server or transfer between worlds.

**Comment by williewillus** [comment]
did you switch the expected/actual results?

**Comment by WittySwat** [comment]
Whoops, i did. Sorry it is fixed now.

**Comment by williewillus** [comment]
the hearts are still there on dimension switch but just invisisible (verifiable using scoreboard). looks like a forge patch for MC-88179 got dropped by accident.

as for loading from save actually dropping the hearts, the mentioned commit fixes it

**Comment by artemisSystem** [comment]
This bug appears to be back in 1.16. As far as i remember, it has always been there in both 1.12 and 1.16. Currently using forge 36.1.12 for mc 1.16.5, and botania 416
