### ISSUE TITLE
Composite Lenses don't exist?

### ISSUE THREAD

**Issue by digiornopizzaboy** [Vazkii/Botania#3028]
I downloaded Botania from curseforge with the name "Botania r1.10-361.jar" for 1.12, and I'm not able to see a crafting recipe for composite lenses in this version. I've got some other mods installed but I don't think they cause the problem. I'm not sure if I downloaded it from the wrong place.

![2019-11-25_15 10 25](https://user-images.githubusercontent.com/58191403/69578459-247e7600-0f96-11ea-91fa-4eaa7040e493.png)

**Comment by williewillus** [comment]
there isn't a single recipe for composite lens, since they're any two lens that can go together joined with a slimeball

potentially may be a bug with how the JEI integration works, but you should be able to just craft them without JEI.

**Comment by digiornopizzaboy** [comment]
Ah, thank you for removing confusion.
