### ISSUE TITLE
Shard of Laputa never dies when blockbreaks cancelled

### ISSUE THREAD

**Issue by clienthax** [Vazkii/Botania#3031]
# Version Information
Forge version:  forge-1.12.2-14.23.5.2847-universal.jar
Botania version:  Botania r1.10-362.jar

# Further Information
Using spongeforge + griefdefender,
When a laputa burst enters a claim, and the action is cancelled, instead of continuing to the next possible position, the shard will continue to attempt to break the same block over and over again.

This can be seen in this log
https://griefdefender.github.io/debug/?vKRrlB16k0

**Comment by Alwinfy** [comment]
Related bug (present in 1.14): If Laputashard tries to pick up a watersource block that gets filled, it picks up the refilled block *ad infinitum*

**Comment by clienthax** [comment]
Shoo stalebot

**Comment by clienthax** [comment]
Shoo stalebot

**Comment by williewillus** [comment]
sorry for the inaction on this. How could this be detected on botania's side? Having a list of positions to skip is relatively easy, but not sure how to detect that permissions has denied something.

**Comment by Alwinfy** [comment]
Possibly populate the list of blocks to lift in memory at use time, then only attempt to lift each block once?

**Comment by clienthax** [comment]
world.setBlockToAir(pos_); returns false if the set fails, just continuing to the next point here should be fine @williewillus

**Comment by clienthax** [comment]
> Shoo stalebot

**Comment by clienthax** [comment]
> > Shoo stalebot
