### ISSUE TITLE
Guardian of Gaia crash

### ISSUE THREAD

**Issue by Mankey99** [Vazkii/Botania#3040]
Hey guys, I'm having an issue with the Guardian of Gaia, every time I attack it I crash the client. It is running on a server and the server seems fine. It is just me. I'm assuming it is either causing a status effect or it is the pixies attempting to render that is causing my client to crash. Probably conflicting with another mod, but I don't know which mod or where to look without pulling out each mod one by one and testing it.

Please help!

# Version Information
**Forge version:**  1.12.2-14.23.5.2847
**Botania version:**  r1.10-362

# Further Information
**Link to crash log:** https://pastebin.com/BunNA0XC
**Steps to reproduce:**
1. Summon Guardian of Gaia with Terrasteel
2. Attack Guardian of Gaia
3. Screen goes funky then client crashes

**What I expected to happen:**
Guardian of Gaia battle to begin

**What happened instead:**
Crash to desktop

**Comment by Mankey99** [comment]
So I've been testing, in a new world where the guardian of gaia crash still happens. I equipped an Elementium shield and blocked against a skeleton till a pixie spawned and nothing crashed. I also hit myself with a splash potion of blindness and again nothing crashes.

It must be something about the guardians attack. If I reload the client and jump back into the world, the guardian is still there, just not in his attack state. If I hit him I crash again.

However, if I get him into Phase 2, he hangs out spawning mobs just fine. Then in Phase 3 it crashes again.

**Comment by quat1024** [comment]
In the mean time, you can get rid of Albedo

**Comment by Mankey99** [comment]
> In the mean time, you can get rid of Albedo

Oh damn, it only bloody solved it! Thank thee quat1024. Let it be known, Albedo is not compatible with Botania and quat1024 has a very big manhood.

**Comment by quat1024** [comment]
* yeah but this is still a bug because they're *supposed* to be conpatible

* :thinking: :thought_balloon:

**Comment by Mankey99** [comment]
Oh, well I'll reopen it then if you reckon someone can figure it.
