### ISSUE TITLE
[1.14.4] Spreaders don't work with quark rotation lock feature

### ISSUE THREAD

**Issue by WittySwat** [Vazkii/Botania#3053]
# Version Information
Forge version:  104
Botania version:  369
Quark: r2.0-201

**Comment by williewillus** [comment]
support for this is on the Quark side (and the API class for use otherwise is missing)

**Comment by williewillus** [comment]
Pretty sure this will just be a wontfix, quark's thing assumes rotation is set as a blockstate prop while for spreaders it's stored in the TE
