### ISSUE TITLE
Manaseer Monocle stops working once applied as a Cosmetic Override

### ISSUE THREAD

**Issue by Alwinfy** [Vazkii/Botania#3055]
# Version Information
Forge version:  28.1.102 for 1.14
Botania version:  selfbuilt, commit 2b21223

Steps to reproduce:
1. Apply Manaseer Monocle to arbitrary other bauble (I used a Benevolent Goddess Charm)
2. Equip other bauble
3. Look at flower

What I expected to happen:
Manaseer overlay
What happened instead:
Nope

**Comment by williewillus** [comment]
i think that's intended, there's the "cosmetic" and the thing you're applying it to ("target").

The target retains its functionality (since that's the actual item under the hood), the cosmetic only retains its looks (since it's just an NBT tag sitting on the target item).

**Comment by Alwinfy** [comment]
Behaved/was documented differently in .12 and below:
!["The monocle can be used as a Cosmetic Override to any other bauble. While in this state, all of its benefits are still provided, which allows for it to be used without taking up a slot."](https://i.imgur.com/kGvtJSh.png)
