### ISSUE TITLE
Vinculotus doesn't affect Farlanders Fanmade/Classic Enderman

### ISSUE THREAD

**Issue by Hafo0135** [Vazkii/Botania#3057]
# Version Information
Forge version:  forge-14.23.5.2847
Botania version:  Botania r1.10-362.jar
farlanders-1.12.2-1.0.1.jar

# Further Information
Steps to reproduce:
Place a Vinculotus near a Mana pool
Spawn Farlander's Fanmade or Classic Enderman
Attack them, causing them to teleport

What I expected to happen:
I expected the Fanmade/Classic Enderman to be stuck teleporting to the Vinculotus like a Vanilla Enderman.
What happened instead:
Their teleportation was unhindered by the Vinculotus.

**Comment by williewillus** [comment]
botania checks for `instanceof EndermanEntity` which should catch all subclasses of vanilla endermen. If said mod doesn't extend the vanilla class, botania can't get it, so it's on the other mods to do that.
