### ISSUE TITLE
[1.14.4] Allow Waterlogging of Blocks

### ISSUE THREAD

**Issue by WenXin20** [Vazkii/Botania#3069]
# Version Information
Forge version:  v28.1.107
Botania version:  r1.11-372

# Further Information
Allowing waterlogging of non-full blocks could be a good enhancement, at least for decoration blocks, such as for the Tiny Potato.

Steps to reproduce:
1. Place blocks underwater, such as the Tiny Potato.
2. No waterlogging.

What I expected to happen:
- Non-full blocks should waterlog.
What happened instead:
- Non-full blocks don't waterlog

**Comment by williewillus** [comment]
which ones exactly?

**Comment by WenXin20** [comment]
Perhaps blocks such as the Tiny Potato, Drums, Eye of Ancients, Cocoon of Caprice, the Petal Apothecaries, Mana Pools, Gaia Guardian Head, Floating Flower Islands, the Runic Altar, Mana Distributors & Spreaders, Tiny Planet, Starfield Creator, Agglomeration Plates, Mana Prism, Mana Pump, Incense Plates, Spark Tinkerer, Luminizer Launcher, Crystal Cube, Pylons, Livingwood Avatar, Manatide Bellows, Botanical Brewery, Luminizers, Corporea Index, Hovering Hourglass, &/or Teru Teru Bozu.

This could be good for decoration or if they happen to be placed underwater.

Also noticed that the glass blocks will render with water flowing down its sides if placed underwater, unlike normal Minecraft glass.

**Comment by williewillus** [comment]
hmm i don't think we're gonna do that. I'd prefer to stick to vanilla's decision of only waterlogging a certain set of blocks.

maybe in the future once they allow fluids in any block.

as for the glass issue, fixed by Hubry in the next release
