### ISSUE TITLE
[1.14.4] Badly Compressed Packet Disconnect on Server join.

### ISSUE THREAD

**Issue by Gbergz** [Vazkii/Botania#3072]
# Version Information
Forge version:  28.1.107
Botania version:  r1.11-372
MC-Version: 1.14.4

# Further Information
Link to error: [Imgur](https://i.imgur.com/sboUwAO.png)
Steps to reproduce:  Try  to join a server with Botania Installed.
1. Start MC with Botania 
2. Join an Online server with Botania
3. Wait.. Disonnected

What I expected to happen:
Being able to join the Server without [Badly Compressed Packets.](https://i.imgur.com/sboUwAO.png)

What happened instead:
I get disconnected upon joining with [Badly Compressed Packets.](https://i.imgur.com/sboUwAO.png)

# EVEN Further Information
Added to my [Modpack,](https://www.curseforge.com/minecraft/modpacks/tnp-limitless) noticed everyone was getting disconnected on the server upon joining when i added it. Happens on a local server & hosted server.

Is this fixable?

I can provide logs when this happens, but i searched and i couldn't find anything linked to it. Maybe i'm just looking at the wrong places.

Current Modlist: 
[GistGithub](https://gist.github.com/Gbergz/7252666765f7028165b2cf903440aec7)

Latest Server Logs: 
[GistGitHub](https://gist.github.com/Gbergz/fde8b4ba606399b34d74c94dc4156cb4)

Latest Debuglog: 
[GistGitHub](https://gist.github.com/Gbergz/ccb12869dad9290b95611be327d57542)

**Comment by gorf18** [comment]
This was fixed by:  https://github.com/Vazkii/Botania/issues/3066
For the interim, you can disable Botania until a new build is created.

**Comment by williewillus** [comment]
fixed in 373
