### ISSUE TITLE
Conflict with Silent's Gems

### ISSUE THREAD

**Issue by dragon076** [Vazkii/Botania#3075]
**Versions**:
    Silent's Gems:  SilentGems-1.14.4-3.4.7+80.jar
    Silent Gear:  SilentGear-1.14.4-1.4.6+72.jar
    Silent Mechanisms:  SilentMechanisms-1.14.4-0.6.9+42.jar
    Silent Lib:  SilentLib-1.14.4-4.4.0+44.jar
    Botania:  Botania+r1.11-372.jar
    Forge:  forge-1.14.4-28.1.103.jar
    Modpack:  Enigmatica 4 Heavily modified

**Expected Behavior**:

Tools that were crafted beforehand to not show and error and continue to work.
And to be able to craft new tools from the blueprints.

**Actual Behavior**:

Added Botania+r1.11-372.jar to mods.
At login get the message: [Silent's Gems] No chaos buffs are loaded! This means chaos gems and runes will not work. This can be caused by a broken mod.
Tools that had been crafted show as broken and new tools can't be crafted.
also with the creation of a new world there is no loot in the starter chest and still can't craft any new tools.

Removed Botania+r1.11-372.jar from mods.
All tools that had been broken in save work again and can craft new tools again.
**Links/Images**:

https://www.dropbox.com/s/l0tgvxxqt62ryw4/2019-12-28_11.54.05.png?dl=0
https://www.dropbox.com/s/w2qrzves2ikx1q2/2019-12-28_11.55.30.png?dl=0

**Steps to Reproduce the Problem**:
1.Add Botania+r1.11-372.jar and Patchouli-1.1-22.jar into a modpack containing Silent's Gems eg: TNP Limitless
2.Create new world and try to craft the Silent's based blueprint weapons
3.Remove Botania and issue should disappear.

PS: These are just my observations i realize the issue could be elsewhere. I also posted a bug report on the Silent's Gems page. 
https://github.com/SilentChaos512/SilentGems/issues/437

**Comment by williewillus** [comment]
got a log? `debug.log`

**Comment by dragon076** [comment]
with the discussion on Silentgems page
> Looks like a mod causing data loading to fail (see #433). Your log file should have more information. Search for "Failed to reload data packs".

i found the "Failed to reload data packs" in this log file.
https://www.dropbox.com/s/hpmnxx82bcznnn0/2019-12-28-2.log?dl=0
From what i can tell there seems to be and issue with KleeSlabs_1.14.4-7.4.7.jar
Not sure if that's the case or not or if there is something else again.
Let me know if u need something else
Thanks

**Comment by Vaelzan** [comment]
It's KleeSlabs, and the issue has already been reported and fixed on their end. You need to update to the latest KleeSlabs. The reason it only broke with Botania installed is because it was triggered by loading the Botania Compat JSON.

**Comment by dragon076** [comment]
Ok. Thank you for the help.
