### ISSUE TITLE
conflict with the mod Levelhearts

### ISSUE THREAD

**Issue by phiphila** [Vazkii/Botania#3076]
# Version Information
Forge version:  forge-1.14.4-28.1.107
Botania version:  R1.11 372

# Further Information
When start minecraft with mods: Levelhearts-1.14.4-2.0.0, Botania+r1.11-372, Patchouli-1.1-22 and curios-FORGE-1.14.4-1.0.6 then the chests in mineshafts are empty
is I run minecraft just with Levelhearts-1.14.4-2.0.0 all is ok.

Steps to reproduce:
1. run minecraft with these mods
2. find a mineshaft and open a chest
3. it is empty

What I expected to happen:

What happened instead:

**Comment by williewillus** [comment]
fixed in next release

**Comment by phiphila** [comment]
the problem is still there ....
