### ISSUE TITLE
[1.14] Botania's custom crafting stops working?

### ISSUE THREAD

**Issue by LezChap** [Vazkii/Botania#3078]
# Version Information
Forge version:  28.1.109
Botania version:  1-.11-372

# Further Information
I haven't been able to figure out the cause or how to replicate the issue yet, but something is causing most of Botania's custom crafting mechanics to fail to work (including mana crafting, petal apothecaries, and pure daisy block conversions, not sure if more is impacted).  Alfhiem Portal consumes items (Living Wood) without returning anything.  The Lexica is also broken.

This is what the Lexica looks like when this happens: https://i.imgur.com/tK3NpL8.png
Clicking around in the Lexica when it happens produced the following crashlog: https://pastebin.com/n0n6GqVb

Here's the issue with users in ATM4 trying to figure it out: https://github.com/AllTheMods/ATM-4/issues/94

I'm not seeing much in the logs.  On logging into the server, the only relevant line in the client console appears to be:
`Error while loading book botania:lexicon`

Not sure if it's related, but the only thing out of place at the time that may be related on the server's log is:
`[18:34:38] [Server thread/ERROR] [ne.mi.fm.ne.si.IndexedMessageCodec/SIMPLENET]: Received empty payload on channel fml:handshake`

Posting this to try to collaborate tracking this issue down.

**Comment by TigerWalts** [comment]
Here's the full error in the client log:

- https://pastebin.com/dhDdYRvE

**Comment by LezChap** [comment]
I was not seeing that full error with stacktrace in my log, just the line I posted.
