### ISSUE TITLE
Some versions of the Flügel Tiara can't be crafted

### ISSUE THREAD

**Issue by ToMe25** [Vazkii/Botania#3082]
# Version Information
Forge version:  28.1.107
Botania version:  r1.11-372

# Further Information
Steps to reproduce:
1. get a Flügel Tiara
2. get some Smokey, Mana or Sunny Quartz
3. put the Tiara and the Quartz in a crafting grid

What I expected to happen: I expected to get a Mega Ultra Chicken, Ice Fairy or One-Winged-Angel Flügel Tiara.

What happened instead: It results in a Flügel one.

**Comment by Hubry** [comment]
The recipe for Flügel wings just uses the quartz tag, which makes me think maybe the colored quartz types shouldn't be tagged together with the rest...

**Comment by ToMe25** [comment]
I think the colored quartz should be in that tag, but maybe this recipe shouldn't use it.
Or as it always causes problems with the same ones maybe it is possible to make sure the quartz tag one gets loaded after all the other ones?

**Comment by ToMe25** [comment]
I would suggest changing the recipe to use the quartz item instead of the quartz tag as i culdn't find a good way to get the recipe ordering to always load the Flügel recipe last since HashMaps don't have to have a consistent ordering across instances or devices and the recipe manager uses one.
