### ISSUE TITLE
Encoding on botaniamod.net isn't UTF-8

### ISSUE THREAD

**Issue by Alwinfy** [Vazkii/Botania#3083]
Which would be fine, except for this entry in the Lexicon:
![`FlÃ¼gel`](https://user-images.githubusercontent.com/20421383/71550297-9f222300-2992-11ea-9ab1-735f9acfa91e.png)

Just throw a `<meta charset="UTF-8" />` in `web/botania.php`.

**Comment by williewillus** [comment]
fixed
