### ISSUE TITLE
[1.14.4] shift clicking non flower items into flower pouch crashes game

### ISSUE THREAD

**Issue by truehunterethan** [Vazkii/Botania#3084]
# Version Information
Forge version:  28.1.109
Botania version: r1.11-372

# Further Information
Link to crash log: https://pastebin.com/9sCGXCPj
Steps to reproduce:
1. shift-left click any non flower item into flower pouch
2. ???
3. game crash.

What I expected to happen:
game not crash, item not be in flower pouch.
What happened instead:
game crash, but item remains in player inventory instead of pouch

**Comment by Z0rdak** [comment]
Version Information

Forge version: 28.1.99
Botania version: r1.11-372

Can confirm this issue.
Got the same StackTrace as 'truehunterethan'.

**Comment by williewillus** [comment]
#3073
