### ISSUE TITLE
Some Hover-Areas in the Lexica-Botania wont scale with the size of the UI

### ISSUE THREAD

**Issue by DasGerippe** [Vazkii/Botania#3085]
# Version Information
Forge version:  28.1.109
Botania version:  1.11-372

# Further Information
Steps to reproduce:  
1. Get yourself a Lexica Botania.  
2. Open it and press the "Resize UI" Button so you get a non-default size.  
3. Go to a chapter where recipes are displayed, for example the "Mana Pool"-Chapter.  
4. Go to the page of the first Mana-Pool recipe (Iron ingot -> Mana Steel) and try to hover the Iron ingot to show it's name or to hover the Mana Usage Bar.  

What I expected to happen:  
The Name of the needed Items appear when hovering over them.  

What happened instead:  
Hovering the area where the iron ingot will be displayed with the default UI size will display it's name.

This isn't an issue when hovering categories or chapters.

**Comment by Hubry** [comment]
Vazkii/Patchouli#174

**Comment by williewillus** [comment]
^
