### ISSUE TITLE
[1.12] Null pointer exception thrown after fight with Gaia Guardian

### ISSUE THREAD

**Issue by jarquafelmu** [Vazkii/Botania#3089]
# Version Information
Forge version:  14.23.5.2846
Botania version:  r1.10-361

# Further Information
Link to crash log: https://gist.github.com/jarquafelmu/b8b05a5f3c6797b93939c58fa3652ecd
Steps to reproduce:
1. Honestly, I don't know what triggered the crash. I've fought and lost to Gaia a couple of times now but the server has only crashed the one time. It happened after respawn but I don't know what the trigger was.

What I expected to happen: The server not to crash

What happened instead: The server crashed

**Comment by Hubry** [comment]
Fixed in a641aed1b2bacb942eb2b18a753338948cc5ed8d. I know you are on 1.12, but that got the final update 9 days ago :(

Seems like a workaround would be fighting the boss while you are not the only person in the dimension.
