### ISSUE TITLE
Botania Axes deal too much damage

### ISSUE THREAD

**Issue by ToMe25** [Vazkii/Botania#3093]
# Version Information
Forge version:  28.1.107
Botania version:  r1.11-373

# Further Information
Steps to reproduce:
1. get yourself a manasteel or elementium axe
2. look at its damage in your inv or else where

What I expected to happen: I expected to see the Manasteel and Elementium axe deal 9 damage like in older versions and most vanilla axes.
For the Terra Truncator i think the damage might be good at 12, not sure.

What happened instead: The Manasteel and Elementium axe both deal 11 damage.

**Comment by Awesomespore** [comment]
As well as this, the shovels have an attack speed of 0.5, which is much slower than the 1.0 attack speed of vanilla shovels
