### ISSUE TITLE
Mana Bar not rendered

### ISSUE THREAD

**Issue by ToMe25** [Vazkii/Botania#3096]
# Version Information
Forge version:  28.1.92
Botania version:  ccf8abe

# Further Information
Steps to reproduce:
1. load a world with the new code changes after r1.11-373 as i think it did work there
2. get a mana tables, band of mana or greater band of mana, but no item constantly or near constantly using mana.
3. see no mana bar in the hud

What I expected to happen: I expected to see the blue mana bar getting rendered over a part of the Experience bar.

What happened instead: Nothing.

**Comment by williewillus** [comment]
it's always been the case you need a mana-using item to see the bar overlay

**Comment by ToMe25** [comment]
OK i didn't know that, i remembered it always being there.
