### ISSUE TITLE
Bloodthirst and Emptiness Effects not working

### ISSUE THREAD

**Issue by ToMe25** [Vazkii/Botania#3098]
# Version Information
Forge version:  28.1.107
Botania version:  r1.11-373

# Further Information
Steps to reproduce:
1. brew a Vial of Crimson Shade
2. drink it
3. wait for nothing to spawn during daytime or in light enough areas

What I expected to happen: I expected there to be some mob spawns at least during night time in lit areas

What happened instead: Nothing.

**Comment by Hubry** [comment]
Seems like the event we used previously no longer fires on light checks, as they are done earlier.

**Comment by ToMe25** [comment]
This is now fixed as of #3588.
