### ISSUE TITLE
Cocoon of Caprice doesn't render in block form and is nonfunctional.

### ISSUE THREAD

**Issue by TyreForHyre** [Vazkii/Botania#3100]
# Version Information
Forge version: 28.1.99  
Botania version: r1.11-373

# Further Information
Screenshot of cocoon in world with hitbox rendering and nothing else: https://i.imgur.com/7jQRyfy.png
What I expected to happen:
N/A
What happened instead:
N/A

**Comment by williewillus** [comment]
fixed in next version
