### ISSUE TITLE
Github wrongly displays Botania as a magic mod

### ISSUE THREAD

**Issue by PrototypeTrousers** [Vazkii/Botania#3109]
![Anotação 2020-01-03 220751](https://user-images.githubusercontent.com/11739607/71757534-81aef680-2e75-11ea-913d-9dd10731f7b7.jpg)

What I expected to happen:
A **tech** mod for Minecraft based on nature and plant life. http://botaniamod.net/
What happened instead:
A **magic** mod for Minecraft based on nature and plant life. http://botaniamod.net/

source of information:

![EMlTYp5WwAAhbxw](https://user-images.githubusercontent.com/11739607/71757487-1533f780-2e75-11ea-9c70-797542a70ae6.jpg)

**Comment by DoomRater** [comment]
I'm sticking that picture in my factory.

**Comment by williewillus** [comment]
only @Vazkii can change it but I'm closing since this isn't an actual bug.
