### ISSUE TITLE
Crash when shift-clicking items that don't belong in the flower pouch

### ISSUE THREAD

**Issue by dmtRoyal** [Vazkii/Botania#3111]
# Version Information
Forge version:  28.1.109
Botania version:  r1.11-373

# Further Information
Link to crash log: https://pastebin.com/ydkLcCsW
Steps to reproduce: 
1) Open flower pouch
2) Shift-click something that can't fit in there

What I expected to happen:  Nothing; the flower pouch should ignore items that aren't mystical flowers

What happened instead: 💣💥

**Comment by williewillus** [comment]
fixed in next version
