### ISSUE TITLE
Hostile Spawn Rate bugged + AI messed up

### ISSUE THREAD

**Issue by MrAwesomeGuy04** [Vazkii/Botania#3112]
# Version Information
Forge version:  1.14.4-28.1.111
Botania version:  r1.11-373

All hostile mobs are spawning extremely less than usual for the entire game
Also, all mobs move differential for example, cows and sheep randomly spin in circles when walking, this also goes for some hostile mobs such as endermen and zombies
Even hostiles from other mods are effected by this

**Comment by Hubry** [comment]
I am pretty sure the spinning thing isn't our issue, I've seen it mentioned multiple times, including two weeks before Botania released. Probably a vanilla bug, possibly a forge bug?
As for the mob spawning, we don't really do anything with it, except block mob spawns when near a player with a specific potion effect.

**Comment by williewillus** [comment]
the spinning thing is https://bugs.mojang.com/browse/MC-94054
the spawn rate doesn't have to do with botania as we only mess with it when emptiness/bloodthirst potion is active
