### ISSUE TITLE
Banner Patterns not working

### ISSUE THREAD

**Issue by ToMe25** [Vazkii/Botania#3114]
# Version Information
Forge version:  28.1.107
Botania version:  r1.11-373

# Further Information
Steps to reproduce:
1. place a loom
2. put a banner into the loom
3. put dye into the loom
4. try putting a iron pickaxe into the loom

What I expected to happen: I expected to be able to put that Pickaxe into the loom and get a Banner with a Pickaxe patter on it.

What happened instead: I couldn't put the Pickaxe into that loom.

**Comment by williewillus** [comment]
forge issue

**Comment by ToMe25** [comment]
I kinda suspected that but as it didn't logs the error the forge code contains i wasn't sure if its really that or something else, thanks.

**Comment by Hubry** [comment]
The forge bug for reference: MinecraftForge/MinecraftForge#6040

**Comment by ToMe25** [comment]
Thanks, but i have seen the problem here([BannerPattern.java.patch#L17](https://github.com/MinecraftForge/MinecraftForge/blob/1.14.x/patches/minecraft/net/minecraft/tileentity/BannerPattern.java.patch#L17)) before i just wasn't sure because the exception that gets thrown there doesn't seems to go anywhere.

**Comment by Hubry** [comment]
That's not the issue, the method you linked is replaced at runtime by a class transformer like in every extensible enum.

Mojang calls `values().length` for a final field in that class and uses that value in the loom gui, which causes ArrayIndexOutOfBoundsException to be thrown if you insert that pattern.

**Comment by ToMe25** [comment]
OK i didn't know that, but why doesn't Botania get that Exception than?
If i try to put the Pattern in it just doesn't works but doesn't cause a exception to get to the log.

**Comment by Hubry** [comment]
Mojang entirely removed the "craft banner with pattern in a crafting table" method in favor of the loom.

**Comment by ToMe25** [comment]
I meant if i try to put the "Pattern" item in the loom, not to craft it in the crafting table :)

**Comment by Hubry** [comment]
Ah, that type of pattern. That thing is actually completely ignored now, and the actual [banner pattern items](https://minecraft.gamepedia.com/Banner_Pattern) are the only thing accepted in the loom gui, and if you try to add your own, it crashes when used.

This is getting quite spammy, you should really join Vazkii's discord :V

**Comment by ToMe25** [comment]
I might do that
