### ISSUE TITLE
Mana Spreader stucks at exporting mana

### ISSUE THREAD

**Issue by MelanX** [Vazkii/Botania#3117]
# Version Information
Forge version: 28.1.109
Botania version: r1.11-373

# Further Information
Steps to reproduce:
1. Create a setup like in the picture below.
2. Wait a few minutes (maybe a bit more)
![unknown](https://user-images.githubusercontent.com/26039509/71771112-60faa580-2f36-11ea-9c95-24bc4ef4ca7c.png)

What I expected to happen:
The mana spreader works without problems

What happened instead:
Sometimes the mana spreader suddenly stucks at spreading. It's completely full of mana but will not export it. 
I don't know the duration until this happens and I have no idea how to force this fail.

How to fix it now:
Just rebind the Spreader to the Pool and it continues working.

**Comment by Mystense** [comment]
I have reproduced this issue in the same version of Forge and Botania, but in a different way. A mana spreader that I have linked to a mana pool, and is placed adjacently as in your example, will have a high chance of un-linking with the mana pool immediately if the mana pool becomes empty. The emptying of the mana pool for which I have observed the issue has been done by both infusing items and charging mana tablets.

I haven't found any conclusive evidence that it seemingly randomly disconnects after a passage of time, however.

**Comment by tiggerbiggo** [comment]
I am unable to reproduce on latest master or latest release 373. My forge version is slightly different but in both cases is below yours.

I don't at this moment have time to test (I will do so with more forge versions tomorrow) but any more details as to how to reproduce would be good.

This is especially strange to me given that Botania's mana spreaders supposedly work on where they are pointing. Maybe this has to do with the specific direction you build it in? 

If I can get it to reproduce I can probably make a breakpoint and find what's going on eventually but right now I can't seem to.

**Comment by MelanX** [comment]
The only thing I could say is that I use the modpack ATM4 v0.3.0. I don’t know if I could send you the world because it’s on a server with friends but I could send you the direction the next time I'm on pc. After I reported this issue I had no problem with this bug anymore... that’s really strange. Maybe because I crafted more Exoflames? I really have no idea. It’s a really weird and hard bug to reproduce.

**Comment by tiggerbiggo** [comment]
@MelanX sure, another useful bit of info possibly, was this on a chunk boundary? No idea if that should make a difference but it's a thought.

F3 + g I think is the button to enable and disable the chunk border preview.

**Comment by MelanX** [comment]
![image](https://user-images.githubusercontent.com/26039509/71905322-3a23b580-3168-11ea-9b18-784eeb5f5212.png)
There are a few more flowers and a Spark now but I see now that one flower of the base picture is in another chunk. But this should not influence the spreader + pool 🤔

**Comment by auxiliary-character** [comment]
I've been experiencing this hangup in my single player world too (running r1.11-375 right now), though I'm not entirely sure what's causing it. It just seems to randomly happen sometimes. I'll try to keep my eyes out to see if I can spot a pattern so it can be more easily reproduced. I had a hypothesis that it might be lazy loaded chunks, but I did a test and ruled that out. I have noticed that rebinding the spreader to the pool does reset it, though. Also, next time I see it, I'll make a backup of my world if you guys wanna do science to it.

**Comment by auxiliary-character** [comment]
Hey, I had it happen again. I tried to take a backup, but when I reloaded the world, the spreader linked to the mana pool afterwards, so the information is probably not in the save.
![2020-01-08_16 46 58](https://user-images.githubusercontent.com/860799/72022829-05326400-3237-11ea-947a-f04e70093758.png)

**Comment by auxiliary-character** [comment]
Also, here's the blockdata, if that helps.
![2020-01-08_17 23 46](https://user-images.githubusercontent.com/860799/72024768-c81ca080-323b-11ea-87c5-974bf61bf87d.png)

**Comment by tiggerbiggo** [comment]
Ok, my intuition can only go so far with my knowledge of botania but i
kinda suspect this may be the spreader not updating, and thinking it can't
send mana somehow, because as you showed it still has the outline around
the mana pool, meaning it is technically linked to it in the sense that the
game knows it is aiming at the pool.

Have you tried different forge versions? I still have yet to encounter this
issue and i have a similar setup with my endoflames.

**Comment by Hubry** [comment]
`forceClientBinding` values in spreader data show that the spreader for some reason thinks it's not linked to anything. The client seems to have found it out itself just fine, but the server got stuck. Sadly it's not really easily reproducible

**Comment by dkambersky** [comment]
Still happens. Can provide world file / server IP if useful.

**Comment by Bellwar** [comment]
Continuing on 1.15-382

**Comment by riskable** [comment]
I also want to confirm that this issue has occurred on my House in Wonderland (modpack) server many, many times now.  This is with Botania 1.15-384 and Forge 31.2.9

**Comment by TuckV** [comment]
I am confirming this issue for Botania-r1.15-387.
