### ISSUE TITLE
[1.14] Bubbles bar briefly overlaps with Flugel Tiara bar

### ISSUE THREAD

**Issue by IronPiston** [Vazkii/Botania#3118]
# Version Information
Forge version:  28.1.111
Botania version:  r1.11-373

What I expected to happen:
The bubble bar should appear when underwater, and disappear without rendering over the wings bar. The bubble bar should disappear at the exact same time as the wings bar lowers.

What happened instead:
![Peek 2020-01-04 14-08](https://user-images.githubusercontent.com/11603684/71771125-e7de5c80-2efb-11ea-86b4-eeb646d3c1ff.gif)
Here, the wing bar drops back down too early. It should instead wait until the bubble bar is gone.

**Comment by Hubry** [comment]
I think Forge actually has a thing for letting modders stack custom bars on top of each other easily nowadays? Need to move to that tbh
