### ISSUE TITLE
Pure Daisy forgets blocks

### ISSUE THREAD

**Issue by Awesomespore** [Vazkii/Botania#3125]
If a Pure Daisy begins converting a block, and you leave and rejoin, the game forgets to continue converting the blocks next to the Pure Daisy.
Re-placing the blocks or the Pure Daisy fixes it.

Steps to reproduce:
Place stone/wood/other next to pure daisy
leave world
join world

**Comment by williewillus** [comment]
this glitch is only visual but the linked commit should fix it
