### ISSUE TITLE
Changing UI size in Lexica Botania breaks the game

### ISSUE THREAD

**Issue by aroluna** [Vazkii/Botania#3134]
# Version Information
Forge version:  28.1.109
Botania version:  1.11-372

# Further Information

Steps to reproduce:
1. Open Lexica Botania
2. Click the up arrow on the GUI zoom setting

What I expected to happen: 
UI for lexica botania becomes slightly bigger, or the text in it becomes bigger

What happened instead:
The entire game UI disappears except for the little book in my avatar's hand, opening any inventory now causes the game to crash.
![Capture](https://user-images.githubusercontent.com/59714911/72118133-0e8a0200-3305-11ea-98f8-b1e8efae93ba.PNG)

**Comment by Hubry** [comment]
What Patchouli version? Are you on latest (1.1-24)?

**Comment by Hubry** [comment]
Couldn't reproduce it on latest Patchouli, reopen this on Patchouli's issue tracker if it still happens.

**Comment by aroluna** [comment]
Yeah I'm on patchouli 1.1-22
