### ISSUE TITLE
(1.12.2) Game crash due to presumably Force Relay actions

### ISSUE THREAD

**Issue by Hyxaru** [Vazkii/Botania#3141]
# Version Information
Forge version:  2847
Botania version: 362 

# Further Information
https://gist.github.com/Hyxaru/85e2fe8ba254d41ebe256beadf513b83

Steps to reproduce:
Uncertain

**Comment by williewillus** [comment]
1.12 is not receiving any more updates
as for the issue, force relays are delicate, treat with care

**Comment by Hyxaru** [comment]
Are force relays known to be buggy, and is that an accepted state?
Maybe leave it in 1.12.2 for what it is, but I can assume this issue might also occur in future versions.
