### ISSUE TITLE
Orechid Igenem Jei recipes use stone as input

### ISSUE THREAD

**Issue by ToMe25** [Vazkii/Botania#3142]
# Version Information
Forge version:  28.1.106
Botania version:  7734609

# Further Information
Steps to reproduce:
1. Search for Orechid in JEI
2. view usages
3. see stone instead of netherrack

What I expected to happen: I expected to see netherrack as input as the Lexica Botania states the Orechid Ignem uses netherrack.

What happened instead: The input of the recipe showed stone.

**Comment by Hubry** [comment]
I knew I'll forget something.
