### ISSUE TITLE
[1.12.2]Cannot work well with mod "ItemPhysic"

### ISSUE THREAD

**Issue by yaxuan97** [Vazkii/Botania#3144]
# Version Information
Forge version:  14.23.5.2846
Botania version:  r1.10-363
Item Physic mod: https://www.curseforge.com/minecraft/mc-mods/itemphysic
What I expected to happen:
Botania should work with it.
What happened instead:
Flowers cannot use dropitem with ItemPhysic.

**Comment by williewillus** [comment]
the flowers look for anything that extends vanilla's `EntityItem`, so it's on ItemPhysic to appear like one so other mods can work properly.
