### ISSUE TITLE
Terra Blade beam doesn't hit mobs if PvP is disabled

### ISSUE THREAD

**Issue by Neumono** [Vazkii/Botania#3146]
# Version Information
Forge version:  forge-28.1.113
Botania version:  r1.11-375
Minecraft version: 1.14.4
![2020-01-16_01 56 47](https://user-images.githubusercontent.com/59985013/72577978-79998280-3889-11ea-9f1a-6dceb12a44d2.png)

# Further Information
What I expected to happen: Swinging Terra Blade at mobs or players causes a mana burst to fire, which normally damages mobs or players on collision.

What happened instead: The mana burst from the blade does not interact with mobs/players at all, passes right through without colliding. It does, however, still affect burst-triggered blocks like the Hovering Hourglass and Drums of the Wild/Gathering.

Mod list:
Bookshelf 4.4.71
Botania r1.11-375
Craftable Saddles 1.3
Curios 1.0.6
Dark Utilities 2.0.10
Druidcraft 0.2.32
Fairy Lights 2.1.14
Forbidden & Arcanus 1.5
Gravestone 1.15.2
Harvest 1.2.10-23
Just Enough Items 6.0.0.27
MineColonies 0.10.593
OptiFine 1.14.4 HD-U-F5
Pathouli 1.1-24
Structurize 0.10.200-Alpha
Xaero's Minimap 1.19.6
Xaero's World Map 1.5.4

**Comment by Hubry** [comment]
Looks like it doesn't do anything if PvP is disabled, instead of doing proper checks if it can damage.
