### ISSUE TITLE
Crafting advanced runes doesn't use up previous runes

### ISSUE THREAD

**Issue by Acuzikwastaken** [Vazkii/Botania#3150]
Forge 28.1.109
Botania Version 314
Modpack is All the Mods 4 if that matters

Apologies if this is already reported, it seems like it would be but I also am new to github and couldn't find it

Crafting advanced runes (in my case, Rune of Sloth and Rune of Autumn) did not use the runes required in their recipes. Upon crafting Rune of Sloth I received a rune of autumn, air, and sloth from the altar, and crafting rune of autumn gave me a rune of autumn, air, and fire. All other resources were used up.

**Comment by TheWhiteWolves** [comment]
This has been intended behaviour for quite a while (as of version 238)
