### ISSUE TITLE
Rod of the Plentiful Mantle particles do not appear through blocks

### ISSUE THREAD

**Issue by alder-nighthawk** [Vazkii/Botania#3151]
# Version Information
Forge version:  28.1.114
Botania version:  r1.11-375

# Further Information
Link to crash log: no crash
Steps to reproduce:
1. Use Rod of the Plentiful Mantle
2. No particles visible through walls, though particles do appear

What I expected to happen:  Using the rod of the plentiful mantle, I believe particles are supposed to appear through the wall to pinpoint ores

What happened instead: Mana is consumed and the particles do appear, but cannot be seen through blocks/walls.

**Comment by williewillus** [comment]
Fixed in the next build, which is coming soon (tm)

**Comment by alder-nighthawk** [comment]
Thank you!
