### ISSUE TITLE
Flüngel Tiara not working on "Botania r1.11-373"

### ISSUE THREAD

**Issue by JaviBite** [Vazkii/Botania#3152]
# Version Information  
Forge version:  28.1.109  
Botania version:  Botania r1.11-373  

# Further Information  
Steps to reproduce:
1. Equip Flüngel Tiara
2. Duble jump to try to fly
3. Not wokring

What I expected to happen: Fly!

What happened instead: No Fly!

The Glide effect is working. This happens on single and multiplayer and with each one kind of wing.

**Comment by williewillus** [comment]
try on the latest version and make sure you have mana

**Comment by JaviBite** [comment]
i had mana, then that version is bugged? I suppose is caused by other mod or somehting, Its on Enigmatica 4 modpack from twich

**Comment by MelanX** [comment]
It’s because of the mod "Angel Ring"
