### ISSUE TITLE
Shifting Crust Rod doesn't check placeability of the block

### ISSUE THREAD

**Issue by Alwinfy** [Vazkii/Botania#3155]
HEAD (edf4020), runClient

Self-explanatory, leads to this:
![image](https://user-images.githubusercontent.com/20421383/72845342-01093c00-3c64-11ea-9269-cbbbcfd0412d.png)

**Comment by williewillus** [comment]
note to self: code should probably be modernized to use usecontexts, getStateForPlacement, and friends. would also solve problems with e.g. placing invalid/unupdated fences
