### ISSUE TITLE
Asada-san is shy

### ISSUE THREAD

**Issue by Hyper-Miiko** [Vazkii/Botania#3156]
Forge version:  14.23.5.2847 (MC 1.12.2)
Botania version:  r1.10-362

# Further Information
Steps to reproduce:
1. Take Mana Blaster
2. Rename it : ("Desu Gun", "desu Gun" or either "Desu gun")
3. Shoot

What I expected to happen:
Get Advancement "Two-Faced Lover"

What happened instead:
Nothing

N.B. : It work fine with "desu gun"

**Comment by SteamDoge9000** [comment]
OK I FIGURED IT OUT!
I had the same issue in 1.12.2 but noticed that there was caps in it so I though "is it cap sensative?" and lord and behold I was right, it needs to be "desu gun" for it to register in the advancment; apperently It will not register if its called "Desu Gun" wiht the caps

**Comment by williewillus** [comment]
1.12 is not receiving further updates.
