### ISSUE TITLE
Dispensers do not plant cocoa beans

### ISSUE THREAD

**Issue by alder-nighthawk** [Vazkii/Botania#3159]
#2720 Version Information
Forge version: 28.1.114
Botania version: r1.11-375

# Further Information
Link to crash log: no crash

What I expected to happen: Using dispensers with cocoa beans inside does not plant on jungle logs.  Botania Lexicon states they must be placed across from the dispenser, but beans do not plant in this or any configuration I have tried.

What happened instead:  Cocoa beans will not plant.
![Untitled](https://user-images.githubusercontent.com/60077643/73129532-c91b3500-3f92-11ea-9105-7d2b2480693c.jpg)

**Comment by Hubry** [comment]
It kinda worked though. 
![image](https://user-images.githubusercontent.com/26120076/73480229-ce64ef00-4399-11ea-8308-1680413536fa.png)

**Comment by alder-nighthawk** [comment]
Lol, works for me!  I will try that and see what happens!
