### ISSUE TITLE
Issues in Spanish Translation

### ISSUE THREAD

**Issue by NathanielFreeman** [Vazkii/Botania#3162]
The Spanish translation (es_es) of this mod is full of inconsistencies and errors, which more than help, hinder their intention to make this mod more familiar to Spanish speakers. All masculine adjectives are in feminine, even those that refer to Vazkii. It seems to have been translated with Google Translator. I am a translator's apprentice. Can I correct the translation?

**Comment by williewillus** [comment]
yes, PR's are welcome, no need to ask.
