### ISSUE TITLE
[1.14.4] Botania Crash Model

### ISSUE THREAD

**Issue by Rumaruka** [Vazkii/Botania#3166]
# Version Information
Forge version:  28.1.118
Botania version:  r1.11-376

# Further Information
https://pastebin.com/NqtChN2J

**Comment by williewillus** [comment]
Can you reduce the number of mods? Maybe it's a conflict

**Comment by Rumaruka** [comment]
Hmm , yes, I can.
I write about results later

**Comment by Hubry** [comment]
I've seen this exact crash report a bunch of times, and it's always caused by a loading error earlier. Please post the console log (preferably the debug one).

**Comment by Rumaruka** [comment]
> Can you reduce the number of mods? Maybe it's a conflict

After remove someone mods worked, its strange bugs
Im close issue, thank for help
