### ISSUE TITLE
Mod not loading

### ISSUE THREAD

**Issue by CTMalens** [Vazkii/Botania#3170]
I only have the botania mod and its dependencies, but when loading the game, it tells me that I don't have any mod

https://imgur.com/a/gwqTMII

**Comment by Hubry** [comment]
Please provide the console log, this screenshot is basically no info.

**Comment by williewillus** [comment]
Please refrain from screaming in your issue titles.

**Comment by CTMalens** [comment]
> Please provide the console log, this screenshot is basically no info.

**Comment by CTMalens** [comment]
@Hubry How do I access the console log?

**Comment by MelanX** [comment]
@CTMalens <minecraft directory>/logs/latest.log
