### ISSUE TITLE
Disable rank S, SS for picks.

### ISSUE THREAD

**Issue by MrLador** [Vazkii/Botania#3174]
Disable rank S, SS for picks!
I need to disable rank S, SS, and that the server can not withstand 4 or more players with such picks!
# Version Information
Minecraft 1.12.2
Forge version: 14.23.5.2847

**Comment by Alwinfy** [comment]
ok boomer

**Comment by Alwinfy** [comment]
(seriously, though: just set up an item-killer. that way a pick never *gets* to S-rank before getting shanked by it-- not without a *lot* more effort, at least)

**Comment by MrLador** [comment]
More precisely, you can explain where this can be done. I'm not very good at English.

**Comment by MrLador** [comment]
> (серьезно, хотя: просто установите элемент-убийца. таким образом, выбор никогда __добирается до S-ранга, прежде чем получить удар от него - не без _много_ больше усилий, по крайней мере)

More precisely, you can explain where this can be done. I'm not very good at English.

**Comment by MrLador** [comment]
> (seriously, though: just set up an item-killer. that way a pick never __gets to S-rank before getting shanked by it-- not without a _lot_ more effort, at least)

More precisely, you can explain where this can be done. I'm not very good at English.
