### ISSUE TITLE
How to get ItemStack In Baubles's GUI

### ISSUE THREAD

**Issue by alwaysForTop** [Vazkii/Botania#3175]
If there is an Botania's item in the slot provided by the Baubles mod, where should I get the item information from the api

Version Information
Minecraft 1.12.2
Forge version: 14.23.5.2847

**Comment by williewillus** [comment]
Using the baubles API
Also ask on discord for questions like this

**Comment by alwaysForTop** [comment]
`public static IInventory getBaubles(EntityPlayer player)
	{
		IBaublesItemHandler handler = player.getCapability(BaublesCapabilities.CAPABILITY_BAUBLES, null);
		handler.setPlayer(player);
		return new BaublesInventoryWrapper(handler, player);
	}`

Is this?
