### ISSUE TITLE
Rod of the plentiful mantle sparks have all the same color.

### ISSUE THREAD

**Issue by DasGerippe** [Vazkii/Botania#3178]
# Version Information
Forge version:  28.2.0
Botania version:  1.11-377

# Further Information
Steps to reproduce:
Use the Rod of the plentiful mantle and look around you. All sparks of all ores will have the same color (except for Redstone Ore and Activated Redstone Ore, which have each a different color).

What I expected to happen:
I expected the same behaviour as in 1.12 and lower: Sparks of different ores have different colors.

What happened instead:
All sparks (except those from redstone) have the same color.

![2020-01-28_23 13 41](https://user-images.githubusercontent.com/33161021/74593895-a7ace680-5030-11ea-8f4a-4dfed8e2c06f.png)

**Comment by Hubry** [comment]
Mojang, why does every block state with the same properties have the same hash code???
