### ISSUE TITLE
Force relays don't save the bound block upon quitting single player world

### ISSUE THREAD

**Issue by sug0** [Vazkii/Botania#3180]
# Version Information
Forge version:  28.2.0
Botania version:  Botania+r1.11-377
Minecraft version: 1.14.4

# Further Information
No game crashes to report.

Steps to reproduce:
Place a force relay, bind it to a block with a wand of the forest, save and exit the single player world, enter the world again, block is unbound.

What I expected to happen:
...

What happened instead:
...

**Comment by auxiliary-character** [comment]
Cannot reproduce on `162519d`
[Video](https://youtu.be/100cJ7Bng5UP)

**Comment by sug0** [comment]
Correct, it seems the issue is with the mod [YAMDA](https://www.curseforge.com/minecraft/mc-mods/yamda), after further testing. The chunks mustn't be properly saved. :|

**Comment by sug0** [comment]
Sorry for the confusion, the issue can be closed.
