### ISSUE TITLE
my game crach when i place a flower of botania 

### ISSUE THREAD

**Issue by doum855** [Vazkii/Botania#3184]
# Version Information
Forge version:  14.23.5.2847
Botania version:  1.12.2 r1.10-363

# Further Information
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)\
---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  Quark Plugin (Quark-r1.6-177.jar)
Contact their authors BEFORE contacting forge

// There are four lights!

Time: 2/19/20 8:31 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at vazkii.botania.common.block.subtile.generating.SubTileRafflowsia.onUpdate(SubTileRafflowsia.java:56)
	at vazkii.botania.common.block.tile.TileSpecialFlower.func_73660_a(TileSpecialFlower.java:103)
	at net.minecraft.world.World.func_72939_s(World.java:1838)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at vazkii.botania.common.block.subtile.generating.SubTileRafflowsia.onUpdate(SubTileRafflowsia.java:56)
	at vazkii.botania.common.block.tile.TileSpecialFlower.func_73660_a(TileSpecialFlower.java:103)

-- Block entity being ticked --
Details:
	Name: botania:specialflower // vazkii.botania.common.block.tile.TileSpecialFlower
	Block type: ID #930 (tile.specialFlower // vazkii.botania.common.block.BlockSpecialFlower // botania:specialflower)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (1270,70,-142), Chunk: (at 6,4,2 in 79,-9; contains blocks 1264,0,-144 to 1279,255,-129), Region: (2,-1; contains chunks 64,-32 to 95,-1, blocks 1024,0,-512 to 1535,255,-1)
	Actual block type: ID #930 (tile.specialFlower // vazkii.botania.common.block.BlockSpecialFlower // botania:specialflower)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1838)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: kkaaggiicc creatif
	All players: 1 total; [EntityPlayerMP['doum855'/815, l='kkaaggiicc creatif', x=1270.28, y=69.13, z=-137.56]]
	Chunk stats: ServerChunkCache: 985 Drop: 0
	Level seed: 3130606847719218205
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: {"diamondSize":8,"lapisCenterHeight":16,"lavaLakeChance":80,"redstoneMaxHeight":16,"diamondMaxHeight":16,"coalMaxHeight":128,"coalMinHeight":0,"seaLevel":63,"graniteCount":10,"riverSize":4,"gravelMinHeight":0,"graniteSize":33,"redstoneSize":8,"fixedBiome":-1,"waterLakeChance":4,"dioriteMinHeight":0,"andesiteCount":10,"graniteMaxHeight":80,"redstoneMinHeight":0,"lapisSize":7,"dirtCount":10,"ironMinHeight":0,"dioriteMaxHeight":80,"coalCount":20,"gravelCount":8,"coalSize":17,"gravelSize":33,"ironMaxHeight":64,"lapisSpread":16,"dioriteCount":10,"andesiteSize":33,"biomeSize":4,"graniteMinHeight":0,"goldCount":2,"diamondCount":1,"dirtSize":33,"gravelMaxHeight":256,"goldSize":9,"ironCount":20,"diamondMinHeight":0,"ironSize":9,"redstoneCount":8,"andesiteMinHeight":0,"dioriteSize":33,"goldMaxHeight":32,"dungeonChance":8,"andesiteMaxHeight":80,"dirtMinHeight":0,"lapisCount":1,"goldMinHeight":0,"dirtMaxHeight":256,"lowerLimitScale":512.0,"biomeDepthOffset":0.0,"upperLimitScale":512.0,"heightScale":684.412,"biomeScaleWeight":1.0,"biomeDepthWeight":1.0,"mainNoiseScaleZ":80.0,"mainNoiseScaleY":160.0,"depthNoiseScaleX":200.0,"mainNoiseScaleX":80.0,"baseSize":8.5,"depthNoiseScaleZ":200.0,"stretchY":12.0,"depthNoiseScaleExponent":0.5,"biomeScaleOffset":0.0,"coordinateScale":684.412,"useStrongholds":true,"useMineShafts":true,"useTemples":true,"useLavaOceans":false,"useCaves":true,"useWaterLakes":true,"useLavaLakes":true,"useMonuments":true,"useRavines":true,"useDungeons":true,"useVillages":true}
	Level spawn location: World: (176,64,256), Chunk: (at 0,4,0 in 11,16; contains blocks 176,0,256 to 191,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 35536 game time, 35536 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 115712 (now: false), thunder time: 17227 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 975674008 bytes (930 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 31 mods loaded, 31 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                  | Version      | Source                                        | Signature                                |
	|:------ |:------------------- |:------------ |:--------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft           | 1.12.2       | minecraft.jar                                 | None                                     |
	| LCHIJA | mcp                 | 9.42         | minecraft.jar                                 | None                                     |
	| LCHIJA | FML                 | 8.0.99.99    | forge-1.12.2-14.23.5.2847.jar                 | None                                     |
	| LCHIJA | forge               | 14.23.5.2847 | forge-1.12.2-14.23.5.2847.jar                 | None                                     |
	| LCHIJA | aether_legacy       | 1.4.4        | Aether-Legacy-Mod-1.12.2.jar                  | None                                     |
	| LCHIJA | appliedenergistics2 | rv6-stable-7 | appliedenergistics2-rv6-stable-7.jar          | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| LCHIJA | quark               | r1.6-177     | Quark-r1.6-177.jar                            | None                                     |
	| LCHIJA | autoreglib          | 1.3-32       | AutoRegLib-1.3-32.jar                         | None                                     |
	| LCHIJA | baubles             | 1.5.2        | Baubles-1.12-1.5.2.jar                        | None                                     |
	| LCHIJA | bigchungus          | 2.0.0        | BigChungusv2.jar                              | None                                     |
	| LCHIJA | botania             | r1.10-363    | Botania+r1.10-363.jar                         | None                                     |
	| LCHIJA | chickens            | 6.0.4        | chickens-6.0.4.jar                            | None                                     |
	| LCHIJA | cucumber            | 1.1.3        | Cucumber-1.12.2-1.1.3.jar                     | None                                     |
	| LCHIJA | fastleafdecay       | v14          | FastLeafDecay-v14.jar                         | None                                     |
	| LCHIJA | gardenofglass       | sqrt(-1)     | GardenOfGlass.jar                             | None                                     |
	| LCHIJA | grimoireofgaia      | 1.7.1        | GrimoireOfGaia3-1.12.2-1.7.1.jar              | None                                     |
	| LCHIJA | kagic               | X11p13       | kagic-X11p13.jar                              | None                                     |
	| LCHIJA | lost_aether         | 0.1.2        | lost_aether-content-1.12.2-0.1.2.jar          | None                                     |
	| LCHIJA | morechickens        | 3.1.0        | morechickens-1.12.2-3.1.0.jar                 | None                                     |
	| LCHIJA | llibrary            | 1.7.19       | llibrary-1.7.19-1.12.2.jar                    | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJA | mowziesmobs         | 1.5.4        | mowziesmobs-1.5.4.jar                         | None                                     |
	| LCHIJA | multimob            | 1.0.5        | multimob-1.0.5.jar                            | None                                     |
	| LCHIJA | mysticalagriculture | 1.7.5        | MysticalAgriculture-1.12.2-1.7.5.jar          | None                                     |
	| LCHIJA | neat                | 1.4-17       | Neat+1.4-17.jar                               | None                                     |
	| LCHIJA | oreexcavation       | 1.4.129      | OreExcavation-1.4.129.jar                     | None                                     |
	| LCHIJA | primitivemobs       | 1.2.3a       | primitivemobs-1.2.3a.jar                      | None                                     |
	| LCHIJA | quarkoddities       | 1            | QuarkOddities-1.12.2.jar                      | None                                     |
	| LCHIJA | rejuv               | 1.0          | rejuvenate-1.1.jar                            | None                                     |
	| LCHIJA | roguelike           | 1.8.0        | RoguelikeDungeons-1.12.2-1.8.0.jar            | None                                     |
	| LCHIJA | twilightforest      | 3.10.1013    | twilightforest-1.12.2-3.10.1013-universal.jar | None                                     |
	| LCHIJA | youwinbutton        | 1.0.0        | youwinbutton-1.0.0.jar                        | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
Quark Plugin (Quark-r1.6-177.jar)
  vazkii.quark.base.asm.ClassTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	AE2 Version: stable rv6-stable-7 for Forge 14.23.5.2768
	AE2 Integration: IC2:OFF, RC:OFF, MFR:OFF, Waila:OFF, InvTweaks:OFF, JEI:OFF, Mekanism:OFF, OpenComputers:OFF, THE_ONE_PROBE:OFF, TESLA:OFF, CRAFTTWEAKER:OFF
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['doum855'/815, l='kkaaggiicc creatif', x=1270.28, y=69.13, z=-137.56]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

Steps to reproduce:
1. First step take a comand block 
2. Second step place the sqpeatial flower block 
3. etc...

What I expected to happen:crach the game 

What happened instead:maybe not crach the game

**Comment by williewillus** [comment]
1.12 is unsupported
to work around this use the forge option "remove erroring tile entities" and restart the game
