### ISSUE TITLE
Shard of Laputa can place water in the Nether

### ISSUE THREAD

**Issue by auxiliary-character** [Vazkii/Botania#3188]
# Version Information
Forge version:  28.2.0
Botania version:  r1.11 378

# Further Information

Steps to reproduce:
1. Place a stair block and waterlog it in the overworld
2. Build a nether portal a good distance directly above it (out of range of the shard)
3. Use the Shard of Laputa
4. Go to the nether

The waterlogged stair should appear in the Nether.

https://www.youtube.com/watch?v=Ah92rtHdnlw

What I expected to happen:
Water in the nether is illegal

What happened instead:
https://www.youtube.com/watch?v=XeDM1ZjMK50

**Comment by williewillus** [comment]
how do you even find this stuff lol
