### ISSUE TITLE
Force relays (and connected blocks) do not move entities.

### ISSUE THREAD

**Issue by n-Holmes** [Vazkii/Botania#319]
The title is hopefully self explanatory.  When a block is moved via its binding to a force relay, it does not interact with entities as if a piston had pushed it.  This means that blocks pushed into mobs will suffocate them, lifts will not work, nor will any other frame machine that has to carry an entity.  Oddly, this behaviour is also exhibited by the force relay block itself, when pushed by a piston.

**Comment by SevereOverfl0w** [comment]
This looks like it will land in 1.14.x? https://github.com/MinecraftForge/MinecraftForge/pull/5798 Is it worth reopening this issue?

**Comment by williewillus** [comment]
that would only fix it for the relay itself, not for the moved block

**Comment by SevereOverfl0w** [comment]
Is that because there's no way to push a block as if by piston without a fake piston?
