### ISSUE TITLE
Can't critical-hit with sashes on

### ISSUE THREAD

**Issue by Alwinfy** [Vazkii/Botania#3190]
Steps to reproduce:
1. Grab a diamond axe
2. Jump and hit a mob as you're falling (mob should take 150% and throw off crit particles)
3. Grab a full mana ring and Planestrider's Sash, equip both
4. Jump and hit a mob as falling again

What I expected to happen: Critical hit

What happened instead: nop

**Comment by Alwinfy** [comment]
Update: Pretty sure the crit code actually checks `fallDistance > 0`, and the sashes set `fallDistance` negative to achieve their effects. Not sure how to fix.

**Comment by Alwinfy** [comment]
bump

**Comment by Hubry** [comment]
Can't seem to repro on 1.16.2, probably no longer an issue
