### ISSUE TITLE
Gourmaryllis not eating items from open crate

### ISSUE THREAD

**Issue by jason-pollak** [Vazkii/Botania#3193]
# Version Information
Forge version:  28.2.1 (MC 1.14)
Botania version:  r 1.11-378

# Further Information
Link to crash log: **Not a crash!**
Steps to reproduce:
1. Place gourmaryllis, connected to spreader of choice
2. place open crate in the 3x3 blocks around it, a few blocks up
3. hopper items into the crate to drop into the flower's eat range

What I expected to happen:
Flower eating the food

What happened instead:
Flower did not eat the food.
![2020-02-28_15 39 22](https://user-images.githubusercontent.com/45409046/75595448-509c0e00-5a41-11ea-8fc7-73c54497d8e5.png)
![2020-02-28_15 39 30](https://user-images.githubusercontent.com/45409046/75595452-5560c200-5a41-11ea-9686-0e2faf3c360f.png)
The flower **does** eat the food when it's thrown by a player- it only fails to activate when the item is dropped by an open crate
![2020-02-28_15 39 42](https://user-images.githubusercontent.com/45409046/75595453-55f95880-5a41-11ea-81fa-591538024328.png)

**Comment by Alwinfy** [comment]
Is the open crate receiving redstone power?

From the Lexica page:
> An interesting side-effect of the Open Crate's construction is that, when given a redstone signal, any items it drops won't be picked up by flowers like the Hopperhock, Rannuncarpus, or Pollidisiac for around ten seconds longer than they otherwise would.

**Comment by jason-pollak** [comment]
Yep, that was it! Sorry for taking the time to post an issue- I'll take another look at the lexica next time!
