### ISSUE TITLE
Being shot by a skeleton has a chance to crash the game

### ISSUE THREAD

**Issue by RevenantWendigo** [Vazkii/Botania#3197]
# Version Information
Forge version:  1.15.2 / 31.1.18
Botania version:  Botania_r1.11-1a303f8bd

# Further Information
Link to crash log: https://pastebin.com/V7VLKK2v
Steps to reproduce:
1. Get shot by a skeleton
2. Game has a chance to crash

What I expected to happen: Not crash

What happened instead: The game crashes immediately after being hit by an arrow.

**Comment by williewillus** [comment]
d3959c1
