### ISSUE TITLE
Crash when minecart lands on spectral rail after launching from spectral rail

### ISSUE THREAD

**Issue by thenewdreamer** [Vazkii/Botania#3199]
# Version Information
Forge version:  28.2.0
Botania version:  r1.11-378

crash log: https://hastebin.com/doraraqusa.pl

setup to reproduce: ![rails](https://user-images.githubusercontent.com/45403659/76046602-56f12500-5f2e-11ea-9b84-5b0f579441a4.png)

**Comment by williewillus** [comment]
ed1005b
