### ISSUE TITLE
Crash when killing a mob

### ISSUE THREAD

**Issue by UnRealDinnerbone** [Vazkii/Botania#3201]
# Version Information
Forge version:  1.15.2-31.1.18
Botania version:  Botania_r1.11-1a303f8bd.jar (Beta Discord Build)

# Further Information
Link to crash log: https://pastebin.com/wYqvZAK1
Steps to reproduce:
Happens when you hit/kill a mob with enhanced amour. It might be anyone mob at random but I was unable to tell for sure, last time It happened it was a mob with enchanted armor 

What I expected to happen: For the server not to crash

What happened instead: The server crashes

**Comment by williewillus** [comment]
fixed inthe next beta
