### ISSUE TITLE
Constantly damaged after defeating Gaia Guardian

### ISSUE THREAD

**Issue by Wakatsu** [Vazkii/Botania#3202]
# Version Information
Forge version:  Minecraft Forge 1.12.2
Botania version:  Botania+r1.10-363

# Further Information
Link to crash log: game doesn't crash so no crashreport generates
Steps to reproduce:
1. Fight Gaia Guardian (level of the GG doesn't matter)
2. Don't die to him

What I expected to happen:
Defeat GG, get my loot, continue playing

What happened instead:
Every time I defeat GG I become unable to heal back to full, as whenever my HP reaches full I start take damage from unknown sourse until my HP becomes not full again. This thing doesn't represent itself as debuf or status effect, it does not go away if I drink milk, the only way to get rid of it is to die, but then any new fight with GG will make it happen again.

**Comment by williewillus** [comment]
This does not sound like a botania bug, there's probably another mod interfering with things.
Also, 1.12 is eol so please reproduce in 1.14

**Comment by Wakatsu** [comment]
What does "eol" mean?
I don't play 1.14, there's nothing interesting out there for this version

**Comment by williewillus** [comment]
= not being supported

**Comment by Wakatsu** [comment]
Aw... well, this is it for me, then, since I have no intention to move to newer versions of minecraft. Thanks for your time anyway, and sorry for bothering you.

**Comment by williewillus** [comment]
I would check your other mods for conflicts, I've never heard of something like this before
