### ISSUE TITLE
Force relay unbind after exiting my singlplayer world 1.14.4

### ISSUE THREAD

**Issue by Alexanderr1989** [Vazkii/Botania#3205]
Forge version:  1.14.4-forge-28.2.0
Botania version:  Botania+r1.11-378

The force relay loses contact with the block after leaving the single player world. I tried to delete all other modifications, but it didn't solve the problem.

**Comment by Jesse-Goertzen** [comment]
Also having this issue, same version of Botania but using Forge 28.2.3.

**Comment by CrisDaumas** [comment]
Same issue here. Binding is removed for both mana warping and piston pushing.
