### ISSUE TITLE
Bowl of Water renders incorrectly

### ISSUE THREAD

**Issue by SleepyEmber** [Vazkii/Botania#3211]
# Version Information
Forge version:  31.1.19
Botania version:  1.11-9fb509e

# Further Information
What I expected to happen: Bowl of Water to render properly

What happened instead: Bowl of Water is slightly overfilled.

![28444baba385354f6c13e0ce9720c900](https://user-images.githubusercontent.com/18420537/76673519-4ec36600-657c-11ea-8247-500811e64606.png)

**Comment by williewillus** [comment]
fixed by a new texture
