### ISSUE TITLE
Crash when placing Mana Spreader with Rannuncarpus.

### ISSUE THREAD

**Issue by eutropius225** [Vazkii/Botania#3215]
# Version Information
Forge version:  -
Botania version:  -

# Further Information
Causes NullPointerException [here](https://github.com/Vazkii/Botania/blob/ad7666e66817a7b49a5dda3aeb7b99e93dce53e1/src/main/java/vazkii/botania/common/block/mana/BlockSpreader.java#L78) for probably unsurprising reasons.
Steps to reproduce:
1. place Rannuncarpus
2. throw mana spreader
3. wait
4. crash

What I expected to happen:
no crash

What happened instead:
crash

Is a crash log necessary?

**Comment by williewillus** [comment]
this is why we need strong null-safety

**Comment by eutropius225** [comment]
[Crash Report](https://gist.github.com/eutropius225/b4d9e430d14928376377bf4a54e11716)
