### ISSUE TITLE
Lexica Botania book issue

### ISSUE THREAD

**Issue by LoverSpirit** [Vazkii/Botania#3216]
#Version Information
Forge version: 1.14.4 forge 28.2.1
Botania version: Botania+r1.11-378

My issue is, when I open the Lexica Botania it shows up like this: ![Minecraft 1 14 4 2020-03-20 00_57_40](https://user-images.githubusercontent.com/62414394/77138137-1f629c80-6a47-11ea-9e20-6e083db98342.png) 
Weirdly enough, all the text is replaced by squares. I removed all the mods except Botania (and the dependencies) and all the texture packs so I know it's not a mod, texture pack or font conflict. 

Could you please help me understanding what causes this and how to fix this?

**Comment by williewillus** [comment]
redirecting to https://github.com/Vazkii/Patchouli/issues/197
