### ISSUE TITLE
[1.15.2] Broken recipes in book/JEI

### ISSUE THREAD

**Issue by 016Nojr** [Vazkii/Botania#3217]
# Version Information
Forge version:  31.1.23
Botania version:  r1.11-2399745

Issue appearing on Forgecraft:
Recipe information in the Lexica Botania and JEI is broken, showing other items unrelated to the crafting, but the "correct" recipe (that isnt shown) does work. 

![Skjermbilde](https://user-images.githubusercontent.com/8192699/77250320-80f15980-6c47-11ea-8a3b-1a19d519004f.PNG)

**Comment by williewillus** [comment]
Fixed by the json migration

**Comment by GordonHollow** [comment]
Have the same problem in 1.14.4 version. Installed last version of Botania available in this version. Is this fix 1.15.2 version only? Chanse to back port just this fix?
