### ISSUE TITLE
Spreader misfire

### ISSUE THREAD

**Issue by Lunar-Rose** [Vazkii/Botania#3220]
# Version Information
Forge version:  1.14.4-Forge- 28.2.3
Botania version:  Botania+r1.11-378

# Further Information
Link to crash log: No Crash Log
Steps to reproduce:
1. First step - Set up flowers
2. Second step - Link the flowers to a Mana Spreader
3. Third step - Link Spreaders to Mana Pool

What I expected to happen: I expect the Spreaders to shoot Mana into the Mana Pools

What happened instead: The Spreaders shoot Mana off into the air
![Screenshot_38](https://user-images.githubusercontent.com/40038523/77478130-18d77a80-6de3-11ea-95bf-5e91c5b4a35e.png)
![Screenshot_39](https://user-images.githubusercontent.com/40038523/77478133-1aa13e00-6de3-11ea-8c80-f75c8f0aae7a.png)

**Comment by Lunar-Rose** [comment]
wait I think I found out the issue, something in the coding of mana shots or coding in the torches I ham using was changed, either way the interdiction torches from project E now affects them, I only got the idea to test it after I posted this. Either way it was fixed by removing said torches and the mana is shooting properly now

**Comment by williewillus** [comment]
bump (stale should autoremove on bump now?)
