### ISSUE TITLE
[1.15.2] Player Head creation broken

### ISSUE THREAD

**Issue by 016Nojr** [Vazkii/Botania#3221]
Player head creation recipe is not starting. Tried naming the nametag "Soaryn" and his UUID. Just shows the red X

Botania: r1.11-2399745
![Soaryn](https://user-images.githubusercontent.com/8192699/77494747-d34c9900-6e46-11ea-9383-12ad25ae4ce7.PNG)

**Comment by Alwinfy** [comment]
It needs mana, like any other Runic Altar recipe.
Feed enough mana, toss a livingrock, and Forest-Wand to get head

**Comment by Hubry** [comment]
Couldn't reproduce locally in SP or MP, and this looks exactly like what Alwinfy said - no mana. If the recipe isn't detected at all, it doesn't show an X/result, only the input items. I can't see a spreader in this screenshot anywhere.

**Comment by 016Nojr** [comment]
Botania updated to: r1.15-379
I can confirm there is mana present
![mana](https://user-images.githubusercontent.com/8192699/77619797-433b4c00-6f39-11ea-9d1d-3e89a3ba83d5.PNG)
![recipe](https://user-images.githubusercontent.com/8192699/77619804-46ced300-6f39-11ea-9675-8f22331e21d7.PNG)

Gonna do some digging on my own as well, could just be that another mod is messing with Botania.

**Comment by Alwinfy** [comment]
I'm pretty sure the fifth ingredient is pixiedust, not a corporea funnel

**Comment by williewillus** [comment]
if you're on forgecraft, the recipes are messed up clientside.

**Comment by 016Nojr** [comment]
Can confirm it's working with pixie dust. Same issue as #3217
