### ISSUE TITLE
Rannuncarpus Crash and somehow placing infinite spreaders

### ISSUE THREAD

**Issue by phit** [Vazkii/Botania#3222]
# Version Information
Forge version:  28.2.3
Botania version:  r1.11-378

# Further Information
Crash report
https://gist.github.com/phit/cc7ee75c0d8aa9da59acede9614b5afe

Somehow one of my players made it place mana spreaders, and it crashed with above log, when i enabled removing erroring tile entities in Forge that same log spammed the console and this is what the player saw. Once they broke the Rannuncarpus it was fine
![](https://cdn.discordapp.com/attachments/285214752173457409/692465274586136676/unknown.png)

edit: player said they had broken a mana spreader near it right before the server crashed, so i guess it decided a spreader was a valid thing to place down

**Comment by williewillus** [comment]
same cause as #3215, fixed in next release
