### ISSUE TITLE
Throwing Diamonds into mana pool makes diamonds disappear 

### ISSUE THREAD

**Issue by Grimmhert** [Vazkii/Botania#3226]
# Version Information
Forge version:  Used TL launcher Forged optifine 1.14.4
Botania version:  Botania r1.11-378.jar

# Further Information

What I expected to happen: Will receive mana coated diamond

What happened instead: Nothing instead, the diamond disappear, there wan an animation but then nothing.

**Comment by williewillus** [comment]
something probably picked it up. try in a clear area with no items or blocks from other mods around.

**Comment by elowanut** [comment]
Just to add to what Williewillus said here, when I first installed Silent's Gems, I had this same problem. Turns out I just wasn't paying attention to my Gem Pouch from that mod, which was auto-picking up the Mana Diamonds. Check all of your inventories and sub-inventories.
