### ISSUE TITLE
[1.14.4] Crash on startup with Immersive Railroading

### ISSUE THREAD

**Issue by ToMe25** [Vazkii/Botania#3227]
# Version Information
Minecraft 1.14.4
Forge 28.2.3/28.2.1/28.2.0
Track API 1.2
Immersive Railroading 1.7.3
Curios 1.0.6.1
Patchouli 1.1-26
Botania r1.11-378

# Further Information
Link to crash log: [latest.log](https://pastebin.com/qp8FEYqB)
Immersive Railroading Issue: TeamOpenIndustry/ImmersiveRailroading#753

What I expected to happen:
The game starts.

What happened instead:
The game crashed.

**Comment by williewillus** [comment]
does it crash if you go back to 28.2.1 or earlier?

**Comment by ToMe25** [comment]
yes, i just tested it with forge 28.2.1 and 28.2.0 both crash with the same crash-report.

**Comment by williewillus** [comment]
see my comment on the IR ticket. Nothing we can do here really.
