### ISSUE TITLE
Lan player sees manasteel pick torch indicator of connected client

### ISSUE THREAD

**Issue by AlexProGear** [Vazkii/Botania#3228]
Steps to reproduce:
Lan player hosts server
Client joins
Client uses RMB with manasteel pickaxe and torches in inventory and sees torch count indicator
Lan player (host) also sees connected player's torch count

Probably, something to do with client/server splitting, because problem doesn't appear for dedicated server.

**Comment by williewillus** [comment]
fixed in 1.15 (coming soon tm)
