### ISSUE TITLE
[1.14.4] Crash on startup when using forge 28.2.3

### ISSUE THREAD

**Issue by Dakedres** [Vazkii/Botania#3229]
# Version Information
Forge version: 28.2.3
Botania version: r1.11-378

# Further Information
Link to crash log: [here](https://gist.github.com/Dakedres/c91b9828b04cde7b9f837fa7f1e170d4)

**Comment by Hubry** [comment]
This is the classic "something errored earlier and Forge stops everything but this event for some reason" crash. Please provide a full console log (`debug.log` from the `logs` folder, or `latest.log` if that's not present).

**Comment by Dakedres** [comment]
I'll get to it as soon as I can

**Comment by KillerVenomDD** [comment]
I have actually had the same problem with servers crashing on start.  I believe its also 28.2.3 version of forge.

**Comment by Dakedres** [comment]
For some reason this just--stopped erroring, I've tried to recreate it to no avail, but when it *was* happening, I knew for sure disabling Botania fixed it. Probably some elusive inter-mod crash. I've tried searching the logs for the one where the crash occurred to no success. Sorry about all this.

**Comment by da3dsoul** [comment]
I'm having this issue, but it's only with Optifine installed.
