### ISSUE TITLE
(1.12.2) Terrasteel armor is too op.

### ISSUE THREAD

**Issue by TobiasMJC** [Vazkii/Botania#3230]
# Version Information
Forge version:  2847
Botania version:  r1.10 361

I'm playing on a server with friends, I just did my terrasteel armor and I saw that my armor is too op, like x2 or x3 better than diamond. 
Is that normal?, in 1.7.10 that never happened to me.

Sorry for my bad english, and thanks.

**Comment by williewillus** [comment]
this is just the result of vanilla's armor rebalancing in 1.9, nothing to do with botania really.
also, 1.12 is unsupported.
