### ISSUE TITLE
[1.15.2] Loading screen foir Mojang stuck on reloading

### ISSUE THREAD

**Issue by dreckz** [Vazkii/Botania#3233]
-->
# Version Information
Forge version:  31.1.36
Botania version:  r1.11-378

# Further Information
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)\
Steps to reproduce:
1. Load up a Modpack with botania and patchouli
2. While the loading screen happens, it continues to loop of loading

What I expected to happen:

For the modpack to load up properly

What happened instead:

It looped in a feedback loop on the loading screen.

Suspected Problem:
https://paste.gg/p/anonymous/d38a164fb0b64c40abdea16ade81864a
Full Log:
[latest.log](https://github.com/Vazkii/Botania/files/4440024/latest.log)

**Comment by williewillus** [comment]
>  Botania version: r1.11-378
this is the 1.14 build of botania, my dude

**Comment by williewillus** [comment]
use build 382+
