### ISSUE TITLE
Botania manapool Tick error

### ISSUE THREAD

**Issue by Lancten** [Vazkii/Botania#3239]
# Version Information
Forge version:1.12.2 - 14.23.5.2847 
Botania version:  1.10-361

# Further Information
Link to crash log: https://pastebin.com/qTT7i8iQ
Steps to reproduce: ( honestly I don't know how the people in my server got this. I can't reproduce the error ) But I can give you a description of what they tried to do.
1. First step They made a mana farm,

What I expected to happen:
THey expected it to work with no problems
What happened instead:
It crashed there Minecraft, with that error.

**Comment by williewillus** [comment]
see #2205
