### ISSUE TITLE
Rod of the Shaded Mesa does not pick up entities

### ISSUE THREAD

**Issue by Tsukreya** [Vazkii/Botania#3242]
# Version Information
Forge version: 1.15.2-forge-31.1.43
Botania version:  Botania+r1.15-382

Singleplayer, no other mods except latest **Patchouli** (Patchouli-1.15.2-1.2-31) 
and **Curios API** (curios-FORGE-1.15.2-2.0.2.1)

# Further Information
Steps to reproduce:
1. Get into creative on a new singleplayer world
2. Spawn a full mana tablet/band and the Rod of the Shaded Mesa
3. Try to right click an entity

What I expected to happen: The entity should be picked up and held untill I release right click, as the Lexica Botanica says

What happened instead: The entity is launched away from the player, without taking damage. The rod also swings on it's own. It is possible to damage the entity by left clicking just after right clicking, suggesting that the holding of the entity is somehow cut short.

**Comment by Hubry** [comment]
Cause: Mojang made using any item for any reason actually swing the hand, as opposed to using items on blocks + a bunch of explicit cases. And the code of the rod is largely unchanged since creation, which means it uses the swing state to detect when to launch the entity.
