### ISSUE TITLE
Wand of the Forrest makes it easier to pull off Vanilla Bedrock Removal glitch

### ISSUE THREAD

**Issue by auxiliary-character** [Vazkii/Botania#3246]
# Version Information
Forge version:  31.41.1
Botania version:  r.1.15-382
Garden of Glass version: 1.2 (from curseforge, not discord)

# Further Information
Vazkii said to report this, but idk, seems fine to me tbh.

Steps to reproduce:
[video](https://youtu.be/NgXX6AxSYWw)

What I expected to happen:
I pretty much expected what happened. But idk, maybe vazkii doesn't want the piston base to rotate when it's extend or something like that.

What happened instead:
It works fine.

**Comment by Vazkii** [comment]
ok

**Comment by Awesomespore** [comment]
boomer

**Comment by eutropius225** [comment]
Duplicate of #3223.

**Comment by williewillus** [comment]
^
