### ISSUE TITLE
Corporea Spark max distance is 8, not 12 as stated in the docs

### ISSUE THREAD

**Issue by sclemens** [Vazkii/Botania#3249]
# Version Information
Forge version:  28.2.1 (Minecraft 1.14.4)
Botania version:  1.11-377

# Further Information
I've been establishing a corporea network to connect a storage network up to some Botania automation. In the Lexica Botanica, this is stated to have a range of "around 12 blocks" but in practice, there is a max distance of 8 blocks.

This is confirmed with right-click (and hold) on the corporea node. 8 blocks shows a link, and 9 blocks does not.

Note - I have just confirmed the same documentation in 1.15-382 (Forge 31.1.41 - Minecraft 1.15.2) and same limitation.

Is this expected, or should we still be at 12 blocks distance for corporea sparks?

**Comment by Hubry** [comment]
Looks like the author of #3067 confused the 12 block range of normal Sparks and the 8 block range of Corporea Sparks.
