### ISSUE TITLE
Gaia's Head "becomes gorgon head" when worn by a player

### ISSUE THREAD

**Issue by Apot98** [Vazkii/Botania#3251]
# Version Information
Forge version:  1.15.2-forge-31.1.44
Botania version:  Botania+r1.15-382

# Further Information
Link to crash log: https://gist.github.com/Apot98/f355d3da06d4f0755bd10d506ae60166
Steps to reproduce:
1. grab a gaia's head, and try to put it on your head;
2. have a friend to try observing your new trophy, or press f5 to watch it yourself;
3. Crash!

What I expected to happen: Gaia's head behaves normal like vanilla skulls

What happened instead: client crashes when trying to render the player on your client

**Comment by Hubry** [comment]
313b0fb0a246f2eddb8c4c68078bbeab702845e1 finished the fix
