### ISSUE TITLE
End Air is only obtainable by right-clicking blocks in the End

### ISSUE THREAD

**Issue by Brycey92** [Vazkii/Botania#3265]
# Version Information
Forge version:  14.23.5.2838
Botania version:  r1.10-363

# Further Information
Steps to reproduce:
1. Go to the End
2. Right click in the air with a glass bottle
3. Observe nothing happens
4. Right click on a piece of end stone
5. Observe you obtain end air

It's notable that this was only tested in the Galaxy-Craft Lite modpack, and not with Botania alone.

What I expected to happen:
Step 2 should produce end air, as the lexica entry states.

What happened instead:
Only step 4 produces end air.

**Comment by elowanut** [comment]
I believe this is implemented this way (and it's been this way for a long time, it's not a recent change) in order to prevent a conflict with the gathering of Dragon's Breath.

**Comment by Brycey92** [comment]
I think this actually causes a partial conflict with gathering dragon's breath, as sometimes when right clicking the breath, I grab the actual breath, but most of the time I just get end air.

In any case, if this is the intended behavior, the lexica entry should be updated so people know how to get end air.

**Comment by Hubry** [comment]
Grabbing dragon's breath works by standing in a certain range around the area effect cloud entity's bounding box. The new ender air behavior uses basically the same check, but inverted and with a bit wider range, giving you a small deadzone if you get close to the cloud. Old behavior is literally just "if you right clicked a block, it makes ender air".

Clicking on breath doesn't make any difference, the player position is what matters. Anyways, if this is a problem, we could extend the deadzone around dragon's breath clouds, but this behavior is definitely an improvement over the old unclear one.

**Comment by Brycey92** [comment]
Ah, which version of Botania was that implemented in? I'm running r1.10-363 on MC 1.12.2, and the old method sounds a lot more like what I'm experiencing.

**Comment by Hubry** [comment]
r1.15-383 for 1.15, released yesterday. The closing thing was a commit changing this behavior. I didn't even notice that you were on 1.12 :P (which we don't really support anymore, sorry for no backport)

**Comment by Brycey92** [comment]
Damn, alright. Thanks for letting me know! I'll backport the commit myself when I have time. The commit in question: https://github.com/Vazkii/Botania/commit/52c27fcc5154866273be59330408b4d59b37c354

**Comment by Brycey92** [comment]
I made a PR #3300 which backports your fix to 1.12.2.
