### ISSUE TITLE
The same problem with recipe in Book\JEI [1.14.4]

### ISSUE THREAD

**Issue by GordonHollow** [Vazkii/Botania#3266]
Fixed by the json migration

_Originally posted by @williewillus in https://github.com/Vazkii/Botania/issues/3217#issuecomment-608012638_

Have the same problem in 1.14.4 version. Installed last version of Botania, Forge and Patchouli available in this version. Is this fix 1.15.2 version only? Any chance to back port just this fix?

**Comment by williewillus** [comment]
the json migration was a massive undertaking that just happened to fix that bug as a side effect. Backporting it to 1.14 isn't really feasible

**Comment by GordonHollow** [comment]
Okay, so it's fixed only 1.15.2, just waiting Create port to 1.15.2.

Also this bag happens only server play, singleplayer works fine

**Comment by GordonHollow** [comment]
1.14.4 still not fixed, 1.15.2 works fine. Probably patchouli issue
