### ISSUE TITLE
Rannicarpus peculiarities not in documentation. 

### ISSUE THREAD

**Issue by jgilmore** [Vazkii/Botania#3267]
# Version Information
Forge version:  14.23.5.2847
Botania version:  1.10-362

What I expected to happen:
Flower should place blocks

What happened instead:
Flower does not place blocks until the dropped stops dropping. 

This would be so hair-tearingly annoying if there was any documentation on it.
To get an automated flower to work with a hopper, open crate, and chest, it is required to turn Hopper off completely. Flower does not function otherwise until a complete 64 stack has been dropped. And then it only has a small window before the hoppercock picks it up.

If this is continuous, there's no problem, but if there's only a small window of time to place the blocks, it becomes flat out impossible. I had to increase the time window from ten seconds to thirty, and that *still* wasn't enough. Perhaps with more precise control of the hopper?

Either fix this (allow them to pick up incomplete stacks) out for heaven's sake, ADD IT TO THE DOCUMENTATION.

**Comment by DoomRater** [comment]
If I recall there is a section on soils changing the delay order of operations of flowers.  Try using that to make the hopperhock wait.
