### ISSUE TITLE
Planting in a flowerpot creates invalid item

### ISSUE THREAD

**Issue by arancaytar** [Vazkii/Botania#3272]
# Version Information
Forge version:  14.23.5.2846
Botania version:  r1.10-361

(Part of modpack FTB Revelation, full mod list in this gist: https://gist.github.com/arancaytar/0287f80606f2099f5663931812bab95d)

# Further Information
Steps to reproduce:
1. Place a flower pot in the world
2. Right-click the flower pot while holding a Botania flower (Pure Daisy in this case)
3. Right click the flower pot again.

What I expected to happen:
* Either nothing would happen, or the flower would be inserted and retrieved correctly.

What happened instead:
* The flower was inserted (texture was of a vanilla red flower)
* On retrieval, the flower became a "Miscellaneous Flower"
* Achievement "Take it Easy" was awarded.

**Comment by williewillus** [comment]
unfortunately the 1.12 version is no longer supported. this bug shouldn't be present in higher versions of minecraft, though
