### ISSUE TITLE
Keep getting booted on death from akliz server, botania is blamed

### ISSUE THREAD

**Issue by cooperhammond** [Vazkii/Botania#3274]
# Version Information
Forge Mod Loader version: 8.0.99.99
Minecraft Forge version: 14.23.5.2847
Botania version:  r1.10-363

# Further Information
Link to crash log: https://paste.dimdev.org/begefuyore.mccrash
Steps to reproduce:
1. If you're willing, get an Akliz server
2. Load the 1.12.2 pack
3. Enter the game (I'm assuming) and die. Me and my brother didn't notice this problem until a day after we started the server, but now occasionally when we join we get booted with botania blamed, and when we die we always get booted with it blamed.

If this isn't a problem with botania, it's probably a problem with my server, but I'd figured I'd raise an error if there was something the team wasn't aware of. Thanks

**Comment by williewillus** [comment]
this is #2205
