### ISSUE TITLE
Visual Glitch while Botanical Brewery is in Use (Valhelsia 2 pack v2.1.7)

### ISSUE THREAD

**Issue by Crimdos** [Vazkii/Botania#3277]
# Version Information
Forge version:  31.1.49
Botania version: r1.15-382 

Botanical Brewery producing visual glitches when in use, both with a vial and tainted blood pendant. If the spreader is pointed at it with nothing brewing, nothing happens. The lights are slightly similar to the particles produced by the brewery. I am on a multiplayer server.

Setup image:
![Brewery_setup](https://user-images.githubusercontent.com/64765237/80936188-07986b00-8d9e-11ea-8c7d-677feff10c0d.JPG)

Glitch image:
![brewery_graphical_glitch](https://user-images.githubusercontent.com/64765237/80936199-0f580f80-8d9e-11ea-87b0-374c7e528279.JPG)

**Comment by williewillus** [comment]
update botania
