### ISSUE TITLE
Runic Alter Broke My Furnace

### ISSUE THREAD

**Issue by funyy** [Vazkii/Botania#3278]
Forge version: 1.15.2-forge-31-1-63 
Botania version: Botania-r1.15-383.jar  

Steps to reproduce:
1. First step: craft runic alter
2. Second step: place runic alter
3. Third step: fuel side of the furnace should not accept coal

What I expected to happen: to make iron ingots 
What happened instead: nothing :/

**Comment by williewillus** [comment]
...what?

**Comment by williewillus** [comment]
I have no idea how your steps and your expectation are tied together in any way
