### ISSUE TITLE
Crash on world open after using Rod of the Skies. (Modern Skyblock 3 modpack).

### ISSUE THREAD

**Issue by boimakillu** [Vazkii/Botania#3280]
# Version Information
Forge version:  14.23.5.2811
Botania version:  r1.10-363

# Further Information
[Link to crash log](https://hastebin.com/hafodoxina.rb)
Steps to reproduce:
1. Launch Modern Skyblock 3, from twitch launcher.
2. Open my world, on which I have used the Rod of the Skies.
3. Profit.... ?

What I expected to happen:
I go fwoosh and fly like a cool man.
What happened instead:
It freezes on Loading World: 0%, sometimes it crashes immediately, and sometimes it goes to 0% CPU usage and I need to kill it.

Thanks for any help!

**Comment by boimakillu** [comment]
Also, I've seen that this may be related to an out of date 'Botania API', but I have no idea how I would update it. And I feel it may be a mod conflict instead. Not sure. Any help would be appreciated.

**Comment by williewillus** [comment]
try updating any mods that have botania integration
