### ISSUE TITLE
Impossible to reset origin with Ring of Loki

### ISSUE THREAD

**Issue by riskable** [Vazkii/Botania#3281]
# Version Information
Forge version:  
Botania version: R1.11-379  

# Further Information
Steps to reproduce:
1. Shift-right-click some block, bare-handed with the Ring of Loki equipped.  Preferably, do this by accident as you're falling to your death over lava.
2. Try to reset the origin of the Ring of Loki by shift-right-clicking like a maniac on anything and everything.  Nothing works.  The ring is now useless since you're never going to be able locate that origin block that you can't remember shift-right-clicking 4 deaths ago.

What I expected to happen: Need *some* way to reset the origin of the Ring of Loki.  e.g. by shift-right-clicking the ground twice real quick or maybe shift-punching the air.

What happened instead: There appears to be no mechanism to reset the origin of the Ring of Loki if you can't find the original block where it was set.

**Comment by riskable** [comment]
Just to add: This was with the Kreation modpack...  https://www.curseforge.com/minecraft/modpacks/kreation

**Comment by williewillus** [comment]
the ring will now exit binding mode when you move it back to your main inventory

**Comment by riskable** [comment]
Thanks @williewillus!  That's a fine solution =)
