### ISSUE TITLE
Bore lenses now destroy saplings?

### ISSUE THREAD

**Issue by sjstark** [Vazkii/Botania#3282]
# Version Information
Forge version:  31.1.74
Botania version:  r1.15-383

# Further Information
Steps to reproduce:
1. Use bore lens on sapling
2. Sapling is destroyed

What I expected to happen:
Bore lenses to ignore saplings and leaf blocks

What happened instead:
Bore lenses destroy saplings that used to not be destroyed.

I've been playing on a Valhelsia server (so maybe not your programming that's causing this), but in the latest push of updates today, my tree farm broke. Before this last update I was able to setup a functional tree farm without hitch (like this link: https://www.reddit.com/r/botania/comments/4sxpui/botania_tree_farm_early_game_late_game/ ). The bore lens now destroys saplings and leaf blocks and so the trees don't have time to grow. I looked through patch notes to see if this was intentional and wasn't able to find anything on the topic.

**Comment by Hubry** [comment]
Whoops, looks like my fault with the duplicate collision fix.

**Comment by sjstark** [comment]
Thanks! Appreciate all the work yall have done on this mod, its been fun getting into it!

**Comment by sjstark** [comment]
Is there a way to hot patch this fix in now? Or do I need to wait until the next version of Botania is released?

**Comment by williewillus** [comment]
I'm going to make a release soon

**Comment by sjstark** [comment]
Hey! Just following up, did this get pushed through with the 384 update 3 days ago? I just heard that our server man is about to update the mods on our server and wanted to see if this was hit with that.

**Comment by williewillus** [comment]
yes, 384 should include this fix
