### ISSUE TITLE
1.15.2 - Cosmetic Trinket Overrides conflicting

### ISSUE THREAD

**Issue by Partonetrain** [Vazkii/Botania#3283]
# Version Information
Forge version:  31.1.75
Botania version:  r1.15-383

**Works with just Botania, Curios, and Patchouli**. I am in the process of figuring out which mod is preventing this.

# Further Information
Steps to reproduce:
1. Have ??? and Botania installed
2. Try to craft a functional trinket with a cosmetic one
3. It doesn't craft :(

What I expected to happen:
Cosmetic overrides work as normal

What happened instead: 
![image](https://user-images.githubusercontent.com/19861808/81193600-33277b00-8f81-11ea-8820-c78580ce344d.png)

**Comment by Hubry** [comment]
The monocle counts as a cosmetic bauble, as discussed on discord.
