### ISSUE TITLE
Enderman flower pickup

### ISSUE THREAD

**Issue by Coolcabbage** [Vazkii/Botania#3285]
# Version Information
Forge version:  31.1.61
Botania version:  383

# Further Information
1. Place down botania flower
2. Have enderman spawn

What I expected to happen:Enderman to leave the flower alone or maybe grab the dirt

What happened instead: enderman yoinked the flower

**Comment by williewillus** [comment]
This is because special flowers are in the small flowers tag but that subjects them to enderman griefing
