### ISSUE TITLE
Special "Botania flower" generated with Endoflame + Flower pot

### ISSUE THREAD

**Issue by AllNaishaVariationsAreTaken** [Vazkii/Botania#3287]
Hello, and thanks for your excellent mod.  

It is possible to generate [Botania Flower] by using an Endoflame on a [Flower Pot] from Vanilla Minecraft.  

Minecraft Version: 1.12.2  
Modpack: Dungeons, Dragons and Space shuttles Patch 7.23a with nothing else installed.

Best regards,
Naïsha

**Comment by Hubry** [comment]
Modded flowers going into flower pots is a Quark feature, and by default, Botania flowers are blacklisted. For some reason this modpack has the config edited to not blacklist them - [report it here](https://github.com/Freebi85/Dungeons-Dragons-Space-Shuttles).

The entry to edit in `quark.cfg` is `decoration` -> `"colored flower pots"` -> `"Flower Overrides"`.

**Comment by AllNaishaVariationsAreTaken** [comment]
Thank you very much.
