### ISSUE TITLE
mana enchanter not getting mana via sparks

### ISSUE THREAD

**Issue by DoomSquirter** [Vazkii/Botania#3288]
# Version Information
Forge version:  1.15  -- 31.1.74
Botania version:  Botania-r1.15-383

# Further Information
Steps to reproduce:
1. setup mana enchanter
2. below ground directly under mana enchanter, setup mana pools with sparks, filled with mana
3. enchant starts, progress does not move
4. put pool on same level, full of mana, progress does not move
5. add spreader, point to main enchanter block, progress starts moving

What I expected to happen:
mana enchanter to pull mana from spark network like it used to

What happened instead:
it did not

**Comment by williewillus** [comment]
can't reproduce.

**Comment by Alwinfy** [comment]
- is the pool in (4) also sparked? 
- sparks have a range cap of ~11 blocks, are the underground sparks at least that close?
- is the mana enchanter itself also sparked? you need a receiving spark to transfer mana
- what happens when you right-click the Enchanter's spark with a Wand?

**Comment by DoomSquirter** [comment]
well shit.  *facepalm* no, I didn't have mana enchanter sparked.  damnit, now you proved I'm stupid.  :(  I blame the quarrantine.  I have done this setup countless times before.  *sadface*  sorry about this.
