### ISSUE TITLE
[1.15.2]  Found a broken recipe: Botania botania:pure_daisy/livingwood class vazkii.botania.common.crafting.RecipePureDaisy Failed to get ingredients from recipe wrapper

### ISSUE THREAD

**Issue by SDUBZ** [Vazkii/Botania#3289]
# Version Information
Forge version:  1.15.2-31.1.77
Botania version:  Botania-r1.15-384
jei-1.15.2-6.0.0.4

# Further Information
logs:
[latest.log](https://github.com/Vazkii/Botania/files/4609241/latest.log)

Steps to reproduce:
1. First step load with forge and botania,jei 
2. Second step load up instance and get the output of the recipe
3. etc...

What I expected to happen:
to work as normal

What happened instead:
got a broken recipe out of bounds exception

**Comment by williewillus** [comment]
can you reproduce with just botania and its deps + jei

**Comment by SDUBZ** [comment]
it stopped happening after i wiped my server
so old data interefering some how 🤔

**Comment by Hubry** [comment]
This seems to be happening in the patreon server pack, too, so I guess I'll cook up a custom build with more logging?
