### ISSUE TITLE
[Config] [Bug] - Botania Config still renders the option to enable justified text. 

### ISSUE THREAD

**Issue by Lanse505** [Vazkii/Botania#3290]
# Version Information
Minecraft version: 1.15.2
Forge version:  31.1.87
Botania version: Botania-r1.15-384

# Further Information
After talking to Vazkii about what exactly:
```
#Set this to true to enable justified text in the Lexica Botania's text pages.
justified_text = false
```

meant in the configs, he pointed out that this config shouldn't even exist anymore in 1.15 since Botania has moved over to using Patchouli.

**Comment by Hubry** [comment]
It actually still has an effect, only on the cover though
False:
![false](https://user-images.githubusercontent.com/26120076/82095546-875bf900-96ff-11ea-8894-1d82c1d58930.png)
True:
![true](https://user-images.githubusercontent.com/26120076/82095558-8f1b9d80-96ff-11ea-8ad5-a597132790f2.png)

**Comment by williewillus** [comment]
I'd just remove it
