### ISSUE TITLE
Manasteel/Elementium shears do not drop leaves/grass

### ISSUE THREAD

**Issue by stackdynamic** [Vazkii/Botania#3296]
# Version Information
Forge version: 31.1.63
Botania version: 1.15-384

# Further Information
Steps to reproduce:
1. Use manasteel or elementium shears on a block that shears should normally drop (leaves, grass, etc.)

What I expected to happen:
Manasteel shears should drop broken leaves/grass.
What happened instead:
Grass/leaves do not drop.

**Comment by elowanut** [comment]
This is #3275 .

**Comment by stackdynamic** [comment]
Apologies, somehow did not see that.
