### ISSUE TITLE
1.15 Mana Bars Auto-Update

### ISSUE THREAD

**Issue by enderger** [Vazkii/Botania#3298]
# Version Information
Forge version:  31.1.87
Botania version:  r1.15-384

# Further Information
Steps to reproduce:
1. Set up a mana spreader attached to some generating flowers and pointing into a mana pool
2. Check one of them with the wand of the forest
3. See that it's auto-updating

What I expected to happen: Like in other versions of Botania, you should have to click on mana containing items to see what they actually have. That is not in the current Botania build

What happened instead: The bar auto-updates

**Comment by Alwinfy** [comment]
#notabug, this is a new feature in 1.14+
