### ISSUE TITLE
Lexicon is Corrupting / Blank

### ISSUE THREAD

**Issue by NoxinTrebor88** [Vazkii/Botania#3299]
# Version Information
Forge version:  31.2.0
Botania version:  r1.15-384

# Further Information
every time i start a new wold of modded minecraft on forge of which botania is one of the mods the book only has rectangles for letters making the in game documentation impossible to use and the mod difficult to operate. 

Steps to reproduce:
1. First step: start a new world
2. Second step: look at lexicon in game documentation
3. Third step : see book filled with rectangles instead of letters after some gameplay

What I expected to happen: for the in game documentation to stay legible

What happened instead:
![2020-05-20_01 38 59 Lexicon Issue](https://user-images.githubusercontent.com/65634388/82392113-f6588b00-9a3a-11ea-9582-4f4d9c70ea21.png)

**Comment by NoxinTrebor88** [comment]
any help anyone ? please

**Comment by williewillus** [comment]
your resource pack is shipping broken unicode fonts. see https://github.com/Vazkii/Patchouli/issues/236
