### ISSUE TITLE
botania crashed my modpack

### ISSUE THREAD

**Issue by mertoalex** [Vazkii/Botania#3301]
ı tired to make a modpack at 1.15.2 but my game is not opened and crashed by botania mod error links: https://pastebin.com/xtCRC1rt debug.log file: https://www.mediafire.com/file/e67hrfm7dfp9avb/debug.log/file

ı said this to forge forum it's said " Seems to be a problem with Botania. Make sure it is up to date, if it is report this to the author. "

**Comment by Pannoniae** [comment]
it says it could not find something in pneumaticcraft.... how would this be related to botania?
Also, try launching the pack without botania and see if it crashes

**Comment by williewillus** [comment]
not botania

**Comment by mertoalex** [comment]
https://pastebin.com/vGqzQZeM again crashed without botania @Pannoniae

**Comment by mertoalex** [comment]
https://pastebin.com/NRiM8hrQ again crashed without pneumatic craft @Pannoniae

**Comment by williewillus** [comment]
this isn't a botania issue, so please stop spamming our issue tracker.

**Comment by Pannoniae** [comment]
the log which you sent is blaming WAWLA/WAILA/HYWLA (or whatever the fuck it is called). Please open an issue at those

**Comment by mertoalex** [comment]
THX for @Pannoniae
