### ISSUE TITLE
Flower Pouch Not accepting flowers when in hand

### ISSUE THREAD

**Issue by LordMZTE** [Vazkii/Botania#3302]
# Version Information
Forge version:  31.1.87
Botania version:  r1.15-384

# Further Information
Link to crash log: [no crash]
Steps to reproduce:
1. Hold a flower pouch in the hand
2. Pick up any mystical flower

What I expected to happen: The Flower goes into the flower pouch

What happened instead: The flower goes into my inventory

**this only happens when the pouch is held and not otherwise**

**Comment by williewillus** [comment]
intended, but not sure if it should be anymore.

it was "intended" a long time ago since modifying a stack while holding it was apparently dangerous for dupes and stuff. don't think that's true anymore.

**Comment by Alwinfy** [comment]
Still is useful as a way to temporarily disable the bag's slurp feature,
though

**Comment by williewillus** [comment]
closing as intended
