### ISSUE TITLE
Mod depend on curios and patchuli

### ISSUE THREAD

**Issue by HaiTangT** [Vazkii/Botania#3304]
# Version Information
Forge version:  1.15.2-31.2.0
Botania version:  1.15-384

# Further Information
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)\
Steps to reproduce:
1. First step
2. Second step
3. etc...

What I expected to happen:

What happened instead:

**Comment by williewillus** [comment]
?
