### ISSUE TITLE
[Botania r1.15-384]  Jumping over three blocks with Soujourner's Sash and Cirrus Amulet causes Fall Damage

### ISSUE THREAD

**Issue by PokeMaserJ** [Vazkii/Botania#3306]
Version Information
Forge version:  31.1.47
Botania version:  r1.15-384

# Further Information
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)\
Steps to reproduce:
1. First step Equip both the Soujourner's Sash and the Cirrus Amulet
2. Second step Double Jump so that you jump over 3 blocks tall
3. Third step You land and take fall damage

What I expected to happen:
I expect (based on older versions) to not take fall damage with this combo of items
What happened instead:
I take fall damage

**Comment by ramirocantu** [comment]
I'll take a look at it. Just to be clear you are referring to jumps where the player falls further than where they started correct? As in runs and jumps on lower terrain.

**Comment by PokeMaserJ** [comment]
Even if you stay on one block, if you fall more than three blocks after double jumping (which is pretty easy with this combo of items) you take fall damage. I've noted even the Globetrotter's Sash by it self has this issue. Since you seem to jump 3.2 blocks with the Globetrotter's Sash.

**Comment by ramirocantu** [comment]
The reason this happens is that since Minecraft 1.14+, mc uses fallspeed to give melee weapons crit damage (150%). The code was adjusted to allow players to crit hit with these combo of items. A side effect has been wonky fall damage.

**Comment by PokeMaserJ** [comment]
With just the Globetrotter's Sash higher jump, you take fall damage no matter what. Probably the same reason why double jumping with a Soujoruner's Sash and the Cirrus Amulet. If you REALLY want to see the effect, have the Globetrotter's Sash AND the Nimbus Amulet and triple jump with this combo. And sadly this probably won't get fixed for 1.15.2 since the "last" version .for 1.15.2, bearing any major bugs,is out.

**Comment by Hubry** [comment]
So after some investigation... the method Botania used is negative fall distance set on jump. This doesn't work anymore, as fall distance gets reset if the player moves upwards. Gotta hook the fall event I guess.

**Comment by Vayxen** [comment]
still exists on 1.16 :/
