### ISSUE TITLE
Suggestion/Question: Botania - Quark Mod Compatibility

### ISSUE THREAD

**Issue by Burgersim** [Vazkii/Botania#3308]
Hi, I wanted to ask (and subsequently suggest) variants for chests/bookshelves/boats and so on made from Botania materials, when Quark is installed. I have tried the newest Version of Quark and Botania together, and I was just wondering if this was possible or even planned in the future for 1.15 and/or later updates, because I also use other mods (AbnormalCore and subsequent mods, that add wood variants and variant blocks, if Quark is present) and at the moment Botania is the only one, that doesn't provide variant blocks for e.g. its wood types, even though, as far as I saw, its from the same author and i feel like it would be very nice to have ^^

**Comment by Burgersim** [comment]
I would still love to see this compatibility, since it's really the only mod that I have that doesn't have it, although Quark is from the same mod author ^^

**Comment by williewillus** [comment]
this would be in Quark if it ever happened, I'd report it there instead of here.
