### ISSUE TITLE
Bug Report, placing Hydroangeas with PSI Trick:PlaceBlock sometime turns them into a bugged "Poppy" flower

### ISSUE THREAD

**Issue by Pudassassin** [Vazkii/Botania#3309]
I was trying to replace dead brush with this neat spell from PSI, all goes well except 2 out of 16 Hydroangeas turning into a fail-safe poppy flowers

One was picked up as it is "placed" mid-air and place that again, another just plain out bugged out of the box

![image](https://user-images.githubusercontent.com/31712530/82722681-1e721380-9cf3-11ea-9e0b-4acefb9d1592.png)
![image](https://user-images.githubusercontent.com/31712530/82722696-3c3f7880-9cf3-11ea-991d-f88f915a6539.png)

**Comment by Hubry** [comment]
This issue was fixed in 1.14+ builds by flattening the flower block into separate blocks per flower type.
