### ISSUE TITLE
When throwing Lexica Botania into Alfheim Portal, It just disappear :( HELPP

### ISSUE THREAD

**Issue by Ass2k11** [Vazkii/Botania#3311]
# Version Information
Forge version:  28.2.4
Botania version:  1.11-379

# Further Information
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)\
Steps to reproduce:
1. First step
2. Second step
3. etc...

What I expected to happen: to work

What happened instead: not work

**Comment by Ass2k11** [comment]
kinda sad because it works with all other things..

**Comment by BenDawgAK** [comment]
thats not how you use the portal to aelfhiem. check the book for what you can throw in
