### ISSUE TITLE
weight lens on lapis ore doesn't creates broken lapis block item

### ISSUE THREAD

**Issue by jdratlif** [Vazkii/Botania#3312]
# Version Information
Forge version:  14.23.5.2854
Botania version:  1.10-363

# Further Information

40 second video demonstrating the problem I am seeing.

http://www.technoplaza.net/temp/botania_weight_lens_lapis_bug.mp4

Steps to reproduce:
1. Trigger mana pulse with weight lens on lapis block
2. Lapis block falls
3. It's not a lapis block item. It's messed up somehow. The texture is missing and the Thermal Expansion Pulverizer does not recognize it as lapis and won't process it. You can place it in the world and that seems to fix the block.

What I expected to happen:
A normal lapis block item would be on the ground.

What happened instead:
A weird messed up lapis block was there.

**Comment by williewillus** [comment]
it's a vanilla bug that was fixed in 1.13+
(https://bugs.mojang.com/browse/MC-112891)
