### ISSUE TITLE
Better Builder's Wand Bug

### ISSUE THREAD

**Issue by babycarrot93** [Vazkii/Botania#3314]
# Version Information
Forge version: 12.18.3.2477  
Botania version:  r1.9-341

# Further Information
Steps to reproduce:
1. First step: Get builder's wand from Better Builder's Wand
2. Second step: Place flower
3. Third step: Use builders wand to place the flower
4. Fourth step: See non textured block
5. Fifth step: Creative middle click to obtain Botania Flower [If you have this, that means something
went wrong, you should report this.]

What I expected to happen: The flower would be placed like other blocks

What happened instead: A bugged flower appeared

**Comment by williewillus** [comment]
ancient version of botania that isn't supported anymore. Try updating BBW for a potential fix, but this can only be fixed completely by going to 1.14+
