### ISSUE TITLE
Botania Terrasteel Will's bug

### ISSUE THREAD

**Issue by JakeLewisFSC** [Vazkii/Botania#3319]
What I expected to happen: 

When a bow is fully charged back it will always crit which should apply the effects of the Wills.

What happened instead: 

The bow did not apply the Will's effects on the affected entity.
I decided to look at the code for the wills.
Here it is:
boolean crit = player.fallDistance > 0.0F && !player.onGround && !player.isOnLadder() && !player.isInWater() && !player.isPotionActive(Effects.BLINDNESS) && !player.isPassenger();

Bows can do vanilla crits while on the ground. However, according to this logic, the player must be in the air at all times.

EDIT: actually also according to this logic, the "crit" from the Will's isn't actually Vanilla Minecraft crit. By this logic, all you need to be is in the air to apply their effects, while vanilla Minecraft crit requires screen angle position as well as in the air.

**Comment by williewillus** [comment]
1. the will only refers to melee crits
2. vanilla melee crits don't require an angle as far as I know, it's only just the falling requirement

**Comment by williewillus** [comment]
the code as is matches vanilla's code for determining melee crits pretty much exactly. I cleaned it up and documented that it was copied, but this isn't a bug.
