### ISSUE TITLE
Sorting Flower Pouch using inventroy sorting voids content of pouch

### ISSUE THREAD

**Issue by Sunekaer** [Vazkii/Botania#3323]
# Version Information
Forge version: 1.15.2-31.2.9
Botania version: r1.15-384

# Further Information
Steps to reproduce:
1. Put flowers in the pouch
2. Sort using inventory sorting
3. all flowers get voided 

What I expected to happen:
Nothing

What happened instead:
all flowers get voided

**Comment by balloonhead** [comment]
Like linked by Sunekaer I got this behaviour but the flowers were not all voided, Light blue and red still were there but i dont know the amount of them before sorting. Could be that all the other colors have been converted into these.

**Comment by williewillus** [comment]
which inventory sorting mod?

**Comment by Sunekaer** [comment]
"Inventory Sorter"

**Comment by williewillus** [comment]
If this is cpw's Inventory Sorter, then this issue is https://github.com/cpw/inventorysorter/issues/89
