### ISSUE TITLE
Tessaract wont send mana on MP in an artificially loaded chunk

### ISSUE THREAD

**Issue by Calibrah** [Vazkii/Botania#3325]
# Version Information
Forge version:  minecraft 1.12.2 forge-14.23.5.2847
Botania version:  1.10-363

What I expected to happen:
I have a mana tesseract about 500 blocks away from my home that is the “input” of my whole mana source. The chunks were loaded with chickenchunks chunkloader and FTB Chunk Loading ( both at one time and just one at a time too). I would’ve expected for the mana to jump straight to the other side of the tesseract and into my pools.

What happened instead:
While online, the tesseract wont work unless im manually chunkloading its proximity ( eg im afk-ing near it ). However, when i log off and no one is on the server, the tesseract works as expected. Having done a bit of testing, the problem sure comes from the tesseract, it just “voids” the mana that is produced, sucks it in but never sends it.

Im here if you need more details.

**Comment by Alwinfy** [comment]
Mana Tesseract is from an addon and not the base mod (Botanic Additions); it has no official support. See https://gitlab.com/DragonForge/botanic-additions

**Comment by Calibrah** [comment]
Oh, my bad, sorry to bother!
