### ISSUE TITLE
no no no no no no no no no no no no no no no no no no no no no no no no no no no no no no no no no no no no

### ISSUE THREAD

**Issue by TheoBuzz** [Vazkii/Botania#3327]
this is stupid forge is already good this is bad fuck you delete this shit ur fabruc sucks use forge mother fuckers fabric sucks forge is perfect awesome good for mod needs no fabric is hacks hacks HACKS mixins stupid kill your self im gay btw

**Comment by shedaniel** [comment]
good job mate this is a forge mod

**Comment by Tfarcenim** [comment]
wow what an idot

**Comment by ZangeloRaj** [comment]
this is a forge mod
