### ISSUE TITLE
Botania crashes with dedicated servers (Registry.containsKey)

### ISSUE THREAD

**Issue by Pannoniae** [Vazkii/Botania#3328]
# Version Information
Forge version:  31.2.9
Botania version:  r1.15-385

# Further Information
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)\
https://gist.github.com/Pannoniae/a31c7407ad4eab0000e4352b5fc63fa3
Steps to reproduce:
1. Start server
2. ????
3. Watch it crash

What I expected to happen:
To not crash

What happened instead:
A NoSuchMethodError crashing the server. It is likely caused by the commit 2 days ago which switched to Registry.containsKey which is a client-only method thus crashing the dedicated server.

**Comment by williewillus** [comment]
fixed and released build 386

**Comment by Pannoniae** [comment]
Thanks! <3
