### ISSUE TITLE
Forge re-introduces bug converting coarse dirt and podzol to dirt after sapling is grown, breaking tree farms

### ISSUE THREAD

**Issue by WebDragon** [Vazkii/Botania#3329]
# Version Information
Forge version:  forge-31.2.20
Botania version:  Botania-r1.15-385.jar

# Further Information
https://bugs.mojang.com/browse/MC-57884 fixed back in 2014

Additionally according to [this](https://minecraft.gamepedia.com/Mycelium#:~:text=Huge%20mushrooms%20can%20grow%20on,do%20not%20grow%20on%20it )
Mycelium should *NOT* allow saplings to be planted on it (verified for vanilla 1.15.2) but once Forge is installed (tested up to latest forge-31.2.20)  mycelium allows the planting of saplings again. (also bad.)

Once the sapling grows, the Coarse Dirt, and Podzol (and apparently erroneously, Mycelium) get converted back to plain dirt again.

this breaks several modded operations/options not the least of which is Botania Tree Farms for which you use the Rannuncarpus to select the coarse dirt to plant the saplings on to differentiate from regular dirt or grass nearby.  

screenshot: https://imgur.com/0NwIANg

I have made multiple attempts at filing this report with Forge this morning after confirming the bug, but cannot get past their blasted spam registration protection to create an account with and either search the forums properly to see if the bug is even reported yet, or submit my own. 

Confirmed this bug exists SOLELY when 1.15.2 +  forge-31.2.20 and no other mods installed.  so NOT a botania issue, but directly affects botania, so you were my second choice for getting this reported upstream since I cannot register at minecraftforge.net. (grr. apologies.)

**Comment by Alwinfy** [comment]
For a workaround, try using one of the pasture seeds variants for tree blocks

**Comment by WebDragon** [comment]
Interestingly the Dry Grass or Golden Grass, while I thought it very likely they would get converted to dirt as well by the forge bug, it actually does not convert to dirt once the tree grows on it. Acceptable workaround. Thumbs up.

 One must just take care not to allow it to spread when you put down the pasture seed, by surrounding it with stone or something.

**Comment by Hubry** [comment]
Tree growth changed a lot in 1.16 and the patch that caused this is currently gone. Please let us know if this becomes a problem again.
