### ISSUE TITLE
Internal Server Error when equiping the Flügel Tiara

### ISSUE THREAD

**Issue by Zayonx-0** [Vazkii/Botania#3331]
Forge version:  forge-1.15.2-32.2.0
Botania version: Botania-r1.15-386

Steps to reproduce: Install Botania, Curios-FORGE-1.15.2-2.0.2.4.jar and Patchouli-1.15.2-1.2-34.jar on a dedicated server, join it and try to equip the Flügel Tiara.

What I expected to happen: Be able to equip the Flügel Tiara without being kicked with a "Internal Server Error" message.

What happened instead: The server keeps running but I can't join it anymore while the Flügel Tiara is equiped. 

logs : https://pastebin.com/T5VZ3yh8

**Comment by williewillus** [comment]
what java version are you running on both sides?

**Comment by Zayonx-0** [comment]
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-8u242-b08-1~deb9u1-b08)
OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)

Running on Debian 10

**Comment by Zayonx-0** [comment]
Same Issue with the latest java build on client side (build 1.8.0_251-b08)

**Comment by Zayonx-0** [comment]
Fixed the issue by installing OpenJDK 8, thanks for asking what version of java i was running, made me fix the issue !

**Comment by williewillus** [comment]
the issue was that code uses a standard library that got moved in java 11. I just pushed a fix that reimplements the logic without using that library, so the next version you should be able to go back to java 11
