### ISSUE TITLE
Undefined Botania Flower sighting

### ISSUE THREAD

**Issue by DialMforMara** [Vazkii/Botania#3337]
Tried to place a Marimorphosis in a flower pot in Botania on Java Edition 1.12. The Marimorphosis became an undefined Botania Flower. When I broke the pot and picked up the flower, it looked like a poppy; when I tried to plant it again, it looked like a placeholder block. I also got the Take It Easy advancement, which told me that this was a bug and I should report it.

**Comment by williewillus** [comment]
This is fixed in newer versions (1.14+), and is not feasible to fix in older ones.
