### ISSUE TITLE
Rendering the scene incorrectly using shaders

### ISSUE THREAD

**Issue by rmdyh** [Vazkii/Botania#3338]
# Version Information
Forge version:  31.2.0
Botania version:  r1.15-386

# Further Information
The mod is interesting and I enjoy it a lot. But when some items in this mod are used with shaders(and optifine), the scene may be rendered in a wrong way like the image showed below. I put some mana pylons on the ground, and dig a cave(about y-5 from the ground) to put some chests. The chests look like they are glowing.
![problem1](https://user-images.githubusercontent.com/31561885/85677507-2fe77a80-b6fa-11ea-8994-93324cc8277e.png)

I use OptiFine HD G1 pre28 ultra and shader pack Sildurs Vibrant Shaders v1.27. When I use another shader pack like SEUS PTGI, it becomes worse.
![problem2](https://user-images.githubusercontent.com/31561885/85681853-498ac100-b6fe-11ea-8e73-08c110a03941.png)

I guess maybe some items cast lights in the wrong way but I didn't verify it.

**Comment by williewillus** [comment]
turn off botania's shaders in the config file, they aren't very compatible with other shader mods
