### ISSUE TITLE
Game crashed whilst ticking block entity

### ISSUE THREAD

**Issue by Rowan2112** [Vazkii/Botania#3341]
# Version Information
Forge version:  1.12.2-forge1.12.2-14.23.5.2847
Botania version:  Botantia+r1.10-361

# Further Information
Link to crash log: https://pastebin.com/Tswtstv3
Steps to reproduce:
1. First step: Be killed by anything from any mod.
2. Second step: You spawn back at your bed, and the game shuts down completely, bringing up the Launcher.

What I expected to happen: I respawn like normal, and run back to where my stuff is.

What happened instead: The game crashed. 

This has never happened before, and I have played with this pack for a long time and on other worlds. This only started happening once I placed the mana spreader down, bound it to the diluted mana pool, and walked off to mine coal for the Endoflames. There is no mana pouring into the pool, but it is bound. 
  Also, I have used these objects before, with Hydrangeas, and left it alone in this exact state after the flowers wilted, and never had this issue. 

# Mod list 
![Screenshot_74](https://user-images.githubusercontent.com/67081170/85932943-32cfa000-b89f-11ea-8c99-44d3bcb69b0e.png)

**Comment by williewillus** [comment]
This is #2205. There are a variety of workarounds for it in that ticket, ranging from placing a block above the offending blocks so voxelmap doesn't touch them, or using a better map mod besides voxelmap.
