### ISSUE TITLE
Garden of Glass no Pumpkin/Melon seeds

### ISSUE THREAD

**Issue by Mystogrigen** [Vazkii/Botania#3342]
# Version Information
Forge version:  31.2.8
Botania version:  Botania-r1.15-385.jar

# Further Information
Modlist (in case another mod is interfering with blockdrops): https://gist.github.com/Mystogrigen/49749d511a07c8f9f388f3e1c3ed1344

I spammed at least 9 stacks of bonemeal for tallgrass to break and no seeds besides wheat and industrial hemp. I even gave myself six stacks of tallgrass items to place/break, and still no pumpkin/melon seeds.

What I expected to happen: To occasionally receive melon/pumpkin seeds from broken tall grass.

What happened instead: No melon/pumpkin seeds from tall grass.

**Comment by BenDawgAK** [comment]
that's a vanilla thing my dude.
it wont drop from tall grass, and botania doesn't change that

**Comment by Alwinfy** [comment]
no, yeah, it's a real bug; botania does change it in GoG mode for fel
pumpkins

**Comment by BenDawgAK** [comment]
oh really? huh. thanks for clarifying i dont really play GoG

**Comment by Hubry** [comment]
BluSunrize/ImmersiveEngineering#4046
Welp, this is annoying. I guess downgrade Forge for now?
