### ISSUE TITLE
Missing texture for Lexica Botania book when in hand/open

### ISSUE THREAD

**Issue by Slexom** [Vazkii/Botania#3344]
# Version Information
Forge version: 31.2.30
Botania version:  r1.15-387

# Further Information
 

What I expected to happen: Have something different from black and purple texture

What happened instead: Black and purple texture

![image](https://user-images.githubusercontent.com/9221469/86519964-1eac1580-be40-11ea-842b-4b33167d826a.png)

**Comment by williewillus** [comment]
try with just botania
