### ISSUE TITLE
Spectator causes game crash when looking at new tardis mod alembic

### ISSUE THREAD

**Issue by LoZFierceDeity** [Vazkii/Botania#3346]
Not sure if this falls under the category of a botania issue, a new tardis mod issue, or a compatibility issue, so sorry if this is invalid/in the wrong place. When I equip the spectator from botania and look at the alembic, the game crashes. Worse, I can't start my save again, it just immediately crashes. I created a world to test this. Steps are very simple in creative:

Version: Minecraft 1.14.4, forge 28.2.5, botania r1.11-379, Tardis-Mod-1.14.4-1.3.1
1. Give yourself mana somehow (ex full mana tablet)
2. Give yourself a spectator and wear it.
3. Place down an alembic.
4. If playing singleplayer, the world can no longer be started.

[crash-2020-07-04_23.38.16-server.txt](https://github.com/Vazkii/Botania/files/4874394/crash-2020-07-04_23.38.16-server.txt)

**Comment by williewillus** [comment]
The tardis mod is closed source so unfortunately there's pretty much no way to research the problem

**Comment by LoZFierceDeity** [comment]
Shame... hadn't noticed that before creating the issue. Debugging issues without source is a pain :/
I'll keep it open on their end, as botania is open source. I suspect it's an issue on their end anyway, with how the object represents its inventory (It has two screens which are probably what cause issues).

**Comment by LoZFierceDeity** [comment]
Was looking at the issue on their site and realized, if you're interested, it's not actually closed source. https://gitlab.com/Spectre0987/TardisMod-1-14/-/tree/master
