### ISSUE TITLE
Garden of Glass - Version Error

### ISSUE THREAD

**Issue by Calibos** [Vazkii/Botania#3348]
I'm putting together a small modpack for myself, and I tried to drop in garden of glass, pack is 1.12.2, I have appropriate version of botania, (10-360), when i put in garden of glass  ( v. 1.2) checked several times to make sure I was pulling the right version, I understand that after 1.12.2 the mod is different. When I try to run it, it says I'm using a version of garden of glass for 1.13.  I realize this is an older version, but I'd appreciate any help you can spare me. Thank you.

https://paste.ee/p/rn5Hk

**Comment by williewillus** [comment]
Download the version of Garden of Glass for 1.12 https://www.curseforge.com/minecraft/mc-mods/botania-garden-of-glass/files/2391198
