### ISSUE TITLE
Life Imbuer not working when not standing in the (loaded) chunk

### ISSUE THREAD

**Issue by ZlaTanskY** [Vazkii/Botania#3349]
# Version Information
Forge version:  31.2.9
Botania version:  r1.15-384

# Further Information
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)\
Steps to reproduce:
1. Place Life Imbuer (y 68) on a Zombie Spawner (y 67) (underground, base is at y 76)
2. Place mana pool  (y 69) and mana/gaia spreader (y 69)
3. Connect spreader to life imbuer with wand of the forest

What I expected to happen: Zombies will spawn, even when I am not in the neighbourhood or even offline.

What happened instead: No mobs are spawning when I am 1 chunk further from the spawner. Chunks are loaded, Rotten flesh is connected to corporea network so I can watch through the Crystal Cube, but the loot is not adding up when I am not near the Life Imbuer.

**Comment by guillermomolla** [comment]
<img width="1254" height="943" alt="Image" src="https://github.com/user-attachments/assets/81464d42-d435-45f7-8a68-8e64c270c055" />

This is still not working (or broken again) on v1.20

I have 2 spreaders with a manapool adyaject conectted to a life inmbuer and they do not shoot mana while I am away. I even forced the chunk to be loaded and still nothing if I am not arround it will not work

Reopen please
