### ISSUE TITLE
Ring of correction doesn't switch to an axe for bamboo

### ISSUE THREAD

**Issue by KrAzYGEEK32** [Vazkii/Botania#3350]
Minecraft: 1.15.2
Botania: R1.15-387
Ring of correction doesn't switch the tool to an axe while used on a bamboo, although an axe is the correct tool(I'm using an elementium axe, and it works on everything else)
for harvesting bamboo.

**Comment by GabuSilver** [comment]
Im just gonna leave this from the Official Minecraft Wiki; "Bamboo can be mined with any tool, but the fastest tool to break them is a **sword**. In **Java Edition, a sword breaks bamboo instantly**, and **in Bedrock Edition, a sword breaks bamboo faster than an axe, though not instantly.**"

**Comment by KrAzYGEEK32** [comment]
Hmm I remember reading something in lines of that, but I was confused by the one probe which highlighted axe as the correct tool, and I even tried it, it seemed like axe was faster and sword(a tetra sword " might be the cause") was a little bit slower. Anyway I'm closing the issue, sorry for bothering you guys :)
