### ISSUE TITLE
Issues with tall mystical flowers

### ISSUE THREAD

**Issue by artemisSystem** [Vazkii/Botania#3351]
# Version Information
Forge version:  32.0.57
Botania version:  1.16-389

# Further Information
I.
First issue: Breaking top half doesn't drop item
Steps to reproduce:
1. Break the top half of a tall mystical flower using shears

What I expected to happen: The item drops

What happened instead: The item doesn't drop

II.
Second issue: Breaking bottom half plays breaking sound twice and has too many particles
Steps to reproduce:
1. Break the bottom half of a tall mystical flower using shears

What I expected to happen: Sound plays once and has a normal amount of particles

What happened instead: Sound plays twice and there are particles as if the block was broken twice

**Comment by williewillus** [comment]
I can't get this to happen anymore.
