### ISSUE TITLE
Plans on a mana equivalent for Netherite? 

### ISSUE THREAD

**Issue by BigCasper** [Vazkii/Botania#3361]
Just as it's titled. Kinda a feature request. For each armour tier in pre-1.16, there was a mana equivalent. Iron - Manasteel, Diamond - Terrasteel. Will there be, I dunno, Gaia Tier for Netherite?

**Comment by Hubry** [comment]
Terrasteel is already Netherite tier in basically everything, and from discord discussions, I don't think anyone has any ideas for an actually interesting armor tier that would fit.
