### ISSUE TITLE
[1.16] Botania won't load on Forge build 93

### ISSUE THREAD

**Issue by FynnWaelsing** [Vazkii/Botania#3367]
# Version Information
Forge version:  32.0.93
Botania version: 1.16-396

# Further Information
Link to latest log: https://pastebin.com/Dmes4L56
Steps to reproduce:
Loading up minecraft with the latest version (93) of Forge won't load Botania. It works fine on build 88.

What I expected to happen: Normal loading.

What happened instead: Got a report saying that Botania had failed to load.

**Comment by williewillus** [comment]
it's a bug in forge. downgrade a couple versions for now until they fix it

**Comment by williewillus** [comment]
update above forge 95
