### ISSUE TITLE
Register The Fruit of Grisaia as a food item for mod compatibility 

### ISSUE THREAD

**Issue by FolfyBlue** [Vazkii/Botania#3368]
**The Fruit of Grisaia** is an amazing item that lets you eat indefinitely, rather useful to anyone who possesses it. However, due to the fact that it's not registered as a proper "food" item, other mods which try to implement an "autofeed" feature _(Such as [Draconic Evolution](https://ftb.gamepedia.com/Draconic_Evolution)'s [Draconic Helmet](https://ftb.gamepedia.com/Draconic_Helm) or [Modular Powersuit](https://tekkitlite.fandom.com/wiki/Category:Modular_Powersuits)'s [Auto-Feeder](https://tekkitlite.fandom.com/wiki/Auto-Feeder))_ fail to use the fruit and leave us to feed ourselves manually, defeating the feature.    

Would it be possible to keep the item's infinite-feeding property while internally being a registered food item?

**Comment by williewillus** [comment]
Bump to unstale, but I'm not sure if this is too feasible. The fruit's effects trigger on usage tick, not when it's eaten. I'm not sure if other mods would handle it properly even if it were to be marked as food.
