### ISSUE TITLE
Mana flash can catch on fire from lava

### ISSUE THREAD

**Issue by Hyper-Miiko** [Vazkii/Botania#3369]
# Version Information
Forge version:  1.12.2-14.23.5.2838
Botania version:  r1.10-361

# Further Information
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)\
Steps to reproduce:
1. Place mana flash near lava (I used mana lens: Flash/Messenger on blaster)

What I expected to happen: Nothing special

What happened instead: Mana flash put fire near of it like wood.

**Comment by TuckV** [comment]
I don't believe this is a bug. Fires can naturally spawn a few blocks around a lava pool even on non-flammable materials.

**Comment by Hyper-Miiko** [comment]
Stone, ores, torch, nitor (from thaumcraft) do not put fire
The only things that take fire (even if it can't break du to fire) is wood based block, TNT and leaves (maybe grass)

**Comment by Hubry** [comment]
Confirmed in 1.16.1 versions
