### ISSUE TITLE
[Botania 1.12.2] Angel with two shot-gun

### ISSUE THREAD

**Issue by Hyper-Miiko** [Vazkii/Botania#3370]
# Version Information
Forge version:  1.12.2-14.23.5.2838
Botania version:  r1.10-361  

# Further Information
Link to crash log: None
Steps to reproduce:
Part 1:
1. Craft 1 (2 is better) mana blaster with velocity/messenger lens (other work but less efficient)
2. Craft and equip Ring of the Mantle
3. Jump (or not) and stay right-click

What I expected to happen: Maybe a little backward not sufficient to stay into the air

What happened instead: Jumping into the skies

Part 2:
4. Once you want to go down (or if you just jumped from high mountain) fire at "slow" rate to avoid touching floor
5. Wait 2 block above floor to stabilize
6. Stop fire and Stomp on the ground

What I expected to happen : Touching the floor like the graceful lady I am and do not take any damage

What happened instead: Sending my health into the oblivion like I just jumped from the highest pike I found.

How to avoid it: Take a Cirrus Amulet and just between step 5 and 6

**Comment by Hubry** [comment]
Looks like because of vanilla changes, this is already done in 1.16 - upwards velocity resets fall damage.
