### ISSUE TITLE
[Botania 1.12.2] Ghost Bullet

### ISSUE THREAD

**Issue by Hyper-Miiko** [Vazkii/Botania#3371]
# Version Information
Forge version:  1.12.2-14.14.23.5.2838
Botania version:  r1.10-361

# Further Information
Link to crash log: None
Steps to reproduce:
1. Make a blaster with damaging
2. Shoot any creature

What I expected to happen: If neutral take aggro on player, if killed give experience

What happened instead: Nothing, just taking damage like a pulse mana spreader killed him

**Comment by Hubry** [comment]
Already fixed in versions for 1.14 and later: 289dd6f9a8b84deed582d579e5589b181c98dafd
