### ISSUE TITLE
Trees (oak) does not grow within the Bubbell dome.

### ISSUE THREAD

**Issue by EastOfEden6502** [Vazkii/Botania#3372]
# Version Information
Forge version:  31.2.30
Botania version:  1.15-387

# Further Information
Steps to reproduce:
1. make an underwater bubble with Bubbell flower.
2. Get some dirt and try to grow trees - use bone meal as desired.
3. Saplings do not grow - at all
4. Build a dirt tower directly over a sapling 
5. destroy the dirt tower quickly
6. Use bonemeal
6. with a bit of luck sapling will grow into a tree

What I expected to happen:
Trees to grow normally.

What happened instead:
Saplings never change into trees.
I believe that the mod uses "fake air" blocks which are not recognized as empty space by the saplings so they think there is no free space above them ... and they are kinda right.

The dirt tower test seems to agree with it ... The dirt blocks are replaced by actual empty space when destroyed and sapling grows into that. Eventually that empty space gets replaced by the "fake air" by the Bubbell flower so further saplings in the same spot do not grow.

**Comment by Hubry** [comment]
Cannot reproduce on 1.16, open a new issue if that reappears
