### ISSUE TITLE
[Botania GoG 1.16] Crash when trying to get pebbles

### ISSUE THREAD

**Issue by iamsewage** [Vazkii/Botania#3378]
# Version Information
Forge version:  1.16.1, forge-32.0.98
Botania version:  Botania-1.16-398

# Further Information
Link to crash log: (https://pastebin.com/pcrdGuj1)
Steps to reproduce:
1. Create Garden of Glass world
2. Hold shift and dig for pebbles
3. Crash

What I expected to happen: Acquire pebbles

What happened instead: No pebbles, just crash

Apologies if bad bug report, only done one or two before

**Comment by williewillus** [comment]
working fine here. Did you download the new version of GoG for 1.16?

**Comment by iamsewage** [comment]
Nope, Twitch auto-downloaded an older version, works fine, sorry about that :x
