### ISSUE TITLE
botania and quark mod make the game crash 

### ISSUE THREAD

**Issue by xtremevisstick** [Vazkii/Botania#3381]
# Version Information
Forge version:  32.0.98
Botania version:  1.7.10
quark version: 1.10

# Further Information
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)\
Steps to reproduce:
1. i added your 2 mods to 1.16.1 version of minecraft
2. i started the game.
3. it crashes when loading the game

What I expected to happen:
i expected it to work like normal in de older 1.14 version

What happened instead:
it crashed

**Comment by Hubry** [comment]
Please attach the crash report and fill the version information properly. The versions of the mods you listed don't exist.

**Comment by MoriyaShiine** [comment]
lol what

**Comment by xtremevisstick** [comment]
sorry i found out what i did wrong.
botania mod was downloaden but it dint instal the the latest version.
normally when i download a mod it automatically does this. 
is also did this with the older version for 1.14 but i got it to work now.
sorry for the inconvenience.
