### ISSUE TITLE
Server Crash when take damage

### ISSUE THREAD

**Issue by yzl210** [Vazkii/Botania#3382]
# Version Information
Forge version:  1.16.1-32.0.88
Botania version:  1.16-399

# Further Information
Link to crash log: [PasteBin](https://pastebin.com/KqQRbBff)
Steps to reproduce:
1. Take Damage
2. Server Crash 
(Maybe it's because I created the world before adding Botania)  

What I expected to happen:
Take Damage

What happened instead:
Server Crash

**Comment by williewillus** [comment]
Post the *entire* log please

**Comment by yzl210** [comment]
https://pastebin.com/UHseQsKp

**Comment by williewillus** [comment]
this seems like a mod incompatibility. can you try with just botania then add in mods until it crashes?

**Comment by yzl210** [comment]
Is it because I created the world before adding Botania?

**Comment by Oct0bass** [comment]
No that shouldn't be an issue, I've added botania to existing worlds and it works fine
