### ISSUE TITLE
[Botania 1.16.1] optifine crash

### ISSUE THREAD

**Issue by lycc193** [Vazkii/Botania#3387]
# Version Information
Forge version:  1.16.1-32.0.107
Botania version:  Botania-1.16-399
Optifine version:  OptiFine_1.16.1_HD_U_G2

# Further Information
Link to crash log:[crash-report](https://pastebin.com/duf37J2X)\
When I check items through jei, the client crashes (maybe it's Rod of the Highlands?)

**Comment by williewillus** [comment]
pushed a workaround that hopefully will help in the next version, but optifine in general is unsupported and its compatibility issues have been getting worse and worse lately, so don't expect much support for it and the issues it causes.

**Comment by lycc193** [comment]
To add, only forge-107 has this problem, forge-106 does not have this problem
