### ISSUE TITLE
[1.16] Crash with Charm

### ISSUE THREAD

**Issue by FynnWaelsing** [Vazkii/Botania#3388]
# Version Information
Forge version:  32.0.106
Botania version:  1.16-399

# Further Information
Link to crash log: https://pastebin.com/iKxi8bQb
Latest log: https://pastebin.com/NeRjBsfC

Steps to reproduce:
1. Load up new world that includes Botania (and its dependencies) and the current Charm beta (1.16.1-2.0.0-beta.1)

What I expected to happen:
No crash.

What happened instead:
Crash.

I've already posted this issue on the Charm github, but figured I'd share it here as well for the sake of thoroughness.

**Comment by Hubry** [comment]
`[08Aug2020 11:30:05.673] [pool-3-thread-1/INFO] [STDERR/]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: org.spongepowered.asm.mixin.throwables.MixinError: Encountered undecorated Accessor method in assets/botania/botania.mixins.json:AccessorFireBlock applying to net.minecraft.block.FireBlock`

Looks like a conflict between [our fire block accessor](https://github.com/Vazkii/Botania/blob/master/src/main/java/vazkii/botania/mixin/AccessorFireBlock.java) and [their accessor](https://github.com/svenhjol/Charm/blob/2.0/src/main/java/svenhjol/charm/mixin/accessor/FireBlockAccessor.java). Should we look into prefixing these methods until Mixin 0.8.1 is out?

**Comment by svenhjol** [comment]
Thanks for the feedback, @Hubry . I'll tweak the method names on Charm's side and test.
