### ISSUE TITLE
[OPTIFINE] Crash when rendering Mana Pylon in inventory / Doesn't render properly when placed

### ISSUE THREAD

**Issue by Gekuu9** [Vazkii/Botania#3389]
# Version Information
Forge version:  32.0.108
Botania version:  1.16-399
OptiFine version: 1.16.1_HD_U_G2

# Further Information
Link to crash log: https://gist.github.com/Gekuu9/135d74ae6292f40aa92f20d1a153b00c
Steps to reproduce:
1. Install OptiFine and Botania
2. View the mana pylon item in your inventory (or in JEI, as I first discovered it)
3. Game crashes

OR

2. Place a mana pylon block in the world (I used /setblock to avoid crash from it being in my inventory)
3. Pylon does not render, looking at where it should be causes other blocks to not render
![2020-08-09_17 58 39](https://user-images.githubusercontent.com/3953783/89746473-a6ec8e80-da6e-11ea-89d8-ee0628ba5a07.png)

What I expected to happen: The mana pylon item renders correctly while in the inventory or in the world.

What happened instead: If the mana pylon is viewed in your inventory, the game will crash. If the mana pylon is placed in the world, it is invisible and causes some other blocks not to render if you look at where the pylon should be.

I don't know if this is considered a Botania issue or an OptiFine issue. Changing settings on OptiFine doesn't seem to prevent this, but it only happens with OptiFine installed.

**Comment by Gekuu9** [comment]
I am a fool, I just noticed the same issue that was already posted. I'll leave this here, as it has some more info than the other post did.

**Comment by TBiscuit1** [comment]
What is the other post? I can't seem to find it...

**Comment by TBiscuit1** [comment]
found it

**Comment by Gekuu9** [comment]
I found that OptiForge actually seems to fix this issue for Forge 32.02.108, also.

**Comment by TBiscuit1** [comment]
just tried and I crashed

**Comment by williewillus** [comment]
Try the latest botania (401). If it still doesn't work, then you're out of luck. I would stop supporting closed-source mods that make invasive, undebuggable changes.
