### ISSUE TITLE
[1.16.1 399] OptiFine Partial Incompatibility

### ISSUE THREAD

**Issue by Wolfan1** [Vazkii/Botania#3393]
Forge version:  32.0.108
Botania version:  1.16.1 399

**EDIT:** I have isolated the issue - it seems to be caused by having OptiFine installed alongside Botania. This is all that I have managed to figure out thus far.

Link to crash log: https://pastebin.com/aatwB4Gf
Steps to reproduce:
1. Have Botania, along with other required mods
2. Load into world (singleplayer or multiplayer, either works)
3. Go to Botania tab in creative inventory, or search botania items in JEI
4. Start scrolling down the list of Botania items in creative inventory

What I expected to happen:
No crash, I am able to scroll the whole way down the list of items
What happened instead:
Game freezes while scrolling down, game crashes

**Comment by TBiscuit1** [comment]
sooo, with optifine, some blocks (I think the pylons are the problem) cause this crash (more info in #3389 issue)

**Comment by TBiscuit1** [comment]
also, it's not just a partial imcompatibility, it's a very bad issue, crashes are always very bad issue... anyway X)

**Comment by Hubry** [comment]
Shouldn't crash after c773f434a0b11dfb53ed3747e59471ea8e481331, but keep in mind this doesn't happen on Forge 106 or lower anyways, and latest Optifine only guarantees compatibility with Forge 32.0.98 (as shown on the [changelog](https://optifine.net/changelog?f=OptiFine_1.16.1_HD_U_G2.jar).
