### ISSUE TITLE
[question] Regarding Botania...

### ISSUE THREAD

**Issue by Ushupiuck** [Vazkii/Botania#3396]
Hey. So I've noticed, a Fabric branch is in the works.

I wanted to ask. How are the Fabric and forge versions of the mod be differentiated from one another? Will they use separate curseforge links, or will they be listed together? Mainly asking because of the versioning-format the mod uses, also the fact that Botania has it's changelog on the official website... Yea, that'd be messy if both versions shared it XD...

Happy modding, and thanks for listening!

**Comment by williewillus** [comment]
1. separate CF projects
2. fabric version gets -fabric added to its version field
3. releases will be synchronized (a given version 1.x-y should have the same feature changes and mod-level bugfixes). Any platform-specific hotpatches will use a decimal in the build number (1.x-y.z)

of course, this is all predicated on me actually finishing the port :)
