### ISSUE TITLE
Entity rendering crash on Forge 32.0.107+

### ISSUE THREAD

**Issue by NikGold** [Vazkii/Botania#3397]
Well, This is very silly and a me problem but I thought of posting here.
Step one, Place four Thermalilys next to a mana pool and a spreader a few blocks above.
Step Two, Bind them all nice and cozy.
Final Step, Feed them hungry mana generating flora some fancy Coal Coke four one for each n.n

And Voila the result is having to go to MC edit or something and probably remove the whole setup cause I cannot enter the world anymore : D
Its totally my fault but I thought sharing.
https://gist.github.com/NikGold/1f91ddf766cb2efee66773d85be8506a

**Comment by Hubry** [comment]
For now downgrade Forge to build 106, Willie will probably push the fix later today.

**Comment by Sebulba13** [comment]
actually I figured out that problem is "Just enough items"

**Comment by Hubry** [comment]
@Sebulba13 That sounds either like an unrelated issue or #3387, not this

**Comment by Sebulba13** [comment]
I'm not an expert but this happens only when mana is getting from mana spreader to mana pool. So maybe "just enough items" cant see mana as actual object like water or oil

**Comment by Hubry** [comment]
@Sebulba13 post the crash report instead of speculating, please
