### ISSUE TITLE
Trees don't grow on custom grasses

### ISSUE THREAD

**Issue by Hubry** [Vazkii/Botania#3401]
Forge version: .75
Botania version: 0dad652c72436505ed95a2b8da078dac935b2e23

Not even bone meal can convince them to grow

**Comment by williewillus** [comment]
I suspect canPlantOn bug, perhaps in forge

**Comment by Hubry** [comment]
Looks like Forge patches `net.minecraft.world.gen.feature.Feature#isDirt` to check their block tag instead of a few hardcoded blocks for tree growth:

https://github.com/MinecraftForge/MinecraftForge/blob/a3c4ffd2c136830a190bf06381e22aa5c67e4d07/patches/minecraft/net/minecraft/world/gen/feature/Feature.java.patch#L20-L23
