### ISSUE TITLE
Client crash NullPointerException

### ISSUE THREAD

**Issue by ClaudiusMinimus** [Vazkii/Botania#3407]
# Version Information
Forge version:  32.0.108
Botania version:  1.16-401

# Further Information
https://paste.ee/p/gODra
Steps to reproduce:
1. Place a spark
2. Client crash

This has also happened when placing a functioning flower. 
BTW: These client crash happens while playing on our server. The server seems fine.

**Comment by Hubry** [comment]
Update Botania to 402 or downgrade Forge to 106. 
Duplicate of #3397
