### ISSUE TITLE
Runic Altar, an alternative way for x-ray

### ISSUE THREAD

**Issue by tigherspider34** [Vazkii/Botania#3411]
Minecraft version: 1.16.1
Forge version: 32.0.108
Botania-1.16-402

When looking at the Runic Altar with a recipe, all the blocks around becomes invisible. You can still see fluids.

[Proof](https://imgur.com/zw5QVQF)

**Comment by DGilbert23** [comment]
Do you happen to also be using the Immersive Portals (Forge) mod?  I didn't notice this issue until I started using it, and the issue goes away if I remove that mod.

**Comment by elowanut** [comment]
This has been around for some time. As far as I've ever seen it, it's 100% related to the Immersive Portals mod, as DGilbert23 mentioned. Check out #3237, which has been closed (due to inactivity), but is still relevant.
