### ISSUE TITLE
1.16.1 rending issue

### ISSUE THREAD

**Issue by MrStatman80** [Vazkii/Botania#3412]
My game as just crashed as it's a rending issue with JEI and Botania which i'll send Mezz an issue as well

https://pastebin.com/JeqVzNJs

That's the crash report if it helps as i'm playing on 1.16.1 and forge 32.0.18 version and version of Botania is 1.16-402

It says it's due to the mana pylon but i haven't started Botania yet nor have it listed in JEI

**Comment by williewillus** [comment]
Fixed in the next version. It's an  optifine conflict so uninstall it if you don't need it
