### ISSUE TITLE
Coarse Dirt Bore Lens

### ISSUE THREAD

**Issue by cdiglio** [Vazkii/Botania#3415]
# Version Information
Forge version:  31.2.33
Botania version:  r1.15-388

# Further Information
Steps to reproduce:
1. Use Mana Spreader with Bore lens to break coarse dirt

What I expected to happen:
Drop coarse dirt

What happened instead:
More often than not a normal dirt block is dropped

**Comment by williewillus** [comment]
Cannot reproduce. More likely than not you have another mod or datapack changing those drops.

To test if it's actually Botania or something else: Place a coarse dirt block in a creative world and repeatedly run `/loot give @s mine <x> <y> <z>` where you put in the coords of the block. This will ask vanilla to roll the loot table and give you the result.
