### ISSUE TITLE
Optfine book rendering 

### ISSUE THREAD

**Issue by HiddenGhost121** [Vazkii/Botania#3416]
# Version Information
Forge version:  forge-32.0.108
Botania version:  Botania-1.16-402.jar

# Further Information
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)\
Steps to reproduce:
1.install botania
2. install optifine
3. make new world
4. find botania book
5. exit world

What I expected to happen:
the book to be looking normal with proper textures 

What happened instead:
https://imgur.com/RMY9IMR

**Comment by williewillus** [comment]
no one has any idea what the heck optifine is doing, this is unfixable on our end.
