### ISSUE TITLE
client crash when sounds are produced

### ISSUE THREAD

**Issue by MagieMalone** [Vazkii/Botania#3423]
# Version Information
Forge version:  32.0.108
Botania version:  1.16-401

# Further Information
Link to crash log: https://pastebin.com/5iwcztFQ
Steps to reproduce:
1. place clayconia
2. place sand nearby
3. client crash

GDlauncher error:
AL lib: (EE) UpdateDeviceParams: Failed to set Stereo, got 5.1 Surround (Rear) instead
AL lib: (EE) UpdateDeviceParams: Failed to set 44100hz, got 48000hz instead
AL lib: (EE) alc_cleanup: 1 device not closed

What I expected to happen:
no crash

What happened instead:
client crashes. Server stays running

**Comment by williewillus** [comment]
update botania
