### ISSUE TITLE
Botania wont start

### ISSUE THREAD

**Issue by Hummingwood** [Vazkii/Botania#3424]
Version Information
Forge version:   1.16.1-32.0.1
Botania version:  1.16-402

its says "The game crashed whilst initializing game
Error: java.lang.NoClassDefFoundError: Could not initialize class net.minecraft.util.registry.Registry" upon trying to start

here us the crash report
https://gist.github.com/Hummingwood/2b4fa97ef703aaf54ee2e3d551e3a2c7

can you help?

Best Regards - Humming Wood

**Comment by williewillus** [comment]
botania isn't out for 1.16.2 yet. it will be soon
