### ISSUE TITLE
[Bug/Feature request] Drum of the gathering does not make bowls of mushroom soup with mooshrooms

### ISSUE THREAD

**Issue by FizzBuzz3000** [Vazkii/Botania#3427]
# Version Information
Botania version:  1.16.1-403

Currently, the Drum of the gathering does not allow for collection of mushroom soup from mooshrooms with bowls, and [instead shears the mushrooms off the mob, turning it into a regular cow.](https://cdn.discordapp.com/attachments/154261184701267969/747625101607960636/2020-08-24_21.14.55.png)

**Comment by Alwinfy** [comment]
Closed in #3428
