### ISSUE TITLE
Shard of Laputa can't place blocks inside water, instead yeets them from existence

### ISSUE THREAD

**Issue by f-raZ0R** [Vazkii/Botania#3431]
# Version Information
Forge version:  32.0.108
Botania version:  1.16.1-403

# Further Information
Link to crash log: N/A, no crash
Steps to reproduce:
1. First step: Use a shard of laputa to pick up an area containing a body of water
2. Second step: Wait for the shard to lift the water to the top, which will then flow all the way down to the bottom
3. When the shard brings up what should be the blocks under the water, it fails to do so, and instead keeps the water flowing down to the bottom.

What I expected to happen:
The shard would place the blocks inside of the water

What happened instead:
The shard of laputa left a massive hole under the water, and made a mess.

**Comment by williewillus** [comment]
1212d1af2
