### ISSUE TITLE
server crash

### ISSUE THREAD

**Issue by TheNimbleNinja** [Vazkii/Botania#3435]
# Version Information
Forge version:  forge-14.23.5.2854
Botania version:  Botania r1.10-363.jar

# Further Information
https://gist.github.com/TheNimbleNinja/0a2fff1a88af2e876c3a6416c29ded63Steps to reproduce:
no idea wats causing it to crash

What I expected to happen:
it to not crashed
What happened instead:
it crashed

**Comment by williewillus** [comment]
>     at com.zeitheron.hammercore.asm.McHooks.tickTile(McHooks.java:38)

whoever this is is the suspect.

also, 1.12 is no longer supported.
