### ISSUE TITLE
[1.16.2] Crashes on Forge 33.0.21 and above

### ISSUE THREAD

**Issue by Mikeliro** [Vazkii/Botania#3438]
Version Information
Forge version:  33.0.22
Botania version:  405

Further Information
https://gist.github.com/Mikeliro/8f98036b92bf5779d657c58d3489c9c5

Steps to reproduce:
1. Fill a bucket of water
2. Right click with the bucket of water on the Petal Apothecary
Video: https://youtu.be/cFkAzkHftk8

What I expected to happen: 
Fill the Petal Apothecary with water

What happened instead:
The game crashes

**Comment by williewillus** [comment]
forge made an incompatible change
workaround: downgrade to 33.0.20- until this is fixed

**Comment by rjbugarj** [comment]
I have the same problem with just right clicking the petal apothecary with an item in general. Throwing items in works though.

**Comment by williewillus** [comment]
fixed in 406
