### ISSUE TITLE
Botania Version 1.16.1-403 does not like Curios API (Forge) revision notation.

### ISSUE THREAD

**Issue by Dalarrus** [Vazkii/Botania#3441]
![image](https://user-images.githubusercontent.com/12202558/92158375-6b38b080-edf1-11ea-858b-4300a7165b6f.png)
As can be seen, I have curios at a higher version than needed, but the way it's written Botania isn't liking it.

This same issue occurs on the 1.16.2 version of Botania(405) as well, I tried downgrading to fix it, as I am on 1.16.1, but that did not solve the issue.

**Comment by Hubry** [comment]
How is this an issue? 3.0 is newer than 3.0-beta4.
https://www.curseforge.com/minecraft/mc-mods/curios/files/3011016
