### ISSUE TITLE
[1.16.1] Inserting comma separated strings in the orechidPriorityMods config causes server startup crash

### ISSUE THREAD

**Issue by NillerMedDild** [Vazkii/Botania#3442]
# Version Information
Forge version:  1.16.1-32.0.108
Botania version:  Botania-1.16.1-403

# Further Information
https://gist.github.com/NillerMedDild/c126a5cf6ae4512199b268414129fab2
Steps to reproduce:
1. Insert strings into orechidPriorityMods config
2. Launch server
3. Observe crash

Used config: `orechidPriorityMods = ["emendatusenigmatica", "minecraft", "immersiveengineering", "mekanism", "jaopca", "kubejs", "appliedenergistics2", "pneumaticcraft", "tmechworks", "industrialforegoing", "botania", "quark", "pedestals"]`

What I expected to happen:
No crash.

What happened instead:
Crash.

**Comment by Hubry** [comment]
Is this the wrong log? There is no crash indicated there, nor are there any errors related to this config

**Comment by NillerMedDild** [comment]
Woops, wrong log indeed! https://gist.github.com/NillerMedDild/c126a5cf6ae4512199b268414129fab2

**Comment by Hubry** [comment]
Am I an idiot or was this always client only

**Comment by Hubry** [comment]
Yeah I am an idiot.

**Comment by Hubry** [comment]
Fix backported to 1.16.1 in d7f1265e930100e30dd2e27620dd401f3e0ccfc6, closing.

**Comment by NillerMedDild** [comment]
Really appreciate it, thanks.
