### ISSUE TITLE
Orechid entry in Lexica Botania doesn't exist

### ISSUE THREAD

**Issue by theRealMrPinky** [Vazkii/Botania#3450]
This prior issue was closed due to inactivity, but my issue is the exact same. https://github.com/Vazkii/Botania/issues/3320

**Forge version:** 32.0.108
**Botania version:** 1.16-402

**Link to crash log:** N/A
**Steps to reproduce:** See closed issue

**What I expected to happen:**
See closed issue
**What happened instead:**
See closed issue

**Comment by Hubry** [comment]
Ugh, we made a change that was supposed to fix it after that issue got autoclosed...
