### ISSUE TITLE
Using bonemeal on a flower duplicates it 

### ISSUE THREAD

**Issue by justinluo4** [Vazkii/Botania#3451]
On the Valhelsia 3 modpack for 1.16.1, I found that using a bonemeal on my munchdew created another copy of itself on the ground. This worked for any generating or functional flower. 

### Version Info
Botania: 1.16.1-403
Forge: 32.0.108

**Comment by williewillus** [comment]
cannot reproduce

it's probably something in the modpack doing that, so I'd report it to them first.

**Comment by Hubry** [comment]
I'll just leave this discord convo screencap here
![image](https://user-images.githubusercontent.com/26120076/92484629-39a55800-f1ea-11ea-8b9f-b4e3019d1c07.png)

**Comment by justinluo4** [comment]
Ok, thanks for letting me know!
