### ISSUE TITLE
[1.16.2] Using Botania (and its mixins) in a development environment?

### ISSUE THREAD

**Issue by desht** [Vazkii/Botania#3452]
# Version Information
Forge version:  1.16.2-33.0.42
Botania version:  1.16.2-407-SNAPSHOT  (as pulled from http://maven.blamejared.com/)

# Further Information
I'm adding Botania as a dev dependency in PneumaticCraft: Repressurized (as I have been since 1.12.2 days) :
```
    compileOnly fg.deobf("vazkii.botania:Botania:${botania_version}:api")
    runtimeOnly fg.deobf("vazkii.botania:Botania:${botania_version}")
```

However in 1.16.2, it looks like Botania's use of mixins doesn't sit well with a deobf'd development environment, since I get this crash in early startup: https://pastebin.com/0NEDa6SY

I seem to vaguely recall noticing some instructions about getting this to work, but I haven't been able to find them again since.  Is there a trick to getting this working in a dev environment?

**Comment by Hubry** [comment]
I guess we should copy [this part of Patchouli's readme](https://github.com/Vazkii/Patchouli#mixin-troubleshooting) here, tbh

**Comment by desht** [comment]
Yep, that'll be where I noticed it :)  Thanks.

**Comment by desht** [comment]
Hit another Botania-related crash, while running data generation (for PNC:R) - https://pastebin.com/U4VkirAZ

**Comment by williewillus** [comment]
Forge made incompatible changes to data generators. Downgrade forge for now until we update Botania's forge version.

**Comment by williewillus** [comment]
updated the readme 
32288d4
