### ISSUE TITLE
Some textures appear to be broken.

### ISSUE THREAD

**Issue by Stanlijane** [Vazkii/Botania#3454]
When looking through the JEI, some textures appear to be broken. Images attached, no crash log.
Version 1.16.1, Forge 32.0.108, Botania 1.16.1-403.1
![2020-09-05_13 21 41](https://user-images.githubusercontent.com/70814496/92949246-c4739600-f428-11ea-90c8-a0a107e5f578.png)
![2020-09-05_13 21 47](https://user-images.githubusercontent.com/70814496/92949247-c5a4c300-f428-11ea-8e5d-428feb2899c9.png)

**Comment by williewillus** [comment]
does it happen without other mods and RP's?

**Comment by Stanlijane** [comment]
Okay so it seems to work fine when I remove all the other mods except curios, patchouli and JEI, and I kept on the resource pack.. Have been using it for a while and only just now had an issue. Suppose I could add each mod one by one to see what is causing the error. 🤷‍♀️

**Comment by Stanlijane** [comment]
Yes, looks like it is having an issue with Optifine. Have run in to a similar issue with Quark and the item frames (issue posted on the Quark github) where textures are broken when running Optifine, shaders on or off.

**Comment by williewillus** [comment]
yes, optifine's changes have become much more invasive as of 1.16, so there's nothing we can really do on our side.
