### ISSUE TITLE
[1.16.1] Server @ 1 TPS, leading to a crash after 2 minutes online. Something regarding End of flame flower. (spark profiler used.)

### ISSUE THREAD

**Issue by Gbergz** [Vazkii/Botania#3462]
# Version Information
**Forge version:** 1.16.1
**Botania version:** 1.16.1-403.1

# Further Information
**Steps to reproduce:**
No idea how to reproduce exactly, but i've used Spark to profile the 2 minutes before the server crashes. And its something regarding the 'End of Flame' generating flower. Wish I could give more info.

**Spark Results:**
https://spark.lucko.me/#33f6RZ1qkK

**Crash-Report:**
https://gist.github.com/Gbergz/c49e2d4df461fda00881213980da26b7

**What I expected to happen:**
Server not crashing after 2 minutes.
**What happened instead:**
Server opens and then crashes after being online for 2 minutes.

**Comment by williewillus** [comment]
The flower is called an "Endoflame", and it scans for item entities near it to pick up to burn and produce mana.

This probably means someone's setup has gone rogue and they have a ton of items near an endoflame, none of which are burnable. So the endoflame spends a long time looking at all of them but can't remove any.
