### ISSUE TITLE
[1.15.2] Flügel Tiara incorrect wing placement

### ISSUE THREAD

**Issue by Ryanicus2002** [Vazkii/Botania#3464]
Forge version:  (1.15.2) forge-31.2.37
Botania version:  r1.14-388

What I expected to happen:
Standard wing placement on the body, on the back and not clipping.

What happened instead:
Wings clip through the player model; it looks like their orientation is off but placement more or less accurate.
![1](https://user-images.githubusercontent.com/71451851/93489103-f6b74480-f8bb-11ea-8d73-027242ab23e8.png)
![2](https://user-images.githubusercontent.com/71451851/93489111-f9199e80-f8bb-11ea-9429-7586540ec662.png)

Similar clipping issues occur regardless of what wing type is used, always looking like the center of rotation is correctly placed but the angle is off.

**Comment by williewillus** [comment]
known issue, but won't be fixed as development has moved on to 1.16.x
