### ISSUE TITLE
[1.16.2] Crash on launch with Apotheosis mod

### ISSUE THREAD

**Issue by Keltas** [Vazkii/Botania#3465]
When launching the game with the following mods installed the game crashes on launch. No crash log just a message that the game has crashed "Exit Code: 0". I have the following installed running using Twitch launcher:  
Minecraft 1.16.2
forge-33.0.61
Apotheosis-1.16.2-4.2.1.jar
Botania-1.16.2-406.jar
curios-forge-1.16.2-4.0.0.1.jar
Patchouli-1.16-42.jar
Placebo-1.16.2-4.2.0.jar

Here is the "latest" log file: https://pastebin.com/xGAB4Y2g

**Comment by williewillus** [comment]
mixin bug, update to forge 1.16.3 build 34.0.8 or above (if possible) to fix, there's nothing on our side we can do
