### ISSUE TITLE
[1.16.2] Crash in dev environment

### ISSUE THREAD

**Issue by Workbench61** [Vazkii/Botania#3467]
# Version Information
Forge version:  1.16.2-33.0.32
Botania version:  1.16.2-406
Java: 1.8.0_252 JVM: 25.252-b09(AdoptOpenJDK) Arch: amd64

# Further Information
Log: https://gist.github.com/Workbench61/c3279f9df254c86200ff353e53b2bee0

Updating my addon and getting crash when running task runClient.

**Comment by williewillus** [comment]
https://github.com/Vazkii/Botania#mixin-troubleshooting
