### ISSUE TITLE
Manaseer Monocle range highlight causes certain objects to become invisible

### ISSUE THREAD

**Issue by jpjuncker** [Vazkii/Botania#3468]
# Version Information
Forge version:  32.0.108
Botania version:  1.16.1-403.1

# Further Information
Steps to reproduce:
1. Wear monocle
2. Look at flower with a spreader or mana pool in its effective range

What I expected to happen:

Spreaders/mana in pools is visible

What happened instead:

Monocle range visualization made them invisible.
![2020-09-22_16 02 20](https://user-images.githubusercontent.com/18267095/93931997-865e5800-fced-11ea-8855-357d93320464.png)
![2020-09-22_16 02 23](https://user-images.githubusercontent.com/18267095/93932001-88281b80-fced-11ea-9d37-53a5429482d6.png)

**Comment by williewillus** [comment]
Does it happen in fabulous mode?

**Comment by jpjuncker** [comment]
I am unaware of this mode.

**Comment by jpjuncker** [comment]
Just realized that refers to Minecraft's graphics setting, not something in Botania. Answer: partially. Spreaders render, but mana in pool does not.
![2020-09-23_19 40 55](https://user-images.githubusercontent.com/18267095/94084955-d19f6600-fdd4-11ea-8c57-3db3435c142c.png)
![2020-09-23_19 40 53](https://user-images.githubusercontent.com/18267095/94084960-d3692980-fdd4-11ea-9aec-632c798da55c.png)
