### ISSUE TITLE
Invisible mana spreader 1.16.1

### ISSUE THREAD

**Issue by kuroneko2627** [Vazkii/Botania#3469]
I just cant see the mana spreaders

![Captura](https://user-images.githubusercontent.com/71740063/93952346-35129080-fd0e-11ea-9381-cb9dd504f663.PNG)
and there  are some missing textures

![tygr](https://user-images.githubusercontent.com/71740063/93952394-55dae600-fd0e-11ea-91be-dc4e46046ba5.PNG)

**Comment by kuroneko2627** [comment]
the texture is a bowl of water

**Comment by williewillus** [comment]
version? is optifine installed?

**Comment by kuroneko2627** [comment]
1.16.1 and optifine is put in as a mod but its still invisible without
optifine

**Comment by Thomsch** [comment]
I have the same problem with the same version as willie. I also don't see the water in the petal apothecary.

**Comment by kuroneko2627** [comment]
and mana on mana pools and some other small things

**Comment by JustLiam040** [comment]
I was also having this issue, missing water in the apothecary and invisible spreaders etc. It is worth noting that removing optifine fixed it for me.

**Comment by Fluymer** [comment]
I am also experiencing the same problem, I do have Optifine installed. Minecraft version 1.16.1

**Comment by ValloZn** [comment]
I had the same problem but removing optifine from the mods folder fixed it! Now I am searching for a solution to keep Optifine installed without the textures being invisible...

**Comment by waxiss39** [comment]
how to play with optifine and not have the invisible block?

**Comment by williewillus** [comment]
you don't
