### ISSUE TITLE
Thermalily infinitely takes lava 1.12.2

### ISSUE THREAD

**Issue by TheDeaX-Lab** [Vazkii/Botania#3470]
# Version Information
Minecraft version: 1.12.2
Forge version:  14.23.5.2847
Botania version:  r1.10-363

# Further Information
No crash. lava disappears into the void when thermalily cools down
Steps to reproduce:
1. place thermalily
2. place near lava
3. wait when thermalily cools down
4. place near lava again
5. lava disappears into the void

What I expected to happen:
I wanted to make a mana farm using a ritual from Bloodmagic Syrinade of Hell
https://youtu.be/JMizryz-p2o

What happened instead:
When Thermalily cools down, it infinitely takes lava into itself without generating mana

**Comment by Hubry** [comment]
Works as expected on 1.16 - the flower doesn't accept lava when generating, then it enters the cooldown, wasting placed lava (which also refreshes the cooldown) until the cooldown ends.

I went and tested this on 1.12.2 as well, and the results are exactly the same.
Please make sure you aren't dropping lava during the cooldown (the period when the flower is generating is not the cooldown!). If you are sure, show a recording of the bug, or an album of screenshots including `/blockdata <x> <y> <z> {}` output containing the flower's data.

That youtube video was recorded on an older version of Botania for 1.7.10, which predates the introduction of lava cooldown resetting - the first build including it was posted about a week later.
