### ISSUE TITLE
1.16.2/1.16.3 crash

### ISSUE THREAD

**Issue by BedrockLegends** [Vazkii/Botania#3473]
# Version Information
Forge version:  34.0.13 to 34.1.0
Botania version:  Botania-1.16.2-406
[crash-2020-09-25_11.13.09-client.txt](https://github.com/Vazkii/Botania/files/5283982/crash-2020-09-25_11.13.09-client.txt)

# Further Information
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)\
Steps to reproduce:
1. First step
2. Second step
3. etc...

What I expected to happen:
A fix
What happened instead:

**Comment by williewillus** [comment]
Stop using experimental and unstable forge forks of Sodium

**Comment by BedrockLegends** [comment]
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 9/27/20 12:33 PM
Description: Rendering overlay

java.lang.IllegalStateException: Failed to load description for particle botania:wisp
	at net.minecraft.client.particle.ParticleManager.func_215236_a(ParticleManager.java:226) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.particle.ParticleManager.lambda$null$0(ParticleManager.java:169) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640) ~[?:1.8.0_252] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1632) ~[?:1.8.0_252] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_252] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_252] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_252] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_252] {}
Caused by: java.io.FileNotFoundException: botania:particles/wisp.json
	at net.minecraft.resources.SimpleReloadableResourceManager.func_199002_a(SimpleReloadableResourceManager.java:63) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:solarflux:coremodone}
	at net.minecraft.client.particle.ParticleManager.func_215236_a(ParticleManager.java:205) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	... 7 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:483) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
-- Overlay render details --
Details:
	Overlay name: net.minecraft.client.gui.ResourceLoadProgressGui
Stacktrace:
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:483) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:953) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:584) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.3.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_252] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_252] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.3-34.1.0.jar:34.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-7.0.1.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-7.0.1.jar:?] {re:classloading}


-- System Details --
Details:
	Minecraft Version: 1.16.3
	Minecraft Version ID: 1.16.3
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_252, AdoptOpenJDK
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), AdoptOpenJDK
	Memory: 2766143472 bytes (2637 MB) / 4294967296 bytes (4096 MB) up to 10737418240 bytes (10240 MB)
	CPUs: 16
	JVM Flags: 23 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx12288m -Xms12288m -Xms4G -Xmx10G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1
	ModLauncher: 7.0.1+78+master.e9771d8
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.1.jar mixin PLUGINSERVICE 
		/eventbus-3.0.3-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.3-34.1.0.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.3-34.1.0.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.3-34.1.0.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.3-34.1.0.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.1.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.3-34.1.0.jar fml TRANSFORMATIONSERVICE 
	FML: 34.1
	Forge: net.minecraftforge:34.1.0
	FML Language Providers: 
		javafml@34.1
		minecraft@1
	Mod List: 
		NetherPortalFix_1.16.3-7.2.0.jar NetherPortalFix {netherportalfix@7.2.0 COMMON_SETUP}
		restrictedportals-1.16.2-1.1.4.jar Restricted Portals {restrictedportals@1.16.2-1.1.4 COMMON_SETUP}
		forge-1.16.3-geckolib-2.1.1.jar GeckoLib {geckolib@2.1.1 COMMON_SETUP}
		upsizer-mc1.16.3-6.0.jar Upsizer {upsizer@6.0 COMMON_SETUP}
		prefab-1.6.2.0.jar Prefab {prefab@1.6.2.0 COMMON_SETUP}
		ExtendedCrafting-1.16.3-3.1.1.jar Extended Crafting {extendedcrafting@3.1.1 COMMON_SETUP}
		ContentCreatorIntegration-1.16.3-1.6.2.jar Content Creator Integration {contentcreatorintegration@1.6.2 COMMON_SETUP}
		borderless-1.16.3-1.1.0.jar Borderless Window {borderless@1.16.3-1.1.0 COMMON_SETUP}
		mcw-windows-1.0.2-mc1.16.3.jar Macaw's Windows {mcwwindows@1.0.2 COMMON_SETUP}
		torohealth-1.16.3-forge-2.jar ToroHealth {torohealth@NONE COMMON_SETUP}
		modnametooltip_1.16.2-1.15.0.jar Mod Name Tooltip {modnametooltip@1.15.0 COMMON_SETUP}
		KleeSlabs_1.16.3-9.2.0.jar KleeSlabs {kleeslabs@9.2.0 COMMON_SETUP}
		IronJetpacks-1.16.3-4.1.1.jar Iron Jetpacks {ironjetpacks@4.1.1 COMMON_SETUP}
		ForgeEndertech-1.16.3-7.0.4.0-build.0017.jar Forge Endertech {forgeendertech@7.0.4.0 COMMON_SETUP}
		CTM-MC1.16.1-1.1.1.5.jar ConnectedTexturesMod {ctm@MC1.16.1-1.1.1.5 COMMON_SETUP}
		CookingForBlockheads_1.16.3-9.2.1.jar Cooking for Blockheads {cookingforblockheads@9.2.1 COMMON_SETUP}
		Controlling-7.0.0.5.jar Controlling {controlling@7.0.0.5 COMMON_SETUP}
		ReAuth-1.16-Forge-3.9.1.jar ReAuth {reauth@3.9.1 COMMON_SETUP}
		Placebo-1.16.2-4.2.0.jar Placebo {placebo@4.2.0 COMMON_SETUP}
		citadel-1.4.0.jar Citadel {citadel@1.4.0 COMMON_SETUP}
		ftb-gui-library-1.0.0.18.jar FTB GUI Library {ftbguilibrary@1.0.0.18 COMMON_SETUP}
		rangedpumps-0.8.2.jar Ranged Pumps {rangedpumps@0.8.2 COMMON_SETUP}
		potionsmaster-0.1.21-1.16.3-34.0.9.jar Potions Master {potionsmaster@0.1.21 COMMON_SETUP}
		culinaryconstruct-forge-1.16.2-4.0.0.0.jar Culinary Construct {culinaryconstruct@1.16.2-4.0.0.0 COMMON_SETUP}
		Bookshelf-1.16.3-8.4.11.jar Bookshelf {bookshelf@8.4.11 COMMON_SETUP}
		u_team_core-1.16.3-3.1.9.181.jar U Team Core {uteamcore@3.1.9.181 COMMON_SETUP}
		randompatches-1.16.2-1.22.1.2.jar RandomPatches {randompatches@1.16.2-1.22.1.2 COMMON_SETUP}
		ChanceCubes-1.16.2-5.0.2.382.jar Chance Cubes {chancecubes@1.16.2-5.0.2.382 COMMON_SETUP}
		buildinggadgets-3.7.0.jar Building Gadgets {buildinggadgets@3.7.0 COMMON_SETUP}
		DarkUtilities-1.16.3-6.0.1.jar Dark Utilities {darkutils@6.0.1 COMMON_SETUP}
		Apotheosis-1.16.2-4.2.1.jar Apotheosis {apotheosis@4.2.1 COMMON_SETUP}
		mcw-doors-1.0.0-mc1.16.3.jar Macaw's Doors {mcwdoors@1.0.0 COMMON_SETUP}
		speedyhoppers-1.16.3-1.jar Speedy Hoppers {speedyhoppers@1.16.3-1 COMMON_SETUP}
		SnowRealMagic-1.16.2-2.1.0.jar Snow! Real Magic! {snowrealmagic@2.1.0 COMMON_SETUP}
		CauldronRecipes-1.16.3-4.0.1.jar CauldronRecipes {cauldronrecipes@4.0.1 COMMON_SETUP}
		FpsReducer-mc1.16.3-1.18.jar FPS Reducer {fpsreducer@mc1.16.3-1.18 COMMON_SETUP}
		JustEnoughResources-1.16.3-0.12.0.100.jar Just Enough Resources {jeresources@0.12.0.100 COMMON_SETUP}
		Hydrogel-1.16.2-2.1.0.jar HydroGel {hydrogel@2.1.0 COMMON_SETUP}
		ftb-teams-1.0.1.12.jar FTB Teams {ftbteams@1.0.1.12 COMMON_SETUP}
		shetiphiancore-1.16-3.8.2.jar ShetiPhian-Core {shetiphiancore@3.8.2 COMMON_SETUP}
		MysticalAgradditions-1.16.3-4.1.0.jar Mystical Agradditions {mysticalagradditions@4.1.0 COMMON_SETUP}
		[1.16.X-1.0.10]+Dragon+Mounts+Legacy.jar Dragon Mounts: Legacy {dragonmounts@1.0.10 COMMON_SETUP}
		refinedstorage-1.9.6.jar Refined Storage {refinedstorage@1.9.6 COMMON_SETUP}
		structure-gel-api-1.16.3-1.3.5.jar Structure Gel API {structure_gel@1.3.5 COMMON_SETUP}
		PackMenu-1.16.2-2.2.0.jar Pack Menu {packmenu@2.2.0 COMMON_SETUP}
		alltheores-0.1.7-1.16.3-34.0.8.jar AllTheOres {alltheores@0.1.7 COMMON_SETUP}
		mcw-bridges-1.0.4-mc1.16.3.jar Macaw's Bridges {mcwbridges@1.0.4 COMMON_SETUP}
		industrial-foregoing-1.16.3-3.1.0-7b7cd48.jar Industrial Foregoing {industrialforegoing@3.1.0 COMMON_SETUP}
		torchmaster-2.3.3-alpha.jar Torchmaster {torchmaster@2.3.3-alpha COMMON_SETUP}
		TipTheScales-1.16.3-3.0.0.5.jar TipTheScales {tipthescales@3.0.0.5 COMMON_SETUP}
		AmbientSounds_v3.0.21_mc1.16.2.jar Ambient Sounds {ambientsounds@3.0.3 COMMON_SETUP}
		GreaterEye-1.16.3-1.1.2.jar GreaterEye {greater_eye@1.1.1 COMMON_SETUP}
		valkyrielib-1.16.2-3.0.3.1.jar ValkyrieLib {valkyrielib@1.16.2-3.0.3.1 COMMON_SETUP}
		simplylight-1.16.3-1.0.2.jar Simply Light {simplylight@1.16.3-1.0.2 COMMON_SETUP}
		SolarFluxReborn-1.16.3-16.1.1.jar Solar Flux Reborn {solarflux@16.1.1 COMMON_SETUP}
		curios-forge-1.16.3-4.0.2.0.jar Curios API {curios@1.16.3-4.0.2.0 COMMON_SETUP}
		Botania-1.16.2-406.jar Botania {botania@1.16.2-406 COMMON_SETUP}
		Splashy-1.16.3-5.0.1.jar Splashy {splashy@5.0.1 COMMON_SETUP}
		Patchouli-1.16.2-44.jar Patchouli {patchouli@1.16.2-44 COMMON_SETUP}
		collective-1.16.3-1.40.jar Collective {collective@1.40 COMMON_SETUP}
		betterweather-1.0.3.jar Better Weather {betterweather@1.0.1 COMMON_SETUP}
		extlights-3.1.jar Extended Lights {extlights@3.1 COMMON_SETUP}
		DrawersTooltip-1.16.2-2.1.0.jar Drawers Tooltip {drawerstooltip@2.1.0 COMMON_SETUP}
		betbeacpl_1.16.2-1.1.jar Better Beacon Placement {betbeacpl@1.1 COMMON_SETUP}
		Gobber2-1.16.3-2.3.10.jar Gobber 2 {gobber2@2.3.8 COMMON_SETUP}
		ftb-ultimine-1.1.0.10.jar FTB Ultimine {ftbultimine@1.1.0.10 COMMON_SETUP}
		Server_Utils-1.16.3-1.4.3.jar Elrol's Server Utilities {serverutilities@1.16.3-1.4.3 COMMON_SETUP}
		buildersaddition-1.16.3-20200927a.jar Builders Crafts & Addition {buildersaddition@1.16.3-20200927a COMMON_SETUP}
		Runelic-1.16.3-5.0.1.jar Runelic {runelic@5.0.1 COMMON_SETUP}
		constructionwand-1.16.2-1.4.jar Construction Wand {constructionwand@1.16.2-1.4 COMMON_SETUP}
		mcws-roofs-1.16.3-v2.0.0.jar Macaw's Roofs {mcwroofs@2.0.0 COMMON_SETUP}
		AI-Improvements-1.16.2-0.3.0.jar AI-Improvements {aiimprovements@0.3.0 COMMON_SETUP}
		moreoverlays-1.18.8-mc1.16.3.jar More Overlays Updated {moreoverlays@1.18.8-mc1.16.3 COMMON_SETUP}
		cherishedworlds-forge-1.16.2-5.0.0.0.jar Cherished Worlds {cherishedworlds@1.16.2-5.0.0.0 COMMON_SETUP}
		AdChimneys-1.16.3-6.0.2.0-build.0017.jar Advanced Chimneys {adchimneys@6.0.2.0 COMMON_SETUP}
		ironcoals-3.1.0.jar Iron Coals {ironcoals@3.1.0 COMMON_SETUP}
		InventoryEssentials_1.16.3-2.2.0.jar Inventory Essentials {inventoryessentials@2.2.0 COMMON_SETUP}
		BetterBurning-1.16.3-4.0.2.jar BetterBurning {betterburning@4.0.2 COMMON_SETUP}
		bwncr-1.16.3-3.8.15.jar Bad Wither No Cookie Reloaded {bwncr@1.16.3-3.8.15 COMMON_SETUP}
		speedyladders-1.16.3-1.jar Speedy Ladders {speedyladders@1.16.3-1 COMMON_SETUP}
		FastLeafDecay-v25.jar FastLeafDecay {fastleafdecay@v25 COMMON_SETUP}
		PrettyBeaches_1.16.3-5.2.0.jar Pretty Beaches {prettybeaches@5.2.0 COMMON_SETUP}
		Cyclic-1.16.3-0.7.1.jar Cyclic {cyclic@1.16.3-0.7.1 COMMON_SETUP}
		BetterAdvancements-1.16.3-0.1.0.102.jar Better Advancements {betteradvancements@0.1.0.102 COMMON_SETUP}
		Kiwi-1.16.2-3.3.0.jar Kiwi {kiwi@3.3.0 COMMON_SETUP}
		ClientTweaks_1.16.3-5.2.0.jar Client Tweaks {clienttweaks@5.2.0 COMMON_SETUP}
		BedBenefits-1.16.3-3.0.1.jar BedBenefits {bedbenefits@3.0.1 COMMON_SETUP}
		Cucumber-1.16.3-4.1.2.jar Cucumber Library {cucumber@4.1.2 COMMON_SETUP}
		TrashSlot_1.16.3-12.2.0.jar TrashSlot {trashslot@12.2.0 COMMON_SETUP}
		mining-helmet-1.16.3-1.0.9.jar Mining Helmet {mining_helmet@1.0.9 COMMON_SETUP}
		woot-1.16.2-1.0.0.0.jar Woot {woot@1.16.2-1.0.0.0 COMMON_SETUP}
		snad-1.0.1-1.16.3.jar Snad {snad@1.0.1 COMMON_SETUP}
		OldJavaWarning-1.16.3-5.0.1.jar OldJavaWarning {oldjavawarning@5.0.1 COMMON_SETUP}
		item-filters-2.2.2.17.jar Item Filters {itemfilters@2.2.2.17 COMMON_SETUP}
		jei-1.16.3-7.3.2.36.jar Just Enough Items {jei@7.3.2.29 COMMON_SETUP}
		AttributeFix-1.16.3-8.0.2.jar AttributeFix {attributefix@8.0.2 COMMON_SETUP}
		invtweaks-1.16.2-1.0.0.jar Inventory Tweaks Renewed {invtweaks@1.16.2-1.0.0 COMMON_SETUP}
		Waystones_1.16.3-7.3.0.jar Waystones {waystones@7.3.0 COMMON_SETUP}
		PassableFoliage-1.16.2-2.1.0.jar Passable Foliage {passablefoliage@2.1.0 COMMON_SETUP}
		Clumps-6.0.0.10.jar Clumps {clumps@6.0.0.10 COMMON_SETUP}
		appliedenergistics2-8.1.0-alpha.3.jar Applied Energistics 2 {appliedenergistics2@8.1.0-alpha.3 COMMON_SETUP}
		TravelersBackpack-1.16.2-5.1.1.jar Traveler's Backpack {travelersbackpack@5.1.1 COMMON_SETUP}
		NaturesCompass-1.16.3-1.8.5.jar Nature's Compass {naturescompass@1.16.3-1.8.5 COMMON_SETUP}
		SimpleStorageNetwork-1.16.2-1.1.1.jar Simple Storage Network {storagenetwork@1.16.2-1.1.1 COMMON_SETUP}
		BotanyPots-1.16.3-5.0.1.jar BotanyPots {botanypots@5.0.1 COMMON_SETUP}
		VanillaTweaks-1.16.2-1.5.32.jar VanillaTweaks {vanillatweaks@1.16.2-1.5.32 COMMON_SETUP}
		AdHooks-1.16.3-6.1.1.0-build.0017.jar Advanced Hook Launchers {adhooks@6.1.1.0 COMMON_SETUP}
		FarmingForBlockheads_1.16.3-7.2.0.jar Farming for Blockheads {farmingforblockheads@7.2.0 COMMON_SETUP}
		pneumaticcraft-repressurized-1.16.3-2.4.1-44.jar PneumaticCraft: Repressurized {pneumaticcraft@1.16.3-2.4.1-44 COMMON_SETUP}
		demagnetize-forge-1.16.2-1.2.2.jar Demagnetize {demagnetize@1.16.2-1.2.2 COMMON_SETUP}
		nhacampfire_1.16.2-2.4.jar No Hostiles Around Campfire {nhacampfire@2.4 COMMON_SETUP}
		mcjtylib-1.16-5.0.9.jar McJtyLib {mcjtylib@1.16-5.0.9 COMMON_SETUP}
		rftoolsbase-1.16-2.0.4-beta.jar RFToolsBase {rftoolsbase@1.16-2.0.4-beta COMMON_SETUP}
		xnet-1.16-3.0.6-beta.jar XNet {xnet@1.16-3.0.6-beta COMMON_SETUP}
		rftoolscontrol-1.16-4.0.4-beta.jar RFToolsControl {rftoolscontrol@1.16-4.0.4-beta VALIDATE}
		restrictions-1.16-3.0.2-beta.jar Restrictions {restrictions@1.16-3.0.2-beta COMMON_SETUP}
		ClickMachine-1.16.2-4.1.0.jar Click Machine {clickmachine@4.1.0 COMMON_SETUP}
		environmentalcreepers-forge-1.16.2-1.6.0.jar Environmental Creepers {environmentalcreepers@1.6.0 COMMON_SETUP}
		ToastControl-1.16.2-4.2.0.jar Toast Control {toastcontrol@4.2.0 COMMON_SETUP}
		mininggadgets-1.6.0.jar Mining Gadgets {mininggadgets@1.6.0 COMMON_SETUP}
		CraftTweaker-1.16.3-7.0.0.45.jar CraftTweaker {crafttweaker@7.0.0.45 COMMON_SETUP}
		Ars+Nouveau-1.16.3+0.16.1.jar Ars Nouveau {ars_nouveau@1.0 COMMON_SETUP}
		rftoolspower-1.16-3.0.5-beta.jar RFToolsPower {rftoolspower@1.16-3.0.5-beta COMMON_SETUP}
		extradisks-1.16.2-1.3.2.jar Extra Disks {extradisks@1.3.2 COMMON_SETUP}
		ftb-chunks-1.1.1.35.jar FTB Chunks {ftbchunks@1.1.1.35 COMMON_SETUP}
		forge-1.16.3-34.1.0-universal.jar Forge {forge@34.1.0 COMMON_SETUP}
		Waddles-1.16.3-0.8.8.jar Waddles {waddles@1.16.3-0.8.8 COMMON_SETUP}
		scuba-gear-1.16.3-1.0.1.jar Scuba Gear {scuba_gear@1.0.1 COMMON_SETUP}
		blame-1.16.2-1.1.0.jar Blame! {blame@1.16.2-1.1.0 COMMON_SETUP}
		MysticalAgriculture-1.16.3-4.1.0.jar Mystical Agriculture {mysticalagriculture@4.1.0 COMMON_SETUP}
		ironchest-1.16.2-11.1.5.jar Iron Chests {ironchest@1.16.2-11.1.5 COMMON_SETUP}
		infernalmobs-1.16.2.1.jar Infernal Mobs {infernalmobs@1.16.2.1 COMMON_SETUP}
		CraftingTweaks_1.16.3-12.2.0.jar Crafting Tweaks {craftingtweaks@12.2.0 COMMON_SETUP}
		forge-1.16.3-34.1.0-client.jar Minecraft {minecraft@1.16.3 COMMON_SETUP}
		EnchantmentDescriptions-1.16.3-5.0.1.jar EnchantmentDescriptions {enchdesc@5.0.1 COMMON_SETUP}
		theoneprobe-1.16-3.0.4-beta.jar The One Probe {theoneprobe@1.16-3.0.4-beta COMMON_SETUP}
		bspawncontrol_1.16.2-1.1.jar Better Spawner Control {bspawncontrol@1.1 COMMON_SETUP}
		MouseTweaks-2.13-mc1.16.2.jar Mouse Tweaks {mousetweaks@2.13 COMMON_SETUP}
		ToolBelt-1.16.2-1.14.4.jar Tool Belt {toolbelt@1.14.4 COMMON_SETUP}
		titanium-1.16.3-3.1.0.jar Titanium {titanium@3.1.0 COMMON_SETUP}
		nccreepers_1.16.2-1.2.jar Naturally Charged Creepers {nccreepers@1.2 COMMON_SETUP}
		ImmersiveEngineering-1.16.3-4.0.1-121.jar Immersive Engineering {immersiveengineering@1.16.3-4.0.1-118 COMMON_SETUP}
		useful_railroads-1.16.3-1.4.4.31.jar Useful Railroads {usefulrailroads@1.4.4.31 COMMON_SETUP}
		concreteconversion-1.16.3-5.0.0.0.jar Concrete Conversion {concreteconversion@1.16.3-5.0.0.0 COMMON_SETUP}
		allthemodium-1.0.14-1.16.3-34.0.8.jar Allthemodium {allthemodium@1.0.14 COMMON_SETUP}
		CreativeCore_v2.0.7_mc1.16.2.jar CreativeCore {creativecore@2.0.0 COMMON_SETUP}
		forbidden_arcanus-1.16.3-1.0.1.jar Forbidden & Arcanus {forbidden_arcanus@1.16.3-1.0.1 COMMON_SETUP}
		ceilingtorch-1.16.2-v1.8.jar Ceiling Torch {ceilingtorch@v1.8 COMMON_SETUP}
		rftoolsbuilder-1.16-3.0.6.jar RFToolsBuilder {rftoolsbuilder@1.16-3.0.6 COMMON_SETUP}
		extragolems-11.1.3.jar Extra Golems {golems@11.1.3 COMMON_SETUP}
		AzureDooms-Doom-Mod-1.16.3-3.1.6.jar Azuredooms Doom Mod {doomweapon@3.1.6 COMMON_SETUP}
		rats-6.1.0-1.16.3.jar Rats {rats@6.1.0 COMMON_SETUP}
		pamhc2foodcore-1.16.2-1.0.1.jar Pam's HarvestCraft 2 Food Core {pamhc2foodcore@version COMMON_SETUP}
		ftb-backups-2.1.1.6.jar FTB Backups {ftbbackups@2.1.1.6 COMMON_SETUP}
		lava-monster-1.16.3-1.0.8.jar Lava Monster {lava_monster@1.0.8 COMMON_SETUP}
		polymorph-forge-1.16.2-0.14.jar Polymorph {polymorph@1.16.2-0.14 COMMON_SETUP}
		multibeds-1.16-1.7.4.jar Multi-Beds {multibeds@1.7.4 COMMON_SETUP}
		StorageDrawers-1.16.2-8.1.0.jar Storage Drawers {storagedrawers@1.16.2-8.1.0 COMMON_SETUP}
		enderchests-1.16-1.7.3.jar EnderChests {enderchests@1.7.3 COMMON_SETUP}
		FastFurnace-1.16.2-4.2.0.jar FastFurnace {fastfurnace@4.2.0 COMMON_SETUP}
		AppleSkin-mc1.16.2-forge-1.0.14.jar AppleSkin {appleskin@1.0.14 COMMON_SETUP}
		engineersdecor-1.16.3-1.1.2-b8.jar Engineer's Decor {engineersdecor@1.1.2-b8 COMMON_SETUP}
		moredragoneggs-1.4.jar More Dragon Eggs {moredragoneggs@1.4 COMMON_SETUP}
		byg-1.0.7.jar Oh The Biomes You'll Go {byg@1.0.7 COMMON_SETUP}
		Aquaculture-1.16.3-2.1.0.jar Aquaculture 2 {aquaculture@1.16.3-2.1.0 COMMON_SETUP}
		betterbedrockgenerator-1.16.2-0.1.0.jar Better Bedrock Generator {betterbedrockgenerator@0.1.0 COMMON_SETUP}
		refinedstorageaddons-0.7.2.jar Refined Storage Addons {refinedstorageaddons@0.7.2 COMMON_SETUP}
		extremeSoundMuffler-2.1.1_Forge-1.16.2.jar Extreme Sound Muffler {extremesoundmuffler@2.1.1_forge-1.16.2 COMMON_SETUP}
		CosmeticArmorReworked-1.16.2-v1.jar CosmeticArmorReworked {cosmeticarmorreworked@1.16.2-v1 COMMON_SETUP}
		EnderMail-1.16.3-1.1.5.jar Ender Mail {endermail@1.16.3-1.1.5 COMMON_SETUP}
		farlanders-1.16.3-1.3.3.jar The Farlanders {farlanders@1.3.3 COMMON_SETUP}
		DefaultOptions_1.16.3-12.2.0.jar Default Options {defaultoptions@12.2.0 COMMON_SETUP}
	Kiwi Modules: 
		kiwi:contributors
		kiwi:data
		snowrealmagic:core
	Launched Version: 1.16.3
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1080/PCIe/SSE2 GL version 4.6.0 NVIDIA 456.38, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: 
	Current Language: English (US)
	CPU: 16x AMD Ryzen 7 2700X Eight-Core Processor 


@williewillus Still crashes without Forks of Sodium

**Comment by williewillus** [comment]
This appears to be https://github.com/MinecraftForge/MinecraftForge/issues/7358

Try with just botania. If it still happens, it's a forge bug, otherwise it's probably an issue in your other mods.
