### ISSUE TITLE
Terra Axe CME

### ISSUE THREAD

**Issue by Darkere** [Vazkii/Botania#3474]
# Version Information
Forge version:  32.0.108
Botania version:  1.16.1-403.1

# Further Information
Link to crash log: https://gist.github.com/Darkere/b034bf2a7aaf9d0740897faf8d1faf8e
Steps to reproduce:
1. Player used Terra axe with FTB Ultimine

**Comment by williewillus** [comment]
what is ftb ultimine?

**Comment by Darkere** [comment]
New Veinminer thing. 
https://www.curseforge.com/minecraft/mc-mods/ftb-ultimine

**Comment by Hubry** [comment]
Analysis: 
* breaking a compatible block with the axe puts a block swapper into a per world set
* on world tick, the axe goes through the swappers for the world
* ticking a swapper fires a break event for every block broken
* Ultimine grabs the event and triggers using the axe if the activation key is pressed
* repeat point 1 here
* CME on continuing iterating through the set
