### ISSUE TITLE
Can't open Lexica entry from item in inventory

### ISSUE THREAD

**Issue by ToMe25** [Vazkii/Botania#3475]
# Version Information
Forge version:  1.16.3-34.1.1
Botania version:  1.16.2-406

# Further Information
Link to crash log: This isn't a crash, so i don't have a crash-report.
Steps to reproduce:
1. get a Lexica Botania
2. run `/advancement grant @s everything` to unlock all entries
3. get a Manasteel Chestplace(as an example)
4. hover over it with your mouse
5. see no icon
6. press ctrl to open the Lexica Botania page
7. see nothing happen

Here an image of the missing icon:
![2020-10-02_11 26 30_edit](https://user-images.githubusercontent.com/38815969/94909597-b652eb80-04a3-11eb-98bf-c0481ed4d132.png)

## What I expected to happen:
I would expect that to open the relevant Lexica Botania Page, as it did in older versions.

## What happened instead:
Nothing.

**Comment by ToMe25** [comment]
Additional Information i figured out randomly:
this function seems to work in JEI, but neither in the player inventory, nor in chests.

**Comment by williewillus** [comment]
is this just with botania?

**Comment by ToMe25** [comment]
Yes, more or less.
I could reproduce it not working in a dev workspace that was just a local clone of this repo with gradle set up.
The only time i noticed the in jei thing was with a few more mods, mainly iron chests, better barrels and voxel minimap+worldmap.

**Comment by ToMe25** [comment]
Updating Forge to version 34.1.12 or newer fixes this issue.
