### ISSUE TITLE
Missing textures on floating plants

### ISSUE THREAD

**Issue by GamingGlitchGG** [Vazkii/Botania#3478]
# Version Information
Forge version:  32.0.108
Botania version:  403.1

# Further Information
Every item with the name "Floating" in it is missing textures both in-inventory and in-game, the lexica book is also missing textures on-hand.
![Screenshot_1](https://user-images.githubusercontent.com/68930560/95027963-e3092d80-0672-11eb-9e32-32654b368ed7.png)

**Comment by williewillus** [comment]
Do you have optifine

**Comment by GabrielPIPON123** [comment]
Why, then, how do I play without lowering my pc's performance

**Comment by williewillus** [comment]
there's your problem.
