### ISSUE TITLE
Crash with botania.wisp

### ISSUE THREAD

**Issue by YannoteX** [Vazkii/Botania#3479]
# Version Information
Forge version:  34.1.0 (1.16.3)
Botania version:  1.16.2-406

# Further Information
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)\
Steps to reproduce:
Launching the game

What I expected to happen:
Play the game

What happened instead:
Back to launcher with a error message : 
       
        The game crashed whilst rendering overlay
        Error: java.lang.IllegalStateException: Failed to load description for particle botania:wisp
        Exit Code: -1

Thank you

**Comment by williewillus** [comment]
Try with just botania and add mods back until you find the offending one

**Comment by YannoteX** [comment]
I just noticed than 5 mods had the same issue so let's go

**Comment by YannoteX** [comment]
Found it sorry for the inconvenience

**Comment by DanDragon401** [comment]
I have the same issue. What mod was it?

**Comment by YannoteX** [comment]
Furenzu

**Comment by DanDragon401** [comment]
Oh, It was an issue with Azuredoom's Doom Mod. I'll contact the creator of that mod

**Comment by YannoteX** [comment]
I forgot that one but the both of them was making the game crash

**Comment by DanDragon401** [comment]
Mod author just confirmed that they work perfectly fine together. You apparently need Gecko Lib. Link: https://www.curseforge.com/minecraft/mc-mods/geckolib

**Comment by YannoteX** [comment]
Ok thank you
