### ISSUE TITLE
Missing Keybinds when updating from Botania-1.16.2-406 to Botania-1.16.2-407 MC 1.16.3

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Vazkii/Botania#3483]
# Version Information
Forge version: forge-34.1.19
Botania version: Botania-1.16.2-407

# Further Information
All I did was update from Botania-1.16.2-406 to Botania-1.16.2-407 and the corporea keybinding is missing. If you click default key of "C" it actaully crashes the game.

What I expected to happen:

No crash. Also keybinding to exist.

What happened instead:

[crash-2020-10-15_08.52.08-client.txt](https://github.com/Vazkii/Botania/files/5385394/crash-2020-10-15_08.52.08-client.txt)

**Comment by Hubry** [comment]
Post a full game log please.

**Comment by P3rf3ctXZer0** [comment]
Too late also it's pretty self-explanatory. I made the post in a hurry.

**Comment by P3rf3ctXZer0** [comment]
You can use my modpack though and it should have the same affect. 
[Project Evolution Main Course-8.1.0.zip](https://github.com/Vazkii/Botania/files/5388540/Project.Evolution.Main.Course-8.1.0.zip)

Just unlock profile and update botania.

**Comment by P3rf3ctXZer0** [comment]
@Hubry 
[latest.log](https://github.com/Vazkii/Botania/files/5398358/latest.log)

**Comment by P3rf3ctXZer0** [comment]
![sFxWG3S 1](https://user-images.githubusercontent.com/10351221/96388686-13bb8d80-1170-11eb-8ba6-513a9c22e11e.png)
Keybinding is still missing and crash still occurs.

**Comment by P3rf3ctXZer0** [comment]
trying to regen configs and options.txt to no avail.

**Comment by raziel23x** [comment]
Botania-1.16.3-409 fixes the issue but they have not released the update yet for some odd reason as i tested the snapshot

**Comment by P3rf3ctXZer0** [comment]
Sounds good because of how much Patchuli and Botania are being problematic I will probably wait a hand full of version before updating or using the mods - good luck though. I do love the mod just don't have time to crash hunt.
