### ISSUE TITLE
[CRASH] Game Crashes When Delete Inventory Button is Pressed

### ISSUE THREAD

**Issue by ultranine** [Vazkii/Botania#3484]
# Version Information
Forge version:  34.1.19
Botania version:  1.16.3-407

# Further Information
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)\
https://gist.github.com/ultranine/084ee192b21b2bf4350c87ade1895e16
Steps to reproduce:
1. Open a Creative World
2. Select Survival Inventory
3. Shift-Click the delete button.

What I expected to happen:
The game would clear my creative inventory as usual.

What happened instead:
Game Crash

EDIT: Closing out of the creative menu also triggers the crash.

**Comment by Hubry** [comment]
Full game log? Do you have Optifine?

**Comment by ultranine** [comment]
0. The bug does not occur when Botania is launched with no other mods, so I think its an incompatability with another mod in the above log. A lot of the mods listed above have sub-10K downloads, and downgrading the version fixes the issue, so unless similar reports start flooding in, I wouldn't worry about it too much.

**Comment by Hubry** [comment]
Weird that a downgrade fixes it, because things relating to this keybind weren't changed for a good while now.

**Comment by Hubry** [comment]
Hmm, actually, I just noticed something weird. There *were* some changes I haven't seen.
