### ISSUE TITLE
The endoflame will not burn bamboo 1.16.3

### ISSUE THREAD

**Issue by magicspell17** [Vazkii/Botania#3502]
# Version Information
Forge version:  34.1.25
Botania version:  1.16.3-403

# Further Information
Steps to reproduce:
1. drop bamboo one block away from endoflame
2. wait 30 secs
3. still nothing happens

What I expected to happen:
mana produced from endoflame buring the bamboo.
What happened instead:
no burning of the bamboo and no mana produced.

**Comment by Hubry** [comment]
Can you use bamboo as furnace fuel? What pack are you playing?

**Comment by magicspell17** [comment]
I am using vanilla bamboo so I can use it as a furnace fuel. I am playing a custom pack with botania and immersive engineering. That’s it
