### ISSUE TITLE
[1.16.3]Crash at startup

### ISSUE THREAD

**Issue by ScottCTD** [Vazkii/Botania#3503]
# Version Information
Forge version:  34.1.35
Botania version:  Botania-1.16.3-409.jar

# Further Information
Link to crash log: [Crash Report](https://paste.ubuntu.com/p/VtRy5sBMnh/)
Steps to reproduce:
1. At startup

What I expected to happen:
Join the game

What happened instead:
Crash

**Comment by beanaboston** [comment]
Also having this issue with forge 34.1.32 and same version of botania. ~~Maybe an issue with optifine?~~ Nevermind, the original poster doesn't have optifine.

**Comment by williewillus** [comment]
can you try with just botania and add mods back in until you find one that breaks it

**Comment by ScottCTD** [comment]
I test all my mods except Immersive Engineering (because it does not support forge higher than 25) with forge 34.1.42 and it successfully started!
![image](https://user-images.githubusercontent.com/35100768/97959696-de0ed980-1dea-11eb-8865-2c68e6aa72da.png)

**Comment by ar7max** [comment]
Forge 34.1.32
MC 1.16.3
`---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 11/4/20 12:11 AM
Description: Rendering overlay

java.lang.IllegalStateException: Failed to load description for particle botania:wisp
	at net.minecraft.client.particle.ParticleManager.func_215236_a(ParticleManager.java:226) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.particle.ParticleManager.lambda$null$0(ParticleManager.java:169) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.particle.ParticleManager$$Lambda$9441/1873973835.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:1.8.0_45] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:1.8.0_45] {}
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:1.8.0_45] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) ~[?:1.8.0_45] {}
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:1.8.0_45] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:1.8.0_45] {}
Caused by: java.io.FileNotFoundException: botania:particles/wisp.json
	at net.minecraft.resources.SimpleReloadableResourceManager.func_199002_a(SimpleReloadableResourceManager.java:63) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs.mixins.json:SimpleReloadableResourceManagerMixin,pl:mixin:A}
	at net.minecraft.client.particle.ParticleManager.func_215236_a(ParticleManager.java:205) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	... 8 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:483) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
-- Overlay render details --
Details:
	Overlay name: net.minecraft.client.gui.ResourceLoadProgressGui
Stacktrace:
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:483) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:953) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:mixin:APP:kubejs.mixins.json:MinecraftMixin,pl:mixin:APP:valhelsia_tweaks.mixins.json:DisplayGuiScreenMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:584) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:mixin:APP:kubejs.mixins.json:MinecraftMixin,pl:mixin:APP:valhelsia_tweaks.mixins.json:DisplayGuiScreenMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.3-34.1.32.jar:34.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$481/842924653.call(Unknown Source) [forge-1.16.3-34.1.32.jar:34.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.5.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.5.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.5.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-8.0.5.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-8.0.5.jar:?] {re:classloading}


-- System Details --
Details:
	Minecraft Version: 1.16.3
	Minecraft Version ID: 1.16.3
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_45, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 6028688944 bytes (5749 MB) / 7314866176 bytes (6976 MB) up to 7314866176 bytes (6976 MB)
	CPUs: 12
	JVM Flags: 10 total; -Xmn128M -Xmx6949M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.5+84+master.3310fe0
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-3.0.3-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.3-34.1.32.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.3-34.1.32.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.3-34.1.32.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.3-34.1.32.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.3-34.1.32.jar fml TRANSFORMATIONSERVICE 
	FML: 34.1
	Forge: net.minecraftforge:34.1.32
	FML Language Providers: 
		javafml@34.1
		minecraft@1
	Mod List: 
		enchantedbookredesign-3.1a.jar                    |Enchanted Book Redesign       |enchantedbookredesign         |3.1a                |COMMON_SET|NOSIGNATURE
		aiotbotania-1.16.2-1.3.2.jar                      |AIOT Botania                  |aiotbotania                   |1.3.2               |COMMON_SET|NOSIGNATURE
		curiousshulkerboxes-forge-1.16.3-4.0.0.1.jar      |Curious Shulker Boxes         |curiousshulkerboxes           |1.16.3-4.0.0.1      |COMMON_SET|NOSIGNATURE
		mcw-windows-1.0.2-mc1.16.3.jar                    |Macaw's Windows               |mcwwindows                    |1.0.2               |COMMON_SET|NOSIGNATURE
		pitg-1.16.3-1.4.1.jar                             |Pane In The Glass             |pitg                          |1.16.3-1.4.1        |COMMON_SET|NOSIGNATURE
		Neat 1.7-24.jar                                   |Neat                          |neat                          |1.7-24              |COMMON_SET|NOSIGNATURE
		BetterTitleScreen-1.16.2-1.10.1.jar               |Better Title Screen           |bettertitlescreen             |1.16.2-1.10.1       |COMMON_SET|NOSIGNATURE
		XaerosWorldMap_1.11.0_Forge_1.16.3.jar            |Xaero's World Map             |xaeroworldmap                 |1.11.0              |COMMON_SET|NOSIGNATURE
		CookingForBlockheads_1.16.3-9.2.1.jar             |Cooking for Blockheads        |cookingforblockheads          |9.2.1               |COMMON_SET|NOSIGNATURE
		Controlling-7.0.0.8.jar                           |Controlling                   |controlling                   |7.0.0.8             |COMMON_SET|NOSIGNATURE
		ReAuth-1.16-Forge-3.9.2.jar                       |ReAuth                        |reauth                        |3.9.2               |COMMON_SET|3d:06:1e:e5:da:e2:ff:ae:04:00:be:45:5b:ff:fd:70:65:00:67:0b:33:87:a6:5f:af:20:3c:b6:a1:35:ca:7e
		Placebo-1.16.3-4.3.3.jar                          |Placebo                       |placebo                       |4.3.3               |COMMON_SET|NOSIGNATURE
		Powah-1.16.3-2.3.4.jar                            |Powah                         |powah                         |2.3.4               |COMMON_SET|NOSIGNATURE
		mightyarchitect-mc1.16.3_v0.5.jar                 |The Mighty Architect          |mightyarchitect               |0.5                 |COMMON_SET|NOSIGNATURE
		Bookshelf-1.16.3-8.7.20.jar                       |Bookshelf                     |bookshelf                     |8.7.20              |COMMON_SET|NOSIGNATURE
		randompatches-1.16.2-1.22.1.2.jar                 |RandomPatches                 |randompatches                 |1.16.2-1.22.1.2     |COMMON_SET|92:f6:29:d4:09:89:f5:f5:98:5e:20:34:31:d0:7b:58:22:06:bd:a5:d1:6a:92:6e:ac:3d:8d:18:c5:b2:5b:d7
		mcw-doors-1.0.1fix-mc1.16.3-1.16.2.jar            |Macaw's Doors                 |mcwdoors                      |1.0.1               |COMMON_SET|NOSIGNATURE
		MekanismGenerators-1.16.3-10.0.15.441.jar         |Mekanism: Generators          |mekanismgenerators            |10.0.15             |COMMON_SET|NOSIGNATURE
		Hwyla-forge-1.10.11-B78_1.16.2.jar                |Waila                         |waila                         |1.10.11-B78_1.16.2  |COMMON_SET|NOSIGNATURE
		SnowRealMagic-1.16.3-2.2.1.jar                    |Snow! Real Magic!             |snowrealmagic                 |2.2.1               |COMMON_SET|NOSIGNATURE
		JustEnoughResources-1.16.3-0.12.0.102.jar         |Just Enough Resources         |jeresources                   |0.12.0.102          |COMMON_SET|NOSIGNATURE
		absentbydesign-1.16.3-1.1.1.jar                   |Absent By Design Mod          |absentbydesign                |1.16.3-1.1.1        |COMMON_SET|1f:47:ac:b1:61:82:96:b8:47:19:16:d2:61:81:11:60:3a:06:4b:61:31:56:7d:44:31:1e:0c:6f:22:5b:4c:ed
		refinedstorage-1.9.8.jar                          |Refined Storage               |refinedstorage                |1.9.8               |COMMON_SET|NOSIGNATURE
		PackMenu-1.16.3-2.3.0.jar                         |Pack Menu                     |packmenu                      |2.3.0               |COMMON_SET|NOSIGNATURE
		mcw-bridges-1.0.4-mc1.16.3.jar                    |Macaw's Bridges               |mcwbridges                    |1.0.4               |COMMON_SET|NOSIGNATURE
		industrial-foregoing-1.16.3-3.1.1-a834e76.jar     |Industrial Foregoing          |industrialforegoing           |3.1.1               |COMMON_SET|NOSIGNATURE
		FarmersDelight-1.16.3-0.2.3.jar                   |Farmer's Delight              |farmersdelight                |1.16.3-0.2.3        |COMMON_SET|NOSIGNATURE
		AmbientSounds_v3.0.21_mc1.16.2.jar                |Ambient Sounds                |ambientsounds                 |3.0.3               |COMMON_SET|NOSIGNATURE
		BiomesOPlenty-1.16.3-12.0.0.409-universal.jar     |Biomes O' Plenty              |biomesoplenty                 |1.16.3-12.0.0.409   |VALIDATE  |NOSIGNATURE
		MekanismAdditions-1.16.3-10.0.15.441.jar          |Mekanism: Additions           |mekanismadditions             |10.0.15             |COMMON_SET|NOSIGNATURE
		valhelsia_structures-16.0.5.jar                   |Valhelsia Structures          |valhelsia_structures          |16.0.5              |COMMON_SET|NOSIGNATURE
		Lollipop-1.16.3-3.2.2.jar                         |Lollipop                      |lollipop                      |3.2.2               |COMMON_SET|NOSIGNATURE
		mcw-trapdors-1.0.0-mc1.16.3.jar                   |Macaw's Trapdoors             |mcwtrpdoors                   |1.0.0               |COMMON_SET|NOSIGNATURE
		fishingreal-1.16.3-1.0.0.jar                      |Fishing Real                  |fishingreal                   |1.0.0               |COMMON_SET|NOSIGNATURE
		curios-forge-1.16.3-4.0.2.0.jar                   |Curios API                    |curios                        |1.16.3-4.0.2.0      |COMMON_SET|NOSIGNATURE
		tetra-1.16.3-3.3.0.jar                            |Tetra                         |tetra                         |3.3.0               |COMMON_SET|NOSIGNATURE
		Botania-1.16.3-409.jar                            |Botania                       |botania                       |1.16.3-409          |COMMON_SET|NOSIGNATURE
		Patchouli-1.16.2-47.jar                           |Patchouli                     |patchouli                     |1.16.2-47           |COMMON_SET|NOSIGNATURE
		leap-1.16.3-1.0.1.jar                             |Leap                          |leap                          |1.0.1               |COMMON_SET|NOSIGNATURE
		betterweather-1.0.3.jar                           |Better Weather                |betterweather                 |1.0.1               |COMMON_SET|NOSIGNATURE
		extlights-3.0.jar                                 |Extended Lights               |extlights                     |3.0                 |COMMON_SET|NOSIGNATURE
		elevatorid-1.16.3-1.7.6.jar                       |Elevator Mod                  |elevatorid                    |1.16.3-1.7.6        |COMMON_SET|NOSIGNATURE
		neoncraft-2.0.jar                                 |Neon Craft                    |neoncraft                     |2.0                 |COMMON_SET|NOSIGNATURE
		Runelic-1.16.3-5.0.1.jar                          |Runelic                       |runelic                       |5.0.1               |COMMON_SET|NOSIGNATURE
		DarkUtilities-1.16.3-6.0.3.jar                    |Dark Utilities                |darkutils                     |6.0.3               |COMMON_SET|NOSIGNATURE
		MekanismTools-1.16.3-10.0.15.441.jar              |Mekanism: Tools               |mekanismtools                 |10.0.15             |COMMON_SET|NOSIGNATURE
		mcws-roofs-1.16.3-v2.0.0.jar                      |Macaw's Roofs                 |mcwroofs                      |2.0.0               |COMMON_SET|NOSIGNATURE
		curiouselytra-forge-1.16.3-4.0.0.1.jar            |Curious Elytra                |curiouselytra                 |1.16.3-4.0.0.1      |COMMON_SET|NOSIGNATURE
		cc-tweaked-1.16.3-1.93.1.jar                      |CC: Tweaked                   |computercraft                 |1.93.1              |COMMON_SET|NOSIGNATURE
		AI-Improvements-1.16.2-0.3.0.jar                  |AI-Improvements               |aiimprovements                |0.3.0               |COMMON_SET|NOSIGNATURE
		cherishedworlds-forge-1.16.3-5.0.0.1.jar          |Cherished Worlds              |cherishedworlds               |1.16.3-5.0.0.1      |COMMON_SET|NOSIGNATURE
		cloth-config-forge-4.1.0.jar                      |Cloth Config v4 API           |cloth-config                  |4.0                 |COMMON_SET|NOSIGNATURE
		BetterBurning-1.16.3-4.0.2.jar                    |BetterBurning                 |betterburning                 |4.0.2               |COMMON_SET|NOSIGNATURE
		FastLeafDecay-v25.jar                             |FastLeafDecay                 |fastleafdecay                 |v25                 |COMMON_SET|NOSIGNATURE
		ServerTabInfo-1.16.3-1.3.3.jar                    |Server Tab Info               |servertabinfo                 |1.3.3               |COMMON_SET|NOSIGNATURE
		BetterMineshaftsForge-1.16.2-1.0.1.jar            |YUNG's Better Mineshafts      |bettermineshafts              |1.16.2-1.0.1        |COMMON_SET|NOSIGNATURE
		SimpleDiscordRichPresence-1.16.2-1.3.4.jar        |Simple Discord Rich Presence  |sdrp                          |1.16.2-1.3.4        |COMMON_SET|NOSIGNATURE
		BetterAdvancements-1.16.3-0.1.0.102.jar           |Better Advancements           |betteradvancements            |0.1.0.102           |COMMON_SET|NOSIGNATURE
		QuarkOddities-1.16.3.jar                          |Quark Oddities                |quarkoddities                 |1.16.3              |COMMON_SET|NOSIGNATURE
		Kiwi-1.16.3-3.4.0.jar                             |Kiwi                          |kiwi                          |3.4.0               |COMMON_SET|NOSIGNATURE
		inventorysorter-1.16.1-18.1.0.jar                 |Simple Inventory Sorter       |inventorysorter               |18.1.0              |COMMON_SET|NOSIGNATURE
		ClientTweaks_1.16.3-5.2.0.jar                     |Client Tweaks                 |clienttweaks                  |5.2.0               |COMMON_SET|NOSIGNATURE
		BedBenefits-1.16.3-3.0.1.jar                      |BedBenefits                   |bedbenefits                   |3.0.1               |COMMON_SET|NOSIGNATURE
		TrashSlot_1.16.3-12.2.0.jar                       |TrashSlot                     |trashslot                     |12.2.0              |COMMON_SET|NOSIGNATURE
		torchslabmod-1.16.3_v1.6.18.jar                   |Torch Slab Mod                |torchslabmod                  |1.6.18              |COMMON_SET|NOSIGNATURE
		mining-helmet-1.16.3-1.1.1.jar                    |Mining Helmet                 |mining_helmet                 |1.1.1               |COMMON_SET|NOSIGNATURE
		spiders-2.0-1.16.3-1.0.3.jar                      |Spiders 2.0                   |spiderstpo                    |1.0.3               |COMMON_SET|NOSIGNATURE
		jei-1.16.3-7.6.0.49.jar                           |Just Enough Items             |jei                           |7.5.0.43            |COMMON_SET|NOSIGNATURE
		kubejs-1603.2.8.73.jar                            |KubeJS                        |kubejs                        |1603.2.8.73         |COMMON_SET|NOSIGNATURE
		goblintraders-1.2.2-1.16.3.jar                    |Goblin Traders                |goblintraders                 |1.2.2               |COMMON_SET|NOSIGNATURE
		Mekanism-1.16.3-10.0.15.441.jar                   |Mekanism                      |mekanism                      |10.0.15             |COMMON_SET|NOSIGNATURE
		caelus-forge-1.16.3-2.0.0.3.jar                   |Caelus API                    |caelus                        |1.16.3-2.0.0.3      |COMMON_SET|NOSIGNATURE
		Waystones_1.16.3-7.3.0.jar                        |Waystones                     |waystones                     |7.3.0               |COMMON_SET|NOSIGNATURE
		Clumps-6.0.0.11.jar                               |Clumps                        |clumps                        |6.0.0.11            |COMMON_SET|NOSIGNATURE
		mgui-1.16.3-3.1.2.jar                             |mgui                          |mgui                          |3.1.2               |COMMON_SET|NOSIGNATURE
		light-overlay-5.5.4.jar                           |Light Overlay Forge           |lightoverlay-forge            |NONE                |COMMON_SET|NOSIGNATURE
		comforts-forge-1.16.3-4.0.0.1.jar                 |Comforts                      |comforts                      |1.16.3-4.0.0.1      |COMMON_SET|NOSIGNATURE
		NaturesCompass-1.16.3-1.8.5.jar                   |Nature's Compass              |naturescompass                |1.16.3-1.8.5        |COMMON_SET|NOSIGNATURE
		netheritehorsearmor-1.4.jar                       |Netherite Horse Armor Mod     |netheritehorsearmor           |1.4                 |COMMON_SET|NOSIGNATURE
		decorative_blocks-1.16.2-1.1.jar                  |Decorative Blocks             |decorative_blocks             |1.5                 |COMMON_SET|NOSIGNATURE
		curioofundying-forge-1.16.3-5.0.0.1.jar           |Curio of Undying              |curioofundying                |1.16.3-5.0.0.1      |COMMON_SET|NOSIGNATURE
		snowundertrees-1.16.3-v1.1.2.jar                  |Snow Under Trees              |snowundertrees                |v1.1.2              |COMMON_SET|NOSIGNATURE
		bedspreads-forge-1.16.3-5.0.0.1.jar               |Bedspreads                    |bedspreads                    |1.16.3-5.0.0.1      |COMMON_SET|NOSIGNATURE
		Toast-Control-1.16.3-4.3.0.jar                    |Toast Control                 |toastcontrol                  |4.3.0               |COMMON_SET|NOSIGNATURE
		iChunUtil-1.16.3-10.0.0.jar                       |iChunUtil                     |ichunutil                     |10.0.0              |COMMON_SET|NOSIGNATURE
		forge-1.16.3-34.1.32-universal.jar                |Forge                         |forge                         |34.1.32             |COMMON_SET|22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		Waddles-1.16.3-0.8.9.jar                          |Waddles                       |waddles                       |1.16.3-0.8.9        |COMMON_SET|NOSIGNATURE
		WailaHarvestability-mc1.16.2-forge-1.1.13.jar     |Waila Harvestability          |wailaharvestability           |1.1.13              |COMMON_SET|NOSIGNATURE
		scuba-gear-1.16.3-1.0.1.jar                       |Scuba Gear                    |scuba_gear                    |1.0.1               |COMMON_SET|NOSIGNATURE
		tl_skin_cape_forge_1.16.3-1.13.jar                |TLSkinCape                    |tlskincape                    |1.6                 |COMMON_SET|19:f5:ce:44:81:0c:e4:22:05:5e:73:c5:a8:cd:de:f3:c8:cf:a9:b3:01:70:40:a0:ee:2d:50:7a:1c:3d:1c:8a
		dash-1.16.3-1.0.1.jar                             |Dash                          |dash                          |1.0.1               |COMMON_SET|NOSIGNATURE
		ironchest-1.16.3-11.2.6.jar                       |Iron Chests                   |ironchest                     |1.16.3-11.2.6       |COMMON_SET|NOSIGNATURE
		CraftingTweaks_1.16.3-12.2.0.jar                  |Crafting Tweaks               |craftingtweaks                |12.2.0              |COMMON_SET|NOSIGNATURE
		forge-1.16.3-34.1.32-client.jar                   |Minecraft                     |minecraft                     |1.16.3              |COMMON_SET|NOSIGNATURE
		swingthroughgrass-1.16.3-1.5.2.jar                |SwingThroughGrass             |swingthroughgrass             |1.16.3-1.5.2        |COMMON_SET|NOSIGNATURE
		MouseTweaks-2.13-mc1.16.2.jar                     |Mouse Tweaks                  |mousetweaks                   |2.13                |COMMON_SET|NOSIGNATURE
		titanium-1.16.3-3.1.0.jar                         |Titanium                      |titanium                      |3.1.0               |COMMON_SET|NOSIGNATURE
		Psi 1.16-87.jar                                   |Psi                           |psi                           |1.16-87             |COMMON_SET|NOSIGNATURE
		ImmersiveEngineering-1.16.3-4.1.0-124.jar         |Immersive Engineering         |immersiveengineering          |1.16.3-4.1.0-124    |VALIDATE  |44:39:94:cf:1d:8c:be:3c:7f:a9:ee:f4:1e:63:a5:ac:61:f9:c2:87:d5:5b:d9:d6:8c:b5:3e:96:5d:8e:3f:b7
		forbidden_arcanus-1.16.3-1.0.2.jar                |Forbidden & Arcanus           |forbidden_arcanus             |1.16.3-1.0.2        |COMMON_SET|NOSIGNATURE
		jeiintegration_1.16.3-6.0.0.8.jar                 |JEI Integration               |jeiintegration                |6.0.0.8             |COMMON_SET|NOSIGNATURE
		Xaeros_Minimap_20.26.0_Forge_1.16.3.jar           |Xaero's Minimap               |xaerominimap                  |20.26.0             |COMMON_SET|NOSIGNATURE
		ftb-backups-2.1.1.6.jar                           |FTB Backups                   |ftbbackups                    |2.1.1.6             |COMMON_SET|NOSIGNATURE
		serverconfigupdater-1.3.jar                       |ServerConfig Updater          |serverconfigupdater           |1.3                 |COMMON_SET|NOSIGNATURE
		FastWorkbench-1.16.3-4.4.0.jar                    |FastWorkbench                 |fastbench                     |4.4.0               |COMMON_SET|NOSIGNATURE
		polymorph-forge-1.16.3-0.15.jar                   |Polymorph                     |polymorph                     |1.16.3-0.15         |COMMON_SET|NOSIGNATURE
		AutoRegLib-1.6-46.jar                             |AutoRegLib                    |autoreglib                    |1.6-46              |COMMON_SET|NOSIGNATURE
		Quark-r2.4-272.jar                                |Quark                         |quark                         |r2.4-272            |COMMON_SET|NOSIGNATURE
		Apotheosis-1.16.3-4.4.1.jar                       |Apotheosis                    |apotheosis                    |4.4.1               |COMMON_SET|NOSIGNATURE
		StorageDrawers-1.16.3-8.2.1.jar                   |Storage Drawers               |storagedrawers                |8.2.1               |COMMON_SET|NOSIGNATURE
		DoubleSlabs-1.16-3.4.10.jar                       |Double Slabs                  |doubleslabs                   |3.4.10              |COMMON_SET|NOSIGNATURE
		InventoryHud_1.16.x.forge-3.1.3.jar               |Inventory HUD+(Forge edition) |inventoryhud                  |3.1.3               |COMMON_SET|NOSIGNATURE
		structurize-0.13.92-ALPHA-universal.jar           |Structurize                   |structurize                   |0.13.92-ALPHA       |COMMON_SET|NOSIGNATURE
		minecolonies-0.13.386-ALPHA-universal.jar         |Minecolonies                  |minecolonies                  |0.13.386-ALPHA      |COMMON_SET|NOSIGNATURE
		FastFurnace-1.16.3-4.3.0.jar                      |FastFurnace                   |fastfurnace                   |4.3.0               |COMMON_SET|NOSIGNATURE
		AppleSkin-mc1.16.2-forge-1.0.14.jar               |AppleSkin                     |appleskin                     |1.0.14              |COMMON_SET|NOSIGNATURE
		engineersdecor-1.16.3-1.1.3-b2.jar                |Engineer's Decor              |engineersdecor                |1.1.3-b2            |COMMON_SET|NOSIGNATURE
		BackTools-1.16.3-10.0.0.jar                       |Back Tools                    |backtools                     |10.0.0              |COMMON_SET|NOSIGNATURE
		Aquaculture-1.16.3-2.1.4.jar                      |Aquaculture 2                 |aquaculture                   |1.16.3-2.1.4        |COMMON_SET|NOSIGNATURE
		FriendlyFire-1.16.3-5.0.3.jar                     |FriendlyFire                  |friendlyfire                  |5.0.3               |COMMON_SET|NOSIGNATURE
		valhelsia_tweaks-16.0.1.jar                       |Valhelsia Tweaks              |valhelsia_tweaks              |16.0.1              |COMMON_SET|NOSIGNATURE
		refinedstorageaddons-0.7.2.jar                    |Refined Storage Addons        |refinedstorageaddons          |0.7.2               |COMMON_SET|NOSIGNATURE
		CosmeticArmorReworked-1.16.3-v1.jar               |CosmeticArmorReworked         |cosmeticarmorreworked         |1.16.3-v1           |COMMON_SET|5e:ed:25:99:e4:44:14:c0:dd:89:c1:a9:4c:10:b5:0d:e4:b1:52:50:45:82:13:d8:d0:32:89:67:56:57:01:53
		overloadedarmorbar-5.1.0.jar                      |Overloaded Armor Bar          |overloadedarmorbar            |5.1.0               |COMMON_SET|NOSIGNATURE
		step-1.16.3-1.0.3.jar                             |Step                          |step                          |1.0.3               |COMMON_SET|NOSIGNATURE
		OpenLoader-1.16.3-7.0.3.jar                       |OpenLoader                    |openloader                    |7.0.3               |COMMON_SET|NOSIGNATURE
		DefaultOptions_1.16.3-12.2.0.jar                  |Default Options               |defaultoptions                |12.2.0              |COMMON_SET|NOSIGNATURE
	Crash Report UUID: 87a1ee97-d721-44fd-8268-d7f538b13feb
	Kiwi Modules: 
		kiwi:contributors
		kiwi:data
		snowrealmagic:core
		snowrealmagic:world
	Launched Version: Forge 1.16.3
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce RTX 2060 SUPER/PCIe/SSE2 GL version 4.6.0 NVIDIA 446.14, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: 
	Current Language: English (US)
	CPU: 12x AMD Ryzen 5 3600 6-Core Processor `

**Comment by ScottCTD** [comment]
> Forge 34.1.32
> MC 1.16.3
> 
> log

If you use the latest version of forge, it should be ok because I successfully started using 34.1.42. (Of course without IE)
