### ISSUE TITLE
[1.16.4] Class vazkii.botania.common.MixinConnector not found

### ISSUE THREAD

**Issue by AuretyubeGit** [Vazkii/Botania#3510]
# Version Information
Forge version:  1.16.4-35.0.7
Botania version:  1.16.3-409

# Log Latest
[latest.log](https://github.com/Vazkii/Botania/files/5513838/latest.log)

# Log Debug
[debug.log](https://github.com/Vazkii/Botania/files/5513837/debug.log)

**Comment by Hubry** [comment]
Does this happen if you remove Optifine?

**Comment by Hubry** [comment]
Well, after seeing a similar issue on Discord... you seem to be lacking Curios. Download that.
