### ISSUE TITLE
Cant seem to get GOG world on 1.16.3 server

### ISSUE THREAD

**Issue by MrsRatbag** [Vazkii/Botania#3511]
I've used GOG in previous versions with no issues at all but I cant seem to get a GOG world on my 1.16.3 dedicated server. It always comes up as a standard minecraft world, even when only using garden of glass and the other necessary mods needed for gog to work. Using latest versions of necessary mods, I have leveltype=botania-skyblock in server properties and yes have deleted the world since changing the server properties to that. What am I missing? Thanks in advance for your help.

**Comment by williewillus** [comment]
there's an issue with custom world types on servers right now where server.properties is loaded too early, before custom leveltypes are available.  

the workaround is to generate a world in single player then transfer it to the server

**Comment by MrsRatbag** [comment]
> there's an issue with custom world types on servers right now where server.properties is loaded too early, before custom leveltypes are available.
> 
> the workaround is to generate a world in single player then transfer it to the server

Oh alright thank you.

**Comment by MrsRatbag** [comment]
Ok, I've copied over a single player gog world to the server. the new problem I'm having is that the gog commands for multiplayer (getting a new player an island and whatnot)  are giving me errors saying "this command cannot be used in a non-skyblock world" since the server apparently still thinks im in a default world.

**Comment by williewillus** [comment]
Transfer the entire world folder, don't leave anything behind
And make sure gog is installed server side

**Comment by MrsRatbag** [comment]
It is installed serverside and I did copy the entire file

**Comment by Hubry** [comment]
d04eb2362bec6f1849660496884f9ef4fd7ced22
