### ISSUE TITLE
What exactly is Botania?

### ISSUE THREAD

**Issue by Ameno-Sagiri** [Vazkii/Botania#3514]
I was curious as to exactly what Botania is. At the time of writing this all of your resources are offline. 

http://botaniamod.net/ is completely down.
The wiki located at https://vazkii.net/mod/Botania/ no longer exists and redirects to botaniamod.net, which is not even online.
The github has a wiki, but it doesn't actually have anything on it.

Sure, I could watch a Youtube video about it, but I figured I would let you know.

**Comment by Alwinfy** [comment]
![image](https://user-images.githubusercontent.com/20421383/98704722-9932f780-2342-11eb-907a-7d3f20ea48a8.png)

**Comment by Ameno-Sagiri** [comment]
It's up now. It wasn't when I posted the thread. Thanks.
