### ISSUE TITLE
[1.16.4] ClassNotFoundException: vazkii.botania.common.MixinConnector

### ISSUE THREAD

**Issue by shortybsd** [Vazkii/Botania#3516]
# Version Information
Forge version:  35.0.15
Botania version:  1.16.3-409
curios-forge version: 1.16.4-4.0.2.1

# Further Information
Link to crash log: [Pastebin](https://pastebin.com/MkYvSKza)
Steps to reproduce:
1. Add Botania and Curios Forge in MultiMC for 1.16.4
2. Launch modpack
3. BOOM... crash

What I expected to happen:
For modpack to launch with only Botania :)
What happened instead:
Crash, see above pastebin link.

**Comment by Haerar** [comment]
@shortybsd hey, can I confirm how you resolved this? Same issue!

**Comment by Haerar** [comment]
Just an update, had to update my version of minecraft to resolve this; make sure you're running forge-35.1.7 (latest)
