### ISSUE TITLE
Pixie Spawn Chance Crash

### ISSUE THREAD

**Issue by Phazanor** [Vazkii/Botania#3517]
# Version Information
Forge version:  1.16.4-35.0.17
Botania version:  1.16.3-409

# Further Information
http://pastebin.fr/73243 (sorry if the link isn't formatted correctly, it's the first time I do this).
1. Get hit by a skeleton arrow (or take any damage by a mob)
2. Game crashes (tested it on server and in single player)

What I expected to happen:  
Lose HP after taking damage.

What happened instead:
Game crashed.

**Comment by yzl210** [comment]
#3382

**Comment by williewillus** [comment]
Can you try with just botania then add mods until it doesn't work.

**Comment by superninjakiwi** [comment]
Same issue as this (and #3518 I suspect), it is caused by Xaero's World Map, somehow. That was extremely annoying to narrow down, which is why I suspect that the others who got this bug just sat around and waited for someone else to find the fix first (thanks, guys).

**Comment by superninjakiwi** [comment]
Something else that might be relevant is that it's a bit inconsistent. At least one configuration of my mods would crash if I took damage, and work fine if I removed Xaero's worldmap, something I tried at least a few times just to make sure. However, I can't recreate that with only xaero's worldmap and botania. Immersive portals is a mod shared by both me and the other ones reporting the crash, so I'd focus on that one more.

**Comment by DylanJones** [comment]
I can confirm that after adding Immersive Portals to our pack, we started getting this exact crash.

**Comment by DylanJones** [comment]
Turns out this is actually a problem with the Immersive Portals mod, not Botania.  I've made [a PR](https://github.com/qouteall/ImmersivePortalsModForForge/pull/182) to the original mod that fixes the issue.  If you just want a working build, I've also uploaded the fixed jar as a release [here](https://github.com/DylanJones/ImmersivePortalsModForForge/releases/tag/v0.9-1.16-temp).

**Comment by williewillus** [comment]
As noted above, the solution is to update Immersive Portals to 0.10 or above

**Comment by Neubulae** [comment]
This is happening on Fabric as well :concern:
