### ISSUE TITLE
Pillager Arrow crasht the server world

### ISSUE THREAD

**Issue by SinobinU** [Vazkii/Botania#3518]
Serverworld crasht with Arrow Damage from Pillager.

Forge version:  forge-1.16.4-35.0.18
Botania version:  Botania-1.16.3-409

java.lang.IllegalArgumentException: Can't find attribute botania:pixie_spawn_chance
at vazkii.botania.common.core.handler.PixieHandler.onDamageTaken(PixieHandler.java:73) ~[botania:1.16.3-409] {re:mixin,re:classloading}

**Comment by BenDawgAK** [comment]
looks like its an issue with elementium gear rather than pillagers based on the error log.

**Comment by BenDawgAK** [comment]
Were you using elementium a the time of the crash?

**Comment by Hubry** [comment]
Firstly, please attach a crash report (or even a console log) using https://gist.github.com/.
Secondly, what modpack did you use?

**Comment by grydian** [comment]
I created my own custom pack and got this crash.  Here is a link to a pastebin.  https://pastebin.com/ebbbCCmS  I was hit by an arrow from a Pillager.  I suspect a mod has a old version of mixin and I have no idea what mod that would be.  Any ideas?

**Comment by grydian** [comment]
Quick update I seem to get this crash when I take damage from a mob.

**Comment by marcebdev** [comment]
Was able to reproduce this, I crash right when I'm about to take damage from any mob.

```
Forge 35.1.7
Botania 1.16.3-409
```

https://pastebin.com/exrZtCKs

**Comment by williewillus** [comment]
please try without any other mods besides botania and add them back until it doesn't work. This is a compatibility thing.

**Comment by Badtz13** [comment]
I have the same crash, serverside, with the same forge version and botania version. The only difference is that my crash happens with a shulker bullet. [Here](https://pastebin.com/14RLsAxz) is the full modlist if that helps at all.

**Comment by grydian** [comment]
Ok so I updated mahoutsukai and it seems to have fixed my crash.  I did update a few mods but this one stands out as the likely culprit.  But for me now botania works fine and I have no crashes when I take damage.  If that isn't the mod and you guys are still crashing I will give you a list of the mods I updated.  mahoutsukai is also a mod in the list badtz13 gave us.  So I really think its likely that mod.  Good luck guys.

**Comment by Badtz13** [comment]
@grydian I completely removed MahouTsukai and I still get the same crash. 

@williewillus When testing with only botania, the crash does *not* occur. However, this does seem to be a botania compatibility issue, as the crash log below indicates. 

[Full crash log](https://pastebin.com/r0etzm4Q)

If anyone is interested in steps to reproduce:

- make a new minecraft world in creative 

- summon a shulker

- change gamemode to survival mode

- the shulker will shoot you and you will crash

**Comment by williewillus** [comment]
This is probably #3517
