### ISSUE TITLE
Mana burst from mana blaster is off center.

### ISSUE THREAD

**Issue by MrSerpophaga** [Vazkii/Botania#3519]
# Version Information
Forge version:  14.23.5.2854
Botania version:  r1.10-363

# Further Information
Steps to reproduce:
1. Grab Mana Blaster
2. Fire at a specific point in the world.

What I expected to happen:
The mana burst should have been centered on the crosshair
What happened instead:
The mana burst was slightly to the right and down.

**Comment by MrSerpophaga** [comment]
Ok, i didn't see on the submitting guidelines that older versions are not supported. I'll close the thread.

**Comment by williewillus** [comment]
>  The mana burst was slightly to the right and down.

it depends on which hand you're holding the blaster in. Vanilla bows used to do this as well before it changed to be centered in 1.9

**Comment by MrSerpophaga** [comment]
Ah, then it's intentional. My bad then.
