### ISSUE TITLE
Thorn chakram disappearing

### ISSUE THREAD

**Issue by TommyDong1998** [Vazkii/Botania#3523]
Sometimes my thorn chakram does not come back to my inventory. I've lost about 3 now. Usually this happens when I'm moving around. I have a ring of dexterity and rod of the skies. Perhaps using those with thorn chakram make it not come back in time? Sometimes I retrace my steps and see the chakram on the floor.

Botania-1.16.3-409

**Comment by TheGreatCatAdorer** [comment]
They might have flown into an unloaded chunk or a portal.  Do you have a low render distance or nether/end portals nearby?  If so, try moving away from your base, increasing your render distance, and/or entering the portals.

**Comment by Zarniwoop42** [comment]
I'm having this issue as well. I'm pretty sure it's not a problem with unloaded chunks since it's happened in my base (I have no portal, either)
