### ISSUE TITLE
Floating flowers break farmland

### ISSUE THREAD

**Issue by ToMe25** [Vazkii/Botania#3526]
# Version Information
Forge version:  34.1.0
Botania version:  9ceaf2c

# Further Information
Steps to reproduce:
1. Make farmland
2. Place a floating flower ontop
3. search for dirt

What I expected to happen:
I expected the floating flower to float above the farmland without breaking it.
EDIT: It doesn't work in 1.15 either, i should have tested that myself.

What happened instead:
The floating flower broke the farmland for no good reason
![2020-11-24_16 40 22](https://user-images.githubusercontent.com/38815969/100117049-b7394580-2e74-11eb-844b-36206acf3175.png)

**Comment by ToMe25** [comment]
After looking into this a bit i am more surprised that it seems to work in 1.15, then that it doesn't in 1.16.

**Comment by ToMe25** [comment]
The image above is from forge, but this doesn't work on fabric either:
![2020-12-10_19 48 45](https://user-images.githubusercontent.com/38815969/101816560-76525980-3b21-11eb-9958-322e880d835b.png)

**Comment by G-Stav** [comment]
I think it's always done this, at least for a long while. If you do have farming for blockheads however using the no-trample-soil-upgrade (don't remember the exact name) you can place the rannucarpus on it.

**Comment by ToMe25** [comment]
Thanks for fixing this :)
