### ISSUE TITLE
I Got an undefined flower

### ISSUE THREAD

**Issue by Noam1415113** [Vazkii/Botania#3529]
# Version Information
Forge version:14.23.5.2847
Botania version:  r-1.10 363

This happned using the "Chance cubes" mod.
One of the things that can happen is the chance cube giving the player a random item,
the random item I got was an undefined flower.
not rly any steps to reprouduce except opening chance cubes and getting insanely lucky.

**Comment by williewillus** [comment]
1.12 is notoriously known for producing these, no workaround, just throw them away
