### ISSUE TITLE
Lexica Botania Elven Knowledge|Blaze and Bellethorne

### ISSUE THREAD

**Issue by GabuSilver** [Vazkii/Botania#3540]
Minecraft version: 1.16.4

Botania version: 409

What I expected to happen:

>When a Lexica Botania (Minecraftian knowledge/basics)  is thrown into an Alfheim Portal, the "trade" back would the "second" tier info or "Elves knowledge" would be written/unlocked. 

>It twists any Mana provided to slowly inflict harm in any living beings (save for players) around it. When a creature dies/is slay/is killed it their drops would be dropped, ANY.

What happened instead:

>The Lexica Botania with Elven Knowledge isn't given back. (I tried many times, 5 to be exact. First I did "read" all other "!" on top of chapters, I do know how to play, I just enjoy reading all contain chapters inside the book; also I did checked my Mana Pools which were full, and again thrown Lexica Botania. There a Hopperhock nearby, by checking the chest there wasn't any sign of book. I did break it tho, just in case. It keeps disappearing, just for info, other Elves trades such as; Elementium, Dragonstone and Pixie Dust are working properly).

>I think I did report this at Vazkii's Discord server but still I'll post it here too now: Bellethrones are killing Blazes (I have a Blaze Farm, courtesy of Apotheosis by bringing the spawner to the overworld) but they aren't dropping their Blaze Rods. As far am aware; Vazkiii did say at discord that it SHOULD, also I did a test in 1.12.2 (It does drop).

-Sorry if I gave unnecessary info, i just bring it so you are immerse to my point of view and how it happens by each detail. Further apologies by grammar... QnQ.

**Comment by williewillus** [comment]
> but they aren't dropping their Blaze Rods

they should not, Vazkii was mistaken. blaze rods are player-kill-only drops.

**Comment by williewillus** [comment]
avatars are not players

**Comment by GabuSilver** [comment]
I know, but it was curiosity. Have a good day :D

**Comment by servireettueri** [comment]
I can't get my lexica botania to upgrade either

**Comment by J0dla** [comment]
Botania 411 
Forge: 36.0.22
Minecraft:1.16.5
Same problem after dropping lexicon into portal nothing happens :(

**Comment by Hubry** [comment]
Make sure you don't have any stray items in the portal (like single manasteel ingots, you can break and replace the portal core to clear it), or update Botania to latest.

I guess this issue can be closed now? Part one is (now fixed) #3608 and part two is an answered question...
