### ISSUE TITLE
Runnuncarpus on top of coarse dirt will not equally identify other coarse dirt as a valid "soil filter"

### ISSUE THREAD

**Issue by Algester** [Vazkii/Botania#3543]
# Version Information
Forge version: 35.1.0 
Botania version:  1.16.3-409

# Further Information
Steps to reproduce:
1. Put the Runnuncarpus on top of coarse dirt.

What I expected to happen:
The Runnuncarpus should put and valid item as a block in this case because of it being a tree farm sapplings

What happened instead:
The Runnuncarpus puts it on any valid Dirt blocks instead as if the flower doesnt detect the change of block data based on the coarse dirt below it and the wand does say it is on top of "dirt". Unless minecraft still treats coarse dirt as any other dirt block? And that not letting grass grow on it makes it none special?

**Comment by Alwinfy** [comment]
Quick check: Is the Rannuncarpus in [floating form](https://botaniamod.net/lexicon.php#shinyFlowers)? If not, the Rannuncarpus will attempt to place on the block *below* its soil:
![image](https://user-images.githubusercontent.com/20421383/101265763-97284280-370e-11eb-8e92-4f9fd9d8fbe0.png)

**Comment by Algester** [comment]
ohh right.... RIGHT.... yes I also turned it floating I forgot about that one thats on me
