### ISSUE TITLE
Getting attacked by ghosts from ice and fire crashes the game

### ISSUE THREAD

**Issue by someDudeeeee** [Vazkii/Botania#3544]
# Version Information
Forge version:  35.1.2
Botania version:  latest

# Further Information
Link to crash log: https://pastebin.com/vtTuQrxf
Steps to reproduce: 
1.use botania and ice and fire
2.let ghost attack you

What I expected to happen: to get attacked by a ghost

What happened instead: the game crashed

**Comment by williewillus** [comment]
#3517
