### ISSUE TITLE
GoG datapack not loading after botania

### ISSUE THREAD

**Issue by rootwalla** [Vazkii/Botania#3550]
# Version Information
Forge version:  35.1.7
Botania version:  410
GoG version: 1.6

What I expected to happen: See gog version of the recipes 

What happened instead: Saw botania version of the recipes

I have since "fixed" this by copying the recipes from the gog jar into a datapack and loading that last with a command.
(incidentally if anyone can tell me how to set this load order permanently and not just for the current session, I will be grateful) 

As a side question: is there no longer a way to edit the orechid individual ore probability?

Thanks

**Comment by williewillus** [comment]
In the latest Botania/GoG the override parts have moved back into Botania itself, so this shouldn't  be a problem anymore.
