### ISSUE TITLE
the Ring of Odin does not prevent magma block fire damage

### ISSUE THREAD

**Issue by Jeuvke** [Vazkii/Botania#3553]
# Version Information
Forge version:  1.16.4-35.1.7
Botania version:  1.16.3-409

# Further Information
Steps to reproduce:
1. Wear a Ring of Odin
2. Step on a magma block

What I expected to happen:
You take no fire damage.

What happened instead:
You take fire damage from the magma.

**Comment by Hubry** [comment]
88f2f6515c8b513c3ac8ecfd06946678b463085b, wait for next build
