### ISSUE TITLE
Botania flower bug - Take it easy achievement

### ISSUE THREAD

**Issue by plugnplay0** [Vazkii/Botania#3556]
# Version Information
Modpack: Modern Skyblock 3.6.0
Botania version:  1.10-360

# Steps to reproduce:
Have some bees from MagicBees in apiaries (Forestry/GenDustry).
Have some dirt or grass nearby.
When the bees pollinate, there's a chance for a Botania Flower to spawn on one of the dirt/grass blocks. The item's subtitle is 'Miscellaneous Flower', with the description 'If you have this, it means something went wrong, you should report it'.

# What I expected to happen:
Probably get some real Botania flowers instead of a Botania Flower.

# What happened instead:
Got a Botania Flower, as well as the 'Take it easy' achievement.
![2020-12-13_01 41 38](https://user-images.githubusercontent.com/3961612/102000137-60d95d00-3ce4-11eb-92f6-db2b37d47c01.png)

**Comment by williewillus** [comment]
3557
