### ISSUE TITLE
[1.16.4] [Forge] Lexica Entry for Solegnolia is Confusing

### ISSUE THREAD

**Issue by HipHopHuman** [Vazkii/Botania#3559]
Not a bug, just an issue with documentation.

The Lexica Botania entry for the Solegnolia is a bit confusing.

Firstly, there is this, which I think is an inconsistency:

The entry in the Lexica says the flower does not consume mana.

![image](https://user-images.githubusercontent.com/70091260/102053189-fd3c5600-3def-11eb-8a95-b92c5635700c.png)

The flower itself clearly shows that it requires access to a mana pool in order to function:

![image](https://user-images.githubusercontent.com/70091260/102053256-16dd9d80-3df0-11eb-89fb-ee554921e82f.png)

I'm not sure if this is an artefact of old changes to the flower where documentation was left out, or if the flower truly doesn't consume mana despite having to be linked to a mana pool, but in either case I think the Lexica entry should be changed to more accurately reflect the flower's mana consumption, or at least remove that last sentence entirely and just leave it as a mystery for the player to discover themselves.

Secondly, there is also this part of the entry in the Lexica:

>  "Any rings within its radius are also prevented from picking items up"

I'm not sure what this means. The way the flower works, is it prevents items from being sucked to me when I'm wearing a ring. That part is already described in the sentence that precedes it *("The Solegnolia disrupts the ring's field of effect and prevents any items near it from being pulled towards a ring-bearer.")* and works as advertised.

The sentence in the blockquote gives the impression that the flower should *also* be preventing the player from picking up *any* items as long as those items and the player are standing within the Solegnolia's radius and they are wearing a ring. In all my experience, this has never been the case. I can still pick up items as long as I'm standing near enough to them, with a ring, a mana tablet and a solegnolia full of mana. I'm not certain if this is a bug with the flower and it *should* behave that way, or if this text is just re-stating what was said in the sentence that came before it and is just superfluously taking up space. Perhaps you can clarify this?

**Comment by Hubry** [comment]
The flower does not consume mana, and its internal storage is 1 (one) mana which is never used. I have no idea why it's not a miscellaneous flower like the daisy or the manastar, would need to ask Vazkii, maybe it's worth changing. Not needing mana to function is not uncommon though, both the rannuncarpus and the hopperhock can do that (though with a reduced radius).

The confusing sentence is two separate functions: items sitting in the flower's range aren't pulled, and rings in the flower's range don't pull anything.

**Comment by HipHopHuman** [comment]
> The flower does not consume mana, and its internal storage is 1 (one) mana which is never used. I have no idea why it's not a miscellaneous flower like the daisy or the manastar, would need to ask Vazkii, maybe it's worth changing. Not needing mana to function is not uncommon though, both the rannuncarpus and the hopperhock can do that (though with a reduced radius).

I'm aware, and those entries in the Lexica clearly explain that. This however is different -  it makes the player assume that a mana pool isn't necessary and then they become confused when it doesn't work.

> The confusing sentence is two separate functions: items sitting in the flower's range cannot be pulled by any rings, and players in the flower's range cannot pull any item with the ring no matter where it is located.

Then the wording is confusing, it sounds as if it prevents any items from being picked up. It should be changed to this description you've just given ^
