### ISSUE TITLE
Exception while ticking 1.16.4

### ISSUE THREAD

**Issue by ClaudiusMinimus** [Vazkii/Botania#3560]
# Version Information
Forge version:  35.1.12
Botania version:  1.16.4-410

# Further Information
https://pastebin.com/bJtrhZ5p
Steps to reproduce:
Not sure what happened. There was only one player on our server at the time and he was not doing anything with Botania. I was notified the server was down and found Botania listed. Wish I could offer more information.

**Comment by williewillus** [comment]
Botania isn't in the stack trace at all, so I'm going to need more information

**Comment by Hubry** [comment]
Have you tried updating Blame? It apparently had an issue where items without a special behavior would crash when thrown by a dispenser.

**Comment by Hubry** [comment]
TelepathicGrunt/Blame@24cafb2a569434c010ca3861f549a866666a2880
Fixed in latest Blame, I asked the mod author.

**Comment by TelepathicGrunt** [comment]
@ClaudiusMinimus  This 100% my fault. Please update Blame to 1.7.5 as I screwed up dispenser code checks in 1.7.4 and below
