### ISSUE TITLE
Headflower name correction

### ISSUE THREAD

**Issue by Gideonseymour** [Vazkii/Botania#3561]
# Version Information
Forge version:  n/a
Botania version:  n/a

# Further Information
Hey, I'm sorry to bother you, this isn't really a big deal but I don't know where else to post it. [My name is here](https://github.com/Vazkii/Botania/blob/master/contributors.properties#L12) in the list of contributors who get head flowers. For various reasons, I don't go by that name anymore. I was wondering if it could be updated here to be my new username, a_rat_girl

Thank you for your time, I'm sorry to bother you. If you need proof it's me let me know.

**Comment by Gideonseymour** [comment]
[Here is a link to the section on the FTB forums in my deadname](https://forum.feed-the-beast.com/forum/gideonseymour.236/), showing the modpacks I made in association with my deadname. [Here is a link to the account that made those posts](https://forum.feed-the-beast.com/members/buggirlexpres.7995/#about), showing my current username of a_rat_girl for Twitter. This is the same name I use for Minecraft. Hopefully this helps verify my identity. 

Here is a pull request which will resolve this issue: https://github.com/Vazkii/Botania/pull/3566

Thank you for your time.

**Comment by williewillus** [comment]
merged
