### ISSUE TITLE
Alf shatterer Not breaking certain types of blocks

### ISSUE THREAD

**Issue by Cubus84** [Vazkii/Botania#3562]
Playing on GoG 4.0.2

Alf shatterer only breaks netherite blocks when mining and subsequently the ores in its AOE but doesn't do anything when pointed at a ore. I noticed a shulkerbox or enderchests cannot be broken with the shatterer either.

# Version Information
Forge version:  4.0.2
Botania version:  Garden of glass

# Further Information
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)\
Steps to reproduce:
1. First step
2. Second step
3. etc...

What I expected to happen:

What happened instead:

**Comment by williewillus** [comment]
Please fill out the full template and include proper version numbers for everything ("4.0.2" is not a GoG version, nor is the "Alf shatterer" a Botania item)

**Comment by Cubus84** [comment]
Sorry I'm quite new at this I'll pay better attention next time
