### ISSUE TITLE
Crash using Rod of the Terra Firma

### ISSUE THREAD

**Issue by dkbhn** [Vazkii/Botania#3563]
# Version Information
Forge version:  25.1.12
Botania version:  1.16.4-410

# Further Information
Playing on my server, doesn't happen in SP
Link to crash log: https://pastebin.com/TbW3WmDM

Steps to reproduce:
1. get Rod of the Terra Firma
2. Right click and hold pointing at dirt

Also, If playing on my server, and I log out, then I can't log in again, unless I restart the client.
[latest.log](https://github.com/Vazkii/Botania/files/5715700/latest.log)

What I expected to happen: -

What happened instead: Crashed

**Comment by williewillus** [comment]
cannot reproduce
