### ISSUE TITLE
Mystical Flowers crafting into more than 2 petals each

### ISSUE THREAD

**Issue by Marshy13** [Vazkii/Botania#3564]
Found on the 1.16 direwolf20 modpack version 1.0.0

Crafting petals by clicking the left petals or shift clicking the whole stack works as intended. However if I crafted petals using keys 1-9 to craft two petals to my hotbar and then shift left click the remaining mystical flowers, it would create much more than 2 petals per flower. 

9 flowers turned into 4 stacks
17 flowers turned into 12 stacks
21 flowers turned into 16 stacks

This bug happens with any color of mystical flower, as well as with both the regular and tall mystical flowers. Gamemode does not seem to matter as it worked in both survival and creative. It happens regardless of which crafting window is used. Both the 2x2 crafting in the inventory and the 3x3 crafting using the crafting table gave me the same results. Exiting and reloading the world as well as rebooting the game didn't help.  

Here is a link to a video showing this bug. I felt it would be useful to give a clip of it happening in addition to the textual description below.
https://streamable.com/upo9m3

# Version Information
Forge version:  35.1.13
Botania version:  1.16-410

# Further Information
Steps to reproduce:
1. First step - Place mystical flowers in crafting window
2. Second step - Use any key 1-9 to craft two petals onto the hotbar
3. Third step - Shift left click to craft the remaining petals

What I expected to happen: 2 petals per mystical flower

What happened instead: much more than 2 per mystical flower

----------------------------------------------------------------------------------------------------------------------------------------------
Apologies something is off or missing I have never created a bug report before. I also don't have a crash report as there was no crash.

**Comment by williewillus** [comment]
Can you try with just botania? sounds like another mod messing with how crafting works

**Comment by Marshy13** [comment]
It works fine with just Botania, so it seems you're correct about another mod messing with the crafting. Sorry for the trouble.
