### ISSUE TITLE
Can't find pixie spawn chance (1.16.4)

### ISSUE THREAD

**Issue by Awoo-desu** [Vazkii/Botania#3568]
Redirected from Ice and Fire (I thought it was because of the cockatrice attacking me), apperantly the pixies are making my game crash on loading world.

Forge 35.1.13

https://pastebin.com/JQxarmzt

**Comment by williewillus** [comment]
this is https://github.com/qouteall/ImmersivePortalsModForForge/pull/182, install Immersive Portals 0.10 or higher
