### ISSUE TITLE
Hopperhock pickup behavior

### ISSUE THREAD

**Issue by Krutontar** [Vazkii/Botania#3569]
# Version Information
Forge version:  35.1.13
Botania version:  1.16.4 410

# Further Information

What I expected to happen:
The hopperhock, in the past, seems to know when an item is produced by a botania mechanic craft and instantly, or at least very quickly, pick it up such as from the output of a mana pool or the runic altar.

What happened instead:
It seems like it's treating everything as if it were dropped by an open crate and is getting a delay.

**Comment by williewillus** [comment]
please present an exact setup that is expressing the bug and show it not working and working in an older version.

**Comment by Krutontar** [comment]
The more I probe this the more I think it's a server TPS issue. Sorry.
