### ISSUE TITLE
Obligatory undefined flower report

### ISSUE THREAD

**Issue by wiverns** [Vazkii/Botania#3571]
Sacrified a fallen kanada to the flower pot gods, was bestowed the mythical _Botania Flower_ as compensation
![2020-12-23_12 11 30](https://user-images.githubusercontent.com/46330016/103025791-29568600-4518-11eb-90b5-a76d9e1c9cec.png)

**Comment by Hubry** [comment]
It's fixed for three whole major Minecraft versions, and there is a pinned issue about this.
