### ISSUE TITLE
Crash while rendering Gaia head with the Indicatia mod

### ISSUE THREAD

**Issue by PokeMaserJ** [Vazkii/Botania#3572]
# Version Information
Forge version:  35.1.11
Botania version:  1.16.4-410
Indicatia version: 1.16.4-4.0.1

# Further Information
https://gist.github.com/PokeMaserJ/9b64df158827ba8129e7cc44eca8cef0
Steps to reproduce:
1. First step look up head in Creative / JEI
2. Second step Crash to desktop
3. etc...

What I expected to happen:
Not to crash
What happened instead:
Crash while viewing the Gaia Head

**Comment by PokeMaserJ** [comment]
https://github.com/SteveKunG/Indicatia/issues/22

**Comment by Hubry** [comment]
Looks like it was fixed by them already?

**Comment by PokeMaserJ** [comment]
My bad, forgot to close it

**Comment by Hubry** [comment]
It's fine, only noticed because of stale bot
