### ISSUE TITLE
Force Relay Disappears on Use

### ISSUE THREAD

**Issue by Aelpecyem** [Vazkii/Botania#3575]
# Version Information
Fabric version:  0.28.4 (API) 
Botania version:  1.16.4-411-Fabric (trunk of Fabric 1.16.x branch)

Steps to reproduce:
1. Place Force Relay
Optional: Bind Force Relay
2. Use Piston to push Force Relay

What I expected to happen:
The bound block gets pushed. 

What happened instead:
The Force Relay disappeared

**Comment by williewillus** [comment]
I told you to report this to the fabric tracker: https://github.com/williewillus/botania-fabric-issues/issues
