### ISSUE TITLE
1.16.4 Unable to use addRecipe for ManaInfusion

### ISSUE THREAD

**Issue by plunginghornets** [Vazkii/Botania#3578]
# Version Information
Forge version:  35.1.10
Botania version:  1.16.4-410
Crafttweaker version: 1.16.4-7.0.0.63

# Further Information
I am trying to do some recipe changes in the newest version. I used the sample recipe found [here](https://github.com/Vazkii/Botania/pull/3521), specifically the "mana_infusion_test".
`<recipetype:botania:mana_infusion>.addRecipe("mana_infusion_test", <item:minecraft:dirt><item:minecraft:enchanted_golden_apple>, 200);`

What I expected to happen: Enter command "/ct syntax" and get no results. Restarting Minecraft adds a recipe.

What happened instead: Received error: "No such member: addRecipe" Recipe did not get added when restarting.

I was able to successfully `removeRecipe` for Mana Infusion. I removed the infusion recipe for ManaSteel Ingots.

# Edit 12/29
I have since tried all the other botania recipe types. They all allow me to remove recipes but give the same "No such member: addRecipe" error.

**Comment by williewillus** [comment]
The crafttweaker support isn't released yet.

**Comment by plunginghornets** [comment]
Darn. Wish I understood github better so I wouldn't waste your time.

Guess I'll keep an eye out for new botania/crafttweaker versions.

**Comment by williewillus** [comment]
for future reference, you can check the [changelog](https://botaniamod.net/changelog.php) to see if something is officially out yet
