### ISSUE TITLE
Terra Shatterer In Awakened Mode Destroys Bedrock

### ISSUE THREAD

**Issue by seelani** [Vazkii/Botania#3579]
# Version Information
Forge version:  35.1.13
Botania version:  1.16.4-410

# Further Information
Link to crash log: **No crash log**
Steps to reproduce: **Refer to below description**

What I expected to happen: Awakened Terra Shatterer to mine blocks around bedrock, without breaking adjacent bedrock.

What happened instead: Awakened Terra Shatterer from Rank C onwards is able to break bedrock by breaking adjacent blocks.

Additional Notes: Noticed the issue on ATM6 modpack. I also tested breaking one of the blocks(Unobtanium) from the modpack where the Terra Shatterer should not be able to mine. If I break the block adjacent to Unobtanium it breaks it but does not drop the block.

I also tested it on a fresh instance (as above Version) to confirm the issue. This could be a repeat of the following issue [https://github.com/Vazkii/Botania/issues/483](https://github.com/Vazkii/Botania/issues/483).

**Comment by williewillus** [comment]
Can you try with just botania?

**Comment by seelani** [comment]
I've already tested with just Botania. (Note that I had to include Curios and Patchouli which are dependencies.)
The result is the same, the Awakened Terra Shatterer can break bedrock by breaking adjacent blocks.

Forge version: 35.1.13
Botania version: 1.16.4-410
Curios version: 1.16.4-4.0.3.0
Patchouli verison: 1.16.4-48
