### ISSUE TITLE
Expected: entropinnyum absorbs explosion damage when tnt in range.

### ISSUE THREAD

**Issue by nvizo** [Vazkii/Botania#3580]
Expected: entropinnyum absorbs explosion damage when tnt explodes within active range of flower.

What happens: If a tnt is lit outside flower range and pushed within flower range by another tnt for example the explosion damage is not absorbed.

Note: Trying to make a minigame where tnt shouldn't explode in a certain area to prevent damage to game. I think making this change makes would be helpful for this type of use case

# Version Information
Forge version:  
Botania version:  

# Further Information
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)\
Steps to reproduce:
1. First step
2. Second step
3. etc...

What I expected to happen:

What happened instead:

**Comment by williewillus** [comment]
Can you show a setup or upload a world that reproduces this?

**Comment by nvizo** [comment]
Not sure how to upload world but here is a basic setup that reproduces the issue. You may have to press the button a couple times before it happens. https://i.imgur.com/de5lKQG.png

**Comment by nvizo** [comment]
Here is a setup that shows the problem a little better. The glass is well within the range of the flower but it still gets blown up about 50% of the time. https://imgur.com/a/1NnXD2G

**Comment by williewillus** [comment]
Is the entro completely empty? It won't absorb a blast if it's not completely empty. You probably want gaia spreaders.

**Comment by nvizo** [comment]
Yep I think that was it. I think one TNT blast fills up a normal mana spreader which explains why I only ever saw it after the second try. I switched it out for a Gaia spreader and it's working great now. Thanks!
