### ISSUE TITLE
Terra-shatterer breaking bedrock.

### ISSUE THREAD

**Issue by JustLiam040** [Vazkii/Botania#3583]
Tested on: Version 1.16.4
Botania Version: 1.16.4-410

Saw a thread about this from 2015, seems the bug has either resurfaced or not been fixed, essentially if you mine a block adjacent to bedrock when in awakened mode it will destroy the bedrock. This is of course, not intended behaviour. I have attached a short video just to demonstrate the issue. 

Was discovered in the DW20 modpack but have found the issues does carry over to a standalone Botania instance hence the submission here. (Has also submitted in the pack github too.)

https://user-images.githubusercontent.com/33065753/103424927-0f1b4880-4ba7-11eb-93ed-c96f7f906866.mp4

**Comment by williewillus** [comment]
fixed in next version
