### ISSUE TITLE
Corporea Network freezes world upon requesting items

### ISSUE THREAD

**Issue by jaojake1804** [Vazkii/Botania#3585]
# Version Information
Forge version:  35.1.13
Botania version:  1.16.4-410

# Further Information
Link to crash log: No crash log generated, unable to crash world on F3+C or shut it down.
Steps to reproduce:
1. Launch Botania and set up a Corporea system
2. Use a Corporea index to request an item
3. Game bugs out

What I expected to happen: Upon requesting the item I expect it to go into my inventory and then continue the game as normal

What happened instead: When the item has been requested, the item request will be successful (mostly). After the item has been requested, any blocks broken simply disappear from the world and not drop. The whole game freezes with exception to the player, who can still move, but can't break blocks etc.

This has happened on both a single player instance with my friend (link to clip here: https://www.twitch.tv/videos/858658953) and myself in a multiplayer world.

**Comment by williewillus** [comment]
This can happen if you relog quickly before accessing corporea and has been fixed in the next version (probably going out today or tomorrow). Look out for it then
