### ISSUE TITLE
[1.16.4/Server] Creating new GoG world doesn't create skyblock type 

### ISSUE THREAD

**Issue by remplerus** [Vazkii/Botania#3586]
# Version Information
Forge version:  35.1.28
Botania version:  1.16.4-410

# Further Information
Steps to reproduce:
1. Install Botania and GoG on forge server
2. try to set botania-skyblock as level-type
3. normal world creates instead of skyblock type

What I expected to happen:
Botania Skyblock

What happened instead:
Normal Worldtype

The "fix" with pasting a working level.dat doesn't work, the server just overwrites it

**Comment by williewillus** [comment]
@Hubry

**Comment by Hubry** [comment]
d04eb2362bec6f1849660496884f9ef4fd7ced22 is not in released version yet :P
When that's released, the world type registry name to put in the server.properties or the Forge config option is `botania:gardenofglass`.

**Comment by remplerus** [comment]
jup, tested it with the snapshot from the jenkins and its working. if you just put level-type=botania:gardenofglass into server.properties and it's working like nothing. so i just need to wait for botania update to load it into my modpack 👍

**Comment by williewillus** [comment]
as mentioned above, this is fixed in the next version
