### ISSUE TITLE
Bore Lens Enchantments not working

### ISSUE THREAD

**Issue by DevilSushi** [Vazkii/Botania#3587]
Forge version:  forge-35.1.10, forge-35.1.28
Botania version:  1.16.4-410

Steps to reproduce:
1. Take a Bore Lens and enchant it with silk touch or fortune 3 in an anvil
2. Put the lens onto a Pulse Mana Spreader
3. Break a block of Stone (Slik Touch) or Gravel (Fortune 3) with the Spreader

What I expected to happen:
To get a Block of Stone (Silk Touch) or a piece of Flint (Fortune 3), like it should happen with the respective enchantment.

What happened instead:
I got Cobblestone out of the Stone and the Gravel only gave the normal 10% chance for Flint instead of 100%.
So the Bore Lens behaved like it wasn't enchanted at all.

**Comment by williewillus** [comment]
This is not a feature.

**Comment by Alwinfy** [comment]
how did you manage to enchant it in the first place

**Comment by Alwinfy** [comment]
oh wait that's a bug lmao
