### ISSUE TITLE
Server crash firing at Terrasteel Armor with Extra Util. 2 Compound Bow in Modern Skyblock 3

### ISSUE THREAD

**Issue by InfoLK-sjg** [Vazkii/Botania#3589]
Forge version:  forge-14.23.5.2854
Botania version:  Botania r1.10-360.jar

# Further Information
Link to crash log: https://pastebin.com/bUtujeZE
Link to crash in server log: https://pastebin.com/1MYDFr6n
Steps to reproduce:
1. Start Modern Skyblock 3 Departed 
2. Fire an Arrow at an Terrasteel Armor with an Extra Utillities 2 Compound bow

What I expected to happen:
Person shot at getting Damage

What happened instead:
Server crashed

**Comment by williewillus** [comment]
There's a mod shipping an old version of the botania api. Unfortunately, it's not easy to tell which one. I'd try updating all mods to their latest versions.

**Comment by williewillus** [comment]
Also, this is 1.12 which is unsupported, so closing. Try the above^, but if it doesn't work I'm not sure what else will.
