### ISSUE TITLE
jdk.nashorn.internal.runtime.ECMAException: TypeError: null has no such function "getPrevious"

### ISSUE THREAD

**Issue by thepriz** [Vazkii/Botania#3590]
# Version Information
Forge version:  1.16.4-35.1.29
Botania version:  1.16.4-410

# Further Information
Here is the link to the logs:
https://gist.github.com/thepriz/a4b2a2d599dc777d890a5a6fe2b024f0

Steps to reproduce:
1. Startup Minecraft with Botania installed.
2. Check Logs

What I expected to happen:
No errors in logs

What happened instead:
errors in logs

**Comment by williewillus** [comment]
Try with just Botania.
