### ISSUE TITLE
Lens can not combine

### ISSUE THREAD

**Issue by flier268** [Vazkii/Botania#3591]
# Version Information
Forge version:  35.1.28
Botania version:  Botania-1.16.4-410
![圖片](https://user-images.githubusercontent.com/19989232/103509061-3e7acf80-4e9d-11eb-9647-9e5e3fdfc4ff.png)
What I expected to happen:

What happened instead:
Lens can not combine

![圖片](https://user-images.githubusercontent.com/19989232/103508378-d677b980-4e9b-11eb-9d98-a4156fd615cf.png)

**Comment by Alwinfy** [comment]
That first lens is a Bounce Lens (反射). You're likely looking for the Warp Lens (传送).

Note also that, if you're trying to use Force Relays (力量传递器), you want to put the Warp Lens **second**.

**Comment by williewillus** [comment]
^
