### ISSUE TITLE
Mine lens will broke piston relay

### ISSUE THREAD

**Issue by flier268** [Vazkii/Botania#3592]
# Version Information
Forge version:  35.1.28
Botania version:  Botania-1.16.4-410
![圖片](https://user-images.githubusercontent.com/19989232/103509061-3e7acf80-4e9d-11eb-9647-9e5e3fdfc4ff.png)

# Further Information
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)\
Steps to reproduce:
1. Bind piston to a block
2. Put a mine lens on the gun
3. fire

What happened instead:

![圖片](https://user-images.githubusercontent.com/19989232/103508880-d1673a00-4e9c-11eb-85ce-a1215cbe3bb5.png)

By the way,
Piston relay always not work in any lens
![圖片](https://user-images.githubusercontent.com/19989232/103508861-c6140e80-4e9c-11eb-9b65-e812202d9f9b.png)

**Comment by williewillus** [comment]
This is the intended behavior. What were you expecting to happen?

**Comment by flier268** [comment]
> 
> 
> This is the intended behavior. What were you expecting to happen?
Should be like [this](https://www.youtube.com/watch?v=ysMknXgYFh0)

**Comment by Alwinfy** [comment]
You want a Composite Mana Lens: Bore Warp (挖掘 传送 I think). This is obtained
by placing a Bore lens with a Warp lens in a crafting grid with a slimeball.

From the documentation book:
> when [the Warp Lens is] combined with a Bore Lens (the Bore Lens must be
first), it'll prevent bursts from breaking Force Relays or Pistons, and
teleport any blocks broken by the Bore Lens to the burst's origin.

**Comment by williewillus** [comment]
^
