### ISSUE TITLE
[1.16] Nether Gold ore gets generated by Orechid instead of Orechid Ignem

### ISSUE THREAD

**Issue by luxamy** [Vazkii/Botania#3593]
Forge version:  35.1.29
Botania version:  1.16.4-410

Steps to reproduce:
1. Place a Orechid/Orechid Ignem and a filled manapool
2. place stone/netherrack nearby

What I expected to happen:
Nether Gold ore should be generated by the Orechid Ignem instead of the Orechid, since it spawns in the Nether
and has a Netherrack texture

What happened instead:
The Orechid generated Nether Gold Ore, but the Orechid Ignem didn't

Edit:
I should note that I have Garden of Glass also installed.

**Comment by Hubry** [comment]
The orechid assigns weights to tags and not single blocks, and there is just one tag for gold ores.

**Comment by Hubry** [comment]
Forgot to close this, but nether gold has been banished to the Nether.
