### ISSUE TITLE
[Bug] [Corporea] [1.16.x] Corporea funnel wonkiness with interceptors

### ISSUE THREAD

**Issue by FizzBuzz3000** [Vazkii/Botania#3601]
# Version Information
Forge version:  35.1.36
Botania version:  1.16.4-410

What I expected to happen: all corpora funnels are activated at once

What happened instead: Only 3 corporea funnels activate

[setup, all interceptor item frames are using corporea bricks in the item frames](https://cdn.discordapp.com/attachments/154261184701267969/797724833563410482/unknown.png) the lights in the back are powered by the quick redstone pulse into a repeater and into a block, to prevent redstone signals from leaking over.
[Input barrel, connected to the corporea system](https://cdn.discordapp.com/attachments/154261184701267969/797725054695505930/unknown.png)
[Output barrel, not connected to the corporea system](https://cdn.discordapp.com/attachments/154261184701267969/797725254901694494/unknown.png)

It seems to consistently grab 3 items and not grab the other 4 remaining as depicted by these pictures:
[input after interception](https://cdn.discordapp.com/attachments/154261184701267969/797726316555534337/unknown.png)
[output after interception](https://cdn.discordapp.com/attachments/154261184701267969/797726174330617866/unknown.png)

[Mixed items test](https://i.imgur.com/PiyTrSq.png), notice how I've changed the number of items requested with the book and redstone.
[Mixed input barrel](https://i.imgur.com/kF5pG8t.png)
Output was empty, I removed the 3 lamps.

[After interception.](https://i.imgur.com/GpLCm2l.png)
The # of items requested from the three working funnels worked, but only 3 funnels ever *worked*.

Sometimes it *does* work properly but usually only after the first try. Otherwise it is hit and miss. filled this out at 2AM, if you need more details like logs, just ask.

**Comment by quat1024** [comment]
After some discussion on discord it was discovered that this effect is usually related to the corporea funnel's intentional implementation of quasiconnectivity. Some of the funnels don't get into the unpowered state so powering then again does nothing. Inconsistent behavior stems from inconsistent redstone dust update order

**Comment by FizzBuzz3000** [comment]
God I hate this redstone jank, mojang pls fix
