### ISSUE TITLE
[1.16.4] Using the Lexica Botania with the Akashic Tome mod displays the wrong title on the held item

### ISSUE THREAD

**Issue by SomeSpicyCheese** [Vazkii/Botania#3603]
# Version Information
Forge version:  35.1.32
Botania version:  410

# Further Information
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)\
No crash log, visual glitch)
Steps to reproduce:
1. Have both Botania version 410 and Akashic Tome version 1.4-15 installed
2. Place the Lexica Botania in the Akashic Tome
3. Select the Lexica Botania with the Akashic Tome
4. Behold its mistitled glory!

What I expected to happen:
![image](https://user-images.githubusercontent.com/76858823/104243606-ad17da00-5415-11eb-9d4c-9814e0cdc6da.png)
(This one shows me holding the Lexica Botania on its own)

What happened instead:
![image](https://user-images.githubusercontent.com/76858823/104243561-97a2b000-5415-11eb-9de2-f01dd6a7d1e3.png)

**Comment by Hubry** [comment]
Fixed in 2b4203b4a75b3.
