### ISSUE TITLE
Option to increase flower spawns in 1.16.4 | Sorry, not a bug report but a feature request

### ISSUE THREAD

**Issue by FearAK** [Vazkii/Botania#3604]
Can we have the option to increase flower spawns in 1.16.4? I'm a flower lover and would like to have the option to increase it in 1.16.4 :(

**Comment by williewillus** [comment]
They're already pretty common. If you want more, use floral fertilizer or the Jaded Amaranthus

**Comment by williewillus** [comment]
^
