### ISSUE TITLE
[Bug][1.16.4] Daffomill consumes mana when disabled by redstone

### ISSUE THREAD

**Issue by FizzBuzz3000** [Vazkii/Botania#3607]
Title says all, disabling the daffomill with redstone does not stop it from consuming mana

# Version Information
Forge version:  35.1.36
Botania version:  1.16.4-410

# Further Information
Steps to reproduce:
1. Disable daffomill with redstone
2. Add mana to it
3. Watch it slowly drain

What I expected to happen: Not consume mana while disabled.

What happened instead: It consumes mana.

**Comment by Hubry** [comment]
Identified on Vazkii's discord as a desync when powered by a comparator.
5337f18
