### ISSUE TITLE
Lexica botania not being "traded" or returned. I've tried 8 times so far.

### ISSUE THREAD

**Issue by servireettueri** [Vazkii/Botania#3608]
# Version Information
Forge version:  0.1.166.1.4
Botania version:  the most recent. Or at least it says there are no more updates.

# Further Information
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)\
Steps to reproduce:
1. First step make elven portal
2. Second step throw lexica betania
3.  hang head in shame for throwing resources away

What I expected to happen:
Whne I throw in the Lexica Botania I should get the upgraded version.
What happened instead:
Nothing happens

**Comment by Hubry** [comment]
> Forge version: 0.1.166.1.4
No such version of Forge exists, and I have no idea where did you get that version number.
> Botania version: the most recent. Or at least it says there are no more updates.
"most recent" is vague and on many occasions mod users thought they are using the latest one, but were horribly outdated as they downloaded a mod from a mod reposting website.
List the exact versions of both (obtained from the ingame mods menu) and what modpack you are using, as well as a console log.

**Comment by davidsielert** [comment]
This happens for me too in ATM6 with forge 35.1.36 with Botania-1.16.4-410

**Comment by Hubry** [comment]
I tried to reproduce on the latest version of ATM6 and couldn't reproduce. Provide more info, possibly even a world file.

**Comment by Thevshi** [comment]
I just ran across this issue today running Direwolf20 1.16 - 1.5.1 The version of Botania is Botania-1.16.4-411. I tried to attach a world file, but it say that file type is not supported. I am happy to provide it if you can give me an alternate means of getting it to you.

**Comment by Hubry** [comment]
You can attach a zip file here ([see GitHub docs](https://docs.github.com/en/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests)). 
Compress your entire world (the level.dat and every folder and file in the same directory) and attach here.

If it is larger than 25MB, drop by Vazkii's Discord server and ping me in #help with the upload, I guess - it has enough boosts for a 100MB upload limit.

**Comment by Thevshi** [comment]
It's 441MB. I can drop it in Discord soon.

**Comment by Vashet** [comment]
Have the same issue in Direwolf20 pack version 1.6.0 on Minecraft 1.16.5 and Forge 36.0.14.

**Comment by Hubry** [comment]
Problem identified - if you have literally any remaining items in the portal (check using `/data get block <block position>` on the gateway core), the portal will refuse to output a lexicon. This is most likely going to be a miscounted manasteel ingot, since the portal discards items not used in recipes.
