### ISSUE TITLE
Mana Spreaders and Pylons don't render behind Manaseer Monocle overlay

### ISSUE THREAD

**Issue by teeth-eator** [Vazkii/Botania#3609]
# Version Information
Forge version:  35.1.36
Botania version:  1.16.4-410
-No Optifine

# Further Information
Steps to reproduce:
1. Equip Manaseer Monocle
2. Place a functional or generating flower
3. Place a Mana Spreader one block below the flower
4. Look at flower from above to see its aoe
5. The spreader doesn't render behind it
6. Replace spreader with any pylon
7. The issue persists

What I expected to happen:
The spreader renders
What happened instead:
It doesn't
(some other blocks probably have the same issue too)

![изображение](https://user-images.githubusercontent.com/72646905/104598400-97115000-5687-11eb-86d7-6044a65882c7.png)

**Comment by williewillus** [comment]
are you using fabulous mode?

**Comment by teeth-eator** [comment]
no, I am on fancy graphics

**Comment by teeth-eator** [comment]
tried using fabulous, the blocks now render properly.

**Comment by williewillus** [comment]
yeah unfortunately due to how TE rendering works nowadays this is unavoidable in non-fabulous mode. Fabulous is the "intended" solution to these problems.
