### ISSUE TITLE
Terra Shatterer doesn't mine Astral Sorcery marble in multi-mining mode

### ISSUE THREAD

**Issue by 351n** [Vazkii/Botania#3610]
# Version Information
Forge version:  31.2.42
Botania version:  Botania-r1.15-388
MC version: 1.15.2
Modpack: Valhelsia: Origins - 1.1.2
Multiplayer: Yes

# Further Information
Link to video with bug: https://streamable.com/o5xfoa 

Steps to reproduce:
1. Get Astral Sorcery marble
2. Get Terra Shatterer
3. Enable multi mining
4. Mine marble

What I expected to happen:
I expected marble to be mined just like stone.

What happened instead:
Single block of marble was mined instead of column.

**Comment by Hubry** [comment]
For some reason AS doesn't define the material of marble as rock (or any of these:) https://github.com/Vazkii/Botania/blob/dad99557eb53830ccef04ba248522a2380922342/src/main/java/vazkii/botania/common/item/equipment/tool/terrasteel/ItemTerraPick.java#L61-L63

Instead, it has its own material defined, and the terra shatterer doesn't have that on the list of materials to use.

**Comment by BlueAgent** [comment]
Perhaps check for `material is in list || tool canHarvestBlock`?
That way if the block's material isn't in the list, but the tool can still harvest the block, then it'll work okay.

**Comment by williewillus** [comment]
I think b7ebacb64dc7efbc1aeb6b4922d1ced201e88b4e fixes this? @Hubry

**Comment by Hubry** [comment]
Nope, the terra shatterer has its own list of materials that I haven't touched.
