### ISSUE TITLE
Mana tablet deletes mana from mana pool

### ISSUE THREAD

**Issue by METAmartian11** [Vazkii/Botania#3611]
# Version Information
Forge version:  
Botania version:  1.16.4-410

# Further Information
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)\
Steps to reproduce:
1. Have mana pool with mana
2. use wand to set the mana pool to empty into mana tablet
3. drop mana tablet
4. watch with wand

What I expected to happen:
When mana pool is switched to fill mana tablet drop the mana tablet into pool and the mana tablet is filled with the mana inside the mana pool.

What happened instead:
When I set the mana pool to fill a mana tablet and then drop the mana tablet the pool switches from half full to its previous level and decreases while not filling the mana tablet until the mana pool is empty.

**Comment by williewillus** [comment]
please fill in the steps to reproduce

**Comment by dreclub** [comment]
I found the mana 2 rf mod will bug pools to not accept or give mana to/from items. removing the mod solved the issue for me

**Comment by Hubry** [comment]
Alwinfy/Mana2RF@3e76ad6ae21f7e6099a1948840848b202bf684a3
