### ISSUE TITLE
Feature Request - "Deep" Mana Pools

### ISSUE THREAD

**Issue by Rumaan3012** [Vazkii/Botania#3615]
As the title says, just a deep mana pool. Maybe 5 regular Mana Pools in the 'U' shape needed to make a regular pool, bound together with a mana diamond, or maybe an Eflheim material? Maybe just a Rune of Mana? This would make mana batteries a bit better performance-wise as we wouldn't have to put as many mana pools down to make a battery, and thus reduce the amount of Sparks we had to use, and reduce particle effects while filling them.

**Comment by williewillus** [comment]
No

**Comment by Alwinfy** [comment]
see rationale: https://vazkii.net/#blog/not-in-botania

**Comment by Rumaan3012** [comment]
Understandable that people miss sparks, but my current setup uses about 30+ pools and sparks and lags a little just looking at it run. This suggestion was to help servers run more smoothly for those people who have large Mana setups. (Necessary for use with Apotheosis and the much higher enchantment caps, and thus higher Mana costs to enchant items.)

**Comment by HipHopHuman** [comment]
> Understandable that people miss sparks, but my current setup uses about 30+ pools and sparks and lags a little just looking at it run. This suggestion was to help servers run more smoothly for those people who have large Mana setups. (Necessary for use with Apotheosis and the much higher enchantment caps, and thus higher Mana costs to enchant items.)

Introducing large mana pools for this reason would just be fixing a *side effect* of the problem you are experiencing. There is already a way to reduce the effect of a spark (apply Phantom Ink), though I'm not sure if that would entirely fix any performance issues you may have. Also, I'm not a mod developer but I'm pretty certain that sparks are not ticking entities and don't do a lot to hinder performance on the server. It's more a client side thing (please correct me if I am wrong here). A better suggestion would be something like a config setting that makes it so Phantom Inked sparks only render while you're holding a Wand of the Forest, or something along those lines.

**Comment by Rumaan3012** [comment]
> > Understandable that people miss sparks, but my current setup uses about 30+ pools and sparks and lags a little just looking at it run. This suggestion was to help servers run more smoothly for those people who have large Mana setups. (Necessary for use with Apotheosis and the much higher enchantment caps, and thus higher Mana costs to enchant items.)
> 
> Introducing large mana pools for this reason would just be fixing a _side effect_ of the problem you are experiencing. There is already a way to reduce the effect of a spark (apply Phantom Ink), though I'm not sure if that would entirely fix any performance issues you may have. Also, I'm not a mod developer but I'm pretty certain that sparks are not ticking entities and don't do a lot to hinder performance on the server. It's more a client side thing (please correct me if I am wrong here). A better suggestion would be something like a config setting that makes it so Phantom Inked sparks only render while you're holding a Wand of the Forest, or something along those lines.

This would be a bit more elegant, and would solve part of the issue. The phantom ink only kind of helped because the particles of Mana floating through the air while the pools are filling are most of the issue. It was my hope to reduce the number of pools necessary, thus reducing the amount of trails created. (Think the enchanting setup bordered by pools, then surrounded again. This gets me almost 4 pieces of armor enchanted with extremely strong Apotheosis enchants.)
