### ISSUE TITLE
Manasteel/elementium shears don't take durability damage or drain mana

### ISSUE THREAD

**Issue by lordbowser** [Vazkii/Botania#3617]
# Version Information
Forge version:  35.1.37
Botania version:  1.16.4-410

# Further Information
Steps to reproduce:
1. Get some manasteel or elementium shears
2. (optional) Get a mana tablet with some mana in it
3. Use them on something

What I expected to happen:
* Using the shears would drain mana, or durability in the absence of mana.

What happened instead:
* Neither durability nor mana is consumed.

**Comment by Hubry** [comment]
Looks like someone forgot to actually make them damageable. Nice.
