### ISSUE TITLE
solegnolia petite only works on North and West side

### ISSUE THREAD

**Issue by Paperweight82** [Vazkii/Botania#3621]
# Version Information
Forge version:  35.1.36
Botania version:  1.16.4-411
![2021-01-21_12 53 55](https://user-images.githubusercontent.com/20756582/105354120-04713380-5be8-11eb-9d6c-2859cbf8bcf2.gif)

# Further Information
Link to crash log: no crash
Steps to reproduce:
1. place solegnolia petite or floating version
2. drop something next to it (i dropped many non stacking items all around it)
3. wait a few blocks away

What I expected to happen: ring of magnetization not pick up any items in range

What happened instead: ring of magentization picked up item on all sides except N, NW and W (and inside same block as non-floating version)

as far as i have tested the normal solegnolia works as expected

**Comment by Alwinfy** [comment]
probably a blockpos offset problem

**Comment by Paperweight82** [comment]
it does look like maybe the area is centred on the nw corner of the block the flower is on, now that you say it. i should have scattered more wands and it would have been clearer!
