### ISSUE TITLE
The Lexica Botania's hold control thing happens to JEI buttons, and sends you to The Resources of Alfheim page

### ISSUE THREAD

**Issue by aaronhowser1** [Vazkii/Botania#3622]
# Version Information
Forge version:  36.0.1
Botania version:  Botania-1.16.4-411

# Further Information
![image](https://user-images.githubusercontent.com/15698722/105461035-45059700-5c52-11eb-8842-2dad99f29fc3.png)
![image](https://user-images.githubusercontent.com/15698722/105461053-4c2ca500-5c52-11eb-9835-ed4a1e188b82.png)
![image](https://user-images.githubusercontent.com/15698722/105461103-5babee00-5c52-11eb-9a2f-1e35aa69eccd.png)

They all bring you here
![image](https://user-images.githubusercontent.com/15698722/105461164-75e5cc00-5c52-11eb-8dd9-a08014901dc7.png)

**Comment by Hubry** [comment]
I think it sends you to whatever was the last item you hovered over, something must not be clearing the tooltip item cache.

**Comment by Hubry** [comment]
Nevermind, I found the issue in Patchouli. Looks like there is no guarding against empty stacks for linking entries anywhere, and that page happens to be one of the pages with empty item components (as you can have multiple outputs for elven recipes)

**Comment by aaronhowser1** [comment]
I didn't report it to Patchouli since it only seemed to be happening with the Lexica Botania (it didn't happen with Industrial Foregoing's, or the one I made for my modpack)
