### ISSUE TITLE
Petal apothecary removes enchantments off bucket when bucket is dropped on top.

### ISSUE THREAD

**Issue by garyyo** [Vazkii/Botania#3623]
# Version Information
Forge version:  35.1.28
Botania version:  1.16.4-411

# Further Information
The petal apothecary will take a bucket with infinity (courtesy of quark) and remove that enchantment if that bucket is dropped on top of the petal apothecary. (Also when i picked it back up i had +1 bucket in my inventory but it was a ghost +1 bucket. this is mostly unrelated)

What I expected to happen:
to get my silly enchanted bucket back

What happened instead:
regular bucket

**Comment by williewillus** [comment]
So the apothecary just uses forge's code to drain the fluid out of the bucket, and that code overwrites the stack without copying the existing nbt data. There's not really a way that botania can fix this in a reliable way.

**Comment by williewillus** [comment]
this is a forge bug
