### ISSUE TITLE
Crash when rannuncarpus tries to place storage drawer with contents

### ISSUE THREAD

**Issue by Goldenlion5648** [Vazkii/Botania#3625]
# Version Information
Forge version:  35.1.13
Botania version:  1.16.3-409

# Further Information
Link to crash log: https://gist.github.com/Goldenlion5648/df610111c3f1492ee0b36bef598e6e41
Steps to reproduce:
1. place a rannuncarpus
2. Drop a storage drawer with items inside on the ground
3. Crash

What I expected to happen: I expected the drawers to be placed (I happened to break the drawers near the rannuncarpus)

What happened instead: The game crashed

**Comment by Hubry** [comment]
Update to 1.16.4-410 or later, Storage Drawers is blacklisted from placing for this exact reason.
