### ISSUE TITLE
Change Solegnolia's Ability

### ISSUE THREAD

**Issue by tyler489** [Vazkii/Botania#3627]
I asked Mekanism to add compatibility for their magnets to the Solegnolia's magnet blocking ability. They replied that they will NOT be adding this as "they already support vanilla's no pickup flags" if possible please change solegnolia to use this behavior.
See https://github.com/mekanism/Mekanism-Feature-Requests/issues/177#issuecomment-767627407

**Comment by telemenar** [comment]
I think this is unlikely to be easy to add without significantly changing the way that things work.

Their armor just extends your pickup range, where as the magnet moves items from far away into your pick up range.

Then the Solegnolia is hard coded into the Magnet Ring where before moving an item it checks if you or the item are within range of the solegnolia and if you it won’t move the item.

If you walk up to an item to pick it up like vanilla it works with the magnet ring, however if you made this change that would no longer work.
