### ISSUE TITLE
Tiny Planet (Block) and Pulse Mana Spreader Interaction

### ISSUE THREAD

**Issue by Jakem721** [Vazkii/Botania#3628]
# Version Information
Forge version:  35.1.13
Botania version: 1.16.4-1.5.0

# Further Information
Steps to reproduce:
1. Place tiny planet within 8 blocks of a pulse mana spreader. 
2. Activate spreader 
3. Have particles turned on

What I expected to happen:
The mana burst to travel normal until it approaches the tiny planet, at which point the vector will change and begin orbiting the planet. 
What happened instead:
Once mana spreader is activated, the burst is instantly teleported within 1 block horizontally (same height as tiny planet block), where it then begins orbiting as expected.
Playing the 1.16.4 garden of glass modpack
https://www.curseforge.com/minecraft/modpacks/garden-of-glass-questbook-edition
I will begin disabling other mods and testing it.

**Comment by Jakem721** [comment]
Tested with same version of Botania, forge, and garden of glass, and the interaction is still the same. Mana bursts are teleported to tiny planet, where they begin to orbit normally.
Disabled garden of glass and interaction persisted. 
Also tested with normal mana spreader, elven, and gaia. All spreaders have their bursts teleported instantly to tiny planet. 
Doesn't even hit the mana pool. 
![image](https://user-images.githubusercontent.com/48389192/106147548-fa9a8380-6145-11eb-85d2-91c0748253d6.png)

**Comment by williewillus** [comment]
can you show a video or gif?

**Comment by Jakem721** [comment]
Now that I'm testing this in previous versions, it seems I'm dumb. I think I got the way tiny planet works with how influence lens work. I'll close this now.
