### ISSUE TITLE
[1.16.4] Crashed with latest forge

### ISSUE THREAD

**Issue by KuroeIzukii** [Vazkii/Botania#3633]
# Version Information
Forge version:  1.16.4-35.1.37
Botania version:  1.16.4-411

# Further Information
Link to crash log: [gist](https://gist.github.com/KuroeIzukii/8ce04f743194b9a2ab87f6cf329e0920)
Steps to reproduce:
1. Open creative inventory or Botania guide book
2. Scroll the pane

What I expected to happen:

What happened instead: Crashed

**Comment by williewillus** [comment]
get rid of optifine

**Comment by KuroeIzukii** [comment]
> get rid of optifine

The problem exists everytime when i run it with forge 35.1.36, and it sometimes occurs with forge 35.1.37 (Only botania itself installed).

**Comment by williewillus** [comment]
Upload a new log without optifine installed, then

**Comment by ahdg6** [comment]
#3647 I think it's the same problem

**Comment by ahdg6** [comment]
When Pylon was rendered as an item,the game would crash.

**Comment by williewillus** [comment]
let's fold this one into 3647 then
