### ISSUE TITLE
[1.16] Luminizer glow is an ugly square

### ISSUE THREAD

**Issue by aaronhowser1** [Vazkii/Botania#3638]
# Version Information
Forge version:  36.0.13
Botania version:  Botania-1.16.4-411

![image](https://user-images.githubusercontent.com/15698722/106664064-341a2700-656a-11eb-873d-60229e1ce5af.png)
![image](https://user-images.githubusercontent.com/15698722/106664101-3c726200-656a-11eb-9087-0f6730892b05.png)

**Comment by williewillus** [comment]
not sure why this happens tbh

**Comment by aaronhowser1** [comment]
Could be the glow texture is only being overlaid on the spark texture, so it's stopping at its edges?

**Comment by williewillus** [comment]
I think it's the glow shader, actually.
