### ISSUE TITLE
Rannucarpus respects block orientation?

### ISSUE THREAD

**Issue by nucleiclight** [Vazkii/Botania#3642]
# Version Information
Forge version:  35.1.37
Botania version:  1.16.4-411

# Further Information
No crash, unexplained/unexpected behaviour  
Steps to reproduce:
1. Place white Terracotta block down facing south (such that the quarter circle is in the upper left)
2. Place dirt on top of white terracotta block from step one
3. On the same Z-Plane as the dirt in step 2, place additional white terracotta blocks in various orientations (south, north, east, west), within 4 blocks of the dirt block from step 2
4. Place Rannucarpus on dirt block from step 2
5. Drop 64 Oak Logs on Rannucarpus
6. Wait for Rannucarpus to place Oak Logs
See https://imgur.com/a/49nM9bj for visual

What I expected to happen:
Oak logs to be place on each Terracotta block

What happened instead:
Oak logs placed on Terracotta blocks matching orientation of Rannucarpus target terracotta block

**Comment by williewillus** [comment]
The rannuncarpus does an exact blockstate match for filtering, so this is intended.

Not sure if we should switch this to a block match now that things are flattened. It might break some contraptions if we change it.

**Comment by nucleiclight** [comment]
Ah, that explains it.  Thank you.
