### ISSUE TITLE
[1.16.5][Bug] Orechid spawns Nether gold ore from stone

### ISSUE THREAD

**Issue by FizzBuzz3000** [Vazkii/Botania#3644]
As stated in the title, the orechid can spawn nether gold ore, which should only be an orechid ignum thing.

[Image for reference, the orechid is hiding behind the manaspreader up top.](https://cdn.discordapp.com/attachments/801591103375015957/808050291336544298/unknown.png)

**Comment by williewillus** [comment]
duplicate of #3593
