### ISSUE TITLE
Bug in translation

### ISSUE THREAD

**Issue by serj1980** [Vazkii/Botania#3646]
Please remove from \assets\botania\lang\ru_ru.json lines started with 
`"": `
(2 lines)
These lines corrupt translation in multiple not related to your mod places.

**Comment by williewillus** [comment]
can you link which line numbers exactly?

**Comment by pgkrol** [comment]
That was before last fix: 
414
![image](https://user-images.githubusercontent.com/61147081/107625035-ca3a0580-6c6c-11eb-92d9-0d12b08161e2.png)
2224
![image](https://user-images.githubusercontent.com/61147081/107625131-eb9af180-6c6c-11eb-9704-c5c710c0981f.png)

I'm so sorry that I' m not adding a new translation, but I'm working on it. Unfortunately, there is a lot of work in the office right now.

**Comment by serj1980** [comment]
> That was before last fix:
> 414
> ![image](https://user-images.githubusercontent.com/61147081/107625035-ca3a0580-6c6c-11eb-92d9-0d12b08161e2.png)
> 2224
> ![image](https://user-images.githubusercontent.com/61147081/107625131-eb9af180-6c6c-11eb-9704-c5c710c0981f.png)
> 
> I'm so sorry that I' m not adding a new translation, but I'm working on it. Unfortunately, there is a lot of work in the office right now.

Yes. These lines corrupt translation at all. I has tried to remove it locally and this fix many places with UI for me.
If you don't have translation better skip resource and user can see English text.

Thank you.

**Comment by Hubry** [comment]
Seems like you are reporting something that is already fixed in #3624, and there are no other instances of this remaining that I can find. Next release will include this fix.
