### ISSUE TITLE
[Fabric] Manasteel tools doesn't break modded ores

### ISSUE THREAD

**Issue by Fogrits** [Vazkii/Botania#3648]
https://user-images.githubusercontent.com/14002834/107176546-713d4980-69ae-11eb-802d-4b0821fa2636.mp4

PS: these three ores can be broken with a stone pickaxe.

**Comment by williewillus** [comment]
please report it to https://github.com/williewillus/botania-fabric-issues/

also, I hope this isn't being used for anything serious yet, it's not ready
