### ISSUE TITLE
[1.16.5][Bug] Hydrogenias vore waterlogged blocks if the < 2 source blocks requirement is met

### ISSUE THREAD

**Issue by FizzBuzz3000** [Vazkii/Botania#3651]
The hydrogenias will delete waterlogged blocks and replace the block with air instead of removing the water from the waterlogged block, if the < 2 source block requirement is met.

**Comment by williewillus** [comment]
concen

**Comment by williewillus** [comment]
61becdd3f5a5fc4157dcc028cc79bb7fa3b42e5c
