### ISSUE TITLE
Mana and items goes away

### ISSUE THREAD

**Issue by AmsterDamian** [Vazkii/Botania#3653]
When I have an mana pool filled with mana sometimes when I drop an tablet in the pool the arrow starts switching sides. Also for example you have an 1/4 mana pool filled so you would get 1/2 tablet full, I get like 3 tablets full of "fake" mana. If I drop the "full" tablets in an other pool it starts glitching again.
I have almost the same thing with the Petal Apothecary. I dropped items in them, they dissapeared and I couldn't make the flower (Entropinnyum) and the items dissapeared.

https://user-images.githubusercontent.com/78864184/107528890-9c948400-6bba-11eb-99ec-7f53c7695d33.mp4

**Comment by FullMetalMaster** [comment]
also have this issue on my server with the lastest version apparently you can't put mana into a tablet or ring

**Comment by RevenantWendigo** [comment]
My friend is experiencing the same issue on Enigmatica 6 0.4.1
