### ISSUE TITLE
Visual bug with altar rituals

### ISSUE THREAD

**Issue by PuppyVenom** [Vazkii/Botania#3656]
# Version Information
Forge version:  36.0.14
Botania version:  1.16.4-411

# Further Information
Steps to reproduce: 
1. Put any recipe in a runic altar, receiving mana or otherwise
2. Look at it outside of F1 mode (ie: with hand or tool out)

What I expected to happen: The hud to show progress of the ritual
What happened instead: The world disappears

![2021-02-11_16 01 56](https://user-images.githubusercontent.com/9993238/107715928-1bee8a00-6c85-11eb-98ad-f4f974e066e6.png)
![2021-02-11_16 01 53](https://user-images.githubusercontent.com/9993238/107715930-1c872080-6c85-11eb-833a-fa7fca68dc1d.png)

**Comment by Hubry** [comment]
Known conflict with Immersive Portals.

**Comment by PuppyVenom** [comment]
Did the trick, thanks! Shame, neat mod.

**Comment by PandaBoy444** [comment]
Hi, are there plans to make them compatible somehow? this is really a problem

**Comment by williewillus** [comment]
No, unless someone does detailed research and comes up with the root cause. We aren't doing anything particularly hacky in our rendering, so it's probably on Immersive Portals' more invasive changes. But we have no idea how that mod works, so it's hard to investigate.

**Comment by PandaBoy444** [comment]
Maybe for now a config option to disable fancy rendering That conflicts?
