### ISSUE TITLE
ID error of dragonstone 

### ISSUE THREAD

**Issue by Celophy** [Vazkii/Botania#3662]
The id of the Dragonstone conflicts with that of the netherrocks mod (a simpleores addon), and can be used in the same crafting recipes.

using lastest version and 1.16.5

**Comment by williewillus** [comment]
what do you mean. Item IDs are prefixed by the mod name, so it's `botania:dragonstone` and does not conflict with anything else.

**Comment by Celophy** [comment]
sorry, i mean the forge tag

**Comment by williewillus** [comment]
That's the point of the tag, to share items with other materials with the same name. Though I guess I question whether it's helpful in this case.

**Comment by Celophy** [comment]
i was making a modpack and i can't find a way to remove it myself, but it is not so important, I was just reporting the problem

**Comment by williewillus** [comment]
you can override the tag with `replace: true` to set what you want explicitly. See https://minecraft.gamepedia.com/Tags
