### ISSUE TITLE
CraftTweaker / Orechid support

### ISSUE THREAD

**Issue by SevereOverfl0w** [Vazkii/Botania#3667]
I would like to tweak the orechid to:
* Disable a nether ore it is spawning in the overworld
* Add a nether ore to the ignem (although haven't tested whether the aforementioned block is there or not already)
* Disable a duplicate ore that from a mod that I've decided is not the canonical block

CraftTweaker support for the orechid would enable this.

**Comment by Paperweight82** [comment]
i think related to this, undergarden diamond ore from The Undergarden mod is being generated by the orechid flower (playing DW20 1.16), but the weight lens doesn't affect it (it has mining level: obsidian). would be good to be able to remove this ore from spawning by the orechid so farms using this method don't break
