### ISSUE TITLE
High MSPT in chunkSave()

### ISSUE THREAD

**Issue by kosma** [Vazkii/Botania#3669]
# Version Information
Forge version: forge-1.16.5-36.0.10.jar  
Botania version: Botania-1.16.4-411.jar
Modpack: Enigmatica E6 0.3.13

# Further Information

Link to profiler results: https://spark.lucko.me/#5Eiq3Gm58m

While investigating possible sources of lag I came upon an unexplained 20 mspt when idle. Profiling led me to Botania using about 25% of tick time (12.5ms) for something related to calling getChunk() inside chunkSave(). The way I can reproduce it on my server is simply:

1. Restart the server, wait until TPS stabilizes to around 20-25
2. Run the profiler over rcon, with no players online.

Sadly this is a rather big modpack, so I am completely lost in terms of possible causes, or possible solutions.

**Comment by williewillus** [comment]
Can you post a screenshot of the trace expanded to the spot where Botania appears? I'm not really sure where you're referring to.

**Comment by williewillus** [comment]
Nvm, I found it. This is related to #3140

**Comment by kosma** [comment]
Posting a screenshot to make life easier for everyone looking at the task. Mappings are MCP 1.16.4.

![image](https://user-images.githubusercontent.com/1089580/108423065-aad84500-7237-11eb-83a7-dd2f9a527f0e.png)

**Comment by kosma** [comment]
I'm gonna try Botania-1.16.4-411.jar with this patch cherry-picked and see if things improve. Will get back to you on this.

**Comment by kosma** [comment]
Issue is resolved, now a nice 1 mspt in idle. Thanks a lot!
