### ISSUE TITLE
Crash on launch with B3M mod installed

### ISSUE THREAD

**Issue by kellixon** [Vazkii/Botania#3670]
Forge version:  1.16.5-36.0.42
Botania version:  r411

Steps to reproduce:
Link to crash log: https://gist.github.com/kellixon/2e08cec3eb42f5fa26b2c9db26bfeb10
1. Without botany, everything runs great
2. After adding the mod, the game crashes at startup
3. I have been waiting for a solution to the problem for six months, and I can not play with this mod. What should I do? Where to dig, who to write to?

What I expected to happen:
-normal launch before the game menu
What happened instead:
-crash at the beginning of loading the game

**Comment by Hubry** [comment]
>I have been waiting for a solution to the problem for six months

If we don't know about a problem, how can we fix it?

This looks like a mod compatibility error. Can you add `-Dmixin.dumpTargetOnFailure=true` to Java arguments, zip up the exported class from `.mixin.out/classes` and attach it here?

**Comment by kellixon** [comment]
[class.zip](https://github.com/Vazkii/Botania/files/6030403/class.zip)

**Comment by Hubry** [comment]
Thanks! Looks like it's a conflict with this mod: https://www.curseforge.com/minecraft/mc-mods/time-speed-mod. 
Looks like [this was already reported to them](https://www.curseforge.com/minecraft/mc-mods/time-speed-mod/issues/10). The most we can do is make this injection not required so it doesn't crash.

**Comment by kellixon** [comment]
Yes, yes, yes. And another my +4 mods (CraftingStation+ExtraTags, Inspirations+Mantle) also started without B3M, which previously crashed with the same error at startup!!!
