### ISSUE TITLE
Lexica Botania breaks with custom Runic Altar recipes

### ISSUE THREAD

**Issue by Wxrlds** [Vazkii/Botania#3671]
# Version Information
Forge version:  36.0.42
Botania version:  Botania-1.16.4-411

# Further Information
Link to log (game does not crash): https://gist.github.com/Wxrlds/491ce1be0dcf164b58b4b2ec4ed021cb
Steps to reproduce:
1. Install CraftTweaker
2. Make a CraftTweaker Script with these recipe changes:
``<recipetype:botania:runic_altar>.removeRecipe(<item:botania:rune_earth>);``
``<recipetype:botania:runic_altar>.addRecipe("botania/runic_altar/rune/earth", <item:botania:rune_earth> * 2, 5200, <tag:items:forge:dusts/mana>, <item:minecraft:gold_ingot>, <tag:items:forge:stone>, <item:minecraft:coal_block>, <item:minecraft:brown_mushroom>|<item:minecraft:red_mushroom>);``
(The recipe replaces Mana Steel with Gold)
3. Restart the game or Save and Quit to the Title and join the world again (``/reload`` does not work)
4. Open Lexica Botania and see a loading error on the first page. Now most pages of the Lexica are broken

What I expected to happen:
Lexica Botania loads all pages normally (and maybe changes the changed recipe in the Lexica)

What happened instead:
Lexica does not load most pages and shows an error message (can be found in line 2536 in the log)

**Comment by Hubry** [comment]
I think you are able to provide an extension book to override the invalid entries as a workaround, but detecting crafttweaked recipes of the same type is something Patchouli does for vanilla recipes... and not loading if one is missing is a bug, yeah.

**Comment by Hubry** [comment]
When the next build is out, you will be able to define this recipe with name `runic_altar/earth` and have it automatically picked up.
