### ISSUE TITLE
[1.16.4] Hovering Hourglass locked message displays twice per click.

### ISSUE THREAD

**Issue by Jkosio23** [Vazkii/Botania#3672]
# Version Information
Forge version:  35.1.37
Botania version:  6.0.17

Steps to reproduce:
1. Place Hovering Hourglass.
2. Fill with sand.
3. Lock Hourglass
4. Right click.

What I expected to happen:
The message "This Hourglass is locked. Right-click it with a Wand of the Forest to unlock it." appearing in chat once.
What happened instead:
The message appears twice per click.

**Comment by Jkosio23** [comment]
Wow, this was a really really quick and easy fix, nice job pinpointing it!

**Comment by Hubry** [comment]
Eh, this type of stuff was fairly common at one point, and it's trivial compared to some stuff that needs a good rewrite to fix...
