### ISSUE TITLE
Rod of the Plentiful Mantle not showing particles in Fabric 1.16.5

### ISSUE THREAD

**Issue by BenCat07** [Vazkii/Botania#3674]
Just like the title says, the Rod is not spawning any particles on rightclick, even with ores right next to me. This should probably be looked into.

**Comment by BenCat07** [comment]
Actually seems this is intentional as of right now, looked at the code to find an `if (false)` in there.

**Comment by Hubry** [comment]
Fabric issues go to https://github.com/williewillus/botania-fabric-issues/issues currently.
