### ISSUE TITLE
[1.16] Terrasteel has no recipe in JEI

### ISSUE THREAD

**Issue by aaronhowser1** [Vazkii/Botania#3676]
# Version Information
Forge version:  36.0.40
Botania version:  Botania-1.16.4-411

![image](https://user-images.githubusercontent.com/15698722/110110932-29270200-7d75-11eb-8124-949586c5ef3e.png)

**Comment by aaronhowser1** [comment]
The plate works fine, I just can't see it in JEI

**Comment by Hubry** [comment]
Yes, we know, that's why I did this less than a week ago! 

a40dc1a69b5e2d49c269a499f43b94929b5a08fe

![image](https://cdn.discordapp.com/attachments/666785671481917459/815344582778683392/unknown.png)
