### ISSUE TITLE
Crash on rendering tiny potato with non-latin characters in name

### ISSUE THREAD

**Issue by frank89722** [Vazkii/Botania#3681]
# Version Information
Forge version:  36.0.46
Botania version:  1.16.4-413

# Further Information
Link to crash log: https://gist.github.com/frank89722/cccc7a74adac53c61f76adfe46b6418e
Steps to reproduce:
1. Switch to zh_tw lang mode
2. Open Lexica Botania or try to open any GUI showing tiny potato
3. Crash

What I expected to happen: Potato

What happened instead: Crash

**Comment by Hubry** [comment]
@eutro nice

I guess a hotfix for this is needed...
