### ISSUE TITLE
Ring of correction does not have in count hoes

### ISSUE THREAD

**Issue by LeoBeliik** [Vazkii/Botania#3683]
# Version Information
Forge version:  36.0.42
Botania version:  1.16.4-414

# Further Information
**Steps to reproduce:**
1. put the ring of correction
2. "mine" any block that uses hoe as default tool
3. observe

**What I expected to happen:**
tool in my main hand switches to a hoe

**What happened instead:**
it switches to other tools

*It also ignores shears*

https://user-images.githubusercontent.com/11804768/110966715-53a82a80-8334-11eb-8b85-cd1ab64f83e6.mp4

**Comment by Hubry** [comment]
blame my laziness, I literally looked at the ring code and just... forgot to do this?
