### ISSUE TITLE
Hydroangeas breaking instantly

### ISSUE THREAD

**Issue by Verquinox** [Vazkii/Botania#3689]
# Version Information
Forge version:  36.0.45
Botania version:  Botania-1.16.4-411

# Further Information
Link to crash log: No crash
Steps to reproduce: 
1. ???

What I expected to happen: I place the Hydroangeas, and it begins generating mana

What happened instead: I placed the Hydroangeas, and it instantly broke/died. I tried this several times with the same results. Prior to this, I had been placing Hydroangeas there with no problem and using them to generate mana. It seems to only happen on the exact blocks that I used to place them on; I can place Hydroangeas on the block right next to, above, and below the spot, but any time I place it there it dies. Prior to the issue arising, I had the Hydroangeas on vivid grass and instead of turning into dead bushes, they would just disappear.

Video of the issue:
https://user-images.githubusercontent.com/40919518/111700472-d38c3400-880f-11eb-9c01-4a73d526feca.mp4

**Comment by Hubry** [comment]
Please post a full console log and your list of mods (preferably a modpack link/CF export/etc.). I cannot reproduce this in a minimal environment.

**Comment by Verquinox** [comment]
As it turns out, the world I was playing on, and more specifically the area around my house, had somehow become corrupted. The issue stopped after a while and I haven't had any such issue since, but the world kept getting worse until it finally stopped loading entirely. In short, I'm pretty sure at this point that it was the world being in the early stages of corruption due to something else and not something to do with Botania. If you still want the modpack I can provide it.

My apologies and thank you for the trouble!
