### ISSUE TITLE
Key of the King's Law crashes the game on multiplayer server.

### ISSUE THREAD

**Issue by DinoPackYT** [Vazkii/Botania#3690]
I don't know what the issue is exactly, but me and my friend are playing a modpack, with botania. We were doing some Gaia Rituals and obtained the Key of the King's Law. It consistently crashes the game when used. My friend used the key to charge it to full, when he released the weapons, both of our games crashed.

**Comment by williewillus** [comment]
got a crash log and version info?

**Comment by DustyEh** [comment]
having same issue cant seem to grab crash report as it says could not render file whenever i try. worked fine for a few days and now crashes the game nothing was changes since then. version 1.16.4

**Comment by Hubry** [comment]
We cannot possibly diagnose the issue if you cannot obtain a crash report or a game console log.
