### ISSUE TITLE
Tiny potato hops less energetically :(((

### ISSUE THREAD

**Issue by SuicidalSteve** [Vazkii/Botania#3693]
# Version Information
Forge version: 35.1.7
Botania version: Compiled from master at 24-3-2021, 22:20 CET... So like right before making this issue-

# Further Information
1. Place tater
2. Pat tater
3. Cry

What I expected to happen:
Tater go jumpy left to right :)))))

What happened instead:
Tater go jumpy but only up and down :(((((

**Comment by eutro** [comment]
![](https://user-images.githubusercontent.com/11538216/112386573-09865800-8ce9-11eb-8a94-e280e74e25a0.png)
fwiw, I asked before changing it.
