### ISSUE TITLE
Crash Exception ticking world with the version Botania-1.16.4-414

### ISSUE THREAD

**Issue by SirDevil1213** [Vazkii/Botania#3697]
I got a crash not sure if this is because of Botania but the only thing I found in the crash is about MixinWorldEntitySpawner and Botania so I think this is because of botania otherwise I don't know and I would love to know. That happen to me when trying to go to the moon with the mod Space Bosstools and to one of my friend when going in a chunk.

Crash report about my friend in the chunk : https://pastebin.com/dmrxiy70
Crash report about going on the moon (other mod) : https://pastebin.com/KABxnxnA

Botania v.Botania-1.16.4-414

**Comment by williewillus** [comment]
Do you have mods that add natural-spawning mobs? That's more likely to be the cause than Botania, whose mixins are only to support the bloodthirst/emptiness effects.

**Comment by SirDevil1213** [comment]
I wasn't sure because I was only able to see that in the crash log something about botania, that's strange but thanks for the information, now I know probably witch mods is the cause of the crash.
