### ISSUE TITLE
Odd Interaction between Botania and Charm

### ISSUE THREAD

**Issue by Kaligraphy22** [Vazkii/Botania#3701]
# Version Information
Forge version:  1.16.4 forge 35.1.36
Botania version:  Botania 1.16.4 -11 and charm-forge-1.16.4-2.2.2 (see below)

# Further Information
Link to crash log: N/A

What I expected to happen/What happened instead::

Before I posted this, I checked to see if either mods' issue tracker mentioned this issue and I checked to see if either had updates that addressed this issue. Found nothing as of posting this.

So Charm adds a new villager type called the Beekeeper. The house for the Beekeeper has what you would expect - flowers, beehives and well, bees. The problem? I'm pretty sure craftable-only Boatnia flowers aren't supposed to generate with the Beekeeper's house. I think it's supposed to be just normal flowers that give dye like vanilla/BoP/ByG flowers. I've seen that windmill flower, the Dreadthorne, the Hopperhock and that one flower that disrupts Endermen teleportation. I would not be surprised if there were more. I wasn't sure whether to let you or Svenhjol know about this. All I think is that this is an odd interaction that probably shouldn't exist? I don't know which mod is responsible. If it's Charm, I'll remove this report from here and copy-paste it to Charm's issue tracker.

![2021-04-04_11 47 50](https://user-images.githubusercontent.com/72703227/113515715-d7bc8f00-953b-11eb-9e76-dc26b8d02d9a.png)
![2021-04-04_11 47 56](https://user-images.githubusercontent.com/72703227/113515718-dc814300-953b-11eb-9c61-8c36823c807e.png)
![2021-04-04_11 48 11](https://user-images.githubusercontent.com/72703227/113515722-e0ad6080-953b-11eb-98b8-88e5f46a6778.png)

**Comment by Hubry** [comment]
Charm pulls from the flower block tag, and we removed special flowers from it in build 413, update Botania.
