### ISSUE TITLE
Duplicating mana tablet

### ISSUE THREAD

**Issue by BookSerpent** [Vazkii/Botania#3705]
# Version Information
Forge version:  36.1.0
Botania version:  414

# Further Information
Steps to reproduce:
1. Have a band of aura in your inventory (I have only tested with an upgraded one)
2. Open your inventory
3. Shift-click on a mana tablet in your hotbar

What I expected to happen:
Mana tablet to go in to my main inventory
What happened instead:
Sometimes when I perform the steps above, (it is inconsistent) it puts two mana tablets into my main inventory, sometimes both appear to have the same amount of mana, and sometimes the duplicated one appears to be empty. The duplicated mana tablet disappears when clicked on.

**Comment by Hubry** [comment]
Classic desync when having mana generation, because changing NBT data often tends to do this. Probably best mitigated by making it create bigger mana packets more rarely rather than 1 mana every X ticks?

**Comment by Hubry** [comment]
This should make the desync a lot less likely, you might still hit it occasionally but it won't be nearly as reliable. It's probably not fixable without some bigger changes.
