### ISSUE TITLE
Some items can not be right-clicked/used into the altar unless placing conditions are met.

### ISSUE THREAD

**Issue by VoilaTada** [Vazkii/Botania#371]
When attempting to make Runes of Earth I was having trouble getting the Runic Altar to take the mushroom from my hand via my use item/place block key (mouse right click/button 2 by default). The Alter had no problems taking the item if it could be placed on the block adjacent to the altar, however, since mushrooms can not be planted in the light on grass, I was unable to get the altar to take the mushroom with torches nearby. Only after removing the nearby torches and creating some shade above the altar, could I get the altar to take the mushroom from my use/place key. This occurs with both types of mushrooms and occurs with other items with placing restrictions such as saplings requiring dirt variants under them; however Redstone successfully places into the altar, even when the block it would be placed upon is glass, which normally can not have Redstone placed on it.  Tossing items with the drop key or throwing them out of one's inventory onto the altar works to get them in the altar, even if they can't be placed on nearby blocks. The forge mod loader client log does not record anything about the Runic Altar, whether items are placed within it successfully or not.

**Comment by jawdylawdy** [comment]
I've had this problem too, but I believe Vazkii added the ability to just drop items onto the altar (along with a few of her other crafting blocks) and have them work that way. Just do that instead.

**Comment by VoilaTada** [comment]
That is indeed a workaround for the issue, but ideally both should work for usability's sake. Some people prefer not to drop items in the world whenever possible and right clicking works for many other devices in Minecraft, making it feel natural to do so.

**Comment by Vazkii** [comment]
Any updates on this? I haven't come across it.

**Comment by VoilaTada** [comment]
It seems to be fixed in more recent versions. I couldn't replicate it in build 169.

**Comment by YoruToboe** [comment]
I haven't came across this problem anymore. . . Seems right for me

**Comment by Vazkii** [comment]
Closing since I haven't heard of it still happening.
