### ISSUE TITLE
Raindeltia not producing mana

### ISSUE THREAD

**Issue by JeffsRealm** [Vazkii/Botania#3712]
# Version Information
Forge version:  FTB Presents Direwolf20 1.16 version 1.9.0
Botania version:  1.16.4-414.jar

# Further Information
Steps to reproduce:
1. Make a Raindeltia wait for rain

What I expected to happen:  From the description it is supposed to produce mana passively from the rain? There is not a whole of information so I am just assuming like all others plant it, It auto bound to my elvish mana spreader.  It has clear view of the sky and it started raining.  I actually had 2 of them there as it is a new to me flower never used before so didn't know what to expect.
![2021-04-19_17 07 47](https://user-images.githubusercontent.com/25747811/115304660-333d6e00-a133-11eb-888e-19175bfcc6e4.png)

What happened instead: Nothing.  No mana was produce I watched the mana spreader, the mana level in it never increased and it never fired.

**Comment by Alwinfy** [comment]
We regret to inform you that the Raindeltia is not, in fact, in baseline Botania. Please direct your issues to [MythicBotany](https://github.com/noeppi-noeppi/MythicBotany/issues).

**Comment by JeffsRealm** [comment]
Ok thanks, sorry for the confusion
