### ISSUE TITLE
[1.16.5] Orechid recipe system can only add, not change or remove

### ISSUE THREAD

**Issue by NillerMedDild** [Vazkii/Botania#3713]
Forge version:  1.16.5-36.1.4
Botania version: 1.16.5-415 

# Further Information
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)\
Steps to reproduce:
1. Add a datapack with a `botania:orechid_ore_weights/orechid.json` file setting orechid recipes to something else.
2. Observe that it does not remove old values

What I expected to happen:
Orechid recipe system to allow removing existing values by not including them in new file

What happened instead:
Old values persist

**Comment by Hubry** [comment]
Crafttweaker bindings have removal, I'll add json soon.

**Comment by NillerMedDild** [comment]
Thanks!

**Comment by Winddbourne** [comment]
Could you explain how to use Crafttweaker to remove ores? I was looking at it's wiki and the information there seems to be outdated when applied to 1.16.4.  I still tried it even though they were talking about ore dictionary rather than tags but it returned an error. 

I'd really like to stop the orechid from generating prosperity ore from Mystical Agriculture. It's kind of OP.

**Comment by Hubry** [comment]
Everything is in [this class](https://github.com/Vazkii/Botania/blob/master/src/main/java/vazkii/botania/common/integration/crafttweaker/OrechidManager.java), I will write some docs for CT soonish.

The gist of it: 
```zenscript
var orechid = mods.botania.Orechid.main;
var nether = mods.botania.Orechid.nether; // this one for the Orechid Ignem

orechid.clear(); // clears the list
orechid.removeOreWeight(<blockstate:minecraft:diamond_ore>);
orechid.registerOreWeight(<tag:blocks:minecraft:stone_bricks>, 250);
orechid.registerOreWeight(<block:minecraft:dirt>, 250);
orechid.registerOreWeight(<blockstate:minecraft:red_sand>, 250);
```

There are some improvements to add (like a dump of all the values), but this is the basics.

**Comment by Winddbourne** [comment]
Thanks I'll fiddle with this and see if I can get it to work, and I'm going to look forward to that documentation. :)

**Comment by Winddbourne** [comment]
Mt Hand gave me the block state, and I kept the dirt and red sand for fun but . . . Nope. This is what I got. 

![nope](https://user-images.githubusercontent.com/24589533/116816780-5e5f8e80-ab31-11eb-96bf-4098dba4943e.png)

**Comment by Hubry** [comment]
Post your script and exact versions. (Also if you wouldn't mind, let's continue this on Vazkii's discord because I kinda don't want to flood this place with support)

**Comment by Winddbourne** [comment]
Good idea. I'll head over there now.

**Comment by Hubry** [comment]
@NillerMedDild Finally got around to this. [The Javadoc comment](https://github.com/Vazkii/Botania/blob/master/src/main/java/vazkii/botania/common/core/handler/OrechidResourceListener.java#L51-L66) should give you an idea of how it will work once we release the build, and here is a sample, which removes the default coal ore and adds some redunant gold ore spawns (though I imagine you will `"replace": true` instead).
```json
{
  "replace": false,
  "remove": [
    {
      "type": "block",
      "block": "minecraft:coal_ore"
    }
  ],
  "values": [
    {
      "type": "block",
      "block": "minecraft:gold_ore",
      "weight": 50000
    }
  ]
}
```

**Comment by NillerMedDild** [comment]
Perfect, just what we need :D thanks!

**Comment by NillerMedDild** [comment]
Worked like a charm through a datapack, but KubeJS still can't change it for some reason, no big deal though. Thanks again!
