### ISSUE TITLE
[Request] Debug command to reduce/remove cooldowns on rods

### ISSUE THREAD

**Issue by thenewdreamer** [Vazkii/Botania#3714]
Rods with long cooldowns (like Hells and Bifrost) are absolute agony to test repeatedly because of all the waiting

![image](https://user-images.githubusercontent.com/45403659/115457112-056b2e80-a1f2-11eb-8971-ef4b54c135c6.png)

**Comment by williewillus** [comment]
just make it not set the cooldown in creative
