### ISSUE TITLE
Clayconia does not react to redstone signal, unlike other block converting flowers

### ISSUE THREAD

**Issue by TheRealWormbo** [Vazkii/Botania#3717]
# Version Information
Forge version:  36.1.0
Botania version:  1.16.4-414

# Further Information
Steps to reproduce:
1. Place Clayconia flower.
2. Place a bunch of sand blocks.
3. Apply a redstone signal to the Clayconia, e.g. using a lever.

What I expected to happen: 
* The Clayconia should stop converting sand blocks, similar to how e.g. Orechid and Marimorphosis stop converting stone blocks.

What happened instead:
* The Clayconia continues converting blocks as long as it has mana and finds nearby sand blocks.

**Comment by Hubry** [comment]
It doesn't have a redstone root in the recipe, so it doesn't get affected by redstone.

**Comment by TheRealWormbo** [comment]
I see. That's unfortunate and it feels inconsistent as far as the usage goes.
