### ISSUE TITLE
Runic Altar makes the world see-through

### ISSUE THREAD

**Issue by Galphanore** [Vazkii/Botania#3719]
# Version Information
Forge version:  36.1.4
Botania version:  1.16.4-414
Modpack: Direwolf20 1.9.0 (the version that released a few days ago), with "Immersive Portals" and "Create Additions) added to it.

# Further Information
Link to crash log: Not crashing
Steps to reproduce: 
1. Place Runic Altar
2. Add ingredients
3. Look at Altar

What I expected to happen: Shows the animation of the ingredients being charged and a UI indicating when it is done.

What happened instead: As expected, plus the entire world goes transparent and I can see underground caves.

Before adding last ingredient: 
![Before adding last ingredient](https://user-images.githubusercontent.com/4059786/115882217-8efd4500-a41a-11eb-8500-a26f3117565c.png)

After adding last ingredient: 
![After adding last ingredient](https://user-images.githubusercontent.com/4059786/115882259-96bce980-a41a-11eb-9567-8dc5572deab7.png)

At first I thought this might be because I was doing this on a platform above a lake, but I replicated it in a desert in creative as well: 
![Desert not looking](https://user-images.githubusercontent.com/4059786/115882738-0e8b1400-a41b-11eb-8d6b-7a3d0b5b8012.png)
![Desert After](https://user-images.githubusercontent.com/4059786/115882733-0df27d80-a41b-11eb-93d6-fe2db344bcf6.png)

**Comment by Hubry** [comment]
Immersive Portals? Well, that's your culprit right there. Known compat issue.

**Comment by Galphanore** [comment]
> Immersive Portals? Well, that's your culprit right there. Known compat issue.

Yep, that was it. Removed immersive portals and no more issues. I'm gonna just leave it out after this. It's a cool mod but it has soooo many compatibility issues.
