### ISSUE TITLE
something causing crash

### ISSUE THREAD

**Issue by Parciwal** [Vazkii/Botania#3720]
-->
# Version Information
Forge version:  36.1.0
Botania version:  Botania-1.16.4-414.jar

# Further Information
Link to crash log:(https://gist.github.com/Parciwal/910a48524564b34a58344c00da254749)
Steps to reproduce:
1. get a server running
2. craft the Flügel Tiara
3. put it in the head slot with a skin, that is not standard

What I expected to happen:
work without problems

What happened instead:
i get Kicked with he Message:
"Internal Exception: io.netty.handler.codec.DecoderException: java.lang.RuntimeException: Tried to read NBT tag that was too big; tried to allocate: 2097190bytes where max allowed: 2097152

I can only join after the server restartet and there is a chance that i get instantly kicked again.

**Comment by williewillus** [comment]
try with just your skin + botania (no other mods)

**Comment by Parciwal** [comment]
it doesnt seem to be the flügel of tiara, I don't know what it is, i will test by removing mods, just hold on for a bit, if it isn't botania, i will close this issue

**Comment by Parciwal** [comment]
false alarm, i saw a connection where there was none, i still don't know there the problem comes from, but it is now gone
