### ISSUE TITLE
Thermalily with cooldown consumes lava before Thermalily without cooldown

### ISSUE THREAD

**Issue by Charismara** [Vazkii/Botania#3721]
# Version Information
Forge version:  1.16.5-36.1.9
Botania version:  1.16.5-415

# Further Information
Link to crash log: none
Steps to reproduce:
1. Place Fluid Placer 
2. Place Thermalily 4 around
3. Wait until they all consume lava one time

What I expected to happen:
All 4 Thermaliliy cooldown and consume lava again.

What happened instead:
3 Thermaliliy cooldown and 1 consume the lava again and again while the other lilies can't take their shot :(

**Comment by williewillus** [comment]
Semi-intended, the order in which flowers of the same type is unspecified (the lexicon talks about this). You probably want each flower to have it's own area for fluid input.

**Comment by Charismara** [comment]
Well, if this is intended i need to change my setup there. Thanks anyway :)
