### ISSUE TITLE
Rod of the Shifting Crust L-click does not instantly replace blocks.

### ISSUE THREAD

**Issue by The-Arcanian** [Vazkii/Botania#3722]
Forge version:  36.1.2
Botania version: 1.16.5-415

Steps to reproduce:
1. Select a replacement block with Rod of the Shifting Crust.
2. L-click a block to see that nothing happens.
3. Hold LMB until block brakes and gets replaced with the replacement block.

What I expected to happen: L-click with the Rod of the Shifting Crust to instantly replace the target block.

What happened instead: LMB must be held until target block brakes to replace it.

**Comment by Hubry** [comment]
Uh, I swear I tested this fully. Why do I always forget to check some crucial thing fully?
