### ISSUE TITLE
Crash during binding

### ISSUE THREAD

**Issue by umifi** [Vazkii/Botania#3725]
Forge version:  36.1.13
Botania version:  1.16.5-415

Link to crash log: https://gist.github.com/VanyaGaming/83c2da57fd221d79dd79f035b7a86416

**Steps to reproduce:**
1. Planted Endoflame
2. Picked up Twig Wand
3. Right-clicked with the Shift key on Endoflame to bind it to Mana Spreader.

**What I expected to happen:**
Expected to bind Endoflame to Mana Spreader.

**What happened instead:**
Crash occurred instead of binding.

**Comment by Hubry** [comment]
I see Mohist, Optifine, Gravit... can you reproduce without any of these? Vanilla launcher, no optifine, plain Forge server. What modpack is this, too?

**Comment by Hubry** [comment]
Looks like we aren't getting any info here...
