### ISSUE TITLE
Fel pumpkin model is not rotated

### ISSUE THREAD

**Issue by IchHabeHunger54** [Vazkii/Botania#3727]
The fel pumpkin always uses the default model (facing north), instead of facing the correct direction.
It's an easy fix. This is literally carved_pumpkin.json, but with the fel pumpkin model.
And yes, I could PR this in, but I don't have the motivation to. I think copy-pasting one file is alright. :P

```
{"variants":{
  "facing=east":{"model":"botania:block/fel_pumpkin","y":90},
  "facing=north":{"model":"botania:block/fel_pumpkin"},
  "facing=south":{"model":"botania:block/fel_pumpkin","y":180},
  "facing=west":{"model":"botania:block/fel_pumpkin","y":270}
}}

**Comment by Hubry** [comment]
You'd have to edit the blockstate json datagen for this though :P
