### ISSUE TITLE
Conflict with Fuzs' Respawnable Animals causes server crash

### ISSUE THREAD

**Issue by TheGreatCatAdorer** [Vazkii/Botania#3728]
Forge version:  36.1.16
Botania version:  r-415

https://gist.github.com/TheGreatCatAdorer/cb807c32f8b700ad055075081108a7d1

**Comment by Hubry** [comment]
Please add `-Dmixin.debug.export=true` to your JVM run arguments, find and zip up the exported class `net.minecraft.world.spawner.WorldEntitySpawner` in .mixin.out/classes and attach it here. I'll look at it in a few hours.

**Comment by Hubry** [comment]
Cannot reproduce in dev. Please provide the full dump as said above, not just the one class.

**Comment by TheGreatCatAdorer** [comment]
Oddly, net.minecraft.world.spawner.WorldEntitySpawner is not in .mixin.out/classes/net/minecraft/world/spawner/WorldEntitySpawner.  Only AbstractSpawner.class is.

**Comment by TheGreatCatAdorer** [comment]
[AbstractSpawner.class.zip](https://github.com/Vazkii/Botania/files/6447546/AbstractSpawner.class.zip)

**Comment by TheGreatCatAdorer** [comment]
[mixin.out.class.zip](https://github.com/Vazkii/Botania/files/6447551/mixin.out.class.zip)

**Comment by TheGreatCatAdorer** [comment]
With world load: 
[mixin.out.class.zip](https://github.com/Vazkii/Botania/files/6447585/mixin.out.class.zip)

**Comment by Hubry** [comment]
I have absolutely no idea what is going on here. Looking at this stuff closer, it looks like something is modifying an entity passenger list while adding an entity with passengers to the world, and it shouldn't be affected by either Respawnable Animals or Botania as both of the mods' mixins don't touch that specific area.

I've been running the game for 50 minutes killing every single entity that spawns every tick (thanks, repeating command blocks) and have not hit this crash yet with just Respawnable Animals and Botania in my dev environment.

Feel free to open an issue with a more minimal mod list if you reproduce it, but it does not seem like our fault.
