### ISSUE TITLE
Cannot implement Botania as dependency in mod files.

### ISSUE THREAD

**Issue by rguy98** [Vazkii/Botania#3731]
# Version Information
Forge version: 1.16.5 - 36.1.16
Botania version:  1.16.5 - 4.16

# Further Information
Link to crash log: https://pastecode.io/s/1xiPjtgNy3
Steps to reproduce:
1. Use CurseMaven to import Botania as a dependency
2. Attempt to load the mod client-side

What I expected to happen: The game loads properly

What happened instead: The game crashes when attempting to load Botania

**Comment by Hubry** [comment]
Probably caused by your choice of using official mappings, looks like some conflicting names after deobf...

**Comment by Hubry** [comment]
That's gonna require a breaking API change, though I don't think any mod actually uses this. On official mappings, `EntityManaBurst` has two `getGravity` methods - the override of `IManaBurst#getGravity`, and the override of what is called `getGravityVelocity` on MCP mappings.

**Comment by rguy98** [comment]
What can I do to get around this issue without the API getting changed?

**Comment by williewillus** [comment]
use non-official mappings until we can change it

**Comment by Hubry** [comment]
Try using `1.16.5-417-SNAPSHOT` as the version if you are still hoping to get mojmap working.
