### ISSUE TITLE
Terra Shatterer doesn't mine while accepting mana from dispersive spark

### ISSUE THREAD

**Issue by corvaxl1** [Vazkii/Botania#3733]
# Version Information
Forge version:  36.1.0
Botania version:  1.16.5-416

# Further Information

Steps to reproduce:
1. Place spark over filled mana pool
2. Add dispersive spark augment 
3. Try to break a block using the shatterer while the dispersive spark is feeding you mana

What I expected to happen: Shatterer breaks block as any pickaxe normally would

What happened instead: block breaking progress constantly resets to 0%

Someone in discord also mentioned that the issue may be the fact that it is accepting mana in general? When the shatterer is in my inventory, my band of mana does not get refilled from the augmented spark. All the mana goes to the shatterer.

**Comment by Hubry** [comment]
2b6c514ebe96ffa356285c81eab3bf2468fdcc9a

I forgot about this issue and did this entirely because of discord convos :P
