### ISSUE TITLE
New Tags dont work with custom botania recipes

### ISSUE THREAD

**Issue by pafeuu** [Vazkii/Botania#3739]
# Version Information
Forge version: 36.1.24
Botania version:  1.16.5-416

Hello while doing some tweaking in my pack i noticed that it is impossible to create a pure daisy recipes using newly created tags. In link below there is full kubejs script for the recipe and new tag creation.

https://pastebin.com/56cHAvxt

**Comment by Hubry** [comment]
Uh, I see an issue. Are you sure you want to add to *item* tags for Pure Daisy recipes, which use *block* tags?

**Comment by pafeuu** [comment]
I had no idea there is a difference and I was talking to guys on kubejs discord and they didnt catch that either, Well sorry for the mistake then

**Comment by Hubry** [comment]
No need to be apologize, missing a little detail like this is far from unusual. I looked at this a few times in the past week and only realized today, too.
