### ISSUE TITLE
Botania and Agricraft startup conflict

### ISSUE THREAD

**Issue by MysticSticker** [Vazkii/Botania#3741]
# Version Information
Forge version: 1.16.5
Botania version: 1.16.5

# Further Information
Link to crash log: https://gist.github.com/MysticSticker/e7ca78496b0672848a41862a59095e9f
Steps to reproduce:
1. Download Botania 1.16.5 and Agricraft 1.16.5 with their respective other mods
2. Start Minecraft
3. Error message "AgriCraft (agricraft) encountered an error during the common_setup event phase"

What I expected to happen:
Minecraft loads
What happened instead:
Minecraft can not load

**Comment by Hubry** [comment]
Looks like @InfinityRaider already released the build using the API change they PRed in in #3735. Guess we should release a build already tbh.

**Comment by MysticSticker** [comment]
No rush! I can still play using both of your wonderful mods with no issue. Just wanted to let you know of the issue incase others ask about the same thing. :)

**Comment by aburone** [comment]
I get the same error with the new agricraft release

	Mod File: agricraft-3.0.1.jar
	Failure message: AgriCraft (agricraft) encountered an error during the common_setup event phase
		java.lang.NoSuchMethodError: 'void vazkii.botania.api.BotaniaAPI.registerHornHarvestableBlock(net.minecraft.util.ResourceLocation, vazkii.botania.api.item.IHornHarvestable)'
	Mod Version: 1.16.5-3.0.1
	Mod Issue URL: https://github.com/AgriCraft/AgriCraft/issues/
	Exception message: java.lang.NoSuchMethodError: 'void vazkii.botania.api.BotaniaAPI.registerHornHarvestableBlock(net.minecraft.util.ResourceLocation, vazkii.botania.api.item.IHornHarvestable)'
Stacktrace:

**Comment by InfinityRaider** [comment]
Yes, I was told I could just push it to force an update: https://github.com/Vazkii/Botania/pull/3735#issuecomment-849826740
Until Botania updates, the crash can be avoided by disabling compat in the config.
This can be closed tbh.

**Comment by AngleWyrm10** [comment]
[Workaround until this gets fixed](https://www.curseforge.com/minecraft/mc-mods/agricraft?comment=763):
change config file line (agricraft-client.toml) to "Enable Botania compat" = false

**Comment by Hubry** [comment]
Build 418 is out for a few days now, so closing this.
