### ISSUE TITLE
Rod of the Shaded Mesa dupes items

### ISSUE THREAD

**Issue by Bastian-5** [Vazkii/Botania#3743]
Note: this is somewhat difficult to recreate. I have no clue how I managed to do it by accident literally the first time I picked up any item with the rod of the shaded mesa. I accidentally dropped a bucket on the ground, realized I hadn't tested the rod 
# Version Information
Forge version:  36.1.23
Botania version:  Botania-1.16.5-416

# Further Information
1. Use the Rod of the Shaded Mesa on any item, holding it like any entity
2. walk towards a door, facing it
3. make sure that you collect the item at the same time that you open the door

In case any details I didn't mention are important, this was part of the Direwolf20 pack on a multiplayer server. The door was on the far side of the block and had a pressure plate on the near side. I was facing somewhat downwards, I can't remember exactly how far down I was looking. All I can say is that I picked up the second item really fast when I first discovered it. If I remember to later, I'll link to a video of the dupe being performed

What I expected to happen: either pick up the item or fire it

What happened instead: both, duping the item

Easiest Solution (hopefully short term): Blacklist items

**Comment by Hubry** [comment]
I'm gonna guess that replacing an item with the special thrown item doesn't test if the item is actually alive? I couldn't reproduce this at all, but maybe this will solve it.

Please grab a build from [Jared's maven](https://ci.blamejared.com/job/Botania/job/master/) and test if you can reproduce, all my attempts ended with failures.
