### ISSUE TITLE
Ars Nouveau's projectile spell with freeze crashes the game when hit a Botania's spark

### ISSUE THREAD

**Issue by Vearmus** [Vazkii/Botania#3748]
# Version Information
Forge version:  36.1.31
Botania version: 1.16.5-416 

# Further Information
Ars Nouveau version: 1.16.5-1.18.5
Steps to reproduce:
1. craft a spell with "projectile" and "freeze"
2. hit a spark

What I expected to happen:
nothing happened
What happened instead:
the game crashed
![QQ截图20210612203111](https://user-images.githubusercontent.com/47314691/121776065-7eb54b00-cbbd-11eb-99ae-1df1894e4153.png)
[crash-2021-06-12_20.22.01-server.txt](https://github.com/Vazkii/Botania/files/6642175/crash-2021-06-12_20.22.01-server.txt)

**Comment by williewillus** [comment]
Ars Nouveau bug, for the record. It seems to be assuming whatever it hits is living, which is not always the case.
