### ISSUE TITLE
The Dead coral fans can use to copy TNT and use on Entropinnyum

### ISSUE THREAD

**Issue by Cursed0Dragon** [Vazkii/Botania#3749]
# Version Information
Forge version:  After 1.14
Botania version:  After 1.14

# Further Information
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)\
Steps to reproduce:
1. First step by use old brush TNT machine but use Dead coral fans
2. Second step by place Dead coral fans under the TNT, it can copy in old way.

What I expected to happen: Remove this "characteristic" to make it can't be use on Entropinnyum

What happened instead: Player can use a easy way to get infinity mana

**Comment by Cursed0Dragon** [comment]
Sorry my expected to happen is wrong, my friend say it can be change to detect if the TNT is copied, then it only get extremely few mana for each. But normal TNT explosion does not affect.

**Comment by williewillus** [comment]
There's already a protection in place to block the simplest dupers. Doing anything more gets really complicated fast, and if a cheater wants to cheat they will anyways. There's also other mods that fix TNT duping, so if a server administrator is concerned they can install those mods.

Otherwise, bother Mojang to fix it. Botania isn't going to do anything further than what we already do.

**Comment by Cursed0Dragon** [comment]
Sir, my friend have few other questiones: The Entropinnyum minimum allowable explosion time for each Entropinnyum, or is their a form about these. 
Another question is: Is there a format or link about use date pack to modify composite of device like Petal Apothecary and Runic Altar.

**Comment by williewillus** [comment]
> The Entropinnyum minimum allowable explosion time for each Entropinnyum, or is their a form about these.

I'm not sure what you're asking about. The Entropinnyum can accept an explosion when it has no mana. There is no time limit, you just need to clear the mana fast enough.

>  In 1.16.5 version does there a format or link about use date pack to modify composite of device like Petal Apothecary and Runic Altar.

Look at Botania's own recipes as an example: 
* https://github.com/Vazkii/Botania/tree/master/src/generated/resources/data/botania/recipes/petal_apothecary
* * https://github.com/Vazkii/Botania/tree/master/src/generated/resources/data/botania/recipes/runic_altar
