### ISSUE TITLE
Eating Fruit of Grisaia with Dark Utilities Gluttony Charm doesn't work

### ISSUE THREAD

**Issue by JJSax** [Vazkii/Botania#3752]
# Version Information
Forge version:  36.1.18
Botania version:  416
Dark Utilities version: 8.0.9

# Further Information
Nothing posts in the log when it fails to eat.  It plays the eat animation and takes mana but no saturation is gained.   This only happens when you have Dark Utilities "Gluttony Charm" in your inventory.  I'm not sure if I should report to Botania or Dark Utilities. 

Steps to reproduce:
1. give/craft a Gluttony Charm (Dark Utilities)
2. Get a bound Fruit of Grisaia
3. try to eat it and notice you get no hunger
4. if you remove the charm you get the hunger as expected.

What I expected to happen:
I expect that the fruit would work basically work as it does without the gluttony charm.

What happened instead:
No hunger/saturation is gained.

Also, your bug reporting 101 website shows a 404 error.

**Comment by williewillus** [comment]
what does the charm do?

**Comment by JJSax** [comment]
@williewillus 

The charm skips the eating animation allowing for instant eating.

**Comment by Hubry** [comment]
The fruit is not a food item, but rather an item that adds hunger and saturation during usage. The animation it uses is not even guaranteed to be the food one, as there is an anvil rename easter egg that makes it show drinking.
