### ISSUE TITLE
Corporea dupe bug when combined with Storage Drawers

### ISSUE THREAD

**Issue by folding-code** [Vazkii/Botania#3755]
### Versions:
Forge version: 1.16.5 - 36.1.0
Botania version: 1.16.5 - 416
Storage Drawers version: 1.16.3 - 8.2.2

### Details:
Simplest setup shown below:
There is a redstone upgrade in the drawer.
![2021-06-18_12 30 16](https://user-images.githubusercontent.com/9374972/122597377-e2fa6380-d030-11eb-81d5-122fd40cbb19.png)

Putting a stack of n items in the empty drawer results in (n*(n+1))/2 items popping out of the funnel.
This means one item has no visible difference, but a stack gives 32.5 stacks of items.
![2021-06-18_12 42 55](https://user-images.githubusercontent.com/9374972/122598462-7f713580-d032-11eb-94d9-9fcc33623285.png)

Note: no redstone signal is produced. A piston placed next to the drawer does not activate
If items are put in using a hopperhock, twice the items are created, so n*(n+1) instead.
I'm not sure why, but sometimes (as in, depending on where you build it or something) using a hopperhock creates only (n*(n+1))/2 items and leaves n items in the drawer. In this case, placing two funnels next to the drawer causes both to individually create (n*(n+1))/2 items.
Also, this all seems to happen in one tick, because a hopperhock can insert any number of stacks simultaneously into the system and they will all dupe individually. If allowed to run multiple times and throw the items into the air so that they are picked up again by the hopperhock, this will quickly crash the game with too many item entities i.e. in seconds.

Interesting note: If the drawer is below the funnel, then the funnel should be placing all items into the drawer. However, the result is that all items are deleted.

Final note: This has existed since 1.12, so I think it has something to do with how minecraft handles redstone. If this is deemed a feature not a bug, I would still love to know how it is happening. I've peeked at the code myself and have no clue.

**Comment by Hubry** [comment]
Aaaaaah I hate storage drawers even more seeing this, why is it always such a pain

**Comment by rebelben99** [comment]
I'm not sure I understand the setup. Is there any way for the steps to be explained in more detail?

**Comment by Hubry** [comment]
AAAAAAAAAAAAAAAAAAAA it works
