### ISSUE TITLE
[1.16.5-416] Crystal Cube/comparator interaction broken on SP world reload

### ISSUE THREAD

**Issue by mathwiz617** [Vazkii/Botania#3763]
# Version Information
Forge version:  36.1.0
Botania version:  1.16.5-416

# Further Information
Link to crash log: not a crash
Steps to reproduce:
1. Place items (up to a stack) in a corporea monitored inventory (in one slot)
2. Watch the item with crystal cube
3. close world
4. reopen world
5a. Shift-click items out of the monitored inventory
   6a. Comparator will now read  same as before
5b. update comparator
   6b. Comparator will now read 0 

What I expected to happen:
Comparator would stay correct after relog.

What happened instead:
It broke as described above

![2021-06-26_19 45 17](https://user-images.githubusercontent.com/9375804/123528679-5ba79280-d6b7-11eb-83a2-4b4c1739f717.png)

**Comment by mathwiz617** [comment]
Known workaround: update both comparator and crystal cube when logging in each time. Comparator needs a block update, cube can be updated by changing the number of items in the system.

**Comment by williewillus** [comment]
are these in the same chunk?

**Comment by mathwiz617** [comment]
Tested having both in the same chunk, and having them across chunk border. Both are broken. In the picture below, the force relay cube is on the Z border, the blue concrete cube is on the X border, ant the orange concrete cube is in the same chunk. This is spawn chunks, if that matters.


![2021-06-27_16 17 29](https://user-images.githubusercontent.com/9375804/123558272-63bd0c00-d763-11eb-9acd-94e918f852f6.png)
