### ISSUE TITLE
Server Crash Due To Invalid Dist: Dedicated Server

### ISSUE THREAD

**Issue by CynicalShrew** [Vazkii/Botania#3764]
# Version Information
Forge version: 36.0.25
Botania version: 417

# Further Information
Link to crash log: https://gist.github.com/CynicalShrew/59a2e4fa7a2a8eff95b91158a26452c5

Steps to reproduce:
1. Run latest update on server

What I expected to happen: Server to start after running .jar

What happened instead: Server crashed on startup

**Comment by CynicalShrew** [comment]
Confirmed that crash occurs after removing all other mods besides Botania and the required dependencies. No issue with singleplayer instances, which makes sen

**Comment by ethosrot** [comment]
Also seeing this issue running solo on 36.1.0 on a dedicated server.
