### ISSUE TITLE
[1.16.5] Livingwood Avatar no longer uses any rods

### ISSUE THREAD

**Issue by MuteTiefling** [Vazkii/Botania#3773]
# Version Information
Forge version:  36.1.32
Botania version:  Botania-1.16.5-418.jar

# Further Information
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)\
Steps to reproduce:
1. Place Creative Mana Pool
2. Place Gaia Spreader
3. Place Livingwood Avatar
4. Link Spreader to Avatar
5. Give Avatar a valid rod, such as Rod of the Lands

What I expected to happen:
Avatar should use the rod

What happened instead:
Avatar does not use the rod

Issue discovered in Enigmatica 6: https://github.com/NillerMedDild/Enigmatica6/issues/2638

Issue can be reproduced with the following mod list:
Botania-1.16.5-418
curios-forge-1.16.5-4.0.5.2
jei-1.16.5-7.7.1.110
Patchouli-1.16.4-53.1

**Comment by williewillus** [comment]
is the avatar powered?

**Comment by williewillus** [comment]
nvm, got it. Inverted a condition check.
