### ISSUE TITLE
Portal to Alfheim doesnt open

### ISSUE THREAD

**Issue by Pitohui202** [Vazkii/Botania#3780]
# Version Information
Forge version:  1.16.5-forge-36.1.0
Botania version:  Botania -1.16.5-419

# Further Information
I have two full mana pools with natura pylons.When i right click the gateway core the animation starts playing,but the portal breaks before its finished.

What I expected to happen:The portal to open

What happened instead:Animation started playing but didnt finish,no mana was used.(picture of area below)
![2021-07-19_01 02 57](https://user-images.githubusercontent.com/77505492/126084958-61f93e35-e02e-42b8-a077-633684d27465.png)

**Comment by Hubry** [comment]
Great that you have a checkerboard floor, because it tells me your pylons are outside the 11x11x11 area around the portal core that is used for them.

Also next time please ask for help on discord, this is an issue tracker.
