### ISSUE TITLE
Terra Shatterer in bulk mining mode voids ores above its mining level

### ISSUE THREAD

**Issue by LuciusV** [Vazkii/Botania#3891]
### Mod loader

Forge

### Minecraft version

1.16.5

### Botania version

Botania-1.16.5-420

### Modloader version

36.2.8

### Modpack info

All The Mods 6 1.8.10

### The latest.log file

no log

### Issue description

When Terra Shatterer is in bulk-mining mode (activated by right click), 
It voids all ores with mining level above it can mine in 5x5x2 and if is extremely likely to happen if ore in second layer (far from player invisible behind first layer)

Expected behavior: ore that cannot be mined left in world untouched. 

(https://github.com/AllTheMods/ATM-6/issues/2765)

### Steps to reproduce

Try mine any mode ore with mining level higher than netherite (e.g. ATM high tier ores)

**Comment by Hubry** [comment]
Fixed on 1.18, *probably* not backporting though.

**Comment by LuciusV** [comment]
Thank you! But the fix code seems to be very simple, why not backport, it's somehow frustrating bug?

**Comment by williewillus** [comment]
@Hubry we probably will need to release a 1.16 build to fix the spreader simulation bug, so you can backport if you feel like it.

**Comment by Hubry** [comment]
Oh, I thought that was in 420.2. And someone came to me yesterday with the bergamute crash on that one, so actually we might need it anyways.
