### ISSUE TITLE
[1.18.1] Flower Priority System not Working, and Dirt Texture for Floating Flowers doesn't Change when Seeds/Spores are Used

### ISSUE THREAD

**Issue by ghost** [Vazkii/Botania#3892]
### Mod loader

Fabric

### Minecraft version

1.18.1

### Botania version

1.18.1-427

### Modloader version

Fabric: Loader 0.12.12 + API 0.45.0

### Modpack info

http://ulaan.net/modlist/

### The latest.log file

https://pastebin.com/yPx7V55r

### Issue description

Issue 1: The priority system for generating/functional flowers seems to be broken. Generating flowers is now getting priority over functional flowers regardless of the type of dirt below them. For example, even if I plant endoflames on mycelium, the combustible items dropped on the ground will still be instantly picked up by the flower, whereas for functional flowers like hopperhock and rannucarpus there's always a slight delay.
Issue 2: The dirt texture of floating flowers doesn't change when seeds/spores on used on them. It's always the default grass texture.

**Comment by anoomolu** [comment]
Tested on latest Fabric release, I can't reproduce the flower priority part of the issue. 

Both Endoflame and Hopperhock on Grass - Endoflame takes priority
Endo on Podzol, Hopperhock on Grass - Hopperhock takes prio
Endo on Mycelium, Hopperhock on Podzol - Hopperhock takes prio

These are the observed results which match up with what's expected. Might be worth adjusting the title to only mention the texture part now.

**Comment by anoomolu** [comment]
The texture issue is to do with Sodium, as I've had this issue too, and disabling the mod fixes it.

Without Sodium:
![image](https://github.com/VazkiiMods/Botania/assets/77850233/78a1eb8b-b0b7-4521-842f-c46dc50b753c)

With:
![image](https://github.com/VazkiiMods/Botania/assets/77850233/2da4d5b0-22a2-43a1-b7db-bb6e31831e56)

**Comment by ProSkillzDragon** [comment]
I'm having the same issue, but with forge in 1.20.1

**Comment by TheRealWormbo** [comment]
The Forge issue likely has a separate cause, so that gets tracked as #4625.
