### ISSUE TITLE
[1.18.1] Thermalily Smoke Particle Effects Are Not Randomly Shifted by World Position

### ISSUE THREAD

**Issue by aquila-zyy** [Vazkii/Botania#3896]
### Mod loader

Fabric

### Minecraft version

1.18.1

### Botania version

1.18.1-427

### Modloader version

Fabric Loader 0.12.12 + API 0.45.0

### The latest.log file

https://pastebin.com/KgH927nY

### Issue description

Unlike other particle effects that should spwan at the center of the flower, such as the torch pe of End of Flame or even the wisp pe of Thermalily when it is buring, the smoke pe of Thermalily always spawn at the center of the block and are not randomly shifted by world position as the flower itself does.

### Steps to reproduce

1. Put down one Thermalily.
2. Pour a bucket of lava beside it.
3. Wait for it to consume the mana.
4. Observe that the smoke particle effect is not aligned to the flower.

### Other information

This glitch is found during a normal survival playthrough, so I do have some other QoL mods such as Roughly Enough Item and Sodium installed.

**Comment by Hubry** [comment]
Good catch, this actually applies to a bunch of other flowers. Except endoflames, that got adjusted years ago.
