### ISSUE TITLE
Alfheim portal spiral quads render on the wrong side

### ISSUE THREAD

**Issue by artemisSystem** [Vazkii/Botania#3897]
### Mod loader

Fabric

### Minecraft version

1.18.1

### Botania version

1.18.1-427

### Modloader version

loader: 0.12.11-1.18.1 api: 0.44.0+1.18

### The latest.log file

n/a

### Issue description

Here is a screenshot taken in 1.16:
The green spiral quad is seen before the center of the portal. Not pictured, standing in the middle of the portal makes both quads invisible (since they're both facing away from the camera)
![2022-01-07_14 30 55](https://user-images.githubusercontent.com/39034386/148577624-8cb64b0d-cee2-4b2d-b6db-6fdf1864a32a.png)

Here is a screenshot taken in 1.18:
The green spiral quad is seen *after* the center of the portal (in the portal in the back). Additionally, when standing in the middle of the portal, you can see both quads.
![2022-01-07_14 50 05](https://user-images.githubusercontent.com/39034386/148577980-de84c80b-4967-448b-8ff0-e3529a3adfa8.png)

### Other information

Reproduced both on 1.18.1-427 from curseforge and in a dev env at https://github.com/artemisSystem/Botania/commit/373c92f9b209da6187e846cda8d13cdf2d1acd0c

tbh, i think i might prefer how it is in 1.18. i just brought it up because it seems like an unintentional change, and it could possibly be slightly changed to be even better

**Comment by williewillus** [comment]
the "visible from the middle" is intentional and I think we want to keep it. I'm not sure what you mean by "before" or "after" center, though.
