### ISSUE TITLE
Spongeforge - Botania mixin error

### ISSUE THREAD

**Issue by BronzeS8** [Vazkii/Botania#3899]
### Mod loader

Forge

### Minecraft version

1.16.5

### Botania version

1.16.5-420.1

### Modloader version

Forge: 36.2.22

### Modpack info

https://www.curseforge.com/minecraft/modpacks/hekkawick

### The latest.log file

https://gist.github.com/BronzeS8/f10284707aa632bc464b6ad0f1eab9ea

### Issue description

Running my modded server, an issue arises with Botania whenever I try run it with spongeforge. I'm not good with technical terms and what not, but from sharing this issue the best way I can describe it is as a conflict/error with Botania's mixins? Im not sure if this means they're broken or act funky, etc but its a problem with it's mixins lmao

(sorry I couldn't give much more info)

### Steps to reproduce

Download modpack and run server with spongeforge in it. Server should begin to start up but then crash start-mid progression of start up.

### Other information

All other mods are updated, the crash says its Botania's doing however there maybe other mods involved with the crash as I haven't had the opportunity to remove Botania and see if the server is then able to run spongeforge

**Comment by BronzeS8** [comment]
I did look in spongeforge's discord and others are experiencing the same issues from searching through messages. Just thought I'd add that as an fyi haha as I've just learnt its not a problem exclusive to me

**Comment by Hubry** [comment]
The respective issue on Sponge's bug tracker: https://github.com/SpongePowered/Sponge/issues/3587

Finally taking a look at this... holy heck, do they really need this GIANT overwrite? [(the code)](https://github.com/SpongePowered/Sponge/blob/547ae4013bbd8a5aad55ec551cdf03837d591813/src/mixins/java/org/spongepowered/common/mixin/core/world/entity/player/PlayerMixin_Attack_Impl.java)

Looks like I might need to do this slightly differently.

**Comment by Hubry** [comment]
Might actually migrate this to Forge's crit events even if that's going to be a bit of a pain.
