### ISSUE TITLE
Not compatible with Enhanced-Celestials

### ISSUE THREAD

**Issue by silentnyte** [Vazkii/Botania#3900]
### Mod loader

Fabric

### Minecraft version

1.17.1

### Botania version

1.17.1-422

### Modloader version

Fabric 0.12.12

### The latest.log file

https://paste.ee/p/SvYLW

### Issue description

Minecraft with not launch with Botania and Enhanced-Celestials

**Comment by silentnyte** [comment]
https://github.com/CorgiTaco/Enhanced-Celestials/issues/95

**Comment by Hubry** [comment]
Duplicate of #3873, this is already fixed on 1.18, how useful is it to actually go back to backport this?

**Comment by silentnyte** [comment]
> Duplicate of #3873, this is already fixed on 1.18, how useful is it to actually go back to backport this?

It is only useful until Yung and Charm are updated to 1.18.
