### ISSUE TITLE
Mana Pylons not affecting Enchanting Table

### ISSUE THREAD

**Issue by zulrang** [Vazkii/Botania#3901]
### Mod loader

Fabric

### Minecraft version

1.18.1

### Botania version

1.18.1-427-FABRIC

### Modloader version

Fabric: Loader 0.12.12 / API 0.45.2+1.18

### Modpack info

https://www.curseforge.com/minecraft/modpacks/all-of-fabric-5/files/3601961

### The latest.log file

https://pastebin.com/dJyxgqHA

### Issue description

Mana Pylons do not increase the enchanting table level.

### Steps to reproduce

1. Put Mana Pylon next to an enchanting table.
2. Observe low level enchants.

### Other information

See it in action:
https://imgur.com/a/gfZFTEl

**Comment by williewillus** [comment]
@MoriyaShiine your mixin is bork, help?

**Comment by Hubry** [comment]
I tested it in prod without other mods when making it, I am pretty sure should it work. Might need to take a look at the modpack.

**Comment by MoriyaShiine** [comment]
Concern

I'll check the pack when I get out of bed

**Comment by Hubry** [comment]
https://github.com/paulevsGitch/BCLib/blob/8ebcf2352ac7d4a940ee1ec799972a22ef28906f/src/main/java/ru/bclib/mixin/common/EnchantmentMenuMixin.java#L58-L59

Not our fault. This is literally an Overwrite in all but name.

**Comment by zulrang** [comment]
Fixed in BCLib 1.2.4
