### ISSUE TITLE
Crash on Server

### ISSUE THREAD

**Issue by TheButterbrotMan** [Vazkii/Botania#3911]
### Mod loader

Fabric

### Minecraft version

1.18.1

### Botania version

1.18.1-427

### Modloader version

0.12.12

### Modpack info

https://www.curseforge.com/minecraft/modpacks/deathdusk

### The latest.log file

https://pastebin.com/QDXzzgxD

### Issue description

Server is crashing

### Steps to reproduce

1. I dont know, appeared two times.

**Comment by TheButterbrotMan** [comment]
https://pastebin.com/8Qxet02F

**Comment by YourLocalMedic** [comment]
Ever find a way around this? We were trying to use Botania on my server and it seems to be crashing because of it, however we do have other mods installed. It crashes after like 25 minutes

**Comment by Hubry** [comment]
The first crash report seems to be from an unrelated mod interaction, possibly some sort of thorns-like damage loop. The only reason Botania appeared in that stack trace was the Odin Ring checking if you are immune against that damage type. You will have to dump the mixin classes with the JVM argument `-Dmixin.debug.export=true` and open the class in a decompiler. Please join Vazkii's discord and ping me in #help if you need assistance with that.

The second one might be fixed already? It's a completely different crash and deserves its own post if it still happens to you.
