### ISSUE TITLE
Gaia is completely invisable 

### ISSUE THREAD

**Issue by GenericQuinn** [Vazkii/Botania#3912]
### Mod loader

Fabric

### Minecraft version

1.18.1

### Botania version

1.18.1-427FABRIC

### Modloader version

0.12.12

### Modpack info

All of Fabric 5 

### The latest.log file

N/A

### Issue description

Gaia is invisble when I have an Iris shader enabled - I'm using Iris 1.1.3, and the complementry shader. 

Granted I can fix the issue by simply disabling the shader but is there a work around to make the rendering work with a shader enabled? Would be lovely for immersion - Thanks 

### Steps to reproduce

Have Iris installed
Have shader enabled
Summon Gaia
Realise Gaia is invisble 
**realise Gaia is invisble**
PANIK 

### Other information

N/A

**Comment by Hubry** [comment]
Known on their side. https://github.com/IrisShaders/Iris/issues/194
We'll probably have to add some fallback render paths for Iris...

**Comment by GenericQuinn** [comment]
Seems it was mentioned a long time ago but they never got around to fixing it. If either party does come up with a fix I'd be super happy - Thanks :)

**Comment by williewillus** [comment]
It's going to be tricky. The GG's main distortion effect has to use a shader, so either we disable our shader (GG looks extremely boring) or the Iris one is disabled (also not fun).

**Comment by nephatrine** [comment]
While not ideal and it's not really botania's fault or problem, a config option to disable botania's shaders would I think be preferable to users having to toggle off their iris shaders to see things.

**Comment by DonFlymoor** [comment]
A possible solution would be to automatically merge botania's shaders and the current irus shader like flywheel-oculus-compat does

**Comment by williewillus** [comment]
Let's centralize on #3951 for this
