### ISSUE TITLE
登陆后无法打开饰品栏

### ISSUE THREAD

**Issue by vicuna-main** [Vazkii/Botania#3915]
### Mod loader

Forge

### Minecraft version

1.16.5

### Botania version

1.16.5-420.1

### Modloader version

Forge 36.2.23

### The latest.log file

https://gist.github.com/764069075/a48526975a68eaa4997e1d359dd164e9#file-latest-log

### Issue description

【路人】🍰 16:56:09
饰品那边的问题就在于每次进服务器，就打不开，死一次才打得开

【路人】🍰 16:56:21
但是如果当时你身上有饰品

【路人】🍰 16:56:30
饰品就会在你死的时候消失

### Other information

结合我的判定,应该是authme登录插件导致.

希望作者们能够修复一下问题,感谢

**Comment by Hubry** [comment]
Firstly, *English please.*
Secondly, this isn't the Curios issue tracker or the AuthMe issue tracker.
