### ISSUE TITLE
[1.18.1 Forge] Sash step assist not working

### ISSUE THREAD

**Issue by Tlp300** [Vazkii/Botania#3920]
### Mod loader

Forge

### Minecraft version

1.18.1

### Botania version

Botania-1.18.1-428-SNAPSHOT

### Modloader version

Forge: 39.0.59

### The latest.log file

https://pastebin.com/1DQ0McV8

### Issue description

The sash currently doesn't appear to be giving the proper effects in the current snapshot build. Fall damage resist doesn't appear to be working, nor does the step-up or move speed increase. Jump height increase works fine though.

### Steps to reproduce

1. Equip a Sojourner's Sash. Make sure you have a filled Mana Tablet.
2. Run around for a bit, try to walk up blocks.
3. Jump off even a block higher height and you'll take damage.

### Other information

Did test this on Fabric, works fine over there.

Also here's a video.

https://user-images.githubusercontent.com/97860243/150853999-df831a7e-b181-4989-a6ed-510e075841e3.mp4

**Comment by williewillus** [comment]
Can you try on the latest snapshot again? Everything should be working now except step height

**Comment by Tlp300** [comment]
Sorry for the late reply, I'm currently busy with other stuff at the moment and didn't really have time to test it immediately. I can confirm that it works properly besides the step height of course on the latest snapshot.

**Comment by williewillus** [comment]
blocked on https://github.com/MinecraftForge/MinecraftForge/pull/8389
