### ISSUE TITLE
Crash stating it ended on the render thread

### ISSUE THREAD

**Issue by Nathan22211** [Vazkii/Botania#3922]
### Mod loader

Fabric

### Minecraft version

1.18.1

### Botania version

1.18.1-427

### Modloader version

Loader 0.12.12, API 0.46.0+1.18

### The latest.log file

https://gist.github.com/Nathan22211/6f2f916657dd09a27a175bb5b8552030

### Issue description

The mod crashes on the render thread

### Steps to reproduce

Add botania and the needed mods on their own in the mods folder of a dev environment's client folder ([mod project]/run/mods). Running it should crash with the report mentioning the render thread

### Other information

This is in a dev environment, I tried to import via Gradle but had similar issues

**Comment by Hubry** [comment]
I have no idea why it fails to remap, but it seems to work fine on latest versions.

Use Mojmap instead of Yarn, or depend on the unstable snapshots from maven (1.18.1-428-FABRIC-SNAPSHOT), they seem to work fine.
