### ISSUE TITLE
[1.18.1 Forge] Bergamute Crash and Chunk Error(?)

### ISSUE THREAD

**Issue by Tlp300** [Vazkii/Botania#3925]
### Mod loader

Forge

### Minecraft version

1.18.1

### Botania version

Botania-1.18.1-428-SNAPSHOT

### Modloader version

Forge: 39.0.59

### Modpack info

Petra's Modpack

### The latest.log file

https://pastebin.com/jspJHHBZ

### Issue description

Placing a bergamute causes a crash/disconnect, and upon loading back into the world, the chunk seems like it's missing or corrupt in some sense.

### Steps to reproduce

1. Place Bergamute.
2. *explosion*

### Other information

I should mention that yes, I was running Optifine at the time, but the chunk issue seems to have persisted even after removing it.
![2022-01-25_04 48 33](https://user-images.githubusercontent.com/97860243/150954464-8516d9a3-6623-408a-ba0e-cc59af4df640.png)

**Comment by Tlp300** [comment]
Another crash report here, doing a quick test in singleplayer without Optifine on the same pack:
https://pastebin.com/wt2sgGF4

**Comment by Hubry** [comment]
Looks like Willie accidentally gave it the functional flower wand hud because it used to be one.
