### ISSUE TITLE
Hopperhocks don't interact with drawers from storage drawers

### ISSUE THREAD

**Issue by LeoBeliik** [Vazkii/Botania#3926]
### Mod loader

Forge

### Minecraft version

1.18.1

### Botania version

428-snapshot

### Modloader version

39.0.59

### Modpack info

petra's pack

### The latest.log file

ehh

### Issue description

hopperhocks can't put items inside the drawers

### Steps to reproduce

place a hh
place a drawer next to it
drop an item

**Comment by Hubry** [comment]
f599fbc03c5344233b2b267e2286f0dfaa2b6a11
