### ISSUE TITLE
Corporea Index doesn't intercept chat requests

### ISSUE THREAD

**Issue by deingithub** [Vazkii/Botania#3927]
### Mod loader

Fabric

### Minecraft version

1.18.1

### Botania version

1.18.1-427-FABRIC

### Modloader version

Fabric: Loader 0.12.12 + API 0.46.1

### Modpack info

https://www.curseforge.com/minecraft/modpacks/benchmark-ii

### The latest.log file

https://paste.ee/p/K7450

### Issue description

The corporea index does not intercept chat requests. When you send a chat request while it is active the message goes through to other players and no item is requested from the network.

### Steps to reproduce

1. Create a simple corporea network: one chest with regular spark, one index with master spark on top
2. Place some cobblestone in the chest
2. Stand next to the index
3. Type "1 cobblestone"
4. Observe: your message is sent and no item is delivered

**Comment by deingithub** [comment]
Did some experimenting with the dev build myself and i can't actually reproduce this issue on the `release-1.18.1-427-fabric` tag. The Fabric API version of that is slightly older, but even if i change it to 0.46.1 it still works. Issue might be related to other mods in the pack, dunno.

**Comment by Hubry** [comment]
I am investigating this, actually. Looks like a Mixin conflict, because it is working properly in dev.

**Comment by Hubry** [comment]
Removed Collective and Starter Kit from the pack, and it started working. It's caused by Collective.

It is *also* caused by FTB Ranks, separately.
