### ISSUE TITLE
Crash when trying to craft the blaster with a lense on a server

### ISSUE THREAD

**Issue by LeoBeliik** [Vazkii/Botania#3928]
### Mod loader

Forge

### Minecraft version

1.18.1

### Botania version

428-snapshot

### Modloader version

39.0.59

### Modpack info

petra's pack

### The latest.log file

https://gist.github.com/LeoBeliik/cc7effc0e5469a79298eeb113cd72bc2

### Issue description

it doesn't crash on sp

**Comment by Hubry** [comment]
def59a30804c109f8c8ee0fe36398fad7344df59
