### ISSUE TITLE
bore lenses can't break normal snow

### ISSUE THREAD

**Issue by LeoBeliik** [Vazkii/Botania#3929]
### Mod loader

Forge

### Minecraft version

1.18.1

### Botania version

428-snapshot

### Modloader version

39.0.59

### Modpack info

petra's pack

### The latest.log file

ehh

### Issue description

bore lenses both in blaster as in spreader can't break normal snow, this also happens in fabritania.

### Steps to reproduce

shoot a bore beam to a snow block

**Comment by williewillus** [comment]
Fixed
