### ISSUE TITLE
Mana fluxfield not working

### ISSUE THREAD

**Issue by ERBEpic** [Vazkii/Botania#3931]
### Mod Loader

Fabric

### Minecraft Version

1.18.1

### Botania version

1.18.1-427-FABRIC

### Modloader version

Fabric loader 0.12.12, API 0.46.1+1.18

### Modpack info

test modpack of modern industrialization, tech reborn, industrial revolution, botania, fabric api, and dependencies trinkets architectury fabric language kotlin and REI

### The latest.log file

https://paste.ee/p/Epztp

### Issue description

Mana fluxfield doesnt output power or doesnt input mana

### Steps to reproduce

1. Get a mana fluxfield
2. Give it mana
3. Try to take power out of it

**Comment by Hubry** [comment]
Oh, that's currently completely unimplemented.

**Comment by williewillus** [comment]
implemented now
