### ISSUE TITLE
Breaking immersion of other mods, flowers spawning in custom dimensions they shouldn't. 

### ISSUE THREAD

**Issue by ghost** [Vazkii/Botania#3935]
### Mod Loader

Forge

### Minecraft Version

1.16.5

### Botania version

Botania-1.16.5-420.2

### Modloader version

forge: 36.2.20

### The latest.log file

this is not log related

### Issue description

Please provide a dimension blacklist in config for where flower spawning should not occur. 

### Other information

The custom dimension used by The Abyss should only have void blocks and its special plants.
https://www.curseforge.com/minecraft/mc-mods/the-abyss-chapter-ii

**Comment by williewillus** [comment]
#3520
