### ISSUE TITLE
Elven portal won't start if the lower part of the pylon is waterlogged

### ISSUE THREAD

**Issue by LeoBeliik** [Vazkii/Botania#3937]
### Mod Loader

Both Fabric and Forge (I confirm that I have tested both loaders and will specify both loader versions below)

### Minecraft Version

1.18.1

### Botania version

427 & 428-SNAPSHOT

### Modloader version

fabric 0.12.12 & forge 39.0.63

### Modpack info

botania + deps only

### The latest.log file

https://pastebin.com/WFent58p

### Issue description

the portal won't start if the lower part of the natura pylons are waterlogged, it works with the pool and the top part of the pylon watterlogged.

### Steps to reproduce

make a portal
waterlog the bottom of the pylons
wand the portal

**Comment by williewillus** [comment]
what do you mean by "bottom"? Pylons are a single block

**Comment by williewillus** [comment]
Do you have a screenshot?

**Comment by LeoBeliik** [comment]
oh I though they were bigger than one block because I still can see the hitbox in the top  side
![2022-01-30_18 19 56](https://user-images.githubusercontent.com/11804768/151718350-6ac688af-5918-49e3-ae07-410e12ea3cb1.png)
