### ISSUE TITLE
Elven portal don't render some things through it

### ISSUE THREAD

**Issue by LeoBeliik** [Vazkii/Botania#3938]
### Mod Loader

Both Fabric and Forge (I confirm that I have tested both loaders and will specify both loader versions below)

### Minecraft Version

1.18.1

### Botania version

427 & 428-SNAPSHOT

### Modloader version

fabric 0.12.12 & forge 39.0.63

### Modpack info

botania + deps only

### The latest.log file

https://pastebin.com/WFent58p

### Issue description

When looking through an active elven portal, things like water, spreaders, banners, don't render

https://user-images.githubusercontent.com/11804768/151713825-8aff3bfb-442e-47a4-9896-fc830df2b06c.mp4

.

### Steps to reproduce

active a portal
put a spreader behind it
observe

**Comment by williewillus** [comment]
What's your graphics mode?

**Comment by LeoBeliik** [comment]
fancy

**Comment by natedogith1** [comment]
I also see this with the Manaseer Monocle's range display (noticed because floating flowers are one of the block types affected).  Switching graphics from fast/fancy to fabulous works around the issue.

Minecraft 1.16.5, Forge 36.2.20, Botania 420.2

**Comment by williewillus** [comment]
Fixed as well as we can on fabulous, to do any more is a lot of effort for little gain
