### ISSUE TITLE
Cant load from within intellij

### ISSUE THREAD

**Issue by xanthian** [Vazkii/Botania#3943]
### Mod Loader

Fabric

### Minecraft Version

1.18.1

### Botania version

-427

### Modloader version

0.12.12

### Modpack info

none

### The latest.log file

https://gist.github.com/xanthian/9bb137e6399af752c644eabdb5938216

### Issue description

add botania, patchouli and trinkets in to mods folder try to run client and crashes.

### Steps to reproduce

try to load botania from within intellij as an additional mod
does this no matter which project I work on.

no other mods have this issue

**Comment by Hubry** [comment]
Are you using Mojmap or Yarn?

**Comment by xanthian** [comment]
Yarn

**Comment by Hubry** [comment]
Welp, I have no idea why it fails to remap. 

Use Mojmap or depend on the unstable snapshots from maven (1.18.1-428-FABRIC-SNAPSHOT), they seem to work fine.
