### ISSUE TITLE
Using Floral Fertilizer (Botania) then Viewing Inventory GUI (Survival) causes Forge Crash

### ISSUE THREAD

**Issue by Danekjovax** [Vazkii/Botania#3944]
### Mod Loader

Forge

### Minecraft Version

1.16.5

### Botania version

1.16.5-420.1

### Modloader version

Forge 36.2.22

### Modpack info

Astral Engineering (https://www.curseforge.com/minecraft/modpacks/astral-engineering)

### The latest.log file

https://gist.github.com/Danekjovax/a8aeb9d28b3f04027af1f6301bab2d4b

### Issue description

![2022-02-03_17 54 53](https://user-images.githubusercontent.com/10191173/152463769-acc7a1f6-f768-4163-b291-4cfad8e2956e.png)

After using some Floral Fertilizer (Botania) on grass, viewing your inventory GUI will immediately produce a Forge crash (see attached 1), and then when given the option to return to the Main Menu and then clicked, sometimes results in another Forge crash (see attached 2). Returning into the game directly from the Main Menu at this point only results in immediate crash (see crash 1), and most likely repeats crash 2. The only way to clear this crash loop is to quit the client completely and restart the Forge client.

### Steps to reproduce

1) While in the game (using above modpack, or possibly any modpack including the two above mods), use floral fertilizer several times in an area next to you.
2) open your inventory GUI. Forge should crash at this action.

### Other information

https://github.com/Suff99/Weeping-Angels/issues/209

**Comment by williewillus** [comment]
```
	at me.suff.mc.angels.client.renders.layers.WingsLayer.shouldDisplay(WingsLayer.java:44) ~[weeping_angels:2.1.7] {re:classloading}
```

Seems to be caused by the Angels mod (or whatever this is?)

Also, I don't think this is specific to the floral fertilizer, does it happen with lots of mana pools nearby? Pools produce the same particles the fertilizer does.

**Comment by Elfinlocks** [comment]
This can be closed - Weeping Angels dev has found and fixed the issue on https://github.com/Suff99/Weeping-Angels/issues/207

**Comment by williewillus** [comment]
great, thanks
