### ISSUE TITLE
Red string container cannot expose the whole inventory of a double chest, only a single chest

### ISSUE THREAD

**Issue by FizzBuzz3000** [Vazkii/Botania#3945]
### Mod Loader

Fabric

### Minecraft Version

1.18.1

### Botania version

Botania-1.18.1-428-FABRIC-SNAPSHOT build #49

### Modloader version

Fabric 0.12.12, fabric-api-0.46.1+1.18

### The latest.log file

https://gist.github.com/FizzBuzz3000/124297d39883cbdd8233b901eec41b23

### Issue description

Title. In the latest fabric snapshot version of botania from  Jenkins, the Red string container does not expose the whole inventory of a double-chest, only the one it is bound to.

### Steps to reproduce

1. Bind a redstring container to a double chest
2. Place a hopperhock or hopper into the block
3. Fill the half the chest is bound to
4. Fill hopper or hopperhocks with items
5. Be sad as it does not insert items into the other half of the double chest

### Other information

As stated, This was done with a SNAPSHOT version of fabric botania. This might affect older versions, and testing is required. Will do testing with release fabric botanias tomorrow to see if it is broken there as well.

**Comment by Hubry** [comment]
With 2414c8e91d0a98b770f242af6789abfb9a1f8aeb, they only use Fabric transfer api (and Forge's item handlers on Forge), which wraps the whole chest at once.
