### ISSUE TITLE
Endoflames eat fuel items too quickly

### ISSUE THREAD

**Issue by ArcanePigeon** [Vazkii/Botania#3948]
### Mod Loader

Fabric

### Minecraft Version

1.18.1

### Botania version

1.18.1-472

### Modloader version

Fabric 0.12.12

### The latest.log file

N/A

### Issue description

Endoflames pick up any fuel item instantly which differs from the forge version making it very difficult to build around the flower as it will eat any wooden building materials (chests, barrels, planks, etc) the second you break the block.

### Steps to reproduce

1. Build endoflame mana gen setup
2. break and wooden block near the endoflames
3. Items instantly get eaten

**Comment by Hubry** [comment]
Fixed in dev already
