### ISSUE TITLE
[Confirmed issue in 1.12.2 and 1.16.5] Botania cauing particles to "cease and desist" in overabundance

### ISSUE THREAD

**Issue by Shibva** [Vazkii/Botania#3952]
### Mod Loader

Forge

### Minecraft Version

1.12.2 and possably up to 1.16.5 or higher

### Botania version

undertermened, but will be in still the 1.12.2 latest and 1.16.5 Botania-1.16.5-420.2.jar

### Modloader version

36..2.22

### The latest.log file

N/a the log as far as i know wont log particles

### Issue description

This has been a bug that I found in 1.12.2 BUT now have confirmed its existence in 1.16.5

This bug is a bit of a strange one, as for what cause it in the 1.16.5 case IHNC, but know how to reproduce it

This issue is one regarding the particle system. idk why but after a given amount of particles are shown the all "disappear" and only reapear once the game itself is restarted. and I mean all particles, anything that is considered one, just stops workingcaused

### Steps to reproduce

as for how this happend in 1.16.5 idk, I do know how in 1.12.2 but for reasons sake ill assme that this is the same way to do it in 1.16.5

you will need to have a lot of particles, in all cases when this happened to me in 1.12.2, it was the Terrastrial Algimator that tipped the scale

So if I'm correct having multiple of them running and spawning particles at the same time (not really, just a bunch of them working, doesn't have to be synchronized) will produce enough of them to cause the issue to occur. you will know you got it when the particles stop working and still see the terrasteel almagamators still turning their materials into terrasteelhappened

### Other information

if I encountered this in 1.16.5 and in 1.12.2, it might be safe to say that it can be in other versions up to the most recent Minecraft version release, anything father than 1.12.2 is uncertain

**Comment by Hubry** [comment]
All particle types, or just the same ones? The particle manager only keeps 16384 particles of each render type, adding more removes the oldest particles. Botania does output a lot of particles, that's true... and most of the particles are in one of 4 types - wisp, sparkle, depth ignoring wisp (visible through walls), grainy sparkle (gaia guardian shader).

**Comment by Shibva** [comment]
All of them all of them just shut down

**Comment by Shibva** [comment]
If you wanna see it for yourself try having multiple terrestrial accumulators running at the same time to produce enough particles called the entire thing to shut down

**Comment by Shibva** [comment]
Some exceptions to this however might be with the particles that are produced from Astral sorcery, but other than that most particles shut down completely including particles created by other mods that have the wrong unique particle mechanics like draconic evolution's

**Comment by williewillus** [comment]
there's nothing really actionable here unless you have an exact and small set of mods + a build that replicates the issue reliably, in 1.18
