### ISSUE TITLE
1.18.1 spreader aim resetting

### ISSUE THREAD

**Issue by natedogith1** [Vazkii/Botania#3954]
### Mod Loader

Fabric

### Minecraft Version

1.18.1

### Botania version

1.18.1-427-FABRIC

### Modloader version

Loader 0.13.2 + API 0.46.4+1.18

### Modpack info

Just using CurseForge installing only Botania (other mod versions are Patchouli (Fabric): 1.18.1-64 and Trinkets (Fabric): 3.2.0)

### The latest.log file

https://gist.github.com/natedogith1/62f127b0bd4be1e72d5f9b34f9e52f9b

### Issue description

When aiming a spreader (at least at a normal block), saving and re-starting the world will undo the aiming.

### Steps to reproduce

1. create a new creative world
2. grab a spreader and a wand
3. place the spreader
4. use the wand to aim the spreader somewhere
5. save and quit to title
6. re-start the world
7. notice the spreader's aim reverted

### Other information

https://user-images.githubusercontent.com/1638163/153773687-c08e137f-cc0e-4a77-9e99-e20a608acc3e.mp4

**Comment by Hubry** [comment]
Ugh, seems like a yet another case of forgetting to mark the BE as changed
