### ISSUE TITLE
forge tag for ingots

### ISSUE THREAD

**Issue by LeoBeliik** [Vazkii/Botania#3955]
### Mod Loader

Forge

### Minecraft Version

1.18.1

### Botania version

428-snapshot

### Modloader version

39.0.75

### The latest.log file

ehh

### Issue description

add forge tags for the ingots 👍🏻

**Comment by LeoBeliik** [comment]
you forgor mana glass panes and elf panes and bifrost pane, add em to forge:glass_panes, this is important for windowlogging :hahayes:

**Comment by Hubry** [comment]
waa
