### ISSUE TITLE
Tile Entities destroyed when upgrading from 1.17 to 1.18

### ISSUE THREAD

**Issue by natedogith1** [Vazkii/Botania#3956]
### Mod Loader

Fabric

### Minecraft Version

1.17.1 & 1.18.1

### Botania version

1.17.1-422-FABRIC & 1.18.1-427-FABRIC

### Modloader version

1.17.1 Fabric: Loader 0.13.2 + API 0.46.1 1.18.1 Fabric: Loader 0.13.2 + API 0.46.4

### The latest.log file

https://gist.github.com/natedogith1/bc1811528f87fd0482b91fb770d9ee14

### Issue description

When upgrading a world from 1.17 to 1.18, all tile entities in a chunk with a spreader are cleared.

### Steps to reproduce

1. create a 1.17 world
2. place a spreader and a chest (with contents) in the same chunk
3. copy save from 1.17 to 1.18
4. open world in 1.18
5. notice that the spreader and chest are invisible and that the chest is empty

**Comment by williewillus** [comment]
this is a vanilla bug if I recall correctly.

**Comment by williewillus** [comment]
https://bugs.mojang.com/browse/MC-244164, fixed in upcoming 1.18.2
