### ISSUE TITLE
Entropynnium Efficiency Bug

### ISSUE THREAD

**Issue by Noxally** [Vazkii/Botania#3957]
### Mod Loader

Fabric

### Minecraft Version

1.18.1

### Botania version

1.18.1-427

### Modloader version

0.12.12 and 0.46.4

### The latest.log file

irrelevant

### Issue description

Entropynnium doesnt detect/doesnt reduce mana generated with tnt dupers. Tested 4 Dupers vs manually placed and ignited tnt, each tnt generates the same mana (6400) as viewed using a mana mirror. This is using slime block based dupers, coral slime based dupers, slime block free dupers and coral free dupers. Some use minecarts, some dont.

### Steps to reproduce

Record mana level, dupe tnt, record mana level, repeat x10

record mana level, manually place and ignite tnt, record mana level, repeat x10

Compare results

**Comment by Hubry** [comment]
https://github.com/VazkiiMods/Botania/issues/3749#issuecomment-860243888
