### ISSUE TITLE
[1.18.1 Forge] Flower transparency broken in Lexica

### ISSUE THREAD

**Issue by FynnWaelsing** [Vazkii/Botania#3960]
### Mod Loader

Forge

### Minecraft Version

1.18.1

### Botania version

1.18.1-428

### Modloader version

Forge 39.0.84

### The latest.log file

https://pastebin.com/G01AJ3S5

### Issue description

The transparency of flowers in the Lexica renders appears to be broken. This can be seen in the screenshot below with the Mana Enchanter entry.

![image](https://user-images.githubusercontent.com/45303748/155245720-8ccfc5a8-6650-470a-bc2c-a3dbb933c25c.png)

**Comment by williewillus** [comment]
can you try in fabric? this is probably a patchouli bug, also.

**Comment by FynnWaelsing** [comment]
It is not broken in the latest Botania (1.18.1-428-FABRIC)

**Comment by williewillus** [comment]
this turned out to be a patchouli bug, will be fixed in next patchouli release https://github.com/VazkiiMods/Patchouli/issues/520
