### ISSUE TITLE
Terrestrial Agglomeration Plate / Sparks no longer work

### ISSUE THREAD

**Issue by Jigglypie** [Vazkii/Botania#3962]
### Mod Loader

Fabric

### Minecraft Version

1.18.1

### Botania version

1.18.1-428

### Modloader version

Fabric: Loader 0.13.3 + API 0.46.4

### The latest.log file

https://pastebin.com/8gqXuG69

### Issue description

The process for making Terrasteel Ingots appears to be bugged on Botania-1.18.1-428 for Fabric. 
Upon updating to the new Botania, our setup for making Terrasteel ingots ceased functions.
I have replicated the setup on multiple different profiles, and none worked with the new update. Upon making a new profile w/ the previous version of Botania (Botania-1.18.1-427) on Fabric-0.13.3, the process once again worked.

### Steps to reproduce

1) Fresh install fabric Botania, fabric Trinkets, & fabric Patchouli
2) Start up a singleplayer world in creative
3) Place down an Everlasting Guilty Pool, then place a Spark above it
4) Nearby, place down 5 Livingrock in an 'X' pattern, 4 Lapis Lazuli blocks in the remaining 3x3 grid.
5) Place a Terrestrial Agglomeration Plate atop the middle Livingrock block, then place a spark on the Terrestrial Agglomeration Plate.
6) Take a Manasteel Ingot, Mana Pearl, & Mana Diamond, then attempt to right-click them all onto the Terrestrial Agglomeration Plate in order to craft a Terrasteel Ingot

**Comment by williewillus** [comment]
d695865ba 

as a temporary workaround, add the vanilla lapis block to the c:lapis_blocks tag

**Comment by quat1024** [comment]
datapack for that temporary workaround: [lapis_blocks_in_c_tag.zip](https://github.com/VazkiiMods/Botania/files/8145657/lapis_blocks_in_c_tag.zip)

this'll get included in botania proper in the next release
