### ISSUE TITLE
Starcaller wont render falling stars

### ISSUE THREAD

**Issue by Warhand** [Vazkii/Botania#3965]
### Mod Loader

Forge

### Minecraft Version

1.18.1

### Botania version

1.18.1-428

### Modloader version

39.0.79

### Modpack info

Custom pack, heres a link to the modlist https://pastebin.com/SPXiHWq8

### The latest.log file

https://gist.github.com/Warhand/2c7967262534937a67f6a3b6067f024b

### Issue description

The starcaller doesn't render any texture or model for the falling stars, it only plays a sound and then an invisible projectile will impact the ground soon after, causing damage to entities it impacts, and causing the block to emit particles as if something landed, but without the star particle itself it doesn't feel right.

### Steps to reproduce

Using the starcaller in any capacity

### Other information

My graphics settings are set to fancy, with all particles enabled, so I don't think its a settings thing

**Comment by ninyauwu** [comment]
I have the same issue. I'm using Optifine though so that might be part of the problem.

**Comment by Warhand** [comment]
I don't have optifine installed, so I can confirm its not that, at least not on my end
