### ISSUE TITLE
Podzol texture doesn't display on floating flower when using Sodium mod

### ISSUE THREAD

**Issue by mwforrest7** [Vazkii/Botania#3972]
### Mod Loader

Fabric

### Minecraft Version

1.18.1

### Botania version

1.18.1-429

### Modloader version

Fabric: loader 0.13.3 + API 0.46.4+1.18

### The latest.log file

https://pastebin.com/s7brv9t4

### Issue description

When using a boreal seed on a floating flower (i.e. a floating hopperhock), the texture does not change while using the Sodium mod. Removing Sodium fixes the issue. I am testing this w/ Sodium version: sodium-fabric-mc1.18.1-0.4.0-alpha6+build.14

### Steps to reproduce

1. Load up Botania & dependencies + the Sodium mod using the versions specified above
2. Place a floating hopperhock
3. Right click a Boreal Seed on it

**Comment by Hubry** [comment]
I don't see Indium in that log, of course modded rendering will be broken without it.
