### ISSUE TITLE
[Feature] Consider Naming Convention

### ISSUE THREAD

**Issue by xanthian** [Vazkii/Botania#3978]
### Mod Loader

Fabric

### Minecraft Version

1.18.1

### Botania version

-429

### Modloader version

0.13.2

### Modpack info

na

### The latest.log file

na

### Issue description

Please consider using the correct naming convention for slabs
Having 'custom' name makes it awkward for modpackers / datagen / dynamic gen etc..

![image](https://user-images.githubusercontent.com/7688001/156632298-b8fee480-1311-4dc0-94a4-66855fbd09de.png)

![image](https://user-images.githubusercontent.com/7688001/156632605-1e9ff018-a1f6-47c7-b83e-fe62d44bd587.png)

### Steps to reproduce

na

### Other information

na

**Comment by Hubry** [comment]
Doing name cleanups is actually planned for a while, but the prerequisites are:
- Usable datafixer hooks in both loaders
- A major MC version change, because datapacks/crafttweaker scripts/etc will break if we just do it now

That said... we are already breaking conventions by providing both living*wood* slabs and livingwood plank slabs (and this is the source of this name, there is just no wood/log variants for shimmerwood). How is your automation handling that? It might be better to use existing recipes as a base for these relations than depending on names.

**Comment by xanthian** [comment]
sadly I'm exempting it from dynamic generation and just adding recipes manually.
not a huge issue, but just thought I'd be a good chap and flag it with you :)

**Comment by williewillus** [comment]
What exactly are you referring to here? From the screenshot my impression is that our lang file is just wrong and we should match the reg name.

**Comment by xanthian** [comment]
Not the lang file (although that is likely incorrect)

It is the registered block name, vanilla wooden slabs are not prefixed with _planks_
![image](https://user-images.githubusercontent.com/7688001/156680624-7d37b157-675a-4c2b-b6f5-e1aa5608b954.png)

By all means call your blocks what you like, its just a bit frustrating trying to create mod compatibility and some mods have random naming conventions for certain block types, requiring doubling up of datagen/dynamic gen code

for eg.. I use the following to create recipes for items, for your mod (and a few others), I have to create a new iteration of it
`iKey.addProperty("item",   modPrefix + material + "_slab");`

I'm asking you to consider changing to match vanilla and the vast majority of other mods.
I know this cannot be done on a minor release so wouldn't expect anything until 1.19 at least.

**Comment by williewillus** [comment]
Hmmm, well, as hubry mentioned, we already deviate by having log/plank slabs for livingwood, and I wouldn't put it past us to add shimmerwood slabs in the future, so I'm not really sure. Also renaming ID's is a pain in the ass and I'd rather not do it as it breaks people's worlds.
