### ISSUE TITLE
Alternate floating island types don't render on forge

### ISSUE THREAD

**Issue by MadAng3l** [Vazkii/Botania#3979]
### Mod Loader

Forge

### Minecraft Version

1.18.1

### Botania version

1.18.1-429

### Modloader version

Forge 1.18.1-39.0.88

### The latest.log file

Dont know what to put here

### Issue description

Using a Boreal Seed or Infestation Seeds does not change the soil texture and does not apply it's effect.

### Steps to reproduce

1. Place down Floating Flower (I used Floating Hopperhock)
2.  Right click with Boreal Seed on the Floating Flower

**Comment by Cicopath** [comment]
In my experience with the mod so far, the Hopperhock is indeed affected by the Boreal Seed and Infestation Spore; however, the visuals of the soil of the floating flower does not change.

I thought the exact same thing, specifically with the Rannuncarpus. I discovered that the Rannuncarpus's area to pick up items is 5 x 5; I am unsure of the vertical range, but it is at least three blocks under the flower. In addition, it was deactivated by a pressure plate with an item on it.
