### ISSUE TITLE
Entropinnyum won't pick up mana

### ISSUE THREAD

**Issue by customgamer10** [Vazkii/Botania#3981]
### Mod Loader

Forge

### Minecraft Version

1.12.2

### Botania version

r1.10-364.4

### Modloader version

Forge - 14.23.5.2854

### Modpack info

https://www.curseforge.com/minecraft/modpacks/stoneblock

### The latest.log file

https://gist.github.com/customgamer10/81004a8f14d794036269db634defcda0

### Issue description

The flower will pick up mana for a little while then it will just stop picking it up

### Steps to reproduce

set up an entropinnyum with a mana spreader with a composite mana lense: velocity potency on it and connect it to a mana splitter that's connected to 4 mana pools

**Comment by williewillus** [comment]
the flower needs to be completely drained before it will take any more mana
