### ISSUE TITLE
Botania crash on startup

### ISSUE THREAD

**Issue by bodynek** [Vazkii/Botania#3984]
### Mod Loader

Forge

### Minecraft Version

1.18.2 and 1.18.1

### Botania version

1.18.1-429 and 1.18.1-428

### Modloader version

Forge 1.18.2-forge-40.0.15

### The latest.log file

https://pastebin.com/E0usMWAR

### Issue description

Mod forces Minecraft to crash. Without Botania, Minecraft with forge works fine. Same behavior on Ubuntu 20.04 and Mac OS 10.15.7

Previous version 1.18.1-428 does the same on Minecraft 1.18.1

![Screenshot 2022-03-15 at 18 45 10](https://user-images.githubusercontent.com/5212199/158448679-b3134be2-70c2-43d6-abf9-4d8526b2bee6.jpeg)

### Steps to reproduce

Put Botania on mods folder, then start Minecraft through launcher

**Comment by Hubry** [comment]
You cannot use a lot of 1.18.1 mods on 1.18.2, including Botania.
