### ISSUE TITLE
Mana burst crash

### ISSUE THREAD

**Issue by itsdinkd** [Vazkii/Botania#3985]
### Mod Loader

Fabric

### Minecraft Version

1.18.1

### Botania version

-428-Fabric

### Modloader version

0.13.3

### Modpack info

https://www.curseforge.com/minecraft/modpacks/another-quality-modpack-2

### The latest.log file

https://pastebin.com/dW8KDwmF

### Issue description

Whenever this player joins, our dedicated server crashes immediately. 

### Other information

If possible for the fix, if it isn't due to a mod conflicting and able to be fixed, may I request for the fix be released for 1.18.1? I am the creator of Another Quality Modpack 2 and am staying on 1.18.1 for a while until all mods finish being ported, and would love to get this fix out (again if possible) to the players and server owners.

**Comment by williewillus** [comment]
Looks like that crash is working as intended :P 

I think carpet is doing something funky, plus another mod having a custom teleporter. Does carpet have a way of disabling its block collision modifications?

**Comment by williewillus** [comment]
To be clear, I mean working as intended as in catching bad situations and crashing instead of continuing in unknown state. We should still fix this.

**Comment by itsdinkd** [comment]
Yes it does. I will look up all the carpet features I enabled and will report back here
