### ISSUE TITLE
Curios aren't dropped on death only when Botania is installed

### ISSUE THREAD

**Issue by Rileybutt** [Vazkii/Botania#3992]
### Mod Loader

Forge

### Minecraft Version

1.18.1

### Botania version

1.18.1-429

### Modloader version

Forge-1.18.1-39.0.88

### The latest.log file

https://gist.github.com/Rileybutt/017ea4bc58ffd485e75df6032b7d2ab6

### Issue description

When you die with Botania installed any Curios, including when you only have only have Botania installed, do not drop when the player dies. This occurs with Sophisticated Backpacks, Enigmatic Legacy and other mods that have Curios. But even when you only have Botania and Curios installed, the but still occurs.

### Steps to reproduce

1. Start game with Botania & Curios
2. Equip a Curio item
3. Check that /gamerule keepInventory is false
4. Die (/kill is the fastest)
5. Look in Curio menu and see how none of the items dropped

**Comment by williewillus** [comment]
I'm 80% sure this is a curios bug, reported there https://github.com/TheIllusiveC4/Curios/issues/232

**Comment by Rileybutt** [comment]
When using a different mod, say Enigmatic Legacy with curios installed and equipping curios that way, the bug doesn't occur. It only occurs when Botania is included in the mod list which made me think that Botania was the culprit not Curios itself.

**Comment by williewillus** [comment]
those mods might be including their own logic to drop stuff on death, not sure.

**Comment by williewillus** [comment]
Turns out the 20% was right today, fixed

**Comment by wendall911** [comment]
@williewillus would you be willing to backport this to 1.18.1? We are still on this waiting for a few other mods to update. If not, I can patch locally and distribute that to players.

**Comment by williewillus** [comment]
we're probably not gonna release any more 1.18.1 builds -- you should be able to cherry pick the fix commit to the last 1.18.1 commit (62753155c2b6abcc64fd849efab431dfc57d879b) though

**Comment by wendall911** [comment]
@williewillus Ok, that's what I did for now. Greatly appreciate the response!
