### ISSUE TITLE
[1.18.2] Drum of the Gathering doesn't work on Fabric atm

### ISSUE THREAD

**Issue by quat1024** [Vazkii/Botania#3995]
### Mod Loader

Fabric

### Minecraft Version

1.18.2

### Botania version

current snapshot https://github.com/VazkiiMods/Botania/commit/900a76b4f25b3d6ecaf379ff409fbd2233654f6e

### Modloader version

irrelevant i promise

### The latest.log file

Please let me get through the template im on my phone

### Issue description

this registers two mana trigger caps for drum of the wild instead of any for drum of the gathering https://github.com/VazkiiMods/Botania/blob/900a76b4f25b3d6ecaf379ff409fbd2233654f6e/Fabric/src/main/java/vazkii/botania/fabric/FabricCommonInitializer.java#L278-L281 so it no worky on fabric

### Other information

the equivalent line on forge is correct https://github.com/VazkiiMods/Botania/blob/900a76b4f25b3d6ecaf379ff409fbd2233654f6e/Forge/src/main/java/vazkii/botania/forge/ForgeCommonInitializer.java#L537-L538

**Comment by williewillus** [comment]
thank
