### ISSUE TITLE
Mixin error on 1.18.2, probably needs to be tackled

### ISSUE THREAD

**Issue by Sunconure11** [Vazkii/Botania#3996]
### Mod Loader

Fabric

### Minecraft Version

1.18.2

### Botania version

1.18.1-429

### Modloader version

Fabric 0.13.3

### The latest.log file

https://pastebin.com/FC6LjBPb

### Issue description

There appears to be a mixin error in this mod. Granted, this could be triggered from the obscene amount of mods I have, but I'm trying to get it into shape by reporting as many bugs as possible.

### Steps to reproduce

Load Botania

**Comment by DasGerippe** [comment]
afaik Botanias latest version (429) is not compatible with Fabric 1.18.2

**Comment by williewillus** [comment]
429 is not compatible with 1.18.2. 1.18.2 is in final testing and should be out soon
