### ISSUE TITLE
AE2 seeds in Open Crate don't drop straight down

### ISSUE THREAD

**Issue by hakanai** [Vazkii/Botania#3999]
### Mod Loader

Forge

### Minecraft Version

1.16.5

### Botania version

1.16.5-420.2

### Modloader version

36.2.28

### The latest.log file

There is nothing in the log

### Issue description

If I put AE2's seeds into an Open Crate, it flings the seeds out in any old direction instead of straight down.

This being a mod interaction issue it was hard to pick which tracker to put it in, but the same _doesn't_ happen with Quark's Chute, so my best guess is it's fixable in Botania?

![javaw_QyAfYtg8gz](https://user-images.githubusercontent.com/43236/161424460-c44f101c-9c2d-4cb5-a7ba-2fc3a5a466f2.png)

### Steps to reproduce

- Place an open crate with at least one block below
- Place a hopper on top
- Place AE2 seed items in the hopper
- Watch the show

### Other information

Applied Energistics 2 8.4.7

**Comment by Hubry** [comment]
Probably the same cause as the ancient https://github.com/HellFirePvP/AstralSorcery/issues/1566? Looking at their entity definition, the seeds are taller.

**Comment by Hubry** [comment]
Looks like Quark chutes spawn the item in the middle of the lower block, too. Open crates spawn the item as high as possible, which has issues the moment anyone makes a taller item.

**Comment by anoomolu** [comment]
The seeds are spat out in random directions when using a vanilla dropper too, the problem seems to lie with the seed size as Hubry mentioned. Closing this issue as it's an AE2 problem.
