### ISSUE TITLE
[addon dev] ItemBaubles cannot be instantiated before Botania loads

### ISSUE THREAD

**Issue by quat1024** [Vazkii/Botania#4001]
### Mod Loader

Fabric

### Minecraft Version

1.18.2

### Botania version

1.18.1-431-FABRIC-SNAPSHOT

### Modloader version

fabricLoaderVersion=0.13.3 fabricApiVersion=0.47.10+1.18.2

### Modpack info

Incorporeal 3 dev instance

### The latest.log file

not sure how useful this is because there's no commit corresponding to it but here you go https://paste.ee/p/ZchRJ

### Issue description

ItemBauble's constructor requires `EquipmentHandler.instance` to be nonnull: https://github.com/VazkiiMods/Botania/blob/82dd84072b0a107dc630ae1ee7707d8d30fd2702/Common/src/main/java/vazkii/botania/common/item/equipment/bauble/ItemBauble.java#L47

Both loaders call `EquipmentHandler.init()` on mod construction, initializing that field: https://github.com/VazkiiMods/Botania/blob/2dc24161dac59820eb3a4df618e9813860cf6fb8/Fabric/src/main/java/vazkii/botania/fabric/FabricCommonInitializer.java#L125-L129

However, on Fabric with unspecified mod load ordering, this initialization is not guaranteed to happen before the first ItemBauble is constructed (like an addon that wants to add more ItemBaubles).

### Steps to reproduce

* Make a mod that calls new ItemMonocle
* Wonder where all those spurious crashes are coming from
* Remember that Fabric has unspecified mod load ordering

### Other information

Currently I'm working around this by [calling EquipmentHandler.init from my side before constructing my ItemBaubles](https://github.com/quat1024/incorporeal-3/blob/c0eaf90719f366e6e859e7540eeef0236159699b/Common/src/main/java/agency/highlysuspect/incorporeal/IncItems.java#L108-L112), and using [a hacky mixin](https://github.com/quat1024/incorporeal-3/blob/trunk/Common/src/main/java/agency/highlysuspect/incorporeal/mixin/hacky/EquipmentHandlerMixin.java) to prevent Botania from calling `init` after I do it because it's not safe to call twice. This appears to work fine.

**Comment by williewillus** [comment]
"fixed" by just making equipmenthandler.init safe to call multiple times
