### ISSUE TITLE
[1.18.2] Flower pouch is unable to deposit flowers in a double chest if one half of a double chest is full

### ISSUE THREAD

**Issue by FizzBuzz3000** [Vazkii/Botania#4008]
### Mod Loader

Fabric

### Minecraft Version

1.18.2

### Botania version

1.18.2-430-FABRIC

### Modloader version

Fabric 0.13.3 / FAPI 0.48.0+1.18.2

### The latest.log file

https://gist.github.com/FizzBuzz3000/704f90c5382dd6a1e360993f1f03b188

### Issue description

Title. Apparently the flower pouch is unable to insert into the other half of a double chest, unless you shift-rclick the other chest block with the pouch. Not tested in forge. Unknown for how long this has been bugged either.

**Comment by anoomolu** [comment]
Was able to reproduce on Fabric 1.18.2,1.19.2, and Forge 1.19.2.

**Comment by TheRealWormbo** [comment]
Can confirm it's still an issue in 1.20.1.
