### ISSUE TITLE
Crashing at starting of client

### ISSUE THREAD

**Issue by TheButterbrotMan** [Vazkii/Botania#4010]
### Mod Loader

Fabric

### Minecraft Version

1.18.2

### Botania version

1.18.2-430-FABRIC

### Modloader version

0.13.3

### Modpack info

https://www.curseforge.com/minecraft/modpacks/deathdusk

### The latest.log file

https://bytebin.lucko.me/5g9yc349gF

### Issue description

Is crashing right after starting client

**Comment by TheButterbrotMan** [comment]
https://github.com/Lemonszz/Biome-Makeover/issues/97

**Comment by TheButterbrotMan** [comment]
Resolved by https://github.com/architectury/architectury-api/issues/241#issuecomment-1095009196

**Comment by TheButterbrotMan** [comment]
It havent.

https://bytebin.lucko.me/KzQgUEn2Et

**Comment by Aquaeyes** [comment]
The crash report with only Botania, Fabric-0.13.3, Patchouli-1.18.2-67, and Trinkets-3.3.0.
https://pastebin.com/ThN1Ap9x

Relation to GabrielOlvH/WirelessNetworks#21 ?

**Comment by Hubry** [comment]
https://github.com/FabricMC/fabric/commit/1f6558e8fb240364d2de812f585e8d0f96faf18c

willie smh

Anyways, downgrading Fabric API will work around this for now

**Comment by TheButterbrotMan** [comment]
Can I possibly ask politely when the bugfix will be released. At the moment Botania is the only mod from my 600 that does not work with the new API yet :(
