### ISSUE TITLE
Crash!

### ISSUE THREAD

**Issue by Oveln** [Vazkii/Botania#4011]
### Mod Loader

Fabric

### Minecraft Version

1.18.2

### Botania version

1.18.2-430

### Modloader version

fabric loader:0.13.3 FabricAPI:0.48.0

### The latest.log file

https://gist.github.com/Oveln/f6c2c493ca35c50cf353dcb6fca9faf7

### Issue description

Destroying the mana pool crashes when there is a spark above it.

**Comment by williewillus** [comment]
should be fixed by 112dd74
