### ISSUE TITLE
Crash with mana enchanter

### ISSUE THREAD

**Issue by gchpaco** [Vazkii/Botania#4013]
### Mod Loader

Forge

### Minecraft Version

1.18.2

### Botania version

1.18.2-430

### Modloader version

40.0.46

### The latest.log file

https://gist.github.com/gchpaco/5aa8ac9c97d2265c619feeb1ac8ecf2c

### Issue description

Mana enchanter with a spark on top crashes the server.

### Steps to reproduce

I had a mana enchanter set up with a spark on top and have twerk installed.  I put my terrasteel axe on the enchanter, and I crouched to disable magnet ring, and one of the flowers grew to double height, breaking the enchanter block.  I speculate you could probably duplicate with bonemealing a flower.

**Comment by gchpaco** [comment]
Possibly the same problem as #4011, but on Forge?

**Comment by williewillus** [comment]
should be fixed by 112dd74
