### ISSUE TITLE
[MC1.18.2 Fabric] fabric-screen-handler-api breaking change

### ISSUE THREAD

**Issue by km0nr1** [Vazkii/Botania#4014]
### Mod Loader

Fabric

### Minecraft Version

1.18.2

### Botania version

1.18.2-430-FABRIC

### Modloader version

Fabric Loader 0.13.3 + Fabric API 0.50.0+1.18.2

### The latest.log file

https://pastebin.com/FNK1g38A

### Issue description

fabric-api-0.50.0, breaking changes occurred at [fabric-screen-handler-api](https://github.com/FabricMC/fabric/tree/1.18.2/fabric-screen-handler-api-v1) .
https://github.com/FabricMC/fabric/pull/2104

so Botania cannot initialize.

> java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'botania'!
> Caused by: java.util.ServiceConfigurationError: vazkii.botania.xplat.IXplatAbstractions: vazkii.botania.fabric.xplat.FabricXplatImpl Unable to get public no-arg constructor
> Caused by: java.lang.NoClassDefFoundError: net/fabricmc/fabric/impl/screenhandler/ExtendedScreenHandlerType

with fabric-api-0.48.0, works fine.

**Comment by ghost** [comment]
I can confirm i'm encountering the same issue.
Also present on farmer's delight mod...

It is a deprecated method.

Fixed in the latest artifact (431)
https://maven.blamejared.com/vazkii/botania/Botania/1.18.2-431-FABRIC-SNAPSHOT/Botania-1.18.2-431-FABRIC-20220415.045404-16.jar

**Comment by ghost** [comment]
Fixed by commit : f364c751206e05238cc51fbf0c3f473474c59539

**Comment by williewillus** [comment]
fixed already (will release in next couple days)
