### ISSUE TITLE
Crash on bootup, connected to Botania

### ISSUE THREAD

**Issue by Sunconure11** [Vazkii/Botania#4015]
### Mod Loader

Fabric

### Minecraft Version

1.18.2

### Botania version

1.18.2-430

### Modloader version

Fabric 0.13.3

### The latest.log file

https://gist.github.com/Sunconure11/2bec16b97b1bf23bad29336c28d24490

### Issue description

https://pastebin.com/GipznSbF

### Steps to reproduce

1. Boot up the mod
2. ???
3. Crash

**Comment by williewillus** [comment]
Fixed in the next version (coming out in an hour or so)
