### ISSUE TITLE
[1.18] Botania quartz pillars textures not consistent with Quartz Pillar texture

### ISSUE THREAD

**Issue by Cicopath** [Vazkii/Botania#4016]
### Mod Loader

Forge

### Minecraft Version

1.18.1

### Botania version

1.18.1-429

### Modloader version

Forge 39.1.2

### The latest.log file

N/A

### Issue description

The Botania quartz pillar textures do not match up with the vanilla Quartz Pillar texture; the Botania quartz pillar textures seem out-of-place when compared to the new Quartz Pillar texture.
![2022-04-16_00 59 14](https://user-images.githubusercontent.com/61031176/163662205-662169fa-a060-40d2-9632-f0953e15e8bb.png)

### Other information

Although not a serious issue, I thought this may have been something to look into for the sake of consistency. Or, maybe this was a stylistic choice by the Botania developers that I was not aware about.

**Comment by quat1024** [comment]
The botania quartz pillars look more like `Programmer Art`'s quartz pillars, so i think this is a case of that texture not being changed for the minecraft texture update. There are a lot of textures in the mod that date back before 1.13 and I guess this is one that looks particularly out of place next to jappa style textures

![image](https://user-images.githubusercontent.com/2068021/164390444-046b9828-e791-4257-b0ca-4d889c579c7b.png)

**Comment by artemisSystem** [comment]
The quartz pillars will be redone as part of the ongoing botania texture update. I'm planning on making them a little more interesting than just plain recolors of the vanilla texture.

**Comment by Cicopath** [comment]
Ooh, sounds exciting! Good to know there will be a texture update; can't wait to see the new textures!
