### ISSUE TITLE
[Feature] Specifying Mobs with Bellethorne

### ISSUE THREAD

**Issue by Cicopath** [Vazkii/Botania#4018]
### Mod Loader

Both Fabric and Forge (I confirm that I have tested both loaders and will specify both loader versions below)

### Minecraft Version

1.18+

### Botania version

N/A

### Modloader version

N/A

### The latest.log file

N/A

### Issue description

As the title says, I am suggesting a feature that allows Bellethornes to attack specific mobs. This would work similarly to the Hopperhock: First, the bellethorne will have three options; attack any entity, attack only entities specified, or attack only entities not specified. To specify mobs, you must place item frames on the block below the Bellethorne, and put the corresponding item in the item frame. Now, from here, I have two ideas regarding corresponding items:

**1. Use items most commonly associated with a mob, specifically an item that is part of the mob's loot table.** For example, rotten flesh is most commonly associated with zombies; bones are most commonly associated with skeletons (or bones to specify wolves and arrows to specify skeletons); ender pearls are most commonly associated with enderman; etc. When the mentioned items are put in the item frames, the Bellethorne will attack only the respective mobs, and not attack everything else, if you have changed the Bellethorne's preference to do so.

**2. Use items from a mob's loot table for specification.** For example, skeletons drop bones and arrows. (To keep things simple, I will not be referencing bows and other potential items.) In my first idea, only bones could be used to specify mobs. However, in my second idea, we can use bones _or_ arrows, since skeletons drop them. Essentially, we are specifying all mobs that drop that item. If we put gunpowder in the item frame, this would specify creepers, witches, and ghasts, since they all drop gunpowder. (The tricky thing with using a mob's loot table is using player-only drops as specification, since the Bellethorne does not cause player-only drops to, well, drop.)

I do not know if this feature has been suggested in the past, but it would prove useful, especially when using the Bellethorne as a home defense to prevent mobs from entering your house, or to keep your animals from dying to the Bellethorne; or additional (complex) automation ideas. Nonetheless, thank you for reviewing my suggestion.

**Comment by williewillus** [comment]
Hmm, why can't you filter your mobs before you pass them to the Bellethorn?

**Comment by Cicopath** [comment]
As stated in my suggestion, it would be cool if the Bellethorne could act as a magical home defense, damaging any hostile mobs, such as zombies, skeletons, creepers, etcetera; yet keeping villagers and pets—or passive mobs in general—unharmed. This would be especially useful during raids.

In an automated setup, I can't think of a specific scenario it would be useful in, other than having the Bellethorne attack _just_ the specified mobs of choice, preventing other mobs from getting harmed when in the Bellethorne's range. But hey, that's why you test the Bellethorne's range and set boundaries.

As I put more thought into it, I think a better suggestion would be to give the Bellethorne an option to attack specifically hostile mobs. (Passive mobs that can become hostile do not count, of course.) It's a much cleaner solution to the idea I have for using the Bellethorne as a house defense system.
