### ISSUE TITLE
Create Zinc not Generating with Orechid

### ISSUE THREAD

**Issue by Awriaan** [Vazkii/Botania#4019]
### Mod Loader

Forge

### Minecraft Version

1.18.1

### Botania version

1.18.1-429

### Modloader version

Forge: 39.1.2

### The latest.log file

https://gist.github.com/Awriaan/19b4161388d86cfcaa52fbd6703e3ff1

### Issue description

I'm playing a custom pack using Garden of Glass and Create, as such Zinc not spawning poses an issue.

### Other information

Create: create-mc1.18.1_v0.4f

**Comment by ramidzkh** [comment]
you can copy [these](https://github.com/ramidzkh/Cinnamon/blob/master/kubejs/data/cinnamon/recipes/orechid/zinc_ore.json) [recipes](https://github.com/ramidzkh/Cinnamon/blob/master/kubejs/data/cinnamon/recipes/orechid/deepslate_zinc_ore.json) into kubejs or a datapack

**Comment by thecommandman0** [comment]
I tried this using a datapack, but I couldn't get it to work. I copied the code and reloaded the game, but the recipe didn't show up, and I couldn't make zinc. I know the datapack works, because I made functional crafting recipes with it, but it won't work for the orechid. I'm on 1.20.1, with some other mods as well. Any idea why it won't work?

**Comment by ramidzkh** [comment]
It seems they changed the orechid recipe format, so replace
```json
  "input": "minecraft:stone",
```
with
```json
  "input": {
    "type": "block",
    "block": "minecraft:stone"
  },
  ```
and same for deepslate, maybe?

**Comment by TheRealWormbo** [comment]
That is correct, you can now use not just block references, but also block states (i.e. block plus properties) and block tags (even excluding certain blocks or other block tags). Botania doesn't use most of these options for its default Orechid recipes, but you can see examples of block tag with exclusion in the Pure Daisy recipe for Livingwood, and block tag without exclusion in the Marimorphoses recipes.
