### ISSUE TITLE
Snowflake Necklace Crashes The Game

### ISSUE THREAD

**Issue by IPicklesI** [Vazkii/Botania#4020]
### Mod Loader

Forge

### Minecraft Version

1.18.2

### Botania version

1.18.2

### Modloader version

Forge 40.0.44

### Modpack info

https://www.curseforge.com/minecraft/modpacks/venturesome

### The latest.log file

<script src="https://gist.github.com/IPicklesI/b781e64584ae049226ff415d06e56786.js"></script>

### Issue description

I put the Snowflake Necklace on and it instantly crashes my game. I can launch the game back up, but if I try to go on the world I had with that Snowflake Necklace on, it just says reading data and then keeps crashing.

### Steps to reproduce

1. Load any game.
2. Put the Snowflake Necklace on.

### Other information

I made this mod pack myself, so I'm not sure if it's my mod pack causing a problem, but I think its the mod.

**Comment by williewillus** [comment]
uhh, your log is a bit weird. Can you try repasting it?

**Comment by IPicklesI** [comment]
yeah of course

**Comment by IPicklesI** [comment]
Alright I updated it.

**Comment by IPicklesI** [comment]
Do you need the first error that pops up when the game crashes? (the error on the launcher) or do you need the crash report?

**Comment by williewillus** [comment]
the debug.log in the game's log folder after it crashes

**Comment by IPicklesI** [comment]
Alright updated it!
