### ISSUE TITLE
Terra blade causes TPS spikes when mana beam is shot

### ISSUE THREAD

**Issue by Virusnest** [Vazkii/Botania#4021]
### Mod Loader

Fabric

### Minecraft Version

1.18.2

### Botania version

430

### Modloader version

Latest as of writing for fabric

### Modpack info

https://cdn.discordapp.com/attachments/927259226034815076/965027136878567514/Modpack2.zip

### The latest.log file

None available as it is not my server but TPS does drop on tab

### Issue description

TPS drops and entitys freeze when using terrablade on the smp that I play on further testing will be done on my side if needed I can link the server owners discord tag

### Steps to reproduce

Use terrablade mana ability
Watch lag spike happen

### Other information

Server side mods are inaccessible to me atm

Edit: written on phone ATM sorry for spelling issues

**Comment by DarianLStephens** [comment]
I'm experiencing the same problem, but only in certain areas, and with any type of mana blast including the Mana Blaster.

**Comment by DarianLStephens** [comment]
The problem does seem to have disappeared for me. I don't know if it still affects the original issue opener, but I haven't seen it in a few months, even in places where it was 100% reproducible before.

**Comment by williewillus** [comment]
if either of you can capture a spark profile while it's happening that would help a lot.

**Comment by dirtbaghippy** [comment]
Happens to me on 1.19.2

**Comment by SireTeddy** [comment]
I already hae the same problem on my own server .. please fix it (since 2/3 month i have this problem )
