### ISSUE TITLE
Putting on certain trinkets almost immediately crashes the game.

### ISSUE THREAD

**Issue by Aquaeyes** [Vazkii/Botania#4024]
### Mod Loader

Fabric

### Minecraft Version

1.18.2

### Botania version

1.18.431

### Modloader version

Fabric-0.13.3, fabric-api-0.51.1

### The latest.log file

https://pastebin.com/spNjHQqq

### Issue description

Attached is the log file, then the latest relevant crash file.

Applying a Snowflake Pendant to the neck trinket slow crashes the game shortly after displaying snowflake particles at the player's feet. Rejoining the world has the problem persist. This does not occur with the other silimar pendants e.g. pyroclast pendant.

### Steps to reproduce

1. Apply Snowflake Pendant to the neck trinket slot.
2. Ice particles will briefly show at the players feet.
3. Game crashes,
4. Loading the world again immediately crashes it.

**Comment by williewillus** [comment]
fixed in next version
