### ISSUE TITLE
Game crashes when equipping Snowflake Pendant into its trinket slot

### ISSUE THREAD

**Issue by takatalvi** [Vazkii/Botania#4034]
### Mod Loader

Fabric

### Minecraft Version

1.18.2

### Botania version

1.18.2-431

### Modloader version

Loader 0.14.4-1.18.2

### The latest.log file

https://pastebin.com/H84brYCP

### Issue description

Hi,

I'm new to modded MC, running a small Fabric server where we use Botania. Yesterday I ran into an issue while equipping a Snowflake Pendant into its slot. I got disconnected and the server gave an error in the console, it's included in the pastebin as the second part. Every time I logged back in, the server disconnected me as timed out, because the item was still in the slot. I had to edit my playerdata file to remove it from my inventory, then I was able to connect. After googling a bit, I found another user reporting the same issue on [Reddit](https://www.reddit.com/r/allthemods/comments/ucy6di/crash_when_loading_into_world_after_equipping/) so I thought I'd post it here. It only happens when you equip the Snowflake Pendant into its trinket slot. It doesn't happen when it's in another inventory slot, it also doesn't happen with any other pendant.

Thanks!

### Steps to reproduce

1. Place the Snowflake Pendant into its respective Trinkets slot.
2. The server disconnects you with an error. In Singleplayer, your game crashes completely.
3. When trying to reconnect, you get timed out. In Singleplayer, your game crashes completely.
4. Removing the item from its slot by editing playerdata resolves this issue.

**Comment by williewillus** [comment]
fixed in the next version, will release today
