### ISSUE TITLE
Renaming /Common/ to /Xplat/ breaks botaniamod.net

### ISSUE THREAD

**Issue by sisby-folk** [Vazkii/Botania#4036]
### Mod Loader

Both Fabric and Forge (I confirm that I have tested both loaders and will specify both loader versions below)

### Minecraft Version

N/A

### Botania version

N/A

### Modloader version

N/A

### The latest.log file

N/A

### Issue description

https://botaniamod.net/lexicon.php

(Apologies for misusing the form! I can't quite find the botaniamod.net source and the commit _just_ happened so)

**Comment by sisby-folk** [comment]
@williewillus RE: df10b660a94eae3f7ecd2d50ca2630c96dcdb78c

**Comment by williewillus** [comment]
fixed, thanks
