### ISSUE TITLE
Avatars with the rod of the unstable reservoir can't kill Gaia's fairies 

### ISSUE THREAD

**Issue by LeoBeliik** [Vazkii/Botania#4039]
### Mod Loader

Both Fabric and Forge (I confirm that I have tested both loaders and will specify both loader versions below)

### Minecraft Version

1.18.2

### Botania version

1.18.2-431

### Modloader version

forge 1.18.2 - 40.1.19 & fabric 0.14.5

### The latest.log file

no

### Issue description

Avatars with the rod of the unstable reservoir try to attack gaia's fairies but don't do damage, they do damage to other mobs and players with the rod of the unstable reservoir can kill the fairies.

https://imgur.com/ki19NuK

### Steps to reproduce

- put a livingwood avatar with a rod of the unstable reservoir near the gaia arena
- summon the gaia
- observe

### Other information

I also tested it with botania alone

**Comment by Hubry** [comment]
Guardian's pixies ignore damage not dealt by players - what is preferred, not targetting them or dealing damage...

**Comment by LeoBeliik** [comment]
In that case will be preferred if they don't target the pixies
