### ISSUE TITLE
[1.18.2] Flowers gen in DimDoors Limbo

### ISSUE THREAD

**Issue by itsdinkd** [Vazkii/Botania#4042]
### Mod Loader

Fabric

### Minecraft Version

1.18.2

### Botania version

all versions for .2

### Modloader version

0.14.2

### Modpack info

AQM 2

### The latest.log file

no log

### Issue description

![image](https://user-images.githubusercontent.com/35115304/168444677-e4f06d14-a33f-4213-a9bf-704a0911299e.png)

Flowers generating in Dimensional Doors limbo when it should not be

**Comment by anoomolu** [comment]
Artemis' comment in https://github.com/VazkiiMods/Botania/issues/3520 shows how you can restrict flower spawning (in your case denying flower spawns in Limbo).
