### ISSUE TITLE
Change marimorphosis to use biome tags

### ISSUE THREAD

**Issue by artemisSystem** [Vazkii/Botania#4044]
### Mod Loader

Both Fabric and Forge (I confirm that I have tested both loaders and will specify both loader versions below)

### Minecraft Version

1.18.2

### Botania version

1.18.2-432

### Modloader version

any

### The latest.log file

-

### Issue description

The Marimorphosis currenty uses biome categories (which to my understanding is on the way out, or at least worse for compatibility) to determine which stones to spawn, this should be changed to use biome tags in 1.18.2.

I might try to make this change myself if i have time, but i'm just noting it here in the meantime.

**Comment by williewillus** [comment]
we tried this when updating but there was some sort of brokenness with how one of the loaders handles dynamic tags (my bet is Forge but I don't remember for sure), but that was in a hurry so maybe there's a solution we can do here.

**Comment by williewillus** [comment]
done in 1.19 c44d5de0a265b576e62512ba274a63aff372a98b
we'll probably want to tweak the contents of the tags later (I don't think I'm even generating those tags yet)
