### ISSUE TITLE
Composite Lens warp force pushes the relays

### ISSUE THREAD

**Issue by LeoBeliik** [Vazkii/Botania#4046]
### Mod Loader

Both Fabric and Forge (I confirm that I have tested both loaders and will specify both loader versions below)

### Minecraft Version

1.18.2

### Botania version

1.18.2-432

### Modloader version

forge 1.18.2 - 40.1.19 & fabric 0.14.5

### Issue description

Composite Lens warp force pushes the relays

Warp + force lens can push relays (and whatever block is link to); In previous versions, this lens only pushed the block the relay was connected to.
also tested with force + warp, which only pushes the relay (as expected).

### Steps to reproduce

craft a Composite mana Lens: warp force
put it on a spreader
aim to a force relay
shoot
observe

**Comment by TheRealWormbo** [comment]
I can confirm this happens on Forge and Fabric, and the force relay seems to forget its binding location after the first hit. Maybe it even forgets the location during the hit already, and the bound block only moves because it was hit by the teleported force burst.
