### ISSUE TITLE
Blocks lose NBT data when absorbed by Black Hole Talisman

### ISSUE THREAD

**Issue by OctupusTea** [Vazkii/Botania#4047]
### Mod Loader

Fabric

### Minecraft Version

1.18.2

### Botania version

1.18.2-432

### Modloader version

Fabric Loader 0.14.5 + Fabric API 0.51.1

### The latest.log file

https://pastebin.com/AhRWmpT7

### Issue description

NBT-storing blocks including shulker box, bee nest and beehive lose the NBT data when absorbed by a Black Hole Talisman.

### Steps to reproduce

Take the shulker box for example:
1. Put down a shulker box in the world.
2. Sneak right-click the shulker box with the Black Hole Talisman in hand to bind it.
3. Put items into the shulker box.
4. Break the shulker box and pick it up.
5. Sneak right-click in the air with the Black Hole Talisman to activate it.
6. The shulker box with items is absorbed by the Black Hole Talisman.
7. Right-click with the Black Hole Talisman to put down the absorbed shulker box in the world
8. The shulker box is empty.

For the bee nest and the beehive, put bees in them instead of items.

### Other information

I would expect the blocks with NBT data to be not absorbed by the Black Hole Talisman, since remembering the NBT data of each block could have some performance impact on the game. It could be excluded in the code (by either blacklisting such blocks entirely or doing an NBT data check before absorption) and/or mentioned in the Lexica Botania that Black Hole Talisman is not suitable for storing such blocks.

**Comment by williewillus** [comment]
Thanks for the report. We should probably just exclude anything with NBT data (or all block entities entirely, but that might be overkill)
