### ISSUE TITLE
Forcing blocks diagonally creates ghost blocks

### ISSUE THREAD

**Issue by LeoBeliik** [Vazkii/Botania#4048]
### Mod Loader

Forge

### Minecraft Version

1.18.2

### Botania version

1.18.2-432

### Modloader version

forge 1.18.2 - 40.1.19

### Issue description

Aiming diagonally a spreader with a force lens moves the block diagonally to it in 2 directions (up and forward), one of the duped blocks is a ghost block.
Doesn't happens if you put a scaffolding on the spreader.

https://discord.com/channels/154261184701267969/977270876200386620/977990228960768060 (video too big for github)

### Steps to reproduce

aim a spreader diagonally to a block
put a force lens on the spreader
shoot the spreader
observe
punch the now duped blocks to see which one is fake

### Other information

this only happens on forge as far as my test showed

**Comment by TheRealWormbo** [comment]
I can't reproduce the ghost blocks in a 1.20.1 version of Botania. Can you confirm whether this still happens for you?

**Comment by LeoBeliik** [comment]
I haven't played botania in a while so no clue, but if you can't repro it , may have been fixed, don't think it was hard to make or anything
