### ISSUE TITLE
While breaking the Altar block, you can see the breaking texture rendering on the items that are on it

### ISSUE THREAD

**Issue by Synthestra** [Vazkii/Botania#4049]
### Mod Loader

Forge

### Minecraft Version

1.18.2

### Botania version

1.18.2-432

### Modloader version

40.1.20

### The latest.log file

No Crash

### Issue description

While breaking the Altar block, you can see the breaking texture rendering on the items that are on it

![Screenshot_12](https://user-images.githubusercontent.com/22637135/169957973-f4acadcb-c7ce-4fbc-b4f3-a52e1d0ad264.png)

### Steps to reproduce

1. Place item on altar
2. Start breaking it
3. See breaking texture

**Comment by williewillus** [comment]
this is because when Minecraft renders a block entity being broken, it simply calls the block entity renderer twice, the second time with the breaking texture. Not sure if this is easy to fix, if not might not be worth fixing.

**Comment by williewillus** [comment]
Okay, I looked into this. I remembered vanilla having a method to control whether a BE is called again with cracking animation or not, but that seems to be gone (probably during the 1.15 refactors). So this is not really worth fixing without a lot of hacks, sorry. It'll be a wontfix.
