### ISSUE TITLE
java.lang.NullPointerException: Key may not be null.

### ISSUE THREAD

**Issue by TheButterbrotMan** [Vazkii/Botania#4051]
### Mod Loader

Fabric

### Minecraft Version

1.18.2

### Botania version

1.18.2-432-FABRIC

### Modloader version

Fabric: Loader 0.14.6 + API 0.53.4+1.18.2

### Modpack info

https://www.curseforge.com/minecraft/modpacks/deathdusk

### The latest.log file

https://bytebin.lucko.me/izU7w4aBfy

### Issue description

I was wandering around, then it crashed.

**Comment by HacoKavanah** [comment]
Got same crash.

**Comment by Andre--D** [comment]
Have the same crash to desktop. Without Botania it seams ok
[crash-2022-10-17_17.59.59-client.txt](https://github.com/VazkiiMods/Botania/files/9804135/crash-2022-10-17_17.59.59-client.txt)

**Comment by TheRealWormbo** [comment]
Likely duplicate of (or strongly related to) #4027. Closing since 1.18 is no longer supported and there are no similar reports for newer versions.
