### ISSUE TITLE
Half-enchanted item not saved?

### ISSUE THREAD

**Issue by uhloin** [Vazkii/Botania#4052]
### Mod Loader

Forge

### Minecraft Version

1.18.2

### Botania version

Botania-1.18.2-432.jar

### Modloader version

Forge 40.1.19

### The latest.log file

-

### Issue description

I started enchantment of diamond boots in Mana Enchanter, close game and when return my half-enchanted boots disappeared. Also there was a Spark attached to Mana Enchanter, it did not disappear.

**Comment by williewillus** [comment]
please reproduce with only botania and its dependencies, and list exact steps to reproduce

**Comment by uhloin** [comment]
Sorry but this is unstable glitch occurred only once in survival world. Later I tried reproduce it in creative mode but without success. I suppose there may be some failure during quit and save process because abnormal termination of Minecraft.

**Comment by uhloin** [comment]
One more similar situation: 4 mana tablets in 3 mana pools were disappeared after exit with Alt+F4 and re-enter.
