### ISSUE TITLE
[1.16] Petal Apothecary can dupe any item

### ISSUE THREAD

**Issue by MuteTiefling** [Vazkii/Botania#4057]
### Mod Loader

Forge

### Minecraft Version

1.16.5

### Botania version

1.16.5-420.2

### Modloader version

Forge 36.2.33

### Modpack info

https://www.curseforge.com/minecraft/modpacks/enigmatica6

### The latest.log file

https://gist.github.com/MuteTiefling/5b27d649fdd81b13514405d685988d01

### Issue description

Petal Apothecary can dupe any item. 

I understand this has been 'fixed' in 1.18 by removing the transformation, but as near as I can tell, there's simply no option for this in 1.16, and no way for a pack maker to resolve it. 

Considering this can dupe absolutely any item in the game, 10 at a time, including shulker boxes full of items... I think this warrants a look. 

### Steps to reproduce

The Petal Apothecary has a weird mechanic to turn it mossy that allows for a very powerful dupe.
To reproduce:

Place a Petal Apothecary
Fill it with water
Throw in any items
Throw in vines
The Apothecary gets emptied, turns mossy, and spits out the items, but they're also still inside its inventory, and the duplicates can be obtained by breaking it.

### Other information

https://github.com/EnigmaticaModpacks/Enigmatica6/issues/4652

**Comment by williewillus** [comment]
We'll look into issuing a hotfix for this, thanks.

**Comment by williewillus** [comment]
Fixed, will issue a hotfix with this (and another bad dupe fix I forgot to release) sometime this week

**Comment by MuteTiefling** [comment]
Awesome thanks!
