### ISSUE TITLE
Game crashes when mana burst hits a mana splitter with another adjacent mana splitter

### ISSUE THREAD

**Issue by GreenBudgie** [Vazkii/Botania#4063]
### Mod Loader

Forge

### Minecraft Version

1.18.2

### Botania version

1.18.2-432

### Modloader version

Forge 40.1.25

### The latest.log file

pastebin.com/S6e7mLtT

### Issue description

When you place a mana splitter next to another mana splitter and mana burst hits one of them the game crashes due to infinite loop.

### Steps to reproduce

1. Place a mana splitter
2. Place another mana splitter adjacent to the first one
3. Hit any mana splitter with a mana burst

**Comment by williewillus** [comment]
fixed in the next botania release
