### ISSUE TITLE
Crash on place/load floating flower

### ISSUE THREAD

**Issue by thetitan555** [Vazkii/Botania#4067]
### Mod Loader

Forge

### Minecraft Version

1.18.2

### Botania version

Botania-1.18.2-433.jar

### Modloader version

Forge 40.1.46

### Modpack info

Custom pack.

### The latest.log file

https://pastebin.com/hr4pHXtq

### Issue description

Game crashes when I place a floating flower or load a world with a floating flower. Tested floating red flower, Thermalily, and MythicBotany's Wither Aconite. 

### Steps to reproduce

Place a floating flower or load a save with a floating flower. The game freezes. The correct small wireframe is present and WAILA displays correctly but model and textures are missing. Then crash.

### Other information

This does not occur in Forge 40.1.30.

**Comment by ripSquid** [comment]
This also happened on my server.

**Comment by MissileMann** [comment]
Hi, just want to add that I am also getting this crash and want to share my logs and crash file to see if it would help.

Mod Loader
Forge

Minecraft Version
1.18.2

Botania version
Botania-1.18.2-433.jar

Modloader version
Forge 40.1.36

Modpack info
Custom pack.

Log: https://drive.google.com/file/d/1DdE_v51FDKdl_SEACU_KsE5Gdyy3I2Oq/view?usp=sharing
Crash: https://pastebin.com/88FaGVrY

If I place one on the server, the server stays up and just says that user disconnected. It only crashes the client

**Comment by MissileMann** [comment]
I made a new profile to check if it happened with just botania and jei and it did. Forge 40.1.36 botannia 433

Log: https://pastebin.com/z084ur4L
Crash: https://pastebin.com/32nv4XRt

**Comment by TheRealWormbo** [comment]
AFAIK this is caused by Forge's `experimentalForgeLightPipelineEnabled` flag being active.

**Comment by NovaLynxie** [comment]
I've had this issue as well, also setting the flag forgeLightPipelineEnabled to false fixed it for me.
