### ISSUE TITLE
Flower pouch removes flowers on sort

### ISSUE THREAD

**Issue by mryusuf5** [Vazkii/Botania#4068]
### Mod Loader

Forge

### Minecraft Version

1.18.2

### Botania version

2-433

### Modloader version

-

### Modpack info

direwolf20

### The latest.log file

-

### Issue description

When you are in your flower pouch, if you use inv tweaks to sort your pouch it removes all flowers except for the blue ones

### Steps to reproduce

1. obtain flower pouch
2. obtain flowers
3. middle mouse button (sort button) click to sort

**Comment by williewillus** [comment]
which sorter mod is it? We should exclude the flower pouch from all of them

**Comment by mryusuf5** [comment]
Simple Inventory Sorter version 19.0.0
