### ISSUE TITLE
Mana Spreaders + ManaPulse entites Need Help

### ISSUE THREAD

**Issue by koalalord9999** [Vazkii/Botania#407]
So, on a server I play on, we have a Plugin called ClearLagg, and it seems to be deleting EntityManaPulse and stopping the mana spreader from firing anymore Mana Pulses. I was wondering if I could get the Entity ID of the mana pulse so I can add it into the clearlagg configs so they stop getting deleted, any ideas?

Below me was the one who found it. Just told me cause I have access to change it

**Comment by BigDrewskii** [comment]
This does not work for me, Any other ideas?
