### ISSUE TITLE
Expose Entity in IHornHarvestable

### ISSUE THREAD

**Issue by DaFuqs** [Vazkii/Botania#4071]
### Mod Loader

Fabric

### Minecraft Version

1.18.2

### Botania version

-

### Modloader version

-

### The latest.log file

-

### Issue description

The parameters in IHornHarvestable currently do specify
`default void harvestByHorn(Level world, BlockPos pos, ItemStack stack, EnumHornType hornType)`

It would be nice to have a reference to the Entity that used that horn to trigger specific logic for that player (such as does it have a specific advancement)

**Comment by williewillus** [comment]
sure
