### ISSUE TITLE
arbitrary entropinnyum consumes tnt

### ISSUE THREAD

**Issue by natedogith1** [Vazkii/Botania#4072]
### Mod Loader

Fabric

### Minecraft Version

1.18.2

### Botania version

1.18.2-431

### Modloader version

Fabric: Loader 0.13.3 + API 0.51.0

### The latest.log file

n/a

### Issue description

When TNT explodes, an arbitrary entropinnyum in range consumes it.  From testing, it seems like it's the first one placed, until you reload and then it seems to be a single random one.

**Comment by williewillus** [comment]
There is no guarantee provided that the closest one will consume it. It's basically up to the order in which the block entities tick.

**Comment by natedogith1** [comment]
My issue is more that if you build something that happens to work with the initial order, it can unexpectedly break when the world reloads.  Making it use closest entropinnyum would be ideal, but even just selecting a random one in range would be an improvement.

**Comment by williewillus** [comment]
well, the problem is that it isn't the tnt selecting the flower, it's the other way around
