### ISSUE TITLE
SMP crash when placing floating flowers

### ISSUE THREAD

**Issue by exciteddog** [Vazkii/Botania#4074]
### Mod Loader

Forge

### Minecraft Version

1.18.2

### Botania version

1.18.2-432

### Modloader version

Forge 40.1.46

### Modpack info

Custom modpack

### The latest.log file

https://paste.ee/p/56mmg

### Issue description

When I would place a floating flower down on the ground (Hopperhock, Munchdew) it crashes my client (not the person who's LAN world I'm on, just mine) and I couldn't get back on his game until he broke the floating flower that I just placed. I placed a screenshot of my mods folder if you would like to know what mods are on the modpack.

![Modlist](https://user-images.githubusercontent.com/107814164/174500168-47eb0212-bb8a-4cd0-b15b-d4deea0963c1.png)
.

### Steps to reproduce

1. Get flower off of my transmutation tablet
2. Make it into a floating flower by crafting it normally
3. Place floating flower on the ground
4. Then it crashes

### Other information

Some other things I would like to mention is that me and my brother are playing on a custom modpack and when I put a floating flower down, it crashes. I got the floating flowers by getting a flower out of my transmutation tablet in my inventory and then making a floating flower out of the flower from my tablet and then placing it down in the world and then it crashes and I couldn't get back on his game, and then he broke the floating flower that caused the crash and then I was able to get back on his game. I don't know if this will help but here is a crash report of the crash.:

[crash-2022-06-19_15.16.05-client.txt](https://github.com/VazkiiMods/Botania/files/8936416/crash-2022-06-19_15.16.05-client.txt)

**Comment by williewillus** [comment]
Can you try on a newer forge version?

**Comment by williewillus** [comment]
Basically forge enabled a buggy option in 46 then patched it later. The upcoming release of Botania will force a dependency on a later forge so that this is resolved.

**Comment by williewillus** [comment]
^ updated botania or forge
