### ISSUE TITLE
"Failed to render lexicon" spam in game log

### ISSUE THREAD

**Issue by flleeppyy** [Vazkii/Botania#4078]
### Mod Loader

Forge

### Minecraft Version

1.16.5

### Botania version

1.16.5-420.2

### Modloader version

36.2.34

### Modpack info

It's a wip modpack and I don't feel like uploading the pack in its current state

### The latest.log file

https://gist.github.com/flleeppyy/c1e90f682d78a0eda49645ecf5be9e53

### Issue description

When choosing the Botania Lexicon from Akashic tome, the same error is repeated hundreds of times per minute.

### Steps to reproduce

1. Add this script

```zs
var akashictome = <item:akashictome:tome>.withTag(
  {
    "akashictome:is_morphing": 1 as byte,
    "akashictome:data": {
      botania: {
        id: "botania:lexicon",
        Count: 1 as byte,
        tag: {
          "akashictome:definedMod": "botania"
        },
        Damage: 0 as short
      },
    }
  }
);

mods.jei.JEI.addItem(akashictome);
```
2. Get an akashic tome
3. Click the Botania lexicon

### Other information

These are the current mods installed (You can see them in the log file but here it is again anyway)

Mods:
  [✔️] AdHooks-1.16.5-6.1.8.1-build.0210
  [✔️] ae2wtlib-0.3.3-1.16.5
  [✔️] AkashicTome-1.4-16
  [✔️] appleskin-forge-mc1.16.x-2.4.0
  [✔️] appliedenergistics2-8.4.7
  [✔️] architectury-1.32.63
  [✔️] Artifacts-1.16.5-2.10.5
  [✔️] AttributeFix-1.16.5-10.1.4
  [✔️] AutoRegLib-1.6-49
  [✔️] BetterCaves-Forge-1.16.4-1.1.2
  [✔️] BetterMineshafts-Forge-1.16.4-2.0.4
  [✔️] BetterPortals-1.16.4-0.3.9
  [✔️] BetterStrongholds-1.16.4-1.2.1
  [✔️] BetterThirdPerson-Forge-1.16.4-1.7.2
  [✔️] BiomesOPlenty-1.16.5-13.1.0.487-universal
  [✔️] Bookshelf-Forge-1.16.5-10.4.32
  [✔️] Botania-1.16.5-420.2
  [✔️] BrandonsCore-1.16.5-3.0.15.248-universal
  [✔️] buildinggadgets-1.16.5-3.8.2
  [✔️] catalogue-1.6.1-1.16.5
  [✔️] CBMultipart-1.16.5-3.0.4.123-universal
  [✔️] cc-tweaked-1.16.5-1.100.6
  [✔️] cfm-7.0.0pre22-1.16.3
  [✔️] ChickenChunks-1.16.5-2.9.1.89-universal
  [✔️] chocolate-1.3.0-1.16.4
  [✔️] ChunkAnimator-1.16.5-1.2.4
  [✔️] ClientTweaks_1.16.3-5.3.0
  [✔️] cloth-config-4.14.64-forge
  [✔️] Clumps-6.0.0.28
  [✔️] CodeChickenLib-1.16.5-4.0.7.445-universal
  [✔️] cofh_core-1.16.5-1.5.0.11
  [✔️] collective-1.16.5-4.28
  [✔️] CommonCapabilities-1.16.5-2.8.0
  [✔️] configured-1.5.2-1.16.5
  [✔️] constructionwand-1.16.5-2.6
  [✔️] Controlling-7.0.0.28
  [✔️] CookingForBlockheads_1.16.5-9.3.4
  [✔️] CosmeticArmorReworked-1.16.5-v5
  [✔️] CraftingTweaks_1.16.5-12.2.1
  [✔️] CraftTweaker-1.16.5-7.1.2.511
  [✔️] create-mc1.16.5_v0.3.2g
  [✔️] Cucumber-1.16.5-4.1.12
  [✔️] culinaryconstruct-forge-1.16.5-4.0.1.0
  [✔️] curios-forge-1.16.5-4.0.8.2
  [✔️] CyclopsCore-1.16.5-1.12.4
  [✔️] DarkUtilities-1.16.5-8.0.14
  [✔️] decorative_blocks-1.16.4-1.7.2
  [✔️] DefaultOptions_1.16.5-12.2.1
  [✔️] doubledoors_1.16.5-3.3
  [✔️] Draconic-Evolution-1.16.5-3.0.26.459-universal
  [✔️] DungeonCrawl-1.16.5-2.3.9
  [✔️] dungeons_plus-1.16.5-1.1.5
  [✔️] elevatorid-1.16.5-1.7.13
  [✔️] endercrop-1.16.5-1.6.0-beta
  [✔️] EnderStorage-1.16.5-2.8.0.170-universal
  [✔️] envirocore-1.16.5-3.0.9.3
  [✔️] enviromats-1.16.5-2.0.9.0
  [✔️] envirotech-1.16.5-3.0.9.4
  [✔️] expandability-2.0.1-forge
  [✔️] fairylights-4.0.5-1.16.5
  [✔️] fancymenu_forge_2.8.0_MC_1.16.2-1.16.5
  [✔️] FarmingForBlockheads_1.16.5-7.3.1
  [✔️] FasterLadderClimbing-1.16.4-0.2.1
  [✔️] FastFurnace-1.16.5-4.5.0
  [✔️] FastWorkbench-1.16.5-4.6.1
  [✔️] ferritecore-2.1.0-forge
  [✔️] FluxNetworks-1.16.5-6.2.1.14
  [✔️] flywheel-1.16-0.2.5
  [✔️] ForgeEndertech-1.16.5-7.2.2.0-build.0202
  [✔️] FpsReducer-forge-1.24-mc1.16.5
  [✔️] ftb-essentials-1605.1.5-build.32
  [✔️] ftb-library-forge-1605.3.4-build.90
  [✔️] goblintraders-1.7.3-1.16.5
  [✔️] gravestone-1.16.5-1.0.7
  [✔️] iChunUtil-1.16.5-10.6.1
  [✔️] ImmersiveEngineering-1.16.5-5.1.0-148
  [✔️] industrial-foregoing-1.16.5-3.2.14.7-16
  [✔️] infernal-expansion-1.16.5-2.4.0
  [✔️] InitialInventory-5.0.3.23
  [✔️] inventorypets-1.16.5-2.0.15
  [✔️] invtweaks-1.16.4-1.0.1
  [✔️] ironchest-1.16.5-11.2.21
  [✔️] jeed-1.16.5-1.6
  [✔️] jei-1.16.5-7.7.1.152
  [✔️] jeiintegration_1.16.5-7.1.0.22
  [✔️] JEITweaker-1.16.5-1.1.0.49
  [✔️] journeymap-1.16.5-5.8.5p5
  [✔️] JustEnoughResources-1.16.5-0.12.1.133
  [✔️] konkrete_forge_1.3.3_MC_1.16.2-1.16.5
  [✔️] kryptonreforged-mc1.16.5_v1.0.0
  [✔️] Ksyxis-Forge1.14thru1.16-1.1
  [✔️] LetSleepingDogsLie-1.16.3-1.1.1
  [✔️] lootr-1.16.5-0.1.12.43
  [✔️] Mantle-1.16.5-1.6.157
  [✔️] mcjtylib-1.16-5.1.7
  [✔️] mcw-bridges-2.0.3-mc1.16.5
  [✔️] mcw-doors-1.0.6-mc1.16.5
  [✔️] mcw-fences-1.0.5-mc1.16.5
  [✔️] mcw-furniture-3.0.0-mc1.16.5
  [✔️] mcw-lights-1.0.3-mc1.16.5
  [✔️] mcw-roofs-2.1.2-mc1.16.5
  [✔️] mcw-trapdoors-1.0.5-mc1.16.5
  [✔️] mcw-windows-2.0.3-mc1.16.5
  [✔️] Mekanism-1.16.5-10.1.2.457
  [✔️] MekanismGenerators-1.16.5-10.1.2.457
  [✔️] MekanismTools-1.16.5-10.1.2.457
  [✔️] mob_grinding_utils-1.16.5-0.4.37
  [✔️] modnametooltip_1.16.2-1.15.0
  [✔️] Morph-1.16.5-10.2.0
  [✔️] Morph-o-Tool-1.4-27
  [✔️] Morpheus-1.16.5-4.2.70
  [✔️] MouseTweaks-2.14-mc1.16.2
  [✔️] MysticalAgriculture-1.16.5-4.2.6
  [✔️] NaturesCompass-1.16.5-1.9.1-forge
  [✔️] Neat 1.7-27
  [✔️] NetherPortalFix_1.16.3-7.2.1
  [✔️] NotEnoughEnergistics-1.16.5-0.1
  [❌] OptiFine_1.16.5_HD_U_G8.jar (disabled)
  [✔️] OreExcavation-1.8.157
  [✔️] Patchouli-1.16.4-53.2
  [✔️] Paxi-Forge-1.16.4-1.0
  [✔️] Placebo-1.16.5-4.7.0
  [✔️] polymorph-forge-1.16.5-0.40
  [✔️] ProjectE-1.16.5-PE1.0.2
  [✔️] ProjectIntelligence-1.16.5-1.1.0.35-universal
  [✔️] Quark-r2.4-322
  [✔️] randompatches-2.4.4-forge
  [✔️] ReAuth-1.16-Forge-4.0.4
  [❌] repurposed_structures_forge-3.4.7+1.16.5.jar (disabled)
  [✔️] rftoolsbase-1.16-2.1.5
  [✔️] rftoolsbuilder-1.16-3.1.11
  [✔️] rftoolsdim-1.16-7.0.21
  [✔️] rftoolspower-1.16-3.0.14
  [✔️] rftoolsstorage-1.16-2.0.19
  [✔️] rftoolsutility-1.16-3.1.16
  [✔️] Scorge-3.1.3
  [✔️] seamless_loading_screen-1.16.5-1.1.7
  [✔️] selene-1.16.5-1.9.0
  [✔️] SimpleSplashScreen-1.16.5-1.3.1
  [✔️] smoothboot-forge-1.16.4-1.2.2
  [✔️] structure_gel-1.16.5-1.7.8
  [✔️] supermartijn642configlib-1.1.4-forge-mc1.16
  [✔️] supermartijn642corelib-1.0.18-forge-mc1.16.5
  [✔️] TConstruct-1.16.5-3.3.4.335
  [✔️] theoneprobe-1.16-3.1.7
  [✔️] thermal_expansion-1.16.5-1.5.0.7
  [✔️] thermal_foundation-1.16.5-1.5.0.14
  [✔️] thermal_innovation-1.16.5-1.5.0.4
  [✔️] titanium-1.16.5-3.2.8.7-22
  [✔️] ToastControl-1.16.5-4.4.0
  [✔️] Translocators-1.16.5-2.6.0.82-universal
  [✔️] trashcans-1.0.15-forge-mc1.16
  [✔️] twilightforest-1.16.5-4.0.870-universal
  [✔️] valkyrielib-1.16.5-3.0.9.5
  [✔️] Waystones_1.16.5-7.6.4
  [✔️] xnet-1.16-3.0.17
  [✔️] YungsApi-1.16.4-Forge-13
  [✔️] YungsExtras-Forge-1.16.4-1.0

**Comment by flleeppyy** [comment]
https://github.com/VazkiiMods/AkashicTome/issues/73

**Comment by quat1024** [comment]
relevant line: https://github.com/VazkiiMods/Botania/blob/e7864c9f8c4877d18d3a32af0aca102b7c75c871/src/main/java/vazkii/botania/client/core/handler/RenderLexicon.java#L160

looks like `ItemLexicon.getTitle` is returning null

https://github.com/VazkiiMods/Botania/blob/e7864c9f8c4877d18d3a32af0aca102b7c75c871/src/main/java/vazkii/botania/common/item/ItemLexicon.java#L86-L95

odd

**Comment by The-Arcanian** [comment]
Still an issue on MC 1.18.2 with Forge 40.2.0, Botania 1.18.2-435, and Akashic Tome 1.5-20.
