### ISSUE TITLE
Add more 1.17/18 stuff to the elementium pick disposal lists

### ISSUE THREAD

**Issue by uhloin** [Vazkii/Botania#4080]
### Mod Loader

Forge

### Minecraft Version

1.18.2

### Botania version

1.18.2-434

### Modloader version

40.1.51

### The latest.log file

-

### Issue description

Terra Shatterer enchanted with Silk Touch combined with Elementium Pickaxe drops Deepslate and inventory is overflowed by garbage very soon. 

List of items for dev/null should be wider... or may be configurable? Could you say may be there is already some config?

List for dev/null should be like this: 
Cobblestone, Stone, Deepslate, Cobbled Deepslate, Netherrack, Basalt, Dirt, Coerced Dirt, End Stone

More useful items to be preserved with Sneak:
Sand, Gravel, Tuff, Calcite, Sandstone, Blackstone, Diorite, Granite, Andesite

Thank you very mush for great mod!

**Comment by uhloin** [comment]
Found:

disposable.json
{
  "replace": false,
  "values": [
    "minecraft:dirt",
    "minecraft:coarse_dirt",
    "minecraft:cobblestone",
    "minecraft:stone",
    "minecraft:netherrack",
    "minecraft:basalt",
    "minecraft:deepslate",
    "minecraft:cobbled_deepslate",
    "minecraft:end_stone",
  ]
}

semi_disposable.json 
{
  "replace": false,
  "values": [
    "minecraft:andesite",
    "minecraft:diorite",
    "minecraft:granite",
    "minecraft:sand",
    "minecraft:gravel",
    "minecraft:tuff",
    "minecraft:calcite",
    "minecraft:sandstone",
    "minecraft:red_sandstone",
    {
      "id": "quark:basalt",
      "required": false
    },
    {
      "id": "quark:jasper",
      "required": false
    },
    {
      "id": "quark:limestone",
      "required": false
    },
    {
      "id": "quark:marble",
      "required": false
    },
    {
      "id": "quark:slate",
      "required": false
    }
  ]
}

**Comment by williewillus** [comment]
Calling this done for now
