### ISSUE TITLE
My flower pouch doesn't take the flowers from the ground

### ISSUE THREAD

**Issue by AlejandroSocasAlvarez** [Vazkii/Botania#4084]
### Mod Loader

Forge

### Minecraft Version

1.18.2

### Botania version

1.18.2-433

### Modloader version

Forge 40.1.51

### The latest.log file

https://github.com/VazkiiMods/Botania/files/9013265/2022-06-29-2.log.gz

### Issue description

When i break flowers the flower pouch doesn't auto collect them and it used to do so.

**Comment by williewillus** [comment]
Make sure you're not holding the pouch, it won't pick up while you're holding it in hand. It's a legacy behaviour we should get rid of honestly.

**Comment by AlejandroSocasAlvarez** [comment]
Thanks
