### ISSUE TITLE
Minecraft keep crashing

### ISSUE THREAD

**Issue by bstlyc** [Vazkii/Botania#4089]
### Mod Loader

Forge

### Minecraft Version

1.18.2

### Botania version

1.18.2.-432

### Modloader version

forge 40.1.30

### Modpack info

valhelsia volitale

### The latest.log file

https://bytebin.lucko.me/Rmaa99KLrS

### Issue description

i cant login to server meanwhille the server still running normally keep crashing when i got into server

**Comment by williewillus** [comment]
Update to a later version of forge, this is fixed there.
