### ISSUE TITLE
materials despawn while terrasteel crafting.

### ISSUE THREAD

**Issue by Frontrider** [Vazkii/Botania#409]
We can not craft any amount of terrasteel because the materials despawn before the process finishes.

We're on build r1.3-138.

**Comment by Murdermancer** [comment]
Just ran into this issue as well. The book does mention that sparks will speed up the process, but the items despawning off the plate feels like more of a bug than a feature when you run into it in-game. Perhaps it would be worth re-wording the entry to warn about this, as I suspect that many users will expect that items added to the plate will not despawn, like with the Infusion Altar.

**Comment by pyure** [comment]
Vazkii, I concur with those above.  If your book says "should use", then it suggests that the spreader method will work, albeit very slowly.  I recommend you either cause the items the items to not despawn, or change the wording.
