### ISSUE TITLE
Alfsteel armor not regenerating health when hunger is full

### ISSUE THREAD

**Issue by bkwalk** [Vazkii/Botania#4099]
### Mod Loader

Forge

### Minecraft Version

1.18.2

### Botania version

1.18.2-434

### Modloader version

Forge 40.1.60

### Modpack info

Custom build

### The latest.log file

https://pastebin.com/wZ303Sam

### Issue description

My health won't regenerate wearing a complete set of Alfsteel armor the way its description says despite not having a full hunger bar.

### Steps to reproduce

1. Crafted initial manasteel armor.
2. Enchanted armor with Protection III on helmet and Protection IV on all the rest. Use enchanting book to affix Thorns III on leggings. I believe Unbreaking is on some of them too.
3. Upgrade to Terrasteel.
4. Upgrade to Alfsteel with all enchantments intact.

**Comment by williewillus** [comment]
Can't reproduce, I got myself below 8  haunches and equipped a full suit of terrasteel armor, and I am regenerating every couple seconds.

**Comment by TheRealWormbo** [comment]
Alfsteel is not a Botania feature. You will have to report that to the Mythic Botany author.

**Comment by bkwalk** [comment]
Terrasteel armor worked. Regen stopped when I upgraded to Alfsteel armor.

**Comment by TheRealWormbo** [comment]
Again, not a Botania issue, as Alfsteel is not a Botania feature. Try here: https://github.com/noeppi-noeppi/MythicBotany/issues

**Comment by bkwalk** [comment]
Ope I’m sorry about that. I found your other message after I sent that. Thank you for the link and taking a look. Have a great weekend.

**Comment by williewillus** [comment]
As you meant the MythicBotany item, redirecting you to their issue tracker
