### ISSUE TITLE
[Feature] disable pebble dropping?

### ISSUE THREAD

**Issue by MSandro** [Vazkii/Botania#4100]
### Mod Loader
Fabric

### Minecraft Version
1.18.2

### Issue description

Am I missing something or where can I prevent Pebbles from dropping?
It would be nice if they could add such a function.

I would like to use GoG but this way of getting Cobblestone is too easy for my Modpack.

**Comment by williewillus** [comment]
I can make it a loot table you can override.

**Comment by MSandro** [comment]
Tyvm
