### ISSUE TITLE
Redstone particles of special flowers appear at effective location, not where the redstone is applied

### ISSUE THREAD

**Issue by TheRealWormbo** [Vazkii/Botania#4102]
### Mod Loader

Forge

### Minecraft Version

1.18.2

### Botania version

1.18.2-434

### Modloader version

Forge: 40.1.54

### Modpack info

Verified with just Botania and its dependencies

### The latest.log file

https://gist.github.com/TheRealWormbo/10d64a7ddd1289b65dae62e631403863

### Issue description

A functional flower on a red stringed spoofer displays its redstone particles on the target flower instead of its own location. That's misleading, because it doesn't actually care about any redstone signals applied to the "spoofed" effective location, only to the actual flower location. Also, if multiple special flowers are spoofed onto the same dummy flower, you can't tell which one is actually disabled.

### Steps to reproduce

1. Place a grass block with e.g. a poppy on top.
2. Place a Red Stringed Spoofer a couple of blocks away, pointing at the poppy.
3. Place a redstone-sensitive functional flower (e.g. Hopperhock) onto the spoofer and satisfy any other needs for it to function (e.g. a chest for hopperhock to deposit items into).
4. Verify that the functional flower works and uses the spoofed location.
5. Apply redstone signal to the spoofer block, e.g. via a lever. – The flower stops working, but the redstone particles are displayed at the spoofed location, not where the redstone signal is actually applied.
6. Repeat steps 2-4 from a different location/direction. Even though the poppy shows redstone particles, that new flower does actually work.
7. Remove the redstone signal and instead apply a redstone signal to the grass block. – Both functional flowers still work and no redstone particles are displayed on any flowers.

**Comment by williewillus** [comment]
This is intended.

**Comment by williewillus** [comment]
Basically, pretty much all particles emitted by a flower should be based on its effective location, so you know where things are actually active. I do see your point about multiple flowers in one spot though. Not sure of a good solution.
