### ISSUE TITLE
Implement Fabric transfer API support for Corporea

### ISSUE THREAD

**Issue by MattiDragon** [Vazkii/Botania#4107]
### Mod Loader

Fabric

### Minecraft Version

1.18.2

### Botania version

1.18.2-434-FABRIC 

### Modloader version

Loader: 0.14.9 Api: 0.58.0+1.18.2

### Modpack info

Extended Drawers 1.3.3+mc1.18.2

### The latest.log file

https://pastebin.com/eJ20S58M

### Issue description

Corporea sparks can't be attached to blocks from extended drawers. I suspect it's because I exclusively use the fabric transfer api, but I can't confirm it as the corporea code really confuses me. 

### Steps to reproduce

1. Set up a corporea network
2. Place down a drawer
3. Fail trying to connect the drawers

### Other information

Originally reported here: MattiDragon/extendeddrawers#18

**Comment by williewillus** [comment]
ah yeah, I haven't implemented corporea integration with the transfer api yet.

**Comment by artemisSystem** [comment]
@williewillus is this something we want to do before 1.19 release?

**Comment by williewillus** [comment]
Yeah. Last time I checked, the transfer API had some dumb stuff that throws if it's ever touched on the client (which Botania does sometimes), so you'd have to check if that's resolved yet.

**Comment by williewillus** [comment]
I'm going to prioritize this out of the 1.19.2  release

**Comment by williewillus** [comment]
77d42a7c699d7e146fb7d4b0f911378fc52e3e97
