### ISSUE TITLE
Lexica Botania: Vine ball entry outdated

### ISSUE THREAD

**Issue by Yadokingu** [Vazkii/Botania#4110]
### Mod Loader

Forge

### Minecraft Version

1.18.2

### Botania version

1.18.2-434

### Modloader version

Forge: 40.1.68

### Modpack info

ATM7

### The latest.log file

-

### Issue description

The vine ball entry states that vanilla vines can't be climbed without support blocks, when free hanging vanilla vines have been climbable for many versions now.

**Comment by williewillus** [comment]
I'm not sure what you mean. I just placed some vanilla vines without any support blocks and I just walk right through them, I don't climb them. Are you sure you don't have another mod doing that?

**Comment by Yadokingu** [comment]
> I'm not sure what you mean. I just placed some vanilla vines without any support blocks and I just walk right through them, I don't climb them. Are you sure you don't have another mod doing that?

You have to hold the spacebar to climb them. Same as with free standing weeping and twisting vines. You can even do it in vanilla without any mods installed.

**Comment by artemisSystem** [comment]
Can confirm. I'll send a patch to update this documentation
