### ISSUE TITLE
Crash when loading my modpack with botania

### ISSUE THREAD

**Issue by Carlguzmantrebu** [Vazkii/Botania#4111]
### Mod Loader

Forge

### Minecraft Version

1.18.2

### Botania version

1.18.2-434

### Modloader version

Forge: 40.1.68 

### The latest.log file

https://gist.github.com/Carlguzmantrebu/28da9f41e83b76420ada5c954f312d98

### Issue description

My modpack works fine, but whean I add botania and quark it crashes. I have tried with all the 1.18.2 versions of the mods, but doesn't work anyone. I'm writing here for help.
[hs_err_pid37996.log](https://github.com/VazkiiMods/Botania/files/9300733/hs_err_pid37996.log)
[crash-2022-08-10_16.07.12-client.txt](https://github.com/VazkiiMods/Botania/files/9300740/crash-2022-08-10_16.07.12-client.txt)
 

### Other information

 titanium-1.18.2-3.5.6-38
 badpackets-forge-0.1.2
 ftb-library-forge-1802.3.6-build. 140
Iceberg-1.18.2-1.0.44
 selene-1.18.2-1.17.9
supermartijn642corelib-1.0.19-forge-mc1...
 balm-3.2.0+0
 geckolib-forge-1.18-3.0.33
 LibX-1.18.2-3.2.18
 feature_nbt_deadlock_be_gone_forge-2.0...
 Mantle-1.18.2-1.9.27
 tl_skin_cape_forge_1.18_1.18.2-1.25
 tombstone-7.4.11-1.18.2
 mcw-roofs-2.1.2fabric-mc1.18.2
mcw-doors-1.0.6fabric-mc1.18.2
repurposed_structures_forge-5.1.14+1.18.2,
 Blood Magic-1.18.2-3.2.3-38
 polymorph-forge-1.18.2-0.44
 CyclopsCore-1.18.2-1.16.0
 MekanismAdditions-1.18.2-10.2.5.465
 MekanismTools-1.18.2-10.2.5.465
MekanismGenerators-1.18.2-10.2.5.465
 industrial-foregoing-1.18.2-3.3.1.4-8
 flywheel-forge-1.18-0.6.4
 supplementaries-1.18.2-1.4.8
 Al-Improvements-1.18.2-0.5.0
 create-mc1.18.2_V0.5.0c
 trashcans-1.0.15-forge-mc1.18
 Immersive Engineering-1.18.2-8.1.0-150
Aquaculture-1.18.2-2.3.7
 twilightforest-1.18.2-4.1.1220-universal
 appliedenergistics2-11.1.5
 TConstruct-1.18.2-3.5.1.31
 Storage Drawers-1.18.2-10.2.1
 ironchest-1.18.2-13.1.9
 waystones-forge-1.18.2-10.1.0
Quark-3.2-358
Botania-1.18.2-434
reliquary-1.18.2-2.0.12.1143
EpicFight-18.2.6-beta
backpacked-2.1.10-1.18.2
rubidium_extras-1.18.2_v1.3.1
RoughlyEnoughltems-8.3.519
RoughlyEnoughltems-jei-internals-worka...
dynamiclightsreforged-1.18.2_v1.3.3
CreativeCore_FORGE_V2.6.12_mc1.18.2
mutil-1.18.2-4.5.0
Control Engineering-0.1.1
fetransformer-1.18.2-1.1.1
 More MekanismProcessing-1.18.2-2.4
 vanillaplustools-1.18.2-1.0
PlayerRevive_FORGE_V2.0.1_mc1.18.2
tetra-1.18.2-4.9.3
expandability-6.0.0
 VampiresNeed Umbrellas-1.18.2-1.0
 Vampirism-1.18.2-1.8.4
 Shrink-1.18.2-1.3.3
 elevatorid-1.18.2-1.8.4
 DungeonCrawl-1.18.2-2.3.10

artifacts-1.18.2-4.1.0
 Incendium_v5.0.4
 [1.18.2]+SecurityCraft+v1.9.3
 carryon-1.18.2-1.17.0.8
 simpleplanes-1.18.2-4.14.1
 corpse-1.18.2-1.0.1
 camera-1.18.2-1.0.4
 Jade-1.18.2-forge-5.2.3
 modernlife-1.18.2-1.54
 hexerei-0.2.2
 Mmmmmmmmmmmm-1.18.2-1.5.2
createaddition-1.18.2-20220712a
findme-3.0.6-forge

**Comment by williewillus** [comment]
This isn't a Botania issue, you're missing AutoRegLib as a dependency for another mod (probably Quark)

**Comment by Carlguzmantrebu** [comment]
Oh, ok, I will try it, Thanks for your attention
