### ISSUE TITLE
Breaking mossy petal apothecary drops regular petal apothecary

### ISSUE THREAD

**Issue by Nevrai** [Vazkii/Botania#4114]
I broke a mossy petal apothecary with my (Silk Touch) pickaxe, and it dropped a regular one. I don’t know if this is because I had Silk Touch or if it would’ve done it regardless, but either way, it’s definitely a bug.

### Versions
* **Modpack:** [All the Mods 7](https://www.curseforge.com/minecraft/modpacks/all-the-mods-7/files/) (version 0.4.25—latest)
* **Minecraft:** 1.18.2
* **Forge:** 40.1.68
* **Botania:** 434 (latest)

**Comment by williewillus** [comment]
Thanks for the report, this is leftover from when the mossy apothecary used to not be obtainable in item form. Should be an easy fix.

**Comment by Nevrai** [comment]
Thanks for the fix!
