### ISSUE TITLE
ATM7 Game crash at startup

### ISSUE THREAD

**Issue by SeanEhle** [Vazkii/Botania#4116]
### Mod Loader

Forge

### Minecraft Version

1.18.2

### Botania version

1.18.2-435

### Modloader version

Forge 40.1.68

### Modpack info

https://www.curseforge.com/minecraft/modpacks/all-the-mods-7/files/3939924

### The latest.log file

https://pastebin.com/Dw1REEPi

### Issue description

Game crashes when loading world at startup.

### Steps to reproduce

1. Load game
2. Wait until it starts rendering in-game world.
3. Watch as the chunks load in the Botania build
4. Cry 'cause game crash.

### Other information

Any assistance at saving this game world would be absolutely appreciated.

**Comment by SeanEhle** [comment]
I made a mistake in there, and I don't know how to correct it.
I accidentally put the crash report under The latest.log file.
However, the actual latest.log file is over 1.6 MB, and pastebin limit is less than 1/3 of that.

How do I fix?

**Comment by williewillus** [comment]
It's a mythicbotany bug, they're using botania internals (again) and so get hosed whenever I make changes. Please report to them instead.
