### ISSUE TITLE
Botania [forge1.16.5] makes KemonoCraft's interactive features unusable

### ISSUE THREAD

**Issue by qq1033142** [Vazkii/Botania#4119]
### Mod Loader

Forge

### Minecraft Version

1.16.5

### Botania version

1.16.5-420.2

### Modloader version

forge:36.2.34

### The latest.log file

no log file

### Issue description

Botania [forge1.16.5] makes KemonoCraft's interactive features unusable,such as feeding the catgirl, opening the catgirl's backpack, and petting the catgirl.

### Steps to reproduce

1.Feed three japariman to catgirl's mouth to tame.
2.Use shit+right mouse button on the tamed catgirl to open the backpack.
3.Right mouse button to pet the tamed catgirl.

### Other information

KemonoCraft-1.16.4-0.3.22

**Comment by williewillus** [comment]
Your steps to reproduce are incomplete. What happens? What makes you think it's Botania?

**Comment by qq1033142** [comment]
I&nbsp;tested&nbsp;this&nbsp;bug.&nbsp;Only&nbsp;three&nbsp;mods&nbsp;are&nbsp;loaded,&nbsp;one&nbsp;is&nbsp;KemonoCraft,&nbsp;the&nbsp;other&nbsp;two&nbsp;are&nbsp;Patchouli&nbsp;and&nbsp;Botania. When&nbsp;Botania&nbsp;is&nbsp;loaded，I Can't&nbsp;feed&nbsp;catgirls ,&nbsp;can't&nbsp;open&nbsp;their&nbsp;backpacks,&nbsp;can't&nbsp;pet&nbsp;them; When&nbsp;removed&nbsp;from&nbsp;Botania, I can do&nbsp;the&nbsp;above&nbsp;operations.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Vincent ***@***.***&gt;; 
发送时间: 2022年8月21日(星期天) 凌晨0:06
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [VazkiiMods/Botania] Botania [forge1.16.5] makes KemonoCraft&#39;s interactive features unusable (Issue #4119)





 
Your steps to reproduce are incomplete. What happens? What makes you think it's Botania?

**Comment by qq1033142** [comment]
> Your steps to reproduce are incomplete. What happens? What makes you think it's Botania?

I tested this bug. Only three mods are loaded, one is KemonoCraft, the other two are Patchouli and Botania. When Botania is loaded，I Can't feed catgirls , can't open their backpacks, can't pet them; When removed from Botania, I can do the above operations.

**Comment by qq1033142** [comment]
I found new KemonoCraft-1.16.5 version and  Botania has no effect on it anymore.

**Comment by qq1033142** [comment]
I found new KemonoCraft-1.16.5 version and Botania has no effect on it anymore.
