### ISSUE TITLE
crash [Botania-1.16.5-420.2]

### ISSUE THREAD

**Issue by qq1033142** [Vazkii/Botania#4123]
### Mod Loader

Forge

### Minecraft Version

1.16.5

### Botania version

1.16.5-420.2

### Modloader version

Forge:36.2.34 or Forge:36.2.35

### The latest.log file

https://pastebin.com/vYU1KAfS

### Issue description

The game client crashes frequently, but it only happens in the block where the mana is generated, and the place far from this block will not crash.
For details, please see the crash report. There are three reports in total, and I only uploaded one of them.

**Comment by TheRealWormbo** [comment]
Closing since 1.16 is no longer supported and this is probably some kind of mod conflict.
