### ISSUE TITLE
Elementium Axe drops unnamed head, causes crash to desktop when head is held.

### ISSUE THREAD

**Issue by itanshi** [Vazkii/Botania#413]
Elementium Axe drops unnamed player head. When held in the hotbar, a crash to desktop occurs until someone else can do /clear [player] 397 3 as soon as they spawn in to get rid of the head.

This occurs on dw20 1.0.1 and any later version of Botania without another mod.
I'll provide a crash log/s for them hopefully soon as I'm third wheel to this.

**Comment by immortaleeb** [comment]
Has this issue been fixed yet?
I just got a report from a user who had this problem on our server and I had to manually remove the head from his inventory because he couldn't login without crashing otherwise.
We're running R1.3 153, but I couldn't find anything about this bug in the changelogs.

**Comment by Vazkii** [comment]
I haven't fixed it because I don't have any info to go on. No logs or anything and I can't reproduce the issue.

**Comment by rubensworks** [comment]
Here is the crash log: http://pastebin.com/v4r55E6K
The crash is only client-side. It happens the moment the player picks up the dropped player head on its hotbar. So it has something todo with rendering. My guess is that the meta/NBT value of the skull is somehow invalid.

**Comment by Vazkii** [comment]
I'll have a look at it sometime then.
