### ISSUE TITLE
Botania causing crashing on startup 

### ISSUE THREAD

**Issue by QueenDD** [Vazkii/Botania#4130]
### Mod Loader

Forge

### Minecraft Version

1.7.10

### Botania version

Botania r1.8-249

### Modloader version

Forge 10.13.14

### Modpack info

Nope

### The latest.log file

https://pastebin.com/DvYhH7XP

### Issue description

Botania suddenly started crashing my game out of no where and revealing this message. It works with older versions of Botania or when its deleted. I dont have IE (Immersive Engineering). I've tried to fix this but cant.

### Other information

None

**Comment by williewillus** [comment]
1.7 is not supported.
