### ISSUE TITLE
Ice pendant causes ticking player error and prevents player from rejoining (possible incompat)

### ISSUE THREAD

**Issue by Tempest-5ky** [Vazkii/Botania#4140]
### Mod Loader

Fabric

### Minecraft Version

1.18.2

### Botania version

1.18.2-434

### Modloader version

Fabric loader 0.14.9 + API 0.58.0

### The latest.log file

https://mclo.gs/lRbrVNM 

### Issue description

When a player puts on an Ice Pendant they get kicked from the server and can't rejoin. The specific error is here: https://mclo.gs/FDTDIwU

Though you can see it at the end of the latest.log provided!
I'm thinking it's an incompatibility with the Puddles mod, based on the log. https://www.curseforge.com/minecraft/mc-mods/motschens-puddles
From what I can see, the implementation of the frost walker effect on the pendant clashes with something on the Puddles mod's end.

### Steps to reproduce

1. Install Botania and dependencies alongside Motschen's Puddles on a server
2. Put on the ice pendant
3. observe

**Comment by williewillus** [comment]
The frost walker effect on the Ice Pendant simply directly calls vanilla's Frost Walker enchantment code. Can you try with a pair of Frost Walker boots as well? If it still crashes, then that's a bug to report to the Puddles mod.

**Comment by Tempest-5ky** [comment]
Will do!

**Comment by Tempest-5ky** [comment]
Seems to have been an issue with Puddles! Sorry and thank you for your time
