### ISSUE TITLE
Botania + FTB Chunks

### ISSUE THREAD

**Issue by NordicGamerFE** [Vazkii/Botania#4148]
### Mod Loader

Fabric

### Minecraft Version

1.18.2

### Botania version

1.18.2-435

### Modloader version

Fabric 0.14.9 + Fabric API 0.58.0

### Modpack info

https://www.curseforge.com/minecraft/modpacks/all-of-fabric-5

### The latest.log file

N/A

### Issue description

You can use the mana pool and elven portal in ftb claims, I would like to report this directly to them but seems to have no way to actually do so

**Comment by williewillus** [comment]
If you mean by tossing items in them, it's unclear to me how you would permission-gate this.

**Comment by baum3001** [comment]
There would need to be a Toggle on the side of FTBChunks for dropping items, which existed in earlier Versions I think

**Comment by anoomolu** [comment]
Closing this, as it's on FTB Chunks' side to prevent the dropping of items in claims.
