### ISSUE TITLE
Server crash on startup

### ISSUE THREAD

**Issue by Aleksandr-Dolganov** [Vazkii/Botania#4150]
### Mod Loader

Forge

### Minecraft Version

1.18.2

### Botania version

1.18.2-434

### Modloader version

Forge: net.minecraftforge:40.1.73

### Modpack info

https://www.curseforge.com/minecraft/modpacks/create-vanilla-exploration

### The latest.log file

https://pastebin.com/K5znjWbJ

### Issue description

We have server with this modpack on Bisect.
A few days ago server start to crashing on startup.
We thinks it's botania, but we not 100%  sure

**Comment by TheRealWormbo** [comment]
Going to close this for the following reasons:
- 1.18 is not supported anymore
- This is a watchdog timeout crash, i.e. the server stalled for too long (here: 1 minute), which could have all kinds of reasons and Botania logic probably just happened to be one of the too many things that are going on there
