### ISSUE TITLE
[1.7.10] Crash when using Shard of Laputa

### ISSUE THREAD

**Issue by Shahelion** [Vazkii/Botania#4154]
### Mod Loader

Forge

### Minecraft Version

1.7.10

### Botania version

r1.8-249

### Modloader version

7.99.40.1614

### Modpack info

Custom modpack. Mod list: https://gist.github.com/Zsashas/ab8e2fa5b519cb5af888c16721e89697

### The latest.log file

https://gist.github.com/Zsashas/10f3cd02bc01b99cb0c9ab472440e261

### Issue description

Now, first off, I know this is an unsupported version. I'm just looking for a little direction as to which mod might be responsible, since I'm pretty sure it's another mod breaking this. I have my suspicions, but I might be completely wrong.

The instant I right-click with any level of Shard of Laputa on a block, the game crashes. Every time, simple as that. It's worked before on this version, but I haven't used a Shard in so long that the modpack is entirely different from what it was then.

### Steps to reproduce

1: Give yourself a Shard of Laputa
2: Try to use it
3: Crash!

**Comment by williewillus** [comment]
> java.lang.NoClassDefFoundError: vazkii/botania/api/mana/ILaputaImmobile

What I suspect is that another mod is packaging the Botania API classes in its jar file, which was common practice in the 1.7 era. The API they packaged got loaded first, but was outdated and doesn't have this interface.

It's going to be rough but you can look in each mod jar and see if they have a folder like `vazkii/botania/api` in it. If so, delete it in all jars except for the main Botania jar. If you can program, you can write a script to assist you in this scan as well.

**Comment by Shahelion** [comment]
Looks like it was Tombenpotter's Icarus. If I delete the jar folder, will this affect the mod in any real way? Or will it be unaffected since I have Botania itself?

**Comment by williewillus** [comment]
If you have Botania itself as well, then you can safely delete the `vazkii/botania/api` folder from the Icarus mod jar, yeah.

**Comment by Shahelion** [comment]
Looks like that wasn't the issue, but no other mods have the Botania API in them.

**Comment by williewillus** [comment]
I don't know what's going on, then.

**Comment by TheMadmanofChaos** [comment]
I would recommend binary elimination. Remove half the mods(Sans Botania,  of course),  make a test world to see if the shard causes a crash. If is does, remove another half of the remaining mods. If it doesn't, one of the mods you last removed is the culprit. Begin re-intigrating and removing mods in smaller and smaller half batches until you have narrowed it down to one. 

Then you can either see if it has an updated version, an api file you missed, or just cut both your losses and the mod by removing it.

**Comment by williewillus** [comment]
Follow that ^. Closing this since 1.7 has been out of support for 6 years
