### ISSUE TITLE
[Mod Incompatibility] Some items don't work with Better Combat

### ISSUE THREAD

**Issue by bassistracer** [Vazkii/Botania#4156]
### Mod Loader

Fabric

### Minecraft Version

1.18.2

### Botania version

1.18.2-435

### Modloader version

0.14.9 + API 0.58.0 

### The latest.log file

N/A

### Issue description

When paired with Better Combat, the swinging animations for Better Combat do not allow weapons (like the Terra Blade, basically any weapon with a projectile) to fire its projectile. This doesn't seem to be an issue with Better Combat itself, as for example, Simply Swords's Chakram allows you to toss it while still using Better Combat animations.
Not exactly sure if this belongs here. If not, sorry.

### Steps to reproduce

1. Download Botania & Better Combat 
2. Let Better Combat's Fallback Compatibility apply to the Botania weapons (should be done by default)
3. Get a Terra Blade and swing it to test it

### Other information

https://www.curseforge.com/minecraft/mc-mods/better-combat-by-daedelus

**Comment by Warhand** [comment]
Iirc this is actually an issue with better combat, since better combat cancels the left click event, which is what botanias weapons use to know when they should do their effects on attack

**Comment by Dr-WeiAL** [comment]
> Iirc this is actually an issue with better combat, since better combat cancels the left click event, which is what botanias weapons use to know when they should do their effects on attack

But if the melee hit the target will fire its projectile, feeling that this problem can only be compatible by Botania

**Comment by Dr-WeiAL** [comment]
I found that this problem has been solved, probably because BetterCombat has made changes to the attack method, in any case, you can launch the projectile normally
![image](https://user-images.githubusercontent.com/47446553/206894111-1027804c-06df-4b8a-a8aa-907694edaf5f.png)

**Comment by williewillus** [comment]
ok, thanks

**Comment by Dr-WeiAL** [comment]
> ok, thanks

I found the problem, although the Terra Blade projectile is normal, but Starcaller does not summon meteors
So this issues may have to be reopened

**Comment by Cicopath** [comment]
Currently playing on Prominence II RPG v2.8.7 on Fabric 1.20.1-0.5.11 with Botania 1.20.1-444 and Better Combat 1.8.3 and it still seems to be an issue with the Terra Blade and Starcaller. Haven't yet tried it with the newest versions of both (445 for Botania and I think 1.8.6 for Better Combat).

**Comment by anoomolu** [comment]
> Currently playing on Prominence II RPG v2.8.7 on Fabric 1.20.1-0.5.11 with Botania 1.20.1-444 and Better Combat 1.8.3 and it still seems to be an issue with the Terra Blade and Starcaller. Haven't yet tried it with the newest versions of both (445 for Botania and I think 1.8.6 for Better Combat).

If it's happening on the latest release and you're able to provide steps to reproduce the problem then feel free to make a new issue
