### ISSUE TITLE
Hidroangeas don't produce mana

### ISSUE THREAD

**Issue by AlejandroSocasAlvarez** [Vazkii/Botania#4158]
### Mod Loader

Forge

### Minecraft Version

1.18.2

### Botania version

1.18.2-433

### Modloader version

Forge 40.1.51

### Modpack info

https://drive.google.com/drive/folders/1wy42RAeuTCvRIlwknVl5twsphklCWjrL?usp=sharing

### The latest.log file

https://github.com/VazkiiMods/Botania/files/9591751/2022-09-16-2.log.gz

### Issue description

I don't see mana produced by 2 hidroangeas in a diluted mana pool.

### Steps to reproduce

1.Place an hidroangea in the middle of a 3x3 pool.
2.Place the other one next to the pool.
3.Connect a mana-spreader next to the second hidroangea and connect it to both.
4.Connect the mana-spreader to a diluted mana pool.

**Comment by williewillus** [comment]
Show a screenshot of your setup, please. The flower and water need to be at the same y level
