### ISSUE TITLE
Pure Daisy randomely vanished and turned into Botania Flower

### ISSUE THREAD

**Issue by LunaHD24** [Vazkii/Botania#4160]
### Mod Loader

Forge

### Minecraft Version

1.12.2

### Botania version

r1.10-360

### Modloader version

Forge - 14.23.5.2808

### Modpack info

https://www.curseforge.com/minecraft/modpacks/equivalent-skies/files/2665045

### The latest.log file

https://gist.github.com/LunaHD24/81fc3388cdb984d4bbcf5ed5dce28e37

### Issue description

I don't know what excactly happened, i opened the quest book, clicked on Detect/Submit and my Pure Daisy was gone. And then the Botania Flower was on the ground.

**Comment by williewillus** [comment]
Please report to your pack, 1.12 is out of support
