### ISSUE TITLE
tntchao

### ISSUE THREAD

**Issue by ghost** [Vazkii/Botania#4161]
### Mod Loader

Forge

### Minecraft Version

1.15.1

### Botania version

1.15.1.-312

### Modloader version

Forge

### Modpack info

ffsaef

### The latest.log file

ffsaef

### Issue description

ffsaef

### Steps to reproduce

ffsaef

### Other information

ffsaef

**Comment by williewillus** [comment]
what?

**Comment by ghost** [comment]
a
