### ISSUE TITLE
Add dedicated tags for horns

### ISSUE THREAD

**Issue by artemisSystem** [Vazkii/Botania#4170]
We should add tags like `botania:horn_of_the_wild_breakable` or something instead of using hardcoded vanilla tags. https://github.com/VazkiiMods/Botania/blob/cad5d35d9906322ecbf8d0c7d00198f2cd3bf75f/Xplat/src/main/java/vazkii/botania/common/item/HornItem.java#L99-L104

**Comment by williewillus** [comment]
Note that this can only be done for the canopy and covering horns, that `instanceof BushBlock` for Wild is something I want so that it covers all modded bushblocks (a lot of them)
