### ISSUE TITLE
Non-eucludian lenses textures

### ISSUE THREAD

**Issue by Aegide** [Vazkii/Botania#4180]
### Mod Loader

Fabric

### Minecraft Version

1.19.2

### Botania version

1.19.2-436

### Modloader version

Fabric 0.14.9

### Issue description

<br><br>

# Context

Depending of where i am located at and how i look at a mana lens (_mounted on a mana spreader_), sometimes i see some textures and sometimes i don't.

# Expected - Visible

![image](https://user-images.githubusercontent.com/43409914/197526459-f75477b7-fd58-4b74-8e25-937ff228123d.png)

![image](https://user-images.githubusercontent.com/43409914/197527170-08a8459f-e9ef-465a-b459-9ac29044a220.png)

<br>

# Unexpected - Invisible 
![image](https://user-images.githubusercontent.com/43409914/197526512-d3d72717-7175-4f4c-85e1-a7a3dcb368b9.png)

![image](https://user-images.githubusercontent.com/43409914/197527086-c6f0ee6f-0013-4b48-8f59-f7564517207f.png)

<br>

### Steps to reproduce

1. Place a block
2. Place spreader on that block
3. Place a lens on that spreader (_exemple: influence lens or flare lens_)
4. Move around and look at the lens

**Comment by artemisSystem** [comment]
I don't think this is something we can fix, really. Same bug that for example makes mana in mana pools invisible behind managlass, or something like that. Can you try it on fabulous graphics and see if it looks correct there?

**Comment by Aegide** [comment]
It seems like the "fabulous graphics" doesn't change anything xd

![image](https://user-images.githubusercontent.com/43409914/198114753-9097b7ed-96be-4f1c-89cb-384c06566b23.png)

**Comment by Aegide** [comment]
Fun fact about  warp lenses.

They always look good from the left side, but not from the right side.

![image](https://user-images.githubusercontent.com/43409914/198116067-5290e3a6-601c-4a97-9415-4c7f5986da4f.png)

![image](https://user-images.githubusercontent.com/43409914/198116174-215ff42c-8474-4b6f-9e24-4bca85a01709.png)


The setup i used :

![image](https://user-images.githubusercontent.com/43409914/198116737-8f1ca229-c1a7-4667-a7ae-394071a42180.png)

**Comment by williewillus** [comment]
this is just how the item model generator works. It doesn't show up much in vanilla because vanilla doesn't have many translucent items (or any at all?). We can't do anything here I think unless we painstakingly carve out the shape of the glass for every lens model specifically (not sure if it'll work even then)

**Comment by Aegide** [comment]
I thought about that possibility, that there was nothing that Botania could do because it's caused by vanilla mechanics.
