### ISSUE TITLE
[1.19] Mana bar is not rendered over XP bar

### ISSUE THREAD

**Issue by Quipex** [Vazkii/Botania#4188]
### Mod Loader

Forge

### Minecraft Version

1.19.2

### Botania version

latest 1.19.x: https://github.com/VazkiiMods/Botania/tree/b5012dfddbb0ff4998cd321734e16d84e99556af

### Modloader version

43.1.47

### The latest.log file

no logs

### Issue description

When wearing a mana ring and a full set of manasteel armor and other mana consumables, the mana bar is not being drawn over the XP bar. I've tried to debug and it shows [here](https://github.com/VazkiiMods/Botania/blob/1.19.x/Xplat/src/main/java/vazkii/botania/client/gui/HUDHandler.java#L228) that width is not 0, but no bar is rendered

### Steps to reproduce

1. Wear a mana ring full of mana
2. Wear items that consume mana

**Comment by Quipex** [comment]
After some debugging, it seems like the problem is that mana bar is rendered underneath the vanilla gui that's why it can't be seen

**Comment by williewillus** [comment]
Just to be sure, this doesn't happen on fabric?

**Comment by Quipex** [comment]
Yes, on Fabric it's fine
