### ISSUE TITLE
Item placed too high for Corporea Crystal Cube

### ISSUE THREAD

**Issue by Aegide** [Vazkii/Botania#4192]
### Mod Loader

Fabric

### Minecraft Version

1.19.2

### Botania version

1.19.2-436

### Modloader version

Fabric 0.14.9

### Issue description

Perhaps the "item" could be placed lower.

![image](https://user-images.githubusercontent.com/43409914/198397337-ddd888fb-45dd-4a85-b5e8-497ae0b78903.png)

**Comment by williewillus** [comment]
The problem is the item entity has its own bobbing which is not lined up with the cube's bobbing.
One idea would be to lock the item entity's age at zero, but then that inhibits the spinning as well.
