### ISSUE TITLE
Apothecary right click consumption bug

### ISSUE THREAD

**Issue by Aegide** [Vazkii/Botania#4195]
### Mod Loader

Fabric

### Minecraft Version

1.19.2

### Botania version

1.19.2-436

### Modloader version

Fabric 0.14.9

### Issue description

Only water-filled apothecaries are affected, if the player's hand is empty.

Empty apothecaries and lava-filled apothecaries are unaffected.

![apothecary](https://user-images.githubusercontent.com/43409914/198403755-bc9f3dfd-9e41-4fdb-8593-c06e3bba4cb0.gif)

**Comment by Quipex** [comment]
I'm curious what behavior is expected? Right-clicking should refill the apothecary with the prev recipe if the last craft happened in the last 20s as far as I remember.

**Comment by Aegide** [comment]
There is no previous recipe, and i have nothing in my hand.

So i expect "nothing" to happen, instead of that right-click interaction.

**Comment by LeoBeliik** [comment]
Note, this also happens with empty Rune altars
