### ISSUE TITLE
Can't place water in apothecary

### ISSUE THREAD

**Issue by artemisSystem** [Vazkii/Botania#4196]
### Mod Loader

Forge

### Minecraft Version

1.19.2

### Botania version

1.19.x @ b1ae2b71cacc6004850ce19e29a543a721da6382 (HEAD as of writing)

### Modloader version

43.1.47

### Issue description

Right clicking a petal apothecary with a water bucket most of the time doesn't fill the apothecary, and instead places the water in the world. I'm gonna take a wild guess and assume this was caused by 051776549a8d60ce81a8aeab97cd33afead01536.

Does not affect fabric.

**Comment by Quipex** [comment]
Just tested that out at the same commit on Forge. Works fine all the time

**Comment by LeoBeliik** [comment]
can't reproduce this :clueless:

**Comment by artemisSystem** [comment]
Weird. will investigate more i guess

**Comment by artemisSystem** [comment]
https://cdn.discordapp.com/attachments/977270876200386620/1040672434623369358/botania_water_bug.mp4

Here's a video demonstrating it. I think it's only in creative mode, perhaps? also possibly related to the fact that a full bucket can empty the apothecary, maybe something's wrong with the fluid interface/api implementation or something? Confirming again that this does not happen on fabric, maybe something is wrong with the forge fluid API implementation @williewillus ?

Could also perhaps be a sync issue, where one side expects the bucket to empty or something?

**Comment by TheRealWormbo** [comment]
Is this still a thing we need to look into?

**Comment by artemisSystem** [comment]
let me try to repro it again, will close if i can't. i'm on vacation but have my laptop but it might be a couple days still
