### ISSUE TITLE
Outdated poolCart entry

### ISSUE THREAD

**Issue by Aegide** [Vazkii/Botania#4202]
### Mod Loader

Fabric

### Minecraft Version

1.19.2

### Botania version

1.19.2-436

### Modloader version

Fabric 0.14.9

### Issue description

`botania.page.poolCart1` => `the transfer rate is extremely fast due to the mechanical nature of the pump-- so fast that overflow is possible, which can cause up to a whole diluted pools' worth of Mana Loss`

I can't reproduce that in-game, perhaps it was fixed.

### Setup

![image](https://user-images.githubusercontent.com/43409914/199851845-c89f1b1c-0063-4eab-a81e-0ce6fab4dd25.png)

I tried to create overflows, a lot of them, but the total of mana in my pool-cart remains stable.

**Comment by TheRealWormbo** [comment]
Tested on latest Botania Forge version for 1.19.2:
![Test setup](https://user-images.githubusercontent.com/7620864/222954765-b504926f-6f5f-4113-8f29-30b28953909b.png)
In this setup I can fill a cart from a guilty pool and have it pump its mana into a diluted pool. Then I can put a number of items into the dropper and it will repeatedly activate both the dropper and the pulse mana spreader (no lenses), which fires a burst worth the standard amount of 160 mana directly into the void and causes the pump to refill the pool.

I started with the cart, the spreader and the pool completely filled. After moving a stack of items, i.e. firing the spreader 64 times, `/data get entity @e[type=botania:pool_minecart,limit=1]` tells me the cart has 360k mana left (capacity is 1M mana), i.e. the pump transferred 64 times 10k mana, even though the pool only had room for 160 after each time the spreader fired.

I'd say the documentation is still correct about the amount of potentially wasted mana.
