### ISSUE TITLE
Z-fighting mana prisms

### ISSUE THREAD

**Issue by Aegide** [Vazkii/Botania#4203]
### Mod Loader

Fabric

### Minecraft Version

1.19.2

### Botania version

1.19.2-436

### Modloader version

Fabric 0.14.9

### Issue description

![image](https://user-images.githubusercontent.com/43409914/200068381-5eb2f494-c719-431a-860a-1587ae45d70b.png)

Affected lenses :
- `lens_mine`
- `lens_magnet`
- `lens_explosive`
- `lens_fire`
- `lens_warp`
- `lens_light`

**Comment by williewillus** [comment]
There is no easy fix here short of making all lenses have the same size glass, I'm opposed to any sort of hacky fix for this otherwise.

**Comment by Aegide** [comment]
No problem, it was just in case you had a solution for that issue

**Comment by artemisSystem** [comment]
This should be fixable by making the lenses render like 1.001x bigger or something, a technique that is already used in some mana spreader code and it's not very noticeable at all, really. I think that's a decent fix, thoughts, willie?
