### ISSUE TITLE
Wand of the forest and the elven wand don't show the bind/function text when in off hand

### ISSUE THREAD

**Issue by LeoBeliik** [Vazkii/Botania#4221]
### Mod Loader

Forge

### Minecraft Version

1.19.2

### Botania version

Botania-1.19.2-436-FORGE-SNAPSHOT

### Modloader version

Forge 1.19.2 - 43.1.47

### The latest.log file

-

### Issue description

The text on top of the toolbar that appears when you change between function and bind modes doesn't show when the wand is held in the off hand.

![2022-11-14_10 57 43](https://user-images.githubusercontent.com/11804768/201678358-9ed71a89-6ce5-4b4e-a27a-29c11d3c6486.png)

### Steps to reproduce

put a wand in your off hand
sneak + rclick
observe

**Comment by artemisSystem** [comment]
I feel like this is a more fitting close status (for future reference, this issue just describes a vanilla semantics thing, not really related to botania)
