### ISSUE TITLE
Warp Bore lens behavior inconsistent with documentation

### ISSUE THREAD

**Issue by cplir-c** [Vazkii/Botania#4225]
### Mod Loader

Fabric

### Minecraft Version

1.19.2

### Botania version

1.19.2-436-FABRIC-SNAPSHOT

### Modloader version

Quilt: Loader 0.17.6; Quilted Fabric API 4.0.0-beta.20+0.66.0-1.19.2

### Modpack info

Just Patchouli 1.19.2-77-FABRIC and Trinkets 3.4.1

### The latest.log file

https://mclo.gs/UejNXvK

### Issue description

Problem: Force relays are broken by `Warp Bore` lenses, but not `Bore Warp` lenses.
Reasoning: According to the Lexicon, there should only be a cosmetic difference between the two (from the article on lenses), and the bore warp combination should not destroy force relays or (pistons?) (from the article on elven lenses).

### Steps to reproduce

[Screenshots](https://imgur.com/a/HXfCpBn)

1. Launch with the described modpack.
2. Load a Creative world.
3. Put in your hotbar:
    - a Wand of the Forest (linking relays)
    - a lever (redstone source)
    - an Everlasting Guilty Pool (mana source)
    - a Pulse Spreader (mana burst source)
    - a Force Relay
    - two Warp lenses
    - two Bore lenses
    - two slime balls
    - a crafting table
4. Place the crafting table, and craft a Warp Bore lens and a Bore Warp lens.
5. Place the pulse spreader pointing up.
6. Place an everlasting guilty pool next to the spreader.
7. Place a lever next to the spreader.
8. Place a Force Relay 0 or 1 block in front of the spreader.
9. Put one of the two lenses on the spreader.
10. Place a 7 block tall pillar of dirt or something breakable.
11. Link the force relay with the bottommost block of the pillar.
12. Flip the lever.

For the Warp Bore combination at either distance, the force relay was broken by the mana burst, and the mana burst was still teleported.
For the Bore Warp combination at either distance, the force relay was still in place, and the mana burst was still teleported.

### Other information

No other mods were used; I made a new instance just for this.

**Comment by TheRealWormbo** [comment]
Can confirm, this is still the case on both Fabric and Forge versions:
- Warp+Bore breaks the force relay (and doesn't teleport the items, but that's intentional)
- Bore+Warp leaves the force relay intact (and teleports the items as advertised)

Neither combination should really break the force relay.
