### ISSUE TITLE
All pylons are visible through blindness

### ISSUE THREAD

**Issue by cplir-c** [Vazkii/Botania#4226]
### Mod Loader

Fabric

### Minecraft Version

1.19.2

### Botania version

1.19.2-436-FABRIC-SNAPSHOT

### Modloader version

Quilt Loader 0.17.6
Quilted Fabric API 4.0.0-beta.20+0.66.0-1.19.2

### Modpack info

Patchouli 1.19.2-77-FABRIC and Trinkets 3.4.1

### The latest.log file

https://mclo.gs/txXtlkt

### Issue description

[Screenshots](https://imgur.com/a/tcvywzN)
When under the blindness status effect, the black fog over everything does not obscure out of range pylons.

### Steps to reproduce

1. Place a Mana Pylon, Gaia Pylon, or Natura Pylon
2. Run command: /effect @p give minecraft:blindness 1024 1
   This gives the closest player the blindness status effect at level 1 for 1024 seconds.
4. Watch the pylon as you fly/run away. It does not disappear when surrounding blocks or beacon beams do.

**Comment by Aegide** [comment]
`/effect give @p minecraft:blindness 1024 1`

![image](https://user-images.githubusercontent.com/43409914/210654362-dd944863-821b-49ab-8c59-423702765c87.png)

**Comment by TheRealWormbo** [comment]
I can not reproduce this in 1.20.1-v444, regardless of Fast/Fancy/Fabulous graphics settings.
