### ISSUE TITLE
Builder's wand + flowers

### ISSUE THREAD

**Issue by StarRaptor1829** [Vazkii/Botania#4230]
### Mod Loader

Forge

### Minecraft Version

1.10.2

### Botania version

1.9-341

### Modloader version

Forge: 12.18.3.2411

### The latest.log file

https://pastebin.com/TLgvZuvu

### Issue description

Using Better Building Wand's mod:
Used the wand on the flower, used the endoflame flower. It shows up as the purple and black error block. Upon breaking, it gives me a, "Botania Flower".

### Steps to reproduce

1. Place down a endoflame flower
2. get a Better Builder Wand(i used a unbreakable wand)
3. with more endoflame flowers in your inventory, right click the flower with the wand
4. done

**Comment by williewillus** [comment]
1.10 isn't supported anymore unfortunately. The root problem is that the wand does not set the NBT data of the stack properly, as before 1.13 all botania flowers share a single block id. If the wand mod is still maintained, I would report this to them.
