### ISSUE TITLE
Crash on new forge version

### ISSUE THREAD

**Issue by LeoBeliik** [Vazkii/Botania#4233]
### Mod Loader

Forge

### Minecraft Version

1.19.2

### Botania version

Botania-1.19.2-436-FORGE-SNAPSHOT

### Modloader version

Forge 1.19.2 - 43.1.60

### The latest.log file

https://gist.github.com/LeoBeliik/7a62279e8fa385e4c0b05d5906597562

### Issue description

last time it worked for me was forge .52 but didn't test all the versions in between sorry

### Steps to reproduce

update forge
start game
:ohno:

**Comment by williewillus** [comment]
067966f5f64b4ed995b548b332e2805081af7e9d
