### ISSUE TITLE
Natura Pylons do not work for mana enchanter

### ISSUE THREAD

**Issue by ghost** [Vazkii/Botania#4235]
### Mod Loader

Forge

### Minecraft Version

1.18.2

### Botania version

1.18.2-435

### Modloader version

Forge: 0.212.4.7222

### Modpack info

https://www.curseforge.com/minecraft/modpacks/all-the-mods-7

### The latest.log file

https://pastebin.com/jjn1nh8b

### Issue description

Tried making the mana enchanter using natura pylons, i saw online this was possible but the multiblock never worked. ended up making more mana pylons and it works like a charm. is this intended?

### Steps to reproduce

1. build out multiblock enchanter
2. use natura pylons instead of mana pylons
3. no feedback, multiblock doesn't create

**Comment by williewillus** [comment]
From what I can tell, the overlay never supported non-mana pylons.

**Comment by ghost** [comment]
https://ftb.fandom.com/wiki/Mana_Enchanter
FTB wiki says you can use pylons other than the mana ones! 

if that's not the way it is intended to work that's fine. i think i just assumed that they would provide a higher enchanting bonus? after actually using the system a couple of times i think i realize that it isn't actually necessary, it just might be worth specifying it in the lexicon

**Comment by williewillus** [comment]
FTB wiki can be incorrect.

They don't provide any higher enchanting power than mana pylons, no.

**Comment by Hubry** [comment]
From an older branch...
https://github.com/VazkiiMods/Botania/blob/8a56a4a60c97be368b45c97da9d9da0ab6490962/src/main/java/vazkii/botania/common/block/BlockPylon.java#L113-L121

**Comment by williewillus** [comment]
that's for the enchanting table, I'm pretty sure OP is talking about the Mana Enchanter seeing as this issue revolves around it.

**Comment by ghost** [comment]
i was talking about the Mana Enchanter, but it isn't an issue if it is only intended to work with mana pylons. it seems like that's the case!
