### ISSUE TITLE
Marimorphosis tags only work after world reload

### ISSUE THREAD

**Issue by artemisSystem** [Vazkii/Botania#4237]
### Mod Loader

Fabric

### Minecraft Version

1.19.2

### Botania version

1.19.x branch

### Modloader version

whatever the dev env is using

### The latest.log file

Nothing relevant

### Issue description

When first placing a marimorphosis with only tag recipes, it doesn't convert any blocks. When reloading the world it starts working

**Comment by williewillus** [comment]
I can repro this

cc @Hubry maybe you have ideas

**Comment by williewillus** [comment]
Looking at the RecipeManager after loading completes, the marimorphosis recipes aren't in there at all, I don't know why. The orechid ones are.

**Comment by artemisSystem** [comment]
For clarity i don't think that's a difference between orechid/marim code, just that i added tag recipes for marim while orechid remains as it is with block ingredients
