### ISSUE TITLE
Mana pool rendering is funky when an adjacent spreader is pointed into it.

### ISSUE THREAD

**Issue by rowanthemodder** [Vazkii/Botania#4238]
### Mod Loader

Forge

### Minecraft Version

1.19.2

### Botania version

1.19.2-436-20221207.211129-46

### Modloader version

Forge 43.1.65

### The latest.log file

https://gist.github.com/rowanthemodder/208c533af392be490cf65de5e58c8f88

### Issue description

If you point a mana spreader at a pool directly adjacent to it, the client will desync and render the pool empty/nearly empty.
[Screencast from 2022-12-10 00-02-40.webm](https://user-images.githubusercontent.com/46363164/206840658-3ab0918c-20d0-4d9f-93b5-273f6e2d8d48.webm)

This can be forcefully updated for the client by performing a mana craft, shown here with 1 manasteel per pool.
![Screenshot from 2022-12-10 00-06-50](https://user-images.githubusercontent.com/46363164/206840664-2ca5e464-214e-4bb2-bacf-d61cd2e44ce0.png)

**Comment by artemisSystem** [comment]
Note: not a rendering issue, but the mana amount gets desynced client-side

**Comment by williewillus** [comment]
I can't get this to happen.

**Comment by williewillus** [comment]
Edit: Now I can, and "fixed" :P
