### ISSUE TITLE
Banners symbol from Botania doesn't work 

### ISSUE THREAD

**Issue by ghost** [Vazkii/Botania#4241]
### Mod Loader

Fabric

### Minecraft Version

1.19.2

### Botania version

1.19.2-436-FABRIC

### Modloader version

Fabric Loader 0.14.11-1.19.2 + API 0.68.0+1.19.2

### The latest.log file

N/A

### Issue description

Banner symbols from Botania doesn't work, in any craft table and loom, any banner doesn't change at all when you put items in craft table with dye, item for banner symbol from botania and banner, happens nothing when you did that

### Steps to reproduce

1. Take item's for banner symbol (any dye and item for banner symbol with any banner)
2. Put all in Craft Table
3. See that didn't work at all
4. The way with loom doesn't works because you can't put items in loom like any item from Botany

### Other information

This is issue doesn't make any crash when you did it, this is just don't working

**Comment by Aegide** [comment]
![image](https://user-images.githubusercontent.com/43409914/210181312-dca92e7b-f19b-4bf7-baee-c75745b3c2af.png)

Banner crafting works, but Botania items are (currently) not recognized as loom materials for the menu.

**Comment by williewillus** [comment]
9af533b087154903e554de181e5f416c87582349

**Comment by Aegide** [comment]
pog
