### ISSUE TITLE
Minor lexicon edits

### ISSUE THREAD

**Issue by anoomolu** [Vazkii/Botania#4243]
### Mod Loader

Fabric

### Minecraft Version

1.19.2

### Botania version

1.19.22-436

### Modloader version

Quilt Loader 0.17.7 / QFAPI 4.0.0-beta.23 but assuming this is the case across loaders

### The latest.log file

https://mclo.gs/16iLXPI

### Issue description

The Pure Daisy page in the lexicon still uses the old flower texture.
![image](https://user-images.githubusercontent.com/77850233/207845153-19507916-4fb6-4947-bcec-f883f2a346a2.png)

The final page of the Challenges page in the lexicon has "can" repeated twice.
![image](https://user-images.githubusercontent.com/77850233/207845606-df8b57ee-ec09-4dd8-bd0c-bc69e03a264f.png)

### Steps to reproduce

Open the lexicon and navigate to the Pure Daisy/Challenges pages respectively.

**Comment by Aegide** [comment]
Thanks for the report, i'll work on it.

**Comment by Aegide** [comment]
https://lists.sr.ht/~williewillus/violet-moon/patches/37887

**Comment by Aegide** [comment]
@Alwinfy done B)

**Comment by artemisSystem** [comment]
Partially fixed in https://github.com/VazkiiMods/Botania/commit/d29ae5fc5a110bc1a60c42214dced6033e3b74b6

**Comment by artemisSystem** [comment]
(in the future, @anoomolu, please open one issue for each thing. This one should ideally have been two different ones. one for the typo and one for the texture)

**Comment by anoomolu** [comment]
Sorry for necroposting, I've made an image for the pure daisy entry with the new texture.

![image](https://github.com/VazkiiMods/Botania/assets/77850233/cb71e141-edef-430e-8953-c79fd479b658)

It's 9kb larger than the old one, hopefully not a problem ^^
