### ISSUE TITLE
1.19.2-436 Fabric version not loading in

### ISSUE THREAD

**Issue by lion099** [Vazkii/Botania#4244]
### Mod Loader

Forge

### Minecraft Version

1.19.2

### Botania version

1.19.2-436

### Modloader version

Fabric: 0.14.11-1.19.2; Api: 0.69.0+1.19.2

### The latest.log file

https://pastebin.com/NpnBMDVq

### Issue description

Game not launching, doesn't even show fabric crash, only in the minecraft launcher

### Other information

if i remove only the botania mod, the game will load in

**Comment by artemisSystem** [comment]
You seem to be using a trinkets version for 1.19.3? (3.5.0) Try with trinkets 3.4.1

**Comment by artemisSystem** [comment]
This doesn't seem to be botania's fault. If my suggestion doesn't work, please reply with a new crash report using the suggested trinkets version.
