### ISSUE TITLE
Crash in the overlay drawer

### ISSUE THREAD

**Issue by gamma-delta** [Vazkii/Botania#4247]
### Mod Loader

Fabric

### Minecraft Version

1.19.2

### Botania version

1.19.2-436-FABRIC

### Modloader version

Quilt Loader 0.17.7 / Quilted Fabric API 4.0.0-beta.24+0.68.0-1.19.2

### Modpack info

Spooled (by Moss)

### The latest.log file

https://mclo.gs/RYgHa2n

### Issue description

The crash happened when sorting my inventory (with MouseWheelie). I think the only mana-interacting item I had in it was a mana tablet, but I was also wearing miner's and magnet rings.

### Steps to reproduce

Not sure

### Other information

i would hate to receive this bug report but i just don't have any more information sorry

**Comment by anoomolu** [comment]
I'm unable to reproduce this with just Mouse Wheelie, Botania + deps on Quilt. Feel free to open another issue if you're still having this problem, preferably with some more information in the form of a log or steps to reproduce.
