### ISSUE TITLE
Holding wand of the forest around mana spreaders causes extreme client lag

### ISSUE THREAD

**Issue by Lilith-In-Starlight** [Vazkii/Botania#4250]
### Mod Loader

Forge

### Minecraft Version

1.19.2

### Botania version

1.19.2-436-FORGE

### Modloader version

Forge 43.2.0

### The latest.log file

https://pastebin.com/9DgxLJgL

### Issue description

When I hold the wand of the forest, if there are more than around 10 mana spreaders around, the game starts lagging so much that it is basically impossible to play. From this point, the lag increases with the amount of spreaders at a rate that feels exponential. The spreaders don't have to be in view for this lag to happen.

### Steps to reproduce

1. Place several mana spreaders of any kind, around 10 should do
2. Hold a wand of the forest, any mode should do

### Other information

I'm using Rubidium for render optimizations, as my computer is unable to run Minecraft otherwise. I was told that Botania conflicts with such mods, so I have already disabled the rendering.shaders setting in the client-config file. Doing this changed nothing.

I'm also playing on Garden Of Glass.

**Comment by Lilith-In-Starlight** [comment]
Hubry asked me to profile it, so I did. https://spark.lucko.me/dvmeETak73

They suggested that it's possible that this is Forge's fault, or that forge may be making the issue worse. To test whether it's an issue with Forge, I profiled the same world in Fabric. Of note: I couldn't get Sodium and Botania to cooperate, so I had to use Botania alone, which made things slightly slower, but still smooth until I held the wand of the forest. The issue was still incredibly present. https://spark.lucko.me/HFtUPnQBFo

After trying to recreate the issue on their end, they realized that it takes them significantly more mana spreaders due to their CPU not being as low-end as mine.

**Comment by Aegide** [comment]
> They suggested that it's possible that this is Forge's fault, or that forge may be making the issue worse.

I suggest that it's possible that this is not Forge's fault.

![image](https://user-images.githubusercontent.com/43409914/210649510-cf259e53-bdc7-4054-b99d-2577407bef5b.png)

**Comment by williewillus** [comment]
Seems to be fixed by that commit
