### ISSUE TITLE
Not up to date

### ISSUE THREAD

**Issue by PeachesLeeches0** [Vazkii/Botania#4252]
### Mod Loader

Forge

### Minecraft Version

1.19.3

### Botania version

1.19.2

### Modloader version

Forge

### The latest.log file

https://www.curseforge.com/minecraft/mc-mods/botania

### Issue description

The mod is not up to date on what versions it can play on. 

### Steps to reproduce

1. Update Botania

**Comment by williewillus** [comment]
These sorts of issues are not helpful. We know 1.19.3 is out. Violet Moon is holding off 1.19.3 for now as a group and will reassess later.
