### ISSUE TITLE
Bergamutes don't work on endoflames

### ISSUE THREAD

**Issue by uhloin** [Vazkii/Botania#4254]
### Mod Loader

Forge

### Minecraft Version

1.19.2

### Botania version

1.19.2-436-FORGE

### Modloader version

43.2.0

### The latest.log file

-

### Issue description

Bergamutes don't deaf loud endoflames farm. And even Omegamute mod could not deaf them.  Other sounds volume reduced normally.

**Comment by williewillus** [comment]
Can you show a screenshot of the setup? I checked the code and it should
work fine. Do the Bergamutes work on other sound sources?

**Comment by uhloin** [comment]
4 rows or endoflames and 1 row of bergamutes (see screenshot). I temporarily removed omegamute to be sure it is not cause of the problem. When I plant row of bergamutes, sound of planting is reduced every time so bergamutes do work on other souds. But "splashes" of endoflames keep the same level of loudness not dependent from number of bergamutes.

![b1](https://user-images.githubusercontent.com/96169906/209771193-93f25122-c22d-4061-8043-f16a45ab9867.png)
![b2](https://user-images.githubusercontent.com/96169906/209771195-5ea971d1-4c4c-44db-8963-7f7035f79372.png)

**Comment by uhloin** [comment]
Also if I replace endoflame.ogg file with file containing 1 second of silence, then sound disapears. 

Also I just checked altar with agglomeration plate and petal apothecary. Their sounds are reduced by bergamutes. Also I checked Hydroangeas and its "drinking" sound is reduced.

So problem is specific for "endoflame.ogg" file and may be some other but not for all Botania's sound files.

**Comment by uhloin** [comment]
Additional info: floating bergamutes work on endoflames!

**Comment by anoomolu** [comment]
Was unable to reproduce this on latest with the following setup, normal bergamutes work fine on endoflames:

![image](https://github.com/VazkiiMods/Botania/assets/77850233/fe7500e4-b31a-492d-bce5-434f565c75bb)
