### ISSUE TITLE
Ring of Odin - health level does not save

### ISSUE THREAD

**Issue by uhloin** [Vazkii/Botania#4255]
### Mod Loader

Forge

### Minecraft Version

1.19.2

### Botania version

1.19.2-436-FORGE

### Modloader version

43.2.0

### The latest.log file

-

### Issue description

When wear Ring of Odin every time I quit/save and re-enter game health bar lost additional 10 hearths as if I was damaged.

**Comment by artemisSystem** [comment]
Looks like #3027 might be back (or was never gone?). Leaving this open since the mentioned issue was closed

**Comment by williewillus** [comment]
I believe this is a problem with the underlying accessories mod (Curios
in this case), vaguely remember testing this with vanilla armor slots
and it didn't happen. Needs more research probably.

**Comment by anoomolu** [comment]
This may just be a vanilla problem, seems like installing [this](https://legacy.curseforge.com/minecraft/mc-mods/max-health-fix) mod fixes the issue.

**Comment by williewillus** [comment]
I'll lay the blame on vanilla then.
