### ISSUE TITLE
Mana bar bug

### ISSUE THREAD

**Issue by gnilobaiter** [Vazkii/Botania#4256]
### Mod Loader

Forge

### Minecraft Version

1.19.2

### Botania version

 Botania-1.19.2-436-FORGE

### Modloader version

Forge 43.2.0

### The latest.log file

https://pastebin.com/qqsP01cF

### Issue description

Mana bar doesn't display NEVER. With forest wand too...

### Other information

I decided to build a mana miner from water hydrants, and it didn't work out for me, their strength is spent, and I can't view mana, and the pool is not filled visually, I don't see any bars and other things

**Comment by gnilobaiter** [comment]
![image](https://user-images.githubusercontent.com/104412752/209857782-5795b2d3-2c2a-4f60-bb59-46685624ef03.png)

**Comment by gnilobaiter** [comment]
![image](https://user-images.githubusercontent.com/104412752/209857899-054f1812-75d5-4e2d-bdb9-ff643dbf3188.png)
Mod list

**Comment by williewillus** [comment]
Shatts Makar writes:

> I decided to build a mana miner from water hydrants, and it didn't work out for me, their strength is spent, and I can't view mana, and the pool is not filled visually, I don't see any bars and other things

What is a mana miner/water hydrant? If they're addon content, please try
replicating with just Botania. A ttest on Fabric would also be appreciated.

**Comment by gnilobaiter** [comment]
I fixed problem myself, chaged optifine version

**Comment by So0vey** [comment]
> I fixed problem myself, chaged optifine version
Чел, ты просто Гигичад. Спасибо большое. Такая же дурь с маной была

**Comment by gnilobaiter** [comment]
> > I fixed problem myself, chaged optifine version
> > Чел, ты просто Гигичад. Спасибо большое. Такая же дурь с маной была

Спасибо xD. Советую использовать ту же версию что и у меня (OptiFine_1.19.2_HD_U_H9), так как если ты будешь юзать AE2 с другими версиями оптифайна, могут возникнуть траблы или краши внезапные. И да, если юзаешь оптифайн, то не советую использовать Phosphor или другие его форки. Юзай Starlight
