### ISSUE TITLE
Optifine 1.19.2 causes the wand of the forest to not show mana levels in the mana pool

### ISSUE THREAD

**Issue by JAWredstoneguy** [Vazkii/Botania#4258]
### Mod Loader

Forge

### Minecraft Version

1.19.2

### Botania version

Botania version 436

### Modloader version

Forge 43.2.0

### The latest.log file

https://pastebin.com/g7rnjrbh

### Issue description

When looking at any manapool while using a wand of the forest. The mana pool fill level does not render when optifine is installed.
With Optifine:
![2022-12-31_16 28 50](https://user-images.githubusercontent.com/107218089/210156258-665907be-6743-4d66-bebf-39a2698d556d.png)
![2022-12-31_16 29 41](https://user-images.githubusercontent.com/107218089/210156260-7b444e44-a175-4ded-91ba-21536b60f9f5.png)
Without Optifine:
![2022-12-31_16 31 19](https://user-images.githubusercontent.com/107218089/210156268-03806472-6a3a-4b50-8058-b5c78490bbdb.png)

### Steps to reproduce

1. Install Botania and it's dependencies onto a 43.2.0 forge installation
2. Download and extract the OptiFine version 1.19.2 HD U | 1 pre 4 into the mods folder of minecraft
3. Start a new world and look at a mana pool with the wand of the forest in your hand

### Other information

Mods used are:
- Botania-1.19.2-436-FORGE.jar
- curios-forge-1.19.2-5.1.1.0.jar
- jei-1.19.2-forge-11.5.0.297.jar
- Optifine_1.19.2_HD_U_|1_pre4_MOD.jar
- Patchouli-1.19.2-77.jar

**Comment by Aegide** [comment]
@JAWredstoneguy your issue is related to Optifine, a project that's not open-source.
It's gonna be extremely hard to understand why this anomaly is happening, and how to find a fix that's compatible with Optifine.

**Comment by artemisSystem** [comment]
Yeah sorry there's not much we can do about optifine. Even working around it could prove to be a hard task. I don't think anything changed about the wand HUD code from 1.18 to 1.19, so if this was working before, it's likely optifine changed something. Report the issue to them if possible.

**Comment by JAWredstoneguy** [comment]
Got it, thank you for responding!
