### ISSUE TITLE
[Bug][1.19.2] Wand of the Forest spreader beam ignores all blocks

### ISSUE THREAD

**Issue by FizzBuzz3000** [Vazkii/Botania#4259]
### Mod Loader

Fabric

### Minecraft Version

1.19.2

### Botania version

Botania-1.19.2-436-FABRIC

### Modloader version

Fabric 0.14.11, fabric-api-0.68.0+1.19.2

### The latest.log file

https://gist.github.com/FizzBuzz3000/b5f9b5492b62df2485278929fde12dee

### Issue description

The wand beam ignores any and all blocks, including normal blocks that would stop the beam, with the exception of the bounce lens, which will then just ignore all mana-accepting items like pools, spreaders, and so on. **The actual burst logic does work as intended, it's just the wand beam logic that is broken.** [Artemis did mention in the discord](https://discord.com/channels/154261184701267969/977270876200386620/1056106766066257950) that [this commit](https://github.com/VazkiiMods/Botania/commit/ec00062a0451bf7bf25cf0f4f16ffd15f8cc9291) may be what is causing the problem, and might also be causing #4250. Tested on Fabric only.

![how](https://media.discordapp.net/attachments/977270876200386620/1056050731024666704/image.png)

### Other information

# Other mods installed:
3dskinlayers-fabric-1.5.2-mc1.19.1.jar
blur-2.6.0.jar
Botania-1.19.2-436-FABRIC.jar
Chunky-1.3.38.jar
cullleaves-fabric-3.0.1.jar
fabric-api-0.68.0+1.19.2.jar
fallingleaves-1.13.0+1.19.2.jar
ferritecore-5.0.3-fabric.jar
firstperson-fabric-2.2.0-mc1.19.2.jar
fpsdisplay-1.5.0+1.19.jar
immersive-portals-2.3.1-mc1.19.2-fabric.jar
iris-mc1.19.2-1.4.5.jar
item-model-fix-1.0.3+1.19.jar
journeymap-1.19.2-5.9.0-fabric.jar
lazydfu-0.1.3.jar
memoryleakfix-1.19.1-0.7.0.jar
mousewheelie-1.10.6+mc1.19.2.jar
Patchouli-1.19.2-77-FABRIC.jar
phosphor-fabric-mc1.19.x-0.8.1.jar
smoothboot-fabric-1.19-1.7.1.jar
sodium-fabric-mc1.19.2-0.4.4+build.18.jar
tooltipfix-1.1.1-1.19.jar
trinkets-3.4.1.jar

**Comment by williewillus** [comment]
Folding into #4250
