### ISSUE TITLE
Orechid does not generate modded ores from Create or IC2 Classic

### ISSUE THREAD

**Issue by EnderVonSlayer** [Vazkii/Botania#4262]
### Mod Loader

Forge

### Minecraft Version

1.19.2

### Botania version

1.19.2-436

### Modloader version

Forge 43.2.0

### The latest.log file

https://pastebin.com/2weYeGUk

### Issue description

I've noticed the orechid is not generating ores like zinc ore from Create or Tin/Silver/Uranium from IC2 Classic. I have confirmed that these ores do naturally generate by creating a new world with the same mods.

**Comment by cplir-c** [comment]
In the meantime, Create zinc is obtainable by crushing Tuff (10% chance of a zinc nugget). Tuff can be renewably obtained using some Botania and Create:

4. Alchemize Deepslate into Tuff
3. Smelt or Bulk Blast cobbled deepslate into deepslate
2. Pure Daisy endstone into [an ender air bottle](https://github.com/VazkiiMods/Botania/issues/4023) and cobbled deepslate
1. Toss/Dispense ender air bottles on stone to make several endstone

You'd need to make glass bottles to capture the ender air as well, but both mods can craft bottles and make sand from cobblestone.

**Comment by EnderVonSlayer** [comment]
Appreciate the work around, thanks!

By meantime, you mean that there *is* something off with the orechid generating ores, right?

**Comment by Prunoideae** [comment]
Orechid recipes are now data-driven (checkout [this](https://github.com/VazkiiMods/Botania/tree/1.19.x/Xplat/src/generated/resources/data/botania/recipes/orechid))

You can add ores you want by datapacks. And I don't think modded ores are supported by just Botania now.

**Comment by EnderVonSlayer** [comment]
Well thats neat! Slightly puts a damper on the skyblock I had going but now that I think about it, orechid being used for vanilla only works pretty well...multi-layed ore generation systems would be cool to implement

**Comment by EnderVonSlayer** [comment]
So, did a slight bit of thinking and realized that without already having zinc, I can't craft the mechanical crafters necessary for the crushing wheels to get the zinc...datapack it is I suppose

**Comment by RingiTsukitora** [comment]
> In the meantime, Create zinc is obtainable by crushing Tuff (10% chance of a zinc nugget). Tuff can be renewably obtained using some Botania and Create:
> 
>     4. Alchemize Deepslate into Tuff
> 
>     5. Smelt or Bulk Blast cobbled deepslate into deepslate
> 
>     6. Pure Daisy endstone into [an ender air bottle](https://github.com/VazkiiMods/Botania/issues/4023) and cobbled deepslate
> 
>     7. Toss/Dispense ender air bottles on stone to make several endstone
> 
> 
> You'd need to make glass bottles to capture the ender air as well, but both mods can craft bottles and make sand from cobblestone.

But crushing wheel need mechanical creafter for production,mechanical creafte need brass...zinc and copper

**Comment by anoomolu** [comment]
Any block should work with the orechid. Like Prunoideae mentioned, you need to add custom recipes to a datapack with the same file structure as the orechid recipes. 
For example, prismarine.json:

{
  "type": "botania:orechid",
  "input": {
    "type": "block",
    "block": "minecraft:stone"
  },
  "output": {
    "type": "block",
    "block": "minecraft:prismarine"
  },
  "weight": 100000
}
