### ISSUE TITLE
Mystical flowers aren't compostable

### ISSUE THREAD

**Issue by 00-Steven** [Vazkii/Botania#4263]
### Mod Loader

Both Fabric and Forge (I confirm that I have tested both loaders and will specify both loader versions below)

### Minecraft Version

1.19.2

### Botania version

yea

### Modloader version

.

### The latest.log file

.

### Issue description

Mystical flowers aren't compostable, but're supposed to be.

### Other information

Was told to make an issue as reminder to implement such.

**Comment by TheRealWormbo** [comment]
Some thoughts.

Things that probably should be compostable:
- petals
- petal blocks
- small mystical flowers
- tall mystical flowers
- shimmering mushrooms
- cellular blocks

I think as soon as non-organic ingredients (dyes can probably count as organic) come into play, the flower should probably no longer be compostable, that is: glimmering, floating or special flowers should probably not go into composters for various reasons.

Relations between composting chances:
- small flowers make 2 petals
- large flowers make 4 petals
- petal blocks are crafted from 9 petals
- shimmering mushrooms are used as petal replacements in recipes

Petals work a lot like seeds for tall mystical flowers, but also petal blocks are crafted from more petals than two tall or four small flowers produce.

Vanilla similarities:
- 30% category: (dried) kelp, seeds, pink petals, saplings, grass/fern
- 50% category: dried kelp block, tall grass/fern, cactus
- 65% category: flowers (small and tall), mushrooms, moss block, unprocessed harvested items (potato, wheat, etc.)
- 85% category: processed harvested items (baked potato, break, cookies, hay bale)
- 100% category: highly processed food items (cake, pumpkin pie)

Reasoning for likely categories:
- It probably makes sense to treat mystical flowers the same as regular flowers, i.e. put them into the 65% category.
- Vanilla crafting typically reduces the combined composting effect, so petals are probably fine to put into the 30% category.
- If the same treatment as for kelp is applied, that would mean petal blocks go into the 50% category, making them highly inefficient, compared to composting the flowers directly.
- Considering that cellular blocks are mostly made from cactus, but also have about one crop product (beetroot, carrot, potato) in them, they might go into the 85% category.
