### ISSUE TITLE
Failed to parse level-type botania:gardenofglass, defaulting to minecraft:normal

### ISSUE THREAD

**Issue by MaxusTheOne** [Vazkii/Botania#4265]
### Mod Loader

Forge

### Minecraft Version

1.19.2

### Botania version

1.19.2-436-FORGE

### Modloader version

forge-1.19.2-43.2.0

### The latest.log file

https://gist.github.com/MaxusTheOne/525b8aebf71fcb0cc64d30ea75aa3112

### Issue description

Forge server generates a default world despite having specified botania:gardenofglass level-type

### Steps to reproduce

1.Create forge server with botania, gardenofglass and dependencies
2.Change level-type to level-type=botania:gardenofglass
3.Log in to the server and see a default world

**Comment by RickieGamer** [comment]
The world type should be "level-type=gardenofglass\:gardenofglass"
https://github.com/VazkiiMods/Botania/blob/1.19.x/garden_of_glass/data/minecraft/tags/worldgen/world_preset/normal.json
Not sure why this isn't documented on the site or curseforge
