### ISSUE TITLE
Mana spreader not firing to bounded object.

### ISSUE THREAD

**Issue by Saint4desu** [Vazkii/Botania#4266]
### Mod Loader

Forge

### Minecraft Version

1.18.2

### Botania version

Botania-1.18.2-435.jar

### Modloader version

Forge 4.2

### Modpack info

https://drive.google.com/u/0/uc?id=1vYcqy9C6u4_Sjt8u2wApS6ud5v8qT4gY&export=download

### The latest.log file

[WARNING] .... [minecraft/ServerGamePacketListenerImpl]: C_ moved too quickly! -10.891421127097601,0.029608053282785818,9.625224018268796  [INFO] .... [ar.su.SuperSaturation/]: saturation: 11.200001  [INFO] .... [ar.su.SuperSaturation/]: hunger: 0  [INFO] .... [ne.mi.co.AdvancementLoadFix/]: Using new advancement loading for net.minecraft.server.PlayerAdvancements@51433a15  [INFO] .... [minecraft/PlayerList]: Otep[/45.9.46.145:56030] logged in with entity id 944137 at (298.5, 70.03584062504456, -42.5)  [INFO] .... [minecraft/DedicatedServer]: Otep joined the game  [INFO] .... [co.wu.pr.Prefab/]: Sent config to 'Otep'.  [INFO] .... [or.ze.so.SolarFlux/]: Sending solar panels to Otep.  [WARNING] .... [aoa3/]: Unable to find inbuilt advancements, another mod is breaking things.  [INFO] .... [Waila/]: Syncing config to Otep (6251f2b0-f9ff-354e-8d77-ccf5cc89adbe)  [INFO] .... [Enigmatic Legacy/INFO]: Synchronizing omniconfig files to Otep...  [INFO] .... [Enigmatic Legacy/INFO]: Sending data for enigmaticlegacy-common.omniconf  [INFO] .... [Enigmatic Legacy/INFO]: Granting starter gear to Otep  [INFO] .... [minecraft/DedicatedServer]: <Otep> everyone went sleep?  [INFO] .... [minecraft/DedicatedServer]: C_ was slain by Pillager  [INFO] .... [Enigmatic Legacy/INFO]: Summoned Extradimensional Storage Crystal for C_ at X: 1386.0962419958369, Y: 69.0, Z: -264.43477083419316

### Issue description

https://www.youtube.com/watch?v=BY8JEhPE8-s

Mana spreader when bound to an object fires in a different direction. Sometimes it curves to the sky. No pattern on where it goes it just never goes into the Object.

Check video to see what it looks like.

### Steps to reproduce

1. Place Any flower down
2. Place Mana spreader
3. Place Mana pool
4. Bind respectively
5. Activate.

**Comment by williewillus** [comment]
This usually happens if you have other mods nearby that deflect
projectiles, as mana bursts count as vanilla projectiles. Examples
include the interdiction torch from ProjectE. Please clear the entire
area, take off any deflecting trinkets or accessories, and try again.

**Comment by anoomolu** [comment]
Closing this as Willie's provided an explanation for why it typically happens, it's evidently not vanilla behaviour and there's been no response.
