### ISSUE TITLE
Living branches cannot be crafted

### ISSUE THREAD

**Issue by Anewri32** [Vazkii/Botania#4271]
### Mod Loader

Forge

### Minecraft Version

1.19.2

### Botania version

436

### Modloader version

43.2.0

### The latest.log file

None

### Issue description

When crafting the branches to make the forest stick, the branches are not crafted, instead the vanilla minecraft sticks are shown.
![javaw_uWLp2z7jW0](https://user-images.githubusercontent.com/70771409/213939439-f227de8e-071b-4ccf-b2fc-1b37e351e17f.png)
![javaw_lDAROXnTGc](https://user-images.githubusercontent.com/70771409/213939467-a785b044-5e6f-417c-b2ff-4a23a8ad4f6e.png)

### Steps to reproduce

1. Get the livingwood logs.
2. Try to craft the branches.

**Comment by enigmaquip** [comment]
That's a recipe added by your modpack. Two logs to 16 sticks is either a fairly standard quality of life recipe added manually, or it also tends to be added by Quark. Adding polymorph so you can choose the recipe output, or removing/disabling the log to stick recipe is the answer

**Comment by artemisSystem** [comment]
This was also fixed in https://github.com/VazkiiMods/Botania/commit/c4a5d2d449b7dbd9bc461cfac3a8cde84cc0a783
