### ISSUE TITLE
Make the composite lens crafting recipe use a new tag instead of hardcoded for slimeballs

### ISSUE THREAD

**Issue by gamma-delta** [Vazkii/Botania#4272]
### Mod Loader

Both Fabric and Forge (I confirm that I have tested both loaders and will specify both loader versions below)

### Minecraft Version

1.19.2

### Botania version

Release 1.19.2-436

### Modloader version

doesn't matter

### The latest.log file

no

### Issue description

Regarding this line: https://github.com/VazkiiMods/Botania/blob/1.19.x/Xplat/src/main/java/vazkii/botania/common/crafting/recipe/CompositeLensRecipe.java#L46

It might be nice for modpack makers to be able to change the item there instead of having it be hardcoded to slimeballs.

**Comment by anoomolu** [comment]
Can be closed due to the above PR being manually applied.
