### ISSUE TITLE
Mana Spreaders don't work

### ISSUE THREAD

**Issue by Wakatsu** [Vazkii/Botania#4274]
### Mod Loader

Forge

### Minecraft Version

1.19.2

### Botania version

Botania-1.19.2-436-FORGE

### Modloader version

Forge 43.2.3

### The latest.log file

https://gist.github.com/Wakatsu/d6d3c5dcb57d4c4b2f50e3cd533f4e75

### Issue description

Mana Spreaders don't work - no mana received from flowers, no beams fired to the pools, no sparks displayed when looked upon with wand of the forest in hand.

### Steps to reproduce

1. Craft a Mana Spreader and put it in world
2. Put a Mana Pool next to it an focus the Spreader on the Pool
3. Put and bind a generating flower to the Spreader
4. Make the flower produce mana
5. Nothing happens

**Comment by thattychan** [comment]
The problem occurs because you are using optfine.

If you want to use shader, you can use Oculus

**Comment by Zandrassen91** [comment]
hmm.. i have same problem, and i don't use optifine

**Comment by williewillus** [comment]
I can't reproduce this. Please reduce the set of mods and try again.

**Comment by Wakatsu** [comment]
Here's the latest log from test superflat world with minimal loadout:
https://gist.github.com/Wakatsu/ed297d8a606c98979d1dbf8fb0f2a0cd
Problem remains, spreaders refuse fire in any configuration I've tried to put them

**Comment by Wakatsu** [comment]
Sorry, closed it by accident.

Here's the latest log from test superflat world with minimal loadout:
https://gist.github.com/Wakatsu/ed297d8a606c98979d1dbf8fb0f2a0cd
Problem remains, spreaders refuse fire in any configuration I've tried to put them

**Comment by LeoBeliik** [comment]
I know for fact that Optifine breaks Botania, I've tested it, remove OF and see if that fixes it.

**Comment by Wakatsu** [comment]
1) I can't. Optifine is built in the launcher I use
2) I can't because potatoPC
3) I know for a fact Opti has nothing to do with this because literally all other builds of Botania work with it just fine. I always played with Opti before and had no problem

**Comment by williewillus** [comment]
Wakatsu ***@***.***> writes:

> 1 I can't. Optifine is built in the launcher I use

whatever launcher you're using is incredibly suspicious. None of the
credible launchers bundle optifine.

> 2 I can't because potatoPC

use lithium and/or sodium instead

> 3 I know for a fact Opti has nothing to do with this because literally all other builds of Botania work with it just fine. I always played with Opti before and had no problem

"It worked before" is not a good explanation. Optifine is so hacky that
breathing on it incorrectly will break mods. Until you can reproduce it
with a minimal set of mods (and especially without Optifine), we can't
help you.

**Comment by Wakatsu** [comment]
1. None of the credible launchers bundle optifine.

Really, you claim to know every launcher there in existence?

3. use lithium and/or sodium instead

Fabric mods. Fabric is junk, no normal mods exist for this poor excuse of a loader

5. "It worked before" is not a good explanation. Optifine is so hacky that breathing on it incorrectly will break mods.

I would've eat that, if it worked for one version and not the other. But Opti + Botania works just fine for literally every other build except for the latest, and Opti updates once in a blue moon, which means the problem is 100% on Botania side

7. Until you can reproduce it with a minimal set of mods (and especially without Optifine), we can't help you.

You do realize people play either vanilla or modpacks? Nobody creates a world to play just 1 specific mod, you either play vanilla for challenges or you go ham with 100500+ thematic mods. A mod that requires a sterile environment to work just won't be played.
Also if your mod is so fragile that the mere presence of the most popular optimizer that is found in pretty much every other modpack would completely bricks its core mechanic, what makes you think it is any better than the optimizer you're so quick to trash on?

**Comment by williewillus** [comment]
This issue has run its course. I already have vanishing time and motivation and this ain't helping.
Isolate the issue to the minimum reproducible setup and make another issue.

**Comment by williewillus** [comment]
I'll give you the benefit of the doubt and respond to your points even though it would be better for me if I didn't.

> Really, you claim to know every launcher there in existence?

Ok, then give me the name of it.

> Fabric mods. Fabric is junk, no normal mods exist for this poor excuse of a loader

There are Forge ports, and the second part of this sentence has nothing to do with the issue at hand.

> But Opti + Botania works just fine for literally every other build except for the latest

As I already said, this means nothing because Optifine is closed-source. Who knows what shit we tripped in it just because we dared to breathe on it?

> A mod that requires a sterile environment to work just won't be played.

Tell that to the 100 million other players of Botania.
