### ISSUE TITLE
Multiple Render Crashes [Fabric 1.19.2]

### ISSUE THREAD

**Issue by JessX0401** [Vazkii/Botania#4275]
### Mod Loader

Fabric

### Minecraft Version

1.19.2

### Botania version

1.19.2-436-Fabric

### Modloader version

Fabric Loader 0.14.12

### The latest.log file

https://pastebin.com/pnVP7pp4 

### Issue description

Hello I'll try to be clear with this since I'm having trouble playing with my modded world, I've been playing with this mod along other ones for some time and my game has been crashing lately and the problems or reason of the crash seem to be "variated".

In the first hand I've seen the crash reports I had so far, and the majority of them seem to point to be an "**Render Thread**" issue caused by different blocks (being functional/generating flowers) and accesories like the "manaseer monocle".

I really don't know anything about this or why would be caused, but I've seen mentions of "**Sodium render**" on some lines of the crash logs along "**fabric render**" but i don't know anything about this (don't want to try removing it, since  without sodium the game would become unplayable for me.).

I'm going to leave this crash logs pointing to the same render thread problems with endoflame, agricarnation and rannucarpus + one ticking entity crash log.

[botania crash - agricarnation.txt](https://github.com/VazkiiMods/Botania/files/10514449/botania.crash.-.agricarnation.txt)
[botania crash - endoflame.txt](https://github.com/VazkiiMods/Botania/files/10514450/botania.crash.-.endoflame.txt)
[botania crash - mana burst.txt](https://github.com/VazkiiMods/Botania/files/10514451/botania.crash.-.mana.burst.txt)
[botania crash - rannucarpus.txt](https://github.com/VazkiiMods/Botania/files/10514452/botania.crash.-.rannucarpus.txt)

I hope you can solve this problem for me and the rest of players that may have similar issues like this ones, and thanks for your attention.

### Steps to reproduce

Random using either...

1.- Generating or functional flowers being present during the game (endoflame, rannucarpus and agricarnation for now)

1.2.- Using accesories like manaseer monocle or worldshape's sextant (for now)

2.- Just playing normally, the crash happens after playing between 2-8 hours on the same world (in worst cases between 10-20 minutes)

Note: there are not FPS or performance issues before the crash happens to actually close the game due to peformance or memory being full.

### Other information

Note: a use a total of 101 mods listed in the next text file, all of them specified by bigger, smaller, optimization mods:

[Mods.1.19.2.Fabric.txt](https://github.com/VazkiiMods/Botania/files/10514675/Mods.1.19.2.Fabric.txt)

Just in case you need to check the mods for any incompatibilities + some aditional information of my settings and hardware specifications.

**Comment by williewillus** [comment]
@emilyploszaj any ideas? seems trinkets related, but I can't deobfuscate the stacktrace for some reason....

**Comment by emilyploszaj** [comment]
This is https://bugs.mojang.com/browse/MC-258939

Fabric API recently patched it itself, updating that should fix this issue.

**Comment by JessX0401** [comment]
> This is https://bugs.mojang.com/browse/MC-258939
> 
> Fabric API recently patched it itself, updating that should fix this issue.

I didn't know about the Fabric API update, I have a version that is from the past year (**ver. 0.69.0** of **Dec 11** to be exact) so I recently found the update due to this comment, I'll try playing with the update of said mod and see if the game doesn't crash for the rest of this weekend, if I don't have problems at all I'll close this post.

If I have problems I'll edit this post adding whatever I encounter (unless is the same error I'll just put a note that it keeps crashing with said version of the mods, along another crash log if there's something new I haven't saw on the previous ones).

**Comment by williewillus** [comment]
I'll increase our fapi dep in the next version to require this fix.
