### ISSUE TITLE
V 1.19.2 | Missing references 

### ISSUE THREAD

**Issue by Pidizzel** [Vazkii/Botania#4284]
### Mod Loader

Forge

### Minecraft Version

1.19.2

### Botania version

1.19.2-437

### Modloader version

Forge: 43.2.4

### The latest.log file

https://pastebin.com/XRV56M5e

### Issue description

[Mod Liste.txt] (https://github.com/VazkiiMods/Botania/files/10610607/Mod.Liste.txt)

As soon as I start my server these errors come up in the console.

### Steps to reproduce

1. Starting server 
2. reading console

**Comment by williewillus** [comment]
I'm not actually sure what causes this. Forge does some weird hackery in
the tag system, but as far as I can tell it doesn't really prevent the
game from working as normal. Have you encountered anything weird other
than the log messages?

**Comment by Pidizzel** [comment]
only it crashes in the nether
