### ISSUE TITLE
Suggestions on the balance of the Entropinnyum

### ISSUE THREAD

**Issue by kangzaig** [Vazkii/Botania#4287]
### Mod Loader

Forge

### Minecraft Version

1.12.2-1.19

### Botania version

1.12.2-1.19

### Modloader version

forge

### The latest.log file

suggest

### Issue description

I tried to publish these problems in discord at the beginning,But it doesn't seem to have any result.My original words on discord:
"kangzaig — 今天09:04
First of all, thank you for your interesting mod, but there are some things to say. In China, Botania was called "dye magic" and "magic in science and technology" when it was first introduced into China, but now it is the consensus of all people to call it "tnt magic". I personally think the colorful flower integrated production magic I made is a pioneering invention. But everyone disagrees, and therefore accuses me of not putting forward this useless method of producing magic. Everyone thinks shulker flowers and hot popcorn are good. My tutorial is useless, and those who want to try new methods also give up, because tnt is better. The measures taken by your Botania team to prevent the use of tnt in the higher version are useless. Some integration packages have deleted the craft of tnt flowers and used the magic of throwing tnt into the pool. But most integration packages have changed the magic consumption to very high because of the simple magic of tnt production, and the magic production of shuiker flowers is too large. With the help of various mods, it is very easy to make a large number of shulker sprayers to produce shulker, The problem is that the shulker production mana is far higher than the cost, which are too simple and powerful. If you can't change the tnt flower, why not delete the tnt flower directly? It's also good to add new magic flowers. The tutorial I made is useless because no one will see it. On the contrary, the people who watch the tnt flower tutorial without slime block brush tnt are very supportive. In this regard, if I do not make effective changes to the tnt flower, I can only delete my video, and I will not make any tutorials about the magic of Botania production from now on. https://www.bilibili.com/video/BV1zD4y1N7e6
I have to say
Hot popcorn is tnt flower.
Can you see this? My English level still needs to be improved
Thank you.
I really hope to pay attention to this serious problem
I don't want to ruin Botania's interest because of tnt flowers
But tnt is a game vulnerability, which almost destroys the interest of botania
This is too pessimistic. It's even better to take unlimited mana from your backpack
Wrong, everyone cheats, this is not cheating, it is legal.
[09:33]
There should be more reasonable and interesting ways than tnt flower.
This repair can be said to have little effect. Since we want to change this situation, we should have a thorough solution.
Like most people who play plant magic, he may not understand red stone at all, but he may be very familiar with tnt without mucus.
This is almost everyone in most package , at least in China.
Tnt flower is not interesting in nature, even a simplified version of cake flower，andThis is without using the game loopholes，You can design other more interesting flowers.
oh，btw means unimportant consolidation package
munchdew？
leaf!
yes
That's all I can say. Finally, I hope to pay attention to it.
Yes, this is very important. In my opinion, it can completely detect that tnt is concentrated by the magic beam and turned into a gravity cube to generate magic
Yes Mana lens:Weight
Mana lens:Weight weight block:tnt
This would be a good way
Will you consider the weight block tnt production mana?
There will be no problem because magic production is not as terrible as tnt
I have something else to do. See you tomorrow.About weight tnt, should we go to gitup?
Thank you, everyone here is very warm and interesting."
This may bring you a burden,But I believe you will understand my heart, right？
So,The place I posted may not be very reasonable, but please help me. It is just a place for information transmission, which should be paid attention to.
In fact, the essential step to copy tnt is to move tnt, which can also be started here,The method of detecting mucus and tramcar cannot solve the problem.Finally, with great excitement and gratitude, I would like to thank you for your contributions to my world. Please also pay attention to this issue.

**Comment by kangzaig** [comment]
A good method is to let TNT block explode automatically once it is detected

**Comment by kangzaig** [comment]
Yes, my negligence

**Comment by TheRealWormbo** [comment]
Please correct me if my understanding of this request is off: Your main issue with the Entropinnyum is that people use "cheaty" TNT to produce mana? And your suggestion is, that the Entropinnyum should instead "eat" blocks of TNT that were hit by a mana burst with the effect of the weight lens?

I agree that this would eliminate all TNT duplication issues, but it also makes the flower "too safe". Falling TNT blocks aren't ignited and won't explode if you make any mistakes. The tricky (and fun) part to work around is to handle the danger of explosions if TNT comes too quickly for the flower to handle.

In my opinion, the check for "unethical" TNT needs to be improved somehow. If it could be focused on the moving TNT block instead of the other components, that should cover almost all TNT duper setups. The difficulty, as far as I understand it, is that the primed TNT entity is spawned before the moving TNT block actually exists. But on the plus side, I think only TNT entities spawned while a piston starts moving blocks are candidates for being duped.

**Comment by williewillus** [comment]
Wormbo's changes are as far as this will go, probably.
