### ISSUE TITLE
Ability on Terra Shatterer not working

### ISSUE THREAD

**Issue by 0Juli0** [Vazkii/Botania#4289]
### Mod Loader

Forge

### Minecraft Version

1.19.2

### Botania version

1.19.2-437

### Modloader version

Forge 43.2.1

### The latest.log file

idk

### Issue description

When i try to activate the ability of the terra shatterer it just put torches

### Steps to reproduce

1. Take a terra shatterer
2. Try to activate its ability in any range (other than D)

**Comment by LeoBeliik** [comment]
It was changed, to activate it you need to sneak and right click in the air

**Comment by williewillus** [comment]
^, it was for consistency between the terra pick and the other Botania picks, sorry for the change.
