### ISSUE TITLE
Crash to Desktop when using Construction Wand

### ISSUE THREAD

**Issue by atlgeek007** [Vazkii/Botania#4290]
### Mod Loader

Forge

### Minecraft Version

1.19.2

### Botania version

Botania-1.19.2-437

### Modloader version

Forge 43.2.3 / Botania-1.19.2-437

### Modpack info

All the mods 8

### The latest.log file

https://gist.github.com/atlgeek007/1cacc40cb844f0781237e51f94768151

### Issue description

Whenever I have botania baubles in my inventory (not even equipped), when I attempt to hold a construction wand in my hand, I crash to desktop and I have to edit my player.dat file to get back into the server.

If I put all of my botania baubles in my backpack or my ME system, the crash does not occur.

I have also posted a bug report on the Construction Wand repo - https://github.com/Theta-Dev/ConstructionWand/issues/66

**Comment by williewillus** [comment]
Root cause has been identified in the Construction Wands ticket
