### ISSUE TITLE
spawner

### ISSUE THREAD

**Issue by kangzaig** [Vazkii/Botania#4293]
### Mod Loader

Forge

### Minecraft Version

1.12.2-1.19

### Botania version

1.12.2-1.19

### Modloader version

forge

### The latest.log file

suggest

### Issue description

When using Shulk Me Not, it is recommended to appropriately reduce the power of Shulkers generated by spawner in the production of mana.

**Comment by williewillus** [comment]
I don't understand what this is asking for. Spawners are not available
in vanilla survival, and Botania is balanced around vanilla (not other
ridiculously overpowered mods).

**Comment by kangzaig** [comment]
It is true that in a large number of irregular mods, you can freely modify the high-capacity spawner， but a moderate reduction can improve the status of other kinds of flowers. Reduce the impact of other mods.

**Comment by kangzaig** [comment]
Yes, it is not necessary to see other mods.

**Comment by williewillus** [comment]
The Shulk-Me-Not is supposed to be high-output, because the required vanilla-based set up for it is quite difficult. I don't see anything actionable here, sorry.

**Comment by kangzaig** [comment]
The vanilla version is very reasonable, but those produced by spawner are not reasonable. That's all
