### ISSUE TITLE
Charm of the Diva,Starcaller

### ISSUE THREAD

**Issue by maosansui** [Vazkii/Botania#4294]
### Mod Loader

Forge

### Minecraft Version

1.19.2

### Botania version

1.19.2-437

### Modloader version

43.2.3

### The latest.log file

https://gist.github.com/maosansui/76ae49b7e9c48aa063144d3b5bf89896

### Issue description

1.Charm doesn't work, that mob still attack me
2.starcaller doesn't call star

### Steps to reproduce

<1>find some mobs
attack one
it's still attack me,not attack else mobs
<2>although many attacks,star doesn't come up

**Comment by williewillus** [comment]
Please only report one bug per ticket. The first bug is tracked in Issue
#4064, the second needs more information. Do you have mana? Do you hear
the sound effects and deal damage but just the stars are missing?

**Comment by anoomolu** [comment]
Tested with just deps + some performance mods, Starcaller works like usual with a (filled) mana tablet in inventory on both Forge and Fabric.

**Comment by williewillus** [comment]
the non dupe half of this cannot be reproduced
