### ISSUE TITLE
Light perma dark bug in new botania shaders off

### ISSUE THREAD

**Issue by Pultex** [Vazkii/Botania#4300]
### Mod Loader

Forge

### Minecraft Version

1.19.2

### Botania version

Botania-1.19.2-437-FORGE

### Modloader version

forge-43.2.3

### Modpack info

ATM 8 1.0.10

### The latest.log file

https://gist.github.com/95c4b7603f189d7b8833b467cb1c2db8.git

### Issue description

the darkenss maybe chunk corruption bug from before 
maybe forge related

### Steps to reproduce

1. load world
2. see chunk go dark
3. panic

### Other information

good think I put all botania only in its own chunk
odd the part next to it seems fine just happened too
maybe be related to add-ons for botania 
as I just happen to place an item from Applied-Botanics-1.4.1
I have never used it before this darkness bug

**Comment by Pultex** [comment]
this was sp not server could be part of the problem

EDIT: also I maybe looking at this wrong
I did not think of the Applied Botanics effecting much but read about how the darkness error is happening from possible malformed chunk or botania data

I did have a spark on the applied botanics pool with no connection to a drive at the time
I went to build one an after coming back the chunk was dark
maybe it gave botania back a negative or zero value an the spreaders wanted to transfer anyway

**Comment by Pultex** [comment]
Here is the pitcure again from the other thread
![2023-02-21_13 41 36](https://user-images.githubusercontent.com/34325251/220463282-1c5037a8-f801-4314-b346-1a4953276c21.png)

the sparks are not trying to transfer to it as you would see it show particles
next to the top left pylon

**Comment by Pultex** [comment]
So another test running for a day the problem seem to be from 
Applied Botanics mana pool it must be causing the corrupt chunk data
as it was in a completely different dimension causing the same error

edit: also only a hopperhock is present in the chunk and the AB mana pool

not sure how to fix this or what further damage it will do

**Comment by williewillus** [comment]
the optimize world feature in vanilla should relight all chunks and fix the issue after you remove the offending blocks. I would report the bug to the addon developer, it's likely the same root cause as our original bug #3140 (accessing the world during saving of a block entity). Nothing we can do on our side.
