### ISSUE TITLE
[Crash] Multi Mod Conflict?

### ISSUE THREAD

**Issue by greensad** [Vazkii/Botania#4301]
### Mod Loader

Quilt

### Minecraft Version

Minecraft 1.19.2

### Botania version

Botania 437

### Modloader version

Quilt 18.2

### Modpack info

https://drive.google.com/file/d/1COmoenH9bkAUhim_UHm5wCupqM-hT1NP/view?usp=share_link

### The latest.log file

https://pastebin.com/h3cnFPDj

### Issue description

I'll be totally honest I'm not sure what's going on here but I'm getting a crash with a multitude of mods when enabled in tandem. Removing any one of the following mods seems to fix the crash (some are dependencies however). 

[BCLib 2.1.6](https://modrinth.com/mod/bclib)
[Bedrockify 1.5](https://modrinth.com/mod/bedrockify)
[Bedspreads 6.0.0](https://modrinth.com/mod/bedspreads)
[Better Nether 7.1.3](https://modrinth.com/mod/betternether)
[Better Taskbar 1.5.1](https://modrinth.com/mod/better-taskbar)
[Bookshelf 16.2.17](https://www.curseforge.com/minecraft/mc-mods/bookshelf)
[Botania 437](https://modrinth.com/mod/botania)
[CorgiLib 1.0.0.22](https://modrinth.com/mod/corgilib)
[EMI 0.6.5](https://modrinth.com/mod/emi)
[Enchant the Rainbow 1.1.0](https://modrinth.com/mod/enchant-the-rainbow)
[Enchanting Infuser 4.2.2](https://modrinth.com/mod/enchanting-infuser)
[Enhanced Celestials 2.1.0.5](https://modrinth.com/mod/enhanced-celestials)
[Entity Texture Features 4.3.1](https://modrinth.com/mod/entitytexturefeatures)
[Forge Config API Port 4.2.11](https://modrinth.com/mod/forge-config-api-port)
[Forgero for Fabric 0.10.6](https://modrinth.com/mod/forgero)
[Patchouli 77](https://modrinth.com/mod/patchouli)
[Puzzles Lib 4.3.12](https://modrinth.com/mod/puzzles-lib)
[Quilted Fabric API 4.0.0 beta 28 & QSL 3.0.0 beta 29](https://modrinth.com/mod/qsl/versions)
[Starlight 1.1.1](https://modrinth.com/mod/starlight)
[Trinkets 3.4.2](https://modrinth.com/mod/trinkets)

Posted about this issue on the [forgero tracker](https://github.com/SigmundGranaas/forgero/issues/479) and a dev had this to say:

> So it seems like mixins are failing for Botania in a worldrenerer class. I do believe I also have a mixin there's so It's possible our mods are conflicting on the mixin injection. I think this can be fixed easily, but I'll have to have another look at it when I have some more time.
> 
> Also, not familiar with how quilt handles things, but hopefully that's not the source of the error. Thanks for the report!

If you need anything else please lmk!

### Steps to reproduce

1. Enable the above list of mods.
2. Launch the game.

**Comment by greensad** [comment]
Forgero devs outlined issue here in more detail: https://github.com/SigmundGranaas/forgero/issues/479#issuecomment-1448060256

**Comment by rilakuma123** [comment]
Enhanced Celestials and Bedrockify seem to be incompatible with Botania.

**Comment by LeakingAmps** [comment]
Correct, it seems like in 1.20.1 the incompatibility with Enhanced Celestials has returned.

Crashes are not consistent, which is making it very hard to track down, but it looks like Mekanism??? might be involved too.

Am able to replicate the crash with 

- Botania
- CorgiLib
- Curios
- Enhanced Celestials
- Mekanism
- Patchouli

But not if I remove Mekanism. Again though, as this crash is somewhat random, this could be a red herring. Looking into it more rn.

Edit: This is on Neoforge

Edit 2: Looks like this crash is more unpredictable than I thought; as one of my friends is unable to replicate it, and another can't seem to get a run that doesn't crash. I suspect it's impacted by some kind of load order or race condition, but forcing Botania to load Before or After Celestials didn't work.

Edit 3: Given that this topic is from a year and change ago and is for a different minecraft version and modloader, I'm going to make a separate issue.

**Comment by TheRealWormbo** [comment]
We will look into better mixin compatibility with the 1.21 port, but since 1.19 is no longer supported, I'm going to close this particular issue as there's still #4607 to track a similar problem in a more recent version.
