### ISSUE TITLE
Ok, it is not a bug.

### ISSUE THREAD

**Issue by kotvkvante** [Vazkii/Botania#4302]
### Mod Loader

Forge

### Minecraft Version

1.7.10

### Botania version

1.8-249

### Modloader version

36.29 

### The latest.log file

fu

### Issue description

I read that suggestions are not accepted, but I need to write my idea somewhere (you know i'm just stupid and dont understand words =) ).

Is it possible make thermalily flower able consume fuels from another mods? Like oil from IC2, propellant from Ender IO etc. 
It make this flower more usefull. 

Sorry for wasting your time

**Comment by Alwinfy** [comment]
Out of scope. Feel free to write an addon, though!
