### ISSUE TITLE
Visual Bug

### ISSUE THREAD

**Issue by Matacael** [Vazkii/Botania#4304]
### Mod Loader

Forge

### Minecraft Version

1.19.2

### Botania version

Botania-1.19.2-437-FORGE.jar

### Modloader version

Forge: 43.2.4

### The latest.log file

https://pastebin.com/VRFa688m

### Issue description

With Shaders you can not see some attacks, for example with the key of the king's law

### Steps to reproduce

1. Take the Key of The king's law
2. Enable your shaders (for example: ComplementaryReimagined_r1.4)
3. Use the Key
![image](https://user-images.githubusercontent.com/126263088/221202273-5d2a8b74-20af-4160-a762-0fbd55082db4.png)

**Comment by williewillus** [comment]
3658e48 reintroduces the option to disable botania's own shaders which should fix this
