### ISSUE TITLE
Hopperhock can't place compostable items inside composters

### ISSUE THREAD

**Issue by LeoBeliik** [Vazkii/Botania#4305]
### Mod Loader

Forge

### Minecraft Version

1.19.2

### Botania version

Botania-1.19.2-437-FORGE

### Modloader version

Forge 1.19.2 - 43.1.65

### The latest.log file

-

### Issue description

![imagen](https://user-images.githubusercontent.com/11804768/221696947-3d3f3051-a684-419f-abbc-42ff5c829e6a.png)

### Steps to reproduce

place composter
put hopperhock on top / next to it
throw compostable item nearby

**Comment by TheRealWormbo** [comment]
~~Situation seems worse on Fabric: A floating hopperhock on a composter removes items, pretending to insert them, but the composter state does not change.~~
On Forge the hopperhock simply doesn't recognize the composter as insertable inventory in the first place.

**Comment by TheRealWormbo** [comment]
Good news, everyone: Fabric's composter handling via the `ItemStorage.SIDED` API is buggy. Composters, when filled by hand or via hopper, have a 100% chance to fill the first level, regardless of the input "quality". Fabric's implementation applies the same chance there as for the higher layers, making somewhat worse use of the composting material.

**Comment by TheRealWormbo** [comment]
For reference, the Fabric inconsistency issue is also fixed: https://github.com/FabricMC/fabric/issues/3017
