### ISSUE TITLE
optifine disables mana hud

### ISSUE THREAD

**Issue by C8236** [Vazkii/Botania#4309]
### Mod Loader

Forge

### Minecraft Version

1.19.2

### Botania version

1.19.2-437

### Modloader version

forge-43.2.0

### The latest.log file

https://pastebin.com/B411DZEX

### Issue description

having optifine disables the hud that shows mana bar

### Steps to reproduce

installing optifine

**Comment by ghost** [comment]
I can confirm that there are issues when Optifine is present in the modlist. However it isn't just that the mana hud doesn't load, the entire mana system just doesn't work. For me I had used endoflame flowers to burn coal blocks for a while before I noticed that no mana had built up in my pools. After trial and error to figure out the issue, there was no mana in the entire system after I removed Optifine.

**Comment by williewillus** [comment]
Optifine isn't supported, sorry.
