### ISSUE TITLE
Ring of Correction anti-corrects when using Farmer's Delight's cutting board

### ISSUE THREAD

**Issue by Ganpan14O** [Vazkii/Botania#4317]
### Mod Loader

Forge

### Minecraft Version

1.18.2

### Botania version

1.18.2-435

### Modloader version

Forge - 40.2.0

### Modpack info

https://www.curseforge.com/minecraft/modpacks/survivors-beginnings

### The latest.log file

https://gist.github.com/Ganpan14O/9d437d3b1ba1d3804f909aa6717c7042

### Issue description

When using a cutting board from Farmer's Delight the Ring of Correction will "correct" the item you're using to an Axe.

### Steps to reproduce

1. Install Farmer's Delight and Botania
2.  Get a Ring of Correction, Manasteel Shovel, Manasteel Axe, Creative Mana Tablet, Cutting Board, and stack of Gravel
3. Place a Cutting Board and hold a stack of Gravel in your offhand and a manasteel shovel in your main hand with a manasteel axe elsewhere in your inventory.
4.  Right click on the cutting board. The ring will correct the shovel to an axe.

**Comment by TheRealWormbo** [comment]
Technically the ring does a "correct" thing, as the cutting board's preferred tool for breaking is the axe. The thing just is that the axe is a tool for breaking, not for using. I wonder if there simply shouldn't be any corrections for using instead of attacking.

**Comment by Ganpan14O** [comment]
> Technically the ring does a "correct" thing, as the cutting board's preferred tool for breaking is the axe. The thing just is that the axe is a tool for breaking, not for using. I wonder if there simply shouldn't be any corrections for using instead of attacking.

Yeah, I think the not changing when right clicking would work, or maybe some form of right click blacklist.

**Comment by TheRealWormbo** [comment]
I could imagine block tags like `#botania:no_correction_breaking` for not trying to select the correct tool while left-clicking on a tagged block (I could see that being useful for things like the Corporea Crystal Cube or storage drawers that you punch to get items out). For right-clicking I can see two possible ways to implement, either as an allow list or an exclude list. Allow list would be more restrictive, but automatically covers that it would be pointless to switch to an axe for a cutting board or already stripped log, while an exclude list would ensure the ring works on all such blocks, but mod/pack authors can turn off unwanted interactions, like the one for the cutting board.
We will need to discuss this internally to figure out what the better approach would be.

**Comment by TheRealWormbo** [comment]
Upon closer inspection, the ring probably shouldn't even activate for right-click actions. There are way too many corner cases and even undecidable situations. For example, the correct tool for right-clicking a (waxed or aged) copper block is an axe, not a pickaxe, but the player might have meant to actually use honeycomb. And what even is the correct tool for right-clicking a dirt or grass block – a shovel or a hoe, or maybe the water bottle or Botania grass seed in the next slot over? And then there are things like the cutting board mentioned in this issue, where the block itself decides the correct tool, based on information the ring does not have.

The Ring of Correction will be restricted to block breaking, as the Lexica Botania already suggests.
