### ISSUE TITLE
Game crashes with EXCEPTION_ACCESS_VIOLATION

### ISSUE THREAD

**Issue by JomerDev** [Vazkii/Botania#4318]
### Mod Loader

Forge

### Minecraft Version

1.19.2

### Botania version

1.19.2-438

### Modloader version

forge-43.2.6

### Modpack info

All the mods 8

### The latest.log file

https://gist.github.com/JomerDev/0d6e1274dafbbc765105fa1cd7f2d49c

### Issue description

The game crashes a few seconds after load. The stacktrace shows botania

### Steps to reproduce

Seems safe specific

### Other information

I tried both updating my java and my graphic drivers, it didn't change anything

**Comment by williewillus** [comment]
Does this happen every time? The native crashlog shows that it's inside `nvoglv64.dll` which sounds like an Nvidia graphics driver. Don't know if there's anything we can do here.

**Comment by JomerDev** [comment]
It happened multiple times after I loaded up the world, but then stopped after it started raining ingame. I assume that that caused something to despawn. It happened again with renders from other mods, so a graphics driver bug seems likely

**Comment by williewillus** [comment]
Closing as native crashes are probably not Botania's fault
