### ISSUE TITLE
[1.19.2] thunder sword particles don't render on server

### ISSUE THREAD

**Issue by LeoBeliik** [Vazkii/Botania#4323]
### Mod Loader

Forge

### Minecraft Version

1.19.2

### Botania version

Botania-1.19.2-438-FORGE

### Modloader version

43.2.8

### The latest.log file

-

### Issue description

The lightning particle from the thundercaller don't render on server, I saw one once, the first time I used the sword and then never again, the AOE still works

### Steps to reproduce

create a server
join
get a thunder sword 
get mana (optional?)
attack a bunch of mobs

### Other information

Seems like this has been brok since 1.7.10
https://discord.com/channels/154261184701267969/481719529337258004/1091504201483436113

**Comment by williewillus** [comment]
Hmm, I fixed this "recently". Not sure why it's broken again.

**Comment by williewillus** [comment]
I can't reproduce this.

**Comment by LeoBeliik** [comment]
Hmm.. I don't actually remember, but I may have only tested it with passive mobs that time, tested it again now with zombies and it works, so I'm closing it 😅
