### ISSUE TITLE
Crash: Tesselating block model

### ISSUE THREAD

**Issue by aaronhowser1** [Vazkii/Botania#4324]
### Mod Loader

Forge

### Minecraft Version

1.19.2

### Botania version

Botania-1.19.2-438-FORGE

### Modloader version

Forge 43.2.8

### The latest.log file

https://gist.github.com/aaronhowser1/579ee521f1053abe10fc15902cce1c9b

### Issue description

Crash report: https://gist.github.com/aaronhowser1/d4d48f5d108bb929a79bb230e88dd549

### Other information

I thought it was a problem with Rubidium, but removing it didn't solve the crash

**Comment by aaronhowser1** [comment]
![image](https://user-images.githubusercontent.com/15698722/230953995-0ffc9ad0-84f3-40a0-b099-14a563d1545b.png)

Very interesting: adding any of these 3 mods causes the game to crash. Without them, the game doesn't crash.

EDIT: as does Rubidium.

**Comment by aaronhowser1** [comment]
If I add back all the mods that I removed in the Binary search, including the ones above, and then *remove* Botanic Additions, it does not crash. However, that's because it removes the floating flower that was causing the crash. 

Placing a normal floating flower added by the main mod does not cause a crash, nor does relogging etc while it's being rendered. I suppose I'll move this to the Botanic Additions tracker.

**Comment by TheRealWormbo** [comment]
Sounds familiar: #4030

**Comment by TheRealWormbo** [comment]
Won't be fixed in 1.19 anymore.
