### ISSUE TITLE
Slime Island

### ISSUE THREAD

**Issue by GoldenMarionette** [Vazkii/Botania#4331]
### Mod Loader

Forge

### Minecraft Version

1.18.2

### Botania version

1.18.2-435

### Modloader version

Forge 1.18.2-40.2.0

### The latest.log file

I dont know how to find this and it isnt a crashing issue

### Issue description

Whenever I load a new world with Tinkers construct and Botania, Botania removes the slime islands that tinkers is supposed to generate. Whenever you do the locate biome command it says there is supposed to be one at "this location" and when you teleport to it, it doesnt exist. I have taken botania out of the mod list and started a new world and the islands appear. Is there a way to fix this easily?

### Other information

Tinkers construct Botania

**Comment by williewillus** [comment]
Do you have Garden of Glass installed?

**Comment by williewillus** [comment]
Please give a seed that reproduces this issue with only TC and Botania installed

**Comment by GoldenMarionette** [comment]
No I do not have Garden of Glass installed and heres a seed 3151849325801076817. Btw, sorry for not getting back sooner. I figured that it would be a few days before I got a response as I know how busy people are lol.
Heres the locate command so you dont have to look for it: /locatebiome #tconstruct:islands/earthslime
And this is without any other mod except the dependancies.
![Screenshot 2023-04-18 110043](https://user-images.githubusercontent.com/130859643/232836149-44e163c5-5044-47d3-b8a1-e15c601ebc07.png)

**Comment by GoldenMarionette** [comment]
But like I said its not any specific seed that does it it is any new world that does this.

**Comment by anoomolu** [comment]
Hiya, are you still having this problem? I just tested with the latest 1.18.2 versions of the mods you listed and have been able to find slime islands just fine with /locate.

![image](https://github.com/VazkiiMods/Botania/assets/77850233/bf4399a2-c7cb-4fb8-bf7e-fe445d0afcfa)
 This was with the seed you provided.
![image](https://github.com/VazkiiMods/Botania/assets/77850233/707edde5-6322-475c-ba2b-b6319376baef)
 And these were the mods used.

**Comment by anoomolu** [comment]
Closing this as it can't be reproduced with just Tinkers and Botania.
