### ISSUE TITLE
Holding flower pouch reduces FPS

### ISSUE THREAD

**Issue by 4RealHaxt0rZ** [Vazkii/Botania#4332]
### Mod Loader

Forge

### Minecraft Version

1.19.2

### Botania version

3.0.0

### Modloader version

43.2.6

### Modpack info

ATM8, but I added around a hundred extra mods to it https://www.curseforge.com/minecraft/modpacks/all-the-mods-8

### The latest.log file

https://gist.github.com/4RealHaxt0rZ/a7d40b0139c97c75855537c69d7663c0

### Issue description

When holding, or even hovering my mouse over the flower pouch in my inventory, I get massive lag, reducing my FPS from 90fps to 0.5-1fps, instantly disappears when I switch my hotbar slot or move my mouse off the pouch
hovering my mouse over the pouch causes MUCH less lag than holding it

### Steps to reproduce

Make world and make a flower pouch, with or without flowers inside

hold flower pouch or hover mouse over it

frame rate drops

**Comment by TheRealWormbo** [comment]
Is that a log from when you experienced the FPS reduction? It seems very incomplete, cut off during what I assume was still the loading phase of the world.

**Comment by 4RealHaxt0rZ** [comment]
I think so? I launched the game, ran around for a bit holding the flower pouch with like 1fps, then let go, did that like 3 times, then quit the game, and put the latest zip file in the log, the game takes about 2 minutes to start up, then another 2 minutes for the world to load, but the world runs fine afterwards

Edit: threw the flower pouch in the trash slot (from a mod), and it crashed my game, had some error to do with too many characters, loaded the game back up and it was gone, gave myself a new flower pouch and I'm not having the problem anymore, think there was a glitch with the item NBT data, think there was too much NBT data in 1 item so it crashed the game, not sure how that got there though

**Comment by anoomolu** [comment]
Closing this as you've seemed to find the source of the issue. Tested myself regardless, didn't observe any noticeable FPS drop.
