### ISSUE TITLE
Hud issue

### ISSUE THREAD

**Issue by ZzBlueMoonzZ** [Vazkii/Botania#4338]
### Mod Loader

Forge

### Minecraft Version

1.19.2

### Botania version

1.19.2-438

### Modloader version

Forge: 43.2.6

### The latest.log file

2023-04-17-2

### Issue description

When I’m holding a wand of the forest and I’m looking towards a mana pool or a mana spreader the HUD doesn’t appear and I can’t see the mana being transferred

**Comment by TheRealWormbo** [comment]
Are you using Optifine? It's a known issue the Botania folks can't do anything about.

**Comment by williewillus** [comment]
uninstall optifine
