### ISSUE TITLE
Various Botania game events don't trigger sculk sensors

### ISSUE THREAD

**Issue by TheRealWormbo** [Vazkii/Botania#4349]
### Mod Loader

Both Fabric and Forge (I confirm that I have tested both loaders and will specify both loader versions below)

### Minecraft Version

1.19.2

### Botania version

1.19.2-438

### Modloader version

any

### The latest.log file

(n/a)

### Issue description

Events that don't trigger sculk sensors, but are silent, so maybe that's correct:

- Animated torch changing direction
- Hovering hourglass putting in or taking out sand
- Hovering hourglass flipping
- Interacting with a Tiny Potato (empty hand, giving item, taking item away)
- Adding or removing incense stick from incense plate (maybe this shouldn't be silent)
- Applying pasture seeds (or any of the similar items that spread grass/dirt variants; maybe applying the item should have some kind of subtle sound effect as well; ~~then again, applying bone meal makes no vibrations either~~ bone meal causes vibrations since 1.20.2)
- Adding or removing a (mana or corporea) spark (maybe this shouldn't be silent)
- Applying or removing a spark augment (maybe this shouldn't be silent)
- Spectrolus eating wool or sheep (items being grabbed by flowers is silent in general, though)
- Bubbell displacing water
- Agricarnating speeding up growth (then again, bone mealing things also doesn't cause vibrations)
- Tigerseye "petrifying" creepers

Events that don't trigger sculk sensors, but maybe should:

- Interacting with Petal Apothecary (adding water, adding or removing ingredients, crafting a result)
- Interacting with Runic Altar (adding ingredients, adding final ingredient, crafting result)
- Mana pool infusing item
- Manatide Bellows hissing (activated by player, or activating automatically for mana pool to item transfer)
- Adding or removing lens from Mana Prism (adding/removing lens causes vibration for mana spreaders)
- Lighting incense stick on incense plate using flint and steel
- Luminizer transportation (mounting, traveling, dismounting; both via block interaction or Luminizer Launcher)
- Special flowers playing effects: (list is probably incomplete)
  - Hydroangeas sipping water
  - Thermalily sipping lava
  - Endoflame burning item
  - Gourmaryllis, Munchdew, or Kekimurus eating
  - Orechid turning block into ore
  - Clayconia turning sand to clay (the clay items trigger the sensor when they hit the ground, though)
  - Pure Daisy converting blocks
  - Shulk Me Not consuming mobs (the noise comes from the flower)
  - Jaded Amaranthus placing flowers
- Using rods that don't place permanent blocks:
  - Rod of the Bifrost blocks appearing or disappearing
  - Rod of the Hells activating fire
  - Rod of the Skies propelling player
  - Converting blocks with Rod of the Molten Core
  - Rod of the Plentiful Mantle activating
  - Rod of the Shaded Mesa grabbing, holding or launching
- Livingwood Avatar activating rods, including those that place blocks
- Using Overgrowth Seed on a grass block
- Opening the Lexica Botania (opening writable/written books doesn't cause vibrations either, though)
- Using Horn of the Wild/Canopy/Covering (their block breaking does make vibrations, though)
- Using Hand of Ender (for yourself or on another player)
- Using Cacophonium to play a mob sound
- Playing a Cacophonium block
- Toggling Stone of Temperance
- Toggling Terra Shatterer
- Toggling Blackhole Talisman
- Teleporting via World Seed or Eye of the Flügel (arriving via Eye plays the vibration for "stop using item", see below)
- Eating Fruit of Grisaia
- Bore lens mana burst breaking a block (triggers projectile hit, even when the block break event should be closer)
- Shard of Laputa (only the mana bursts trigger "projectile shoot" vibrations, no block breaking/placing vibrations, or using the shard itself)

Events that trigger sculk sensors, but maybe shouldn't:

- Adding a wool cover to mana spreaders
- Changing wool-covered spreader orientation with Wand of the Forest
- Breaking a covered mana spreader
- Stopping use of any rods with a use animation (Molten Core, Unstable Reservoir)
- Stopping use of any horn
- Stopping use of the Cacophonium
- Stopping use of the Eye of the Flügel (especially without teleporting)
- Stopping to eat Fruit of Grisaia

While it would probably be correct to have covered spreaders dampen/block vibrations, that's likely not possible, since it's controlled through block tags and the covered spreader is not a separate block type.

**Comment by williewillus** [comment]
In general I don't think it's a good idea to overload even more crap onto the vanilla Sculk Sensor (which already is way too sensitive and picks up too many things/lots of things are overloaded onto the same redstone power level).

We can register and fire our own GameEvents but I don't think making the vanilla Sculk sensor fire (beyond what it already does) is desired.

**Comment by TheRealWormbo** [comment]
Is the "more sculk sensor events = bad" assessment still applicable with the calibrated sculk sensor being a thing?

**Comment by TheRealWormbo** [comment]
Moving spreader covers from block entity attribute to block types is on the list of potential 1.21 changes now. That will allow letting them occlude vibrations (their own and others) via block tags.
Some of the "stop using" and "projectile shoot" vibrations are hard-coded deep in some vanilla logic, and will require mixins. The plan to add MixinExtras for the 1.21 port should make it easier to skip the corresponding calls without the code becoming too messy.
