### ISSUE TITLE
Quests Broken?

### ISSUE THREAD

**Issue by SocialIssues** [Vazkii/Botania#4354]
### Mod Loader

Fabric

### Minecraft Version

1.19.2

### Botania version

1.19.2

### Modloader version

Fabric

### Modpack info

All of fabric 6

### The latest.log file

unavailable

### Issue description

The quest book isnt progressing. i got the book for botania and it wont let me do find mystical flowers. how do i fix

**Comment by LeoBeliik** [comment]
I think that advancement only work with 2 tall flowers at the moment, have you acquired one of those?

**Comment by quat1024** [comment]
Botania doesn't have quests (apart from the manual-complete ones in the back chapter of the Lexica), report this to your modpack author

**Comment by williewillus** [comment]
The bug with Sky of Beginning has been resolved
