### ISSUE TITLE
Ignite lens flames wrong color

### ISSUE THREAD

**Issue by troyheady2** [Vazkii/Botania#4355]
### Mod Loader

Fabric

### Minecraft Version

1.19.2

### Botania version

Botania-1.19.2-438-FABRIC

### Modloader version

Fabric 

### Modpack info

https://www.curseforge.com/minecraft/modpacks/all-of-fabric-6

### The latest.log file

https://gist.github.com/troyheady2/697160de28662ee75beb402cb2a3a3a1

### Issue description

when using the ignite lens on soul sand. it it creating a yellow flame instead of the excepted blue flame.

### Steps to reproduce

run AOF6 modpack

setup mana pool (with mana), pulse mana spreader pointing at soul sand block.  button
Place ignite lens on spreader
press button to active pulse.

Flame is yellow but blue

**Comment by anoomolu** [comment]
Can confirm this happens on -439 in an instance with just Botania + deps, on both Forge and Fabric. Once the block that the mana burst collided with is removed, the flame goes back to blue.
