### ISSUE TITLE
Comparators do not properly update the signal they output when a Thermalily goes on cooldown mode

### ISSUE THREAD

**Issue by beholderface** [Vazkii/Botania#4364]
### Mod Loader

Forge

### Minecraft Version

1.19.2

### Botania version

1.19.2-439

### Modloader version

Forge 43.2.6

### Modpack info

N/A

### The latest.log file

https://pastebin.com/cUfiEG5v

### Issue description

[Demonstration video](https://youtu.be/2EkhS7URnjA). The same behavior occurs when not directly modifying the NBT.
When a Thermalily goes on cooldown mode, it does not cause comparators looking at it to update the signal they output. The comparators must receive a block update in order to update the signal.

### Steps to reproduce

1. Place comparator reading from a Thermalily and outputting to a redstone wire
2. Give the Thermalily some lava, wait for it to go on cooldown
3. Observe that the power level in the redstone wire does not change

### Other information

Full modlist :

![image](https://github.com/VazkiiMods/Botania/assets/13290805/33c3793c-0a92-47db-811b-c5d3b100b031)

**Comment by beholderface** [comment]
It works as expected with the red string comparator
![2023-05-15_16 01 59](https://github.com/VazkiiMods/Botania/assets/13290805/2d3b40ce-659b-4ba0-8fe8-69a8b9d6aeab)

**Comment by TheRealWormbo** [comment]
The Thermalily's block entity doesn't appear to call `setChanged()` to notify nearby comparators, like e.g. furnaces or brewing stands do.
