### ISSUE TITLE
English language file conflict and Rod of the Shaded Mesa cannot be installed to avatar in 1.19.2

### ISSUE THREAD

**Issue by Dawnwalker666** [Vazkii/Botania#4367]
### Mod Loader

Forge

### Minecraft Version

1.19.2

### Botania version

1.19.2-439

### Modloader version

43.2.11

### The latest.log file

no such thing...

### Issue description

When I translated into Chinese, I found in the English files, "botania.page.thermalily1" and "botania.page.thermalily2" have conflicting expressions.The former says the cooldown time varies from 20 seconds to a full 5 minutes. The latter says that it will not continue to produce mana until after the 5 minutes cooldown period is over.When I went to discord to ask, I realized that the former was correct. But I... What can I do?
And when I checked the changelog about Rod of the Shaded Mesa, I found that in 1.16.1-403 it says you can install to avatar and targets all hostile mobs.But I found in 1.19.2 detailed testing, Rod of the Shaded Mesa can not be loaded to the avatar, I do not know if it is considered a bug, or in a version removed this feature.

**Comment by williewillus** [comment]
The changelog has a typo, it means the Rod of the Unstable Reservoir.

**Comment by williewillus** [comment]
For the first question, I don't see how the two statements conflict? thermalily1 says the cooldown is chosen randomly between 20s and 5min. thermalily2 says if you give the flower any Lava during the cooldown time, it will reset the cooldown.

**Comment by williewillus** [comment]
[bd5c644](https://github.com/VazkiiMods/Botania/commit/bd5c644356fa0456efc3773c8829517f1f2c5808) to fix the changelog

**Comment by Dawnwalker666** [comment]
> For the first question, I don't see how the two statements conflict? thermalily1 says the cooldown is chosen randomly between 20s and 5min. thermalily2 says if you give the flower any Lava during the cooldown time, it will reset the cooldown.

I see, I downloaded the latest version of botania. but this problem was fixed a few days ago...My fault...So the language files may not be up to date...

So in that case, I probably need to download the language files on GitHub again for the Chinese update. After all, the Chinese language files in this commit are only based on version 1.19.2-439. I'm sure a lot of things have been updated in two months.
5bc8f601606325b65fbb7fbe46e0fb564dd99f3e

**Comment by Dawnwalker666** [comment]
But the newly changed text was submitted on March 6 and the 439 version was updated on March 15. I can't believe the text wasn't changed? So when is the English text of 439 up to?

**Comment by Dawnwalker666** [comment]
The other is "botaniamisc.optifine_warning" in line 31, where it says it is recommended to use Sodium instead of your ~~favorite~~ Optifine. but Sodium only works in forge.

**Comment by williewillus** [comment]
There are unofficial sodium ports to forge. They will definitely work better than optifine, but we didn't want to recommend them outright since they are unofficial after all.

Anyways, I think everything in this task has been addressed, so closing. Feel free to open another one if other stuff comes up.
