### ISSUE TITLE
Flugel tiara "black snow princess" wings look off

### ISSUE THREAD

**Issue by anoomolu** [Vazkii/Botania#4370]
### Mod Loader

Forge

### Minecraft Version

1.19.2

### Botania version

1.19.2-439

### Modloader version

Forge: 43.2

### The latest.log file

n/a

### Issue description

Hiya. Like the title says, on Forge I'm experiencing a visual bug with the Black Snow Princess wings for the Flugel Tiara. Below is what they look like:
![image](https://github.com/VazkiiMods/Botania/assets/77850233/6f1fe5d9-01c0-47f0-9ef9-988919dabfed)

This is what they are supposed to look like:
![image](https://github.com/VazkiiMods/Botania/assets/77850233/26e2f5e5-2c30-4156-8270-5005991c12dd)

This was observed in a minimally modded instance without Rubidium. The issue does not occur on Fabric.

**Comment by williewillus** [comment]
We just use the vanilla rendering paths for bakedmodels, so I'm tempted to say it's a forge bug (since forge actually has its own copy of the model generator logic, iirc).

Can you repro by just holding an item on Forge and looking carefully at the seams in hand in fullscreen?

**Comment by anoomolu** [comment]
Seems like it's a problem with forge itself like you mentioned, happens when holding vanilla items too (e.g diamond sword). No worries then, thanks for the info ^^
