### ISSUE TITLE
Narslimmus overshadows other mana-generating flowers on GoG

### ISSUE THREAD

**Issue by anoomolu** [Vazkii/Botania#4372]
### Mod Loader

Both Fabric and Forge (I confirm that I have tested both loaders and will specify both loader versions below)

### Minecraft Version

1.19+

### Botania version

1.19+

### Modloader version

n/a

### The latest.log file

n/a

### Issue description

Setting up a slime chunk to use the Narslimmus typically requires a fair bit of time investment, one that could be spent on automating other flowers for larger mana gains. However, in Garden of Glass where mob spawning is limited to areas the player hasn't lit up (intentionally or otherwise), the Narslimmus is much more efficient. It's not too hard to rush a Slime in a Jar after making your first piece of elementium, then reaping the rewards of basically free mana, going against the automation puzzles that Botania creates.

I did a quick experiment with an 11-long Gourm chain using non-meat foods and found a single large slime produces quite a bit more mana.

A discussion on [Discord](https://discord.com/channels/154261184701267969/1079855089767952496/1099401950216335380) considered nerfing the base value of a small slime to ~1/4 of its current value (1/3 suggested by myself, 1/4-1/5 by Wormbo). In this way, those fortunate enough to find a slime chunk within/near their island can still get value out of the flower, while not vastly accelerating progression/disincentivising players from automating other flowers.

**Comment by TheRealWormbo** [comment]
If my calculations are correct, a single Narslimmus at 25% mana output can still outperform any single Gourmaryllis (even with 8-streak of 12-point foods) or the theoretically fastest Botania-only Dandelifeon setup. Reasonably fast Entropinnyum or Spectrolus setups do have a good chance, though.
