### ISSUE TITLE
Only river biome in GoG

### ISSUE THREAD

**Issue by CrimCroogle** [Vazkii/Botania#4376]
### Mod Loader

Forge

### Minecraft Version

1.19.2

### Botania version

1.19.2

### Modloader version

Forge - 43.2.11

### The latest.log file

https://pastebin.com/NAQ7MSvR

### Issue description

If you choose Garden of Glass type world, there will be no other biomes besides River, even for thousands of blocks it will be river, minecraft itself doesn't spawn any structures cuz it can't

I am using gardenofglass-1.11.jar, the latest version for 1.19.2

Using a bounding box mod, i could not find any regions that would be there by using chunkbase

### Steps to reproduce

1. Create a GoG World

**Comment by anoomolu** [comment]
Reproduced with just Botania, GoG + deps on both Forge and Fabric. Issue isn't present in gardenofglass-1.10 so something has broken between 1.18 and 1.19.
