### ISSUE TITLE
Key of The King's Law destroys items

### ISSUE THREAD

**Issue by zacharybarbanell** [Vazkii/Botania#4384]
The Key of The King's Law is made pretty ineffective as a weapon since you can't use it without fear of it destroying the items dropped by whatever you're trying to kill.  The best fix for this would be to make those explosions not destroy items.

**Comment by anoomolu** [comment]
Can be closed, the [PR ](https://github.com/VazkiiMods/Botania/pull/4402)fixing this was merged a while back.
