### ISSUE TITLE
Lexicon entry for Generating Flora does not mention the output rate philosophy

### ISSUE THREAD

**Issue by TheRealWormbo** [Vazkii/Botania#4394]
### Mod Loader

Both Fabric and Forge (I confirm that I have tested both loaders and will specify both loader versions below)

### Minecraft Version

1.19.2

### Botania version

1.19.2-440

### Modloader version

(n/a)

### Modpack info

(n/a)

### The latest.log file

(n/a)

### Issue description

Often when someone asks for help with mana generation or which flower(s) to use, some responses (on Discord or Reddit) will usually point out that Botania's generating flowers produce mana roughly corresponding to their required automation effort. This is not mentioned anywhere in the lexicon entry for "Generating Flora", but probably should at least be hinted at.

The only suggestion it mentions is that Endoflame and Hydroangeas are considered starter flowers. And while that somewhat implies you should upgrade, many players don't seem to get that hint. Maybe the individual flower descriptions should also make a better effort at describing the amount of mana you can expect. (e.g. for Endoflame it could be something like "…to generate Mana at a very low rate.")

### Other information

The second page on Generating Flora seems like a good place to add a short paragraph for the general information, as it already talks about general mana output mechanics and currently takes up less than half the page in the English version.

**Comment by anoomolu** [comment]
I think the Lexicon does a decent job of encouraging players to diversify their mana generation - the Endoflame page says it's a very rudimentary generating flower, while the Hydroangeas page states 

> even ... during rain, their mana throughput is still rather slow.

For the "Generating Flowers" page, I guess something along the lines of: 

> Generating Flowers requiring more complex infrastructure can be expected to produce more mana.

could be added to the end.

The endoflame page could be edited with the words in brackets:
> ... and burn through them to generate (a trickle of) mana.

**Comment by anoomolu** [comment]
https://github.com/VazkiiMods/Botania/commit/5e235fcbfbf0912382798650c08fc344ca81f677 should close this.
