### ISSUE TITLE
Crash Initializing game - Botania 1.19.2-440-FABRIC

### ISSUE THREAD

**Issue by ClaudiusMinimus** [Vazkii/Botania#4399]
### Mod Loader

Fabric

### Minecraft Version

1.19.2

### Botania version

Botania 1.19.2-440-FABRIC

### Modloader version

Fabric 0.14.21

### Modpack info

https://legacy.curseforge.com/minecraft/modpacks/create-conquest-arcane

### The latest.log file

https://pastebin.com/x6GjeUuB

### Issue description

I was updating my pack and when I updated Botania to 1.19.2-440-FABRIC the client crashed on launch. Reverted to 339.

Crash report
[Formatted](https://crashy.net/e7d38c47-7802-4c93-a82b-074dfc676ad0)
[Raw](https://crashy.net/e7d38c47-7802-4c93-a82b-074dfc676ad0/raw.txt)

**Comment by williewillus** [comment]
KubeJS was reaching into Botania's internals, and now it's crashing because we changed said internals. Please report it to them and send the log along. Thanks!

**Comment by ClaudiusMinimus** [comment]
https://github.com/Prunoideae/KubeJS-Botania/issues/4
