### ISSUE TITLE
Full and Creative tablets are missing in creative menu and EMI

### ISSUE THREAD

**Issue by zacharybarbanell** [Vazkii/Botania#4400]
### Mod Loader

Fabric

### Minecraft Version

1.19.4

### Botania version

1.19.4-441-FABRIC-SNAPSHOT

### Modloader version

0.14.19

### The latest.log file

N/A

### Issue description

The full mana tablet and creative mana tablet don't show up in the creative menu or in EMI

**Comment by anoomolu** [comment]
Can confirm on the 1.20.1 beta release, flasks/vials aren't showing up either.

**Comment by williewillus** [comment]
a7976b2597bdc179e9205a23f9a595c7885a12c8
