### ISSUE TITLE
Mana Tablets' fullness bar renders in wrong place when hovered in inventory

### ISSUE THREAD

**Issue by zacharybarbanell** [Vazkii/Botania#4401]
### Mod Loader

Fabric

### Minecraft Version

1.19.4

### Botania version

1.19.4-441-FABRIC-SNAPSHOT

### Modloader version

0.14.19

### The latest.log file

N/A

### Issue description

When hovering over a mana tablet, instead of the bar showing how much mana it has appearing in the tooltip, it appears near the top-left of the screen.

**Comment by williewillus** [comment]
no longer a problem on trunk
