### ISSUE TITLE
slf4j no providers were found

### ISSUE THREAD

**Issue by 77wisher77** [Vazkii/Botania#4407]
### Mod Loader

Forge

### Minecraft Version

1.19.4

### Botania version

1.19.2-440

### Modloader version

Forge 45.1.0

### The latest.log file

https://pastebin.com/RcCarLFY

### Issue description

When launching the minecraft instance an error complaining about slf4j having no providers appears

### Steps to reproduce

1. Install Forge 45.1.0 for MC 1.19.4
2. Install Botania
3. run minecraft

### Other information

I don't see any information about the issue in the log file

**Comment by artemisSystem** [comment]
Where does this message appear? In a popup ingame? Does it prevent you from playing? Can you send a screenshot of what it looks like? I've never seen anything like this

**Comment by 77wisher77** [comment]
In the launcher before the game window even appears, the error prevents the game window from appearing 

i'm using GDLauncher here as im on linux and it has a linux version

![image](https://i.imgur.com/rG88gxq.png)

**Comment by williewillus** [comment]
You're trying to run botania 1.19.2 on 1.19.4.

Botania 1.19.4 does not exist.
