### ISSUE TITLE
Marimorphosis does not convert tuff

### ISSUE THREAD

**Issue by TheRealWormbo** [Vazkii/Botania#4415]
### Mod Loader

Both Fabric and Forge (I confirm that I have tested both loaders and will specify both loader versions below)

### Minecraft Version

1.19.2

### Botania version

1.19.2-440

### Modloader version

(any)

### Modpack info

(none)

### The latest.log file

(n/a)

### Issue description

The block tag `botania:marimorphosis_convertable` contains natural stone, natural deepslate, as well as the stone variants andesite, granite, and diorite. It seems only logical that tuff would be convertible as well, but it's not mentioned in the block tag definition.

### Other information

According to discussion on Discord, the conversion should include tuff as well.

**Comment by TheRealWormbo** [comment]
@williewillus It looks like the changelog got its addition in the wrong section, and datagen might need to run as well.

**Comment by williewillus** [comment]
Datagen is clean, there's a CI signal for it.
