### ISSUE TITLE
Game crash when using hoe on dirt

### ISSUE THREAD

**Issue by postal291** [Vazkii/Botania#4417]
### Mod Loader

Forge

### Minecraft Version

1.19.2

### Botania version

1.19.2-440-FORGE

### Modloader version

Forge 43.2.14

### The latest.log file

https://pastebin.com/adkVcSnQ

### Issue description

Any botania hoe when used on dirt causes client to crash

### Steps to reproduce

1. Equip any botania hoe.
2. Right click on a dirt block.
3. Crash.

### Other information

Originally discovered this bug while playing FTB Skies.  Upon further testing (Installed a fresh instance with Minecraft, Forge, and Botania only) realized that the problem was only related to botania.

**Comment by anoomolu** [comment]
I can't reproduce this issue with latest Botania + deps - both the Manasteel and Elementium hoes work fine on Forge 43.2.0 (recommended version) and 43.2.14 (the version you have). Might help to send the crash log from your test instance.
