### ISSUE TITLE
Maximum amount of mana generated by Endoflame in 1.19.2

### ISSUE THREAD

**Issue by Dawnwalker666** [Vazkii/Botania#4419]
### Mod Loader

Forge

### Minecraft Version

1.19.2

### Botania version

1.19.2-440

### Modloader version

43.2.11

### The latest.log file

There's no such thing. It's pure math.

### Issue description

When I was writing the Chinese mod wiki, I realized that Endoflame's maximum amount of mana production has been changing with version updates.
In the latest version, 1.19.2-440.The introduction at Lexica Botania is this: `the flower can only burn around four $(item)Block of Coal$(0)s' worth of fuel at once. `
Let's assume that the efficiency is constant.It does in fact remain constant, except that it's not if it's measured in ticks. A coal block is 8,000 burnTime. I fed another fuel that burns much longer than 4 blocks of coal, like Create's Creative Blaze Cake.I found it to have a burnTime of just 16,000, or twice as much as the coal block . That translates to a maximum magic production value of just two Coal Blocks. Not four as stated in the book.
That's kind of interesting. Maybe one of the versions secretly changed it too?

### Steps to reproduce

Step 1. someone asks me this question.
Step 2, I test it inside the game. Come to GitHub to see the code.
Step 3, a controlled test, and it did.
Step 4, submit the issue.

**Comment by Dawnwalker666** [comment]
Well, changelog and Lexica Botania are both fake, both are illusions.
**Changelog** tells me that the maximum amount of mana that can be produced from a single fuel is **one** block of coal.
**Lexica Botania** tells me the maximum amount of mana that can be produced from a single fuel is **four** blocks of coal.
It's interesting isn't it? The test is **two** blocks of coal.

**Comment by anoomolu** [comment]
The source code for the endoflame has a fuel cap of 32000 ticks. Coal blocks have a burn time of 16000 ticks ([source](https://minecraft.fandom.com/wiki/Block_of_Coal)), so the maximum amount of mana produced is equivalent to two coal blocks like your test shows. 

You're right with regards to the lexicon giving incorrect info.

**Comment by Dawnwalker666** [comment]
> The source code for the endoflame has a fuel cap of 32000 ticks. Coal blocks have a burn time of 16000 ticks ([source](https://minecraft.fandom.com/wiki/Block_of_Coal)), so the maximum amount of mana produced is equivalent to two coal blocks like your test shows.
> 
> You're right with regards to the lexicon giving incorrect info.

No, no, no, no. These values should be halved. You see, inside EndoflameBlockEntity.java on lines 73 and 74. This makes the calculated value divide by two. This is also the case in the game, where the coal block burns 8000 ticks and the fuel cap is 16000 ticks.

**Comment by Dawnwalker666** [comment]
And not just in 1.19. I'm afraid it was changed in 1.18 or even before .

**Comment by LuciusV** [comment]
Does that mean that blaze mesh with burn time of 18000 ticks just wastes 2000 ticks of burn time? :(

**Comment by TheRealWormbo** [comment]
According to the code, the current fuel cap is at 32000 game ticks, which is indeed only twice the coal block burn time. Note that the Endoflame burns fuel like a blast furnace or smoker at twice the furnace speed, so its actual maximum burn time will be 16000 game ticks, while a coal block will produce mana only for 8000 game ticks.

Blaze Mesh is *not* capped. It will burn for 12000 ticks, just like in a blast furnace or smoker.

I'm not sure what lead to the fuel cap in the first place, but it seems to nicely line up with typical coal coke block burn times. That change was introduced very early in https://github.com/VazkiiMods/Botania/commit/0a8b48ba841eab07112b2b5ff871d68c318efdc5, but doesn't mention a reason. If the lexicon says otherwise, it's wrong. (And it seems it was wrong for a long time as well already.)

**Comment by Dawnwalker666** [comment]
So... Does it follow the code or the lexicon?

**Comment by TheRealWormbo** [comment]
The code is what dictates the behavior. It can't *not* follow what's programmed.

**Comment by anoomolu** [comment]
https://github.com/VazkiiMods/Botania/commit/5e235fcbfbf0912382798650c08fc344ca81f677 should close this.
