### ISSUE TITLE
Client Crash [1.19.2] Lexica Botania - Reported exception thrown --> Tesselating block in world

### ISSUE THREAD

**Issue by suerion** [Vazkii/Botania#4423]
### Mod Loader

Fabric

### Minecraft Version

MC 1.19.2

### Botania version

Botania 1.19.2-440 Fabric

### Modloader version

Fabric 0.14.21 with Fabric API 0.76.0+1.19.2

### The latest.log file

https://mclo.gs/xwaeRXr

### Issue description

Open Botania Book, and open the better lexica Botania on natural apparatus enchanting with mana, the client crash.

### Steps to reproduce

Start Client,
Connect to Server.
Open Lexica Botania,,
Open page of enchanting with mana.
Client Crash

**Comment by anoomolu** [comment]
I wasn't able to reproduce this with just Botania + deps, Sodium, Indium (mentioned in the crashlog) and Continuity. Does this crash happen in a new world as well? If you're using a modpack on Curseforge/Modrinth, I could test to see if it happens on my end with the same modlist.

**Comment by suerion** [comment]
I will look, if the error is persisten on latest update, come back if yes

**Comment by anoomolu** [comment]
Any updates on if the error is still happening?

**Comment by suerion** [comment]
Hey, i will look on the last updates

**Comment by anoomolu** [comment]
Closing this as it looks to be a duplicate of #4324.
