### ISSUE TITLE
client login to server well be crash

### ISSUE THREAD

**Issue by Mr-Ao-Dragon** [Vazkii/Botania#4429]
### Mod Loader

Forge

### Minecraft Version

1.19.2

### Botania version

1.19.2-440-FORGE

### Modloader version

forge 43.2.21

### The latest.log file

https://gist.github.com/Mr-Ao-Dragon/0d7c16943c964f2004f636c921e870a5

### Issue description

As the title says, the client crashes when trying to join the server.

### Steps to reproduce

1. launch client
2. login to server

### Other information

mod list
![image](https://github.com/VazkiiMods/Botania/assets/67987607/9bf35af3-f2b5-4859-90c3-e1da6fd8a314)

**Comment by williewillus** [comment]
敖律风 ***@***.***> writes:

> ### The latest.log file
>
> https://gist.github.com/Mr-Ao-Dragon/0d7c16943c964f2004f636c921e870a5

The log shows no error.

**Comment by williewillus** [comment]
^, please provide much more detail in another report
