### ISSUE TITLE
[1.16.5]error

### ISSUE THREAD

**Issue by yuankun1** [Vazkii/Botania#4430]
### Mod Loader

Forge

### Minecraft Version

1.16.5

### Botania version

1.16.5-420.3

### Modloader version

forge36.2.9

### Modpack info

no

### The latest.log file

https://pastebin.com/C31Knfmm

### Issue description

Start catserver

### Steps to reproduce

Start catserver

### Other information

no

**Comment by williewillus** [comment]
In the log:

>		at noppes.npcs.ScriptPlayerEventHandler.registerForgeEvents(ScriptPlayerEventHandler.java:317) ~[customnpcs:1.16.5.20220226]
>		at noppes.npcs.CustomNpcs.setup(CustomNpcs.java:241) ~[customnpcs:1.16.5.20220226]

Not a Botania issue.
