### ISSUE TITLE
1.20 Crash with Rubidium

### ISSUE THREAD

**Issue by KLONOA9X6** [Vazkii/Botania#4434]
### Mod Loader

Forge

### Minecraft Version

1.20.1

### Botania version

Botania-1.20.1-441-FORGE-20230805.120703-18

### Modloader version

Forge: 47.1.43

### The latest.log file

https://pastebin.com/2zcd2Uk0

### Issue description

_No Response_

### Steps to reproduce

1. get a flowerbag
2. right click the flowerbag
3. see the crash

**Comment by anoomolu** [comment]
Unable to reproduce this with the latest Botania snapshot and Forge 47.1.47

![image](https://github.com/VazkiiMods/Botania/assets/77850233/aa7750ca-946b-49c2-8bd6-c0e61706774e)

It might be an incompatibility with one or more of your other mods.

**Comment by ZenZenXDz** [comment]
Probably was caused by Rubidium 0.6.5, it also happened to my gameplay. Had to remove Botania.

**Comment by anoomolu** [comment]
I'd suggest using Embeddium, it's designed with mod compat in mind.
