### ISSUE TITLE
Mushrooms in superflat worlds

### ISSUE THREAD

**Issue by traincrisis** [Vazkii/Botania#4436]
### Mod Loader

Forge

### Minecraft Version

1.19.2

### Botania version

1.19.2-440

### Modloader version

Forge 43.2.8

### The latest.log file

https://pastebin.com/

### Issue description

In superflat worlds mushrooms from this mod generate in them, it is annoying!

### Steps to reproduce

Just make the superflat world and explore it you will find many mushrooms

### Other information

Other mods are not required for that

**Comment by anoomolu** [comment]
I've made multiple superflat worlds for testing in the past and have never come across this, on both Forge and Fabric. Are you sure you're not running Botania alongside other mods (that may affect world generation)? Seems like you might have forgotten to paste a latest.log file.

**Comment by anoomolu** [comment]
Unable to reproduce this on latest (or 1.16, 1.18 and 1.19).
