### ISSUE TITLE
Ring of the mantle haste buff not changing mining speed

### ISSUE THREAD

**Issue by MiusR** [Vazkii/Botania#4442]
### Mod Loader

Forge

### Minecraft Version

1.19.2

### Botania version

1.19.2-440

### Modloader version

43.2.8

### The latest.log file

-

### Issue description

When using a Ring of the Mantle, the mining speed is not affected by the haste buff.
While the animation of the hand does seem to move faster it mines at the same speed.
Probably due to Minecraft not handling effects if they are constantly reapplied.

### Steps to reproduce

1. Have a source of mana in your inventory
2. Equip ring of the mantle
3. Try to mine with it

### Other information

Other mods that we have installed and might interfere:
better combat

**Comment by williewillus** [comment]
> ### Other information
>
> Other mods that we have installed and might interfere:
> better combat

Can you try without it?

**Comment by anoomolu** [comment]
Works fine with just Botania + deps on both Forge and Fabric. I tested with an efficiency V diamond pickaxe - with haste 2 (the ring of the mantle buff) it instamines andesite, but without, it does not.

**Comment by MiusR** [comment]
I tried it again today and it works fine.... must have been my computer having issues with breaking blocks so fast. Sorry for the trouble.
