### ISSUE TITLE
Pick pixie handler attribute crash fix to 1.16

### ISSUE THREAD

**Issue by Natedogwoooof** [Vazkii/Botania#4445]
### Mod Loader

Forge

### Minecraft Version

1.16.5

### Botania version

1.16.5-420.3

### Modloader version

3.36.29

### The latest.log file

https://pastebin.com/jxEsT0sH

### Issue description

i fought a guy in his house from blue skys or aminotar or any mob and the game crashes 

### Steps to reproduce

download mods i have
hurt any hostile\
game crashes

**Comment by williewillus** [comment]
Duplicate of #4077. The fix is in 1.18 50f71bae60f5b3b13084edaf4f940c9ad934724d

If I have time, I'll pick it back to 1.16, but don't count on it happening.

**Comment by anoomolu** [comment]
@Natedogwoooof try adding [AttributeFix](https://www.curseforge.com/minecraft/mc-mods/attributefix) to your pack, might solve your problem and save time backporting this fix

**Comment by Natedogwoooof** [comment]
Ok

> @Natedogwoooof try adding [AttributeFix](https://www.curseforge.com/minecraft/mc-mods/attributefix) to your pack, might solve your problem and save time backporting this fix

Ok

**Comment by Natedogwoooof** [comment]
> @Natedogwoooof try adding [AttributeFix](https://www.curseforge.com/minecraft/mc-mods/attributefix) to your pack, might solve your problem and save time backporting this fix

I checked and I areadey have it

**Comment by zoroBOZO** [comment]
> @Natedogwoooof try adding [AttributeFix](https://www.curseforge.com/minecraft/mc-mods/attributefix) to your pack, might solve your problem and save time backporting this fix

it didn't work

**Comment by TheRealWormbo** [comment]
As mentioned by doxne in https://github.com/VazkiiMods/Botania/issues/4493#issuecomment-1828744250, this seems to be caused by the Pufferfish's Skills mod. Since this is fixed in 1.18+ and we no longer support 1.16, I'm going to close this issue.
