### ISSUE TITLE
Black Hole Talismans put a "crash server" button on your keyboard when you put them in a crafting grid.

### ISSUE THREAD

**Issue by Buggy123** [Vazkii/Botania#4450]
### Mod Loader

Fabric

### Minecraft Version

1.19.2

### Botania version

Botania-1.19.2-440-FABRIC

### Modloader version

quilt loader 0.19.0, qfapi-4.0.0-beta.30_qsl-3.0.0-beta.29_fapi-0.76.0_mc-1.19.2

### The latest.log file

https://mclo.gs/Zp3CUJV

### Issue description

You extract items from a black hole talisman by crafting.

If you shift click the output of a crafting grid, it repeatedly crafts until it no longer can, either because the recipe ingredients are depleted, or because your inventory has no room for the products.

If you ctrl+q it does the same thing, except it tosses the products on the ground. Therefore, because it will not fill up your inventory, the recipe repeatedly crafts until there is no longer a valid recipe in the crafting grid.

This means that if you ctrl+q while emptying a black hole talisman, it repeats until it is empty. Tossing a item entity on the ground for every stack.

A black hole talisman can hold 9,223,372,036,854,775,807 items. Ctrl+q can create quadrillions of item entities. This is bad.

### Steps to reproduce

1: Put a lot of stuff in a black hole talisman.

2: Put in crafting grid.

3: Press Ctrl+q while hovering over the output slot.

**Comment by williewillus** [comment]
Works as intended. Lots of other mods provide items that hold large quantities of other items, and all of them are susceptible to this same "crash button".

It's up to servers to guard against this spamming by adding rate limits, or just trusting their players not to be stupid.
