### ISSUE TITLE
Every time the saves is loading, it prompts "Worlds using Experimental settings are not supported"

### ISSUE THREAD

**Issue by CoreanXka** [Vazkii/Botania#4464]
### Mod Loader

Fabric

### Minecraft Version

1.19.2

### Botania version

1.19.2-440

### Modloader version

Loader 1.14.23 + API 0.76.1

### The latest.log file

https://pastebin.com/xSQEcWja

### Issue description

When  loading created saves, always 

Every time the saves is loading, it prompts "Worlds using Experimental settings are not supported"

Like this.
![image](https://github.com/VazkiiMods/Botania/assets/68276806/06357c94-40f6-4beb-9e5b-a8f85202d352)

**Comment by williewillus** [comment]
This is just vanilla being annoying since we use json worldgen
files. Either ignore it, or install a mod like
https://www.curseforge.com/minecraft/mc-mods/fabric-disable-custom-worlds-advice
to silence the warnings.
