### ISSUE TITLE
copera index crashing

### ISSUE THREAD

**Issue by hi4444** [Vazkii/Botania#4466]
### Mod Loader

Forge

### Minecraft Version

1.19.2

### Botania version

1.19.2-440-jar

### Modloader version

forge 43.30

### Modpack info

https://www.mediafire.com/file/820t3m3ow66rlml/DerpMania-hehe.zip/file

### The latest.log file

https://gist.github.com/hi4444/b7c2a201432356c8d4db7d608288ddd8

### Issue description

When playing the modpack im with placing the corpera index right with a copera master spark
and placing anthor 1 near the index crashs 

### Steps to reproduce

place copera index 
place a copera master spark on it
then anthor of same spark near it

### Other information

none

**Comment by TheRealWormbo** [comment]
I can place two corporea indexes, each with a master spark on top (which you should definitely _not_ do), just fine and even attempt to send a request.

Your log file doesn't list the actual crash, but shows a whole lot of errors in a bunch of mods. Can you maybe try to produce a clean test case for this issue?

**Comment by anoomolu** [comment]
I can't reproduce this either.
