### ISSUE TITLE
Botania banner additions cannot be shift-clicked into Loom

### ISSUE THREAD

**Issue by anoomolu** [Vazkii/Botania#4472]
### Mod Loader

Both Fabric and Forge (I confirm that I have tested both loaders and will specify both loader versions below)

### Minecraft Version

1.19.2

### Botania version

1.19.2-440

### Modloader version

Forge: 43.2 / Fabric Loader 0.14.21 and Fabric API 0.76.0

### The latest.log file

n/a

### Issue description

As stated in the title, I'm unable to shift-click banner "patterns" added by Botania into the Loom. In Vanilla, all components involved in banner crafting (the banner, dye and pattern) are able to be shift-clicked.

Tested with the Tiny Potato, Spark Augments and Dreamwood Twig.

**Comment by TheRealWormbo** [comment]
Is there any good reason to hack the pattern feature into non-pattern items in the first place?
I'd suggest crafting actual banner patterns from these items instead. Presumably using the items directly was a remnant from when vanilla used items to apply patterns to banners. Those pattern items could have Vanilla Tweaks style icons to make then visually identifiable without having to look at their tooltip.

**Comment by anoomolu** [comment]
I think banner patterns for the Tiny Potato and Lexicon would be sufficent, given how there's not thaat many for vanilla anyways.
Something like Friend and Tome Banner Pattern respectively.
