### ISSUE TITLE
Special arrows fired from Crystal Bow can't be picked up, even though they are consumed

### ISSUE THREAD

**Issue by Partonetrain** [Vazkii/Botania#4476]
### Mod Loader

Both Fabric and Forge (I confirm that I have tested both loaders and will specify both loader versions below)

### Minecraft Version

1.20.1

### Botania version

1.20.1 SNAPSHOT

### Modloader version

Fabric 0.14.24 / Forge 27.2.4

### The latest.log file

N/A

### Issue description

Relevant code:
https://github.com/VazkiiMods/Botania/blob/1.20.x/Xplat/src/main/java/vazkii/botania/common/item/equipment/tool/bow/CrystalBowItem.java#L103

I assume vanilla code is responsible for the arrow ItemStack being reduced by 1

### Steps to reproduce

1. Get Crystal Bow and special arrows (such as Spectral Arrow), as well as a Mana Tablet w/ mana
2. Ensure you are in Survival Mode
3. Fire the Crystal Bow into a block
4. See that the special arrow stack has decreased
5. Try to pick up the special arrow entity can't be picked up in Survival Mode

### Other information

This could be fixed by either:
1) not reducing the ItemStack (probably OP)
2) allowing the resulting arrow to be picked up

**Comment by TheRealWormbo** [comment]
It used to be that special arrows were not consumed this way. Firing Quark's exploding arrows with a crystal bow was definitely very OP. As such, it's probably better for the balance to consume special arrows but allow them to be picked up again.
