### ISSUE TITLE
 The ender hand, when clicking on a player on the server, allows you to climb into his ender chest

### ISSUE THREAD

**Issue by BloodInAs** [Vazkii/Botania#4477]
### Mod Loader

Forge

### Minecraft Version

1.20.1

### Botania version

Botania-1.20.1-441-FORGE-SNAPSHOT

### Modloader version

Forge Version 47.2.1

### Modpack info

-

### The latest.log file

-

### Issue description

The ender hand, when clicking on a player on the server, allows you to climb into his ender chest
`botania:ender_hand`

**Comment by anoomolu** [comment]
From the lexicon: 

> Using the hand on another player will use substantially more Mana, but will open their inventory instead.

There's a config option that allows you to disable this functionality.
