### ISSUE TITLE
Suggestion: Effect descriptions

### ISSUE THREAD

**Issue by Partonetrain** [Vazkii/Botania#4479]
### Mod Loader

Both Fabric and Forge (I confirm that I have tested both loaders and will specify both loader versions below)

### Minecraft Version

1.20.1

### Botania version

1.20.1-441-SNAPSHOT

### Modloader version

N/A

### The latest.log file

N/A

### Issue description

Adding the relevant language keys in the following format would allow mods like [Just Enough Effect Descriptions](https://www.curseforge.com/minecraft/mc-mods/just-enough-effect-descriptions-jeed) and [EMIffect](https://modrinth.com/mod/emiffect) to describe Botania's potion effects. To me this is preferable to checking what the effects do in the Lexica.

`"effect.botania.[effect_name].description": "Lorem Ipsum"`

### Steps to reproduce

N/A

**Comment by anoomolu** [comment]
Do these sound reasonable?

  "effect.botania.allure.description": "Doubles fishing speed.",
  "effect.botania.bloodthirst.description": "Allows hostile mobs to spawn in a 64-block radius, regardless of spawning conditions. Doesn't work if under the effect of Emptiness.",
  "effect.botania.clear.description": "Clears all status effects, positive or negative.",
  "effect.botania.emptiness.description": "Prevents natural mob spawning in a 128-block radius.",
  "effect.botania.feather_feet.description": "Grants immunity to fall damage.",
  "effect.botania.soul_cross.description": "Restores health upon killing mobs.",

**Comment by williewillus** [comment]
Sure

**Comment by williewillus** [comment]
ccd6bfeaa1f589156f55fe903fc77ed898376d83
