### ISSUE TITLE
Terra blade able to shoot beam under spectator mode

### ISSUE THREAD

**Issue by misaka10987** [Vazkii/Botania#4480]
### Mod Loader

Forge

### Minecraft Version

1.16.5

### Botania version

1.16.5-420.3

### Modloader version

Forge 36.2.39

### The latest.log file

https://gist.github.com/misaka10987/f85459072e065093aac094cb0d160748

### Issue description

Terra blade able to shut beam in spectator mode.

### Steps to reproduce

1. Hold a terra blade.
2. Switch to spectator mode.
3. Left click.

**Comment by anoomolu** [comment]
Can confirm on the Fabric 1.20.1 beta.
