### ISSUE TITLE
Corporea Crystal Cube causing ticking block entity crash

### ISSUE THREAD

**Issue by MissCapy** [Vazkii/Botania#4486]
### Mod Loader

Fabric

### Minecraft Version

1.20.1

### Botania version

1.20.1-441-fabric

### Modloader version

Fabric Loader 0.14.24 + API 0.90.7

### The latest.log file

https://pastebin.com/UuBZSUBV

### Issue description

The title is pretty much it. attempting to measure the amount of any item in a corporea system with a crystal cube causes the game to crash. 

### Steps to reproduce

Place down a master corporea spark on a corporea brick
put a regular corporea spark on a chest
put any item in the chest
place down a corporea crystal cube
set the corporea crystal cube to read whatever item you put in the chest
client should crash basically immediately due to a ticking block entity

### Other information

I first ran into this when I ported my 1.19 world to 1.20.1. several troubleshooting steps later, I created a fresh install, with just Botania, Patchouli, and Trinkets. I made a new creative world and attempted the steps above, which still produced the crash described above. the linked log file is from said creative world. the fully modded client as well as the fresh install ran completely fine right up until I right clicked the corporea crystal cube to tell it what item to read.

**Comment by anoomolu** [comment]
Can confirm. https://mclo.gs/pxZfaQg
I can't actually get into my world without crashing once it's loaded in :c

**Comment by TheRealWormbo** [comment]
Might have accidentally been introduced with the changes in 66680dd33c5cf3f719359e4c188d5b0d28cdb91c.

**Comment by williewillus** [comment]
ugh, this transaction api sucks.

**Comment by TheRealWormbo** [comment]
Upon further inspection, it's probably related to https://github.com/VazkiiMods/Botania/blob/7a5f36a55ad1257754cc4806f4e1bebfca7c1a3b/Fabric/src/main/java/vazkii/botania/fabric/integration/corporea/FabricTransferCorporeaNode.java#L66 not passing the outer transaction to `simulateExtract`.
