### ISSUE TITLE
Datapack data not modifying anything from the mod

### ISSUE THREAD

**Issue by NeuTraLZero** [Vazkii/Botania#4487]
### Mod Loader

Forge

### Minecraft Version

1.20.1

### Botania version

1.20.1-441

### Modloader version

Forge: 47.2.6

### The latest.log file

-

### Issue description

For example, when I try to edit the recipes for absorption brew and terrasteel ingot through a datapack, the in-game recipe simply don't change

**Comment by anoomolu** [comment]
I'm able to edit recipes just fine, check your file path is correct.
so datapackname/data/botania/recipes/terra_plate (or brew)

![image](https://github.com/VazkiiMods/Botania/assets/77850233/cbca77cb-2b50-4bd1-91a7-f375c45fe121)
![image](https://github.com/VazkiiMods/Botania/assets/77850233/1b7fb0e4-10a0-4cde-8d7a-a4352da20426)

**Comment by NeuTraLZero** [comment]
I found that it might be a compatibility issue with Paxi

Loading the datapack through Paxi didn't change the recipe but loading manually through the world folder works

**Comment by NeuTraLZero** [comment]
update again, this only happens when I add the data to my big tweaking datapack, for some reason when the pack is seperated the recipes are working fine

**Comment by anoomolu** [comment]
Not sure it's a Paxi issue either, worked fine when I shifted my datapacks and resource packs over to check. Are there any errors in the log when you try loading your modified Botania recipes?

**Comment by NeuTraLZero** [comment]
No, there wasn't really any error either, it's weird. You can close this issue for now if you want

**Comment by NolanHewitt** [comment]
I've been unable to change stuff with datapacks as well, using openloader. Had to change the recipes in the mod itself to get stuff to change.

**Comment by anoomolu** [comment]
> I've been unable to change stuff with datapacks as well, using openloader. Had to change the recipes in the mod itself to get stuff to change.

What recipe are you trying to change? Might be able to help
