### ISSUE TITLE
placing a floating torch in any direction that isn't south will not cause it to power existing redstone components

### ISSUE THREAD

**Issue by Elitemagikarp** [Vazkii/Botania#4489]
### Mod Loader

Fabric

### Minecraft Version

1.20.1

### Botania version

1.20.1-441

### Modloader version

Fabric: Loader 0.14.24 API 0.91.0

### The latest.log file

N/A

### Issue description

title

this isn't that important because the floating torch just toggling back to that side will power the component and you can just place the stuff after the torch

### Steps to reproduce

1. place a redstone component
2. place a floating torch facing it that isn't facing south
3. the redstone component will not be powered

**Comment by TheRealWormbo** [comment]
This seems to be restricted to Fabric, it works fine on Forge.

Test case:

1. Place four redstone lamps around a free block space.
2. Place an animated torch into the center, pointing anywhere but south.
    Forge: The lamp in the direction of the torch lights up.
    Fabric: The lamp to the south lights up, regardless of torch direction.

Follow-up options for Fabric:

- Place another torch on top of the existing one, pointing in the same direction. The originally expected lamp lights up, as it apparently received a redstone update (it is not powered by the new torch, just updated.) The lamp to the south stays lit.
- Place the second torch facing south. The lamp to the south turns off, as it now realizes it didn't actually get powered. (No update to the actually powered lamp in this scenario.)
