### ISSUE TITLE
el monoculo

### ISSUE THREAD

**Issue by Ernee122** [Vazkii/Botania#4504]
### Mod Loader

Forge

### Minecraft Version

1.20.1

### Botania version

441

### Modloader version

forge

### The latest.log file

aa

### Issue description

el monóculo no se puede equipar

**Comment by anoomolu** [comment]
In your inventory, there should be a small circle near your character's head. Click that, and there should be some new slots where you can shift-click the monocle into.

**Comment by Ernee122** [comment]
I make it but it is not equipped, check that part
I'm on 1.20.1

**Comment by anoomolu** [comment]
Google translating in case it is easier for you:

Puedo equiparme el monóculo sin problema, con Botania, Curios y Patchouli. ¿Tienes otros mods instalados, u otras Curios en tu ranura "Charm"? Un video del problema o los pasos para reproducirlo sería útil.

**Comment by Ernee122** [comment]
probé desactivando mods y me genera conflicto con Create Chromatic Return mod cuando tengo el mod activado no me puedo equipar el monóculo pueden revisar eso, gracias por su atención 
edit: edite un poco el mod causante y resolví el problema (solo elimine una parte y bumb resuelto)
