### ISSUE TITLE
Gaia Guardian head doesn't render correctly with Entity Texture Features

### ISSUE THREAD

**Issue by Partonetrain** [Vazkii/Botania#4505]
### Mod Loader

Fabric

### Minecraft Version

1.20.1

### Botania version

1.20.1-441-FABRIC

### Modloader version

Fabric 0.15.0

### The latest.log file

N/A

### Issue description

Gaia Head renders as Steve's head when [Entity Texture Features](https://modrinth.com/mod/entitytexturefeatures) is installed.

![image](https://github.com/VazkiiMods/Botania/assets/19861808/78e36147-9d3d-4f9b-af39-b36a7c5e12fc)

This might be an Entity Texture Features issue, not sure

### Steps to reproduce

1. Install Botania
2. Install Entity Texture Features
3. Place Gaia Guardian Head and observe

### Other information

Forge may have the same issue if Synatra Connector is installed, untested.

**Comment by TheRealWormbo** [comment]
I'm not quite sure what Botania can do to fix this. Did you report it to ETF as well? (If not, it might be a good idea, just to track it on both sides.)

**Comment by TheRealWormbo** [comment]
I can't seem to reproduce this with just the latest versions of ETF and Botania+dependencies on either Fabric or Forge (there is actually a Forge version of all involved mods, no need for the connector), using the default ETF configuration.

@Partonetrain: Can you please check if you have any non-default configuration going that might be causing this?

**Comment by Partonetrain** [comment]
I have not been able to reproduce this issue with the latest version of ETF.
