### ISSUE TITLE
Ring of Far Reach Visual Glitch

### ISSUE THREAD

**Issue by jawdylawdy** [Vazkii/Botania#451]
This is a two-part report.

1) Occasionally (only once that I saw, but once is enough to merit investigation in my opinion), the Ring of Far Reach extends client-side interaction far...far beyond what it ought to be. As in from a tower 40 blocks off of the ground, I can break grass, punch trees, whatever else you can imagine. However, the interactions aren't actually valid, and result in "invisible blocks" that haven't actually been broken.

2) Consistently (every time I've used the ring), the Ring of Far Reach appears to extend one block outside of its actual range, resulting in the same invisible blocks when those blocks are broken.

This is on the 1.0.3 version of the DireWolf20 pack, FastCraft installed, nothing else.

**Comment by akvgergo** [comment]
The ring seems to extend the reach by 3 blocks every time I jump between dimensions.

same, DW20 1.0.3 (Botania 146)

**Comment by Vazkii** [comment]
Does this happen in LAN, SMP or SSP?

**Comment by Kubuxu** [comment]
It was happening for me on SMP. I don't know about other types

**Comment by Vazkii** [comment]
I'm not going to fuss much about it if it doesn't happen on SSP, since I know baubles is super fiddly in the others :|

**Comment by akvgergo** [comment]
I'm only playing SSP and i get this every time I jump between dimensions so :P

**Comment by Vazkii** [comment]
Interesting, I'll have a look at it sometime then.
