### ISSUE TITLE
Minecraft 1.19.2 Game Launch Crash

### ISSUE THREAD

**Issue by IsmacraftGG** [Vazkii/Botania#4511]
### Mod Loader

Forge

### Minecraft Version

1.19.2

### Botania version

1.19.2-440-FORGE

### Modloader version

Forge: 43.3.5

### The latest.log file

<script src="https://gist.github.com/IsmacraftGG/340fdfb02902c3b4de334899b28dade5.js"></script>

### Issue description

Hello, this is my first time reporting a bug/crash from a mod so i hope i did it right, anyway, about the issue:
I use prism Launcher (Portable 8.0). when i try to launch the game, it loads the mojang loading bar as usual, but when it doesnt get past that and then it crashes. prism launcher gave me 3 suspect mods for the crash and i tried every one of these 3 and botania is the one causing the crash. by disabling botania the game launches normally. 

### Steps to reproduce

1. use prism launcher 
2. use the specified forge and botania version
3. click the launch button or click on a instance with the botania mod to launch the game.
4. CRASH

### Other information

Mods:
  [✔] [1.19.2 ONLY PATCH]_Many_More_Ores_2.0_Full_Release
  [✔] [1.19.2] SecurityCraft v1.9.6.1
  [✔] [1.19.2-forge]-Epic-Knights-8.11
  [✔] 1.19.2netherskeletons4.9
  [✔] aas-1.19_1.3.1
  [✔] ad_astra-forge-1.19.2-1.12.7
  [✔] AdditionalBanners-Forge-1.19.2-10.1.7
  [✔] additional-guns-0.8.2-1.19.2
  [✔] AdLods-1.19.2-7.0.8.1-build.0865
  [✔] advancednetherite-1.14.7-1.19.2
  [✔] AdvancementPlaques-1.19.2-1.4.7
  [✔] aether-1.19.2-1.0.0-beta.2-forge
  [✔] AgeOfWeapons-Reforged-1.19.2-(v.0.15.1)
  [✔] alchemistry-1.19.2-2.3.2
  [✔] alchemylib-1.19.2-1.0.21
  [✔] alexsmobs-1.21.1
  [✔] allay-forge-1.19.1-4.1.1
  [✔] allthemodium-2.1.7-1.19.2-43.1.1
  [✔] alternate-current-mc1.19-1.7.0
  [✔] AmbientSounds_FORGE_v5.2.13_mc1.19.2
  [✔] Amplified_Nether_1.19.3_v1.2.1
  [✔] AngelRing2-1.19.2-2.1.8
  [✔] another_furniture-forge-1.19.2-2.1.4
  [✔] Apotheosis-1.19.2-6.4.1
  [✔] appleskin-forge-mc1.19-2.4.2
  [✔] appliedenergistics2-forge-12.9.8
  [✔] Aquaculture-1.19.2-2.4.8
  [✔] aquamirae-6.API15
  [✔] aquatictorches-1.19-1.1.0
  [✔] architectury-6.5.85-forge
  [✔] armorplus-1.19.2-19.1.0-beta
  [✔] ars_nouveau-1.19.2-3.21.5
  [✔] ars_ocultas-1.19.2-0.1.1-all
  [✔] artifacts-1.19.2-5.0.4
  [✔] Astral_1.5
  [✔] atmospheric-1.19.2-5.0.0
  [✔] AttributeFix-Forge-1.19.2-17.2.7
  [✔] AutoRegLib-1.8.2-55
  [✔] autumnity-1.19.2-4.0.1
  [✔] awesomedungeonend-forge-1.19.2-3.1.1
  [✔] awesomedungeon-forge-1.19.2-3.2.0
  [✔] awesomedungeonnether-forge-1.19.2-3.1.1
  [✔] awesomedungeonocean-forge-1.19.2-3.3.0
  [✔] azurelib-forge-1.19.2-1.0.38
  [✔] Baguslib-1.19.2-3.5.1
  [✔] balm-forge-1.19.2-4.6.0
  [✔] berry_good-1.19.2-6.1.0
  [✔] Better_Katanas_1.1.3-1.19.2
  [✔] BetterAdvancements-1.19.2-0.3.0.148
  [✔] betteranimalsplus-1.19.2-11.0.10-forge
  [✔] bettercombat-forge-1.7.1+1.19
  [✔] betterfoliage-4.0.6
  [✔] betterfpsdist-1.19.2-4.0
  [✔] BetterThirdPerson-Forge-1.19-1.9.0
  [✔] BetterTridents-v4.0.2-1.19.2-Forge
  [✔] Big Swords R-1.19.2-1.4.0
  [✔] biomancy-forge-1.19.2-2.2.0.0
  [✔] biomemakeover-FORGE-1.19.2-1.6.4
  [✔] BiomesOPlenty-1.19.2-17.1.2.544
  [✔] Blades Plus 1.0.0 - 1.19.2
  [✔] blue_skies-1.19.2-1.3.20
  [✔] blueprint-1.19.2-6.2.0
  [✔] BOMD-Forge-1.19.2-1.0.4
  [✔] Bookshelf-Forge-1.19.2-16.3.20
  [✔] Botania-1.19.2-440-FORGE
  [✔] BotanyPots-Forge-1.19.2-9.0.41
  [✔] botarium-forge-1.19.2-1.8.2
  [✔] brutalbosses-1.19.2-6.3
  [✔] bucolicorigins-3.6.6[FORGE]
  [✔] Builders_Dimension_0.0.7_1.19.2
  [✔] buzzier_bees-1.19.2-5.0.1
  [✔] bygonecreatures-2.2-1.19.2
  [✔] bygonenether-1.3.2-1.19.2
  [✔] caelus-forge-1.19.2-3.0.0.6
  [✔] camera-1.19.2-1.0.6
  [✔] canary-mc1.19.2-0.2.8
  [✔] castle_in_the_sky-1.19.2-0.5.2
  [✔] Cave Dweller Reimagined
  [✔] cfm-7.0.0-pre35-1.19.2
  [✔] cgm-forge-1.19.2-1.3.7
  [✔] charmofundying-forge-6.2.1+1.19.2
  [✔] chemlib-1.19.2-2.0.18
  [✔] chipped-forge-1.19.2-2.1.5
  [✔] chisels-and-bits-forge-1.3.142
  [✔] citadel-2.1.4-1.19
  [✔] cloth-config-8.3.103-forge
  [✔] Clumps-forge-1.19.2-9.0.0+14
  [✔] CNB-1.19-1.5.4
  [✔] coalexplosion-forge-1.19.2-1.6.2
  [✔] CodeChickenLib-1.19.2-4.3.1.481-universal
  [✔] cofh_core-1.19.2-10.3.1.48
  [✔] collective-1.19.2-7.13
  [✔] collectorsreap-1.19-1.2.4
  [✔] comforts-forge-6.0.6+1.19.2
  [✔] Compat-O-Plenty-1.19.2-2.0.1
  [✔] Compressium-2.1.1-build.8+mc1.19
  [✔] configured-2.1.1-1.19.2
  [✔] connectedglass-1.1.9-forge-mc1.19
  [✔] constructionwand-1.19.2-2.10
  [✔] cookingforblockheads-forge-1.19.2-13.3.4
  [✔] coppergolem-forge-1.19-41.0.100-2.0.1
  [✔] copperoverhaul-MC1.19.2-22.10.11
  [✔] coralreef-forge-1.19-1.0.2
  [✔] CorgiLib-forge-1.19.2-1.0.0.34
  [✔] coroutil-1.19.2-1.2.37
  [✔] CosmeticArmorReworked-1.19.2-v1a
  [✔] craftingtweaks-forge-1.19.2-15.1.9
  [✔] create_enchantment_industry-1.19.2-for-create-0.5.1.f-1.2.7.d
  [✔] create-1.19.2-0.5.1.f
  [✔] createaddition-1.19.2-1.2.1
  [✔] create-stuff-additions1.19.2_v2.0.4a
  [✔] CreativeCore_FORGE_v2.9.4_mc1.19.2
  [✔] creeperoverhaul-2.0.9-forge
  [✔] crittersandcompanions-1.19.2-2.1.0
  [✔] Croptopia-1.19.2-FORGE-2.2.2
  [✔] CTM-1.19.2-1.1.6+8
  [✔] ctov-3.2.6c
  [✔] Cucumber-1.19.2-6.0.10
  [✔] CullLessLeaves-Reforged-1.0.5
  [✔] cupboard-1.19.2-2.1
  [✔] curios-forge-1.19.2-5.1.4.3
  [✔] Curses' Naturals 1.0.0 - 1.19.2
  [✔] Cyan Warrior Swords Mod 3.4.1 (1.19.2)
  [✔] Cyclic-1.19.2-1.8.2
  [✔] CyclopsCore-1.19.2-1.18.11
  [✔] DarkerDepths-1.19.2-1.0.0
  [✔] DarkPaintings-Forge-1.19.2-13.1.5
  [✔] DarkUtilities-Forge-1.19.2-13.1.9
  [✔] davespotioneering-1.19.2-2
  [✔] DecorationDelightRefurbished-1.19.2
  [✔] Decorative Blocks-forge-1.19.2-3.0.0
  [✔] deeperdarker-forge-1.19.2-1.2.2
  [✔] Desolation 1.1.8 1.19.2
  [✔] dimdungeons-179-forge-1.19.0
  [✔] Dimensional-Threading-Reforged-1.19.2-1.2.8
  [✔] Divine Weaponry v1.4 1.19.2
  [✔] DoggyTalents-1.19.2-2.6.10
  [✔] domum_ornamentum-1.19-1.0.146-BETA-universal
  [✔] dragonfight-1.19.2-4.1
  [✔] dragonmounts-1.19.2-1.1.4a
  [✔] dummmmmmy-1.19.2-1.7.1
  [✔] DungeonCrawl-1.19-2.3.12
  [✔] dungeons_enhanced-1.19.2-4.1
  [✔] dungeons_gear-1.19.2-5.0.5-beta
  [✔] dungeons_libraries-1.19.2-3.0.10-beta
  [✔] dungeons_mobs-1.19.2-4.0.8-beta
  [✔] dungeons_plus-1.19.2-1.3.1
  [✔] dungeons-and-taverns-2.0.2 forge
  [✔] DungeonsArise-1.19.2-2.1.56-beta
  [✔] dungeonsweaponry-1.11.0-1.19.2
  [✔] durabilitytooltip-1.1.5-forge-mc1.19
  [✔] dynamiclightsreforged-1.19.2_v1.4.0
  [✔] DynamicTrees-1.19.2-1.1.0-BETA10
  [✔] earthmobsmod-1.19.2-9.1.0
  [✔] EasyMagic-v4.3.3-1.19.2-Forge
  [✔] ecologics-forge-1.19.2-2.1.11
  [✔] EDParaglidersCompat-Forge-1.19.2-1.0.1
  [✔] ElementalSwords-1.19.2-2.6.9-[FORGE]
  [✔] elenaidodge2-1.0.2
  [✔] EnchantingInfuser-v4.2.2-1.19.2-Forge
  [✔] EnchantmentDescriptions-Forge-1.19.2-13.0.16
  [✔] enchantwithmob-1.19.2-11.4.0
  [✔] endercrop-1.19.2-1.7.0-beta
  [✔] endermanoverhaul-forge-1.19.2-0.0.1
  [✔] endersdelight-1.19-1.2.1
  [✔] EnderStorage-1.19.2-2.10.1.181-universal
  [✔] endrem_forge-5.2.1-R-1.19.X
  [✔] End's Phantasm - BETAv1.2.10.5 - 1.19.2
  [✔] EnhancedVisuals_FORGE_v1.5.9_mc1.19.2
  [✔] ensorcellation-1.19.2-4.3.1.20
  [✔] Entity_Collision_FPS_Fix-forge-1.19-2.0.0.0
  [✔] entityculling-forge-1.6.1-mc1.19.2
  [✔] environmental-1.19.2-3.0.0
  [✔] epicsamurai-0.0.17-1.19.2-forge
  [✔] EvilCraft-1.19.2-1.2.30
  [✔] explorify-forge-1.19-1.3.0
  [✔] extragolems-19.2.6
  [✔] fairylights-6.0.0-1.19.2
  [✔] Fallingleaves-1.19.1-2.0.0-alpha+20221129-2000
  [✔] fallingtrees-0.9-beta-forge-mc1.19.2
  [✔] FarmersDelight-1.19.2-1.2.3
  [✔] FastFurnace-1.19.2-7.0.0
  [✔] FastLeafDecay-30
  [✔] Fastload-Reforged-mc1.19.2-3.4.0
  [✔] FastSuite-1.19.2-4.1.1
  [✔] FastWorkbench-1.19.2-7.1.4
  [✔] feathers-1.1.2
  [✔] fennecfox-forge-1.19-1.0.0
  [✔] ferritecore-5.0.3-forge
  [✔] FixMySpawnR-forge-1.19.2-1.1.2
  [✔] ForgeEndertech-1.19.2-10.0.6.1-build.0897
  [✔] FramedBlocks-6.8.6
  [✔] framework-forge-1.19.2-0.6.16
  [✔] FullTurtleArmor-1.2-FORGE-MC1.19
  [✔] fusion-1.1.0b-forge-mc1.19.2
  [✔] gardens-of-the-dead-forge-2.0.1
  [✔] geckolib-forge-1.19-3.1.40
  [✔] geophilic-1.19-2.0.0c
  [✔] glare-forge-1.19-1.0.1
  [✔] glassential-forge-1.19-1.2.4
  [✔] gnumus_settlement_[Forge]1.19.2_v1.7
  [✔] Gobber2-Forge-1.19.2-2.7.28
  [✔] goblins-0.5
  [✔] goblintraders-1.8.0-1.19.2
  [✔] goodall-1.2.0-forge
  [✔] gourmet-forge-1.0.0
  [✔] gpumemleakfix-1.19.2-1.6
  [✔] grappling_hook_mod-1.19.2-1.19.2-v13
  [✔] Healing+Bed+1.19.2
  [✔] healingcampfire-1.19.2-5.2
  [✔] helpfulfaeries-1.0.0-1.19.2
  [✔] helpfulwizards-1.0.0-forge
  [✔] Highlighter-1.19.1-1.1.4
  [✔] hmag-forge-mc1.19.2-6.2.10
  [✔] HopoBetterMineshaft-[1.19-1.19.3]-1.1.6
  [✔] HopoBetterRuinedPortals-[1.19-1.19.3]-1.3.3
  [✔] HopoBetterUnderwaterRuins-[1.19-1.19.3]-1.1.1
  [✔] horsecombatcontrols-1.19.2-1.0.1
  [✔] HyperRemaster_1.19.2_modversion_1.85
  [✔] ibarnoriginsaddon-1.1.3-forge-1.19
  [✔] Iceberg-1.19.2-forge-1.1.4
  [✔] iceologer-forge-1.19-41.0.100-1.0.1
  [✔] idas_forge-1.7.6+1.19.2
  [✔] ImmediatelyFast-1.2.7+1.19.2
  [✔] immersive_armors-1.5.6+1.19.2-forge
  [✔] ImmersiveEngineering-1.19.2-9.2.3-167
  [✔] ImmersivePetroleum-1.19.2-4.2.0-28
  [✔] Immunity Enchantments 1.0.0 - 1.19.2
  [✔] Incendium_1.19.3_v5.1.6
  [✔] infernal-expansion-1.19.2-2.5.3
  [✔] infernalmobs-1.19.2.4
  [✔] integrated_api_forge-1.2.7+1.19.2
  [✔] ironfurnaces-1.19.2-3.6.5
  [✔] irons_spellbooks-1.19.2-2.1.1
  [✔] itemcollectors-1.1.8-forge-mc1.19
  [✔] Jade-1.19.1-forge-8.9.2
  [✔] JadeAddons-1.19.2-forge-3.6.0
  [✔] javd-forge-4.0.1-build.2+mc1.19.2
  [✔] jei-1.19.2-forge-11.6.0.1018
  [✔] jmi-forge-1.19.2-0.13-44
  [✔] journeymap-1.19.2-5.9.7-forge
  [✔] JustEnoughResources-1.19.2-1.2.3.243
  [✔] kobolds-0.4
  [✔] Kobolds-2.6.8
  [✔] kotlinforforge-3.12.0-all
  [✔] KryptonReforged-0.2.1
  [✔] L_Enders_Cataclysm-1.38 -1.19.2
  [✔] lava_monster-1.19.1-1.0.11
  [✔] lazydfu-1.19-1.0.2
  [✔] LegendaryTooltips-1.19.2-forge-1.4.0
  [✔] leosbosses-1.1
  [✔] leosillagers-1.1.2
  [✔] libraryferret-forge-1.19.2-4.0.0
  [✔] LibX-1.19.2-4.2.8
  [✔] Life Steal Enchant 1.0.0 - 1.19.2
  [✔] lightspeed-1.19.2-1.0.5
  [✔] luckytntlib-1.19.2-43.2.11.2
  [✔] luckytntmod-1.19.2-1.1
  [✔] macawsbridgesbop-1.19.2-1.3
  [✔] macawsbridgesbyg-1.19.2-1.3
  [✔] macawsroofsbop-1.19.2-1.4
  [✔] macawsroofsbyg-1.19.2-1.3
  [✔] maenchants-1.19.2-6.0.0
  [✔] MagicalForest-forge-1.19-2.1.0
  [✔] magiccombatwands-forge-1.19-1.0.3
  [✔] mahoutsukai-1.19.2-v1.34.59
  [✔] majrusz-library-1.19.2-5.1.2
  [✔] majruszs-enchantments-1.19.2-1.9.2
  [✔] marbledsarsenal-1.19.2-2.0.3
  [✔] matc-1.3.1
  [✔] mavapi-1.1.1-mc1.19.2
  [✔] mavm-1.2.4-mc1.19.2
  [✔] MCDoom-Forge-1.19.2-5.0.6
  [✔] mcjtylib-1.19-7.2.5
  [✔] mcw-bridges-2.1.1-mc1.19.2forge
  [✔] mcw-doors-1.1.0forge-mc1.19.2
  [✔] mcw-fences-1.0.7-mc1.19.2forge
  [✔] mcwfencesbop-1.19.2-1.0
  [✔] mcwfencesbyg-1.19.2-1.0
  [✔] mcw-furniture-3.2.1-mc1.19.2forge
  [✔] mcwfurnituresbop-1.19.2-1.3
  [✔] mcwfurnituresbyg-1.19.2-1.2
  [✔] mcw-lights-1.0.6-mc1.19.2forge
  [✔] mcw-paintings-1.0.5-1.19.2forge
  [✔] mcw-paths-1.0.3forge-mc1.19.2
  [✔] mcw-roofs-2.2.4b-mc1.19.2forge
  [✔] mcw-trapdoors-1.1.2-mc1.19.2forge
  [✔] mcw-windows-2.2.0-mc1.19.2forge
  [✔] Mega TNT Mod-1.19.2-1.4
  [✔] Mekanism-1.19.2-10.3.9.13
  [✔] MekanismAdditions-1.19.2-10.3.9.13
  [✔] MekanismGenerators-1.19.2-10.3.9.13
  [✔] MekanismTools-1.19.2-10.3.9.13
  [✔] memoryleakfix-forge-1.17+-1.0.0
  [✔] memorysettings-1.19.2-5.4
  [✔] merenc-forge-1.20.x-v3.2
  [✔] mes-1.3-1.19.2-forge
  [✔] metalbarrels-1.19.2-5.0.1
  [✔] minecraft-comes-alive-7.5.11+1.19.2-universal
  [✔] MissingWilds-forge-1.19.2-1.2.0-beta.2
  [✔] modernfix-forge-5.10.0+mc1.19.2
  [✔] modonomicon-1.19.2-1.34.0
  [✔] Mo'Enchantments-1.19.3-1.7.0
  [✔] MoGuns-1.9.2-1.19.2
  [✔] MonsterPlus-Forge1.19.2-v1.1.6.1
  [✔] moonlight-1.19.2-2.3.5-forge
  [✔] More Babies-forge-1.19.1-1.0.0
  [✔] More Wandering Trades 1.0.0 - 1.19.2
  [✔] more_ships_1.19.2_4.1
  [✔] MoreBows-1.0.12+1.19.2.forge
  [✔] MoreBuckets-1.19.2-3.0.2
  [✔] moredragoneggs-3.2
  [✔] moreminecarts-1.5.7
  [✔] moremobvariants-forge+1.19.2-1.2.0
  [✔] MoreOresInONE-1.0-1.19.2
  [✔] morevanillapotions-1.19.2-1.8
  [✔] MouseTweaks-forge-mc1.19-2.23
  [✔] MutantMonsters-v4.0.6-1.19.2-Forge
  [✔] mutantmore-1.19.2-early-access-1.0.7
  [✔] mutil-1.19.2-5.2.0
  [✔] mvs-4.1.1-1.19.2-forge
  [✔] MysticalAdaptations-1.19.2-1.0
  [✔] MysticalAgradditions-1.19.2-6.0.3
  [✔] MysticalAgriculture-1.19.2-6.0.13
  [✔] MysticPotions-1.1.2-1.19.2-Forge
  [✔] mysticsbiomes-1.19.2-3.1.2
  [✔] naturalist-forge-4.0.3-1.19.2
  [✔] NaturesAura-38.2
  [✔] NaturesCompass-1.19.2-1.10.0-forge
  [✔] Nether Ores Plus+ 1.0.0 - 1.19.2
  [✔] NetherChested-v4.0.4-1.19.2-Forge
  [✔] netherdepthsupgrade-3.1.1-1.19.2
  [✔] netherdungeons-1.0
  [✔] Nether's Overhaul-1.19.2_V1.1.0
  [✔] NethersDelight-1.19-3.1
  [✔] NEW_corpse_stalker(JE)_MC-1.19.2_V-1.0
  [✔] NewOresAndArmors_v.2.2(1.19.2)
  [✔] notenoughwands-1.19-5.0.2
  [✔] Nullscape_1.19.3_v1.2.2
  [✔] nyfsarcheryplus-forge-1.19.2-1.1.0
  [✔] nyfsbp-forge-1.19.2-1.1.0
  [✔] NyfsQuiver-1.19.2-0.7.4
  [✔] nzgExpansion-1.3.2-1.19.2
  [✔] obscure_api-15
  [✔] occultism-1.19.2-1.88.0
  [✔] oculus-flywheel-compat-1.19.2-0.2.1
  [✔] oculus-mc1.19.2-1.6.9
  [✔] ogres-0.6
  [✔] Oh_The_Biomes_You'll_Go-forge-1.19.2-2.0.1.6
  [✔] Ore_And_More_for_1.19.2_(v6.0)
  [✔] OreBerries-Replanted-1.19.2-0.2.3
  [✔] oresabovediamonds-9.0.2
  [✔] origins-forge-1.19.2-1.7.1.3-all
  [✔] origins-plus-plus-2.2-forge
  [✔] ostrich-forge-1.19.2-1.0.0
  [✔] Paintings-forge-1.19.2-10.2.4.0
  [✔] pamhc2crops-1.19.2-1.0.2
  [✔] pamhc2foodcore-1.19.2-1.0.1
  [✔] pamhc2foodextended-1.19.2-1.0.0
  [✔] pamhc2trees-1.19.2-1.0.1
  [✔] Paraglider-1.19.2-1.7.0.5
  [✔] Patchouli-1.19.2-77
  [✔] Pehkui-3.7.11+1.19.2-forge
  [✔] phantasmic-1.19.2-0.2.5
  [✔] PigPen-Forge-1.19.2-11.1.2
  [✔] Placebo-1.19.2-7.3.4
  [✔] player-animation-lib-forge-1.0.2
  [✔] polymorph-forge-0.46.5+1.19.2
  [✔] Potion-Blender-1.19.2-FORGE-1.1.0
  [✔] potionbundles-1.19.1-1.6
  [✔] potionsmaster-0.6.0-1.19.2-43.1.1
  [✔] PresenceFootsteps-1.19.2-1.6.4.1-forge
  [✔] primalmagick-3.2.1
  [✔] Prism-1.19.1-1.0.2
  [✔] projectvibrantjourneys-1.19.2-5.1.2
  [✔] puffish_skills-0.10.0-1.19.2-forge
  [✔] PuzzlesLib-v4.4.3-1.19.2-Forge
  [✔] Quark-3.4-418
  [✔] realcamera-1.19.2-forge-0.5.4-beta
  [✔] rechiseled-1.1.5c-forge-mc1.19.2
  [✔] rechiseledcreate-1.0.1-forge-mc1.19
  [✔] reds-more-structures-1.0.7-common
  [✔] RegionsUnexploredForge-0.5.3+1.19.2
  [✔] reliquary-1.19.2-2.0.40.1198
  [✔] repurposed_structures_forge-6.3.28+1.19.2
  [✔] resourcefulconfig-forge-1.19.2-1.0.20
  [✔] resourcefullib-forge-1.19.2-1.1.24
  [✔] Rex's-AdditionalStructures-1.19.x-(v.4.0.4)
  [✔] rftoolsbase-1.19-4.1.7
  [✔] rftoolsbuilder-1.19-5.2.8
  [✔] rftoolscontrol-1.19-6.1.4
  [✔] rftoolsdim-1.19.2-9.1.9
  [✔] rftoolspower-1.19-5.1.2
  [✔] rftoolsstorage-1.19-4.1.2
  [✔] rftoolsutility-1.19-5.1.9
  [✔] rottencreatures-forge-1.19.2-1.0.1
  [✔] RPG_style_more_weapons_7.1_1.19.2
  [✔] rubidium-extra-0.4.19+mc1.19.2-build.105
  [✔] rubidium-mc1.19.2-0.6.2c
  [✔] Runelic-Forge-1.19.2-14.1.4
  [✔] SandBox-1.19.2-1.0.1
  [✔] saturn-mc1.19.2-0.0.8
  [✔] savage_and_ravage-1.19.2-5.0.5
  [✔] scorchedguns-1.12-1.19.2
  [✔] scorpions-forge-1.19-41.0.100-1.3
  [✔] scuba_gear-1.19-1.0.5
  [✔] sculpt-1.19.2-v1.1.2.0
  [✔] SereneSeasons-1.19.2-8.1.0.24
  [✔] ShieldExpansion-1.19.2-1.1.7
  [✔] Simple Weapons 1.4.5 - 1.19.2
  [✔] simplehats-forge-1.19.2-0.1.6
  [✔] simplyswords-forge-1.47.0-1.19.2
  [✔] Sky Structures 1.0.0 - 1.19.2
  [✔] SkyVillages-1.0.3-1.19.2-1.20.x-forge-release
  [✔] sliceanddice-forge-2.3.2
  [✔] smallships-forge-1.19.2-2.0.0-a2.3
  [✔] SmartBrainLib-forge-1.19.2-1.9
  [✔] smoothchunk-1.19.2-3.5
  [✔] sophisticatedbackpacks-1.19.2-3.19.1.960
  [✔] sophisticatedcore-1.19.2-0.5.106.503
  [✔] soundphysics-forge-1.19.2-1.3.0
  [✔] spellbound-weapons-v4.0.1g
  [✔] spells_and_shields-1.19.2-2.15.1
  [✔] SpelunkersCharm-3.4.4-1.19.2
  [✔] spiderstpo-1.19.2-2.0.4
  [✔] spirit-forge-1.19.2-2.2.6
  [✔] spore_1.19.2_2.0.0b
  [✔] stalwart-dungeons-1.19.2-1.2.8
  [✔] starlight-1.1.1+forge.cf5b10b
  [✔] Steam_Rails-1.5.3+forge-mc1.19.2
  [✔] StorageDrawers-1.19-11.1.2
  [✔] Structory_Towers_1.19_v1.0.1
  [✔] Structory-1.19-v1.3
  [✔] Structural Statues 1.1.0 - 1.19.2
  [✔] structure_gel-1.19.2-2.7.3
  [✔] supermartijn642configlib-1.1.8-forge-mc1.19
  [✔] supermartijn642corelib-1.1.16-forge-mc1.19.2
  [✔] supplementaries-1.19.2-2.4.13
  [✔] swampier_swamps-1.19-1.2.0
  [✔] swordinthestone-1.1-1.19.2
  [✔] tectonic-mod-mc1.19.2-v2.1.1
  [✔] TerraBlender-forge-1.19.2-2.0.1.166
  [✔] Terralith_1.19.3_v2.3.12
  [✔] tetra-1.19.2-5.6.0
  [✔] TFD 1.3 Release MC1.19.2
  [✔] TFTH 0.2
  [✔] the man 1.19.2 - 1.0.0
  [✔] The_Graveyard_2.5.3_(FORGE)_for_1.19.2.
  [✔] The_Graveyard_Biomes_1.4_(FORGE)_for_1.19.2
  [✔] the_midnight_lurker_1.2.7
  [✔] The_Undergarden-1.19.2-0.8.3
  [✔] the-conjurer-1.19.2-1.1.5
  [✔] thedragonlib-1.19-1.0.0
  [✔] TheOneWhoWatches-V1.2.1-1.19.2
  [✔] THEUNDEADREVAMPED_0.9e_1.19.2
  [✔] THT-1.19.2-4.3.1
  [✔] tombstone-8.2.12-1.19.2
  [✔] TonsOfEnchants-1.19.2-1.2
  [✔] ToolBelt-1.19.2-1.19.7
  [✔] Towns-and-Towers-v.1.10-_FORGE-1.19.2_
  [✔] transparent-5.1.2+1.19-forge
  [✔] TravelersBackpack-1.19.2-8.2.37
  [✔] TravelersTitles-1.19.2-Forge-3.1.2
  [✔] traverse-forge-6.2.4
  [✔] trolls-0.5
  [✔] twigs-forge-1.19.2-3.0.1
  [✔] twilightforest-1.19.2-4.2.1518-universal
  [✔] u_team_core-1.19.2-4.4.3.260
  [✔] UndeadUnleashed-1.1.1-1.19.2
  [✔] UndergroundVillages-1.19.2-1.2.0
  [✔] Unique Enchantments Apex-1.19.2-3.0.1
  [✔] Unique Enchantments Base-1.19.2-3.0.2.1
  [✔] Unique Enchantments Battle-1.19.2-3.0.2
  [✔] Unique Enchantments Utils-1.19.2-3.0.2.1
  [✔] Unique Enchantments-1.19.2-4.0.2.1
  [✔] UniversalEnchants-v4.2.15-1.19.2-Forge
  [✔] upgrade_aquatic-1.19.2-5.1.0
  [✔] upgradedcore-1.19.2-4.1.0.1-release
  [✔] upgradednetherite_items-1.19.2-4.1.0.2-release
  [✔] upgradednetherite_ultimate-1.19.2-4.1.0.4-release
  [✔] upgradednetherite-1.19.2-5.1.0.9-release
  [✔] useful_railroads-1.19.2-1.5.1.47
  [✔] usefulhats-1.19.2-3.0.2.0
  [✔] useless-sword-furtos-edition-1.19.2-1.0.1
  [✔] valhelsia_core-forge-1.19.2-0.5.0
  [✔] valhelsia_furniture-forge-1.19.2-1.1.1
  [✔] valhelsia_structures-forge-1.19.2-1.0.4
  [✔] vanillaplustools-1.19-1.1
  [✔] villagesandpillages-forge-mc1.19.2-1.0.0
  [✔] VisualWorkbench-v4.2.4-1.19.2-Forge
  [✔] voidtotem-forge-1.19.2-2.1.0
  [✔] vulture-forge-1.19.2-1.0.0
  [✔] Waddles-1.19-0.9.1
  [✔] wardenhorn-1.1-forge-mc1.19.2
  [✔] wardenwalkers-1.3-forge-mc1.19.2
  [✔] waystones-forge-1.19.2-11.4.1
  [✔] wearablebackpacks-1.19.2-0.1.2
  [✔] Weeping-Angels-43.0.9-forge
  [✔] weirdmobs-forge-1.19-41.0.100-3.0.2
  [✔] whisperwoods-1.19-2.1.1-forge
  [✔] worldedit-mod-7.2.12
  [✔] Worldofbosses_0.4
  [✔] WWOO-FORGE-3.1.9+1.19.x
  [✔] xaeroarrowfix-forge-1.1+1.19
  [✔] Xaeros_Minimap_23.9.3_Forge_1.19.1
  [✔] xaeros_waystones_compability-1.0
  [✔] XaerosWorldMap_1.37.2_Forge_1.19.1
  [✔] xlpackets-1.18.2-2.1
  [✔] ydms_redpanda-forge-1.19.x-1.0.2
  [✔] YungsApi-1.19.2-Forge-3.8.10
  [✔] YungsBetterDesertTemples-1.19.2-Forge-2.2.2
  [✔] YungsBetterDungeons-1.19.2-Forge-3.2.2
  [✔] YungsBetterEndIsland-1.19.2-Forge-1.0
  [✔] YungsBetterJungleTemples-1.19.2-Forge-1.0.1
  [✔] YungsBetterMineshafts-1.19.2-Forge-3.2.1
  [✔] YungsBetterNetherFortresses-1.19.2-Forge-1.0.6
  [✔] YungsBetterOceanMonuments-1.19.2-Forge-2.1.1
  [✔] YungsBetterStrongholds-1.19.2-Forge-3.2.0
  [✔] YungsBetterWitchHuts-1.19.2-Forge-2.1.0
  [✔] YungsBridges-1.19.2-Forge-3.1.0
  [✔] YungsExtras-1.19.2-Forge-3.1.0
  [✔] zombieawareness-1.19.2-1.12.3
and also the latest log and debug file
[debug.log](https://github.com/VazkiiMods/Botania/files/13625576/debug.log)
[latest.log](https://github.com/VazkiiMods/Botania/files/13625577/latest.log)

**Comment by artemisSystem** [comment]
from a brief look on my phone - looks like it might be a mixin conflict with apotheosis. does it work if you keep botania and remove that?

**Comment by IsmacraftGG** [comment]
@artemisSystem wow. i tried and it worked, i did some digging on the web and i found some people saying that apotheosis is incompatible with unique enchantments... do you think that could be the cause behind the mixin error?

**Comment by artemisSystem** [comment]
if so, it's not a botania issue in that case. does it work if you keep botania and unique enchantments but remove apotheosis, and does it work if you keep botania and apotheosis and remove unique enchantments? can you try those two cases for me?

**Comment by IsmacraftGG** [comment]
@artemisSystem look man, im gonna be honest, i tried disabling, unistalling and moving and removing files. i think that at this point i will just delete all te mods and install one by one in a more cautious way. when i removed apotheosis and  unique enchantments the game COULD actually launch, but when i tried creating a world it just said "datapack validation failed", and when i click reset to default the game just froze at 100% world loading and never actually went into the world. i think its just best to close my bug report and ignore since tbh idk how to read log text nor to fix compatability issues, but hey thank you a lot for helping me. before going if you dont mind would you give me a few tips on how to read log and debug files to figure out the problems myself? thanks.

**Comment by IsmacraftGG** [comment]
@artemisSystem at this point im starting to think there is something wrong when i install mods cuz i swear everytime i try to download a bunch of mods i always end up with a headache.

**Comment by artemisSystem** [comment]
yeah, this doesn't seem to be a botania issue in any case

my best tip is to install fewer mods. you have a lot there. or try playing an existing modpack
