### ISSUE TITLE
Can you add a manasteel shield plssss!!! , original shield so easy broken

### ISSUE THREAD

**Issue by yaphoe** [Vazkii/Botania#4518]
### Mod Loader

Forge

### Minecraft Version

1.18.2

### Botania version

1.18.2

### Modloader version

forge

### The latest.log file

www.google.com

### Issue description

Can you add a manasteel shield plssss!!! , original shield so easy broken

### Steps to reproduce

Can you add a manasteel shield plssss!!! , original shield so easy broken

**Comment by artemisSystem** [comment]
there are no plans to add a manasteel shield. and this issue tracker is not for suggestions. Besides, 1.18.2 is not getting more features
