### ISSUE TITLE
Botania Doubles All Loot Created in CraftTweaker Scripts

### ISSUE THREAD

**Issue by Darkosto** [Vazkii/Botania#4520]
### Mod Loader

Forge

### Minecraft Version

1.20.1

### Botania version

1.20.1-441 Forge

### Modloader version

Forge 47.2.0

### The latest.log file

N/A

### Issue description

When using both CraftTweaker and Botania, loot drops created via scripts are doubled.

### Steps to reproduce

1. Install both CraftTweaker and Botania
2. Setup a script for a Drowned to drop stone: `<entitytype:minecraft:drowned>.addLootModifier("drowned_drops_heart_of_the_sea", CommonLootModifiers.add(<item:minecraft:stone> * 2));`
3. Kill Drowned and observe stone amount

### Other information

The following is the list of mods in the pack when testing:
Botania: 1.20.1-441-FORGE
CraftTweaker: 14.0.27
Curios API: 5.4.6+1.20.2
Patchouli: 1.20.1-84-FORGE

This issue is potentially related to the following code: https://github.com/VazkiiMods/Botania/blob/1.20.x/Xplat/src/main/java/vazkii/botania/mixin/LootTableMixin.java#L39

**Comment by jaredlll08** [comment]
This is related to Global Loot Modifiers being ran multiple times, so this can be reproduced with just forge itself

**Comment by Terraj459** [comment]
Has there been any movement on this issue?
