### ISSUE TITLE
1.20.1 - PistonStructureResolverMixin Server crash

### ISSUE THREAD

**Issue by Gamerbolts** [Vazkii/Botania#4527]
### Mod Loader

Forge

### Minecraft Version

1.20.1

### Botania version

1.20.1-442

### Modloader version

47.2.16

### Modpack info

Heavily modified ATM9

### The latest.log file

https://gist.github.com/Gamerbolts/528f6e8aa1f5e2229bacc0a3c0531035

### Issue description

I am not sure what happened I was running around exploring the world and crashed. I think a piston did something somewhere I could not see.

### Other information

[crash-2023-12-30_15.29.56-server.txt](https://github.com/VazkiiMods/Botania/files/13799223/crash-2023-12-30_15.29.56-server.txt)

**Comment by TheRealWormbo** [comment]
How heavily modified? You appear to be running a bunch of Fabric mods on a post-fork Forge version, which means you use a Fabric compatibility mod *and* a Forge version that may or may not be unstable.

The crash your log file shows does indeed happen from a mixin for piston pushing logic, which requires Forge's access transformer features to work properly. This works with Forge versions 47.1.3 (the latest version before most Forge devs forked NeoForged) and 47.1.47, but as not been tested on any newer version of the mod loader. Can you maybe downgrade to one of those two versions and check if it still causes issues?

**Comment by Gamerbolts** [comment]
Quite heavily modded. I added about 200 mods to ATM9 which gave me a total of 678. I do have neoforge connector and forgified fabric in the pack. I'll try those two earlier versions of forge to see if that works. Thanks for the help

**Comment by lgc2333** [comment]
+1
[crash-2024-01-01_18.39.44-server.txt](https://github.com/VazkiiMods/Botania/files/13804281/crash-2024-01-01_18.39.44-server.txt)

**Comment by TheRealWormbo** [comment]
Thank you. A fix is already in the pipeline and probably gets released soon.

**Comment by liny-fox** [comment]
Just tested by creating a blank modpack in the curse forge loader and installing botaina and its required dependencies and placing a piston and a button next to it and the server instantly crashes when pressing the button.

**Comment by lgc2333** [comment]
try this before the next version release
https://github.com/lgc2333/Botania/actions/runs/7383125195
(PR #4528 did this)

**Comment by TheRealWormbo** [comment]
> try this before the next version release https://github.com/lgc2333/Botania/actions/runs/7383125195

What does that do? (And how does it relate to this bug?)

**Comment by artemisSystem** [comment]
Fix is now out: https://forum.violetmoon.org/d/158-botania-1201-443-released

**Comment by OBS3SS1ON** [comment]
Oh!! Thank you very much as I read your mod name in the log.txt thinking it was from your mod, Thank you very much I will see if it is resolved
