### ISSUE TITLE
Bi-Directional Mana Flow with Dominant Spark

### ISSUE THREAD

**Issue by Vanir2314** [Vazkii/Botania#453]
I found a behaviour that I think should not be there.
If I have a mana pool with dominant Spark near a terrestrial Agglomeration Plate Mana flows in both directions and no progress is made.
So basically particles go from Spark A to B and from B to A and the particles at the Plate stay blue.
As soon as I remove the Dominant Augment everything goes the way it is supposed to.
![2015-01-02_12 42 33](https://cloud.githubusercontent.com/assets/6696271/5595808/e21da9a2-927c-11e4-97e9-82cf7d6b3bce.png)
![2015-01-02_12 43 35](https://cloud.githubusercontent.com/assets/6696271/5595813/fef5b89e-927c-11e4-98fd-80ce512b7a27.png)

**Comment by Vazkii** [comment]
Interesting, I'll have a look.
