### ISSUE TITLE
In certain modded environments, all loot tables appear to be empty

### ISSUE THREAD

**Issue by unilock** [Vazkii/Botania#4539]
### Mod Loader

Quilt (possibly also Fabric)

### Minecraft Version

1.20.1

### Botania version

1.20.1-443

### Modloader version

Quilt Loader 0.23.0 + QFAPI 7.4.0 / Fabric API 0.90.0

### Modpack info

N/A

### The latest.log file

https://gist.github.com/unilock/102676f783706c3df48a78b89980b897

### Issue description

Under very certain conditions (namely, the exact set of mods installed), all loot tables appear to be empty - blocks drop nothing, slain mobs drop nothing, etc.

### Steps to reproduce

1. Install Quilt Loader 0.23.0
2. Install the *exact* set of mods listed below
3. Start the game, create a new superflat world in survival mode with cheats enabled
4. Try breaking a Grass Block by hand; nothing is dropped
5. `/give <username> minecraft:netherite_sword`
6. `/summon minecraft:sheep`
7. Kill the Sheep with the Netherite Sword; nothing is dropped

### Other information

This issue does not occur reliably across all modded environments; rather, it seems dependent on which mods are installed at the time. I suspect this is due to the mod loading order being semi-random on Fabric / Quilt; I'm guessing it's deterministic based on the current mod set. My theory is that some loot-related mixin is being applied before / after some other loot-related mixin in an incompatible manner, ultimately causing the issue.

Due to this issue being so random, it's been very difficult to narrow down the mod set to only those related to the issue. Here is the smallest set of mods I've been able to reproduce the issue with thus far:
- [`badpackets-fabric-0.4.3.jar`](https://modrinth.com/mod/badpackets/version/fabric-0.4.3)
- [`balm-fabric-1.20.1-7.2.1.jar`](https://modrinth.com/mod/balm/version/7.2.1+fabric-1.20.1) *
- [`Botania-1.20.1-443-FABRIC.jar`](https://modrinth.com/mod/botania/version/1.20.1-443-fabric) *
- [`can-i-mine-this-block-1.4.0.jar`](https://modrinth.com/mod/can-i-mine-this-block/version/1.4.0)
- [`Crafty-Crashes-1.0.jar`](https://github.com/Chocohead/Crafty-Crashes/releases/tag/v1.0)
- [`ctrlq-fabric-mc1.19.3+-1.9.jar`](https://modrinth.com/mod/ctrl-q/version/1.9-f1.19.3+)
- [`emi-1.0.29+1.20.1+fabric.jar`](https://modrinth.com/mod/emi/version/1.0.29+1.20.1+fabric)
- [`macos-input-fixes-1.6.jar`](https://modrinth.com/mod/macos-input-fixes/version/1.6)
- [`mixintrace-1.1.1+1.17.jar`](https://modrinth.com/mod/mixintrace/version/1.1.1+1.17)
- [`modmenu-7.2.2.jar`](https://modrinth.com/mod/modmenu/version/7.2.2)
- [`MouseTweaks-fabric-mc1.20-2.25.jar`](https://modrinth.com/mod/mouse-tweaks/version/1.20-2.25-fabric)
- [`Patchouli-1.20.1-84-FABRIC.jar`](https://modrinth.com/mod/patchouli/version/1.20.1-84-fabric)
- [`porting_lib-2.1.1175+1.20.1.jar`](https://github.com/Fabricators-of-Create/Porting-Lib/actions/runs/7365652519) *
- [`qfapi-7.4.0_qsl-6.1.2_fapi-0.90.0_mc-1.20.1.jar`](https://modrinth.com/mod/qsl/version/7.4.0+0.90.0-1.20.1) *
- [`quilt-kotlin-libraries-2.1.3+kt.1.9.10+flk.1.10.10.jar`](https://modrinth.com/mod/qkl/version/2.1.3+kt.1.9.10+flk.1.10.10)
- [`trinkets-3.7.1.jar`](https://modrinth.com/mod/trinkets/version/3.7.1)
- [`wthit-quilt-8.4.3.jar`](https://modrinth.com/mod/wthit/version/quilt-8.4.3)

Mods marked with a `*` are noted to have a mixin targetting `net/minecraft/world/level/storage/loot/LootTable` (Mojmap) / `net/minecraft/loot/LootTable` (Yarn).

I'm fairly certain this issue is caused by, or at least related to Botania, as removing Botania results in the issue resolving itself, even after several other changes to the mod set.

**Comment by Partonetrain** [comment]
I have had issues with porting_lib in the past - my understanding is it drastically changes the vanilla loot system. Does this happen without it?

**Comment by unilock** [comment]
Removing Porting Lib (and all mods that depend on / embed it) *does* also appear to "fix" the issue. However, it's used by quite a few large mods in the modpack I'm working with, so removing it is not much of an option, in my case.

This leads me to believe that this is an incompatibility between Botania and Porting Lib. That being said, I believe this *specifically affects Quilt (Loader / API),* as I have in the past used a Fabric-based 1.20.1 modpack with Botania and Porting Lib without ever encountering this issue.

Although... another Fabric-based 1.20.1 modpack, [All of Fabric 7](https://github.com/TeamAOF/All-of-Fabric-7), appears to have also had this issue after adding Botania and Create (and thus Porting Lib): https://github.com/TeamAOF/All-of-Fabric-7/issues/66  
...but I guess it's since been resolved? I have no idea what they might've done to fix it, though...

**Comment by anoomolu** [comment]
I wonder if it's to do with the chest loot injects Botania does?

**Comment by unilock** [comment]
I checked [All of Fabric's Discord guild](https://discord.gg/6rkdm48), and apparently this is a recurring issue - though it seems to only occur after their AOF7 server(s) have been running for a while (instead of immediately), and is usually fixed by restarting the server. Neither is the case for me...

Links to some relevant messages in the Discord guild: [2024-01-07](https://discord.com/channels/570630340075454474/1142965778371596419/1193630520660201536), [2024-01-04](https://discord.com/channels/570630340075454474/1142965778371596419/1192570918107627611), [2024-01-04](https://discord.com/channels/570630340075454474/1142965778371596419/1192552420488777869), [2023-12-31](https://discord.com/channels/570630340075454474/1142972811460214905/1191106434541305907) (with some relevant discussion)

**Comment by unilock** [comment]
Fixed on Porting Lib's end.
