### ISSUE TITLE
Abstruse/Spectral Platform can't disguise properly on fabric 1.20.1.

### ISSUE THREAD

**Issue by kagamime** [Vazkii/Botania#4545]
### Mod Loader

Fabric

### Minecraft Version

1.20.1

### Botania version

Botania-1.20.1-443-FABRIC

### Modloader version

fabric loader 0.14.22 or 0.15.3 / api 0.87.0 or 0.91.0

### The latest.log file

n/a

### Issue description

Abstruse/Spectral Platform can't render properly on fabric 1.20.1.
(Try right click with a slab, there could see the shape was applied, however the texture wasn't applied properly.)
![image](https://github.com/VazkiiMods/Botania/assets/128010390/9a3cde7d-5435-40fc-8838-8884f4a21bdc)
(And put a slab near by platform, render miss like that.)
![image3](https://github.com/VazkiiMods/Botania/assets/128010390/16765687-d01b-462c-9f33-c9a1e992769f)

There only botania and its required mods.
![image2](https://github.com/VazkiiMods/Botania/assets/128010390/a1869f17-321f-4be4-8475-e2a51463b389)

### Other information

p.s. forge 1.20.1 working normally.
![image4](https://github.com/VazkiiMods/Botania/assets/128010390/6fe9d13d-b893-457a-8077-ec515eddf78d)

**Comment by anoomolu** [comment]
Apologies, was able to reproduce the issue in a test instance.

```
I'm unable to reproduce this in my small-ish modpack with Sodium disabled (nothing else should be affecting rendering). Right-clicking an Abstruse or Spectral Platform with an oak slab successfully replaced the block without any issues:

![image](https://github.com/VazkiiMods/Botania/assets/77850233/b8d1b895-4974-4bc6-b966-132c3beb129d)

My log in case there's a significant difference in setups: https://mclo.gs/ygaxF4v
```

**Comment by kagamime** [comment]
My case doesn't use any modpacks.
And here is the log: https://mclo.gs/O0whZXy

There is use a slab right click abstruse platform lower half and spectral platform upper half.
![image](https://github.com/VazkiiMods/Botania/assets/128010390/6f23cd33-50c6-4a4e-8d48-355466fd399b)

There  is graphics info:
![1](https://github.com/VazkiiMods/Botania/assets/128010390/364598cd-240b-4bc9-8543-a12ca025cb3a)
with nvidia gpu:
![2](https://github.com/VazkiiMods/Botania/assets/128010390/7ba6b2c8-d798-42ae-a192-da975d515a1e)

**Comment by Robotgiggle** [comment]
Can confirm I am experiencing the exact same issue. Running on Fabric version 0.15.6, with only the below mods installed:
<img width="205" alt="image" src="https://github.com/VazkiiMods/Botania/assets/88736742/1ecea44c-83f9-4c70-885e-84939d9accc3">
Both types of platforms fail to change texture when disguised, despite playing the right-click animation when I click with a block. As above, attempting to disguise with a slab shows the outline of the slab without changing the block model, and placing another slab next to the "disguised" platform causes the side to stop rendering.
![2024-02-14_20 51 56](https://github.com/VazkiiMods/Botania/assets/88736742/3239150e-a6e5-49d9-a05a-eef4f8feb6ec)
![2024-02-14_20 52 08](https://github.com/VazkiiMods/Botania/assets/88736742/9f73d312-8d08-4239-9e06-087f3201bc31)
