### ISSUE TITLE
Summoning Blaze via Fel Pumpkin doesn't trigger minecraft:summoned_entity

### ISSUE THREAD

**Issue by anoomolu** [Vazkii/Botania#4554]
### Mod Loader

Both Fabric and Forge (I confirm that I have tested both loaders and will specify both loader versions below)

### Minecraft Version

1.20.1

### Botania version

1.20.1-443

### Modloader version

Forge 47.2.0 / Fabric Loader 0.15.0, API 0.91.0

### The latest.log file

n/a

### Issue description

As the title says, spawning a Blaze via Fel Pumpkin doesn't fire "minecraft:summoned_entity", making advancements like the one below incompletable. When I asked on Discord, Wormbo suggested that it should fire for starting the Gaia Ritual, and I think this would be good too (I want to edit the relevant advancement).
```
{
  "parent": "botania:main/mana_pool_pickup",
  "criteria": {
    "summoned_blaze": {
      "conditions": {
        "entity": [
          {
            "condition": "minecraft:entity_properties",
            "entity": "this",
            "predicate": {
              "type": "minecraft:blaze"
            }
          }
        ]
      },
      "trigger": "minecraft:summoned_entity"
    }
  },
  "display": {
    "announce_to_chat": true,
    "description": "Summon a Blaze by placing a Fel Pumpkin atop two Iron Bars",
    "frame": "task",
    "hidden": false,
    "icon": {
      "item": "botania:fel_pumpkin"
    },
    "show_toast": true,
    "title": "Pumpkin Syndrome"
  },
  "requirements": [
    [
      "summoned_blaze"
    ]
  ],
  "sends_telemetry_event": true
}
```

**Comment by TheRealWormbo** [comment]
I just remembered that pixies are technically also a mob a player can summon – though not quite voluntarily. Should those also fire that trigger?

**Comment by anoomolu** [comment]
At least in vanilla, it only triggers following block placement that would lead to entity spawning - end crystals, pumpkins, wither skeleton skulls etc., so maybe it should just stick to fel pumpkins? (and gaia because boss spawning?)
