### ISSUE TITLE
Crash when opening Flower Pouch on Fabric 1.20.1 with older Sodium version

### ISSUE THREAD

**Issue by Nezarbek** [Vazkii/Botania#4558]
### Mod Loader

Fabric

### Minecraft Version

1.20.1

### Botania version

1.20.1-443-fabric

### Modloader version

Fabric: Loader / 0.15.6

### The latest.log file

https://pastebin.com/vZXYkvt8

### Issue description

If Sodium version 0.4.10 and Fabric API version 0.88.1 are installed, attempting to open a flower pouch will crash the game. Unfortunately, using the older Sodium and Fabric API versions are necessary with any modpack that includes Create as Create is currently incompatible with Sodium versions newer than 0.4.10. Issue occurs on single player and on servers, with crash log indicating it was an issue rendering the Flower Pouch menu.

### Steps to reproduce

Install Botania and dependencies, Fabric API version 0.88.1, and Sodium version0.4.10.
Launch any world.
Attempt to open a flower pouch.

**Comment by TiGReX423** [comment]
Version Forge 47.2.19, Botania 1.20.1-443, with Rubidium 0.6.5 also crash when opening pouch. (Can not use new Rubidium version). Probably have to write to Rubidium dev.. let me know
`The game crashed whilst rendering screen
Error: java.lang.ClassCastException: class vazkii.botania.client.core.helper.RenderHelper$GhostVertexConsumer cannot be cast to class me.jellysquid.mods.sodium.client.render.vertex.VertexBufferWriter (vazkii.botania.client.core.helper.RenderHelper$GhostVertexConsumer is in module botania@1.20.1-443-FORGE of loader 'TRANSFORMER' @3d71e10b; me.jellysquid.mods.sodium.client.render.vertex.VertexBufferWriter is in module rubidium@0.6.5 of loader 'TRANSFORMER' @3d71e10b)`

**Comment by anoomolu** [comment]
Does replacing Sodium/Rubidium with Embeddium make any difference? It’s supposed to be more compatible with mods.

**Comment by goodiesohhi** [comment]
Anybody have any updates on this?

**Comment by TheRealWormbo** [comment]
It looks like Create figured things out on their side. We will not add a workaround for a conflict between two other mods.
