### ISSUE TITLE
Gaia Guardian Health Bar Not Rendering?

### ISSUE THREAD

**Issue by NolanHewitt** [Vazkii/Botania#4559]
### Mod Loader

Fabric

### Minecraft Version

1.20.1

### Botania version

1.20.1-443

### Modloader version

Quilt 0.23 QFAPI 7.4.0

### The latest.log file

https://gist.github.com/NolanHewitt/e9e836a1ecce268940f66cde6d636e3a

### Issue description

The health bar appears, but the purple part of the bar which decreases as the guardian takes damage does not. 
![huge_2024-01-18_05 00 38](https://github.com/VazkiiMods/Botania/assets/52480898/864f237e-8494-4600-8099-1866a419b331)

**Comment by anoomolu** [comment]
It's an incompatibility with ImmediatelyFast, disable it and it should render fine.

I posted an issue about it here: https://github.com/RaphiMC/ImmediatelyFast/issues/152

**Comment by NolanHewitt** [comment]
Ah, yeah that fixed it. Looks like it is IF causing the issue.
