### ISSUE TITLE
Sprinkling Starter Flowers with Pixie Dust: and making them actually viable to use

### ISSUE THREAD

**Issue by Barhandar** [Vazkii/Botania#456]
Dayblooms, Nightshades, and Hydroangeas produce absolutely infinitesimal amounts of power for the space taken. Why not add Elven Knowledge way to increase their output, say, thirtyfold or so, so that they can be used for later game, and not just serve as a sparkly decoration?

**Comment by Vazkii** [comment]
Because that means that the other ones that actually require resoruces become obsolete.
