### ISSUE TITLE
Livingwood/Dreamwood Planks have the wrong noteblock sound (Harp instead of bass)

### ISSUE THREAD

**Issue by Aeonsteel** [Vazkii/Botania#4564]
### Mod Loader

Fabric

### Minecraft Version

1.20.1

### Botania version

1.20.1-443-FABRIC

### Modloader version

Fabric 0.15.3

### The latest.log file

https://pastebin.com/7J82WaPS

### Issue description

Botania wooden planks have the wrong noteblock sound.

### Steps to reproduce

Place a vanilla plank and a botania plank next to each other.
Place a noteblock on top of each.
Note (Via F3 or right-clicking) that the noteblock instruments are different, (Bass for vanilla, harp for Botania)

### Other information

This also breaks compatibility with the new "Sawmill" mod's auto recipe generation.

**Comment by dhouck** [comment]
This also causes compat issues with other mods; see MehVahdJukaar/WoodGood#439.  Although I’m not sure why they can’t just use the `#minecraft:planks` tag…

**Comment by TheRealWormbo** [comment]
Same actually applies to livingrock blocks. They should probably make basedrum sounds, but also just play harp.
It might be worth checking all Botania blocks for their noteblock instruments.
