### ISSUE TITLE
Missing Translation

### ISSUE THREAD

**Issue by RickieGamer** [Vazkii/Botania#4565]
### Mod Loader

Forge

### Minecraft Version

1.20.1

### Botania version

Botania-1.20.1-443-FORGE

### Modloader version

FORGE 47.2.0

### The latest.log file

NA

### Issue description

itemGroup.botania is untranslated in en_us
![image](https://github.com/VazkiiMods/Botania/assets/90967853/da84e26c-4d2b-4a6b-851c-4a8f9c655a1c)

**Comment by anoomolu** [comment]
I'm making a small patch for some lexicon stuff but if you'd like a fix for the time being, removing one of the .botania from:
https://github.com/VazkiiMods/Botania/blob/80fbdb902f76794b62b933f6a59857c8887e6cc0/Xplat/src/main/resources/assets/botania/lang/en_us.json#L8

and adding it to your game via resource pack should fix the issue.

**Comment by TheRealWormbo** [comment]
Strange bug. I cannot reproduce it showing that particular incorrect Creative tab tooltip with just Botania and its dependencies. The Creative tab's key is `botania.botania` (both on Fabric and Forge), and that is part of the translation file in 443 already. I tried both with the officially supported Forge version of 41.3.1, and the one from this report.

**Comment by anoomolu** [comment]
It's still incorrect on the root Botania advancement/advancement tab iirc

**Comment by TheRealWormbo** [comment]
Oh, that's what that is. Confirmed on Fabric as well, and should be an easy fix.
