### ISSUE TITLE
Manasteel Shears do not drop cobwebs

### ISSUE THREAD

**Issue by ToxinZangoose** [Vazkii/Botania#4566]
### Mod Loader

Forge

### Minecraft Version

1.20.1

### Botania version

1.20.1-443-FORGE

### Modloader version

Forge 47.2.20

### The latest.log file

https://mclo.gs/IvJvq58

### Issue description

When using Manasteel shears on a cobweb, the cobweb breaks and gives string instead of a whole cobweb. Unsure if this is intentional or not, since I do know that there is a recipe for crafting cobwebs with mana infused string.

### Steps to reproduce

1. Craft Manasteel shears
2. Find a cobweb
3. Break the cobweb and receive string

**Comment by anoomolu** [comment]
I'm unable to reproduce this on both Forge and Fabric with just Botania + deps. Does the cobweb drop itself when broken with regular shears?
