### ISSUE TITLE
No Reliquary Reincarnations drops with Botania and Garden of Glass Installed

### ISSUE THREAD

**Issue by DarthDuroq** [Vazkii/Botania#4573]
### Mod Loader

Forge

### Minecraft Version

1.20.1

### Botania version

1.20.1-443

### Modloader version

Forge 47.2.20

### The latest.log file

N/A

### Issue description

When Reliquary Reincarnations is installed the mobs drop the mod's special items just fine, same when both Reliquary Reincarnations and Botania are installed together. However, adding Garden of Glass causes all special Reliquary drops to cease dropping.

### Steps to reproduce

1. Install latest Reliquary Reincarnations, Botania, and Garden of Glass.
2. Kill a number of zombies.
3. Get no Reliquary loot.

**Comment by Partonetrain** [comment]
possibly related to https://github.com/VazkiiMods/Botania/issues/4520 (same mixin)
