### ISSUE TITLE
Lexica Botania is not placeable in Chiseled Bookshelf

### ISSUE THREAD

**Issue by sehrgut** [Vazkii/Botania#4575]
### Mod Loader

Forge

### Minecraft Version

1.20.1

### Botania version

1.20.1-443-FORGE

### Modloader version

NeoForge mod loading, version 47.1.84, for MC 1.20.1 with MCP 20230612.114412

### Modpack info

https://www.feed-the-beast.com/modpacks/119-ftb-presents-direwolf20-120

### The latest.log file

https://pastebin.com/MP7SHR4d

### Issue description

Lexica Botania is not placeable in Chiseled Bookshelves. Other mod manuals are, but I have to keep my Lexica Botania in a chest or item shelf.

### Steps to reproduce

1. Place Chiseled Bookshelf
2. Craft both Lexica Botania and another mod manual like Iron's Guidebook (Iron's Spells 'n' Spellbooks) or PNC:R Manual (PneumaticCraft).
3.  Attempt to place both books in shelf.
4. Observe that Lexica Botania is not placeable.

### Other information

DireWolf20 version 1.12.1 (no link available to specific modpack version)

**Comment by anoomolu** [comment]
Hiya, thanks for the bug report ^^

This has been filed in https://github.com/VazkiiMods/Botania/issues/4488

**Comment by TheRealWormbo** [comment]
Closing as duplicate.
