### ISSUE TITLE
Villager

### ISSUE THREAD

**Issue by saphsara** [Vazkii/Botania#4577]
### Mod Loader

Fabric

### Minecraft Version

1.20.1

### Botania version

Botania-1.20.1-443-FABRIC.jar

### Modloader version

0.15.6

### Modpack info

https://www.curseforge.com/minecraft/modpacks/saphsgaming

### The latest.log file

n/a

### Issue description

is there a botania villager? if so where can i find info to obtain it thx

**Comment by anoomolu** [comment]
There’s currently no Botania villager.

**Comment by saphsara** [comment]
> There’s currently no Botania villager.

Thank you, Is it something that would possibly added in the future?

**Comment by anoomolu** [comment]
I can't speak for the dev team but I don't really see the need for one or how it would fit into the lore. The Elves trade with the player through the Alfheim portal, which is too fragile for them to travel through. If you have any ideas, feel free to post something on the Violet Moon forum
