### ISSUE TITLE
1.20.1 Forge Json removal no longer works

### ISSUE THREAD

**Issue by Joshernoob** [Vazkii/Botania#4578]
### Mod Loader

Forge

### Minecraft Version

1.20.1

### Botania version

Botania-1.20.1-443-FORGE

### Modloader version

Forge 47.2.20

### Modpack info

Custom/ In the works Pack

### The latest.log file

N/A

### Issue description

When checking the Files system as i would normally do i noted that adding recipe to the existing json works but removing them, crafttweaker or kubejs no longer is possable,

this in turn making it impossable to make custom recipe with the mod.

Am only posting as if this is a bug then hope for it to get fixed fast for modpack creators, and if not maybe remove the json or have a warning on the front of the github for pack makers from now on that it won't be a thing anymore?

### Steps to reproduce

Download the mod
try to remove a recipe with crafttweaker or kubejs
see that it fails

### Other information

Again only reporting to get fix or get it know its removed or all that make packs

**Comment by Joshernoob** [comment]
with more checking this seem to be only the pure daisy recipes that won't be removed, removing the flower itself from the petal apothecary worked as i know it to

**Comment by anoomolu** [comment]
Not sure about CT or KubeJS, but recipes can definitely be removed via datapack. Copy over the recipe inside a pure_daisy folder and replace the contents with curly brackets {}

I've been using Fabrication/Forgery's yeet recipes feature and it works perfectly, maybe give that a go in the meanwhile? Can't test it myself atm

**Comment by Joshernoob** [comment]
> Not sure about CT or KubeJS, but recipes can definitely be removed via datapack. Copy over the recipe inside a pure_daisy folder and replace the contents with curly brackets {}
> 
> I've been using Fabrication/Forgery's yeet recipes feature and it works perfectly, maybe give that a go in the meanwhile? Can't test it myself atm

Thanks for the idea but since the pure daisie only recipe that seems blocked I'll go with just leaving it alone until ita fixed or more get mekanism'd (locked out) even if its not on purpose

**Comment by TheRealWormbo** [comment]
Could you be a little more specific about how you attempt to remove recipes for the Pure Daisy and for other Botania recipe types? (Ideally show a minimum script that is supposed to do that, but fails.)
There is no special support for KubeJS or CraftTweaker in recent versions of the mod, and there shouldn't be anything special about "pure_daisy"-type recipes, as far as I can tell.

**Comment by artemisSystem** [comment]
[remove_livingrock_recipe.zip](https://github.com/user-attachments/files/16066548/remove_livingrock_recipe.zip)
This datapack works fine for me, to remove the pure daisy recipe for livingrock. Tested on your specified botania and forge versions.

It should also be possible to do something like this with kubejs (but it's been years since i've used it and i'm not entirely sure how). You'd specify the recipe path and replace it with "{}".

**Comment by artemisSystem** [comment]
KubeJS seems to not let you set a recipe at a specific path, but it does support removing arbitrary recipes. I would imagine the following would work:
`event.remove({ id: 'botania:pure_daisy/livingrock' })`
