### ISSUE TITLE
IncompatibleClassChangeError with Dye Depot

### ISSUE THREAD

**Issue by TheRealWormbo** [Vazkii/Botania#4589]
### Mod Loader

Both Fabric and Forge (I confirm that I have tested both loaders and will specify both loader versions below)

### Minecraft Version

1.20.1

### Botania version

1.20.1-443

### Modloader version

Forge 47.1.3, Forge 47.2.21, Fabric Loader 0.15.7, Fabric API 0.92.0+1.20.1

### Modpack info

(n/a)

### The latest.log file

https://gist.github.com/TheRealWormbo/69313e37da2252337681ff0f96382003

### Issue description

The presence of Dye Depot causes Botania's floating flower registration logic to crash with an `IncompatibleClassChangeError`.

### Steps to reproduce

Start Minecraft with Botania (+ dependencies) and Dye Depot installed.

### Other information

User [MagicFlowersss](https://forum.violetmoon.org/u/MagicFlowersss) initially [reported the incompatibility](https://forum.violetmoon.org/d/208-my-modpack-with-botania-installed-crashes-during-startup-of-minecraft) for Forge and confirmed it to be independent of the loader version, later finding out it was caused by Dye Depot.

**Comment by ereese99** [comment]
I too am getting this @Vazkii

**Comment by TheRealWormbo** [comment]
> I too am getting this @Vazkii

For the record: Vazkii handed off Botania development years ago already.

I'm also inclined to track this issue for reference only, as it's really Dye Depot's design decision to implement a binary-incompatible change.
