### ISSUE TITLE
JEI lexion lookup feature's progress circle hidden by tooltip

### ISSUE THREAD

**Issue by anoomolu** [Vazkii/Botania#4596]
### Mod Loader

Forge

### Minecraft Version

1.20.1

### Botania version

1.20.1-443

### Modloader version

Forge: 47.2.0

### The latest.log file

n/a

### Issue description

As visible (or rather not visible) in the picture below, when tooltips shift to the left-hand side of the item, like when hovering items further right in JEI, the tooltip obscures the progress circle when looking up the relevant entry in the lexicon via CTRL.

![image](https://github.com/VazkiiMods/Botania/assets/77850233/15219ebc-668c-425f-8fe7-8f6fbbe83e52)

**Comment by TheRealWormbo** [comment]
Probably a Patchouli bug, as that's where that feature comes from.
