### ISSUE TITLE
Lexicon lookup feature doesn't work in inventory on Fabric

### ISSUE THREAD

**Issue by anoomolu** [Vazkii/Botania#4597]
### Mod Loader

Fabric

### Minecraft Version

1.20.1

### Botania version

1.20.1-443

### Modloader version

Fabric Loader 0.15.7, API 0.92.0

### The latest.log file

n/a

### Issue description

While in-world lexicon lookups are possible by shift-right clicking blocks with the Lexicon, the inventory version doesn't seem to work on Fabric. The prompt for looking up lexicon entries isn't present, and pressing CTRL doesn't do anything either. On Forge, these work as normal.

**Comment by TheRealWormbo** [comment]
I'm relatively sure that would be a Patchouli feature, as there's a request to add support for EMI to it: https://github.com/VazkiiMods/Patchouli/issues/688
Could you maybe check if it's broken for Fabric in general (e.g. running Botania with REI or JEI) or only in combination with EMI specifically? Also maybe try Botania and EMI on Forge.

**Comment by anoomolu** [comment]
It's broken in general on Fabric - my instance didn't contain any recipe viewer mod aside from the vanilla recipe book. Tested without any similar mod on Forge and the lookup feature seemed to work fine.

edit: seems like lookup still works fine in inventory with EMI on Forge, just doesn't want to work in the EMI index - doesn't break existing functionality

**Comment by TheRealWormbo** [comment]
I'm going to close this since it's a Patchouli feature, not a Botania one. I assume it's a limitation in EMI, as pointed out in the issue I linked above.
