### ISSUE TITLE
Outdated structures cause DFU to process every time they are loaded

### ISSUE THREAD

**Issue by Linguardium** [Vazkii/Botania#4602]
### Mod Loader

Fabric

### Minecraft Version

1.20.1

### Botania version

1.20.1-443-FABRIC

### Modloader version

N/A

### Modpack info

AOF7

### The latest.log file

N/A

### Issue description

structure nbt files do not match the version of minecraft your mod is released for. this causes DFU to process them every time they are loaded.
Please update the structure nbt for the versions of minecraft you are releasing for to prevent unnecessary DFU usage on player computers

### Steps to reproduce

open game
spawn structure
dfu has now processed structure
(could also just check the nbt itself)

**Comment by TheRealWormbo** [comment]
Which structures, specifically? Botania doesn't place any structures by default. The player-built ones are validated as Patchouli multi-blocks.
