### ISSUE TITLE
RenderHelper#renderProgressPie causes a crash

### ISSUE THREAD

**Issue by iSTeeWx** [Vazkii/Botania#4604]
### Mod Loader

Forge

### Minecraft Version

1.20.1

### Botania version

1.20.1-443

### Modloader version

Forge: 47.2.20

### Modpack info

All The Mods 9, https://www.curseforge.com/minecraft/modpacks/all-the-mods-9

### The latest.log file

https://gist.github.com/iSTeeWx/6f34881697f1af3d333710cb9feccf4d

### Issue description

The game crashes when making runes due to the **progress indicator**
The crash is due to a OutOfMemoryError, and happens at "vazkii.botania.client.core.helper.RenderHelper.renderProgressPie(RenderHelper.java:362)"
```java
for (int i = degs; i >= 0; i--) {
	float rad = (i - 90) / 180F * (float) Math.PI;
	buf.vertex(mat, centerX + Mth.cos(rad) * r, centerY + Mth.sin(rad) * r, 0).color(0F, 1F, 0.5F, a).endVertex();
}
```

This code tries to make a buffer that is size MAX_INT + 1 (i believe)

### Steps to reproduce

1. Try to make runes
2. Succeed
3. Try to make more runes
4. Crash

### Other information

I allocated 25Gb of ram to the game, and the crash also occurred with 16Gb of ram.

**Comment by iSTeeWx** [comment]
EDIT: It seems I was wrong, looking at the crash report, I don't think it's a memory issue
Crash report: https://pastebin.com/vF1pgnkT

**Comment by TheRealWormbo** [comment]
This appears to work fine with just Botania and its dependencies, so it's probably a conflict with other mods in the pack. Could you try narrowing it down to a smaller set of mods?

**Comment by iSTeeWx** [comment]
The bug seems not to happen anymore. Sorry for bothering you.
