### ISSUE TITLE
Incompatible with Enhanced Celestials (again) [1.20.1] [Forge] 

### ISSUE THREAD

**Issue by LeakingAmps** [Vazkii/Botania#4607]
### Mod Loader

Forge

### Minecraft Version

1.20.1

### Botania version

1.20.1-433-FORGE

### Modloader version

Neoforge 47.1.101

### The latest.log file

https://paste.ee/p/kGR3n

### Issue description

While running with Enhanced Celestials and Mekanism, there is an unreliable crash.

Seems to be a reoccurrence of https://github.com/VazkiiMods/Botania/issues/3873 potentially? 

### Steps to reproduce

Load up Botania, Mekanism, and Enhanced Celestials (and dependencies)
Crash (sometimes)

### Other information

I have no idea why Mekanism is involved at all, and it's likely simply triggering the issue that the two mods have, rather than being directly responsible.

The crash is not reliable, and different computers seem to have different levels of success crashing or not crashing with this list.

I suspect the issue is actually on Enhanced Celestials' end, but thought I should report it anyways.

Reported here https://github.com/CorgiTaco/Enhanced-Celestials/issues/198

**Comment by festro** [comment]
Yeah getting this too, however however my crash log looks a bit different
log: 
[latest.log](https://github.com/VazkiiMods/Botania/files/15048013/latest.log)
crash:
[crash-2024-04-20_04.37.06-server.txt](https://github.com/VazkiiMods/Botania/files/15048014/crash-2024-04-20_04.37.06-server.txt)

**Comment by LeakingAmps** [comment]
That looks like a separate issue; your latest.log doesn't seem to be a crash-on-launch, which is what happens with Botania and Enhanced Celestials.

**Comment by festro** [comment]
Figured it was similar enough to not risk creating a duplicate issue, your right that mine is not a crash on launch, but looking at the crashlog both Botania and Enhanced Celestials were mentioned in the crash report.

**Comment by bitbloxhub** [comment]
I am also experiencing this issue, but with [FerriteCore](https://modrinth.com/mod/ferrite-core) instead of Mekanism.
