### ISSUE TITLE
Floating Flower render in Lexica Botanica clashes with Indium/Iris

### ISSUE THREAD

**Issue by Austoixist** [Vazkii/Botania#4613]
### Mod Loader

Fabric

### Minecraft Version

1.20.1

### Botania version

1.20.1-443

### Modloader version

Fabric - 0.15.10

### The latest.log file

https://pastebin.com/FTNHgra9

### Issue description

the crash is a rendering issue with iris/indium trying to render a floating flower inside the lexica botanica (patchouli book)

### Steps to reproduce

open the lexica botanica and go to a page with a multiblock that can contain a floating flower (ex: mana enchanter) and wait for it to try to render a floating flower

**Comment by Partonetrain** [comment]
With just Embeddium, the floating flowers don't render at all in the book preview or the in-world preview (but there's no crash). Probably a Patchouli problem.

**Comment by TheRealWormbo** [comment]
Same with just Indium and Sodium on Fabric, it's specifically an Iris-related issue in combination with Patchouli's multiblocks rendering Botania's floating flower model.

**Comment by TheRealWormbo** [comment]
Okay, I tried again, and can't get it to crash with the latest versions of Sodium+Indium+Iris.
However, semi-related to this, I found some outdated code in relation to floating flower rendering. Fixing those made the floating flowers show up in the book, but not for the in-world visualization yet.

**Comment by TheRealWormbo** [comment]
@xlgamer789 Does this still happen for you with Botania release 444? (Not counting the missing in-world rendering of floating flowers in the Mana Enchanter preview mentioned in #4181.)

**Comment by TheRealWormbo** [comment]
Assuming this is fixed or otherwise no longer an issue. Please reopen if it happens again or more information is available.
