### ISSUE TITLE
Mana spreader not collecting mana from thermalily

### ISSUE THREAD

**Issue by 61352151511** [Vazkii/Botania#464]
I'm not sure if I did something wrong or if something broke when it was moved to elven knowledge. The thermalily's have mana in them according to the wand of the forest, but the elven mana spreader is never collecting from them and putting it in the mana pool, it collects from all the day blooms however.

If I'm just being completely stupid and did something wrong, please tell me what it is :)

![2015-01-07_08 45 33](https://cloud.githubusercontent.com/assets/2399411/5645755/0affab06-964a-11e4-9311-a4a35f818b9c.png)

**Comment by 61352151511** [comment]
And apparently they needed to be manually bound (Which I don't remember having to do before) thanks Barhandar

**Comment by Vazkii** [comment]
It's possible they bound themselves to the one pointing to the rune altar.
