### ISSUE TITLE
crash with halo

### ISSUE THREAD

**Issue by XBlackLeopardX** [Vazkii/Botania#465]
I'm currently using the latest version of botania version 149
im also using the latest version of forge 1277
Im using the vanilla forge
I am not using optifine

I was trying to craft the unstable ingots from extra utilities (latest version of mod) and when you go to pull the ingot out of the crafting window it crashes the game it works in the vanilla crafting table but not the halo

crash log http://pastebin.com/2M8dvbzd

**Comment by Vazkii** [comment]
Interesting, the recipe doesn't match? That's odd. @RwTema: https://github.com/Vazkii/Botania/blob/master/src/main/java/vazkii/botania/common/item/ItemCraftingHalo.java#L288

**Comment by XBlackLeopardX** [comment]
it let me put the stuff in the table but when i went to pull out the unstable ingot i crashed instantly and the stuff dropped on the ground

**Comment by rwtema** [comment]
The recipe uses the java stacktrace to check that it was called from the ContainerWorkbench.class, otherwise it refuses to craft.

**Comment by Vazkii** [comment]
O.o
Well that's an odd one. I'll add a null check then.
