### ISSUE TITLE
Wing bar wont move for mount health

### ISSUE THREAD

**Issue by Acat1234** [Vazkii/Botania#4650]
### Mod Loader

Forge

### Minecraft Version

1.20.1

### Botania version

443

### Modloader version

47.2.32

### The latest.log file

Idk what this means

### Issue description

I have the wings so it shows wing bar but I then use a mount and the bar wont move

**Comment by TheRealWormbo** [comment]
As far as I can tell the bar moves up, but only by one row regardless of mount health. In other words it overlaps with the part of the bar that shows mount health beyond 10 saddles.

**Comment by Acat1234** [comment]
Yah it does
