### ISSUE TITLE
Visual bug with Manaseer

### ISSUE THREAD

**Issue by MrAyfan** [Vazkii/Botania#4651]
### Mod Loader

Forge

### Minecraft Version

1.20.1

### Botania version

Botania-1.20.1-444-FORGE

### Modloader version

Forge 47.2.20

### Modpack info

https://petitesetoiles.fr.nf/

### The latest.log file

https://pastebin.com/8NqMW7Hh

### Issue description

At 30M blocks away from spawn, there is a visual bug with the Manaseer Monocle

VIDEO: https://youtu.be/XSWk45dTQbg

### Steps to reproduce

1. Wearing the Manaseer Monocle
2. Pointing to a Functionnal Flower

### Other information

List of all mods we have in the modpack:

aether-1.20.1-1.4.2-neoforge.jar
alexsmobs-1.22.8.jar
amendments-1.20-1.1.30.jar
Aquaculture-1.20.1-2.5.1.jar
architectury-9.2.14-forge.jar
balm-forge-1.20.1-7.2.2.jar
BiomesOPlenty-1.20.1-18.0.0.592.jar
born_in_chaos_[Forge]1.20.1_1.2.jar
Botania-1.20.1-444-FORGE.jar
citadel-2.5.4-1.20.1.jar
corpse-forge-1.20.1-1.0.12.jar
cosmeticarmorreworked-1.20.1-v1a.jar
CraftTweaker-forge-1.20.1-14.0.38.jar
CreativeCore_FORGE_v2.11.28_mc1.20.1.jar
cristellib-1.1.5-forge.jar
Croptopia-1.20.1-FORGE-2.3.2.jar
CroptopiaAdditions-1.20.1-FORGE-2.3.jar
curios-forge-5.9.0+1.20.1.jar
drippyloadingscreen_forge_3.0.1_MC_1.20.1.jar
EasierSleeping-1.20.1-2.1.3.jar
elevatorid-1.20.1-lex-1.9.jar
embeddium-0.3.19+mc1.20.1-all.jar
emotecraft-for-MC1.20.1-2.2.7-b.build.50-forge.jar
EpheroLib-1.20.1-FORGE-1.2.0.jar
fancymenu_forge_3.2.3_MC_1.20.1.jar
ferritecore-6.0.1-forge.jar
framework-forge-1.20.1-0.6.27.jar
ftb-essentials-forge-2001.2.2.jar
ftb-library-forge-2001.1.5.jar
ftb-ranks-forge-2001.1.3.jar
geckolib-forge-1.20.1-4.4.4.jar
goblintraders-forge-1.20.1-1.9.3.jar
handcrafted-forge-1.20.1-3.0.6.jar
hiddennames-1.20.1-1.0.3.jar
InventoryProfilesNext-forge-1.20-1.10.10.jar
ironchest-1.20.1-14.4.4.jar
item-filters-forge-2001.1.0-build.59.jar
Jade-1.20.1-forge-11.8.0.jar
jei-1.20.1-forge-15.3.0.4.jar
journeymap-1.20.1-5.9.21-forge.jar
konkrete_forge_1.8.0_MC_1.20-1.20.1.jar
kotlinforforge-4.10.0-all.jar
libIPN-forge-1.20-4.0.2.jar
LuckPerms-Forge-5.4.102.jar
mcw-furniture-3.2.2-mc1.20.1forge.jar
melody_forge_1.0.3_MC_1.20.1-1.20.4.jar
modernfix-forge-5.17.0+mc1.20.1.jar
moonlight-1.20-2.11.22-forge.jar
morevillagers-forge-1.20.1-5.0.0.jar
NaturesCompass-1.20.1-1.11.2-forge.jar
oculus-mc1.20.1-1.7.0.jar
Paraglider-forge-20.1.3.jar
Patchouli-1.20.1-84-FORGE.jar
player-animation-lib-forge-1.0.2-rc1+1.20.jar
resourcefullib-forge-1.20.1-2.1.24.jar
SimpleBackups-1.20.1-3.1.4.jar
sophisticatedbackpacks-1.20.1-3.20.5.1044.jar
sophisticatedcore-1.20.1-0.6.22.611.jar
supplementaries-1.20-2.8.11.jar
TerraBlender-forge-1.20.1-3.0.1.6.jar
 Towns-and-Towers-1.12-Fabric+Forge.jar
Twigs-1.20.1-3.1.0.jar
twilightforest-1.20.1-4.3.2145-universal.jar
waterframes-1.20.1-2.0.7.jar
watermedia-2.0.53.jar
waystones-forge-1.20-14.1.3.jar
WI-Zoom-1.5-MC1.20.1-Forge.jar
yawp-1.20.1-0.0.2.9-beta3-forge.jar

**Comment by TheRealWormbo** [comment]
I think I see what might be causing this. The "pose stack" is first being translated by the negative flower position, then back by one corner of the area to render. Since the pose stack translation is being handled as 32 bit floating point, it's subject to severe rounding errors in the process.
We should probably refactor that logic to instead translate the area description, because that one uses integer and 64 bit floating point values. That way the rendering operations use reasonably small numbers, even near the default world border.
