### ISSUE TITLE
[Request] MineTweaker Support

### ISSUE THREAD

**Issue by UndeadZeratul** [Vazkii/Botania#466]
I'm aware Modtweaker currently adds support, but @joshiejack has stopped working on it a while ago.  I don't know his policies on giving you the code to integrate it with Botania, but I saw Blood Magic now has the classes from ModTweaker, and they're credited to Josh. [Here's](https://github.com/joshiejack/ModTweaker/tree/master/src/main/java/modtweaker/mods/botania) the classes you'd need to implement in order to get it working.

**Comment by Barhandar** [comment]
Would be rather awesome.

What would also be awesome is ability to drain mana when crafting, for things like using Rod of the Seas to fill buckets and bottles in inventory.

**Comment by Vazkii** [comment]
I don't want to do this as I'd have to actively support it.
