### ISSUE TITLE
Gradle plugin not found

### ISSUE THREAD

**Issue by NEstoll** [Vazkii/Botania#4664]
### Mod Loader

Both Fabric and Forge (I confirm that I have tested both loaders and will specify both loader versions below)

### Minecraft Version

N/A

### Botania version

1.20.1-445

### Modloader version

N/A

### The latest.log file

N/A

### Issue description

Gradle build fails with the following error.
```
FAILURE: Build failed with an exception.

* Where:
Build file '/home/estolln/documents/Botania/Xplat/build.gradle' line: 3

* What went wrong:
Plugin [id: 'org.spongepowered.gradle.vanilla', version: '0.2.1-SNAPSHOT'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'org.spongepowered.gradle.vanilla:org.spongepowered.gradle.vanilla.gradle.plugin:0.2.1-SNAPSHOT')
  Searched in the following repositories:
    Fabric(https://maven.fabricmc.net/)
    QuiltFlower(https://server.bbkr.space/artifactory/libs-release/)
    Gradle Central Plugin Repository
    Sponge Snapshots(https://repo.spongepowered.org/repository/maven-public/)
```
This happens despite it clearly being available: https://repo.spongepowered.org/#browse/browse:maven-public:org%2Fspongepowered%2Fgradle%2Fvanilla%2Forg.spongepowered.gradle.vanilla.gradle.plugin
I've attached the gradle logs where the error happens [here](https://github.com/user-attachments/files/15570353/gradle.log)

### Steps to reproduce

Clone Botania repository
Run ./gradlew
See above error

### Other information

Computer is running Linux (RHEL 8)
Build fails identically when built via command line (./gradlew) and through Intellij
Gradle version is 8.1.1

**Comment by TheRealWormbo** [comment]
I'm not sure why you keep running into that. Then again, maybe we shouldn't depend on a snapshot dependency.

[edit] Williewillus pointed out the snapshot issue to the VanillaGradle folks last year already, no news since then: https://github.com/SpongePowered/VanillaGradle/issues/106

**Comment by TheRealWormbo** [comment]
For the record, two things have happened in this regard, even though they are probably not directly related to the issue encountered here:
- We [updated some dependencies](https://github.com/VazkiiMods/Botania/commit/99c660e929260395348fde4b1920af53a2f04c77) to fix a problem with Xplat no longer compiling after a recent VanillaGradle change. It may be necessary rebasing local feature branches onto at least that change in the 1.20.x branch to be able to compile them.
- We are currently looking into how viable it is to drop VanillaGradle entirely and instead [compile Xplat with the help of "minivan"](https://github.com/VazkiiMods/Botania/pull/4684).

**Comment by TheRealWormbo** [comment]
This should no longer be happening, as we switched to minivan and can use non-snapshot versions for all parts of the build.
