### ISSUE TITLE
Suspicious stew made with Pure Daisy didn't clear effects on player.

### ISSUE THREAD

**Issue by yappy2000d** [Vazkii/Botania#4674]
### Mod Loader

Both Fabric and Forge (I confirm that I have tested both loaders and will specify both loader versions below)

### Minecraft Version

1.20.1

### Botania version

1.20.1-444

### Modloader version

Forge: 47.3.1

### The latest.log file

https://pastebin.com/vp2YFCtT

### Issue description

Make suspicious stew with Pure Daisy. It didn't clears effects on player after using.

### Steps to reproduce

1. drink any potion.
2. eat suspicious stew made with Pure Daisy.

**Comment by anoomolu** [comment]
Can confirm this on Fabric as well - the absolution effect pops up briefly but doesn't clear existing effects, unlike the brew version.

**Comment by TheRealWormbo** [comment]
Apparently suspicious stew does not support instant effects, at least not in 1.20.1.
