### ISSUE TITLE
Crashes upon entering the Nether

### ISSUE THREAD

**Issue by QianFuv** [Vazkii/Botania#4675]
### Mod Loader

Forge

### Minecraft Version

1.19.2

### Botania version

1.19.2-440

### Modloader version

43.3.13

### The latest.log file

https://mclo.gs/f1aQrND

### Issue description

Crashes upon entering the Nether

### Steps to reproduce

It happens suddenly, and it can't be reproduced

**Comment by TheRealWormbo** [comment]
The code this crashes in should not actually be able to crash, unless some other mod changed how a particular player inventory lookup works.

You will need to provide some kind of reproduction case, as we don't have the time to sift through unclear mod compatibility issues on older versions.

**Comment by QianFuv** [comment]
Your response mentioned that the cause of this crash was due to other mods changing the way players search for inventory. In order to locate the problem more quickly, could you provide some known mods or related code that have changed the way players search for inventory?

**Comment by TheRealWormbo** [comment]
If I knew, I would have mentioned. I can only tell that the method it crashes in shouldn't be able to crash in the way it did, unless `PlayerHelper.getFirstHeldItemClass(player, AssemblyHaloItem.class)` returned a non-empty stack that is not actually of an item that extends the `AssemblyHaloItem` class. It has no way of doing that, unless some other mod broke that piece of vanilla logic.
The other (less likely) option is that some mod messed with the way NBT data is extracted from item stack objects, causing the stack to become empty, or worse – change its item type at a time it should absolutely never change.

**Comment by QianFuv** [comment]
Thank you for your reply! I will continue to pay attention to this issue, as this crash is the first time I have encountered it in a year of developing modpack. If similar situations continue to occur in the future, I will continue to collect relevant information.

**Comment by TheRealWormbo** [comment]
Will close this for now. Feel free to reopen if it happens again and you have more information.
