### ISSUE TITLE
crash when trying to put a block from gregtech next to the stove

### ISSUE THREAD

**Issue by ghost** [Vazkii/Botania#4692]
### Mod Loader

Forge

### Minecraft Version

1.20.1

### Botania version

1.20.1-444

### Modloader version

Forge:47.3.0

### The latest.log file

https://gist.github.com/ZET125132/08cc141f595961b09efde593c03f8385

### Issue description

crash when trying to put a block from gregtech next to the stove

### Steps to reproduce

Uploading Base Profile 2024.06.25 - 23.02.43.09.mp4…

### Other information

crash related to another mechanism
https://gist.github.com/ZET125132/4db4f40edd0d7a9d788e76b29bdc021e

**Comment by ghost** [comment]
https://youtu.be/_tOFx5hPMPM

**Comment by ghost** [comment]
latest.log
https://gist.github.com/ZET125132/1ce7deaef421e47c168ecc5b5b9b8374

**Comment by TheRealWormbo** [comment]
Not an issue specifically in Botania code. Please report to GregTechCEu (their `MetaMachineBlock` seems to do something funky) and maybe also Patchouli (this happens in its multiblock validation code), although I assume GregTech is doing something wrong.
