### ISSUE TITLE
Botania incompatibility with BedrockIfy

### ISSUE THREAD

**Issue by VeriSerp** [Vazkii/Botania#4697]
### Mod Loader

Fabric

### Minecraft Version

1.20.1

### Botania version

1.20.1-444

### Modloader version

 Fabric loader version: 0.15.11+ API 0.92.2

### The latest.log file

https://mclo.gs/xGP9A0N / https://mclo.gs/kGy82SI

### Issue description

Upon trying to launch game with both the latest versions of Botania and Create for 1.20.1 Fabric (Create 1.20.1 v0.5.1.f Patch 1), i get booted back to launcher after a while with a crash report.

### Steps to reproduce

1. Install Create 1.20.1 v0.5.1.f Patch 1 and Botania 1.20.1-444-fabric with dependencies
2. Open Launcher
3. Click Play
4. Crash

### Other information

Loading my mods without both enables it to load into main menu normally.

**Comment by TheRealWormbo** [comment]
Please also report to PortingLib, as it's not the first time (see #4614) that library is messing with the things we have already done before it existed.

**Comment by Poopooracoocoo** [comment]
Unable to reproduce with only Create Fabric and Botania. This must be Botania's incompatibility with Bedrockify #4516

**Comment by NolanHewitt** [comment]
> Unable to reproduce with only Create Fabric and Botania. This must be Botania's incompatibility with Bedrockify #4516

I don't use bedrockify and can replicate the issue.

**Comment by TheRealWormbo** [comment]
@Poopooracoocoo - For future reference, commenting on closed issues by other people has a high chance of going unnoticed. You should have opened a new issue back then already.
