### ISSUE TITLE
Duplication glitch with Thermal Expansion and Botania

### ISSUE THREAD

**Issue by IBeRamen** [Vazkii/Botania#470]
If you use a Terra Pick (From Botania) in hammer mode and break a block next to any type of TE Strongbox/Tank it will drop a creative tank and a creative strongbox.

Thermal Expansion Version: 1.7.10 4.0.0 B8-23
CoFHCore Version: 3.0.0B9-40
CoFHLib Version: 1.0.0B8-34
RedstoneArsenal Version: 1.1.0RC1-19
Botania Version: r1.3-145

**Comment by IBeRamen** [comment]
I have also reported this bug to Thermal Expansion.

**Comment by Vazkii** [comment]
Will await for some feedback from their end before looking too much into this, as TE is closed source.

**Comment by skyboy** [comment]
https://github.com/Vazkii/Botania/blob/master/src/main/java/vazkii/botania/common/item/equipment/tool/ToolCommons.java#L78-84
These calls are out-of-order compared to how vanilla calls them, and the check above for != 0 should be > 0 (< 0 means unbreakable, like bedrock; 0 is insta-break).
Comparison implementation: https://github.com/SlimeKnights/TinkersConstruct/blob/master/src/main/java/tconstruct/library/tools/HarvestTool.java#L252

**Comment by Vazkii** [comment]
Sounds good, will fix then.
