### ISSUE TITLE
Witchery + Botania: make item-eating flowers be able to accept items from Grasspers

### ISSUE THREAD

**Issue by Barhandar** [Vazkii/Botania#471]
Items in Grasspers aren't items in world, so they're not laggy on the server. Possibly a compatibility config option that defaults to off, so that people experience `<sarcasm>`glorious in-world dropping of hundreds of items*`</sarcasm>` first.

*I don't have issue with it, but many apparently do, with it not working or working badly.

On the non-flora side of the suggestion, there's TC4's Arcane Pedestals, which could've used for that as well.

**Comment by Vazkii** [comment]
No, I have no intention of doing this, I like the item movement mechanic. I understand that it can cause lag on large servers, but I'm not going to deliberately dumb down the mod just to allow hundreds of people to play at once.

**Comment by Barhandar** [comment]
@Vazkii 
Lag on large servers, gets blocked from working by any Magnetism effect or area item pickup nearby, causes everyone to just slap down Thermalilies which you grump on.
