### ISSUE TITLE
Mana spread accumulate but do not spread mana

### ISSUE THREAD

**Issue by Colluttorio** [Vazkii/Botania#4711]
### Mod Loader

Forge

### Minecraft Version

1.20.1

### Botania version

1.20.1-445-FORGE

### Modloader version

FORGE

### Modpack info

47.3.1

### The latest.log file

https://gist.github.com/Colluttorio/62d3cf763a99d5f01f1f4efb93ab8698

### Issue description

With last update, the mana spreader don't push mana into mana pool
![immagine](https://github.com/VazkiiMods/Botania/assets/63145139/db8dcb12-f669-4d09-978a-38e8e80a7cc7)
![immagine](https://github.com/VazkiiMods/Botania/assets/63145139/7aad6591-6bba-473c-bc0d-c3d110ada48e)

### Steps to reproduce

1. Place a mana spread
2. Place mana pool
3. Connect mana spread with mana pool
4. Give mana spread mana
5. It accumulate mana but not spread it

**Comment by TheRealWormbo** [comment]
Do you have anything nearby that affects projectiles, like Interdiction Torches or similar protective measures?

**Comment by Colluttorio** [comment]
No, nothing. I haven't placed nothing else. I could try to rollback version and check if it work with the same configuration.

Edit: no, with rollback mana spreader continue to not work. 
The list of my mods is: https://gist.github.com/Colluttorio/da99a8e78cc1141ac73d6796989884a9
These instead are the last mods that i have updated:
![immagine](https://github.com/VazkiiMods/Botania/assets/63145139/22b8705d-708f-4f07-b6d3-dc0441f8878e)
Before of these, if i remember correctly all works fine. I continue to try to do a troubleshooting to help to resolve the issue.

**Comment by Colluttorio** [comment]
I don't know if this can help you. 
![immagine](https://github.com/VazkiiMods/Botania/assets/63145139/1fd95d75-a3fa-4ac2-857d-119ad61d8b27)
I have also tried to force the spawn of Pillagers and they shot and hit me easily

EDIT:

This morning, using the previous version (444), placing down a new mana spread and connect with an existen endoflame, it work fine
![immagine](https://github.com/VazkiiMods/Botania/assets/63145139/a51a06ae-dcda-4086-8646-de41bad70579)
So, i closed the game and applied 445. Restart the game and now also the previous mana spread have started working again.
![immagine](https://github.com/VazkiiMods/Botania/assets/63145139/a080f707-6583-4360-96a7-c6f55575ebd8)

What have i changed? The claim of the chunk (that is also the same mod that i have updated recently).
Leaving the claim and rebooting the game, all work fine. Thanks for help

**Comment by TheRealWormbo** [comment]
Thanks for the information. So it was an over-eager chunk protection feature.

**Comment by PlemGitHub** [comment]
I'm happy I found this thread about the same issue I've met in-game. Mana from the Mana Spread doesn't flow to the Pool.
The issue is caused by the Open‑parties‑and‑claims‑forge‑1.20.1‑0.25.8 mod
When I unclaim the chunk, the Mana immediately starts flowing.

<img width="1353" height="570" alt="Image" src="https://github.com/user-attachments/assets/5077501a-6c00-4425-b5d4-44c49db55b0e" />

**Comment by TheRealWormbo** [comment]
There is nothing we can do about Open Parties and Claims being way too strict with unowned projectiles by default.

**Comment by PlemGitHub** [comment]
I wrote more to the players who stuck with the problem and don't know what to do.

**Comment by thexaero** [comment]
@TheRealWormbo The server owners can add an exception in OPAC's config if they want the option of getting claims griefed. You can even configure it to let players toggle it per sub-claim. Considering how rare such a compatibility issue really is, I don't agree that choosing protection by default is too strict. I pretty much only hear about Botania. I've tried both approaches. Most unowned projectiles from mods cause a lot of destruction. Projectiles in general tend to do some type of damage. Botania isn't even really different in that regard. And there are other reported compatibility issues where Botania just lets people circumvent protection by default. Nothing really unusual here for a complex mod like Botania.
So our mods need explicit support for each other, there's no way around it. This can be implemented on either end. To be honest, it's much easier to do on Botania's as that's where the protection checks would have to go, and you guys already know Botania's codebase and mechanics and it's easier to work with it directly. So, technically, there is something you could do, if you REALLY wanted to, but I'm not here to force you to do anything of course. I am planning to add support for Botania myself in the future, if you don't do it by then. It is not my top priority atm though.
