### ISSUE TITLE
The interface in the flower bag has moved out

### ISSUE THREAD

**Issue by Mifr1l3551** [Vazkii/Botania#4713]
### Mod Loader

Forge

### Minecraft Version

1.20.1

### Botania version

(1.20.1-444-FORGE-SNAPSHOT)

### Modloader version

Forge 47.2.1

### Modpack info

N/A

### The latest.log file

N/A

### Issue description

The interface has moved out of the botany flower bag, most likely due to the fact that it also has large (2 blocky) flowers

![image](https://github.com/VazkiiMods/Botania/assets/166610642/bb294d86-a9ce-49c0-81fa-fb8ae6bc0610)

### Steps to reproduce

Open Flower bag

**Comment by TheRealWormbo** [comment]
Check your resource packs. You may have something that attempts to replace the UI background with an older version.

[edit]
Also, please do not report old **snapshot** versions. They are very unsupported and not meant for public use.
