### ISSUE TITLE
Mana Tablet draining infinitely with tetra manasteel items

### ISSUE THREAD

**Issue by itszenergy** [Vazkii/Botania#4720]
### Mod Loader

Forge

### Minecraft Version

1.20.1

### Botania version

1.20.1-445-FORGE

### Modloader version

Forge 47.3.5

### Modpack info

Valhelsia 6

### The latest.log file

https://gist.github.com/itszenergy/519a506de4e2c918c965f64f9e80eb0f

### Issue description

Full mana tablet draining to zero in a few minutes when holding tetra manasteel items.

### Steps to reproduce

1. Have mana tablet with mana in
2. Pick up tetra mana steel item (durability seems to be stuck 1 below max, not sure if relevant)
3. Watch your mana pool drain to zero

**Comment by TheRealWormbo** [comment]
If this is a Tetra-based item, you will need to report it to them. Mana consumption in your inventory is a "pull" operation, i.e. the item consuming the mana is responsible for requesting and doing something with it – or not consuming it when it can't do anything with it.

**Comment by TheRealWormbo** [comment]
Closing this issue. The bug is tracked as mickelus/tetra#757, and there's nothing Botania itself could do about it, unless you can show that it also affects Botania's own tool repair.
