### ISSUE TITLE
Terra Shatterer and Bore lense breaking protected blocks

### ISSUE THREAD

**Issue by LemADEC** [Vazkii/Botania#473]
Terra shatterer and Bore lense can be used to break into protected area (spawn, WorldGuard, etc.).
As tested with Botania-r1.3-148.jar

**Comment by Vazkii** [comment]
Not a forge issue so I'm not fixing it.

**Comment by LemADEC** [comment]
Spawn protection is vanilla, just saying...

**Comment by Vazkii** [comment]
Ah, yeah, you're right, I forgot that. I'll have a look then.
