### ISSUE TITLE
Belt are not worn in Baubles slots

### ISSUE THREAD

**Issue by MrLeonardosMi** [Vazkii/Botania#4730]
### Mod Loader

Forge

### Minecraft Version

1.20.1

### Botania version

1.20.1-444

### Modloader version

(any)

### The latest.log file

(n/a)

### Issue description

Pilgrim's Belt and Speed Belt should be worn in the Baubles ‘belt’ slot, but this cannot be done.

### Other information

'botania:super_travel_belt' - Pilgrim's Belt
'botania:speed_up_belt' - Speed Belt

**Comment by TheRealWormbo** [comment]
Works fine with Botania 445 on Forge alone:
![Sojourner's Sash](https://github.com/user-attachments/assets/dd18325e-b6eb-4b11-a69f-1f3c46cbf34a)
![Globetrotter's Sash](https://github.com/user-attachments/assets/c5003c66-a5d0-4239-805d-8b1bf8477c1b)
![Planestrider's Sash](https://github.com/user-attachments/assets/f6e8793a-c6ac-4590-96d5-afd82220a727)

You will need to provide more information on what exactly doesn't work for you.

**Comment by TheRealWormbo** [comment]
Presumably a compatibility issue with some other mod or the mod pack messing up item tags. Closing as it's unlikely to be something we can fix.
