### ISSUE TITLE
Problems with vacuum chest and redstone pipes

### ISSUE THREAD

**Issue by MrLeonardosMi** [Vazkii/Botania#4731]
### Mod Loader

Forge

### Minecraft Version

1.20.1

### Botania version

1.20.1-444

### Modloader version

(any)

### The latest.log file

(n/a)

### Issue description

When the vacuum chest is connected to the redstone pipe, it continues to draw in items, but they remain invisible and cannot be picked up or viewed. However, if you switch the operation mode of the chest using the redstone pipe to the original mode, the ‘invisible’ items become available. Also, if you break the vacuum chest, the ‘invisible’ items will fall out and can be picked up.

### Other information

‘enderio:vacuum_chest’ - Vacuum chest
‘enderio:redstone_conduit’ - Redstone pipe

![image](https://github.com/user-attachments/assets/2560f3dd-2e2e-4b63-ba7f-97ee051f2687)
![image](https://github.com/user-attachments/assets/602b504c-3679-4348-aac4-4d6ea4d727b0)
![image](https://github.com/user-attachments/assets/5f713c3a-7439-401c-805e-52a3975e1e17)

**Comment by TheRealWormbo** [comment]
Those links don't work and you have nod provided any information that would help identifying which mods are involved or even present.

**Comment by MrLeonardosMi** [comment]
Oh, apologies, wrong repository. All good (
