### ISSUE TITLE
Random Crash on Startup due to the moon

### ISSUE THREAD

**Issue by ScoutTheSaneless** [Vazkii/Botania#4733]
### Mod Loader

Forge

### Minecraft Version

1.20.1

### Botania version

1.20.1-v445

### Modloader version

NeoForge 47.1.106

### The latest.log file

https://gist.github.com/ChaosDogG/aaf86562d12d38eb3a219206d714555d

### Issue description

Whenever I try to boot my pack, I can't seem to get it to just boot up. The game just screams at me and doesn't expressly tell me what the issue is. I try uninstalling mods and it throws a fit and I install new mods and it throws a fit. If I need to head somewhere else, please let me know where I need to be, because this issue is very vexing

### Steps to reproduce

1. attempt to boot the game
2. watch as it crumbles and yells at me

### Other information

my only other thought would be Enhanced Celestials, but I was able to get it to boot w it also installed before, so something is wrong here

**Comment by TheRealWormbo** [comment]
There is a known compatibility issue between Botania and either BedrockIfy or Enhanced Celestials that *should* be fixed in the upcoming 446 release of Botania. I'm a bit surprised that even worked for you at some point.

**Comment by ScoutTheSaneless** [comment]
Given that it's a known issue, then I am too, but honestly, I didn't think too much of it at the time. Is there an ETA for the release, cuz I use EC for onenof my Cobblemon addons and I do like me some Botania. I don't mean to sound too rush-y I just wanna know if I should expect it soon or if I shouldn't hold my breath for a while.

**Comment by ScoutTheSaneless** [comment]
I found the commit and the other issue created ~~making this a dupe, my bad for not checking closed reports-~~ Glad to see a fix coming soon anyhow!

**Comment by TheRealWormbo** [comment]
Closing as duplicate now, since the fix is released.
