### ISSUE TITLE
Drum of the Gathering egg feature isn't documented

### ISSUE THREAD

**Issue by anoomolu** [Vazkii/Botania#4737]
### Mod Loader

Both Fabric and Forge (I confirm that I have tested both loaders and will specify both loader versions below)

### Minecraft Version

1.20.1

### Botania version

1.20.1-446

### Modloader version

Forge 47.2.0 / Fabric Loader 0.15.0, API 0.91.0

### The latest.log file

n/a

### Issue description

The recent addition of time until next egg being lowered by the drum of the gathering isn't documented in the lexicon, which doesn't seem right given how useful it is for kekimurus automation.

**Comment by TheRealWormbo** [comment]
That page also doesn't mention mooshrooms. I don't think the entire mushroom stew and suspicious stew mechanic needs to be explained, players may figure it out just from mooshrooms being name-dropped.
