### ISSUE TITLE
Crashing server 

### ISSUE THREAD

**Issue by oskarbukovsky** [Vazkii/Botania#4738]
### Mod Loader

Forge

### Minecraft Version

1.20.1

### Botania version

1.20.1-446-FORGE

### Modloader version

Forge 47.3.5

### Modpack info

https://www.curseforge.com/minecraft/modpacks/tech-craft-neobox

### The latest.log file

https://gist.github.com/oskarbukovsky/590bb1f366f608964cdc310e5479115d

### Issue description

When starting server, it crashes

### Other information
Edit: Upload debug.log
https://gist.github.com/oskarbukovsky/e1573943e6146c801ed9187cafc7ba0c

_No response_

**Comment by TheRealWormbo** [comment]
From the log my first impression is that "mohistmc" (I assume that's some kind of server software, since it's referencing Bukkit and Spigot?) is calling things it shouldn't be calling at the time it does, because things are not ready yet. You may want to report this crash to them.

**Comment by oskarbukovsky** [comment]
Ok, i downgaded mohist (it's software that allow running mods on forge/neoforge with plugin support) and server manage to boot, things are half working for now, but better than fully offline. I'll try to make issue on their page. My first though was mod issue as it was in log

**Comment by TheRealWormbo** [comment]
I'm going to assume there are no further actions for us here, so closing this issue for now.
