### ISSUE TITLE
i dont really know if its a issue

### ISSUE THREAD

**Issue by Ultratoster** [Vazkii/Botania#4744]
### Mod Loader

Forge

### Minecraft Version

1.20.1

### Botania version

1.20.1 446

### Modloader version

forge 47.3.0

### The latest.log file

https://gist.github.com/ff386b5ac487661ba491ad18dd900498.git

### Issue description

why is flare lens removing damaging lens effect, idk if it is a issue, but looks like it to me, i was trying to make railgun, but i wasnt able to have colored and damaging lens at once wchich made me mad and now im here writing this

### Steps to reproduce

idk what to write here

### Other information

it might be vault of the fact that i have mods like: create, clockwork, valkyrien skies, modern fix, embeddium, eureka for valkyrien skies, refined storage, kotlin for forge, and ferrite core

**Comment by anoomolu** [comment]
All you need to do to colour your lenses is craft the lens with the appropriate dye like so:
![image](https://github.com/user-attachments/assets/0db32ba9-cc41-42ec-91b2-4765e2948e31)

The Flare lens is a type of control lens, preventing spreaders from firing bursts, basically stopping the damaging lens from functioning properly. The Lexicon should have all the info you're looking for.

**Comment by TheRealWormbo** [comment]
As mentioned above, the flare lens is not for changing color, but for converting a spreader into a decorative particle spawner. Use dyes to change the color of your mana bursts.
