### ISSUE TITLE
Terra Shatterer AoE mines out shovel-tool blocks, but Terra Shatterer itself isn't working as shovel

### ISSUE THREAD

**Issue by Barhandar** [Vazkii/Botania#475]

**Comment by Vazkii** [comment]
#476

**Comment by Barhandar** [comment]
Was running 149, though, with complaint being "why is it not a shovel as well as a pickaxe if it can AoE-mine shovel blocks".

**Comment by Vazkii** [comment]
It can mine out shovel blocks so they don't get in your way while running through holes, but you should still keep a shovel on you.
