### ISSUE TITLE
Floating Hopperhock ignores modulating delay after Petal Apothecary craft

### ISSUE THREAD

**Issue by Yadokingu** [Vazkii/Botania#4753]
### Mod Loader

Forge

### Minecraft Version

1.20.1

### Botania version

1.20.1-446-FORGE

### Modloader version

Forge 47.3.7

### Modpack info

ATM9

### The latest.log file

https://pastebin.com/raw/tpabtiBu

### Issue description

I have a floating Hopperhock, that I turned into the mycelium-version with Infestation Spores, covering most of my Botania area. However, I want results from my Petal Apothecary to be picked up by an unmodified floating Hopperhock Petite next to the Apothecary. But the crafting-result from the Apothecary gets sucked up almost immediatly by the big, floating, mycelium Hopperhock.
It should be noted that replacing the big, floating, infested Hopperhock with a normal Hopperhock on a mycelium block makes the delay work as expected, where the small floating Hopperhock next to the Apothecary is always picking up the crafting result.

### Steps to reproduce

1. Place a Petal Apothecary
2. Place a big, infestation spored, floating Hopperhock with a chest in the vicinity.
3. Place a normal, floating Hopperhock Petite with a chest next to the Apothecary
4. Craft something in the Apothecary
5. See where the output goes

**Comment by TheRealWormbo** [comment]
Flower delay did not have any effect in e.g. the 1.12 versions of Botania either, but it probably makes sense to be able to prioritize flowers for picking up crafting results. Marking this as a potential enhancement.

**Comment by Yadokingu** [comment]
If this function isn't intended, then the Lexica entry on modulating delay is very imprecise, since it mentions no exception for crafting results. So maybe that should be changed? Of course the far better solution would be to add the functionality, like you suggested. :)

**Comment by artemisSystem** [comment]
Closed in https://github.com/VazkiiMods/Botania/commit/07612688a8e0d3d91f3567e9128b32c39f8355e6
