### ISSUE TITLE
Halloween easter egg inconsistency

### ISSUE THREAD

**Issue by anoomolu** [Vazkii/Botania#4756]
### Mod Loader

Fabric

### Minecraft Version

1.20.1

### Botania version

1.20.1-446

### Modloader version

Fabric Loader 0.16.2, API 0.92.2

### The latest.log file

n/a

### Issue description

Hiya. There's an inconsistency in Halloween easter egg textures/models between the Tiny Potato and Teru Teru Bozu, and I'm unsure which one has the intended behaviour. Images are attached below.

When held, the Tiny Potato model doesn't match that of the placed tater which has the Halloween texture, while the Teru Teru Bozu does. Either the tater should have the Halloween texture when held in hand too, or the Teru shouldn't. 

Tater children and LGBTQ+ taters lack the halloween texture too, but strangely the shiny ones don't.

![image](https://github.com/user-attachments/assets/ea8667db-2238-464c-b402-9c300bf13a16)
![image](https://github.com/user-attachments/assets/cfe3f550-6ffe-402a-8e7f-a20f88d8e077)

**Comment by TheRealWormbo** [comment]
The face on the tater is baked into the texture. We'd need a Halloween version of each of those as well to properly display the spooky face on them. I'd say that's a non-issue for now.

As far as the difference in default display texture goes, I'm not quite sure why the Teru Teru Bozu properly changes texture in item form, while the tater does not, considering it properly applies name-based changes. IMHO the Halloween easter egg should apply to its item form as well, as rendered in hand or when held by a placed tater.

**Comment by anoomolu** [comment]
I imagine the minecraft:condition item model type introduced in 24w46a will come in useful here in the future.

**Comment by TheRealWormbo** [comment]
Probably, but since that's a 1.21.4+ change, it's still two major-ish versions beyond what our porting efforts currently target.
