### ISSUE TITLE
Benevolent Goddess' Charm and Charm of the Diva don't work

### ISSUE THREAD

**Issue by eugene418** [Vazkii/Botania#4759]
### Mod Loader

Fabric

### Minecraft Version

1.20.1

### Botania version

1.20.1-446

### Modloader version

Fabric Loader 0.16.5 + API 0.92.2

### The latest.log file

n/a

### Issue description

Benevolent Goddess' Charm and Charm of the Diva don't work at all.
I had an item supplying mana in my inventory.
I put them on the trinket slot.
I tested them without other mods.

**Comment by TheRealWormbo** [comment]
Looks like Leo was faster: #4758 and #4757

Since having two issues for likely separate bugs is better, I'll close this one as duplicate.
