### ISSUE TITLE
solo or server crash when user equip items

### ISSUE THREAD

**Issue by oddvans** [Vazkii/Botania#4763]
### Mod Loader

Forge

### Minecraft Version

1.20.1

### Botania version

Botania-1.20.1-446-FORGE

### Modloader version

Forge 47.3.11

### Modpack info

Homemade modpack, mods list in the crashlog

### The latest.log file

https://gist.github.com/oddvans/c8c6eb1f8ab9bf5213aff0aab659007b

### Issue description

Hi, (English is not my native language, excuse me by advance)
Since i'm not sure if this crash is related to Botania, Curios API or The Aether, do you think i have to post an issue on both ?
When a player try to equip some multiples items, in my case `botaniacosmetic_botanist_emblem`,`aether:golden_ring`,`botania:cosmetic_eyepatch` the server (or game if in local) imediatly crash (see crashlog).
it appear to be when you equip items that may go in the Curio slot, in certain order or with different methods (right clicking or manualy)

Equip manualy -> open menu, drag and drop the item
Equip right clicking -> right click with the item on hand 

Exemple 1 : 
equip any methods `botania:cosmetic_botanist_emblem`
equip any methods `botania:cosmetic_eyepatch`
equip manualy `aether:golden_ring` (Curio slot 1 or 2)
Result exemple 1 : item replaced without problem.

Exemple 2 : 
equip any methods `botania:cosmetic_botanist_emblem`
equip any methods `botania:cosmetic_eyepatch`
equip right clicking `aether:golden_ring`
Result exemple 2 : `aether:golden_ring` disapear without being equiped or replacing previously equiped items

Exemple 3 : 
equip any methods `aether:golden_ring`
equip any methods `botania:cosmetic_eyepatch` or `botania:cosmetic_botanist_emblem`
equip right clicking `botania:cosmetic_eyepatch` or `botania:cosmetic_botanist_emblem`
Result exemple 3: Game crash.

it may work with different items than the ones i have used in my exemple, i havent tested others combinaisons, in my case `aether:golden_ring` is always implicated.

### Steps to reproduce

equip any methods `aether:golden_ring`
equip any methods `botania:cosmetic_eyepatch` or `botania:cosmetic_botanist_emblem`
equip right clicking `botania:cosmetic_eyepatch` or `botania:cosmetic_botanist_emblem`

### Other information

I havent tested with others items from the listed ones.

**Comment by anoomolu** [comment]
The crashlog mentions Botanic Pledge, which I assume is a Botania addon. Could you disable the mod and see if you can still cause the crash to happen?

**Comment by oddvans** [comment]
Thx for the anwser,
The bug no longer exist when `Botanic Pledge` is removed from the game.
I will report the issue in the Botanic Pledge GitHub

**Comment by oddvans** [comment]
reported in https://github.com/YerovaArusu/botanicpledge/issues/20
