### ISSUE TITLE
Mana Mirror: visuals broken after taking it out in GC Space Station

### ISSUE THREAD

**Issue by Barhandar** [Vazkii/Botania#477]
I'm guessing it's because it's not exactly normal dimension.

`manaVisual` tag is stuck at 379496, `mana` tag correctly matches mana in the pool, it's constantly updating like the previous time, and displaying 0 mana (and having metadata 1000) when in player inventory, but correct amount of mana on cursor/in other inventories.

**Comment by Vazkii** [comment]
That behaviour has been removed recently though. If you have the tag it's because it stayed there from old updates, it won't do anything now.

**Comment by Barhandar** [comment]
The identical error, minus the tag since it was more recent mana mirror, just happened to my friend. Issue's here, yo.

**Comment by Vazkii** [comment]
There's no link there.

**Comment by Barhandar** [comment]
#548
Hurr.
