### ISSUE TITLE
Creative tab scroll resets from aura rings ticking mana to another ring

### ISSUE THREAD

**Issue by programaus** [Vazkii/Botania#4774]
### Mod Loader

Fabric

### Minecraft Version

1.20.1

### Botania version

1.20.1-446-fabric

### Modloader version

fabric API 0.92.2+1.20.1, fabric 0.16.9

### Modpack info

https://drive.google.com/file/d/1YT_kTE8GZeG-X1Q3CWPH6yiDFCELcwAQ/view?usp=drive_link

### The latest.log file

https://gist.github.com/programaus/4e52ffa7712c655eea6e3931d81e6e6b

### Issue description

Any mana regen ring + a mana storing ring equipped in trinket slots will reset creative tab scroll to 0 (beginning) whenever the ring ticks.

### Steps to reproduce

1. Equip Band of mana/Greater band of mana into any Trinket (Ring, unless modded) slot
2. Equip a Mana Ring/Greater mana ring into any Trinket (Ring, unless modded) slot\
3. Your scroll bar "progress" now resets to 0 every time the ring ticks

### Other information

![image](https://github.com/user-attachments/assets/7cabccdf-22d0-414a-949d-1352acbc9ca8)
https://streamable.com/d45g3h
(other mods are irrelevant as bug still occurs without them)
Scroll resets every time the ring ticks and does its thing
log doesnt seem to say anything related besides other botania errors
modpack link provided is just for testing

**Comment by anoomolu** [comment]
I'm also able to reproduce this. Curios over on Forge doesn't seem to have the same issue.

**Comment by TheRealWormbo** [comment]
This is not a Botania bug. I can reproduce it with e.g. Elytra Slot as well:

1. Give yourself an Elytra with `{Damage:431}` and the mending enchantment, then equip it in the cape slot.
2. Set up some way to gain XP in the background.
3. Open Creative inventory and scroll. Every time you gain XP and thus repair some elytra damage, the scroll position resets.

Presumably this is a Trinkets issue that we cannot do anything about. (reported as emilyploszaj/trinkets#354)
