### ISSUE TITLE
Suggestion: Give the Terrasteel amalgamation plate (or whatever it's called, the terrasteel thing) the ability to "hold on" to the reagents

### ISSUE THREAD

**Issue by WolfAmaril** [Vazkii/Botania#479]
Too many times I've been making terrasteel and accidentally been standing too close, and minecraft decides I want to pick up the reagents and POOF, there goes all that mana.

This is assuming I can ever get all three out of my inventory to begin with.
And yes, I take off my magnet ring first.

**Comment by MrKunji** [comment]
Do you mean making it hold the items like the Runic Altar?

**Comment by WolfAmaril** [comment]
Nah, just, sort of hold them there as entities.
There was a mod for 1.6.4 called "The Runic Dust Mod" that did what I'm talking about.

**Comment by Barhandar** [comment]
*That's what problem engineering is for.*

Stand on a platform above it, dropping items straight down.
Utilize blocks dropping it for you and any filterable automation to pick up and deposit the result. You don't even have to be near.
