### ISSUE TITLE
Botania armor helmets lose enchants when upgrading to helmets of revealing

### ISSUE THREAD

**Issue by QuantumManiac** [Vazkii/Botania#480]
Whenever I upgrade my terrasteel, manasteel, or elementium helmets to helmets of revealing, I lose their enchants. Is this intentional or needs to be fixed?

**Comment by Vazkii** [comment]
Whenever you use an enchanted item in a recipe it loses the enchant, it's fixable, but it's a pain so I'm not going to bother about it.
