### ISSUE TITLE
Terra Shatterer being able to break bedrock and drops the blocks

### ISSUE THREAD

**Issue by GonzaloXavier** [Vazkii/Botania#483]
If you break a block that's adjacent to bedrock i'll mine it. Given the pick is in awakened mode.

PS: Tested with rank S

**Comment by Barhandar** [comment]
Ranks SS and B do it as well. It also breaks Warded Glass, Buildcraft Springs, and, presumably, other supposed-to-be-unbreakable blocks just fine.
