### ISSUE TITLE
My server crashes at start with Botania R1.3 152

### ISSUE THREAD

**Issue by Hund** [Vazkii/Botania#485]
I just installed Botania R1.3 152 on my custom[1] Direwolf 1.7.10 (v1.0.3) server and it now crashes when I try to start it. I'm not sure what's wrong, but since it started when I updated Botania I'll try my luck here. :)

Some logs:
[fml-server-latest.log](http://pastebin.com/3ceJAG8C)
[crash-2015-01-19_08.54.13-server.txt](http://pastebin.com/vW2AeYaE)

[1] I have installed a few new mods and updated some existing mods myself. [Complete Modlist](http://pastebin.com/9KWqV0Dv).

**Comment by VictiniX888** [comment]
You forgot to get rid of the old Botania version.

**Comment by Hund** [comment]
Holy crap.. I feel so f*ing stupid right now. :D
