### ISSUE TITLE
Losing terrasteel heart on login in.

### ISSUE THREAD

**Issue by Buuz135** [Vazkii/Botania#486]
Every time you log on you have to reheal all the extra hearts that the terrasteel armor gives.

Using Beyond Reality on the ATLauncher

**Comment by Vazkii** [comment]
That's a vanilla bug.

**Comment by Buuz135** [comment]
I think it doesn't happen when you have Tinkers Construct installed.

**Comment by Barhandar** [comment]
Tinkers Construct probably isn't using vanilla attribute modification, either.
