### ISSUE TITLE
Assembly Halo Blood Magic Orb Vanishes

### ISSUE THREAD

**Issue by sjones321** [Vazkii/Botania#488]
So I found what I presume is an unintended bug and seems more related to this side of things. When using the assembly halo with any of the blood orbs for crafting it does not return the blood orb as it should when using the quick crafting.. It should be noted that using crafting table like a regular table does not have any problems returning the blood orb. however any time you save a recipe to a slot and use that recipe it will use up the blood orb and not return it. Tested this with all orbs.

I do not know if you want other data from me or if I should also post this in the blood magic page.

**Comment by Vazkii** [comment]
I'll have a look at it sometime.
