### ISSUE TITLE
Feature Request: Mana Diamond and Dragonstone Blocks

### ISSUE THREAD

**Issue by Durpady** [Vazkii/Botania#494]
Iron has Blocks.  Manasteel is made from Iron, and it has blocks, and can in fact be converted on a block basis.  The same goes for Elementium.

Diamond also has Blocks.  So where are the Mana Diamond Blocks?  Or Dragonstone Blocks?

This isn't something that would change gameplay all that much, but it seems fitting.

**Comment by Vazkii** [comment]
Closing to make (screen) real estate for bugss as it's an idea, on the todo list already.
