### ISSUE TITLE
Flugel Tiara

### ISSUE THREAD

**Issue by Ryusen15** [Vazkii/Botania#496]
Hello, and thank you for the great mod, I have found it to be a lot of fun.  I am using the FTB Direwolf20 ver. 1.7.10 modpack.  I only have Hats, Hat Stands, and OPIS disabled, all other mods are enabled and should be up to date.  I am doing a direct connect with a friend using Hamachi, and have had no issues with Botania until I tried to use the Flugel Tiara.  My friend is hosting the game, but when I equip the tiara, I do not get the wing effect or the creative flight mode.  My friend was able to see the wings and I was unable to.  I had him try using it, he saw the wing effect (not visible to me) and he was able to use the creative flight mode.  Is it a problem with me being a guest in his game?  Thank you for your assistance.

**Comment by MrKunji** [comment]
First of all, do you have any Mana container in your inventory?

**Comment by Ryusen15** [comment]
Ah, thank you for pointing that out to me.  First I tried using a using the terra steel mana ring that stores a large amount of mana.  Then I tried holding a fully charged mana tablet.  Thank you again for catching that for me.

**Comment by Yulife** [comment]
If it is solved, close the issue.

**Comment by Ryusen15** [comment]
The issue is not quite solved.  I tried with a mana tablet and my terra steel mana ring and neither would cause the Flugel Tiara to activate.  So the problem is not with the mana supply, and I do not think it is with Direwolf20, since my friend who I am playing with has the same mods disabled as I, and he can use the tiara with its' wing effect (though I cannot see the effect).  Could the problem be with me being a guest in his game?  I am doing a direct connect to his game.

**Comment by Vazkii** [comment]
Direct conect through LAN? That'll break it, yes. See Azanor/Baubles#70

**Comment by Ryusen15** [comment]
Okay, thank you for the information.
