### ISSUE TITLE
IDEA: Spark networks

### ISSUE THREAD

**Issue by Motusification** [Vazkii/Botania#497]
After playing around with Sparks that there is no way to have only some sparks interact with each other. So for example I use sparks for my main managen and for my livingwood/stone production but I don't want the sparks to interact between these. My suggestion would be to be able to dye the sparks to make them only interact with other sparks of that color. 
-Motusification

**Comment by Vazkii** [comment]
I'm not interested on that, the lack of ability for multiple networks works as intended.
