### ISSUE TITLE
More color flashes

### ISSUE THREAD

**Issue by cdfa** [Vazkii/Botania#498]
Hi, I was playing around with the flash mana lens and realised that it was only gonna be useful in combination with a mana blaster. However you can only make 1 color flashes with the blaster. Could you add tinted lenses to the list of lenses which can be combined with other lenses (like velocity and potency lens)? This would greatly increase the spectrum of the colors of flashes.

**Comment by Vazkii** [comment]
I don't get what you're trying to say.
*(you can still comment on closed issues)*

**Comment by Durpady** [comment]
Not quite one color.  A Rainbow-tinted Flash Lens will make all sorts of different colors.  Of course you can't control what color it produces...

**Comment by cdfa** [comment]
Ah, okay. Didn't try that one out. Sorry for bothering you
