### ISSUE TITLE
Mapmaker's Soils: Inverted and Sentient

### ISSUE THREAD

**Issue by Barhandar** [Vazkii/Botania#503]
A suggestion to add two things for mapmakers to utilize Botania in traps:

Inverted Soil inverts the plant's effect. Producing drain mana, functional have inverse effect - like Fallen Kanade degrading player health rapidly, Vinculotus making Endermen teleport more often, whatever the flower is that poisons mobs healing them instead, et cetera.

Sentient Soil switches plant target between player and mobs, i.e. Sentient Kanade would ignore players and heal enemies, and Sentient poisonflower would poison players instead of enemies.

Presumably they should be able to be combined to be bane or boon: like Inverted Sentient Kanade serving as room-clearer.

**Comment by Vazkii** [comment]
I'd have to code all the effects of all the flowers again just for that. It's an interesting idea but definitely too much work for what it's worth.
