### ISSUE TITLE
Botania Crash

### ISSUE THREAD

**Issue by TjoMas-A** [Vazkii/Botania#504]
I had this crash while playing the DireWolf20 modpack (version 1.0.3) I have also added Optifine and Fastcraft  to the pack for performance improvements, and I understand that Optifine changes some rendering code. However, I have had it installed for almost as long as I have had the pack, and I have never had any similar crashes. Hope it can be fixed.

http://pastebin.com/uSLTcS5U

**Comment by Vazkii** [comment]
Can you remove optifine and see if it still happens?

**Comment by TjoMas-A** [comment]
I've removed Optifine, played with it for a little longer, and no further crash. I think it may be an Optifine issue, but if there is any more information you require, I will be happy to provide it.

**Comment by Vazkii** [comment]
Yeah, that type of crash happens often with optifine. There really isn't anything I can do about it.
