### ISSUE TITLE
[Suggestion] Vanilla Interaction: Rod of the Seas filling Cauldron

### ISSUE THREAD

**Issue by micglin** [Vazkii/Botania#505]
I noticed playing a Gregtech based pack (where you need to "wash" some dusts in a cauldron, e.g: dirty redstone dust) that the Rod of the Seas won't fill a vanilla Cauldron; it seems to just place the water block on top.  However, unlike the Thaumcraft crucible, you also can not pipe in water to keep vanilla cauldrons filled like you can with the Thaumcraft crucible, which is what would make the Rod of the Seas very handy in this regard.

As a non-programmer, my idea is that if the Rod of the Seas is right-clicked onto a fluid container (any mods tank, cauldron, crucible, etc that supports adding water via a water-bucket right-click), it behaves as a water bucket does to add up to 1000mb of water to the container.  If it is not clicked onto a fluid container, it would behave as it does now, and place a water source block in the world.  I admit I have no idea what is involved in implementing that functionality, or whether it's widely desired.  This would seem to also provide the mod compatibility mentioned in Issue #422 without needing explicit mod interaction.

**Comment by Vazkii** [comment]
From what I can tell, this doesn't seem to be possible without hardcoding or using fake players, I don't want to do either, sorry.
