### ISSUE TITLE
[Suggestion] Changing amount of mana from Tiny TNT (if possible)

### ISSUE THREAD

**Issue by Reyls** [Vazkii/Botania#506]
tiny TNT from AE2 produces same amount of mana like ordinary TNT.
slightly imbalanced

**Comment by Vazkii** [comment]
If it spawns a EntityTNTPrimed I can't do anything about it.

**Comment by Kubuxu** [comment]
But this EntityTNTPrimed has smaller explosion multiplier, I presume.

**Comment by Vazkii** [comment]
No, it overrides the explode function and creates an explosion with a lower value there. Nowhere in the class is there a field for the explosion radius.

**Comment by Kubuxu** [comment]
Oh. Ok then.
