### ISSUE TITLE
Feature Request: Dynamic upgrades to Mana Enchanter

### ISSUE THREAD

**Issue by Durpady** [Vazkii/Botania#507]
Two Natura Pylons would allow the machine to accept ONE additional enchantment (adding more pairs would not increase this further).  

Four, or maybe two, Gaia Pylons would tweak the Enchanter's behavior, scanning each book for all enchantments, and applying the first valid one (possibly for an increased cost determined by how low on the list each enchantment is), instead of its "if-first-isn't-valid-then-skip" behavior.  This would give the player greater flexibility, allowing them to have a "complete" enchantment library with fewer books.

Other ideas include having certain blocks (like unstable cubes/beacons) nearby to reduce costs a bit but that might make it too close to Thaumcraft's Infusion for your tastes.

**Comment by Vazkii** [comment]
Not exactly interested, no.
