### ISSUE TITLE
Hydroangeas not working r1.53

### ISSUE THREAD

**Issue by l2edeyejedi** [Vazkii/Botania#508]
Ok So I might have derped the placement of the hydroangeas however something appears broken with the recipe, 2 reg cyan 1 mana cyan, 1 mana blue an 1 reg blue, 1 pink. Nothing however, nothing with multiple types of seeds used.

**Comment by Vazkii** [comment]
What is the problem even?

**Comment by l2edeyejedi** [comment]
Well at first I wasnt able to make them work, Fixed that I derped the placement. Now however I cant get the recipe to work in the petal apothecary to make the flower itself. The lexica an the nei recipe are the same however neither one is working, Nor are variations of them. No idea why. It worked fine in r148 on this world.

**Comment by Vazkii** [comment]
Send screenshots of exactly what you have in your inventory.

**Comment by l2edeyejedi** [comment]
Sorry vaz, I appear to be the victim of dumbshititis. I was using light blue rather then cyan for my 2 mysticals. glad you closed this.
