### ISSUE TITLE
[154] NEI mana infusion mana requirement display issues

### ISSUE THREAD

**Issue by Belgabor** [Vazkii/Botania#509]
There seems to be something wrong with the mana requirement display for mana pool infusions in NEI.
The most obvious thing is that the display is wrong by a factor of ten. Going by the numbers used with modtweaker (and testing the actual infusion), a full mana pool equates 1.000.000 units. The bar on NEI is full at 100.000 units. Going above that results in render bugs, for example with 500.000 units I have a second full bar rendered in the middle of the NEI item display on the right side of my screen.

A second related or unrelated issue is when I set mana requirement to 12.500 units. That should (currently) display as 1/8th of a full pool but looks significantly less, I'd say about like 5% of a full pool. 25.000 units displays "correctly" as 1/4th of a full pool.

Finally, to prevent confusion with how I titled the issue, it is not a new one, I just confirmed it in the current version.

**Comment by Vazkii** [comment]
That is intended. If it was at a 1:1 scale it would render at 1px for most items, making it so you really couldn't tell the difference.

**Comment by Belgabor** [comment]
Would it be at least possible to get rid of the render bugs when using large requirements? So rendering caps out at 100.000?

**Comment by Vazkii** [comment]
Sure, that's doable.

**Comment by Belgabor** [comment]
Thanks =)
