### ISSUE TITLE
[r1.3-149] OpenBlocks Gravestone Glitch

### ISSUE THREAD

**Issue by jawdylawdy** [Vazkii/Botania#512]
On a server for Resonant Rise 3 (3.2.2.1-RC-MAIN), with OpenBlocks Gravestones enabled, a person who dies seems to lose everything BUT their Baubles inventory. A possible conflicting mod is the Erebus, which has an optional alternative to gravestones, but they've been disabled.

Also, apologies if you're not the person to bug about this. My first thoughts were "Baubles? Botania. VAZKII! :D"

**Comment by TheMadmanofChaos** [comment]
You, in all likely hood, have a "Very" out of date version of baubles. That was a bug fixed months ago.

**Comment by Vazkii** [comment]
This also is not on botania's side.
