### ISSUE TITLE
Feature Request: Harvesting mature crops

### ISSUE THREAD

**Issue by SynfulChaot** [Vazkii/Botania#522]
Would it be possible to get an upgrade to the Horn/Drum of the Wild, or perhaps a new functional flower, that harvests only mature crops?  Could have it so it only drops the crops on the ground so you still need to use another method (such as the Hopperhock) to actually gather them.  Bonus if it can 'right-click gather', if the crop supports it.

The only current in-mod solution is a Drum of the Wild, but with it's range it's highly impractical for auto crop harvesting as you need to wait for *all* crops in a large area to be mature to be efficient.

**Comment by Vazkii** [comment]
No, I don't want to do that. They're not meant to be efficient.

**Comment by SynfulChaot** [comment]
Ah well.  Inefficiency to the point of inadequacy for crops just means one less option.  Was worth the ask, though.
