### ISSUE TITLE
NEI Compatibility crash

### ISSUE THREAD

**Issue by Arouka** [Vazkii/Botania#523]
We get this crash on my server any time we try to look up the use of an item in NEI.

http://pastebin.com/SDVQFfvF

**Comment by Vazkii** [comment]
Post a copy of your config.

**Comment by Arouka** [comment]
http://pastebin.com/5R0zBvu9

Left out the shedding part for simplicity's sake

**Comment by Vazkii** [comment]
Update botania, that version doesn't have the potion ID config.
