### ISSUE TITLE
Client crash upon drinking Vanity's Emptiness

### ISSUE THREAD

**Issue by Zaegar** [Vazkii/Botania#524]
My client crashes when I drink from a flask of Vanity's Emptiness. This issue happened both when in creative and in survival. I am using Botania r1.4-155, and I have only tested this in SSP.

crash log: http://pastebin.com/gdPxDrA8

**Comment by TheMadmanofChaos** [comment]
Mind using NEI to make a data dump for your potion ID's? Should be under the NEI options, accessible from the button in the lower left side of the inventory screen. I recall the data dumps are under "Tools",but I might be wrong.

**Comment by Zaegar** [comment]
Here is the list of all used potion IDs:
http://pastebin.com/9btUb3ph

**Comment by TheMadmanofChaos** [comment]
In the botania config file, shift the potion effects to 90-97. Where they are now, it's out of bounds and causing this crash.

**Comment by Zaegar** [comment]
That fixed the issue, thank you for the help.
