### ISSUE TITLE
Using Amulet with Allure in it causes me to crash

### ISSUE THREAD

**Issue by Hazado** [Vazkii/Botania#525]
Crash log
http://pastebin.com/CUFkA9Yz
Config File
http://pastebin.com/CSHwuy0h

**Comment by Vazkii** [comment]
Your potion IDs are too high.

**Comment by PikadudeNo1** [comment]
They're the default IDs. Surely Botania assigning default IDs that it cannot use in pendants without crashing is a bug?

**Comment by Vazkii** [comment]
Ah, you're right, I was looking at it wrong.
The log is still very weird, because it doesn't reference botania at all, though.
