### ISSUE TITLE
Mana Mirror not working in the Outerlands.

### ISSUE THREAD

**Issue by OldOpa** [Vazkii/Botania#529]
If you enter the Outerlands from Thaumcraft the Mana Mirror isn't able to drain mana from its bound pool. Whereas when I enter the nether it is working fine, thus the pool must be loaded. Is it a bug or a feature (from thaumcraft) ?

Edit: using the lates botania r1.4-157 with the latest Thaumcraft 1.7.10-4.2.3.4.

**Comment by Vazkii** [comment]
The pool naturally needs to be loaded. Whether TC unloads stuff or not I wouldn't know.
