### ISSUE TITLE
 Terrestrial Agglomeration Plate has no visual effects and doesn't create terrasteel.

### ISSUE THREAD

**Issue by Sirius902** [Vazkii/Botania#530]
![2015-02-06_19 38 39](https://cloud.githubusercontent.com/assets/10891979/6090716/eb54acd2-ae38-11e4-9a29-400d3e2f8042.png)
I am using the Direwolf20 1.7.10 modpack and I have even updated Botania to attempt to make it work, but all attempts have failed. It seems to infinitely absorb mana, but never gets anywhere. Eventually the items just despawn.

**Comment by Vazkii** [comment]
Can you reproduce it with botania only? I'm fairly sure I would have noticed that one.

**Comment by MrKunji** [comment]
Tested with only Botania, works fine: http://i.imgur.com/P7090zc.png
Try removing the augments, it may work.

**Comment by Sirius902** [comment]
I reproduced the issue, only using Botania r1.4-157 and Baubles-1.7.10-1.0.8 and removing the augments makes the plate not draw mana at all.

**Comment by Sirius902** [comment]
I'd like to know what you mean adding the needs-info tag though.

**Comment by Vexatos** [comment]
@Sirius902 Uuuh, do you have particles enabled? Not sure if Botania cares about that, but it's worth a try.

**Comment by Sirius902** [comment]
I have particles enabled.

**Comment by Vazkii** [comment]
I'm assuming you figured out what was causing it as you closed the issue?

**Comment by Mortach** [comment]
Would like to know as I seem to have the same issue. Was able to make 1 ingot and nothing since. have rebuilt the entire structure to no avail.

**Comment by Vazkii** [comment]
![](http://static.tvtropes.org/pmwiki/pub/images/MTG-ThreadNecromancer_3198.jpg)

**Comment by Sirius902** [comment]
Hey, you probably don't have what my problem was. I didn't read the Lexica Botania carefully enough and didn't put a piece of living rock under the plate and just alternating around it one block under. Sorry for not responding when I closed Vazkii. I was mad at myself lol.
