### ISSUE TITLE
Tweak suggestion: Elven Rods crafted with Dreamwood Twigs

### ISSUE THREAD

**Issue by Durpady** [Vazkii/Botania#533]
Title sums it up, since you've added Dreamwood Twigs for the Elementium Tools, it makes sense to me that the Elven Lore Rods (Shaded Mesa and Unstable Reservoir, possibly but probably not Bifrost) should also be made from them.

**Comment by Vazkii** [comment]
Gaaaaaaaaah I gotta change the textures and recipes and D:
