### ISSUE TITLE
Greater Gaia's projectiles don't despawn

### ISSUE THREAD

**Issue by MajorCooke** [Vazkii/Botania#534]
Because they don't despawn, when the "magic missile" goes beyond the boundaries of a loaded chunk into an old chunk, it might not cause a crash, but it can certainly cause a server to choke up and die, cutting everyone off from it.

This is mostly guesswork:
Now, I know there are a few properties about them, like they seek after Gaia's primary target, but try fighting Gaia with a Taintacle Ring from the Thaumic Exploration mod. Whenever the player takes damage, a mini-taintacle will sprout around the player and damage anything it touches (minus the player themselves) whom are capable of drawing the ire of other monsters.

But the main point is, they can cause an issue. The admin tried to MCEdit it out, but without success so we removed Botania to get rid of them, and reinstalled it again.

FML server: https://pste.me/#/IzPd8
latest-log: https://pste.me/#/11kte

**Comment by JackBarnett2014** [comment]
Mr Server Admin here

Some version information for reproduction:
Botania Version: 1.4_145
Java: 1.7.0_25

The server didn't crash, hence the lack of a crashlog, however it caused the server to come to a halt and continue to run (and use resources) until Ctrl+C'd. The users seem to time out. When investigating the specified entities there is absolutely nothing there.

Our solution (Although brutal):
1. Stop Server
2. Remove Botania
3. Restart server and /fml confirm the entities to be removed
4. Readd Botania.
5. Restart and replace any lost items.

Hope this helps.
