### ISSUE TITLE
Idea: Mystical Flower Bag

### ISSUE THREAD

**Issue by Durpady** [Vazkii/Botania#538]
Sixteen varieties of Mystical Flower mean that going on a flower-picking expedition requires a huge chunk of your inventory to be free.  Some sort of satchel that will hold them for you would fix that, capable of holding up to 64 of each type.

I know you're averse to adding GUIs, so if you'd really rather not give one to this thing, I have a system thought out: Flowers the player picks up from the world would go to it instead of the player's main inventory (like a Forestry backpack), and crafting it with a flower would place it into the bag.  It could cycle through the "active" flower type with shift-right and shift-left clicking, and regular right-click would plop one of the active flower into the player's inventory.  Or, you could come up with your own system.  Though I think, given the nature of the item, a GUI really would be best.

**Comment by erima** [comment]
I really like this idea. I'll put my +1 in for something for petals and powders too, either one-for-all or something different.

**Comment by Hjaldar** [comment]
Please call it a "flower basket". That is the correct container to use when collecting flowers. And one must skip while doing so.
