### ISSUE TITLE
ProjectE Cannot Transmute Functional/Generating Flowers

### ISSUE THREAD

**Issue by Kolatra** [Vazkii/Botania#539]
After looking through the code of Botania and testing, it seems that the way they are registered fails through ProjectE's transmutation system, giving the Botania Flower every time.
![2015-02-08_19 45 12](https://cloud.githubusercontent.com/assets/3821892/6100329/166e921e-afcb-11e4-8585-55e7c38b2925.png)
![2015-02-08_19 45 19](https://cloud.githubusercontent.com/assets/3821892/6100338/29c30dc2-afcb-11e4-90fc-e13c1255fce9.png)
![2015-02-08_19 45 32](https://cloud.githubusercontent.com/assets/3821892/6100340/2d5602b4-afcb-11e4-849a-0a74a2785c55.png)

**Comment by Vazkii** [comment]
That's because the botania flowers have all the same id and metadata, but the various types are defined through NBT.

**Comment by MaPePeR** [comment]
Just for curiosity: whats the benefit of using NBT instead of having a different metadata value for the different flower types? Botana flowers sound like a perfect example of when to use metadata instead of NBT.

**Comment by Vazkii** [comment]
It uses only one block ID. It made more sense in 1.6 but stuck to 1.7.

**Comment by MaPePeR** [comment]
But using Metadata would also only use 1 block Id. Or was that not possible in 1.6? I don't know.

**Comment by Vazkii** [comment]
Using metadata would force me to only 16 different flowers. I'd have to use the name lookup in the TE anyway so what's the point?

**Comment by MaPePeR** [comment]
Oh right, i forgot, that the metadata is restricted to 16 values for blocks. Items can have a lot more different values though.

**Comment by Hyper-Miiko** [comment]
Hey, i'm the gravedigger!
Just for other people who have this issue, there is a config file in ProjectE directory : "~/config/ProjectE/nbt_whitelist.cfg" for adding some item who would keep NBT data when transmuted. It seem to be designed especially for this purpose.
[nbt_whitelist.zip](https://github.com/Vazkii/Botania/files/3127077/nbt_whitelist.zip)
