### ISSUE TITLE
GL Error

### ISSUE THREAD

**Issue by XBlackLeopardX** [Vazkii/Botania#544]
When using botania with psychedelicraft the console gets spammed with a GL error
I am using the latest forge, botania build 158, psychedelicraft and baubles

It is something to do with the shaders because once they are disabled in the config of psychedelicraft it doesn't spam the console

Here is the log it was generated with botania build 157 but I tested it with 158 and it gets the same result
https://gist.github.com/XBlackLeopardX/07c2ecc5e0a824e15c0d

here is the link to the issue opened for the other mod I was told to also post it here
https://github.com/Ivorforce/Psychedelicraft/issues/5

**Comment by Vazkii** [comment]
This doesn't give me any info whatsoever. I'll pass the relevant code to the other issue but that's about all I can do right now.
