### ISSUE TITLE
Nazi Symbol | Mana Pool

### ISSUE THREAD

**Issue by unpure** [Vazkii/Botania#545]
Hey there, just found a nazi symbol in the mana pool.
http://fs1.directupload.net/images/150211/tzwk5biw.jpg
I know the "swastika" has many uses but i think its not the best design. :P

**Comment by Vazkii** [comment]
Not an issue, you're just letting your imagination run too free.

**Comment by BarbasTheDog** [comment]
Wat? That isn't even a swastika. If anything this looks more like a little windmill than a swastika :P

**Comment by LorenzoDCC** [comment]
I'm pretty sure I saw an Illuminati triangle in the mana particles the other day ~
