### ISSUE TITLE
Mana Mirror Stops Working

### ISSUE THREAD

**Issue by whitestarx0312** [Vazkii/Botania#548]
Sometimes when joining my server, my mana mirror does not transmit. It appears white, as if it is not linked to a mana pool. When I click the item as if to move it to another inventory spot, it turns blue like it is linked but unlinks immediately when I place it in my inventory. When I put the mirror in any other inventories like a chest or bag, it looks linked. 

Using Forge 10.13.2.1291 (Recommended)
Botania R1.4-156.

I can include screenshots or a quick video if you need it.

**Comment by Vazkii** [comment]
A quick video would be good, yes.

**Comment by whitestarx0312** [comment]
Alright here you go. https://www.youtube.com/watch?v=NBi-okdYPLM

**Comment by Vazkii** [comment]
Gah, multiplayer, I'll look into it.

**Comment by whitestarx0312** [comment]
Haha thanks (;

**Comment by Barhandar** [comment]
Hurr.
