### ISSUE TITLE
[Bug] Duping bug with Force Relays.

### ISSUE THREAD

**Issue by kyahco** [Vazkii/Botania#549]
Upon messing with Force Relays, I suddenly had duped them, so I decided to try and reproduce it and see what was happening. 

I installed only Botania ( and Baubles as it's a dependency), started up a single player world (Though had the same results on multiplayer), And found out that when a you have two pistons pushing a force relay in perpendicular directions activated by redstone pulsers it will "push the force relay in both directions" and dupe it. 

I recorded video of it here:  https://www.youtube.com/watch?v=OLZ8oAQg4TA&feature=youtu.be

The set up of the repeaters is important, one piston (pushing the block) has to active slightly after the other one.

Log with a forced crash report: http://pastebin.com/jHaZ3u0h

So far I have tested it with Botania 158 and 159.

**Comment by Vazkii** [comment]
Well this will be a pain to fix :T
