### ISSUE TITLE
Strange transparency with elven gateway

### ISSUE THREAD

**Issue by ariscop** [Vazkii/Botania#551]
![screenshot from 2015-02-08 09 15 04](https://cloud.githubusercontent.com/assets/1522423/6181919/f6364d3a-b38e-11e4-9af4-68623fdc480a.png)
![screenshot from 2015-02-08 09 15 07](https://cloud.githubusercontent.com/assets/1522423/6181915/e50f1d16-b38e-11e4-88fd-44c252abfce3.png)
r1.3-143 in the direwolf20 pack
Getting a world download later today to check against r1.4 with newer forge.

**Comment by ariscop** [comment]
r1.4-159, similar behaviour, but different blocks are invisible. same version of forge
![screenshot from 2015-02-13 19 42 27](https://cloud.githubusercontent.com/assets/1522423/6184643/c3254606-b3b8-11e4-8e9b-679111db7639.png)

**Comment by ariscop** [comment]
Seems which blocks are hidden changes every time the chunks are loaded

**Comment by Vazkii** [comment]
This is a vanilla bug, sadly TileEntities' renders are fiddly with transparency.
