### ISSUE TITLE
Crash with warp lens and tiny planet

### ISSUE THREAD

**Issue by RedsaphirCZ** [Vazkii/Botania#555]
Hello,warp lens with tiny planet and force relay dont play well together probably :)  i wanted to teleport mana. Tried to send mana burst modified with warp lens into mana pool, let it interact with tiny planet and let manaburst interact with force relay... world is corrupted now

Crash log is here : http://pastebin.com/2B51gQR2

**Comment by Vazkii** [comment]
Update botania, I've fixed that already.
