### ISSUE TITLE
Lense caused server hang

### ISSUE THREAD

**Issue by devryb** [Vazkii/Botania#557]
Had a server hang today with version 1.4-157.  I ran visualvm for a bit while it was in this state shown in the link below.  I think it might be a one off issue but will let you know if it happens again

http://puu.sh/fTzWj/d3856face8.png

**Comment by Vazkii** [comment]
I mean, it's probably this for loop that's causing it, but if you have that many entities in one spot you probably have worse issues O.o
https://github.com/Vazkii/Botania/blob/master/src/main/java/vazkii/botania/common/item/lens/LensDamage.java#L29

**Comment by Vazkii** [comment]
Going to assume it's something odd out of my control, feel free to comment if it happens again.
