### ISSUE TITLE
Bug: Manasteel/Elementium Shears trigger Tripwire

### ISSUE THREAD

**Issue by Durpady** [Vazkii/Botania#558]
Title says pretty much everything, when you try to cut Tripwire with Botania Shears, the hooks it's attached to still trigger.

**Comment by Vazkii** [comment]
This isn't fixable.

**Comment by Durpady** [comment]
Can you at least add a disclaimer to the Lexica pointing this out?

**Comment by Vazkii** [comment]
That's doable.
