### ISSUE TITLE
Idea: Gaia Spreader add-on for Mana Blaster

### ISSUE THREAD

**Issue by Durpady** [Vazkii/Botania#559]
This would add a "charge" function to the Mana Blaster: if right-click is held down, the Burst will "charge up" with some sort of visual effect, with a full charge (this could be significantly slower than a Bow if you're worried about balance) being more in line with a Gaia Spreader's Mana Burst (after the existing Blaster multipliers to speed and capacity).  Tapping right-click would still allow it to function like a normal Mana Blaster.

A fully charged blast could have special bonuses, depending on the Lens it's equipped with: Damaging would deal more damage (losing a proportionally higher amount of Mana as it does so), Bore would break a larger area of blocks (I'm thinking 3x3, and again its Mana loss would reflect this), and the four basic Lenses would have their effects accentuated... that's all I can think of (Entropic already works based on Mana Burst payload size, it doesn't need any bonus), but maybe you can think of other Lenses that could benefit from this.

**Comment by Vazkii** [comment]
Not interested in doing that.
