### ISSUE TITLE
Idea: certain blocks beneath Loonium change its loot spawning behavior

### ISSUE THREAD

**Issue by Durpady** [Vazkii/Botania#560]
The block would go underneath the Grass/Dirt the Loonium is on (like the Rannuncarpus), with Planks causing it to generate Mineshaft loot, and Stone Bricks causing it to generate Stronghold loot, Nether Brick causing it to generate Nether Fortress loot, and (if the player really wants this) an Anvil causing it to generate Blacksmith Chest loot.

If it wouldn't be too much trouble, you could even add an area in the config where other blocks would cause it to generate loot from other mod structures (like Mazestone causing it to generate loot from a Twilight Forest labyrinth)

**Comment by Vazkii** [comment]
I'm not interested in this, polling from other pools would make the thing even more broken.
