### ISSUE TITLE
Terra Shatterer does not break ChromatiCraft Ores.

### ISSUE THREAD

**Issue by Kolatra** [Vazkii/Botania#570]
![2015-02-16_20 43 56](https://cloud.githubusercontent.com/assets/3821892/6223147/fbcb8048-b61e-11e4-84de-46b893808bc1.png)

**Comment by Vazkii** [comment]
I had a look through it and for the life of me can't figure out what's going on, sorry.

**Comment by Kolatra** [comment]
It honestly MIGHT be because the ores are handled differently, just no idea as to how to work around that.

**Comment by ReikaKalseki** [comment]
They are not a render type zero; is that related?

**Comment by Vazkii** [comment]
That really shouldn't be the case, but you can have a look at the respective code here if you want.
https://github.com/Vazkii/Botania/blob/master/src/main/java/vazkii/botania/common/item/equipment/tool/ItemTerraPick.java
https://github.com/Vazkii/Botania/blob/master/src/main/java/vazkii/botania/common/item/equipment/tool/ToolCommons.java

**Comment by ReikaKalseki** [comment]
Found it.
https://github.com/ReikaKalseki/DragonAPI/blob/master/Base/BlockTieredResource.java#L79
