### ISSUE TITLE
Rendering Issue with Colored Lights Core

### ISSUE THREAD

**Issue by shadowfacts** [Vazkii/Botania#571]
When using Botania with [Colored Lights Core][clc] there is a rendering issue with most Botania blocks:

![2015-02-17_16 17 38](https://cloud.githubusercontent.com/assets/7091588/6237403/7f5d87de-b6c0-11e4-92b3-57aff7a53293.png)

The two blocks on the left are Mana Spreaders and the one on the right is a Petal Apothecary.

Botania: r1.5-162
Colored Lights Core: 1.3.7.35

P.S. This should probably be fixed relatively soon, especially seeing as @Vazkii is [bragging about it][brag] on the website.

[clc]: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/1445251-1-7-10-beta-wip-colored-light-progress-and
[brag]: http://botaniamod.net/downloads.php

**Comment by Vazkii** [comment]
This was definitely not the case when I was testing with the mod in eclipse, but those blocks don't do anything weird in terms of rendering, they're just simple TESRs. Which leads me to believe this is a problem in CLC, not botania. Also, telling me to fix an issue soon won't make me fix it any sooner than normal, quit it.

**Comment by shadowfacts** [comment]
Ok, will report this to the CLC dev.
