### ISSUE TITLE
Crash after updating to 1.62 when Opening Lexicon

### ISSUE THREAD

**Issue by markaskey** [Vazkii/Botania#574]
I am experiencing a crash anytime I attempt to open the Lexicon.   I had the previous version working find but the latest build.  I was using 1.4-159 before upgrading to 

Here is the crash log. http://pastebin.com/D8Ah3K0K

This is the first time submitting a crash to git, so please let me know if you need more.

Thanks!

**Comment by Kolatra** [comment]
I think this is an error with enchiridion, because the Lexicon was changed, and they haven't updated to accommodate that.

**Comment by Vazkii** [comment]
Fix your shit @joshiejack

**Comment by joshiejack** [comment]
It is fixed. :p

They just need to update ;p
