### ISSUE TITLE
Corporea sparks Barrel issues

### ISSUE THREAD

**Issue by Cyrakrum** [Vazkii/Botania#579]
The Corporea sparks are only registering one stack of items when looking at Jabba/Refined relocation barrels as seen here http://imgur.com/8ZPro2j Also tested with Thermal expansion Caches and get the same result. 

Factorization barrels and mekanism bins aren't reading at all.

**Comment by Vazkii** [comment]
That's normal, they technically only have one inventory slot which is automatically refilled as needed.

**Comment by Cyrakrum** [comment]
Damn... I was really hoping to be able to call from my barrels =(
