### ISSUE TITLE
Horn of the Wild does not break ExtrabiomesXL flowers

### ISSUE THREAD

**Issue by Mrbyte2k** [Vazkii/Botania#580]
Using Botania version R1.5 162 and ExtrabiomesXL version 3.16.0 (latest), the Horn of the Wild will not break the ExtrabiomesXL flowers.  Not a major problem, just a minor annoyance.

**Comment by Vazkii** [comment]
That's because it checks for BlockBush. I guess they aren't, which is weird. It's in nobody's end, just an incompatibility of the implementations.
