### ISSUE TITLE
Band of Aura stopped working

### ISSUE THREAD

**Issue by AkitoKitsune** [Vazkii/Botania#581]
Everything was fine, everything it worked. Until all of a sudden the Greater Band of Aura stopped working on armor, Band of Mana, etc. I tried anything possible, like changing the Greater Band of Aura to a new one, replacing it in the slot, changing slots, restarting the complete client and so on. I even crafted a regular Band of Aura to double check, but nothing works. And its not like it is a configuration error or something like that, because it used to work until a couple of days in the past.
Please help, thank you.

I checked the Band of Mana too and it works in the Mana Pool. And like I said, even if it would not work, my armor and pickaxe should get mana from the Greater Band of Aura, but it didn't in roughly 20 hrs of active game.

Now I found out, that every time I equip my Tainted Blood Pendant with Speed II in it, Mana Regen stops working immediatly as well as it starts working immediatly after I unequip it.

**Comment by Vazkii** [comment]
I really can't do much with just "it stopped working".

**Comment by AkitoKitsune** [comment]
What else do you want to know?

**Comment by Vazkii** [comment]
I need info on your environment, mods loaded (a log is prefered as it has more info) and a screenshot of your inventory.

**Comment by AkitoKitsune** [comment]
![javaw 2015-02-22 15-45-36-62](https://cloud.githubusercontent.com/assets/11080705/6318939/18c559dc-baaa-11e4-9649-628a1fa211a4.jpg)

**Comment by AkitoKitsune** [comment]
http://pastebin.com/BgR3RnxK
http://pastebin.com/A0YZgMxz

**Comment by AkitoKitsune** [comment]
ROG Maximus VII Ranger
Intel i7-4790K
Windows 7 Ultimate x64
Intel HD Graphics 4600 (no external graphics card)

**Comment by AkitoKitsune** [comment]
Corsair Vengeance 8GB RAM

**Comment by Vazkii** [comment]
It doesn't work because you don't have anywhere to store the mana.

**Comment by AkitoKitsune** [comment]
The description says, that the mana goes in "mana containing items" which obviously should include items like the armor. That said I had a Greater Band of Mana and it did not work with that either until it glitched away, so I do not have it anymore.

**Comment by Vazkii** [comment]
The armor doesn't contain mana, it uses it.

**Comment by AkitoKitsune** [comment]
I will try it again with a new Greater Band of Mana soon. If it won't work I will tell.

**Comment by AkitoKitsune** [comment]
I tried it now with a Mana Tablet and it works indeed. Seems like it was a temporary or server related glitch.
Anyway, thank you very much for your help and investment of your time in the issue i mentioned.

**Comment by AkitoKitsune** [comment]
Well I noticed there is still an issue left. Mana Regeneration stops when equipping a Tainted Blood Pendant.

**Comment by Vazkii** [comment]
Of course it does, the pendant consumes mana as well, so you get a negative delta.
