### ISSUE TITLE
Idea: Livingwood and Dreamwood Bows

### ISSUE THREAD

**Issue by Durpady** [Vazkii/Botania#583]
Crafted with Twigs replacing Sticks in the standard Bow recipe, and Ingots/Gems in the empty corners.  Their main feature would be the ability to add Runes to them (via crafting grid), giving them different effects depending on the Rune - Livingwood would hold one or two, Dreamwood would hold two to four.  Some Runes' effects would cost more durability/mana than others, like Wrath and Pride, and some would prevent arrows from being recovered (most notably Wrath).  Runes would be removed by cycling it though the grid, like the current Mana Blaster setup - hence why Dreamwood wouldn't have more than four slots, so they can all be returned in the 2x2 grid.  May or may not use special Manasteel/Elementium Arrows.
FIRE: mob/terrain lit on fire; with Flame enchantment, mobs burn longer and blocks are smelted if possible (even if the result is an item, like Wood/Charcoal or Ore/Ingot)
WATER: spawns flowing/temporary Water (like Thaumcraft 2's Wand of Water), extra damage to Blazes
AIR: launches mobs high into the air (~10 blocks)
EARTH: knockback, mimics (and stacks with) Punch
SPRING: bonemeal effect
SUMMER: evaporates water
AUTUMN: breaks leaves and crops
WINTER: spawns Snow, freezes water
MANA: mimics Infinity; when Infinity is also present, it acts like Unbreaking, and reduces the damage/mana cost of other Rune effects (if any)
SLOTH: slows mobs hit
GREED: improves drops (like Looting)
PRIDE: increased damage, mimics (and stacks with) Power, improves potency of other rune effects where applicable (Winter could freeze Lava; Envy drops more items; Earth gives more Knockback; etc.)
GLUTTONY: portion of damage dealt is returned as hunger (or maybe health) refill
WRATH: explosive arrows (radius/damage influenced by Power and Pride), gives/improves AoE to/of other Runes (like Winter, Fire and Spring)
LUST: puts target mob in Love Mode (passive), or charms it (hostile)
ENVY: target drops a random equipment piece (held item or armor)

Do bear in mind that the only real ranged weapons added by Botania at the moment require either Terrasteel (Thorn Chakram) or Gaia Spirits (Unstable Reservoir).

**Comment by Durpady** [comment]
To further differentiate the Dreamwood Bow from the Livingwood one, the latter could draw faster and shoot farther.  Some other Rune effects I couldn't fit in include homing and armor piercing, but I suppose the latter could be innate to Dreamwood.  Also, if you're up to it, certain Rune combinations could "synergize"... like Winter and Summer creating an "ice shell" underwater, with Summer activating (a tick) before Winter but in a smaller radius.

**Comment by jawdylawdy** [comment]
Might also be interesting if they had some sort of use for the lenses, though that wouldn't make much sense, as the lenses are for mana flow, not physical objects.

**Comment by MrKunji** [comment]
Well, then the bows would use Mana to fire an 'energy arrow' (and the bow could reference Dungeons and Dragons beacause of this)

**Comment by Yulife** [comment]
@MrKunji I like that idea a lot!
