### ISSUE TITLE
Particles do not respect the particles setting

### ISSUE THREAD

**Issue by MysteriousAges** [Vazkii/Botania#585]
I have my Minecraft client set to display decreased particles, but Botania shows the same number of particles as if it was set to normal. Additionally, when set to 'None', Botania still displays particles.

To reproduce:
Open video settings, set Particles to None. Place a Botania flower/Mana pool and observe particles.

**Comment by MrKunji** [comment]
Does not happen when the game's particles are disabled from CoFH configuration.

**Comment by Vazkii** [comment]
There's a config option in the mod to override the particle limiter in the vanilla options, check that to see if it's on.
https://github.com/Vazkii/Botania/blob/master/src/main/java/vazkii/botania/client/core/proxy/ClientProxy.java#L348

**Comment by MysteriousAges** [comment]
Assuming this is the line:

    # Set to false to always display all particles regardless of the "Particles" setting in the Vanilla options menu.
    B:vanillaParticleConfig.enabled=true

**Comment by Vazkii** [comment]
Try putting down a mana spreader firing a mana burst and seeing if there's any holes in it in Decreased. Also botania absolutely needs particles to function (you can't see things like mana bursts without them for example), so I opt to still show a few in Minimal.
