### ISSUE TITLE
Narslimus not working

### ISSUE THREAD

**Issue by GabeC1997** [Vazkii/Botania#587]
I built a Farm to gather slimes only to discover that the narslimus wouldn't absorb them...

Possible Reasons

1. When Big Slimes are broken down they cannot be used
2. Bug with version 163
3. Has to be in the same chunk (both are slime chunks)
![2015-02-20_14 54 04](https://cloud.githubusercontent.com/assets/11096190/6308721/95116f54-b914-11e4-81e9-c1a71681905e.png)

**Comment by Vazkii** [comment]
> When Big Slimes are broken down they cannot be used

That's intentional.
