### ISSUE TITLE
Lexica Botania changed font size

### ISSUE THREAD

**Issue by Yadokingu** [Vazkii/Botania#590]
After I shift-rightclicked the Terrestrial Agglomeration Plate with the Lexica Botania (which was the first thing I ever clicked with it, btw.) the font size changed to something slightly too large: https://i.imgur.com/Ag4DnPM.png
This does not seem to be reversable.

I sadly don't have a log from when it happend, but here is the latest, maybe it has some usefull information: https://mega.co.nz/#!eZZn0KSD!XAIOlNH9slATEx9X2Cv7NrBJwfcX5zkUbSmOrUP9PdY

**Comment by Vazkii** [comment]
What in the actual fuck? O.o

**Comment by Drullkus** [comment]
Lolwut

**Comment by Vazkii** [comment]
Yeah, I can't reproduce this.

**Comment by DaedalusGame** [comment]
And here I was hoping to find a solution to this somewhere. Time to go forge version meddling.

**Comment by DaedalusGame** [comment]
I have one fucking wish

A build of Dragon API that A) works and B) doesn't break everything under the sun.

Reika is breaking people's mods again~~~

**Comment by 1skandar** [comment]
It has something to do with the custom font hooks in Dragon API added in v4.

**Comment by Drullkus** [comment]
Gg @ReikaKalseki ...

**Comment by ReikaKalseki** [comment]
How exactly does the Botania font rendering work?

In v4, I added code that basically makes the FontRenderer delegate strings beginning with certain substrings to custom font rendering objects. This was done because NEI craps all over the font rendering code and most of the ability to use a custom font renderer properly is broken with it installed.

**Comment by Vazkii** [comment]
I don't have any, all I do is use setUnicodeFlag.

**Comment by ReikaKalseki** [comment]
Hm....the good news is that this may then be a simple fix.

**Comment by ReikaKalseki** [comment]
OK, I just added this for inclusion in v5.

`this.setUnicodeFlag(fr.getUnicodeFlag());`

Hopefully it fixes it; v5 will be out later this week, or, if you want, you can have a copy early to test.

**Comment by ReikaKalseki** [comment]
@Kolatra confirms that this worked. The problem is now resolved.

**Comment by ReikaKalseki** [comment]
v5 successfully fixes this issue.
