### ISSUE TITLE
Idea: Livingwood Fishing Rod

### ISSUE THREAD

**Issue by Durpady** [Vazkii/Botania#598]
Well, now that we have Mana Infused String, we have all the components necessary to build one of these.  Also, due to Anvil mechanics, vanilla Fishing Rods can't be infused with Timeless Ivy.  It'd be nice to have a Rod that doesn't break after a few uses.  It could have some sort of bonus effect/buff/whatever, but that's not really necessary.

**Comment by GabeC1997** [comment]
Maybe some fish that only it can catch?

**Comment by Vazkii** [comment]
Closing all misc ideas just to clean clutter, post them on reddit or the forums instead.
