### ISSUE TITLE
Items rubber band back to Daffomill

### ISSUE THREAD

**Issue by Yadokingu** [Vazkii/Botania#602]
See here: http://youtu.be/Ir0eWbQvm9s
It just started happening all of a sudden, don't know why or when. All my other Daffomills work fine. Breaking and replacing the flower does nothing.

log: https://mega.co.nz/#!fdwkwaib!XK5oP3l_58xBzo98WJNqp-97_0H1k9WwMwudJywAzkk
world DL: https://mega.co.nz/#!mUJSnIYI!DK9MzJdm9acz4LCuDjYS9lQpoCKgl2PwF6LQTEGYF1Y

**Comment by Yadokingu** [comment]
I put a water stream in the same place and items in it were transported without a problem. So there isn't some invisible obstruction. Ofcourse that isn't a solution, since I can't run water where the flowers are.
I also tried moving the Daffomill and open crate foreward a little. That didn't do anything either.

**Comment by Vazkii** [comment]
Ah, syncing issues. Your pool is nearly empty so the amount of mana in the daffomill is very inconstant, which causes things to move in the client but not server. Not really much I can do.
