### ISSUE TITLE
Request: Clarify Timeless Ivy description

### ISSUE THREAD

**Issue by Yadokingu** [Vazkii/Botania#603]
It took me forever to figure out that the three repair-items can't be stacked, but have to be spread out.

**Comment by MrKunji** [comment]
Have you ever seen a recipe that uses stacked items in a crafting table? '-'

**Comment by Yadokingu** [comment]
Now that you meantion it... I must have made way too many machine-recepies in AE. Still, it's somewhat unclear.

**Comment by MrKunji** [comment]
But it is a vanilla thing, normal crafting operations never used stacked items.

**Comment by Vazkii** [comment]
ಠ_ಠ
