### ISSUE TITLE
Rod of Unstable Resevoir hang

### ISSUE THREAD

**Issue by devryb** [Vazkii/Botania#605]
Got another server hang here this time I got information from the player likely involved that they were fighting a Gaia 2 Guardian with a Rod of Unstable Resevoir

http://puu.sh/gbmpm/41b53fac84.png

Version: 1.4-154

**Comment by Vazkii** [comment]
Could you get me a log?

**Comment by devryb** [comment]
Here's last 10 min of it when it hung, not sure if you need more
https://gist.github.com/devryb/dcd17447dc34350987c5

**Comment by Vazkii** [comment]
Do you have cauldron on your server per chance? Your stack trace points to a freeze in a vanilla method.

**Comment by MajorCooke** [comment]
According to the admin of my report, for when we opened ours, no.

**Comment by devryb** [comment]
We are using Cauldron
