### ISSUE TITLE
[164]Greater Gaia's projectiles still causing issues

### ISSUE THREAD

**Issue by MajorCooke** [Vazkii/Botania#606]
We're on version 164, but the exact same issue from https://github.com/Vazkii/Botania/issues/534 still persists. 4-5 seconds after spawning a greater gaia via sacrifice, it still causes the server to crash.

I'm also wearing KAMI armor and deflecting his projectiles if that helps.

Referenced it over there in case it's a KAMI bug itself with nothing anyone can do here.

**Comment by Vazkii** [comment]
Clone of #605
