### ISSUE TITLE
Lexica Botania tutorial not working?.....

### ISSUE THREAD

**Issue by SniperHauss89** [Vazkii/Botania#607]
Hello ^.^, I have attempted multiple times to go through the Lexica Botania tutorial but every every time I click the tutorial button all that appears is the message that tells you to follow the red arrows to learn the basics. That is where the problem is I don't see any red arrows no matter how many times I go back and click on the tutorial start button. I'm not sure this is a bug or if it's not fully implemented yet or what but I really look forward to getting into Botania ^.^ I have a friend that really likes it and knows the ropes but I'm just getting to the point where I want to start. any help is appreciated.

(side note - I'm running r1.5-164 but I know that there is a slightly newer build.)

**Comment by Vazkii** [comment]
It doesn't work when you have elven knowledge, that's a known issue.

**Comment by SniperHauss89** [comment]
oh ok well I made the one without elven knowledge and it didn't seem to work either....?

**Comment by Vazkii** [comment]
Are you using a texture pack? That might also be it, since it doesn't have the new texture. Either way it's bugged with elven knowledge so I'm keeping this issue open to remind me of that.

**Comment by SniperHauss89** [comment]
Ok yes it was my texture pack oddly even know it doesn't affect the Lexica Botania... anyway thank you probably would have taken me awhile to figure that out.
