### ISSUE TITLE
[Idea/Suggestion] Items dropped from an Open Crate are not pulled by the Ring of Magnetization

### ISSUE THREAD

**Issue by joshft91** [Vazkii/Botania#608]
I know that if you apply a redstone signal to the crate dropped items are not affected by flowers like the Hopperhock for an extra 10 seconds, but it would be nice to have the opposite effect if possible.

In my situation, it'd be nice to drop items without being instantly pulled by the ring of magnetization and then planted with a Rannuncarpus.

**Comment by dylanpiera** [comment]
I'd like this idea to happen

**Comment by Vazkii** [comment]
Closing all misc ideas just to clean clutter, post them on reddit or the forums instead.
