### ISSUE TITLE
Soujourner's and Globetrotter's sash not giving step assist when Botania is  installed with the Aether II

### ISSUE THREAD

**Issue by BiwaShiwaBiwa** [Vazkii/Botania#618]
Hi Vazkii, i've informed the Aether II devs of this issue and they advised me to let you know too. So, with the latest Forge 1307, latest Botania 167 and latest Aether II 1.1 something prevents the step-assist from both sashes (and also TiCon's Traveller's Boots, but not Thaumcraft's Boots of the Traveller and TT's / Thaumic Explorer's equivalents). Tested this issue with just Botania and forge and with Forge, Botania and the Aether II and it's only when the Aether II is present. Hope this helps, everything else works exactly as intended

**Comment by Vazkii** [comment]
LAN world?

**Comment by BiwaShiwaBiwa** [comment]
Non-LAN single player world and through a forge server

**Comment by Vazkii** [comment]
Confirmed an issue on the Aether end.
