### ISSUE TITLE
Birch Sapling does not convert to Jungle Sapling

### ISSUE THREAD

**Issue by lunaKM** [Vazkii/Botania#619]
Using FTB Infinity pack. Mana infusion with Alchemy Catalyst, toss Birch sapling in (HUD shows it can craft Jungle Sapling) get particle effect but no sapling.

**Comment by MrKunji** [comment]
Do you have an Endoflame near the Mana Pool?

**Comment by lunaKM** [comment]
OMG yes thanks, that was it.
