### ISSUE TITLE
Feature Request: Some sort of yellow Quartz

### ISSUE THREAD

**Issue by Durpady** [Vazkii/Botania#620]
So, we have Redquartz (red), and we have Blaze Quartz (orange).  We have Elven Quartz (green), Mana Quartz (blue), and Lavender Quartz (purple).  We even have Smokey Quartz (black).
So where is the yellow Quartz?
The options for the yellow ingredient are Sunflower/Flower/Dandelion Yellow, Glowstone Dust, and Gold Nugget... maybe but probably not Wheat.  Each option has downsides though: Gold Nugget is a little on the rare/valuable side for one to produce (effectively) just two blocks; Glowstone Dust is more associated with "light" than "yellow"; and Flowers/dye is already done by Lavender Quartz, so you may not want to do that again.
Hell, with yellow in the mix, you could even throw in "Rainbow Quartz", created (2 at a time) by combining one piece of each color (including regular/white) in the Crafting Table... it would shimmer like Gaia Spirits/Ingots/Spreaders.

**Comment by Durpady** [comment]
The more I think about it, the best option for this is the Gold Nugget, since thus far each Quartz type has a distinctly different source than the other types (Dust, Flower, Charcoal, Blaze Powder, Infusion, Trade).  "Glowquartz" would use Dust again (and be expected to glow), and "Sunquartz" would use Flower again.  Besides, "Golden Quartz" has a nice ring to it.

**Comment by Vazkii** [comment]
Closing all misc ideas just to clean clutter, post them on reddit or the forums instead.
