### ISSUE TITLE
Disintegration Lens

### ISSUE THREAD

**Issue by ruifung** [Vazkii/Botania#625]
By combining a Bore + Fire lens, any mined items will not be dropped.

**Comment by Vazkii** [comment]
You can't even combine these lenses. Non-issue.

**Comment by ruifung** [comment]
Well, its a feature request, not a issue...

**Comment by Vazkii** [comment]
Well, you could've specified that >.<

**Comment by ruifung** [comment]
Whoops, my bad.

**Comment by Vazkii** [comment]
Closing all misc ideas just to clean clutter, post them on reddit or the forums instead.
