### ISSUE TITLE
Resize categories icons in lexica from 48x48 to 64x64 to support old graphics card

### ISSUE THREAD

**Issue by Radviger** [Vazkii/Botania#627]
Hi, Vazkii!
I have an issue with botania on my pc:
In game in lexica botania on first page I can't see icons of categories, because that icons resolution unsupported by my graphics card, but when I resized the icons (in mod assets) to 64x64 it became to works perfectly. Can you make it 64x64 by default please? Thanks!

**Comment by Vazkii** [comment]
What the actual fuck

**Comment by kris545545** [comment]
@Radviger My Nvidia 210 GPU supports the 48x48 textures, and the Radeon 3600M in my laptop does too, so like @Vazkii said, what in the actual fuck is wrong with your GPU.

**Comment by zerotheliger** [comment]
its probably made by foxconn in china

**Comment by TheJulianJES** [comment]
@Radviger Please try to update your GPU drivers.

**Comment by zerotheliger** [comment]
actually what gpu do you even have

**Comment by Radviger** [comment]
Yes, it is Foxconn, and I can't update my gpu drivers because then I can't run Minecraft. @Vazkii, so can you make icons 64x64 by default? I know that not only me have this issue.

**Comment by TheJulianJES** [comment]
@Radviger Updating your GPU drivers should still allow to run Minecraft, what GPU do you even have?

**Comment by Radviger** [comment]
Intel(R) 82945G Express Chipset Family

**Comment by Radviger** [comment]
When I updating GPU drivers my Minecraft says me that "Pixel format not accelerated", but other games like Garry's Mod etc. still running and works perfectly.

**Comment by Vazkii** [comment]
Does minecraft even run properly for you at all? O.o

**Comment by Radviger** [comment]
Aside shaders and low FPS it works fine.

**Comment by Radviger** [comment]
I didn't find new and OpenGL compatible drivers for my GPU

**Comment by Radviger** [comment]
So I'm using Intel media graphics accelerator

**Comment by Radviger** [comment]
Can you just fix resolution plz?

**Comment by Vazkii** [comment]
Run "msinfo32" either through CMD-R or the Start search menu. Save an info file through File > Save and upload it somewhere, I want to have a look.

**Comment by Radviger** [comment]
Ok, there is: https://www.dropbox.com/s/ds9oire7fztfp5t/Sys.nfo?dl=0

**Comment by Vazkii** [comment]
Gah, that's a pain. I'll have a look at it sometime, you can use a resource pack for now.

**Comment by Radviger** [comment]
Thx!

**Comment by Entoarox** [comment]
there are actually still ^2 limited graphics cards in use these days????
(PS: you might want to resize to 64 anyway @Vazkii , even if modern graphics cards can work with non ^2 graphics, the ^2 graphics are still a tiny bit more efficient because of the binary nature of the things)

**Comment by Lazersmoke** [comment]
Will just resizing the images from 48x to 64x work, or will code need to change as well. Asking because I could resize the graphics, but am lost when it comes to rendering code :(

**Comment by Chaotic-Potato** [comment]
What?! Your graphics card cant support 48x48?! What?!

**Comment by TheJulianJES** [comment]
@Chaotic-Potato xD

**Comment by Lazersmoke** [comment]
@Vazkii I would attempt to fix this issue, but I can't find the rendering code that displays the categories... I am not entirely sure that it would need changing either! I have already resized the images but I'm not sure what the next step is.

**Comment by Chaotic-Potato** [comment]
What card are you using.

**Comment by Vazkii** [comment]
No more necroposting please.

**Comment by Vazkii** [comment]
32x32 yo
https://github.com/Vazkii/Botania/commit/d824024
