### ISSUE TITLE
Ender artefacts not showing up

### ISSUE THREAD

**Issue by ProgrammerHans** [Vazkii/Botania#632]
Vazkii, in my Lexica Botania book, i can't see all the things in the ender artefacts page. It's not that the items/blocks do not exist, they appear in NEI, but they don't show up in the Lexica Botania. Even if I search some of the amazing stuff(Corporea Sparks...) in the Lexicon Index, it didn't show up.
All the other pages is working fine. 
;(.
I am using Botania version r1.5-169
Screenshots:

Missing pages in Ender Arefacts:
http://i.imgur.com/c7cMHoB.png

Can't find it:
http://i.imgur.com/Ueguwf6.png

Thanks
SireHans

**Comment by TheMadmanofChaos** [comment]
You need to acquire elven knowledge first.

**Comment by ProgrammerHans** [comment]
Thx, my fault
