### ISSUE TITLE
Morph and The Ring of Far Reach in the Direwolf20 Pack

### ISSUE THREAD

**Issue by DynamicSurbus** [Vazkii/Botania#635]
If you have morph installed and use have the Ring of Far Reach equipped (I also had the Globetrotters Sash and morph into different creature (I did Silver Fish, Book(from Mystcraft) and the default player) over and over the Ring of Far Reach's reaching distance gets farther to place and break blocks but not with tile entities and regular entities (also re logging in a single player world will fix this till you morph again) but the max distance seems to be around 85 blocks. I have Updated all the mods in the direwolf20 pack if an update was available and I could find it, (I have also added Equivalent Exchange 3, thermal Dynamics, and MmmMmmMmmMmm). In testing this I have also found that the default reaching distance is a Little more than 4 blocks and the interacting with entities increased to a 5 block distance and blocks to a 9 block distance so this is 1 block increase for entities and a 5 block increase for blocks while the book says an increase about three blocks.

![2015-03-07_20 41 56](https://cloud.githubusercontent.com/assets/7884105/6544434/bb793128-c50c-11e4-8ca1-ab8077a65778.png)
(I use waila to show that you can reach that far in this pictures)

![2015-03-07_20 53 32](https://cloud.githubusercontent.com/assets/7884105/6544429/85f37e6e-c50c-11e4-8ac5-904240733f85.png)

**Comment by Vazkii** [comment]
Fffffffff... I'm not fixing this.
