### ISSUE TITLE
Translation tips

### ISSUE THREAD

**Issue by Xottab-DUTY** [Vazkii/Botania#636]
I think that this issue will be very useful for translators. There are words that can not be translated unambiguously. Tip from the author of modification may ease the task.

Idea: translators ask questions and Vazkii answers these questions.

So this topic should be open at least for a long time :wink:

**Comment by Xottab-DUTY** [comment]
First question: what "Corporea" means? This word can not be translated?

**Comment by Vazkii** [comment]
This is not a forum, this "issue" is invalid. You can figure it out by context, or just don't translate it at all.

**Comment by Xottab-DUTY** [comment]
Okay! =)
