### ISSUE TITLE
TC silktouch Hammer + mana pools = restore from backup.

### ISSUE THREAD

**Issue by mst3in** [Vazkii/Botania#644]
Please don't take it personal because this mod is very original and deserves respect...but damn!  You've taken (map) corruption and (player) frustration to a whole new level.

**Comment by Nincodedo** [comment]
A crash log or description of what happened would probably be useful.

**Comment by mst3in** [comment]
There is no crash log.   The server doesn't crash.  All players time-out.  The server still thinks that players are logged in (they are not) and from then forward, no one can connect again.   Restarting the server works for a few minutes, but by "work" I mean you can connect but there are strange serialization and lag issues...and shortly later the timeout monster reappears.  The solution for this situation is to restore the server from backup to before the mana pools were broken.

Lay down a pair of mana pools side by side, and start filling them with Dayblooms and a few spreaders.    Get yourself a TC hammer with silk touch and break the pools = oh noes.

We use Bevo's pack.

If there are other mods in use below botainia stuff but in the same chunk...are there any interactions?

**Comment by mst3in** [comment]
Perhaps a related issue, if you break livingwood/livingrock with a TC hammer, again with silk touch, only the targeted living-block is broken as a living block.  The adjacent living blocks break as oak/stone.

**Comment by Vazkii** [comment]
Are all the mods in the pack updated?

**Comment by KamranMackey** [comment]
@Vazkii No. The pack is currently at pack version 12, which was released 23 days ago, and a LOT of mods (including yours) have been updated since then.

**Comment by Vazkii** [comment]
Report this to BevoTechPack/BevoTechPack/ then.
