### ISSUE TITLE
Spark visual glitch

### ISSUE THREAD

**Issue by SimonRefs** [Vazkii/Botania#645]
Visual bug where a Spark directly beneath a Mana Pool will repeatedly appear directly above it, around every 20 seconds. Noticed it in my modded Singleplayer Survival World, where it caused lag spikes, and I was able to recreate it in Creative Mode with only Botania and Baubles installed.

Forge: 1291
Botania: 169
Log Pastebin: http://pastebin.com/dePTgcHA
Example of the Visual Bug: 
 - http://imgur.com/Q427yqq (how it was set)
 - http://imgur.com/a3W39H2 (the visual glitch)

**Comment by Vazkii** [comment]
I get the visual issue, it's caused by a vanilla bug, but it makes the sparks look better when in pylons. I don't get any lagspikes, so I doubt that the spark updates are the cause of the ones you're getting.
