### ISSUE TITLE
Lexica Botania Visual problems

### ISSUE THREAD

**Issue by drago87** [Vazkii/Botania#646]
i'm using version Botania r1.5-169 and forge 10.13.2.1291 i'm also using fastcraft 1.19

https://www.dropbox.com/s/4hfaavz2wto5w8z/2015-03-13_12.40.16.png?dl=0

it dosent seam to be eny different when changing the GUI scale

**Comment by Kolatra** [comment]
Update DragonAPI.

**Comment by drago87** [comment]
i have the DragonAPI 1.7.10 V4c and thats the newest on the site
