### ISSUE TITLE
MineChem crash when looking up used-in recipes for the Terra shatterer

### ISSUE THREAD

**Issue by AlfieSR** [Vazkii/Botania#647]
No idea exactly what causes this as none of the components nor their components cause this issue, but attempting to use NEI to look up what a Shattered breaks down into results in a permenant game lockup. No crash nor errors in logs, but the game refuses to respond even when left alone for a few hours.

**Comment by Vazkii** [comment]
Probably not on my end, ask on the MineChem repo.
