### ISSUE TITLE
Idea: Literally ANYTHING to Break Snow

### ISSUE THREAD

**Issue by jawdylawdy** [Vazkii/Botania#648]
I don't even care if it drops the snowballs, just as long as it gets rid of it. Ideally, in a similar fashion to the horn of the wild. 

(Also I am sorry for the likely rude tone of this request, I am tired.)

**Comment by YoruToboe** [comment]
I like the idea, maybe a flower of the spring, it breaks the snow and give bone meal effect on the grass, you could make flower from each season, winter gives snow, autumn makes the trees lose their leaves and summer. . . I don't know
