### ISSUE TITLE
Suggestion: Fat potato

### ISSUE THREAD

**Issue by yrsegal** [Vazkii/Botania#655]
So, the tiny potato is always confident and happy. Maybe someone wants a pet, though, they can give attention to!
So, I'm proposing the fat potato. Crafted with 9 tiny potatos, It starts out sad. For every right click, it gets a little happier. Once it's fully happy, it will look like a bigger tiny potato. But, over time, it will miss you and get sadder. So, you've got to cheer it up again!
This idea has no real use, I just thought it would be cute. Ya know, like the tiny potato.

**Comment by Vazkii** [comment]
For fuck sake.

**Comment by yrsegal** [comment]
What? I thought it was a good suggestion... Can you at least say why you don't like it?
