### ISSUE TITLE
Flugel Tiara, Globetrotters Sash not functional in LAN 

### ISSUE THREAD

**Issue by Pheonix69Dragon** [Vazkii/Botania#668]
Greetings!
First things first, Botania is absolutely brilliant! 
My sons Will, Liam and I play on in LAN mode through the AT Launcher. 
The pack is not one of the maintained or preconfigured ones (It is one we put together)
I did very little in the config files aside from turning down some difficulty (my sons are 10 and 9)
If a list is required then I will post.
Now for the problem: after battling the Gaia to get the crafting elements for the Flugel Tiara and Globetrotters Sashes for all three of us. The Tiaras and Sashes only function for the host, 
Crafted Mama Mirrors and Greater Bands thinking it was a lack of Mana to no luck.
I have searched for simular issues and found none. I have copied the world save to each of the three PCs and the problem persists, only the host can benefit from the items
Next steps?
Once more thank you for your brilliance and hard work you have put into Botania

**Comment by Vazkii** [comment]
That's a longstanding bug in baubles itself. I'm afraid I can't help you with it, but you can try hosting a local server on your computer if it's critical.

**Comment by Pheonix69Dragon** [comment]
Thank you Vazkii, for the reply and a possible solution.
