### ISSUE TITLE
Issues with the warp mana lens

### ISSUE THREAD

**Issue by TheMadmanofChaos** [Vazkii/Botania#670]
Botania 170
Forge 10.13.2.1230

Needing to transport mana a fair distance, I wanted to try out the warp mana lens before investing in the rails for a mana pool cart. I first tried an elven spreader, then after remembering it would only send mana if the destination could accept it(Which the force relay needed wouldn't), I broke the elven mana spreader to find that the lens didn't drop with it. Spawning in a new one to replace it, I placed a redstone mana spreader, a redstone clock(Extra utilities, basically emits a redstone signal once a second), added the lens, then after the first burst was fired I received this crash: http://pastebin.com/mU2Ju66A

Let me know if you need any other info, I'm often The Madman in your IRC channel.

**Comment by Vazkii** [comment]
One of your mods is distributing a botania API without the package-info. This causes the FML to load it even if it's outdated.

**Comment by TheMadmanofChaos** [comment]
Fair enough, some testing has narrowed it down to witching gadgets. Thank you for your time and assistance on this matter.

**Comment by Durpady** [comment]
You can "trick" Spreaders with Mana Prisms.
Attach a Phantom lens to the Spreader, and attach whatever lens you want to use to the Prism.  Arrange it so the block you want it to hit is behind the prism, and behind that block place another Mana Pool.
I discovered this trick in a (successful) attempt to combine the function of an Entropic(+Potency) lens with a Gaia Spreader, but it sounds like it'd be useful here, too.
