### ISSUE TITLE
Endoflames activate without consuming the fuel if the fuel is pulled in by the Ring of Magnetization at the same time

### ISSUE THREAD

**Issue by InvaderAZ** [Vazkii/Botania#671]
Using the latest Botania r1.5-170

Steps to reproduce:

1. Have Ring of Magnetization equipped
2. Throw block of coal at Endoflame
3. Back up in feeble attempt to let block get consumed before Ring sucks it in
4. Ring grabs block of coal at the same time the Endoflame 'consumes' it
5. Block of coal returns to inventory but Endoflame is happily producing mana

**Comment by Vazkii** [comment]
I can't reproduce this, if you can make a video that'd be great.
