### ISSUE TITLE
Memory leak experienced in 170

### ISSUE THREAD

**Issue by Alaberti** [Vazkii/Botania#676]
I noticed my memory usage climb dramatically when updated to version 170 this morning. I have 4GB allotted to account for shaders and typically see 4.5-5.5GB out of 16 used over extended play. After updating, I noticed memory usage had climbed to an astounding 10GB before minecraft was force-closed.

The only blocks in our world with Botania (this is a fresh world, barely a month old) are a mana pool and the flowers. Returning to 169 solves the issue. Checked with my other players, confirmed they were also experiencing the abnormally high memory usage.

Forge 1307, Botania 170

**Comment by Vazkii** [comment]
https://github.com/Vazkii/Botania/compare/6c922ebc8f22394295d9d6e12541356c979aaf9d...f04c50a2d7aebe6cd4a24deb147f02c6f2305197
This would be the commit set that could potentially cause this. Nothing here looks suspicious. Player told me to tell you to get a heap dump.

**Comment by Vazkii** [comment]
I need some more info about this. Logs of your server and client, list of mods, cauldron or forge, can you reproduce in singleplayer or with botania only, etc.

**Comment by Alaberti** [comment]
I'm just now finding time to properly test. I will try to get you the information you're requesting ASAP inbetween real-world stuff. Thank you for your understanding!

**Comment by Alaberti** [comment]
Modlist: https://docs.google.com/spreadsheets/d/1Pfm-2ABofwggXsTeAWjnwJWGsJjzfEIcuyy7patDjls/edit#gid=0 [Disclaimer, using Fastcraft, Optifine, Gregtech. The first two enable the pack to be playable for most of my players. The third is a request for a specific player, and if he weren't a great friend of mine it wouldn't even be a conversation)

Forge 1307, issue also seems to happen with 169, so I have reason to believe it's not Botania but another mod. Testing will take time but I will start by removing Botania in a few minutes and letting the client run and watch memory usage. It doesn't tend to become noticeable until about 15-20 mins in unfortunately.

Server/Client logs are a little big and have currently frozen Pastebin, so that will also take a little bit. I'll provide them to you fresh with this next test.

**Comment by Alaberti** [comment]
http://pastebin.com/TZNi14fP This is the out of memory error I received. I give Java 4GB and have 16GB total and other than Chrome had nothing significant up.

**Comment by Vazkii** [comment]
Better off, does it happen /without/ botania?

**Comment by Vazkii** [comment]
Try removing Witching Gadgets.

**Comment by Alaberti** [comment]
Taking out Witching Gadgets keeps it at a pretty steady 3-3.5GB. I had also removed Botania so I will do a confirmation test that it's not related, but it seems like Witching Gadgets is the culprit.

**Comment by Alaberti** [comment]
169 doesn't exceed 4GB. Last test for 170 again, but I think it's good. I think we found the culprit. Thanks!

**Comment by Vazkii** [comment]
Confirmed as a Witching Gadgets issue then?

**Comment by Alaberti** [comment]
Confirmed.
