### ISSUE TITLE
Elven Lexica crashes game when attempting to read any section

### ISSUE THREAD

**Issue by Harvestfarmer** [Vazkii/Botania#677]
The game crashes when attempting to read any section of the Lexica Botanica after receiving the updated version from the Alfheim portal. It is possible to open the book and view the sections, but selecting them instantly causes the game to crash due to an IndexOutOfBounds error. However, it seems that by recreating the non-Elven Lexica and reading it's sections, it has resolved the issue and the Elven Knowledge Lexica can be read as normal.

Crash Log: https://gist.github.com/ccbc9f8bf64c6a6084be.git
Forge Log: https://gist.github.com/74ed3c1157a7311704dd.git

**Comment by Vazkii** [comment]
Update Enchiridion.
