### ISSUE TITLE
Pure Daisy Issue

### ISSUE THREAD

**Issue by BuckitHead** [Vazkii/Botania#679]
Version 370
Forge 1307
Using Cauldron(This issue just started on updating Botania from 369)
No Optifine

Pure Daisy- When placing wood or stone around it this issue has been happening. 

Wood placed, after it transforms you use a axe to pick it up and you get back the original wood, when you place it back down it transforms again quicker and you finally get the living wood.
This happens with Stone as well.

**Comment by BuckitHead** [comment]
One of the players on the server let me know that it visually changes, but if you wait it out it will look like it's changing again then you good to pick it up

**Comment by yrsegal** [comment]
This has been a bug for a while in botania; your client thinks the Pure Daisy transformed the wood/stone before the server knows it happened. Right-click the livingwood/livingstone to see if it's actually transformed.

**Comment by BuckitHead** [comment]
I have been running this on many servers for along time. I have never seen this. If you bust out one of the pieces of wood after it fakes the trans and place stone down it will transform the stone asap. This is something we are just seeing after update to 370. I get the client server sinc but this is different. After the first fake transform(1-2 min) its like another min + before it finishes the final. Server is not this slow

**Comment by BuckitHead** [comment]
Back up to 369 and the issue goes away....

**Comment by Vazkii** [comment]
Where are you getting these numbers? The latest build is 170, not 370.

**Comment by BuckitHead** [comment]
I'm sorry.... I'm playn your mod in the future Hehe.  Again sorry for the number mixup .
