### ISSUE TITLE
Shimmering Mushrooms don't pop up

### ISSUE THREAD

**Issue by ShadowLord0** [Vazkii/Botania#680]
Latest version of Botania (r1.5-170)
Latest recommended version of Forge for 1.7.10
No Optifine

The Shimmering Mushrooms do not pop up off the ground when exposed to high levels of light (higher then 9) like the vanilla mushrooms do. (also results in them being able to be planted in any light level)
Proof: http://imgur.com/FhzSExl

**Comment by Vazkii** [comment]
Intended.

**Comment by ShadowLord0** [comment]
Ah ok was not aware it was.

**Comment by MuscaTzetze** [comment]
how can i make multiple mushrooms from one?

**Comment by Hubry** [comment]
* Good job posting on a 6 year old issue report. Next time please ask questions like this on Vazkii's discord or the subreddit.
* You don't.
