### ISSUE TITLE
Mana spreader pointing two directions at once

### ISSUE THREAD

**Issue by Quojil** [Vazkii/Botania#681]
https://i.imgur.com/F940cEv.png

The fake beam always points left no matter which direction I place the mana spreader. The real beam works just fine.

Edit: Appears to have stopped happening after a while

**Comment by yrsegal** [comment]
do you have another mana spreader pointing towards that one?

**Comment by Quojil** [comment]
Nope.

**Comment by Vazkii** [comment]
Server or client? Logs, etc.

**Comment by Quojil** [comment]
Client. It still happens on occasion, though it may be optifines fault. Here is my most recent log (it is happening at time of copy/paste):

http://pastebin.com/raSLNM5Y

**Comment by Vazkii** [comment]
Can you get it to happen without optifine?

**Comment by Vazkii** [comment]
Closing for now due to lack of updates, feel free to update later.
