### ISSUE TITLE
Idea: Use IMC or API  to blacklist items from being attracted the magnet ring

### ISSUE THREAD

**Issue by LordIllyohs** [Vazkii/Botania#683]
Currently the way to blacklist items from the magnet ring is to open a PR and them to the private list. Using IMC or this API for adding items to the blacklist would remove the need to make a PR for this.

**Comment by nabijaczleweli** [comment]
The simplest way for this would be to modify `ItemMagnetRing.BLACKLIST` (which you can reflect into and change yourself anyway).
The more complex and versatile way would be to have some sort of a `Filter`/`Matcher` list and checking against that (which would require Vazkii to support it).

Relevant lines: [ItemMagnetRing.java#L48](https://github.com/Vazkii/Botania/tree/master/src/main/java/vazkii/botania/common/item/equipment/bauble/ItemMagnetRing.java#L48), [ItemMagnetRing.java#L114](https://github.com/Vazkii/Botania/tree/master/src/main/java/vazkii/botania/common/item/equipment/bauble/ItemMagnetRing.java#L114).

**Comment by Kubuxu** [comment]
@nabijaczleweli To modify this list one would have to include BotaniaAPI. IMC was created to replace plain API in cases like that (ItemStack sending).
