### ISSUE TITLE
Breaking elven mana spreader with primordial axe causes crash

### ISSUE THREAD

**Issue by echohunter221** [Vazkii/Botania#692]
I already reported this to BluSunrize, the Witching Gadgets guy, and he says that you might be missing a null check. It's only the elven mana spreader, not the normal one. Crash log:  http://pastebin.com/Qg4uyyms
My other open issue on the Witching Gadgets Github: https://github.com/BluSunrize/WitchingGadgets/issues/29

**Comment by Vazkii** [comment]
https://github.com/BluSunrize/WitchingGadgets/pull/33/
