### ISSUE TITLE
Flowers not saving their bound Mana-Spreader

### ISSUE THREAD

**Issue by knoxz** [Vazkii/Botania#693]
Playing on a Server with Infinity 1.2.1 Bontania Version r1.5-165.
Flowers are not saving their bound Mana Spreader. Tested it for Dayblooms, Endoflames and Thermalilys. As soon as the chunk is unload they reset.
I found an issue someone had in November, I guess I have the same.
Server is running a Cauldron/Forge.

**Comment by Vazkii** [comment]
a) Update Botania.
b) Does it happen without Cauldron?

**Comment by knoxz** [comment]
Gotta wait until the server owner updates to the latest infinity version and I dont think they remove cauldron.
I dont have a privat setup to test it own.
I am sorry :-(

**Comment by Vazkii** [comment]
I'll close it for now then. When you've managed to test it give me a poke.
