### ISSUE TITLE
Minecraft crashes when I open the second page of the Natura Shedding entry under the Miscellaneous tab

### ISSUE THREAD

**Issue by Guy370** [Vazkii/Botania#694]
Crash report: http://pastebin.com/rpSG6ZER
Config options: http://pastebin.com/7LJC3Mhu

I didn't change much in the configs besides deleting all shedding mob options. I don't have any idea as to why this happened though.

**Comment by Vazkii** [comment]
Delete your config and have it redo the shedding options.
