### ISSUE TITLE
Have to rebind force relay after restarting the game.

### ISSUE THREAD

**Issue by go371211** [Vazkii/Botania#701]
As title mentioned, BTW, i am using FTB Infinity 1.3.4.

**Comment by Vazkii** [comment]
SMP, Cauldron? Mod list (with versions), are you using the latest version? Etc...

**Comment by Vazkii** [comment]
Closing for lack of info.

**Comment by iarspider** [comment]
I have the same issue. 
Botania 191
Mod list: http://pastebin.com/r4c5fDTw
