### ISSUE TITLE
Crash to desktop when clicking a category in Lexica Botanica

### ISSUE THREAD

**Issue by itanshi** [Vazkii/Botania#702]
Version is 170.
Modpack is Regrowth .7.2
This is on a server.
Justification is set to false.
I crashed before and after I removed the botania config file.
Before: http://pastebin.com/pK8w8Hrx
After: http://pastebin.com/7SkSJ5eV

Single player works without issues.

Thank you.

**Comment by Vazkii** [comment]
Update enchiridion.

**Comment by itanshi** [comment]
Just noticed, we are running the latest Enchiridion 2-1.7.10-2.0e.jar, or did you men Enchiridion 1? (I'm inclined to think Ench 2)
