### ISSUE TITLE
Weird rendering crash with excaliber.

### ISSUE THREAD

**Issue by SkeletonPunk** [Vazkii/Botania#705]
Whenever I try to use the excalibur it crashes.
http://pastebin.com/RvFAK5vw
I only have botania and baubles in my instance.

**Comment by Vazkii** [comment]
Oh, god dammit. Install CodeChickenCore for now, I'm using the class from there instead of the one in botania itself by accident.

**Comment by SkeletonPunk** [comment]
Yeah, I figured that was the problem when it mentioned something about chickens lol
