### ISSUE TITLE
how to make multiblock of mana pool?

### ISSUE THREAD

**Issue by oks1998** [Vazkii/Botania#706]
i saw the changelog in 173version got said about the multiblock of mana pool, when i place the mana pool in 3x3 nothing happen?
its that a bug or just my misunderstand or wrong method?

**Comment by kurokuno** [comment]
well assuming this is ether a joke or date derp its April 1st so not the entire changelog is legit

**Comment by oks1998** [comment]
Really? But the changelog looks like is normal update..so thermalily also not yet  remove the cooling time?
