### ISSUE TITLE
Ring of Loki/Aesir not working?

### ISSUE THREAD

**Issue by MajorCooke** [Vazkii/Botania#709]
For some reason the Loki portion of the ring is not working for me. I've tried to do everything and I just can't seem to get it to work. All I've got is one regular block highlighted, and nothing else seems to do anything.

Also I think the description might be too vague.

Yes, I had bare hands.

EDIT: Taking it off and putting it back on after experimenting finally showed the many blocks I had interacted with but it wasn't updating to show it until AFTER I took it off, and put it back on.

EDIT 2: Shift right clicking while aiming at nothing makes the coordinates stick for the block highlights.

There also doesn't appear to be any method of resetting the ring, other than to delete it and give it back.

**Comment by Vazkii** [comment]
¯\_(ツ)_/¯
