### ISSUE TITLE
Excalibur cannot be enchanted

### ISSUE THREAD

**Issue by KaiserYoshi** [Vazkii/Botania#710]
Unsure if this is intentional or not, but it is definitely a glaring shortcoming. No enchanting means no Looting, no Sharpness, none of those things swords are awesome for. Currently, a Terra Blade with Sharpness 3 out-damages Excalibur, which feels wrong.

(it's also misspelled Excalib**e**r in game.)

**Comment by Vazkii** [comment]
Ah, yes, it's the good old "unbreakable items can't be enchanted" problem. I'm fairly sure there's a way around it, I'll look into it~
Also, the e is intentional.

**Comment by Entoarox** [comment]
@Vazkii You could give it durability and then use the 'Unbreakable' NBT tag that has been added in 1.7.2, that should allow enchanting while also making the item unbreakable.
