### ISSUE TITLE
huge number of mana burst entities on server after a while

### ISSUE THREAD

**Issue by User12123** [Vazkii/Botania#711]
Running the Regrowth modpack v .72.

Server has been running for a while, several weeks. 

Last few days we noticed performance dropping. What seemed to be the cause was that there were 140,000 mana burst entities in the world. did a killall on them and after a couple of hours it seems to be happening still. about 1000 entities after about 2 hours of uptime. We have less than 100 spreaders in the world right now.

**Comment by Vazkii** [comment]
Hm, I've seen this happen in Forgecraft. (ping @TTFTCUTS). Could you possibly send me your world files so I can have a look?

**Comment by User12123** [comment]
My world backups are about 270MB zipped. I'll upload them to google drive and give you the link.

**Comment by User12123** [comment]
Here is a download of our latest backup. 

https://drive.google.com/file/d/0By4BgahWpbUsRzZwOWpVY1RMamc

**Comment by Vazkii** [comment]
I can't reproduce it, but I'll leave it open in case someone wants to add to the discussion.

**Comment by User12123** [comment]
I'll try to get a world backup at a time there are lots of mana bursts. Would that be of help?

**Comment by Vazkii** [comment]
That would be better, if you can.

**Comment by User12123** [comment]
I'll need to get Opis back on the server but it is certainly possible. I have to do a "cofh killall mana" at least once a day right now.

**Comment by User12123** [comment]
Here is a world backup. When I made the backup there were about 2900 mana burst entities as reported by Opis.

Hope it helps.

BTW, mod list is Regrowth .73 modpack plus Morpheus, Servertools, Servertools-backup, and Opis

https://drive.google.com/file/d/0By4BgahWpbUsYWRZbnZMWGFYbzQ

**Comment by Vazkii** [comment]
I have 66 entities in the world when I load that backup. Possibly because the bursts are in unloaded chunks. Can you find out their position?

**Comment by User12123** [comment]
Hrm.

I actually tried to find coords for some mana bursts but I didn't see anyway to have opis tell me. 

When I get home tonight I can get you the coordinates to where  peoples' bases are.

**Comment by User12123** [comment]
Also, if you can tell me how to find the coordinate for mana bursts in opis I can do that.

And if it would be useful I'm willing to give you login/op rights to my server.

**Comment by Vazkii** [comment]
I have no idea how to find coordinates with opis, that's why I asked you if you can :V 
I've seen this sort of issue in FC as well, but it's a pain to debug because I'm fairly sure it has to do with some obscure chunkloading mechanic.

**Comment by User12123** [comment]
So the three bases that have the most botania infrastructure are at the following cords. 

-258 1576
-2463 3639 - most mana spreaders removed
-137 504

When getting this, I noticed something interesting. When I logged into my server there were about 3500 mana bursts. I teleported to the bases and each base I visited caused a bunch of mana burst entities to disappear. By the time I visited each base the mana burst count went from 3500 to 20.

Two of the bases were chunkloaded with railcraft anchors the third wasn't chunkloaded except one chunk that was being loaded by a witchery poppet shelf.

**Comment by User12123** [comment]
Oh, and while I can't find cords for individual mana bursts I did discover that sorting chunks in opis by entity count will give me a good idea as to which chunk has most of the mana bursts. At least on my server since there are not tons of entities normally.

**Comment by Vazkii** [comment]
I'll need confirmation if that commit fixed it. When 176 is out try seeing if it still happens.

**Comment by User12123** [comment]
Will keep an eye out.

**Comment by Vazkii** [comment]
Does it still happen with the chunk checking changes in the latest version?

**Comment by User12123** [comment]
I haven't had a chance to start up Minecraft yet since the update. Work is crazy. =)

I will consider this done and will let you know if I find otherwise in the future.

**Comment by Vazkii** [comment]
Sure.
