### ISSUE TITLE
Botanurgist's Inkwell cannot create the TC Research Table

### ISSUE THREAD

**Issue by SynfulChaot** [Vazkii/Botania#713]
For some reason, the Botanurgist's Inkwell doesn't create a TC Research Table when used in place of the standard TC Inkwell.

**Comment by Parker8283** [comment]
This may be more of a problem on Thaumcraft's end, though I don't know.

**Comment by Vazkii** [comment]
It's not a problem, it's that the table creation code is in the item, not the block, so I can't adapt it without messy reflection.
