### ISSUE TITLE
Agricarnations fertilizing petal blocks

### ISSUE THREAD

**Issue by KaiserYoshi** [Vazkii/Botania#715]
See picture. Agricarnations think petal blocks are growable plants, and throw away mana trying to fertilize them.

Forge 10.13.2.1291
Botania r1.6-173

![2015-04-02_11 48 39_2](https://cloud.githubusercontent.com/assets/9879642/6970040/416321ea-d930-11e4-8c27-7adbec67d35e.png)

**Comment by Vazkii** [comment]
derp
