### ISSUE TITLE
Ring of Odin and Ring of Aesir Stack to get 2 two extra bars of health

### ISSUE THREAD

**Issue by kyahco** [Vazkii/Botania#717]
It appears having two Rings of Odin or two Rings of Aesir does not stack health (ie. will only every give one bar of health) but when you give have one Ring of Odin and one Ring of Aesir it does stack (ie. It give you 2 extra bars of health, making for a total of 3). 

Also, when you take off one of the rings if you have two of the same rings you "fake die" (as you can see in the pics below), as in your character appears in a dead position, but you are still alive and able to walk around with out ever getting the death screen.

Pics: http://imgur.com/T5ajgL0,tIE5t88,C4QgNSj,x2oAxnq

(This is with Botania only on single player)

**Comment by Vazkii** [comment]
In all honesty, this really is a non-issue since you can't possibly have the two rings in a normal world.
