### ISSUE TITLE
Are Gaia Guardians supposed to disable a Tainted Blood Pendant's effects?

### ISSUE THREAD

**Issue by TennePG** [Vazkii/Botania#723]
I tired fighting a Gaia Guardian and when the fight started, the blood pendant's effect was disabled. It never said anything about that in the Lexica Botania, so I'm assuming that this might be a bug.

EDIT: If it isn't a bug, would it be possible to write something in the Lexica about it?

**Comment by jawdylawdy** [comment]
I think Gaia 2.0 removes all buffs (at least that's what I remember from the book), though I may be confusing it with something else.

**Comment by TennePG** [comment]
I read through the Lexica on both entries for the Guardian of Gaia, it doesn't say anything about removing all effects, except for the fact that it disables the beacon's effect, if it has one.

**Comment by TheMadmanofChaos** [comment]
The reason this happens is due to how The Gaia Guardian(Both variations) removes the effect of the beacon for the fight. It doesn't effect the beacon itself, instead it basically keeps checking the player for potion effect with a duration of X or less, if there are there then removes them. This in turn effects anything that functions by casting the same effect every few seconds with a low duration, not just beacon used for the ritual or beacons in general.

**Comment by TennePG** [comment]
Well, I'm not sure if this is the best solution, but maybe adding in a Gaia Beacon(Three elementium on the bottom, vanilla beacon in the middle and alfglass in a helmet shape) might be a fix for that. The basic explaination of what it could do would be that it's just for the Gaia arena. It would just sit there on top of a 3x3 mix of four elementium blocks and five manasteel blocks so that you can summon the Guardian of Gaia. Even though that probably isn't going to be implemented, it would definitely fix the problem.

**Comment by MrKunji** [comment]
@TennePG, the beacon's platform can be of any metal, not only Manasteel and Elementium.
Also, the effects from any Blood Tainted Pendant are disabled because their short duration, so the Gaia Guardian (and v2) disable short effects.

**Comment by TennePG** [comment]
I was making a suggestion for a completely separate idea for a different beacon .-.

**Comment by MrKunji** [comment]
Oh well, at least the second part of what I said wasn't in vain '-'
