### ISSUE TITLE
[Bug] Mana spreader not dropping lenses

### ISSUE THREAD

**Issue by DarkLight66** [Vazkii/Botania#724]
When a mana spreader is broken, any lenses that were on it just disappear. Happened with a normal mana spreader with potency lens and another one with potency + velocity lens. Used version 174.

**Comment by kurokuno** [comment]
this has been a long running issue for many versions you can remove them i think its by shift right clicking with a wand before breaking them i would suggest that till its fixed unless its intended behavior

**Comment by benedict42** [comment]
This also destroys any wool that you put on them.
