### ISSUE TITLE
Botania lag (20-30fps)

### ISSUE THREAD

**Issue by sonicbrandyn** [Vazkii/Botania#734]
Whenever i go near my mana farm: http://prntscr.com/6rplst
I get extreme lag i go down from 70=90 fps (I normally run 150-250 in vanilla but i have a load of mods)

**Comment by Vazkii** [comment]
I could use screenshots of your profiler (Shift-F3) when you're on the area vs when you're not. An FML log would be appreciated too.

**Comment by sonicbrandyn** [comment]
Okay <3 (btw i love botania, and thanx for the fast reply)  http://prntscr.com/6rpqkh

**Comment by Vazkii** [comment]
Particle /tick/ out of all things causing lag? That's odd. Can you reproduce this setup with only botania and see if it still happens?

**Comment by sonicbrandyn** [comment]
Heres when im not http://prntscr.com/6rpryb

**Comment by sonicbrandyn** [comment]
Just a side note im on a server

**Comment by Vazkii** [comment]
Nevermind. I'm wrong. Your particle tick is causing 2% of overhead, that's not where the lag is coming from. I don't want you to open the particles entry, I need it on a higher level.

**Comment by Vazkii** [comment]
You don't have a high amount of particles in the world (pW: 546, that's pretty low). So the issue has to lie somewhere else.

**Comment by sonicbrandyn** [comment]
Tick? http://prntscr.com/6rptol

**Comment by Vazkii** [comment]
Root would help.

**Comment by sonicbrandyn** [comment]
Where do i find root?

**Comment by Vazkii** [comment]
It's the higher level.

**Comment by sonicbrandyn** [comment]
Oh nvm http://prntscr.com/6rpw4d

**Comment by Vazkii** [comment]
Can you compare your root and your root.gameRenderer in and out of the laggy area?

**Comment by sonicbrandyn** [comment]
http://prntscr.com/6rqfhy http://prntscr.com/6rqfrv

**Comment by Vazkii** [comment]
Does that area still lag if you removed your hydroangeas?

**Comment by sonicbrandyn** [comment]
Would this tell you? http://prntscr.com/6rqlp4

**Comment by sonicbrandyn** [comment]
Im confussed?
Is my problem going to be fixed?

**Comment by Vazkii** [comment]
I've done some optimizations to that code, it *should* be better next version.

**Comment by sonicbrandyn** [comment]
When will it be released?

**Comment by sonicbrandyn** [comment]
The issue persists

**Comment by sonicbrandyn** [comment]
EDIT: ITs allot worse

**Comment by Vazkii** [comment]
It's worse with 175?

**Comment by sonicbrandyn** [comment]
Yes, Much AND I Have half the amount of hydrangeas

**Comment by Vazkii** [comment]
Alright, I'll have a look at it sometime ._.

**Comment by sonicbrandyn** [comment]
Thank you <3
