### ISSUE TITLE
Botania Items Missing

### ISSUE THREAD

**Issue by Dudesfield** [Vazkii/Botania#737]
I was using Botania R1.5-172, and everything was peachy, excluding for a bit of lag (Hadn't done any config work).
I updated to R1.6-174 and when I loaded the game up, I got the "These items are missing from this save"
When I started the game up, EVERY Botania item I had, had been removed from the world. 
I do have Optifine, but I am sure that it cannot remove item IDs and such. It's Vanilla forge. 
I have a few screen shots as well as the latest log. 

FML Latest Log: http://pastebin.com/y56Sz5Kp

![ss 2015-04-09 at 05 18 46](https://cloud.githubusercontent.com/assets/8277434/7077520/6a533270-dedf-11e4-96e4-ccb83fa8aed6.png)
![ss 2015-04-09 at 05 21 42](https://cloud.githubusercontent.com/assets/8277434/7077524/6e28c662-dedf-11e4-91fc-9e20b9f5884e.jpg)
![ss 2015-04-09 at 05 22 03](https://cloud.githubusercontent.com/assets/8277434/7077527/715abd5e-dedf-11e4-8a08-62425365beef.png)
![ss 2015-04-09 at 05 23 54](https://cloud.githubusercontent.com/assets/8277434/7077530/750a5a54-dedf-11e4-8baf-c796747ff98b.jpg)
The empty spaces contained water and hydroangeas.

**Comment by MrKunji** [comment]
Corrupted file

![](http://i.imgur.com/fnRl8XW.png)

**Comment by Dudesfield** [comment]
Okay, I used the in-game update prompt to update. I guess the crash a few minutes after corrupted it. If it's not one mod, it's another. I've been repairing my game after every mod update I do.

**Comment by Vazkii** [comment]
I really need to implement checksum verification sometime. Sorry for that.

**Comment by Dudesfield** [comment]
Quite alright. Some things fall through the cracks. I just was like.. wut. I just couldnt tell if it was a corrupt file from the crash or the .jar was messed up and some other mod was overwriting it.

**Comment by Dudesfield** [comment]
I've been wanting to make my own mod, but I have very little coding experience and am like a deer in headlights with some code. Plus I only have a few half baked ideas that don't amount to much
