### ISSUE TITLE
Wrong Location for Mana Burst

### ISSUE THREAD

**Issue by TheReaper9456** [Vazkii/Botania#743]
Hello, I run a server and we've been recently getting this error a lot and it's causing our server to crash any time someone gets near certain areas where this bug is happening. 

[22:27:05 WARN]: Wrong location for EntityManaBurst['Mana Burst'/217137, l='world', x=9558982231.98, y=17350410351.96, z=-102173101373.94] in world 'world'!
[22:27:05 WARN]: Entity is at 9.558982231981922E9,-1.0217310137393524E11 (chunk 597436389,2147483647) but was stored in chunk -19,-19

Hoping for some insight on the issue.

**Comment by Vazkii** [comment]
Can I have the crash log?

**Comment by TheReaper9456** [comment]
Sadly whenever this happens it doesn't generate a crash log. It's crashed the server at least 20 times upon my attempts to restart it, but it never generates one. 

I can't show the Botania setup where it's happening either because it obviously crashes every time I get near. I wish I could be of more help. :S

**Comment by TheReaper9456** [comment]
Been attempting to recreate the crash. No luck so far - it may just be that the area was simply corrupted from before. As far as I can tell the update may have fixed it.

**Comment by Vazkii** [comment]
I'll close it then. If you come across it again feel free to update.
