### ISSUE TITLE
Botania jar size like 2x bigger with 175

### ISSUE THREAD

**Issue by erkro1** [Vazkii/Botania#745]
I noticed the jar size almost doubled with the 175 update, and in the changelog I can't really find anything that should cause it, do you have any explaination for this?

**Comment by Kubuxu** [comment]
It is music...

**Comment by erkro1** [comment]
Damn, can't you compress it more, I mean it doesn't has to be crystal clear does it?

**Comment by Kubuxu** [comment]
But is is a problem?

**Comment by erkro1** [comment]
I don't know how mods work but I think it loads them in, plus if you can compress them without loss of quality it's always good. (it will save you a lot of internet traffic for people downloading a 7/8 MB file instead of 13)

**Comment by erkro1** [comment]
@Vazkii Here you have the compressed soundfiles: http://www.mediafire.com/download/r2m3t0weud711yi/Soundfiles.rar

**Comment by Vazkii** [comment]
Cheers, I'll replace them later today.

**Comment by Vazkii** [comment]
I can definitely tell a change of quality in that. Sorry, but I prefer the larger filesize to having poor quality music packed in.
