### ISSUE TITLE
Botania <-> Galacticraft Ticking block entity

### ISSUE THREAD

**Issue by karst** [Vazkii/Botania#747]
Hello there, I have just updated both Botania & Galacticraft and when I joined my server with these updates I crashed when the world loaded in. I figured that I should report this first to botania and if it is the wrong place to go, I'll report it to their bug tracker. If it is easy to fix I am even more happy. I am currently using a modpack which has 259 mods running on only minecraftforge.
Crash Report: http://pastebin.com/NLfYb2sG

**Comment by karst** [comment]
I forgot to say. This happend before I updated galacticraft aswell, I updated galacticraft because of this in the hope it might fix it. But it happend after updating botania (r1.5-162 -> r1.6-175)

**Comment by Vazkii** [comment]
Technically with only GC and botania this issue is completely impossible. I checked the lines and it doesn't match up. The only thing that could have happened is that one of your bajillion mods changed the entity list.

**Comment by karst** [comment]
I have had entity problems with EnderZoo before, but I don't know. I do know Gardenstuff has an integration for botania on which you can plant mystical flowers in one spot with other flowers. I am not sure if that is the actual thing though. Yesterday I have made a garden using gardenstuff in my base, but I really don't know what that has to do with galacticraft, which is on the other side of my base with it's machines and a tier 1 rocket.

**Comment by karst** [comment]
Alright I tried it with the previous version (The one that released at april third) but it has the exact same crash with the same crashreport

**Comment by karst** [comment]
Out of curiousity. What is the issue about? And what of my other mods could have caused this?

**Comment by Vazkii** [comment]
It's pretty hard to explain without going into technical spiel. The only thing I can see is that one of your mods messed up the world's player entity list. I changed it to look for Object (the lowest possible value in the hierarchy) instead of EntityPlayer. I don't know if it'll fix it, but that's the only thing that comes to mind.

**Comment by karst** [comment]
Alright :) We'll see if it worked ;)

2015-04-12 16:27 GMT+02:00 Lizbeth Rika <notifications@github.com>:

**Comment by karst** [comment]
Intresting stuff now. It seems it now crashes too in the version before the updating....

**Comment by karst** [comment]
I am now pretty much sure that it is DragonAPI v6d that has caused all the trouble.
