### ISSUE TITLE
Crash with the latest version of Botania

### ISSUE THREAD

**Issue by Sunconure11** [Vazkii/Botania#750]
For once, in several hundred years, I have encountered a crash with this mod on startup. The pack I am building does use Fastcraft.

http://pastebin.com/t0XnmaXN

**Comment by Vazkii** [comment]
This has to do with @ReikaKalseki signing the botania API in his jar. Since it's a coremod, my new class will have a different signature and break everything.

**Comment by Vazkii** [comment]
Leaving this open until he fixes it to prevent further dupes.

**Comment by wasweb** [comment]
For a temporary fix: remove vazkii folder from DragonAPIxyx.jar

**Comment by Vazkii** [comment]
Have you tested that, @wasweb? The botania api classes are included in the manifest.

**Comment by wasweb** [comment]
yep, it's loaded up fine, even in an existing world

**Comment by ReikaKalseki** [comment]
I accidentally shipped the API. This will be fixed later today.

**Comment by Sunconure11** [comment]
Hm, DragonAPI updated. Maybe its fixed now?

**Comment by ReikaKalseki** [comment]
It is.

**Comment by Vazkii** [comment]
I'll keep this open for a bit longer to prevent more dupes.

**Comment by Sunconure11** [comment]
Should I just close this now Vazkii?

**Comment by Sunconure11** [comment]
Fuck it, I'll close it now, until this crash reappears in the far far future or something.

**Comment by Vazkii** [comment]
I'll leave it open for another week or so, it doesn't hurt.
