### ISSUE TITLE
Unable to use the Ring of Loki due to ping.

### ISSUE THREAD

**Issue by Dawgie3000** [Vazkii/Botania#758]
It seems that the Ring of Loki will not function correctly on higher amounts of ping.  I personally have a ping rate of 670+ and when I go to use the omnipresence feature of the ring, The block outline for the selected blocks do not appear.  The ring itself works fine though I find myself unable to disable the omnipresence feature.  I tested this in single player and the feature worked just fine and the ping rate is the only cause that I could come up with.

**Comment by Vazkii** [comment]
It might just not work properly on SMP at all, I need to have a look.
