### ISSUE TITLE
Eye of the flügel glitch

### ISSUE THREAD

**Issue by akvgergo** [Vazkii/Botania#759]
For some reason, every time I try to drop the dice, it just gives me another Flügel eye, but none of them gets bound to me.
![2015-04-15_00 58 59](https://cloud.githubusercontent.com/assets/8812148/7149235/2520cafc-e30b-11e4-9919-9e4ce1595982.png)

Using r1.6-173

**Comment by Vazkii** [comment]
# Using r1.6-173
