### ISSUE TITLE
Terrasteel helm of revealing loses ancient wills on crafting

### ISSUE THREAD

**Issue by akvgergo** [Vazkii/Botania#766]
If I have a terrasteel helmet with ancient wills applied, crafting a terrasteel helmet of revealing out of it will remove all already applied wills.

**Comment by Vazkii** [comment]
._.

**Comment by Gencode** [comment]
Also loses any enchantments aswell.

**Comment by Lazersmoke** [comment]
@Vazkii pull request submittedt
