### ISSUE TITLE
Build file depends on Windows

### ISSUE THREAD

**Issue by SoniEx2** [Vazkii/Botania#770]
I'm on Linux.

**Comment by Vazkii** [comment]
Thanks for the highly descriptive bug report.

**Comment by SoniEx2** [comment]
https://github.com/Vazkii/Botania/blob/master/build.properties#L4 (also why's that on the build.properties? meh w/e)

**Comment by RX14** [comment]
If you are going to leave it so that gradle crashes when not using windows, you might as well have a note...
