### ISSUE TITLE
Add ISidedManaReceiver

### ISSUE THREAD

**Issue by SoniEx2** [Vazkii/Botania#774]
An ISidedManaReceiver would require the use of something that can send mana to a specific side of a block, for example a mana spreader. This would allow (proper) CompactMachines interaction. A well-explained reason why not would be appreciated.

**Comment by Vazkii** [comment]
Go away.

**Comment by Barhandar** [comment]
Translation: "A request this misguided doesn't warrant a well-explained reason why not. Explain what would the point be in making mana interaction sided, with examples, please, before I consider it."

**Comment by SoniEx2** [comment]
CompactMachines would be able to split their mana buffers, having one for each side, and then the inside wouldn't have the same mana buffer on all sides. Try CompactMachines and see it for yourself.

**Comment by Vazkii** [comment]
No, Barhandar, I actually mean "Go away."

**Comment by SoniEx2** [comment]
> No, Barhandar, I actually mean "Go away."

As expected from someone who dislikes me... Why do you dislike me anyway? It's not like my issues are invalid :/

**Comment by Vazkii** [comment]
Yes they are. You're looking for me to implement something that is not needed at all and will be used for your mod when you can just make a PR with that functionality yourself.

**Comment by SoniEx2** [comment]
Well I thought you wanted to work on mod compatibility stuff... I guess I'll do a PR then.
