### ISSUE TITLE
Placing floating rannuncarpus on tiled dirt turn it back to dirt.

### ISSUE THREAD

**Issue by Hypneos** [Vazkii/Botania#779]
This happens when i place the flower directly on the dirt, or on an adjacent wall.

https://gist.githubusercontent.com/Hypneos/98f652431025d611be10/raw/4df6211551a8763c4e37948c6e54b02dd7b65f44/gistfile1.txt

**Comment by Vazkii** [comment]
Too minor to bother fixing.
