### ISSUE TITLE
Botania Potion/Pendant ID - Bypassy Stuff

### ISSUE THREAD

**Issue by Azikai** [Vazkii/Botania#783]
I am helping run a towny server and I need to ban the Crimson Shade Pendant/Potion and the Vanity's Emptiness Potion/Pendant.

Banning the ID bans all of them.

Maybe you could add an option for disabling the creation of certain flasks/pendants?
---------------------------------------
Not sure if you could fix, but thought I would try and throw it out there:
Bypasses Towny and WG:

Shard of Laputa
Rod of the Molten Core
Terrashatterer
Horn of the Wild/Canopy (Breaks vanilla plants and pams stuff)
Vineball
Mana Lens Bore/Weight/Influence/Paintslinger/Flash
Livingwood Slingshot
Ring of Loki and Aesir (Omnipresence allows building in towns)

Snowflake Pendant makes water permanently ice if removed.

Might not be able to fix those, but IDK.

Thanks

**Comment by Vazkii** [comment]
I don't support bukkit plugins, sorry. You might be able to get around that by disabling the problem potions with modtweaker. I don't know if it has support for that.

**Comment by Azikai** [comment]
Might want to fix Snowflake Pendant though. Seems to make the ice permanent if you take it off.
