### ISSUE TITLE
Mana Pylons no longer give bookshelf boost (R1.6 181)

### ISSUE THREAD

**Issue by spinner2727** [Vazkii/Botania#788]
After upgrading from 175 to 181, Mana Pylons no longer give the level boost to the enchantment table.  I have 2 next to it, and it acts as if there isn't anything around it at all.  Tested on my server and single player.

**Comment by Yadokingu** [comment]
Still works for me. Are they one block away?

**Comment by spinner2727** [comment]
Okay, you're right, and that makes sense.  I guess this can be closed.  Is this something that changed, or has it always been like that?  Cause I could have sworn it worked fine with them right up against the table.
