### ISSUE TITLE
Force relays unbind from pistons after reboot

### ISSUE THREAD

**Issue by Yadokingu** [Vazkii/Botania#791]
I'm playing feed the beast infinity in a single player world. Sadly my setup for automated living wood/rock breaks every time I reboot the world, since the bore-warp burst just goes straight down instead of going from relays to pistons.
The pack used an older version of Botania, but I updated to R1.6-181 to make sure the problem wasn't fixed yet and sadly it wasn't.

**Comment by Vazkii** [comment]
Can't reproduce, sorry.

**Comment by Yadokingu** [comment]
Weird that it's not reproduceable. Maybe it's important that my setup is vertical? Sorry for forgetting to mention it. Here is how it looks: https://i.imgur.com/kj2Y4N6.png

Guess I'll switch to open blocks breakers in the meantime.
