### ISSUE TITLE
Ring of Aesir causes double block placement

### ISSUE THREAD

**Issue by Yadokingu** [Vazkii/Botania#800]
At first it would cause placed blocks to teleport to a spot about 2 blocks away from where I actually sat them down, now it's placing one block where I want it and another 2 blocks away.
It's a little hard to explain so here is video: https://www.youtube.com/watch?v=Fyxvm_wPPoo

This is the feed the beast infinity pack, but botania is updated to 181.

**Comment by Lazersmoke** [comment]
It seems like the second block is placed on the line between the first block and some point. Try placing lots of blocks to triangulate the point (if it exists), as it may lead to the solution.

**Comment by Vazkii** [comment]
Did you do anything with the ring at all after crafting it? Is this a singleplayer or multiplayer? Does it happen with only botania?

**Comment by OJwithC** [comment]
...Is this not how it's supposed to work? It is crafted with the Ring of Loki in it, no?

**Comment by Yadokingu** [comment]
This is single player. It didn't happen right away, just started happening all of a sudden, but now it happens every time I put the ring on. It only happens with the ring of aesir, but with every block/placable item I try to put down.

**Comment by Yadokingu** [comment]
Seems like the problem was that I had no idea what the ring of loki does.
I take half of that repsonsibility, the lexica botania says basically nothing about the relics, the discriptions are rather cryptic (I also crafted the ring of aesir before doing anything with the individual rings and that description says nothing about what the rings do) and when I googled for the ring of aesir no actual info came up, no matter what search combinations I tried.

**Comment by OJwithC** [comment]
I found out how the ring of Loki works through Vazkii's YouTube channel.
http://youtu.be/3tJMvtYBixY
