### ISSUE TITLE
 Soujourner's and Globetrotter's sashes step assist broken

### ISSUE THREAD

**Issue by JadeDrgn** [Vazkii/Botania#801]
Using the newest version, 182, the step assist doesn't work when when you change dimensions still, but their speed boost works though.

**Comment by MrKunji** [comment]
https://github.com/Vazkii/Botania/commit/6b0b158219865a5411ff198aab4c256237ab7883 didn't fixed it?

**Comment by JadeDrgn** [comment]
It did not it seems. I just did a test with only botania installed and I swapped dimensions and I only receive the speed boost and have to re-equip it to get the step assist.

**Comment by JadeDrgn** [comment]
Could it be because I'm still on forge 1291?

**Comment by Nagapito** [comment]
There must be some incompatibility with the Aether mod, since it still doesnt work when you have this mod. It worked nicely before you changed it initially
