### ISSUE TITLE
Ring of Odin - Adds extra hearts each dimension change

### ISSUE THREAD

**Issue by mulch75** [Vazkii/Botania#803]
I have the Ring of Odin on in a bauble slot and every time I change dimensions it add's 20 hearts to my health. 
I'm playing through the new Hubris modpack so it could be related to that, its very new and being frequently updated. I have updated botania to 182 and the problem remains.
I am running optifine but as its not a crash or graphics related I doubt its relevant. I also use the Faithful32 texture pack.

FML LOG - Well the first bit anyways, its 5 mb so let me know if you need the whole thing.
http://pastebin.com/KbMSesg5

**Comment by MrKunji** [comment]
This happens with Tinkers' too, blame Aether for it.

**Comment by mulch75** [comment]
If that is the case I found a workaround/fix for your save.
Use an NBT Editor (such as NBTExplorer)
Open your save game and go to
Level.dat\Data\Player\Attributes\
Then open each of these and find the one that says  generic.MaxHealth. Set it back to 20.
This works for single player saves at least.

**Comment by Vazkii** [comment]
Does this only happen with the aether loaded @MrKunji?

**Comment by MrKunji** [comment]
https://github.com/SlimeKnights/TinkersConstruct/issues/1507

**Comment by Vazkii** [comment]
Ok, pinging @kingbdogz while I'm here.
