### ISSUE TITLE
Multilingual Vuvuzela

### ISSUE THREAD

**Issue by Xottab-DUTY** [Vazkii/Botania#810]
Hello Vazkii!
Just noticed the commit @294cca5. How about checking vuvuzelas from translation files?

*offtopic: I want to ask you about the Holy Sword Excaliber. Should I translate it as Excalib**u**r? Or do I need to translate it exactly as Excalib**e**r?*

**Comment by Vazkii** [comment]
Excaliber. There's really no reason to check against lang files for mini easter eggs.

**Comment by Xottab-DUTY** [comment]
Thanks! Okay :|
