### ISSUE TITLE
Lexicon crash with shedding turned off

### ISSUE THREAD

**Issue by doushio9967** [Vazkii/Botania#813]
Botania r183.

Setting natural shedding to blank/nothing on, for example, chickens will cause the following crash when you go go through the Natural shedding pages in the lexicon:
http://pastebin.com/NgkwDnGc

**Comment by Vazkii** [comment]
Can I have a copy of the config that caused this?

**Comment by doushio9967** [comment]
http://pastebin.com/2PVeCvPn
It's one line changed from the default generated config.
`S:Chicken.item=`

Testing it again it seems to happen if you blank out the item while having the .rate set to something other than -1.

Thanks.

**Comment by Vazkii** [comment]
I'll blame this on @soundlogic2236
