### ISSUE TITLE
item stacking

### ISSUE THREAD

**Issue by StompMC** [Vazkii/Botania#818]
I was just using Botania in a single player and I found a small issue. I have a basic mana pool and was dropping items in to charge them. First it was petals and then it happened with iron bars. After dropping the bars/petals in if there was not enough mana the items would be spit back at me and will no longer stack with the original stack of items. 
Just to add to this I don't know if it effects anything but I was doing all of this in the Aroma Mining Dimension. 
I was using the newest version I downloaded just this morning.

**Comment by Barhandar** [comment]
Presumably the same as #815, but I hadn't used mana infusion/alchemy so far, only conjuration.

**Comment by StompMC** [comment]
it may be linked somehow I dont know. When it happened with an iron bar it still shows as
 "Iron Ingot" with the same item ID and both have Minecraft tag. so upon appearances it looks like the same item but it won't stack in any inventory as being treated as a separate item.

**Comment by Barhandar** [comment]
That happens with NBT-tagged items. If the tags are different, they won't stack.

**Comment by Lazersmoke** [comment]
It is possible that the redstone you put in was NBT-tagged, and the redstone you got out was not tagged. The same with the ingots; the infusion failed so it tried to give back iron ingots, untagged.

**Comment by Barhandar** [comment]
>It is possible that the redstone you put in was NBT-tagged, and the redstone you got out was not tagged.

Redstone crafted out of redstone blocks is by definition untagged (without recipes getting messed with) and still returns NBT-tagged redstone. Also, I don't even have Aroma and it was in overworld, and creative tests result in nonstacking redstone.

**Comment by Lazersmoke** [comment]
I see! I was confusing empty-tagged with untagged :O... 
This is the final result: http://imgur.com/BODF9UD
The fresh ingot is straight from creative and will not stack with the other 52 that failed transmutation. Ingots that fail infusion can stack with others that have done the same.

**Comment by Vazkii** [comment]
I think I figured it out. This was caused by the addition of the Petite flowers. When the item is thrown on the pool it goes through the list of recipes to figure out which is the right one. When it gets to the Petite Flower recipes it checks the item's NBT to verify it's the proper flower. Since it doesn't have an NBT tag to compare to, it creates an empty one. It's an easy fix.
