### ISSUE TITLE
Sparks + Mana Pools result in graphical issues

### ISSUE THREAD

**Issue by RAnders00** [Vazkii/Botania#822]
Clearly visible:
[![Loading image, click here if it does not load](http://i.imgur.com/lt0CO3m.png)](http://i.imgur.com/lt0CO3m.png)
I am referencing to the catalysts shining through. It basically makes mana pools and spreaders (and potentially other blocks as well) not visible behind the spark.

**Comment by Lazersmoke** [comment]
This is a well know minecraft bug. Other examples include not being able to see thaumcraft nodes when water is behind them, being unable to see a lot of things through alfheim portals, etc.
References:
- https://bugs.mojang.com/browse/MC-9553
- http://www.reddit.com/r/Minecraft/comments/1h95w9/

although this could be a Botania thing, I highly doubt it
