### ISSUE TITLE
Overlay of the Eye of the Flügel is broken after getting it instantly selected after rolling the Dice of Fate

### ISSUE THREAD

**Issue by RAnders00** [Vazkii/Botania#823]
When you roll the Dice of fate and you get the Eye of the Flügel and the  item lands in your hand after using the dice of fate, the names of the teleportation destinations are broken and the icons are not visible, as demonstrated [here](http://imgur.com/a/NW7cg).

When scrolling on your hotbar to the side and then scrolling to the item again, the names appear properly and the icons are visible.

FML Log: https://gist.github.com/RAnders00/ae644b1ab5096a3a8ccc

This has been tested using the versions shown in the screenshots in the imgur album, which are the very latest.
I also had NEI, CodeChickenCore and ttCore installed.

**Comment by Lazersmoke** [comment]
Also occurs randomly when holding or selecting it afterwards
