### ISSUE TITLE
internal server crash

### ISSUE THREAD

**Issue by Sailren** [Vazkii/Botania#824]
im getting an internal server crash upon creating a new world

http://paste.ubuntu.com/10889072/

used botania version is 1.6-184, oh and fastcraft is installed as you can see in the crash report

**Comment by Vazkii** [comment]
Does this happen without fastcraft?

**Comment by Sailren** [comment]
gonna test this out, im still experimenting with different client setups

**Comment by Lazersmoke** [comment]
@Sailren any updates?

**Comment by Sailren** [comment]
until now no crash related to botania, but now something is messing with thaumic exploration and gregtech

**Comment by Vazkii** [comment]
Closing if there's no further updates. Feel free to comment if something else happens.
