### ISSUE TITLE
Ritual of Gaia not checking for enough open space

### ISSUE THREAD

**Issue by RAnders00** [Vazkii/Botania#825]
I am able to summon the guardian in a very little amount of space.
http://imgur.com/a/jNCcJ

Note that the pylons are placed inside of the cobblestone, and there are no air blocks in that solid cube. Using latest version of Botania.

The cube is 21 wide and long and 15 blocks high.

Note that the guardian also summons the hostile mobs inside of the blocks. It also teleports inside of them (or I just never noticed that it is not visible all the time)

**Comment by Lazersmoke** [comment]
Am I correct in assuming that because Vazkii tagged this as a bug, this behavior is unintentional, and building special arenas for the ritual, or is the bug the teleporting and spawning inside blocks?

**Comment by Vazkii** [comment]
Eh, going to call a non issue after all. If you really want to use an arena then bob's your uncle.
