### ISSUE TITLE
NEI crashing with Botania:

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [Vazkii/Botania#826]
I'm crashing when using NEI and Botania whenever I press U to see what the item is used for:

http://hastebin.com/rayuyoluje.1c

**Comment by Barhandar** [comment]
I'm on latest Botania and I fail to encounter crash on checking out 'u'se. Have you tried to do it while not in the multipage chest's GUI?

**Comment by Unrepentant-Atheist** [comment]
Yea, I did. No go. Still crashing.

**Comment by Corvorosso** [comment]
i have the same issue with MagicBees 2.3.0 and last Botania
if i downgrade to 2.2.3 of MagicBees the problem seems solved

**Comment by Lazersmoke** [comment]
As far as I can tell, this is a MagicBees issue; All of times the issue has shown, MagicBees 2.3.0 is present. In addition, the Botania code looks good to me. :)

**Comment by Keridos** [comment]
Having the same crash when trying to view salt recipe usage.

**Comment by Lazersmoke** [comment]
This is now closed, but I don't have permission to mark it as such :( The people in the other repo's said it would be fixed in the next update on their end :)
