### ISSUE TITLE
Heisei Dream makes Skeleton shoot indefinitely

### ISSUE THREAD

**Issue by Yadokingu** [Vazkii/Botania#827]
I decided to make a little record-factory using the heisei dream, but in my testing I noticed that the skeleton would just keep shooting, long after the creeper was dead. This is the result: https://i.imgur.com/xUP0qVv.png

181, single player, ftb infinity pack

**Comment by Vazkii** [comment]
Not worth fixing.

**Comment by BlueWilder** [comment]
This is still an issue, most of the arrows won't despawn, thus creating unnecessary lag.

**Comment by JRoffel** [comment]
Of course this is still an issue, like vazkii said, this is not worth fixing. Please stop talking about it, as the result will not change. (I come bearing a temp solution tho, place a command block with a timer with an 200 tick (10 second) interval, and make it execute "kill @e[type=Arrow]" ( my limited amount of command knowledge tells me this should(?) work))

**Comment by howtonotwin** [comment]
@JRoffel Nope, the target selector arguments for `@e` come from 1.8.

**Comment by JRoffel** [comment]
@howtonotwin maybe the "all" selector (@a) will work? Or does that not target entities like the arrow if you give it a type parameter?

**Comment by yrsegal** [comment]
nope, entity targeting is ONLY possible 1.8 and further.

**Comment by JRoffel** [comment]
Then never mind my solution

**Comment by BlueWilder** [comment]
So a bug that  can be reproduced 100% of the time and if left alone can lag the fudge out of a world is not worth fixing, yup, okay.
Vazkii refuses to fix it and there's no workaround for it in 1.7.10
Great, instead of a music disc farm I built a lag machine
