### ISSUE TITLE
Heisei Dram makes Sekeleton non-aggressive

### ISSUE THREAD

**Issue by Yadokingu** [Vazkii/Botania#830]
I think this happened after a restart, but I can't be completely sure. I was wondering why I was lagging so much and it turns out it was because nobody was killing creepers: https://i.imgur.com/Gnk3ipL.png

The Skeleton won't even aggro on me. Replecing the Heisei Dream did nothing, picking the skeleton up with a safari ball and re-placing it does nothing. As you can see to the right, the mana pool, it is bound to, is filled to the brim.

Botania 181, single player, ftb infinity

Edit: Even grabbing a completely new skeleton from the wild doesn't change this. It still won't aggro on me or the creepers. 
I grabbed them with a jailors ball if that is important. But I kinda doubt this, since it used to work.

Edit2: I think it might actually be the tigers eye malfunctioning. After removing that and replacing the skelli, it will aggro on me and the creepers again.

**Comment by Vazkii** [comment]
Can't reproduce this, sorry.
