### ISSUE TITLE
Unique Artifacts + Timeless Ivy compatibility?

### ISSUE THREAD

**Issue by Azutte** [Vazkii/Botania#832]
Dev has taken a look at it [here](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1291999-unique-artifacts-powerful-randomly-generated-items?comment=1435), and apparently doesn't understand the issue. See previous comment in post. They have the materials registered as working in anvils, which I understand to be the key feature in Timeless Ivy crafting.

**Comment by Vazkii** [comment]
I can't do anything if the mod is closed source. The possible culprit is that the item has isRepairable() set to failse.

**Comment by Draco18s** [comment]
Its not closed source
https://github.com/Draco18s/Artifacts/blob/master/main/java/com/draco18s/artifacts/item/ItemArtifact.java#L588-600

**Comment by Vazkii** [comment]
I didn't see a github link in the thread so I just assumed. Then again there might've been one and I'm just blind :P
Alas, the regen ivy checks for isRepairable(), the one with no parameters - https://github.com/Vazkii/Botania/blob/master/src/main/java/vazkii/botania/common/crafting/recipe/RegenIvyRecipe.java#L33
Your call of setNoRepair() makes it not trigger. It's not really a bug, it's just a side effect of using that to block the item from being repaired by normal means.
https://github.com/Draco18s/Artifacts/blob/master/main/java/com/draco18s/artifacts/item/ItemArtifact.java#L61

**Comment by Draco18s** [comment]
Ah, I see the problem now.  I think its leftover from before they were repairable, and the Anvil didn't use that particular check.
And the GitHub link is probably buried.  Editing the main post has been...problematic lately.

**Comment by Azutte** [comment]
[It didn't work](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1291999-unique-artifacts-powerful-randomly-generated-items?comment=1500). Any ideas, Vazkii?

**Comment by Draco18s** [comment]
Vazkii, if you put together a debug build with some logging statements for each if-check in the recipe, so either myself or Azutte can run them side by side, that'd be fantastic.  I'd clone the project myself, but I'm afraid I've been terribly busy lately and I haven't been able to get Artifacts to work in dev lately (probably an update to Forge, I just don't know to which one).
