### ISSUE TITLE
Mana Spreaders "not shooting" on Cauldron Server.

### ISSUE THREAD

**Issue by Marvien14** [Vazkii/Botania#834]
Mana spreader appears to not be shooting on a Cauldron Server(works fine in Singeplayer).

After a bit of testing with the spreaders on the server it is in fact shooting but in a random direction.
So every once in a while it'll hit the mana pool, but it's a very small chance considering the amount of angles/directions that are available.

Video of what I just tried to explain: https://www.youtube.com/watch?v=fTsZzKGeyIA
Just to show that it does work in Singleplayer: https://www.youtube.com/watch?v=UG-6r1mf11Y

Using version r1.6-184 of Botania and the Cauldron server is using forge 1291.

**Comment by Vazkii** [comment]
I don't support cauldron. Does it happen in a vanilla forge server?

**Comment by Lazersmoke** [comment]
Isn't singleplayer just a local server? The report says that single player works, and the rest is about Cauldron (unsupported) In all likelihood, a plugin on Cauldron is disrupting the spreader somehow. In any case it doesn't seem to be a Botania issue IMO

**Comment by Vazkii** [comment]
Yes, a local server. Something can happen in a dedicated server and not in a local server.

**Comment by Marvien14** [comment]
Well it's kinda preventing me from progressing right now.

**Comment by Vazkii** [comment]
I can't do anything then, I'm sorry.
