### ISSUE TITLE
Relay pairs don't get saved in the moment of binding or when exiting the world.

### ISSUE THREAD

**Issue by createdforissues** [Vazkii/Botania#835]
Issue occurs only with fastcraft.

Basically if I just bind relay to a block it doesn't update PistonRelayPairs.dat, if I exit a world it doesn't update it either. But if I move relay with piston after binding, it forces to save coordinate pairs into the file.

It's not a big problem, but if it forced saving of relay pairs on world exit (like it does with pistons), it would remove this issue.

**Comment by Abacor** [comment]
I don't think this is related to fastcraft. I have this bug with only Botania and baubles installed.
