### ISSUE TITLE
Mana spreader not shooting.... again.

### ISSUE THREAD

**Issue by Marvien14** [Vazkii/Botania#836]
So as from my last post it wasn't shooting and I assumed the problem was Cauldron, now I have removed Cauldron and am now running a vanilla forge server and it seems to only shoot at the pool when I'm NOT close to the spreader.

Video: https://www.youtube.com/watch?v=SiL9eMNVcC4
Botania version: r1.6-184
Forge version: 1.7.10-10.13.3.1388

After posting/recording all that the mana spreader seemed to stop completely, mana is not going anywhere. :D

Images: 
  Mana Pool: http://prntscr.com/6yxy8p
  Mana Spreader: http://prntscr.com/6yxyft
  The Endoflame's: http://prntscr.com/6yxyqv

**Comment by Vazkii** [comment]
What version of BM are you running, do you have Whirlwind on your armor?

**Comment by Marvien14** [comment]
Running Blood Magic version 1.7.10-1.3.2-1 and I do not have Whirlwind on my armour as I just installed Blood Magic, but that does make me think about the ring I have which pushes all entities away from me.
Still unexplained is the clogging up of the spreader that I just updated the post with.

**Comment by Vazkii** [comment]
The bursts are entities, the spreader is firing, which you can see by the fact that the mana amounts change. It's likely the ring that's pushing the entities away.

**Comment by Marvien14** [comment]
Yeah, I turned off my ring and it's working now, but now I have the issue that the spreaders are full and not shooting
Mana Pool: http://prntscr.com/6yxy8p
Mana Spreader: http://prntscr.com/6yxyft
The Endoflame's: http://prntscr.com/6yxyqv

**Comment by Vazkii** [comment]
Break the spreader and replace it.

**Comment by Marvien14** [comment]
That temporarily fixes the issue, thanks.
