### ISSUE TITLE
Holy Sword Excaliber fires on right clicking object

### ISSUE THREAD

**Issue by Lazersmoke** [Vazkii/Botania#837]
Right clicking the air or blocks will make you block, but right clicking doors, chests, crafting tables, etc make the sword fire. I think this is because the firing is based on the angle of the sword during the swing, but the correct angle is also obtained through many other actions. This is the same thing as the waking up bug that was inexplicably closed a while ago...

**Comment by Vazkii** [comment]
Not worth fixing.
