### ISSUE TITLE
Mana Blaster color does not match Mana Flash color when using rainbow tinted Flash Lens.

### ISSUE THREAD

**Issue by Melazu** [Vazkii/Botania#841]
When a rainbow tinted Flash Lens is equipped on a Mana Blaster, that line on the blaster changes colors. This color matches the mana burst it fires, but not the color of the Mana Flash created on impact. 

E.g., the Mana Blaster is pink, and fires a pink mana burst. the pink mana burst hits a wall, and creates a blue Mana Flash.

This makes it difficult to time firing to get a specific colored Mana Flash.

**Comment by Vazkii** [comment]
That's intended behaviour, the rainbow lens actively changes the burst's color.
