### ISSUE TITLE
When a Mana Blaster is fired using a Bore Warp lens, the broken blocks do not teleport to the player who fired it.

### ISSUE THREAD

**Issue by Melazu** [Vazkii/Botania#842]
Fired a mana burst using the Mana Blaster with a Bore Warp lens, and it broke blocks successfully, but the blocks dropped in place and did not teleport as the Lexica suggests they should.

I made sure it was a Bore Warp lens and not a Warp Bore lens, too. (Bore Lens was visible.)

**Comment by Vazkii** [comment]
Intended behaviour as well.
