### ISSUE TITLE
Petite recipe working?

### ISSUE THREAD

**Issue by Tergiver** [Vazkii/Botania#847]
What am I doing wrong?
![What am I doing wrong?]
(http://i62.tinypic.com/16ggak4.png)

I discovered this while playing Agrarian Skies 2 (1.0.37) which is r1.6-184 and tested it in my personal mod pack with the same version of Botania.

I tried all six of the flowers with and without the spark.

**Comment by Barhandar** [comment]
Had the same with Hopperhock, no reaction and no visual display like with other convertible items.
