### ISSUE TITLE
Tutorial of the Basics bug

### ISSUE THREAD

**Issue by CatDany** [Vazkii/Botania#848]
When you get to Mystical Accessories (or smth?) on the tutorial, the arrow is in the top-left corner.
http://i.imgur.com/F4qthSy.png

**Comment by CatDany** [comment]
it also seems to work for Livingwood Bow, so pretty much everything in Mystical Accessories (sorry, I don't know how this tab is called on English)

**Comment by Vazkii** [comment]
Can't reproduce.
