### ISSUE TITLE
Two minor issues with Ring of Loki/Aesir - Keybind needed

### ISSUE THREAD

**Issue by LazerusKI** [Vazkii/Botania#851]
The idea behind them is great, but after a while of messing around with them, i found two minor issues.

The first is its "activation key". Shift+RMB
Since this combination is used by many other mods, it causes some annoying side effects. For example opening a witchery coffin. You cant open or activate things without placing the Loki effect on it.
I was looking for a keybinding option to change it...but couldnt find anything.
Could you add the option to deactivate that part with a key, so that you dont have to unequip it whenever you want to use that combination for something else? Instead toggling it on and off whenever you want?

The second happens when you "forget" about it.
I was placing some Loki effects on blocks while messing around with it...and forgot wich one was the point of origin that i have to remove to activate the effect.
Once the effect is activated, simply placing another one can reset it. But i could not find a way to reset the pattern while placing it.
This is especially annoying with the first described issue. I had opened a coffin without noticing the effect, then i wanted to build a small house with the Loki effect...but i could not trigger it, because i could not figgure out where the first click was. Had to delete the ring and cheat it back in.
So a key to reset it would be usefull.

**Comment by Lazersmoke** [comment]
Suggestion: shift right click in air with Aesir ring to toggle Loki ring functionality

**Comment by Vazkii** [comment]
I do have some tweaks in mind for the ring in my todo list already, so I'm closing this.
