### ISSUE TITLE
botaniamod.net/lexicon.php broken

### ISSUE THREAD

**Issue by Abacor** [Vazkii/Botania#852]
90%+ of the text on http://botaniamod.net/lexicon.php is currently junk like `ÐºÐ¾Ð½ÐµÑ‡Ð½Ð¾`

**Comment by Barhandar** [comment]
For some reason it autodetects codepage ISO-8859-5 instead of UTF-8. If it did it right you'd be seeing Russian, which for some reason is the content on en_US.lang, which means any build before it's fixed will be essentially unusable.
