### ISSUE TITLE
Lag in Assembly Halo

### ISSUE THREAD

**Issue by devemouse** [Vazkii/Botania#857]
When crafting in assembly halo (crafting table, not the auto-crafting spots) there is a lag spike when valid recepie is formed.
Also I noticed that when there are beacon beams in the background they re-form (as if beacon was just created) in the same situation.
At the same time Crafting Station from TC and vanilla crafting table doesn't have that issue

Second, when using auto crafting spots there is also a lag spike but the thing with beacon beams do not appear

It all works fine in minecraft fresh started and the issue starts to appear after some time.

Seen in versions 167-177.

**Comment by Vazkii** [comment]
Can't reproduce.
