### ISSUE TITLE
Dupe bug

### ISSUE THREAD

**Issue by bosto2** [Vazkii/Botania#860]
## Botania: r16-183
(checked r16-184 change log)
almost every time i throw a stack of items (8-16) in a mana pool and stand on top of it i get a extra item or 2
Edit: i have not tested this for bigger stacks

**Comment by Vazkii** [comment]
I need more info. Give me a log.

**Comment by bosto2** [comment]
i tried to replicate the bug. 
i could not do it and i think it was due to me having a memory leak at the time of the bug happening
Note: (this happened on a server)
and yes the items ware actually still there to be a bit more precise:
12 iron = 13 manasteel
18 glass = 19 managlass
8 ender pearls = 9 mana pearl

**Comment by Vazkii** [comment]
I can't reproduce the bug, so I can't do anything without a log to check your circumstances, sorry.
