### ISSUE TITLE
Problems with Glob sash on Lan

### ISSUE THREAD

**Issue by toxicytears** [Vazkii/Botania#862]
So, more or less none of the items I make on a lan server that I'm not hosing do not work, I can however make them work by going into a single player put on what I want and then go back into the server. I'm not sure if this is a bug or just a lan thing but thought I would let you know.

**Comment by RAnders00** [comment]
Kind of incomplete, please make clear:
* What does not work?
* How can one reproduce it?
* How did you work around it?
* Versions of mods?
* Did you try it with a latest forge and only botania installed?
Vazkii will close this if you keep it that incomplete.

**Comment by toxicytears** [comment]
What does not work?
  bobbles (sojurners sash, rings...etc)
How can one reproduce it?
  have roommate open lan, make bobbles, try to use, wont work. Go to single player and give your     self items go back to lan.. now they work (even ones you dont have)
How did you work around it?
  see last step
Versions of mods?
  using ftb infinity 1.4.1
Did you try it with a latest forge and only botania installed? Vazkii will close this if you keep it that incomplete.
  not yet. going to ask roommate to do so. 

I've had this problem on a few modpacks like dw20 and ftb infinity and I think mage quest also... Just now making a bug report.

**Comment by Reyls** [comment]
please write the botania version.
vazkii doesn't know any botania version in any modpack.
i guess in infinity 1.4.1 the version is r1.6-174

**Comment by Vazkii** [comment]
For the ten millionth time, this is a baubles issue, not botania.
