### ISSUE TITLE
generating flowers change bind on chunk load

### ISSUE THREAD

**Issue by buglord** [Vazkii/Botania#866]
mod version: Botania r1.6-183
mod pack: genesis 1.2.3
server details: Cauldron, bungee

mana producing flowers bound to mana spreaders rebind when chunk is unloaded and loaded again.
they can bind to spreaders at far range despite all being in the same chunk and spreaders at shorter distance are available.
bug consistent across multiple unload/load sequences.

grid shows entire setup is within the same chunk.
![2015-04-30_18 50 30-overview](https://cloud.githubusercontent.com/assets/4242467/7435976/0fc5b6a4-f049-11e4-8f66-ffa802e7c7c4.png)

flower at -1460,210,2536 bound to -1461,209,2536 unaffected.
flower at -1463,210,2533 bound to -1463,209,2534 unaffected.
flower at -1463,210,2539 bound to -1463,209,2538 affected and binds to -1465,209,2536.
flower at -1466,210,2536 bound to -1465,209,2536 affected and binds to -1466,207,2531.
![2015-05-01_16 40 41-post](https://cloud.githubusercontent.com/assets/4242467/7436121/729cda36-f04a-11e4-8366-f05d4d5d4cdb.png)

related: #693 and #383 

I was informed cauldron might change some tick timing. I don't know if this could cause it to tick the flowers before all blocks are fully loaded.

**Comment by Lazersmoke** [comment]
Cauldron is not supported by Botania

**Comment by Vazkii** [comment]
As @Lazersmoke said. Does it happen without cauldron?

**Comment by Barhandar** [comment]
Happened to my friend on server without cauldron. Multiple times her flowers were rebinding to a different spreader, causing manapool to dry and portal to shut off.

**Comment by Rainboww** [comment]
Can confirm, happened to me as well (until I moved the entire setup) and we're not on cauldron.

**Comment by ljfa-ag** [comment]
Might be related to this: https://github.com/Vazkii/Botania/blob/master/src/main/java/vazkii/botania/api/subtile/SubTileGenerating.java#L87
blockExists might not do what you'd expect. It will return false when the given coordinates lay in an unloaded chunk.

**Comment by PatchouliKnowledge** [comment]
Can confirm this too. OP has gourmaryllises, but I encountered this also with floating thermalilies and regular/floating hydroangeas, so it's probably safe to assume that all flowers are affected. Non-Cauldron modpack here as well.

**Comment by Vazkii** [comment]
Close @ljfa-ag. The function is right, it's just flawed logic that's the problem.

**Comment by Elvarion** [comment]
Flowers unbind when chunk unloads
http://gyazo.com/647699aca1b654e2a76bd6fb3cfaa8d8
Singleplayer works fine and so did the last server we had.
Does not happen for another player on the server. (No chunk loaders yet), However he is close to spawn. Not sure if spawn has some sort of chunkloading? Also tried teleporting far away from my place and testing the setup there, it worked just fine. -Confused-

Server Instance
Forge-1.7.10-10.13.3.1395-1710ls-universal
Botania r1.6-187

ModList
http://gyazo.com/640b985071f6ba2c2f9e54e8d6c72e46
Old Server list
http://gyazo.com/e951b1d42bdac9df5c03f99bacec9c47

Major difference would be; Biomes o' Plenty, HungerOverHaul, HQM and Agricraft
And also updating Botania.

**Comment by Lazersmoke** [comment]
@Elvarion new bug report please; this bug has been fixed in d0639411, but your bug may be different
