### ISSUE TITLE
Sideways greatwood logs + pure daisy = nothing

### ISSUE THREAD

**Issue by johnnydickpants** [Vazkii/Botania#867]
Sideways greatwood logs do not convert to livingwood. Normal greatwood logs convert with no issue.
![2015-05-01_21 18 53](https://cloud.githubusercontent.com/assets/1294493/7439411/3011f928-f048-11e4-99b2-357559863560.png)
![clip 2015-05-01 at 07 20 26](https://cloud.githubusercontent.com/assets/1294493/7439426/c07a8e4e-f048-11e4-95ad-0e3595060111.png)

**Comment by MrKunji** [comment]
Wich version of Botania?

**Comment by johnnydickpants** [comment]
185

**Comment by Lazersmoke** [comment]
I think sideways Thaumcraft logs are not oreDict "logWood"'s like they should be. You should try with silverwood logs
Relevant code:
- https://github.com/Vazkii/Botania/blob/master/src/main/java/vazkii/botania/common/crafting/ModPureDaisyRecipes.java#L22
- https://github.com/Vazkii/Botania/blob/master/src/main/java/vazkii/botania/api/recipe/RecipePureDaisy.java#L43 through line 45

**Comment by Vazkii** [comment]
That's a TC bug.

**Comment by Zsashas** [comment]
I've noticed this exact same issue, still occuring in version 221, with Greatwood logs and all Natura logs (Eucalyptus, Willow, etc). It's not just a Thaumcraft bug. Only vanilla logs are converted when sideways, all others are ignored.
