### ISSUE TITLE
Horn of the Wild destroys Tall Mystical flowers, gives nothing.

### ISSUE THREAD

**Issue by Adrellisartar** [Vazkii/Botania#871]
Horn of the Wild will destroy all Tall flowers equally, but give nothing as a drop.
If Tall Mystical flowers can be only be harvested by shears, being destroyed by the Horn seems needless; it covers a large enough area that it is unavoidable, except by code.

**Comment by MrKunji** [comment]
https://github.com/Vazkii/Botania/issues/807

**Comment by Adrellisartar** [comment]
how unfortunate. very well. it'll remain just an annoyance.
