### ISSUE TITLE
Ring of Loki Block being in places...

### ISSUE THREAD

**Issue by Deathlymad** [Vazkii/Botania#872]
A friend of mine is a huge fan of Botania. We are playing on a little private Server. He got the ring of Loki and started to play around with it. However after a while he discovered something you can see on the following pictures:

http://imgur.com/d7qcSTA,vOkJh3D,1Bt5NWK
http://imgur.com/8GQHm0t&5s8Go6k
http://imgur.com/d7qcSTA,vOkJh3D,1Bt5NWK
http://imgur.com/PEiyuJX,4eOOfFw,nxtyLUm
http://imgur.com/1hkbWf3

For some reason the Block selection seems to be placed (i guess by default) to places it shouldn't have been.

**Comment by Deathlymad** [comment]
The Server is running the newest available Botania Version ( 1.6 - 187 )

**Comment by Lazersmoke** [comment]
I have no idea what is happening in the screenshots. Is there a chronological order? What was he trying to do? Where did he right click? What did he want to happen? @Vazkii please tag needs info

**Comment by Deathlymad** [comment]
He never right clicked, the pictures are oin chronological order and the block is in every dimension. He wasn't trying to do anything

**Comment by Lazersmoke** [comment]
@Vazkii pull request submitted. A better fix may be to set the defaults in https://github.com/Vazkii/Botania/blob/master/src/main/java/vazkii/botania/common/item/relic/ItemLokiRing.java#L217 to null or the max integer value or something.
