### ISSUE TITLE
Add ores from Alexndr's Simple Ores 2 and akkamaddi's Additions to orechids' list.

### ISSUE THREAD

**Issue by Sinhika** [Vazkii/Botania#875]
That would be the orechid for overworld ores and the orechid ignem for nether ores, of course. The mods in question are Alexndr's Simple Ores 2 & Netherrocks (plugin for Simple Ores), and akkamaddi's Simple Tungsten & Hadite Coal (add-ons for Simple Ores).

I have already submitted a pull request that covers this ;-)

**Comment by Lazersmoke** [comment]
@Vazkii @Sinhika closed?
