### ISSUE TITLE
Sign order in the Eye of The Flugel is wrong.

### ISSUE THREAD

**Issue by brandaop** [Vazkii/Botania#877]
Aquarius and Capricorn are in reverse order, since Capricorn should come first.

**Comment by Vazkii** [comment]
I blame this on @wiiv

**Comment by Lazersmoke** [comment]
on it in all langs

**Comment by Chaotic-Potato** [comment]
I believe someone submitted a pull request to fix this issue.

**Comment by Lazersmoke** [comment]
@Vazkii actually fixed now :) lol
