### ISSUE TITLE
Ring of Odin has no Lexica Botania Entry

### ISSUE THREAD

**Issue by DrasticDemise** [Vazkii/Botania#878]
The lexica botania has no entry for the Ring of Odin in any part of the Lexica Botania this update. 

Also just so you know, the Aether 2 mod causes the sojourners sash to no longer step-assist, and causes the ring of Odin to duplicate health when changing dimensions, but these issues are strictly for your knowledge and a problem for the Aether devs.

**Comment by TheMadmanofChaos** [comment]
It is intend that the relic items are without a lexica entry. They have a poem in the tool tip, and that gives you hints as to the effects.
