### ISSUE TITLE
Minor typos

### ISSUE THREAD

**Issue by toyi85** [Vazkii/Botania#879]
Hello Vazkii,

While checking some entries in the Lexica  Botania I found a few typos you may want to check:

-In pages 1 and 7 of "Mystical Flowers" it says "Floral Fertlizer" instead of "Floral Fertilizer"
-In page 3 of "Flügel Tiara" it says "Misclaneous" instead of "Miscellaneous"
-In page 12 of "The Portal to Alfheim" the red text is marking "letting the" instead of "Elves"

Hope it helps, I love your mod. Thanks a lot!

**Comment by OJwithC** [comment]
Miscellaneous has two L's.

**Comment by Lazersmoke** [comment]
@Vazkii MrKunji's pull request is updated with the two L's part

**Comment by Lazersmoke** [comment]
@toyi85 Please close this issue, it will be fixed in the next version
