### ISSUE TITLE
Eye of Flugel GUI doesn't always render properly

### ISSUE THREAD

**Issue by Chaotic-Potato** [Vazkii/Botania#883]
Sometimes the GUI (except the text) for the Eye of the Flugel doesn't show up. It only happens it certain locations when facing a certain direction.

Screenshot:
![2015-05-02_21 10 25](https://cloud.githubusercontent.com/assets/12214800/7443443/e59b43e0-f10f-11e4-8b49-6e0270a610b0.png)

**Comment by Vazkii** [comment]
Give me a log.

**Comment by Lazersmoke** [comment]
We play on a server together, so [this](http://popcorn.no-ip.info/pastey.txt) log will contain this bug as well as the server hang from the other report.

**Comment by ProRedHD** [comment]
Could it be the Water? I know that water renders wrong sometimes. It renders in front of particles for example. Try to do it on land.

**Comment by Vazkii** [comment]
Can't reproduce.
