### ISSUE TITLE
Excalibur makes server hang forever 

### ISSUE THREAD

**Issue by Lazersmoke** [Vazkii/Botania#884]
It feels like a crash; the players time out, but the server selection screen shows them as being on. This  is the server's log up until it hangs: http://popcorn.no-ip.info/pastey.txt
This happens on 187, 186, 185, and 184, probably further back but I didn't test.

I think this is caused by the sword because it always happens when I am spamming the sword at things, especially in the Nether.

**Comment by Tfree77** [comment]
I've had the same issue. A mana burst from Excalibur causes all players to time out on the server and stop the server from accepting any connections. Restarting the server had no effect, and the only solution I could find was removing Botania from the server completely and reinstalling it. I tried it on versions 187 and 186 with a Tinker's glove w/ 500 redstone attached. After about 5-10 seconds of spamming left click, I crash the server. Server Console spam on server crash using version 187:

http://pastebin.com/W6EmePcs

I'm unable to get the full server console spam, but I've uploaded what I can in the following pastebin. The server Botania version is 187:

http://pastebin.com/CKw8JwzV

The last pastebin is what I believe is the relevant server spam from the previous server crash in version 186:

http://pastebin.com/P5rub2ef

**Comment by Lazersmoke** [comment]
Oh dear god, its the return of #408 ! specifically, http://pastebin.com/EQdVJZXi is present in both cases the Vec3 and Vector3 code is boggling my mind though, but it seems like the mana bursts are being accelerated to very high speeds or teleported to the (MAX_INT,MAX_INT) chunk or (2147483647,2147483647) Also, what does the Tinker's glove have to do with this/ what does it do? I very rarely use tinker's so IDK

**Comment by Tfree77** [comment]
The Tinker's glove gives you haste for everything. So, faster left clicks and more mana bursts.

**Comment by Vazkii** [comment]
I can't reproduce. But it does look like the same issue in #408
