### ISSUE TITLE
Issue with binding

### ISSUE THREAD

**Issue by Locotime** [Vazkii/Botania#885]
Before reading please note, this bug is in Botania v176, but I haven't noticed a changelog update saying that it has been fixed, so I assume that it is still a problem. (Pack is preludepack-reborn,found on technic launcher if you need to see if this issue is simply a mod conflict somehow)
Recently while playing on a server, I noticed that my ~~wand of the forest~~ Ring of the Aesir, Loki portion had decided to "bind" itself to my botanical brewery without me ever having used my ~~wand~~ Ring of the Aesir on it. I then tried to bind a mana spreader to another and my wand switched to function mode and turned the mana spreader around. 
Now whenever I try to bind a mana spreader the same thing occurs and my wand has bound itself to my petal apotheracry. I created a new wand, relogged on to the server, restarted my Minecraft, and even tried to break the offending items. When I broke them they disappeared, did not give any drops, and left their binding boxes hovering where they used to be.
https://imgur.com/a/zq7lB
(images of empty binding locations, I attempted to put the pictures directly in this report, but github decided to say that the gif and png images I was putting in weren't gif and/or png files)
I've yet to try fully restarting my computer, and the server has yet to perform a restart, so that may fix the issue, but it still is a fairly persistant and annoying one.
Update:
I have partially figured out the issue, it appears the my Ring of the Aesir allowed me to bind those two areas with my Ring of Loki binding, but I'm unable to remove the binding or start a new one. Now I can no longer have my Ring of the Aesir in my inventory if I'm binding spreaders
Update 2:
I have found my botanical brewery, after breaking it, it placed itself just outside of my loaded chunks breaking the chest that was already there and placing itself down in it's place, this location has also been "bound" by the Ring of Aesir's Loki portion.

**Comment by Vazkii** [comment]
What the actual fuck
