### ISSUE TITLE
EVERYTHING IS BROKEN

### ISSUE THREAD

**Issue by Vazkii** [Vazkii/Botania#893]
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

**Comment by Chaotic-Potato** [comment]
?

**Comment by OJwithC** [comment]
So... Everyone gets the new achievement? O.o

**Comment by BarbasTheDog** [comment]
Not specific enough; can't reproduce.

**Comment by MyDeloreanWontStart** [comment]
wat

**Comment by anexusarchon** [comment]
Have you turned it off and back on again?

**Comment by MyDeloreanWontStart** [comment]
Many times

**Comment by Simon04090** [comment]
What does everything mean? Did it get fixed already?

**Comment by Nova001Sol** [comment]
Can we have an ETA for a fix?

**Comment by ruifung** [comment]
Yes. One day after the next day after the next day, ad infinitum.
