### ISSUE TITLE
Crash using NEI (NotEnoughItems-1.7.10-1.0.4.106-universal)

### ISSUE THREAD

**Issue by FyeRee** [Vazkii/Botania#896]
I opened my inventory and tried to look up what you can craft with slime balls in NEI. gold ingots crashed it too and then I got tired of launching Minecraft to reproduce it. (U default bind). 

www.fyeporn.com/fml-client-3.log (paste sites didn't like the large file that 200 mods generated..)

**Comment by BionicFelps** [comment]
This also seems related to RotaryCraft... See https://github.com/Chicken-Bones/NotEnoughItems/issues/206

**Comment by Lazersmoke** [comment]
Can't reproduce with only:
- Botania r1.6-187
- CodeChickenCore-1.7.10-1.0.6.43-universal
- NotEnoughItems-1.7.10-1.0.4.106-universal
So it is probably a RotaryCraft issue

**Comment by FyeRee** [comment]
I'm trying to whittle it down a little more when I get home tonight

**Comment by FyeRee** [comment]
It was a Better Loading Screen conflict somehow..

**Comment by BionicFelps** [comment]
FyeRee, try this with the latest version of NEI, as Chicken-Bones/NotEnoughItems#206 has been fixed.
