### ISSUE TITLE
[Updated OP] Crash when using Corporea Intercepor or Funnel with an Empty Item Frame

### ISSUE THREAD

**Issue by GeistInMachine** [Vazkii/Botania#897]
[Edited to consolidate issues].

Original Corporea Interceptor Crash:
--
Original Crashlog:
http://pastebin.com/xgngrKRB
Original Setup:
![2015-05-04_07 11 42](https://cloud.githubusercontent.com/assets/12229465/7454906/0077b25c-f22d-11e4-9252-65f711dfd38e.png)
Upon Experimenting, I discovered the crash only occurs when there is an empty item frame on the Corporea Interceptor. Removing the item frame stopped the crash. ![2015-05-04_07 14 05](https://cloud.githubusercontent.com/assets/12229465/7454944/36292818-f22d-11e4-985a-e8239e6fbb2c.png)

Corporea Funnel Crash:
--
After more testing, the crash also occurs for Corporea Funnels when they are triggered wth an empty Item Frame.

New Crashlogs:
http://pastebin.com/91aKEv7A
Crash occured when I triggered a Corporea Funnel that had an empty Item Frame with a Project Red State Cell. After a relog, the State Cell appears to be triggered until updated.
![2015-05-04_17 12 32](https://cloud.githubusercontent.com/assets/12229465/7465167/c46ca926-f280-11e4-95b2-8156ee352a7b.png)

Upon further testing, a second crash occurs when I attempt to place a button:
http://pastebin.com/1eU2HDyP
Picture is after a relog.
![2015-05-04_17 00 06](https://cloud.githubusercontent.com/assets/12229465/7465094/52cf12aa-f27f-11e4-8ca7-d30cb59883d4.png)

Crash also occurs when removing button:
http://pastebin.com/K2qPYA36
Picture is after a relog.
![2015-05-04_17 09 46](https://cloud.githubusercontent.com/assets/12229465/7465149/681443aa-f280-11e4-8e46-8f5fc1206b2d.png)

Removing the empty Item Frame removes all crashes

**Comment by Vazkii** [comment]
Can I have a screenshot of the setup?

**Comment by GeistInMachine** [comment]
Original Setup:

![2015-05-04_07 11 19](https://cloud.githubusercontent.com/assets/12229465/7454905/00737e44-f22d-11e4-9a40-0b6f48680226.png)
![2015-05-04_07 11 42](https://cloud.githubusercontent.com/assets/12229465/7454906/0077b25c-f22d-11e4-9252-65f711dfd38e.png)
Upon Experimenting, I discovered the crash only occurs when there is an empty item frame on the Corporea Interceptor. Removing the item frame stopped the crash. ![2015-05-04_07 14 05](https://cloud.githubusercontent.com/assets/12229465/7454944/36292818-f22d-11e4-985a-e8239e6fbb2c.png)
However, It shouldn't crash just because I forgot to fill an item frame

**Comment by GeistInMachine** [comment]
Updated OP for more findings
