### ISSUE TITLE
Undefined flowers after storing/loading inventory

### ISSUE THREAD

**Issue by hupster** [Vazkii/Botania#898]
I'm using a Cauldron server with Multiverse plugin to have multiple words. Each user has a separate inventory, for creative and survival. The inventory is stored and loaded by another server plugin called LimitedCreative (https://github.com/possi/LimitedCreative).

After an inventory has been stored and loaded, all Botania flowers revert to "Botania Flower", saying "If you have this, it means something went wrong, you should report it".

Example of data stored in .yml files:

inv:
  '0':
    ==: org.bukkit.inventory.ItemStack
    type: BOTANIA_SPECIALFLOWER
    amount: 21
  '1':
    ==: org.bukkit.inventory.ItemStack
    type: BOTANIA_SPECIALFLOWER
    amount: 3

Some items show meta data (enchantments e.d.), the flowers don't..

**Comment by Vazkii** [comment]
>Cauldron server with Multiverse plugin
That's your problem. It doesn't save NBT.
