### ISSUE TITLE
Terrasteel Not Crafting Properly

### ISSUE THREAD

**Issue by candy49997** [Vazkii/Botania#901]
When making terrasteel, sometimes the particles stop at the very last second and won't change the materials used to craft it. There is no crash or the game freezing, except the terrasteel production...
![2015-05-04_16 17 31](https://cloud.githubusercontent.com/assets/4218730/7464785/e6278500-f27a-11e4-87c4-1f6948f2ae92.png)

**Comment by Lazersmoke** [comment]
Do you just barely have enough mana? It might be almost crafting, then the portal steals the mana or something like that...

**Comment by candy49997** [comment]
I'm pretty sure I had enough mana... Even if I didn't, it would have finished because my manastar showed that I was producing more mana than I was using before activating the terrasteel production... It did not progress at all...

**Comment by Lazersmoke** [comment]
If you take the items off and put them back on does it work? Do you need to reload the world? Restart the game? Single player or multiplayer? Are you using MCPC+/Cauldron? Fastcraft? Mystcraft? Where are you pulling mama from with the spark?

**Comment by candy49997** [comment]
I am using Fastcraft and Mystcraft. This is singleplayer. I found out that this is a visual issue because the mana is not being drained even though it looked like it...

**Comment by Vazkii** [comment]
Does this always happen or did it only happen once? Do you have more screenshots of the setup?

**Comment by candy49997** [comment]
Here is the mod list: http://pastebin.com/6dRMNFeH
Here is a log: http://pastebin.com/yUTqUUsc
This happened multiple times, but not every time.
I am using the latest version of Botania (R1.6-187).

**Comment by Lazersmoke** [comment]
Would tick skipping mess up the crafting process @Vazkii?

**Comment by Vazkii** [comment]
Yes, server lag might cause this.
