### ISSUE TITLE
Mana Spreaders and Mana Pools Disappearing When Looking Though Alfheim Portal

### ISSUE THREAD

**Issue by candy49997** [Vazkii/Botania#904]
Um... Is this supposed to happen? I have fastcraft enabled.
Before ![2015-05-04_19 34 50](https://cloud.githubusercontent.com/assets/4218730/7466259/bdc9c720-f294-11e4-8ac4-0fe9224446ce.png)
After ![2015-05-04_19 34 53](https://cloud.githubusercontent.com/assets/4218730/7466264/c9900448-f294-11e4-92c2-1fa3f6dd5a34.png)

**Comment by Lazersmoke** [comment]
See #822
