### ISSUE TITLE
Infinite range for the ring of far reach

### ISSUE THREAD

**Issue by Nikkolino99** [Vazkii/Botania#907]
I'm using Botania 1.6-187, with latest Forge installed, using Vanilla MC and I installed Optifine, but it's not a visual problem, when I put my ring of far reach in the ring slot, I have almost infinite distance for destroying  and using blocks, but I do not crash when I'm trying to do this.
As you can see, it's zoomed with optifine option, but I'm at least 50 blocks away from there, and I know that the Ring should increase the radius for only a few blocks
![2015-05-05_21 48 13](https://cloud.githubusercontent.com/assets/7397855/7481748/b257b9fe-f372-11e4-8da0-bf14b39dedb6.png)

**Comment by Lazersmoke** [comment]
If you go over to where you break or place the block, does it actually act as if the block is there? Does reloading the world reset any changes you make? I remember this happening to me before but it was only client-side. Still a bug, but less serious.

**Comment by Nikkolino99** [comment]
Yes, The block is broken/placed like if I where there to place it
Il 05/Mag/2015 22:28, "Sam Quinn" <notifications@github.com> ha scritto:

**Comment by Lazersmoke** [comment]
Alright, I just looked at the source code and it looks pretty clean, but then again I am newish to java. What forge version are you using?

**Comment by Nikkolino99** [comment]
I'm using 10.13.2.1291

**Comment by Nikkolino99** [comment]
Optifine HD B6
Il 05/Mag/2015 22:46, "Sam Quinn" <notifications@github.com> ha scritto:

**Comment by Lazersmoke** [comment]
I couldn't reproduce it. Can you provide a full list of mods that you are using? If there are a lot then use [this](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1289490-all-versions-mod-lister-lists-the-mods-you-are)

**Comment by Vazkii** [comment]
Does this happen only with botania? If not try to find which mod causes the problem. If it's Aether I don't want to hear it.

**Comment by Nikkolino99** [comment]
I don't nave Aether installed
 Il 06/Mag/2015 12:50, "Lizbeth Rika" <notifications@github.com> ha scritto:

**Comment by OJwithC** [comment]
Do  you have Morph?

**Comment by Nikkolino99** [comment]
Yes I do
Il 06/Mag/2015 19:45, "OJwithC" <notifications@github.com> ha scritto:

**Comment by 0ghost0** [comment]
So I managed to recreate this, or a similar effect by doing the following:
1. make two rings of far reach and place them in your baubles slot
2. die (I threw myself into lava)
3. your reach stays, you can go ahead and repeat the process as many times as you like

Only Botania 1.6-187 installed (and baubles 1.0.1.10)
Though the effects are the same, this might be a separate problem

**Comment by OJwithC** [comment]
Then I believe https://github.com/Vazkii/Botania/issues/635 is the same.

**Comment by Nikkolino99** [comment]
So I can close this, if vazkii said that she don't want to fix this?
