### ISSUE TITLE
"graphical error" with ring of loki

### ISSUE THREAD

**Issue by PharMiki** [Vazkii/Botania#910]
This is not a huge problem but it should be easy to fix it.
When the ring of loki has no origin defined the game renders the origin wireframe at
(x,y,z)=(0,-1,0)
(you can see it through the ground in the form of a shining dot or like the screenshot if you come close/break bedrock)

![2015-05-06_15 21 01](https://cloud.githubusercontent.com/assets/12104926/7493823/3eca8c86-f404-11e4-8cc6-05400d57ec39.png)

The problem is probably in the ItemLokiRing.java on ln201
```
public ChunkCoordinates getSourceWireframe(EntityPlayer player, ItemStack stack) {
	return getOriginPos(stack);
}
```
should probably be something along the lines of:
```
public ChunkCoordinates getSourceWireframe(EntityPlayer player, ItemStack stack) {
	ChunkCoordinates origin = getOriginPos(stack);
	return origin.posY==-1? null : origin;
}
```

P.S. i was hoping it was an easter egg :(

**Comment by Vazkii** [comment]
It's great that you can write code but not read past issues.
