### ISSUE TITLE
[Request] Keybind for Toggling Magnet On/Off

### ISSUE THREAD

**Issue by cdl1051** [Vazkii/Botania#914]
Can we get a key bind to toggle the magnet on/off easily.  Shift works great in some instances but often you want it off for a while like while watching someone build.  Taking it off works but is obviously more hassle than mashing a key.  I searched and did not find this suggestion previously but I apologize if this has already been suggested and denied.  Thanks for a great mod!

**Comment by Vazkii** [comment]
No more keybinds for items, please. Every mod has a "toggle item on/off keybind" at this point that if you want to make use of them your keyboard becomes a rocket control panel.
