### ISSUE TITLE
RIng of Loki/Aesir Derpy Selection Square

### ISSUE THREAD

**Issue by hjake123** [Vazkii/Botania#918]
Basically, the square teleports to a location beneath the bedrock when I deselect it. The location is 0, -1, 0. The derpy box is visible from anywhere in loaded chunks. It remains even if I remove the ring and even if I reload the game. EDIT: It only exsts while the ring of Loki/Aesir is in my inventory, but it does not need to be equipped.

![2015-05-06_20 36 29](https://cloud.githubusercontent.com/assets/5803666/7507082/9c111bf0-f42f-11e4-90f8-b36e9b229fc1.png)
![2015-05-06_20 24 50](https://cloud.githubusercontent.com/assets/5803666/7507073/80299b2e-f42f-11e4-83b5-3f90a0107ea5.png)
![2015-05-06_20 34 20](https://cloud.githubusercontent.com/assets/5803666/7507074/802ae1a0-f42f-11e4-93ff-5b0a56724ac6.png)

**Comment by 0ghost0** [comment]
This was already mentioned and closed in #899
