### ISSUE TITLE
Tall Botania flowers don't drop items

### ISSUE THREAD

**Issue by DarkRaxZax** [Vazkii/Botania#920]
I don't think this requires a long explanation... They just don't drop anything, no matter if you punch it at the top or at the bottom block.

I haven't seen any report related to this, but in chase it was posted and it's already fixed I should thank you for your nice mod and all the hidden easter eggs. I found it on the latest version (r1.6-187.jar) with the latest version of Forge.

Appart from this, can I get the special flower for reporting a bug? Thanks Vazkii :D

**Comment by Vazkii** [comment]
https://github.com/Vazkii/Botania/blob/master/src/main/resources/assets/botania/lang/en_US.lang#L1405
