### ISSUE TITLE
Question regarding the Drum of the Wild and Growthcraft Crops

### ISSUE THREAD

**Issue by Sunconure11** [Vazkii/Botania#922]
It seems Growthcraft crops are unaffected by the Drum of the Wild. Is there anything you can do about this, or would this have to be something the dev of that mod would have to do?

**Comment by Lazersmoke** [comment]
Although it could be done on Botania's end, it is much better for it to be done by the Growthcraft developer. If you want to contact Gwafu yourself, send him this link: https://github.com/Vazkii/Botania/blob/861f40e64cd64ad8345065c6843261fbd3ca5c6b/src/main/java/vazkii/botania/common/item/ItemGrassHorn.java#L128

**Comment by Sunconure11** [comment]
Sent, but, I'll leave this up, incase there is anything that can be done on this side.

**Comment by Lazersmoke** [comment]
Just a heads up, that was probably intentional on the part of the Growthcraft dev to not allow his crops to follow normal plant rules.

**Comment by Sunconure11** [comment]
I'm sure it is, but, I'm still making sure to see if there is anything Vazkii can do on her side.
