### ISSUE TITLE
Gaia Guardian #1 disabling all potion effects, including Botania brews/Purple is not a valid indicator?

### ISSUE THREAD

**Issue by Trisscar05** [Vazkii/Botania#925]
Admittedly this is with the FTB Regrowth modpack, but I'd still like to check if this is supposed to happen even with only Botania installed.
As the title, all potion effects are negated every couple seconds except the various bad ones from the Guardian itself, and for some reason the mining fatigue effect from my TC cleaver, all of which makes sense I suppose. However brew effects like absorption, resistance, feather falling, etc. are all immediately cleared as well, despite the book suggesting these for the fight, hence my confusion.

Secondly, (and please do let me know if you'd rather this be a different topic) I've also noticed that the purple goo, which I assume is supposed the be an indicator of where you'll get the wither debuff if you stand in it, does not actually mark where such a thing will happen. For instance, if the Guardian is on one side of the arena, the purple will only stretch about halfway, and still leave large areas exposed; But you still get withered no matter where you stand. This also happens if the Guardian is standing on the beacon, regardless of whether there appear to be safe areas or not.

**Comment by OJwithC** [comment]
For the first part of your question, the Guardian disables (positive?) effects that last 8 seconds (or so) or less. Not sure how long those potion effects you had are though.

**Comment by Trisscar05** [comment]
The basic 1:30 Mana Vial ones you make with the Botanical Brewery. I haven't tried the ones with Alfglass Flasks yet, but I've also noticed that the regen from Magical Crops Magic Food is negated, though I think that might only be six seconds itself.
