### ISSUE TITLE
[Feature Request] Drum of the Wild Agricraft integration

### ISSUE THREAD

**Issue by gr8pefish** [Vazkii/Botania#927]
Currently when the drum of the wild is activated it breaks both the crops and the seeds on Agricraft crop sticks. Since there is no way to replant the seeds on the crops using Botania (dispensers don't work for this), I was wondering if you could add in some special compatibility to make the drum of the wild only harvest the crops it finds nearby, rather than outright breaking them, as this would allow a purely botanical form of gardening with Agricraft.

**Comment by Lazersmoke** [comment]
Based on previous issues, I doubt this will be added. However, I am but a pawn, and summon the great @Vazkii decide this issue
