### ISSUE TITLE
Ring of Loki/Aesir won't place blocks against origin block

### ISSUE THREAD

**Issue by Iapyx** [Vazkii/Botania#928]
When placing multiple blocks, the ring of Loki/Aesir won't place a block if the block it would be placing it against was the initial block placed of the sequence. (I'm assuming the ring works by something like having a fake player right click with the block at each location in order with the same orientation the player chose for the first block. If not, my reasoning behind why this didn't work is probably nonsense, but it may still be a bug.) Example with images below, done in Botania 184 in an FTB infinity 1.5.1 world, replicated in 187 with just Botania and Baubles.

http://imgur.com/a/3tAGW#YDyTZeZ

Top image is the set up. 2x2x1 square on left selected in order of numerals, so block 1 is the origin, then 2,3,4. A and B are the block faces I clicked on for the two trials: A down onto the ground, B flat against the wall. 

Bottom image is the result. In attempt A, block 3 was successfully placed against block 2. However, block 4 is missing (red outline), as it wasn't able to be placed against block 1. However, in attempt B by clicking horizontally against the wall all blocks were placed against pre-existing surfaces, and so all 4 successfully placed.

**Comment by Vazkii** [comment]
Intended. Not doing so would mean terrible amounts of messy recursion.
