### ISSUE TITLE
Tangleberrie on a spoofer changes texture of targeted functional or generating flower.

### ISSUE THREAD

**Issue by createdforissues** [Vazkii/Botania#934]
Build something like this
![2015-05-09_20 44 02](https://cloud.githubusercontent.com/assets/12113532/7551281/31912a5e-f68c-11e4-8c44-45e10ea2dcdd.png)
and update flower
![2015-05-09_20 44 04](https://cloud.githubusercontent.com/assets/12113532/7551282/3d0a93c0-f68c-11e4-8bda-16b25c274641.png)

**Comment by Lazersmoke** [comment]
can confirm/reproduce
