### ISSUE TITLE
Can't do the thing

### ISSUE THREAD

**Issue by 3rg0** [Vazkii/Botania#936]
The tiny potato doesn't believe in me! Just look at him! 

![2015-05-09_22 05 03](https://cloud.githubusercontent.com/assets/12375008/7551856/3ca4e7b2-f698-11e4-80f8-48ece8da1c8d.png)

He's silently judging me with his dead eyes! D:

**Comment by Lazersmoke** [comment]
Intended behavior; the potato judges those who post unclear bug reports

**Comment by Vexatos** [comment]
Definitely needs the uwot label.
