### ISSUE TITLE
Thaumcraft Crucible Rod of the Seas support

### ISSUE THREAD

**Issue by ProRedHD** [Vazkii/Botania#939]
Can you add Thaumcraft Crucible support to the Rod of the Seas?

**Comment by Lazersmoke** [comment]
It is technically possible to do, but Vazkii typically doesn't add special cases for everything. This is not a no, but it is @Vazkii's choice.

**Comment by ProRedHD** [comment]
@Lazersmoke There already is some TC Integretion, so it would be fitting.
