### ISSUE TITLE
Trodden Dirt is not recognized by tools

### ISSUE THREAD

**Issue by Zylande** [Vazkii/Botania#940]
Just a curious issue - Trodden Dirt is not cleaned up quicker with a higher efficiency on a shovel, pickaxe, nor axe. Should I be using something else to clean up the dirt?

**Comment by Omnissia** [comment]
What is your version? It was already fixed in v.185 - "Fixed shovels not being effective against Trodden Dirt."

**Comment by Zylande** [comment]
Ah, sorry, I thought I had already updated Botania for everyone on my server. Seems it is still 170. My apologies, and I'll make sure to update right now. You may have already fixed the other, too, with the leaves.
