### ISSUE TITLE
Horn of the Canopy - Doesn't appear to work on Thaumcraft leaves

### ISSUE THREAD

**Issue by Zylande** [Vazkii/Botania#941]
The Horn of the Canopy doesn't appear to break leaves on the following:
Silverwood Leaves (209:1 is the item ID I have)
Greatwood Leaves (209 is the item ID I have)

Appears to work with all other trees I've tested (witchery and vanilla)

I don't know if this is on your side or Thaumcraft's

**Comment by MrKunji** [comment]
It's on Azanor's side as far as I remember.

**Comment by Lazersmoke** [comment]
Yes, that looks right, azanor needs to implement or extend standard Minecraft leaves to make the horn work on them, but this may also be intentional, similar to how agricraft works.
