### ISSUE TITLE
Config setting for Hunger / Satiation of Mana Cookie

### ISSUE THREAD

**Issue by GauHelldragon** [Vazkii/Botania#944]
Mods like "Hunger Overhaul" change the balance of all food values. Since the mana cookie restores hunger and satiation using potion effects, that mod cannot change the mana cookie so that it is in more line with the balance changes it makes.

It would be great if there was a config setting that allowed you to tweek how much hunger and satiation restore.

**Comment by Lazersmoke** [comment]
@Vazkii usually doesn't like config options for special cases. Besides, the point of the mana cookie is that it fills your hunger bar completely, so to change that would be to substantially change the item.

**Comment by Elvarion** [comment]
Id suggest getting ModTweaker and just disabling the Mana Cookie. Thats what I did :)
