### ISSUE TITLE
Excaliber speed description bugs out with Sharpness.

### ISSUE THREAD

**Issue by Konork** [Vazkii/Botania#946]
The Sharpness enchant seems to amplify the listed speed bonus on Excaliber. You don't actually get the increased speed, which I kind of expected since it's a pretty huge jump just from unenchanted to Sharpness I, so this is just a minor visual issue.
![2015-05-10_23 56 35](https://cloud.githubusercontent.com/assets/5567194/7559756/4a491b4e-f770-11e4-8c6b-07e23b73da7d.png)
![2015-05-10_23 56 36](https://cloud.githubusercontent.com/assets/5567194/7559757/4a4c102e-f770-11e4-9269-54ea31e8bd5a.png)

**Comment by MrKunji** [comment]
Vanilla bug.

**Comment by Lazersmoke** [comment]
@MrKunji should we work around or leave it?

**Comment by MrKunji** [comment]
Vazkii said it is not worth fixing.
