### ISSUE TITLE
Spreader's aiming beam shoots in multiple directions

### ISSUE THREAD

**Issue by Omnissia** [Vazkii/Botania#947]
![2015-05-11_00 51 34](https://cloud.githubusercontent.com/assets/11790433/7560710/4d1ee070-f7ce-11e4-8cea-6397b6038aee.png)

Latest version. The bug is rather rare, only encountered two or three times by now.

**Comment by MrKunji** [comment]
It's just a visual thing, it may or may not be related to Optifine.
