### ISSUE TITLE
Make Ring of Loki/Aesir toggleable

### ISSUE THREAD

**Issue by Cypher121** [Vazkii/Botania#948]
Actually, not so important on Loki, it can be simply unequipped, but for Aesir it's quite bad, 'cause it has other effects and isn't only worn for building ability. I can't use anything that requires sneak-clicking with bare hand (e.g., Armor Stands) with it.

**Comment by Lazersmoke** [comment]
#851 
@Dylan4ever please close the issues that should be closed; @Vazkii hasn't been around
