### ISSUE TITLE
Rannucarpus won't take items if they are on a pressure plate 

### ISSUE THREAD

**Issue by acpcalin** [Vazkii/Botania#949]
both wooden and weighted pressure plates don't work
![2015-05-11_19 50 47](https://cloud.githubusercontent.com/assets/9417983/7570198/1252f17c-f817-11e4-9445-f3ee7f63830a.png)

**Comment by MrKunji** [comment]
Does it works if the flower isn't touching the Pressure Plate?

**Comment by acpcalin** [comment]
yes

**Comment by MrKunji** [comment]
You may haven't noticed, but the Pressure Plate emits redstone signal, thus, it disables the flower.

**Comment by acpcalin** [comment]
Oh, I didn't know that. I'm sorry for the wrong bug report
