### ISSUE TITLE
Dayblooms crashing my game

### ISSUE THREAD

**Issue by antoniagames** [Vazkii/Botania#950]
When I place too many dayblooms my game crashes. It happened earlier today and I restored it from a backup, tried creating dayblooms again and when I placed my 13. daybloom my game crashed. Have been able to reproduce the crash multiple times now. 

FML log: http://pastebin.com/FTnrzT50

Crashlog: http://pastebin.com/nSD609Xq

**Comment by MrKunji** [comment]
Was fixed in https://github.com/Vazkii/Botania/commit/29cb302cd4570bef92a58f5f58a9612768b8e91a, just update to 187.

**Comment by antoniagames** [comment]
Thanks! So sorry, really thought I updated to the latest Botania today. Great mod! Loving it!
