### ISSUE TITLE
Mana Enchanting does not check if an item is actually able to be enchanted.

### ISSUE THREAD

**Issue by TheMadmanofChaos** [Vazkii/Botania#951]
Forge: 10.13.3.1355-1.7.10
Botania: 187

Some mods, such as blood magic, add armor or tools that is set to be unenchantable by giving it an enchantability of zero(Or Integer.MIN_VALUE). Mana enchanting ignores this and applies enchants anyway, which can be problematic.

**Comment by Vazkii** [comment]
That's not how you make an item unenchantable, you do so by setting isItemTool to false.
