### ISSUE TITLE
Phantom and magnetizing lenses act strangely with life imbuer.

### ISSUE THREAD

**Issue by createdforissues** [Vazkii/Botania#954]
![2015-05-12_13 47 57](https://cloud.githubusercontent.com/assets/12113532/7585650/93b307ac-f8ad-11e4-80b7-c77780a80941.png)

From four left spreaders only elven one is actually sends his mana to life imbuer, for the rest burst travel through it, even though visually it stops at life imbuer.

Burst from right spreader with magnetizing lens homes in on lmbuer but starts slowing down and diminishes without ever reaching the target.

**Comment by Vazkii** [comment]
The block has such a small bounding box this will happen, not much I can do.
