### ISSUE TITLE
WhiteListing Dimensions

### ISSUE THREAD

**Issue by Dzurky** [Vazkii/Botania#957]
Hey Vazkii, I was wondering if in the future it would be possible to add a config option which would allow us to whitelist in which dimension the mystical flowers can spawn. For example in my case, I'd really love the mystical flowers to spawn in the Twilight Forest only as I want to avoid getting into Botania easily right off the bat :p

**Comment by Lazersmoke** [comment]
@Dzurky not saying no, but very unlikely

**Comment by Dzurky** [comment]
ah, that's a shame
