### ISSUE TITLE
Excaliber seeking the one who swings it (#188) | Suggestion on Ring of Loki

### ISSUE THREAD

**Issue by homemmakako** [Vazkii/Botania#958]
After R1.6 188 whenever I swing the excaliber the mana beam just keeps going back and forth, trying to hit me. It doesn't damage me, but the beam becomes useless for long ranges (when you get really close to the target the projectile eventualy hits it).

On a different note, can you make it so the ring of Loki/Aesir don't work on blocks with NBT data (I think that is how they are called :stuck_out_tongue_winking_eye: ). Some blocks from other mods require shift+rc interaction, which conflicts with the functionality of the rings. Some examples would be Thaumcraft jars and alembics, JABBA barrels, SFManager's cables (block gates, for instance), and so on. Everytime you have to interact with those blocks you must first remove the ring and then do whatever you have to, or else you'll end up making a mess.

**Comment by homemmakako** [comment]
Just realized the second note is pretty much the same as #851 , my bad. However, the 1st bug is still a thing :smile:

**Comment by MrKunji** [comment]
Are you equiped with the Tiny Planet by chance?

**Comment by Vazkii** [comment]
It's a dumb logic flaw on my end, it's easy to fix.
