### ISSUE TITLE
Ring of Aesir Health Dupe

### ISSUE THREAD

**Issue by cibastian** [Vazkii/Botania#971]
I've noticed while playing that my health increases, this happenes whenever I wear the ring of aesir. I gain 10 extra hearts, now I know that is intended. The thing is that if I drop it from my inventory (specifically the bauble equipment window while it's equipped) it takes away 10 hearts but once I recraft it and re-equip it it gives me 20 extra hearts resulting in the following:
![2015-05-15_12 49 08](https://cloud.githubusercontent.com/assets/2328915/7650693/b2193c38-fb01-11e4-9d40-8b24b50c27ff.png)

This is in a test instance running Botania R1.6-188, Baubles 1.0.1.10 and Forge 10.13.3.1403 only.
here's the log: https://gist.github.com/cibastian/f656f6d08ccff796234f

**Comment by Vazkii** [comment]
Hm, interesting. I'll have a look.

**Comment by Vazkii** [comment]
I can't reproduce this.

**Comment by cibastian** [comment]
Will uploading a video of recreating this problem help?

**Comment by Vazkii** [comment]
Yeah, that would help so I can see exactly what you're doing.

**Comment by cibastian** [comment]
here you go: https://youtu.be/Ml77gNKH9dk
tell me if you need anything else

**Comment by Vazkii** [comment]
Ah, interesting, it only happens when right clicked from the hotbar.
