### ISSUE TITLE
Bug with bound items and Mojang name changing 

### ISSUE THREAD

**Issue by jamesthelad** [Vazkii/Botania#975]
I have changed my name with mojang and this breaks the bound system which means in theory people can steal other people's bound items by doing mojang name change.
Also when you change your name your bound item don't change with your player data so i lose all my rings e.g

**Comment by Vazkii** [comment]
I'm not fixing this, the whole username thing is a pain. Just ask to have the baubles' NBT data changed or do it yourself in a server..

**Comment by Zsashas** [comment]
Just to point out, I'm pretty sure you can't take a username already in use so you can't steal someone's bound items this way.
