### ISSUE TITLE
API Question

### ISSUE THREAD

**Issue by Lazersmoke** [Vazkii/Botania#977]
Do I import `import vazkii.botania.common.block.mana.BlockPool;` and then say `public class BlockElvenPool extends BlockPool {`?

Or do I do lots of imports from the api and from minecraft and then say `public class BlockElvenPool extends BlockContainer implements IWandHUD, IWandable, ILexiconable{`? (and re implement all of the BlockPool things manually?)

I am asking because the FAQ link to the API points to https://github.com/Vazkii/Botania/tree/master/src/main/java/vazkii/botania/api, so it seems like you should clone the repository and copy that folder into your working directory, then import it into the project, which seems illogical considering that there is a deobf download on the website as well. I am also asking because [this](https://github.com/Lazersmoke/Botanical-Workshop/blob/master/src/main/java/lazersmoke/botanical/common/block/mana/BlockElvenPool.java) works, but is mostly copy/paste from [here](https://github.com/Vazkii/Botania/blob/master/src/main/java/vazkii/botania/common/block/mana/BlockPool.java)

**Comment by Vazkii** [comment]
It depends on what access you have. If you only have access to the API, you need do the latter and redo the implementation. If you can access the botania code you can do the former but it might break if I change it. Also, please refrain from using the issues for questions and ask them on IRC in the future.

**Comment by Lazersmoke** [comment]
OK ty
