### ISSUE TITLE
Shift right clicking a double-chest with flower pouch only shows 1 chest

### ISSUE THREAD

**Issue by GauHelldragon** [Vazkii/Botania#978]
If you shift right click a double chest with the flower pouch with flowers in it, it puts the flowers into the chest (as expected), but then shows a GUI for a single chest.

**Comment by Lazersmoke** [comment]
This is minecraft's fault, IIRC. Double chests are a total hack, and supporting them is a waste of time IMO

**Comment by Vazkii** [comment]
No, this is fixable, I do have double chest detection code.

**Comment by Lazersmoke** [comment]
Sorry, I must have been thinking of Azanor

**Comment by Entoarox** [comment]
@Vazkii just cause its fix-able doesnt change the fact that double chests are a total hack! :stuck_out_tongue_winking_eye:
