### ISSUE TITLE
Can add items to dry petal apothecary using last recipe.

### ISSUE THREAD

**Issue by GauHelldragon** [Vazkii/Botania#979]
If you complete a recipe of the petal apothecary, and then right click it while it is dry, it will make the splash sound and particles will appear. If you then add water you'll see the petals were added. It probably shouldn't allow you to add in the last recipe if it's dry?

**Comment by GauHelldragon** [comment]
If this is the intended behavior, it probably shouldn't be making the 'splash' sounds then.

**Comment by Barhandar** [comment]
Or rather, it should use buckets/rods of the seas automatically as well.
