### ISSUE TITLE
Adorned Flugel Tiara won't render special wings if it's combined with a cosmetic bauble

### ISSUE THREAD

**Issue by CatDany** [Vazkii/Botania#987]

**Comment by MrKunji** [comment]
It is intended, right?...

**Comment by CatDany** [comment]
I don't know, it's sometimes good, sometimes bad.

**Comment by Vazkii** [comment]
It's intended.

**Comment by Durpady** [comment]
That's a shame.  It'd be nice if combining a Flugel Tiara (with Flugel Wings) with a Unicorn Horn produced an "Alicorn Amulet".
