### ISSUE TITLE
Getting a crash with a new world in the latest version

### ISSUE THREAD

**Issue by Chefbarbie** [Vazkii/Botania#989]
http://pastebin.com/vCUMqKvN

No fastcraft or optifine involved (both are disabled for testing).

**Comment by Vazkii** [comment]
Does this happen with only botania?

**Comment by Chefbarbie** [comment]
With just latest forge, bauble and botania the world loads up fine, any idea what mod may be doing it before closing this?

**Comment by Vazkii** [comment]
¯\_(ツ)_/¯

**Comment by Entoarox** [comment]
If you install fastcraft you can use one of its config options to have fastcraft trace issues like that, would make it a lot easier to find and identify the issue.
