### ISSUE TITLE
Make Relic Items Regettable

### ISSUE THREAD

**Issue by Timemon** [Vazkii/Botania#992]
Hey this isn't an urgent issue but it would be nice to be able to get the Relic items again if you lose them somehow e.g. dropped into void/lava, despawned on the ground etc.

**Comment by Barhandar** [comment]
They do not burn in lava and do not despawn.

**Comment by Entoarox** [comment]
@Barhandar multiplayer + malicious trolling, enough said I hope? (Just cause they damage non-owners wont stop a troll from taking one and trashing it immediately you know...)

**Comment by MrKunji** [comment]
'Relic items no longer despawn naturally. They can still be destroyed by explosions, lava, etc, so you should still be careful.' It hasn't changed since  174. I would recommend adding Resolute Ivy on your Relics for emergency reasons.
