### ISSUE TITLE
Crash when seeds touch the Apothecary

### ISSUE THREAD

**Issue by Zsashas** [Vazkii/Botania#996]
It happens randomly, the first time was when I tossed the seeds to make my fourth Pure Daisy, but the first three didn't have problems. The second time, seems to be when an Octorok (ZSS+) or its projectile rock hit the Apothecary. It looks like the same crash both times.

EDIT: I forgot that Octoroks drop seeds for some reason. So it's Vanilla seeds causing the issue, but not every time.

EDIT2: It is a normal cobblestone Petal Apothecary, filled with water, and with the vines on it.

http://hastebin.com/erizinetoy.coffee

**Comment by TheWhiteWolves** [comment]
Have you tried replicating this with only Botania installed as one of that long list of mod you have installed could be changing something

**Comment by Zsashas** [comment]
It doesn't even happen 100% of the time, I used the Apothecary at least 50 times before it happened once. Also, I don't have any mods that affect vanilla seeds.

**Comment by Zsashas** [comment]
After some testing, I cannot reproduce this with only Botania and Baubles. Although I did find that the colored Apothecaries can't have vines on them...

**Comment by TheWhiteWolves** [comment]
ok, it may be that another mod is adding something to the vanilla seeds or looking for vanilla seeds in some way.

My suggestions would be either go through the arduous process of trying each mod in your setup with Botania or maybe grabbing an NBT explorer type program/mod and see if anything has been added to the vanilla seeds.

As for the mossy coloured alters, that would need looking into s you might want to open a separate issue for it.

**Comment by Zsashas** [comment]
Using MCEdit (2), it seems to be just regular seeds in every way. There are two seeds in the entity.

**Comment by TheWhiteWolves** [comment]
mmm, you will most likely have to go through each mod testing them to find the cause, otherwise it will be very hard to find a solution to it.

**Comment by Zsashas** [comment]
Further testing with the current pack, it only happens with an Apothecary that has water in it, if there is nothing else already in it.  Empty ones don't cause the crash.

**Comment by Zsashas** [comment]
Ok so it seems it was being caused by a script that I forgot I had...it removes the Apothecary recipe for the Endoflame and adds a new recipe using mana petals and Witchery materials. I guess the Apothecary doesn't like it's recipes being touched.

The lines in the script:
mods.botania.Apothecary.removeRecipe("endoFlame");
recipes.addShaped(endoFlame, [[null, null, null], [brownManaPetal, oilOfVitriol, redManaPetal],[null, null, null]]);

The entire script in question:
https://github.com/PhoenixTeamMC/PhoenixConfig/blob/master/PhoenixTeam/Botania-Witchery.zs

**Comment by Zsashas** [comment]
This was probably also what caused NEI to crash when checking Apothecary recipes.
