### ISSUE TITLE
Tiara flying options

### ISSUE THREAD

**Issue by CrowAU** [Vazkii/Botania#997]
Can you please add options in the configs to disable flying or change the mana drain on the tiaras? There's so many mods out there that adds flying and even more mods that get too easy when you can fly. I've already disabled/tweaked other items from mods to make flying more risky or expensive but there's no options for the tiaras in botania, but something like a mana usage multiplier or just an option to disable the flying on the tiaras would be nice.

**Comment by CrowAU** [comment]
Come to think of it, a mana usage multiplier for the mod as a whole would be nice, like x2 mana required to perform mana usage tasks, such as making terrasteel would require a whole mana pool rather than half, due to mod packs already being very easy for getting resources.

**Comment by MrKunji** [comment]
The next version will already have configurable mana cost for the Flügel Tiara, but may be released only next month (due to tests, Vazkii needs to study).
Now about a mana multiplier for the whole mod, I feel that it isn't going to be implemented.

**Comment by Zsashas** [comment]
I feel like the only way a mod-wide mana multiplier would work, is if it had a minimum of 1x. So you can make it more expensive, but not less.

**Comment by MrKunji** [comment]
I think you can use Modtweaker to adjust the mana cost of some operations (like Mana Pool or the Runic Altar), just remove the original and add a new cost in the script.
